### PR TITLE
Update CMSSW 13.3.x to CUDA 12.0.1

### PR DESCRIPTION
**Pull request by fwyzard**
CUDA-related updates:
  - update to CUDA 12.0.1 and NVIDIA drivers 525.85.12;
  - update to cuDNN version 8.8.0.121 for CUDA 12;
  - update UCX to version 1.14.1 for compatibility with CUDA 12.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
See https://github.com/cms-sw/cmssw/issues/41748 .

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
So, it looks like we cannot update CUDA because TensorFlow does not support
the recent versions ?

**Comment by smuzaffar** [comment]
@fwyzard , yes unfortunately this is true. Though we have cuda 12.1.1 in gcc12 IBs but we have disabled tensorflow gpu there.

**Comment by fwyzard** [comment]
Can we roll back to CUDA 12.0.1 in the GCC 12 builds ?
CUDA 12.1.1 fails to compile some of our code...

**Comment by fwyzard** [comment]
(I can make the PRs for that)

**Comment by smuzaffar** [comment]
> (I can make the PRs for that)

thanks, yes please open a PR.

**Comment by smuzaffar** [comment]
> Can we roll back to CUDA 12.0.1 in the GCC 12 builds ? CUDA 12.1.1 fails to compile some of our code...

yesterday I reported it [here](https://forums.developer.nvidia.com/t/cicc-compilation-error-and-debug-flag/27910/23?u=shahzad.muzaffar) but do not know how to provide a simple re-producer

**Comment by fwyzard** [comment]
> thanks, yes please open a PR.

https://github.com/cms-sw/cmsdist/pull/8515

**Comment by fwyzard** [comment]
> So, it looks like we cannot update CUDA because TensorFlow does not support the recent versions ?

See https://github.com/tensorflow/tensorflow/issues/60691:

> The latest tensorflow stable version 2.12 is compatible with CUDA 11.8 and cuDNN 8.6. Please take a look at the official document for the tested build [configurations](https://www.tensorflow.org/install/source).
> 
> Going forward for the upcoming releases, tensorflow might move to CUDA 12.0 or higher version. We will announce that information in the mentioned official doc once the next release happens.

**Comment by smuzaffar** [comment]
not needed as moving to gcc12 already brings in cuda 12.2

**Pull request closed without merging**
