### PR TITLE
Pythia 8.311

### PR DESCRIPTION
**Pull request by mseidel42**
Let's give this a go, we should not delay it too much if we ever want to use the new hadronization weights.

C++20 fixes should not be needed anymore.

Needs https://github.com/cms-sw/cmssw/pull/43786

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by mseidel42** [comment]
@alberto-sanchez  Would it be possible to update EvtGen to 2.2.1?
It includes a compatibility patch for Pythia 8.310: https://phab.hepforge.org/source/evtgen/history/master/;R02-02-01

**Comment by alberto-sanchez** [comment]
@mseidel42 sure, I will try asap.

**Comment by mseidel42** [comment]
> @mseidel42 sure, I will try asap.

Ok, thank you! Alternatively, I could just include the corresponding [patch](https://phab-files.hepforge.org/file/data/ryhrc4dbor3hgovolp2z/PHID-FILE-hsz6mymaknwdwu25tfjo/D96.vson.id407.diff).

But it's then probably up to BPH to decide whether EvtGen should be updated or kept at 2.0.0+patches.

**Comment by alberto-sanchez** [comment]
@mseidel42, yes probably would be faster, and then see what BPH decide

**Comment by mseidel42** [comment]
Hi @iarspider, I added the EvtGen patch, could you test again, please?

**Comment by iarspider** [comment]
please test

**Comment by mseidel42** [comment]
CMSSW PR is here: https://github.com/cms-sw/cmssw/pull/43786

Not sure review got triggered, and the bot just tries to compile it with the old Pythia version again and again

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmssw#43786

**Comment by smuzaffar** [comment]
please test

once externals are built then we can trigger the code-checks for https://github.com/cms-sw/cmssw/pull/43786 using pythia8 from this Pr

**Comment by mseidel42** [comment]
Hi, this should be ready to be tested together with https://github.com/cms-sw/cmssw/pull/43786 now

**Comment by mseidel42** [comment]
Hi @smuzaffar could you test again with the latest version of https://github.com/cms-sw/cmssw/pull/43786, please?

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
a unit tests is [failed](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6b4d0d/37250/unitTests/src/TauAnalysis/MCEmbeddingTools/test/testTauEmbeddingProducers/testing.log)
```
----- Begin Fatal Exception 06-Feb-2024 16:57:22 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Processing global begin LuminosityBlock run: 274199 luminosityBlock: 125
   [1] Calling method for module Pythia8HadronizerFilter/'generator'
Exception Message:
Failed to initialize hadronizer Pythia8Hadronizer for external parton generation
----- End Fatal Exception -------------------------------------------------
```

it looks like related to this update ... right?

**Comment by mseidel42** [comment]
Hi Malik,

> a unit tests is [failed](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6b4d0d/37250/unitTests/src/TauAnalysis/MCEmbeddingTools/test/testTauEmbeddingProducers/testing.log)

It looks like Pythia 8.310 does not accept the imcomplete LHE produced by the TauEmbedding anymore. In particular, there is no beam information, see a printout here:

```
% cmsRun dumpLHE_cfg.py 
07-Feb-2024 14:28:40 CET  Initiating request to open file file:lhe_and_cleaned.root
07-Feb-2024 14:28:52 CET  Successfully opened file file:lhe_and_cleaned.root
Begin processing the 1st record. Run 274199, Event 245779397, LumiSection 125 on stream 0 at 07-Feb-2024 14:28:56.508 CET
Number of particles = 3                                            
#              0            23    -12.300641     -7.798994      4.711514     88.216826     86.878536
#              1           -15    -26.852410    -19.663413     37.636589     50.272972      1.776820
#              2            15     14.551770     11.864419    -32.925075     37.943854      1.776820
```

@cms-sw/tau-pog-l2 @roger-wolf could you have a look into this, please?

**Comment by winterchristian** [comment]
Hi I will look into this error a bit.
@smuzaffar can you please provide me with a test environment, where I can test my code changes?
@mseidel42 suggested to use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/8938/37250/install.sh`, but this is already deleted.

**Comment by iarspider** [comment]
please test
Retrigger tests to recreate environment

**Comment by mseidel42** [comment]
Thank you! Is there any possibility to keep the environment longer than a week, in case it takes longer to resolve the issue?

**Comment by iarspider** [comment]
> Thank you! Is there any possibility to keep the environment longer than a week, in case it takes longer to resolve the issue?

You can create your own environment by following instructions on [TWiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/SDTExternalsWithCMSSW)

**Comment by mseidel42** [comment]
Just rebased on the master branch.

@winterchristian is currently looking into the tau embedding.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
At this point we can directly go for Pythia 8.311

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
assign generators

**Comment by menglu21** [comment]
+1

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test

lets refresh tests

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
ignore tests-rejected with external-failure

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
