### PR TITLE
Update awkward and uproot

### PR DESCRIPTION
**Pull request by iarspider**
* Updated py3-awkward (0 and 1) to latest versions
* Updated py3-uproot (3 and 4) to latest versions

Question: can we drop py3-awkward0 and py3-uproot3? Keeping them was requested in https://github.com/cms-sw/cmsdist/pull/6119, @ianna can you comment?

### CODE REVIEW

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@jpivarski and @ianna  do we need both 1awkward0 and awkward1 in cmssw? I do not see any direct use of `awkward` in cmssw though.

**Comment by iarspider** [comment]
@smuzaffar awkward is needed for uproot, and uproot is used widely in cmssw

**Comment by ianna** [comment]
> @jpivarski and @ianna do we need both 1awkward0 and awkward1 in cmssw? I do not see any direct use of `awkward` in cmssw though.

@smuzaffar - perhaps, we should try to phase out `awkward0` in `CMSSW_12_1 `and plan to switch from `awkward1` to `awkward2` from early next year? In `CMSSW_13_0`?

However, I see many Python packages (e.g. scram tools) are configured and distributed(?) via scram. I'd assume you will not see any direct dependencies on many of them :-)

BTW, why wouldn't they be `pip` or `conda` installed by a user?

```
 py3-absl-py                              0.13.0-5ac521bb48ce86e08ebac382db0de453
 py3-anyio                                3.3.2-7534bebd44b559a2a54285eed7555e36
 py3-appdirs                              1.4.4-1a1dc33c6a78d4e7ea338c084249eea5
 py3-argon2-cffi                          21.1.0-c7d1134fc8943f2ade045f4062bba4fe
 py3-argparse                             1.4.0-ec10a0cef8be83d445c8a853e114d14a
 py3-asn1crypto                           1.4.0-af565236a8bc1ba0b0d77d4781a9a849
 py3-astor                                0.8.1-e49b4d06e075c8de485046bd724508eb
 py3-astroid                              2.7.3-e008749435c63328677058b41183b5ad
 py3-astunparse                           1.6.3-c271bf1caa7d88afafd4b1a60560cad0
 py3-atomicwrites                         1.4.0-dfc5d32c80ad9b9c6915467f78dcefd0
 py3-attrs                                21.2.0-aef9bd17f5ceaa3a24eac9164e98371c
 py3-autopep8                             1.5.7-ec971dd3bce239be3eebcd3dcc899ffd
 py3-avro                                 1.10.2-21d0e6fb9237d52412c6239583efcb2b
 py3-awkward                              0.14.0-53084919c1cc33fae8e852cc75b80d5b
 py3-awkward1                             0.4.4-3e6f2648a9c6a6bad3156b9e1130a840
 py3-backcall                             0.2.0-40904c62a5b53e82c8705b45143581a5
 py3-backports-entry-points-selectable    1.1.0-7af16fd76d275da9e0a14e1165d12417
 py3-beautifulsoup4                       4.9.3-394419920668315147060393af706c54
 py3-beniget                              0.4.1-5d8c300a15890a4b72478118a2680093
 py3-bleach                               4.1.0-ec67f061d5bfe4fcd48318b8a3c1f704
 py3-bokeh                                2.3.3-17b2c1af3a0f39671393b195b66d3b3b
 py3-boost-histogram                      1.1.0-4c7d3f1ccaca248382515d4359dd074b
 py3-bottleneck                           1.3.2-bdd9066858e71344f5a28321c92a7477
 py3-cachecontrol                         0.12.6-927bbed1d4d01c93262c8cebe828d27e
 py3-cachetools                           4.2.2-2d467a46e9accdd99d971fea5bbc465b
 py3-cachy                                0.3.0-34acc0cc028096a2230eb96782ca6c31
 py3-certifi                              2021.5.30-7892dbde799e30f02e307c1d6776d5de
 py3-cffi                                 1.14.6-4ea2597ed3cb673980ecb5abe52ac69b
 py3-chardet                              4.0.0-0593e24ca18ca1a48a841d250cb4c141
 py3-charset-normalizer                   2.0.4-e3790437918c566667cdd758bf84eb0d
 py3-cleo                                 0.8.1-e014fc83d85069336227c2740ecbe729
 py3-click                                8.0.1-05edb0a48568ffb330a218c4434dbef0
 py3-clikit                               0.6.2-7da8dba1aafee618c8b710ada7c7b816
 py3-climate                              0.4.6-f1c4675bcc295d4bfb41c9075f368b18
 py3-cloudpickle                          1.6.0-d18522506c789f7cadf0b63396d639fa
 py3-cmsml                                0.1.2-0cbf0b982e37b191007142f60e3ce0f4
 py3-colorama                             0.4.4-f499799d0daf8c5e21bb06d982fc17ca
 py3-commonmark                           0.9.1-641a526f9ccef3f063f6e967d3fe0a53
 py3-contextlib2                          21.6.0-7c1a8a7574b5e848b3ba7b5a915dc2a5
 py3-correctionlib                        2.0.0-0c4f44c8dd5561d8c0660135feeb81f4
 py3-coverage                             5.5-4a137cd4d78d9209787772dcf7653343
 py3-crashtest                            0.3.1-33d4ab92c0fe3de935e7b4c11c07e5f0
 py3-cx-oracle                            8.2.1-a681690ce0179d0d5e801c545a7d716f
 py3-cycler                               0.10.0-268843f84d650997497a4e947d883fd9
 py3-cython                               0.29.24-48208c98f1b2fb05fdf8cf248e8e98e3
 py3-debugpy                              1.4.1-4c901672a3eb2931942bed49e60555a1
 py3-decorator                            5.0.9-9bd4286b7e134ea01de3ae72f82252a9
 py3-defusedxml                           0.7.1-9e3ff58e075efc1d134c540ff54b6c7f
 py3-deprecation                          2.1.0-f237da4c18e2cdcdfeb3fdab2598e07d
 py3-distlib                              0.3.2-c20f4e6ef2dc8038cebd6506501408ea
 py3-docopt                               0.6.2-2fc5aa063d70804f766efbf73f30bba5
 py3-docutils                             0.17.1-868cf0c632e83093fe347f4d24a95855
 py3-downhill                             0.4.0-9bb2d2b78f0f8768ad3868cd1f900839
 py3-dxr                                  1.0.x-43183acb2ae07d06dce1305f57b908b4
 py3-entrypoints                          0.3-f5e0dbaa285fa2b056098aa913315e85
 py3-filelock                             3.0.12-9e738588e591866ceaf73c19e8290a99
 py3-fire                                 0.4.0-1d6139a5e5f6e1396538309f431a2a2b
 py3-flake8                               3.9.2-8950883f4d48b0b2e46262adc237f723
 py3-flatbuffers                          2.0-b09013090943aeb60524deea77bf2578
 py3-flawfinder                           2.0.19-0f2133d0cf12c6c355101edad985e610
 py3-flit                                 3.3.0-661d76bba1b74b7fff4f2847c7cabb5e
 py3-flit-core                            3.3.0-d48e5b07d8fcfff4adb3455f75aff166
 py3-fonttools                            4.26.2-ca6db84ee50d045603d0f6a9a8e48c87
 py3-fs                                   2.4.13-09072582661758179aa8257e49466a2d
 py3-funcsigs                             1.0.2-a69090d7593a0c43c35051dfd4a3c3a7
 py3-future                               0.18.2-69168592cbd870f2e4cb7bfc5a4b82fc
 py3-gast                                 0.5.2-2a04a6f000de5e6a3fe190c027d796df
 py3-gitdb                                4.0.7-bbf765c1fe9ded5a7d8543f3f0baecc8
 py3-gitpython                            3.1.18-d4e414ee4e9cc259fc14938f7bf19f4b
 py3-google-auth                          2.0.2-ef02b8a06efe8b2d6a03eaa990416898
 py3-google-auth-oauthlib                 0.4.6-6cdc1228ffbee27c718aeea89d215896
 py3-google-pasta                         0.2.0-5fbc408debaf2fe4d9736011e5885387
 py3-grpcio                               1.39.0-72b64d954fd661f52d02c2678156b187
 py3-grpcio-tools                         1.39.0-ccb56d13eb4862b184111b8e49720ea4
 py3-h5py                                 3.4.0-b29c333b38ffa29810dda0ac2f29d411
 py3-h5py-cache                           1.0-a7a90be17b3a90f86b1da8ebe8d3e13e
 py3-hep_ml                               0.6.2-99e17b89ad0b3f43c2be7f57db33fec5
 py3-hepdata-lib                          0.8.1-414a5a666f0d24bf5b16f02069dbea18
 py3-hist                                 2.4.0-739fd0e8a6dc1bb2edcf880bec2c47f5
 py3-histbook                             1.2.5-5486ef5f0746728e91234088ff5611af
 py3-histogrammar                         1.0.25-f384c9c414392716ff24b6623d60518d
 py3-histoprint                           2.2.0-5efbf04253846d777b0680bba2d25cd9
 py3-html5lib                             1.1-67f1ce2e0c8b3c6c2f09012b7c13e80b
 py3-hyperas                              0.4.1-25de9b1c3e66c836ff22cc8d07665560
 py3-hyperopt                             0.2.5-ad837d72beacc907003331e13166b1d5
 py3-idna                                 3.2-50a14f65d518876726268425c49fd3ff
 py3-importlib-metadata                   4.8.1-fd74f57677a7b7794e4099fdda7ecb76
 py3-importlib-resources                  5.2.2-be5f3405c0d7898165b512a315182075
 py3-iniconfig                            1.1.1-35acd73f449e776ab9f59053252f2135
 py3-ipaddress                            1.0.23-34bb6ca6fb10aeb7ea53c889371939b0
 py3-ipykernel                            6.3.1-85e3dab2569ef406e84d393a445763a7
 py3-ipython                              7.27.0-043c1d545e7ae30b265cb52a21d307ac
 py3-ipython_genutils                     0.2.0-5fd96f5272f2bd63a216bac7f8d1e575
 py3-ipywidgets                           7.6.4-975c1b81fdd840ba74ec9202f29419b4
 py3-isort                                5.9.3-31d3a8bc49838fb1ffae697b48e626e0
 py3-jedi                                 0.18.0-64562e731753ef8b11588f837a86b5aa
 py3-jinja2                               3.0.1-4e4fabb2e057c5e29fd508fb04cfbacf
 py3-joblib                               1.0.1-70046aa137a1810909ad335d9a9e6c46
 py3-jsonpickle                           2.0.0-425014f307969fbffd06cb95ba9ec6fe
 py3-jsonschema                           3.2.0-e65d5922d306b7e760fe3e89b4b437ba
 py3-jupyter                              1.0.0-aadd4f1d012630dfe7eef44c574c4e41
 py3-jupyter-client                       7.0.2-98aec3471f86f54bfc3fa08aa0eb2738
 py3-jupyter-console                      6.4.0-f326ba4c53a2ff03fa756821809a271a
 py3-jupyter-core                         4.7.1-ecb5f127346b626e33c229eda5b15448
 py3-jupyter-packaging                    0.10.4-cd00e6384f507f5035a553172550e436
 py3-jupyter-server                       1.10.2-3348c8f46358d4b29cf1df8c2ee8c0ce
 py3-jupyter-server-mathjax               0.2.3-285bf2cb6a1d7088b2645ad48d7f2870
 py3-jupyterlab-pygments                  0.1.2-435443e9d7eef265273f0936f0c729ca
 py3-jupyterlab-widgets                   1.0.1-1021a621f2fdc35bf9dedd29c2264abc
 py3-keras                                2.6.0-b540ff42e26204b93a8d25f1b22da4f8
 py3-keras-applications                   1.0.8-38bf52c59b11bd343e5d990e2b152018
 py3-keras-preprocessing                  1.1.2-c82884e424e2b3dce86cbec2eb3fe4da
 py3-keras2onnx                           1.7.0-346e6888b5ee10686c89c91929b64e21
 py3-keyring                              23.1.0-cf8ba424e191e91736eae35882339d07
 py3-kiwisolver                           1.3.2-82e6442772c0f6ed377eae52e3811468
 py3-law                                  0.1.5-6ceddccdb25377e4a92baea52493ae1d
 py3-lazy-object-proxy                    1.6.0-acb0737baced067b03aa5145872d1331
 py3-lizard                               1.17.9-7a013f50371843ea812900d3463a1c53
 py3-llvmlite                             0.37.0-67761827299d80d937fa9e6715b8443f
 py3-lockfile                             0.12.2-051368fee39ff4b1059797b8f60c232b
 py3-luigi                                3.0.3-236d2596d9d05d7a543a747ab3dbc082
 py3-lxml                                 4.6.3-4a3d45a05fc4742a9798ef407c056cf8
 py3-lz4                                  3.1.3-d0314d03821d733e51e70c1a9ba27137
 py3-mako                                 1.1.5-c1fb78824e23473eedc03c832cd4f30d
 py3-markdown                             3.3.4-3c8e9c79f3d746f4a6f0674d3df7d7dd
 py3-markupsafe                           2.0.1-4302b6407be132d3ecbab31249bfb886
 py3-matplotlib                           3.4.3-5ec9321bf707a31476b71864719d8d51
 py3-matplotlib-inline                    0.1.2-e0a48227188967f9362e9ab5a9ed81d3
 py3-mccabe                               0.6.1-165a5ddc9b50edba469d131d5d5343e1
 py3-mistune                              0.8.4-60e953f9f4e68b0617d913e6ef4200de
 py3-mock                                 4.0.3-7f0f997be8b91553d36ae8bd2ca9564f
 py3-more-itertools                       8.9.0-3fa16df6eff92c13d401892945bb3db6
 py3-mpld3                                0.5.5-549bfe4506d4eaecf3b0f09b79817954
 py3-mplhep                               0.3.12-7035ea3f07f1140591d576e2b24108c3
 py3-mplhep-data                          0.0.3-17ab5b5743a412f3b1b268bdf69a5f7f
 py3-mpmath                               1.2.1-de82f9e1c98d4ed63754a908b5a7016b
 py3-nbclient                             0.5.4-0bd45107ef7848f44082dffe0d2232ce
 py3-nbconvert                            6.1.0-723f48fb43eae1e6482fa692560820e5
 py3-nbdime                               3.1.0-bd27f3f5293ddbe1792eeda9185984b5
 py3-nbformat                             5.1.3-7f72ce73f50393606f35c8cc666c04dd
 py3-nest-asyncio                         1.5.1-c89749a63b05c8dc059ec6508326bd7c
 py3-networkx                             2.6.2-e1c98b493fbdca691f3c0ad2d8b65011
 py3-neurolab                             0.3.5-825a467e2158b64c8821d3c9923f2e9e
 py3-nose                                 1.3.7-97bec7852c550b4ff00d344aa8f4bfa8
 py3-nose-parameterized                   0.6.0-cd753bc859e3c335f5d56dd97225d1fd
 py3-notebook                             6.4.3-fb0da82c80e3a9b6e934e289ff8fdb97
 py3-numba                                0.54.0-cf40ba02bfb66527ae792683f68d2ea8
 py3-numexpr                              2.7.3-ff92bf305652862ce58e18e14be20adf
 py3-numpy                                1.21.2-c4261ffefd3ca80b00d8cb08e36b5a67
 py3-oauthlib                             3.1.1-e650e75a80b4c4d0835c930551a90db2
 py3-onnx                                 1.10.1-c6a70b7f9e7deb51ba24030cb86539eb
 py3-onnxconverter-common                 1.8.1-6c412f96d5351ac8898868881b4d9f26
 py3-onnxmltools                          1.9.1-7a7d896bbe891a108cd9895266ee7839
 py3-opt-einsum                           3.3.0-6fe2f20ed4b1c33a761716296715623a
 py3-packaging                            21.0-84da294764fc9b30a1457dbd154f0856
 py3-pandas                               1.2.2-fe8e1c13d453660e60eb669e2953e739
 py3-pandocfilters                        1.4.3-275c35b6efdaeacc793c195de0ab8b66
 py3-parsimonious                         0.8.1-4a6080d97f46eb6da971e97bde427eb0
 py3-parso                                0.8.2-d228afff35574af5083701b0db7f12ee
 py3-pastel                               0.2.1-d680df3c61c3731b3d557e6f03c62cba
 py3-pathlib2                             2.3.6-55f1819df27a0144c231a67c91c51db1
 py3-pbr                                  5.6.0-daa315981ba1e757873532d0e04fab7d
 py3-pexpect                              4.8.0-03f12a12c008c37892f70b36f152f8b6
 py3-pickleshare                          0.7.5-17270807831c536304a3358301bb73f6
 py3-pillow                               8.3.2-f3b548f48818975aaaf5f4dd6139ae67
 py3-pip                                  20.3.3-llifpc       
 py3-pkgconfig                            1.5.5-69dcbc0a97c7df45fcf654a03468e1fe
 py3-pkginfo                              1.7.1-07ca4c6e5d886176145a13e02eef2700
 py3-plac                                 1.3.3-e8020ab6433d2b7c53d6be665c2c0918
 py3-platformdirs                         2.3.0-99654b1a37527e972fc7e3accbf5fdb7
 py3-pluggy                               1.0.0-73cb4702795486ae871c52b2b4ee9f78
 py3-ply                                  3.11-b7a80329c986885d047bd68b53969471
 py3-poetry                               1.1.8-fbdab9ec15ff74b94b0b332d9a702c32
 py3-poetry-core                          1.0.4-52f6a24f4dc071d3b26921d6ba3c228b
 py3-prettytable                          2.2.0-4e8aebf0bd43a73dee9ead1491d197f4
 py3-prometheus-client                    0.11.0-cf8deb769df6cf538f9c4a3a0b330b1b
 py3-prompt_toolkit                       3.0.20-306ba9e2de4c007670e4d1b283b3bd15
 py3-protobuf                             3.17.3-19d696f8e860f55f761157e968ed25ec
 py3-prwlock                              0.4.1-6bffb972e70750672ffdba9edec86628
 py3-psutil                               5.8.0-119ac95d5a37dd97d6c47c895b4bfbaa
 py3-ptyprocess                           0.7.0-7a4a4f78705c8708c7154cb746d4c753
 py3-py                                   1.10.0-7f0d524f490e98f48c705be64005a778
 py3-pyasn1                               0.4.8-0a5ac5438cac2dbbec6702f835363379
 py3-pyasn1-modules                       0.2.8-ed9c7d44f4f93d5db32a5f626ce21d8e
 py3-pybind11                             2.7.1-c04b45f9db1ce4f0c15fbe1890ab1e4f
 py3-pybrain                              0.3.3-1b86d86aecaaa013e742f2eea2d3455c
 py3-pycodestyle                          2.7.0-2972d1552c3219dd0fc4c15c115085c8
 py3-pycparser                            2.20-5db5e58e3a97462f4acc73eed7086058
 py3-pycuda                               2021.1-a18c16c3c10320f6315dd42e4005656d
 py3-pycurl                               7.44.1-546890a6e93d9f6b7b098f06c04a1786
 py3-pydantic                             1.8.2-6902bfe55133ab8ed07ad38b6d92874b
 py3-pydot                                1.4.2-89ab9b709b4edf0bea3b596e2ff26666
 py3-pyflakes                             2.3.1-769fe7531e1d3caf638bfd19cf53f1d5
 py3-pygithub                             1.55-2e3d0f5c955fac22f0efc4d39e88e50c
 py3-pygments                             2.10.0-5eb96676085f1f971a354043c080628d
 py3-pylev                                1.4.0-91c9033a59293c0b004776be0991fe4f
 py3-pylint                               2.10.2-ac876b263ef4d26f922f7e37f310f0b5
 py3-pymongo                              3.12.0-edfdc8dc91bddf0d4d2ea524b72fcbf3
 py3-pyparsing                            2.4.7-3889581b5242ea91a2b1525da15b20b3
 py3-pyrsistent                           0.18.0-4fb5fd3db8f75ab485bb5c50f8f40a52
 py3-pysqlite3                            0.4.6-47e2bf44293187ce7afa70232fc3a187
 py3-pytest                               6.2.5-17c2d9c11b36f71b55fc35278712d565
 py3-pytest-cov                           2.12.1-3b20b69f1a0935f354aa408dfdcc2d28
 py3-pytest-runner                        5.3.1-a3cb3bb9331d357008a9ddabcbc32b52
 py3-python-daemon                        2.3.0-2bd8c5d5e981686077d68311fc0bba61
 py3-python-dateutil                      2.8.2-b484edae8e2f299c2cac4a9bc8bd7a10
 py3-python-ldap                          3.3.1-6907051f1a82411cfe67767f85521295
 py3-python-rapidjson                     1.4-aeba729547e2d982d223653082be2f6e
 py3-pythran                              0.9.12.post1-d30ba951bcf8938d54e6ed21496a8988
 py3-pytoml                               0.1.21-0048068c406b1ccfc837a0fb314d1a7e
 py3-pytools                              2021.2.8-f198f65dce4f07c9450956e61f28ba6b
 py3-pytz                                 2021.1-8f9a83168abcb29366a33fc47a58f394
 py3-pyyaml                               5.4.1-528200fed65908e734afca4332ba8660
 py3-pyzmq                                22.2.1-47b5a6cf0a7337c36ad87f45cb871b01
 py3-qtconsole                            5.1.1-f90d80fb0d03dfba8201085997978a2a
 py3-qtpy                                 1.11.0-53aca83bb0633bbf3bdb6f1971234020
 py3-rep                                  0.6.6-69ee55b2515d3d70e246cd4431a6fc80
 py3-repoze-lru                           0.7-2766d76141c52a8bac75346c4f06212c
 py3-requests                             2.26.0-2bef08f8966195ff7d412f99339cbaed
 py3-requests-oauthlib                    1.3.0-265fcbfe07c35b3386198b87bc790dd1
 py3-requests-toolbelt                    0.9.1-447f8b489cd4d67f86eeed2d070e9492
 py3-requests-unixsocket                  0.2.0-3746600f1760c08b636d6f3f40be8fd3
 py3-rich                                 10.9.0-2bda476e9caed382dbe38d9450942087
 py3-rsa                                  4.7.2-604e79c2663aade5963c22481ea076f7
 py3-scandir                              1.10.0-de76b13a1bb7819479382132a768d325
 py3-schema                               0.7.4-2721f855b2677195cb2e9b44ae7d712a
 py3-scikit-learn                         0.24.2-cb0f5e37c594bcc77c9bfc04f9ca23ae
 py3-scinum                               1.2.0-87d02fa4222c34613f9e38bc04fbc885
 py3-scipy                                1.7.1-c59502069094870046fda47cb5a5065e
 py3-seaborn                              0.11.2-e19bd640caa5d08b3127a2c269924cad
 py3-send2trash                           1.8.0-c611d73d7dac22877ac2d3f33e9fe386
 py3-setuptools                           51.3.3-llifpc       
 py3-setuptools-scm                       6.3.1-e379c90b40bb0f15b6df8760ff5087a7
 py3-shellingham                          1.4.0-ab22cd5b402b21df89e1692a69745991
 py3-simplegeneric                        0.8.1-71d3aab046f16b23c048f89ab2044793
 py3-singledispatch                       3.7.0-94680d499aee692c21dd5b1a9754917e
 py3-six                                  1.16.0-21a001264b43f15f2b70e2815266a90f
 py3-skl2onnx                             1.9.2-bc4907eded5c9c14ac945eb49d3dcb52
 py3-smmap                                4.0.0-75692f667d349917a68512ad8f472b0f
 py3-smmap2                               3.0.1-eddadb37241495eb0e122fc90e46bcb4
 py3-sniffio                              1.2.0-3d67c0ae96a12405581ffb4066e31463
 py3-soupsieve                            2.2.1-725b803d28be046c185b7376809d3a22
 py3-sqlalchemy                           1.3.24-7dd2a28d1f239f23eb59ff34c78b14b2
 py3-stevedore                            3.4.0-402aab8d15de0c0f99fcf9c15cf74ba5
 py3-subprocess32                         3.5.4-6724d0ff4b43c74a40a0edec40ad97d4
 py3-sympy                                1.8-b9fbb58504f6e4658184e911c68f8fd6
 py3-tables                               3.6.1-1afd5ed23654e755b1f771efb9309140
 py3-tenacity                             8.0.1-10da57a42df43189b1ccd7a38a35b7d0
 py3-tensorboard                          2.6.0-5648b9641e5a7dd255aba3785d9607c1
 py3-tensorboard-data-server              0.6.1-aec91ae90a04b8725fa5fcd04563dea9
 py3-tensorboard-plugin-wit               1.8.0-36cb87a6b7db4d5f8b786fce88a806fe
 py3-tensorflow                           2.6.0-5dcedb38de4bf4c624ba2e18587bb0d7
 py3-tensorflow-estimator                 2.6.0-d7d9ac085269a98fd80d383b4064cf5c
 py3-termcolor                            1.1.0-7ae4448e3ec3c2206db0b795acd320bc
 py3-terminado                            0.11.1-a07445fce989715860dc2bc3e60887e2
 py3-testpath                             0.5.0-68fc748325b865cd8a810693fa58dd26
 py3-theanets                             0.7.3-98c6f4dc69ae79a4a5de55279c6f8c4e
 py3-theano                               1.0.5-41c036671ea00863195be9608d648ffc
 py3-threadpoolctl                        2.2.0-968c3d34d99ac2eed82bdb4543405c25
 py3-toml                                 0.10.2-3c4437afa94c85cf6abf0aa661d7f216
 py3-tomli                                1.2.1-66ef83b91b1f315fcc8d2adb1b7feda7
 py3-tomlkit                              0.7.2-c7ca87b8f04cf96fd1aad0c5bb326dcf
 py3-tornado                              6.1-595b11e596aedab00f27b268e3066b23
 py3-tqdm                                 4.62.2-5bcdd661f72a90b80acb748463d99215
 py3-traitlets                            5.1.0-05d5f68a99bba111b20bc2f393715cc1
 py3-typed-ast                            1.4.3-84ddc94cf1207dad6d69947b8892d9fd
 py3-typing                               3.7.4.3-721a0333c31bb9f9ffd06acf541ed895
 py3-typing-extensions                    3.10.0.2-37756f8116036a3e1ed9e4228def767c
 py3-uhi                                  0.3.0-ead53c89885413ae4e6f22f5d8383bc2
 py3-uncertainties                        3.1.6-44eebeddd2d6c98ee92a764f08605946
 py3-uproot                               3.13.0-6e09435b80e0c6b5fa949c15a068b533
 py3-uproot-methods                       0.9.2-94d32a2de7530a492505d68c6fe24676
 py3-uproot4                              0.1.2-ed7c2af90443cd3a86dbdb38f851c3ef
 py3-urllib3                              1.26.6-1e6d370eeac3b0cc63a265e8710c1b4a
 py3-virtualenv                           20.7.2-c2fb54f3d11b2df041cb7d751b85a9d9
 py3-virtualenv-clone                     0.5.6-2dabad3b92264c76feb1659d2d1dfcf4
 py3-virtualenvwrapper                    4.8.4-2795ba6556aa81659a81803799e27cee
 py3-wcwidth                              0.2.5-bc25fe5864f6a06701c7317b10f2c4db
 py3-webencodings                         0.5.1-37172c9b49244737a957d1b38a9fa838
 py3-websocket-client                     1.2.1-366db2c3700b5a1c2eba0bf511807bce
 py3-werkzeug                             2.0.1-a3fa921c43a80ebee71f0a3631adb08e
 py3-wheel                                0.37.0-fc8f1cc2b29b02010a8ea78ff6ffd6aa
 py3-widgetsnbextension                   3.5.1-4bad642bb2229cfd7b6331a899a61eed
 py3-wrapt                                1.12.1-84b77f8bf18ccd5339b6b95be356c02f
 py3-xgboost                              1.3.3-ff32f0e478bf10e8b05709e7d10a98e2
 py3-xrootdpyfs                           0.2.1-0bb6db5292624427e51ab6e94406a625
 py3-zipp                                 3.6.0-d6171ca8abc4e2d40ca22e9fd5d7d7a8
 pyclang                                  12.0.1-ec5a7ac0a9d1cc77313956671b63e821
 pydata                                   426-ghbfee          
 pyquen                                   1.5.4-0647ba6ed006a2d4ea805c48ddc52e2a
```

**Comment by davidlange6** [comment]
> On Oct 26, 2021, at 10:21 AM, Ianna Osborne ***@***.***> wrote:
> 
> 
> @jpivarski and @ianna do we need both 1awkward0 and awkward1 in cmssw? I do not see any direct use of awkward in cmssw though.
> 
> @smuzaffar - perhaps, we should try to phase out awkward0 in CMSSW_12_1 and plan to switch from awkward1 to awkward2 from early next year? In CMSSW_13_0?
> 
> However, I see many Python packages (e.g. scram tools) are configured and distributed(?) via scram. I'd assume you will not see any direct dependencies on many of them :-)
> 
> BTW, why wouldn't they be pip or conda installed by a user?

You'll find quite a number of direct dependencies in tests/scripts actually.. Users can of course update their area as they wish.

Cheers-
David

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
But if this PR works, then you could just drop the old versions (eg, uproot3 and awkward0) and add uproot-methods 0.9.2 while dropping uproot-methods3. That should all be transparent as the current commits already switch to the newer versions of these packages.

**Comment by iarspider** [comment]
@davidlange6 uproot4 does not depend on uproot-methods anymore, so not sure if it's still needed.

**Comment by davidlange6** [comment]
Right - Its not a required one. (And never was afaik) and can be handled separately.

**Comment by jpivarski** [comment]
The trio of "awkward0, uproot-methods, and uproot3" were a wedge-shaped graph of dependencies, terminating on uproot3. Some people used uproot-methods independently of Uproot, for Lorentz vectors, but it was never intended that way.

Based on this experience, "vector" is now a stand-alone package that can be used with "awkward" (version 1.x) and "uproot" (version 4.x). In setuptools, none of these are strictly dependent on each other—Vector and Uproot have modes that depend on NumPy (1.13+) only.

The switchover from Awkward 0 and Uproot 3 to the new versions happened in December of last year, so it's pretty safe to deprecate them in CMSSW. Anyone depending on old versions of these likely depend on old versions of CMSSW. (I'm just guessing, but it seems implausible to need old Uproot and new everything else.)

About Awkward 2.x and the corresponding Uproot 5.x, this pair will be a smaller, more incremental change, and will not change any package names—they'll just transition over like a normal release. This means that it won't be possible to use both in the same version of CMSSW, but user scripts will require little to no updating to take advantage of it. (They're largely internal changes, so the amount that a user script will need to adapt depends on how much they used internal, non-public APIs...)

**Comment by ianna** [comment]
@smuzaffar - as discussed with @jpivarski - could you, please, remove `awkward0`, `uproot-methods`, and `uproot3` from `CMSSW_12_1` release onwards? Thanks!

**Comment by smuzaffar** [comment]
@iarspider can you please take care of https://github.com/cms-sw/cmsdist/pull/7410#issuecomment-951857860 ?

**Comment by jpivarski** [comment]
My comment above was just background information, not an action item.

Talking with @ianna, I learned that this CMSSW release is targeting Run 3, and the awkward0, uproot3-methods, uproot3 trio are strictly for legacy analyses, so removing them (as in c7ebf383539e9f8801ee8eec019d12cd239144e6) is a good idea.

I just checked the list and saw that Vector is not on it: [vector 0.8.4](https://pypi.org/project/vector/0.8.4/) is the latest version. Users of uproot3-methods for Lorentz vectors are encouraged to switch to Vector, so I think you'll want to include it as an option so they'll have someplace to go. Its dependencies should be easy to satisfy: the same NumPy as Awkward and Uproot, [packaging](https://pypi.org/project/packaging/), and `importlib_metadata`, `typing_extensions` if your Python is less than 3.8.

https://github.com/scikit-hep/vector/blob/340b711cb9913ae2507e134878fe5bdc9bbdf6d2/setup.cfg#L40-L45

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar was that - `test TestDQMServicesDemo had ERRORS` - a known failure?

**Comment by smuzaffar** [comment]
> @smuzaffar was that - `test TestDQMServicesDemo had ERRORS` - a known failure?

Not really

**Review by smuzaffar — APPROVED** [review]

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
