### PR TITLE
Update Tensorflow to version 2.7.0

### PR DESCRIPTION
**Pull request by smuzaffar**
There is security issue reported for tensorflow 2.6.0 ( https://github.com/cms-sw/cmsdist/security/dependabot/pip/requirements.txt/tensorflow/open ).  This PR updates
- Tensorflow and its friends to version 2.7.0
- Eigen latest commit https://gitlab.com/libeigen/eigen/-/commit/675b72e44bd5a6177aebddc0ca6e754d6cd19dc7

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
FYI @riga
@fwyzard , I have updated eigen to its latest commit. Can you please check the your changes on top of it https://github.com/cms-externals/eigen-git-mirror/compare/675b72e44bd5a6177aebddc0ca6e754d6cd19dc7...cms-externals:46f072265231c56d9cbad74ab0af2fb2ae576d5a

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@riga @cms-sw/reconstruction-l2 , looks like cmssw might need some changes for Tensorflow 2.7.0, Can you please look in to it?

**Comment by fwyzard** [comment]
> FYI @riga @fwyzard , I have updated eigen to its latest commit. Can you please check the your changes on top of it [cms-externals/eigen-git-mirror@675b72e...cms-externals:46f072265231c56d9cbad74ab0af2fb2ae576d5a](https://github.com/cms-externals/eigen-git-mirror/compare/675b72e44bd5a6177aebddc0ca6e754d6cd19dc7...cms-externals:46f072265231c56d9cbad74ab0af2fb2ae576d5a)

@smuzaffar thanks for rebasing the changes. I've tested them with the pixel code outside of CMSSW and they seem fine.
For a more in-depth test including also the ECAL and HCAL code, we'll have to see the behaviour within CMSSW.

**Comment by iarspider** [comment]
@smuzaffar supposedly tensorflow-estimator is not needed as a standalone package, it is already part of main tensorflow package.

**Comment by smuzaffar** [comment]
please test

**Pull request closed without merging**
