### PR TITLE
Update uproot to 4.2.2

### LINKED ISSUE #37724: Loads of python warnings in `DQMServices/Demo` unit tests
When running the `DQMServices/Demo` unit tests in order to test PR https://github.com/cms-sw/cmssw/pull/37665 I encountered a lot of python warnings of the type:

```console
cvmfs/cms-ib.cern.ch/nweek-02729/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/cvmfs/cms-ib.cern.ch/nweek-02729/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
```
These are, by the way, visible also in the IB unit tests: [log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-04-27-2300/unitTestLogs/DQMServices/Demo#/12755)

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Fixes https://github.com/cms-sw/cmssw/issues/37724

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmssw#37665

**Comment by smuzaffar** [comment]
please test
lets test it with the cmssw PR where following warning were seen
```
cvmfs/cms-ib.cern.ch/nweek-02729/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/cvmfs/cms-ib.cern.ch/nweek-02729/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
```

**Comment by smuzaffar** [comment]
+externals
this indeed fixed the warning

**Comment by perrotta** [comment]
Should we push the "Ready for review" button, thus allowing this PR being merged?

**Comment by smuzaffar** [comment]
done and merged

**Pull request merged**
