### PR TITLE
Update hydjet.spec

### PR DESCRIPTION
**Pull request by wouf**
This PR is related to cms-sw/cmssw#39874

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by wouf** [comment]
@perrotta We have to merge it to the same release as cms-sw/cmssw#39874 otherwise Hydjet1 will work wrong!

**Comment by smuzaffar** [comment]
@wouf , I have merged it and it should go in 11h00 IB today (which should also include https://github.com/cms-sw/cmssw/pull/39874)

**Comment by wouf** [comment]
@smuzaffar Thank You!

**Comment by perrotta** [comment]
Thank you @smuzaffar : I forgot it

**Pull request merged**
