### PR TITLE
remove python2 bindings from opencv and llvm

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmsdist#7094

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = CondFormats,CondCore,DataFormats

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
It looks like we should just merge this revert before the next ib.

On Jul 2, 2021 9:28 PM, Malik Shahzad Muzaffar ***@***.***> wrote:

test parameters:

  *   full_cmssw = true

**Comment by smuzaffar** [comment]
I already did ( https://github.com/cms-sw/cmsdist/pull/7094 ) . https://github.com/cms-sw/cmsdist/pull/7095 is re-revert :-)

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
but this should be integrated after or with cms-sw/cmssw#34323

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
