### PR TITLE
HG1606 testbed

### PR DESCRIPTION
**Pull request by ticoann**
using WMCore 1.0.17.pre6  add critical fixes on reqmgr2

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 7bbab6d9225ca721eb2c819607fd4e57a7f5a17d on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2317/test_7bbab6d-20160531-073509.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Bruno, hold on this PR please. We'll bump the tag once again.

**Comment by ticoann** [comment]
Thanks Alan, I bump the tag 1.0.17.pre6 including CherryPy 5.4.0 compatibility fix

**Comment by geneguvo** [comment]
+1 to b4bb539c5891b404ff824680e66fe06edcb08566 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2317/test_b4bb539-20160531-084509.log" target="_blank">here</a>.

**Pull request closed without merging**
