### PR TITLE
Drop mxnet (cms-sw/cmssw#30432)

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#41377

**Comment by smuzaffar** [comment]
please test

**Review by smuzaffar — APPROVED** [review]

**Comment by perrotta** [comment]
> cms-sw/cmssw#41377

@smuzaffar are these tests picking https://github.com/cms-sw/cmssw/pull/41377 , which is already merged but not yet in the IB?

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41377

ah right @perrotta , no it was not picking up the merge pr

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
