### PR TITLE
Update root on cmsdist/rootmodule

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by davidlange6** [comment]
I guess this error has nothing to do with root... is it worth rerunning or is there an error in the IB?

**Comment by davidlange6** [comment]
Ok, yes its a IB issue.

On Nov 27, 2019, at 9:50 AM, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess this error has nothing to do with root... is it worth rerunning or is there an error in the IB?

**Comment by davidlange6** [comment]
please test


On Nov 27, 2019, at 9:50 AM, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess this error has nothing to do with root... is it worth rerunning or is there an error in the IB?

**Comment by smuzaffar** [comment]
+externals
external builds and cmssw builds. Lets merge it and start an IB (this only effects CXXMODULES IBs)

**Comment by davidlange6** [comment]
Thx @smuzaffar


On Nov 27, 2019, at 4:44 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


+externals
external builds and cmssw builds. Lets merge it and start an IB (this only effects CXXMODULES IBs)

**Pull request merged**
