### PR TITLE
[12_4_X] bumping up sherpa to 2.2.12

### PR DESCRIPTION
**Pull request by SiewYan**
bumping up sherpa to 2.2.12 for run-3 MC production's need

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by smuzaffar** [comment]
@SiewYan , as changes should go in to master branch first so I have opened https://github.com/cms-sw/cmsdist/pull/7916 for master branch

**Comment by SiewYan** [comment]
> @SiewYan , as changes should go in to master branch first so I have opened #7916 for master branch

thank you!

**Comment by smuzaffar** [comment]
backport of #7916

**Comment by smuzaffar** [comment]
+externals
@qliphy @perrotta feel free to merge it for 12.4.X

**Comment by qliphy** [comment]
+1

**Pull request merged**
