### PR TITLE
Upgrade Herwig7 from 7.1.4 to 7.2.0

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
Upgrade Herwig7 from 7.1.4 to Herwig 7.2.0.
To be tested with: cms-sw/cmssw#29523

Kind regards,
Dominic

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Comment by davidlange6** [comment]
hi @smuzaffar @mrodozov  - perhaps the forward port of this did not work for gcc9 or the cxxmodules branch? There are IB errors from the herwig interface.

**Comment by smuzaffar** [comment]
exactly https://github.com/cms-sw/cmssw/pull/29523#issuecomment-617585191 , this is fixed and I have already started 08h00 IBs for gcc9 and CXXMODULE.

**Comment by davidlange6** [comment]
cool - thanks!

**Pull request merged**
