### PR TITLE
dont add WMCore packages to crab-dev client

### PR DESCRIPTION
**Pull request by ddaina**
changes:
- dont add WMCore packages to crab-dev client, instead copy WMCoreConfigWrapper.py to WMCore dir and rename it to Configuration.py. This will allow users to keep in their config files `from WMCore.Configuration import Configuration` line instead of changing it to `from CRABClient.Configuration import Configuration`;
- update to v3.211117 version

fyi @belforte

### CODE REVIEW

**Comment by ddaina** [comment]
please test

**Comment by ddaina** [comment]
@smuzaffar I modified crab-build.file and now crab-prod/crab-pre fails because it requires new suffix. Should I change it just for the tests to pass?

**Comment by smuzaffar** [comment]
yes you have to change the prefix in all crab-*.spec

**Comment by ddaina** [comment]
please test

**Comment by ddaina** [comment]
thank you @smuzaffar 
+externals

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
