### PR TITLE
WMAgent stable release: 1.5.4.patch2

### PR DESCRIPTION
**Pull request by amaltaro**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to b2bd20eef4028129b4180b8dd1f9243493bd6e24 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7385/test_b2bd20e-20211012-144503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Comment by amaltaro** [comment]
@todor-ivanov FYI

**Comment by todor-ivanov** [comment]
Thanks @amaltaro

**Pull request merged**
