### PR TITLE
remove py2-six tool file as there is not bin path

### PR DESCRIPTION
**Pull request by davidlange6**
Ib is still broken after my last PR - this should help

### CODE REVIEW

**Comment by davidlange6** [comment]
@smuzaffar - the rest of the tools should correspond to a valid path

**Comment by smuzaffar** [comment]
thanks, I have restarted the DEVEL IB.

**Comment by davidlange6** [comment]
sorry for the trouble - hopefully thats the last blocker to at least getting a build.

**Comment by davidlange6** [comment]
Looks like the cmssw-tool-conf part is all ok now. CMSSW is building.

**Pull request merged**
