### PR TITLE
Revert RecoHGCal-TICL

### PR DESCRIPTION
**Pull request by jpata**
Reverts https://github.com/cms-sw/cmsdist/pull/6562, as a possible attempt at a fix to https://github.com/cms-sw/cmssw/issues/32756.

I open this PR to get the jenkins results right now. This could be a backup option for the release managers in case technical improvements to bring the memory under limits do not converge.

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

(maybe I don't have the rights to start the test, in which case, can someone start them?)

**Comment by smuzaffar** [comment]
@jpata @slava77 , are the reco comparison differences here expected?

**Comment by jpata** [comment]
hold

Yes, we wanted to see how big the differences are. This should not be merged right now, it's a backup option. Today @rovere opened https://github.com/cms-data/RecoHGCal-TICL/pull/3 which should solve the problem.

**Comment by jpata** [comment]
not needed as https://github.com/cms-data/RecoHGCal-TICL/pull/3 is merged.

**Pull request closed without merging**
