### PR TITLE
Update CUDA to version 10.1.105, on x86_64

### PR DESCRIPTION
**Pull request by fwyzard**
* CUDA version 10.1.105
    Support for gcc 8 and clang 7.
    Include new Matrix Multiply library cublasLt.
    Various fxes to CUDA libraries and NVCC compiler.

  * NVIDIA drivers version 418.39

See https://docs.nvidia.com/cuda/archive/10.1/cuda-toolkit-release-notes/index.html .

### CODE REVIEW

**Comment by fwyzard** [comment]
@smuzaffar could you check if the GPU-equipped machines at CERN are compatible with CUDA 10.1 ?

We have updated all the local machines we have access to, and the ones at Flatiron are being updated as well.

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
This should bring CUDA for the gcc 7 builds back in sync with the gcc 8 builds.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@mrodozov I will move forward with the merge, @fwyzard verified the CUDA version used on the CERN machine used for tests

**Comment by fabiocos** [comment]
merge

**Pull request merged**
