### PR TITLE
[G4VECGEOM] Update geant4 to 11.1.ref09

### PR DESCRIPTION
**Pull request by iarspider**
Closes cms-externals/geant4#75

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by civanch** [comment]
@iarspider , Thanks for this test. It turned out that the most recent update of Geant4 requires update of DD4hep as well. We need to figure out what can be done now.

**Comment by civanch** [comment]
The fix is provided for DD4hep  https://github.com/AIDASoft/DD4hep/pull/1176  
I am not sure if we can check it in easy way. I ask them for reference version.

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by smuzaffar** [comment]
changes from geant4 branch will be forward port to vecgeom branch

**Pull request closed without merging**
