### PR TITLE
[10.2.X] RecoBTag-Combined: New DeepFlavour training on 10X MC

### PR DESCRIPTION
**Pull request by smuzaffar**
https://github.com/cms-data/RecoBTag-Combined/pull/14

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
please proceed with integration of this external: performance based on tests in #23467 looks as expected.
Thank you.

**Comment by smuzaffar** [comment]
@slava77 , this PR removes a data file. Can this be safely merged with out merging the cmssw PR https://github.com/cms-sw/cmssw/pull/23467?

**Comment by slava77** [comment]
> @slava77 , this PR removes a data file. Can this be safely merged with out merging the cmssw PR cms-sw/cmssw#23467?

yes, that removed file is not used in cms-sw; it was meant to be used with the older equivalent of cms-sw/cmssw#23467, but then that took a while and a new training file became available

**Pull request merged**
