### PR TITLE
Update gcc version to 7.4.1

### PR DESCRIPTION
**Pull request by fabiocos**
Update gcc version to 7.4.1 already running in the DEVEL_X IB without apparent problems

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar is this test going to rebuild everything? Basically this is already done in the DEVEL_X IB, not sure we really need it...

**Comment by smuzaffar** [comment]
@fabiocos , for externals it is going to reuse all the pre-build packages but yes for cmssw it is going to rebuild every thing. I agree we do not need the test but does not hurt much

**Comment by fabiocos** [comment]
@smuzaffar ok let it run, this will provide anyway the comparison which is useful to see

**Comment by fabiocos** [comment]
BTW, pre-build with the new gcc? I guess not, while this is done in DEVEL_X...

**Comment by smuzaffar** [comment]
yes, as architecture is same (slc7_amd64_gcc700) so what ever has been build by DEVEL IBs will be reused by normal IBs. Ideally no external package should be rebuild.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please abort

not sure that the bot is in the correct state

**Comment by smuzaffar** [comment]
bot is in correct state and I have restarted tests (for those which were using bad bot). I did not realized that you already have revert the change.

**Comment by fabiocos** [comment]
@slava77 @perrotta @civanch all the DQM and comparison test failures are concentrated in a single workflow, 9.0, which is a simulation one. And indeed there are differences already a generator level.
I guess that the subsequent differences in the comparison are due to that

**Comment by fabiocos** [comment]
I have performed the following test: rerun wf 9 starting from either step1 or step2 produced with the default CMSSW (gcc730). Rerunning the DQM comparison with the baseline in the former case I see

```
 - summary of 121564 tests:
 o Failiures: 1.43% (1736/121564)
 o Nulls: 0.00% (0/121564) 
 o Successes: 98.57% (119828/121564) 
 o Skipped: 0.00% (0/121564) 
 o Missing objects: 0
```

and in the latter

```
 - summary of 121564 tests:
 o Failiures: 0.00% (1/121564)
 o Nulls: 0.00% (0/121564) 
 o Successes: 100.00% (121563/121564) 
 o Skipped: 0.00% (0/121564) 
 o Missing objects: 0
```

So this confirms that the non reproducibility is located in the simulation part, and not only at GEN-SIM level.

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@smuzaffar I have put the discussion about this PR in agenda for next ORP, I would like to merge it after that

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar we are not tracking minor version update in the architecture name (it was gcc700 already with gcc 731...), am I correct?

**Comment by smuzaffar** [comment]
that is correct @fabiocos

**Pull request merged**
