### PR TITLE
remove more python2 tools

### PR DESCRIPTION
**Pull request by davidlange6**
based on #6869, this change might cause problems (for reasons I didn't understand yet)..

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
please test

I think I have a consistent set finally.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
hi @smuzaffar - I have another round ready if you think this is ready to be merged.

**Comment by smuzaffar** [comment]
+externals
comparison diff are due to message logger

**Pull request merged**
