### PR TITLE
First release candidate for CRAB3 server client taskworker (3.3.11)

### PR DESCRIPTION
**Pull request by mmascher**
Details here: https://svnweb.cern.ch/trac/CMSDMWM/ticket/4305#comment:1

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 6927da53112d84e696cf2563211922e80e107048 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
+1 to 9a1031e1a96f2e122a3dd804d1454f11d7309f16 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
+1 to afbc35b0a321574dc12de6e4a01aad14b5a468d3 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
-1 to 085943156ed183cbbd320d601e4a53ffc875b0a3 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
Hi,
I think there was an update to this patch after Rida had pushed it upstream. I believe I can close it since Justas made a new PR (https://github.com/cms-sw/cmsdist/pull/1169) which bumps to an even newer crabserver version.

However, if there were changes elsewhere (i.e in the condor patch part) we are going to miss them...
Diego.

**Comment by juztas** [comment]
Closing, You are right @geneguvo

**Comment by mmascher** [comment]
Hi Diego,

There were no changes in the condor patch. Thanks for the heads up
Il 07/nov/2014 18:04 "Diego" notifications@github.com ha scritto:

**Pull request closed without merging**
