### PR TITLE
Updated root to tip of branch v6-18-00-patches

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@slava77 (in response to https://github.com/cms-sw/cmsdist/pull/5154#issuecomment-523659677 ) no this error is not common and looks like some side effect of root update. I would like to merge this in to ROOT618 IBs to see what else is broken.  There are 4 reco comparison differences , can you please check if they are real?

**Comment by slava77** [comment]
> There are 4 reco comparison differences , can you please check if they are real?

these are not real
In the comparisons:

all_OldVSNew_TTbar13TeVPU2017wf10224p0 | 4
-- | --

is related to the randomness in the pileup file opening

**Comment by smuzaffar** [comment]
closing in favor of #5189

**Pull request closed without merging**
