### PR TITLE
Updating GeneratorInterface-EvtGenInterface to to new tag V02-00-08

### PR DESCRIPTION
**Pull request by mrodozov**
According to cmsdist PR https://github.com/cms-sw/cmsdist/pull/3023 in response to
cms-data/GeneratorInterface-EvtGenInterface#10

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by oozcelik** [comment]
Is it some kind of an unrelated error? or should be taken seriously?

**Comment by smuzaffar** [comment]
yes it should be unrelated to this Pr but we are trying to understand why it is failing.

**Comment by smuzaffar** [comment]
+externals
AddOn test is failing because of Geometry data packages which during the PR tests overrides the xml files from the releases itself. This is a known issue. So from our side this PR is good to go in to release.

**Comment by smuzaffar** [comment]
+tests

**Pull request merged**
