### PR TITLE
[10.2.X] Update RecoEgamma-PhotonIdentification to 01-00-06

### PR DESCRIPTION
**Pull request by guitargeek**
Backport of https://github.com/cms-sw/cmsdist/pull/4230

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar this is needed for cms-sw/cmssw#25372 Do you see any issue with it? Otherwise I would merge it

**Comment by fabiocos** [comment]
+1

**Comment by guitargeek** [comment]
Just a little heads up @fabiocos : if you don't merge cms-sw/cmssw#25372 at the same time, nothing will work anymore because all weights files got renamed and gzipped.

**Comment by fabiocos** [comment]
merge

**Pull request merged**
