### PR TITLE
Switch to Geant4 10.1p02 DEVEL branch

### PR DESCRIPTION
**Pull request by civanch**

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by ghost** [comment]
please test
Due to an error in the testing script this PR has not been tested wrt the correct IB.

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
@civanch do you think the above error is legit? I don't see problems within the testing script.

**Comment by civanch** [comment]
@degano , this may be a valid error, because parfullsim version is old. I will try to figure out, may be a minor update of parfullsim code will be needed.

**Comment by civanch** [comment]
@degano , is it possible to have a parfullsim project under externals? Likely until now this test was unchanged.

**Comment by ghost** [comment]
@civanch I'll create the repository ASAP.

**Comment by ghost** [comment]
@civanch I've created the repository here: https://github.com/cms-externals/parfullcms. Let me know if you wish to add more branches. Once the patch is in place I can take care of modifying the parfullcms spec file to take the source from github.

**Comment by ghost** [comment]
@civanch I prepared a PR with this commit and the update of ParFullCMS at #1997, I'm testing it.

**Comment by ghost** [comment]
superseded by #1997

**Pull request closed without merging**
