### PR TITLE
Build alpaka code in GPU-only mode [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
Build alpaka device code for the CUDA and ROCm back-ends in "GPU only" mode. In this mode, functions marked as ALPAKA_FN_ACC are marked as `__device__` functions, and are compiled only for the corresponding GPU device back-ends.

Currently, functions marked as ALPAKA_FN_ACC are marked as `__host__ __device__` functions, and may be compiled for both device and host back-ends. The latter leads to linker errors in kernels that use device symbols like `threadIdx`, `blockIdx`, _etc_. that are compiled for the ROCm back-end.

No impact on the HLT performance, as expected.
`CMSSW_14_0_4`:
```
Running 4 times over all events with 8 jobs, each with 32 threads, 24 streams and 1 GPUs
   525.9 ±   0.6 ev/s (11800 events, 99.8% overlap)
   522.7 ±   0.5 ev/s (11800 events, 99.9% overlap)
   534.2 ±   0.8 ev/s (11800 events, 99.8% overlap)
   541.6 ±   0.6 ev/s (11800 events, 99.9% overlap)
 --------------------
   531.1 ±   8.5 ev/s
```

`CMSSW_14_0_4` with https://github.com/cms-sw/cmssw/pull/44650 and https://github.com/cms-sw/cmsdist/pull/9125:
```
Running 4 times over all events with 8 jobs, each with 32 threads, 24 streams and 1 GPUs
   536.3 ±   0.6 ev/s (11800 events, 99.8% overlap)
   531.2 ±   0.5 ev/s (11800 events, 99.7% overlap)
   558.7 ±   0.4 ev/s (11800 events, 99.5% overlap)
   520.9 ±   0.8 ev/s (11800 events, 99.8% overlap)
 --------------------
   536.8 ±  16.0 ev/s
```

Backport #9121 to CMSSW 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #9121

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#44650

**Comment by smuzaffar** [comment]
+externals

@cms-sw/orp-l2 , feel free to include it for next 14.0.X IB/release

**Comment by fwyzard** [comment]
> @cms-sw/orp-l2 , feel free to include it for next 14.0.X IB/release

However, https://github.com/cms-sw/cmssw/pull/44650 needs to be merged before (or at the same time as) this PR.

**Comment by antoniovilela** [comment]
Will merge it with https://github.com/cms-sw/cmssw/pull/44650, after passing an IB in master.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
