### PR TITLE
Update CXXModules.mk.file

### PR DESCRIPTION
**Pull request by davidlange6**
undo commit made a few months ago that now appears to be causing problems.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
this would have no effect outside of the mainstream...

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , this file is not used in ROOT CXXModule IB. We are using https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/rootmodule/CXXModules.mk.file (i.e. in branch IB/CMSSW_11_0_X/rootmodule ) where all modules are disabled.

**Comment by davidlange6** [comment]
Ah. I will modify the right branch then But can we not keep them in sync instead?




On 19 Sep 2019, at 16:57, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> , this file is not used in ROOT CXXModule IB. We are using https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/rootmodule/CXXModules.mk.file (i.e. in branch IB/CMSSW_11_0_X/rootmodule ) where all modules are disabled.

**Comment by smuzaffar** [comment]
closing it as this file is kept in rootmodule branch.

**Pull request closed without merging**
