### PR TITLE
[CLHEP] Update to version 2.4.7.1

### LINKED ISSUE #8747: New version of CLHEP 2.4.7.0
A new version of CLHEP is available: https://gitlab.cern.ch/CLHEP/CLHEP/-/tree/CLHEP_2_4_7_0?ref_type=tags

In this version MixMax random generator is updated, expecting better CPU performance. The algorithm itself is not changed, so regression is not excluded but should be confirmed.

### PR DESCRIPTION
**Pull request by smuzaffar**
fixes https://github.com/cms-sw/cmsdist/issues/8747

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@civanch , clhep `2.4.7.1` update shows a lot of reco and dqm differences (see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-13-1100+d12604/59241/validateJR.html ) . Looks like it has same differences as we have when we moved to [Geant4 11.1.2](https://github.com/cms-sw/cmsdist/pull/8698#issuecomment-1716949759) . Can you please check and are these differences expected for clhep update?

**Comment by civanch** [comment]
@smuzaffar , it is expected, because in this version of MixMax random generator a bug was fixed, which is seen when number of calls is big. It is non-reproducibility due to not proper initialisation of all field of random seed. With ordinary statistics the problem was not seen. In CMS run the event is reach and many random numbers are used.

So, having this version of CLHEP in 13_3_X is our goal but we need to decide if validation on base of pre-release validation is enough. I think so but the agreement with release managers and PPD is required.

**Comment by smuzaffar** [comment]
thanks @civanch , so I leave this PR as it is. May be you can discuss this with release managers/PPD during ORP today

**Comment by smuzaffar** [comment]
+externals

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
