### PR TITLE
[ROOT626] Root update v6 26 00 patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
@aandvalenzuela , this type of errors occurs when root version is update e.g. https://github.com/cms-sw/root/blob/cms/v6-26-00-patches/269db443df/build/version_number shows that new version if 6.26/09. so please update the version in spec file to `6.26.09`

**Comment by aandvalenzuela** [comment]
test parameters:

- full_cmssw = true

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
I think this error is related to the change of root version. @smuzaffar do you know if we generate this file `DataFormatsTestObjects_xr_rdict.pcm` ourselves for the test?

```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_ROOT626_X_2022-10-25-2300/TestIOPoolInputNoParentDictionary
Produce a file with TransientIntParentT<1> product
terminate called after throwing an instance of 'edm::Exception'
  what():  An exception of category 'FatalRootError' occurred.
   Additional Info:
      [a] Fatal Root Error: @SUB=TFile::Init
no StreamerInfo found in /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_ROOT626_X_2022-10-25-2300/TestIOPoolInputNoParentDictionary/CMSSW_12_6_ROOT626_X_2022-10-25-2300/lib/el8_amd64_gcc10/DataFormatsTestObjects_xr_rdict.pcm therefore preventing schema evolution when reading this file.
The file was produced with version 6.26/07 of ROOT.

A fatal system signal has occurred: abort signal
```

**Comment by smuzaffar** [comment]
+externals
this failure is expected with root version update. The unit test tries to create a dev area for the same IB and in this case the Ib had older version of root. unit test should pass in the IB once we merge this PR

**Comment by smuzaffar** [comment]
oops this was for root 6.26 , I thought it was root  master. We should hold on to update root 6.26 as we are still waiting for its validation. I have reverted the change for root 626 ( https://github.com/cms-sw/cmsdist/pull/8150 )

**Pull request merged**
