### PR TITLE
add networkX package

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by ktf** [comment]
@nclopezo can you build this?

**Comment by nclopezo** [comment]
Hi, I built it and the external builds without errors.

**Comment by ktf** [comment]
This is lacking the tool file. Can you prepare it please and then we look together whether it does the correct thing? Thanks.

**Comment by gartung** [comment]
This package does not need a tool file. It is not used in a scram build rule.

**Comment by ktf** [comment]
How do you get it in path?

**Comment by gartung** [comment]
The script that calls statics.py calls ../../../external/py2-networkx/1.8.1/etc/profile.d/init.sh

**Comment by ktf** [comment]
Sorry this is not ok. We should have it in path somehow, IMHO. 
@smuzzaffar do you have any better ideas?

**Comment by nclopezo** [comment]
Hi,

Anyway, I created a tool file in this pull request https://github.com/cms-sw/cmsdist/pull/353 In case you decide to use it.

**Pull request closed without merging**
