### PR TITLE
adding new pdl for bc in 9_3_x

### PR DESCRIPTION
**Pull request by alberto-sanchez**
we need this in production

### CODE REVIEW

**Comment by smuzaffar** [comment]
backport of https://github.com/cms-sw/cmsdist/pull/4069

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
system curl does not work with cms bootstrap env for older releases. I force data packages to use wget instead

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by alberto-sanchez** [comment]
@fabiocos the MC request which uses this table has been requested. Could you please consider to merge this PR and make a new release?

**Comment by kpedro88** [comment]
merge

**Pull request merged**
