### PR TITLE
crab. py3-only specfiles, removing unused .patch files.

### PR DESCRIPTION
**Pull request by mapellidario**
### status

ready to merge, [tested](https://github.com/dmwm/CRABServer/issues/7105) in preprod (`cmsweb-testbed` for crabserver, crab-preprod-tw01 for taskworker and publisher).

### description

After having merged the branch `python3` into `master`, we switched back to the old format for tags: `v3.YYMMDD` will be used for images with python3 environment, which is the new default.

This change required to remove the `if` switches in `crab(server|taskworker).spec` to differentiate the build of py2 images form the one of py3 images. 

While doing it, I took the chance to remove patches that I think are not used anymore. This is my opinion, i tested it and no problem occurred. However, i may have overlooked something, so please add your feedback if you think that those `.patch` files are still needed!

fyi: @belforte

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 3fb4019ee24321baeaa9e981a8fbc5725dd4833a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7661/test_3fb4019-20220302-234003.log" target="_blank">here</a>.

**Comment by mapellidario** [comment]
@belforte do you think we can merge this? otherwise we can not use our jenkins to build images in our current `dmwm/CRABServer/master` branch

**Comment by belforte** [comment]
sorry, I had overlooked this, sure,go ahead

**Comment by belforte** [comment]
please merge

**Pull request merged**
