### PR TITLE
tool file updated

### PR DESCRIPTION
**Pull request by KiSooLee**
tool file for starlight is updated and applied

### CODE REVIEW

**Comment by davidlt** [comment]
NAK, still wrong, look at the diff of `cmssw-tool-conf.spec`. It's wrong.

**Comment by KiSooLee** [comment]
I found the reason. Let me make Pull Request again.

**Comment by davidlange6** [comment]
@KiSooLee , @degano  -before we too much further, is there a presentation or other documentation as to how we expect to use starlight in CMSSW? The readme for starlight does not suggest an easy way to do that.

**Comment by KiSooLee** [comment]
We expect to use starlight like pythia.
Unfortunately we don't have presentation or documentation yet

**Comment by davidlange6** [comment]
is there at least a prototype generator interface ? (or else where in starlight would I find an entrance point into its results (e.g., hepmc particle list or equivalent) that you expect to use?

**Pull request closed without merging**
