### PR TITLE
[13.0.X] Upgrade lhapdf sets to 6.5.1c

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@cms-sw/orp-l2 feel free to include this for next 13.0.X release.

@mkirsano , what about 13.1.X to 13.3.X releases?

**Comment by stahlleiton** [comment]
> +externals
> 
> @cms-sw/orp-l2 feel free to include this for next 13.0.X release.
> 
> @mkirsano , what about 13.1.X to 13.3.X releases?

Hi @smuzaffar ,

I see that there is another CMSSW branch called [CMSSW_13_0_HeavyIon_X](https://github.com/cms-sw/cmssw/tree/CMSSW_13_0_HeavyIon_X) , which seems to be for Heavy Ion gen production and since this PR targets HIN gen production (adding new nuclear PDFs), does this PR also needs to be backported to CMSSW_13_0_HeavyIon_X or is the branch CMSSW_13_0_X enough?

**Comment by smuzaffar** [comment]
@stahlleiton , for now both [13.0.X](https://github.com/cms-sw/cms-bot/blob/master/config.map#L56) and [13.0.HeavyIon_X](https://github.com/cms-sw/cms-bot/blob/master/config.map#L62) are using same externals (IB/CMSSW_13_0_X/master) . So once this PR is merged then it will also go in to 13.0.HeavyIon.X.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
