### PR TITLE
Update jemalloc to version 5.3.0 [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
This release contains many speed and space optimizations, from micro optimizations on common paths to rework of internal data structures and locking schemes, and many more too detailed to list below. Multiple percent of system level metric improvements were measured in tested production workloads.
The release has gone through large-scale production testing.

See https://github.com/jemalloc/jemalloc/releases/tag/5.3.0 for more details.

Simplify and make more uniform the syntax of the `jemalloc{,-debug}.spec` files.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #7953

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc10

**Comment by fwyzard** [comment]
@smuzaffar, once the tests pass, I would like to use the area created by cmsbuild to run some benchmarks and compare the performance of jemalloc 5.2.1 and 5.3.0, before merging it.

**Comment by smuzaffar** [comment]
+externals
@cms-sw/orp-l2  feel free to merge it for next 12.4 release.

**Comment by qliphy** [comment]
merge

**Pull request merged**
