### PR TITLE
new PDF sets for lhapdf6 (backport from 73X)

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
@mkirsano just a reminder this is also desired to be backported to 53x

**Comment by ghost** [comment]
+1
Tested compilation till cmssw-tool-conf.

**Comment by bendavid** [comment]
+1

**Comment by bendavid** [comment]
-1
(the added pdf sets have a problem which is fixed by a new update from the LHAPDF authors as of this morning, so might as well wait for that one)

**Comment by mkirsano** [comment]
OK, waiting for lhapdf 6.1.5

**Pull request closed without merging**
