### PR TITLE
Updated root to tip of branch v6-22-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
this contains the Arm update we wanted

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
comparison dif are due to change in input for wf  140.53

**Comment by smuzaffar** [comment]
@mrodozov , did this fix any of the arm failures?

**Comment by mrodozov** [comment]
as far as I can tell not really, the report was that it does quote 
https://github.com/cms-sw/cmssw/issues/31123#issuecomment-779375531
followed by https://github.com/cms-sw/cmssw/issues/31123#issuecomment-802323891
but I'll just ask for examples to check. It does fix a problem that should've not been there 
we can build an IB in non-threading mode to separate relvals that are not thread related and maybe fix them
first or at least to have a list with the 'normal failures'

**Pull request merged**
