### PR TITLE
[10.2.X] updated Sherpa 2.2.5 and OpenLoops 2.0.b

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #4377 
and #4351

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by alberto-sanchez** [comment]
please test workflow 534.0, 511.0, 535.0

**Comment by alberto-sanchez** [comment]
please abort

**Comment by alberto-sanchez** [comment]
sorry It is missing the other test.

**Comment by alberto-sanchez** [comment]
please test workflow 534.0, 511.0, 535.0

**Comment by fabiocos** [comment]
@alberto-sanchez do you confirm this version is validated for backport?

**Comment by alberto-sanchez** [comment]
@fabiocos the new libraries seems ok, with tests performed so far.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
