### PR TITLE
adding runtime var to mctester-toolfile

### PR DESCRIPTION
**Pull request by inugent**
This modification adds a runtime variable that enables the mctester analysis stage to be run in the default CMSSW environment.

### CODE REVIEW

**Comment by ktf** [comment]
Why not simply using LD_LIBRARY_PATH?

**Comment by smuzaffar** [comment]
scram does not add tools' lib directories to LD_LIBRARY_PATH.

**Comment by ktf** [comment]
> scram does not add tools' lib directories to LD_LIBRARY_PATH.

True, but the contents of that directory are in the global 
LD_LIBRARY_PATH. @inugent can you elaborate a bit more what you are 
trying to do here?

**Comment by davidlt** [comment]
It's in `LD_LIBRARY_PATH` by default:

```
$ ls /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_X_2014-05-23-0200/e
xternal/slc6_amd64_gcc481/lib | grep -E 'HEPEvent|HepMCEvent|MCTester'
libHEPEvent.a
libHEPEvent.so
libHepMCEvent.a
libHepMCEvent.so
libMCTester.a
libMCTester.so
```

@inugent do you plan to use `MCTESTERLOCATION` to find them and then `dlopen()`?

**Comment by inugent** [comment]
Hello,
 MC-Tester runs in two stages. One  is run as a plugin, while the other is run in root, but requires the libraries from the external rpm (ie https://github.com/inugent/cmssw/blob/Tauola114_7_1_X/GeneratorInterface/MCTESTER/test/analyze/MERGE.C or ). The idea was to setup a variable such that the correct libraries will automatically be load in the CMS environment. Otherwise the user has to add the path by hand or use a hack. Best regards,
Ian

**Comment by smuzaffar** [comment]
In CMS environment libHEPEvent.so (and other libs) should already be 
available under LD_LIBRARY_PATH. So just doing 
gSystem.Load("libHEPEvent.so"); should work ... is it not working in CMS 
environment?

**Comment by ktf** [comment]
Which library are we talking about? AFAICT all the mctester libraries 
are in LD_LIBRARY_PATH so you can simply pick them up from there.

**Comment by inugent** [comment]
You are right. It will be automatically found from the LD_LIBRARY_PATH. This request is not needed. I have modified the scripts in GeneratorInterface/MCTESTER accordingly. I am closing this request. Thank you and best regards,
Ian

**Pull request closed without merging**
