### PR TITLE
update of mkFit for new TBB : new tag V2.1.0-0+pr291

### PR DESCRIPTION
**Pull request by slava77**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 11634.7

**Comment by slava77** [comment]
Looking at ` cms/6553/slc7_amd64_gcc900/relvals/input Pending — Running tests ` 
https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/244/

`runTheMatrix.py ... -l 4.17,4.22,4.23,4.24,4.25,4.26,4.27,4.28,4.29,4.34,4.36,4.37,4.4,4.41,4.42,4.43,4.44,4.45,4.51,4.52,4.53,4.54,4.55,4.57,4.58,4.6,4.61,4.62,4.63,4.64,4.65,4.67,4.68,4.71,4.72,4.73,4.74,4.75,4.76,4.77,4.78,6.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,35.0,36.0,37.0,38.0,39.0,43.0,44.0,45.0,134.701,134.702,134.703,134.704,134.705,134.706,134.707,134.708,134.709,134.71,134.801,134.802,134.803,134.804,134.805,134.806,134.807,134.808,134.809,134.81,134.811,134.812,134.813,134.901,134.902,134.903,134.904,134.905,134.906,134.907,134.908,134.909,134.91,134.911,134.912,136.721,136.722,136.723,136.724,136.72411,136.725,136.726,136.727,136.728,136.729,136.73,136.731,136.732,136.733,136.734,136.735,136.736,136.737,136.738,136.739,136.74,136.741,136.742,136.743,136.744,136.745,136.746,136.747,136.748,136.749,136.75,136.751,136.752,136.753,136.754,136.755,136.756,136.757,136.758,136.759,136.76,136.761,136.7611,136.76111,136.762,136.763,136.764,136.765,136.766,136.767,136.768,136.769,136.77,136.771,136.772,136.7721,136.77211,136.7722,136.773,136.774,136.775,136.776,136.777,136.778,136.779,136.78,136.7801,136.7802,136.7803,136.781,136.782,136.783,136.784,136.785,136.786,136.787,136.788,136.789,136.79,136.791,136.792,136.793,136.794,136.795,136.7952,136.796,136.797,136.798,136.799,136.8,136.801,136.802,136.803,136.804,136.805,136.806,136.807,136.808,136.809,136.81,136.811,136.812,136.813,136.814,136.815,136.816,136.817,136.818,136.819,136.82,136.821,136.822,136.823,136.824,136.825,136.826,136.827,136.828,136.829,136.83,136.831,136.8311,136.83111,136.832,136.833,136.834,136.835,136.836,136.837,136.838,136.839,136.8391,136.84,136.841,136.842,136.843,136.844,136.845,136.846,136.847,136.848,136.849,136.85,136.8501,136.851,136.852,136.8521,136.8522,136.8523,136.853,136.854,136.855,136.856,136.8561,136.8562,136.857,136.858,136.859,136.86,136.861,136.862,136.863,136.864,136.8642,136.8643,136.865,136.866,136.867,136.868,136.869,136.87,136.871,136.872,136.873,136.874,136.875,136.876,136.877,136.878,136.879,136.88,136.881,136.882,136.883,136.884,136.885,136.8855,136.885501,136.885511,136.885521,136.886,136.8861,136.8862,136.887,136.888,136.88811,136.8885,136.888501,136.888511,136.888521,136.889,136.89,136.891,136.892,136.893,136.894,136.895,136.896,136.898,137.8,138.1,138.2,140.51,140.52,140.53,140.54,140.55,140.56,140.5611,140.57,158.01,158.1,158.2,158.3,1306.0,1307.0,1308.0,1309.0,1310.0,1311.0,1312.0,1313.0,1314.0,1315.0,1316.0,1317.0,1318.0,1319.0,1320.0,1321.0,1322.0,1323.0,1324.0,1325.0,1325.1,1325.2,1325.3,1325.4,1325.5,1325.51,1325.516,1325.5161,1325.517,1325.518,1325.6,1325.61,1325.7,1325.8,1325.81,1325.9,1325.91,1326.0,1327.0,1328.0,1329.0,1329.1,1330.0,1331.0,1332.0,1333.0,1334.0,1335.0,1336.0,1337.0,1338.0,1339.0,1340.0,1341.0,1343.0,1344.0,1345.0,1347.0,1348.0,1349.0,1350.0,1351.0,1352.0,1353.0,1354.0,1355.0,1364.0,1365.0,1366.0,134.0,134.99601,134.99602,134.99603,134.99901,144.6,139901.0,139902.0,13992501.0,13992502.0,200.0,202.0,203.0,205.0,11024.2,11024.3,25200.0,25202.0,25202.1,25202.15,25202.2,25203.0,25204.0,25205.0,25206.0,25207.0,25208.0,25209.0,25214.0,50200.0,50202.0,50203.0,50204.0,50205.0,50206.0,50207.0,50208.0,1000.0,1001.0,1001.2,1002.0,1003.0,1004.0,1010.0,1020.0,1030.0,1040.0,1040.1,1102.0,4000.0,4001.0,4002.0,4003.0,10001.0,10002.0,10003.0,10004.0,10005.0,10006.0,10007.0,10008.0,10009.0,10023.0,10024.0,10024.1,10024.2,10024.3,10024.4,10024.5,10025.0,10026.0,10042.0,10059.0,10071.0,10224.0,10224.15,10225.0,10424.0,10801.0,10802.0,10803.0,10804.0,10805.0,10806.0,10807.0,10808.0,10809.0,10823.0,10824.0,10824.1,10824.5,10824.501,10824.511,10824.521,10824.6,10824.8,10825.0,10826.0,10842.0,10842.501,10859.0,10871.0,11024.0,11024.15,11024.6,11025.0,11224.0,11224.6,11634.0,11634.1,11634.24,11634.5,11634.501,11634.511,11634.521,11634.7,11640.0,11646.0,11650.0,11650.501,11723.17,11834.0,11834.13,11834.24,11834.99,11846.0,12024.0,12434.0,12634.0,12634.99,12834.0,13034.0,13034.99,23234.0,23234.103,23234.21,23234.9,23434.21,23434.99,23434.999,250200.0,250200.17,250200.18,250202.0,250202.1,250202.17,250202.171,250202.172,250202.18,250202.181,250202.2,250202.3,250202.4,250202.5,250203.0,250203.17,250203.18,250204.0,250204.17,250204.18,250205.0,250205.17,250205.18,250206.0,250206.17,250206.18,250206.181,250207.0,250207.17,250207.18,250208.17,250208.18,500200.0,500202.0,500203.0,500204.0,500205.0,500206.0,500207.0`

are we really making all of these for every PR now?

**Comment by mrodozov** [comment]
not really, there should be a short matrix run ... I think

**Comment by smuzaffar** [comment]
@slava77 , yes we are but as a separate test which runs all wf with input data set and only run step2 for 1 event. 
```
--command '-n 1 --customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport' --job-reports  -i all --maxSteps=2
```

**Comment by slava77** [comment]
> @slava77 , yes we are but as a separate test which runs all wf with input data set and only run step2 for 1 event.
> 
> ```
> --command '-n 1 --customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport' --job-reports  -i all --maxSteps=2
> ```

thanks for clarifying.
in many cases the startup costs as much the first few events.
I'll take a note that we apparently have plenty of CPU ;)

**Comment by smuzaffar** [comment]
> I'll take a note that we apparently have plenty of CPU ;)

Not really, we are making use of some of the HTCondor nodes :-) the job runs for under an hour (on 16 core machine)

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@slava77 , looks like comparsion failure are due to message logger. If no objections then I would like to merge this.

**Comment by slava77** [comment]
> @slava77 , looks like comparsion failure are due to message logger. If no objections then I would like to merge this.

indeed; also the .7 workflow passed OK. 
So, please go ahead with merging.

**Pull request merged**
