### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
Tests are failing as in here: 
https://github.com/cms-sw/cmsdist/pull/4208
and they are failing also in IBs, I'd suggest to merge this one to have the latest commits.

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
@mrodozov there are even more failures as far as I can see, but they are not fixed by keeping this on hold

**Comment by fabiocos** [comment]
+1

**Pull request merged**
