### PR TITLE
Bump python package versions

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
hi @smuzaffar  - what part of our tests trigger this check on duplicate dictionaries? I'd like to make sure I run it before submitting PRs

**Comment by smuzaffar** [comment]
duplicate dictionaries ? sorry I did not get your question. If you are talking about cmssw dicts then that check is run when we have any cmssw PRs to test

**Comment by davidlange6** [comment]
ha - old habits - I mean duplicate binaries which is the error in the tests above

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
ah ok, that check is run by cmssw-tool-conf package https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/scramv1-tool-conf.file#L123-L155 . We run it there as this package has app the dependencies and here we can check if there are duplicate binaries. So if you locally build cmssw-tool-conf then you should be able to see such errors

**Comment by davidlange6** [comment]
Thanks!

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
