### PR TITLE
HG1411 DAS changes

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 4fc4200f3abbf781b1c8638d75985750d005ada3 on slc5_amd64_gcc461.

**Comment by geneguvo** [comment]
Hi Valentin,

We've moved to comp_gcc481 branch completely now and production DAS is running on SLC6 already. Would you re-do the request for comp_gcc481 or can we go ahead and do the similar changes?

**Comment by vkuznet** [comment]
Ahh, sorry I didn't pay attention to that when I created PR. I'll create a new
PR in a next hour.

V.

**Comment by vkuznet** [comment]
Ok, I created new PR against comp_gcc481, https://github.com/cms-sw/cmsdist/pull/1161, please use it and disregard this one. I'll update TRAC ticket as well

**Pull request closed without merging**
