### PR TITLE
Upgrade to rivet 2.2.1

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by ghost** [comment]
+1
Tested compilation and all of its dependencies.
Tested compilation of CMSSW package GeneratorInterface/RivetInterface against it.

**Comment by ghost** [comment]
@davidlange6 Merging this now.

**Comment by davidlange6** [comment]
was about to comment - but I think its still relevant -. could we not remove all of the commented out code in the patch?

**Comment by mkirsano** [comment]
The commented out code does not compile with c++11. It is substituted 
by another code.

**Pull request merged**
