### PR TITLE
Advance to latest release of RecoBTag/CTagging data.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-data/RecoBTag-CTagging/commit/7a5db4187a1a8192e3b669b3de074553884a4a86

### CODE REVIEW

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@degano 
I'm looking at https://cmssdt.cern.ch/jenkins/job/cmsdist-test-pr/73/console
It looks like the full release is recompiled.
This is excessive for data externals.

Is the logic for testing to have a full rebuild for any cmsdist update?
We maybe need to get some improvement to this.

In this case we only needed the new external built and then the matrix&addOn tests rerun.

**Comment by slava77** [comment]
the unit test failures are unrelated, they are present in the IB as well
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2016-01-27-2300/unitTestLogs/RecoLocalCalo/HGCalRecProducers

looking at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2106/73/summary.html
even after 11 hours, the comparisons have never completed.

from the change in the code
https://github.com/cms-data/RecoBTag-CTagging/compare/V01-00-00...V01-00-02
it's is clear that only new files are added.
I think at this point it is more important to merge this and have the new training files in the release.
If they are good, we can get the https://github.com/cms-sw/cmssw/pull/13054 in as well. 
The last set of tests check only the jenkins test infrastructure, not very successfully.

**Comment by ghost** [comment]
please test

**Comment by slava77** [comment]
@degano 
which jenkins project is running the comparisons for builds done in cmsdist-test-pr?
The status for this test https://cmssdt.cern.ch/jenkins/job/cmsdist-test-pr/80/ says there is supposed to be a subproject job in https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/, but I do not see anything relevan there.

Please clarify where to look for the comparison job.
Thank you.

**Comment by smoortga** [comment]
Dear @degano, Dear @slava77,
Since the dealine for the last open 8.0.X. release is only two days away, I was wondering if you could update @mverzett and myself about the status of our PR. It seems like all of the tests discribed above have eventually passed successfully (or is this not the case?), and our cmssw PR (https://github.com/cms-sw/cmssw/pull/13054) is still waiting for this one to be approved. 

Thanks a lot!
Cheers, Seth

**Comment by slava77** [comment]
@davidlange6 
This is just to note that we may need some extra time (or action) to get #13054 through into 80X (once this external update is done).

**Comment by davidlange6** [comment]
I'll merge it - but yes, any externals update means a full cmssw rebuild.

**Comment by slava77** [comment]
On 1/30/16 10:58 AM, David Lange wrote:

> I'll merge it - but yes, any externals update means a full cmssw rebuild.

Thank you for the merge.
I suppose, the file will show up in the -2300 IB.

The case of data file externals may better be reconsidered.
Although a better way is still to push everything to a GT.
At an extreme, when only this external is changing,
a sub-MB size update in a data file costs a few GB of release space.

**Pull request merged**
