### PR TITLE
Move to HTCondor 8.9.7

### PR DESCRIPTION
**Pull request by khurtado**
Move from HTCondor 8.8.3 to 8.9.7

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 9c3360dee9ba40c67eb049e979cd9fb8259c0341 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5967/test_9c3360d-20200618-230503.log" target="_blank">here</a>.

**Comment by khurtado** [comment]
This version was tested in WMAgent and CRAB and it worked fine.
Can we merge it? 
CC: @amaltaro @belforte 
EDIT: Putting this on hold until new WMAgent release candidate

**Comment by amaltaro** [comment]
@khurtado as we just chatted over slack, I'd rather keep it open until we get to the point that a new WMAgent release candidate can be made (in a couple of weeks from now).

**Comment by belforte** [comment]
from my side, feel free

**Comment by amaltaro** [comment]
@muhammadimranfarooqi feel free to merge this one

**Comment by amaltaro** [comment]
@muhammadimranfarooqi this RPM hasn't showed up in cmsrep either.

**Comment by muhammadimranfarooqi** [comment]
@smuzaffar @amaltaro 

The RPMs for the PRs merged yesterday did not appear in http://cmsrep.cern.ch/cgi-bin/repos/comp/slc7_amd64_gcc630?C=M;O=D.

I did not find any error in the logs. Do we need to change something in build machine?

Thanks

**Comment by smuzaffar** [comment]
log here is only for build, Where is the log for upload?

**Comment by muhammadimranfarooqi** [comment]
There are a couple of entries for PRs yesterday like this


```
[cmsweb@vocms055 ~]$ less /build/dmwmbld/srv/logs/dmwmbld/dmwmbld-20200915

------------- 2020-09-15 14:05:01 comp_gcc630:slc7_amd64_gcc630 -------------
Checking for new commits:
New commit 9eb8f379eb4264c947b4d1c17b55e4d7340a7f83. Pre-releasing RPMs...
/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc630
testing
Cloning into 'cmsdist'...
HEAD is now at 9eb8f37 Move to HTCondor 8.9.7 (#5967)

Building RPMs...
Uploading RPMs...
Pull Requests to test:
#6021, New specs for a python3 wmagent and wmcore-devtools
#5004, Update setuptools to 40.5.0
#4956, New spec for uwsgi
Latest status is pending
```

**Comment by amaltaro** [comment]
If upload is made against cmsrep node, since it changed this last Monday, don't we need to update its key in ~/.ssh/known_hosts (on the build machine node)?

**Comment by smuzaffar** [comment]
No @amaltaro, if you are using latest pkgtools commit .

**Comment by smuzaffar** [comment]
@muhammadimranfarooqi , where is the script which you run for build and upload?

**Comment by muhammadimranfarooqi** [comment]
This is the key in known_host
```
cmsrep.cern.ch,128.142.142.109 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArEjm7lr887Gfl1wiVEziGEeNGPoN81AQV6iwd2JfJiQANQ4HBx2UzTKwGH0aXaW6RzoqSVXsLP7Bd47HnIB6mDxRxGVRkA6kUNATxIi0A2KbJxmd+PcD6aUEmsxWfMaq99yFrpWkfo94rtNVUIHJrXS5GWKpzilm415hq80WaQyXySevKnzaN+6kSOaSLugyOJKux1UW+LsCdpn3KR1UIp6TbVjxnqbQEUDnp4lescUvuzYJFBz0sXo6hXbhDuuCTtUSRe3nyW0qRW8oQZY3ZceGqNPEVP9vnifYGEy43V41eJGTMRKxKj68BPSPY5dcrtEO+392qbUUUX+lUKUlZw==
```

**Comment by muhammadimranfarooqi** [comment]
The script is this:

```
/build/dmwmbld/srv/current/config/dmwmbld/dmwmbld_task 
```

**Comment by smuzaffar** [comment]
so this script is not cloning pkgtools. 
@amaltaro is right that if you are not using latest pkgtools commit then you need to update the host key.

**Comment by amaltaro** [comment]
AFAIK we don't usually change pkgtools, Shahzad. We stick with one branch and usually one commit, and only change that if really needed.

**Comment by muhammadimranfarooqi** [comment]
I have updated key

**Comment by smuzaffar** [comment]
so did this update work? are you able to upload now?

**Comment by muhammadimranfarooqi** [comment]
Yes, packages are uploaded. 

http://cmsrep.cern.ch/cgi-bin/repos/comp/slc7_amd64_gcc630?C=M;O=D

Thanks

**Comment by amaltaro** [comment]
Yes, I see both condor and rucio-clients up-to-date in there. Thank you very much!

**Pull request merged**
