### PR TITLE
Herwig7: Config files needed to implement Herwig7

### PR DESCRIPTION
**Pull request by mharrend**
Original pullrequest #2082 was splitted in two requests
LHAPDF: Herwig7 requires two further PDFs
MG5aMC: Herwig7 allows to use it as a ME provider
gengetopt: Herwig7 needs it during compilation
HerwigPP: Removed obsolete patches and a small patch to compile it with our boost version is necessary

### CODE REVIEW

**Comment by mharrend** [comment]
Please note that this request relies on #2099  in which gengetopt is provided.

**Comment by davidlt** [comment]
Question, don't you need `BuildRequires: gengetopt` ?

**Comment by mharrend** [comment]
Since gengetopt #2100 is now merged into CMSSW, can you please test this PR?
Thanks Marco

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by mharrend** [comment]
This error is strange, the MMHT2014 PDF is not found in the lhapdf installation, even though I changed the lhapdf.spec file to make sure it is included.

**Comment by mharrend** [comment]
Please test again. I tried to make sure that the updated lhapdf.spec is using.

**Comment by covarell** [comment]
please test

**Comment by mharrend** [comment]
For some reasons the MMHT2014LO PDF is not found, excerpt from error message : 
Requested to quit.
- The action "build-external+herwigpp-toolfile+1.0-cms2" was not completed successfully because The following dependencies could not complete:
  install-external+herwigpp+7.0.0
- The action "final-job" was not completed successfully because The following dependencies could not complete:
  build-external+herwigpp+7.0.0
- The action "install-external+herwigpp-toolfile+1.0-cms2" was not completed successfully because The following dependencies could not complete:
  build-external+herwigpp-toolfile+1.0-cms2
- The action "build-external+herwigpp+7.0.0" was not completed successfully because Failed to build herwigpp. Log file in /build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/BUILD/slc6_amd64_gcc493/external/herwigpp/7.0.0/log. Final lines of the log file:
  make  install-data-hook
  make[5]: Entering directory `/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/BUILD/slc6_amd64_gcc493/external/herwigpp/7.0.0/Herwig-7.0.0/src'
  Creating repository
  Error: 'set /Herwig/Partons/HardLOPDF:PDFName MMHT2014lo68cl': PDF not installed. Try 'lhapdf install'.
  make[5]: **\* [install-data-hook] Error 1

However, it is included by the updated lhapdf.spec file look here:

external+lhapdf+6.1.6-cms', 'install-external+rivet+2.4.0', 'fetch-external+thepeg+2.0.0']
Done fetching http://www.hepforge.org/archive/lhapdf/pdfsets/6.1/CT10.tar.gz
Done fetching http://www.hepforge.org/archive/lhapdf/pdfsets/6.1/MSTW2008nlo68cl.tar.gz
Starting to process package external+madgraph5amcatnlo+2.3.3
Checking if madgraph5amcatnlo is cached.
Package external+madgraph5amcatnlo+2.3.3 not found in repository. Queuing for build.
Dependencies for external+madgraph5amcatnlo+2.3.3: ['install-external+gcc+4.9.3', 'install-external+python+2.7.6-kpegke', 'install-external+hepmc+2.06.07', 'install-external+lhapdf+6.1.6-cms', 'install-lcg+root+6.06.00-agmdcp', 'fetch-external+madgraph5amcatnlo+2.3.3']
Done fetching https://www.hepforge.org/archive/lhapdf/pdfsets/6.1/MMHT2014lo68cl.tar.gz
Starting to process package external+herwigpp+7.0.0

If I am trying to compile Herwig7 locally adding the two missing PDF sets in the lhapdf.spec file seems to be enough. 
However, it seems that even if the lhapdf is updated some older version of lhapdf is used for Herwig7.

Should I split the PR  and first update the lhapdf.spec in a dedicated PR to make sure that the newer LHAPDF is used? Any other ideas?

**Comment by ghost** [comment]
Building locally gives the same error by simply compiling herwigpp:
`PKGTOOLS/cmsBuild -j 12 -i a --repository cms.week0 --arch slc6_amd64_gcc493 build herwigpp`

**Comment by mharrend** [comment]
Please test

Dear all, 
if have now added two patches which deactivate the failing tests during make check.
These tests are not required since we are testing Herwig7 anyway, furthermore, I would expect that the problem is solved as soon as the updated lhapdf.spec file is becoming globally.

Since Herwig7 should be part of CMSSW 8_0_X please start the tests as soon as possible and sorry, for the late update before the release.

Thanks, 

Marco

**Comment by covarell** [comment]
please test

**Comment by covarell** [comment]
This needs to be forward-ported to 8_1_X if successful

**Comment by davidlange6** [comment]
instead - lets get it to work in 81x and then consider back ports

**Comment by ghost** [comment]
I'm closing this PR as this change should be targeted to 81X anyway.

**Pull request closed without merging**
