### PR TITLE
upgrade evtgen to 1.6.0

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by govoni** [comment]
+1

**Comment by smuzaffar** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
the error is related to bugin sherpa spec. We shall test it again once sherpa fix is integrated.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mkirsano , for building evtgen with gcc6 (thanks fot @davidlt) we apply this patch

```
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_8_1_X/gcc600/evtgen-1.5.0-configure-gcc6.patch
```

can you please get this merged in upstream for next evtgen version?

**Comment by mkirsano** [comment]
Thanks a lot, I will send it to the authors.

11/08/16 11:59, Malik Shahzad Muzaffar пишет:

**Comment by davidlt** [comment]
@mkirsano send them with the commit message as it contains reasoning: https://github.com/cms-sw/cmsdist/commit/cdd03dbd7367c35d986c3d6f5ef7d57611392ee5

**Comment by davidlt** [comment]
The two issues are that:
- `libgfortranbegin.a` was deprecated long time ago and finally completely removed.
-  Package might want to pick which C++ standard they want to support C++03/C++11/C++14/C++1z as those could yield different behaviour (just as a precaution, not a hard requirement).

**Comment by mkirsano** [comment]
Yes, actually I have already asked the authors to add the possibility 
of using user's additional compiler flags.

11/08/16 13:43, davidlt пишет:

**Pull request merged**
