### PR TITLE
Update LLVM to 11.1

### LINKED ISSUE #6666: llvm/clang 11.1
Whenever it's convenient, we could start upgrading llvm/clang to version 11.1 .

Note that 11.0 had an ABI incompatibility with 10.0 and 12.0 (trunk), which is fixed in 11.1 .

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #6666
This builds the LLVM external

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
hopefully full toolconf will build.

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
@mrodozov , you need to issue please test for slc7_aarch64_gcc9 again. In one iteration bot only recognize the last command. Normally you have to wait for the bot to ack your last command before issuing the next one :-)

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/33110

**Comment by smuzaffar** [comment]
test parameters:
- pull_request =  cms-sw/cmssw#33110
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test for CMSSW_11_3_CLANG_X

**Comment by smuzaffar** [comment]
@makortel , @Dr15Jones, I ran llvm11.1/clang-tidy on full cmssw and one change which it proposes [a], causes `gcc` to produce `unused-variable` warning [b]. Should we disable clang-tidy check for this line by adding `WaitingTaskHolder h(task); // NOLINT`?

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_11_3_X_2021-03-08-1100/63/code-checks.patch
```
--- a/FWCore/Framework/interface/Callback.h
+++ b/FWCore/Framework/interface/Callback.h
@@ -146,7 +146,7 @@ namespace edm {
                                    EventSetupImpl const* iImpl,
                                    ESProxyIndex const* proxies,
                                    edm::ServiceToken const& token) const {
-        WaitingTaskHolder h(task);
+        const WaitingTaskHolder& h(task);
         auto recs = producer_->getTokenRecordIndices(id_);
         auto n = producer_->numberOfTokenIndices(id_);
         for (size_t i = 0; i != n; ++i) {
```

[b] https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_11_3_X_2021-03-08-1100/63/build-logs/

**Comment by makortel** [comment]
> Should we disable clang-tidy check for this line by adding `WaitingTaskHolder h(task); // NOLINT`?

That is probably the simplest workaround. While `const WaitingTaskHolder& h(task);` would technically work correctly, it looks a bit "strange", so I'd rather keep the current code than try to fight against GCC's warning.

**Comment by Dr15Jones** [comment]
It looks to me like the line can just go away. The lifetime of `task` is already making sure that the task can't start until after the function ends.

**Comment by makortel** [comment]
> It looks to me like the line can just go away. The lifetime of `task` is already making sure that the task can't start until after the function ends.

That would of course be even better.

**Comment by mrodozov** [comment]
is this patch:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_11_3_X_2021-03-08-1100/63/code-checks.patch
a "one time fix" we have to apply that is the differences between 10/11 (maybe the improved existing checks) ?

**Comment by smuzaffar** [comment]
Yes it is full patch but we do not have to apply it. LLVM 10 also suggest the similar changes ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_11_3_X_2021-03-08-2300/59/code-checks.patch ) . We can apply on cmssw categories bases after llvm 11.1

**Comment by smuzaffar** [comment]
looks like new llvm generate few more warnings for CLANG build ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c0a525/13406/build-logs/ ). Once ready we should first get llvm 11. 1 only CLANG builds

**Comment by Dr15Jones** [comment]
See https://github.com/cms-sw/cmssw/pull/33136

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
@cms-sw/externals-l2 can we merge this PR with cms-sw/cmssw#33110? Do we need cms-sw/cmssw#33136 too?

**Comment by mrodozov** [comment]
cms-sw/cmssw#33110 and cms-sw/cmssw#33136 can and should be merged on their own . 33110 was updated to work with both llvm10 and 11 . I'll quote this (from above comments)


> looks like new llvm generate few more warnings for CLANG build ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c0a525/13406/build-logs/ ). Once ready we should first get llvm 11. 1 only CLANG builds

for which we have #6720

**Comment by smuzaffar** [comment]
please test for CMSSW_11_3_CLANG_X

**Comment by smuzaffar** [comment]
@mrodozov , @silviodonato , once we have  https://github.com/cms-sw/cmssw/pull/33171 merged then all the new build warnings should go away and we can merge it directly in the master IB.

**Comment by smuzaffar** [comment]
+externals
looks good to go, CLANG IBs will have an extra warnings which should be fixed when  cms-sw/cmssw#33171 is merged

**Comment by davidlange6** [comment]
Hi @smuzaffar @mrodozov - did you look at clang-tidy changes due to this upgrade? I've noticed a few unexpected changes in the last day (eg, here was a change needed after an unrelated commit was pushed yesterday https://github.com/cms-sw/cmssw/pull/33189

**Comment by smuzaffar** [comment]
yes I did run clang-tidy and format for this, see the following comments
https://github.com/cms-sw/cmsdist/pull/6691#issuecomment-795290374
https://github.com/cms-sw/cmsdist/pull/6691#issuecomment-795875290

Most of these are already reported by llvm 10 too.

**Comment by davidlange6** [comment]
Hum, then I don’t understand the need for
https://github.com/cms-sw/cmssw/pull/33189/commits/04a1e0b5091fa793790380da5c5c99bb293eaa5b
That came one the second code-checks run of the PR on a file that wasn’t touched during the PR review..

Hopefully isolated:)

**Comment by smuzaffar** [comment]
cms-sw/cmssw@04a1e0b is code format change. Looks like llvm 11 has improved on few formats . See the below links for code format changes for full cmssw

LLVM 10: https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_11_3_X_2021-03-08-2300/59/code-format.patch (61 changes)
LLVM 11: https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_11_3_X_2021-03-08-1100/63/code-format.patch  (112 changes)

**Comment by smuzaffar** [comment]
it could be if google code style has updated few defaults. Let me see the differences

**Comment by makortel** [comment]
Would it make sense to have an automated reformatting campaign? (after double-checking the style definition itself)

**Comment by smuzaffar** [comment]
here is the code format changes which is reasonable. I would not recommend to change the google default. After all it is not a big bang changes. Only 50 new changes.
```
--- l10.txt     2021-03-17 15:02:22.291374654 +0100
+++ l11.txt     2021-03-17 15:03:58.029633511 +0100
@@ -1,19 +1,21 @@
 >> Local Products Rules ..... started
 >> Local Products Rules ..... done
-clang-format   -dump-config /build/muz/CMSSW_11_3_X_2021-03-07-0000/src/.clang-format
+clang-format   -dump-config /build/muz/CMSSW_11_3_X_2021-03-16-2300/src/.clang-format
 ---
 Language:        Cpp
 AccessModifierOffset: -2
 AlignAfterOpenBracket: Align
 AlignConsecutiveMacros: false
 AlignConsecutiveAssignments: false
+AlignConsecutiveBitFields: false
 AlignConsecutiveDeclarations: false
 AlignEscapedNewlines: Left
-AlignOperands:   true
+AlignOperands:   Align
 AlignTrailingComments: true
 AllowAllArgumentsOnNextLine: true
 AllowAllConstructorInitializersOnNextLine: true
 AllowAllParametersOfDeclarationOnNextLine: true
+AllowShortEnumsOnASingleLine: true
 AllowShortBlocksOnASingleLine: Never
 AllowShortCaseLabelsOnASingleLine: false
 AllowShortFunctionsOnASingleLine: All
@@ -29,7 +31,7 @@
 BraceWrapping:
   AfterCaseLabel:  false
   AfterClass:      false
-  AfterControlStatement: false
+  AfterControlStatement: Never
   AfterEnum:       false
   AfterFunction:   false
   AfterNamespace:  false
@@ -39,6 +41,8 @@
   AfterExternBlock: false
   BeforeCatch:     false
   BeforeElse:      false
+  BeforeLambdaBody: false
+  BeforeWhile:     false
   IndentBraces:    false
   SplitEmptyFunction: true
   SplitEmptyRecord: true
@@ -85,10 +89,13 @@
 IncludeIsMainRegex: '([-_](test|unittest))?$'
 IncludeIsMainSourceRegex: ''
 IndentCaseLabels: true
+IndentCaseBlocks: false
 IndentGotoLabels: true
 IndentPPDirectives: None
+IndentExternBlock: AfterExternBlock
 IndentWidth:     2
 IndentWrappedFunctionNames: false
+InsertTrailingCommas: None
 JavaScriptQuotes: Leave
 JavaScriptWrapImports: true
 KeepEmptyLinesAtTheStartOfBlocks: false
@@ -98,6 +105,7 @@
 NamespaceIndentation: All
 ObjCBinPackProtocolList: Never
 ObjCBlockIndentWidth: 2
+ObjCBreakBeforeNestedBlockParam: true
 ObjCSpaceAfterProperty: false
 ObjCSpaceBeforeProtocolList: true
 PenaltyBreakAssignment: 2
@@ -135,6 +143,8 @@
       - PARSE_TEXT_PROTO
       - ParseTextOrDie
       - ParseTextProtoOrDie
+      - ParseTestProto
+      - ParsePartialTestProto
     CanonicalDelimiter: ''
     BasedOnStyle:    google
 ReflowComments:  false
@@ -166,5 +176,9 @@
 TabWidth:        8
 UseCRLF:         false
 UseTab:          Never
+WhitespaceSensitiveMacros:
+  - STRINGIZE
+  - PP_STRINGIZE
+  - BOOST_PP_STRINGIZE
```

**Comment by smuzaffar** [comment]
> Would it make sense to have an automated reformatting campaign? (after double-checking the style definition itself)

Yes, it is about time to do one. Although for default clang-tidy and format , we have 120 packages (194 files) which needs format/tidy updates but we can enable cms-hanlde check too (needs 6.5K changes)

**Comment by makortel** [comment]
I would do the `cms-handle` separately as it is conceptually different from "changes from LLVM upgrade" (and try it out on a few packages first to get feedback like we did when we started to use `clang-tidy`).

**Pull request merged**
