### PR TITLE
Test vecgeom 1.1.20 in master branch

### PR DESCRIPTION
**Pull request by iarspider**
Requested here: https://github.com/cms-sw/cmsdist/pull/7735#issuecomment-1092576925

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by civanch** [comment]
@iarspider , @smuzaffar , test is rejected in the same way as in G4VECGEOM. There is a new PR  [#37542 ](https://github.com/cms-sw/cmssw/pull/37542), whihc may help.

**Comment by iarspider** [comment]
please test with cms-sw/cmssw#37542

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
PR https://github.com/cms-sw/cmssw/pull/37542 is closed, because is useless but there is a question: is DD4hep recompiled when a new vecgeom is tested?

**Comment by smuzaffar** [comment]
@civanch , although there is no [direct dependency](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_4_X/master/dd4hep.spec) on `vecgeom` for `dd4hep` but yes it is rebuild when `vecgeom` is updated as `dd4hep` in-directly depends on `vecgeom` via [geant4](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_4_X/master/geant4.spec)

**Comment by civanch** [comment]
@smuzaffar , may be a problem in rebuild order?

**Comment by smuzaffar** [comment]
@civanch , no it can not be. dd4hep can not be build before geant4 and geant4 can not be build before vecgeom

**Comment by smuzaffar** [comment]
disabling `biglib` should the error is from libG4geometry.so
```
#0  0x00007fffbf57c53a in vecgeom::cxx::CommonUnplacedVolumeImplHelper<vecgeom::cxx::PolyhedronImplementation<(EInnerRadii)0, (EPhiCutout)0>, vecgeom::cxx::VUnplacedVolume>::SafetyToIn(vecgeom::cxx::Vector3D<double> const&) const () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4geometry.so
#1  0x00007fffbf57fe27 in G4UAdapter<vecgeom::cxx::UnplacedPolyhedron>::DistanceToIn(CLHEP::Hep3Vector const&) const () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4geometry.so
#2  0x00007fffbf3cbde2 in G4VoxelNavigation::ComputeStep(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, double, double&, G4NavigationHistory&, bool&, CLHEP::Hep3Vector&, bool&, bool&, G4VPhysicalVolume**, int&) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4geometry.so
#3  0x00007fffbf3acc64 in G4Navigator::ComputeStep(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, double, double&) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4geometry.so
#4  0x00007fffbe053604 in G4Transportation::AlongStepGetPhysicalInteractionLength(G4Track const&, double, double, double&, G4GPILSelection*) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4processes.so
#5  0x00007fffbcf786cc in G4SteppingManager::DefinePhysicalStepLength() () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4tracking.so
#6  0x00007fffbcf76ca0 in G4SteppingManager::Stepping() () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4tracking.so
#7  0x00007fffbcf81ea8 in G4TrackingManager::ProcessOneTrack(G4Track*) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4tracking.so
#8  0x00007fffbf84fc5b in G4EventManager::DoProcessing(G4Event*) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/external/slc7_amd64_gcc10/lib/libG4event.so
#9  0x00007fffbfbd963e in RunManagerMTWorker::produce(edm::Event const&, edm::EventSetup const&, RunManagerMT&) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/lib/slc7_amd64_gcc10/libSimG4CoreApplication.so
#10 0x00007fffbfc0de45 in omt::ThreadHandoff::Functor<OscarMTProducer::produce(edm::Event&, edm::EventSetup const&)::{lambda()#1}>::execute() () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/lib/slc7_amd64_gcc10/pluginSimG4CoreApplicationPlugins.so
#11 0x00007fffbfbe890a in omt::ThreadHandoff::threadLoop(void*) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7775/23855/CMSSW_12_4_X_2022-04-12-1100/lib/slc7_amd64_gcc10/libSimG4CoreApplication.so
#12 0x00007ffff5591ea5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007ffff52bab0d in clone () from /lib64/libc.so.6

```

**Comment by smuzaffar** [comment]
@civanch , I see that geant4 is built with  [-DGEANT4_USE_USOLIDS="all"](https://github.com/cms-sw/cmsdist/blob/b589effb57995b0444cb6106a60579e6a924d949/geant4.spec#L52) , should we then define [G4GEOM_USE_USOLIDS](https://github.com/Geant4/geant4/blob/v10.7.2/source/geometry/management/include/G4UAdapter.hh#L58) for cmssw?

**Comment by smuzaffar** [comment]
In past , when we enable vecgeom for 11.3.X then we had this marco set  https://github.com/cms-sw/cmsdist/commit/a3bea0e87c5036c5eff8ffb1df1d2009919a3759 .

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@iarspider , @smuzaffar , likely this PR may be closed. 

Recent IBs GEANT4 and G4VECGEOM are working fine. There is only one problem: Geant4 and VecGeom are built in the debug mode. In the next IBs we would like to use optimal compile options in order to be able to check CPU performance.

**Comment by smuzaffar** [comment]
thanks @civanch , https://github.com/cms-sw/cmsdist/pull/7981 should build geant4 in `Release` mode for g4vecgeom IBs.

**Comment by smuzaffar** [comment]
@civanch , I think building vecgeom and geant4 in debug mode fixed the runtime issues we were seeing before. I see that G4 and G4+Vecgeom Ibs now again have same failure as we are not building g4 and vecgeom in debug mode.

**Comment by civanch** [comment]
@smuzaffar , yes, we realized this. Probably for summer it is better to return back debug mode for the G4VECGEOM branch. Is it possible simultaneously build the GEANT4 branch with optimal mode?

**Pull request closed without merging**
