### PR TITLE
[cxxmodules] Enable DataFormats/{HLT,MET}Reco

### PR DESCRIPTION
**Pull request by vgvassilev**
cc: @davidlange6, @oshadura

### CODE REVIEW

**Comment by mrodozov** [comment]
we are testing this 
https://github.com/cms-sw/cmsdist/pull/5532 
which gets the latest commits from master,
if it goes fine we test also this one and get it in.

**Comment by mrodozov** [comment]
well, we still have trouble with the string_view + string operator in CMSSW and we have to fix it everywhere :/

**Comment by davidlange6** [comment]
e.g., there was an api change in ROOT?

**Comment by davidlange6** [comment]
if that's going to take a while, It may be worthwhile cherry picking things with the help of @vgvassilev

**Comment by mrodozov** [comment]
yes. ROOT was providing a string_view + string operator which is not there anymore 
I was searching (again) to see where exactly that happened :
https://github.com/root-project/root/search?q=string_view&type=Commits

**Comment by smuzaffar** [comment]
it might be related to https://github.com/root-project/root/commit/f00051d336c43d3d26b948c88f7e336c34451f4e

**Comment by davidlange6** [comment]
interesting.

Anyway, 0 errors fixed in a week? Perhaps we can cherry pick some things given that there is some nice progress expected on the modules side.

On Feb 17, 2020, at 4:34 PM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:


yes. ROOT was providing a string_view + string operator which is not there anymore
I was searching (again) to see where exactly that happened :
https://github.com/root-project/root/search?q=string_view&type=Commits

**Comment by smuzaffar** [comment]
@davidlange6 , it is not fully under our control. root changed some thing which broken DD4Hep, we now have dd4hep (claiming) that it should work with root 6.18 and above. we now need to fix cmssw to adopt root changes.

**Comment by mrodozov** [comment]
We started fixing cmssw last week with this:
https://github.com/cms-sw/cmssw/pull/28951
which was not enough as there are more places to be fixed

**Comment by davidlange6** [comment]
Sure - I understand:(.. thus my suggestion to work around it..

On Feb 17, 2020, at 4:44 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> , it is not fully under our control. root changed some thing which broken DD4Hep, we now have dd4hep (claiming) that it should work with root 6.18 and above. we now need to fix cmssw to adopt root changes.

**Comment by smuzaffar** [comment]
you are welcome to provide a patch/fix for cms root's cxxmodule branch to make MODULES IBs go ahead :-)

**Comment by davidlange6** [comment]
Ok - will do.

On Feb 17, 2020, at 4:54 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


you are welcome to provide a patch/fix for cms root's cxxmodule branch to make MODULES IBs go ahead :-)

**Comment by smuzaffar** [comment]
closing in favor of #5558

**Pull request closed without merging**
