### PR TITLE
Update python from 3.6.2 to 3.8.2

### PR DESCRIPTION
**Pull request by amaltaro**
Update python version with basically the same spec in the default CMSSW branch, here:
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/python3.spec

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
to 5860e7b38a8c3f9e4b265194069f165873cc5330 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6377/test_5860e7b-20201106-074503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 5860e7b38a8c3f9e4b265194069f165873cc5330 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6377/test_5860e7b-20201106-083003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Perfect! Given that there are no spec files depending on it (besides the python libraries and WMArchive, which no longer uses the python baseline code), I'd suggest to get it merged such that I can try to advance with:
https://github.com/cms-sw/cmsdist/pull/6021

Imran, can you please have a look at get it merged? @muhammadimranfarooqi

**Comment by smuzaffar** [comment]
@amaltaro @muhammadimranfarooqi  are you sure comp bit actually building this package? bot is building `comp` spec which does not depend on python3

**Comment by amaltaro** [comment]
Thanks for noticing it Shahzad. You're right, I do not see a new RPM in the repository...

**Pull request merged**
