### PR TITLE
[11.1.X][Cuda] drop compute_61 and add compute_35

### PR DESCRIPTION
**Pull request by smuzaffar**
Techlab GPU nodes we have are K20Xm and for those we need to build for compute_35

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
enable gpu

**Comment by smuzaffar** [comment]
FYI @fwyzard

**Comment by fwyzard** [comment]
thanks

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
