### PR TITLE
Fix igprof in g12 branch (#8269)

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test for el8_amd64_gcc12

**Comment by iarspider** [comment]
please test for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
@iarspider , why close it? It fixes the igprof compilation issue ... right ? GCC 12 IBs are broken anyway due to cuda/gcc compatibility issue. If the patch is not needed any more than I think we should merge it

**Comment by iarspider** [comment]
@smuzaffar I can't reproduce the issue anymore, thus closing.

**Comment by smuzaffar** [comment]
aren't gcc12 IBs jobs failing any more?

**Comment by smuzaffar** [comment]
humm, looks like they are still failing https://cmssdt.cern.ch/jenkins/job/build-any-ib/147140/ with error
https://cmssdt.cern.ch/SDT/jenkins-artifacts/build-any-ib/CMSSW_13_0_X_2023-02-04-1100/el8_amd64_gcc12/147140/external/igprof/5.9.16-134870b2b3774cff1c837d73b1dab312/log 
```
+ PKGTOOLS_PATCH_NUM=0
+ echo 'Patch #0 (igprof-gcc8):'
Patch #0 (igprof-gcc8):
+ patch --no-backup-if-mismatch -p1 --fuzz=0
patching file CMakeLists.txt
Hunk #1 FAILED at 80.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
error: Bad exit status from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/rpm-tmp.MH8qRO (%prep)
```
```

**Comment by iarspider** [comment]
~~I have tested current version of igprof (i.e. the unchanged recipe), and it built just fine, see log on cmsbuild32:/build/razumov/cmsbuild/BUILD/BUILD/el8_amd64_gcc12/external/igprof/5.9.16-41686e91f8e987d922b0f95430b59264/log .~~ NVM, forgot to pull

**Comment by smuzaffar** [comment]
ah ok, so may be we should rebuild the gcc12 IB job then

**Pull request closed without merging**
