### PR TITLE
Update gcc to 7.4.0

### PR DESCRIPTION
**Pull request by mrodozov**
GCC to be updated for building tensorflow

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
shouldn't have reference to this class anymore :/

**Comment by mrodozov** [comment]
please test
the root commits went in so lets see gcc alone

**Comment by mrodozov** [comment]
abort
root got reverted, lets restart the test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
abort
lets wait for GCC 7 DEVEL IB to finish then we should run tests

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
lets merge it for DEVEL IBs

**Pull request merged**
