### PR TITLE
[ROOT modules] Get latest from master

### PR DESCRIPTION
**Pull request by mrodozov**
test parameters:
- release = CMSSW_11_2_CXXMODULE_X_2020-07-20-2300

### CODE REVIEW

**Comment by mrodozov** [comment]
please test for CMSSW_11_2_CXXMODULE_X_2020-07-20-2300

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov , looks like we do not need root boost patch ... @davidlange6 @vgvassilev can you please confirm?

**Comment by mrodozov** [comment]
yes, @vgvassilev changed the file in https://github.com/cms-sw/root/commit/703ae329227e1bda4ae64a0a3e35457b2cbd5764#diff-08ab54598c82d3544558d0e9326977a6
and now the patch is not applicable 
I'm changing the existing patch to put the changes and rebuild

**Comment by vgvassilev** [comment]
That particular patch can go. However, we will be fixing header includes in boost mainline and we will be backporting those patches. I guess that's not cxxmodules-related but of general interest?

cc: @camolezi

**Comment by mrodozov** [comment]
@vgvassilev right, but I need the cross section of what was in the patch and what is now in the new file :) 
I'll remove all that is removed in the patch but I wonder about this difference:
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/rootmodule/root_boostmod.patch#L15
vs
https://github.com/cms-sw/root/blob/703ae329227e1bda4ae64a0a3e35457b2cbd5764/interpreter/cling/include/cling/boost.modulemap#L5345
should I skip the adding part in the patch altogether and leave whats in root already or the opposite ?

**Comment by mrodozov** [comment]
please test

**Comment by vgvassilev** [comment]
@mrodozov, indeed we should get what's in the current master: https://github.com/root-project/root/blob/master/interpreter/cling/include/cling/boost.modulemap

**Comment by mrodozov** [comment]
the patch was entirely covered with whats already in master, I checked. so I removed it

**Comment by davidlange6** [comment]
I’d propose we just merge this change so that I can fix things on top of it. Is that ok?

On Jul 24, 2020, at 11:48 AM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:



the patch was entirely covered with whats already in master, I checked. so I removed it

**Comment by mrodozov** [comment]
the external built:
```

13:29:39 Build logs cleanup root
13:29:41 Build successful root.
```
so it's relatively safe to merge it, yes.

**Comment by davidlange6** [comment]
Ok, lets do that - my guess is that a dependency may fail (as it did in the IB last night) - but that depends on what got picked up. I can resync things this afternoon.

On Jul 24, 2020, at 12:56 PM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:



the external built:


13:29:39 Build logs cleanup root
13:29:41 Build successful root.


so it's relatively safe to merge it, yes.

**Pull request merged**
