### PR TITLE
Update data-RecoBTag-Combined.spec

### PR DESCRIPTION
**Pull request by mrodozov**
Description: https://github.com/cms-data/RecoBTag-Combined/pull/15

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
please merge this or comment if some changes are necessary.
This PR data files were already successfully tested at run time (as a part of #4176). 
Thank you.

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
assign reconstruction

**Comment by smuzaffar** [comment]
@slava77 , we are fine to merge it but as  cms-data/RecoBTag-Combined#15 updates couple of existing files so assigned reco to sign it too.

**Comment by smuzaffar** [comment]
oops sorry, all files are new (I was looking in to master branch). So forget my previous comment.

**Pull request merged**
