### PR TITLE
use -msse3 in mkfit.spec to match gcc-toolfile.spec

### PR DESCRIPTION
**Pull request by slava77**
This is a followup to tests and discussion in https://github.com/cms-sw/cmssw/pull/27895#issuecomment-530019102

@makortel @osschar

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , this is ready to go in IBs

**Comment by fabiocos** [comment]
+1

**Pull request merged**
