### PR TITLE
[celeritas] build with -DCMAKE_POSITION_INDEPENDENT_CODE=ON

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by whokion** [comment]
@smuzaffar was this MR merged (i.e, can I test the linking celeritas from SimG4Core with the latest CMSSW build) or is there still remaining issue?  Thanks.

**Comment by smuzaffar** [comment]
> @smuzaffar was this MR merged (i.e, can I test the linking celeritas from SimG4Core with the latest CMSSW build) or is there still remaining issue? Thanks.

yes, it is already in latest cmssw builds

**Comment by whokion** [comment]
@smuzaffar I tried to link celeritas with one of recent CMSSW builds (CMSSW_14_0_X_2024-01-02-1100 and CMSSW_14_0_X_2024-01-04-1100) which still fails with the same error message reported earlier ([#8867](https://github.com/cms-sw/cmsdist/issues/8867)).  All those undefined objects actually exist inside celeritas libraries. As a test, I put separate static libs into one which still did not work while celeritas links successfully from SimG4Core with shared libs built locally. Per @makortel request (to reproduce the lining error), the changes that I made for linking testing is included here([changes-to-SimG4Core.txt](https://github.com/cms-sw/cmsdist/files/13836288/changes-to-SimG4Core.txt)).

**Comment by makortel** [comment]
I was able to reproduce the link error in CMSSW_14_0_X_2024-01-05-1100. The error occurs, after disabling the big library with `scram b disable-biglib`, when building the `libSimG4CoreApplication.so` shared library.

Out of the box the order of the 3 Celeritas static libraries is `-lceleritas -lcorecel -laccel`. With this arrangement the linker complains
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02818/slc7_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/../lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../x86_64-redhat-linux-gnu/bin/ld.bfd: tmp/slc7_amd64_gcc12/src/SimG4Core/Application/src/SimG4CoreApplication/cc9rFhUQ.ltrans6.ltrans.o: in function `celeritas::UniformAlongStepFactory::operator()(celeritas::AlongStepFactoryInput const&) const':
<artificial>:(.text+0xf49): undefined reference to `celeritas::world_logger()'
```

I changed the order to `-lceleritas -laccel -lcorecel`, after which the linker error changed to
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02818/slc7_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/../lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../x86_64-redhat-linux-gnu/bin/ld.bfd: /tmp/mkortela/cc8aCxfY.ltrans5.ltrans.o: in function `celeritas::UniformAlongStepFactory::operator()(celeritas::AlongStepFactoryInput const&) const':
<artificial>:(.text+0x6c21): undefined reference to `celeritas::UrbanMscParams::from_import(celeritas::ParticleParams const&, celeritas::MaterialParams const&, celeritas::ImportData const&)'
```

Changing the order to `-laccel -lceleritas -lcorecel` makes the linker to complain on missing OMP symbols along
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02818/slc7_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/../lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../x86_64-redhat-linux-gnu/bin/ld.bfd: /tmp/mkortela/ccrE594H.ltrans7.ltrans.o: in function `celeritas::AlongStepGeneralLinearAction::execute(celeritas::CoreParams const&, celeritas::CoreState<(celeritas::MemSpace)0>&) const':
<artificial>:(.text+0x77ef): undefined reference to `GOMP_parallel'
```
which feels a bit weird. Anyway, adding `-lgomp` manually made the link succeed.

This exercise made me wonder some questions
* Should we disable OpenMP in the Celeritas build?
* For the Celeritas static libraries, do we want to keep them split in 3, or merge them into 1?
   * IIUC "merging into one static library" is what we do with `geant4` and `g4hepem`
* Should we (eventually) provide both dynamic and static libraries for Celeritas, similarly to `geant4` and `g4hepem`?
  * Static library being used in the `biglib`, and dynamic libraries when `biglib` is disabled
* Should we (eventually) change `vecgeom` to the dynamic+static setup as well?
  * I _guess_ before Celeritas `vecgeom` was fine as static library only, as only `geant4` depended on it.
  * Since dynamic linker ignores the duplicate symbols from link-to-static library, keeping `vecgeom` as static should work, with the price of some code bloat (as the `vecgeom` code would get included into both `geant4` and `celeritas` libraries)

**Comment by whokion** [comment]
Thanks @makortel for testing and the summary.  OpenMP can be disable with  adding`-DCELERITAS_USE_OpenMP=OFF`.   I created a branch,  [celeritas-add-shared](https://github.com/whokion/cmsdist/tree/celeritas-add-shared) in the case that adding shared libraries for celeritas is recommended (please see the relevant commit [5a30b2c](https://github.com/whokion/cmsdist/commit/5a30b2c57a030b7692ff6803f702055a6d4cd4df), which has not requested for a PR yet).

**Comment by smuzaffar** [comment]
>     * Should we disable OpenMP in the Celeritas build?

thanks @whokion , I will update the spec to disable the openmp deps
 
>     * For the Celeritas static libraries, do we want to keep them split in 3, or merge them into 1?

we can merge these in to one ( some thing link https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_0_X/master/geant4.spec#L76-L77) or simply fix the order in the celeritas.xml file. I prefer to merge these in to one

>     * Should we (eventually) provide both dynamic and static libraries for Celeritas, similarly to `geant4` and `g4hepem`?

I would prefer only static libraries which should avoid accidentally locding of shared libs via big `Simulation` edm plugin and then have conflicting symbols.

>       * Static library being used in the `biglib`, and dynamic libraries when `biglib` is disabled
> 
>     * Should we (eventually) change `vecgeom` to the dynamic+static setup as well?

I suggest to even drop the shard libs for g4hepem :-)

>       * I _guess_ before Celeritas `vecgeom` was fine as static library only, as only `geant4` depended on it.
>       * Since dynamic linker ignores the duplicate symbols from link-to-static library, keeping `vecgeom` as static should work, with the price of some code bloat (as the `vecgeom` code would get included into both `geant4` and `celeritas` libraries)

In past we had issues with Geant4 symbols in big simulation plugin due to loading of G4 shared libs. So I would prefer to have `vecgeom, g4hepme and Celeritas` as static only

**Comment by smuzaffar** [comment]
@whokion @makortel , I have opened https://github.com/cms-sw/cmsdist/pull/8920 to 
- disable OpenMP 
- fix the lib link order

I also have opened https://github.com/cms-sw/cmssw/pull/43676 ( with the https://github.com/cms-sw/cmsdist/files/13836288/changes-to-SimG4Core.txt changes ) to test it in cmssw

**Pull request merged**
