### PR TITLE
upgrade to pythia8 209

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
Did the the jet matching patch not need to be updated?

**Comment by mkirsano** [comment]
Matching patch worked as is.

**Comment by mkirsano** [comment]
Question to SW people: what was the reason to introduce the compiler option patch adapted here?

**Comment by bendavid** [comment]
What's the reason we don't need --with-boost anymore?

**Comment by mkirsano** [comment]
pythia8 uses lhapdf compatibility/access functions. Boost is not used in the compilation.
Actually it turned out that it was so also in the previous version, but the configure script checked for Boost and did not build lhapdf interface in absence of Boost. This is fixed now.

**Comment by bendavid** [comment]
Ah, ok, I was confused by the release notes, which say 
"Linkage to LHAPDF6 so far has been based on the LHAPDF5 compatibility mode, which requires no Boost headers. The new configure option --with-lhapdf6-plugin=LHAPDF6.h uses native mode, and then requires Boost headers."

So we are still using the compatability mode then?  Is there any advantage moving to native mode?

**Comment by mkirsano** [comment]
In principle there could be some timing advantages. I don't know about such studies.

**Comment by nclopezo** [comment]
+1
tested building cmssw-tool-conf

**Comment by nclopezo** [comment]
@bendavid is this PR ok for you? I would like to confirm before merging it.

**Comment by bendavid** [comment]
Basic tests are ok (identical results on 1000 minbias events)

**Comment by bendavid** [comment]
+1

**Pull request merged**
