### PR TITLE
Update to CUDA 11.2 Update 1

### PR DESCRIPTION
**Pull request by fwyzard**
Update to CUDA 11.2 Update 1 (11.2.1):
  * CUDA runtime version 11.2.142
  * NVIDIA drivers version 460.32.03

Various bug fixes.

See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html .

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
enable GPU

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
