### PR TITLE
Backport gcc630next changes

### PR DESCRIPTION
**Pull request by smuzaffar**
Back ported following changes from 94x/gcc630next in tonormal IBs
- curl: New version 7.51.0 -> 7.52.1
- dmtcp: move to a newer commit and applied dmtcp-remove-git-hooks patch
- gdb: new version  7.12 -> 7.12.1
- geant4data-toolfile: bug fix toolfile
- git: new version 1.8.3.1 ->  2.13.0
- libunwind: new version 1.1 -> 1.2
- llvm: new version 4.0.0 -> 4.0.1
- openldap: new version  2.4.34 ->  2.4.44
- openmpi: enable-mpi-cxx
- sherpa: Updates needed for openmpi
- sqlite: new version  3.15.1 -> 3.16.2
- tbb: new version 2017_20161004oss -> 2017_U6

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@davidlange6 , any objection on getting these changes back on to normal IBs?

**Comment by davidlange6** [comment]
hi @smuzaffar - looks good

**Comment by davidlange6** [comment]
+1

**Pull request merged**
