### PR TITLE
Update cmsmon-tools.spec.

### PR DESCRIPTION
**Pull request by arooshap**
Change the cmsmon-tools tag to incorporate murre and newer version of stern.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@arooshap , this failed to download https://github.com/dmwm/CMSMonitoring/releases/download/0.5.36/cmsmon-tools.tar.gz , are you sure `0.5.36` is correct tag?

**Comment by arooshap** [comment]
@smuzaffar I did not know that the tag is downloaded from there. The issue that we have is that event though the version of stern is set to 1.22 in the spec file, when I do `[apervaiz@lxplus806 ~]$ /cvmfs/cms.cern.ch/cmsmon/stern --version`, it gives me `stern version 1.11.0`, and apparently, the new tool that we have is also not working as expected. For example, if I do, `[apervaiz@lxplus806 ~]$ /cvmfs/cms.cern.ch/cmsmon/murre --version`, it gives me the following error: `ERROR: Unable to find command 'murre' for 'alma8_amd64' architecture.` So, I thought that we might need a new upgrade to the tag in order to reflect the changes-- similar to what we have for cmsweb.

Could you please shed some light on this issue?
`

**Comment by smuzaffar** [comment]
@arooshap , all these `cmsmon` tools use `cmsos` command to find out the cms `os_arch` , I see that on `lxplus806 ` it returns `alma8_amd64` because this is an almalinux8 based node. I will update `cmsos` to map all rhel distros ( alma, rocky, rhel, cs8) to el8. For now you can set `BUILD_ARCH=el8_amd64` to use the latest version [a]. I will let you know once `cmsos` has the proper mapping for el8

[a]
```
[muzaffar@lxplus806 ~]$ BUILD_ARCH=el8_amd64 /cvmfs/cms.cern.ch/cmsmon/stern --version
version: 1.22.0
````

**Comment by arooshap** [comment]
@smuzaffar Thanks a lot for your input. I will close this PR. Please proceed with the update on your own convenience, it's nothing urgent.

Thank you once again.

**Comment by smuzaffar** [comment]
`cmsos` has been updated to properly map `amla8` to `el8`
```
lxplus8> cmsos
el8_amd64
lxplus8> /cvmfs/cms.cern.ch/cmsmon/stern --version
version: 1.22.0
commit: f6f4f640be851ccbd311b609d94a6fdab432d212
built at: 2022-09-27T13:34:04Z
```

**Pull request closed without merging**
