### PR TITLE
Update Alpaka to version 0.6.1

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@fwyzard , looks good to me, do you want to run any other tests?

**Comment by fwyzard** [comment]
I'm running some tests outside of CMSSW (until we move on with the integration of alpaka in CMSSW itself), I'll comment here when I'm done.

**Comment by fwyzard** [comment]
OK, looks good to me.

**Pull request merged**
