### PR TITLE
[12.3.X] added L1TriggerConfig-L1TConfigProducers V00-01-00

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #7823
Move L1TriggerConfig-L1TConfigProducers data to new tag, see
https://github.com/cms-data/L1TriggerConfig-L1TConfigProducers/pull/1

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals
FYI @perrotta , @qliphy 
This has already been tested for master branch and only added new data files. so it is safe to merge it in 12.3.X

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by perrotta** [comment]
Thank you @smuzaffar

**Pull request merged**
