### PR TITLE
Fix Professor2 and update to 2.2.2

### PR DESCRIPTION
**Pull request by mseidel42**
Need to specify `LIBDIR` to find `libProfessor2.so`. Also updated to 2.2.2 then.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , this can be merged. Both professor and professor2 provide separate libs and python packages. Their libs can safely co-exists under LIBDIR.

**Comment by fabiocos** [comment]
+1

@smuzaffar thanks, Professor is a standalone tool that does not enter in production workflows, GEN experts are performing dedicated checks on it

**Pull request merged**
