### PR TITLE
Add new data package for CondTools-SiPhase2Tracker

### PR DESCRIPTION
**Pull request by mrodozov**
Adds new package needed for https://github.com/cms-sw/cmssw/pull/26029
Resolves: https://github.com/cms-sw/cmsdist/issues/4792

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
please test

the failures were unrelated to this PR

**Pull request merged**
