### PR TITLE
Update tag for RecoBTag-Combined to V01-17-00 [CMSSW_13_0_X]

### PR DESCRIPTION
**Pull request by perrotta**
backport of https://github.com/cms-sw/cmsdist/pull/8492 into 13_0_X
To be merged together with https://github.com/cms-sw/cmssw/pull/41434

### CODE REVIEW

**Comment by rappoccio** [comment]
@smuzaffar are the tests stuck for this?

**Comment by smuzaffar** [comment]
+externals
no @rappoccio , we did not test it here. It was tested via https://github.com/cms-sw/cmssw/pull/41434 . Feel freelt o merge it along with https://github.com/cms-sw/cmssw/pull/41434

**Comment by rappoccio** [comment]
+1

**Comment by perrotta** [comment]
merge
(this was needed by #41434, already merged...)

**Pull request merged**
