### PR TITLE
Add fastjet-contrib to rivet-toolfile

### PR DESCRIPTION
**Pull request by mseidel42**
As proposed by @kpedro88

### CODE REVIEW

**Comment by mrodozov** [comment]
allow @intrepid42 test rights

**Comment by mseidel42** [comment]
please test

**Comment by mrodozov** [comment]
github had some issues around the time of the test
https://www.githubstatus.com/
the PR failed because it time outed three times. I restarted the job

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
