### PR TITLE
Update aiohttp to 3.8.1

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
