### PR TITLE
Update dbs3-client to 4.0.4 and dbs3-client-pycurl to 3.17.7

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes https://github.com/dmwm/WMCore/issues/10884
Superseeds https://github.com/cms-sw/cmsdist/pull/7493

Besides having all the changes required for the Go implementation of DBSReader (including aggregation and data streaming), it also has url redirect enabled in RestClient.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 7c9b2f166e968d59c4e2dee3f520a5389b660dda on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7508/test_7c9b2f1-20211214-074002.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@todor-ivanov @belforte @germanfgv @jhonatanamado this tag has a fix to the redirects imposed by the new Go server. 
Some basic tests in the agent and central services are looking fine, we still cannot declare it good to be used in production though and further tests will be performed in testbed later today.

**Comment by amaltaro** [comment]
I'm going to merge it to release a fix for cmsweb-testbed production services.

German/Jhonatan, please do not use this new dbs3-client in production yet, we need to run further tests.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
