### PR TITLE
Fireworks-Geometry: download cmsGeom2026 from cmsrep

### PR DESCRIPTION
**Pull request by smuzaffar**
this should be tested along with https://github.com/cms-data/Fireworks-Geometry/pull/10 and https://github.com/cms-sw/cmssw/pull/29169

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-data/Fireworks-Geometry#10

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
can we merge this with cms-sw/cmssw#29169?

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#29169

**Comment by silviodonato** [comment]
@mrodozov @smuzaffar @tulamor is it ready to be merged?

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
contains only news data files, so we can safely merge it.

**Pull request merged**
