### PR TITLE
[14.1.X] Backport multi-arch chanegs from 15.0.X

### PR DESCRIPTION
**Pull request by smuzaffar**
same as #9572

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by antoniovilela** [comment]
@smuzaffar
Will you need this for 14_1_7?  If so, it would be good to merge today, so that we build tomorrow.

**Comment by smuzaffar** [comment]
@antoniovilela , I would like to get this in for 14.2.X first. 
OK, let me merge https://github.com/cms-sw/cmsdist/pull/9572 for 14.2.X first and I can trigger an IB now and if 14.2.X IB has no issues then I can merge this before 23h00 14.1.X IB

**Comment by antoniovilela** [comment]
> @antoniovilela , I would like to get this in for 14.2.X first. OK, let me merge #9572 for 14.2.X first and I can trigger an IB now and if 14.2.X IB has no issues then I can merge this before 23h00 14.1.X IB

Sounds good

**Comment by smuzaffar** [comment]
+externals

14.2.X IB looks good so lets merge this for 14.1.X

**Comment by antoniovilela** [comment]
@smuzaffar 
Hi Shahzad, do you understand why we started having the unit test failure from FWCore/Integration ?

**Comment by smuzaffar** [comment]
@antoniovilela , no idea but I am looking in to it

**Comment by antoniovilela** [comment]
> @antoniovilela , no idea but I am looking in to it

Many thankks. We will wait a bit, before we launch the 14_2 & 15_0 builds.

**Comment by smuzaffar** [comment]
I think https://github.com/cms-sw/cmssw-config/commit/91e7bf620361fad2a8427d018e8839c50c183263 change broke the python impor. I am reverting that change . Change was needed for runing edm class check during patch release built. We have a work around for that https://github.com/cms-sw/cmssw/pull/46922 . Can you please integrate https://github.com/cms-sw/cmssw/pull/46922 . 

I will revert the https://github.com/cms-sw/cmssw-config/commit/91e7bf620361fad2a8427d018e8839c50c183263 foo all release cycles 14.1 and above

**Comment by antoniovilela** [comment]
> I think [cms-sw/cmssw-config@91e7bf6](https://github.com/cms-sw/cmssw-config/commit/91e7bf620361fad2a8427d018e8839c50c183263) change broke the python impor. I am reverting that change . Change was needed for runing edm class check during patch release built. We have a work around for that [cms-sw/cmssw#46922](https://github.com/cms-sw/cmssw/pull/46922) . Can you please integrate [cms-sw/cmssw#46922](https://github.com/cms-sw/cmssw/pull/46922) .
> 
> I will revert the [cms-sw/cmssw-config@91e7bf6](https://github.com/cms-sw/cmssw-config/commit/91e7bf620361fad2a8427d018e8839c50c183263) foo all release cycles 14.1 and above

https://github.com/cms-sw/cmssw/pull/46922 is merged.

Ok, we will wait for the revert.

**Comment by smuzaffar** [comment]
@makortel , https://github.com/cms-sw/cmssw-config/commit/91e7bf620361fad2a8427d018e8839c50c183263 change was using the realpath of imported python package. This was done so that edm class check script can import `FWCore.Reflection.ClassesDefXmlUtils` during the build phase of patch release. This change broke `TestIntegrationParameterSet` unit test. Here is what python directory looks like in patch release

- If FWCore is not part of patch release then we create symlink `cmssw-patch/python/FWCore` pointing to full release 
```
cmssw-patch/python/FWCore  -- symlink to --> cmssw/python/FWCore
```

- if FWCore is part of patch release then we create `cmssw-patch/python/FWCore` directory and create symlink for Integration
```
cmssw-patch/python/FWCore/Integration  -- symlink to --> cmssw/python/FWCore/Integration
```

After the cmssw-config update for python imports, in patch releases , imported python module path starts with

- CMSSW_FULL_RELEASE_BASE: If package is not part of patch release
- CMSSW_RELEASE_BASE: If package is part of patch release
- CMSSW_BASE: In devel area, if patch was locally checkout

The reason unit test https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_0_X_2024-12-13-1100/unitTestLogs/FWCore/Integration#/3356-3356 start failing was that https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/python/Config.py#L55  only allows CMSSW_RELEASE_BASE and CMSSW_BASE. For now I have reverted the cmssw-config change. But do you think we should update https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/python/Config.py#L55 and also allow CMSSW_FULL_RELEASE_BASE ?

**Comment by smuzaffar** [comment]
I have opened a cmssw issue for this

**Pull request merged**
