### PR TITLE
[ROOTMaster] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
@iarspider , looks like we need cmssw change for https://github.com/cms-sw/cmssw/blob/master/RecoVertex/BeamSpotProducer/interface/BSpdfsFcn.h to go with root master

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/45965

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/45965 for CMSSW_14_2_ROOT6_X

**Comment by iarspider** [comment]
@cmsbuild ping

**Comment by iarspider** [comment]
`ROOT::Minuit2::ModularFunctionMinimizer::Minimize(ROOT::Minuit2::FCNBase const&, std::vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> > const&, unsigned int, unsigned int, double) const`

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/45965 for CMSSW_14_2_ROOT6_X

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/45965 for CMSSW_14_2_ROOT6_X

**Comment by smuzaffar** [comment]
closing in favor of #9399

**Pull request closed without merging**
