### PR TITLE
Update hwloc to version 2.10.0

### PR DESCRIPTION
**Pull request by fwyzard**
See https://raw.githubusercontent.com/open-mpi/hwloc/v2.10/NEWS for the changes in this version.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
enable gpu

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
looks good ( ` testTFVisibleDevicesCUDA ` is failing for GPU IBs due to missing TF cuda support)

**Pull request merged**
