### PR TITLE
Use root 5.34.17 in stable branch

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidlt** [comment]
Does our fork of ROOT5 has all patches from SPEC? I see that ARMv7 changes were reverted? Could we have ARMv7 patch back in SPEC?

**Comment by ktf** [comment]
> Does our fork of ROOT5 has all patches from SPEC? I see that ARMv7 
> changes were reverted? Could we have ARMv7 patch back in SPEC?

Can you add the ARM changes with ARM specific ifdefs so that we do not 
need a special patch / branch for it? Just do a new pull request to the 
cms/root-5.34.17 branch in cms-sw/root.

## 

Ciao,
Giulio

**Comment by davidlt** [comment]
I have multiple versions of the patch. One of them is less invasive, I will try to look it up.

**Comment by ktf** [comment]
thanks.

**Comment by davidlt** [comment]
Could you remove all unneeded ROOT patches from CMSDIST?
I created a pull request for cms-sw/root#8 for ARMv7 support with different trampolines implementation. Almost finished compile test on armv7hl.
Also the following lines should be no more needed (seems that you already have this file committed):

```
%if %isarmv7
cp ./cint/iosenum/iosenum.linux3 ./cint/iosenum/iosenum.linuxarm3
%endif
```

```
$ file  ./cint/iosenum/iosenum.linuxarm3
./cint/iosenum/iosenum.linuxarm3: ASCII c program text
```

**Comment by ktf** [comment]
> Could you remove all unneeded ROOT patches from CMSDIST?

Yes. I've done it in #580.

**Comment by davidlt** [comment]
Thanks.

Will you update root.spec to include ARMv7 support (and remove iosenum.linuxarm3 lines) or should I do it?

**Comment by ktf** [comment]
I've applied you pull request. Is there more? If yes, can you do a pull request please?

**Comment by davidlt** [comment]
Well, we need to update root.spec to build against new hash to get this in `CMSSW_7_1_X/stable`. I will do it.

**Pull request merged**
