### PR TITLE
[TF] Updating TF 2.15.0 which supports CUDA 12

### PR DESCRIPTION
**Pull request by smuzaffar**
Update TF to 2.15.0-rc1 tag which supports CUDA 12.2

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test

latest changes should fix the unit tests ( at least locally I can run `import tf; import keras` )

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
enable gpu

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
@fwyzard , any idea on these GPU unit tests [a] failures?

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b75e6c/36066/gpuUnitTests/src/RecoTracker/PixelTrackFitting/test/testBrokenLineFitGPU_t/testing.log
```
Eigen::internal::variable_if_dynamic<T, Value>::variable_if_dynamic(T) [with T = long; int Value = 3]: block: [29,0,0], thread: [62,0,0] Assertion `v == T(Value)` failed.
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/eigen/aa6964bf3a34fd607837dd8123bc42465185c4f8-0dbec0072195e50e4de1a0d4e91d47c7/include/eigen3/Eigen/src/Core/util/XprHelper.h:157: Eigen::internal::variable_if_dynamic<T, Value>::variable_if_dynamic(T) [with T = long; int Value = 3]: block: [29,0,0], thread: [63,0,0] Assertion `v == T(Value)` failed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-26-0000/src/RecoTracker/PixelTrackFitting/test/testEigenGPU.cu, line 264:
cudaCheck(cudaMemcpy(fast_fit_resultsGPUret, fast_fit_resultsGPU, riemannFit::maxNumberOfTracks() * sizeof(Vector4d), cudaMemcpyDeviceToHost));
cudaErrorAssert: device-side assert triggered
/bin/sh: line 1: 1719154 Aborted                 (core dumped) sh -c 'testBrokenLineFitGPU_t '
```

**Comment by smuzaffar** [comment]
assign reconstruction
@cms-sw/reconstruction-l2 , this PR updated tensorflow to 2.15.0 which has cuda 12 support. Can you please review this specially the DQM/Reco comparison changes ?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
> ##
> 
> I found 2 errors in the following unit tests:
> 
> ---> test testBrokenLineFitGPU_t had ERRORS
> ---> test testFitsGPU_t had ERRORS

Are these tests working in the IBs ?

**Comment by smuzaffar** [comment]
yes e.g. see https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_GPU_X_2023-12-05-2300/unitTestLogs/RecoTracker/PixelTrackFitting#/2-2

**Comment by fwyzard** [comment]
OK, so it's really the TF update that breaks them ?

**Comment by smuzaffar** [comment]
these tests do not use TF, so I think it is eigen update which broke these tests

**Comment by fwyzard** [comment]
Ah... I was thinking that the tests might be running at the same time as some other job that does use TF.
But if there are changes to Eigen, sure, it's a real possibility.

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
> ## GPU Unit Tests
> 
> I found 2 errors in the following unit tests:
> 
> ---> test testBrokenLineFitGPU_t had ERRORS
> ---> test testFitsGPU_t had ERRORS

@smuzaffar do these tests pass in the regular IBs ?

**Comment by smuzaffar** [comment]
yes @fwyzard they do. Note that we also have updated `eigen` in the PR (needed by new TF)

**Comment by fwyzard** [comment]
> yes @fwyzard they do. Note that we also have updated `eigen` in the PR (needed by new TF)

Yes, I noticed 🤷🏻‍♂️

**Comment by gartung** [comment]
@smuzaffar Tensorflow v2.15.0 without gpu support been built recently? I want to look at the dependencies of the libraries with ldd.

**Comment by smuzaffar** [comment]
@gartung , no not recently. lt me fix the conflicts here and restart the tests

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung , TF 2.15 is available (here)(/cvmfs/cms-ci.cern.ch/week1/PR_66d7f335/el8_amd64_gcc12/external/tensorflow/2.15.0-9227157101a3a3331f478e110f8c3f3e)

**Comment by smuzaffar** [comment]
lers merge it for dedicated TF branch

**Pull request merged**
