### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
test parameters:
- pull_requests = cms-sw/cmssw#44328
- release = CMSSW_14_1_ROOT6_X

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by guitargeek** [comment]
Fingers crossed!

**Comment by makortel** [comment]
```
A fatal system signal has occurred: floating point exception

#3  0x0000152abc1c7730 in sig_dostack_then_abort () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/lib/el8_amd64_gcc12/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000152a69785af6 in RooBatchCompute::AVX2::RooBatchComputeClass::compute(RooBatchCompute::Config const&, RooBatchCompute::Computer, double*, unsigned long, std::__ROOT::span<std::__ROOT::span<double const> const>, std::__ROOT::span<double>) () from /cvmfs/cms-ci.cern.ch/week1/PR_362c25e6/el8_amd64_gcc12/lcg/root/6.31.01-d42a9edd92e845afeb787d4a3967d55a/lib/libRooBatchCompute_AVX2.so
#6  0x0000152a6e9a053d in RooBreitWigner::computeBatch(double*, unsigned long, RooFit::Detail::DataMap const&) const () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFit.so
#7  0x0000152a6e492ea2 in RooFit::Evaluator::computeCPUNode(RooAbsArg const*, RooFit::NodeInfo&) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFitCore.so
#8  0x0000152a6e493641 in RooFit::Evaluator::run() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFitCore.so
#9  0x0000152a6e46d415 in RooEvaluatorWrapper::getValV(RooArgSet const*) const () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFitCore.so
#10 0x0000152a6e51a35a in RooMinimizerFcn::operator()(double const*) const () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFitCore.so
#11 0x0000152ac773820f in ROOT::Math::Functor::DoEval(double const*) const () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libMathCore.so
#12 0x0000152a719ca40e in ROOT::Minuit2::MnUserFcn::operator()(ROOT::Minuit2::LAVector const&) const () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libMinuit2.so
#13 0x0000152a719c6883 in ROOT::Minuit2::MnSeedGenerator::operator()(ROOT::Minuit2::MnFcn const&, ROOT::Minuit2::GradientCalculator const&, ROOT::Minuit2::MnUserParameterState const&, ROOT::Minuit2::MnStrategy const&) const () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libMinuit2.so
#14 0x0000152a719d1d40 in ROOT::Minuit2::ModularFunctionMinimizer::Minimize(ROOT::Minuit2::FCNBase const&, ROOT::Minuit2::MnUserParameterState const&, ROOT::Minuit2::MnStrategy const&, unsigned int, double) const () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libMinuit2.so
#15 0x0000152a719920f5 in ROOT::Minuit2::Minuit2Minimizer::Minimize() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libMinuit2.so
#16 0x0000152ac7792f4e in ROOT::Fit::Fitter::DoMinimization(ROOT::Math::IBaseFunctionMultiDimTempl<double> const*) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libMathCore.so
#17 0x0000152a6e515ce6 in RooMinimizer::minimize(char const*, char const*) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFitCore.so
#18 0x0000152a6e334ce6 in RooFit::FitHelpers::minimize(RooAbsReal&, RooAbsReal&, RooAbsData const&, RooCmdConfig const&) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFitCore.so
#19 0x0000152a6e33c963 in RooFit::FitHelpers::fitTo(RooAbsReal&, RooAbsData&, RooLinkedList const&, bool) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFitCore.so
#20 0x0000152a6e3a3d6c in RooAbsPdf::fitToImpl(RooAbsData&, RooLinkedList const&) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/external/el8_amd64_gcc12/lib/libRooFitCore.so
#21 0x0000152a6eb8d295 in PhotonDataCertification::invMassZtest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TString, dqm::implementation::IGetter&) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/lib/el8_amd64_gcc12/pluginDQMOfflineEGammaPlugins.so
#22 0x0000152a6eb8d812 in PhotonDataCertification::dqmEndJob(dqm::implementation::IBooker&, dqm::implementation::IGetter&) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/lib/el8_amd64_gcc12/pluginDQMOfflineEGammaPlugins.so
#23 0x0000152a6eb5b6d9 in non-virtual thunk to DQMEDHarvester::endProcessBlockProduce(edm::ProcessBlock&) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/lib/el8_amd64_gcc12/pluginDQMOfflineEGammaPlugins.so
#24 0x0000152ac7f43b7b in edm::one::EDProducerBase::doEndProcessBlock(edm::ProcessBlockPrincipal const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9047/37927/CMSSW_14_1_ROOT6_X_2024-03-05-2300/lib/el8_amd64_gcc12/libFWCoreFramework.so
```

on `Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz`

**Comment by guitargeek** [comment]
Should be fixed now. Thanks for bearing with me on this RooFit change here! It's indeed quite a large change for RooFit, this was not unexpected to me (although I validated the new code over years to be confident that it can be the default).

**Comment by iarspider** [comment]
Superseeded by https://github.com/cms-sw/cmsdist/pull/9056 .

**Pull request closed without merging**
