### PR TITLE
[ROOT master] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- enable_test = threading
- pull_request = cms-sw/cmssw#36903

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_ROOT6_X

**Comment by guitargeek** [comment]
Just for the record if you see these RooFit errors again: https://github.com/cms-sw/cmssw/pull/36903#issuecomment-1032020817

Sorry again for breaking things with new compile-time restrictions :slightly_smiling_face:

**Pull request merged**
