### PR TITLE
[ROOT] 6-22 fix for geometry unit test

### PR DESCRIPTION
**Pull request by mrodozov**
test parameters:
- pull_request=cms-sw/cmssw#32000

### CODE REVIEW

**Comment by mrodozov** [comment]
please test
fixes this issue: https://github.com/cms-sw/cmssw/issues/31194

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
lets get this in IBs. This includes 3 extra commits on top of existing root
- [cling] Force char-signedness of host. Fixes root-project#6465.
- Fix for copying title to cloned volumes and nodes.
- Clone also name in the reflected shape.

**Comment by smuzaffar** [comment]
+externals

**Comment by civanch** [comment]
@smuzaffar , thanks!

**Pull request merged**
