### PR TITLE
build py2-Pygments which is needed by dxr; treat .icc as cpp files

### PR DESCRIPTION
**Pull request by smuzaffar**
DXR which needs py2-Pygments is only available for Python2. Python3 support seems unlikely ( https://github.com/mozilla/dxr/issues/704 ) . So for now, we add back py2-Pygments  and also patch dxr and Pygments  to treat our `.icc` files as `c++` files

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
so what is the longer term plan - or does dxr in cmssw end in a few months?

**Comment by smuzaffar** [comment]
looks like porting it to py3 should be easy ( at least that what DXR developer say) but as DXR is not actively developed so I am thinking of replacing it with searchFox ( which is what mozilla is moving to)

**Pull request merged**
