### PR TITLE
Update root master

### PR DESCRIPTION
**Pull request by mrodozov**
TF1 version now changes to 12, see https://github.com/root-project/root/pull/7274

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@davidlange6 could this have anything to do with your latest work in https://github.com/cms-sw/cmssw/pull/33014 ?
I'm asking before dig in

**Comment by davidlange6** [comment]
no. But it looks related to errors I posted to the core Mattermost last week (the Hash<ParameterSetType>). Perhaps @Axel-Naumann is already looking at something similar
(https://github.com/cms-sw/cmssw/blob/master/DataFormats/Provenance/interface/HashedTypes.h)

```
Leaving library rule at src/RecoRomanPot/RecoFP420/plugins
@@@@ Running edmWriteConfigs for RecoRomanPotRecoFP420Plugins
DataFormatsProvenance_xr dictionary forward declarations' payload:56:28: error: use of undeclared identifier 'ParameterSetType'
namespace edm{typedef Hash<ParameterSetType> ParameterSetID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/ParameterSetID.h")))  __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/BranchDescription.h"))) ;}
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:57:28: error: use of undeclared identifier 'ParentageType'
namespace edm{typedef Hash<ParentageType> ParentageID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/ParentageID.h")))  __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/BranchDescription.h"))) ;}
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:58:28: error: use of undeclared identifier 'ProcessHistoryType'
namespace edm{typedef Hash<ProcessHistoryType> ProcessHistoryID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/ProcessHistoryID.h")))  __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/BranchDescription.h"))) ;}
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:59:28: error: use of undeclared identifier 'ProcessConfigurationType'
namespace edm{typedef Hash<ProcessConfigurationType> ProcessConfigurationID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/ProcessConfigurationID.h")))  __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/BranchDescription.h"))) ;}
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:60:28: error: use of undeclared identifier 'EntryDescriptionType'
namespace edm{typedef Hash<EntryDescriptionType> EntryDescriptionID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/EntryDescriptionID.h")))  __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/EventEntryInfo.h"))) ;}
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:61:28: error: use of undeclared identifier 'ModuleDescriptionType'
namespace edm{typedef Hash<ModuleDescriptionType> ModuleDescriptionID;}
                           ^
edmWriteConfigs: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01-d0520f36b3c94cb8dcdd42bbef260b92/root-6.23.01/interpreter/cling/lib/Interpreter/Transaction.cpp:136: void cling::Transaction::append(cling::Transaction::DelayCallInfo): Assertion `getState() == kCollecting && "Cannot append declarations in current state."' failed.
```

**Comment by mrodozov** [comment]
Hm, so it's not ROOT (root builds) but it's ROOT (comes from root). I'll check it :)

**Comment by Axel-Naumann** [comment]
Any chance that that I can see the `DataFormatsProvenance_xr` dictionary as generated?

**Comment by davidlange6** [comment]
This is not from today’s report, but I had a similar errors last week (eg, the 26th)

https://gist.github.com/davidlange6/dcce3b468220378910c8f463b6d5e598
https://gist.github.com/davidlange6/41f534e1eb81f438b5f73686cbfcecd3

**Comment by mrodozov** [comment]
So we have the second:
https://reviews.llvm.org/D36368?id=109963
of four updates but since then this part of llvm has changed and now the context of this last change is very different
Anyway, I'll try to get the last update later and see if it helps

**Comment by Axel-Naumann** [comment]
In my reproducer I get the following warnings:
```
Warning: Forward declarations of templates with enums as template parameters. The responsible class is: NonTypeTemplateParmDecl 0x55d9c8152fb0 </home/axel/build/tmp/CMS-typedef-template-args-fwd-decl/cl1.h:9:11, col:16> col:16 'cl1::Enum' depth 0 index 0 E

Warning: Problems with arguments for forward declaration of class Template
```
Can you confirm that you get those when generating the relevant dictionaries?

**Comment by davidlange6** [comment]
My working area broken it seems - I’m rebuilding with debug root and more recent commits.. So I can answer in the morning. Maybe Mircho knows from his side?

**Comment by mrodozov** [comment]
What I was doing was try build the latest commits on this LLVM issue and then build cmssw so - not yet :/ Without much success
Because this is failing with the same LLVM commit (regardless where we take it from) I don't expect it will work as it is unless we change something so I was trying to get this new commits from the issue and see if this helps - before going and try to figure it what this code actually does (last resort to do it without thinking :D )

**Comment by davidlange6** [comment]
I think Axel is looking for some Information from logs - I just happen not to have it - you don’t have the log from the initial failure still?

**Comment by mrodozov** [comment]
I figured it I'm searching the logs :)

**Comment by mrodozov** [comment]
running 
grep -r "Forward declarations" jenkins-artifacts/pull-request-integration/PR-1e32a3/13181/
doesn't return anything. how did you get this warning Axel ? I'll run the build anyway to check but I think all warnings should be in the logs already in
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1e32a3/13181/
You can also see 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1e32a3/13181/build-logs/
which is compilation warnings (from cmssw)

**Comment by davidlange6** [comment]
My build got far enough to check - I also don’t see this message. Maybe we are suppressing it, but I don’t think so 

>>> import ROOT 
ROOT.gSystem.Load("libDataFormatsProvenance.so")
>>> ROOT.gSystem.Load("libDataFormatsProvenance.so")

Is enough - maybe I can put everything into a standalone directory (but not tonight, so tomorrow..)

```
python -c 'import ROOT; ROOT.gSystem.Load("libDataFormatsProvenance.so")'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: File "/dlange/210304/slc7_amd64_gcc900/lcg/root/6.23.01/lib/libCore.so-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /dlange/210304/slc7_amd64_gcc900/lcg/root/6.23.01/lib/libCore.so-gdb.py
line to your configuration file "/afs/cern.ch/user/d/dlange/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/afs/cern.ch/user/d/dlange/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
warning: File "/dlange/210304/slc7_amd64_gcc900/external/gcc/9.3.0/lib64/libstdc++.so.6.0.28-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
[Detaching after fork from child process 177643]
[Detaching after fork from child process 177645]
[Detaching after fork from child process 177718]
[Detaching after fork from child process 177720]
[Detaching after fork from child process 180825]
[Detaching after fork from child process 180827]
[Detaching after fork from child process 180831]
[Detaching after fork from child process 180877]
DataFormatsProvenance_xr dictionary forward declarations' payload:56:28: error: use of undeclared identifier 'ParameterSetType'
namespace edm{typedef Hash<ParameterSetType> ParameterSetID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/ParameterSetID.h")))  __attribute__((annotate("...
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:57:28: error: use of undeclared identifier 'ParentageType'
namespace edm{typedef Hash<ParentageType> ParentageID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/ParentageID.h")))  __attribute__((annotate("$clingAut...
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:58:28: error: use of undeclared identifier 'ProcessHistoryType'
namespace edm{typedef Hash<ProcessHistoryType> ProcessHistoryID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/ProcessHistoryID.h")))  __attribute__((anno...
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:59:28: error: use of undeclared identifier 'ProcessConfigurationType'
namespace edm{typedef Hash<ProcessConfigurationType> ProcessConfigurationID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/ProcessConfigurationID.h")))  _...
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:60:28: error: use of undeclared identifier 'EntryDescriptionType'
namespace edm{typedef Hash<EntryDescriptionType> EntryDescriptionID __attribute__((annotate("$clingAutoload$DataFormats/Provenance/interface/EntryDescriptionID.h")))  __attribute__...
                           ^
DataFormatsProvenance_xr dictionary forward declarations' payload:61:28: error: use of undeclared identifier 'ModuleDescriptionType'
namespace edm{typedef Hash<ModuleDescriptionType> ModuleDescriptionID;}
                           ^
python: /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/Transaction.cpp:136: void cling::Transaction::append(cling::Transaction::DelayCallInfo): Assertion `getState() == kCollecting && "Cannot append declarations in current state."' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6f113d7 in raise () from /lib64/libc.so.6
(gdb) where
#0  0x00007ffff6f113d7 in raise () from /lib64/libc.so.6
#1  0x00007ffff6f12ac8 in abort () from /lib64/libc.so.6
#2  0x00007ffff6f0a1a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff6f0a252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fffed0578f2 in cling::Transaction::append (this=0x5211820, DCI=...)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/Transaction.cpp:136
#5  0x00007fffed234c85 in cling::DeclCollector::HandleInterestingDecl (this=0x5840c0, DGR=...)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/DeclCollector.cpp:255
#6  0x00007fffedc78f08 in clang::ASTReader::PassInterestingDeclToConsumer (this=0x58cc00, D=0x556cf00)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:8104
#7  0x00007fffedd2062e in clang::ASTReader::PassInterestingDeclsToConsumer (this=0x58cc00)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReaderDecl.cpp:4031
#8  0x00007fffedc8d5bb in clang::ASTReader::FinishedDeserializing (this=0x58cc00)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:12156
#9  0x00007fffedc9766f in clang::ExternalASTSource::Deserializing::~Deserializing (this=0x7fffffff3ba8, __in_chrg=<optimized out>)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/include/clang/AST/ExternalASTSource.h:89
#10 0x00007fffedd20477 in clang::ASTReader::ReadDeclRecord (this=0x58cc00, ID=664850)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReaderDecl.cpp:3696
#11 0x00007fffedc77c1e in clang::ASTReader::GetDecl (this=0x58cc00, ID=664850)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:7856
#12 0x00007fffedc76a32 in clang::ASTReader::GetExternalDecl (this=0x58cc00, ID=664850)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:7571
#13 0x00007fffed0429f1 in cling::ExternalASTSourceWrapper::GetExternalDecl (this=0x5ceff0, ID=664850)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/InterpreterCallbacks.cpp:115
#14 0x00007fffede34016 in clang::MultiplexExternalSemaSource::GetExternalDecl (this=0x5dad50, ID=664850)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/Sema/MultiplexExternalSemaSource.cpp:44
#15 0x00007ffff0804ca6 in clang::RedeclarableTemplateDecl::loadLazySpecializationImpl (this=0x511b5a8, LazySpecInfo=...)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/AST/DeclTemplate.cpp:211
#16 0x00007ffff0804c11 in clang::RedeclarableTemplateDecl::loadLazySpecializationsImpl (this=0x511b5a8, OnlyPartial=false)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/AST/DeclTemplate.cpp:200
#17 0x00007ffff0805511 in clang::ClassTemplateDecl::LoadLazySpecializations (this=0x511b5a8, OnlyPartial=false)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/AST/DeclTemplate.cpp:405
#18 0x00007ffff0805531 in clang::ClassTemplateDecl::getSpecializations (this=0x511b5a8)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/lib/AST/DeclTemplate.cpp:410
#19 0x00007fffeccecf38 in clang::ClassTemplateDecl::spec_begin (this=0x511b5a8)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/llvm/src/tools/clang/include/clang/AST/DeclTemplate.h:2326
#20 0x00007fffed0bf09e in cling::DeclUnloader::VisitClassTemplateDecl (this=0x7fffffff4260, CTD=0x511b5a8)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/DeclUnloader.cpp:962
#21 0x00007fffed050214 in clang::declvisitor::Base<std::add_pointer, cling::DeclUnloader, bool>::Visit (this=0x7fffffff4260, D=0x511b5a8)
    at interpreter/llvm/src/tools/clang/include/clang/AST/DeclNodes.inc:201
#22 0x00007fffed0be559 in cling::DeclUnloader::VisitDeclContext (this=0x7fffffff4260, DC=0x511b2b8)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/DeclUnloader.cpp:729
#23 0x00007fffed0be61f in cling::DeclUnloader::VisitNamespaceDecl (this=0x7fffffff4260, NSD=0x511b288)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/DeclUnloader.cpp:737
#24 0x00007fffed0500f4 in clang::declvisitor::Base<std::add_pointer, cling::DeclUnloader, bool>::Visit (this=0x7fffffff4260, D=0x511b288)
--Type <RET> for more, q to quit, c to continue without paging--
    at interpreter/llvm/src/tools/clang/include/clang/AST/DeclNodes.inc:105
#25 0x00007fffed04df07 in cling::DeclUnloader::UnloadDecl (this=0x7fffffff4260, D=0x511b288)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/DeclUnloader.h:65
#26 0x00007fffed05a70b in cling::TransactionUnloader::unloadDeclarations (this=0x7fffffff42e0, T=0x5211820, DeclU=...)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/TransactionUnloader.cpp:53
#27 0x00007fffed05aad4 in cling::TransactionUnloader::RevertTransaction (this=0x7fffffff42e0, T=0x5211820)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/TransactionUnloader.cpp:119
#28 0x00007fffed02ecf5 in cling::Interpreter::unload (this=0x4c4000, T=...)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/Interpreter.cpp:1533
#29 0x00007fffed1747e9 in cling::IncrementalParser::commitTransaction (this=0x583b10, PRT=..., ClearDiagClient=true)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/IncrementalParser.cpp:546
#30 0x00007fffed175291 in cling::IncrementalParser::Compile (this=0x583b10, input=..., Opts=...)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/IncrementalParser.cpp:769
#31 0x00007fffed02dfd9 in cling::Interpreter::DeclareInternal (this=0x4c4000, input=..., CO=..., T=0x7fffffff47e8)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/Interpreter.cpp:1336
#32 0x00007fffed02cbf2 in cling::Interpreter::declare (this=0x4c4000, input=..., T=0x7fffffff47e8)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/interpreter/cling/lib/Interpreter/Interpreter.cpp:968
#33 0x00007fffece1b896 in TCling::RegisterModule (this=0x56f370, modulename=0x7fffd88b155b "DataFormatsProvenance_xr", 
    headers=0x7fffd88dbac0 <(anonymous namespace)::TriggerDictionaryInitialization_DataFormatsProvenance_xr_Impl()::headers>, 
    includePaths=0x7fffd88dba60 <(anonymous namespace)::TriggerDictionaryInitialization_DataFormatsProvenance_xr_Impl()::includePaths>, 
    payloadCode=0x7fffd88ae247 "\n#line 1 \"DataFormatsProvenance_xr dictionary payload\"\n\n#ifndef CMS_DICT_IMPL\n  #define CMS_DICT_IMPL 1\n#endif\n#ifndef _REENTRANT\n  #define _REENTRANT 1\n#endif\n#ifndef GNUSOURCE\n  #define GNUSOURCE 1\n"..., 
    fwdDeclsCode=0x7fffd88af3e8 "\n#line 1 \"DataFormatsProvenance_xr dictionary forward declarations' payload\"\n#pragma clang diagnostic ignored \"-Wkeyword-compat\"\n#pragma clang diagnostic ignored \"-Wignored-attributes\"\n#pragma clang d"..., triggerFunc=0x7fffd88613b8 <(anonymous namespace)::TriggerDictionaryInitialization_DataFormatsProvenance_xr_Impl()>, 
    fwdDeclsArgToSkip=..., classesHeaders=0x7fffd88db440 <(anonymous namespace)::TriggerDictionaryInitialization_DataFormatsProvenance_xr_Impl()::classesHeaders>, lateRegistration=false, 
    hasCxxModule=false) at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/core/metacling/src/TCling.cxx:2191
#34 0x00007ffff69c6f51 in TROOT::RegisterModule (modulename=0x7fffd88b155b "DataFormatsProvenance_xr", 
    headers=0x7fffd88dbac0 <(anonymous namespace)::TriggerDictionaryInitialization_DataFormatsProvenance_xr_Impl()::headers>, 
    includePaths=0x7fffd88dba60 <(anonymous namespace)::TriggerDictionaryInitialization_DataFormatsProvenance_xr_Impl()::includePaths>, 
    payloadCode=0x7fffd88ae247 "\n#line 1 \"DataFormatsProvenance_xr dictionary payload\"\n\n#ifndef CMS_DICT_IMPL\n  #define CMS_DICT_IMPL 1\n#endif\n#ifndef _REENTRANT\n  #define _REENTRANT 1\n#endif\n#ifndef GNUSOURCE\n  #define GNUSOURCE 1\n"..., 
    fwdDeclCode=0x7fffd88af3e8 "\n#line 1 \"DataFormatsProvenance_xr dictionary forward declarations' payload\"\n#pragma clang diagnostic ignored \"-Wkeyword-compat\"\n#pragma clang diagnostic ignored \"-Wignored-attributes\"\n#pragma clang d"..., triggerFunc=0x7fffd88613b8 <(anonymous namespace)::TriggerDictionaryInitialization_DataFormatsProvenance_xr_Impl()>, 
    fwdDeclsArgToSkip=..., classesHeaders=0x7fffd88db440 <(anonymous namespace)::TriggerDictionaryInitialization_DataFormatsProvenance_xr_Impl()::classesHeaders>, hasCxxModule=false)
    at /dlange/210304/BUILD/slc7_amd64_gcc900/lcg/root/6.23.01/root-6.23.01/core/base/src/TROOT.cxx:2561

```

**Comment by Axel-Naumann** [comment]
These messages are emitted during dictionary generation. If you don't see them there I need to reproduce the issue in situ, where I might need help from Vassil, Oksana, or Philippe. Can you confirm that you do not see this warning during dictionary generation?
________________________________

**Comment by davidlange6** [comment]
They aren’t in our logs during dictionary generation - but we should explicitly check we aren’t suppressing them

**Comment by Axel-Naumann** [comment]
https://github.com/cms-sw/cmssw-config/blob/ef9d787cad2b4af040256fb0e14bbe7540a55351/SCRAM/GMake/Makefile.lcgdict#L34 looks good to me. I'll ask our CMSSW experts for help!

**Comment by davidlange6** [comment]
But the exit code from rootclog is indeed 0....

On Mar 4, 2021 9:03 PM, David Lange <notifications@github.com> wrote:

They aren’t in our logs during dictionary generation - but we should explicitly check we aren’t suppressing them

**Comment by pcanal** [comment]
Where can I find this build (and/or how can I reproduce it)?

**Comment by mrodozov** [comment]
You can use this for reproducing the build
`/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/6690/13181/install.sh`
use an of the cmsdev machines, once it's setup run
`scram b -j 16`
if you mean the build by David

**Comment by pcanal** [comment]
@mrodozov thanks.

**Comment by Axel-Naumann** [comment]
Thanks everyone! Update: I can now reproduce it, it being the real thing. (No, there's no warning.) Debugging...

**Comment by davidlange6** [comment]
hi @Axel-Naumann , all - I tested your PR (root-project/root#7389) with cmssw - everything builds and at least one simple workflow that I tried runs. So this looks ready to try in our IB this week. Thanks!

**Comment by mrodozov** [comment]
please test
lets try it

**Comment by mrodozov** [comment]
closing this, see #6704

**Pull request closed without merging**
