### PR TITLE
Changed the sherpa2.spec and toolfile to implement the newest sherpa ver...

### PR DESCRIPTION
**Pull request by thuer**
Update the Sherpa2 toolfile to the new version 2.1.0 of Sherpa
Added a new patchfile for the LHAPDF issue and added fastjet support in the configure step
Keep in mind, that either sherpa or sherpa2 has to be chosen, both do not work at the same time since the libraries & variables have the same name.

### CODE REVIEW

**Comment by vciulli** [comment]
sherpa2 should become the new default
Keeping sherpa has available external is an option, but we could just drop it

**Comment by ktf** [comment]
I would vote for just dropping it, if you do not mind.

**Comment by davidlange6** [comment]
me too..

**Comment by ghost** [comment]
Done in #592

**Pull request closed without merging**
