### PR TITLE
New dasgoclient version

### PR DESCRIPTION
**Pull request by vkuznet**
Fix issue https://github.com/dmwm/das2go/issues/30 and support `file dataset=/a/b/c site=XXX run=123` query using Rucio APIs

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
+externals
testign it for production arch is enough as now we get sources for all archs in same buiild

**Pull request merged**
