### PR TITLE
new config tag for generating glimpse indexes for cfipython

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by ghost** [comment]
+1
Tested compilation up to cmssw-tool-conf.

**Comment by ghost** [comment]
@davidlange6 Is this still wanted? Shall we merge it?

**Comment by davidlange6** [comment]
i don't think we need this in 73x. (its already in 74x and 75x, right?)

**Comment by smuzaffar** [comment]
yes it is already in 74X and 75X.
Cheers,
--shahzad

**Pull request closed without merging**
