### PR TITLE
add two new data packages in SimTransport

### PR DESCRIPTION
**Pull request by mrodozov**
Add two new data packages to hold data from sub packages discussed here:
https://github.com/cms-sw/cmssw/pull/24490

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
closing in favor of https://github.com/cms-sw/cmsdist/pull/4515

**Pull request closed without merging**
