### PR TITLE
[10.2.X] Update data-L1Trigger-L1TMuon.spec

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #4365
Testing changes from cms-data/L1Trigger-L1TMuon#16

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@rekovic @thomreis is this still needed?

**Comment by fabiocos** [comment]
@rekovic this looks a remnant of last Fall whose usefulness is unclear to me at this point. Could we just close it or is it needed in 10_2_X? In this case I guess there should be a corresponding CMSSW code.

**Comment by fabiocos** [comment]
@rekovic this looks a remnant of last Fall whose usefulness is unclear to me at this point. Could we just close it or is it needed in 10_2_X? In this case I guess there should be a corresponding CMSSW code.

**Comment by mrodozov** [comment]
@fabiocos  the corr cmssw pr cms-sw/cmssw#24617, the pr itself is closed. I'd suggest you close it, and we reopen it if we have to

**Comment by fabiocos** [comment]
@mrodozov at this point I agree, let's close it for the time being.
@rekovic FYI

**Pull request closed without merging**
