### PR TITLE
Update alpaka to pickup fix for C++20

### PR DESCRIPTION
**Pull request by iarspider**
Backport from #8561, as requested by @smuzaffar

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@fwyzard FYI

**Comment by fwyzard** [comment]
👍🏻

**Comment by smuzaffar** [comment]
please test

any objections @fwyzard on this update? your last [comment](https://github.com/cms-sw/cmsdist/pull/8567#issuecomment-1608976717) is not clear

**Comment by fwyzard** [comment]
my comment was a "thumbs up"... no objections from my side

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
