### PR TITLE
clean up binary moves in python packages 

### PR DESCRIPTION
**Pull request by davidlange6**
No longer needed as python2 packages are gone.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test with  cms-sw/cmssw#35437

**Comment by smuzaffar** [comment]
@davidlange6 , please delete https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_1_X/master/pip/ipython.file#L2 line too

**Comment by smuzaffar** [comment]
@davidlange6 ping

**Comment by davidlange6** [comment]
sorry - missed this.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#35438

**Comment by smuzaffar** [comment]
+externals
Thsi should be merged with  cms-sw/cmssw#35438

**Comment by qliphy** [comment]
+1

**Pull request merged**
