### PR TITLE
Update qgraf to 3.4.2

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
@smuzaffar  Looks like cmsBuild (or rpmbuild) can't handle URLs with login and password. Is it possible to put the code on CMS mirror?

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@iarspider , please test with https://github.com/cms-sw/pkgtools/pull/184 which should be able to download urls with `username:password`

**Comment by iarspider** [comment]
@cmsbuild please test with cms-sw/pkgtools#184

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 , any objections on updating qgraf to version 3.4.2 ?

**Comment by smuzaffar** [comment]
please test

**Comment by SiewYan** [comment]
> @cms-sw/generators-l2 , any objections on updating qgraf to version 3.4.2 ?

I have no objection towards the update.

**Comment by smuzaffar** [comment]
+externals

**Comment by agrohsje** [comment]
One follow-up for @iarspider . Why didn't we move directly to 3.5.0:   http://cfif.ist.utl.pt/~paulo/d.html ?

**Comment by iarspider** [comment]
@agrohsje no special reason, except that 3.4 is declared stable.

**Comment by smuzaffar** [comment]
right, as they mentioned on they website, 3.4 is the only stable version

**Comment by agrohsje** [comment]
Thanks!

**Pull request merged**
