### PR TITLE
Address https://github.com/cms-sw/SCRAM/issues/29

### PR DESCRIPTION
**Pull request by gartung**
https://github.com/cms-sw/SCRAM/issues/29

### CODE REVIEW

**Comment by gartung** [comment]
pending merge of 
https://github.com/cms-sw/cms-common/pull/1

**Comment by gartung** [comment]
@davidlange6 @Dr15Jones

**Comment by gartung** [comment]
This can be tested in an IB build without impacting /cvmfs/cms.cern.ch/common.
The IB builds get installed in /cvmfs/cms-ib.cern.ch. The setup scripts on lxplus use /cvfms/cms.cern.ch/cmsset_default.csh which uses the scram wrapper /cvfms/cms.cern.ch/common/scram. The change to cms-common can be tested by sourcing /cvmfs/cms-ib.cern.ch/cmsset_default.sh and using /cvmfs/cms-ib.cern.ch/common/scram.

**Comment by Feandil** [comment]
Any news on this? We are still hit by this bug :(

**Comment by mrodozov** [comment]
@Feandil https://github.com/cms-sw/cmsdist/pull/4290 
can we close this one now

**Comment by Feandil** [comment]
Sorry, I was away for the last weeks, I'm now getting the ongoing loops and will see if it's reappear, thanks!

**Pull request closed without merging**
