### PR TITLE
Rivet 3.1.10 and Yoda 1.9.10

### PR DESCRIPTION
**Pull request by mseidel42**
Version bump, will provide code updates if necessary

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mseidel42 , looks like patch for first two files in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_1_X/master/rivet-deprecated-warn.patch  are not needed any more. Can you check and update the patch ?

**Comment by smuzaffar** [comment]
@mseidel42 , I think https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_1_X/master/rivet-deprecated-warn.patch also needs cleanup ... right?

**Comment by mseidel42** [comment]
Ah sorry, I saw only the YODA in the log. Reverted the Rivet patches as well, they are all in the main repo now :)

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@mseidel42 , looks like we need cmssw updates to go with this

**Comment by mseidel42** [comment]
Yep, just created the PR :slightly_smiling_face: 

https://github.com/cms-sw/cmssw/pull/43973

**Comment by smuzaffar** [comment]
test parameters:
- pull_requests = https://github.com/cms-sw/cmssw/pull/43973
- workflow = 534.0,536.0
- enable = threading
- workflows_threading = 534.0,536.0

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_DEVEL_X

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
The error actually comes from this new ATLAS analysis, probably just caused by a missing include.
But I am wondering why it was not failing before?

```make
pluginATLAS/ATLAS_2023_I2663725.cc: In member function 'virtual void Rivet::ATLAS_2023_I2663725::init()':
pluginATLAS/ATLAS_2023_I2663725.cc:43:7: error: 'VetoedFinalState' was not declared in this scope; did you mean 'ChargedFinalState'?
   43 |       VetoedFinalState vfs;
      |       ^~~~~~~~~~~~~~~~
      |       ChargedFinalState
pluginATLAS/ATLAS_2023_I2663725.cc:44:7: error: 'vfs' was not declared in this scope; did you mean 'ffs'?
   44 |       vfs.addVetoOnThisFinalState(photon_fs);
      |       ^~~
      |       ffs
pluginATLAS/ATLAS_2023_I2663725.cc:49:24: error: expected ';' before 'hadrons'
   49 |       VetoedFinalState hadrons(FinalState(Cuts::abseta < 4.4));
      |                        ^~~~~~~
pluginATLAS/ATLAS_2023_I2663725.cc:50:7: error: 'hadrons' was not declared in this scope
   50 |       hadrons.addVetoOnThisFinalState(dressedelectron_fs);
      |       ^~~~~~~
In file included from ../include/Rivet/Config/RivetCommon.hh:11,
                 from ../include/Rivet/Analysis.hh:5,
                 from pluginNovosibirsk/SND_2000_I524221.cc:2:
../include/Rivet/Tools/Utils.hh: In function 'std::pair<double, double> Rivet::minmax(const std::vector<double>&, double)':
../include/Rivet/Tools/Utils.hh:778:84: note: parameter passing for argument of type 'std::pair<double, double>' when C++17 is enabled changed to match C++14 in GCC 10.1
  778 |   inline pair<double,double> minmax(const vector<double>& in, double errval=DBL_NAN) {
      |                                                                                    ^
pluginATLAS/ATLAS_2023_I2663725.cc: In member function 'virtual void Rivet::ATLAS_2023_I2663725::analyze(const Rivet::Event&)':
pluginATLAS/ATLAS_2023_I2663725.cc:98:28: error: 'VetoedFinalState' was not declared in this scope; did you mean 'ChargedFinalState'?
   98 |       Particles fs = apply<VetoedFinalState>(event, "isolatedFS").particles();
      |                            ^~~~~~~~~~~~~~~~
      |                            ChargedFinalState
pluginATLAS/ATLAS_2023_I2663725.cc:98:45: error: no matching function for call to 'Rivet::ATLAS_2023_I2663725::apply<<expression error> >(const Rivet::Event&, const char [11])'
   98 |       Particles fs = apply<VetoedFinalState>(event, "isolatedFS").particles();
      |                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
In file included from ../include/Rivet/Projection.hh:6,
                 from ../include/Rivet/Event.hh:7,
                 from ../include/Rivet/Analysis.hh:7:
../include/Rivet/ProjectionApplier.hh:96:5: note: candidate: 'template<class PROJ> std::enable_if_t<std::is_base_of<Rivet::Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::apply(const Rivet::Event&, const Rivet::Projection&) const'
   96 |     apply(const Event& evt, const Projection& proj) const { return applyProjection<PROJ>(evt, proj); }
      |     ^~~~~
../include/Rivet/ProjectionApplier.hh:96:5: note:   template argument deduction/substitution failed:
pluginATLAS/ATLAS_2023_I2663725.cc:98:45: error: template argument 1 is invalid
   98 |       Particles fs = apply<VetoedFinalState>(event, "isolatedFS").particles();
      |                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
../include/Rivet/ProjectionApplier.hh:111:5: note: candidate: 'template<class PROJ> std::enable_if_t<std::is_base_of<Rivet::Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::apply(const Rivet::Event&, const PROJ&) const'
  111 |     apply(const Event& evt, const PROJ& proj) const { return applyProjection<PROJ>(evt, proj); }
      |     ^~~~~
../include/Rivet/ProjectionApplier.hh:111:5: note:   template argument deduction/substitution failed:
pluginATLAS/ATLAS_2023_I2663725.cc:98:45: error: template argument 1 is invalid
   98 |       Particles fs = apply<VetoedFinalState>(event, "isolatedFS").particles();
      |                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
../include/Rivet/ProjectionApplier.hh:126:5: note: candidate: 'template<class PROJ> std::enable_if_t<std::is_base_of<Rivet::Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::apply(const Rivet::Event&, const std::string&) const'
  126 |     apply(const Event& evt, const std::string& name) const { return applyProjection<PROJ>(evt, name); }
      |     ^~~~~
../include/Rivet/ProjectionApplier.hh:126:5: note:   template argument deduction/substitution failed:
pluginATLAS/ATLAS_2023_I2663725.cc:98:45: error: template argument 1 is invalid
   98 |       Particles fs = apply<VetoedFinalState>(event, "isolatedFS").particles();
      |                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
../include/Rivet/ProjectionApplier.hh:131:5: note: candidate: 'template<class PROJ> std::enable_if_t<std::is_base_of<Rivet::Projection, PROJ>::value, const PROJ&> Rivet::ProjectionApplier::apply(const std::string&, const Rivet::Event&) const'
  131 |     apply(const std::string& name, const Event& evt) const { return applyProjection<PROJ>(evt, name); }
      |     ^~~~~
../include/Rivet/ProjectionApplier.hh:131:5: note:   template argument deduction/substitution failed:
pluginATLAS/ATLAS_2023_I2663725.cc:98:45: error: template argument 1 is invalid
   98 |       Particles fs = apply<VetoedFinalState>(event, "isolatedFS").particles();
      |                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

**Comment by smuzaffar** [comment]
> The error actually comes from this new ATLAS analysis, probably just caused by a missing include.
> But I am wondering why it was not failing before?

@mseidel42 , this is failing for ppc64le only. For `aarch64` and `amd64` it did not fail.
By the way, do we need to build all the plugins? Why not just enable build CMSAnalysis rivet plugin?

**Comment by mseidel42** [comment]
Hi Malik, sometimes we need the other experiments' plugins for comparison or generator tuning, so I will just remove this specific one, or add a patch for it.

Do you know which flags are actually making the compiler more strict to give errors on things like this? We could ask the Rivet authors to use them as well, so that it does not cause problems in CMSSW later.

**Comment by smuzaffar** [comment]
@mseidel42 , we are not passing any special build/compilation flags. The only flags we set is `-std=c++17` but this flag is set for all archs (x86_64, ppc64le and aarch64). So ideally it should work unless there is any conditional include statements for non-ppc64le

**Comment by smuzaffar** [comment]
@mseidel42 , it could be the ordering of files when rivet build system tries to run `g++ -o "RivetATLASAnalyses.so" -shared -fPIC <list-of-plugin-sources>`. May be adding the missing `#include "Rivet/Projections/VetoedFinalState.hh"` in `pluginATLAS/ATLAS_2023_I2663725.cc` fix this issue

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
+externals

**Comment by antoniovilela** [comment]
ignore tests-rejected with external-failure

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
