### PR TITLE
Update LLVM to version 12.0.1

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
please test

**Comment by mrodozov** [comment]
there is 13 already, should we get it given numba and llvmlite are relatively simple to adjust ?

**Comment by fwyzard** [comment]
no idea.. they make new releases too quickly !

**Comment by smuzaffar** [comment]
please test for CMSSW_12_1_CLANG_X

**Comment by smuzaffar** [comment]
looks good though, I ran clang-tidy and format on full cmssw. For clang-tidy there are no changes but clang format suggests changes for few extra files 

- LLVM 12.0.0 : https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_12_1_X_2021-08-31-1100/87/code-format.patch
```
DataFormats/SiStripCluster/interface/SiStripClusterfwd.h
SimG4CMS/HGCalTestBeam/src/HGCalTB16SD01.cc
SimG4CMS/ShowerLibraryProducer/interface/FiberSD.h
SimG4CMS/ShowerLibraryProducer/interface/HFChamberSD.h
SimG4CMS/ShowerLibraryProducer/interface/HFWedgeSD.h
SimG4CMS/ShowerLibraryProducer/src/FiberSD.cc
SimG4CMS/ShowerLibraryProducer/src/HFChamberSD.cc
SimG4CMS/ShowerLibraryProducer/src/HFWedgeSD.cc
```

- LLVM 12.0.1: https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_12_1_X_2021-08-31-1100/86/code-format.patch
```
DQM/CSCMonitorModule/plugins/CSCDQM_Configuration.h
DataFormats/SiStripCluster/interface/SiStripClusterfwd.h
DetectorDescription/Core/test/DDFilter.cppunit.cc
FWCore/FWLite/bin/storageSizeForBranch.cc
FWCore/Framework/test/statemachine_t.cc
FWCore/Integration/bin/interprocess.cc
FWCore/Integration/bin/interprocess_random.cc
FWCore/PluginManager/bin/dump.cc
Fireworks/Core/src/CmsShowMain.cc
GeneratorInterface/Core/bin/externalGenerator.cc
RecoBTau/JetTagComputer/interface/GenericMVAJetTagComputerWrapper.h
SimG4CMS/HGCalTestBeam/src/HGCalTB16SD01.cc
SimG4CMS/ShowerLibraryProducer/interface/FiberSD.h
SimG4CMS/ShowerLibraryProducer/interface/HFChamberSD.h
SimG4CMS/ShowerLibraryProducer/interface/HFWedgeSD.h
SimG4CMS/ShowerLibraryProducer/src/FiberSD.cc
SimG4CMS/ShowerLibraryProducer/src/HFChamberSD.cc
SimG4CMS/ShowerLibraryProducer/src/HFWedgeSD.cc
```

**Comment by makortel** [comment]
> clang format suggests changes for few extra files

By quick look the patch looks ok to me. Some of the changes look like those files would not have been formatted before though.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
