### PR TITLE
Update XRootD to 5.x in CMSSW 10_6_X

### PR DESCRIPTION
**Pull request by iarspider**
please test for CMSSW 10_6_X

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW 10_6_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
> please test for CMSSW 10_6_X

@iarspider , release queueis wrong here it should be `CMSSW_10_6_X` :-) or `please test` should be enough as bot is going to use the PR base branch to find the correct cmssw queue

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/41599

**Comment by smuzaffar** [comment]
@iarspider , can youplease check why xrootd cmake says that `-- SciTokens:         disabled` (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b26359/32315/externals/xrootd/5.5.3-dc58751a1d829398da464bcdbd1e304d/log).

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , can you please check what is missing here

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
Looks like we need to backport https://github.com/cms-sw/cmssw/pull/34991 (and maybe other PRs) to make cmssw work.

**Comment by iarspider** [comment]
And probably also this: https://github.com/cms-sw/cmssw/pull/35455

**Comment by smuzaffar** [comment]
@iarspider , right, please open a cmssw PR with these changes

**Comment by smuzaffar** [comment]
@iarspider , I think `scitokens-cpp` is not needed for xrdclient, better to remove it

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
`test_occi_std_length` (the only unit test that failed) also fails in IBs

**Comment by smuzaffar** [comment]
yes this test is failing for every IB 9 looks like some issues with oracle connection at cern).

**Comment by rappoccio** [comment]
Should we also merge this one @smuzaffar ? Do you expect the checks to pass once the oracle connection is re-established?

**Comment by iarspider** [comment]
@rappoccio the db failure is unrelated,  it should be fixed by https://github.com/cms-sw/cmssw/pull/41630

**Comment by smuzaffar** [comment]
please test

yes @rappoccio , we should merge this too along with https://github.com/cms-sw/cmssw/pull/41599 . let me re-run the tests once more. Note the the oracle unit test will still fail in 10.6.X

**Comment by smuzaffar** [comment]
+externals

@rappoccio @perrotta  this is ready to go in 10.6.X ( along with https://github.com/cms-sw/cmssw/pull/41599 ).  I would suggest to merge these and let the IBs run for few days before cutting a 10.6.X release.

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
