### PR TITLE
[XROOTD] Update top version 5.3.1

### LINKED ISSUE #7179: Bump xrootd to 5.3.x
We are still using 4.12, it's high time to move on! :)

On a serious note, fwlite can not open CERN EOS files througg TFile::Open("root://eoscms.cern.ch/..." because of that. I assume cmsRun has the same problem.

### PR DESCRIPTION
**Pull request by smuzaffar**
fixes #7179

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by osschar** [comment]
@smuzaffar I can give it a try tomorrow, fixing XrdAdaptor and friends. Are the instructions from buildbot above reasonable? I haven't done much cmssw development lately :)

**Comment by osschar** [comment]
decided to try it anyway, apparently directory 7180 has not been created:
```
matevz@lxplus7100 ~> ls /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist
7167  7168  7169  7170  7171  7172  7174  7175  7176  7177  7178
```

**Comment by smuzaffar** [comment]
ah yes @osschar , in case of build errors we do not upload cmssw area. I will fix bot message for that. 
For now you can try this 

```
scram p CMSSW_12_0_X_2021-07-28-1100
cd CMSSW_12_0_X_2021-07-28-1100/
mv config/toolbox/slc7_amd64_gcc900/tools tools.old
cp -r /cvmfs/cms-ci.cern.ch/week1/PR_c3ae2f01/slc7_amd64_gcc900/cms/cmssw-tool-conf/50.0-26030e972e4c6e452a0c6d6969074d6a/tools config/toolbox/slc7_amd64_gcc900/
scram setup
cmsenv
git cms-addpkg Utilities/XrdAdaptor
scram b -j 20
```

**Comment by osschar** [comment]
Thank you! Missing XrdSysLinuxSemaphore was actually the only compilation error.

https://github.com/osschar/cmssw/tree/from-CMSSW_12_0_X_2021-07-28-1100

I'm in contact with core xrootd guys to see if I should re-check some other things as well.

When I'm done, what do I make the PR against to make it link to this external update?

**Comment by smuzaffar** [comment]
@osschar , if changes are needed only for `CMSSW` then open PR to cmssw repository and then we can test it using "please test with cms-sw/cmsdist#7180".  If changes are also needed for `root` then we need to open a pr https://github.com/cms-sw/root/tree/cms/v6-22-00-patches%2Fabd79a9716 and then test all of them together

**Comment by osschar** [comment]
@smuzaffar apparently my working area setup as you advised me before is no longer viable, IB and tool-confs are both gone, it seems.
I have changes for cms-sw/cmssw#34700 that I'd like to test.
Please help! :)

**Comment by smuzaffar** [comment]
@osschar , the PR build area is only available for one week that is why the old externals have been deleted from cvmfs. Please try
 
```
scram p CMSSW_12_1_X_2021-08-18-1500
cd CMSSW_12_1_X_2021-08-18-1500/
mv config/toolbox/slc7_amd64_gcc900/tools tools.old
cp -r /cvmfs/cms-ci.cern.ch/week1/PR_c3ae2f01/slc7_amd64_gcc900/cms/cmssw-tool-conf/50.0-26030e972e4c6e452a0c6d6969074d6a/tools config/toolbox/slc7_amd64_gcc900/
scram setup
cmsenv
git cms-addpkg Utilities/XrdAdaptor
scram b -j 20
```

/cvmfs/cms-ci.cern.ch/week1/PR_c3ae2f01/slc7_amd64_gcc900/cms/cmssw-tool-conf/50.0-26030e972e4c6e452a0c6d6969074d6a is newly build cmssw externals

**Comment by osschar** [comment]
I'm sorry, I can't see directory `/cvmfs/cms-ci.cern.ch/week1/PR_c3ae2f01/` ... it's also not in `../week0/` where there are some newer sub-dirs.

I tried to figure out what hash following `PR_` is and failed (I was guessing it's a cmsdist short commit id).

**Comment by smuzaffar** [comment]
ah sorry, please use 
```
/cvmfs/cms-ci.cern.ch/week0/PR_3c452db3/slc7_amd64_gcc900/cms/cmssw-tool-conf/51.0-59a51b1ea7b46a451767770f84e0362b/tools
```

**Comment by smuzaffar** [comment]
lets merge it for DEVEL IBs to fully test it

**Pull request merged**
