### PR TITLE
Branch IB/CMSSW_10_6_X/gcc700 - Cherry-picked  6c1e592 from root pr.

### PR DESCRIPTION
**Pull request by gudrutis**

### CODE REVIEW

**Comment by gudrutis** [comment]
Please test

**Comment by smuzaffar** [comment]
+externals
@Dr15Jones this includes the ROOT https://github.com/root-project/root/pull/3485 fix for our normal IBs (i.e. root 6.12 based IBs). 
@fabiocos , any objection on merging this?

**Comment by fabiocos** [comment]
+1

there is no other external merge I plan, so let's try it now

**Comment by Dr15Jones** [comment]
@smuzaffar which IBs have this change?

**Comment by smuzaffar** [comment]
@Dr15Jones, CMSSW_10_6_X_2019-03-03-0000 and above

**Pull request merged**
