### PR TITLE
Fix GBL compilation for non-x64 architectures

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test for el8_aarch64_gcc12

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test for el9_aarch64_gcc12

**Comment by iarspider** [comment]
please test for CMSSW_14_0_X/el9_aarch64_gcc12

No builds for aarch yet for 14_1_X, due to an issue this PR should fix

**Comment by smuzaffar** [comment]
@iarspider , please open a separate PR for 14.0.X

**Comment by iarspider** [comment]
please abort

**Comment by smuzaffar** [comment]
+externals

this has been tested for 14.0.X (https://github.com/cms-sw/cmsdist/pull/8992 ). As we do not have 14.1.X non-x86_64 IBs, so lets get this in for 11h00 and trigger aarch64 and ppc64le IBs for 14.1.X at 11h00

**Pull request merged**
