### PR TITLE
Rivet 3.1.7 & YODA 1.9.7

### PR DESCRIPTION
**Pull request by mseidel42**
Rivet and YODA version bump

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
looks like rivet needs some fixing
```
Rivet/Tools/RivetSTL.hh:48:14: error: 'make_unique' has not been declared in 'std'
```

**Comment by mseidel42** [comment]
Hi Malik,

Maybe it would be sufficient to compile Sherpa with C++14?
https://github.com/cms-sw/cmsdist/blob/e0ddfdbc53c5daab74a70407a9d444a67b451bfd/sherpa.spec#L50

Let me try it out...

Best,
Markus

**Comment by smuzaffar** [comment]
@mseidel42 , I built sherpa with `c++17` and it worked. So I would suggest to go with `c++17`  as rivet is already using it https://github.com/cms-sw/cmsdist/pull/8109/files#diff-5d526b7eadac085699ac3414d6f0dffefe4f218d6240d7e54a39eb86f6aa370bR39 . 

Also the `mcfc` dependency in `sherpa` is unused, may be clean that up too

**Comment by mseidel42** [comment]
Ok, I tried
```
time pkgtools/cmsBuild --new-scheduler -i a -a el8_amd64_gcc10 --builders 4 -j $(($(getconf _NPROCESSORS_ONLN) * 2)) build sherpa-toolfile
```
and it's somehow stuck at building openloops...

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc10

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc10

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc11

**Comment by smuzaffar** [comment]
assign generators

**Comment by smuzaffar** [comment]
+externals
@cms-sw/generators-l2 [this looks good](https://github.com/cms-sw/cmsdist/pull/8109#issuecomment-1272681911) to me, please sign it if you are ok with this update.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mseidel42 , can you please 
- delete `%{relocateConfig}lib/python*/site-packages/rivet-*egg-info/SOURCES.txt` line from rivet.spec as it is [not needed](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-265ba6/28488/external_checks/unknown/rivet.txt) any more
- delete `%{relocateConfig}lib/python*/site-packages/yoda*egg-info/SOURCES.txt` frpm yoda.spec as it is [not needed](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-265ba6/28488/external_checks/unknown/yoda.txt)

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@mseidel42 , looks like after this update we start getting crashes for couple of workflows ( see https://github.com/cms-sw/cmssw/issues/39914 ). Any idea? should we revert this ?

**Comment by mseidel42** [comment]
Hi @smuzaffar, ok, let's revert this for now.

I think we do not really need the Sherpa-internal Rivet interface in CMSSW, so I may try to disable that and see if things work fine. I got the complete build commands from one of the log files, so I can test it on cmsdev before making a new PR!

**Pull request merged**
