### PR TITLE
Fix CUDA compilation flags (11.1.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Re-enable optimisations in CUDA compilation.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
backport of #5840

**Comment by silviodonato** [comment]
+1

**Comment by fwyzard** [comment]
backport #5840

**Comment by fwyzard** [comment]
backport #5840

**Comment by fwyzard** [comment]
@smuzaffar the 11.2.x IB with #5840 looks good: https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_2_X .
Can you merge this for 11.1.x ?

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
