### PR TITLE
Update Eigen to the master branch

### PR DESCRIPTION
**Pull request by fwyzard**
Update Eigen to the master branch as of Wed, 9 Jan 2019 18:00:05 +0100
 - hg hash ad3bcd81cc4973a193a14c20fbbd2f2b24aaa125
 - git hash c9f748adbc827fbcbd71b19e52ab7134c587396e

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
I'd like to retry this last one and see how it goes as it works (building igprof with cmake 3.13.3) with the local build

**Comment by smuzaffar** [comment]
@mrodozov , please revert all your changes for this PR and cherry-pick the fix https://github.com/eigenteam/eigen-git-mirror/commit/a83b6171fa9b55f9d0139a7c0d60d6b55111b9a2#diff-af3b638bc2a3e6c650974192a53c7291 on top of https://github.com/cms-externals/eigen-git-mirror/tree/cms/c9f748adb

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , as discussed, we can now merge it.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
