### PR TITLE
1.0.1.pre8 update

### PR DESCRIPTION
**Pull request by ticoann**
use WMCore 1.0.1.pre8  fixes dashboard report and wmdatamining

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 9aba07a32e0c9d921983333ea13c24fc8ec664eb on slc6_amd64_gcc481.

**Comment by amaltaro** [comment]
@geneguvo @ticoann , I've finally found the source of the KeepOutput bug.
I'm will start running a couple of tests and when Seangchan wakes up I'll ask him to create a new tag.
I'm really sorry for that!

**Comment by geneguvo** [comment]
+1 to e9d7eec0fd3ee8e75fcd5d23544a3a3a7d5302bb on slc6_amd64_gcc481.

**Comment by ticoann** [comment]
Updated the patch with Alan's fix and tier0 Monitor fix.

**Pull request closed without merging**
