### PR TITLE
Enable -Wshadow=local compilation flag for DEVEL IBs.

### PR DESCRIPTION
**Pull request by smuzaffar**
Resolves https://github.com/cms-sw/cmssw/issues/27675
We are proposing to include it first in DEVEL IBs and fix all the warnings before enabling it for production IB.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/27849

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
closing it

**Pull request closed without merging**
