### PR TITLE
WMCore 2.0.2.pre2 release candidate for HG2204

### PR DESCRIPTION
**Pull request by amaltaro**
New central services pre-release: 2.0.2.pre2
and WMAgent Py3 bump as well.

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by muhammadimranfarooqi** [comment]
-1 to e9b802e90cb160b4582db5ab242dbe4178b13991 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7736/test_e9b802e-20220331-162003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
This fails because we are unable to download the source code with git protocol:
```
resulted in:
Initialized empty Git repository in /build/dmwmbld/srv/state/dmwmbld/builds/7736/w/tmp/tmp7RqJUA/WMCore-2.0.2.pre2/.git/
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

@smuzaffar Shahzad, is there a fix upstream for this (maybe in pkgtools)? Or should we actually update our spec files to start using `https` instead of `git`?

**Comment by smuzaffar** [comment]
@amaltaro , you need to use ` git+https://` instead of `git://` which is now not supported. You can start cleaning it up in the specs you have touched in this PR.

**Comment by muhammadimranfarooqi** [comment]
+1 to e71915968096b0fb161c599ce0e2d0cb311dcc0f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7736/test_e719159-20220331-175002.log" target="_blank">here</a>.

**Pull request merged**
