### PR TITLE
Updated root to tip of branch v6-18-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by davidlange6** [comment]
seems a real error (and related to the pyroot changes introduced in root) but will retest

**Comment by davidlange6** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
is this unit test error in TestRunnerDataFormatsFWLite something common or did it start appearing with this PR updates?
The error message is not particularly clear
```
 *** Break *** segmentation violation
starting python test
Failed in chainEvent_python.py: status 129
status = 33024

```

**Comment by mrodozov** [comment]
@slava77 
This IB is clean from errors, so it's coming from the commits on top
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_11_0_ROOT618_X_2019-08-22-2300/unitTestLogs/DataFormats/FWLite#/129-129

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
> @slava77
> This IB is clean from errors, so it's coming from the commits on top
> https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_11_0_ROOT618_X_2019-08-22-2300/unitTestLogs/DataFormats/FWLite#/129-129

would it be OK to still merge it so that this IB can be used to debug the problem?

**Comment by smuzaffar** [comment]
closing in favor of #5171

**Pull request closed without merging**
