### PR TITLE
Update DD4Hep to latest commit on master

### PR DESCRIPTION
**Pull request by mrodozov**
please test with https://github.com/cms-sw/cmssw/pull/31770

### CODE REVIEW

**Comment by mrodozov** [comment]
Resolves: #6308

**Comment by ianna** [comment]
@mrodozov - the fix for these errors is to use:
```c++
if (mySpecParSection.second->hasPath(nodePath)) {
```
```c++
return mySpecParSection.second->value>(parameterName);
```
Could you, please, apply the changes? Alternatively, I can provide a PR for that. Please, let me know. Thanks.

**Comment by ianna** [comment]
@mrodozov - I have a patch for it:
cmsdev20:/build/yana/CMSSW_11_2_X_2020-10-15-1100/src/alignmemt.patch.diff

Piggybacked on it and cleaned up the header and SealModule.

**Comment by ianna** [comment]
> @mrodozov - I have a patch for it:
> cmsdev20:/build/yana/CMSSW_11_2_X_2020-10-15-1100/src/alignmemt.patch.diff
> 
> Piggybacked on it and cleaned up the header and SealModule.

Ok, there are more files need similar changes. I'll make a PR soon.

**Comment by ianna** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/31821

**Comment by ianna** [comment]
please test with cms-sw/cmssw#31821

**Comment by ianna** [comment]
@mrodozov - sorry, I should have tested it with both PRs

**Comment by ianna** [comment]
please test with cms-sw/cmssw#31770,  cms-sw/cmssw#31821

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort
this couldn't go by itself I forgot

**Comment by ianna** [comment]
please test with https://github.com/cms-sw/cmssw/pull/31770, https://github.com/cms-sw/cmssw/pull/31810, https://github.com/cms-sw/cmssw/pull/31821

**Comment by ianna** [comment]
please test with cms-sw/cmssw#31770, cms-sw/cmssw#31810, cms-sw/cmssw#31821

**Comment by ianna** [comment]
@mrodozov - can we please, merge it for 11 am IB? I see that one unit test fails due to PGeometricDetExtra removal that is addressed in a separate PR. The second one is a DT geometry validation test. It would be easier to fi it with a clean IB. Thanks.

**Comment by smuzaffar** [comment]
@ianna , Is it safe to merge only dd4hep without cmssw? If not then we will wait for cmssw PRs to be fully singed and merge together with this.

**Comment by smuzaffar** [comment]
please test
testing external only

**Comment by ianna** [comment]
> @ianna , Is it safe to merge only dd4hep without cmssw? If not then we will wait for cmssw PRs to be fully singed and merge together with this.

You'll get lots of compilation errors :-(

**Comment by ianna** [comment]
OK, https://github.com/cms-sw/cmssw/pull/31729 was merged 16 hours ago. It fixes the `GeometryTrackerGeometryBuilderTestDriver` unit test.

**Comment by ianna** [comment]
please test with cms-sw/cmssw#31770, cms-sw/cmssw#31810, cms-sw/cmssw#31821

**Comment by ianna** [comment]
please test with cms-sw/cmssw#31770, cms-sw/cmssw#31810, cms-sw/cmssw#31821

**Comment by ianna** [comment]
please test with https://github.com/cms-sw/cmssw/pull/31879

**Comment by ianna** [comment]
@mrodozov and @smuzaffar - I cannot access the log for git cms-merge-topic.

**Comment by civanch** [comment]
@mrodozov , @smuzaffar , DD4Hep migration this PR is essential. Would it be possible to merge it even if the DT unit test is failing?  @ianna promised fixing unit test tomorrow. The merge of this will allow others to continue fixing problems more effectively.

**Comment by smuzaffar** [comment]
@civanch , this can go in but only with cms-sw/cmssw#31879 (when that is fully signed and ready to merge). without cms-sw/cmssw#31879 IB will fail to build

**Comment by ianna** [comment]
please test with  cms-sw/cmssw#31879

**Comment by ianna** [comment]
@smuzaffar - please, consider this update for 11:00 am IB. There are several people who need this for their development. Thanks!

**Comment by smuzaffar** [comment]
@ianna , same question, is it safe to merge it without cmssw changes? If not then I am afraid I can not merge it and break IB for all.

**Comment by ianna** [comment]
> @ianna , same question, is it safe to merge it without cmssw changes? If not then I am afraid I can not merge it and break IB for all.

@smuzaffar - no, it has to go along with cms-sw/cmssw#31879, however, the code checks block its proper integration.

**Comment by smuzaffar** [comment]
@ianna , I have approved the code checks ( after testing it locally using new dd4hep)

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
merge

**Pull request merged**
