### PR TITLE
Include patch jet Matching for SUSY.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/smrenna/pythia8/commit/f07694f3750a59b12f2dd4d49bb3af8697b8a6e8

### CODE REVIEW

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by ghost** [comment]
@smrenna Looks like this PR will need a corresponding CMSSW one to fix changed methods.

**Comment by bendavid** [comment]
Normally we wouldn't have done this in a pythia8 patch in cms-externals, but this change is anyways part of 8.215 so would have to be made eventually.

Fixed by taking this together with https://github.com/cms-sw/cmssw/pull/13305

**Comment by bendavid** [comment]
@covarell @govoni

**Comment by govoni** [comment]
+1

**Comment by bendavid** [comment]
(Having this in IB's would ease the testing of ongoing developments for SUSY parameter scans, which are ultimately targeting SUSY fastsim production in 80x)

**Comment by bendavid** [comment]
I'm trying to make sure that (non-trivial) changes needed in 80x for SUSY parameter scans in fastsim come on a somewhat reasonable timescale.  These changes are needed to coherently test things in the release.

**Comment by ghost** [comment]
+1
The tests run correctly (see cmssw thread for reference).
Due to a bug in the testing script it just failed to report them here.

**Pull request merged**
