### PR TITLE
Update to Rivet 2.4.0 in 76X 

### PR DESCRIPTION
**Pull request by xjanssen**
Update to latest Rivet version: 2.4.0 (and to Yoda 1.5.5 dependency)

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
@davidlange6 Should we first merge this in 8_0_X?

**Comment by ghost** [comment]
@xjanssen I've merged this PR for 8_0_X here: #1933. Is it also needed for 76X?

**Comment by xjanssen** [comment]
Yes, we need to have it available in 76x as many people are going to use that release after x-mas production. Ideally we could try to port as well to 74x but ...

**Pull request merged**
