### PR TITLE
Update ipython to 3.1.0.

### PR DESCRIPTION
**Pull request by ghost**
Requested in: https://github.com/cms-sw/cmsdist/issues/1540

### CODE REVIEW

**Comment by ghost** [comment]
-1
Compilation is fine.
However cmssw package PhysicsTools/HeppyCore needs to be update accordingly.

**Comment by ghost** [comment]
@davidlange6 @ktf As requested by @cbernet this is the update to ipython. However heppy in PhysicsTools/HeppyCore will break following this update.
Also, @cbernet asked this update for 74X particularly, I think however that we should first include it in 75X, fix the cmssw package and then backport everything to 74X. Do you agree?

**Comment by cbernet** [comment]
Hi Alessandro, 

Could you please give me more details about why PhysicsTools/HeppyCore will break? 
How can I test that? 

Thanks, 

Colin

**Comment by ktf** [comment]
@degano, maybe you can install `ipython-toolfile` by hand in AFS so that @cbernet can try it out.

**Comment by ghost** [comment]
@ktf @cbernet Done installing on afs week0 volume.
@cbernet you can now setup ipython 3.1.0 in a 7_5_X release by doing:

```
scram setup /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/external/py2-ipython-toolfile/1.0-cms2/etc/scram.d/py2-ipython.xml
cmsenv
```

NOTE: Because of the usual IB volumes rotation this package will be available until Sunday 24th of May.

**Comment by cbernet** [comment]
@degano: thank you very much. 

Could you please tell me more about the problem you observed? 

I did some testing, and I can see that I have to remove the -noconfirm_exit option from this script:

[test]$ cat PhysicsTools/HeppyCore/scripts/heppy
#!/usr/bin/env bash
ipython --pdb -noconfirm_exit -- $CMSSW_BASE/src/PhysicsTools/HeppyCore/python/framework/heppy.py "$@" 

When I do that, it seems to work. 
But: 
- I would like to be sure I have fixed the problem you are referring to, and not another one. 
- I’d like to know how you managed to catch that because I’m kind of impressed :-)

**Comment by ghost** [comment]
@cbernet That was the only issue I observed and frankly I don't know if there are more. As for how I caught it I just searched for ipython in cmssw repository ;)

**Comment by cbernet** [comment]
Nice catch anyway ;-) 
As you have seen, I did a pull request with a fix. Please let me know if you need anything else. 
Colin

**Comment by ktf** [comment]
@cbernet: since you use ipython, you might find:

https://github.com/blog/1995-github-jupyter-notebooks-3

inspiring, if you have not read it already...

**Comment by ghost** [comment]
+1
https://github.com/cms-sw/cmssw/pull/9054 have fixed the issue observed.
Merging now.

**Pull request merged**
