### PR TITLE
[GCC] Update to GCC 12.3.1

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by VinInn** [comment]
ICE!

**Comment by VinInn** [comment]
I reproduced in my area.
DOES NOT reproduce outside CMSSW
``` nvcc -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/eigen/82dd3710dac619448f50331c1d6a35da673f764a-a265c39c534705ccfbcfdf86bff919ba/include/eigen3 -O2 simpleCholeskyTest.cu --expt-relaxed-constexpr```

**Comment by VinInn** [comment]
this one gives me "no match"

```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/cuda/12.1.1-5b5fda0c810f24361aa8d53b953de396/bin/nvcc -x cu -dc -DGNU_GCC -D_GNU_SOURCE -DEIGEN_DONT_PARALLELIZE -DTBB_USE_GLIBCXX_VERSION=120201 -DTBB_SUPPRESS_DEPRECATED_MESSAGES -DTBB_PREVIEW_RESUMABLE_TASKS=1 -DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1 -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DCMSSW_GIT_HASH='CMSSW_13_2_X_2023-05-24-1100' -DPROJECT_NAME='CMSSW' -DPROJECT_VERSION='CMSSW_13_2_X_2023-05-24-1100' -I/data/user/innocent/CMSSW_13_2_X_2023-05-24-1100/src -I/cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_13_2_X_2023-05-24-1100/src -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/pcre/8.43-7946d556a5a1260072bf3e097680624a/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/boost/1.80.0-69849cb70f0240742403f2fd275629e9/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/bz2lib/1.0.6-7aeadbe70e110206a5215d8bdf1c337b/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/cuda/12.1.1-5b5fda0c810f24361aa8d53b953de396/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/gsl/2.6-a502fedfb9023468a258791e8fcdc267/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/libuuid/2.34-59e047c826b5e94cb5390ba14889f03d/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/lcg/root/6.26.11-c5c906214175712d6a43e428c3614908/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/tbb/v2021.8.0-6a3afa8c4dec4c67044a76844beadecf/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/xz/5.2.5-d8c06d7482621243ce7642b606f43978/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/zlib/1.2.11-534b7a9a31a2ae78c735f4d1a6ef6449/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/eigen/82dd3710dac619448f50331c1d6a35da673f764a-a265c39c534705ccfbcfdf86bff919ba/include/eigen3 -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/fmt/8.0.1-21e9de038149d246e94d3d21f032bcfb/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/md5/1.0.0-85248a7e85b8359f56d8b795ff446626/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/OpenBLAS/0.3.15-07d0d0b37f978d5dbbdf5bb2efcdb81f/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/tinyxml2/6.2.0-b2ebac2deee9bfa03d0edd2a5c748576/include --diag-suppress 20014 -std=c++17 -O3 --generate-line-info --source-in-ptx --display-error-number --expt-relaxed-constexpr --extended-lambda -gencode arch=compute_60,code=[sm_60,compute_60] -gencode arch=compute_70,code=[sm_70,compute_70] -gencode arch=compute_75,code=[sm_75,compute_75] -Wno-deprecated-gpu-targets -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored --cudart shared -w --compiler-options '-O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -ftree-vectorize -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -Wno-error=array-bounds -Warray-bounds -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS  -std=c++17 -fPIC ' simpleCholeskyTest.cu
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/cuda/12.1.1-5b5fda0c810f24361aa8d53b953de396/bin/nvcc: No match.
```

**Comment by VinInn** [comment]
got it!

```
[innocent@patatrack01 ice]$ nvcc -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/eigen/82dd3710dac619448f50331c1d6a35da673f764a-a265c39c534705ccfbcfdf86bff919ba/include/eigen3 simpleCholeskyTest.cu --expt-relaxed-constexpr -std=c++17 -O3 --extended-lambda -gencode arch=compute_75,code=sm_75 --cudart shared -w --compiler-options '-O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -ftree-vectorize -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -Wno-error=array-bounds -Warray-bounds -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS  -std=c++17 -fPIC ' -x cu -dc
[innocent@patatrack01 ice]$ ls
a.out  choleskyInversion.h  simpleCholeskyTest.cu  simpleCholeskyTest.o
[innocent@patatrack01 ice]$ nvcc -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/eigen/82dd3710dac619448f50331c1d6a35da673f764a-a265c39c534705ccfbcfdf86bff919ba/include/eigen3 simpleCholeskyTest.cu --expt-relaxed-constexpr -std=c++17 -O3 --extended-lambda -gencode arch=compute_75,code=sm_75 --cudart shared -w --compiler-options '-O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -ftree-vectorize -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -Wno-error=array-bounds -Warray-bounds -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS  -std=c++17 -fPIC ' -x cu -dc --generate-line-info --source-in-ptx
nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
nvcc error   : 'cicc' core dumped
```

the culprit seems to be ```--source-in-ptx```

**Comment by VinInn** [comment]
minimal  nvcc -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/eigen/82dd3710dac619448f50331c1d6a35da673f764a-a265c39c534705ccfbcfdf86bff919ba/include/eigen3 simpleCholeskyTest.cu --expt-relaxed-constexpr -std=c++17 -O3 --source-in-ptx  -x cu -dc
nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
nvcc error   : 'cicc' core dumped

**Comment by VinInn** [comment]
self contained test in https://github.com/VinInn/ctest/tree/master/cuda/ice
just
```source compile``` with proper CMSSW environment

**Comment by VinInn** [comment]
for reference 
```
[innocent@patatrack01 ice]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
[innocent@patatrack01 ice]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454/bin/../libexec/gcc/x86_64-redhat-linux-gnu/12.2.1/lto-wrapper
Target: x86_64-redhat-linux-gnu
Configured with: ../configure --prefix=/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454 --disable-multilib --disable-nls --disable-dssi --enable-languages=c,c++,fortran --enable-gnu-indirect-function --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-plugin --with-linker-hash-style=gnu --enable-linker-build-id --enable-ld=default --enable-lto --enable-gold=yes --with-gmp=/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454 --with-mpfr=/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454 --enable-bootstrap --with-mpc=/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454 --with-isl=/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454 --enable-checking=release --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --enable-libstdcxx-time=rt --enable-shared --disable-libgcj --with-zstd=/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454/tmp/sw CC='gcc -fPIC' CXX='c++ -fPIC' CPP=cpp CXXCPP='c++ -E' CFLAGS=-I/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454/tmp/sw/include CXXFLAGS=-I/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454/tmp/sw/include LDFLAGS=-L/data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/tmp/BUILDROOT/59043c7bdcfa6002a8c9155ca1109454/opt/cmssw/el8_amd64_gcc12/external/gcc/12.2.1-59043c7bdcfa6002a8c9155ca1109454/tmp/sw/lib
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.1 20230403 (GCC)
```

**Comment by VinInn** [comment]
@fwyzard FYI

**Comment by fwyzard** [comment]
hi @VinInn, we already reported to NVIDIA a problem caused by `--source-in-ptx` that appeared with CUDA 12.1: https://forums.developer.nvidia.com/t/cicc-crashes-with-segmentation-fault-core-dumped/254188 (plus a bug report that is not public).

NVIDIA support confirmed that it is a known issue, that they have an internal fix, and that it should be fixed in the next CUDA minor version (not sure if they mean 12.1.2 or 12.2.0).

Can you confirm that the same test can be compiled with 12.0.x ?

**Comment by VinInn** [comment]
@fwyzard where I can find  a cuda 12.0.x?
in  /cvmfs/cms-ib.cern.ch/*/x86_64/*/*/external/cuda/ I see only
12.1.1-5b5fda0c810f24361aa8d53b953de396

**Comment by VinInn** [comment]
in order to move on we could remove ```source-in-ptx ``` from the config

**Comment by fwyzard** [comment]
> where I can find a cuda 12.0.x?

/cvmfs/patatrack.cern.ch/externals/x86_64/rhel8/nvidia/cuda-12.0.1/

**Comment by VinInn** [comment]
/cvmfs/patatrack.cern.ch/externals/x86_64/rhel8/nvidia/cuda-12.0.1/bin/nvcc  -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02786/el8_amd64_gcc12/external/eigen/82dd3710dac619448f50331c1d6a35da673f764a-a265c39c534705ccfbcfdf86bff919ba/include/eigen3 simpleCholeskyTest.cu --expt-relaxed-constexpr -std=c++17 -O3 --source-in-ptx  -x cu -dc

no error

**Comment by smuzaffar** [comment]
please test with #8527 for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
this looks good. we have the same errors as we have with GCC 12.2.1, so lets get this in

**Pull request merged**
