### PR TITLE
New version to use make

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to 170ca3c058fdf96fca3edeb9f472b615a48f6c91 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6287/test_170ca3c-20201002-020503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Its failed.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , please trigger the build, I added missing dependency.

**Comment by muhammadimranfarooqi** [comment]
+1 to 3353a2364ec3b8dad9bb59dbcc13bd9542397931 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6287/test_3353a23-20201002-132503.log" target="_blank">here</a>.

**Pull request merged**
