### PR TITLE
Backport: FastSimulation-TrackingRecHitProducer: New pixel resolution files [102X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #4196

For FastSim backports in 102X.

attn: @ssekmen, @pmaksim1

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by ssekmen** [comment]
@fabiocos , can we please merge this so I can proceed with testing https://github.com/cms-sw/cmssw/pull/25309 ? Thanks.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
