### PR TITLE
Update Alpaka to version 1.1.0

### PR DESCRIPTION
**Pull request by fwyzard**
Major changes include:
  - introduce SYCL/oneAPI support for CPUs and Intel GPUs
  - make alpaka platforms full objects, and rename from `Pltf` to `Platform`
  - make the vendor random number generators support optional
  - refactor `Vec` type, and add `.x()`, `.y()`, `.z()` accessors
  - enable support for asynchronous memory operations in ROCm 5.3 and later
  - change all CUDA warp operations to synchronise all threads
  - remove `ALPAKA_ASSERT_OFFLOAD`, introduce `ALPAKA_ASSERT_ACC`
  - implement `copysign()`, `fma()`, `log2()`, `log10()` math functions
  - simplify offset and pitch APIs
  - add support for CUDA 12.2, 12.3 and ROCm 5.6, 5.7, 6.0
  - improve error messages related to kernel launches
  - rework thread pool and callback threads
  - fix `alpaka::wait(device, event)` function for CUDA/HIP GPUs
  - implement `alpaka-ls`

Disable the vendor specific random number generators in Alpaka (NVIDIA cuRAND, AMD rocRAND, Intel DPL).

### CODE REVIEW

**Comment by fwyzard** [comment]
This will require a corresponding update in CMSSW.

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772

**Comment by fwyzard** [comment]
please abort

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/43772

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
enable gpu

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
Going through the logs, all the `el8_ppc64le_gcc12` errors seem unrelated to these changes.

**Comment by smuzaffar** [comment]
`testPhysicsToolsSelectorUtilsPythonTestsDriver` is failing ppc64le IBs

**Comment by smuzaffar** [comment]
@fwyzard , looks like GPU tests are hanging. Pr tests are running for over 30 mins now [a] while during IB tests these take just few secs https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/el8_amd64_gcc12/CMSSW_14_0_GPU_X_2024-01-23-2300/unitTestLogs/HeterogeneousCore/AlpakaInterface

[a]
```
3696591 00:00:06                      |                               \_ /cvmfs/cms-ci.cern.ch/week1/PR_04f9da7f/el8_amd64_gcc12/external/gmake/4.3-24ac97ee64086a54e50727abb
3697547 00:00:00                      |                                   \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${RESULT}
3697619 00:00:00                      |                                   |   \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${RESU
3697620 00:00:00                      |                                   |       \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${
3697636 00:30:02                      |                                   |           \_ alpakaTestHistoContainerCudaAsync
3697591 00:00:00                      |                                   \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${RESULT}
3697686 00:00:00                      |                                   |   \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${RESU
3697687 00:00:00                      |                                   |       \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${
3697703 00:30:02                      |                                   |           \_ alpakaTestOneHistoContainerCudaAsync
3697632 00:00:00                      |                                   \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${RESULT}
3697734 00:00:00                      |                                   |   \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${RESU
3697736 00:00:00                      |                                   |       \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${
3697752 00:30:03                      |                                   |           \_ alpakaTestOneToManyAssocCudaAsync
3697655 00:00:00                      |                                   \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${RESULT}
3697756 00:00:00                      |                                       \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${RESU
3697757 00:00:00                      |                                           \_ /bin/sh -c if [ "X" == "Xyes" ] ; then RESULT=$(/usr/bin/echo Skip); /usr/bin/printf "${
3697859 00:30:03                      |                                               \_ alpakaTestPrefixScanCudaAsync
```

**Comment by fwyzard** [comment]
I suspect this may actually due to https://github.com/cms-sw/cmssw/pull/43064 .
Let's check the results from tonight's IB.

**Comment by fwyzard** [comment]
FYI @ericcano , in case you have any ideas on the timeouts.

**Comment by smuzaffar** [comment]
> I suspect this may actually due to [cms-sw/cmssw#43064](https://github.com/cms-sw/cmssw/pull/43064) . Let's check the results from tonight's IB.

@fwyzard , IBs unit tests for GPU IB look good.

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
I see 🤷🏻‍♂️ 

I'll have a look after we are done with the last Alpaka PR, either today or next week.

**Comment by ericcano** [comment]
I reproduce the issue with CMSSW_14_0_X_2024-01-28-2300 +  alpaka-1.1.0 + `git cms-merge-topic 43772`.

Package `HeterogeneousCore/AlpakaInterface` compiles fine but other packages brought by `git cms-checkdeps -a` do not:

A random example:
```
/data/user/cano/OneToManyAssoc/alpaka-1.1/CMSSW_14_0_X_2024-01-28-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/SiPixelRawToClusterKernel.dev.cc:465:30: error: 'ALPAKA_ASSERT_OFFLOAD' was not declared in this scope; did you mean 'ALPAKA_ASSERT_ACC'?
  465 |         ALPAKA_ASSERT_OFFLOAD(TrackerTraits::numberOfModules < 2048);  // easy to extend at least till 32*1024
      |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         ALPAKA_ASSERT_ACC
```

I'm looking at the blocking, which involves a warp level primitive, as expected.

**Comment by fwyzard** [comment]
Yes, all uses of `ALPAKA_ASSERT_OFFLOAD` need to be replaced with `ALPAKA_ASSERT_ACC`.

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772

**Comment by fwyzard** [comment]
@ericcano's work in https://github.com/cms-sw/cmssw/pull/43811 (just merged) should fix the kernel hangs.

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772

**Comment by fwyzard** [comment]
That was actually useful, it spotted a bug in `RecoTracker/PixelVertexFinding/plugins/alpaka/splitVertices.h`, fixed by https://github.com/cms-sw/cmssw/pull/43820.

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772, cms-sw/cmssw#43820

**Comment by fwyzard** [comment]
Once all tests pass, we should consider adding
```xml
<!-- disable Alpaka device-side asserts in non-test libraries and plugins -->
<flags LIBRARY_CXXFLAGS="-DALPAKA_DISABLE_ASSERT_ACC"/>
```
to CMSSW's `config/BuildFile.xml`.

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772, cms-sw/cmssw#43820 for el8_ppc64le_gcc12

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772, cms-sw/cmssw#43820 for el8_aarch64_gcc12

**Comment by fwyzard** [comment]
> ---> test testG4Refitter had ERRORS

is this a known failure, at least for non-x86 architectures ?

**Comment by mmusich** [comment]
> is this a known failure, at least for non-x86 architectures ?

yes :( , see https://github.com/cms-sw/cmssw/pull/43758#issuecomment-1918368879

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772 for el8_aarch64_gcc12

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772 for el8_ppc64le_gcc12

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772 for el8_ppc64le_gcc12

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#43772 for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
+externals

looks good, x86_64, aarch64, ppc64le externals built fine.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
