### PR TITLE
New spec files for WMArchive project

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to f50b70af89c4d1ff10f7671720d390068f0b949c on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_f50b70a-20160120-195511.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 30b8bc0b2aa195d4e160a127db1395da2324d10c on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_30b8bc0-20160120-204510.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 1c2e9dc93129f07319f80e5b9bcf609da007e3cf on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_1c2e9dc-20160120-221511.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to e325013eb8c5fcb5e7d9e2762fc36c3c881459e3 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_e325013-20160120-224511.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 7c718893b3d6caac12ac5c4d91799509fdc05171 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_7c71889-20160120-225510.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to f1e14bb0fa25148f3fc1de49857574550dd39e40 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_f1e14bb-20160121-134510.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 77ef1a344834ed9f03b2eb2365165f4253fbc907 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_77ef1a3-20160121-152510.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to ed67eb943687e79db3bc3e393aadb6efdb2e8ae7 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_ed67eb9-20160122-005513.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 39ef11a96837d3087547a5ab0c2cdcc29e405204 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_39ef11a-20160128-203516.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 158397fb161a1226d384cd889b9125739622b776 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_158397f-20160128-220516.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 4e5de987cde6f8c1c28d3c2477f5a8bb2346b0ac on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_4e5de98-20160204-165523.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to df858192c6bdd79f576143421413b8ad76c8b648 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_df85819-20160208-221515.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to b1bcde0ce3706fd297f4a180f6754def14c892fb on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_b1bcde0-20160208-224515.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 9f0fd325e813c33e954539221efe1149859b868c on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_9f0fd32-20160209-160515.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 8fdda518ebe634c7bff7da74e72dac8dba8977b9 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_8fdda51-20160209-202514.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to b073c8c34845f0c151d6e7097119abfaa71342e8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_b073c8c-20160225-151514.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 206b61cc4a18714e47a338cc696d95f735c4312e on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_206b61c-20160229-163512.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 3c43815ee7f0724772c6baf018cb357db1e6aacc on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_3c43815-20160308-174514.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 9ab6071d44f8963fec43ba7de2207b61e97dfcb6 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_9ab6071-20160311-214514.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to b996bbb15f394e193c0ac718f25545719563b229 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_b996bbb-20160314-165516.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 6624d0db58f2c1e6335a3bb504b53144c843f636 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_6624d0d-20160317-200515.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 79fa4ac72e3811d1788b61b637c21b3dce048859 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_79fa4ac-20160318-145727.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to e2dce345165a8d63f0a5babf2ceafaba015ab2be on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_e2dce34-20160318-184519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to b525df7ebe68ccc71e8c755ab92647ce0fea79b8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_b525df7-20160320-160515.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to c435e6cd8ebe9314e79280838b50b348f165e06e on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_c435e6c-20160320-203516.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 01dc3673f50bf20138cc446c886ff31621cfbe18 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_01dc367-20160321-141517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to db59ab6134dea850d4b5acdbe960ba8fc4008b18 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_db59ab6-20160321-163520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 4f099d1128bec60692a3a9e26bb683c8065784cd on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_4f099d1-20160321-190517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 9731297b80ab8157a5f1302e372d140c544a422c on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_9731297-20160321-194517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 16aa0075528fd8f3f7bd6d637ab3585248db7315 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_16aa007-20160321-200517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-214519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-215518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-221801.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-222520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-223519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-224518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-225518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-230518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-231518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-232517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-233518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-234519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160321-235517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-000518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-001518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-002518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-003517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-004517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-005517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-010518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-011517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-012518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-013518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-014519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-015518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-020518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-021518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-022518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-023518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-024518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-025517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-030518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-031517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-032517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-033517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-034517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-035518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-040518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-041517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-042517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-043517.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-045821.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-050519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-051520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-052518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-053518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-054519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-055518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-060519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-061519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-062519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-063519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-064519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-065519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-070520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-071519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-072518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-073518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-074519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-075519.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@vkuznet can you please squash all these commits (several of them are simply new version)? The bot builder is building RPMs for each of your commit and that's is spamming our email inbox.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-080519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-081519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-082519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-083519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-085519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-090519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-091519.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-092520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-093520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-094520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-095518.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-100520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-101520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 09e8195bd4d4d127faa098689f70a9d1f29c90c8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2072/test_09e8195-20160322-102520.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
There's a bug due to the limit of 30 feeds in the output of the github api the build-agent is using. I'll close this PR. Valentin, please open a new one.

**Comment by vkuznet** [comment]
@geneguvo Diego, I created new PR: https://github.com/cms-sw/cmsdist/pull/2217 I would appreciate if you'll review it and merge eventually. The new PR contains all specs required for WMArchive project and they are independent from anything else in cmsdist repository.

**Pull request closed without merging**
