### PR TITLE
Rivet 3.1.3 and YODA 1.8.5

### PR DESCRIPTION
**Pull request by mseidel42**

### CODE REVIEW

**Comment by mrodozov** [comment]
allow @intrepid42 test rights

**Comment by mrodozov** [comment]
please test
in case you have to rerun it (more patches on top etc)

**Comment by mseidel42** [comment]
please test

**Comment by mseidel42** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
