### PR TITLE
Update LLVM to version 14.0.6

### PR DESCRIPTION
**Pull request by smuzaffar**
Backport of #8201 
llvm 14 has been integrated for CLANG IBs and unit tests which were failing during PR tests worked in IB.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping bot

**Comment by smuzaffar** [comment]
lets wait for all the llvm 14 related code-checks/formats changes to go in cmssw.

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = CondFormats

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc11

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc11

**Comment by smuzaffar** [comment]
@perrotta @rappoccio @makortel , this is ready to go in 13.1.X. Note that few cmssw files will be formated with this update e.g. see [a] where `clang-tidy` and `clang-format` were run on full cmssw. We can not apply these changes before we merge llvm14 otherwise existing llvm12 reverts the formating. Any objections on getting this in now?

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_13_1_X_2023-04-20-1100/98/
- 7 files [clang-tidy](https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_13_1_X_2023-04-20-1100/98/code-checks.patch)
- 45 files [clang-format](https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_13_1_X_2023-04-20-1100/98/code-format-orig.patch)

**Comment by perrotta** [comment]
+orp
- No objection, provided all needed updates can get implemented in time for next week last open pre-release

**Comment by smuzaffar** [comment]
thanks @perrotta , I will merge this before 11h00 IB and then will open cmssw PRs for clang tidy/format

**Comment by smuzaffar** [comment]
+externals

**Comment by makortel** [comment]
No objections from me either. @smuzaffar Are you planning to make PRs to apply the changes in https://github.com/cms-sw/cmsdist/pull/8213#issuecomment-1522889473?

**Comment by smuzaffar** [comment]
yes @makortel , once we have the IB with llvm14 available then I will open cmssw PR

**Pull request merged**
