### PR TITLE
Updating GeneratorInterface-EvtGenInterface to to new tag V02-00-08

### PR DESCRIPTION
**Pull request by mrodozov**
cms-data/GeneratorInterface-EvtGenInterface#10

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov please create a PR for 71X too

**Comment by oozcelik** [comment]
@smuzaffar Does this PR compensate 90X? or another one is needed for 90X?

**Comment by smuzaffar** [comment]
a separate PR is needed

**Comment by oozcelik** [comment]
ok so could you please create one?

**Pull request merged**
