### PR TITLE
[10.2.X] Update MXNet to 1.5.0

### PR DESCRIPTION
**Pull request by mrodozov**
please test
redo of #5534 which needs also cms-sw. I merged it without reading this detail

### CODE REVIEW

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
this will be needed for the backport of https://github.com/cms-sw/cmssw/pull/28902

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
can this be merged?

**Comment by smuzaffar** [comment]
yes @slava77 , this is good to go in.
@silviodonato feel free to merge it when you want to build a next full 10.2 release.

**Comment by slava77** [comment]
> yes @slava77 , this is good to go in.
> @silviodonato feel free to merge it when you want to build a next full 10.2 release.

I wanted to check the CMSSW part at run time (locally) before signing off on the backport without the pain of building the external.
Do we have the PR builds on cvmfs now?

**Comment by smuzaffar** [comment]
> Do we have the PR builds on cvmfs now?

Not yet, it need a lot work change whihc are not in place yet.

**Comment by slava77** [comment]
@silviodonato 
if a full build of 10_2_X is coming, not blocking some quick patch releases, may I ask you to merge this external in the IB so that I can complete checks of cms-sw/cmssw#29063.
Thank you.

**Comment by slava77** [comment]
> @silviodonato
> if a full build of 10_2_X is coming, not blocking some quick patch releases, may I ask you to merge this external in the IB so that I can complete checks of [cms-sw/cmssw#29063](https://github.com/cms-sw/cmssw/pull/29063).
> Thank you.

ping

**Comment by silviodonato** [comment]
+1

**Pull request merged**
