### PR TITLE
Update tensorflow-sources.spec

### PR DESCRIPTION
**Pull request by davidlange6**
use sse3 as suggested in cms-sw/cmssw#19893

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlt** [comment]
`sse3` is not a valid option for `-march`.  The lowest you can go is `prescott` (the first one to enable SSE3). Another safe alternative could be `core2`. Later on, e.g. `nehalem`, already brings SSE4.2 which is probably still not available on every worker node (should be minority).

**Comment by davidlange6** [comment]
hi @davidlt - thanks - i couldn't find definitive documentation on this (undoubtedly because I didn't search for the right thing)

**Comment by davidlange6** [comment]
please test

(I'm trying to match what we did with openblas)

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Comment by davidlt** [comment]
The list is here: https://gcc.gnu.org/onlinedocs/gcc-6.4.0/gcc/x86-Options.html#x86-Options

**Pull request merged**
