### PR TITLE
update CrabClient-dev

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by belforte** [comment]
@smuzaffar in the spirit "speed up crab client deployment" which we discussed by mail, do you think we can dare merge such PR's myself so to proceed with the Jenkins build/upload/deploy ?
I am bit puzzled that differently from usual this has not been deployed on IB yet, maybe you are busy? maybe you were waiting for me to merge ? Myabe I am simply not patient enough ?
@ddaina FYI

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@belforte , normally it should not take this much time to merge crab changes. Yesterday we were in process of building CMSSW release and I did not want to integrate any thing while we are building the release.

**Comment by belforte** [comment]
thanks @smuzaffar 
@ddaina please feel free to give it a try to deploy crab using Jenkins, it should update just crab-dev with the new version which tests S3 in the background

**Comment by ddaina** [comment]
ok, having a look.

**Pull request merged**
