### PR TITLE
Gengetopt: Gengetopt is required to build Herwig7 

### PR DESCRIPTION
**Pull request by mharrend**
but it was requested to insert it as a single PR by @davidlt 

I also modified the configure script so that all the unnecessary stuff in the share folder is written to /tmp.
Should I choose another folder?

### CODE REVIEW

**Comment by davidlt** [comment]
All installations are done on unique installation path, then `rpmbuild` packs the files into packages from that specific prefix. You don't need to set `/tmp`, just keep it was it was, but after installation remove what's not need (e.g., `rm -rf %{i}/share`)

**Comment by mharrend** [comment]
Can you please sign off this request now?

**Comment by covarell** [comment]
please test

**Comment by covarell** [comment]
??? @degano

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
@cmsbuild please test
The above errors where caused by a bug in cms-bot testing script. Now should be fixed.

**Comment by mharrend** [comment]
Can you please now merge this request since all tests were successful and start then the tests for #2100 ?

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
lets add this topic to the ORP on Tuesday before merging. Thanks

**Comment by davidlt** [comment]
Reviewed.
Could you make the fellowing changes?

```
diff --git a/gengetopt.spec b/gengetopt.spec
index 31bc1f6..568df4f 100644
--- a/gengetopt.spec
+++ b/gengetopt.spec
@@ -4,14 +4,6 @@ Patch0: gengetopt-parallelbuild

 BuildRequires: autotools

-%if "%{?cms_cxx:set}" != "set"
-%define cms_cxx c++
-%endif
-
-%if "%{?cms_cxxflags:set}" != "set"
-%define cms_cxxflags -O2 -std=c++14
-%endif
-
 %prep
 %setup -q -n gengetopt-%{realversion}

@@ -21,20 +13,13 @@ BuildRequires: autotools
 autoreconf -fiv

 %build
-CXX="$(which %{cms_cxx}) -fPIC"
-CC="$(which gcc) -fPIC"
-PLATF_CONF_OPTS="--enable-shared --disable-static"
-
 # Only keep bin folder
-./configure $PLATF_CONF_OPTS \
-            --disable-silent-rules \
-           --prefix=%{i}\
-            CXX="$CXX" CC="$CC" CXXFLAGS="%{cms_cxxflags}"
+./configure --disable-silent-rules \
+           --prefix=%{i}

 make %{makeprocesses}

-rm -rf %{i}/share
-
 %install
 make install

+rm -rf %{i}/share
```

**Comment by smuzaffar** [comment]
please test

**Comment by mharrend** [comment]
Since the tests were succesfull, could you merge the PR now?

I would be glad to see the Herwig 7 PR #2100 also implemented rather soon in CMSSW.

**Pull request merged**
