### PR TITLE
Update ROCm to version 6.1.0

### PR DESCRIPTION
**Pull request by fwyzard**
Add amd-smi and ROCProfiler binaries and libraries.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#44777

**Comment by fwyzard** [comment]
`runtestPhysicsToolsPatAlgos` has been failing for weeks.

@smuzaffar do you think it would be possible to teach the bot to ignore failures that are already present in the base release ?

**Comment by smuzaffar** [comment]
> `runtestPhysicsToolsPatAlgos` has been failing for weeks.
> 
> @smuzaffar do you think it would be possible to teach the bot to ignore failures that are already present in the base release ?

we had discussed this in core sw meeting. One reason to not do this is that sometimes a PR is suppose to fix a failure but if it does not provide the right fix (and test still fails) then bot is going to ignore the error ( as we told it to ignore IB errors) and mark it as passed.

**Comment by smuzaffar** [comment]
ignore tests-rejected with ib-failure

**Comment by smuzaffar** [comment]
+externals

**Comment by fwyzard** [comment]
> One reason to not do this is that sometimes a PR is suppose to fix a failure but if it does not provide the right fix (and test still fails) then bot is going to ignore the error ( as we told it to ignore IB errors) and mark it as passed.

What about ignoring the tests that are expected to fail (because they fail in the IB), but report if they actually pass ?
This way if a PR is supposed to fix a test, it should be easy to see that it does.

**Comment by smuzaffar** [comment]
but if a PR is suppose to fix a test but it still fails during PR tests then bot will ignore the failure and mark PR test passed  ... right?

**Comment by fwyzard** [comment]
> but if a PR is suppose to fix a test but it still fails during PR tests then bot will ignore the failure and mark PR test passed ... right?

In such case I would expect the person that submitted the PR specifically to fix a test, the relevant L2, or the release manager, to check if the bot reports the test being fixed.

**Comment by smuzaffar** [comment]
> In such case I would expect the person that submitted the PR specifically to fix a test, the relevant L2, or the release manager, to check if the bot reports the test being fixed.

this is a big expectation :-) I will see if we can come up with reasonable solution

**Comment by fwyzard** [comment]
@cms-sw/orp-l2 could you merge this and https://github.com/cms-sw/cmssw/pull/44777 for the next IB ?

**Comment by rappoccio** [comment]
+1

**Comment by fwyzard** [comment]
thanks

**Comment by makortel** [comment]
Given https://github.com/cms-sw/cmssw/issues/44821 maybe we should revert this update before building 14_1_0_pre3? @cms-sw/orp-l2

**Comment by fwyzard** [comment]
OK for me to revert.

The main reason for the update was to fix the linker warnings about executable stack, but we can live with them.

Does https://github.com/cms-sw/cmssw/issues/44821 mean that we have to start building HIP/ROCm from sources ?

**Comment by makortel** [comment]
> Does [cms-sw/cmssw#44821](https://github.com/cms-sw/cmssw/issues/44821) mean that we have to start building HIP/ROCm from sources ?

That is certainly one way forward, but I'm not sure if we understand the full picture well enough to judge if that is the best (or only?) way forward. (e.g. I still wonder if there is something (non-)LTO-specific in this failure mode, or if the set of so-far-impacted IBs is just "luck")

**Comment by smuzaffar** [comment]
@makortel , all the IBs with this failure are non-lto ( https://github.com/search?q=repo%3Acms-sw%2Fcms-bot%20BUILD_OPTS%3Dno-lto&type=code )

**Pull request merged**
