### PR TITLE
Update bazel to 1 16 0

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
bazel builds tf doesn't. reminder for the next attempt

**Comment by mrodozov** [comment]
hunting for this:
ERROR: /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc6_amd64_gcc700/external/tensorflow-python3-sources/1.6.0-cms/build/0bc9c0a9d7196bc86f3dc9a3a3ab603d/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
leads to here:
https://github.com/tensorflow/tensorflow/issues/18450#issuecomment-381380000

a bit demotivational

**Comment by davidlange6** [comment]
Is updating tensorflow to 1.7.1 difficult for other reasons?

Cheers,
David


On 24 Aug 2018, at 15:10, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:


hunting for this:
ERROR: /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc6_amd64_gcc700/external/tensorflow-python3-sources/1.6.0-cms/build/0bc9c0a9d7196bc86f3dc9a3a3ab603d/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
leads to here:
tensorflow/tensorflow#18450 (comment)<https://github.com/tensorflow/tensorflow/issues/18450#issuecomment-381380000>

a bit demotivational

**Comment by mrodozov** [comment]
I didn't tried moving tf itself. I can try in Monday

**Pull request closed without merging**
