### PR TITLE
[10.4.X] [ROOT] Cherry-pick changes to resolve memory over-write due to execution of a I/O

### PR DESCRIPTION
**Pull request by smuzaffar**
https://github.com/root-project/root/pull/2861

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , can you please check if comparison looks good. I see some failures in `Tracking` for the following

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_4_X_2018-10-26-2300+4452/29120/136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM/

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_4_X_2018-10-26-2300+4452/29120/136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017/

**Comment by fabiocos** [comment]
@smuzaffar the difference affects just a few histograms, but it might not be trivial, I would prefer to have feedback by @slava77 @perrotta and possible tracking experts

**Comment by slava77** [comment]
I got confused a bit by the title "10.2.X" and the fact that this PR points to IB/CMSSW_10_4_X/gcc700.
The changes are in the comparisons of the HitPattern variables in tracks (from the old 80X AOD, supposedly) and the miniAOD made on top of them.
Given that there was a change in the HitPattern class layout, I can suspect that there is a problem with the schema evolution in this update.

**Comment by smuzaffar** [comment]
sorry my bad, I have fixed the title

**Comment by slava77** [comment]
please test

I wanted to check if the results are reproducible/repeatable.
It looks like further debugging will require a local build to debug the problem.

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@slava77 @perrotta there was any conclusion about these differences? I see that now @smuzaffar is producing again the set of plots for  a further test

**Comment by smuzaffar** [comment]
@fabiocos , the previous plots/logs were deleted that is why I am re-running.

**Comment by slava77** [comment]
I didn't find time to make a local root build for further investigation.
it would be nice to get something scram-able centrally.

**Comment by smuzaffar** [comment]
we can merge it for DEVEL IBs so that you can test there

**Comment by slava77** [comment]
> we can merge it for DEVEL IBs so that you can test there

sure, as long as it's the same 6.12 version in the DEVEL to compare with in the baseline as we have in the current 104X [just in case more may be already going on in the DEVEL which can affect this check/test]

**Comment by smuzaffar** [comment]
only difference b/w normal and DEVEL IBs is boost version every thing else should be same.

**Comment by smuzaffar** [comment]
@slava77 , this is now merged for DEVEL IBs. Tonight's 23h DEVEL IB should have it.

**Comment by slava77** [comment]
> @slava77 , this is now merged for DEVEL IBs. Tonight's 23h DEVEL IB should have it.

thanks.
let's see if I manage to get to this in the next couple of days

**Comment by smuzaffar** [comment]
@slava77 , did you find time to look in to this? DEVEL IBs should have it.

**Pull request merged**
