### PR TITLE
Redo - Fix for PS API query to the DB

### PR DESCRIPTION
**Pull request by mapsacosta**
Trying to redo the PR

### CODE REVIEW

**Comment by h4d4** [comment]
@mapsacosta Hi Maria,

Unfortunately, the build boot is still showing the errors[1] for these PRs.
Since, I'll need to check what is going there and I don't know how much time 
it could take, and the production tag to upgrade on production next Tuesday ready, 
maybe is late to include this change.
Which impact has this minor fix for the service functionality?
[1]
Checking for new commits:
Last commit is still the same: f8698a107ad925f3871410eeb47ae91fc97ec168
Pull Requests to test:
#4240, Redo - Fix for PS API query to the DB
#4239, Traceback (most recent call last):
  File "/build/dmwmbld/srv/current/config/dmwmbld/gh-bot", line 186, in <module>
    opts.cfgdir, opts.authfile)
  File "/build/dmwmbld/srv/current/config/dmwmbld/gh-bot", line 36, in pull_req_tester
    print "#%s," % pr['number'], pr['title']
UnicodeEncodeError: 'ascii' codec can't encode character u'\u02db' in position 30: ordinal not in range(128)

**Comment by mapsacosta** [comment]
Hi Lina,

It’s a critical fix. Can you by any chance please make the change directly? It’s only upgrading SiteDB to 2.7.3

**Comment by h4d4** [comment]
@mapsacosta Hi Maria,

I've updated sitedb.spec[1] and included the change in HG1808h tag,
it was also deployed on testbed.

I would say that something in PRs #4239 and #4240 is triggering the errors into the build boot, because for example after those, the boot has successful triggered and building PRs like[2]. I'll review this. Also if you realized something, please let me know :)


[1] https://github.com/cms-sw/cmsdist/commit/267818bb7e4dcc031798a4a944375a8389457663
[2] https://github.com/cms-sw/cmsdist/pull/4238

**Comment by h4d4** [comment]
to 19b6b363e03c2e2544975156d1e8207c7acd5d6e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4240/test_19b6b36-20180810-191221.log" target="_blank">here</a>.

**Comment by davidlange6** [comment]
is this obsolete?

**Comment by mrodozov** [comment]
@h4d4 can we close this PR ?

**Comment by h4d4** [comment]
@mrodozov 
Closed.

**Comment by h4d4** [comment]
-1 to 19b6b363e03c2e2544975156d1e8207c7acd5d6e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4240/test_19b6b36-20180911-163254.log" target="_blank">here</a>.

**Pull request closed without merging**
