### PR TITLE
[10_6_X] bumping up sherpa to 2.2.15

### PR DESCRIPTION
**Pull request by shimashimarin**
Bumping up Sherpa to 2.2.15 based on the discussion in this thread: https://cms-talk.web.cern.ch/t/sherpa-event-generation-segfault-with-privately-generated-sherpack-for-z-jets/23629/9

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
backport of https://github.com/cms-sw/cmsdist/pull/8450

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
assign generators

@rappoccio  @antoniovilela feel free to merge it for 10.6.X

**Comment by menglu21** [comment]
+1

**Comment by smuzaffar** [comment]
@rappoccio @antoniovilela feel free to merge it for 10.6.X and incldue it in next 10.6 release

**Comment by rappoccio** [comment]
+1

**Comment by mseidel42** [comment]
Would it be possible to have a new release with this?

**Comment by antoniovilela** [comment]
> Would it be possible to have a new release with this?

Yes.

**Pull request merged**
