### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@guitargeek , ROOT master (latest commit) failed to build with error [a]  . Looks like  it might be due to https://github.com/root-project/root/commit/d217838b19288144903cc2b02ee88b9485bf92e9 change. Note that cmssw root uses external xrootd (5.6.3). Do we need to update xrootd?

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5b1a96/36784/externals/root/6.31.01-7095e99d5bd79caa78d7ec02eb58fd93/log
```
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/lcg/root/6.31.01-7095e99d5bd79caa78d7ec02eb58fd93/root-6.31.01/net/netxng/src/TNetXNGFile.cxx:22:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc12/lcg/root/6.31.01-7095e99d5bd79caa78d7ec02eb58fd93/root-6.31.01/net/netxng/inc/TNetXNGFile.h:27:10: fatal error: XrdCl/XrdClFileSystem.hh: No such file or directory
   27 | #include <XrdCl/XrdClFileSystem.hh>
```

**Comment by guitargeek** [comment]
Yes, you need to update xrootd to [5.6.4](https://github.com/xrootd/xrootd/releases/tag/v5.6.4).

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals 

looks good for root master

**Pull request merged**
