### PR TITLE
[Do not merge] Testing PR tests results with LTO

### PR DESCRIPTION
**Pull request by aandvalenzuela**
We expect not differences

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
test parameters:
- full_cmssw = true

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
looks good, LTO enable full rebuilt also do not show any comparison differences

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41269

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41269

**Pull request closed without merging**
