### PR TITLE
[gsl] Updated tool file to add gsl/bin in to PATH env

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by agrohsje** [comment]
hi @smuzaffar, will you also back port to 10_6 and maybe 12_4 ? @cms-sw/generators-l2

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Comment by smuzaffar** [comment]
> hi @smuzaffar, will you also back port to 10_6 and maybe 12_4 ? @cms-sw/generators-l2

For other release cycles and already build releases, we can fix it via SCRAM global runtime hooks. SCRAM global runtime hooks are run when one runs `cmsenv`. I can add a hook to include `gsl/bin` in `PATH` so that old releases can pick `gsl-config` from cms externals

**Comment by agrohsje** [comment]
Thanks @smuzaffar. Sounds good. Please let me know when this becomes available so that we can update the affected gridpacks.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/8712 adds scram site based runtime hook. I will let you know once it is merged and deployed on cvmfs.

**Comment by smuzaffar** [comment]
@agrohsje , new scram hook is now available on cvmfs. It now properly sets the gsl/bin path for already existing releases
```
lxplus> scram p  CMSSW_10_6_21
lxplus> cd CMSSW_10_6_21 
lxplus> cmsenv
lxplus> which gsl-config
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/gsl/2.2.1-pafccj2/bin/gsl-config
lxplus> gsl-config --prefix
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/gsl/2.2.1-pafccj2
lxplus> gsl-config --libs
-L/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/gsl/2.2.1-pafccj2/lib -lgsl -lgslcblas -lm
```

**Pull request merged**
