### PR TITLE
Backport OpenBLAS fixes [10_6_X]

### PR DESCRIPTION
**Pull request by kpedro88**
This is a combined backport of #5063 and #5091. The goal is to propagate the DeepAK8 speedup to the ultra legacy release (for both production and analysis).

attn: @hqucms @smuzaffar @slava77

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by fabiocos** [comment]
@kpedro88 besides the impact on DeepAK8 this is impacting also some generators, where the BLAS version by gsl is replaced by OpenBLAS. I do not recall we observed any problem related to this, but it is good that @qliphy @agrohsje are aware of this

**Comment by fabiocos** [comment]
please test workflow 511.0

**Comment by fabiocos** [comment]
@smuzaffar the error in the unit test seems to be disconnected to this PR (likely a transient issue we see from time to time)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
