### PR TITLE
updates sherpa to 2.2.1

### PR DESCRIPTION
**Pull request by iahmad-khan**
https://github.com/cms-sw/cmsdist/issues/2410

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by thuer** [comment]
Thanks for taking care of this!
In 2.2.1 they changed the configure option for the UFO model and you have to additionally have --enable-ufo to get the executable.
Also would it be possible to add
`<runtime name="SHERPA_LIBRARY_PATH" value="$SHERPA_BASE/lib/SHERPA-MC" type="path"/>'`
to the sherpa-toolfile.spec?
 This is the location the dynamic library loader of sherpa searches for libraries.

**Comment by iahmad-khan** [comment]
@thuer tested in https://github.com/cms-sw/cmsdist/pull/2415

**Comment by thuer** [comment]
@iahmad-khan thanks a lot, fine for me!

**Comment by smuzaffar** [comment]
this has been forward ported via stable branch https://github.com/cms-sw/cmsdist/pull/2415

**Pull request closed without merging**
