### PR TITLE
Update to CUDA 11.0.2 (11.0.207)

### PR DESCRIPTION
**Pull request by fwyzard**
Update to CUDA 11.0.2:
  - CUDA version 11.0.207
  - NVIDIA drivers version 450.51.05

Various bug fixes.

See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-new-features .

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc820

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc820

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
