### PR TITLE
[CXXMODULE] Remove root_12193 patch for rootmodule

### PR DESCRIPTION
**Pull request by aandvalenzuela**
`CXXMODULE` iB fails when applying this patch. After checking it, I think it might not be needed anymore (See https://github.com/cms-sw/root/blob/cms/master/94b3064bb5/interpreter/cling/include/cling/std.modulemap#L376-L380)

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
test parameters:

- full_cmssw = true

**Comment by aandvalenzuela** [comment]
please test

**Comment by davidlange6** [comment]
Right - that PR got merged into master. Thanks!

**Comment by smuzaffar** [comment]
as externals build so this looks good to go in ( module Ibs are broken anyway)

**Pull request merged**
