### PR TITLE
Updated t0.spec

### PR DESCRIPTION
**Pull request by andresfelquintero**
I changed the t0 version to 2.1.6 and Wmcore version to 1.2.6.patch1 .

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 782228f592bfbeb0da935874409f15f0be786666 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5269/test_782228f-20191008-220510.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
changes look good, Andres

**Comment by h4d4** [comment]
@andresfelquintero Andres, 

would you guys need to include this change into next CMSWEB relase?
If yes, would you please make a PR and ask for its inclusion into: 
https://gitlab.cern.ch/cms-http-group/doc/issues/189

Best Regards, Lina.

**Comment by amaltaro** [comment]
@h4d4 Lina, this is the T0 WMAgent spec, which means it does not go to CMSWEB. Please merge it at your convenience.

**Comment by h4d4** [comment]
@amaltaro @andresfelquintero Andres, Alan,

Ok, in this case the commit was just merged.

Best Regards, Lina.

**Pull request merged**
