### PR TITLE
Use HTCondor python bindings from pip (wheel binaries)

### PR DESCRIPTION
**Pull request by khurtado**
Use wheel binaries from HTCondor 9.2.0 rather than building our own.

Related issue:
https://github.com/dmwm/WMCore/issues/10256

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to b7c7fdcd66becfcc9fc9677779d7da39f1c14b92 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7379/test_b7c7fdc-20211011-191503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 5e0a277dff27ec2a1c4425b376c76e56e7f7726c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7379/test_5e0a277-20211011-193503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@khurtado Kenyi, I managed to test it with the RPM you had uploaded to your cmsrep private repo, and it seems to be working well.

Given that we are now able to build it from PyPi, I think it would be better if we actually rename these spec files to py2-htcondor.spec and py3-htcondor.spec. I will cherry-pick your changes and create the new specs and build an official patch2 release.

Out of curiosity, how did you identify all those libraries to be added in the `Provides` sentence/macro?

**Comment by khurtado** [comment]
@amaltaro Awesome!

Sounds good to me.
The libraries were listed in the error message the first time, when the RPM
tried to install (before I would out those Provides: lines) and determined
those were needed.

**Comment by amaltaro** [comment]
I see, thanks Kenyi.
I'm going to run a final test now - with an official build - on both CERN and FNAL agents. I hope I'm wrong, but I have the impression that the vomsapi patch was actually required for FNAL nodes...

**Comment by amaltaro** [comment]
And this is working fine on the FNAL nodes as well. 
@khurtado since this has been merged with https://github.com/cms-sw/cmsdist/pull/7383, shall we close this PR?

**Comment by khurtado** [comment]
Yes, sounds good to me!

**Comment by amaltaro** [comment]
close

**Pull request closed without merging**
