### PR TITLE
Fix CherryPy 18.8.0 requirements

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes https://github.com/dmwm/WMCore/issues/11080
Superseeds https://github.com/cms-sw/cmsdist/pull/8043

### CODE REVIEW

**Comment by amaltaro** [comment]
@muhammadimranfarooqi Imran, I believe the build bot got stuck. Could you please have a look at it and restart it if needed? Thanks

**Comment by muhammadimranfarooqi** [comment]
Hi @amaltaro 
There are errors in build logs with this PR. 

```
[dmwmbld@vocms055 ~]$ less /build/dmwmbld/srv/logs/dmwmbld/dmwmbld-20220826


#8045, Fix CherryPy 18.8.0 requirements
#8043, Traceback (most recent call last):
  File "/build/dmwmbld/srv/current/config/dmwmbld/gh-bot", line 187, in <module>
    opts.cfgdir, opts.authfile)
  File "/build/dmwmbld/srv/current/config/dmwmbld/gh-bot", line 36, in pull_req_tester
    print "#%s," % pr['number'], pr['title']
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 69: ordinal not in range(128)
```

**Comment by muhammadimranfarooqi** [comment]
+1 to ba684944975e3e282227d47c27c358598e49787e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8045/test_ba68494-20220826-145502.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
With these changes in, I am now able to start all the WMCore central services. A quick look at the ReqMgr2 logs shown that basic REST calls are properly served as well. I am going to merge it and we can proceed with further validation, maybe even in testbed.
@vkuznet thanks for providing initial changes in #8043

**Comment by amaltaro** [comment]
merge

**Pull request merged**
