### PR TITLE
Update llvm/clang to 7.0.0-svn334210 (prerelease) 

### PR DESCRIPTION
**Pull request by fwyzard**
Also
  - only add CUDA dependency on amd64 (backport from gcc700 branch)
  - enable support for compiing CUDA code to NVPTX on amd64
  - disable automatic package dependencies

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
Mhm, this did build fine on top of CMSSW_10_2_0_pre5 for slc7_amd64_gcc700.
Do we expect changes related to the failure in the gcc810 IB ?

**Comment by smuzaffar** [comment]
again the problem is that cuda is not going well with gcc > 7
```
FAILED: projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/omptarget-nvptx_generated_critical.cu.o 
cd .../llvm/7.0.0-svn334210/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src && /cvmfs/cms-ib.cern.ch/nweek-02529/slc7_amd64_gcc810/external/cmake/3.11.1/bin/cmake -E make_directory .../llvm/7.0.0-svn334210/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/. && /cvmfs/cms-ib.cern.ch/nweek-02529/slc7_amd64_gcc810/external/cmake/3.11.1/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=.../llvm/7.0.0-svn334210/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/./omptarget-nvptx_generated_critical.cu.o -D generated_cubin_file:STRING=.../llvm/7.0.0-svn334210/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/./omptarget-nvptx_generated_critical.cu.o.cubin.txt -P .../llvm/7.0.0-svn334210/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/omptarget-nvptx_generated_critical.cu.o.Release.cmake
In file included from /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc810/external/cuda/9.2.88-gnimlf/include/host_config.h:50,
                 from /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc810/external/cuda/9.2.88-gnimlf/include/cuda_runtime.h:78,
                 from <command-line>:
/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc810/external/cuda/9.2.88-gnimlf/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
 #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  ^~~~~
CMake Error at omptarget-nvptx_generated_critical.cu.o.Release.cmake:215 (message):
  Error generating
  .../llvm/7.0.0-svn334210/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/./omptarget-nvptx_generated_critical.cu.o
```

**Comment by fwyzard** [comment]
Thanks - I keep tripping on the fact that the last shown error is not the real problem :-(

Indeed I can reproduce this locally for a gcc 8 build - I will investigate if it is possible compile llvm openmp support with clang itself instead of nvcc, and/or patch the header work around the error.

**Comment by davidlange6** [comment]
hi @fwyzard - is this obsolete now?

**Comment by fwyzard** [comment]
Yes, in the sense that there are much newer version of llvm 7 out by now (rc2 was tagged  a couple of days ago).
No, in the sense that I would still like to include llvm/clang 7 with CMSSW 10.3.x.

**Comment by davidlange6** [comment]
makes sense to me (at least once its not an rc) - but anyway, i was just trying to close prs the are not going to get merged. do you plan to update this one or start over later?

**Comment by fwyzard** [comment]
On Fri, 24 Aug 2018, 12:15 David Lange, <notifications@github.com> wrote:

> Do you plan to update this one or start over later?


I can do it either way - what do you prefer ?

**Comment by fwyzard** [comment]
Superseded by #4353 .

**Pull request closed without merging**
