### PR TITLE
[12.0] Update UTM 0.9.1

### PR DESCRIPTION
**Pull request by mrodozov**
backport of #7281
https://github.com/cms-sw/cmsdist/pull/7281#issuecomment-928020346

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@qliphy @perrotta , this is `utm` backport for 12.0.X release cycle. Feel free to merge it

**Comment by qliphy** [comment]
+1

**Comment by dildick** [comment]
Thanks for doing this!

**Pull request merged**
