### PR TITLE
[ROOT628] Updated root to tip of branch v6-28-00-patches

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@makortel @Dr15Jones , while testing [ROOT 6.28 changes](https://github.com/root-project/root/compare/4376f61...8735554) we now see this FW unit tests failing [a]. Looks like with new changes of root now CMS requires at least 150MB more virtual memory.  Do you see any obvious change in root which might have contributed to this increase?

@hahnjo, could it be due to https://github.com/root-project/root/commit/873555425373e6528873f9cd87d4c0430c3dc514  llvm module path change? 

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1f9abe/34654/unitTests/src/FWCore/Services/test/TestFWCoreServicesDriver_resource/testing.log
```
===== Test "TestFWCoreServicesDriver_resource" ====
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 08-Sep-2023 03:14:28.793 CEST
----- Begin Fatal Exception 08-Sep-2023 03:14:28 CEST-----------------------
An exception of category 'ExceededResourceVSize' occurred while
   [0] Calling EventProcessor::runToCompletion (which does almost everything after beginJob and before endJob)
Exception Message:
Exceeded maximum allowed VSize of 1 GB (VSize is 1.15728)
----- End Fatal Exception -------------------------------------------------
Failure using /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_13_3_ROOT628_X_2023-09-06-2300/src/FWCore/Services/test/test_resource_succeed_cfg.py: status 94

---> test TestFWCoreServicesDriver_resource had ERRORS
```

**Comment by smuzaffar** [comment]
With existing root 6.28 i.e. [commit 4376f61](https://github.com/root-project/root/commit/4376f61) `cmsRun` shows `Vsize 0.676969G`

**Comment by smuzaffar** [comment]
I tried [reverting](https://github.com/cms-sw/root/pull/187) https://github.com/root-project/root/commit/873555425373e6528873f9cd87d4c0430c3dc514 but still cmsRun process complains about high `vsize`, so https://github.com/root-project/root/commit/873555425373e6528873f9cd87d4c0430c3dc514 is not the causing this

**Comment by smuzaffar** [comment]
#8689 shows that just rebuilding root (without any other update anyway shows high vsize). Let get this in and see if in IBs we do get this unit test failure

**Comment by hahnjo** [comment]
> @hahnjo, could it be due to [root-project/root@8735554](https://github.com/root-project/root/commit/873555425373e6528873f9cd87d4c0430c3dc514) llvm module path change?

Hi @smuzaffar, that commit is only about CMake modules used during configuration time, not even during build itself. It does not affect memory usage while running ROOT, ie nothing to do with (runtime) C++ modules.

**Pull request merged**
