### PR TITLE
Update sigcpp to 3.2.0

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
Please test

**Comment by iarspider** [comment]
please test with #7662

**Comment by iarspider** [comment]
Just in case...

**Comment by smuzaffar** [comment]
please test
lets re-test based on clean IB ( no idea why there are too many comparison differences)

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
