### PR TITLE
bump crab-dev to v3.241211

### PR DESCRIPTION
**Pull request by belforte**
add support for scram microarch

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@belforte , crab-dev job submit fails with error
```
The server answered with an error.
Server answered with: Invalid input parameter
Reason is: Excess keyword arguments, not validated kwargs='{'jobminuarch': 'x86-64-v3'}'
Error Id: f49855fc6f1c17622662ae9ae96437d8
```

I guess crab server needs an update ... right?

**Comment by belforte** [comment]
Yes, by design :-)
Where does the build test submit to ?
The server update is ready and deployed in preprod (cmsweb-testbed.cern.ch) but not in production.
It is convenient to have `crab-dev` updated for doing more tests.

**Comment by smuzaffar** [comment]
+externals

**Comment by belforte** [comment]
@smuzaffar production crab server has been updated. submission with `crab-dev` from IB will work now

**Pull request merged**
