### PR TITLE
Two fixes for CRAB3 client June release

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by mmascher** [comment]
Add a missing `import os` and include header directory in the sandbox.

**Comment by geneguvo** [comment]
+1 to 45a9aece2c09ca98bd87f098d66b750b2db702a0 on slc6_amd64_gcc481.

**Comment by mmascher** [comment]
Changed version number on the commit so that this will be used for the production release tomorrow.

**Comment by geneguvo** [comment]
+1 to 775fb5cf42b2cb8ffc230c9feccabf44f08db23a on slc6_amd64_gcc481.

**Pull request closed without merging**
