### PR TITLE
Update geant4 and geant4-parfullcms.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-externals/geant4/commit/ba06375bc3f709e90555746c17f2daae663e2924
https://github.com/cms-externals/parfullcms/commit/15512c809659aafd4e52b6e31acf1cc8737cfe1d

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
one unit test is already failing in IB and I do not see any reason why the other unit tests failure relates to this PR. I would suggest to include this PR when ready.

**Comment by ghost** [comment]
@civanch given the above I'm merging this one.

**Pull request merged**
