### PR TITLE
py2-Jinja2 is needed by DXR

### PR DESCRIPTION
**Pull request by smuzaffar**
FYI @davidlange6

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
Dxr needs a unit test - can we make one… (and to use python3..)

You will also need to add back MarkupSafe for python2...

**Comment by smuzaffar** [comment]
@davidlange6 , I will check if I can add a simple unit test for dxr.
No need to explicity add py2-MarkupSafe, the py2-dxr ( https://github.com/cms-sw/cmsdist/pull/6988/files#diff-a8cf4578268220533c594eca1b9ed79e4d1a61fd390f1fdd53c39a5b74417ce8R5) should bring it in indirectly.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33984

**Comment by davidlange6** [comment]
Great - thanks for the unit test!

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
