### PR TITLE
Update DD4Hep

### PR DESCRIPTION
**Pull request by mrodozov**
Get latest commits from dd4hep

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
lets retry

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
@ianna @cvuosalo @civanch is this considered as finally ready? At least I do not see any more failures in unit tests

**Comment by mrodozov** [comment]
@fabiocos the tests are over the latest commit before the discussed breaking commit. That's why the test passed

**Comment by cvuosalo** [comment]
@mrodozov Are you currently working on fixing this problem? I would like to help, but I am confused. I tried to reproduce the problem but could not.

**Comment by smuzaffar** [comment]
please test
@cvuosalo , no one is looking in to it. @mrodozov  updated the PR to move back to the commit which works but we would like to move forward with latest development of DD4Hep. I just updated the PR to the commit which was failing. We ned to resolve this issue.

**Comment by cvuosalo** [comment]
@smuzaffar How can I re-create this error? I tried to get this PR with:
```
cms-merge-topic --unsafe 5376
```
but it didn't work. When I run the unit tests, they don't encounter this error.

**Comment by smuzaffar** [comment]
@cvuosalo , this is cmsdist PR (not cmssw) so cms-merge-topic is not going to work.
@mrodozov , please provide the instruction to @cvuosalo on how to test this.

**Comment by mrodozov** [comment]
@cvuosalo , assuming you have access to cmsdev22 , please follow this:
```
ssh lxplus
ssh cmsdev22
mkdir -p /build/cvuosalo ; cd /build/cvuosalo
scram p CMSSW_11_1_X_2019-12-18-2300 // or any later release of choice that is "production"
cp /build/mrodozov/dd4hep/build_dd4hep/slc7_amd64_gcc820/external/dd4hep-toolfile/1.0-cms/etc/scram.d/dd4hep* /build/cvuosalo/CMSSW_11_1_X_2019-12-18-2300/config/toolbox/slc7_amd64_gcc820/tools/selected/ 
scram setup
git-cms-addpkg DetectorDescription/DDCMS
scram b -j 16
scram b runtests
```
This will fail exactly as in the test
This sets up the new version of dd4hep for which DetectorDescription/DDCMS needs a fix. 
Let me know if anything doesn't work as expected

**Comment by cvuosalo** [comment]
Some clues about this problem can be found here:
https://github.com/AIDASoft/DD4hep/commit/aa680e7b1638631936c6d79d114410432305a693

**Comment by cvuosalo** [comment]
I may have a fix for this problem.

**Comment by cvuosalo** [comment]
CMS PR 28671 provides a fix for the failing unit tests.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar I think we may merge this, and cms-sw/cmssw#28671 in parallel to verify whether everything is ok with this new DD4hep version

@silviodonato FYI

**Comment by smuzaffar** [comment]
+1

**Pull request merged**
