### PR TITLE
Pythia8.240 fix for re-initialization

### LINKED ISSUE #5225: Update pythia8 to fix re-initialization
The latest fix to pythia8 provided by @smrenna cms-externals/pythia8#14 should be integrated to build CMSSW_11_0_0_pre8

### PR DESCRIPTION
**Pull request by fabiocos**
Resolves: #5225
Addition of cms-externals/pythia8#14 by S. Mrenna fixing the issue cms-sw/cmssw#27918

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 1361.181

**Comment by mrodozov** [comment]
Resolves: #5225 
Seems I cannot do that (the Resolve trick) if the PR is not mine

**Comment by fabiocos** [comment]
Resolves: #5225

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
