### PR TITLE
update openblas and a few more python tools

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by mrodozov** [comment]
+1

**Comment by mrodozov** [comment]
aaaand of course openblas broke tensorflow on arm :joy:

**Comment by davidlange6** [comment]
nice:) pretty surprising - can you just ifdef around the versions again?

**Comment by smuzaffar** [comment]
error is "virtual memory exhausted: Cannot allocate memory" try re-building

https://cmssdt.cern.ch/SDT/jenkins-artifacts/build-any-ib/CMSSW_10_6_X_2019-04-24-1100/slc7_aarch64_gcc700/74652/external/tensorflow-sources/1.6.0-pafccj3/log

**Comment by mrodozov** [comment]
I've restarted the IB just now. I don't remember how I decided it's openbals as tf doesn't depend on it. Anyway, it's rebuilding.

**Pull request merged**
