### PR TITLE
updates data-RecoBTag-Combined to version v01-00-03

### PR DESCRIPTION
**Pull request by iahmad-khan**
https://github.com/cms-data/RecoBTag-Combined/pull/4

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by slava77** [comment]
@iahmad-khan 
please clarify when do you expect this to be merged
we now have https://github.com/cms-sw/cmssw/pull/17247 waiting for the external files from this PR

**Comment by smuzaffar** [comment]
backport failed
**Reason:**

Error: Failed to cherry-pick commits. Please backport this PR yourself.
```Automatic cherry-pick failed.  After resolving the conflicts,
mark the corrected paths with 'git add <paths>' or 'git rm <paths>'
and commit the result with: 

        git commit -c 42937f99d86c03ba41e69e50a85793f9ce493f7b

```

**Comment by smuzaffar** [comment]
backport failed
**Reason:**

Error: Failed to cherry-pick commits. Please backport this PR yourself.
```Automatic cherry-pick failed.  After resolving the conflicts,
mark the corrected paths with 'git add <paths>' or 'git rm <paths>'
and commit the result with: 

        git commit -c 42937f99d86c03ba41e69e50a85793f9ce493f7b

```

**Pull request merged**
