### PR TITLE
Upgrade frontier client to v 2.8.19

### LINKED ISSUE #2230: Please backport frontier_client 2.8.19 and pacparser 1.3.5 to older CMSSW release lines
frontier_client 2.8.18 and pacparser 1.3.5 is in CMSSW_8_1_0_pre[12] and hasn't seen any problems.  Please start backporting it to older release lines that still expect to see active use for quite a while, as was attempted for version 2.8.14 in issue #1952.

### PR DESCRIPTION
**Pull request by iahmad-khan**
Fix #2230

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by ghost** [comment]
@iahmad-khan can you test locally and check what's the problem here?

**Comment by iahmad-khan** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , we do not understand the reason why the addOnTest  pat1 https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2337/206/addOnTests/pat1/ is failing .
Now Ijaz is testing this PR locally by building the full CMSSW. You can start the 7_1_24 build but in case we find something strange then we will let you know.

**Pull request merged**
