### PR TITLE
Move boost to python3

### PR DESCRIPTION
**Pull request by davidlange6**
likely this will break unit tests. Trying to find out which ones.

### CODE REVIEW

**Comment by davidlange6** [comment]
test parameters:
 -  full_cmssw = true

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
fyi @smuzaffar  - only one unit test fails - which is fixed by making getPayloadData.py use /usr/bin/env python3. So I can make a PR to change that

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
test parameters:
  - full_cmssw = true
  - pull_request = cms-sw/cmssw#34298

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
@smuzaffar - did this not run the tests with cmssw#34298?

**Comment by davidlange6** [comment]
hum, to answer my question - yes, the cmssw PR was used.

**Comment by davidlange6** [comment]
```===== Test "testGetPayloadData" ====
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_0_X_2021-06-30-2300/bin/slc7_amd64_gcc900/getPayloadData.py", line 292
    except ValueError, e:```
    
   ah - this error is in the PY3 IB:(

**Comment by smuzaffar** [comment]
yes it did. There are few py3 related changes needed for getPayloadData script itself

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
this should be merged along with cms-sw/cmssw#34298

**Comment by qliphy** [comment]
merge

**Pull request merged**
