### PR TITLE
[Geant4] Update to 11.2.0 for G4VecGeom IBs

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , Thanks!

**Comment by smuzaffar** [comment]
@civanch , looks like new Geant4 version requires vecgeom 1.2.6 [a]. Note that we have issues/test failures with Vecgeom 1.2.6


[a]
```
CMake Error at cmake/Modules/G4OptionalComponents.cmake:298 (find_package):
  Could not find a configuration file for package "VecGeom" that is
  compatible with requested version "1.2.6".
```

**Comment by civanch** [comment]
@smuzaffar , this condition to set minimal VecGeom 1.2.6 was introduce at last minute before G4 11.2 was out. Developers are saying that in VecGeom 1.2.6 important fixes are done to be coherent with G4 11.2.

Several peoples tried gdml geometry files, which I produced in 14_0_X using DD4hep and DB geometry for 2023. This trapezoid description was not changed since long and in all standalone tests they claim no problems.

So, there are two possibilities: a) take this CMakeList.txt from cand02; b) migrate to VecGeom 1.2.6. Of course, b) would be a natural way. Is it possible to try both G4 11.2 and  VecGeom 1.2.6 simultaneously?

**Comment by smuzaffar** [comment]
yes , we can test vecgeom 1.2.6 with this update

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , our geometry colleagues rolled back modifications they introduced in VecGeom and they now provide VecGeom 1.2.7, which may work with CMSSW.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@civanch , VecGeom 1.2.7 looks good. Previously failing addon tests and unit tests are now running fine

**Comment by smuzaffar** [comment]
+externals

looks good for G4Vecgeom IBs

**Pull request merged**
