### PR TITLE
New WMArchive: add Monit support; simplify deps, switch to new WMCore version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 20da8a457cd4ec00fe18c6e641dea884ec395924 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5332/test_20da8a4-20191105-165004.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 6253aa8f4acd5e402917282db9b1ddf50530ff87 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5332/test_6253aa8-20191105-174006.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to c57a3a9bd75a8d0be098ab7a9c20ad276e2563a1 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5332/test_c57a3a9-20191105-193005.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 27dbb70eefb2e1b46199a94ab20d8fdbe9f3f8e9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5332/test_27dbb70-20191105-195006.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to d0cbead7323077a7c6529cbe61fb7927ada0a9b2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5332/test_d0cbead-20191105-201005.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , Muhammad could you please merge this PR. It brings new WMArchive version. Since WMArchive deployment cycle is not constrained by cmsweb one we can merge WMArchvie PRs at any time.

**Pull request merged**
