### PR TITLE
Updated t0.spec

### PR DESCRIPTION
**Pull request by andresfelquintero**
Changed t0 release version and wmcore tag.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
to efb5105379c41071c5f6b35043e6e6206ef3d26a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5357/test_efb5105-20191115-223825.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@h4d4 can you please trigger the tests again?

**Comment by amaltaro** [comment]
or @muhammadimranfarooqi  please trigger the tests once again

**Comment by muhammadimranfarooqi** [comment]
to efb5105379c41071c5f6b35043e6e6206ef3d26a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5357/test_efb5105-20191119-103005.log" target="_blank">here</a>.

**Comment by andresfelquintero** [comment]
Hello, can you try it again please? I think that the new tag was not on the t0 main repository. If it passes then you can merge it right away.

**Comment by muhammadimranfarooqi** [comment]
+1 to efb5105379c41071c5f6b35043e6e6206ef3d26a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5357/test_efb5105-20191120-073005.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@andresfelquintero , @amaltaro 
This PR has been merged and will be included HG1912b tag.

**Pull request merged**
