### PR TITLE
Build/install python packages with pip; upgrade several python specs

### PR DESCRIPTION
**Pull request by amaltaro**
Trying to superseed https://github.com/cms-sw/cmsdist/pull/4479 , given that cms bot doesn't like that PR...

Summary of changes is:
* update pyopenssl version which has two security vulnerabilities, as reported here:
https://github.com/dmwm/WMCore/network/alert/requirements.txt/pyopenssl/closed
* updated build-with-pip to be in sync with the CMSSW branch (rules for py2-* packages installed via pip)
* updated several other specs (mostly python libraries), reusing those from the CMSSW 10_4_X branch when possible, including numpy and scipy. Still a bunch to be updated though....
* and renamed a couple of specs

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 33a7f8c62ea2ce8ddd4a50501445d4846ed57567 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4640/test_33a7f8c-20190115-180509.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@h4d4 from my side, these changes are good to go. I'll also request it to be merged via the gitlab ticket, but the sooner we have this in, the better. I still have one or two other changes that will depend on this.

FYI @vkuznet @belforte

**Comment by belforte** [comment]
sorry for being thick, why/how am I involved ? Should we look at using PIP in/for CRAB somehow, or is this to mean that now we will update pyopenssl in CMSWEB and we need to make sure it works for CRAB (gee.. I forgot all about that...)

**Comment by amaltaro** [comment]
It's just to let you know that one of the CRAB dependencies (pyopenssl) has been updated (and maybe a few others). Just in case you see weird things when you cut a new CRAB release.

**Pull request merged**
