### PR TITLE
[llvm] Update to version 14.0.6

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_4_CLANG_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung , I think cms clang-tidy checks need updates for clang 14.0.0. clang-tidy-checks failed with [a]. I tried to get your changes from https://github.com/cms-externals/llvm-project/commits/cms/release/12.x/fed4134 in to https://github.com/cms-externals/llvm-project/commits/cms/release/14.x/3f43d80 branch. Can you please check and provide a fix. Note that without cms clang-tidy checks these tests passed [b]

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-53867e/23472/external/llvm/14.0.0-1e54cb1887a6207267482ee7b02b1796/log
```
  Unsupported      :   1
  Passed           : 520
  Expectedly Failed:   2
  Failed           : 637
```
```
Running ['clang-tidy', '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc10/external/llvm/14.0.0-1e54cb1887a6207267482ee7b02b1796/build/tools/clang/tools/extra/tes
t/clang-tidy/infrastructure/Output/objc-arc-and-properties.m.tmp.m', '-fix', '--checks=-*,bugprone-suspicious-semicolon', '-config={}', '--', '-fobjc-abi-version=2', '-fobjc-arc', '-fblocks', '-
nostdinc++']...
clang-tidy /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc10/external/llvm/14.0.0-1e54cb1887a6207267482ee7b02b1796/build/tools/clang/tools/extra/test/clang-tidy/
infrastructure/Output/objc-arc-and-properties.m.tmp.m -fix --checks=-*,bugprone-suspicious-semicolon -config={} -- -fobjc-abi-version=2 -fobjc-arc -fblocks -nostdinc++ failed:
2 warnings generated.
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc10/external/llvm/14.0.0-1e54cb1887a6207267482ee7b02b1796/build/tools/clang/tools/extra/test/clang-tidy/infrastruct
ure/Output/objc-arc-and-properties.m.tmp.m:18:22: warning: potentially unintended semicolon [bugprone-suspicious-semicolon]
  if(f.shouldDoStuff); [f nop];
                     ^
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc10/external/llvm/14.0.0-1e54cb1887a6207267482ee7b02b1796/build/tools/clang/tools/extra/test/clang-tidy/infrastruct
ure/Output/objc-arc-and-properties.m.tmp.m:18:22: note: FIX-IT applied suggested code changes
clang-tidy applied 1 of 1 suggested fixes.
Suppressed 1 warnings (1 with check filters).
*** Error in `clang-tidy': double free or corruption (fasttop): 0x000000000305cf40 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x2b4d80650329]
/lib64/libc.so.6(__cxa_finalize+0x9a)[0x2b4d8060905a]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc10/external/llvm/14.0.0-1e54cb1887a6207267482ee7b02b1796/build/bin/../lib64/libclang-cpp.so.14(+0x9d25d3)[0x2b4d786d15d3]
======= Memory map: ========
00400000-00762000 r--p 00000000 fc:02 1061185659                         /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc10/external/llvm/14.0.0-1e54cb1887a6207267482ee7b02b1796/build/bin/clang-tidy
00762000-02496000 r-xp 00362000 fc:02 1061185659                         /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc10/external/llvm/14.0.0-1e54cb1887a620726
```

[b] https://github.com/cms-sw/cmsdist/pull/7729#issuecomment-1082202746
```
Unsupported      :    1
Passed           : 1155
Expectedly Failed:    2
```

**Comment by gartung** [comment]
@smuzaffar I pushed an update to the cms clang tidy library CMakeLists.txt that I tested locally to work. The new head of the branch is 282462f20845d87aad8e6d55bccc06b3de1ab4d0

**Comment by smuzaffar** [comment]
please test
trhanks @gartung , I have updated the PR to use the latest commit.

**Comment by gartung** [comment]
@smuzaffar the build will fail at checkout.

**Comment by smuzaffar** [comment]
> @smuzaffar the build will fail at checkout.

thanks for the extra pair of eyes. should be fix now

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
hold
looks like llvm-lite ( required by numba) does not yet support llvm 14.0.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmssw#38576

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
we have `clang++` issues where it is not picking up our gcc headers see https://github.com/llvm/llvm-project/issues/56343

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_5_CLANG_X

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test for CMSSW_12_4_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_12_6_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_12_6_CLANG_X

**Pull request closed without merging**
