### PR TITLE
Update t0.spec. T0 version 2.1.9

### PR DESCRIPTION
**Pull request by germanfgv**

### CODE REVIEW

**Comment by germanfgv** [comment]
merge

**Comment by amaltaro** [comment]
@germanfgv sorry for getting late to this, but can you please use `1.3.3.patch2` instead? It has a bug fix for runtime code that will be necessary in T0

**Comment by muhammadimranfarooqi** [comment]
+1 to 022774017608961864dd2690be547aa949ae038e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5781/test_0227740-20200427-101504.log" target="_blank">here</a>.

**Comment by germanfgv** [comment]
> @germanfgv sorry for getting late to this, but can you please use `1.3.3.patch2` instead? It has a bug fix for runtime code that will be necessary in T0

Ok, thanks Alan. I'm changing to patch2.

**Pull request merged**
