### PR TITLE
Update Correctionlib to version 2.1.0

### LINKED ISSUE #7510: Correctionlib 2.1
A minor release https://github.com/cms-nanoAOD/correctionlib/releases/tag/v2.1.0 just has some small internal changes, dependencies are the same as 2.0.
Is it possible also to backport this to CMSSW 10_6_X release? I am happy to help of course.

### PR DESCRIPTION
**Pull request by smuzaffar**
fixes https://github.com/cms-sw/cmsdist/issues/7510

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
urgent

**Comment by tvami** [comment]
Hi @smuzaffar I think https://github.com/cms-sw/cmsdist/issues/7510 wanted the backport of this to 10_6_X, can you please do that as well? Thanks!

**Comment by smuzaffar** [comment]
> Hi @smuzaffar I think #7510 wanted the backport of this to 10_6_X, can you please do that as well? Thanks!

here it is https://github.com/cms-sw/cmsdist/pull/7520

**Comment by smuzaffar** [comment]
we will integrate it for master once 12.3.0.pre2 is built

**Comment by tvami** [comment]
Hi @smuzaffar 
I think more is needed, please see:
https://github.com/cms-sw/cmsdist/issues/7510#issuecomment-996007309

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
