### PR TITLE
builds pycurl with openssl option, fix import pycurl with proper backend

### PR DESCRIPTION
**Pull request by iahmad-khan**
https://github.com/cms-sw/cmssw/issues/17483

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by davidlange6** [comment]
Thanks

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please add a unit test in cmssw/PhysicsTools/PythonAnalysis/test to test pycurl?

**Comment by smuzaffar** [comment]
OK, I did it here https://github.com/cms-sw/cmssw/pull/17488 (pycurl test in cmssw)

**Comment by smuzaffar** [comment]
jenkins tests looks good

**Pull request merged**
