### PR TITLE
Update OpenBLAS to 0.3.15

### PR DESCRIPTION
**Pull request by mrodozov**
see https://github.com/cms-sw/cmsdist/pull/6933#issuecomment-852906475

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- release = CMSSW_12_0_SKYLAKEAVX512_X

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_amd64_gcc900

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
