### PR TITLE
DQMGUI 9.0.3

### PR DESCRIPTION
**Pull request by rovere**
* Fix Castor backup
* Restore minimal ROOT marker for overlaid histograms

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 51e8c22e6d39582ed6eb70fed013130d225e5d56 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3319/test_51e8c22-20170727-212506.log" target="_blank">here</a>.

**Comment by davidlange6** [comment]
hi @rovere - is this PR obsolete?

**Comment by smuzaffar** [comment]
@rovere , @h4d4, should this PR be closed?

**Comment by rovere** [comment]
indeed, to be closed.

**Pull request closed without merging**
