### PR TITLE
[BuildRules] Do not build a shared library/plugin if content of Buildfile are empty

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters
 - full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc820

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc820

**Comment by smuzaffar** [comment]
+externals
it works fine for amd64 and aarch64. ppc64le failed due to onnx issue.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
