### PR TITLE
 Make abseil-cpp and c-ares (required for grpc) external packages 

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc10

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
> ---> test DRNTest had ERRORS

This is fine, I guess: the error is related to Triton client, for which there is no PowerPC image...

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
