### PR TITLE
New version fixed acess to RunRegistry data-service

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
hi @smuzaffar - how does this go into 93x?

**Comment by smuzaffar** [comment]
oops, did not notice that it was for 92X. I will do it

**Comment by smuzaffar** [comment]
@vkuznet, automatic porting did not work. Please provide a PR for IB/CMSSW_9_3_X/gcc530 (which is default branch of cmsdist)

**Comment by vkuznet** [comment]
@smuzaffar , here is PR against 93X: https://github.com/cms-sw/cmsdist/pull/3144

**Pull request merged**
