### PR TITLE
 Update CUDA to version 10.1.105

### PR DESCRIPTION
**Pull request by fwyzard**
* Move cuda-gdb wrapper to cuda.spec 

  * CUDA version 10.1.105
    Support for gcc 8 and clang 7.
    Include new Matrix Multiply library cublasLt.
    Various fxes to CUDA libraries and NVCC compiler.

  * NVIDIA drivers version 418.39

See https://docs.nvidia.com/cuda/archive/10.1/cuda-toolkit-release-notes/index.html .

### CODE REVIEW

**Comment by fwyzard** [comment]
@smuzaffar do we have to change anything in the spec or build files to enable CUDA for gcc 8 builds ?

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@fwyzard , no we do not have to change any thing. If check here https://github.com/cms-sw/cmsdist/blob/0ecba218c172d4e858e37e5d76711d5d030cfdb1/cuda-toolfile.spec#L161 passes for gcc8 cuda-gcc support will be available and unit tests (e.g https://github.com/cms-sw/cmssw/blob/master/DataFormats/Math/test/BuildFile.xml#L75 ) will start building/running

**Comment by fwyzard** [comment]
Ah, nicely done, thanks.

**Comment by smuzaffar** [comment]
please test
missing data is now available.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
