### PR TITLE
update to pythia 8.201 with patch to fix minbias issue (73x)

### PR DESCRIPTION
**Pull request by bendavid**
Update to pythia 8.201 plus minimal patch from @smrenna to fix multiple initialisation issue with diffractive processes (breaking MinBias in production)

@mkirsano

### CODE REVIEW

**Comment by bendavid** [comment]
+1

**Comment by nclopezo** [comment]
@bendavid do you plan to do the same PR for 7_2_X?

**Comment by bendavid** [comment]
No, we have stopped maintaining 72x for what concerns generator issues.

**Comment by nclopezo** [comment]
Last week, I did it here for 7_3_X in gcc481. https://github.com/cms-sw/cmsdist/pull/1200

**Comment by nclopezo** [comment]
The automatic merges merge from IB/CMSSW_7_3_X/stable to the other cmsdist branches for 73X

**Pull request closed without merging**
