### PR TITLE
Change the default optimisation level to `-O3`

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
test parameters:
  - full_cmssw = true
  - enable = threading

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Now that CMSSW_14_1_0_pre4 has been built, we can merge this in the master branch.

**Comment by smuzaffar** [comment]
+externals

this has been tested in Geant4 IBs

**Pull request merged**
