### PR TITLE
Update to CUDA 11.4.4

### PR DESCRIPTION
**Pull request by fwyzard**
Update to CUDA 11.4.4:
  * CUDA runtime version 11.4.148
  * NVIDIA drivers version 470.82.01

Fixes various Apache Log4J vulnerabilities.

See https://docs.nvidia.com/cuda/archive/11.4.4/cuda-toolkit-release-notes/index.html for the full CUDA 11.4.x release notes and change log.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@smuzaffar, I don't know where Log4J is used in the CUDA tools, but should we backport this to 12.2.x as well ?

**Comment by fwyzard** [comment]
type bugfix

**Comment by smuzaffar** [comment]
@fwyzard Looking at https://nvidia.custhelp.com/app/answers/detail/a_id/5294 , the only product which are affected by this are NETQ and "VGPU SOFTWARE LICENSE SERVER" . I think we are not using any of these so no need to backport

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
