### PR TITLE
Update Geant4 to 11.0.6

### PR DESCRIPTION
**Pull request by iarspider**
Closes https://github.com/cms-externals/geant4/issues/60

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_12_5_GEANT4_X

**Comment by iarspider** [comment]
please test for CMSSW_12_5_GEANT4_X/el8_amd64_gcc10

**Comment by iarspider** [comment]
@smuzaffar 
```
$ cat config.map | grep CMSSW_12_5_GEANT4_X
SCRAM_ARCH=el8_amd64_gcc10;PKGTOOLS_TAG=V00-34-XX;CMSDIST_TAG=IB/CMSSW_12_5_X/geant4;RELEASE_BRANCH=master;RELEASE_QUEUE=CMSSW_12_5_GEANT4_X;DOCKER_IMG=cmssw/el8;BUILD_HOUR=23;BUILD_DAY=2,5;
SCRAM_ARCH=slc7_amd64_gcc10;PKGTOOLS_TAG=V00-34-XX;CMSDIST_TAG=IB/CMSSW_12_5_X/geant4;RELEASE_BRANCH=master;RELEASE_QUEUE=CMSSW_12_5_GEANT4_X;DOCKER_IMG=cmssw/cc7;BUILD_HOUR=23;BUILD_DAY=2,5;
```

Bot is unable to choose which architecture to use.

**Comment by iarspider** [comment]
please test for CMSSW_12_5_GEANT4_X/el8_amd64_gcc10

**Comment by smuzaffar** [comment]
> @smuzaffar
> 
> ```
> $ cat config.map | grep CMSSW_12_5_GEANT4_X
> SCRAM_ARCH=el8_amd64_gcc10;PKGTOOLS_TAG=V00-34-XX;CMSDIST_TAG=IB/CMSSW_12_5_X/geant4;RELEASE_BRANCH=master;RELEASE_QUEUE=CMSSW_12_5_GEANT4_X;DOCKER_IMG=cmssw/el8;BUILD_HOUR=23;BUILD_DAY=2,5;
> SCRAM_ARCH=slc7_amd64_gcc10;PKGTOOLS_TAG=V00-34-XX;CMSDIST_TAG=IB/CMSSW_12_5_X/geant4;RELEASE_BRANCH=master;RELEASE_QUEUE=CMSSW_12_5_GEANT4_X;DOCKER_IMG=cmssw/cc7;BUILD_HOUR=23;BUILD_DAY=2,5;
> ```
> 
> Bot is unable to choose which architecture to use.

great, you have found the correct way to select the arch:-)

**Comment by smuzaffar** [comment]
@iarspider , @civanch do we need 
- https://github.com/cms-externals/geant4/pull/58
- https://github.com/cms-externals/geant4/pull/59

which were added on top of G4 11.0.1 for newer geant4 version?

**Comment by civanch** [comment]
@smuzaffar , this is not needed, because fixes are part of new version.

**Comment by smuzaffar** [comment]
+externals
loogs good got G4 Ibs

**Pull request merged**
