### PR TITLE
continue with removing python2 versions

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
test parameters:
  - full_cmssw = true

**Comment by davidlange6** [comment]
please test with cms-sw/cmssw#33991

**Comment by davidlange6** [comment]
please test with cms-sw/cmssw#33991

**Comment by davidlange6** [comment]
hi @smuzaffar  - despite no changes in this PR (a unit test removed on the cmssw side), the new round of tests has massive failures not found in the previous ones.  

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-afd996/15698/summary.html
vs
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-afd996/15690/summary.html

did something timeout?  Any other ideas? (I believe both are full cmssw builds, so should be comparable)

**Comment by smuzaffar** [comment]
@davidlange6 , I think it might be related to cmssw patch release and PR asking for full_cmssw. Ideally it should work, but let me see what bot is doing

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33991

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33991
let's test it against a full IB

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33991

**Comment by davidlange6** [comment]
we could also use the devel build for this if it doesn't have another purpose?

**Comment by davidlange6** [comment]
please test with cms-sw/cmssw#33991

**Comment by smuzaffar** [comment]
as suggested by @davidlange6 , we are trying this in DEVEL IBs to understand the failure better

**Comment by smuzaffar** [comment]
@davidlange6 , looks like during PR tests the lib/arch/NAME_xr.rootmap files are missing that is why we get these errors, I see the same error for GCC 10 PR. I am checking why rootmaps files are not generated

**Pull request merged**
