### PR TITLE
[ROOTMaster] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by iarspider**
[Changes](https://github.com/root-project/root/compare/30a654283f...b2da3719ab). Superseeds https://github.com/cms-sw/cmsdist/pull/9502

### CODE REVIEW

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46635 for CMSSW_14_2_ROOT6_X

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46635 for CMSSW_14_2_ROOT6_X

**Comment by smuzaffar** [comment]
@iarspider , you also need to update dd4hep

**Comment by iarspider** [comment]
> @iarspider , you also need to update dd4hep

Did that already, thanks!

**Comment by iarspider** [comment]
test parameters:
- release = CMSSW_14_2_ROOT6_X
- full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
[src/FWCore/Reflection/test/TestFWCoreReflectionClassVersionUpdate](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9b6ca8/42765/unitTests/src/FWCore/Reflection/test/TestFWCoreReflectionClassVersionUpdate/testing.log) and [src/IOPool/Input/test/TestIOPoolInputNoParentDictionary](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9b6ca8/42765/unitTests/src/IOPool/Input/test/TestIOPoolInputNoParentDictionary/testing.log) - usual failures when ROOT version changes

[src/FWCore/Concurrency/test/testFWCoreConcurrency](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9b6ca8/42765/unitTests/src/FWCore/Concurrency/test/testFWCoreConcurrency/testing.log) - timed out

[src/DQMServices/Demo/test/TestDQMGUIUpload](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9b6ca8/42765/unitTests/src/DQMServices/Demo/test/TestDQMGUIUpload/testing.log) - known failure https://github.com/cms-sw/cmssw/issues/46682

@smuzaffar I think we can merge it, and keep an eye on testFWCoreConcurrency.

**Comment by smuzaffar** [comment]
looks good

**Pull request merged**
