### PR TITLE
Updated root to tip of branch v6-24-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@mrodozov , there is root 6.24.02 tag. Can you please update ROOT624 branch with that tag (do not forget to update the version in root.spec too)

**Comment by mrodozov** [comment]
sure , I'll get it

**Comment by mrodozov** [comment]
alright seems we got the tag (yesterday) + one commit 
and this second commit is just a version change. so we are good with the tag and we need only to change the root.spec
https://github.com/cms-sw/root/commits/cms/v6-24-00-patches/5fc30f5 is this branch and the 6.24.02 tag commit is ad1ddb8

**Pull request merged**
