### PR TITLE
Get llvmlite,numba from sources, move llvm to 5

### PR DESCRIPTION
**Pull request by mrodozov**
Porting this PR https://github.com/cms-sw/cmsdist/pull/3605 to gcc630 and move llvm to 5

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please abort

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@davidlange6 , @Dr15Jones any objections on getting LLVM 5.0 (along with updated llvmlite and numba) in to normal 10.0.X IBs?

**Comment by smuzaffar** [comment]
ping cmsbot

**Comment by davidlange6** [comment]
hi @mrodozov - sorry I missed following up on this - it looks like llvmlite has come out with a new release (0.21) in the meanwhile. Is that something we can use? [it didn't make it to pypi yet, so maybe there is no point yet?]

**Comment by davidlange6** [comment]
and there is a llvmlite 0.36.1 (also not on pypi..)

**Comment by mrodozov** [comment]
I might try build llvmlite 0.21  and you maybe you meant numba 0.36.1 ? I'll try them and then update the PR

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please abort

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
thanks @mrodozov . @davidlange6 any objection getting this for 10.0.X?

**Comment by smuzaffar** [comment]
+externals

**Comment by davidlange6** [comment]
nice:( - so thanks to my twitter i notice that last night, these version updates got pushed to pypi... let me see if i can make the changes...

otherwise, what do the numpy changes affect?

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge



On 9 Dec 2017, at 21:16, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3615/25023/summary.html

@slava77<https://github.com/slava77> comparisons for the following workflows were not done due to missing matrix map:

  *   /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-3615/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017

Comparison Summary:

  *   No significant changes to the logs found
  *   Reco comparison results: 0 differences found in the comparisons
  *   DQMHistoTests: Total files compared: 27
  *   DQMHistoTests: Total histograms compared: 2835241
  *   DQMHistoTests: Total failures: 1
  *   DQMHistoTests: Total nulls: 0
  *   DQMHistoTests: Total successes: 2835062
  *   DQMHistoTests: Total skipped: 178
  *   DQMHistoTests: Total Missing objects: 0
  *   DQMHistoSizes: Histogram memory added: 1.10999999999 KiB( 23 files compared)
  *   Checked 113 log files, 9 edm output root files, 27 DQM output files

**Pull request merged**
