### PR TITLE
Fix pythia8 interface library to lhapdf6

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
The errors must be unrelated, it works for me

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
I don't understand why the test fails. May be because of commands made in parallel (install library and check that it is there)?

**Comment by smuzaffar** [comment]
please test
@mkirsano , I see warnings like this
```
+ ./configure --prefix=/build/muz/pp/w/tmp/BUILDROOT/8427946e18b609e49876774239460ffe/opt/cmssw/slc6_amd64_gcc630/external/pythia8/226-cms --enable-shared --with-hepmc2=/build/muz/pp/w/slc6_amd64_gcc630/external/hepmc/2.06.07-oenich --with-lhapdf6=/build/muz/pp/w/slc6_amd64_gcc630/external/lhapdf/6.1.6-mlhled2 --with-lhapdf6-plugin=LHAPDF6.h
WARNING: Disabling BOOST - header boost/shared_ptr.hpp missing.
WARNING: Disabling LHAPDF6 - requires BOOST.
```
I guess it worked for you as you might have boost installed on local build machines. I have updated the PR to use boost from our externals

**Comment by mkirsano** [comment]
Thanks @smuzaffar. The behaviour of pythia8 wrt boost is a mess, it changed several times. I forgot it, but fortunately I added a check time ago. By the way I cannot see the full test result using the link above.

**Comment by smuzaffar** [comment]
+tests

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
