### PR TITLE
update mkfit to 3.0.1

### PR DESCRIPTION
**Pull request by slava77**
A new release of mkfit is now available
https://github.com/trackreco/mkFit/releases/tag/V3.0.0-0%2Bpr315

this cmsdist PR still needs a matching PR in cms-sw/cmssw

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33802

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33802

**Comment by makortel** [comment]
@cmsbuild, please test with cms-sw/cmssw#33802

**Comment by makortel** [comment]
Got stuck?

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please test with cms-sw/cmssw#33802

**Comment by makortel** [comment]
@cmsbuild, please test with cms-sw/cmssw#33802

**Comment by jpata** [comment]
is this a problem of the PR or of the test (also for the main PR cms-sw/cmssw#33802)?

```python
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02684/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-06-06-0000/bin/slc7_amd64_gcc900/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02684/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-06-06-0000/bin/slc7_amd64_gcc900/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-06-06-2300/python/Configuration/Applications/ConfigBuilder.py", line 2301, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-06-06-2300/python/Configuration/Applications/ConfigBuilder.py", line 891, in addCustomise
    __import__(packageName)
  File "/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/6917/15720/CMSSW_12_0_X_2021-06-06-2300/python/RecoTracker/MkFit/customizeHLTIter0ToMkFit.py", line 4, in <module>
    import RecoTracker.MkFit.mkFitHitConverter_cfi as mkFitHitConverter_cfi
  File "/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/6917/15720/CMSSW_12_0_X_2021-06-06-2300/python/RecoTracker/MkFit/mkFitHitConverter_cfi.py", line 3, in <module>
    from RecoTracker.MkFit.mkFitHitConverterDefault_cfi import mkFitHitConverterDefault as _mkFitHitConverterDefault
ImportError: No module named mkFitHitConverterDefault_cfi
```

**Comment by makortel** [comment]
It is a problem in  cms-sw/cmssw#33802 for which I'll submit a fix soon.

**Comment by makortel** [comment]
@cmsbuild, please test with cms-sw/cmssw#33802

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
Comparisons seem to be stuck, and I was thinking launching tests anyway from cmssw side now that code-checks there succeeded

**Comment by qliphy** [comment]
tested with https://github.com/cms-sw/cmssw/pull/33802

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
