### PR TITLE
 [9.4.X] Backport of Egamma weight files updates

### PR DESCRIPTION
**Pull request by guitargeek**
Backport of #4056 and #4230

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by guitargeek** [comment]
Oh sorry @mrodozov, I was not aware you are so kind to trigger tests in this repo. Actually my two PRs here ain't ready to get tested just yet, I need to open a corresponding CMSSW PR. Will come in a few hours.

**Comment by fabiocos** [comment]
+1

in support of the integration of cms-sw/cmssw#25408 , the deleted files are coherently replaced there by the new ones

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
