### PR TITLE
Updated root to tip of branch v6-24-00-patches

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6783

**Comment by smuzaffar** [comment]
please test with #6783

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@cvuosalo the comparison failures are the same here in 11634.911

**Comment by mrodozov** [comment]
please test
the failing test is fixed now

**Comment by cvuosalo** [comment]
@mrodozov Changing ROOT causes the simulation histories for the DD4hep workflow 11634.911 to change.

**Comment by mrodozov** [comment]
ok what about https://github.com/cms-sw/cmsdist/pull/6822 where ROOT doesn't change.

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
