### PR TITLE
Update CRABClient to 3.3.2001

### PR DESCRIPTION
**Pull request by lecriste**

### CODE REVIEW

**Comment by lecriste** [comment]
build

**Comment by muhammadimranfarooqi** [comment]
Leonardo
Why did you select old architecture for this PR??

**Comment by lecriste** [comment]
@muhammadimranfarooqi because we still need to provide CRAB Client also for SL6.
The [SL7 PR](https://github.com/cms-sw/cmsdist/pull/5448) has been merged already.
@belforte

**Comment by muhammadimranfarooqi** [comment]
@lecriste 
Actually build machine builds RPMs for only current architecture. I am not aware how to configure this build machine to build for old architecture as well. I'll see this once I am back at CERN after holidays. 

Best
Muhammad Imran

**Comment by lecriste** [comment]
@muhammadimranfarooqi I could build the slc6_amd64_gcc493 RPM myself on vocms022 but I can not access that machine.
Do you know of any issue with vocms022 or whether it has been replaced by another machine?

**Comment by muhammadimranfarooqi** [comment]
@lecriste ,
I just noticed vocms022 was not running (I don't know why). I have started again this machine. I login there. You should be able to login now. 

Best
M

**Comment by h4d4** [comment]
+1 to 4b952cd66c572d402e71e317429e8922ef6e64ef on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5449/test_4b952cd-20200101-134509.log" target="_blank">here</a>.

**Comment by lecriste** [comment]
merge

**Pull request merged**
