### PR TITLE
Updates pip based packages

### PR DESCRIPTION
**Pull request by smuzaffar**
- new versions for pip based python packages
- Use `--upgrade --upgrade-strategy only-if-needed` to make sure that we always install a package in our externals area. 
- Cleanup for py2 and py3 packages
- Cleanup of some unused files
- Create lib/py3 for llvm
- Build xrootd for both python2 and python3
- Build numpy, matplotlib and tensorflow using our `build-with-pip` system.
- Build dxr for py3
- Get cx-Oracle from pip and install it for both py2 and py3

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
hi @smuzaffar - nice to see numpy/matplotlib making it to the pip packages!

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
failing unit tests has nothing to do with this change. Unit tests itself need fixing.

**Pull request merged**
