### PR TITLE
t0wmadatasvc era and gt entry points

### PR DESCRIPTION
**Pull request by LinaresToine**

### CODE REVIEW

**Comment by arooshap** [comment]
please test

**Comment by smuzaffar** [comment]
> please test

@arooshap , are you assuming that cms-bot will start tests for this PR?
Note that cms-bot does not react to `comp` branches

**Comment by arooshap** [comment]
> > please test
> 
> @arooshap , are you assuming that cms-bot will start tests for this PR? Note that cms-bot does not react to `comp` branches

I was just trying to see if this triggers a build because for some pull requests, for example, [here](https://github.com/cms-sw/cmsdist/pull/8710), it gets triggered automatically. Many thanks for the information! :)

**Comment by smuzaffar** [comment]
@arooshap , for comp there is a cron job which runs on some vocms node and automatically start testing if the PR is created by a valid user. I guess `LinaresToine` is not in that list that is why comp bot did not start tests for this PR.

**Comment by arooshap** [comment]
> @arooshap , for comp there is a cron job which runs on some vocms node and automatically start testing if the PR is created by a valid user. I guess `LinaresToine` is not in that list that is why comp bot did not start tests for this PR.

@smuzaffar Thanks a lot for this information, I did not find it anywhere. I will add him in the list.

**Comment by LinaresToine** [comment]
Hello @arooshap and @smuzaffar,

Thank you both very much for helping me solve this issue. 

Regards,

Antonio Linares for Tier 0

**Pull request merged**
