### PR TITLE
Rivet 3.1.4, YODA 1.9.0, Professor 2.3.2

### PR DESCRIPTION
**Pull request by mseidel42**

### CODE REVIEW

**Comment by mrodozov** [comment]
allow @mseidel42 test rights

**Comment by mseidel42** [comment]
please test

**Comment by mrodozov** [comment]
that has nothing to do with the PR itself, the IB is late due to a job failure and this is "catched in the middle"
I'll restart the job when the IB is available

**Comment by mseidel42** [comment]
> that has nothing to do with the PR itself, the IB is late due to a job failure and this is "catched in the middle"
> I'll restart the job when the IB is available

All right, thank you!

**Comment by mrodozov** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/33473

**Comment by mrodozov** [comment]
please test
this will do (I hope)

**Comment by mseidel42** [comment]
please test

**Comment by mseidel42** [comment]
Hi Mircho, at least the unit tests are helpful to detect problems now :)

The problem seems to come from ROOT with python2. Is there a way to fix that?
Or, are we going to switch to python3 as default anytime soon?

**Comment by mrodozov** [comment]
we are having both py3 and py2 right now and the cppyy supports both it's up to the test and the caller (python or python3)
ROOT requires as dependency to have both pythons
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/root.spec#L16
I have to see the tests to tell why this is happening (if you see both libcppyy2_7 and 3_8 calls are in the logs which suggests something is wrong)
let me find the PR and related JIRA tickets explaining how both py3 and py2 can be used by ROOT

**Comment by mseidel42** [comment]
Ok, as a workaround we can compile the python2 module without ROOT, and then force the two YODA<->ROOT conversion scripts to use python3. Local behavior looks good.

**Comment by mseidel42** [comment]
please test

**Comment by mrodozov** [comment]
@cvuosalo the comparison failures are in 11634.911 , please advise

**Comment by cvuosalo** [comment]
@mrodozov The PR test included this change:
#6826 @cms-sw: DD4Hep - get latest on master

DD4hep has been changed, so that changes the simulation histories for the DD4hep workflow 11634.911.

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
