### PR TITLE
upgrade pythia8 to 212

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by ghost** [comment]
@mkirsano Thanks, I'm going to test this now.

**Comment by ghost** [comment]
@mkirsano what about evtgen? I thought it was necessary for this version of Pythia... In case you'll add it, please don't include the toolfile if it isn't necessary.

**Comment by mkirsano** [comment]
This is to be tested against cmssw #12189

**Comment by ghost** [comment]
@mkirsano ok, will test again.

**Pull request merged**
