### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@guitargeek , this PR is trying to tests https://github.com/root-project/root/compare/ecbd0c7fc2...fe7cbd4643 root changes for cmssw. One unit test is failign with error [a]. I see the above mentioned root changes contains some pyroot fixes from you. Do yousee any obvious reason why this is failing? I think https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/python/TkAlMap.py#L749-L754 is where is test failed 

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10bcdd/43202/unitTests/src/Alignment/OfflineValidation/test/GCPall/testing.log

```
TkAlMap: saving canvas in "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_15_0_ROOT6_X_2024-12-02-2300/tmp/UnitTest/test_yaml/GCPdetUnits/SURun3vsIdeal/1_vs_1/TkAlMaps/TkAlMap_strips_dphi_drange.pdf"
Info in <TCanvas::Print>: pdf file /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_15_0_ROOT6_X_2024-12-02-2300/tmp/UnitTest/test_yaml/GCPdetUnits/SURun3vsIdeal/1_vs_1/TkAlMaps/TkAlMap_strips_dphi_drange.pdf has been created
TkAlMap: saving canvas in "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_15_0_ROOT6_X_2024-12-02-2300/tmp/UnitTest/test_yaml/GCPdetUnits/SURun3vsIdeal/1_vs_1/TkAlMaps/TkAlMap_strips_dphi_drange.png"
Info in <TCanvas::Print>: png file /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_15_0_ROOT6_X_2024-12-02-2300/tmp/UnitTest/test_yaml/GCPdetUnits/SURun3vsIdeal/1_vs_1/TkAlMaps/TkAlMap_strips_dphi_drange.png has been created
TkAlMap: drawing variable distribution
TFile::Append:0: RuntimeWarning: Replacing existing TH1: dphi_hist (Potential memory leak).
Info in <TCanvas::Print>: png file /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_15_0_ROOT6_X_2024-12-02-2300/tmp/UnitTest/test_yaml/GCPdetUnits/SURun3vsIdeal/1_vs_1/TkAlMaps/VariableDistribution_dphi_strips.png has been created
TkAlMap: deleting temporary file "1733224072_6900866_TkAlMapTempFile.root"
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x000014794f15ee0b in waitpid () from /lib64/libc.so.6
#1  0x000014794f0b2747 in do_system () from /lib64/libc.so.6
#2  0x000014794e77be7f in TUnixSystem::StackTrace() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_15_0_ROOT6_X_2024-12-02-2300/external/el8_amd64_gcc12/lib/libCore.so
#3  0x000014794ec33783 in (anonymous namespace)::TExceptionHandlerImp::HandleException(int) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_15_0_ROOT6_X_2024-12-02-2300/external/el8_amd64_gcc12/lib/libcppyy_backend.so
#4  0x000014794e7797d1 in TUnixSystem::DispatchSignals(ESignals) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_15_0_ROOT6_X_2024-12-02-2300/external/el8_amd64_gcc12/lib/libCore.so
#5  <signal handler called>
#6  0x0000000008654750 in ?? ()
#7  0x000014793396101d in CPyCppyy::op_dealloc_nofree(CPyCppyy::CPPInstance*) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/lcg/root/6.35.1-6860bb4961e400c5b031c2aeae477b7a/lib/libcppyy.so
#8  0x0000147933961061 in CPyCppyy::op_dealloc(CPyCppyy::CPPInstance*) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/lcg/root/6.35.1-6860bb4961e400c5b031c2aeae477b7a/lib/libcppyy.so
#9  0x0000147950112152 in subtype_dealloc (self=0x14793104fa80) at Objects/typeobject.c:1353
#10 0x00001479500ea505 in _Py_DECREF (op=<optimized out>) at ./Include/object.h:430
#11 _Py_XDECREF (op=<optimized out>) at ./Include/object.h:497
#12 free_keys_object (keys=0x8d88a50) at Objects/dictobject.c:598
#13 0x00001479500eb3b8 in dictkeys_decref (dk=0x8d88a50) at Objects/dictobject.c:333
#14 dict_dealloc (mp=0x1479310c2440) at Objects/dictobject.c:2026
#15 0x000014795011229d in _Py_DECREF (op=<optimized out>) at ./Include/object.h:430
#16 subtype_dealloc (self=0x14793101fd00) at Objects/typeobject.c:1331
#17 0x0000147950065b43 in _Py_DECREF (op=<optimized out>) at ./Include/object.h:430
#18 frame_dealloc (f=0xc42d50) at Objects/frameobject.c:585
#19 0x0000147950065a98 in _Py_DECREF (op=0xc42d50) at ./Include/object.h:430
#20 function_code_fastcall (tstate=0xae1340, co=<optimized out>, args=<optimized out>, nargs=<optimized out>, globals=<optimized out>) at Objects/call.c:338
#21 0x000014795006c0d1 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0xb39f20, callable=0x1479310a5430, tstate=0xae1340) at ./Include/cpython/abstract.h:118
#22 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at ./Include/cpython/abstract.h:127
#23 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0xae1340) at Python/ceval.c:5077
#24 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3520
#25 0x000014795019ea91 in _PyEval_EvalFrame (throwflag=0, f=0xb39db0, tstate=0xae1340) at ./Include/internal/pycore_ceval.h:40

```

**Comment by guitargeek** [comment]
Hi @smuzaffar, which Python file is actually run in this test? Does only this one test fail? Can I reproduce it? (note I'm not a CMS member).

What is already fishy is this warning in the output
```txt
TFile::Append:0: RuntimeWarning: Replacing existing TH1: dphi_hist (Potential memory leak).
```
Attempting to have different objects with the same name in a TFile often doesn't go well, and also the histogram doesn't need to be managed by the file (it's only for temporary plotting).

So my first try would be to detatch the histogram from the file:
```python
hist = ROOT.TH1F(self.var+'_hist', 'Variable distribution', nbins, h_min, h_max)
hist.SetDirectory(ROOT.nullptr)
```
Then hopefully things to less wrong when the TFile is cleaned up.

**Comment by smuzaffar** [comment]
thanks @guitargeek , adding `hist.SetDirectory(ROOT.nullptr)` resolved the `TFile::Append:0: RuntimeWarning: Replacing existing TH1: dphi_hist (Potential memory leak).` issue but it still crashes at the end. Look like it crashes when we return from https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/scripts/GCPpyPlots.py#L25 . There is no easy way to reproduce it. Let me merge this  update for our ROOT6 IBs so that it is easy to reproduce using an IB

**Comment by smuzaffar** [comment]
@guitargeek , this has been integrated in cmssw root6 IBs and yes this is the only test which is failing. Here is what you can do to reproduce it

```
ssh lxplus8
cd /tmp/$(whoami)
source /cvmfs/cms.cern.ch/cmsset_default.sh
scram p CMSSW_15_0_ROOT6_X_2024-12-03-2300
cd CMSSW_15_0_ROOT6_X_2024-12-03-2300
cmsenv
git cms-addpkg Alignment/OfflineValidation
patch -p1 < ~muzaffar/public/root6-crash/TkAlMap.patch
scram b -j 10
tar -xzvf ~muzaffar/public/root6-crash/GCPall.tar.gz
cd unit_tests/GCPall/test_yaml/GCP/GCPdetUnits/SURun3vsIdeal/1_vs_1/GCPpython
sed -i -e "s|@CMSSW_BASE@|$CMSSW_BASE|" validation.json
./GCPpyPlots.py validation.json
```

**Comment by guitargeek** [comment]
Thank you very much! It was a big change I did in PyROOT, we're lucky it's only this single test :slightly_smiling_face:

**Comment by guitargeek** [comment]
I opened a PR to fix this: https://github.com/root-project/root/pull/17197

**Pull request merged**
