### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
@smuzaffar it builds now fine with the update. Can I update `dd4hep` in ROOT626 PR https://github.com/cms-sw/cmsdist/pull/8131 accordingly?

**Comment by smuzaffar** [comment]
@aandvalenzuela , root 6.26 does not need latest dd4hep . So there is no need to update it there. But we should check with @cms-sw/simulation-l2  and @cms-sw/geometry-l2 that if it is OK to update dd4hep in 12.6.X/master

**Comment by aandvalenzuela** [comment]
Hello @cms-sw/simulation-l2, @cms-sw/geometry-l2,

To summarize the discussion, we would like to update `dd4hep` to version `v01-23` (released on Sep 30, 2022) in `12.6.X/master`. Do you have any objections?

Thank you,
Andrea.

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Unit Test `testDiMuonVertexMonitor` is also failing in ROOT6 IBs.

**Comment by smuzaffar** [comment]
looks good

**Pull request merged**
