### PR TITLE
Build boost with python3 for PY3 IBs

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals
this should be merged along with cms-sw/cmssw#30194

**Comment by silviodonato** [comment]
please test with cms-sw/cmssw#30194

**Comment by smuzaffar** [comment]
@silviodonato , these are known failure for python3, so please ignore these errors for PY3 based Ibs,

**Comment by silviodonato** [comment]
merge

**Pull request merged**
