### PR TITLE
Backport vecgeom to 10_0_X

### PR DESCRIPTION
**Pull request by mrodozov**
Add vecgeom to 10_0_X from 10_1_X

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
ping

**Comment by smuzaffar** [comment]
Cons_ is broken due to vecgeom. we need to backport https://github.com/cms-sw/cmssw/pull/21898 in to 10.0.X to fix this.

**Comment by smuzaffar** [comment]
@fabiocos , vecgeom should be part of next 10.0.X IB. One unit test fail which we can fix if we get  cms-sw/cmssw#21898 in to 10.0.X

**Pull request merged**
