### PR TITLE
Minor updates to CUDA and OpenMPI

### PR DESCRIPTION
**Pull request by fwyzard**
Update to CUDA 11.1 Update 1
  - various bug fixes, including a security fix for the CUDA libraries
  - see https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-whats-new-11-1-Upd1 for more details

Update to OpenMPI 4.0.5
  - various bug fixes
  - see https://www.mail-archive.com/announce@lists.open-mpi.org/msg00135.html for more details

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
I would say this
> `---> test MagneticFieldEngineTestDriver had ERRORS`

is unrelated to the CUDA and OpenMPI updates ?

**Comment by mrodozov** [comment]
it isn't .  https://github.com/cms-sw/cmssw/pull/32000 is to fix the test

**Comment by smuzaffar** [comment]
+externals
unit test is already failing in IBs

**Pull request merged**
