### PR TITLE
[10.1.X] updated utm to tag 0.7.1

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #4338

### CODE REVIEW

**Comment by rekovic** [comment]
@fabiocos @kpedro88 @smuzaffar 

By the time my presentation at L1Trigger Weekly meeting finished today, the ORP meeting finished.
I wanted to ask for a new build in 10_1_X that includes the new UTM library (already merged in 10_3_x).
This new UTM library is 100% backward compatible.  It only adds new features for HeavyIon running.

As I have discussed with Fabio over skype, at P5, where we run O2O, we run 10_1_X release. 
We urgently need the new UTM library to O2O L1TMenu for HI tests that are currently being done
this week (have till the end of Technical Stop , Friday 17:00 ).  The easiest and the most cosher way to get the new UTM library is through the central release.   

Therefore,  I would like to request a new build for 10_1_X with this PR merged.  May I dare to ask, is it 
possible to have this new release today/tomorrow ?

Thanks,
Vladimir

**Comment by kpedro88** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic ok let's go for a 10_1_11. @kpedro88 thank you for starting the test, when ok we may merge and start a build

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
