### PR TITLE
Add eigen/include in INCLUDE path

### PR DESCRIPTION
**Pull request by smuzaffar**
This allows statement like `#include <eigen3/...>` to work

### CODE REVIEW

**Comment by iarspider** [comment]
@smuzaffar I am currently testing an alternative fix (just waiting for local build to complete) - changing include statement to remove `third_party/eigen3` part.

**Comment by smuzaffar** [comment]
@iarspider , you mean something like https://github.com/cms-sw/cmssw/pull/45701 ? Note that https://github.com/cms-sw/cmssw/pull/45701 change still needs this cmsdist update

**Comment by iarspider** [comment]
> @iarspider , you mean something like [cms-sw/cmssw#45701](https://github.com/cms-sw/cmssw/pull/45701) ? Note that [cms-sw/cmssw#45701](https://github.com/cms-sw/cmssw/pull/45701) change still needs this cmsdist update

Essentially, yes.

**Comment by smuzaffar** [comment]
> @smuzaffar I am currently testing an alternative fix (just waiting for local build to complete) - changing include statement to remove `third_party/eigen3` part.

I would prefer to only remove `third_party` part otherwise `#include <unsupported/Eigen/CXX11/Tensor>` does not seem right :-)

**Comment by iarspider** [comment]
> > @smuzaffar I am currently testing an alternative fix (just waiting for local build to complete) - changing include statement to remove `third_party/eigen3` part.
> 
> I would prefer to only remove `third_party` part otherwise `#include <unsupported/Eigen/CXX11/Tensor>` does not seem right :-)

Makes sense. Thanks!

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
