### PR TITLE
update vecgeom to 1.2.0 and geant4 to 11.0ref04

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
FYi @civanch

**Comment by smuzaffar** [comment]
@civanch , same errors with vecgeom 1.2.0 and geant4 11.0ref04

**Comment by civanch** [comment]
@smuzaffar , the same place but after few events - probability to have this problem is smaller now. So, vecgeom experts should address the problem.

**Comment by smuzaffar** [comment]
thanks @civanch , OK I am merging this forG4Vecgeom Ibs

**Comment by smuzaffar** [comment]
@civanch , now we have vecgeom and geant4 build inj debug mode. Few relvals now fails with this stack trace
```
#0  0x00002b1a5e9daddd in poll () from /lib64/libc.so.6
#1  0x00002b1a6485d73f in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02732/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_G4VECGEOM_X_2022-05-11-1100/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#2  0x00002b1a6485e0cc in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02732/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_G4VECGEOM_X_2022-05-11-1100/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#3  0x00002b1a64860a1b in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02732/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_G4VECGEOM_X_2022-05-11-1100/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b1a94173a73 in vecgeom::cxx::SOA3D<double>::operator[] (index=<optimized out>, this=0x2b1abb5c8900) at /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/base/SOA3D.h:323
#6  vecgeom::cxx::PolyhedronImplementation<(EInnerRadii)0, (EPhiCutout)0>::ScalarInsideSegBorder (zIndex=1, point=..., unplaced=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/kernel/PolyhedronImplementation.h:810
#7  vecgeom::cxx::PolyhedronImplementation<(EInnerRadii)0, (EPhiCutout)0>::ScalarInsideSegPhi (phiIndex=26, zIndex=1, point=..., unplaced=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/kernel/PolyhedronImplementation.h:850
#8  vecgeom::cxx::PolyhedronImplementation<(EInnerRadii)0, (EPhiCutout)0>::ScalarSafetyKernel (pt_inside=false, point=..., unplaced=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/kernel/PolyhedronImplementation.h:970
#9  vecgeom::cxx::PolyhedronImplementation<(EInnerRadii)0, (EPhiCutout)0>::SafetyToIn<double> (safety=<synthetic pointer>: 1.7976931348623157e+308, point=..., unplaced=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/kernel/PolyhedronImplementation.h:1183
#10 vecgeom::cxx::CommonUnplacedVolumeImplHelper<vecgeom::cxx::PolyhedronImplementation<(EInnerRadii)0, (EPhiCutout)0>, vecgeom::cxx::VUnplacedVolume>::SafetyToIn (this=this@entry=0x2b1abb5b4e30, p=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/UnplacedVolumeImplHelper.h:173
#11 0x00002b1a9417c0d5 in G4UAdapter<vecgeom::cxx::UnplacedPolyhedron>::DistanceToIn (this=0x2b1abb5b4e00, pt=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/geometry/management/include/G4UAdapter.hh:351
#12 0x00002b1a94256038 in G4VoxelNavigation::ComputeStep (this=0x2b1aa92242a0, localPoint=..., localDirection=..., currentProposedStepLength=26187.331447571862, newSafety=@0x2b1aa8df8aa8: 0, history=..., validExitNormal=@0x2b1aa93df48c: false, exitNormal=..., exiting=@0x2b1aa93df48b: false, entering=@0x2b1aa93df48a: false, pBlockedPhysical=0x2b1aa93df470, blockedReplicaNo=@0x2b1aa93df478: -1) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/geometry/navigation/src/G4VoxelNavigation.cc:196
#13 0x00002b1a93e4d7bb in G4Navigator::ComputeStep (this=0x2b1aa93df380, pGlobalpoint=..., pDirection=..., pCurrentProposedStepLength=<optimized out>, pNewSafety=@0x2b1aa8df8aa8: 0) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/geometry/navigation/src/G4Navigator.cc:844
#14 0x00002b1a9403eec6 in G4Transportation::AlongStepGetPhysicalInteractionLength (this=0x2b1ac8e58000, track=..., currentMinimumStep=26187.331447571862, currentSafety=@0x2b1aa8df8aa8: 0, selection=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/processes/transportation/src/G4Transportation.cc:276
#15 0x00002b1a945a2081 in G4VProcess::AlongStepGPIL (selection=0x2b1aa928d18c, proposedSafety=@0x2b1aa8df8aa8: 0, currentMinimumStep=<optimized out>, previousStepSize=<optimized out>, track=..., this=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/processes/management/include/G4VProcess.hh:467
#16 G4SteppingManager::DefinePhysicalStepLength (this=this@entry=0x2b1aa928d000) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/tracking/src/G4SteppingManager2.cc:221
#17 0x00002b1a945a015e in G4SteppingManager::Stepping (this=0x2b1aa928d000) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/tracking/src/G4SteppingManager.cc:200
#18 0x00002b1a9403652c in G4TrackingManager::ProcessOneTrack (this=0x2b1aa93fd580, apValueG4Track=apValueG4Track@entry=0x2b1acce4d908) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/tracking/src/G4TrackingManager.cc:138
#19 0x00002b1a93d361e1 in G4EventManager::DoProcessing (this=0x2b1aa9283f60, anEvent=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/event/src/G4EventManager.cc:205
#20 0x00002b1a93d36518 in G4EventManager::ProcessOneEvent (this=<optimized out>, anEvent=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc10/external/geant4/11.0ref04-0ea0d73f4905d6bc658a6ad6d952b489/geant4.11.0ref04/source/event/src/G4EventManager.cc:382
#21 0x00002b1a939c382e in RunManagerMTWorker::produce(edm::Event const&, edm::EventSetup const&, RunManagerMT&) () from /cvmfs/cms-ib.cern.ch/nweek-02732/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_G4VECGEOM_X_2022-05-11-1100/biglib/slc7_amd64_gcc10/pluginSimulation.so
#22 0x00002b1a939d9975 in omt::ThreadHandoff::Functor<OscarMTProducer::produce(edm::Event&, edm::EventSetup const&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02732/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_G4VECGEOM_X_2022-05-11-1100/biglib/slc7_amd64_gcc10/pluginSimulation.so
#23 0x00002b1a939cf63a in omt::ThreadHandoff::threadLoop(void*) () from /cvmfs/cms-ib.cern.ch/nweek-02732/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_G4VECGEOM_X_2022-05-11-1100/biglib/slc7_amd64_gcc10/pluginSimulation.so
#24 0x00002b1a5e6d2ea5 in start_thread () from /lib64/libpthread.so.0

```

**Pull request merged**
