### PR TITLE
Update CUDA to version 11.5.2

### PR DESCRIPTION
**Pull request by fwyzard**
Update CUDA to version 11.5.2:
  * CUDA runtime version 11.5.117
  * NVIDIA drivers version 495.29.05

See https://docs.nvidia.com/cuda/archive/11.5.2/cuda-toolkit-release-notes/index.html for the full CUDA 11.5.x release notes and change log.

Update cuDNN to version 8.3.2.44.
See https://docs.nvidia.com/deeplearning/cudnn/release-notes/rel_8.html for the release notes and change log.

### CODE REVIEW

**Comment by fwyzard** [comment]
The comparisons done in https://github.com/cms-sw/cmssw/issues/37129 indicate that CUDA 11.5.x should give a small performance improvement with respect to 11.4.x:
image

**Comment by fwyzard** [comment]
@smuzaffar before merging this, I'd like to compare the performance in CMSSW itself using the PR artifacts.

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard , looks like `cudnn` also needs an update

**Comment by fwyzard** [comment]
Thanks, I'll have a look later today.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for aarch64

**Comment by fwyzard** [comment]
please test for ppc64le

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please abort

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
It looks like the bot is having issues downloading https://developer.download.nvidia.com/compute/redist/cudnn/v8.3.2/local_installers/11.5/cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz:
> 06:55:58 Error while downloading https://developer.download.nvidia.com/compute/redist/cudnn/v8.3.2/local_installers/11.5/cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz: [Errno 104] Connection reset by peer

But from the command line on lxplus it works fine:

> [2022-03-10 07:03:36] fwyzard@lxplus8s13:/tmp/fwyzard$ wget https://developer.download.nvidia.com/compute/redist/cudnn/v8.3.2/local_installers/11.5/cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz
> --2022-03-10 07:04:00--  https://developer.download.nvidia.com/compute/redist/cudnn/v8.3.2/local_installers/11.5/cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz
> Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 152.199.20.126
> Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|152.199.20.126|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 857894928 (818M) [application/octet-stream]
> Saving to: 'cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz'
> 
> cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz         100%[========================================================================================================================================>] 818.15M   147MB/s    in 5.5s    
> 
> 2022-03-10 07:04:06 (148 MB/s) - 'cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz' saved [857894928/857894928]

Let's retry, might have been a transient issue.

**Comment by fwyzard** [comment]
OK, it's making progress...
> 07:13:13 Fetching sources for cudnn
> 07:13:13 Done fetching https://developer.download.nvidia.com/compute/redist/cudnn/v8.3.2/local_installers/11.5/cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz

**Comment by fwyzard** [comment]
Mhm...
> 07:24:22 * The action "build-external+cudnn+8.3.2.44-a1fbc142632e3aac1804acc974f3d7b1" was not completed successfully because Error happened before any log output.

I guess the only option is to try locally :-/

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
> **User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/7669/23001/install.sh` to create a dev area with all the needed externals and cmssw changes.

Mhm, it looks like this has already been deleted ?

**Comment by smuzaffar** [comment]
not really, when build fails during external build process then `User test area` is not deployed. I will cleanup bot to not add this message when external fails

**Comment by smuzaffar** [comment]
bit failed to build onnxruntime ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-810d14/23001/external/onnxruntime/1.7.2-8d85088b90377f827095cae329d90fd5/log ) and error is missing cudnn lib
```
6_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lcudnn
```

**Comment by fwyzard** [comment]
> not really, when build fails during external build process then `User test area` is not deployed. I will cleanup bot to not add this message when external fails

Ah, I see.



> bit failed to build onnxruntime ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-810d14/23001/external/onnxruntime/1.7.2-8d85088b90377f827095cae329d90fd5/log ) and error is missing cudnn lib
> 
> ```
> 6_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lcudnn
> ```

Yes, I saw that, I was trying to figure out why it failed... OK, no problem, back to the local build then.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
OK, at least the externals seem to be working now.

**Comment by smuzaffar** [comment]
enable gpu

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
+externals
> @smuzaffar before merging this, I'd like to compare the performance in CMSSW itself using the PR artifacts.

@fwyzard , if you want more tests then we can include it in DEVEL IBs first otherwise this looks go to go in

**Comment by fwyzard** [comment]
I'd like to run some benchmarks with it first, I was thinking to use the
areas provided by the bot for that.

**Comment by smuzaffar** [comment]
bot area for amd64 ( https://github.com/cms-sw/cmsdist/pull/7669#issuecomment-1065859621 ) should remain available till Sat. 19th of March. If you still need a bot area after that then feel free to start another PR test

**Comment by fwyzard** [comment]
OK, a comparison of the performance of the pixel reconstruction in the full CMSSW looks good too:

### `CMSSW_12_4_X_2022-03-11-1100`
```
Running 4 times over 4100 events with 4 jobs, each with 16 threads, 16 streams and 1 GPUs
  1271.2 ±   0.5 ev/s (4000 events, 99.4% overlap)
  1269.0 ±   0.5 ev/s (4000 events, 99.4% overlap)
  1265.1 ±   0.4 ev/s (4000 events, 99.3% overlap)
  1259.8 ±   0.6 ev/s (4000 events, 99.3% overlap)
 --------------------
  1266.3 ±   5.0 ev/s
```

### `CMSSW_12_4_X_2022-03-11-1100` + #7669 
```
Running 4 times over 4100 events with 4 jobs, each with 16 threads, 16 streams and 1 GPUs
  1275.0 ±   0.4 ev/s (4000 events, 99.2% overlap)
  1273.5 ±   0.5 ev/s (4000 events, 99.1% overlap)
  1267.0 ±   0.8 ev/s (4000 events, 97.4% overlap)
  1265.2 ±   0.5 ev/s (4000 events, 99.0% overlap)
 --------------------
  1270.2 ±   4.8 ev/s
```

**Comment by fwyzard** [comment]
Same for the HCAL reconstruction:

### `CMSSW_12_4_X_2022-03-11-1100`
```
Running 4 times over 4100 events with 4 jobs, each with 16 threads, 16 streams and 1 GPUs
  1454.3 ±   0.2 ev/s (4000 events, 99.9% overlap)
  1452.7 ±   0.2 ev/s (4000 events, 99.8% overlap)
  1457.8 ±   0.2 ev/s (4000 events, 99.9% overlap)
  1452.5 ±   0.2 ev/s (4000 events, 99.6% overlap)
 --------------------
  1454.3 ±   2.5 ev/s
```

### `CMSSW_12_4_X_2022-03-11-1100` + #7669
```
Running 4 times over 4100 events with 4 jobs, each with 16 threads, 16 streams and 1 GPUs
  1486.9 ±   0.2 ev/s (4000 events, 99.8% overlap)
  1484.9 ±   0.2 ev/s (4000 events, 99.8% overlap)
  1484.5 ±   0.2 ev/s (4000 events, 99.9% overlap)
  1480.1 ±   0.2 ev/s (4000 events, 99.9% overlap)
 --------------------
  1484.1 ±   2.9 ev/s
```

**Comment by fwyzard** [comment]
@smuzaffar @perrotta @qliphy for me this is good to go in.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
