### PR TITLE
Test ROOT PRs on CMSSW

### PR DESCRIPTION
**Pull request by yamaguchi1024**
This PR is to make sure ROOT PRs
(https://github.com/root-project/root/pull/3268 and
 https://github.com/root-project/root/pull/3267) work on CMSSW.

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
Hi! Could someone trigger the test? Thanks.

**Comment by yamaguchi1024** [comment]
please test :D

**Comment by smuzaffar** [comment]
please test

**Comment by yamaguchi1024** [comment]
Option -Dtable needs to be removed when testing master, because of recent change.

**Comment by yamaguchi1024** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@yamaguchi1024 , in the above test we run 
```
root -n -b -l -q src/PhysicsTools/PythonAnalysis/test/test_PyMVA.cpp+
```
so looks like root is not including its include directories here?
I can go ahead to merge this PR so that we can have a clean CXXCOMDULE IB for testsing.

**Comment by yamaguchi1024** [comment]
@smuzaffar Thanks a lot! Let me debug.. Might be related to modulemap overlay change

**Comment by yamaguchi1024** [comment]
Because of this commit, https://root.cern.ch/gitweb/?p=root.git;a=commitdiff;h=7041513ee3922b1f8e57d5d97ad1f76310c11447
we need to explicitly add -Dtmva=ON from now :)

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
Could someone test this?

**Comment by yamaguchi1024** [comment]
This PR can be merged to IB, I think it'll make it green.

**Pull request merged**
