### PR TITLE
[10.6.X] Add patches to propagate lhe numbering through herwig

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
Backport of #8670 for use in Run 2 UL production. Adds patches which propagate an event number provided in an LHE file through Herwig, which is necessary for ensuring the lhe events "line up" with the gen events if some events are skipped in merging.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@rappoccio @antoniovilela , feel free to merge it for next 10.6.X release

**Comment by smuzaffar** [comment]
backport of #8670

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/42907

**Comment by rappoccio** [comment]
+1

**Pull request merged**
