### PR TITLE
t0 1.9.90

### PR DESCRIPTION
**Pull request by lucacopa**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to f0be863801ee16953f7c031558a85b16429c1426 on slc5_amd64_gcc461.

**Comment by geneguvo** [comment]
Hi,
Do you still need this on the comp (SLC5) branch? shouldn't we have it on the SLC6 branch (comp_gcc481) instead? or in both?
Cheers,
Diego.

**Comment by lucacopa** [comment]
I didnt know that the SLC6 branch was comp_gcc481, my bad. We dont need the SLC5.

**Comment by geneguvo** [comment]
Ok. So I'll push similar changes but to the other (SLC6) branch.

**Comment by lucacopa** [comment]
Thanks Diego

**Comment by geneguvo** [comment]
Pushed to the comp_gcc481 (SLC6) branch instead: https://github.com/cms-sw/cmsdist/commit/c8d70b484bd04853756a009da4dd5b0653b921b6

**Pull request closed without merging**
