### PR TITLE
Update pacparser to 1.3.7

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , looks good but lets wait for a clean IB and rerun the tests

**Comment by smuzaffar** [comment]
please test

**Review by smuzaffar — APPROVED** [review]

**Comment by smuzaffar** [comment]
Please test

**Comment by smuzaffar** [comment]
please test
lets re-test based on clean IB ( no idea why there are too many comparison differences)

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
