### PR TITLE
add enable-pythia to the sherpa configure arguments

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
+1

**Comment by ghost** [comment]
+1
Tested the compilation itself and the compilation of GeneratorInterface/SherpaInterface against it as well.

**Comment by ghost** [comment]
@mkirsano can you please add the explicit dependency of pythia in the requirements?
That way in case it gets dropped in some part of the dependency chain we are sure it's there.
Also please bring this up next ORP (02/08).

**Comment by davidlange6** [comment]
@mkirsano - so then how are the potentially conflicting pythia6 versions handled between the internals of sherpa and CMSSW (e.g., the SherpaInterface package)?

**Comment by mkirsano** [comment]
I don't know how this is handled. Here is the information that I have:
1. I checked that Pythia6Interface works.
2. sherpa installed in GENSER is compiled with this option, and it is 
   used by ATLAS, in the software that uses also pythia6.
   
   If there are doubts, I think we can ask the sherpa authors about 
   handling this.

**Comment by bendavid** [comment]
Since we do not have a better solution or understanding about possible symbol conflicts with the default pythia 6 library, suggest closing this for now.

**Pull request closed without merging**
