### PR TITLE
use full condor for TW and remove unused cherrypy

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
@mapellidario please review

**Comment by muhammadimranfarooqi** [comment]
+1 to b2e9b8e559918ef28c55e08bba646b5f338b6717 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7547/test_b2e9b8e-20220115-160502.log" target="_blank">here</a>.

**Review by mapellidario — APPROVED** [review]
This looks good to me! Thanks Stefano!

**Comment by belforte** [comment]
please merge

**Pull request merged**
