### PR TITLE
[71X] Update tag for Configuration-Generator to V01-01-01  

### PR DESCRIPTION
**Pull request by fabiocos**
This PR addresses the request in https://github.com/cms-sw/cmsdist/pull/5121#issuecomment-517163769

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@scodella @efeyazgan @qliphy FYI

**Comment by fabiocos** [comment]
+1

**Pull request merged**
