### PR TITLE
cleanup python2; use rpm macros for python versions

### PR DESCRIPTION
**Pull request by smuzaffar**
With this cleanup non of the py3 packages should depend on python (directly or indirectly)

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- pull_request = cms-sw/cmssw#34407

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please tets

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
Sorry to bother @smuzaffar but since CMSSW_12_0_X_2021-07-06-0300 the DQM Bin By Bin tool in the Jenkins test stooped working claiming numpy does not exist.
I assume it is due to the change from python to python3, since numpy exist in the latter but not in the former for that version and later.
Can you confirm the transition to python3 has been effective since that release in the Jenkins tests at least?
Thanks

**Comment by smuzaffar** [comment]
@jfernan2 , yes we are dropping py2 packages and recently has dropped numpy for python2 ( https://github.com/cms-sw/cmsdist/pull/7099 ).
Today's 11h00 IB will be the first one where cmsRun will use python3. Though transition to python3 is not yet completed. We still have few packages to get ride of. 

Sorry I did not notice the failure of DQM Bin by bin comparison test. I thought it was already using python3 ( at least the script we run in Pr tests uses python3). Anyway,  hopefull with your changes in https://github.com/cms-sw/cmssw/pull/34374 will be enough to run it again.

**Comment by jfernan2** [comment]
Thank you!!

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
