### PR TITLE
Spec/patches to build apache 2.4 and mod_perl for it

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 1e2368145dea80a69d82ee013e10818a83af8051 on slc5_amd64_gcc461.

**Comment by geneguvo** [comment]
+1 to 39fd6e57990c77e97923ef1a9fc6f81e71fbd045 on slc5_amd64_gcc461.

**Comment by geneguvo** [comment]
+1 to 055d989c0eb30639f7f6ea29411c91143dccfc04 on slc5_amd64_gcc461.

**Comment by ktf** [comment]
what's the status of this? Can it be either closed or merged?

**Comment by vkuznet** [comment]
This may be merged/closed once #1126 will be accepted. I don't know if HTTP group plans to use gcc461 architecture anymore. If so, then we'll need it too, otherwise we my close it. I'll wait from Diego and Co.

**Comment by ktf** [comment]
@geneguvo ?

**Comment by geneguvo** [comment]
We'll not make this change on SLC5. Closing it.

**Pull request closed without merging**
