### PR TITLE
Inclusion of Latest Pede in CMSSW_7_3_X for PCL needs.

### PR DESCRIPTION
**Pull request by arunhep**
Please check with these people about the pull request.
@mmusich @frmeier @diguida @rcastello @tlampen

### CODE REVIEW

**Comment by diguida** [comment]
Ping!
Can the new executable go in pre3? This was mentioned at the last ORP.
The tests we did following the instructions were ok.
Thanks

**Comment by ktf** [comment]
@degano can you test this?

**Comment by ktf** [comment]
Also, make sure you squash the commits.

**Comment by diguida** [comment]
@ktf do you want me to make a new PR with only one commit?

**Comment by ghost** [comment]
@diguida don't worry I'm on it.

**Comment by ktf** [comment]
nah, but next time please clean up history before proposing changes. There is no hope for CMSSW, but maybe we can keep a bit of sanity in CMSDIST.. ;)

**Comment by diguida** [comment]
@degano thanks a lot.
Note to self: after requesting an external update at the ORP, ping the release managers on github. Do you agree? :-)

**Comment by diguida** [comment]
@ktf Ok, point taken.
For the future: you can write this in the github documentation. Do you want a PR also for that?

**Comment by diguida** [comment]
And here you are the documentation changes: #1202

**Comment by ghost** [comment]
Done in #1203.
I'm closing this one.

**Pull request closed without merging**
