### PR TITLE
Update CUDA to version 11.5.2 [12.3.x]

### PR DESCRIPTION
**Pull request by fwyzard**
Update CUDA to version 11.5.2:
  * CUDA runtime version 11.5.117
  * NVIDIA drivers version 495.29.05

See https://docs.nvidia.com/cuda/archive/11.5.2/cuda-toolkit-release-notes/index.html for the full CUDA 11.5.x release notes and change log.

Update cuDNN to version 8.3.2.44.
See https://docs.nvidia.com/deeplearning/cudnn/release-notes/rel_8.html for the release notes and change log.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #7669

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@qliphy , @perrotta this has been successfully tested in 12.4.X IBs. feel free to include it for 12.3.X

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
