### PR TITLE
[G4] Update Geant4 to version 11.3.0

### PR DESCRIPTION
**Pull request by iarspider**
Closes https://github.com/cms-externals/geant4/issues/87

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_15_0_GEANT4_X

**Comment by iarspider** [comment]
please test for CMSSW_15_0_G4VECGEOM_X

**Comment by iarspider** [comment]
+externals

Unit test failures seem unrelated.

**Comment by iarspider** [comment]
please test with cms-sw/cmssw#46892 for CMSSW_15_0_GEANT4_X
just to be sure

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46892 for CMSSW_15_0_G4VECGEOM_X

**Comment by civanch** [comment]
It seems that it is possible to merge to GEANT4 and G4VECGEOM branches.

**Pull request merged**
