### PR TITLE
Update Geant4 to version 11.1.ref06

### PR DESCRIPTION
**Pull request by iarspider**
Resolves https://github.com/cms-externals/geant4/issues/83

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_14_1_GEANT4_X

**Comment by iarspider** [comment]
please test for CMSSW_14_1_G4VECGEOM_X

**Comment by iarspider** [comment]
@civanch 

```
G4GeometryManager::CheckOptimisation: ERROR  logical volume SF has Voxel Header = G4GeometryManager::CheckOptimisation: ERROR  logical volume SF has Voxel Header = 
G4GeometryManager::CheckOptimisation: ERROR  logical volume SF has Voxel Header = 

%MSG-w SimG4CoreApplication:  (NoModuleName) 24-Jul-2024 20:32:16 CEST  pre-events

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomMng002
      issued by : G4GeometryManager::UndertakeOptimisation
 Expected that all voxelisation work is done, but found that voxels headers are missing in 1 volumes. 

-------- EEEE -------- G4Exception-END --------- EEEE -------

%MSG
%MSG-w SimG4CoreApplication:  (NoModuleName) 24-Jul-2024 20:32:16 CEST  pre-events

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomMng002
      issued by : G4GeometryManager::UndertakeOptimisation
 Expected that all voxelisation work is done, but found that voxels headers are missing in 1 volumes. 

-------- EEEE -------- G4Exception-END --------- EEEE -------

%MSG
%MSG-w SimG4CoreApplication:  (NoModuleName) 24-Jul-2024 20:32:16 CEST  pre-events

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomMng002
      issued by : G4GeometryManager::UndertakeOptimisation
 Expected that all voxelisation work is done, but found that voxels headers are missing in 1 volumes. 

-------- EEEE -------- G4Exception-END --------- EEEE -------
```

**Comment by civanch** [comment]
@iarspider , the author of this new code is at vacations. I will think a bit what can be done but there is a probability that we put this update on hold.

**Comment by iarspider** [comment]
@civanch any updates on this?

**Comment by civanch** [comment]
This PR should be closed. When a new Geant4 reference version will be available a new PR may be opened.

**Pull request closed without merging**
