### PR TITLE
Update alpaka to the devel branch as of 2022.04.27 / 879b95ffce2

### PR DESCRIPTION
**Pull request by fwyzard**
Also:
  - remove the compiler flags from the alpaka tool files;
  - remove the Cupla external.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test
no idea why there are too many comparison failures

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
