### PR TITLE
Test PRs 4751 and 4616 gcc8 and root

### PR DESCRIPTION
**Pull request by mrodozov**
Get ROOT commit fixing https://sft.its.cern.ch/jira/projects/ROOT/issues/ROOT-9995?filter=allopenissues and test with gcc8.3

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
lets merge it for gcc820next and build a DEVEL IB

**Pull request merged**
