### PR TITLE
[13_0_X] Bumped CepGen version to 1.2.3

### PR DESCRIPTION
**Pull request by forthommel**
This PR bumps the version of CepGen to 1.2.3.
Changelog is available [here](https://cepgen.hepforge.org/changelog).

### CODE REVIEW

**Comment by forthommel** [comment]
They should :-)

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/44649

**Comment by smuzaffar** [comment]
+externals

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
