### PR TITLE
[102X][data] PhysicsTools-NanoAOD to tag 01-00-05

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of cmsdist#4937

### CODE REVIEW

**Comment by fabiocos** [comment]
@peruzzim @smuzaffar at this point in parallel we could just update this PR to use V01-00-05 and merge it to support the remaining tests in 10_2_X

**Comment by smuzaffar** [comment]
@fabiocos , I agree. 
If no objections then I can update this PR.

**Comment by peruzzim** [comment]
no objections, thanks

**Comment by smuzaffar** [comment]
+externals
done

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
