### PR TITLE
Update G4HepEm to new pre-release

### PR DESCRIPTION
**Pull request by hahnjo**
This includes an important fix to install all headers, among some other smaller changes developed during the last months.

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by hahnjo** [comment]
cc @civanch

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
looks good, dqm/reco comparison diff are due to message logger. lets re-fresh the tests and integrate

**Comment by civanch** [comment]
@smuzaffar , it seems that this update can be merged.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
