### PR TITLE
test latest crab client

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by mrodozov** [comment]
I'll see how did you proceeded with older version and merge it after that

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@belforte it can be integrated. can it go in ?

**Comment by belforte** [comment]
@mrodozov yes, certainly. Updating crab-dev is never a problem. I will try to make a new PR tomorrow for prod and pre to address the problem with py2-future

**Comment by belforte** [comment]
Please merge with this latest change as well. No need to re-test, but fell free. Thanks.

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
@belforte  I should close this, correct ? I've inspected the case with the missing py2-future in the 9 releases (I did it yesterday) . The thing is - even if I put it in the externals, it will be there for IBs but still missing from the 9_4 release.
Unless we build a release of course 😅

**Comment by smuzaffar** [comment]
@mrodozov , this should be merged. This updates crab dev. There are 3 card spec and these prs were updating different crab spec file

**Comment by belforte** [comment]
@mrodozov please merge. this will only affect crab-dev (yeah.. I made 3 different PR's for crab-prod, crab-pre and crab-dev) and this will create a new up-to-date version where the py2-futurize problem is rolled back.  A new release for CMSSW_9_ will not do, I suspect that py2-futurize is missing in other series as well. In any case that change was not sufficient for py3 compatibility of CRABClient, it will be something to address with much more care and time.

**Comment by mrodozov** [comment]
ah this is a dev version. alright :)

**Comment by mrodozov** [comment]
please test
lets try this add on one more time before 2300

**Pull request merged**
