### PR TITLE
Updated root to tip of branch v6-24-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
lets wait for ROOT624 IB.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
cms-bot/config.map is cleanup now for ROOT622. There were two entries one for ROOT624 and other was for ROOT622 which was confusing bot.

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
abort
this hanged hours due to runtime error, I'll restart it and then see if it does it again

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test
use newer root624 IB

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by smuzaffar** [comment]
@mrodozov , I would suggest that we merge it and build an IB

**Comment by smuzaffar** [comment]
@mrodozov , looks like IB is stuck ( https://cmssdt.cern.ch/jenkins/job/build-any-ib/107192/console ) , please check on the build node what it is doing, kill it if needed. Try to build the IB on cmsdev and report to root team to get help

**Comment by smuzaffar** [comment]
ah @mrodozov is away , I will check then

**Pull request merged**
