### PR TITLE
Update hwloc to version 2.7.1 [12.3.x]

### PR DESCRIPTION
**Pull request by fwyzard**
2.7.1 fixes several issues, all users are encouraged to upgrade.
The following is a summary of the changes since v2.7.0.

Version 2.7.1
-------------
* Workaround crashes when virtual machines report incoherent x86 CPUID
  information about numbers of cores and threads.
  Thanks to Peter Bense for the report.
* Use setenv() instead of putenv() when trying to force enable oneAPI L0
  support, to avoid issues with applications that touch the environment,
  thanks to Josh Hursey for the patch.
* Add some warnings at the end of configure when GPU libraries are
  missing on the system or their path is missing in the environment.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #7714

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
no idea why there are large number of comparison failure

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@perrotta @qliphy this is backport of https://github.com/cms-sw/cmsdist/pull/7714 . Feel free to merge it for 12.3.X

**Comment by perrotta** [comment]
+1

**Pull request merged**
