### PR TITLE
upgrade pythia8 to 243, vincia to 2.3.01, dire to 2.004

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
To be tested together with PR cmssw #28301

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/28301

**Comment by mrodozov** [comment]
@mkirsano do we have to put any patches from this branch 
https://github.com/cms-externals/pythia8/commits/cms/240
on top of this source ?

**Comment by mkirsano** [comment]
@mrodozov probaly yes. These changes are not included in 243. Adding @smrenna

**Comment by smuzaffar** [comment]
hold
we need go these changes ( https://github.com/cms-externals/pythia8/compare/8d04df9516d2975a2f719547b2bda93811d9ad86...cms/240 ) on top of pythia8 243

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
Reminder: to be tested together with PR cmssw #28301

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#28301
thanks @mkirsano

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar I will merge this and the corresponding cms-sw/cmssw#28301 for next IB

**Comment by fabiocos** [comment]
merge

**Pull request merged**
