### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**
This includes https://github.com/root-project/root/pull/16810

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test with cms-sw/cmssw#46635 for CMSSW_14_2_ROOT6_X

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46635 for CMSSW_14_2_ROOT6_X

**Comment by smuzaffar** [comment]
closing this in favor of #9512

**Pull request closed without merging**
