### PR TITLE
Update professor2 to 2.3.3

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for slc7_ppc64le_gcc11

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
assign generators

**Comment by SiewYan** [comment]
please test

**Comment by iarspider** [comment]
please test
GitHub is having issues - again

**Comment by SiewYan** [comment]
please test

lets do another one

**Comment by smuzaffar** [comment]
@SiewYan do you understand the various comparison differences [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-03-24-2300+831b74/49161/validateJR.html)?

**Comment by SiewYan** [comment]
@smuzaffar , I do not see the relevancy of the comparison in the context of professor2 upgrade. Most errors come from EGamma's..

**Comment by SiewYan** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
this looks good, @cms-sw/generators-l2  any objection on this update?

**Comment by SiewYan** [comment]
+1

Hello, I have no objection.

**Pull request merged**
