### PR TITLE
[10.2.X] Update MXNet to 1.5.0

### PR DESCRIPTION
**Pull request by hqucms**
Backport of https://github.com/cms-sw/cmsdist/pull/5148 to 10_2_X. 

This will be needed for the backport of https://github.com/cms-sw/cmssw/pull/28902.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
Backport of #5148

**Comment by mrodozov** [comment]
+externals

**Comment by smuzaffar** [comment]
@mrodozov , i guess we also needed cmssw pr to go with these mxnet updates. Didyou check with @slava77 and @silviodonato before merging these?

**Comment by mrodozov** [comment]
fixed . 
right, I didn't checked that it needs cms-sw pr.

**Comment by hqucms** [comment]
@smuzaffar @mrodozov We don't need any CMSSW PR for these updates -- the CMSSW PR that depends on this update will come afterwards.

**Comment by mrodozov** [comment]
@hqucms ok then, I'm signing #5591 & #5592 for externals

**Pull request merged**
