### PR TITLE
[11.1.X] Updated root to tip of branch v6-20-00-patches

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@smuzaffar I fixed the typo directly in https://github.com/cms-sw/cmsdist/tree/smuzaffar-patch-1 (see https://github.com/cms-sw/cmsdist/pull/6074/commits/f49bcb1eec982d1651bda487c0ccd66d3f41107a)

**Comment by smuzaffar** [comment]
please test
thanks @silviodonato

**Comment by smuzaffar** [comment]
+externals
FYI @silviodonato

**Comment by silviodonato** [comment]
+1

**Pull request merged**
