### PR TITLE
[EgammaAnalysis-ElectronTools] Push the 2018 S+S files

### LINKED ISSUE #4951: cms-data/EgammaAnalysis-ElectronTools#7:  Push the 2018 S+S files
A new Pull Request was created by  @rchatter (Rajdeep Mohan Chatterjee) for branch master.

Pull Request Reference: cms-data/EgammaAnalysis-ElectronTools#7

@smuzaffar, @gudrutis, @mrodozov can you please review it and eventually sign? Thanks.

### PR DESCRIPTION
**Pull request by smuzaffar**
resolves https://github.com/cms-sw/cmsdist/issues/4951
Note that this just adds couple of new files cms-data/EgammaAnalysis-ElectronTools#7

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
two new files added

**Comment by peruzzim** [comment]
There was some issue here, the e4bb35f commit above only updates PhysicsTools-NanoAOD to V01-00-05, and this is not consistent with its comment.
We need to have both PhysicsTools-NanoAOD->V01-00-05 and EgammaAnalysis-ElectronTools->V00-01-04 in 106X for #26845 to work.

**Comment by smuzaffar** [comment]
@peruzzim , https://github.com/cms-sw/cmsdist/pull/4996 now updated
PhysicsTools-NanoAOD->V01-00-05
EgammaAnalysis-ElectronTools->V00-01-04

**Pull request merged**
