### PR TITLE
Updated root to tip of branch v6-24-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov ., error is
```
@@@@ ----> OK  EDM Class Version 
>> Checking EDM Class Transients in libCUDADataFormatsBeamSpot.so
Error in <TUnixSystem::Load>: version mismatch, /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_ROOT624_X_2021-09-03-2300/lib/slc7_amd64_gcc900/libAnalysisDataFormatsTrackInfo.so = 62405, ROOT = 62407
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_ROOT624_X_2021-09-03-2300/src/FWCore/Utilities/scripts/edmCheckClassVersion", line 181, in <module>
    raise RuntimeError("failed to load library '"+options.library+"'")
RuntimeError: failed to load library 'libAnalysisDataFormatsTrackInfo.so'
@@@@ ----> OK  EDM Class Version 
>> Checking EDM Class Transients in libCUDADataFormatsCaloCommon.so
@@@@ ----> OK  EDM Class Version 
Suggestion: You can run 'scram build updateclassversion' to generate src/AnalysisDataFormats/TrackInfo/src/classes_def.xml.generated with updated ClassVersion
>> Checking EDM Class Transients in libCUDADataFormatsEcalRecHitSoA.so
gmake: *** [tmp/slc7_amd64_gcc900/edm_checks/libAnalysisDataFormatsTrackInfo.so] Error 1
```

update the root version in spec file and run full cmssw build

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test
too many comparison diffs

**Comment by mrodozov** [comment]
assign reconstruction
the reco diffs doesn't disappear

**Comment by slava77** [comment]
>  the reco diffs doesn't disappear

please rerun in a way that only this PR is added on top of the reference. 
This test had 16 more PRs. Even though some look technical, I'd rather not debug known differences from elsewhere.
Thanks.

**Comment by mrodozov** [comment]
see https://github.com/cms-sw/cmsdist/pull/7289

**Pull request closed without merging**
