### PR TITLE
Updated openloops to 1.2.4 and sherpa to version 2.2

### PR DESCRIPTION
**Pull request by thuer**
Backport of the changes for Sherpa and Openloops done in 81X

### CODE REVIEW

**Comment by thuer** [comment]
Aehm, I actually do not know what failed there, I have to take another look, but I do not see how that IntegrationTest_cfg.py is in anyway affected by Sherpa or the SherpaInterface

**Comment by covarell** [comment]
We had this error in other (unrelated) PRs before...

**Comment by thuer** [comment]
So we can ignore it / redo the test?

**Comment by covarell** [comment]
@degano can we have this merged anyway or is it a genuine error?

**Comment by ghost** [comment]
@covarell As I am unable to reproduce the error locally I'm merging this PR and its CMSSW counterpart. Please let's all keep an eye on the next IBs.

**Pull request merged**
