### PR TITLE
DD4Hep update to 1-16 tag

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@slava77 would you check the reco diffs ? It shows again ~3000 (as the last time)

**Comment by mrodozov** [comment]
+externals
workflows with failed comparisons  - 11634.911 -> 73407
similar to the last update

**Comment by cvuosalo** [comment]
Comparison differences in DD4hep workflow 11634.911 are expected with the new DD4hep version. The differences are minor statistical fluctuations.

**Comment by mrodozov** [comment]
fine this is getting in then

**Pull request merged**
