### PR TITLE
Add cmsmonitoring dependency

### PR DESCRIPTION
**Pull request by vkuznet**
This PR includes CMSMonitoring into DBS. This is required if we'll integrate NATS publisher into DBS codebase. This PR should be approved by Yuyi.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to a277d1b33824aca4204901c31ee7088dc0fd97f7 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5401/test_a277d1b-20191204-104837.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet , Valentin,

Should I merge this PR? 

Best
M Imran

**Comment by vkuznet** [comment]
Not yet I think since I'm awaiting for ok from Yuyi. This PR is related to https://github.com/dmwm/DBS/pull/617 (once we merge DMWM/DBS PR then we'll need this PR.

**Comment by amaltaro** [comment]
Given that DBS will have to be tested with the new curl/pycurl, should this also go in? @yuyiguo @vkuznet

**Comment by vkuznet** [comment]
Yes, I suggest this. Even we don't enable nats it does not affect anything since it is only a dependency.

@muhammadimranfarooqi , could you please merge this PR for next round to include in cmsweb upgrade.

**Comment by yuyiguo** [comment]
Alan.

I will take a look tomorrow.
Yuyi

**Pull request merged**
