### PR TITLE
Add Pybind11 

### PR DESCRIPTION
**Pull request by davidlange6**
header only library as possible boost.python alternative

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , cmssw-tool-conf should depend on py2-pybind11-toolfile if we want to have this tools known to scram.

**Comment by davidlange6** [comment]
hi @smuzaffar - It seems I forgot to include one commit that does exactly that.. One moment..

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
