### PR TITLE
Update pip to 21.3.1

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
hold
This should go along with changes needed for https://github.com/cms-sw/cmsdist/issues/7534  so that we rebuild once.

**Comment by smuzaffar** [comment]
closing as it has been integrated via https://github.com/cms-sw/cmsdist/pull/7696

**Pull request closed without merging**
