### PR TITLE
New spec for python3

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by BrunoCoimbra** [comment]
-1 to 1e8f12036221992772c41faf438497ff75510475 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2756/test_1e8f120-20170106-222506.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
test this please

**Comment by BrunoCoimbra** [comment]
+1 to 7fa78e63397f4a5354cb6a83e926920917023d1d on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2756/test_7fa78e6-20170107-022506.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
I put python3 spec into https://github.com/cms-sw/cmsdist/pull/2784, closing this PR

**Pull request closed without merging**
