### PR TITLE
libunwind - rename lib64 to lib if exists

### PR DESCRIPTION
**Pull request by mrodozov**
forcefully move lib64 to lib if it's there

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by smuzaffar** [comment]
@mrodozov , I am testing a bot feature to recognize past comments of users who had L2 rights but not any more. Can you please add a dummy comment on this PR?

**Comment by mrodozov** [comment]
dummy comment :)

**Comment by smuzaffar** [comment]
test comment

**Pull request merged**
