### PR TITLE
Build static library for vomsapi in condor - CC7

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes https://github.com/dmwm/WMCore/issues/7936

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 88a88ceea572d666efe2be277d16533e2aa9a745 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3323/test_88a88ce-20170801-151504.log" target="_blank">here</a>.

**Comment by davidlt** [comment]
Based on your build log posted in the issue:
```
-- external configured (VOMS_FOUND=/build/amaltaro/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4-comp4/condor-8.5.4/bld_external/voms-2.0.6/install/lib/libvomsapi.so)
```
Now you are building shared and static libraries, but it seems that shared is still picked. You need explicitly disable shared library (e.g. --disable-shared, check ./configure --help for exact command). Later verify CMake variables (e.g. `VOMS_FOUND`) to make sure that static version was picked).

**Comment by amaltaro** [comment]
I have some local changes and I built the condor RPM once again. @davidlt could you have a look at this log:
http://amaltaro.web.cern.ch/amaltaro/forAlan/condor-static-build-log2

I see the static library (libvomsapi.a) being built and linked to `VOMS_FOUND_STATIC`, however `VOMS_FOUND` still points to the shared one.

Do we need to set VOMS_FOUND to the static one or how it works?

**Comment by h4d4** [comment]
+1 to 2a9fdabc26c39e36aff45e9e72502f3f02e5c9e0 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3323/test_2a9fdab-20170802-234504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Tested this new condor RPM in a new agent and it works fine.
@bbockelm since you came up with that spec, can you please review.
@davidlt your input is also most welcome.

If they look ok, I'll then backport it to gcc493 as well.

**Review by bbockelm — APPROVED** [review]
Looks good to me!

**Comment by h4d4** [comment]
+1 to ca6daf9dbc72a02b0a7f207d897cc3a506697703 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3323/test_ca6daf9-20170807-105504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Next step will be to bump this condor version to 8.6.x (or 8.7.x). Trying to keep it aligned with the global pool versions. Anyways, that's for a future PR.

@h4d4 this PR can be merged now, thanks!

**Comment by amaltaro** [comment]
@h4d4 can you merge this, please? Thanks

**Pull request merged**
