### PR TITLE
upgrade rivet from 2.0.0 to 2.1.2 and yoda from 1.0.4 to 1.1.0

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
To be done simultaneously with PR CMSSW #4649

**Comment by lsonnens** [comment]
Please don't forget to include this important upgrade from  Rivet 2.0.0 to Rivet 2.1.2 into CMSSW_7_2_X. 
... and the we have to backport to CMSSW_7_1_X

**Comment by vciulli** [comment]
+1

**Comment by ktf** [comment]
@degano, can you try this out?

**Comment by ghost** [comment]
Yes, already started testing

**Pull request merged**
