### PR TITLE
[data] PhysicsTools-NanoAOD to tag 01-00-04

### LINKED ISSUE #4936: cms-data/PhysicsTools-NanoAOD#5: Updated lepton MVA weights for NanoAOD v5 and UL
A new Pull Request was created by  @peruzzim  for branch master.

Pull Request Reference: cms-data/PhysicsTools-NanoAOD#5

@smuzaffar, @gudrutis, @mrodozov can you please review it and eventually sign? Thanks.

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #4936

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-data/PhysicsTools-NanoAOD/pull/5

**Comment by fabiocos** [comment]
@mrodozov @smuzaffar concerning this conflict, if I understand the logic of this file both externals should be taken now, am I correct?

**Comment by fabiocos** [comment]
I would like to merge this asap, so as to start possibly building the external tools for 10_6_0

**Comment by smuzaffar** [comment]
+externals
@fabiocos , this is ready to be merged. Tests signature got reset due to merge conflicts. there is no need to re-run the tests

**Comment by smuzaffar** [comment]
@fabiocos , this is now merge. I see that this was tested with two cmssw PRs
cms-sw/cmssw#26703
cms-sw/cmssw#26672
while only one of these is merged in cmssw.

**Comment by peruzzim** [comment]
could you please update it also for 10_2_X? it is needed for cms-sw/cmssw#26769

**Comment by smuzaffar** [comment]
@peruzzim , https://github.com/cms-sw/cmsdist/pull/4967 is for 10.2.X

**Comment by peruzzim** [comment]
thanks

**Pull request merged**
