### PR TITLE
update to evtgen 2.0.0 and requirements to  hepmc 2.06.10, photospp 3…

### PR DESCRIPTION
**Pull request by alberto-sanchez**
This mean to update EvtGen to 2.0.0 and dependencies:

hepmc 2.06.10,
photospp 3.64, 
and tauolpp 1.1.8

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
Not quite ready yet. we need to update update 

https://github.com/cms-externals/evtgen/issues/1

first

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
ignore build-warnings

**Comment by alberto-sanchez** [comment]
@smuzaffar , @mrodozov , anything I can do from my side to fix this warnings which apparently does not belong to this PR

**Comment by alberto-sanchez** [comment]
+1

**Comment by qliphy** [comment]
please test

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmssw#32452

**Comment by mrodozov** [comment]
@alberto-sanchez this needs update on the CMSSW side. 
see this for example:
https://github.com/cms-sw/cmssw/pull/32420
if you see the the error scram tells you to checkout the package containing HepMC::HeavyIon
and change it's class version to new version

**Comment by mrodozov** [comment]
ah you already did. let me see

**Comment by mrodozov** [comment]
test parameters:
- pull_requests=cms-sw/cmssw#32452
- release_queue=CMSSW_11_3_X_2021-01-03-2300/slc7_amd64_gcc900

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals
@qliphy lets merge this and cms-sw/cmssw#32420 together on your request
@alberto-sanchez would this work without 32420 ? If yes, I can merge it first otherwise they go together

**Comment by alberto-sanchez** [comment]
@mrodozov, yes that should work without 32420. In 32452 I am updating the version for HepMC::HeavyIon, which
is the only required for this PR.

**Comment by mrodozov** [comment]
> I am updating the version for HepMC::HeavyIon

that will fail if I merge this. @qliphy merge them both when ready

**Comment by qliphy** [comment]
> In 32452 I am updating the version for HepMC::HeavyIon, which
> is the only required for this PR.

@alberto-sanchez  This has been done with your commit: https://github.com/cms-sw/cmssw/pull/32452/commits/965f6c6a003e8ae6def6e1aa5518eefe047db0cd
Right?  If so I think we can merge both PRs.

**Comment by alberto-sanchez** [comment]
That is correct.

**Comment by qliphy** [comment]
+1

**Pull request merged**
