### PR TITLE
Advance data for L1Trigger/L1TMuon to latest version.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-data/L1Trigger-L1TMuon/commit/9cd0907917af494d45bac8ac63acd5467d8d228a.

### CODE REVIEW

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by ghost** [comment]
@mulhearn this PR implements your changes from: cms-data/L1Trigger-L1TMuon#2. Does the error seems related to you?

**Comment by mulhearn** [comment]
I don't understand how... none of this code is exercised in standard sequences yet!  But it seems causally related, so probably I missed something.  I think it requires scrutiny...

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
@degano please note the status change... maybe there was problem with IB?  Anyway, this is good to go now.

**Comment by ghost** [comment]
@mulhearn Good, I'll merge it now then.

**Pull request merged**
