### PR TITLE
Pythia8.200pre2

### PR DESCRIPTION
**Pull request by bendavid**
@mkirsano

Add back pythia 8.200pre2 this time which solves some technical issues with headers and adds back a previously removed function needed by evtgen.

Because of the removal of the lhapdfdummy library from pythia8, the link options in the evtgen external are also modified.

### CODE REVIEW

**Comment by bendavid** [comment]
To be merged simultaneously with corresponding interface changes
https://github.com/cms-sw/cmssw/pull/5551

**Comment by bendavid** [comment]
+1

**Comment by bendavid** [comment]
@smrenna

**Comment by ghost** [comment]
+1
Tested compilation till cmssw-tool-conf.
Tested compilation and workflows of cms-sw/cmssw#5551 against this.

**Pull request merged**
