### PR TITLE
[10.6][pythia8] slha-multiple-reinitializations fix

### PR DESCRIPTION
**Pull request by smuzaffar**
Includes https://github.com/cms-externals/pythia8/pull/32  on top of existing pythia8 240

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
assign generators

**Comment by menglu21** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

@cms-sw/orp-l2 , feel free to merge it for next 10.6.X IB/release

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
