### PR TITLE
Rivet 4.0.0 and YODA 2.0.0

### PR DESCRIPTION
**Pull request by mseidel42**
Requires HepMC3, HDF5, and ONNX now.

Announcement at https://rivet.hepforge.org/

CMSSW PR coming -> https://github.com/cms-sw/cmssw/pull/44603

### CODE REVIEW

**Comment by mseidel42** [comment]
needs https://github.com/cms-sw/cmssw/pull/44603

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/44603

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
These might be dictionary related errors but they seem transient? See discusison in https://github.com/cms-sw/cmssw/pull/44603#issuecomment-2036561878

Any ideas? :/

**Comment by smuzaffar** [comment]
@mseidel42 , in the relval logs ( e.g. [135.4](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c03f46/38582/runTheMatrix-results/135.4_ZEEFS_13/step4_ZEEFS_13.log) ) I  see errors like
```
In file included from SimDataFormatsGeneratorProducts_xr dictionary payload:72:
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9111/38582/CMSSW_14_1_X_2024-04-03-1100/src/SimDataFormats/GeneratorProducts/interface/HepMC3Product.h:11:10: fatal error: 'HepMC3/GenEvent.h' file not found
#include <HepMC3/GenEvent.h>
```

could it be that we are missing `hepmc3` dependency somewhere in cmssw BuildFile

**Comment by smuzaffar** [comment]
or we now have `HepMC3/GenEvent.h` part of root dictionaries and we need to update the hepmc3 toolfile to have `<runtime name="ROOT_INCLUDE_PATH" value="$INCLUDE" type="path"/>` so that rootcling can find hepmc3 headers at rutime

**Comment by mseidel42** [comment]
Ah, just that one line or

```
  <runtime name="ROOT_INCLUDE_PATH"  value="$INCLUDE" type="path"/>
  <use name="root_cxxdefaults"/>
```

as in [hepmc_headers.xml](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_1_X/master/scram-tools.file/tools/hepmc/hepmc_headers.xml)?

I added hepmc3 to GeneratorInterface/RivetInterface/BuildFile.xml, and Mikhail had it added to SimDataFormats/GeneratorProducts/BuildFile.xml already before :)

**Comment by smuzaffar** [comment]
just `<runtime name="ROOT_INCLUDE_PATH"  value="$INCLUDE" type="path"/>` should be enough

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
It's trying to load an old (deprecated) and incompatible Rivet 3 analysis from the daily build instead of the PR build?

`#5  0x00001507c2747015 in Rivet::CMS_2013_I1224539_DIJET::~CMS_2013_I1224539_DIJET() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-03-2300/lib/el8_amd64_gcc12/RivetGeneratorInterfaceRivetInterface.so`

**Comment by smuzaffar** [comment]
@mseidel42 , I see that newly build `RivetGeneratorInterfaceRivetInterface.so` is PR area dos not have following symbols
```
typeinfo name for Rivet::AnalysisBuilder<Rivet::CMS_2013_I1224539_DIJET>
typeinfo name for Rivet::CMS_2013_I1224539_DIJET
```

e.g this library from IB has
```
> pwd
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9111/38595/CMSSW_14_1_X_2024-04-03-2300
> nm -D $CMSSW_RELEASE_BASE/lib/el8_amd64_gcc12/RivetGeneratorInterfaceRivetInterface.so | c++filt | grep Rivet::CMS
000000000000d280 R typeinfo name for Rivet::AnalysisBuilder<Rivet::CMS_2013_I1224539_DIJET>
000000000000d3c0 R typeinfo name for Rivet::CMS_2013_I1224539_DIJET
```

while same library from PR does not
```
> pwd
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9111/38595/CMSSW_14_1_X_2024-04-03-2300
> nm -D lib/el8_amd64_gcc12/RivetGeneratorInterfaceRivetInterface.so | c++filt | grep Rivet::CMS
>
```

so may be we need some updates in cmssw to properly register it ?

**Comment by mseidel42** [comment]
Hi Malik, that's an absolete analysis that I removed.
It has been superseded by https://gitlab.com/hepcedar/rivet/-/blob/release-4-0-x/analyses/pluginCMS/CMS_2013_I1224539.cc?ref_type=heads
Should I bring it back just to make this transition easier?

**Comment by smuzaffar** [comment]
please test

lets build full cmssw

**Comment by smuzaffar** [comment]
@mseidel42 , running `rivet --list-analyses -v` shows that `rivet` tries to read/load `RivetGeneratorInterfaceRivetInterface.so` from both PR area and cmssw base release area [a]. Building full cmssw with new rivet fixes this crash as in that case both `RivetGeneratorInterfaceRivetInterface` are build against the same version of rivet. But I think `rivet` should only read/load the first `RivetGeneratorInterfaceRivetInterface.so` found in RIVET_ANALYSIS_PATH? In general `rivet` should only read unique `Rivet<Name>.so`

[a]
```
[muzaffar@cmsdev41 rivet]$ rivet --list-analyses -v    
Setting log level: Rivet 10
Rivet.AnalysisLoader: DEBUG  Using plugin libraries from analysis-path search = [
 /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9111/38595/CMSSW_14_1_X_2024-04-03-2300/lib/el8_amd64_gcc12/RivetGeneratorInterfaceRivetInterface.so,
 /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-03-2300/lib/el8_amd64_gcc12/RivetGeneratorInterfaceRivetInterface.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetLHCfAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetD0Analyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetHERAAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetCESRAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetFrascatiAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetLHCbAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetBABARAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetALICEAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetTOTEMAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetTristanAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetRHICAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetLEPAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetCDFAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetCMSAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetNovosibirskAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetBELLEAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetBESAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetDORISAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetONNXAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetMiscAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetMCAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetPetraAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetOrsayAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetSPSAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetSLACAnalyses.so,
 /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/Rivet/RivetATLASAnalyses.so,
]
Rivet.AnalysisInfo: DEBUG  No datafile CMS_2013_I1224539_DIJET.info found

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fb05662c68b in waitpid () from /lib64/libc.so.6
#1  0x00007fb05658ece7 in do_system () from /lib64/libc.so.6
#2  0x00007fb044c2eacd in TUnixSystem::StackTrace() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9111/38595/CMSSW_14_1_X_2024-04-03-2300/external/el8_amd64_gcc12/lib/libCore.so
#3  0x00007fb044c2e484 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9111/38595/CMSSW_14_1_X_2024-04-03-2300/external/el8_amd64_gcc12/lib/libCore.so
#4  <signal handler called>
#5  0x00007fb04190e015 in Rivet::CMS_2013_I1224539_DIJET::~CMS_2013_I1224539_DIJET() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-03-2300/lib/el8_amd64_gcc12/RivetGeneratorInterfaceRivetInterface.so
#6  0x00007fb04190e899 in Rivet::CMS_2013_I1224539_DIJET::~CMS_2013_I1224539_DIJET() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-03-2300/lib/el8_amd64_gcc12/RivetGeneratorInterfaceRivetInterface.so
#7  0x00007fb056234bd4 in std::default_delete<Rivet::Analysis>::operator()(Rivet::Analysis*) const () from /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/python3.9/site-packages/rivet/core.so
#8  0x00007fb056230158 in std::unique_ptr<Rivet::Analysis, std::default_delete<Rivet::Analysis> >::~unique_ptr() () from /cvmfs/cms-ci.cern.ch/week1/PR_d6877065/el8_amd64_gcc12/external/rivet/4.0.0-015a44bf1dc6c18ae3688168d9ced02c/lib/python3.9/site-packages/rivet/core.so
#9  0x00007fb04960ec52 in Rivet::AnalysisBuilderBase::name[abi:cxx11]() const () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9111/38595/CMSSW_14_1_X_2024-04-03-2300/external/el8_amd64_gcc12/lib/libRivet.so
#10 0x00007fb0495f82b7 in Rivet::AnalysisLoader::_registerBuilder(Rivet::AnalysisBuilderBase const*) () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9111/38595/CMSSW_14_1_X_2024-04-03-2300/external/el8_amd64_gcc12/lib/libRivet.so
#11 0x00007fb04190b6c2 in _sub_I_65535_0.0 () from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-04-03-2300/lib/el8_amd64_gcc12/RivetGeneratorInterfaceRivetInterface.so

```

**Comment by mseidel42** [comment]
Ok, I am trying to patch it

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by mseidel42** [comment]
--> test test-genParticles2HepMC had ERRORS

> Fatal system signal has occurred during exit

Still not sure what to do about this exit error. Could it be related to https://github.com/cms-sw/cmssw/issues/40347?

---> test TestGeneratorInterfacePythia8ConcurrentGeneratorFilter had ERRORS

[This test](https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Pythia8Interface/test/test_Pythia8ConcurrentGeneratorFilter_WZ_TuneCP5_13TeV-pythia8.sh#L3) fails to fetch the GEN fragment from [McM](https://cms-pdmv-prod.web.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-RunIISummer20UL17GEN-00002).

```
% cat GIP8/BTV-RunIISummer20UL17GEN-00002-fragment.py
{"message": "Internal Server Error"}
```

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
Hi, I tried adding a couple more dictionary entries for HepMC3 classes:
```xml
 <class name="HepMC3::GenEvent"/>
 <class name="HepMC3::Attribute"/>
 <class name="HepMC3::GenParticle"/>
 <class name="HepMC3::GenVertex"/>
 <class name="HepMC3::FourVector"/>
 <class name="HepMC3::GenParticleData"/>
 <class name="HepMC3::GenRunInfo"/>
 <class name="HepMC3::GenRunInfo::ToolInfo"/>
 <class name="HepMC3::GenVertexData"/>
 <!--
 <class name="shared_ptr&lt;HepMC3::GenParticle&gt;"/>
 <class name="shared_ptr&lt;HepMC3::GenRunInfo&gt;"/>
 <class name="shared_ptr&lt;HepMC3::GenVertex&gt;"/>
 -->
 <class name="weak_ptr&lt;HepMC3::GenParticle&gt;"/>
 <class name="weak_ptr&lt;HepMC3::GenVertex&gt;"/>
 <class name="std::vector&lt;HepMC3::GenRunInfo::ToolInfo&gt;"/>
 <class name="std::map&lt;int,std::shared_ptr&lt;HepMC3::Attribute&gt; &gt;"/>
 <class name="std::map&lt;string,std::shared_ptr&lt;HepMC3::Attribute&gt; &gt;"/>
 <class name="std::map&lt;string,std::map&lt;int,std::shared_ptr&lt;HepMC3::Attribute&gt; &gt; &gt;"/>
 <class name="std::pair&lt;int,std::shared_ptr&lt;HepMC3::Attribute&gt; &gt;"/>
 <class name="std::pair&lt;string,std::shared_ptr&lt;HepMC3::Attribute&gt; &gt;"/>
 <class name="std::pair&lt;string,std::map&lt;int,std::shared_ptr&lt;HepMC3::Attribute&gt; &gt; &gt;"/>
 <class name="std::vector&lt;std::shared_ptr&lt;HepMC3::GenParticle&gt; &gt;"/>
 <class name="std::vector&lt;std::shared_ptr&lt;HepMC3::GenVertex&gt; &gt;"/>
```

Running `GeneratorInterface/Pythia8Interface/test/pythia8hmc3ex2_cfg.py` still gives me 
```
----- Begin Fatal Exception 13-May-2024 18:19:05 CEST-----------------------
An exception of category 'DictionaryNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=Pythia8HepMC3GeneratorFilter label='generator'
   [2] Calling ProductRegistryHelper::addToRegistry, checking dictionaries for produced types
Exception Message:
No data dictionary found for the following classes:

  _Mutex_base<__gnu_cxx::_S_atomic>
  _Sp_counted_base<__gnu_cxx::_S_atomic>
  __recursive_mutex_base
  __shared_count<__gnu_cxx::_S_atomic>
  __shared_ptr<HepMC3::GenParticle>
  __shared_ptr<HepMC3::GenRunInfo>
  __shared_ptr<HepMC3::GenVertex>
  __shared_ptr_access<HepMC3::GenParticle,__gnu_cxx::_S_atomic,false,false>
  __shared_ptr_access<HepMC3::GenRunInfo,__gnu_cxx::_S_atomic,false,false>
  __shared_ptr_access<HepMC3::GenVertex,__gnu_cxx::_S_atomic,false,false>
  __weak_count<__gnu_cxx::_S_atomic>
  __weak_ptr<HepMC3::GenParticle,__gnu_cxx::_S_atomic>
  __weak_ptr<HepMC3::GenVertex,__gnu_cxx::_S_atomic>
  enable_shared_from_this<HepMC3::GenParticle>
  enable_shared_from_this<HepMC3::GenVertex>
  recursive_mutex
  shared_ptr<HepMC3::GenParticle>
  shared_ptr<HepMC3::GenRunInfo>
  shared_ptr<HepMC3::GenVertex>

Most likely each dictionary was never generated, but it may
be that it was generated in the wrong package. Please add
(or move) the specification '<class name="whatever"/>' to
the appropriate classes_def.xml file along with any other
information needed there. For example, if this class has any
transient members, you need to specify them in classes_def.xml.
Also include the class header in classes.h

A type listed above might or might not be the same as a
type declared by a producer module with the function 'produces'.
Instead it might be the type of a data member, base class,
wrapped type, or other object needed by a produced type. Below
is some additional information which lists the types declared
to be produced by a producer module that are associated with
the types whose dictionaries were not found:

  edm::HepMC3Product

----- End Fatal Exception -------------------------------------------------
```

I'm a bit lost what to do about the `atomic` stuff, is this supposed to go into the dict as well?

Furthermore, when I try adding the `shared_ptr`s I get this:
```
>> Building LCG reflex dict from header file src/SimDataFormats/GeneratorProducts/src/classes.h
Error: Class shared_ptr<HepMC3::GenParticle> has been selected but currently the support for its I/O is not yet available. Note that shared_ptr<HepMC3::GenParticle>, even if not selected, will be available for interpreted code.
Error: Class shared_ptr<HepMC3::GenVertex> has been selected but currently the support for its I/O is not yet available. Note that shared_ptr<HepMC3::GenVertex>, even if not selected, will be available for interpreted code.
Error: Class shared_ptr<HepMC3::GenRunInfo> has been selected but currently the support for its I/O is not yet available. Note that shared_ptr<HepMC3::GenRunInfo>, even if not selected, will be available for interpreted code.
```

**Comment by makortel** [comment]
Does `HepMC3` internally use `std::shared_ptr`?

**Comment by makortel** [comment]
> Does `HepMC3` internally use `std::shared_ptr`?

The answer is yes, and apparently heavily (links below are not exhaustive)
https://gitlab.cern.ch/hepmc/HepMC3/-/blob/254c5f4fb9d7a3d7c6c04f3508d5cbbaeac6e707/include/HepMC3/GenEvent.h#L389-394
https://gitlab.cern.ch/hepmc/HepMC3/-/blob/254c5f4fb9d7a3d7c6c04f3508d5cbbaeac6e707/include/HepMC3/GenEvent.h#L370
https://gitlab.cern.ch/hepmc/HepMC3/-/blob/254c5f4fb9d7a3d7c6c04f3508d5cbbaeac6e707/include/HepMC3/GenParticle_fwd.h#L21

Unfortunately we can't store objects of this class because of the use of `shared_ptr`.

On a cursory look it seems to me `HepMC3` itself uses a transient-persistent model via `GenEvent` <-> `GenEventData` classes, see e.g. an example in
https://gitlab.cern.ch/hepmc/HepMC3/-/blob/254c5f4fb9d7a3d7c6c04f3508d5cbbaeac6e707/rootIO/src/WriterRootTree.cc#L85
The `GenEventData` looks like something that can be stored.

**Comment by mseidel42** [comment]
Hi Matti, thanks for checking!

I see there are `GenEvent::read/write_data()` functions, I will try those for passing the event as `GenEventData` between CMSSW modules.

**Comment by mseidel42** [comment]
Updated https://github.com/cms-sw/cmssw/pull/44603 so that the HepMC3Product now contains GenEventData instead of GenEvent. My local tests look fine...

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
Hi, would it be possible to proceed with this PR?

Matti did not have any additional comments in the corresponding https://github.com/cms-sw/cmssw/pull/44603

**Comment by smuzaffar** [comment]
lets test https://github.com/cms-sw/cmssw/pull/44603 and once that is approved/merged then we merge this PR too

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/44603 has been merged  so this should also get in to IB otherwise we will have broken IBs

**Comment by mseidel42** [comment]
Right, thanks! :slightly_smiling_face:

**Comment by smuzaffar** [comment]
see https://github.com/cms-sw/cmssw/pull/44603/files#r1663891689

**Pull request merged**
