### PR TITLE
Geant4p03 tf fix 75 x

### PR DESCRIPTION
**Pull request by ghost**
+1
Tested compilation.
Tested compilation of SimG4Core/ against it.
Tested matrix tests against it.

### CODE REVIEW

**Comment by civanch** [comment]
@degano , Great! do not forget the Geant4e patch on top of 10.0p03. For any case I put a link for any case: http://vnivanch.web.cern.ch/vnivanch/verification/verification/data/geant4-10.0p03-cms.patch

**Comment by ghost** [comment]
@civanch sorry, I don't understand: so https://github.com/cms-externals/geant4/tree/cms/4.10.00.p03  never had that patch?
But it does have other cms patches?

**Comment by ghost** [comment]
@civanch Here you can see what we already have on the externals on top of 4.10.00.p03:
https://github.com/cms-externals/geant4/compare/4.10.00.p03...cms/4.10.00.p03 it seems that patch is already merged in.
Can you confirm please?

**Comment by civanch** [comment]
@degano , Thanks, Geant4e is there. This is what we need.

**Pull request merged**
