### PR TITLE
[10.6] Update tag for GeneratorInterface-EvtGenInterface to V02-06-00

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of https://github.com/cms-sw/cmsdist/pull/7037

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mgratti** [comment]
@smuzaffar, @mrodozov, @iarspider , sorry, but I think that this PR was forgotten?

**Comment by smuzaffar** [comment]
+externals
@mgratti , normally it is up to release managers (@silviodonato  , @qliphy ) to merge changes for old release cycles. They normally do it before building a requested release.

@silviodonato  , @qliphy this PR only adds new files, so should be safe to merge. I have no idea how urgent it is to build a new 10.6 release with this change.

**Comment by qliphy** [comment]
+1

**Pull request merged**
