### PR TITLE
Backport tag update for L1Trigger-L1TGlobal from IB/CMSSW_12_4_X/master

### PR DESCRIPTION
**Pull request by aandvalenzuela**
backport of #7769

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
@aandvalenzuela , there is a build error 
```
ERROR: Duplicate data package definitions found in /data/cmsbld/jenkins/workspace/ib-run-pr-tests/cmsdist/data/cmsswdata.txt for package L1Trigger-L1TGlobal
```
I think you have forgot to remove the L1Trigger-L1TGlobal=V00-01-00 line?

**Comment by smuzaffar** [comment]
ah you need to remove https://github.com/cms-sw/cmsdist/pull/7770/files#diff-27429f03ae22541c3e2b9d4a96fc49fd32d75d896a8b0bb48079ec02ec461887L104 too . For each data repo we can only have one entry in cmsswdata.txt file

**Comment by aandvalenzuela** [comment]
Done! Sorry, I was confused. Since the section states _#Never update any package here. Always move it to default section._ I didn't touch it. Should we update the comment as well?

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
@aandvalenzuela , sure go ahead and update the comment. I thought `move` in "Always move it to default section" was enough :-)

**Comment by smuzaffar** [comment]
@aandvalenzuela , can you please also update the PR description and include `backport of cms-sw/cmsdist#7769` . This will allow cms bot to add the `backport` label e.g. see https://github.com/cms-sw/cmsdist/pull/7755#issue-1194557162

**Comment by aandvalenzuela** [comment]
Description updated! And for the comment, I think you are right, `move` should be enough jeje

**Comment by perrotta** [comment]
please test with #37497

**Comment by aandvalenzuela** [comment]
Hi @perrotta! Please, link the PR to _cms-sw/cmssw_ so that the bot can find the reference to start the tests. Thank you!

**Comment by perrotta** [comment]
please test with https://github.com/cms-sw/cmssw/pull/37497

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
+1
- Tested together with https://github.com/cms-sw/cmssw/pull/37497

**Pull request merged**
