### PR TITLE
Bump py3 dbs3-client to 4.0.5

### PR DESCRIPTION
**Pull request by amaltaro**
This has a fix to sanitize the DbsUrl in the DbsApi class, such that no trailing slashes will pass through.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to e4d1d4390b38c954be7763c8fc6a1f21d56439f2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7524/test_e4d1d43-20211220-090503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Comment by amaltaro** [comment]
@belforte FYI

**Comment by belforte** [comment]
@mapellidario please rebuild TW image and make sure that CRAB preprod instance runs with this

**Pull request merged**
