### PR TITLE
Use thepeg from cms-externals and update, update herwigpp.

### PR DESCRIPTION
**Pull request by ghost**
This PR overrides #881.

### CODE REVIEW

**Comment by ghost** [comment]
+1
Tested locally compilation till full cmssw-tool-conf.

**Comment by ktf** [comment]
In general try to avoid merge commits for cmsdist. Always rebase the branch before merging.

**Comment by ghost** [comment]
@ktf ok, fixed it.

**Comment by bendavid** [comment]
@degano and @mkirsano can we prepare the corresponding pull requests for the backport to both 71x and 53x?

**Comment by mkirsano** [comment]
71x is done (merged)
  53x is in PR (for some time already).

**Pull request merged**
