### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
lets get this in IB to see what else is failing

**Comment by slava77** [comment]
the following commands lead to a segfault now in CMSSW_11_0_ROOT6_X_2019-08-29-2300

```python
 import os, re, sys, time, ROOT, subprocess
 from DataFormats.FWLite import Events, Handle
 muonHandle = Handle("std::vector<pat::Muon>")
```

The stack trace snippet is (omitting stack addresses and some paths  are truncated)
```
#7  <signal handler called>
#8   in TString::IsLong (this=0xd8) at include/TString.h:224
#9   in TString::GetPointer (this=0xd8) at include/TString.h:243
#10  in TString::Data (this=0xd8) at include/TString.h:364
#11  in TDataMember::GetTrueTypeName (this=0x0) at [...]/core/meta/src/TDataMember.cxx:625
#12  in Cppyy::GetDatamemberType[abi:cxx11](long, long) (scope=22, idata=-1) at [...]/pyroot/src/Cppyy.cxx:976
#13  in PyROOT::PropertyProxy::Set (this=0x7ff921c42e40, scope=22, name="InEvent", address=0x3b1f600) at [...]/pyroot/src/PropertyProxy.cxx:220
#14  in PyROOT::PropertyProxy_NewConstant (scope=22, name="InEvent", address=0x3b1f600) at [...]/pyroot/src/PropertyProxy.h:78
#15  in (anonymous namespace)::AddPropertyToClass (pyclass=0x41ebf40, scope=22, name="InEvent", address=0x3b1f600) at [...]/pyroot/src/RootWrapper.cxx:128
#16  in BuildScopeProxyDict (scope=22, pyclass=0x41ebf40) at [...]/pyroot/src/RootWrapper.cxx:369
#17  in PyROOT::CreateScopeProxy (scope_name="edm", parent=0x7ff935350980) at [...]/pyroot/src/RootWrapper.cxx:687
#18  in (anonymous namespace)::LookupCppEntity (pyname=0x0, args=0x7ff934366200) at [...]/pyroot/src/RootModule.cxx:194
#19  in call_function (oparg=<optimized out>, pp_stack=0x7fff2bee4480) at Python/ceval.c:4357
```

**Comment by smuzaffar** [comment]
@slava77 , this should be fixed with latest root update https://github.com/cms-sw/cmsdist/pull/5186. See https://sft.its.cern.ch/jira/browse/ROOT-10294

**Pull request merged**
