### PR TITLE
Extended the lock coverage when calling into Frontier

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@smuzaffar I don't know how to properly add this to the spec file nor how to test in the cmsdist environment.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@Dr15Jones , please provide your patch via http://github.com/cms-externals/coral repo

**Pull request closed without merging**
