### PR TITLE
crabclient for Nov 2015 release

### PR DESCRIPTION
**Pull request by belforte**
Dear Diego and Bruno
this is new Crabclient for 1511 release to be put in CVMFS
This is the first time I do this, covering for Marco who is away.
I am not sure what is the recommended way to communicate that this is for production rather than pre, i.e. that it will be accessed via `/cvmfs/cms.cern.ch/crab3/crab.sh` rather than
`/cvmfs/cms.cern.ch/crab3/crab_pre.sh`

On the substance, there is no chance from previous tag made by Marco, which was tested, so this PR should be safe.

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to adc22b98ef6e40e0a82c612e9b608b80dde1c055 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1941/test_adc22b9-20151105-144503.log" target="_blank">here</a>.

**Comment by juztas** [comment]
Merged. @BrunoCoimbra please cherrypick this to new arch.

**Comment by juztas** [comment]
@belforte communicate is that we all are almost in the same office and I have access and rights to merge ONLY for crabclient. So whenever +1 is got, I am merging it. Maybe the new guy/girl who will change us can get access and he/she also has to know all cons/pros and how safely to do that :)

**Comment by belforte** [comment]
@juztas ?? do you mean that you can only merge crabclient.spec file in this repository  ? Are authorizations so fine grained ? Who does it for other crab\* and ASO\* components ?

**Comment by belforte** [comment]
can someone comment on how it exactly happen that this makes it to CVMFS ? which are the steps ? the checks, the authorizations ? Merging I understand (permissions aside). But from githup to cvmfs ? And from one more release to replacing symlinks like crab.sh and/or crab_pre.sh ?

**Comment by juztas** [comment]
lets move to crab-dev

**Pull request closed without merging**
