### PR TITLE
update RecoMET-METPUSubtraction data for backport DeepMET into CMSSW_10_6_X

### PR DESCRIPTION
**Pull request by yongbinfeng**
The DeepMET was added to CMSSW from CMSSW_11_1_0_pre8, 

https://github.com/cms-sw/cmssw/pull/29764/

with the modification to cms-data

https://github.com/cms-data/RecoMET-METPUSubtraction/pull/5

and cms-dist

https://github.com/cms-sw/cmsdist/pull/5826

Now we would like to backport this change so DeepMET could be running with CMSSW_10_6_X: https://github.com/cms-sw/cmssw/pull/30612

@steggema  @intrepid42

### CODE REVIEW

**Comment by yongbinfeng** [comment]
any expert could provide some help on this? we don't have much clue on how to fix this...

**Comment by mrodozov** [comment]
please test

**Comment by yongbinfeng** [comment]
move the updates of RecoMET-METPUSubtraction to the default section. Does it look good now? Also, is it needed to make the same change to the `IB/CMSSW_10_6_X/gcc820` branch as well?

**Comment by smuzaffar** [comment]
yes it looks good now

**Comment by silviodonato** [comment]
merge
adding new files, see https://github.com/cms-data/RecoMET-METPUSubtraction/compare/V01-00-03...V01-01-00

**Pull request merged**
