### PR TITLE
CMS data popularity app and Victor the cleaner

### PR DESCRIPTION
**Pull request by rcaspart**
Dear all,

This pullrequest includes the specfiles required to build the rpms for the CMS data popularity service (popdb), the associated monitoring 'Victor the cleaner' and the required django 1.4.13 python module.

Feel free to comment or make any suggestions to this.

Cheers,
Rene

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to acb69c45380d226fa9535cd6de95571e19d991bc on slc6_amd64_gcc481.

**Comment by nikmagini** [comment]
Hi all,

the spec files for the 'popdb' and 'victor' rpms point to Rene's fork of the DDM repo. I think we need to merge back rcaspart/DDM into dmwm/DDM and then get the rpms from there.
Also a comment about the rpm names: I would suggest to change them to 'popdb-web' and 'victor-web' to avoid confusing them with the agent rpms

Thanks
Nicolo'

**Comment by geneguvo** [comment]
-1 to 35a7a5135488a62f2b1a61230eff34a0bcdf2775 on slc6_amd64_gcc481.

**Comment by rcaspart** [comment]
Hi all,

as suggested by @nikmagini I appended "-web" to the names of both services. I also changed the repository from which the releases are pulled to the dmwm repository.

Cheers,
Rene

**Comment by nikmagini** [comment]
Hi Rene', Diego,

what was the issue in the build test?

Thanks
Nicolò

**Comment by nikmagini** [comment]
Hi Rene',

can you please check why the build test failed?

Thanks
N

**Comment by rcaspart** [comment]
Hi Nicolo,

for me building with these files works fine. Maybe the test fails due to the changed names of the services (in case it specifically tries to build victor and popdb)?

Cheers,
Rene

**Comment by geneguvo** [comment]
The builder tests are failing since last week when github was made to send back redirections for a few URLs. I'm fixing it.

**Comment by geneguvo** [comment]
+1 to 35a7a5135488a62f2b1a61230eff34a0bcdf2775 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
I've pushed everything with my changes after review and it will be included in the next testbed. Later we have to fix the URLs in conf.ini as discussed, but as it is right now it would be already useful for testing/validation on testbed.

**Pull request closed without merging**
