### PR TITLE
[Backport 12_5] Pythia Update to fix tau decays

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Backport of https://github.com/cms-sw/cmsdist/pull/8139, following https://github.com/cms-sw/cmsdist/pull/8147#issuecomment-1293165101.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test with https://github.com/cms-externals/pythia8/pull/29

**Comment by smuzaffar** [comment]
@aandvalenzuela , as cms-externals/pythia8#29 has been merged so no need explicitly test with `https://github.com/cms-externals/pythia8/pull/29`. A simple `please test` should be fine :-)

**Comment by perrotta** [comment]
+1
- As decided during the [ORP meeting of Oct 25](https://indico.cern.ch/event/1208164/) 
- It does not affect minbias production for PU samples
- It would be desirable for the Phase2 MC productions

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
