### PR TITLE
[Backport 12_4_X] Update tag for L1Trigger-CSCTriggerPrimitives to V00-12-00

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Backport https://github.com/cms-sw/cmsdist/pull/8003

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test with https://github.com/cms-sw/cmssw/pull/38722

**Comment by aandvalenzuela** [comment]
+1

**Comment by aandvalenzuela** [comment]
merge

**Comment by perrotta** [comment]
+1
- It has to go with https://github.com/cms-sw/cmssw/pull/38722, and tested together with it

**Pull request merged**
