### PR TITLE
Drop byacc

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , I do not think that this external is used by cmssw (at least I do not see any spec e.g. *-tool-conf using it). So better to just drop it.

**Comment by iarspider** [comment]
@smuzaffar sure.

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by mrodozov** [comment]
listing the externals by reverse date of last update might show others to be disposed of :)
this one has not been updated in 9 years

**Review by smuzaffar — APPROVED** [review]

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
