### PR TITLE
Update Jemalloc to 4.0.4.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by smuzaffar** [comment]
cmsbuild, please test
last time it has used a broken IB

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
@davidlt @fwyzard The tests ran fine and didn't find any issue. Should we try to merge this upgrade in the DEVEL branch?

**Comment by davidlange6** [comment]
would be great!
Thanks Alessandro

**Comment by davidlt** [comment]
Someone should do memory consumption and performance comparison between older and newer jemalloc versions, not that I expect any significant differences, but it would be nice to know.

**Comment by davidlange6** [comment]
Right - we can compare that in the devel IB and then push into the mainstream.

**Comment by davidlange6** [comment]
Hi- looks like the memory gets quite a bit worse with this change (i’m comparing 02-09-1100 and 02-15-1100). Lets revert and see that indeed things get better again (it can be because of something else that I have not noticed)

**Comment by davidlt** [comment]
You should be comparing a single IB with different jemallocs. It's just a single scram setup && cmsenv and you have new jemalloc.

**Comment by davidlange6** [comment]
ok- then I’ll try to set up the old jemalloc in -15 and check

**Pull request merged**
