### PR TITLE
Update ROCm to version 5.6

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for el9_amd64_gcc11

**Comment by fwyzard** [comment]
please test for el8_amd64_gcc12

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc11

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for el9_amd64_gcc11

**Comment by fwyzard** [comment]
please test for el8_amd64_gcc12

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc11

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for el8_amd64_gcc12

**Comment by fwyzard** [comment]
please test for el9_amd64_gcc11

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc11

**Comment by fwyzard** [comment]
@smuzaffar this should be fine to merge after pre2 is out.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
