### PR TITLE
Update Geant4 to 11.2.ref03

### PR DESCRIPTION
**Pull request by iarspider**
Resolves https://github.com/cms-externals/geant4/issues/80

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
build and run step are successful. lets get this in for G4 IBs

**Comment by civanch** [comment]
@iarspider , @smuzaffar , I may be misunderstand something but it seems to me that the update is done in the master while we are suppose to make it in GEANT4 and G4VECGEOM branches only.

**Comment by iarspider** [comment]
@civanch as far as I can tell, [geant4 in master](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_1_X/master/geant4.spec) is still 11.2.1. Can you give us commands to reproduce your result?

**Pull request merged**
