### PR TITLE
DMWMMON-datasvc version 1.1.0 for HG1602 release.

### PR DESCRIPTION
**Pull request by nataliaratnikova**
Changelog:
- storageusage  - implemented new algorithm that fixes serious bugs
- getlastrecord - improved documentation
- dumppacequery - new API useful for debugging

### CODE REVIEW

**Comment by nataliaratnikova** [comment]
Please take into HG1602, hope I got it merged right this time.

**Comment by geneguvo** [comment]
+1 to 40e176ec7c48905e737d079feda86c9cc7a3f49c on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2101/test_40e176e-20160127-224515.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
I already included PR #2098 with no problems. As they contain the same changes I'm closing this one.

**Comment by nataliaratnikova** [comment]
Thanks, Bruno!  I did not realize the automated builds aren't done from my feature branch. They seem to use  my  upstream target branch, which was far behind. 
Once I merged cms-sw/comp-gcc493 to my upstream,  both feature branches I created from it succeeded.

**Pull request closed without merging**
