### PR TITLE
[COMP][DQMGUI] Sync Root 6.14 changes from IB/CMSSW_10_6_X/rootnext branch

### PR DESCRIPTION
**Pull request by smuzaffar**
As mentioned in https://github.com/cms-sw/cmsdist/pull/4882, this will be needed for DQMGUI once we have 6.14 in a CMSSW release.

FYI @schneiml , @rovere, @andrius-k, @kmaeshima, @jfernan2, @fioriNTU .

### CODE REVIEW

**Comment by h4d4** [comment]
-1 to 0f40b155630925f3c08c8fc7d3819182ebbff300 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4941/test_0f40b15-20190507-211505.log" target="_blank">here</a>.

**Comment by davidlange6** [comment]
hi @smuzaffar - seems the ancient matplotlib in comp is too old for the libpng update. Is that update needed?

**Comment by smuzaffar** [comment]
@davidlange6 , we need this update not for root itself but matplotlib which is part of dqmgui. comp matploylib is picking up libpng from system that is why it failed but missing dependency. I will update this PR to include new matplotlib and its deps

**Comment by smuzaffar** [comment]
FYI @schneiml , @rovere, @andrius-k, @kmaeshima, @jfernan2, @fioriNTU
I have update this PR to get the minimal changes needed to build root 6.14. DQMQUI might still fail (might need to update dqmgui to latest cmssw sources).
What about protobuf? Current version of protobuf in comp/dqmgui is 2.6.1 while we have 3.5.2 in cmssw.

**Comment by h4d4** [comment]
+1 to 6982d6421a930ab4e87323f5b306bf8caeee3843 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4941/test_6982d64-20190508-135005.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to d7cbc21504831208d968f5e50fc6f39f53707ffd on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4941/test_d7cbc21-20190508-151004.log" target="_blank">here</a>.

**Comment by schneiml** [comment]
@smuzaffar We did not update the CMSSW parts used in DQMGUI in a long time, and that is perfectly fine; the (legacy, `DQM*.root`) file format rarely changes.

So if current DQMGUI version compiles and runs with the new ROOT, we should be good to go.

Thanks for the help, I'll close my PR.

**Comment by schneiml** [comment]
@smuzaffar re protobuf: Afaik the protobuf functionality in DQMGUI is not used at all in production, so it should not matter. But, better to update it as well if it is not too complicated.

**Comment by smuzaffar** [comment]
protobuf is now in sync with cmssw

**Comment by h4d4** [comment]
+1 to 57b54ebd8da36f826cd89a60fc079d67a6959a59 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4941/test_57b54eb-20190513-105952.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
@schneiml , FYI CMSSW_10_6_0 is now out with root updated 6.14

**Comment by schneiml** [comment]
@smuzaffar yes, I noticed.

@h4d4 can we get this onto the testbed soonish? If the release schedule holds, we'll have a production-ready release just in time for the MWGR, where we will need to deploy this in online DQM.

**Comment by schneiml** [comment]
@h4d4 anything blocking a testbed deployment of this?

**Comment by amaltaro** [comment]
@schneiml Marcel, cmsdist comp_gcc630 changes need to be requested in the usual CMSWEB tickets. Next release is HG1906, so here is the ticket where you ask for these changes to be included:
https://gitlab.cern.ch/cms-http-group/doc/issues/161

**Comment by schneiml** [comment]
@amaltaro hmm, I never went via a ticket in the past. Let me go there...

**Comment by h4d4** [comment]
@smuzaffar @schneiml 

Including the PR to deploy in testbed today.

Best Regards, Lina.

**Pull request merged**
