### PR TITLE
[DQM] Bump dmqgui version

### PR DESCRIPTION
**Pull request by nothingface0**
Update DQMGUI version ([9.8.1](https://github.com/cms-DQM/dqmgui_prod/releases/tag/9.8.1)) to include a patch.

### CODE REVIEW

**Comment by arooshap** [comment]
please test

**Comment by arooshap** [comment]
+1 to cf9e5d18e1671cb18c335b880fd9175b63eb3ead on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8887/test_cf9e5d1-20231215-214002.log" target="_blank">here</a>.

**Comment by arooshap** [comment]
@nothingface0, your build tests passed. Is this PR ready to be incorporated?

**Comment by dpapagiannis** [comment]
@arooshap I believe so, it's a very small change which should fix an error in a python script, so, yes. 

It's also a bit urgent, as it breaks several services (running on `vocms0731` and `vocms0739`). 

CC: @syuvivida @tjavaid @antoniovagnerini

**Pull request merged**
