### PR TITLE
[Do not merge] Testing runtime cxxmodules with reverting a patch

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
allow @yamaguchi1024 test rights

**Comment by yamaguchi1024** [comment]
please test

**Comment by smuzaffar** [comment]
@yamaguchi1024,  you have just killed 8 hours of testing :-( tests where already running. Build phase went fine (i.e no more std::bad_alloc error).

**Comment by smuzaffar** [comment]
@yamaguchi1024 , unit tests failed with error
```
===== Test "test_root_PyMVA" ====

Processing test_PyMVA.cpp+...
Info in <TUnixSystem::ACLiC>: creating shared library /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_4_ROOT6_X_2018-12-17-2300/tmp/test_PyMVA/./test_PyMVA_cpp.so
In module 'stl':
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1117:2: error: 'std::boyer_moore_searcher::_M_bad_char_shift' from module 'stl.functional' is not present in definition of 'boyer_moore_searcher<_RAIter, _Hash, _BinaryPredicate>' in module 'stl.functional'
        _M_bad_char_shift(_Tp __c) const
        ^
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1117:2: note: declaration of '_M_bad_char_shift' does not match
        _M_bad_char_shift(_Tp __c) const
        ^
In module 'stl':
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1170:2: error: 'std::boyer_moore_horspool_searcher::_M_bad_char_shift' from module 'stl.functional' is not present in definition of 'boyer_moore_horspool_searcher<_RAIter, _Hash, _BinaryPredicate>' in module 'stl.functional'
        _M_bad_char_shift(_Tp __c) const
        ^
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1170:2: note: declaration of '_M_bad_char_shift' does not match
        _M_bad_char_shift(_Tp __c) const
        ^
In module 'stl':
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1122:43: error: 'std::boyer_moore_searcher::_M_good_suffix' from module 'stl.functional' is not present in definition of 'boyer_moore_searcher<_RAIter, _Hash, _BinaryPredicate>' in module 'stl.functional'
      _GLIBCXX_STD_C::vector<__diff_type> _M_good_suffix;
                                          ^
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1122:43: note: declaration of '_M_good_suffix' does not match
      _GLIBCXX_STD_C::vector<__diff_type> _M_good_suffix;
                                          ^
In module 'stl':
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1090:7: error: 'std::boyer_moore_searcher::_M_is_prefix' from module 'stl.functional' is not present in definition of 'boyer_moore_searcher<_RAIter, _Hash, _BinaryPredicate>' in module 'stl.functional'
      _M_is_prefix(_RAIter __word, __diff_type __len,
      ^
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1090:7: note: declaration of '_M_is_prefix' does not match
      _M_is_prefix(_RAIter __word, __diff_type __len,
      ^
In module 'stl':
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1102:7: error: 'std::boyer_moore_searcher::_M_suffix_length' from module 'stl.functional' is not present in definition of 'boyer_moore_searcher<_RAIter, _Hash, _BinaryPredicate>' in module 'stl.functional'
      _M_suffix_length(_RAIter __word, __diff_type __len,
      ^
/cvmfs/cms-ib.cern.ch/nweek-02555/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/functional:1102:7: note: declaration of '_M_suffix_length' does not match
      _M_suffix_length(_RAIter __word, __diff_type __len,
      ^
Error in <ACLiC>: Dictionary generation failed!

---> test test_root_PyMVA had ERRORS
```

**Comment by yamaguchi1024** [comment]
Debugging, but I would like to check if DataFormats/Common pcm were actually generated in its library.

**Comment by yamaguchi1024** [comment]
`error: 'std::boyer_moore_searcher::_M_bad_char_shift' from module 'stl.functional' is not present in definition of 'boyer_moore_searcher<_RAIter, _Hash, _BinaryPredicate>' in module 'stl.functional'`
It looks C++ ABI mismatch. The reference is pointing to `lib/gcc/x86_64-unknown-linux-gnu/7.3.1`, but is ROOT compiled with ABI compatible compiler?

**Comment by smuzaffar** [comment]
closing it as this is not needed due to #4599

**Pull request closed without merging**
