### PR TITLE
Update GBL to V03-01-00

### PR DESCRIPTION
**Pull request by henriettepetersen**
* Update of GBL software version for tracker alignment calibration
* Main implementation in the new GBL version is THICK scatterers at GblPoints
* Works with new MP version in the PR here: https://github.com/cms-sw/cmsdist/pull/8953
* See presentation [here](https://indico.cern.ch/event/1363492/#27-new-mp2-solution-method-par) at TrkAl meeting (09.01.2024) by C. Kleinwort with overview of method and performance summary from test campaign.

### CODE REVIEW

**Comment by perrotta** [comment]
please test workflow 1001.0,1001.2,1001.3,1001.5

**Comment by mmusich** [comment]
> -1

I suppose we need to bump up eigen as well?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by iarspider** [comment]
@henriettepetersen please resolve conflicts

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
please test

**Comment by mmusich** [comment]
@iarspider do you have any insight on the cause of the errors above?

**Comment by mmusich** [comment]
this is supposedly superseded by https://github.com/cms-sw/cmsdist/pull/9053 (hopefully that one won't have compilation errors).

**Comment by smuzaffar** [comment]
closing it as a new version of gbl has already been integrated via https://github.com/cms-sw/cmsdist/pull/9053

**Pull request closed without merging**
