### PR TITLE
Update geant4 to version 11.2.1

### PR DESCRIPTION
**Pull request by iarspider**
Closes https://github.com/cms-externals/geant4/issues/79

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_14_1_GEANT4_X

**Comment by iarspider** [comment]
please test for CMSSW_14_1_G4VECGEOM_X

**Comment by smuzaffar** [comment]
looks good to go in geant4 IBs

**Pull request merged**
