### PR TITLE
Update dqmgui.spec

### PR DESCRIPTION
**Pull request by ErnestaP**
Changed from Rovere's personal repo to cms-DQM

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to 6f9d2e40eedfaeb10626ea7771ecf263b49e788d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7128/test_6f9d2e4-20210713-115002.log" target="_blank">here</a>.

**Comment by ErnestaP** [comment]
Sorry, there was a small mistake!

**Comment by muhammadimranfarooqi** [comment]
+1 to 4949b12c4f15a70f016ec64f5dac1ae67ce6cf76 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7128/test_4949b12-20210713-134003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to b93241bde217bec136ddba6928025852a6acc5f0 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7128/test_b93241b-20210713-141003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@ErnestaP 
Do you want this to be deployed in cmsweb-testbed?

**Comment by muhammadimranfarooqi** [comment]
@ErnestaP 
Pinging again

**Comment by ErnestaP** [comment]
Hi @muhammadimranfarooqi , sorry for the late reply. Yes, we would like to have deployed in prod and dev, because this PR changes git repo where dqmgui_prod is taken from (from personal Rovere's to cms-DQM) :)

**Comment by muhammadimranfarooqi** [comment]
@ErnestaP 

We have tickets for every month for release requests. https://gitlab.cern.ch/cms-http-group/doc/-/issues/269
Whenever you need to add something in cmsweb, please request on the relevant ticket.

**Comment by muhammadimranfarooqi** [comment]
@ErnestaP 

This PR has been deployed in testbed. Please test and provide validation at https://gitlab.cern.ch/cms-http-group/doc/-/issues/270 Thanks

**Pull request merged**
