### PR TITLE
CRAB Client 3.3.1802

### PR DESCRIPTION
**Pull request by todor-ivanov**

### CODE REVIEW

**Comment by h4d4** [comment]
to 8c4e385bd616c6a9489bd2bf729ead5eecb9089e on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3716/test_8c4e385-20180206-122607.log" target="_blank">here</a>.

**Comment by todor-ivanov** [comment]
test

**Comment by todor-ivanov** [comment]
help

**Comment by h4d4** [comment]
+1 to 8c4e385bd616c6a9489bd2bf729ead5eecb9089e on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3716/test_8c4e385-20180206-131506.log" target="_blank">here</a>.

**Comment by todor-ivanov** [comment]
merge

**Pull request merged**
