### PR TITLE
Advance fastjet-contrib to version cms/v1.020.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-externals/fastjet-contrib/commit/d53aaa4eae502d51154a362d262af2155ed17f38

### CODE REVIEW

**Comment by davidlt** [comment]
I guess this broke CMSSW.
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc493/CMSSW_7_6_X_2015-10-13-1100/RecoJets/JetProducers

```
RecoJets/JetProducers/plugins/NjettinessAdder.cc:30:3: error: 'GeometricMeasure' is not a member of 'fastjet::contrib'
```

@davidlange6 @slava77 @smuzaffar

**Comment by slava77** [comment]
@rappocio

**Comment by slava77** [comment]
@rappoccio

**Comment by rappoccio** [comment]
Ugh. They changed the interface. Here is the accompanying PR for CMSSW : 

https://github.com/cms-sw/cmssw/pull/11791

**Pull request merged**
