### PR TITLE
New version of DCAFPilot package along with deployment of etc area and new dependency settings

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 6f352e3fb1728d5bcd097ecfb73916a26da06365 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
-1 to 7c4d9ab34e7053cb32ec6478a521de41921c4221 on slc6_amd64_gcc481.

**Comment by vkuznet** [comment]
Diego, can I see build log for this failutre, in my private build area everything build correctly.

**Comment by vkuznet** [comment]
Hi there, once again, could someone post build log failure or its location that I can look. My local builds are fine.

**Comment by geneguvo** [comment]
Hi Valentin,

I think you have submitted an update for the PR after it has been already merged and "closed" (see Rida's push that says "Close #1400". That's why I believe it failed. The "Close #NNN" does not work when using these branches.

I'll therefore close the PR. Please submit a new PR on top of whatever is there on HEAD of this branch.

Cheers,
Diego.

**Pull request closed without merging**
