### PR TITLE
[12.1.X] Update of mkFit release and configuration (backport of PRs #7427 + #7443)

### PR DESCRIPTION
**Pull request by mmasciov**
#### PR description

Backport to 12_1_X of PRs #7427 + #7443 (cms-data/RecoTracker-MkFit#7).
This is related to backport of PR cms-sw/cmssw#35974, realized in PR cms-sw/cmssw#36075.

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/36075#issuecomment-965630371

**Comment by qliphy** [comment]
please test with cms-sw/cmssw#36075

**Comment by qliphy** [comment]
conflict resolved.    Re-test to make sure everything works well.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
