### PR TITLE
[12.4.X] Updated files for the v1_1_0 menu for Run 3 (and minor fix for v1_0_0)

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #7925
Fixes https://github.com/cms-data/L1Trigger-L1TGlobal/issues/12

### CODE REVIEW

**Comment by elfontan** [comment]
Thank you so much!

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/38331

**Comment by perrotta** [comment]
+1
- See https://github.com/cms-sw/cmssw/pull/38331#issuecomment-1154331497 for the failing Unit Tests

**Comment by perrotta** [comment]
merge

**Pull request merged**
