### PR TITLE
add yoda and cython

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
Needed for rivet2

**Comment by ghost** [comment]
This doesn't build for me:

/build/degano/ext/CMSSW_7_0_X/20140128_1129/a/tmp/rpm-tmp.WnY4vA: line 40: configure: command not found
error: Bad exit status from /build/degano/ext/CMSSW_7_0_X/20140128_1129/a/tmp/rpm-tmp.WnY4vA (%prep)

**Comment by mkirsano** [comment]
Sorry, I fixed the error "configure: command not found"

**Comment by ktf** [comment]
Closing this. Fixed by #374.

**Pull request closed without merging**
