### PR TITLE
Revert "Remove root_numpy and root_pandas on cmsdist master"

### PR DESCRIPTION
**Pull request by mrodozov**
Reverts cms-sw/cmsdist#6896

### CODE REVIEW

**Comment by mrodozov** [comment]
https://github.com/cms-sw/cmsdist/pull/6896#issuecomment-841869910

**Comment by mrodozov** [comment]
please test

**Comment by jfernan2** [comment]
Thanks @mrodozov !
Do you know of any alternative to root_numpy that we could use instead so that root_numpy may be dropped?

**Comment by davidlange6** [comment]
uproot? (Dqm is already using it iirc)

**Comment by jfernan2** [comment]
Thanks @davidlange6 
uproot was not even necessary
https://github.com/cms-sw/cmssw/pull/33751

**Comment by mrodozov** [comment]
well that was quick :)

**Pull request merged**
