### PR TITLE
WMAgent release candidate 2.2.4rc8

### PR DESCRIPTION
**Pull request by amaltaro**

### CODE REVIEW

**Comment by arooshap** [comment]
+1 to ea1729d360fab90d52fc83625583f379c2bdeaf2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8726/test_ea1729d-20230927-042503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Comment by amaltaro** [comment]
merge

**Comment by amaltaro** [comment]
@arooshap @smuzaffar @muhammadimranfarooqi  for some reason I seem no longer able to trigger the bot build to merge this pull request. Could you please merge it for me? Thanks

**Pull request merged**
