### PR TITLE
bump up sherpa to 2.2.10

### PR DESCRIPTION
**Pull request by SiewYan**
update sherpa to 2.2.10.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by mrodozov** [comment]
wait there are 4 differences in comparison

**Comment by silviodonato** [comment]
+1

**Comment by SiewYan** [comment]
@mrodozov , The differences are expected for ttbar process for the new sherpa version made some enhancement on ttbar related process generation, highlighted here https://gitlab.com/sherpa-team/sherpa/-/merge_requests/296 @GurpreetSinghChahal.

**Pull request merged**
