### PR TITLE
added build options which can be controlled via cmsBuild

### PR DESCRIPTION
**Pull request by smuzaffar**
This change allows to override the build options for various tools. Default build options are not changed and this should this should work with existing pkgtools `V00-34-XX`.

In future we will make use of these build options to enable/disable lto, ue of vecgeom etc via `cmsBuild` command-line options instead of have separate `cmsdist` branch

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
