### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@fabiocos and @Dr15Jones I would suggest to go ahead and merge this so that we have an IB to explorer the unit tests issues

**Comment by Dr15Jones** [comment]
@smuzaffar I assume the merge would only effect CMSSW_11_0_ROOT6_X? If so, then that is fine with me.

**Comment by smuzaffar** [comment]
yes that is correct @Dr15Jones

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
