### PR TITLE
[10_2_X] MSAFETY set to 1e-4

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@qliphy @agrohsje there are two comparison differences
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2020-11-30-1100+0b90d7/40197/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0/

**Comment by agrohsje** [comment]
The plots are fully compatible:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2020-11-30-1100+0b90d7/40197/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0/all_OldVSNew_TTbar13TeVPU2017wf10224p0c_edmErrorSummaryEntrys_logErrorHarvester__RECO_objAT_size.png
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2020-11-30-1100+0b90d7/40197/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0/all_OldVSNew_TTbar13TeVPU2017wf10224p0c_edmErrorSummaryEntrys_logErrorHarvester__RECO_obj_count.png
Do you have something else in mind or do I look at the wrong ones?

**Comment by mrodozov** [comment]
I have nothing in mind, I have no idea what this difference is, so I'm just pointing it to someone that does. I mean someone had to read it and make sense of it. So it's ok from your perspective ?

**Comment by agrohsje** [comment]
They are both fully compatible within statistical precision. Don't ask me why it gets reported. The same two get reported in a recent pr I made that had definitely no impact at all beyond statistics. So nothing to worry about but thanks for the heads-up.

**Comment by mrodozov** [comment]
+externals

**Comment by makortel** [comment]
> there are two comparison differences
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2020-11-30-1100+0b90d7/40197/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0/

Those are from `logErrorHarvester` and are (likely) caused by MessageLogger messages being emitted in different order. These are safe to ignore (almost?) always.

> They are both fully compatible within statistical precision.

PR tests aim to be fully reproducible (as long as nothing in GEN or SIM changes).

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
see https://github.com/cms-externals/pythia8/pull/26

**Pull request merged**
