### PR TITLE
New dasgoclient version

### PR DESCRIPTION
**Pull request by vkuznet**
This version removes Phedex data service from DAS queries.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by vkuznet** [comment]
@smuzaffar , I'm not sure that this change is caused the failure in some of the tests. According to log https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-815783/10334/addOnTests/logs/cmsDriver-fastsim_cmsDriver.py_TTbar_8TeV_TuneCUETP8M1_cfi__--conditions_auto:run1_mc_--fast__-n_100_--eventcontent_AODSIM,DQM_--relval_100000,1000_-s_GEN,SIM,RECOBEFMI.log
there is a traceback from some of the CMSSW module(s) and I don't see anything related to dasgoclient changes.

**Comment by makortel** [comment]
@vkuznet Seems to be a random crash in that particular test (https://github.com/cms-sw/cmssw/issues/24051).

**Comment by smuzaffar** [comment]
for now, we need to merge this only for DEVEL IBs to test new dasgoclient. I will backport it for normal IBs once we have successfully tested it for a week in DEVEL

**Comment by smuzaffar** [comment]
lets merge it for devel IB. If every thing goes fine for DEVEL IBs then on Wednesday 4th NOV we can backport it to normal IBs.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
