### PR TITLE
madgraph5amcatnlo: use external collier and ninja instead of downloading them

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- relval = 539.0
- relval_threading = 539.0
- enable = threading
- pull_requests = cms-sw/cmssw#43261

**Comment by smuzaffar** [comment]
please test

lets tests with workflows which actually use madgraph

**Comment by smuzaffar** [comment]
> please ignore tests-rejected with external-failure

@iarspider,  we should not ignore such errors . Although it is external failure but we should try to understand , fix and rerun the tests

**Comment by iarspider** [comment]
please test

all failures are "socket timeout", eos hiccup?

**Comment by smuzaffar** [comment]
please test

looks like eos is bit stable now ( local tests were able to read the data from root://eoscms.cern.ch//eos/cms/store/user/cmsbuild)

**Comment by iarspider** [comment]
> You potentially added 1412 lines to the logs

@smuzaffar  can you remind me where to find these added lines? Or these lines are due to extra tests (threading)?

**Comment by smuzaffar** [comment]
looks for `validateJR/logRootQA-events.log` log file in the comparison with baseline directory. Search for `You added ...` message in this log

**Comment by iarspider** [comment]
The added lines doesn't seem to be caused by this PR: see https://github.com/cms-sw/cmsdist/pull/8812

> You potentially added 1250 lines to the logs

**Comment by iarspider** [comment]
assign generators

**Comment by Dominic-Stafford** [comment]
Hi, thanks for doing this, in the gen group we've also been experiencing problems of not being able access ninja and collier due to hepforge downtime, so having these built in CMSSW would be very helpful. Just to comment here, the madgraph version being updated here is only used internally by Herwig in the "Matchbox" mode, however once this PR is accepted we were thinking of also using these libraries in the genproductions repository used for madgraph gridpack production.

Related to this, I'm not sure if any of the tests you've run here will actually test the version of madgraph you've built as I think they all use gridpacks- we don't yet have any madgraph+herwig matchbox tests as this isn't yet ready for central production (though we're working on it). However we can also do some tests on the dev area.

**Comment by makortel** [comment]
> Related to this, I'm not sure if any of the tests you've run here will actually test the version of madgraph you've built as I think they all use gridpacks- we don't yet have any madgraph+herwig matchbox tests as this isn't yet ready for central production (though we're working on it).

Having tests, even if the functionality is not yet ready for production, in CMSSW would be very useful in general.

**Comment by smuzaffar** [comment]
@iarspider , please fix the [external relocation](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35672/external_checks/relocate/) and [unknown file](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35672/external_checks/unknown/) issues . There are some build log files in the distribution , please delete those

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
thanks for information @Dominic-Stafford , I thought that tests/workflows where we see [a] type messages were trying to use/run madgraph. I agree with @makortel , having some tests in cmssw to make sure that basic functionality of an external is not broken will really help with integration.

[a]
```
************************************************************
*                                                          *
*                      W E L C O M E to                    *
*             M A D G R A P H 5 _ a M C @ N L O            *
*                      M A D E V E N T                     *
*                                                          *
*                 *                       *                *
*                   *        * *        *                  *
*                     * * * * 5 * * * *                    *
*                   *        * *        *                  *
*                 *                       *                *
*                                                          *
*         VERSION 2.6.5                 20xx-xx-xx         *
*                                                          *
*    The MadGraph5_aMC@NLO Development Team - Find us at   *
*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
*                                                          *
*               Type 'help' for in-line help.              *
*                                                          *
************************************************************
```

**Comment by Dominic-Stafford** [comment]
Hi, I've made a PR to add a relval testing the herwig-madgraph Matchbox here: https://github.com/cms-sw/cmssw/pull/43261, and also tested this in the user test area, so it seems this works well and the new collier runs fine.

**Comment by Dominic-Stafford** [comment]
> thanks for information @Dominic-Stafford , I thought that tests/workflows where we see [a] type messages were trying to use/run madgraph. I agree with @makortel , having some tests in cmssw to make sure that basic functionality of an external is not broken will really help with integration.
> 
> [a]
> 
> ```
> ************************************************************
> *                                                          *
> *                      W E L C O M E to                    *
> *             M A D G R A P H 5 _ a M C @ N L O            *
> *                      M A D E V E N T                     *
> *                                                          *
> *                 *                       *                *
> *                   *        * *        *                  *
> *                     * * * * 5 * * * *                    *
> *                   *        * *        *                  *
> *                 *                       *                *
> *                                                          *
> *         VERSION 2.6.5                 20xx-xx-xx         *
> *                                                          *
> *    The MadGraph5_aMC@NLO Development Team - Find us at   *
> *    https://server06.fynu.ucl.ac.be/projects/madgraph     *
> *                                                          *
> *               Type 'help' for in-line help.              *
> *                                                          *
> ************************************************************
> ```

Sorry, I missed this response. Madgraph is being run in these cases, but the entire madgraph version is bundled in the gridpack used by the externalLHEProducer, rather than the vaersion in CMSSW. One can see this as MG 2.6.5 is called here, while this version of CMSSW has MG 2.7.3

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
Relval [539.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35778/runTheMatrix-results/539.0_DY_TuneCH3_13TeV_herwig_madgraph_matchbox/) looks good

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 can you please review and sign this?

**Comment by menglu21** [comment]
looks good.

**Comment by menglu21** [comment]
+1

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by Dominic-Stafford** [comment]
Hi, from the generators side we'd like to have this PR backported to CMSSW_10_6 and 12_4 so we could link against the collier and ninja libraries when making external gridpacks for use in central production. Would you be able to easily do this, please? If not I can prepare the PRs

**Comment by Dominic-Stafford** [comment]
> -1
> 
> **Failed Tests**: RelVals RelVals-THREADING **Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35861/summary.html **COMMIT**: [1e9c9be](https://github.com/cms-sw/cmsdist/commit/1e9c9be99d72940440b53c00df6a7442155b4458) **CMSSW**: CMSSW_14_0_X_2023-11-14-2300/el8_ppc64le_gcc12 **Additional Tests**: THREADING **User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/8809/35861/install.sh` to create a dev area with all the needed externals and cmssw changes.
> ## RelVals
> 
>     * [539.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35861/runTheMatrix-results/539.0_DY_TuneCH3_13TeV_herwig_madgraph_matchbox)`539.0_DY_TuneCH3_13TeV_herwig_madgraph_matchbox/step1_DY_TuneCH3_13TeV_herwig_madgraph_matchbox.log`
> 
>     * [24896.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35861/runTheMatrix-results/24896.0_CloseByPGun_CE_E_Front_120um+2026D98)`24896.0_CloseByPGun_CE_E_Front_120um+2026D98/step2_CloseByPGun_CE_E_Front_120um+2026D98.log`
> 
>     * [24900.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35861/runTheMatrix-results/24900.0_CloseByPGun_CE_H_Coarse_Scint+2026D98)`24900.0_CloseByPGun_CE_H_Coarse_Scint+2026D98/step2_CloseByPGun_CE_H_Coarse_Scint+2026D98.log`
> 
> 
> Expand to see more relval errors ...
> ## RelVals-THREADING
> 
>     * [539.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35861/runTheMatrixTHREADING-results/539.0_DY_TuneCH3_13TeV_herwig_madgraph_matchbox)`539.0_DY_TuneCH3_13TeV_herwig_madgraph_matchbox/step1_DY_TuneCH3_13TeV_herwig_madgraph_matchbox.log`
> 
>     * [24834.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35861/runTheMatrixTHREADING-results/24834.0_TTbar_14TeV+2026D98)`24834.0_TTbar_14TeV+2026D98/step2_TTbar_14TeV+2026D98.log`
> 
>     * [23234.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65e2cf/35861/runTheMatrixTHREADING-results/23234.0_TTbar_14TeV+2026D94)`23234.0_TTbar_14TeV+2026D94/step2_TTbar_14TeV+2026D94.log`
> 
> 
> Expand to see more relval errors ...

Also, do we need to worry about these failing relvals? It seems to segfault part way through running the madgraph integration in 539, which is a bit worrying. I tried checking out the dev area, but python wouldn't run

**Pull request merged**
