### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
The `RooAbsPdf::paramOn` overload used in CMSSW code was deprecated even in ROOT 6.06, and got removed in ROOT master: https://github.com/root-project/root/pull/12608 .

**Comment by smuzaffar** [comment]
@iarspider , please open an issue in cms-sw/cmssw

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/41322
- skip_test = static

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar why did you disable "static" test?

**Comment by smuzaffar** [comment]
@iarspider , static tests are enough to run via cmssw PR so in this case https://github.com/cms-sw/cmssw/pull/41322 static tests will be good. Tests for cmssw+cmsdist PRs (specially for root PRs whcih checks out too many packages) can add extra 2/3 hours for PR tests :-)

**Comment by smuzaffar** [comment]
please test for CMSSW_13_1_ROOT6_X

**Comment by iarspider** [comment]
thanks for the explanation!

**Pull request merged**
