### PR TITLE
[Geant4] Update vecgeom and clhep version, get geant4 from it's github

### PR DESCRIPTION
**Pull request by mrodozov**
please test
following https://github.com/cms-externals/geant4/issues

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@civanch now it needs changes for clhep in cmssw which can't be merged unless we change clhep to the new version we'll be using in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/master/clhep.spec 
if geant4 10.6.2 will work with clhep 2.4.4.0 then that will be fine

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/32420

**Comment by civanch** [comment]
@mrodozov , I expect, that updated CLHEP and VecGeom are compatible with 10.6 but will consult experts.

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6486

**Comment by civanch** [comment]
@mrodozov , in the last CLHEP a revision of constants like electric charge was made. This means, that the last digits of some constants will be different, so regression may be broken.

**Comment by mrodozov** [comment]
@civanch clhep is compatible with g4 10.6.2 if this can be integrated https://github.com/cms-sw/cmsdist/pull/6492 
then we don't have to have special branch on cmssw. if all is fine the first release with it will be available this Friday

**Pull request merged**
