### PR TITLE
Remove vecgeom from toolfiles

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
abort
lets remove it as in https://github.com/cms-sw/cmsdist/compare/REL/CMSSW_11_1_0_pre4_GEANT4/slc7_amd64_gcc820...0e77e8eb44f6844e106d9f3db342f905b9e82464

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@smuzaffar we need this to remove any reference to vecgeom, any objection I merge it and build a geant IB ?

**Comment by smuzaffar** [comment]
@mrodozov , changes in `vectorization/cmsdist_packages.py ` are not necessary. Please revert those.

**Pull request merged**
