### PR TITLE
Add `ROOT_INCLUDE_PATH` to `alpaka.xml` [12.5.x]

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #8056

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@perrotta @rappoccio , this is bug fix and safe to be included in 12.5.X

**Comment by perrotta** [comment]
+1

**Pull request merged**
