### PR TITLE
[ROOT modules] get latest from master

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by davidlange6** [comment]
hi @mrodozov - as to get the results of a different PR in the IBs, lets not merge this today -

**Comment by mrodozov** [comment]
@davidlange6 sure, for this IB I'll probably first ask if the faling tests are acceptable

**Comment by davidlange6** [comment]
There are failing tests in the IB - I didn’t check if these failures are “new”? (In which case probably we should be careful…)

On Mar 18, 2020, at 11:03 AM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6> sure, for this IB I'll probably first ask if the faling tests are acceptable

**Comment by davidlange6** [comment]
Now I checked - there are some new things.. but you have the same new things without modules too. Definitely needs some understanding..

On Mar 18, 2020, at 11:10 AM, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


There are failing tests in the IB - I didn’t check if these failures are “new”? (In which case probably we should be careful…)

On Mar 18, 2020, at 11:03 AM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6> sure, for this IB I'll probably first ask if the faling tests are acceptable

**Comment by davidlange6** [comment]
@vgvassilev suggests that the compilation errors will go away with a full build. [as this is being due to some lingering root issue]

@mrodozov

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@davidlange6 @vgvassilev 
same error as in the last IB 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc820/CMSSW_11_1_CXXMODULE_X_2020-03-19-2300/CondFormats/HLTObjects

**Comment by davidlange6** [comment]
good.  Lets integrate this

On Mar 20, 2020, at 4:29 PM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6> @vgvassilev<https://github.com/vgvassilev>
same error as in the last IB
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc820/CMSSW_11_1_CXXMODULE_X_2020-03-19-2300/CondFormats/HLTObjects

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Comment by smuzaffar** [comment]
@davidlange6 , @vgvassilev , do you understand the runtime error [a] which we get near the end of job?

[a]
```
Fatal in &lt;TClass::SetUnloaded&gt;: The TClass for vector&lt;Trajectory&gt; is being unloaded when in state 3
```

**Comment by davidlange6** [comment]
We know the error means that this dictionary did not get loaded for some reason, but I don’t think @vgvassilev has debugged it yet (its not new)

On Mar 23, 2020, at 3:07 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6> , @vgvassilev<https://github.com/vgvassilev> , do you understand the runtime error [a] which we get near the end of job?

[a]

Fatal in &lt;TClass::SetUnloaded&gt;: The TClass for vector&lt;Trajectory&gt; is being unloaded when in state 3

**Pull request merged**
