### PR TITLE
Update Geant4 candidate version for the ROOT6 branch

### PR DESCRIPTION
**Pull request by mrodozov**
Testing changes requested here https://github.com/cms-sw/cmsdist/issues/3594

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by civanch** [comment]
@mrodozov , thanks. The difference with the baseline is expected.

**Comment by davidlange6** [comment]
hi Vladimir
Could you post a few plots from the comparisons that show this update is not crazy?

**Comment by civanch** [comment]
@davidlange6 , after merge to the ROOT6 branch I will make TB2006 set of plots, Sunanda will do his analysis + other plots may be done. We did this with several Geant4 pre-releases.

**Comment by davidlange6** [comment]
Right - but you have plots created for you now:)

**Comment by civanch** [comment]
I have tested it standalone not within CMSSW, results are not changed since previous version, which is used in ROOT6.

**Comment by civanch** [comment]
To say more: physics was not changed between previous reference version of 3 weeks ago and today except few technical fixes which does not affect results, geometry and and other fixes were added, histories should not be the same, at least, because data files for nuclear levels were updated.

**Comment by civanch** [comment]
@davidlange6 , to say more: we need merge this to ROOT6 in order to be sure that the new release of Geant4 is acceptable for CMSSW. Only few days left when we may feedback a problem to Geant4 if any.

**Comment by civanch** [comment]
If results will be with a problem we always may role back previous version to this branch.

**Comment by davidlange6** [comment]
i'm only asking you to look at a few of the comparison plots created for you by cmsbot.....

**Comment by civanch** [comment]
they are not available for some reason...

**Comment by davidlange6** [comment]
looks like the sdt server is down..

**Comment by davidlange6** [comment]
Here is the correct link:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_0_X_2017-11-22-2300+3596/23898/

**Comment by civanch** [comment]
tracking__trackalltpeffic_cutsrecohp_trackingparticlerecoasssociation_striplayerswith1dmeas_vs_eta 1
There are many differences in tracking but recHits plots are reasonable, for example 
tracking__trackalltpeffic_cutsrecohp_trackingparticlerecoasssociation_hits_eta 1

**Comment by civanch** [comment]
EB plot for hits: 
ecalhitsv__ecalsimhitsvalidation_eb 20crystal 20energy 20spectrum 202 1

**Comment by civanch** [comment]
@davidlange6 , some plots are added. Can this PR be merged?

**Comment by davidlange6** [comment]
merge

**Pull request merged**
