### PR TITLE
Advance clhep to CMS version 2.3.1.1.

### PR DESCRIPTION
**Pull request by ghost**
Remove unneeded patches.

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
@civanch If you read the above log you will notice that for some reason Geant's cmake thinks that CLHEP is < 3.1 (which is false, ofc). Do you happen to have any idea of what might be the cause?

**Comment by davidlt** [comment]
If you look at `geant4/cmake/Modules/FindCLHEP.cmake`

```
#----------------------------------------------------------------------------
# Extract the CLHEP version from defs.h
# Versions COMPATIBLE if RequestedVersion > FoundVersion
# Also check if versions exact

if(CLHEP_INCLUDE_DIR)
    set(CLHEP_VERSION 0)
    file(READ "${CLHEP_INCLUDE_DIR}/CLHEP/Units/defs.h" _CLHEP_DEFS_CONTENTS)
    string(REGEX REPLACE ".*#define PACKAGE_VERSION \"([0-9.]+).*" "\\1"
        CLHEP_VERSION "${_CLHEP_DEFS_CONTENTS}")

    if(NOT CLHEP_FIND_QUIETLY)
        message(STATUS "Found CLHEP Version ${CLHEP_VERSION}")
    endif()

    if(CLHEP_FIND_VERSION)
        set(CLHEP_VERSIONING_TESTS CLHEP_VERSION_COMPATIBLE)

        if("${CLHEP_VERSION}" VERSION_LESS "${CLHEP_FIND_VERSION}")
            set(CLHEP_VERSION_COMPATIBLE FALSE)
        else()
            set(CLHEP_VERSION_COMPATIBLE TRUE)

            if(CLHEP_FIND_VERSION_EXACT)
                if("${CLHEP_VERSION}" VERSION_EQUAL "${CLHEP_FIND_VERSION}")
                    set(CLHEP_VERSION_EXACT TRUE)
                endif()
                    list(APPEND CLHEP_VERSIONING_TESTS CLHEP_VERSION_EXACT)
            endif()
        endif()
    endif()
endif()
```

And the content of `slc6_amd64_gcc493/external/clhep/2.3.1.1/include/CLHEP/Units/defs.h`

```
      1 /* Units/defs.h  Generated by cmake.  */
      2
      3 #ifndef UNITS_DEFS_H
      4 #define UNITS_DEFS_H
      5
      6 /* Define to the address where bug reports for this package should be sent. */
      7 #ifndef CLHEP_UNITS_BUGREPORT
      8 #define CLHEP_UNITS_BUGREPORT "http://proj-clhep.web.cern.ch/proj-clhep/"
      9 #endif
     10
     11 /* Define to the full name of this package. */
     12 #ifndef CLHEP_UNITS_NAME
     13 #define CLHEP_UNITS_NAME "CLHEP Units"
     14 #endif
     15
     16 /* Define to the full name and version of this package. */
     17 #ifndef CLHEP_UNITS_STRING
     18 #define CLHEP_UNITS_STRING "CLHEP Units 2.3.1.1"
     19 #endif
     20
     21 /* Define to the version of this package. */
     22 #ifndef CLHEP_UNITS_VERSION
     23 #define CLHEP_UNITS_VERSION "2.3.1.1"
     24 #endif
     25
     26 #endif  // UNITS_DEFS_H
```

Then difference between CLHEP versions:

```
% git diff cms/v2.2.0.4..cms/v2.3.1.1 -- Units/Units/cmake-defs.h.in
diff --git a/Units/Units/cmake-defs.h.in b/Units/Units/cmake-defs.h.in
index 7731b97..106ee7c 100644
--- a/Units/Units/cmake-defs.h.in
+++ b/Units/Units/cmake-defs.h.in
@@ -3,39 +3,24 @@
 #ifndef @UPACKAGE@_DEFS_H
 #define @UPACKAGE@_DEFS_H

-/* Name of package */
-#ifndef PACKAGE
-#define PACKAGE "@PACKAGE@"
-#endif
-
 /* Define to the address where bug reports for this package should be sent. */
-#ifndef PACKAGE_BUGREPORT
-#define PACKAGE_BUGREPORT "http://savannah.cern.ch/projects/clhep/"
+#ifndef CLHEP_@UPACKAGE@_BUGREPORT
+#define CLHEP_@UPACKAGE@_BUGREPORT "http://proj-clhep.web.cern.ch/proj-clhep/"
 #endif

 /* Define to the full name of this package. */
-#ifndef PACKAGE_NAME
-#define PACKAGE_NAME "@PROJECT_NAME@ @PACKAGE@"
+#ifndef CLHEP_@UPACKAGE@_NAME
+#define CLHEP_@UPACKAGE@_NAME "@PROJECT_NAME@ @PACKAGE@"
 #endif

 /* Define to the full name and version of this package. */
-#ifndef PACKAGE_STRING
-#define PACKAGE_STRING "@PROJECT_NAME@ @PACKAGE@ @VERSION@"
-#endif
-
-/* Define to the one symbol short name of this package. */
-#ifndef PACKAGE_TARNAME
-#define PACKAGE_TARNAME "@PACKAGE@"
+#ifndef CLHEP_@UPACKAGE@_STRING
+#define CLHEP_@UPACKAGE@_STRING "@PROJECT_NAME@ @PACKAGE@ @VERSION@"
 #endif

 /* Define to the version of this package. */
-#ifndef PACKAGE_VERSION
-#define PACKAGE_VERSION "@VERSION@"
-#endif
-
-/* Version number of package */
-#ifndef VERSION
-#define VERSION "@VERSION@"
+#ifndef CLHEP_@UPACKAGE@_VERSION
+#define CLHEP_@UPACKAGE@_VERSION "@VERSION@"
 #endif

 #endif  // @UPACKAGE@_DEFS_H
```

Looks like GEANT4 FindCLHEP.cmake is broken and will not detect newer CLHEP versions.

**Comment by civanch** [comment]
@degano , I have a discussion with Geant4 expert and he suggested integrate new CLHEP together with new Geant4. His argument is following: Geant4 was released and verified together with a specific version of CLHEP, if CLHEP is older or newer Geant4 may compile and run but without a grantee. Of course, it is possible try to patch cmake files but may be optimal not to do this and close this PR for today. In two weeks time corresponding Genat4 version will be prepared. When it will be ready we can make a common PR clhep+geant4 in cmsdist.

**Comment by ghost** [comment]
@civanch Okay, will wait for new Geant4 then.

**Pull request closed without merging**
