### PR TITLE
update mkfit to V3.1.0

### PR DESCRIPTION
**Pull request by slava77**
related CMSSW and cms-data PR are coming.

https://github.com/trackreco/mkFit/releases/tag/V3.1.0-0%2Bpr332

@mmasciov @makortel

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 11634.7

I think that the API is backward compatible. So, I wanted to test to see if synchronized merge is required.

**Comment by makortel** [comment]
I think (but haven't tested) that
```diff
-cp -a Geoms/*.so %{i}/Geoms
```
line could be removed, and the `mkdir` line be changed accordingly
```diff
-mkdir %{i}/include %{i}/include/mkFit %{i}/Geoms
+mkdir %{i}/include %{i}/include/mkFit
```

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
abort test

**Comment by slava77** [comment]
@cmsbuild please test workflow 11634.7

**Comment by slava77** [comment]
> I think that the API is backward compatible. So, I wanted to test to see if synchronized merge is required.

Apparently I forgot about one runtime feature change that requires a change in cms-sw/cmssw.

**Comment by smuzaffar** [comment]
please test

**Comment by qliphy** [comment]
tested in https://github.com/cms-sw/cmssw/pull/34395

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
