### PR TITLE
upgrades matplotlib to 1.5.0

### PR DESCRIPTION
**Pull request by iahmad-khan**
https://github.com/cms-sw/cmsdist/issues/2387

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
please test

**Comment by davidlt** [comment]
According to their webpage the latest stable version is 1.5.1, so they did you pick 1.5.0?

**Comment by iahmad-khan** [comment]
@davidlt because i followed the spec file , where they use source forge as the source and there 1.5.0 was the latest one. http://sourceforge.net/projects/matplotlib/files/matplotlib/
where in the title it was written that 1.5.0 is the latest stable. although 1.5.1 was also there in the list. And according to the version format i also kind of thought that 1.5.0 may be the major version and stable.

**Comment by davidlt** [comment]
Actually they have 1.5.2 now: https://github.com/matplotlib/matplotlib/releases/tag/v1.5.2

**Comment by ghost** [comment]
@iahmad-khan can you test 1.5.2? Also first verify locally that it builds so we don't waste too much time waiting for the jenkins job to run.

**Comment by iahmad-khan** [comment]
@degano ok , although 1.5.0 was building fine locally , but lets try the latest.

**Comment by iahmad-khan** [comment]
please test

**Comment by smuzaffar** [comment]
@iahmad-khan , we should not revert libpng to 1.2.X

**Comment by smuzaffar** [comment]
please see the build instruction here http://matplotlib.org/users/installing.html see if we need to patch setupext.py  to have it picked our path

**Comment by iahmad-khan** [comment]
@smuzaffar ok , testing it

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
the errors are not related to PR

**Pull request merged**
