### PR TITLE
davix updated to 0.6.0

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by smuzaffar** [comment]
cmsbuild, please test

**Comment by smuzaffar** [comment]
+externals

**Comment by ghost** [comment]
@iahmad-khan You will need to also (or only) make the same PR to 8_1_X/stable

**Comment by davidlange6** [comment]
yes - definitely 81x is the first place for this PR to enter the release

**Comment by davidlt** [comment]
@iahmad-khan have you checked that ROOT detected **our davix** and it was linked correctly?

**Comment by iahmad-khan** [comment]
@davidlt 
`grep davix build/slc6_amd64_gcc530/lcg/root/6.06.00-cms2/include/*.h`

gives:

...............

DAVIX_INCLUDE_DIR=/build/build/iahmad/build/slc6_amd64_gcc530/external/davix/0.6.0/include/davix DAVIX_INCLUDE_DIRS=/build/build/iahmad/build/slc6_amd64_gcc530/external/davix/0.6.0/include/davix DAVIX_LIBRARIES=/build/build/iahmad/build/slc6_amd64_gcc530/external/davix/0.6.0/lib64/libdavix.so DAVIX_LIBRARY=/build/build/iahmad/build/slc6_amd64_gcc530/external/davix/0.6.0/lib64/libdavix.so
..............

**Comment by davidlt** [comment]
Looks like it did find **our davix**. Good. Double check that all paths within ROOT are relocated after RPM was installed (we don't want to have surprises in the future).

**Comment by iahmad-khan** [comment]
Yes , all of them are relocated.

**Comment by smuzaffar** [comment]
changes are merged via stable branch (auto forward port)

**Pull request closed without merging**
