### PR TITLE
Add initial version of Geometry/TestReference

### PR DESCRIPTION
**Pull request by fabiocos**
Proposed update to add a new data package, needed by cms-sw/cmssw#29841

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar a corresponding package in cms-data is needed, are you going to create it and then I fill with an initial commit, or do I directly propose it?

**Comment by mrodozov** [comment]
Once the Geometry/TestReference repo is created on cms-data, the files needs to be added as a  (first) PR.

**Comment by smuzaffar** [comment]
repository https://github.com/cms-data/Geometry-TestReference is now available.

**Comment by fabiocos** [comment]
@smuzaffar @mrodozov thank you, I have made a commit
@silviodonato I will clean this PR now to use that package

**Comment by smuzaffar** [comment]
this pr is not needed, bot will create a proper one once https://github.com/cms-data/Geometry-TestReference/pull/1 is merged

**Pull request closed without merging**
