### PR TITLE
GCC 10 is supported by CUDA 11.x

### PR DESCRIPTION
**Pull request by fwyzard**
Drop the `--allow-unsupported-compiler` compilation flag.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc10

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc10

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = HeterogeneousCore

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc10

**Comment by mrodozov** [comment]
abort
this got stuck in this state where the cmssw PR for TBB went in but the external didn't

**Comment by mrodozov** [comment]
please test for slc7_amd64_gcc10

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
