### PR TITLE
Update dxr to v2.0

### PR DESCRIPTION
**Pull request by gartung**
Dxr now uses elasticsearch.

### CODE REVIEW

**Comment by gartung** [comment]
This requires a newer version of setuptools.

**Comment by davidlt** [comment]
I think, @iahmad-khan added the latest version of setuptools few days ago.

**Comment by gartung** [comment]
This is the error that I think is related to the version of setuptools but I am unsure:

[gartung@gartung CMSSW_8_1_DEVEL_X_2016-10-10-2300]$ dxr
Traceback (most recent call last):
  File "/home/gartung/cmssw-build/CMSSW_8_1_DEVEL_X_2016-10-10-2300/external/slc7_amd64_gcc530/bin/dxr", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 3020, in <module>

  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 614, in _build_master

  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 920, in require

  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 807, in resolve

pkg_resources.DistributionNotFound: dxr==2.0

**Comment by gartung** [comment]
Hmm... a cryptic way of saying one of these dependencies is not met?

click>=3.3,<5.0
configobj>=5.0.6
Flask>=0.9
funcy>=1.0,<2.0
futures>=2.1.1,<4.0
Jinja2>=2.6,<3.0
Mercurial>=3.4
more-itertools>=2.0,<3.0
ordereddict>=1.1,<2.0
parsimonious>=0.6,<0.7
pyelasticsearch>=1.1,<2.0
Pygments>=2.1.3,<3.0
python-hglib>=1.7,<2.0
tabulate>=0.7.5,<0.8
xpidl>=1.0
requests>=1.0,<2.0

**Comment by davidlt** [comment]
We definitely do not have these :)

**Comment by gartung** [comment]
Or urllib3 or python3

**Pull request closed without merging**
