### PR TITLE
Rivet3 gcc900

### PR DESCRIPTION
**Pull request by mrodozov**
Get changes from #5159 to gcc9

### CODE REVIEW

**Comment by mrodozov** [comment]
plase test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@fabiocos I have also herwigpp to build (at least on its own) which was the last package failing from this PR. Hope it would finish before the next IB

**Comment by mrodozov** [comment]
+externals
lets hope it would be sufficient

**Comment by mrodozov** [comment]
@intrepid42 would you take a look please and comment if herwigpp without rivet is acceptable

**Comment by mseidel42** [comment]
Thank you! I did the same for the gcc700 PR because we do not need to run Rivet through Herwig (and wait for whenever they update their Rivet interface) but use the CMSSW RivetInterface.

**Comment by mrodozov** [comment]
@fabiocos I'm merging this for the next IB

**Pull request merged**
