### PR TITLE
Update ROOT in master

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Align master with root626. New commit on 17 of March (https://github.com/root-project/root/commit/5858905487bba8769a8d612d1e3aff20a3acb63d).

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
too many difference in comparison. lets wait for tonights IB and run tests against that

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
Now comparison if clean , no idea why previously there were many reco differences

**Pull request merged**
