### PR TITLE
fix pythia8 interface to lhapdf

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by perrozzi** [comment]
Hi Mikhail, this is the backport of https://github.com/cms-sw/cmsdist/pull/3173 for the lhapdf6 support, right?
If so, aren't you missing the boost part in the configure line?

**Comment by mkirsano** [comment]
Yes, it is the backport of #3173. And this time the boost support is not forgotten

**Comment by perrozzi** [comment]
not forgotten in the sense that `--with-boost=${BOOST_ROOT}` is not needed in 71x?

**Comment by mkirsano** [comment]
You are right

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
backport of #3173

**Comment by davidlange6** [comment]
merge

**Pull request merged**
