### PR TITLE
Upgrade frontier client to v 2.8.19.

### LINKED ISSUE #2230: Please backport frontier_client 2.8.19 and pacparser 1.3.5 to older CMSSW release lines
frontier_client 2.8.18 and pacparser 1.3.5 is in CMSSW_8_1_0_pre[12] and hasn't seen any problems.  Please start backporting it to older release lines that still expect to see active use for quite a while, as was attempted for version 2.8.14 in issue #1952.

### PR DESCRIPTION
**Pull request by ghost**
Fix #2230.

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
please test

**Comment by DrDaveD** [comment]
@degano  It's not clear to me that you've also upgraded to pacparser 1.3.5 with this change -- have you?

**Comment by ghost** [comment]
@DrDaveD you're right, somehow the updates to pacparser slipped while backporting. Thanks for noticing!

**Comment by ghost** [comment]
please test

**Pull request merged**
