### PR TITLE
[94X][Pythia8] Use cms-external/pythia8 repository cms/230 branch to build

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test
lets test it stand alone and after that we need to test it with https://github.com/cms-externals/pythia8/pull/20

**Comment by smuzaffar** [comment]
please test for CMSSW_9_4_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_9_4_X

**Comment by smuzaffar** [comment]
please test with cms-externals/pythia8#20

**Comment by smuzaffar** [comment]
please test with cms-externals/pythia8#20 for CMSSW_9_4_X

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test for CMSSW_9_4_X
yeah right

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
Do you remember if there is a special reason for this update?
The comparison shows several differences
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a82783/4858/summary.html

Eg. 
image

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test for CMSSW_9_4_X

**Comment by silviodonato** [comment]
@sbein (@alberto-sanchez @agrohsje @efeyazgan @mkirsano @qliphy @SiewYan) this PR shows several changes in wf 10024.0 10042.0 10224.0 10824.0 11624.0 PixelPhase1V/TrackingParticle plots (eg. https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2020-02-23-0000+a82783/35271/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/PixelPhase1V_TrackingParticle.html)

This seems to be against the "no-change rule" in production code for backports.
Could you comment on this?

**Comment by agrohsje** [comment]
In 10_2 there was no discrepancy:
https://github.com/cms-externals/pythia8/pull/20
To which version of 8.230 is the patch applied? 10_2 has 230-gnimlf5 while 9_4 was never modified, it is still the old base version of 8.230.

**Comment by silviodonato** [comment]
@agrohsje 
10_2_X points towards pythia8.230 `6e0f72a4478754a4fb13c91ccc92f21947f2788e` [1]
9_4_X   points towards pythia8.230 http://home.thep.lu.se/~torbjorn/pythia8/pythia8230.tgz [2]

https://github.com/cms-externals/pythia8/pull/20 is simply a change of one single line to `const double ResonanceDecays::MSAFETY     = 0.01`.
This changes correspond to the commit `31a940710c1f0199cef5862c480248623d1de9b1`.

The test in 10_2_X (cms-externals/pythia8#20) compared the tag from `6e0f72a4478754a4fb13c91ccc92f21947f2788e` to`31a940710c1f0199cef5862c480248623d1de9b1`

This PR (https://github.com/cms-sw/cmsdist/pull/5553) is in 9_4_X and changes from
http://home.thep.lu.se/~torbjorn/pythia8/pythia8230.tgz to `31a940710c1f0199cef5862c480248623d1de9b1`

In other words, the change in 10_2_X is just one single line, while the change in 9_4_X is much larger.
10_2_X change: https://github.com/cms-externals/pythia8/compare/6e0f72a4478754a4fb13c91ccc92f21947f2788e...31a940710c1f0199cef5862c480248623d1de9b1
9_4_X change: https://github.com/cms-externals/pythia8/compare/64564869d2d67e87c096de4921545e8e8334081f...31a940710c1f0199cef5862c480248623d1de9b1

If you want to apply only the single-line change to CMSSW_9_4_X I think we need a new tag corresponding to http://home.thep.lu.se/~torbjorn/pythia8/pythia8230.tgz + https://github.com/cms-externals/pythia8/pull/20

[1] https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_2_X/gcc700/pythia8.spec
[2] https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_9_4_X/gcc700/pythia8.spec

**Comment by agrohsje** [comment]
Hi @silviodonato, thanks for confirming. So this indeed explains the discrepancies. 
As far as I know 9_4 is only/mainly used by SUSY. It would be good to get their input on which of the 2 options they prefer. Full consistency or the inclusion of all modifications.  @kpedro88 can you comment or add others SUSY people. @qliphy what do you think?

**Comment by qliphy** [comment]
@agrohsje   I agree we should hear more from SUSY,  on whether to just add a single line change:
 http://home.thep.lu.se/~torbjorn/pythia8/pythia8230.tgz + cms-externals/pythia8#20
Adding @scarletnorberg

@silviodonato  
Maybe a naive question, are the changes on PixelPhase1V/TrackingParticle related to GEN?
I noticed  e.g. https://github.com/cms-sw/cmsdist/pull/3932 also had many failures on DQMHistoTests but was merged.

**Comment by kpedro88** [comment]
For general information: the other changes in the cms/230 branch are mainly bug fixes. These bug fixes are already used in 9_3_X ([spec file](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_9_3_X/gcc630/pythia8.spec)), so I think it is most consistent to use them also in 9_4_X.

**Comment by agrohsje** [comment]
Ok, if that is no issue for the susy scan, perfect. Let's include the fixes and accept the changes.

**Comment by silviodonato** [comment]
+1

These are the PR integrated in cms/230.
As @kpedro88 said, they were bug fixes.
https://github.com/cms-externals/pythia8/pull/8
https://github.com/cms-externals/pythia8/pull/9
https://github.com/cms-externals/pythia8/pull/10
https://github.com/cms-externals/pythia8/pull/12

In particular, as noted by @qliphy,  
https://github.com/cms-externals/pythia8/pull/10 (#3932) generated some differences.

**Comment by qliphy** [comment]
@smuzaffar   As discussed in [hn](https://hypernews.cern.ch/HyperNews/CMS/get/generators/4751.html), we realize [this](https://github.com/cms-externals/pythia8/pull/20) is not included in 10_2_X yet, can you help on this? Thanks a lot in advance!

**Comment by mrodozov** [comment]
@qliphy you want us to include the latest commit from here: 
https://github.com/cms-externals/pythia8/commits/cms/230
in 10_2 , correct ?

**Comment by qliphy** [comment]
@mrodozov   That is correct.

**Comment by mrodozov** [comment]
it's running https://github.com/cms-sw/cmsdist/pull/6097

**Comment by qliphy** [comment]
Thanks a lot @mrodozov

**Pull request merged**
