### PR TITLE
update py2-sqlalchemy to 1.1.4

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@ggovi, looks like the 0.8.2 patch does not work for 1.1.4? Canm you please build locally and provide a valid patch?

**Comment by smuzaffar** [comment]
please test

**Comment by ggovi** [comment]
@smuzaffar 
ok, I have updated https://github.com/cms-sw/cmsdist/pull/2762
please give it a try...

**Comment by smuzaffar** [comment]
@ggovi , this will still not work. I have updated it here #2763 . If that PR runs fine then I will backport it to for the normal IB. We can close this Pr in favour of #2763

**Comment by ggovi** [comment]
@smuzaffar 
not sure to understand... #2763 is this one.  I have provided the new patches.

**Comment by ggovi** [comment]
@smuzaffar 
ok i see, let's see, I think my patches should be ok anyhow

**Comment by smuzaffar** [comment]
oops sorry, I thought you commented on #2762 :-)
I meant, we can close #2762 and once #2763 is tested then we will backport it to the normal IBs.

**Comment by smuzaffar** [comment]
merging it for DEVEL IBs

**Comment by smuzaffar** [comment]
@ggovi , CMSSW_9_0_DEVEL_X_2017-01-12-2300 IB for slc6_amd64_gcc620 now contains the new sqlalchemy. Can you please test it there to make sure that it works as expacted before we merge it back to 90X IBs?

**Comment by ggovi** [comment]
Ok thanks, i'll have a look.

**Comment by ggovi** [comment]
it looks everything ok. Please go ahead with the merge!

**Pull request merged**
