### PR TITLE
Update to CUDA 11.0 RC (11.0.182)

### PR DESCRIPTION
**Pull request by fwyzard**
Update to CUDA 11.0 RC:
  * CUDA version 11.0.182
  * NVIDIA drivers version 450.36.06

Use the same package structure on Intel/AMD (x86_64), Power (ppc64le) and ARMv8/SBSA (aarch64).

Include support for c++17, gcc 9, clang 9.

See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-new-features .

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
abort

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for slc7_ppc64le_gcc820

**Comment by fwyzard** [comment]
please test for slc7_ppc64le_gcc820

**Comment by fwyzard** [comment]
please test for slc7_aarch64_gcc820

**Comment by fwyzard** [comment]
## Summary of the tests
External | CMSSW | `$SCRAM_ARCH` | Test results
---|---|---|---
:heavy_check_mark: | :heavy_check_mark: | slc7_amd64_gcc820 | [summary.html](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-822ae7/7016/summary.html)
:heavy_check_mark: | :heavy_check_mark: | slc7_amd64_gcc900 | [summary.html](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-822ae7/7034/summary.html)
:heavy_check_mark: | :heavy_check_mark: | cc8_amd64_gcc8 | [summary.html](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-822ae7/7033/summary.html)
:heavy_check_mark: | :heavy_check_mark: | slc7_aarch64_gcc820 | [summary.html](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-822ae7/7036/summary.html)
:heavy_check_mark: | :x: | slc7_ppc64le_gcc820 | [summary.html](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-822ae7/7020/summary.html)

So this looks good on CC7 and on CC8, with GCC 8 and GCC 9, on x86 and ARM.
On Power the externals build fine, and I'm not sure that the CMSSW are related or not; at least some are timeouts.

**Comment by fwyzard** [comment]
please test for slc7_ppc64le_gcc820

**Comment by fwyzard** [comment]
abort

**Comment by fwyzard** [comment]
please test for slc7_ppc64le_gcc820

**Comment by smuzaffar** [comment]
@fwyzard , this looks good to go. Do you have any other changesing mind? One simplification we can do is to set cppstd in `cuda-flags.file` and then use it where needed e.g in `cuda-toolfile.spec`,  `cupla.spec` and  `cuda-flags.file`

**Comment by fwyzard** [comment]
Do you mean having a way to synchronise the `-std=c++##` flags in
  - https://github.com/cms-sw/cmsdist/blob/260596a1131ed5dd8751bb3509e70a4d5e75f83e/cuda-flags.file#L20
  - https://github.com/cms-sw/cmsdist/blob/260596a1131ed5dd8751bb3509e70a4d5e75f83e/cuda-toolfile.spec#L42
  - https://github.com/cms-sw/cmsdist/blob/260596a1131ed5dd8751bb3509e70a4d5e75f83e/cupla.spec#L21

?
Yes, that sounds like a good idea.

Should I do it here, or open a separate PR for it ?

We should also update the `cub` toolkit, now that it comes as a part of the `cuda` package.

**Comment by smuzaffar** [comment]
yes that is the idea, so that in future we only update host std flag in one place.
Yes please, update it here, I will rerun a final test for production architecture ( just to get the labels green).

**Comment by fwyzard** [comment]
Let's see if it works ...

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
