### PR TITLE
[Geant4] Update to verion new patched version 10.6.2

### PR DESCRIPTION
**Pull request by smuzaffar**
New Geant4 patch02 version:  http://cern.ch/geant4-data/ReleaseNotes/Patch4.10.6-2.txt
FYI @civanch , let me know if we need any CMS patches to go with it or if any geant4 data needs to be updated. Do we need to build G4Py (only available for python3 with Boost.Python version 1.72)?

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , no modification in data files are required for this patch. We never use G4Py in CMSSW. Not clear if we will use in future.

Unfortunately, differences in regression are visible, so ordinary 11_2_0_pre1 validation will be required. 

I do not understand why ECAL unit test fails in reading of DB, likely it is not connected with this PR?

**Comment by smuzaffar** [comment]
@civanch thanks.
unit test failure is not related to this change , it is already failing in IB ( https://github.com/cms-sw/cmssw/issues/30049 )
So so we first integrate in a dedicated GEANT4 IB and build CMSSW_11_2_0_pre1_GEANT4 for validation?

**Comment by civanch** [comment]
@smuzaffar , yes, let us start from GEANT4 IB. I am not sure if it will be needed CMSSW_11_2_0_pre1_GEANT4 or test within CMSSW_11_2_0_pre1. Let us ask PPD.

**Comment by civanch** [comment]
@smuzaffar , should this PR be re-tested or GEANT4 IB may be updated with this patch?

**Comment by smuzaffar** [comment]
@civanch , I just have added GEANT4 IB and will include this in that.

**Pull request merged**
