### PR TITLE
[5.3.X][FrontierClient] Update to verison 2.9.1

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by smuzaffar** [comment]
backport of #5673

**Comment by mrodozov** [comment]
@smuzaffar when do we get this backports in ?

**Comment by smuzaffar** [comment]
@mrodozov , this is not urgent. We are building 11.1.0.pre5 with this new verision and will see how it goes. If there are no issues in next couple of weeks then we can merge these.

**Comment by smuzaffar** [comment]
+externals
@silviodonato , feel free to merge it for next full release. It contains a bug fix for frontier client ( https://github.com/cms-sw/cmsdist/issues/5672 )

**Comment by silviodonato** [comment]
+1

**Pull request merged**
