### PR TITLE
[Do not merge] Testing virtual overlay file on CMSSW

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
Hi! Please trigger the testing when it's possible. Thanks.

**Comment by davidlange6** [comment]
please test


On 10 Jan 2019, at 12:26, Yuka Takahashi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! Please trigger the testing when it's possible. Thanks.

**Comment by smuzaffar** [comment]
please test

**Comment by yamaguchi1024** [comment]
Is this the same error as IB's?

**Comment by smuzaffar** [comment]
No, this is different error. The one in IB is about duplicate bins and this one is
```
----- Begin Fatal Exception 11-Jan-2019 06:13:16 CET-----------------------
An exception of category 'WrongNumberOfTasks' occurred while
   [0] Calling endJob for module TestTBBTasksAnalyzer/'tester'
Exception Message:
expected 8 but instead saw 6
----- End Fatal Exception -------------------------------------------------
Failure using cmsRun -n 8 /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_5_CXXMODULE_X_2019-01-08-2300/src/FWCore/Framework/test/test_tbb_threads_from_commandline_cfg.py: status 65
status = 16640
```

**Comment by yamaguchi1024** [comment]
Delete relocateconfig, it should work with out this! Could you please trigger the test again?

**Comment by smuzaffar** [comment]
@yamaguchi1024 , do we need to relocate etc/cling/llvm/Config/llvm-config.h ?

**Comment by yamaguchi1024** [comment]
@smuzaffar As far as I know, we don't need

**Comment by smuzaffar** [comment]
please test

although this should not fix the failing unit test.

**Comment by yamaguchi1024** [comment]
Why is it taking so much time? Maybe it's in an infinite loop?

**Comment by mrodozov** [comment]
@yamaguchi1024 can you see this 
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/32564/console ? 
(I'm not sure about permissions) The job is still ongoing

**Pull request merged**
