### PR TITLE
update crab-dev to v3.220714

### PR DESCRIPTION
**Pull request by novicecpp**
Bump crab-dev to [v3.220714](https://github.com/dmwm/CRABClient/releases/tag/v3.220714).
Also remove unused `wmcore_version`.

cc: @belforte

### CODE REVIEW

**Comment by belforte** [comment]
thanks @novicecpp , maybe you are still in time to also update crabserver version to latest one before @smuzaffar starts processing this. If not.. we'll do in next round

**Comment by novicecpp** [comment]
Done. I forgot that we have update in `ServerUtilities.py` file.
Thanks @belforte.

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Hi @novicecpp, @belforte,

Test have passed. Do you agree to merge?

Thank you

**Comment by novicecpp** [comment]
Yes, please.

**Comment by aandvalenzuela** [comment]
+1

**Pull request merged**
