### PR TITLE
updated frontier client to 2.8.20

### PR DESCRIPTION
**Pull request by smuzaffar**
- new version 2.8.20
- updated frontier client python dbapi

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , frontier client 2.8.20 is in DEVEL IBs and we do not see any issues. @ggovi also requested to also update the python db api which is also included in this PR.  Should we include this in 81X?

**Comment by davidlange6** [comment]
no problem.  but can you see how to test online so we aren’t surprised later (that test can be months from now)

**Comment by smuzaffar** [comment]
@fwyzard , is it possible to test any latest 81X DEVEL IB in online env to test frontier client 2.8.20 (which is just a bug fix release: http://frontier.cern.ch/dist/clientreleasenotes.txt )?

**Comment by fwyzard** [comment]
hi @smuzaffar ,
after the switch to cmspkg, I haven't tried to installing any releases myself, so I'm not sure how to try the DEVEL IBs online.

If you can point me to some instructions I can give it a try in the coming days.

**Comment by smuzaffar** [comment]
@fwyzard, how were you installing the release before the cmspkg switch? Were you using the same installation area used by production online machine or some separate area? If it is different then all you need to do is to run (note you need to select the right repo e.g. this week the latest repo is cms.week0 and next week it will be cms.week1)

```
INST_DIR=<dir-to-install>
ARCH=slc6_amd64_gcc530
wget http://cmsrep.cern.ch/cmssw/repos/bootstrap.sh
sh ./bootstrap.sh -a $ARCH -r cms.week0 -path $INST_DIR setup
$INST_DIR/common/cmspkg -a $ARCH  search CMSSW_8_1_DEVEL_X
$INST_DIR/common/cmspkg -a $ARCH install <version>
```

**Comment by fwyzard** [comment]
Tested successfully on one of the online machines at Point 5, with CMSSW_8_1_DEVEL_X_2016-11-11-1100 .

**Comment by smuzaffar** [comment]
Thanks @fwyzard .

**Pull request merged**
