### PR TITLE
Update libunwind to v1.7.2

### PR DESCRIPTION
**Pull request by gartung**
Might address problems with segfaults

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
looks good, the unit test error is due to https://github.com/cms-sw/cmssw/pull/43037

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
@smuzaffar The profiling seems to run without the recent segfaults. Can this be merged?

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
