### PR TITLE
[12_4_X] bumping up sherpa to 2.2.15

### PR DESCRIPTION
**Pull request by shimashimarin**
Bumping up Sherpa to 2.2.15 based on the discussion in this thread: https://cms-talk.web.cern.ch/t/sherpa-event-generation-segfault-with-privately-generated-sherpack-for-z-jets/23629/9

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
backport of https://github.com/cms-sw/cmsdist/pull/8450

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@shimashimarin why only backport this to 10.6 and 12.4? What about 12.5, 12.6 and 13.0?

**Comment by shimashimarin** [comment]
Hi @smuzaffar, 10.6 and 12.4 are used for current UL and Run3 sample production. If needed, I can make pull requests to backport this to 12.5, 12.6, and 13.0. Please let me know.

**Comment by smuzaffar** [comment]
assign generators

@rappoccio  @antoniovilela feel free to merge it for 12.4

**Comment by menglu21** [comment]
+1

**Comment by smuzaffar** [comment]
@rappoccio , @antoniovilela looks like this can also go in next 12.4 release

**Comment by rappoccio** [comment]
+1

**Pull request merged**
