### PR TITLE
backports jemalloc numpy matplotlib and scikit-learn from 81devel

### PR DESCRIPTION
**Pull request by iahmad-khan**
For https://github.com/cms-sw/cmssw/issues/15602

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
@davidlange6 should we merge it now.

**Comment by smuzaffar** [comment]
looks good to me. We still have some changes for heppdt.spec in devel (e.g. getting heppdt changes from out github repo instead of http://lcgapp.cern.ch).
I would suggest to make another PR to heppdt too.

**Comment by davidlange6** [comment]
indeed I wasn’t sure what the heppdt changes were.. if those are safe, we can back port them too.

**Comment by davidlt** [comment]
This resulted in failures on multiple architectures. matplotlib is failing to link to build png module.

**Comment by davidlt** [comment]
Install step re-runs the configuration, finds out that there is no png installed on the system and fails. On the systems where png is installed, everything works.

**Comment by davidlt** [comment]
I pushed a fix, but this needs a review if a more proper fix should be added.

**Pull request merged**
