### PR TITLE
update pdf sets for ultra legacy release

### PR DESCRIPTION
**Pull request by agrohsje**
This PR is a back-port of 
https://github.com/cms-sw/cmsdist/pull/5940
to extend the available PDF sets in UL MC production.

### CODE REVIEW

**Comment by agrohsje** [comment]
assign generators

**Comment by agrohsje** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@qliphy @perrotta feel free to merge it for 10.6.X

**Comment by agrohsje** [comment]
+generators
thanks @smuzaffar

**Comment by qliphy** [comment]
+1

**Pull request merged**
