### PR TITLE
Remove python and py2-future

### PR DESCRIPTION
**Pull request by smuzaffar**
This is backport of https://github.com/cms-sw/cmsdist/pull/7359 (from DEVEL IBs)  which remove python2 and python2 based packages
backport of #7359

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@qliphy , @perrotta @makortel  , this pr drops python2 and last py2 back package from 12.3.X release. This has been in devel IBs for  couple of months. Feel free to merge it.

**Comment by perrotta** [comment]
+1
- The beginning of the 12_3_X cycle is the right moment to merge this

**Comment by davidlange6** [comment]
hi @smuzaffar - the IB of last night has some warnings due to this change
```
****WARNING: Invalid tool python. Please fix das_client file.
****WARNING: Invalid tool python. Please fix frontier_client file.
```

**Comment by smuzaffar** [comment]
thanks @davidlange6 , https://github.com/cms-sw/cmsdist/pull/7501 should fix this.

**Pull request merged**
