### PR TITLE
[DD4hep] Bump to new version

### PR DESCRIPTION
**Pull request by mrodozov**
please test
@andresailer

### CODE REVIEW

**Comment by mrodozov** [comment]
this last changes are fixing our ROOT master and ROOT 6-20 builds (I really hope so) ! 
well done then, I don't have to deal with this myself

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_X_2020-02-26-1100

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@andresailer I'd assume 
`#include "DD4hep/BasicGrammar.h"`
doesn't exist anymore ?

**Comment by mrodozov** [comment]
Yup it's called Grammar.h now. I'll fix i in the morning

**Comment by mrodozov** [comment]
+externals
@silviodonato we need cms-sw/cmssw#29055 to go in with this

**Comment by ianna** [comment]
+1

**Comment by mrodozov** [comment]
@ianna the cmssw one :)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
