### PR TITLE
Update pymongo to 3.10.1

### PR DESCRIPTION
**Pull request by amaltaro**
Keep both py2 and py3 in sync as well.
@vkuznet since you are still the main "customer" of pymongo, any reason not to update it?

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 1d66737e2f3577d5b0733e5e69c3e6ad765b1f5e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5754/test_1d66737-20200417-084004.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
Alan, as with any Python dependency it should be validated. Since DAS is pure Go code we only left with WMArchive. Therefore before the merge we should validate WMarchive service with new version, I'll try to to do it next week. If I'll not back on this ticket feel free to ping me again, I'm quite busy these days.

**Comment by amaltaro** [comment]
@vkuznet Valentin, did you manage to look into this? Once we put @todor-ivanov Todor's PR in WMCore, we could do some checks from our side too.

**Comment by vkuznet** [comment]
Alan, I tested WMArchive with new build which includes this change and so far it looks fine. Therefore you have a green light from me here.

**Comment by amaltaro** [comment]
Thanks Valentin.
@todor-ivanov please verify this new version once new RPMs are made available.

**Comment by todor-ivanov** [comment]
Hi @muhammadimranfarooqi I see this one is already merged. Can you confirm that pymongo version in vocms0731 is already updated to 3.10.1. I checked the logs from the machine and everything works as it is expected. But since I do not have the access to that machine I just wanted to confirm that service there is already running with the new version of pymongo. Anyway, I do not see a showstopper for us to move to the newer version.

**Comment by muhammadimranfarooqi** [comment]
@todor-ivanov 

Yes, today I deployed new release on testbed. Pymongo has been udpated on VM testbed nodes.

**Comment by todor-ivanov** [comment]
Thanks @muhammadimranfarooqi ! In this case, Yes - (as expected) we are definitely running well with the new version.

**Comment by amaltaro** [comment]
Perfect! Thanks for checking it, Todor.

**Pull request merged**
