### PR TITLE
add cuda to ROOT_INCLUDE_PATH

### PR DESCRIPTION
**Pull request by davidlange6**
(@smuzaffar - are you aware of some reason why ROOT_INCLUDE_PATH should differ from the list of all include paths of cmssw and its externals?)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , in start we blindly start adding include directories to $ROOT_INCLUDE_PATH . this side effect of this is that root cling has to go through all these to find header files at runtime.
Ideally we should only have those include path in $ROOT_INCLUDE_PATH  which are part of our dictionaries.

**Comment by davidlange6** [comment]
Ok- thanks for the clarification - maybe we have a good way to trimming that list with modules.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
