### PR TITLE
backport cuda from 104X devel

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #4368

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard , any idea what to do with these failing unit tests? They fail now as there was no cuda device.

**Comment by fwyzard** [comment]
I didn't know we had pushed them upstream... I'll have a look and see if I can add a simple check

**Comment by fwyzard** [comment]
Hi @smuzaffar , 
I've had a look at the tests, and while they could print a more meaningful error message (i.e. "No CUDA devices found, skipping the test"), any error is already being caught, and the tests return success (return 0).

How should they be changed to keep the bot happy ?

**Comment by smuzaffar** [comment]
@fwyzard , thanks for looking in to this. 
Can you please propose a change where these tests do not fail (i.e. return 0) when no cuda device is found?

**Comment by fwyzard** [comment]
As far as I can see, `main()` already always does `return 0`:

### cudaAtan2Test.cu
```
  ...
} catch(cuda::runtime_error ex) {
   std::cout << "cuda error " << ex.what() << std::endl;
} catch(...) {
   std::cout << "a non cuda error" << std::endl;
}

  return 0;
}
```
### cudaMathTest.cu
```
   ...
} catch(cuda::runtime_error ex) {
   std::cout << "cuda error " << ex.what() << std::endl;
} catch(...) {
   std::cout << "a non cuda error" << std::endl;
}

  return 0;
}
```

What else would I need to change ?

**Comment by smuzaffar** [comment]
@fwyzard , I think problem is here https://github.com/cms-sw/cmssw/blob/master/DataFormats/Math/test/cudaMathTest.cu#L100 where we exit if device count is 0.

**Comment by fwyzard** [comment]
Should be fixed by
  - https://github.com/cms-sw/cmssw/pull/24938 (master)
  - https://github.com/cms-sw/cmssw/pull/24939 (10.3.x)
  - https://github.com/cms-sw/cmssw/pull/24940 (10.2.x)

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fwyzard** [comment]
by the way, when changes to CMSDIST are forward- or back-ported across different branches, would it be possibly to keep the original split in the commits, or at least the original author ?

**Pull request merged**
