### PR TITLE
[xrootd] Updated to version 5.5.3

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
@smuzaffar we plan to start building pre1 after 1100: do you have other cmsdist additions that we should wait for before starting it?

**Comment by smuzaffar** [comment]
No @perrotta , this was the last change I wanted to include before 11h00 IB.

**Pull request merged**
