### PR TITLE
Replace old HF shower data in SimG4CMS/Calo.

### PR DESCRIPTION
**Pull request by ghost**
According to issue #795.

### CODE REVIEW

**Comment by civanch** [comment]
-1
@degano , please do not remove SimG4CMS/Calo/data/HFShowerLibrary_npmt_eta4_16en.root, because it is our main SL for 2015.

**Comment by ghost** [comment]
@civanch fixed.

**Comment by civanch** [comment]
@degano, sorry after today discussion with HCAL experts its turn out that not the best file was taken for 2015 production.

The correct one is located in /afs/cern.ch/user/a/abdullin/public/HF_NewShowerLibrary_NewPMTs/HFShowerLibrary_npmt_noatt_eta4_16en.root - it is also required change file name inside data-SimG4CMS-Calo.spec

**Comment by civanch** [comment]
At the last SIM meeting (September,5) it was confirmed that we need to have two HF SLs:
HFShowerLibrary_npmt_noatt_eta4_16en.root
HFShowerLibrary_oldpmt_noatt_eta4_16en.root
@degano, please, proceed with this PR

**Comment by civanch** [comment]
@degano, sorry but the most important part is not there: for 2015 run HFShowerLibrary_npmt_noatt_eta4_16en.root is needed instead of existing file HFShowerLibrary_npmt_eta4_16en.root

We need this urgently for pre6.

**Comment by ghost** [comment]
@civanch I am taking care of it right now.

**Comment by ghost** [comment]
@civanch sorry for the mess, fixed in #990

**Pull request merged**
