### PR TITLE
Get catch2 2.13.6

### LINKED ISSUE #7052: Update catch2
We seem to have Catch2 version 2.2.2, whereas the latest version appears to be 2.13.6. The later versions have some useful-looking features (`STATIC_REQUIRE` motivated me for this issue). Could we look into updating Catch2?

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #7052

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#34205

**Comment by smuzaffar** [comment]
+externals
this should be merged along with cms-sw/cmssw#34205

**Comment by qliphy** [comment]
+1

**Comment by smuzaffar** [comment]
@mrodozov , looks like https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_0_X_2021-06-23-1600/DQM/TrackerRemapper also need changes due to catch2.

**Comment by smuzaffar** [comment]
the reason that PR tests did not catch this is that this was merged in a newer IB `CMSSW_12_0_X_2021-06-22-2300` while the tests were run based on `CMSSW_12_0_X_2021-06-22-1100`

**Comment by smuzaffar** [comment]
OK I opened a PR https://github.com/cms-sw/cmssw/pull/34230 to fix it

**Pull request merged**
