### PR TITLE
[9_4_X] Update data-RecoBTag-Combined.spec

### PR DESCRIPTION
**Pull request by mrodozov**
Backport of https://github.com/cms-sw/cmsdist/pull/4540

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 0 differences found in the comparisons

this confirms that this PR can be merged by itself now, before cms-sw/cmssw#25371  is merged

**Comment by smuzaffar** [comment]
+externals

this resolves #4537

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
