### PR TITLE
Remove tinyxml external, tinyxml2 used instead in cmssw

### PR DESCRIPTION
**Pull request by mrodozov**
Dependencies on tinyxml removed from cmssw, no externals depend on it, so we remove the external itself. Use tinyxml2 instead

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , @Dr15Jones: CMSSW and its externals do not use tinyxml any more. This has been replaced by tinyxml2 in cmssw. Any objection on dropping it from our externals?

**Comment by Dr15Jones** [comment]
Please do drop

**Pull request merged**
