### PR TITLE
Advance data for RecoJets/JetProducers.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-data/RecoJets-JetProducers/commit/90ae65aeac2c5b528578458717d300c83fa07b09

### CODE REVIEW

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@davidlange6 
shouldn't we have equivalent CMSSW categories for externals?

In this particular case just new files are added, and cmssw code change is required to enable the feature.
However, sometimes file names stay but contents change and this case should be checked.

**Comment by slava77** [comment]
Just making a note about https://github.com/cms-sw/cmssw/pull/13472 so that the merge status of this PR is visible there.

For new files added in this package (no indiscriminate includes are present in the code runtime) we can get the update of the external  in IBs and then proceed on cmssw side.

**Comment by davidlange6** [comment]
is why we nominally want these requests raised at the ORP. But there are several ways to do it.

**Comment by slava77** [comment]
@degano 
ping
This just adds new files.
Nothing will change or be noticed in the tests.

**Comment by slava77** [comment]
We need 80X and 76X versions of this.

**Pull request merged**
