### PR TITLE
spec file for new release of t0wmadatasvc 2.0.8

### PR DESCRIPTION
**Pull request by LinaresToine**

### CODE REVIEW

**Comment by LinaresToine** [comment]
please test

**Comment by LinaresToine** [comment]
Hello @arooshap

I am not sure if the bot was triggered. Does it normally say something? I don't know if the 'please test' command did anything.

Thank you for your help!!

Regards,

Antonio

**Comment by smuzaffar** [comment]
please test

For now bot should not trigger the test as I am not a valid comp PR tester (https://github.com/cms-sw/cms-bot/blob/431f4e0695be4862972deddd5db7906403a11791/cmsdist_merge_permissions.py#L9-L17)

**Comment by smuzaffar** [comment]
ping

now bot should recognize my plase test comment

**Comment by LinaresToine** [comment]
@smuzaffar Thank you. So as I understand I must comment `please test` and then `ping`, is this correct?

**Comment by smuzaffar** [comment]
no @LinaresToine . @arooshap is trying to setup comp bot so that one of the comp admin can start the tests using `please test` comment. This is still not functional yet ( see https://github.com/dmwm/deployment/pull/1282 and https://github.com/dmwm/deployment/pull/1285 )

**Pull request merged**
