### PR TITLE
Further cleaning of python2 packages

### PR DESCRIPTION
**Pull request by davidlange6**
For DEVEL.
note - this removes the python dependencies of triton-interface-server - the comments suggest the python interface has been removed

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
> note - this removes the python dependencies of triton-interface-server - the comments suggest the python interface has been removed

FYI @kpedro88

**Comment by kpedro88** [comment]
We're not currently setting up the Triton python client library, but those dependencies may be needed for other parts of the installation. I guess we'll see if it breaks in the test.

**Comment by smuzaffar** [comment]
while test are still running, let get it in DEVEL IB to run full tests

**Comment by smuzaffar** [comment]
@davidlange6 , we need to slow down this migration :-) we need to fix cms-bot scripts to somehow switch python versions based on release. we have started dropping py2 packages which were needed by bot scripts e.g. psutils, yaml, requests.

**Comment by kpedro88** [comment]
While checking the test logs, I noticed something else that should probably be fixed for the python3 migration:
```
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7010/15875/CMSSW_12_0_DEVEL_X_2021-06-09-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:155: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not path is '':
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7010/15875/CMSSW_12_0_DEVEL_X_2021-06-09-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:174: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7010/15875/CMSSW_12_0_DEVEL_X_2021-06-09-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:263: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not path is '':
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7010/15875/CMSSW_12_0_DEVEL_X_2021-06-09-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:276: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7010/15875/CMSSW_12_0_DEVEL_X_2021-06-09-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:414: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7010/15875/CMSSW_12_0_DEVEL_X_2021-06-09-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:530: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7010/15875/CMSSW_12_0_DEVEL_X_2021-06-09-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:742: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
```

**Comment by davidlange6** [comment]
The issue has already been reported in an issue (its not a python3 issue just python3 is smart enough to report it)

**Pull request merged**
