### PR TITLE
Added new dqmgui spec

### PR DESCRIPTION
**Pull request by smuzaffar**
New DQM GUI is an upload dependencies of cmssw-tool-conf which means it will be built/uploaed when we build cmssw but cmssw does not depend on it.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@andrius-k, @jfernan2 this is the spec to build new dqm gui. Note that I am getting the sources from https://github.com/andrius-k/cmssw. I would suggest to create a separate repository for this. These is no need to keep it in cmssw.

For now I have set the version of this to 6.22_V1 (i.e. ROOT version of cmssw and V1 of dqmgui). Please suggest a correct version e.g. once we have a separate repo for it then you can provide a tag which we can use in here

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@andrius-k, @jfernan2, I have built new dqmgui . Can you please install and run to see if it works. All you need ot do is
```
wget http://cmsrep.cern.ch/cmssw/bootstrap.sh
ARCH=slc7_amd64_gcc820
bash ./bootstrap.sh -a ${ARCH} -r cms.week1.muzaffar setup
./common/cmspkg -a ${ARCH} install -y cms+dqmgui+V1_6.22-cms
source ${ARCH}/cms/dqmgui/V1_6.22-cms/etc/profile.d/init.sh
# the start the gui ... no idea how :-)
```

**Comment by andrius-k** [comment]
Hi @smuzaffar, I ran the instructions on lxplus and I faced a few difficulties:

* Looks like `bootstrap.sh` should be executed with an argument `-r` instead of `-repo` 
* Running `cmspkg` took about 7 minutes to complete, which might introduce some friction in our daily operations. Is it possible to cache/optimise this?

When running in our P5 machine I faced some more issues:

* I was unable to `wget` the `bootstrap.sh` file when deploying in our P5 machine due to the fact that there's access to the outside in P5
* When I manually copied over the `bootstrap.sh` to the P5 machine and executed it, it got stuck. After debugging it I saw that `bootstrap.sh` launches `wget` that keeps on trying to run this, and timeouts every time: 
`connect(4, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("188.184.102.160")}, 16) = -1 ETIMEDOUT (Connection timed out)`

Is there a canonical way to overcome the lack of network connectivity in P5, or do we have to coordinate with sysadmins to white-list required servers?

**Comment by andrius-k** [comment]
Hi @smuzaffar, also we will move the code from CMSSW repo to a separate repository. We will inform you once that is done.

**Comment by smuzaffar** [comment]
@andrius-k , for P5, the online team clones our repository inside P5 and use that clone to deploy package. So once we have an official build of this then it should be available in online repository for deployment.

About the installation time, it installs `root` and its dependencies. It should not take 7 mins e.g. on lxplus in /tmp area is took less than 2 mins (I am not inclduing the bootstrap time as that is only done once).

**Comment by andrius-k** [comment]
@smuzaffar, 7 minutes is that time that I observed running the script for the very first time.
 
I would like to make one thing straight before proceeding: how do we identify the correct CMSSW version we want the DQMGUI to be compatible with?

**Comment by smuzaffar** [comment]
how this was done in past? 
dqmgui only depends on root and you have a test in cmssw which check the root versiona dn dqmgui competibility .... you should know better than me :-)

**Comment by andrius-k** [comment]
Can we configure the ROOT version by just changing this value: `V1_6.22`? If that's the case, then we can do this mapping (CMSSW version -> ROOT version) ourselves.

**Comment by smuzaffar** [comment]
Youwill get the root version which is selected by cmsdist/root.spec . If you want to build it for a different root version then we need to use a different cmsdist branch.
I am trying to automate the detection of root version automatically , so that dqmgui is get automatically the root version for root.spec

**Comment by jfernan2** [comment]
Thank you @smuzaffar 
We definitely want to use the same ROOT version, so the use case that would need a different cmsdist branch is not needed indeed.
If my understanding is correct we should then wait for you to automate the detection of root version automatically.
Thanks

**Comment by smuzaffar** [comment]
@jfernan2 , should we create a cms-sw/dqmgui repo?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by andrius-k** [comment]
Hi @smuzaffar, usually we host all our services here: https://github.com/cms-dqm/ 
Is there any advantage of being under the cms-sw user? If not, we will host the code in the cms-dqm account for consistency.

**Comment by smuzaffar** [comment]
no advantage, go ahead and create a repo under https://github.com/cms-dqm/

**Comment by andrius-k** [comment]
Ok, I'll let you know once the code is migrated.

**Comment by andrius-k** [comment]
Hi @smuzaffar,
I created a separate repo for the DQM GUI and ported the code there: https://github.com/cms-dqm/dqmgui

This is the script to build the DQM GUI outside of CMSSW environment (`g++` available in CMSSW 11 is still required): https://github.com/cms-DQM/dqmgui/blob/master/scripts/build.sh
Also some CMSSW dependencies are required (see `build.sh`) and now I'm getting them from CVMFS.

Running requires Python 3 and libraries listed here: https://github.com/cms-DQM/dqmgui/blob/master/python/requirements.txt

Please let me know if anything else is required from your side.

**Comment by smuzaffar** [comment]
@andrius-k , can you please create a tag for  https://github.com/cms-dqm/dqmgui which I can use in the spec file?

**Comment by smuzaffar** [comment]
@andrius-k I have opened a pull request https://github.com/cms-DQM/dqmgui/pull/1 to simpilfy the build. This will allow me you us ethe Makefile directly to build dqmgui

**Comment by andrius-k** [comment]
Hi @smuzaffar, I have a short question about your PR, please see inline: https://github.com/cms-DQM/dqmgui/pull/1

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
Hi @smuzaffar 
How do we proceed with this PR given the testing done in:
https://github.com/cms-DQM/dqmgui/pull/1
?
Thanks

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@jfernan2 , lets re-run the tests and I will integrate it once successful

**Comment by smuzaffar** [comment]
please test
errors are due to heppdt update

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
