### PR TITLE
MkFit - add in architecture condition

### PR DESCRIPTION
**Pull request by mrodozov**
The external doesn't build for arm, expecting the same for ppc, put it in conditional statement until we have a proper fix

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
@mrodozov 
in case the mkFit developers can make it work on these archs: which nodes can be used for testing?

@makortel 
@osschar

**Comment by makortel** [comment]
@mrodozov Thanks. Would you happen to have pointers to the build logs on arm (and power) to get a glimpse on the failures? Eventually, as @slava77 wrote, they would need to be addressed by the developers.

I suppose the (upcoming) CMSSW lib and plugin need a similar arch protection as well, right? (as otherwise they couldn't link `mkfit` external)

**Comment by mrodozov** [comment]
please test
this "fixes" arm in terms of "it compiles", for ppc we need a bit more

**Comment by mrodozov** [comment]
> @mrodozov Thanks. Would you happen to have pointers to the build logs on arm (and power) to get a glimpse on the failures? Eventually, as @slava77 wrote, they would need to be addressed by the developers.

We'll think of some service account to give to developes

> I suppose the (upcoming) CMSSW lib and plugin need a similar arch protection as well, right? (as otherwise they couldn't link `mkfit` external)

If the external is not building/running on the non prod archs then yes.

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc700

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc700

**Comment by davidlange6** [comment]
nothing to do with the build error - but should this not be compiled with some optimization?

**Comment by mrodozov** [comment]
update to use single patch is here https://github.com/mrodozov/cmsdist/tree/adjusting_mkfit 
I'll push it when the ppc tests are finished (not to ruin the relval results, the test is at the end)
@davidlange6 I'd left it to the devs first to propose suggestions

**Comment by smuzaffar** [comment]
closing in favor of #5179 which uses a simple patch.

**Comment by smuzaffar** [comment]
@davidlange6 , about optimization option. It does build with `-O3` . The `g++ -MM -MG -MQ ...` commands without any optimization options are for generating Make dependencies .

**Pull request closed without merging**
