### PR TITLE
Backport ROOT PR 7563 to test in Arm

### PR DESCRIPTION
**Pull request by mrodozov**
see 
https://github.com/root-project/root/pull/7563
and
bottom of https://github.com/cms-sw/cmssw/issues/31123

### CODE REVIEW

**Comment by mrodozov** [comment]
I'm building it on arm to test this:
https://github.com/cms-sw/cmssw/issues/31123#issuecomment-800450831
if it works we can just build full Arm IB to check if it makes a difference / for dev purposes

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
thanks @mrodozov for testing it. In future, instead of merging changes to cms root branch, please open a PR for cms-externals/root and test that

**Comment by mrodozov** [comment]
I can't reproduce the mentioned crash anyhow, I tried master, 6.22 etc on Arm . 
We can get this (it's a small change) and build an IB to check it

**Comment by smuzaffar** [comment]
enable threading

**Comment by smuzaffar** [comment]
please test workflow 136.776 for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
ROOT got this backported, I'm closing this to get the latest versions

**Pull request closed without merging**
