### PR TITLE
backport boost and eigen changes for cuda

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , are you happy with this eigen update? comparison dos not show many failures.
Note that for tensorflow we are using a different commit for eigen ( https://github.com/cms-externals/tensorflow/blob/cms/v1.3.0/tensorflow/workspace.bzl#L150 )

**Comment by davidlange6** [comment]
we need the pre2 validation as already discussed for eigen. However, we should also sync up the eigen in tensorflow (also in the master)

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
