### PR TITLE
Update protobuf 3.15.1 and grpc 1.35.0

### PR DESCRIPTION
**Pull request by smuzaffar**
Update protobuf to version 3.15.1 and GRPC to version 1.35.0 which allows to build with c++17 .
These changes are needed by newer Tensorflow but can go in before we converge on TF 2.4.1

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmssw#32993

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
merge

**Pull request merged**
