### PR TITLE
New tag for geant4

### PR DESCRIPTION
**Pull request by mrodozov**
Testing changes in the latest PR: https://github.com/cms-externals/geant4/pull/26

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
I'm closing this as it's the same as  #3505

**Comment by mrodozov** [comment]
+1

**Comment by civanch** [comment]
@mrodozov , @davidlange6,  now we have several PRs for various branches of 9_3_0 and 9_4_0 but not for all. Please, confirm that I am doing a correct thing adding more PRs for cmsdist - there are also gcc700 branches where similar PRs are not yet proposed.  For now I am waiting for  merge of existing PRs  before submitting new.

**Comment by smuzaffar** [comment]
closing it in favor of https://github.com/cms-sw/cmsdist/pull/3511

**Pull request closed without merging**
