### PR TITLE
Updating db from Mysql to Mariadb_10.0.12 version + py2-mysqldb_1.2.4b4

### PR DESCRIPTION
**Pull request by jmonkevicius**
- Updated database from MySQL to MariaDB 10.0.12 version.
- Updated py2-mysqldb to newer 1.2.4b4 version.
- Updated  py2-mysqldb-setup.patch for correct py2-mysqldb working with new mysqldb version.
- Removed mysql.spec file

It was tested only in SLC6 and pushed to comp_gcc481 branch.
It was tested also with SQLAlchemy 0.9.6 version [ https://github.com/cms-sw/cmsdist/pull/983 ]. Not with 0.5.2 version.
It was tested also with cx_Oracle 5.1.3 version [ https://github.com/cms-sw/cmsdist/pull/1024 ]. Not with 5.1 version.

In WMAgent deployment case, before starting MariaDB services, need to change deployment file [ https://github.com/jmonkevicius/deployment/commit/fb33c9e12365d760b0ca27075d0fd5285df77503 ]. 
Reason: new version of database don't understand simbols "set-variable" . Seting my.cnf parameters at mariadb.spec file is not working because deployment script [  https://github.com/dmwm/deployment ] is overwriting this config file.
# 
- [Not resolved yet] Standart testing and validation of WMAgent from Justas was successful, but this MariaDB version gives warning after command 

" ./manage execute-agent wmagent-resource-control --add-all-sites --plugin=CondorPlugin --pending-slots=50 --running-slots=50 " -->

"
Adding T3_GR_IASA to the resource control db...
/data/srv/wmagent/0.9.95b-comp2/sw.pre.jmonkevi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6/lib/python2.6/site-packages/sqlalchemy/engine/default.py:435: Warning: Duplicate entry 'T3_GR_IASA' for key 'site_name'
cursor.execute(statement, parameters)
"
# .

@amaltaro @juztas @hufnagel @geneguvo

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 2d6f6939499e3ceb099c62a8325cae7286f5b3ed on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
-1 to b275eb5da150996f8df71e8a4877a2018a7a50ea on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
-1 to 0130b53610c1c1e126729e8ba2c93543a0aac5d2 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
-1 to 0c9bfd062853e40892ce7bc6ce397f50a2a05d1b on slc6_amd64_gcc481.

**Comment by jmonkevicius** [comment]
Wrong pull request

**Pull request closed without merging**
