### PR TITLE
Pede Revision 148: /tags/V04-03-03 "with Function not decreasing Fix"

### PR DESCRIPTION
**Pull request by skeshri**
Hi!

Please Consider this pull request.

It has already tested.

Thanks!

### CODE REVIEW

**Comment by ghellwig** [comment]
@skeshri, @degano: Shouldn't this PR go into  IB/CMSSW_7_4_X/stable ?

**Comment by ghost** [comment]
@ghellwig no, this is the branch we build the production release from. You can check here: https://github.com/cms-sw/cms-bot/blob/master/config.map#L25 where we mark production release with the variable "PROD_ARCH=1".

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by ghellwig** [comment]
@degano thanks for the clarification. This is indeed nice to know.

**Pull request merged**
