### PR TITLE
Update curl to 7.79.0

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar this is ready for review. Since it's a very low level package, it should probably be held for now.

**Comment by smuzaffar** [comment]
> @smuzaffar this is ready for review. Since it's a very low level package, it should probably be held for now.

right, lets keep this on hold and include it when we do pip/python update

**Comment by smuzaffar** [comment]
hold

**Comment by smuzaffar** [comment]
closing as it has been integrated via https://github.com/cms-sw/cmsdist/pull/7696

**Pull request closed without merging**
