### PR TITLE
Revert "Use a private pythia8 200pre1 tarball in cmsdist 73x with some o...

### PR DESCRIPTION
**Pull request by ghost**
Reverts cms-sw/cmsdist#1028

I missed it the first time but this PR actually breaks evtgen which requires to update its use of pythia API.
Example error:

```
EvtGenExternal/EvtPythiaEngine.cpp:240:40: error: 'class Pythia8::Event' has no member named 'daughterList'
std::vector<int> daugList = theEvent.daughterList(startInt);
```

### CODE REVIEW

**Comment by bendavid** [comment]
@degano, is this problem in the CMSSW interface or in evtgen itself?

**Comment by ghost** [comment]
@bendavid with evtgen itself I would say as it appear when compiling it as external.

**Comment by bendavid** [comment]
There are multiple evtgen specs in cmsdist, is it the one associated with
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_3_X/stable/evtgen.spec
?

**Comment by ghost** [comment]
Yes, the issue appear when explicitly building that one.

**Comment by bendavid** [comment]
Ok thanks, can you confirm whether there is any issue with tauolapp, which also declares pythia8 as a dependency?

**Comment by ghost** [comment]
tauolapp looks fine.

**Comment by bendavid** [comment]
Thanks,
This should be straightforward to solves on the pythia side.  Will try to get it taken care of together with the other needed header changes.  (ie 8.200pre2 coming soon with this addressed)

**Pull request merged**
