### PR TITLE
Get latest changes from pythia8 226 on 7_1_X

### LINKED ISSUE #4581: cms-externals/pythia8#13: Backport UncertaintyBand options from Pythia 8.230 to 8.226
A new Pull Request was created by  @intrepid42 (Markus Seidel) for branch cms/226.

Pull Request Reference: cms-externals/pythia8#13

@smuzaffar, @gudrutis, @mrodozov can you please review it and eventually sign? Thanks.

### PR DESCRIPTION
**Pull request by mrodozov**
Description: https://github.com/cms-externals/pythia8/pull/13
Resolves #4581

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
assign generators
pythia8 external tests finished. There are comparison difference. Please sign this PR if these are expected changes

**Comment by qliphy** [comment]
Please test

**Comment by qliphy** [comment]
(Sorry we overlooked this during holidays. The test results can not be found anyway, so redo it now)

**Comment by qliphy** [comment]
The comparison difference seems not much related to the change the PR makes. 

Adding also @mkirsano @intrepid42

**Comment by mseidel42** [comment]
Hi Qiang, I don't have experience with this, how to read it?

It seems DQM fails on `Data: /SingleMuon/CMSSW_9_0_0_pre4-90X_dataRun2_relval_v1_MRH_test_RelVal_sgMuPrpt2016B-v3-274199-274200/DQMIO`, which is maybe expected for a 71X release?

**Comment by qliphy** [comment]
@intrepid42 .  that (SingleMuon DQM) seems not related to Pythia8 change brought with this PR.

Generator part of [(WF 25202)](https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/Configuration/Generator/python/TTbar_13TeV_TuneCUETP8M1_cfi.py) test looks fine to me.  So probably this is already a good check.

Maybe we should also test several additional work flows.

**Comment by qliphy** [comment]
please test workflow 503, 504, 505, 506

**Comment by alberto-sanchez** [comment]
test seems ok.

**Comment by alberto-sanchez** [comment]
+1

**Comment by mseidel42** [comment]
I cannot find plots for those GEN workflows but the root files look reasonable 👍

**Comment by efeyazgan** [comment]
@intrepid42 do you think we can sign it now?

**Comment by mseidel42** [comment]
Hi Efe, yes, I don't see any Pythia failures, so it is good to go

**Comment by Andrej-CMS** [comment]
Dear @all ,
Are there any further studies required for this PR? It would be very useful to have the PSweights in 2016.
Kind regards,
Andrej

**Comment by qliphy** [comment]
@smuzaffar  We need "externals-approved" here.  Can you have a look and sign if possible?  We would like to have a patched 71X release for 2016 production with PSweights.  Thanks!

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@qliphy @efeyazgan @alberto-sanchez is this the backport into an older version of a new pythia8 feature not present in the version of 7_1_X?

**Comment by qliphy** [comment]
@fabiocos   Yes, exactly, as you can also see from https://github.com/cms-externals/pythia8/pull/13
this is to bring in 7_1_X the new pythia8 feature of UncertaintyBand options

**Comment by fabiocos** [comment]
+1

**Pull request merged**
