### PR TITLE
[10.2.X] RecoBTag-Combined: Update to retrained DeepDoubleB models

### PR DESCRIPTION
**Pull request by smuzaffar**
To include https://github.com/cms-data/RecoBTag-Combined/pull/13

### CODE REVIEW

**Comment by fabiocos** [comment]
@slava77 from your comment https://github.com/cms-sw/cmssw/pull/23033#issuecomment-393649652 I understand that https://github.com/cms-sw/cmssw/pull/23033 and this external PR are technically independent, but I assume they are not from the physics content point of view. So it would be useful to have an explicit "+1" to merge when the tests are done

**Comment by slava77** [comment]
> So it would be useful to have an explicit "+1" to merge when the tests are done

it sounds like the tests need to be redone because they never completed.
The full build approach we are using for external data files is excessive.

**Comment by slava77** [comment]
> it sounds like the tests need to be redone because they never completed.

nevermind, the "Comparison is ready" just never made it to this thread, while it shows up in https://github.com/cms-sw/cmssw/pull/23033#issuecomment-393739110

**Comment by slava77** [comment]
> So it would be useful to have an explicit "+1" to merge when the tests are done

+1 for reco
based primarily on the two plots in https://github.com/cms-sw/cmssw/pull/23033#issuecomment-393649652 . Jenkins comparisons show that changes are in the expected places.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
