### PR TITLE
Update eigen, get omitted commit

### PR DESCRIPTION
**Pull request by mrodozov**
See https://github.com/cms-externals/eigen-git-mirror/pull/4

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
@ericcano @fwyzard one test failed on ARM would you see if there's anything wrong I can see the test ran and it's saying it used `long double `
we've changed this recently:
https://github.com/cms-sw/cmssw/pull/33892
which includes Phi.h which includes deltaPhi and angle_units

**Comment by ericcano** [comment]
@mrodozov would it be possible to re-try (possibly against another IB)?

The logs for the test against `CMSSW_12_0_X_2021-06-02-1100/slc7_aarch64_gcc9` are do not seem to matching the expected output from the code (there is no assertion in the area where the logs stop).

The logs `CMSSW_12_0_X_2021-06-02-2300/slc7_ppc64le_gcc9` indicate memory allocation issues in CUDA and a files access error.

**Comment by mrodozov** [comment]
please test for CMSSW_12_0_X_2021-06-02-1100/slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
test parameters:
- release/arch = CMSSW_12_0_X_2021-06-03-2300/slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
is last night IB ok ? it's a full build and only 3 unit test (unrelated) fail in it

**Comment by mrodozov** [comment]
please test

**Comment by ericcano** [comment]
@mrodozov, yes `CMSSW_12_0_X_2021-06-03-2300` seems like a good baseline, thanks!

**Comment by fwyzard** [comment]
> ## Unit Tests
> 
> I found errors in the following unit tests:
> 
> ---> test PhiTest had ERRORS

Well, looks like it is reproducible ...

**Comment by ericcano** [comment]
Indeed, the test exists at the same place (from the output). But the function which stops is not expected to stop at that point due to an assertion or test. It is a 3 step performance measurement test which never fails, and it stops after the 1st step. We should have a block of 3 runs like here:
```
Test 3 versions big decre
Fast version after 1234567980 iterations is 4.398231250149003
Time diff is  600.706042838
Simple version after 1234567980 iterations is 4.398231250149003
Time diff is  220.472635812
ReduceRange after 1234567980 iterations is 4.398231250149003
Time diff is  470.251683834
```
but test for `big incr` abruptly stops here:
```
Test 3 versions big incr
Fast version after 1234567980 iterations is 1.884954057030583
Time diff is  547.5369472
```
The last log is from this line: https://cmssdt.cern.ch/lxr/source/DataFormats/GeometryVector/test/PhiTest.cc?v=CMSSW_12_0_X_2021-06-03-2300#0100

**Comment by ericcano** [comment]
The test turned out to take more that 1 hour in the current circumstances/load of the ARM build machine, and we timeout individual tests after one hour.
Both base IB and IB running against the new Eigen ran in similar times when run by hand:
```
...
Test 3 versions big incr
Fast version after 1234567980 iterations is 1.884954057030583
Time diff is  558.000620182
Simple version after 1234567980 iterations is 1.884954057030583
Time diff is  174.290960233
ReduceRange after 1234567980 iterations is 1.884954057030583
Time diff is  470.337560569

real    68m40.245s
user    68m38.962s
sys     0m0.229s
```
and
```
...
Test 3 versions big incr
Fast version after 1234567980 iterations is 1.884954057030583
Time diff is  554.9811655460001
Simple version after 1234567980 iterations is 1.884954057030583
Time diff is  172.712609137
ReduceRange after 1234567980 iterations is 1.884954057030583
Time diff is  470.612648628

real    68m51.581s
user    68m45.160s
sys     0m1.780s
```
respectively.

A PR has been proposed to reduce the test length to seconds: https://github.com/cms-sw/cmssw/pull/34029

**Comment by smuzaffar** [comment]
+externals
thanks @ericcano for checking this

**Comment by qliphy** [comment]
+1

**Pull request merged**
