### PR TITLE
Fix scipy numpy

### PR DESCRIPTION
**Pull request by smuzaffar**
- Fix lapack package to properly add its lib64 in to library path
- Fix numpy and scipy to disable ATLAS explicitly (otherwise it can pick it from system if available)

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
@smuzaffar 

fwiw, I had the same problem today, after adding your fixes, I got to a different one

Raise RpmInstallFailed (pkg, output)
RpmInstallFailed: Failed to install package py2-scikit-learn. Reason:
error: Failed dependencies:
        libcblas.so.3()(64bit) is needed by external+py2-scikit-learn+0.18.1-cms-1-1.x86_64

which I though I would get around by adding lapack to py2-scikit-learn requires list. but this seems not to be the solution

**Comment by smuzaffar** [comment]
@davidlange6 , yes scikit-learn also need to disable ATLAS. I am goin to update the PR soon (once locally build)

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
interesting... lets see how far this takes use - but ok, we should depend on ATLAS it seems...

**Comment by smuzaffar** [comment]
I tired building ATLAS but it fail as it found that cpu  throttling is enabled ( http://math-atlas.sourceforge.net/atlas_install/node5.html ) and disabling it is not trivial. So I decided to not build it

**Comment by davidlange6** [comment]
interesting....ok, will look tomorrow.

**Pull request merged**
