### PR TITLE
[12.4][BuildRules] back port multi-vec fixes

### PR DESCRIPTION
**Pull request by smuzaffar**
- https://github.com/cms-sw/cmssw-config/commit/8d8e331cb8b5987fea112657b7b6d624676e9ef4
- https://github.com/cms-sw/cmssw-config/commit/cce76729284f381166741d74d4ff4c429360b823
- use latest scram V3_00_48

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@cms-sw/orp-l2 , this is needed in order to build SKYLAKEAVX512 IBs for 12.4.X release cycle. These changes are already in 12.5.X and 12.6.X release cycles. so it should be safe to include these in 12.4.X.

**Comment by perrotta** [comment]
+1

**Pull request merged**
