### PR TITLE
Dummy WMCore to build python3

### PR DESCRIPTION
**Pull request by amaltaro**
Not sure this is the best approach, but there are 3 PRs that got merged today which did not do/build anything, so trying to build python3 here.

Complement to: https://github.com/cms-sw/cmsdist/pull/6377

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to b3917a091a97323cc4d200dc48a4e6695ce45616 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6381/test_b3917a0-20201106-232003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to c104add97ffda0081971768231a96e323eac458e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6381/test_c104add-20201107-114503.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
@amaltaro , Yes this is one way of of making sure that packages are properly built but the side effect is that when you deploy comp package then it will bring in also all the py3 packages too.

I would suggest to make `wmcorepy3-devtools` a `BuildRequires` in `comp.spec` for now. This will build the py3 packages but will not deploy them along with comp

**Comment by amaltaro** [comment]
Thanks Shahzad! I was testing it manually ;)

**Comment by amaltaro** [comment]
> I would suggest to make it a wmcorepy3-devtools a BuildRequires in comp.spec for now. This will build the py3 packages but will not deploy them along wioth comp

That's a great idea. I'll update it. But I think we never deploy the comp package, it;s really just a meta to build packages.

**Comment by muhammadimranfarooqi** [comment]
+1 to f15cb45a8cb836a6546fb33e1e91b682c226a72c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6381/test_f15cb45-20201107-155503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
I tried to build some of the python3 packages together with this change, but had some import errors like:
```
from pyexpat import *
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt
```

will try again once we have the latest python3 uploaded to the repository.

@muhammadimranfarooqi I checked the logs and I see that python3 gets properly built now. From my side this is ready to be merged.

**Comment by amaltaro** [comment]
Just to confirm, new python package has been also uploaded to the cmsrep:
external+python3+3.8.2-1-1.slc7_amd64_gcc630.rpm

Thanks Shahzad and Imran.

**Pull request merged**
