### PR TITLE
Update dd4hep to latest on master

### LINKED ISSUE #4557: DD4hep update
Please, update DD4hep to master branch to include bug fixes from:
https://github.com/AIDASoft/DD4hep/pull/468

Thanks

### PR DESCRIPTION
**Pull request by mrodozov**
Fixes #4557

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by ianna** [comment]
@mrodozov and @smuzaffar - is it in the IBs yet?

**Comment by smuzaffar** [comment]
@ianna , not now but it should be available in 11h IBs today.

**Pull request merged**
