### PR TITLE
Update Geant4 IB branch to 10.05.ref08

### PR DESCRIPTION
**Pull request by mrodozov**
As requested here: https://github.com/cms-externals/geant4/issues/40

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@civanch fixes for CMSSW are needed with this change

**Comment by civanch** [comment]
@mrodozov, we removed DataQuestionary in the master branch few days ago, if GEANT4 branch is already synchronized with the master than this new Geant4 will compile,

**Comment by mrodozov** [comment]
please test
@civanch if the PR with cmssw changes is already merged this should go fine.

**Comment by mrodozov** [comment]
abort 
@civanch we'll build the Geant4 IB with the latest commits from cmssw and then retry. the IB that we have doesn't have that changes

**Comment by civanch** [comment]
@mrodozov; #27943 was merged 2 days ago, likely we need force new GEANT4 branch.

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#27965

**Comment by smuzaffar** [comment]
cmssw compiles, lets get this in and build a full release

**Pull request merged**
