### PR TITLE
Update ROOT to 6.14

### PR DESCRIPTION
**Pull request by schneiml**
Tracking the change in latest CMSSW, commit 87811f7 / PR #4852.

This will be needed for DQMGUI once we have 6.14 in a CMSSW release.

FYI @rovere, @andrius-k, @kmaeshima, @jfernan2, @fioriNTU .

### CODE REVIEW

**Comment by h4d4** [comment]
-1 to ec1972f1dde5307ea9c9d7fd069c77e182d4ebd4 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4882/test_ec1972f-20190416-102006.log" target="_blank">here</a>.

**Comment by schneiml** [comment]
Looks like ROOT now requires numpy to build. I think we discussed before if it would be possible to import the entire root.spec from CMSSW, but it seems we have not. I'll try to just add numpy for now, not sure if that is enough.

**Comment by h4d4** [comment]
-1 to 5bd67ce96f3e58c108057aeff3c6eae1d18ec6d1 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4882/test_5bd67ce-20190416-120506.log" target="_blank">here</a>.

**Comment by schneiml** [comment]
Seems that did not do the trick, and now it is a rather opaque CMake message, if I read the log correctly. 

I could just import the file from CMSSW, would that work?
@h4d4 , @smuzaffar any hints on whether we can use the same root.spec for CMSWEB as for CMSSW?

**Comment by schneiml** [comment]
I imported the file from CMSSW. Not sure if it will work, but it's worth a try, I guess.

**Comment by h4d4** [comment]
-1 to 550498c93a1920bc79cdb46615fcf93674997bc1 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4882/test_550498c-20190416-171007.log" target="_blank">here</a>.

**Comment by schneiml** [comment]
Ok, looks like it is not that easy. But now I am out of ideas, and the build log does not help much this time...

**Comment by schneiml** [comment]
We need a working ROOT 6.14 in CMSWEB before CMSSW moves to it. Is there anybody we could ask for help?

**Comment by mrodozov** [comment]
@schneiml when you require something in the spec file you have to have it as a file, i.e. you need the https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/rootnext/lz4.spec file which is missing in this branch. Add this file from the link above to the PR and retry.

**Comment by schneiml** [comment]
@mrodozov thanks for the hint, let's try that.

**Comment by h4d4** [comment]
-1 to 7890fe612df74e0d5a5b97528a25ed8d119a2d7a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4882/test_7890fe6-20190423-113009.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to d506fb8bf92c57583eb679ef75663041e02130e5 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4882/test_d506fb8-20190423-120509.log" target="_blank">here</a>.

**Comment by schneiml** [comment]
Getting closer, I think. But now the build fails... I think I can't access the individual log files, can somebody have a look?

**Comment by mrodozov** [comment]
@h4d4 you are using pkgtools/cmsBuild to build your pkgs, correct ? would you let us know how can we build as the bot builds (maybe the command it executes) so that we build it locally until it starts building instead of committing minor changes here

**Comment by amaltaro** [comment]
@mrodozov this is where you should see all logs related to the latest build attemp:
amaltaro@vocms055:/build/amaltaro $ ls -lt /build/dmwmbld/srv/state/dmwmbld/builds/4882/

**Comment by mrodozov** [comment]
@amaltaro yes but in principle it would be easier/faster if one can retry it locally until it eventually builds.

**Comment by amaltaro** [comment]
This is what I've written down:
```
git clone -b V00-32-XX https://github.com/cms-sw/pkgtools.git
git clone git@github.com:cms-sw/cmsdist.git && cd cmsdist && git checkout comp_gcc630

### change your spec, and build it (or build the metapackage "comp", as below)
pkgtools/cmsBuild -c cmsdist --repository comp \
   -a slc7_amd64_gcc630 --builders 8 -j 4 --work-dir w \
   build comp
```

**Comment by smuzaffar** [comment]
@schneiml , https://github.com/cms-sw/cmsdist/pull/4941 should bring in root 6.14.
This PR can be closed in favor of https://github.com/cms-sw/cmsdist/pull/4941

**Pull request closed without merging**
