### PR TITLE
migration to lhapdf 5.9.0

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by smuzaffar** [comment]
Is it correct that LHAPDF 5.9.0 sources are now much bigger (5.4GB as compare to 3.1GB)?

**Comment by smuzaffar** [comment]
@mkirsano , Please update lhapdf-5.9.0-gzio.patch file, I get these errors when this patch is applied

```
+ cat /build/muz/rel/slc5/5.3.14.lhapdf/SOURCES/external/lhapdf/5.9.0/lhapdf-5.9.0-gzio
+ patch -s -p2 --fuzz=0
3 out of 3 hunks FAILED -- saving rejects to file src/eps09.f.rej
3 out of 3 hunks FAILED -- saving rejects to file src/wrapabkm09.f.rej
4 out of 4 hunks FAILED -- saving rejects to file src/wrapabkm09-lite.f.rej
```

**Comment by mkirsano** [comment]
Hello,
  How this is possible - it works for me. I checked again the pull 
request, seems that nothing is missing.
  Is it possible that you have lhapdf 5.8.5 cashed, so the patch is 
applied to it?
  As to the size - the size of PDFsets in 5.9.0 after gzipping I 
measured to be 4.1 GB. The code and libraries are small compared to this.
                               Cheers, Mikhail

**Comment by smuzaffar** [comment]
Here is what I did

```
git clone git@github.com:cms-sw/pkgtools.git
git clone git@github.com:cms-sw/cmsdist.git
cd cmsdist/
git checkout IB/CMSSW_5_3_X/stable
curl https://github.com/cms-sw/cmsdist/pull/285.patch | git am
git show --summary
cd ..
./pkgtools/cmsBuild --repo cms -a slc5_amd64_gcc462 -c cmsdist -j 20 -i w build lhapdf
```

and it yields the error I mentioned above. No I do not have 5.8.5 , here is what rpmbuild tried to do and failed

```
+ cd /build/muz/rel/slc5/5314.lhapdf/w/BUILD/slc5_amd64_gcc462/external/lhapdf/5.9.0
+ rm -rf lhapdf/5.9.0
+ gzip -dc /build/muz/rel/slc5/5314.lhapdf/w/SOURCES/external/lhapdf/5.9.0/lhapdf-5.9.0-src-sets.tgz
+ tar -xf -
+ cd lhapdf/5.9.0
+ chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #0 (lhapdf-5.9.0-32bit-on-64bit-recheck-workaround):'
Patch #0 (lhapdf-5.9.0-32bit-on-64bit-recheck-workaround):
+ cat /build/muz/rel/slc5/5314.lhapdf/w/SOURCES/external/lhapdf/5.9.0/lhapdf-5.9.0-32bit-on-64bit-recheck-workaround
+ patch -s -p2 --fuzz=0
+ touch src/gzio.inc
+ touch src/gzio.F
+ touch src/ftn_gzio.c
+ echo 'Patch #1 (lhapdf-5.9.0-gzio):'
Patch #1 (lhapdf-5.9.0-gzio):
+ cat /build/muz/rel/slc5/5314.lhapdf/w/SOURCES/external/lhapdf/5.9.0/lhapdf-5.9.0-gzio
+ patch -s -p2 --fuzz=0
3 out of 3 hunks FAILED -- saving rejects to file src/eps09.f.rej
3 out of 3 hunks FAILED -- saving rejects to file src/wrapabkm09.f.rej
4 out of 4 hunks FAILED -- saving rejects to file src/wrapabkm09-lite.f.rej
```

By the way, for 5.9.0 you are not applied lhapdf-data-5.8.5-gzio.patch, so should we drop Patch2: lhapdf-data-5.8.5-gzio line from the spec too?

about the size, I am talking about http://cern.ch/service-spi/external/MCGenerators/distribution/lhapdf/lhapdf-5.9.0-src-sets.tgz which is 5.4 GB now. As I have not build yet the rpm so I am not sure what will be the rpm size itself.

**Comment by mkirsano** [comment]
A, you are trying 5_3_X. OK, I will try this below
               Mikhail

**Comment by smuzaffar** [comment]
Looks like 

```
curl https://github.com/cms-sw/cmsdist/pull/285.patch | git am
```

is not doing what I thought it should do. Fetching cms-sw/refs/pull/285 and merging worked (at least patch seems to be applied properly). I am building lhapdf now.

cheers,

**Comment by smuzaffar** [comment]
OK, I am able to build it. By the way, now the RPM size is 4.1GB (it was 1.2GB for 5.8.5).

**Comment by mkirsano** [comment]
Hello, the size is the same as for me.
  I disabled the patch lhapdf-data-5.8.5-gzio, hoping that it is fixed 
in 5.9.0. If we don't get back to 5.8.5 it can be dropped. Anyway, it 
concerns only some documentation lines.
               Cheers, Mikhail

**Comment by bendavid** [comment]
This pull request is obsolete, can it be closed please?

**Pull request closed without merging**
