### PR TITLE
updated root from IB/CMSSW_10_1_X/gcc630 along with its deps

### PR DESCRIPTION
**Pull request by smuzaffar**
@h4d4, this PR sync root 6.10.09 from IB/CMSSW_10_1_X/gcc630.

### CODE REVIEW

**Comment by h4d4** [comment]
to 9a2c34859185da5b34ef9180c3d02d74e91ea3e4 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3789/test_9a2c348-20180303-102503.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
to 9a2c34859185da5b34ef9180c3d02d74e91ea3e4 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3789/test_9a2c348-20180305-122504.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
@h4d4 , are you using head of V00-30-XX ?

**Comment by rovere** [comment]
Ciao @smuzaffar 
I independently come up with the same patch to update root into comp_gcc630.
Using the tip of V00-30-XX I'm still building on vocms055, but everything seems to be working as expected.
@h4d4 please let us know your outcome.

**Comment by rovere** [comment]
@h4d4 DQMGUI will need to bump to 9.1.4 to support c++17 features used internally by ROOT.
I'll submit a PR once I verify that everything works ok.

**Comment by rovere** [comment]
#3804 on top to build DQMGUI against ROOT

**Comment by h4d4** [comment]
to 9a2c34859185da5b34ef9180c3d02d74e91ea3e4 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3789/test_9a2c348-20180306-175932.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
Hello @smuzaffar, 
I've been retriggered this PR but still the building testing fails, maybe I need to do an additional configuration in the build agent, please see my email reply, is so long to put here.

**Comment by BrunoCoimbra** [comment]
Hi guys! Sorry for stepping in.

I was helping Lina with this problem and I noticed a couple of links are broken according to the build logs:
http://heanet.dl.sourceforge.net/project/libjpeg-turbo/1.3.1/libjpeg-turbo-1.3.1.tar.gz (libjpeg-turbo)
http://heanet.dl.sourceforge.net/project/giflib/giflib-4.x/giflib-4.2.3.tar.bz2 (giflib)
In fact I can't wget them.

I'm wondering if Marco was able to build it before the links were broken and now he's just sourcing it from his private repository.
Do you think it's worth to replace those links and try to build it again?

Please feel free to ignore me if it doesn't make sense. :)

Cheers,
Bruno

**Comment by smuzaffar** [comment]
BrunoCoimbra, @h4d4 , guys you are not using the tip of pkgtools V00-30-XX. I am able to build root/dqmgui by cloneing pkgtools (default branch which is V00-30-XX) . What are the commands you run to build?

```
./pkgtools/cmsBuild -a slc7_amd64_gcc630 --repo comp -i w -j 10 build dqmgui
....
....
Creating directory /build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/external/libjpeg-turbo/1.3.1 if not existing.
Building libjpeg-turbo. Log can be found in /build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/external/libjpeg-turbo/1.3.1/log.
source /build/cmsbld/x/comp/w/slc7_amd64_gcc630/rpm-env.sh ; TMPDIR=/build/cmsbld/x/comp/w/tmp  rpmbuild  --buildroot /build/cmsbld/x/comp/w/tmp/BUILDROOT/96f0151d22890bb4f8f83fa7c1d026f9 -ba --define '_topdir /build/cmsbld/x/comp/w' --define "compiling_processes 10"  --define "cmscompilerv  630" --define "cmsos slc7_amd64" /build/cmsbld/x/comp/w/SPECS/external/libjpeg-turbo/1.3.1/spec >/build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/external/libjpeg-turbo/1.3.1/log 2>&1
Build successful.
(<function buildPackage at 0x1f35c80>, <Package name=libjpeg-turbo>, <scheduler.Scheduler object at 0x1fe2b50>) done
Trying to install the rpm package external+libjpeg-turbo+1.3.1 just built.
Checking local path dependency for rpm package external+libjpeg-turbo+1.3.1 just build.
Done
Creating directory /build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/lcg/root/6.10.09-comp if not existing.
Building root. Log can be found in /build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/lcg/root/6.10.09-comp/log.
source /build/cmsbld/x/comp/w/slc7_amd64_gcc630/rpm-env.sh ; TMPDIR=/build/cmsbld/x/comp/w/tmp  rpmbuild  --buildroot /build/cmsbld/x/comp/w/tmp/BUILDROOT/62bc8c15d15dbb3d8b69422d6089af65 -ba --define '_topdir /build/cmsbld/x/comp/w' --define "compiling_processes 10"  --define "cmscompilerv  630" --define "cmsos slc7_amd64" /build/cmsbld/x/comp/w/SPECS/lcg/root/6.10.09-comp/spec >/build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/lcg/root/6.10.09-comp/log 2>&1
Build successful.
(<function buildPackage at 0x1f35c80>, <Package name=root>, <scheduler.Scheduler object at 0x1fe2b50>) done
Trying to install the rpm package lcg+root+6.10.09-comp just built.
Checking local path dependency for rpm package lcg+root+6.10.09-comp just build.
Done
Creating directory /build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/cms/dqmgui/9.1.4-comp if not existing.
Building dqmgui. Log can be found in /build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/cms/dqmgui/9.1.4-comp/log.
source /build/cmsbld/x/comp/w/slc7_amd64_gcc630/rpm-env.sh ; TMPDIR=/build/cmsbld/x/comp/w/tmp  rpmbuild  --buildroot /build/cmsbld/x/comp/w/tmp/BUILDROOT/262c7bdb7af99cda6717cee7a217f689 -ba --define '_topdir /build/cmsbld/x/comp/w' --define "compiling_processes 10"  --define "cmscompilerv  630" --define "cmsos slc7_amd64" /build/cmsbld/x/comp/w/SPECS/cms/dqmgui/9.1.4-comp/spec >/build/cmsbld/x/comp/w/BUILD/slc7_amd64_gcc630/cms/dqmgui/9.1.4-comp/log 2>&1
Build successful.
(<function buildPackage at 0x1f35c80>, <Package name=dqmgui>, <scheduler.Scheduler object at 0x1fe2b50>) done
Nothing else to be done, exiting.
Trying to install the rpm package cms+dqmgui+9.1.4-comp just built.
Checking local path dependency for rpm package cms+dqmgui+9.1.4-comp just build.
Done
Trying to install the rpm package cms+dqmgui-webdoc+9.1.4-comp just built.
Checking local path dependency for rpm package cms+dqmgui-webdoc+9.1.4-comp just build.
Done
Requested to quit.
```

**Comment by h4d4** [comment]
to 9a2c34859185da5b34ef9180c3d02d74e91ea3e4 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3789/test_9a2c348-20180307-005504.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
@h4d4 , can you provide me the instruction how you build? Do you build with in docker container? could it be that container already has a pkgtools checkedout?

**Comment by h4d4** [comment]
@smuzaffar Sure.
I'm using CC7 build machine, 
It's the machine used to test the build of every PR that is committed to comp_gcc630 cmsdist branch, before merged it to comp_gcc630 cmsdist.

There is dmwmbld agent, it triggers each PR.
His build area is: /build/dmwmbld [1]
His  pkgtools is pointing to HEAD of V00-30-XX, on both directories when it's, those are[1]: bootstrap_gcc630/pktools and pkgtools

dmwmbld runs automatically, in order to test the building. In' this case I'm, not running the commands to build the RPMS by hand as when I used my private build area: /build/lijimene

Another thing, cmsdist local repository for the agent build area points only to comp_gcc630[2] branch, should be it pointing to IB/CMSSW_10_1_X/gcc630 HEAD too?

[1]
[dmwmbld@vocms055 dmwmbld]$ ls -l
total 108
-rw-r--r--.  1 dmwmbld zh 16358 Feb 15  2017 bootstrap-driver.spec
-rw-r--r--.  1 dmwmbld zh 26867 Feb 15  2017 bootstrap-driver.spec.cmssw
drwxr-xr-x.  7 dmwmbld zh  4096 Mar 27  2017 bootstrap_gcc630
drwxr-xr-x. 59 dmwmbld zh  4096 Mar 31  2017 cfg
drwxr-xr-x.  3 dmwmbld zh 20480 Mar  7 09:57 cmsdist
drwxr-xr-x.  2 dmwmbld zh  4096 Feb  1  2017 jenkins
-rw-r--r--.  1 dmwmbld zh     0 Oct 25 13:11 logBuild
-rw-r--r--.  1 dmwmbld zh 17196 Sep  5  2017 logUpload
 drwxr-xr-x.  6 dmwmbld zh  4096 Mar  5 12:15 pkgtools
drwxr-xr-x. 10 dmwmbld zh  4096 Mar 31  2017 srv
drwxr-xr-x. 16 dmwmbld zh  4096 Oct 25 13:12 w

[2]
[dmwmbld@vocms055 cmsdist]$ git branch
* comp_gcc630

**Comment by smuzaffar** [comment]
@h4d4 , I do not have access to vocms055 so can not check what is wrong there.
No, your cmsdist should not point to IB/CMSSW_10_1_X/gcc630. It is correctly pointing to comp_gcc630. Lets meet after the IT-CMs meeting to actually see what is wrong.

**Comment by h4d4** [comment]
@smuzaffar Yes please,  let's do it.

**Comment by rovere** [comment]
you are **NOT** using the HEAD of V00-30-XX
Please read [here](https://github.com/dmwm/deployment/blob/master/dmwmbld/build.sh#L33)
to see what version of pkgtool you are using while building.
Update that branch in that area and most likely you'll have a successful build.
I mean here:
/build/dmwmbld/srv/current/apps/pkgtools
where the last commit is 1+ year old and git status tells you are 19 commits behind the tip of the branch.

How this machinery is mixing HG tags and PKGTOOL is still a mystery to me but I gave it for granted that HTTP responsible know all the internal details.

**Comment by h4d4** [comment]
@rovere 
Thanks for pointing out this.
I've updated /build/dmwmbld/srv/current/apps/pkgt

waiting for the build test result.

**Comment by h4d4** [comment]
@smuzaffar Just in case. I've give acces to muzaffar for vocms055.

**Comment by h4d4** [comment]
+1 to 9a2c34859185da5b34ef9180c3d02d74e91ea3e4 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3789/test_9a2c348-20180307-112504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
@smuzaffar @rovere Marcos's findings was really ussefull.
The build test are passed.
I'm going to prepare the tag for deploy on testbed

**Pull request merged**
