### PR TITLE
upgrade pythia8 to 302

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
To be tested together with the PR CMSSW cms-sw/cmssw#29995

**Comment by smuzaffar** [comment]
@mkirsano , looks like `geneva` failed to build [a] with new pythia8 version

[a]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7765b8/6611/external/geneva/1.0-RC3-7765b8/log

**Comment by mkirsano** [comment]
The idea is to create a special release for extended tests

**Comment by mkirsano** [comment]
I finally managed to test geneva build. This test rebuilds openloops, which requires 30 GB of disk space! I confirm that geneva build fails. I suggest to temporarily exclude it for a special release.

**Comment by mkirsano** [comment]
+1

**Comment by smuzaffar** [comment]
@mkirsano , so I guess generators are ok with removal of `dire, vincia and geneva` tools?

**Comment by mkirsano** [comment]
dire and vincia are no more needed, they are included in pythia8. The removal of geneva is temporary, agreed with generators.

**Comment by silviodonato** [comment]
@smuzaffar is it ready to be merged?

**Comment by smuzaffar** [comment]
+externals
yes @silviodonato , it is ready to go in along with https://github.com/cms-sw/cmssw/pull/29995

**Comment by silviodonato** [comment]
+1

**Pull request merged**
