### PR TITLE
[ROOT 6-20] Get tag 6-20-06

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
the PR is fine this unit test is failing also in the IB
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_ROOT620_X_2020-06-07-0000/unitTestLogs/RecoTauTag/RecoTau#/220-220

**Comment by mrodozov** [comment]
abort
not this PR

**Comment by mrodozov** [comment]
+externals

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
hold
we will merge it once we have ROOT6.20 validation is all OK

**Comment by smuzaffar** [comment]
closing it in favor of https://github.com/cms-sw/cmsdist/pull/5951

**Pull request closed without merging**
