### PR TITLE
Downgrade HTCondor python bindings to 8.9.7

### PR DESCRIPTION
**Pull request by amaltaro**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to 25a0affd6cd01845764f1debfb09316d4a9960b8 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7453/test_25a0aff-20211116-224003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to 30e5e779ccda103a4ce1a30b791a80efca765104 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7453/test_30e5e77-20211116-231003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 747c7f0d35d7e378b26bc3b87695362339e1e96d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7453/test_747c7f0-20211116-233504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to cfff97bd810ba33fe775a10d2e9eb66a69757604 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7453/test_cfff97b-20211117-000503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
