### PR TITLE
New dasgoclient version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by vkuznet** [comment]
New dasgoclient fixes issue with McM requests (https://github.com/dmwm/DAS/issues/4295), adds CRIC data look-up and preliminary integration of DAS with Rucio data-service APIs.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by heitorPB** [comment]
Is there an estimative of when this new dasgoclient will be released in lxplus?

**Comment by vkuznet** [comment]
The build is done and usually it takes some time when new client appears on
cvmfs. If you need to speed-up the process you need to contact Shahzad and ask.

**Pull request merged**
