### PR TITLE
Update to CUDA 11.4.1

### PR DESCRIPTION
**Pull request by fwyzard**
Update to CUDA 11.4.1 (11.4.20210728):
  * CUDA runtime version 11.4.108
  * NVIDIA drivers version 470.57.02
  * cuDNN version 8.2.2.26

Add support for GCC 11 and clang 12.

See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html .

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
I expect building CMSSW may fail, so let's check that before testing on other architectures.

**Comment by fwyzard** [comment]
However it might be worth checking a GCC 11 build in parallel.

**Comment by fwyzard** [comment]
please test for CMSSW_12_1_X/slc7_amd64_gcc11

**Comment by fwyzard** [comment]
I forgot, we should retest with Alpaka 0.6.1

**Comment by smuzaffar** [comment]
please test
Alpaka 0.6.1 is merged

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for CMSSW_12_1_X/slc7_amd64_gcc11

**Comment by fwyzard** [comment]
please abort

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for CMSSW_12_1_X/slc7_amd64_gcc11

**Comment by fwyzard** [comment]
OK, I need to look into it in more detail.

**Comment by fwyzard** [comment]
I opened a bug report with NVIDIA along with a simplified test that reproduces the issue, and they confirmed that there is a bug affecting CUDA 11.3.0, 11.3.1, 11.4.0, 11.4.1.

NVCC fails to compiles constructs like
```c++
template<typename T>
void function(T argument)
{
    auto value(argument);
}
```

This should be fixed in CUDA 11.5.0, targeting some time around October.

**Comment by fwyzard** [comment]
@smuzaffar do you think it would be useful to have CUDA 11.4.1 just in the GCC 11 build ?

Given the bug, I would not want to move to it for the production and GCC 10 builds.

**Comment by smuzaffar** [comment]
@fwyzard , it will break the gcc11 IBs (as it fails to build externals)

**Comment by fwyzard** [comment]
Does it break only Alpaka / Cupla, or others as well ? Anyway, it will certainly break some GPU code in CMSSW. 
I do not mind **not** updating to 11.4.1, it's just a possibility to start exercising some GPU code.

**Comment by smuzaffar** [comment]
yes only `cupla` failed to build

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9af979/17496/cmsswtoolconf.log
```
* The action "build-cms+cmssw-tool-conf+50.0-6e47356e7295ee06e267d023af40b875" was not completed successfully because The following dependencies could not complete:
install-external+cupla+0.3.0-dev-801d32d3dcf5d9a19bd1534545be71f6
* The action "install-cms+cmssw-tool-conf+50.0-6e47356e7295ee06e267d023af40b875" was not completed successfully because The following dependencies could not complete:
build-cms+cmssw-tool-conf+50.0-6e47356e7295ee06e267d023af40b875
```

**Comment by smuzaffar** [comment]
may be for gcc11, remove cupla from cmssw-tool-conf and then we might be able to include it

**Comment by fwyzard** [comment]
There are new versions of alpaka (0.7.0) and cupla (0.3.0), let me see if they are compatible and work around the issue.

**Comment by fwyzard** [comment]
please test for CMSSW_12_1_X/slc7_amd64_gcc11 with cms-dist#7204

**Comment by fwyzard** [comment]
please test with #7204 for CMSSW_12_1_X/slc7_amd64_gcc11

**Comment by fwyzard** [comment]
From a standalone test, alpaka 0.7.0 and cupla 0.3.0 do work with CUDA 11.4 .

**Comment by smuzaffar** [comment]
comment like `please test with #7204` should start the test for production arch

**Comment by smuzaffar** [comment]
please test with #7204

**Comment by smuzaffar** [comment]
please test with #7204 for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test with #7204 for CMSSW_12_1_X/slc7_pcc64le_gcc9

**Comment by smuzaffar** [comment]
please test with #7204 for CMSSW_12_1_X/slc7_ppc64le_gcc9

**Comment by fwyzard** [comment]
@smuzaffar , keep in mind that we *do not* want to merge CUDA 11.4.x in the GCC 9 and GCC 10 builds.

**Comment by smuzaffar** [comment]
lets gets this in for GCC 11

**Pull request merged**
