### PR TITLE
Update G4 11.1.1, vecgeom 1.2.1, clhep 2.4.6 and G4-data

### PR DESCRIPTION
**Pull request by smuzaffar**
These are the changes needed to update Geant 4 to version `11.1.1`

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
hold

we need to wait for the validation results of Geant4/Geant4LTO builds

**Comment by civanch** [comment]
@smuzaffar , at the last PPD meeting April, 6, PdmV team confirmed that they approve validation campaign for 13_0_0_pre3_LTOVECGEOM, so this PR may be unhold.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
unhold

**Comment by civanch** [comment]
@smuzaffar , may be good time to merge it now? Next days we can react if a new problem appears.

**Comment by smuzaffar** [comment]
+externals

lets get this in then

**Pull request merged**
