### PR TITLE
Update fmt to 8.0.1

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test with cmssw#35286

**Comment by smuzaffar** [comment]
@iarspider , please use full repo name e.g cms-sw/cmssw#35286

**Comment by iarspider** [comment]
please test with cms-sw/cmssw#35286

**Comment by iarspider** [comment]
@smuzaffar do you know how this can be fixed:
```
@@@@ Running edmWriteConfigs for CalibTrackerSiPixelToolsPlugin
error: edmWriteConfigs caught an exception while loading a plugin library.
The executable will return success (0) so scram will continue,
but no cfi files will be written.
An exception of category 'PluginLibraryLoadError' occurred.
Exception Message:
unable to load /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-14-1100/tmp/slc7_amd64_gcc900/src/CalibTracker/SiPixelTools/plugins/CalibTrackerSiPixelToolsPlugin/libCalibTrackerSiPixelToolsPlugin.so because libfmt.so.7: cannot open shared object file: No such file or directory
```

libCalibTrackerSiPixelToolsPlugin.so was linked with old libfmt?

**Comment by smuzaffar** [comment]
first try to fix the build errors
```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-14-1100/src/L1Trigger/L1TMuonOverlap/src/GhostBuster.cc: In member function 'virtual std::vector<AlgoMuon> GhostBuster::select(std::vector<AlgoMuon>, int)':
  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-14-1100/src/L1Trigger/L1TMuonOverlap/src/GhostBuster.cc:16:8: error: 'sort' is not a member of 'std'; did you mean 'sqrt'?
    16 |   std::sort(refHitCands.rbegin(), refHitCands.rend());
      |        ^~~~
      |        sqrt
>> Compiling  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-14-1100/src/L1Trigger/L1TMuonOverlap/src/GoldenPattern.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-14-1100/src/L1Trigger/L1TMuonOverlap/src/GhostBusterPreferRefDt.cc: In member function 'virtual std::vector<AlgoMuon> GhostBusterPreferRefDt::select(std::vector<AlgoMuon>, int)':
  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-14-1100/src/L1Trigger/L1TMuonOverlap/src/GhostBusterPreferRefDt.cc:43:8: error: 'sort' is not a member of 'std'; did you mean 'sqrt'?
    43 |   std::sort(muonsIN.rbegin(), muonsIN.rend(), customLess);
      |        ^~~~
      |        sqrt
  gmake: *** [tmp/slc7_amd64_gcc900/src/L1Trigger/L1TMuonOverlap/src/L1TriggerL1TMuonOverlap/GhostBuster.cc.o] Error 1
```

**Comment by smuzaffar** [comment]
please test
hopefully now bot will deploy the cmssw under /cvmfs/cms-ci.cern.ch even if there are build errors

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#35286

**Comment by smuzaffar** [comment]
@iarspider , /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7309/18657/install.sh should be available soon ( it has been publish on cvmfs but will take 10-15 mins before it is visible)

**Comment by iarspider** [comment]
please test with cms-sw/cmssw#35286

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
