### PR TITLE
Geant4: updated to version 10.0.p02

### PR DESCRIPTION
**Pull request by nclopezo**
removed geant4-10.0.p01-dynamic-tls.patch
this is a backport of https://github.com/cms-sw/cmsdist/pull/831

### CODE REVIEW

**Comment by civanch** [comment]
@nclopezo, @ktf,

7_2_X is working fine with big plugin and geant4 10.0p02. Branch 7_2_GEANT10 does not work any more due to the same TLS problem we had in past:

> > Package src/BigProducts/Simulation built
> > Subsystem BigProducts built
> > ***_WARNING: Invalid tool blackhat. Please fix sherpa file.
> > ***_WARNING: Invalid tool sherpa_USE_ERR+=qd. Please fix sherpa file.
> > Local Products Rules ..... started
> > Local Products Rules ..... done
> > gmake[1]: Entering directory `/build/civanch/CMSSW_7_2_GEANT10_X_2014-07-22-0200'
> > @@@@ Refreshing Plugins:edmPluginRefresh
> > @@@@ Refreshing Plugins:edmPluginRefresh
> > Creating project symlinks
> > Done python_symlink
> > Compiling python modules cfipython/slc6_amd64_gcc481
> > Compiling python modules src/SimG4Core/Application/python
> > Compiling python modules python
> > Caught exception An exception of category 'PluginLibraryLoadError' occurred.
> > Exception Message:
> > unable to load lib/slc6_amd64_gcc481/pluginSimG4CoreApplicationPlugins.so because /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_2_GEANT10_X_2014-07-22-0200/external/slc6_amd64_gcc481/lib/libG4particles.so: cannot allocate memory in static TLS block
> >  will ignore pluginSimG4CoreApplicationPlugins.so and continue.

 **\* Break **\* segmentation violation
Caught exception An exception of category 'PluginLibraryLoadError' occurred.
Exception Message:
unable to load biglib/slc6_amd64_gcc481/pluginSimulation.so because biglib/slc6_amd64_gcc481/pluginSimulation.so: cannot allocate memory in static TLS block
 will ignore pluginSimulation.so and continue.

> > All python modules compiled

**Comment by civanch** [comment]
@nclopezo, @ktf  -dynamic-tls.patch is needed for this branch because here we are using Geant4 built in MT mode.

**Comment by nclopezo** [comment]
Hi Vladimir, 

The modifications introduced by the patch are already in the source code. That is why I removed it. However, I noticed that geant4.spec doesn't have:

<pre> 
-DGEANT4_BUILD_TLS_MODEL:STRING="global-dynamic"
</pre>

https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_2_X/geant10/geant4.spec

If I add it it should work now?

**Comment by civanch** [comment]
Hi David,

I think it will, it was the major requirement for G4 to be built in MT mode.

**Comment by nclopezo** [comment]
Hi Vladimir, 

I did it here https://github.com/cms-sw/cmsdist/pull/895

**Comment by ghost** [comment]
@civanch Is this PR stil necessary? Or can I close it?

**Comment by civanch** [comment]
@nclopezo, it was done, so should be closed.

**Comment by nclopezo** [comment]
wait, this was done for 7_2_X, if you need it for 7_1_X we can use this pr after discussing it in the ORP.

**Comment by civanch** [comment]
Yes, we are waiting for validation of 7_2_0_pre3 and it will take some time. However, technically PR is done and working for 7_2_X.

**Pull request closed without merging**
