### PR TITLE
fix couch authentication

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 5542727ee69ab6a4d484c27193fb4cf99d0d737e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4574/test_5542727-20181212-054004.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 9750f0380f669ddaadd728a0a413aa9f88b61224 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4574/test_9750f03-20181212-080504.log" target="_blank">here</a>.

**Comment by kdziedzi** [comment]
@ticoann If the the CRIC guys added the to_lower() on the name and the role, would that do the trick? I've checked the old code and that was the thing that was done with it.

**Comment by kdziedzi** [comment]
@ticoann 
To be exact, if this code was added for username and role: 
role = re.sub(r"[^a-z0-9]+", "-", role.lower())
name = re.sub(r"[^a-z0-9]+", "-", name.lower())
?

**Comment by ticoann** [comment]
@kdziedzi, Do you mean role and group? If that is the case, that should be fine. Thank you very much. 
It seems production agents are OK but I will double check.

**Comment by ticoann** [comment]
Since it is fixed in CRIC side, I am closing this one. Thanks Kate, Lina.

**Pull request closed without merging**
