### PR TITLE
[LLVM 10] Update LLVM to 10

### PR DESCRIPTION
**Pull request by mrodozov**
LLVM itself builds but codechecker and py2-dxr needs adjustments

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters
  - full_cmssw = true

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true
- release = CMSSW_11_1_CLANG_X
- pull_requests = https://github.com/cms-sw/cmssw/pull/29391

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort
oh dear

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by smuzaffar** [comment]
hold
looks like llvmlite is not yet ready for LLVM10.

**Comment by mrodozov** [comment]
it's not llvmlite . I have the fix for llvmlite, it's numba actually. latest numba works only with python3 
https://github.com/numba/numba/blame/1ea770564cb3c0c6cb9d8ab92e7faf23cd4c4c19/setup.py#L349
so now I'm trying to have one version for py2 and another for py3 (for numba) although the running python would be py2 and the llvmlite version that match the old numba (that will work for py2) doesn't work with latest llvm.

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
I'm getting this:
```
<stdin>:1: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.datamodel', please update to use 'numba.core.datamodel' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
```
so we might be able to patch oamap

**Comment by davidlange6** [comment]
OAMap looks to be superseded now. I’d suggest removing it.

On Apr 21, 2020, at 1:45 PM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm getting this:

<stdin>:1: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.datamodel', please update to use 'numba.core.datamodel' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.


so we might be able to patch oamap

**Comment by mrodozov** [comment]
removed

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
This PR https://github.com/cms-sw/cmssw/pull/29523
seems to be related, it broke also the gcc9 build

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by mrodozov** [comment]
@smuzaffar the test fails in the IB, maybe we can put this into DEVEL ?

**Comment by smuzaffar** [comment]
with LLVM10, there are many compilation warnings ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-547418/5818/build-logs/ ). We first need to fix these warning before we can integrate LLVM 10 in master IBs. I would suggest to integrate this along with cms-sw/cmssw#29391 for CLANG IBs and first get rid of all compilation warnings.

Any objections @silviodonato , @makortel ?

**Comment by makortel** [comment]
I agree integrating LLVM 10 first to CLANG IBs, fixing warnings, and then integrating it to master IBs is a good path forward.

**Comment by smuzaffar** [comment]
please test
lets re-run final test based on CLANG branches and merge it for CLANG IBs.

**Comment by smuzaffar** [comment]
Please test

**Comment by smuzaffar** [comment]
unhold

**Comment by smuzaffar** [comment]
+externals
lets get this in for CLANG IBs and fix the wranings before including this for master IBs

**Comment by silviodonato** [comment]
+1

**Comment by smuzaffar** [comment]
@mrodozov, some of these changes are independent of llvm 10. Can you open a PR to backport those changes for master branch? We will backport llvm 10 once all the warnings in CLANG IBs are clean.

**Comment by mrodozov** [comment]
sure I'll get what we can

**Pull request merged**
