### PR TITLE
[TF] Build with tensorflow_mkldnn_contraction_kernel=0

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/42444 for details

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for CMSSW_14_0_SKYLAKEAVX512_X

**Comment by gartung** [comment]
@smuzaffar is there a way to make this available as a stand alone install for IB's. I would like to be able to setup this version of tensorflow, then run profiling.

**Comment by smuzaffar** [comment]
@gartung , only trivial way to do it is to setup a dedicated IB. I will do it once https://github.com/cms-sw/cmsdist/pull/8972 is merged ( which allows to make `tensorflow_mkldnn_contraction_kernel` a configurable build option)

**Comment by smuzaffar** [comment]
closing in favor of https://github.com/cms-sw/cmsdist/pull/8972

**Comment by smuzaffar** [comment]
@gartung , CMSSW_14_0_MKLDNN0_X_2024-01-28-2300 IB is now available where TF is build with `tensorflow_mkldnn_contraction_kernel=0` option.

**Pull request closed without merging**
