### PR TITLE
Upgrade sqlalchemy to 1.1.4

### PR DESCRIPTION
**Pull request by ggovi**
The external package sqlalchemy is upgraded to version 1.1.4

The change is required to fix several problems recently identified, notably:
- Handling of stale connection in the pool
- handling of queries with long column names, including fully qualified columns

The patches in use for the current version 0.8.2 have been kept unchanged.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by ggovi** [comment]
@smuzaffar
Any suggestion on what is missing here?

**Comment by smuzaffar** [comment]
it was not able to download the source
The action "fetch-external+py2-sqlalchemy+1.1.4" was not completed successfully because Unable to download https://pypi.python.org/packages/source/S/SQLAlchemy/SQLAlchemy-1.1.4.tar.gz

**Comment by davidlt** [comment]
The correct link would be https://pypi.python.org/packages/ca/ca/c2436fdb7bb75d772d9fa17ba60c4cfded6284eed053a7274b2beb96596a/SQLAlchemy-1.1.4.tar.gz

**Comment by smuzaffar** [comment]
I created a PR for DEVEL IB here #2763 with the correct source url

**Comment by ggovi** [comment]
ok i've just realised that...  I changed the source.

**Comment by smuzaffar** [comment]
closing this PR in favour of #2767

**Pull request closed without merging**
