### PR TITLE
Adding new MariaDB version

### PR DESCRIPTION
**Pull request by jmonkevicius**
- Updated database from MySQL to MariaDB 10.0.12 version.
- Updated py2-mysqldb to newer 1.2.4b4 version.
- Updated  py2-mysqldb-setup.patch for correct py2-mysqldb working with new mysqldb version.
- Removed mysql.spec file
- Removed "required mysql " from crabserver.spec

It was tested only in SLC6 and pushed to comp_gcc481 branch.
It was tested also with SQLAlchemy 0.9.6 version [ https://github.com/cms-sw/cmsdist/pull/1029 ]. Not with 0.5.2 version.
It was tested also with cx_Oracle 5.1.3 version [ https://github.com/cms-sw/cmsdist/pull/1030 ]. Not with 5.1 version.

In WMAgent deployment case, before starting MariaDB services, need to change deployment file [ https://github.com/jmonkevicius/deployment/commit/fb33c9e12365d760b0ca27075d0fd5285df77503 ]. 
Reason: new version of database don't understand simbols "set-variable" . Seting my.cnf parameters at mariadb.spec file is not working because deployment script [  https://github.com/dmwm/deployment ] is overwriting this config file.
# 
- [Not resolved yet] Standart testing and validation of WMAgent from Justas was successful, but this MariaDB version gives warning after command 

" ./manage execute-agent wmagent-resource-control --add-all-sites --plugin=CondorPlugin --pending-slots=50 --running-slots=50 " -->

"
Adding T3_GR_IASA to the resource control db...
/data/srv/wmagent/0.9.95b-comp2/sw.pre.jmonkevi/slc6_amd64_gcc481/external/py2-sqlalchemy/0.9.6/lib/python2.6/site-packages/sqlalchemy/engine/default.py:435: Warning: Duplicate entry 'T3_GR_IASA' for key 'site_name'
cursor.execute(statement, parameters)
"
# .

@amaltaro @juztas @hufnagel @geneguvo

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to ea15ddb1b2d723115fceaae2799881f8c95d2002 on slc6_amd64_gcc481.

**Comment by amaltaro** [comment]
@geneguvo , hold this one please.
I noticed only now that we are dropping mysql RPM from cmsdist repo. Are we sure we want to take all these steps together (new sqlAlchemy, switch from mysql to maria, WMA in slc6)?
To be on the safe side, I would not remove mysql.spec from the repository.
@hufnagel and @ticoann , what do you think?

**Comment by geneguvo** [comment]
too late...

**Comment by hufnagel** [comment]
It's not like the file is gone, we can always restore it. I see no point in building mysql rpms if we aren't using them. Anyways I would find it more problematic to build two different packages that provide the same dependency, that just leads to problem. We either switch to MariaDB or we don't.

**Comment by ticoann** [comment]
Sorry I didn't know we are switching to MariaDB this time. Some of the WMAgent production machine still use mysql. I assume this is tested in Tie0, but I think we still need to test this with integration team.

**Comment by hufnagel** [comment]
@juztas tested it, we are about as ready as we are going to get with it. The whole SL6 builds will go through another validation phase, but I would like to get this in now so we don't validate twice, once now SL6 plus new SqlAlchemy plus old MySQL and then again later the same, just with MariaDB. Seems a waste of effort to me given that we already did a standalone WMAgent/MariaDB validation.

**Comment by juztas** [comment]
This is tested with current production wmagent version (0.9.95b-comp2) and small validation was done (3-4 workflows per each test). These test was done :

a) Validate new sqlAlchemy https://github.com/cms-sw/cmsdist/pull/1029 with old mysql; :+1
b) Validate new sqlAlchemy https://github.com/cms-sw/cmsdist/pull/1029 with oracle; :+1
c) Validate new sqlAlchemy https://github.com/cms-sw/cmsdist/pull/1029 with oracle + https://github.com/cms-sw/cmsdist/pull/1030 ; :+1
d) Validate new sqlAlchemy https://github.com/cms-sw/cmsdist/pull/1029 with MariaDB :+1

In all cases it was used wmagent version (0.9.95b-comp2). these patches was applied :
https://github.com/hufnagel/WMCore/commit/5f3ace855cda77488892e59410880f8a824e5997.patch
https://github.com/dmwm/WMCore/commit/9d8a5a6c20dc4acaca612a46f75d13c29083bbb5.patch

**Comment by ticoann** [comment]
Thanks, Justas for the info, is the test only on sl6? or sl5 as well?

**Comment by hufnagel** [comment]
SL5 stays on mysql, no point in upgrading that just to retire it a short while later. In fact, the SL5 builds don't get any of the updates (SqlAlchemy, py2-cx-oracle, MariaDB, py2-mysqldb).

**Comment by ticoann** [comment]
I see I got confused then. Thanks Dirk for clarifying.

**Pull request closed without merging**
