### PR TITLE
initalizing theQuickParticles with nullptr

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear all,
I made the changes that you proposed and the code did run locally (which it already did before).
I need a version to test it on crab.
Kind regards,
Andrej

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by Andrej-CMS** [comment]
Dear @all 
It would be nice to have a testable build of this for crab jobs.
Kind regards,
Andrej

**Comment by qliphy** [comment]
@smuzaffar, @gudrutis, @mrodozov   Would you please review and sign it?  We need to test if for Herwig7 asap.  Thanks!    

More details can be found in this ticket: https://its.cern.ch/jira/browse/CMSCOMPPR-5075

**Comment by mrodozov** [comment]
+externals

**Comment by mrodozov** [comment]
you'll need also the release manager to sign it, the near most IB would be today at 23:00. 
@fabiocos

**Comment by qliphy** [comment]
@fabiocos   Can you sign it thus we can have a IB to test Herwig7 requests?  

@Andrej-CMS may comment more, but the details can be found here:
https://its.cern.ch/jira/browse/CMSCOMPPR-5075

**Comment by fabiocos** [comment]
@qliphy this was merged 11 days ago...

**Comment by qliphy** [comment]
Ok, thanks.  I saw ORP still pending and misunderstood.

**Pull request merged**
