### PR TITLE
Geant4: added DGEANT4_BUILD_TLS_MODEL to cmake to make it work in MT mod...

### PR DESCRIPTION
**Pull request by nclopezo**
...e

### CODE REVIEW

**Comment by nclopezo** [comment]
I did a test build in my local environment and I didn't see the error:

<pre>
cannot allocate memory in static TLS block
</pre>

in /SimG4Core/Application anymore

**Comment by civanch** [comment]
Thanks! will check next IB.

**Comment by nclopezo** [comment]
Actually, I just started a CMSSW_7_2_GEANT10_X_2014-07-25-0900 IB 

So It should be ready during the afternoon.

**Comment by civanch** [comment]
@nclopezo, thanks, it is working properly.

**Pull request merged**
