### PR TITLE
Revert lhapdf to 6.4.0 but keep lhapdh_dataset 6.5.1c

### PR DESCRIPTION
**Pull request by smuzaffar**
See https://github.com/cms-sw/cmssw/issues/43526 for detail on this revert.

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- relval = 132.0
- enable = threading
- relval_threading = 132.0

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
I agree with this. revert. I would not be as simple as this to revert the sets.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
