### PR TITLE
upgrade ThePEG to the version patched in GENSER to work with lhapdf6

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
The additional patch in cmsdist fixes the problem (warning) about PDFsets.index not found

**Comment by ktf** [comment]
@degano can you test this?

**Comment by bendavid** [comment]
@mkirsano can you make the pull request for this also for 74x (since this is the current dev release)?

**Comment by ghost** [comment]
+1
Tested full compilation till cmssw-tool-conf.
Tested compilation of GeneratorInterface/ThePEGInterface vs it.

**Comment by bendavid** [comment]
+1

**Comment by ktf** [comment]
Closing this in favor of #1244.

**Pull request closed without merging**
