### PR TITLE
Herwig7 backport to 93x for 2017 production

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear all,
these are the externals required for the Herwig7interface in 9_3_X. Requested by GEN for the Fall17 MC production.
This superseeds Herwig++.

to be tested with: https://github.com/cms-sw/cmssw/pull/25484
Kind regards,
Andrej

### CODE REVIEW

**Comment by smuzaffar** [comment]
@Andrej-CMS , you missed qgraf.spec

**Comment by smuzaffar** [comment]
@Andrej-CMS , we are also missing -toolfile dependencies (of some of the newly added packages) in cmssw-tool-conf.

**Comment by smuzaffar** [comment]
please test

**Comment by kpedro88** [comment]
@Andrej-CMS,  @alberto-sanchez, @qliphy, @perrozzi, @efeyazgan:

Before we merge this and build the next 9_3_X, we want to make sure no incompatibilities or problems are introduced. A few questions:
1. As far as I can tell, these changes were originally merged into master back during 10_0_X. Have the new Herwig version and modified interfaces been used in central production successfully since then?
2. This PR also appears to change the MadGraph version. Is this acceptable for a 9_3_X backport? Will it cause any undesired differences for MC production?

**Comment by kpedro88** [comment]
@Andrej-CMS, @alberto-sanchez, @qliphy, @perrozzi, @efeyazgan: ping (please respond to the above questions so we can move forward)

**Comment by qliphy** [comment]
@kpedro88    About 1, we are waiting for Herwig Tune to be finalized before starting official production. But from private production and Reval test, it look fine.  More details can be found from [year end GEN report](https://indico.cern.ch/event/761409/contributions/3159834/attachments/1765548/2866907/2018-12-05_GENnews.pdf#page=10&zoom=auto,-56,401).

About question 2,  @Andrej-CMS  may comment more. But I think this only affect the Herwig7 internal matrix element generation.  As for standard MC production with MadGraph gridpack, we are using MadGraph as external (https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO), so not affected by here.

**Comment by Andrej-CMS** [comment]
Dear @qliphy and @kpedro88 

Question 1: There is for example this Hewig 7 request from Jet-MET which is already done https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_JME-RunIIFall18GS-00015

Question 2: As Qiang said, the MG5 here is only used by Hewig7 in CMSSW. For standalone MG5 gridpack production, the version in genproduction is used, which is not affected by the changes here.

**Comment by kpedro88** [comment]
@smuzaffar, @gudrutis, @mrodozov please sign

**Comment by smuzaffar** [comment]
+externals

**Comment by kpedro88** [comment]
+1

**Pull request merged**
