### PR TITLE
Added geant4 patch for decay of K0 and antiK0

### PR DESCRIPTION
**Pull request by civanch**
This is a clone of #3505, which was done for gcc630.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by mrodozov** [comment]
please test
i don't see the link to jenkins console neither results, so I'll try it again

**Comment by civanch** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
wrong arch.

**Pull request closed without merging**
