### PR TITLE
Tracker daq 4.2 gcc700

### PR DESCRIPTION
**Pull request by rgerosa**
With this PR, we have updated the tracker online source code to be compliant with gcc 7.0. This PR follows [0], which was merged in the gcc630 branch. With respect to the past, where a huge patch file with O(20k) lines was used to patch the tkonline code to compile under gcc7,  we have now produced a new tarball for the source code, as indicated in the spec file.

[0]https://github.com/cms-sw/cmsdist/pull/3709

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@rgerosa , looks like there are still some places left with throw(). Can you please fix these.

**Comment by rgerosa** [comment]
@smuzaffar, ah yes there were some "throw" calls left in the code which were not failing the compilation of tkonline itself. Should be solved now. The tarball has been updated so it does not require an update of the spec files.

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
