### PR TITLE
Split WMArchvie for python and go based specs

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
to ed99d7de9acc21ef0b31f8e8633205806f540041 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6212/test_ed99d7d-20200904-173003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Its failed.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , I fixed the issue (some clean-up of redundant wmcore stuff). Could you please re-trigger the build, I built it already in my local area and everything is fine now.

**Comment by muhammadimranfarooqi** [comment]
+1 to fc85e85dba765d3f3c0c1a0526cf23c75c44c7f3 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6212/test_fc85e85-20200904-183503.log" target="_blank">here</a>.

**Pull request merged**
