### PR TITLE
upgrade lhapdf pdf sets to 6.1.6a

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by govoni** [comment]
@davidlange6 this is urgently needed, to validate the pdfs to be used for the future Monte Carlo production

**Comment by davidlange6** [comment]
maybe someone should have raised that issue at the release meeting....

**Comment by govoni** [comment]
Hello David, I am sorry about that, I guess there might have been some miscommunication within the GEN group about it.
Is there any showstopper now?

**Comment by govoni** [comment]
are there any news on this?

**Comment by davidlange6** [comment]
Seems more systemic. Anyway, my notes from the last orp include a question of the validation status of this change (from 91x/92x) - is there a summary that can be linked to this PR?

**Comment by govoni** [comment]
What do you mean by validation? Maybe @mkirsano could clarify, since he was attending the meeting?
In the meanwhile, this sample is needed urgently for pdf validation: we want to produce some samples with the official CMS production chain and check differences wrt to the past. Not having these PRs merged is delaying the validation procedure for the future MC production.

**Comment by davidlange6** [comment]
> On May 8, 2017, at 10:03 AM, Pietro Govoni <notifications@github.com> wrote:
> 
> What do you mean by validation? Maybe @mkirsano could clarify, since he was attending the meeting?


validation that the as built, as distributed build is working as needed in 92x.

> In the meanwhile, this sample is needed urgently for pdf validation: we want to produce some samples with the official CMS production chain and check differences wrt to the past. Not having these PRs merged is delaying the validation procedure for the future MC production.
> 

then come to the meeting where these things are discussed as raise your issues....

**Comment by govoni** [comment]
validation that the as built, as distributed build is working as needed in 92x.
--> why is this a concern in 71X?

**Comment by davidlange6** [comment]
the idea is that the development release is used to check that things work to avoid propagating bugs into production releases...

**Comment by govoni** [comment]
everything was ok during the 91X tests, if I am not wrong. Isn't this enough?

**Comment by davidlange6** [comment]
what 91x tests do you refer to ? I don't mean the purely mechanical ones that likely don't test the new functionality in these pdf sets but some confirmation that the new pdf sets run in the expected way - nothing fancy

**Comment by govoni** [comment]
I fail to understand the situation here. We would like the pdfs to be integrated to use the cms software to test them, and you're asking me whether they've been tested?
The pdfs by themselves are tested by the pdf authors and some in CMS are looking at them with calculations, but for event generation we want to have them in the release so that we can make those tests.

**Comment by davidlange6** [comment]
the pdfs are integrated into cms software already (in the development release). 

So, event generation can be done (in fact, can be done in the release cycle for 2017 gen). Have some some basic checks been done on on this release (eg, to run GEN workflows that use the pdfs of interest) as to avoid a useless (or worse)  back port?

**Comment by govoni** [comment]
thanks for clarifying. I think that such tests can be done quickly, will let you have feedback soon.

**Comment by mkirsano** [comment]
@davidlange6, I made some basic physics tests of the new lhapdf sets by running internal tests of Pythia8Interface in 91X when I was preparing the pythia8 upgrade. After this exchange I extended them a bit, checking physical file sets, sets used through symbolic links, and new sets. The numbers are reasonable, within allowed limits.

**Comment by efeyazgan** [comment]
See https://indico.cern.ch/event/637354/contributions/2581688/attachments/1455691/2246653/pcgt_news_8_May_2017.pdf for comparisons with NNPDF3.1. w.r.t. NNPDF3.0 with ttbar events (slides 3-7)

**Comment by davidlange6** [comment]
thanks @mkirsano

**Pull request merged**
