### PR TITLE
Add tag for py3-dbs3-client

### PR DESCRIPTION
**Pull request by todor-ivanov**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to ebf29974964d53e02fdf7bbe794b4aae5521fa92 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6946/test_ebf2997-20210528-094503.log" target="_blank">here</a>.

**Comment by todor-ivanov** [comment]
test this

**Comment by muhammadimranfarooqi** [comment]
+1 to 4ab1fdea34ccb739edf3c65f716588d42ef648ca on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6946/test_4ab1fde-20210528-113003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
LGTM. Thanks Todor.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
