### PR TITLE
New dasgoclient version

### PR DESCRIPTION
**Pull request by vkuznet**
The new release brings support for Rucio production services, support for lumi dataset query, and profile measurements.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@vkuznet , please submit the Pr agains the default branch i.e. IB/CMSSW_11_1_X/master

**Comment by vkuznet** [comment]
@smuzaffar , I tried to use IB/CMSSW_11_1_X/master but my build fails with this:
```
pkg(s): dasgoclient-binary
upload:
Package cms+dasgoclient-binary+v02.02.06 requested.
This will bring in also the following packages:
external+gcc+7.0.0-cms3 (bec9481b39dd748704b2807bf1182734)
Starting to process package cms+dasgoclient-binary+v02.02.06
Checking if dasgoclient-binary is cached.
Package cms+dasgoclient-binary+v02.02.06 not found in repository. Queuing for build.
Dependencies for cms+dasgoclient-binary+v02.02.06: ['install-external+gcc+7.0.0-cms3', 'fetch-cms+dasgoclient-binary+v02.02.06']
Fetching sources for dasgoclient-binary
Starting to process package external+gcc+7.0.0-cms3
Checking if gcc is cached.
Package external+gcc+7.0.0-cms3 not found in repository. Queuing for build.
Dependencies for external+gcc+7.0.0-cms3: ['fetch-external+gcc+7.0.0-cms3']
Fetching sources for gcc
Error while downloading sources from github.com/gcc-mirror/gcc.git using git.

cd /afs/cern.ch/work/v/valya/builds/w700/tmp/tmpViEcjI/gcc-7.0.0 &&git init &&git pull --tags https://github.com/gcc-mirror/gcc.git refs/heads/gcc-8-branch &&git reset --hard 9cde2018638fdc5ad3da8afcd0d89a6c92ed6694 &&find . ! -path '*' -delete &&rm -rf .git .gitattributes .gitignore

resulted in:
Initialized empty Git repository in /afs/cern.ch/work/v/valya/builds/w700/tmp/tmpViEcjI/gcc-7.0.0/.git/
fatal: Couldn't find remote ref refs/heads/gcc-8-branch
Unexpected end of command stream
(<function fetchSources at 0x7f2a2e056d70>, <Package name=gcc>, <scheduler.Scheduler object at 0x7f2a2945ddd0>) done
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Done fetching git+https://github.com/dmwm/dasgoclient?obj=master/v02.02.06&export=dasgoclient&output=/dasgoclient.tar.gz
Done fetching git+https://github.com/dmwm/cmsauth?obj=master/e9fca92e3335252a5f71d8e6d09c64012f7d3c0c&export=github.com/dmwm/cmsauth&output=/cmsauth.tar.gz
Done fetching git+https://github.com/vkuznet/x509proxy?obj=master/c93f6cae85114060b3b65861ea8436e4e14c54a6&export=github.com/vkuznet/x509proxy&output=/x509proxy.tar.gz
Done fetching git+https://github.com/buger/jsonparser?obj=master/6bd16707875b997f7a60327f888a28a3d28cf8c2&export=github.com/buger/jsonparser&output=/jsonparser.tar.gz
Done fetching git+https://github.com/go-mgo/mgo?obj=v2/3f83fa5005286a7fe593b055f0d7771a7dce4655&export=gopkg.in/mgo.v2&output=/mgo.v2.tar.gz
Done fetching git+https://github.com/pkg/profile?obj=master/3a8809bd8a80f8ecfe4ee1b34b3f37194968617c&export=github.com/pkg/profile&output=/profile.tar.gz
Done fetching git+https://github.com/dmwm/das2go?obj=master/42146d6e1b6bd830a9ebe5d34532e1d2de7a7860&export=github.com/dmwm/das2go&output=/das2go.tar.gz
Done fetching git+https://github.com/sirupsen/logrus?obj=master/a3f95b5c423586578a4e099b11a46c2479628cac&export=github.com/sirupsen/logrus&output=/logrus.tar.gz
(<function fetchSources at 0x7f2a2e056d70>, <Package name=dasgoclient-binary>, <scheduler.Scheduler object at 0x7f2a2945ddd0>) done
Requested to quit.
* The action "build-external+gcc+7.0.0-cms3" was not completed successfully because The following dependencies could not complete:
fetch-external+gcc+7.0.0-cms3
* The action "install-cms+dasgoclient-binary+v02.02.06" was not completed successfully because The following dependencies could not complete:
build-cms+dasgoclient-binary+v02.02.06
* The action "install-external+gcc+7.0.0-cms3" was not completed successfully because The following dependencies could not complete:
build-external+gcc+7.0.0-cms3
* The action "final-job" was not completed successfully because The following dependencies could not complete:
fetch-external+gcc+7.0.0-cms3
build-external+gcc+7.0.0-cms3
* The action "fetch-external+gcc+7.0.0-cms3" was not completed successfully because Unable to download git+https://github.com/gcc-mirror/gcc.git?obj=gcc-8-branch/9cde2018638fdc5ad3da8afcd0d89a6c92ed6694&export=gcc-7.0.0&output=/gcc-7.0.0-9cde2018638fdc5ad3da8afcd0d89a6c92ed6694.tgz
* The action "build-cms+dasgoclient-binary+v02.02.06" was not completed successfully because The following dependencies could not complete:
install-external+gcc+7.0.0-cms3

lxplus734(23:52:52) builds > env | grep SCRAM_ARCH
SCRAM_ARCH=slc7_amd64_gcc700
```
So, which ARCH I need to use. Please advise.

**Comment by smuzaffar** [comment]
slc7_amd64_gcc820 ( https://github.com/cms-sw/cms-bot/blob/master/config.map#L1 )

**Comment by vkuznet** [comment]
closing this one in favor of https://github.com/cms-sw/cmsdist/pull/5736

**Pull request closed without merging**
