### PR TITLE
Add mxnet python package

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by smuzaffar** [comment]
@mrodozov , did you try using INSTALL_PYTHON_VERSIONS to directly build mxnet python ?

**Comment by mrodozov** [comment]
@smuzaffar ok I'll see both

**Comment by smuzaffar** [comment]
@mrodozov , I am fine with using pip package but just make sure that they do not install onnxrumtime libs or dependnecies e.g protobuf etc. If they are just installing python packages then I have no objections using these pip packages.

Can you build them locally and share the list of files they install?

**Comment by smuzaffar** [comment]
@mrodozov , you need to add py2-mxnet in python_tools.spec too

**Comment by mrodozov** [comment]
There is another PR to substitute this one

**Comment by mrodozov** [comment]
I'll check what onnxruntime installs because we might need the pip install there. 
Enabling the flag doesn't build the python part :/

**Pull request closed without merging**
