### PR TITLE
[10.6.X] Update RecoBTag-Combined to V01-01-03

### PR DESCRIPTION
**Pull request by mrodozov**
Description here: https://github.com/cms-data/RecoBTag-Combined/pull/21

### CODE REVIEW

**Comment by mrodozov** [comment]
Resolves: #4827 
Previous update is still open https://github.com/cms-sw/cmsdist/pull/4752

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
> Resolves #4827
> Previous update is still open #4752

ah, good point. 
~If~ Once the related CMSSW PR for this one is ready, we'll just proceed with this update and will supersede #4752.

**Comment by slava77** [comment]
I have recently signed the CMSSW PR (cms-sw/cmssw#26298) that needs this cmsdist PR.
Please proceed with merging when convenient.

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
