### PR TITLE
Update to ROCm 5.4.2 and TBB 2021.8.0

### PR DESCRIPTION
**Pull request by fwyzard**
Update ROCm to version 5.4.2.

Enable support for newer AMD GPUs:
  - AMD Instinct MI50/MI60 (gfx906)
  - AMD Instinct MI100/MI210/MI250 (gfx908)

Update TBB to version 2021.8.0.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard , as this is rebuilding TBB also so better to update TBB to v2021.8.0 too

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
OK... anyway, the only differences between TBB 2021.8.0-rc1 and 2021.8.0 are in a documentation file.

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard , `hipcc` generates a lot of tmp files under `/tmp` directory. I tried to add `-fno-temp-file` flag but it still does create temp files. Do you have any idea how to tell it to either not create temp files or create them under `cmssw/tmp/src/package` directory?

**Comment by fwyzard** [comment]
would it be OK to create the temporary files and _leave_ them there, until they are deleted by hand ?

**Comment by fwyzard** [comment]
@smuzaffar , if we add `-save-temps=obj` the temporary files _should_ be created in the same directory as the target files, _e.g._ under `tmp/el8_amd64_gcc11/src/HeterogeneousTest/ROCmDevice/plugins/HeterogeneousTestROCmDevicePlugins/`.

**Comment by smuzaffar** [comment]
I noticed that setting TMPDIR to `$CMSSW_BASE/tmp/$SCRAM_ARCH` works and `hipcc` create temp files under cmssw tmp area. I think we can update build rules to explicitly set TMPDIR to point to the package tmp directory.

Create temp files under `/tmp` fills up the disk on our build (and lxplus) nodes , so I would like to avoid this.

**Comment by smuzaffar** [comment]
> @smuzaffar , if we add `-save-temps=obj` the temporary files _should_ be created in the same directory as the target files, _e.g._ under `tmp/el8_amd64_gcc11/src/HeterogeneousTest/ROCmDevice/plugins/HeterogeneousTestROCmDevicePlugins/`.

ah ok, thanks. I am testing it now

**Comment by fwyzard** [comment]
However, I do not know if that may create problems during concurrent builds (`scram b -j`), as some files seem to have pretty generic names, like `a.out-hip-amdgcn-amd-amdhsa-gfx900`.

**Comment by fwyzard** [comment]
> I noticed that setting TMPDIR to `$CMSSW_BASE/tmp/$SCRAM_ARCH` works and `hipcc` create temp files under cmssw tmp area. I think we can update build rules to explicitly set TMPDIR to point to the package tmp directory.

I think this might be a better solution - maybe even use `TMPDIR=$CMSSW_BASE/tmp/$SCRAM_ARCH/some/target/specific/dir` to keep them per-package.

**Comment by fwyzard** [comment]
By the way, can we make any further changes in a separate PR ?
If it doesn't break things, I'd like to merge this one so I can move forward with the CMSSW part...

**Comment by smuzaffar** [comment]
hopefully current changes should not break any thing in cmssw as nothing depends on rocm in cmssw . Although we can make change here but that means restarting the PR tests so I would suggest to lets get this in once current tests are done (pr tests are already building cmssw now). 

The change for `TMPDIR` for `hipcc` needs to go in `cmssw-config` and I will open a separate PR for that

**Comment by smuzaffar** [comment]
@fwyzard , do we have rocm distributions for SLC7, RH9?

**Comment by fwyzard** [comment]
We have them for RHEL7 under `/cvmfs/patatrack.cern.ch/externals/x86_64/rhel7/amd/`.

We have them for RHEL9 under `/cvmfs/patatrack.cern.ch/externals/x86_64/rhel9/amd/` starting from ROCm 5.3.0, which was the first to be released for this architecture.

**Comment by fwyzard** [comment]
@smuzaffar if on a CMSSW PR I ask the bot to `please test with cms-sw/cmsdist#8273`, will it rebuild the externals from scratch or reuse them from here ?

**Comment by fwyzard** [comment]
> `---> test testTriggerMonitors had ERRORS`

looks pretty much unrelated ?

**Comment by fwyzard** [comment]
@smuzaffar can we merge this, or should I try to rerun the tests ?

**Comment by smuzaffar** [comment]
+externals
 looks good, the unit test failure is not related to this change.

**Pull request merged**
