### PR TITLE
Add Zstandard library to externals

### LINKED ISSUE #4947: addind Zstandard library
Zstandard is a fast compression library which outperforms zlib (gzip) in compression speed with comparable compression factor.

I recently presented benchmarks, showing slight improvement for HLT (RAW) payloads, here (slides 6-7 in particular):
https://indico.cern.ch/event/818796/contributions/3421318/attachments/1838786/3018173/compression_CMSSW_update2.pdf

I would therefore suggest to add it to the CMS distribution. Depending on this, a CMSSW PR isbeing prepared to provide Zstandard (as well as LZMA) compression option with all Streamer output modules as well as readers in the Streamer input source. Those changes are currently in the branch:
https://github.com/smorovic/cmssw/tree/zstd-106X

Latest version of the library sources is available here:
https://github.com/facebook/zstd/releases/download/v1.4.0/zstd-1.4.0.tar.gz

I found two possibilities to build only the library sources without executables:

a) regenerate makefiles with Cmake and use custom options:

cmake build/cmake -DZSTD_BUILD_CONTRIB:BOOL=OFF -DZSTD_BUILD_STATIC:BOOL=OFF -DZSTD_BUILD_TESTS:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DZSTD_BUILD_PROGRAMS:BOOL=OFF -DZSTD_LEGACY_SUPPORT:BOOL=OFF -DCMAKE_INSTALL_PREFIX:STRING=/usr -DCMAKE_INSTALL_LIBDIR:STRING=lib -Dzstd_VERSION:STRING=1.4.0

make DESTDIR=%i install

b) use existing Makefile from lib directory - this in addition to "a)" also builds the static library:
cd lib/
make ZSTD_LEGACY_SUPPORT=OFF DESTDIR=%i install

Best regards,
Srecko Morovic

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #4947

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc700

**Comment by smuzaffar** [comment]
@mrodozov , you also need to add the dependency in cmssw-tool-conf otherwise PR tests are not going to build it

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
