### PR TITLE
[llvm] Update to version 18.1.6

### PR DESCRIPTION
**Pull request by smuzaffar**
Updating LLVM version to 18.1.6

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- pull_request = https://github.com/cms-sw/cmssw/pull/45034
- skip_tests = static,header

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
@gartung , I am testing llvm 18.1.6 and it failed due to cms checker.
```
external/llvm/18.1.6-8bc7be74528ffeea7b2f711cb6c15f6b/llvm-18.1.6-0a498c5f36995dfa2810d831f7e42804003a3672/clang/include/clang/AST/../Basic/Attr.td:734:57: error: Expected a class name, got 'C2x'
  let Spellings = [ CXX11<"cms","thread_safe", 200809>, C2x<"cms", "thread_safe"> ];                                                        ^
```

Can you please look in to this and provide a fix for https://github.com/cms-externals/llvm-project/tree/cms/release/18.x/1118c2e

**Comment by smuzaffar** [comment]
please test with cms-externals/llvm-project#14 for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
@makortel , new clang 18 shows a lot of new warnings [a]. Also clang-format now also proposes [many fixes](https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_14_1_CLANG_X_2024-05-27-2300/1/code-format.patch) like [b]. 

I would suggest to merge this for CLANG IB and start fixing the warnings and apply the code-format changes. Once CLANG IB is clean then we can integrate it in normal master IBs. What do you think?


[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b8de6/39569/build-logs/
```
      3  'get_temporary_buffer<trackerTFP::State *>' is deprecated [-Wdeprecated-declarations]
      3  'get_temporary_buffer<TrackWithHistory *>' is deprecated [-Wdeprecated-declarations]
      3  'get_temporary_buffer<Trajectory *>' is deprecated [-Wdeprecated-declarations]
      6  'get_temporary_buffer<TrajectoryMeasurement>' is deprecated [-Wdeprecated-declarations]
      6  'get_temporary_buffer<unsigned int>' is deprecated [-Wdeprecated-declarations]
      6  'get_temporary_buffer<unsigned long>' is deprecated [-Wdeprecated-declarations]
      6  'get_temporary_buffer<unsigned short>' is deprecated [-Wdeprecated-declarations]
      3  implicitly-declared 'Eigen::Transpositions<5, 5, int>::Transpositions(const Eigen::Transpositions<5, 5, int>&)' is deprecated [-Wdeprecated-copy]
     33  optimization flag '-funroll-all-loops' is not supported [-Wignored-optimization-argument]
      3  size of symbol `pyint4_' changed from 6800 in tmp/el8_amd64_gcc12/src/GeneratorInterface/HijingInterface/src/GeneratorInterfaceHijingInterface/hipyset1.35.f.o to 22000 in /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_1_CLANG_X_2024-05-27-2300/lib/el8_amd64_gcc12/libGeneratorInterfaceCore.so
     15 src/DataFormats/HcalRecHit/test/test_hcal_reco.cu(22): warning #177-D: variable "info" was declared but never referenced
     18 src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CalorimeterDefinitions.h(108): warning #68-D: integer conversion resulted in a change of sign
     60  'unary_function<const boost::detail::multi_array::extent_range<long, unsigned long> &, long>' is deprecated [-Wdeprecated-declarations]
     60  'unary_function<const boost::detail::multi_array::extent_range<long, unsigned long> &, unsigned long>' is deprecated [-Wdeprecated-declarations]
     36  unnecessary parentheses in declaration of 'assert_arg' [-Wparentheses]
     36  unnecessary parentheses in declaration of 'assert_not_arg' [-Wparentheses]
    699  use of infinity is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
    150  use of NaN is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
     18  using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
   4281  variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
      3  variable 'parentName' is uninitialized when used within its own initialization [-Wuninitialized]
      3  variable 'sumwt2' set but not used [-Wunused-but-set-variable]
```

[b] https://cmssdt.cern.ch/SDT/jenkins-artifacts/jenkins-test-code-format/CMSSW_14_1_CLANG_X_2024-05-27-2300/1/code-format.patch
```
--- a/Alignment/CocoaFit/interface/FittedEntriesManager.h
+++ b/Alignment/CocoaFit/interface/FittedEntriesManager.h
@@ -16,8 +16,8 @@
 class FittedEntriesManager {
 public:
   //---------- Constructors / Destructor
-  FittedEntriesManager(){};
-  ~FittedEntriesManager(){};
+  FittedEntriesManager() {};
+  ~FittedEntriesManager() {};
   static FittedEntriesManager* getInstance();
   void AddFittedEntriesSet(FittedEntriesSet* fents);
   void MakeHistos();

--- a/Alignment/APEEstimation/plugins/ApeEstimator.cc
+++ b/Alignment/APEEstimation/plugins/ApeEstimator.cc
@@ -128,8 +128,8 @@ public:

 private:
   struct PositionAndError2 {
-    PositionAndError2() : posX(-999.F), posY(-999.F), errX2(-999.F), errY2(-999.F){};
-    PositionAndError2(float x, float y, float eX, float eY) : posX(x), posY(y), errX2(eX), errY2(eY){};
+    PositionAndError2() : posX(-999.F), posY(-999.F), errX2(-999.F), errY2(-999.F) {};
+    PositionAndError2(float x, float y, float eX, float eY) : posX(x), posY(y), errX2(eX), errY2(eY) {};
     float posX;
     float posY;
     float errX2;
```

**Comment by iarspider** [comment]
Most of these warnings are easy to fix:

```
      3  'get_temporary_buffer<trackerTFP::State *>' is deprecated [-Wdeprecated-declarations]
      3  'get_temporary_buffer<TrackWithHistory *>' is deprecated [-Wdeprecated-declarations]
      3  'get_temporary_buffer<Trajectory *>' is deprecated [-Wdeprecated-declarations]
      6  'get_temporary_buffer<TrajectoryMeasurement>' is deprecated [-Wdeprecated-declarations]
      6  'get_temporary_buffer<unsigned int>' is deprecated [-Wdeprecated-declarations]
      6  'get_temporary_buffer<unsigned long>' is deprecated [-Wdeprecated-declarations]
      6  'get_temporary_buffer<unsigned short>' is deprecated [-Wdeprecated-declarations]
```
Replace with `new` or `std::unique_ptr`

```
      3  implicitly-declared 'Eigen::Transpositions<5, 5, int>::Transpositions(const Eigen::Transpositions<5, 5, int>&)' is deprecated [-Wdeprecated-copy]
``` 
Is in external package, we should report it to Eigen devs

```
     33  optimization flag '-funroll-all-loops' is not supported [-Wignored-optimization-argument]
```
Clang only supports `funroll-loops`. We can modify `TrackingTools/KalmanUpdators/BuildFile.xml` to use different flags for clang and gcc.

```
      3  size of symbol `pyint4_' changed from 6800 in tmp/el8_amd64_gcc12/src/GeneratorInterface/HijingInterface/src/GeneratorInterfaceHijingInterface/hipyset1.35.f.o to 22000 in /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_1_CLANG_X_2024-05-27-2300/lib/el8_amd64_gcc12/libGeneratorInterfaceCore.so
```
@smuzaffar has suggested that this warning is harmless (Fortran COMMON blocks are known to change size), so maybe we can disable it?

```
     15 src/DataFormats/HcalRecHit/test/test_hcal_reco.cu(22): warning #177-D: variable "info" was declared but never referenced
```
Remove unused variable

```
     18 src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CalorimeterDefinitions.h(108): warning #68-D: integer conversion resulted in a change of sign
```
Probably change [this line](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CalorimeterDefinitions.h#L108) to read `return static_cast<uint32_t>(-1);`?

```
     60  'unary_function<const boost::detail::multi_array::extent_range<long, unsigned long> &, long>' is deprecated [-Wdeprecated-declarations]
     60  'unary_function<const boost::detail::multi_array::extent_range<long, unsigned long> &, unsigned long>' is deprecated [-Wdeprecated-declarations]
     36  unnecessary parentheses in declaration of 'assert_arg' [-Wparentheses]
     36  unnecessary parentheses in declaration of 'assert_not_arg' [-Wparentheses]
```
These come from Boost

```
    699  use of infinity is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
    150  use of NaN is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
```
We are building cmssw with `-ffast-math`, which sets (among other flags) `-ffinite-math-only`, allowing compiler to assume all floating-point numbers will be finite (no NaNs or infinities), but some functions explicitly return `std::numeric_limits<float>::infinity` and `std::numeric_limits<float>::quiet_NaN`. We can try adding `-fno-finite-math-only` flag and checking if that hurts performance or not.

```
     18  using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
      3  variable 'parentName' is uninitialized when used within its own initialization [-Wuninitialized]
      3  variable 'sumwt2' set but not used [-Wunused-but-set-variable]
```
Already fixed.

```
   4281  variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
```
This means that code like
```cpp
bool used[n];
```

is not a valid ISO C++ code. We can either silence this warning, or replace all such instances with `std::vector`s
```cpp
std::vector<bool> used(n);
```

**Comment by iarspider** [comment]
See also [this article](https://simonbyrne.github.io/notes/fastmath/) about dangers and benefits of `-ffast-math`

**Comment by makortel** [comment]
> ```
> 18 src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CalorimeterDefinitions.h(108): warning #68-D: integer conversion resulted in a change of sign
> ```
> 
> Probably change [this line](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CalorimeterDefinitions.h#L108) to read `return static_cast<uint32_t>(-1);`?

I'd say returning `std::numeric_limits<uint32_t>::max()` would be easier to understand.

> ```
>     699  use of infinity is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
>     150  use of NaN is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
> ```
> 
> We are building cmssw with `-ffast-math`, which sets (among other flags) `-ffinite-math-only`, allowing compiler to assume all floating-point numbers will be finite (no NaNs or infinities), but some functions explicitly return `std::numeric_limits<float>::infinity` and `std::numeric_limits<float>::quiet_NaN`. We can try adding `-fno-finite-math-only` flag and checking if that hurts performance or not.

We have [`edm::isNotFinite()`](https://github.com/cms-sw/cmssw/blob/master/FWCore/Utilities/interface/isFinite.h) to be used with `-ffast-math`, that we are suggesting instead of `std::isinf()` and `std::isnan()` in the static analyzer.

(disallowing `-ffast-math`, which would have many benefits, would need to be a discussion separate from this PR)

> ```
>   4281  variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
> ```
> 
> This means that code like
> ```c++
> bool used[n];
> ```
> is not a valid ISO C++ code. We can either silence this warning, or replace all such instances with `std::vector`s
> 
> ```c++
> std::vector<bool> used(n);
> ```

Moving away from VLAs (which would have its benefits) would need to be a separate discussion. See https://github.com/cms-sw/cmssw/issues/44937 for some recent discussion. Maybe in some places the cost of dynamic memory allocation is negligible, but there are places where it has (or had) noticeable performance impact.

**Comment by iarspider** [comment]
@makortel 

> We have [`edm::isNotFinite()`](https://github.com/cms-sw/cmssw/blob/master/FWCore/Utilities/interface/isFinite.h) to be used with `-ffast-math`, that we are suggesting instead of `std::isinf()` and `std::isnan()` in the static analyzer.

`clang` is not complaining about `std::isnan` or `std::isinf` checks, but about explicitly using `std::numeric_limits<float>::infinity` and `std::numeric_limits<float>::quiet_NaN`, see e.g. [ElectronSeed](https://github.com/cms-sw/cmssw/blob/master/DataFormats/EgammaReco/interface/ElectronSeed.h#L115-L122)

```cpp
    void setNegAttributes(const float dRZ2 = std::numeric_limits<float>::infinity(),
                          const float dPhi2 = std::numeric_limits<float>::infinity(),
                          const float dRZ1 = std::numeric_limits<float>::infinity(),
                          const float dPhi1 = std::numeric_limits<float>::infinity());
    void setPosAttributes(const float dRZ2 = std::numeric_limits<float>::infinity(),
                          const float dPhi2 = std::numeric_limits<float>::infinity(),
                          const float dRZ1 = std::numeric_limits<float>::infinity(),
                          const float dPhi1 = std::numeric_limits<float>::infinity());
```

**Comment by makortel** [comment]
> > We have [`edm::isNotFinite()`](https://github.com/cms-sw/cmssw/blob/master/FWCore/Utilities/interface/isFinite.h) to be used with `-ffast-math`, that we are suggesting instead of `std::isinf()` and `std::isnan()` in the static analyzer.
> 
> `clang` is not complaining about `std::isnan` or `std::isinf` checks, but about explicitly using `std::numeric_limits<float>::infinity` and `std::numeric_limits<float>::quiet_NaN`

Ah, ok. Maybe we should replace such comparisons as well with `edm::isNotFinite` (under the assumption we continue to use `-ffast-math`.

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
looks good, lets get this in next CLANG IB

**Pull request merged**
