### PR TITLE
Attempt to fix compilation warnings and optimize usage of VecGeom

### PR DESCRIPTION
**Pull request by civanch**
Currently in any local compilation there is a warning related to VecGeom and Geant4:

warning: "G4GEOM_USE_USOLIDS" redefined
   34 | #define G4GEOM_USE_USOLIDS
<command-line>: note: this is the location of the previous definition

There is no run time problems but this warning means some inconsistency of compilation options.

This PR is an attempt to remove it and also to remove G4CutTubs problem within the same version of VecGeom 1.1.18

### CODE REVIEW

**Comment by civanch** [comment]
@smuzaffar , if this PR will be OK it may substitute #7735

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , I see that SimG4CMS/Calo/plugins/BuildFile.xml does not have explicit
geant4core. It may get it indirectly.... but build fails in this plugin. Should it be added?

**Comment by smuzaffar** [comment]
@civanch , I see that https://github.com/cms-sw/cmssw/blob/master/SimG4CMS/Calo/plugins/CaloSteppingAction.cc#L266-L267 we try to access `G4Trap::GetZHalfLength()` but in `libG4geometry.so` there is no G4Trap but there is `G4UTrap::GetZHalfLength() const`. This is the reason we have these link issues.

**Comment by civanch** [comment]
@smuzaffar , I step back from geant4.spec change.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
this is for special G4VECGEOM IBs

**Pull request merged**
