### PR TITLE
Update the tag of RecoTracker-FinalTrackSelectors

### PR DESCRIPTION
**Pull request by mrodozov**
Description:
dzPVClosest values were clamped to +-2mm to ensure correct performance with particleGun type tracks.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by smuzaffar** [comment]
@slava77 , are the deleted files here https://github.com/cms-data/RecoTracker-FinalTrackSelectors/pull/3/files already used in cmssw? If not then we can merge this PR

**Comment by slava77** [comment]
On 2/1/18 10:34 AM, Malik Shahzad Muzaffar wrote:
> @slava77 <https://github.com/slava77> , are the deleted files here
> https://github.com/cms-data/RecoTracker-FinalTrackSelectors/pull/3/files
> already used in cmssw? If not then we can merge this PR

They are not used yet.
This PR is a part of https://github.com/cms-sw/cmssw/pull/21717 integration.
I still have some questions to the performance there.
So, it's not obvious yet that this version of the training file the
final one that we will have
in time for merging that cmssw PR.

**Comment by fabiocos** [comment]
@smuzaffar @slava77 I suggest that we merge this and the cmssw PR together, when that is approved

**Comment by mrodozov** [comment]
since we are testing the changes with the next tag 03, this is not needed anymore. closing it

**Pull request closed without merging**
