### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/42899 for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
lets get this in for more debugging

**Comment by nsmith-** [comment]
I wonder if there is a way to have
```
$ root-config --version
6.29.01
```
print out something more correct? Since as I understand, this is actually one commit above https://github.com/root-project/root/commit/1a029b559b8adbb848370fe15993fb027d365e94 which includes the tag 6.31.01 in the history

**Comment by smuzaffar** [comment]
@nsmith- , https://github.com/root-project/root/commit/1a029b559b8adbb848370fe15993fb027d365e94 commit was before the tag `6.31.01` , so `root-config --version` printing `6.29.01` is correct. Next update to root master should print `6.31.01`

**Comment by nsmith-** [comment]
Ok, I misread the github history. Thanks!

**Pull request merged**
