### PR TITLE
Update tag for RecoBTag-Combined to V01-07-01-01-00

### PR DESCRIPTION
**Pull request by mrodozov**
this is needed in 10_6
 cms-data/RecoBTag-Combined#45
 needed for https://github.com/cms-sw/cmssw/pull/33588

### CODE REVIEW

**Comment by jpata** [comment]
sorry to bother, but just to make sure it's not stuck behind me - could the test be started, can I do it myself?

**Comment by mrodozov** [comment]
allow @jpata test rights

**Comment by mrodozov** [comment]
now you do, but also this was already tested. this only adds the tag that includes the cms-data change to be used

**Comment by mrodozov** [comment]
+externals
when the release manager merge the cmssw PR he'll merge also this

**Comment by qliphy** [comment]
+1

**Pull request merged**
