### PR TITLE
WMAgent 1.0.21.patch4

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by ticoann** [comment]
ping

**Comment by ticoann** [comment]
@amaltaro, Alan, 1.0.21.patch4

**Comment by BrunoCoimbra** [comment]
+1 to 9f892e290fc8fa5583075dfaba00f738a8e2652b on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2743/test_9f892e2-20161215-064505.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
ping

**Comment by smuzaffar** [comment]
@amaltaro , it should have acknowledged your command too. Let me check.

**Comment by amaltaro** [comment]
Great! And what's the magical sentence to get it merged?

**Comment by smuzaffar** [comment]
bot recognize these commands
(please, |)merge: to merge the PR
(please, |)close: to close the PR
(please, |)(re|)open: to open/reopen the PR
ping: to re-trigger the bot to re-read your previous commands if missed due to any infrastructure errors.

**Comment by amaltaro** [comment]
please, merge

**Pull request merged**
