### PR TITLE
Update zstd to latest version 1.5.2

### LINKED ISSUE #8220: Update zstd to latest version 1.5.2
@iarspider or @aandvalenzuela can you pleae take care of it?  Also I think the section https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_0_X/master/zstd.spec#L15-L20 is not needed any more.

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Resolves https://github.com/cms-sw/cmsdist/issues/8220

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
please test
a data external was not merged in cmsdist which was causing these missing data file errors

**Comment by smuzaffar** [comment]
please test
rerun tests based on newer IB

**Comment by aandvalenzuela** [comment]
please test

- Test `TestGeneratorInterfacePythia8InterfaceCompareExternalStreams` failed due to time out

**Comment by aandvalenzuela** [comment]
Unit Test `TestConfigDP` failure is a global issue (https://github.com/cms-sw/cmssw/pull/40301) and unrelated to this PR.

**Comment by smuzaffar** [comment]
please test
lets rerun based on newer IB

**Comment by smuzaffar** [comment]
hold
will merge after 13.0.0.pre2

**Comment by smuzaffar** [comment]
please test
no idea why this shows DQM comparison differences

**Pull request merged**
