### PR TITLE
update crab-dev to v3.211122

### PR DESCRIPTION
**Pull request by ddaina**
fyi @belforte

### CODE REVIEW

**Comment by ddaina** [comment]
please test

**Comment by smuzaffar** [comment]
@ddaina , I see that crab-dev distribution still has some code which refers to `WMCore` modules [a] which are not part of crab-client distribution. Is this a known issue?

[a] /cvmfs/cms-ib.cern.ch/nweek-02708/share/cms/crab-dev/v3.211117.00
```
lib/CRABClient/ClientUtilities.py:    from WMCore.Services.UserFileCache.UserFileCache import UserFileCache
lib/ServerUtilities.py:    from WMCore.WMExceptions import STAGEOUT_ERRORS
lib/RESTInteractions.py:from WMCore.Services.Requests import JSONRequests
lib/RESTInteractions.py:from WMCore.Services.pycurl_manager import RequestHandler
```

**Comment by ddaina** [comment]
thanks @smuzaffar 
- `lib/CRABClient/ClientUtilities.py` in the past used WMCore to upload log to the old crabcache. However, old crabcache was replaced by s3 and that part of the code is not used anymore. @belforte  cleaned the code but those changes are not in this tag.
- `lib/ServerUtilities.py` is imported from CRABServer repo. But code block which uses WMCore is not used by CRABClient.
- `lib/RESTInteractions.py` is imported from CRABServer as well, but is not used anymore by crab-dev client. It is only used by crab-prod/crab-pre. Once we are ready to update crab-prod, we’ll stop importing this file.

**Comment by ddaina** [comment]
please abort

**Comment by ddaina** [comment]
latest tag (v3.211122) should remove WMCore import from `lib/CRABClient/ClientUtilities.py`

**Comment by ddaina** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
