### PR TITLE
adds py2-cycler as external for matplotlib

### PR DESCRIPTION
**Pull request by iahmad-khan**
https://github.com/cms-sw/cmssw/issues/15660

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
after adding the external , it got fixed , in build log , grep showed:

```
cycler: yes [using cycler version 0.10.0]

```
thanks to shahzad for trobleshooting tip.

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
please test

**Comment by smuzaffar** [comment]
looks good

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please make a PR for gcc530 branch

**Pull request merged**
