### PR TITLE
Extend jmalloc to monitor the peak memory usage of each thread (11.1.x)

### PR DESCRIPTION
**Pull request by fwyzard**
See https://github.com/jemalloc/jemalloc/pull/1176 and https://github.com/jemalloc/jemalloc/issues/1850 for the discussion with the jemalloc development team.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #5852

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@silviodonato , this can go in 11.1.X . Feel free to merge.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
