### PR TITLE
updates GeneratorInterface-EvtGenInterface to version v02-00-03

### PR DESCRIPTION
**Pull request by alberto-sanchez**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by alberto-sanchez** [comment]
The errors are unrelated with the change

**Comment by iahmad-khan** [comment]
@alberto-sanchez yes , seems unrelated
@davidlange6 can we merge it?

**Comment by ghost** [comment]
@alberto-sanchez @iahmad-khan This PR is no longer necessary since this commit: https://github.com/cms-sw/cmsdist/commit/d3c650330ac4225ff65d3cb72d9bd791b1fc7a70 upgraded the data to version `V02-00-04`

**Pull request closed without merging**
