### PR TITLE
blackhat: fix compile on armv7hl; add dependency on openssl

### PR DESCRIPTION
**Pull request by davidlt**
On armv7hl target integers in switch(..) expressions overflow, .e.g,

```
case 0x0F02030908:
case 0x0E02030908:
```

generates:

```
warning: overflow in implicit constant conversion [-Woverflow]
```

and:

```
error: duplicate case value
error: previously used here
```

Change all 'long' to 'long long'. long is 4 bytes on armv7hl, but 8
bytes on x86_64. long long is 8 bytes on both platforms. Thus there
should be no changes on ABI level.

In addition package is using OpenSSL from the standard system location.
Force it to link to OpenSSL from CMSDIST.

Signed-off-by: David Abdurachmanov davidlt@cern.ch

### CODE REVIEW

**Comment by ghost** [comment]
Hi @davidlt,
I fixed the openssl issue in a previous PR (which is yet to be integrated) that also re-enable sherpa2.
I think the best way to go is that we first merge my PR #496 and then you update yours to only take the arm7 changes.

**Comment by davidlt** [comment]
@degano I am not against it. I will update PR later once you have merged another one. Just ping me.

**Comment by ktf** [comment]
@degano you have `-ldl`, why is that?

**Comment by ghost** [comment]
Just a cut and paste mistake, I'm removing it and merging, so we can move on.

**Comment by davidlt** [comment]
Updated.

**Pull request merged**
