### PR TITLE
Upgrade condor to v8.8.3

### LINKED ISSUE #4877: Update htcondor to 8.8.1/8.8.2
Schedd machines have been upgraded to 8.8.1, the condor binding should also do the same.

Note: 
8.8.2 was released 3 days ago, which include a new feature in the bindings for printing classAds in json format that some people in SI were waiting for:
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6950
If schedds are updated to that version, this package should update to that too.

This is related to:
https://github.com/dmwm/WMCore/issues/9064

### PR DESCRIPTION
**Pull request by khurtado**
Fixes #4877
Update patch and spec for condor, so that it builds agains v8.8.1.

### CODE REVIEW

**Comment by khurtado** [comment]
please test

**Comment by h4d4** [comment]
+1 to a62b77af8c15fb8d32049b0eaf52839eba76fd7c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4899/test_a62b77a-20190419-181504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to a51dafccebfb4018cb779bcdac439f826a6e3e94 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4899/test_a51dafc-20190503-215510.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 86c5be456f7f06538d914e020b959da337217181 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4899/test_86c5be4-20190528-174025.log" target="_blank">here</a>.

**Comment by khurtado** [comment]
@amaltaro , @belforte: 
Considering both WMAgent and CRAB made their respective tests with this version already, do you agree with requesting this PR to be merged into the framework then? 

If so, @h4d4 , who should we ask for that? Is there any other requirement that needs to be met in order to merge this?

**Comment by belforte** [comment]
+1

**Comment by amaltaro** [comment]
@khurtado I'd rather not merge it now because it will cause WMAgents to have a different HTCondor python binding version (once it gets merged, any new RPM built will carry this new version).

I'd rather merge it only when we work on a new agent production release (which is meant to be only in September though).

Can you remind me whether we can upgrade the htcondor binding version and still keep using schedd 8.6.x?

**Comment by khurtado** [comment]
@amaltaro Ah, thanks for reminding me that! Regarding 8.8 with 8.6 schedds, yes. Submission and queries worked on python bindings 8.8.3 + schedd on 8.6.13 (even using the new `queue_with_itemdata` submit method)

Should we just wait on this 'till September, then?

**Comment by khurtado** [comment]
@amaltaro Pinging about this again, now that we are close to September. To summarize:

- Using python bindings 8.8.3 doesn't require any additional change in WMAgent or the schedd to work (bindings work with 8.5.x condor in the schedd, and collector query related changes have already been merged in the agent.
- Once 8.8.3 is in place, we can move to the new Submit() method in agent (will update code to add some new classads that were added since the PR and remove the collector query change from here, since it's in the agent already) this week: https://github.com/dmwm/WMCore/pull/9133
 - Then, after the new method() works, we can do tests with HTCondor v8.9.2 in the schedd + this version of the python bindings in the agent and enable late materialization.

**Comment by amaltaro** [comment]
@h4d4 can you please merge it? Thanks

**Comment by amaltaro** [comment]
Given that I'll need it soon for the final validation and, it only affects WMAgent and TaskWorker (which do not get deployed in testbed), I'm going to merge it myself.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
