### PR TITLE
[ROOTMaster] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by iarspider**
Changes: [link](https://github.com/root-project/root/compare/5d82c6bdb6...f510880899).

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
```

ROOT::Minuit2::ModularFunctionMinimizer::Minimize(ROOT::Minuit2::FCNBase const&, std::span<double const, 18446744073709551615ul>, std::span<double const, 18446744073709551615ul>, unsigned int, unsigned int, double) const

```

**Comment by iarspider** [comment]
I guess this needs https://github.com/cms-sw/cmssw/pull/46079?

**Comment by smuzaffar** [comment]
I think cms-sw/cmssw#46079 is needed when https://github.com/root-project/root/pull/16491 is merged

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46195

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46195 for CMSSW_14_2_ROOT6_X/el8_amd64_gcc12

**Comment by smuzaffar** [comment]
+externals
https://github.com/cms-sw/cmssw/pull/46195 has been merged so this can go in now

**Pull request merged**
