### PR TITLE
[10_6_X] bumping up sherpa to 2.2.12

### PR DESCRIPTION
**Pull request by SiewYan**
bumping up sherpa to 2.2.12 for UL's

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
please test

**Comment by smuzaffar** [comment]
@SiewYan , unit test `SiStripDAQ_O2O_test` failure is not related to this change.

**Comment by SiewYan** [comment]
@smuzaffar , thanks for the information. Once the master branch is ready and passed , this PR can be considered again.

**Comment by smuzaffar** [comment]
backport of #7916

**Comment by smuzaffar** [comment]
+externals
unit test failure is not related to this PR
@qliphy @perrotta feel free to merge it for 10.6.X

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
