### PR TITLE
[11.2.X] Update tag for L1Trigger-L1TMuon to V01-04-00

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #6772
see https://github.com/cms-data/L1Trigger-L1TMuon/pull/20

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmssw#33281

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
