### PR TITLE
Build alpaka code in GPU-only mode

### PR DESCRIPTION
**Pull request by fwyzard**
Build alpaka device code for the CUDA and ROCm back-ends in "GPU only" mode. In this mode, functions marked as ALPAKA_FN_ACC are marked as `__device__` functions, and are compiled only for the corresponding GPU device back-ends.

Currently, functions marked as ALPAKA_FN_ACC are marked as `__host__ __device__` functions, and may be compiled for both device and host back-ends. The latter leads to linker errors in kernels that use device symbols like `threadIdx`, `blockIdx`, _etc_. that are compiled for the ROCm back-end.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
test parameters:
  - full_cmssw = true
  - enable_tests = gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#44640

**Comment by fwyzard** [comment]
> ---> test runtestPhysicsToolsPatAlgos had ERRORS

I take it this error is unrelated to the Alpaka changes ?

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#44640

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
> `---> test runtestPhysicsToolsPatAlgos had ERRORS`

Independent from this PR ?

**Comment by makortel** [comment]
> > `---> test runtestPhysicsToolsPatAlgos had ERRORS`
> 
> Independent from this PR ?

Yes

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
