### PR TITLE
Do not rely on custom java, we'll pick it up from the system

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 4df37be449f4b52ef99ac9b0b496556c0a476ab7 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4922/test_4df37be-20190430-212505.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
ping

**Comment by amaltaro** [comment]
Valentin, is this outdated and no longer needed?

**Comment by vkuznet** [comment]
No, it is not outdated and it is needed.

**Comment by amaltaro** [comment]
I see it only affects wmarchive. Is there any reason then it hasn't been merged yet?

**Comment by vkuznet** [comment]
I don't know. I'll ping Muhammad directly

@muhammadimranfarooqi , Muhammad could you please merge this PR

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

There are conflicts in this PR. Please resolve this or create a new PR. Thanks

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , I resolved conflict, please trigger build and then if successful merge the PR

**Comment by muhammadimranfarooqi** [comment]
+1 to 07115a45f492b195fce16f2cb2b448598885e9c4 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4922/test_07115a4-20200325-153507.log" target="_blank">here</a>.

**Pull request merged**
