### PR TITLE
[CXXMODULE] build cxxmodules for FWCore/Framework FWCore/ParameterSet

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
this is the error from the IB - to get this far, FWCore* must have built..

**Comment by smuzaffar** [comment]
looks good, lets merge it.

**Comment by davidlange6** [comment]
you beat me to it:)  Thanks.

**Comment by smuzaffar** [comment]
oops no. This change here is not tested by the PR tests :-(  So FWCore was built but without FWCore as CXXMODULE,
Anyway, I am starting a CXXMODULE IB now to get the full build results.

**Pull request merged**
