### PR TITLE
Root update master 20220606

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
Failed unit tests: 
* [src/Validation/CTPPS/test/TestCTPPSDirectProtonSimulation](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1e58ef/25298/unitTests/src/Validation/CTPPS/test/TestCTPPSDirectProtonSimulation/testing.log)
```
Running script: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/src/Validation/CTPPS/test/simu/run_multiple
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/src/Validation/CTPPS/test/simu/run_multiple: line 59: 27823 Segmentation fault      cmsRun "$cfg" &> "$log"
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/src/Validation/CTPPS/test/simu/run_multiple: line 59: 27827 Segmentation fault      cmsRun "$cfg" &> "$log"
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/src/Validation/CTPPS/test/simu/run_multiple: line 59: 27830 Segmentation fault      cmsRun "$cfg" &> "$log"
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/src/Validation/CTPPS/test/simu/run_multiple: line 59: 27835 Segmentation fault      cmsRun "$cfg" &> "$log"
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/src/Validation/CTPPS/test/simu/run_multiple: line 59: 27840 Segmentation fault      cmsRun "$cfg" &> "$log"
```

* [src/TauAnalysis/MCEmbeddingTools/test/testTauEmbeddingProducers](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1e58ef/25298/unitTests/src/TauAnalysis/MCEmbeddingTools/test/testTauEmbeddingProducers/testing.log)
```
Thread 1 (Thread 0x2b53a4898480 (LWP 25674) "cmsRun"):
#0  0x00002b53a3b2dae1 in poll () from /lib64/libc.so.6
#1  0x00002b53ae16772f in full_read.constprop () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/lib/el8_amd64_gcc10/pluginFWCoreServicesPlugins.so
#2  0x00002b53ae1680bc in edm::service::InitRootHandlers::stacktraceFromThread() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/lib/el8_amd64_gcc10/pluginFWCoreServicesPlugins.so
#3  0x00002b53ae16aa0b in sig_dostack_then_abort () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/lib/el8_amd64_gcc10/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  __cxxabiv1::(anonymous namespace)::adjust_pointer<void> (offset=<error reading variable: Cannot access memory at address 0xfffffffffffffff0>, base=0x7ffddac12c30) at ../../../../libstdc++-v3/libsupc++/tinfo.h:65
#6  __cxxabiv1::__dynamic_cast (src_ptr=0x7ffddac12c30, src_type=0x2b53a18aadf0 <typeinfo for ROOT::Math::IBaseFunctionMultiDimTempl<double>>, dst_type=0x2b53a18aa9f0 <typeinfo for ROOT::Fit::BasicFCN<ROOT::Math::IBaseFunctionMultiDimTempl<double>, ROOT::Math::IParametricFunctionMultiDimTempl<double>, ROOT::Fit::BinData>>, src2dst=0) at ../../../../libstdc++-v3/libsupc++/dyncast.cc:55
#7  0x00002b53a170f2d0 in ROOT::Fit::Fitter::GetDataFromFCN<ROOT::Fit::BasicFCN<ROOT::Math::IBaseFunctionMultiDimTempl<double>, ROOT::Math::IParametricFunctionMultiDimTempl<double>, ROOT::Fit::BinData> > (this=0x2b540e1e2480) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc10/lcg/root/6.27.01-c963ca4826d5b69bf3ff29bd97e3fad4/root-6.27.01/math/mathcore/inc/Fit/Fitter.h:560
#8  0x00002b53a170bb8e in ROOT::Fit::Fitter::ExamineFCN (this=0x2b540e1e2480) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc10/lcg/root/6.27.01-c963ca4826d5b69bf3ff29bd97e3fad4/root-6.27.01/math/mathcore/src/Fitter.cxx:984
#9  0x00002b53a17063a1 in ROOT::Fit::Fitter::FitFCN (this=0x2b540e1e2480) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc10/lcg/root/6.27.01-c963ca4826d5b69bf3ff29bd97e3fad4/root-6.27.01/math/mathcore/src/Fitter.cxx:305
#10 0x00002b54139acc21 in ProtonReconstructionAlgorithm::reconstructFromMultiRP(edm::RefVector<std::vector<CTPPSLocalTrackLite, std::allocator<CTPPSLocalTrackLite> >, CTPPSLocalTrackLite, edm::refhelper::FindUsingAdvance<std::vector<CTPPSLocalTrackLite, std::allocator<CTPPSLocalTrackLite> >, CTPPSLocalTrackLite> > const&, LHCInfo const&, std::ostream&) const () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_ROOT6_X_2022-06-05-2300/lib/el8_amd64_gcc10/libRecoPPSProtonReconstruction.so
```

RelVals are complaining about missing files or collections, but I don't observe any crash logs

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
closing in favor of #7922

**Pull request closed without merging**
