### PR TITLE
Update HTCondor python bindings to 9.2.0

### PR DESCRIPTION
**Pull request by khurtado**
Update HTCondor python2/3 bindings to the latest 9.2.0 version

Related issue:
https://github.com/dmwm/WMCore/issues/10256

### CODE REVIEW

**Comment by khurtado** [comment]
test this please

**Comment by muhammadimranfarooqi** [comment]
-1 to e7681bea4387d6ba723a550180603c0fed525c43 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7368/test_e7681be-20211006-230505.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to e7681bea4387d6ba723a550180603c0fed525c43 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7368/test_e7681be-20211007-010502.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to e7681bea4387d6ba723a550180603c0fed525c43 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7368/test_e7681be-20211007-052003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
It looks like `root` is failing to build with an error:
```
* The action "install-lcg+root+6.14.09-comp3" was not completed successfully because Traceback (most recent call last):
File "/build/dmwmbld/srv/HG1704e/apps.sw.pre/pkgtools/scheduler.py", line 269, in doSerial
result = commandSpec[0](*commandSpec[1:])
File "/build/dmwmbld/srv/current/apps/pkgtools/cmsBuild", line 3636, in installPackage
installRpm(pkg, pkg.options.bootstrap)
File "/build/dmwmbld/srv/current/apps/pkgtools/cmsBuild", line 3384, in installRpm
raise RpmInstallFailed(pkg, output)
RpmInstallFailed: Failed to install package root. Reason:
error: Failed dependencies:
	libOpenGL.so.0()(64bit) is needed by lcg+root+6.14.09-comp3-1-1.x86_64
```

maybe we should try updating this root spec to one of those from the CMSSW_11_x or CMSSW_12_x branch (I guess the 11_x, which still brings in python2 packages - for DQMGui?)

**Comment by muhammadimranfarooqi** [comment]
-1 to e7681bea4387d6ba723a550180603c0fed525c43 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7368/test_e7681be-20211007-085003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi @smuzaffar something is wrong with this PR, it keeps triggering the build bot. Can you please close it for the moment? Thanks

**Comment by smuzaffar** [comment]
I have no control ober dmwm  bot :-)

**Comment by amaltaro** [comment]
I could kill it in the node, but I think it will keep restarting as long as this PR is opened. I do not have permissions to close this PR, do you?

**Comment by smuzaffar** [comment]
@amaltaro , I think you have the rights to close. Just comment "please close" and bot should close it for you :-) 

[a]
https://github.com/cms-sw/cms-bot/blob/master/cmsdist_merge_permissions.py#L10
https://github.com/cms-sw/cms-bot/blob/master/cmsdist_merge_permissions.py#L18-L23

**Comment by amaltaro** [comment]
please close

**Comment by amaltaro** [comment]
I tried to build comp with the changes provided here, plus root.spec from CMSSW_11_x/gcc8 and I hit the same issue when installing lcg root package:
```
libOpenGL.so.0()(64bit) is needed by lcg+root+6.14.09-comp3-1-1.x86_64
```

I wonder if it's a matter of installing `libglvnd-opengl` with the bootstrap.spec (or bootstrap-driver)?

@smuzaffar would you by any chance remember how this was resolved for slc7_* builds of CMSSW?

**Comment by smuzaffar** [comment]
we fixed it by adding `libglvnd-opengl` in to the slc7_amd64 bootstrap driver file on cmsrep.cern.ch. I have fixed this for `comp` repo too. Please try again

**Comment by amaltaro** [comment]
Thanks, Shahzad!

**Comment by amaltaro** [comment]
please open

**Comment by amaltaro** [comment]
@khurtado Kenyi, I expected the build bot to run once it was opened again, but it looks like it's not happening.
Could you please push any meaningless change to this PR (like a white space or blank line), just so we can trigger the build bot?

**Comment by khurtado** [comment]
@amaltaro Ok, just did so.

**Comment by muhammadimranfarooqi** [comment]
+1 to 1fbb515a5fcedf9e5bbc59ec497b68c562a57904 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7368/test_1fbb515-20211007-204504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Awesome! Thanks for providing these changes, Kenyi (and thanks to Shahzad for the priceless support!).

@belforte Stefano, sorry for the extremely short noticed, but I'm planning to merge this by tomorrow early in the morning, such that we can proceed with WMAgent validation with this new condor version. Do you see any reason why we should not upgrade the "python2 version" of condor (condor.spec)? From my logs, I see that we have rebuilt crab-devtools, crabserver and crabtaskworker.

**Comment by belforte** [comment]
I do not see any reason why not. Esp. given that we are running now condor 9.1.2 on schedd's. Hope API's from 9.2 are at least as compatible with that as what we are using now. At some point we need to understand what the  crab-devtools is and whether anything uses it, but that's a different story.

**Comment by amaltaro** [comment]
Yes, I should have an answer for you tomorrow at some point. We haven't yet done any test with this release. If things are too bad, we can always revert it :)

**Comment by amaltaro** [comment]
@muhammadimranfarooqi Imran, please merge it at your earliest convenience.

**Comment by belforte** [comment]
CRAB may be using API (features) different from WMA, so it will be better to build a TW with this and give it a try in test setup. Should be easy.

**Comment by amaltaro** [comment]
@belforte FYI. I already see the following RPM available in the official cmsrep repo:
cms+crabtaskworker+v3.210301-comp3-1-1.slc7_amd64_gcc630.rpm

I still have to merge a few PRs and cut a new WMAgent release before I can do any tests with this.

**Comment by belforte** [comment]
thanks Alan, but we do not use that repo (nor that crab tag) anymore. Our next builds will pick up the new bindings anyhow and we'll see. I need to make a new TW for the $HOME/.root.mimes problem :-)

**Comment by belforte** [comment]
CRAB TaskWorker v3.211008 was built with htcondor 9.2 and passed initial tests on crab dev ('test2') instance. I will now run more tests (which I am very confident will work) and deploy in production. FYI @mapellidario @ddaina

**Pull request merged**
