### PR TITLE
reqmgr 0.9.95pre4

### PR DESCRIPTION
**Pull request by ticoann**
fixes https://github.com/dmwm/WMCore/issues/5071 and https://github.com/dmwm/WMCore/issues/5078

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 6497292e1c35168124c5020cf970f1c5a9e3cf78 on slc5_amd64_gcc461.

**Comment by ticoann** [comment]
Sorry Diego, I don't understand comments. Is something wrong?

**Comment by amaltaro** [comment]
Hi Seangchan, most likely it's a misconfiguration or typo in the build agent. I just built the RPMs for slc5 and everything looks fine. We'll investigate this issue

**Comment by geneguvo** [comment]
I had left one testing instance of the agent running and therefore it complained the build failed (was on purpose to simulate errors). It is not running anymore, but in any case the right build-agent did the test and set the status of this PR correctly. I'll delete this "-1" comment.

**Comment by amaltaro** [comment]
Thanks Diego! It's now merged in the repo. Closing it.

**Pull request closed without merging**
