### PR TITLE
Add C++ wrappers for the CUDA API

### PR DESCRIPTION
**Pull request by fwyzard**
Add C++ wrappers for the CUDA API from https://github.com/eyalroz/cuda-api-wrappers

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
@fwyzard , I see following error message in the build log https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3691/25635/external/cuda-api-wrappers/20180125/log . Is this expected?
```
-- Found CUDA: /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc630/external/cuda/9.1.85-cms (found suitable version "9.1", minimum required is "7.0") 
/tmp/cuda-compute-version-helper-23001-1516918207.316623085: error while loading shared libraries: libcudart.so.9.1: cannot open shared object file: No such file or directory
-- CUDA device-side code will assume compute capability 

```

**Comment by fwyzard** [comment]
Hi @smuzaffar, that would only affect the tests, which we don't actually build.
Anyway, I've updated the spec file to pass some parameters explicitly, which should avoid the error.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Pull request merged**
