### PR TITLE
modifying t0.spec to have a configurable WMCore relase.

### PR DESCRIPTION
**Pull request by vytjan**
This is going together with 
https://github.com/dmwm/WMCore/pull/9173
and 
https://github.com/dmwm/deployment/pull/770

### CODE REVIEW

**Comment by h4d4** [comment]
-1 to 55ba81afc152c71dd7f9f6f9755c658075451cfb on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4975/test_55ba81a-20190515-181005.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to e44ad45cbe24f1e8c568eedbd21ec85b7ffee68d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4975/test_e44ad45-20190613-141511.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 6fcb95669a67f60d7c2b0bd4a94f2be6865e5d6d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4975/test_6fcb956-20190724-153507.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to a9c6d9d11917bb5cb04963e6a7bb7386a3b3cc23 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4975/test_a9c6d9d-20190725-150508.log" target="_blank">here</a>.

**Comment by vytjan** [comment]
@h4d4 Lina, could you merge this, please?

Tested and working in multiple replays using the WMCore 1.2.4.patch3 and patching the T0 WMAgent with https://github.com/dmwm/WMCore/pull/9314

**Comment by h4d4** [comment]
@vytjan Vytas, 

the PR was merged.

Best Regards, Lina.

**Pull request merged**
