### PR TITLE
Updated root to tip of branch v6-14-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
please test
Resolves: #5313

### CODE REVIEW

**Comment by smuzaffar** [comment]
@mrodozov , please first get this in master (CMSSW_11_0_X) and then we will backport

**Comment by mrodozov** [comment]
+externals

**Comment by mrodozov** [comment]
@slava77 do you still need this in 10_6 ?

**Comment by slava77** [comment]
> @slava77 do you still need this in 10_6 ?

yes.
This is a long term support release for analysis of Run 2 data.

**Comment by fabiocos** [comment]
I would suggest to merge it once the validation of 11_0_0_pre12 has passed without issues

**Comment by smuzaffar** [comment]
please test
just to get fresh test results

**Comment by fabiocos** [comment]
Apart for the IB tests, not showing any problem, the CMSSW_11_0_0_pre12 has shown no issue, so no reason to keep this backport on hold further

**Comment by fabiocos** [comment]
+1

**Pull request merged**
