### PR TITLE
Minimal backport of fixes and updates to alpaka::Vec [13.2.x]

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #8645

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@perrotta @rappoccio feel free to include it for next 13.2.x release

**Comment by rappoccio** [comment]
+1

**Pull request merged**
