### PR TITLE
backport of py2-h5py from 10_3_X

### PR DESCRIPTION
**Pull request by gudrutis**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by gudrutis** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by mrodozov** [comment]
@fabiocos @davidlange6 any objection to integrate this,
aiming to solve https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3478/1/2/1/4/1.html 
?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
