### PR TITLE
t0.spec file for new t0 release

### PR DESCRIPTION
**Pull request by LinaresToine**
t0.spec file for new t0 release.

### CODE REVIEW

**Comment by LinaresToine** [comment]
please test

**Comment by smuzaffar** [comment]
@arooshap , are dmwm changes to start tests using `please test` comment already deployed on vocmsXX node?

**Comment by arooshap** [comment]
@LinaresToine @smuzaffar No, the changes are not deployed to the build machine yet. Our next production upgrade is on December 4th. We did not have a production upgrade for the last month because we had to delay it due to data taking.

**Comment by LinaresToine** [comment]
Thank you @arooshap. So I suppose that starting December 4 the bot will trigger upon command "please test" regardless of who comments it, right? For now, could you please trigger the bot to test?

Thank you!

**Comment by arooshap** [comment]
@LinaresToine I just made a patch release for this, I am going to see if it works.

No, only the users in the valid comp list will be able to, but I have included your name.

**Comment by arooshap** [comment]
please test

**Comment by arooshap** [comment]
+1 to ed53642cf761a2a20eb5afd1051bd374632e4e8f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8829/test_ed53642-20231128-111003.log" target="_blank">here</a>.

**Comment by arooshap** [comment]
@LinaresToine it's done.

**Pull request merged**
