### PR TITLE
[10.6.X] Add collier toolfile

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
Backport of https://github.com/cms-sw/cmsdist/pull/9206 to provide collier path for run 2 UL madgraph gridpack generation (not exactly the same since handling of toolfiles has changed)

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@cms-sw/orp-l2 , feel free to merge it for 10.6.X IBs and next possible 10.6 release

**Comment by smuzaffar** [comment]
hold

@Dominic-Stafford , for 10.6.X, we need to explicitly add `collier-toolfile` dependency in [cmssw-tool-conf.spec](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/cmssw-tool-conf.spec). Can you please update this PR to include  `collier-toolfile` in cmssw tool conf

**Comment by Dominic-Stafford** [comment]
> hold
> 
> @Dominic-Stafford , for 10.6.X, we need to explicitly add `collier-toolfile` dependency in [cmssw-tool-conf.spec](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/cmssw-tool-conf.spec). Can you please update this PR to include `collier-toolfile` in cmssw tool conf

Thanks for catching this, is it OK now?

**Comment by smuzaffar** [comment]
please test 

@Dominic-Stafford , yes it looks good now

**Comment by smuzaffar** [comment]
unhold

**Comment by smuzaffar** [comment]
+externals

@cms-sw/orp-l2 , this is good to go in 10.6.X , feel free to sign/merge it

**Comment by rappoccio** [comment]
+1

**Pull request merged**
