### PR TITLE
Fix triton-inference-client undefined uint8 error

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes triton-inference-client  build for el9/gcc13 IBs

### CODE REVIEW

**Comment by smuzaffar** [comment]
This fixes the `triton-inference-client` build error [a] for el8/gcc13 IBs  as those IBs are broken since Feb16. I am running local tests to see if cmssw-tool-conf for el9/gcc13 can be build


[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/build-any-ib/CMSSW_14_1_X_2024-03-22-2300/el9_amd64_gcc13/175366/external/triton-inference-client/2.25.0-20c34ade3616410186310d7280fc5778/log
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el9_amd64_gcc13/external/triton-inference-client/2.25.0-20c34ade3616410186310d7280fc5778/triton-inference-client-2.25.0/src/python/library/tritonclient/utils/cuda_shared_memory/cuda_shared_memory.cc:147:24: error: 'uint8_t' does not name a type
  147 |       reinterpret_cast<uint8_t*>(base_addr) + offset, data, byte_size,
      |                        ^~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el9_amd64_gcc13/external/triton-inference-client/2.25.0-20c34ade3616410186310d7280fc5778/triton-inference-client-2.25.0/src/python/library/tritonclient/utils/cuda_shared_memory/cuda_shared_memory.cc:36:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?

```

**Comment by makortel** [comment]
FYI @kpedro88

**Comment by kpedro88** [comment]
Thanks, I'll try to upstream this.

**Comment by smuzaffar** [comment]
upstream this code has been migrated to python so I guess if we update the tritonclinet version then we do not need this patch

**Pull request merged**
