### PR TITLE
[ROOT628] ROOT update v6 28 00 patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
The failing tests are also failing in IBs. There is a relocation error for tensorflow (see [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0e7645/34145/external_checks/relocate/py3-tensorflow.txt)), do you have any hint @iarspider?

**Comment by iarspider** [comment]
Relocation error is on my todo list.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
