### PR TITLE
Add back and update the compiler flags to the alpaka tools [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
Backport https://github.com/cms-sw/cmsdist/pull/7934 .

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@perrotta @qliphy , nothing in cmssw use these tools, so it is safe to include these in 12.4.X IBs. These will be used when we include new alpaka build rules

**Comment by perrotta** [comment]
+1

**Pull request merged**
