### PR TITLE
Try Madgraph 2.7.3 for py3 compatibility

### LINKED ISSUE #5324: Herwig 7 migration to python3
Looking at the failures in the PY3 IB I see that test workflow 511.0 (Herwig7 + external ME) fails due to a trivial issue in an internal python script:

```
&gt;&gt;&gt; Compiling MadGraph amplitudes. This may take some time -- please be patient.
&gt;&gt;&gt; In case of problems see ./Herwig-scratch/Build/MadGraphAmplitudes/MG.log for details.

  File "/cvmfs/cms-ib.cern.ch/nweek-02600/slc7_amd64_gcc820/external/herwigpp/7.1.4-fdffeh2/bin/mg2herwig", line 63
    if it.replace("-","").isdigit():
                                   ^
TabError: inconsistent use of tabs and spaces in indentation
Error: Failed to initialize amplitude 'MadGraph'
```

happening in https://phab.hepforge.org/source/herwighg/browse/herwig-7-1/MatrixElement/Matchbox/External/MadGraph/mg2herwig.py.in$63

A closer inspection shows that there are other issues (for instance print statement syntax). There are not so many python scripts in this generator:

```
07:50 cmsdev25 561> find ./Herwig-7.1.4 -name "*.py" -print
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/particles.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/vertices.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/helpers.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/lorentzparser.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/__init__.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/collapse_vertices.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/write_paramcard.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/converter.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/check_lorentz.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/particles.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/couplings.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/vertices.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/write_param_card.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/lorentz.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/parameters.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/__init__.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/function_library.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/object_library.py
./Herwig-7.1.4/MatrixElement/Matchbox/External/MadGraph/mg2herwig.py
./Herwig-7.1.4/MatrixElement/Matchbox/External/GoSam/gosam2herwig.py
./Herwig-7.1.4/Sampling/herwig-mergegrids.py
./Herwig-7.1.4/Tests/python/histogram.py
./Herwig-7.1.4/Tests/python/compare.py
./Herwig-7.1.4/Tests/python/make_input_files.py
./Herwig-7.1.4/Tests/python/main.py
```

but they should be made python3 compatible.

@qliphy @agrohsje @alberto-sanchez was this already discussed with the authors? Is there already a plan for this?

### PR DESCRIPTION
**Pull request by mrodozov**
this is building, want to check if it integrates and runs
@Dominic-Stafford I don't know whats the difference between 273 and 292 but I'll assume they are similar, so I got the latest version
Resolves: #5324

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test workflow 511.0 for CMSSW_11_3_PY3_X

**Comment by smuzaffar** [comment]
please test workflow 511.0

**Comment by smuzaffar** [comment]
please test workflow 511.0 for CMSSW_11_3_PY3_X

**Comment by smuzaffar** [comment]
+externals
looks good, workflow 511.0 for PY3 also worked

**Comment by mrodozov** [comment]
@smuzaffar I think generators might have other concerns than integration+working lets ask them

**Comment by mrodozov** [comment]
assign generators

**Comment by agrohsje** [comment]
As we don't use the logic in central production it might not matter. However 2.9 was not yet validated by GEN while 2.7 is close to be approved. If there is no strong argument for 2.9, 2.7 might be the better choice to be more in sync with central production.

**Comment by mrodozov** [comment]
I think if I just change the version all the other patches might work, so let me try it and keep the prev commit for when we go from 27 to 29 :D

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test workflow 511.0 for CMSSW_11_3_PY3_X

**Comment by agrohsje** [comment]
Hi @mrodozov, I think the patch failures are due to changes in the default mg5_configuration.txt file for MG5.2.7.3. Would it make sense to make a new patching file starting from the new default in the MG5 tarball that we are using?

**Comment by mrodozov** [comment]
it will I'm making it is it the 2.7.3 or the 2.7.3.py3 that I should use ?

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test workflow 511.0 for CMSSW_11_3_PY3_X

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test workflow 511.0 for CMSSW_11_3_PY3_X

**Comment by mrodozov** [comment]
please test workflow 511.0 for CMSSW_11_3_PY3_X

**Comment by smuzaffar** [comment]
please test workflow 511.0

**Comment by smuzaffar** [comment]
+externals

**Comment by Dominic-Stafford** [comment]
Thank you for doing this!

**Comment by agrohsje** [comment]
+generators

**Pull request merged**
