### PR TITLE
[BuildRules] Enable alpaka ROCm backend [13.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
Backport of #8346.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #8346

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
urgent

needed for 13.0.0

**Comment by fwyzard** [comment]
please abort

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#40725

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#40725 for el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
test parameters:
  * addpkg = DataFormats/Portable,DataFormats/PortableTestObjects,HeterogeneousCore/AlpakaCore,HeterogeneousCore/AlpakaInterface,HeterogeneousCore/AlpakaServices,HeterogeneousCore/AlpakaTest

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
+externals
this can go in 13.0.X now

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
