### PR TITLE
[ROOT CXXMODULE] Get latest commits from master

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by smuzaffar** [comment]
@davidlange6 , @vgvassilev this PR updates root for CXXModule IB and also include the extra lib support https://github.com/cms-sw/cmssw-config/pull/74 . For now I have add DataFormatsWrappedStdDictionaries for DataFormatsCommon. 
By the way, any idea why this deps in needed? May be we can merge the two packages?

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
On Jan 20, 2020, at 7:13 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> , @vgvassilev<https://github.com/vgvassilev> this PR updates root for CXXModule IB and also include the extra lib support cms-sw/cmssw-config#74<https://github.com/cms-sw/cmssw-config/pull/74> . For now I have add DataFormatsWrappedStdDictionaries for DataFormatsCommon.
By the way, any idea why this deps in needed? May be we can merge the two packages?

Its needed for the dictionaries… merging the two packages does “solve” the issue.. but to be discussed what the negative side effects are… We are more in the experimental mode still

**Comment by vgvassilev** [comment]
The dependency is needed because the dictionary for edm::Wrapped\<double\> (and alike) is linked in libDataFormatsWrappedStdDictionaries.so and we have no way to relate to it (because its module definition is empty). I see this a temporary workaround, we may be able to add classes.h as part of the module definition of DataFormatsWrappedStdDictionaries and resolve this properly at some point in future...

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
