### PR TITLE
Define c++ standard in one place

### PR DESCRIPTION
**Pull request by iarspider**
@smuzaffar I have only touched packages where C++ standard was set explicitly, should I also add the flag to packages that were touched in cpp20 branch (e.g. [bazel](https://github.com/cms-sw/cmsdist/pull/8558/files#diff-714cafb16cabd5dbb8245b55b5c195d06f94ecc3b94cbb5f13f6f0553d0fd135R32), [eigen](https://github.com/cms-sw/cmsdist/pull/8558/files#diff-3957d1a15812add5564effd371aa74b39cdf9cb5c1c9cd2552b46fde38e464aaR18), ...)?

### CODE REVIEW

**Comment by smuzaffar** [comment]
I would suggest to update all package from https://github.com/cms-sw/cmsdist/pull/8558/files which have cpp standard change e.g I think yoiu can also add c++ standard related changes for 
- abseil-cpp
- bazel
- eigen
- flatbuffers
- gbl 
and so on

Just only get the changes which are c++ standard related or minor version updates

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test
I have pushed a fix, but github is slow updating this PR...

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/8617#issuecomment-1659838543 is just a merge issue

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
