### PR TITLE
Update rivet-toolfile.spec

### PR DESCRIPTION
**Pull request by mseidel42**
110X Backport of https://github.com/cms-sw/cmsdist/pull/5520

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test for CMSSW_11_0_X

**Comment by mrodozov** [comment]
weird. I have to check whats wrong

**Comment by mseidel42** [comment]
Or is it the wrong branch? There are a couple 11_0_X

**Comment by mrodozov** [comment]
This is the right branch it's something else not sure what yet

**Comment by mrodozov** [comment]
There is also 11_0_master so probably thats it give me a sec to try

**Comment by smuzaffar** [comment]
always check the cms-bot/config.map if you do not know whcih branch is used for a release cycle

**Comment by mrodozov** [comment]
yes, we should've started that way. I opened another one because there were too many commits when comparing 820 and 11_0_master

**Comment by smuzaffar** [comment]
IB/CMSSW_11_0_X/gcc820 brach is not in use. we shoudl delete it

**Pull request closed without merging**
