### PR TITLE
Fix for PS API query to the DB˛

### PR DESCRIPTION
**Pull request by mapsacosta**
New SiteDB release. Includes a fix for the correct display of perfSONAR endpoints.

### CODE REVIEW

**Comment by h4d4** [comment]
@mapsacosta @BrunoCoimbra Hi Maria, 
the boot is showing this message[1], once the PR is triggered,
would you please check if maybe is something unusual in the PR?
Thanks!
[1]
------------- 2018-08-03 18:15:01 comp_gcc630:slc7_amd64_gcc630 -------------
Checking for new commits:
Last commit is still the same: f8698a107ad925f3871410eeb47ae91fc97ec168
Pull Requests to test:
#4066, New TFaaS version
Latest status is pending

------------- 2018-08-03 18:25:01 comp_gcc630:slc7_amd64_gcc630 -------------
Checking for new commits:
Last commit is still the same: f8698a107ad925f3871410eeb47ae91fc97ec168
Pull Requests to test:
#4239, Traceback (most recent call last):
  File "/build/dmwmbld/srv/current/config/dmwmbld/gh-bot", line 186, in <module>
    opts.cfgdir, opts.authfile)
  File "/build/dmwmbld/srv/current/config/dmwmbld/gh-bot", line 36, in pull_req_tester
    print "#%s," % pr['number'], pr['title']
UnicodeEncodeError: 'ascii' codec can't encode character u'\u02db' in position 30: ordinal not in range(128)
------------- 2018-08-03 18:35:01 comp_gcc630:slc7_amd64_gcc630 -------------

**Comment by mapsacosta** [comment]
Hi Lina, so the PR includes a very minor change (one character). What worries me is that the issue is pointing to a different PR: https://github.com/cms-sw/cmsdist/pull/4066

**Comment by mapsacosta** [comment]
Actually no, I take that back. I made another attempt at https://github.com/cms-sw/cmsdist/pull/4240

**Comment by mrodozov** [comment]
@h4d4 Do you still need this or we can close it ?

**Comment by h4d4** [comment]
@mrodozov I just closet it.

Best Regards, Lina.

**Pull request closed without merging**
