### PR TITLE
Get classdef update for TF1 in 6.22

### PR DESCRIPTION
**Pull request by mrodozov**
this is for testing if
1. ROOT builds with this changes
2. Fixes a unit test

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
ROOT builds, to run it needs the cmssw update (32890)

**Comment by smuzaffar** [comment]
@mrodozov , should we close this in favor of #6670 ?

**Comment by mrodozov** [comment]
This one is to make 6-22 change work (as ROOT devs will approve it) while the other one is to get the new stuff from 622
I'll close this anyway eventually and just update 6.22 when they merge the change.
In short - not for now :)

**Comment by mrodozov** [comment]
we don't need this anymore

**Pull request closed without merging**
