### PR TITLE
Revert "Boost - update to 1.75.0"

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmsdist#6655

need more testing on aarch64 where it is failing all relvals with errors like
```
----- Begin Fatal Exception 04-Mar-2021 02:04:40 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named MinBias_8TeV_pythia8_TuneCUETP8M1_cff_GEN_SIM.py
Exception Message:
 unknown python problem occurred.
RuntimeError: boost::filesystem::status: Function not implemented: "/build/cmsbld/jenkins_c/workspace/ib-run-relvals/CMSSW_11_3_X_2021-03-03-2300/poison/SimTracker/SiStripDigitizer/data/APVShapePeak_default.txt"

At:
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Types.py(835): insertInto
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Mixins.py(377): insertContentsInto
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Types.py(920): insertContentsInto
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Types.py(913): insertInto
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Mixins.py(377): insertContentsInto
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Types.py(920): insertContentsInto
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Types.py(913): insertInto
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Config.py(1092): _insertInto
  /cvmfs/cms-ib.cern.ch/nweek-02670/slc7_aarch64_gcc9/cms/cmssw-patch/CMSSW_11_3_X_2021-03-03-2300/python/FWCore/ParameterSet/Config.py(1306): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```

### CODE REVIEW

**Comment by davidlange6** [comment]
This must be FileInPath

https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/src/FileInPath.cc#L96

Perhaps? Looking at it

**Comment by smuzaffar** [comment]
Yes it is FileInPath but at https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/src/FileInPath.cc#L89 . Looks like now `bf::exists(p)` throws exception if file does not exist but this is only happening for aarch64 . for amd64 and ppc64le, it is not throwing exception

**Comment by smuzaffar** [comment]
boost code in question is 
https://github.com/cms-externals/boost/blob/cms/v1.75.0/libs/filesystem/src/operations.cpp#L2571
https://github.com/cms-externals/boost/blob/cms/v1.72.0/libs/filesystem/src/operations.cpp#L1693

**Comment by davidlange6** [comment]
Yes - do we have the boost build logs? Eg, was the platform found correctly?

**Comment by davidlange6** [comment]
If you want the commit history
https://github.com/boostorg/filesystem/blob/develop/src/operations.cpp

**Comment by smuzaffar** [comment]
boost build log for aarch64 is https://cmssdt.cern.ch/SDT/jenkins-artifacts/build-any-ib/CMSSW_11_3_X_2021-03-02-1100/slc7_aarch64_gcc9/106005/external/boost/1.75.0-692eebc1b36f0139611ad4f3eddf0ca8/

**Comment by davidlange6** [comment]
- has statx                : no
    - has statx syscall        : yes

Are we hitting this?
https://github.com/boostorg/filesystem/issues/172

**Comment by smuzaffar** [comment]
I am not 100% sure. A simple test[a] on aarch64 with boost 1.75 also fails even if I set -DBOOST_FILESYSTEM_HAS_STATX_SYSCALL

[a]
```
#include <iostream>
#include <string>
#include "boost/filesystem/path.hpp"
#include "boost/filesystem/operations.hpp"
namespace bf = boost::filesystem;
#include <sys/stat.h>
int main()
{
  std::string p("/build/cmsbld/x/p/CMSSW_11_3_X_2021-03-03-2300/poison/FWCore/ParameterSet/python/Config.py");
  struct ::stat path_stat;
  int err = ::stat(p.c_str(), &path_stat);
  std::cout<<err<<std::endl;
  if (!bf::exists(p))
    std::cout <<"ok"<<std::endl;
  return 0;
}
```

**Comment by smuzaffar** [comment]
let me try to build on the 2nd aarch64 node , may be boost was built on the other node

**Comment by smuzaffar** [comment]
yup looks like issue is with boost built on one system and running it on other.

**Comment by davidlange6** [comment]
I think we can replace boost::filesystem in this package with std::filesystem. I may have a PR soon to try (of course std::filesystem may not have the same issue)

**Comment by davidlange6** [comment]
https://github.com/cms-sw/cmssw/pull/33066

**Comment by smuzaffar** [comment]
thanks @davidlange6 , https://github.com/cms-sw/cmsdist/pull/6699 is not testing boost 1.75 and cms-sw/cmssw#33066

**Pull request merged**
