### PR TITLE
Minimal backport of CUDA-related changes

### PR DESCRIPTION
**Pull request by fwyzard**
Update the CUDA external packaging:
  - include the CUDA runtime static library in the external package;
  - create symlinks for the library stubs to satisfy link-time checks.

Add the cuda-compatible-runtime test as a new external.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@smuzaffar @perrotta @qliphy 
do you prefer to
1. run more extensive tests for this PR by itself, and add the changes to the SCRAM hooks separately 
or
2. add the the changes to the SCRAM hooks together with this, and test them more extensively together
?

**Comment by smuzaffar** [comment]
@fwyzard , I would say, lets add the scram change (https://github.com/cms-sw/cmsdist/pull/7344/commits/b5d11457bbeebd9f56c29f0dbadb57deaf1c64d3 ) and test here extensively

**Comment by fwyzard** [comment]
ok :+1:
thanks for the update

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for slc7_aarch64_gcc9

**Comment by fwyzard** [comment]
please test for slc7_ppc64le_gcc9

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc10

**Comment by fwyzard** [comment]
please test for cc8_amd64_gcc9

**Comment by fwyzard** [comment]
I think we can skip the test for `cc8_aarch64_gcc9` and `cc8_ppc64le_gcc9`.
Or should we run those as well ?

**Comment by smuzaffar** [comment]
> I think we can skip the test for `cc8_aarch64_gcc9` and `cc8_ppc64le_gcc9`. Or should we run those as well ?

ppc64le resources are doing nothing so I suggest to start the tests for `cc8_ppc64le_gcc9` but we can skip `cc8_aarch64_gcc9` as we only have one arm machine available and there is long list of pending jobs to run there

**Comment by fwyzard** [comment]
ok

**Comment by fwyzard** [comment]
please test for cc8_ppc64le_gcc9

**Comment by smuzaffar** [comment]
+externals
looks good to go in 12.0.X. Failed unit tests for non-x86-64 archs are already in the IBs.

**Comment by perrotta** [comment]
+1

**Pull request merged**
