### PR TITLE
Updated root to tip of branch v6-26-00-patches

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
fixed test parameters typo and restart the tests with full cmssw

**Comment by smuzaffar** [comment]
usual results, closing it as we hold the root 6.26 update till ROOT626 validation

**Pull request closed without merging**
