### PR TITLE
drop openssl and use it from system

### PR DESCRIPTION
**Pull request by smuzaffar**
Backported system OpenSSL  changes from IB/CMSSW_11_3_X/cc8 branch.
This should be included in CMSSW 12.0.Xand above

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- enable_test = threading

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
@davidlange6 , as dropping openssl means rebuilt of all python based tools, should we consider updating pip, setuptools (for py3) and python3 itself e.g. python 3.9?

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9
retesting with the 2 unit test fixed

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
test it again for 12_0 and amd

**Comment by mrodozov** [comment]
please test
openloops is fixed now

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
we are keeping this until pre2 (before I forget)

**Comment by smuzaffar** [comment]
12.0.0.pre2 has been build, Iwould suggest to get this in now

**Comment by silviodonato** [comment]
@smuzaffar @cms-sw/xpog-l2 has getting troubles with the NanoAOD integration tests.
In the latest test they are getting
```
>> Compiling  /builds/cms-nanoAOD/nanoAOD-integration/CMSSW_12_0_X_2021-05-31-2300/src/CondCore/CondDB/src/Binary.cc
/builds/cms-nanoAOD/nanoAOD-integration/CMSSW_12_0_X_2021-05-31-2300/src/CondCore/CondDB/src/Binary.cc:8:10: fatal error: openssl/sha.h: No such file or directory
    8 | #include <openssl/sha.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
gmake: *** [config/SCRAM/GMake/Makefile.rules:1694: tmp/slc7_amd64_gcc900/src/CondCore/CondDB/src/CondCoreCondDB/Binary.cc.o] Error 1
gmake: *** Waiting for unfinished jobs....
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
```
It seems that `openssl` is not visible anymore.
See https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/jobs/14197088

Is it a bug on CMSSW side? Do they need to install `openssl` locally?

**Comment by davidlange6** [comment]
yum install openssl-devel
(Or its equivalent on different linux distros)

**Comment by smuzaffar** [comment]
correct, as announced 
- https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/5317.html
- https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/6000.html

we now pick up openssl from system and one should have openssl-libs and openssl-devel packages installed on system

**Pull request merged**
