### PR TITLE
added cmsssw data package EgammaAnalysis-ElectronTools

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
is there a 94(MAOD)X version of this?

**Comment by fabiocos** [comment]
@slava77 @perrotta this is supporting the integration of #22308, and it is affecting only the reminiAOD as as far as I can see, so it can go immediately to facilitate the integration process

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by slava77** [comment]
@fabiocos 
thank you for the quick integration.
IIUC, this made it to the 1100 IB

**Pull request merged**
