### PR TITLE
Test ROOT 6-14 against cmsdist master branch

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
run tests based on newer IB (with new geant4)

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
will retry when ROOT is adapted

**Pull request closed without merging**
