### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- pull_requests = cms-sw/root#142

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test
there is a new PR https://github.com/root-project/root/pull/6668 I want to get in after this changes

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true

**Comment by mrodozov** [comment]
please test
seems it's the same PR, but before it was merged in root:master. anyway, this gets the latest available on master.

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
latest commits from master + 6-22 fix. The fix is not merged yet even on 6-22.
IBs are in better state, lets see if relvals will pass this time

**Comment by mrodozov** [comment]
closing this, https://github.com/cms-sw/root/commit/489ffcd0f273ae4bcb5803bf61f5671518ebdebe is in the latest master, see #6360

**Pull request closed without merging**
