### PR TITLE
Add Nsight Compute CLI python libraries

### PR DESCRIPTION
**Pull request by fwyzard**
Properly package the Nsight Compute command line client and python libraries.

### CODE REVIEW

**Comment by fwyzard** [comment]
@smuzaffar do you think this should work ?

The idea is to have in the PATH the file `nv-nsight-cu-cli`, which internally will launch `$CUDA_BASE/NsightCompute-1.0/target/linux-desktop-glibc_2_11_3-glx-x64/nv-nsight-cu-cli` .

If it works, do you think it would make sense to merge the `cuda-gdb` wrapper package here as well ?

**Comment by smuzaffar** [comment]
@fwyzard , this should work. By the way, `nv-nsight-cu-cli` is already in PATH, so why you want to add wrapper?

Looks like `nv-nsight-cu-cli` is broken for slc6 (due to GLIBC version mismatch)
```
nv-nsight-cu-cli -v
nv-nsight-cu-cli: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by nv-nsight-cu-cli)
```

**Comment by fwyzard** [comment]
> By the way, `nv-nsight-cu-cli` is already in PATH, so why you want to add wrapper?

I put it in the PATH moving it and its support libraries from `$CUDA_BASE/NsightCompute-1.0/target/linux-desktop-glibc_2_11_3-glx-x64/nv-nsight-cu-cli` to `$CUDA_BASE/bin` .
However I just discovered that it looks for some support files in `../../ProfileSectionTemplates` by default, which then gets broken.

**Comment by fwyzard** [comment]
> Looks like `nv-nsight-cu-cli` is broken for slc6 (due to GLIBC version mismatch)

Not much we can do - RHEL 6 and RHEL 7 use the same installer - apart from a bug report to NVIDIA.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@smuzaffar, is it possible to test the external built by Jenkins interactively ?

**Comment by fwyzard** [comment]
OK, from a local build it seems to work as intended.

**Comment by smuzaffar** [comment]
@fwyzard , no it is not possible to test it interactively from jenkins. Once the jenkins job is done then the build area is cleaned up. 
We can upload the RPMS to e.g. `cms-PR<NUM>`  repository for any extra tests if needed.

**Pull request merged**
