### PR TITLE
update sherpa to 2.2.4

### PR DESCRIPTION
**Pull request by smuzaffar**
requested by @pmillet https://github.com/cms-externals/sherpa/pull/11

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by pmillet** [comment]
@smuzaffar As far as i can tell the error does not seem to be related to sherpa. What do you think?

**Comment by smuzaffar** [comment]
@pmillet , yes error does not relate to this PR but we need to re-run the tests based on a newer IB CMSSW_9_4_X_2017-09-13-0100 which is not yet ready. I will start the tests once its available

**Comment by smuzaffar** [comment]
please test
CMSSW_9_4_X_2017-09-13-0100 IB is ready for PR testing

**Comment by smuzaffar** [comment]
+externals
@davidlange6 , any objection including it for 94X. It is also requested for 93X along with openmpi change (https://github.com/cms-sw/cmsdist/pull/3367/files ) which were tested in 93X DEVEL IBs.

**Pull request merged**
