### PR TITLE
Update OpenMPI to version 2.1.5 (critical bugfix release) (10.2.x backport)

### PR DESCRIPTION
**Pull request by fwyzard**
Open MPI v2.1.5 is a critical bug fix release, and is likely the last release in the v2.1.x series.
Open MPI v2.1.5 is only recommended for those who are still running Open MPI v2.0.x or v2.1.x.

Enable support for multithreading in OpenMPI.

Include Boost.MPI:
  - add a dependency on OpenMPI
  - build boost with MPI support
  - add a new boost_mpi tool

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #4255

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
type bug-fix

**Comment by fwyzard** [comment]
backport #4255, #4288

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
+externals

**Comment by kpedro88** [comment]
+1

**Pull request merged**
