### PR TITLE
April pre-prod CRABClient

### PR DESCRIPTION
**Pull request by emaszs**

### CODE REVIEW

**Comment by BrunoCoimbra** [comment]
+1 to abd314fb64b6f0afd7c69f8365a062770cd2b2d9 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2912/test_abd314f-20170322-151505.log" target="_blank">here</a>.

**Comment by emaszs** [comment]
merge

**Comment by amaltaro** [comment]
ping

**Comment by emaszs** [comment]
ping

**Comment by emaszs** [comment]
merge

**Pull request merged**
