### PR TITLE
New WMArchive version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 00a4b31479028eed8ea80c7b4c36e120ddaeef62 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_00a4b31-20161128-154506.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to adc1b67f3aee127c93bf341fcc5dd9e34ceaefa4 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_adc1b67-20161129-175509.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to adc1b67f3aee127c93bf341fcc5dd9e34ceaefa4 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_adc1b67-20161130-172506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to adc1b67f3aee127c93bf341fcc5dd9e34ceaefa4 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_adc1b67-20161130-181355.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 81c4a57902f320c7f2dae33a1594f6b7c3929d1d on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_81c4a57-20161202-161506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 61252f7a7049ff4ec56bd61eadd00418a9de923f on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_61252f7-20161203-020505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to e9e19042d2c077eeb63ff53b7a7a3be6a01d7e37 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_e9e1904-20161203-164505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 61d40cdf62a15a2f3c2f1237212915de2bdb0ff6 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_61d40cd-20161203-202505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 72043bbabc5a433f5d95b7f37264430e805d4d63 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_72043bb-20161203-220505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 1759a38061896618ab8a82f3f21719e1483caaa3 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_1759a38-20161204-005505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 87d5ac0c198c51b2b7742242fbd01c3c7b802afa on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_87d5ac0-20161204-012505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 830b638ee79b66c23128807a80d775fccba58769 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_830b638-20161204-153505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 11e4d778d4be40bda5fca0f6546228fc169ac50e on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_11e4d77-20161204-155505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 9778aef54c9c5a613f80e913bb5d4083197ec21d on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_9778aef-20161204-205505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 79b8a1e67c5e1ec59652a87f6a9c55f14ee51183 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_79b8a1e-20161205-151505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 584be90deb36f48f0e4e24fa33da6f6231bf3576 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_584be90-20161205-211506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 2eaafbe9744219cbed15403d6803d6881fc42ea8 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_2eaafbe-20161206-151506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 49f34263a3d460d45fdb524dc8cf7640d4dafdc5 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_49f3426-20161208-154506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 0110e373b15fa8042d59864676bb7c59c89ace2c on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_0110e37-20161209-161506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 31e98fb22378fd62094aabaa87eee7cde9746e0c on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_31e98fb-20161209-173506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 4b31d7da86d9613013fc3eda0d8f7303b45660c4 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_4b31d7d-20161209-175507.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 502713791ed40503be5eb989b448f7d2ad621d65 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_5027137-20161214-211508.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 36ed27921f3fdc3f7fe9fa79eb403e076ae9baf0 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2685/test_36ed279-20161215-155508.log" target="_blank">here</a>.

**Pull request merged**
