### PR TITLE
Update Eigen to leverage the latest updates to CUDA and AVX support

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fwyzard , do you understand why the latest commit here https://github.com/cms-externals/eigen-git-mirror/tree/cms/64060da  is 64060da while if you click on commits of this branch then there are many other commits on top of it?

**Comment by fwyzard** [comment]
Is it possible that in one case they are sorted by date, and in the other
by graph ?

**Pull request merged**
