### PR TITLE
Updated root to tip of branch v6-14-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
assign dqm
The schema evolution test is failing for root 6.14 and root master IBs. Looks like it is due to the change https://github.com/root-project/root/commit/94610d9fbca67feb898b67d97d8092eaaa960db7 
Can we get this test fixed?

**Comment by smuzaffar** [comment]
@rovere , any suggestion to fix this testSchemaEvolution test?

**Comment by schneiml** [comment]
@smuzaffar It will need a change to the test to whitelist the new version. This check watches any changes in the ROOT object versions that are relevant for DQMGUI/fastHadd so we are reminded to check and update them if needed.

**Comment by schneiml** [comment]
The check tests for version *equality* as far as I remember, after we had trouble with *decreasing* version numbers. So we either need to get the ROOT version and test update in at the same time or modify the test logic again.

**Comment by mrodozov** [comment]
> get the ROOT version and test update in at the same time

we can do that. Once the cms-sw test is updated (I suppose assign the new numbers) you just test your cms-sw PR with the changes in this PR together. Write the cms-sw PR and share the link to it, I'll start the test.

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
merging it for root614 IBs. We have opened a dedicated cmssw branch CMSSW_10_6_ROOT614_X to integrate cms-sw/cmssw#26464

**Pull request merged**
