### PR TITLE
Update setuptools for py2 and py3 and pip for py3

### PR DESCRIPTION
**Pull request by davidlange6**
Separate the py2 and py3 versions of setuptools to allow us to follow the last year of development after py2 support was dropped. These are now separate spec files.

This pr includes #6556 as all of those packages would be rebuilt anyway.

There are some new dependencies included. One to note is a number of new dependencies on wheel, which others have encountered when bumping setuptools. I just added a build requires in each case.

From discussion in this PR, pip is now updated for python3. While current pip releases nominally support python2, I quickly ran into dependency issues that I didn't want to solve for an obsolete stack. So it is updated for python3 only.

The one oddity is with scipy (as commented below). I don't think there is any regression, just a newly known dependency.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , as this is going to build nearly all the pythoon packages, I would suggest to do the same for pip (for python3) i.e. a separate py3-pip package

**Comment by davidlange6** [comment]
Pip seems not to have dropped py2 support yet; so hopefully there is no reason to split things before we drop py2. 
I can try bumping it forward if you want. Did we run into problems upgrading pip before? We are 3 years behind now.

**Comment by smuzaffar** [comment]
IIRC, the newer pip also needed some extra packages and for couple of these there were cyclic dependencies. I hope those are fixed by now

**Comment by smuzaffar** [comment]
how about adding py3-setuptools dependency via https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/master/build-with-pip.file . We include py2-setuptools in build-with-pip.file , I would suggest to update that to include py3-setuptools.

if you decided to add py3-pip then that can also go in build-with-pip

**Comment by davidlange6** [comment]
Ha - meaning none of the pip/*.files need py*setuptools as a requirement.

**Comment by smuzaffar** [comment]
right, as setuptool is very common dependency, so we had decided to include it via the common build file (`build-with-pip`).

**Comment by davidlange6** [comment]
Ok, I started a test with 20.3.3, but it already failed with missing dependencies that seem never to have been supported in python2. Bof, ok, so splitting pip as to solve problems with python3.

(The new pip says that pip 21.0 will drop support for Python 2.7 in January 2021.)

**Comment by davidlange6** [comment]
The first interesting error is 

RpmInstallFailed: Failed to install package py3-scipy. Reason:
error: Failed dependencies:
	libtatlas.so.3()(64bit) is needed by external+py3-scipy+1.5.4-cms2-1-1.x86_64

Atlas is needed by Scipy according to its documentation. Are we getting this via heplibs or something?

**Comment by davidlange6** [comment]
ok, I tested up through python_tools except for tensorflow. I'll start tests here.

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
it failed to fetch pandas
```
Error while downloading sources from pip://pandas/1.2.0?pip_options=--no-deps%20--no-binary%3D:all:&pip=pip3&output=/source.tar.gz.

cd /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/tmp/tmp8R9q6p; . /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc900/external/py2-pip/9.0.3-21e44f7178a7d0bf25f76240640c6530/etc/profile.d/init.sh; pip3 download --no-cache-dir  --no-deps --no-binary=:all: --disable-pip-version-check  -d . pandas==1.2.0; /bin/ls | grep -v files.list > files.list 
256 
Collecting pandas==1.2.0
Could not find a version that satisfies the requirement pandas==1.2.0 (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 0.25.0rc0, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0rc0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0rc0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
No matching distribution found for pandas==1.2.0 
```

**Comment by davidlange6** [comment]
strange - I didn’t have that problem (but probably I downloaded the source with the old pip) - the source is there on pypi..
https://files.pythonhosted.org/packages/75/bc/abf2e8cc6a9d918008774b958613cfdbd3a8c135cffb0757f78fabd8268f/pandas-1.2.0.tar.gz

**Comment by smuzaffar** [comment]
looks like bug in cmsBuild or need to update build-with-pip. cmsBuild is sourcing py2-pip env and running pip3

```
. /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc900/external/py2-pip/9.0.3-21e44f7178a7d0bf25f76240640c6530/etc/profile.d/init.sh; pip3
```

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
@smuzaffar - hum - do you understand these changes? I guess I avoided them by chance.

**Comment by smuzaffar** [comment]
yes @davidlange6 , the pip `19+` version now also run `python setup` at download time to get egg_info ( https://github.com/pypa/pip/issues/1884 ) . This triggers checking of packages dependencies at download time . I am changing the sources to get downloaded directly from github which avoid running `pip download`

**Comment by smuzaffar** [comment]
You avoided them because you were still using pip2 ( i.e. version 9.0) to get sources. For py3 based packages we should use pip3

**Comment by davidlange6** [comment]
So basically we’ll have to change every package that has a dependency (eg, whenever we need to download a source)? Hum..

**Comment by smuzaffar** [comment]
yes unless pip provides an option to disable the running of setup

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
I can check it tomorrow, but this sort of url should work for pypi packages with source available

https://pypi.io/packages/source/p/ppci/ppci-0.5.4.tar.gz


On Jan 20, 2021 5:09 PM, Malik Shahzad Muzaffar <notifications@github.com> wrote:

yes unless pip provides an option to disable the running of setup

**Comment by smuzaffar** [comment]
for most of the package there is github repo so we can always get sources directly from there. In case the sources are not directly available then we can of course download them from pypi

**Comment by davidlange6** [comment]
Sure. I agree  Just thinking of a url that could be programmed in to our tools instead of having to find the github url (which can be subject to moving around)

On Jan 20, 2021 5:35 PM, Malik Shahzad Muzaffar <notifications@github.com> wrote:

for most of the package there is github repo so we can always get sources directly from there. In case the sources are not directly available then we can of course download them from pypi

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
In fact, I think that we can just change it here
https://github.com/cms-sw/pkgtools/blob/dd13151e6667b8343a9fe3f8d0e7cc944d20532e/cmsBuild#L588

I’ll see if I can get the url from pip instead of “knowing” what it is (as that can change)

**Comment by smuzaffar** [comment]
great, yes that will make life easier. Let me change it and test it with this PR.

**Comment by smuzaffar** [comment]
please test with cms-sw/pkgtools#171

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , do you understand the comparison failures? I see that these differences ar also present for the https://github.com/cms-sw/cmsdist/pull/6556#issuecomment-761282738 ? Should we try just updating pip/setuptools and keep the rest unchanged to see if there are comparison diff?

**Comment by davidlange6** [comment]
At first glance - I don’t see how these changes can be from this PR.. They are naively isolated in one workflow which uses dd4hep.  Is there some link between dd4hep and python?

**Comment by smuzaffar** [comment]
@davidlange6 , I can not think of any direct link between dd4hep and python but there is indrect link via root

**Comment by davidlange6** [comment]
I’d propose we retest #6556 and integrate it if no issues and then come back to this PR
(I realize the differences I commented in in #6556 were in the PY3 build, where you expect some differences)

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , this looks much better now. Comparison diff are due to messagelogger.

**Comment by davidlange6** [comment]
Now to know what changed:)

On Jan 26, 2021 8:33 PM, Malik Shahzad Muzaffar <notifications@github.com> wrote:

@davidlange6<https://github.com/davidlange6> , this looks much better now. Comparison diff are due to messagelogger.

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test
re-run based on latest IBs to make sure every thing works

**Comment by smuzaffar** [comment]
+externals
https://github.com/cms-sw/cmsdist/pull/6557#issuecomment-767971155 looks good , comparison diff are due to changeb uin input dataset file

**Pull request merged**
