### PR TITLE
Change the default optimisation level to `-O3`

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
https://github.com/cms-sw/cmssw/issues/44931 shows a 2.4% speed up to the HLT, running with the `x86-64-v3` microarch.

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- enable = threading

**Comment by smuzaffar** [comment]
please test

lets re-build full cmssw

**Comment by slava77** [comment]
> [Reco comparison results: 12 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-05-09-2300+be9632/62739/validateJR.html)

this doesn't have the usual numerical precision level differences. 
The log looks like the build is full. Oddly clean.

**Comment by makortel** [comment]
> > [Reco comparison results: 12 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-05-09-2300+be9632/62739/validateJR.html)
> 
> this doesn't have the usual numerical precision level differences.

What do you mean? We shouldn't be having random numerical-precision level differences that would occur "reliably" in CPU PR tests (as opposed to the "known random differences"), or have I missed something?

**Comment by slava77** [comment]
> > > [Reco comparison results: 12 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-05-09-2300+be9632/62739/validateJR.html)
> > 
> > 
> > this doesn't have the usual numerical precision level differences.
> 
> What do you mean? We shouldn't be having random numerical-precision level differences that would occur "reliably" in CPU PR tests (as opposed to the "known random differences"), or have I missed something?

a recompilation with different flags related to optimization typically leads to some bitwise differences. It's not the case here. I haven't looked closely enough at what `-O3` does compared to the baseline/default.

**Comment by fwyzard** [comment]
On top of `-O2`, `-O3` enables
  - [`-fgcse-after-reload`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-fgcse-after-reload)
  - [`-fipa-cp-clone`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-fipa-cp-clone)
  - [`-floop-interchange`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-floop-interchange)
  - [`-floop-unroll-and-jam`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-floop-unroll-and-jam)
  - [`-fpeel-loops`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-fpeel-loops)
  - [`-fpredictive-commoning`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-fpredictive-commoning)
  - [`-fsplit-loops`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-fsplit-loops)
  - [`-fsplit-paths`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-fsplit-paths)
  - [`-ftree-loop-distribution`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-ftree-loop-distribution)
  - [`-ftree-partial-pre`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-ftree-partial-pre)
  - `-funroll-completely-grow-size` (_undocumented_)
  - [`-funswitch-loops`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-funswitch-loops)
  - [`-fvect-cost-model=dynamic`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-fvect-cost-model)
  - [`-fversion-loops-for-strides`](https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/Optimize-Options.html#index-fversion-loops-for-strides)

According to the GCC documentation these should only deal with invariant changes. So, unlike with `-Ofast`, `-ffast-math` and `-ffp-contract`, I think it is expected that there aren't any differences in the results.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

lets test with thread enabled too

**Comment by smuzaffar** [comment]
+externals 
lets get this in  GEANT4 IBs first

**Pull request merged**
