### PR TITLE
[ROOT master] Root update master

### PR DESCRIPTION
**Pull request by mrodozov**
please test
keep experimental pyroot OFF to update ROOT6
We have https://github.com/cms-sw/cmsdist/pull/5531 dedicated on enabling the new pyroot

### CODE REVIEW

**Comment by mrodozov** [comment]
please test
comparison job failed, lets see if it fails again

**Comment by mrodozov** [comment]
please test
this comparison job keeps failing, last retry

**Comment by davidlange6** [comment]
hi @mrodozov - is this ready to go in?

**Comment by mrodozov** [comment]
yes, should be fine, but the comparison job keeps failing (time outs)
I was considering to get it in regardless

**Comment by mrodozov** [comment]
please test
changed the timeout to twice as much, lets see

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
test parameters:
- release = CMSSW_11_1_X_2020-02-27-2300

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
