### PR TITLE
[10.3.X] updated utm to tag 0.7.1

### PR DESCRIPTION
**Pull request by smuzaffar**
as requested here https://github.com/cms-sw/cmsdist/issues/4334

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by rekovic** [comment]
thanks @smuzaffar 
Is this external going to be part of tonight's 10_3_X IB ?  It would be great if it could.

Asking because of two  HeavyIon PR I want to make.  The second  of the two PRs  depends on the first and on this external UTM at the same time.  So having the UTM in the IB would help.  Thanks.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
