### PR TITLE
Fix ROCM_FLAGS

### PR DESCRIPTION
**Pull request by fwyzard**
Delay the expansion of the COMPILER environment variables.

### CODE REVIEW

**Comment by fwyzard** [comment]
assign heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
I'm not sure if this is the intended behaviour... I'll check on Monday

**Comment by fwyzard** [comment]
OK, from what I can understand it looks good...

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
