### PR TITLE
Backport: FastSimulation-TrackingRecHitProducer: New pixel resolution files [94X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #4196 

Part of the ongoing FastSim backport campaign for 94X.

attn: @ssekmen, @pmaksim1

### CODE REVIEW

**Comment by pmaksim1** [comment]
Awesome, thanks!

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by ssekmen** [comment]
Do we need further checks to merge this PR?

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov please sign

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
