### PR TITLE
bump to version 4.1.4

### PR DESCRIPTION
**Pull request by TonyWildish**
let's try again...

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 9cc3bba7d5fad6febb97cbb0bb343de0bff2eb34 on slc5_amd64_gcc461.

**Comment by TonyWildish** [comment]
Phew!

...now to try for SLC6 :-)

**Comment by TonyWildish** [comment]
I don't see any 4.1.4 RPMs in either comp or comp.pre, was there a problem with the release?

**Comment by ktf** [comment]
What is the status of this one? Can it be closed / merged?

**Comment by geneguvo** [comment]
This is already there. Closing it.

**Pull request closed without merging**
