### PR TITLE
Release 1.1.0 intended for CMSWEB HG1602 release.

### PR DESCRIPTION
**Pull request by nataliaratnikova**
Changelog:
- storageusage       - implemented new algorithm that fixes serious bugs
- getlastrecord        - improved documentation
- dumpspacequery - new API useful for debugging

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 8af036ab3e942e6362d13c8b2ad42f4991b84bbd on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2098/test_8af036a-20160127-175514.log" target="_blank">here</a>.

**Comment by nataliaratnikova** [comment]
The same thing happens for slc6_amd64_gcc493 build :  build log file on the link  is not found..

**Comment by geneguvo** [comment]
+1 to 10d91d6077dd129d18cd8ae87ef85847e4616fc9 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2098/test_10d91d6-20160127-222514.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
Hi Natalia, this last commit seems to be fixed the problem!
I'm Including your changes.

**Pull request closed without merging**
