### PR TITLE
[12.3.X] added DQM-Integration V00-01-00

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #7822
Move DQM-Integration data to new tag, see
https://github.com/cms-data/DQM-Integration/pull/1

### CODE REVIEW

**Comment by smuzaffar** [comment]
FYI @qliphy 
As this only added new data files, so it is safe to merge in cmssw 12.3.X ( this has been tested via master branch)

**Comment by smuzaffar** [comment]
+externals

**Comment by qliphy** [comment]
+1
thanks @smuzaffar

**Comment by qliphy** [comment]
merge

**Pull request merged**
