### PR TITLE
Updated root to tip of branch v6-32-00-patches

### PR DESCRIPTION
**Pull request by iarspider**
ROOT [changes](https://github.com/root-project/root/compare/3f50d37674...48b9717d33)

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
known unit tests failures when root version changes
```
---> test TestFWCoreReflectionClassVersionUpdate had ERRORS
---> test TestIOPoolInputNoParentDictionary had ERRORS
```

and `TestDQMOfflineConfigurationGotAll` is failing in IBs

**Pull request merged**
