### PR TITLE
Update DD4Hep to latest on master

### PR DESCRIPTION
**Pull request by mrodozov**
please test
lets try and see if it integrates

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters
- full_cmssw = true

**Comment by smuzaffar** [comment]
pelase test

**Comment by mrodozov** [comment]
please test

**Comment by cvuosalo** [comment]
@smuzaffar @mrodozov How can I test CMSSW with this PR?

**Comment by mrodozov** [comment]
I've sent an email to explain

**Comment by cvuosalo** [comment]
@mrodozov I get big problems with this version of DD4hep. I tested with CMSSW_11_2_ROOT6_X_2020-08-04-2300, as you instructed.
Here's a look at some errors. More later
```
Running .Warning in <TFile::Init>: no StreamerInfo found in /afs/cern.ch/work/c/cvuosalo/geometry/dd4heptesting/build_dd4hep/slc7_amd64_gcc820/external/dd4hep/v01-13x/lib/G__DD4hep_rdict.pcm therefore preventing schema evolution when reading this file. The file was produced with version 6.20/07 of ROOT.
Warning in <TFile::Init>: no StreamerInfo found in /afs/cern.ch/work/c/cvuosalo/geometry/dd4heptesting/build_dd4hep/slc7_amd64_gcc820/external/dd4hep/v01-13x/lib/G__DD4hepSegmentations_rdict.pcm therefore preventing schema evolution when reading this file. The file was produced with version 6.20/07 of ROOT.
Warning in <TFile::Init>: no StreamerInfo found in /afs/cern.ch/work/c/cvuosalo/geometry/dd4heptesting/build_dd4hep/slc7_amd64_gcc820/external/dd4hep/v01-13x/lib/G__DD4hepProperties_rdict.pcm therefore preventing schema evolution when reading this file. The file was produced with version 6.20/07 of ROOT.
Warning in <TFile::Init>: no StreamerInfo found in /afs/cern.ch/work/c/cvuosalo/geometry/dd4heptesting/build_dd4hep/slc7_amd64_gcc820/external/dd4hep/v01-13x/lib/G__DD4hepGeo_rdict.pcm therefore preventing schema evolution when reading this file. The file was produced with version 6.20/07 of ROOT.
Warning in <TFile::Init>: no StreamerInfo found in /afs/cern.ch/work/c/cvuosalo/geometry/dd4heptesting/build_dd4hep/slc7_amd64_gcc820/external/dd4hep/v01-13x/lib/G__DDCond_rdict.pcm therefore preventing schema evolution when reading this file. The file was produced with version 6.20/07 of ROOT.
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
Info in <TGeoManager::TGeoManager>: Geometry DUMMY, Detector Geometry created
CompactLoader    INFO  +++ Processing compact file: /afs/cern.ch/work/c/cvuosalo/geometry/dd4heptesting/CMSSW_11_2_ROOT6_X_2020-08-04-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml with flag (null)
DD4CMS           INFO  +++ Processing the CMS detector description file:///afs/cern.ch/work/c/cvuosalo/geometry/dd4heptesting/CMSSW_11_2_ROOT6_X_2020-08-04-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
Detector         INFO  *********** Created World volume with size: 10100 10100 45000
Info in <TGeoManager::SetTopVolume>: Top volume is world_volume. Master volume is world_volume
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Warning in <TClassTable::Add>: class dd4hep::NamedObject already in TClassTable
Warning in <TClassTable::Add>: class _Rb_tree_iterator<pair<const string,map<string,string> > > already in TClassTable
Warning in <TClassTable::Add>: class _Rb_tree_iterator<pair<const string,dd4hep::Handle<dd4hep::NamedObject> > > already in TClassTable
Warning in <TClassTable::Add>: class _Rb_tree_iterator<pair<const string,dd4hep::DetElement> > already in TClassTable
Warning in <TClassTable::Add>: class _Rb_tree_iterator<pair<const string,string> > already in TClassTable
```

**Comment by mrodozov** [comment]
Could you please use this IB and do the same
CMSSW_11_2_X_2020-08-07-2300
I picked the ROOT IB and sent it instead of the default one, by mistake. The root 6 IB is master ROOT branch and the ROOT version in the default cmsdist branch is 620 (hence the warnings)
Sorry about that, my mistake
Could you checkout CMSSW latest IB release with 
`scram p CMSSW_11_2_X_2020-08-07-2300`
the rest is the same

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@slava77 could you have a look into this 8 differences ?

**Comment by cvuosalo** [comment]
Testing with CMSSW_11_2_X_2020-08-07-2300, there is a core dump for testDD4hepFilteredView in DetectorDescription/DDCMS. I will investigate some more.

**Comment by mrodozov** [comment]
please test
lets see the test. it doesn't show in PR testing 
I'll run it by hand, too

**Comment by cvuosalo** [comment]
Why has this PR been merged? I see it causing crashes.

**Comment by mrodozov** [comment]
To have it in the next IB and see if it's crashing the tests. 
If it is I'll just revert it to the prev state for the tomorrow 11:00 IB

**Comment by cvuosalo** [comment]
The test `DetectorDescription/DDCMS/test/python/testGeometry2021FromDB.py` reads the geometry (XMLFILE_Geometry_110YV2_Extended2021_mc) from the DB and then processes it with DD4hep. It looks like this old geometry has an error that v13x of DD4hep is now sensitive to. If so, then we would have a big problem with backward compatibility.

```
%MSG-i Root_Information:  DDCMSDetector:test TGeoManager::SetTopVolume()  11-Aug-2020 23:02:42 CEST Run: 1 Event: 1
Top volume is world_volume. Master volume is world_volume
%MSG
%MSG-i Root_Information:  DDCMSDetector:test TGeoNavigator::BuildCache()  11-Aug-2020 23:02:42 CEST Run: 1 Event: 1
--- Maximum geometry depth set to 100
%MSG
DD4CMS           ERROR Exception while processing xml source:xml-memory-buffer
DD4CMS           ERROR ----> Handle_t::attr_ptr: Element [rSolid] has no attribute of type ''
dd4hep: Error interpreting XML nodes of type <LogicalPart/>
dd4hep: Error interpreting XML nodes of type <LogicalPartSection/>
```

**Comment by cvuosalo** [comment]
Tests with the new CMSSW_11_2_X_2020-08-12-1100 IB that contains the new version of DD4hep are clean. There appears to be no problem with this new version. It continues to return lengths as centimeters, as our code expects.

The previous errors I reported must have been due to a misconfigured test setup. We need to figure out a reliable way to create a test setup for testing new versions of DD4hep outside of an IB.

**Pull request merged**
