### PR TITLE
Add -Druntime_cxxmodules

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by yamaguchi1024** [comment]
ping

**Comment by mrodozov** [comment]
please test

**Comment by vgvassilev** [comment]
This is part of cms-sw/cmssw#15248

**Comment by vgvassilev** [comment]
That’s due to root-project/root#2091

**Comment by davidlange6** [comment]
I guess we had assumed that at least root would build... is this specific to one component?


On 16 Nov 2018, at 19:35, Vassil Vassilev <notifications@github.com<mailto:notifications@github.com>> wrote:


That’s due to root-project/root#2091<https://github.com/root-project/root/pull/2091>

**Comment by vgvassilev** [comment]
ROOT with -Dcxx14=On and -Droot7=On has yet another build issue (not related to modules) https://sft.its.cern.ch/jira/browse/ROOT-9804

I think we can turn off `-Droot7` (and likely remove the `-Dcxx17=On`) option.

**Comment by davidlange6** [comment]
> On Nov 17, 2018, at 3:36 PM, Vassil Vassilev <notifications@github.com> wrote:
> 
> ROOT with -Dcxx14=On and -Droot7=On has yet another build issue (not related to modules) https://sft.its.cern.ch/jira/browse/ROOT-9804
> 
> I think we can turn off -Droot7 (and likely remove the -Dcxx17=On) option.

eg, if we remove -Droot7 and -Dcxx17=On but keep Yuka's change, root is likely to build? We can try that..

**Comment by vgvassilev** [comment]
Yep, @yamaguchi1024 could you update the PR?

**Comment by davidlange6** [comment]
i did it.

**Comment by davidlange6** [comment]
please test

**Comment by vgvassilev** [comment]
Wow, I always wondered how this is done...

**Comment by davidlange6** [comment]
please test

**Comment by vgvassilev** [comment]
That's root-project/root#2999

**Comment by vgvassilev** [comment]
I see blank page if I open the link. Is dd4hep part of ROOT in cmssw? Otherwise I do not understand why we cannot build it.

PS: the invocation of rootcling for the dd4hep dictionary should not contain `-cxxmodule` flag.

**Comment by davidlange6** [comment]
Likely it’s still transferring the log. This error is in the build of the dd4hep external (which we were worried about on Friday in the context). It’s. It part of root but rather a package that depends on root



On 17 Nov 2018, at 21:04, Vassil Vassilev <notifications@github.com<mailto:notifications@github.com>> wrote:


I see blank page if I open the link. Is dd4hep part of ROOT in cmssw? Otherwise I do not understand why we cannot build it.

**Comment by vgvassilev** [comment]
We know how to fix it, however, we wanted to test ROOT with modules and the rest of the stack with no modules. If we somehow inherit the rootcling flags from ROOT, it’d explain why we see this.

**Comment by davidlange6** [comment]
hi @vgvassilev - the log is here

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4507/31715/external/dd4hep/v01-08x-cms/log

that fails on this error (which I didn't make sense of yet)

/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/lcg/root/6.15.01-cms/include/ROOT/RStringView.hxx:32:4: error: redefinition of 'basic_string_view' as different kind of symbol
   using basic_string_view = ::std::experimental::basic_string_view<_CharT,_Traits>;
   ^
/cvmfs/cms-ib.cern.ch/nweek-02550/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/string_view:71:11: note: previous definition is here
    class basic_string_view

**Comment by vgvassilev** [comment]
Hi!

Looks like we still enable c++17 for rootcling
```
rootcling -cint -f G__DD4hepProperties.cxx -s /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/external/dd4hep/v01-08x-cms/build/DDCore/../lib/G__DD4hepProperties -inlineInputHeader -c -p -D__ROOFIT_NOBANNER -DBOOST_SPIRIT_USE_PHOENIX_V3 -DDD4HEP_USE_XERCESC -std=c++17 -I/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/external/dd4hep/v01-08x-cms/dd4hep-v01-08x/DDCore/include -I/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/lcg/root/6.15.01-cms/include -I/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/external/xerces-c/3.1.3-omkpbe2/include -I/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/external/dd4hep/v01-08x-cms/dd4hep-v01-08x/DDParsers/include /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/external/dd4hep/v01-08x-cms/dd4hep-v01-08x/DDCore/include/ROOT/Warnings.h /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/external/dd4hep/v01-08x-cms/dd4hep-v01-08x/DDCore/src/PropertyDictionary.h /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/external/dd4hep/v01-08x-cms/dd4hep-v01-08x/DDCore/include/ROOT/LinkDef.h
```

That can be problematic if ROOT was built with c++11

**Comment by davidlange6** [comment]
i can add back the c++17 if leaving it out means an inconsistent root build.

**Comment by davidlange6** [comment]
please test

**Comment by vgvassilev** [comment]
We should explicitly disable root7

**Comment by davidlange6** [comment]
please test

**Comment by vgvassilev** [comment]
Can you add -Dcxx11=On to ROOT.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
ok... lets see..

**Comment by davidlange6** [comment]
looks like c++11 had no effect (I would have thought it was the default already).. perhaps some fix from the root side is needed to get our C++17 + root7 to compile with modules and then we try again?

**Comment by vgvassilev** [comment]
Looks like we have cxx17 and cxx11 at the same time...

**Comment by vgvassilev** [comment]
@oshadura, we have green builds of ROOT with -Druntime_cxxmodules=On and this platform (gcc 7) right?

**Comment by yamaguchi1024** [comment]
slc7/gcc7 is not tested in nightlies (slc6/gcc7 is tested). Let me investigate which cmake option is causing this.

**Comment by yamaguchi1024** [comment]
please test (?)

**Comment by vgvassilev** [comment]
Works on my platform:
`cmake  -DCMAKE_BUILD_TYPE="Release" -DLLVM_BUILD_TYPE="Release" -Dbuiltin_gsl="On" -Dcxx17="On" -Dpython="On" -Droot7="Off" -Druntime_cxxmodules="On" -Dx11="Off" /home/vvassilev/workspace/sources/root `

```bash
uname -a 
Linux vv-nuc 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

**Comment by davidlange6** [comment]
was something changed in the last ~5 days in the root master?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
here is log file of dd4hep https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4507/31723/external/dd4hep/v01-08x-cms/log

**Comment by davidlange6** [comment]
we are back to the same error message as yesterday (basic_string_view_ being declared in two different ways. I gather that we need cxx17=ON to be consistent with the rest of our build?

**Comment by yamaguchi1024** [comment]
Hm, let's try

**Comment by yamaguchi1024** [comment]
please test

**Comment by smuzaffar** [comment]
allow @yamaguchi1024 test rights

**Comment by yamaguchi1024** [comment]
@smuzaffar Thank you!!!!!

**Comment by oshadura** [comment]
@vgvassilev it was tested for centos7/gcc62 & slc6/gcc62 as well as gcc7.3/gcc8.
We were testing with flags -Dall=ON.. how I can see logs?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@yamaguchi1024 , you should have testing rights now for this PR only. As you might have noticed that your commits are in future, so our system is only going to recognize the 'please test' command once `future-commit` label is removed i.e. once all commits timestamp are in past.

**Comment by yamaguchi1024** [comment]
please test

**Comment by smuzaffar** [comment]
@yamaguchi1024 , you still have commits in future that is why your `please test` command is not recognized :-( either fix your clock or wait for few minutes before issuing `please test`

**Comment by yamaguchi1024** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
this time rootpy failed to build. log file is https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4507/31734/external/py2-rootpy/1.0.1-cms/log

**Comment by vgvassilev** [comment]
Looks like ROOT cannot find its module cache, pcm files should be on th LD_LIBRARY_PATH. How do we relocate the so files of ROOT? We should probably do the same with all pcm files.

**Comment by smuzaffar** [comment]
@vgvassilev , we do not relocate .so files. are there any hard coded build paths in .pcm? If yes then let me know how to relocate them?

**Comment by vgvassilev** [comment]
Can you find all pcm files in ROOT and tell us what is their location?

Also could you print the LD_LIBRARY_PATH?

**Comment by smuzaffar** [comment]
all pcm files are in root/lib directory (i.e. /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/lcg/root/6.15.01-cms/lib). and LD_LIBRARY_PATH does include root/lib. see https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4507/31734/external/py2-rootpy/1.0.1-cms/log (pyroot log file) for the full LD_LIBRARY_PATH.

**Comment by vgvassilev** [comment]
How is it possible to run ROOT and not put its libs in that path? Do you set ROOTSYS in a different way?

**Comment by smuzaffar** [comment]
LD_LIBRARY_PATH **includes** root/lib path and ROOTSYS is also set pointing to correct installation. Can you access the log file I mentioned above?

**Comment by vgvassilev** [comment]
Yes I can access the log, however, I first asked then saw ;) (that's the bad part using a phone...)

**Comment by smuzaffar** [comment]
ping testing new webhook

**Comment by smuzaffar** [comment]
@yamaguchi1024 , can you please add a comment in here (just type ping or something)? I would like to check if cms-bot receive the call

**Comment by yamaguchi1024** [comment]
Ping!

**Comment by smuzaffar** [comment]
thanks

**Comment by smuzaffar** [comment]
@yamaguchi1024 , as you should be able to start the tests now so feel free to issue 'please test' command if you want cms-bot to start testing your updates

**Comment by yamaguchi1024** [comment]
@smuzaffar Ok, thanks!

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@yamaguchi1024 , looks like your branch or commit is not correct. Our system was not able to download the sources 
```
12:17:27 * The action "fetch-lcg+root+6.15.01-cms" was not completed successfully because Unable to download git+https://github.com/yamaguchi1024/root.git?obj=cmstest/861f5268075b9c47a167c4d91420589f10d024c8&export=root-6.15.01&output=/root-6.15.01-861f5268075b9c47a167c4d91420589f10d024c8.tgz
```

**Comment by yamaguchi1024** [comment]
I think this is correct.. does `### RPM lcg root 6.15.01` matter?

**Comment by smuzaffar** [comment]
No, that line does not matter. I do not see commit `861f5268075b9c47a167c4d91420589f10d024c8` in your branch https://github.com/yamaguchi1024/root/commits/cmstest

**Comment by yamaguchi1024** [comment]
I didn't push ;((( Sorry

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by yamaguchi1024** [comment]
Now I'm getting error like this:
```
ERROR in cling::CIFactory::createCI():
  resource directory /build/yuka/build-py2-rootpy/tmp/BUILDROOT/fd48ef2cc995181782e498ec3f7df67e/opt/cmssw/slc7_amd64_gcc700/lcg/root/6.15.01-cms2/etc/cling/lib/clang/5.
0.0 not found!
In file included from input_line_1:1:
In file included from /build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3
.1/new:40:
In file included from /build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3
.1/exception:142:
In file included from /build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3
.1/bits/exception_ptr.h:38:
/build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/cxxabi_init_ex
ception.h:38:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
Error in <TCling::LoadModule>: Module libc not found!
Error in <TCling::LoadModule>: Module stl not found!
```
Which is better than looking into python build directory, but still is not the right path. Maybe ROOTSYS is temporary being set to `/build/yuka/build-py2-rootpy/tmp/BUILDROOT/fd48ef2cc995181782e498ec3f7df67e/opt/cmssw/slc7_amd64_gcc700/lcg/root/6.15.01-cms2/` ?

**Comment by davidlange6** [comment]
you can see if ROOT_SYS is set and what it is set to from the log file - do you see it there? (it was set in the log we looked at earlier today)

**Comment by yamaguchi1024** [comment]
Yep
```
+ export ROOT_INCLUDE_PATH
+ export ROOTSYS=/build/yuka/build-py2-rootpy/tmp/BUILDROOT/fd48ef2cc995181782e498ec3f7df67e/opt/cmssw/slc7_amd64_gcc700/lcg/root/6.15.01-cms2
+ ROOTSYS=/build/yuka/build-py2-rootpy/tmp/BUILDROOT/fd48ef2cc995181782e498ec3f7df67e/opt/cmssw/slc7_amd64_gcc700/lcg/root/6.15.01-cms2
++ getconf _NPROCESSORS_ONLN
```

So the ROOTSYS is intentionally set to here.. Hmm is this a correct behavior? Then we'll need to search LD_LIBRARY_PATH or something to find root, or to desend from pyroot as you suggested (I think it's going to be quite a big construction though).

**Comment by smuzaffar** [comment]
which log file is this? root log or rootpy log? In py2-rootpy log I see it is correctly set
```
++ export ROOTSYS=/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/lcg/root/6.15.01-cms
++ ROOTSYS=/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/lcg/root/6.15.01-cms
```

**Comment by davidlange6** [comment]
it might be worth printing out what ROOTSYS is set to inside of your function where this problem happens? Its surprising that it would be changed, but ...

**Comment by yamaguchi1024** [comment]
```
Singularity slc7-builder:latest:/build/yuka> less /build/yuka/build-py2-rootpy/BUILD/slc7_amd64_gcc700/lcg/root/6.15.01-cms2/log | grep ROOTSYS
+ export ROOTSYS=/build/yuka/build-py2-rootpy/tmp/BUILDROOT/fd48ef2cc995181782e498ec3f7df67e/opt/cmssw/slc7_amd64_gcc700/lcg/root/6.15.01-cms2
+ ROOTSYS=/build/yuka/build-py2-rootpy/tmp/BUILDROOT/fd48ef2cc995181782e498ec3f7df67e/opt/cmssw/slc7_amd64_gcc700/lcg/root/6.15.01-cms2
```

It's from /build/yuka/build-py2-rootpy/BUILD/slc7_amd64_gcc700/lcg/root/6.15.01-cms2/log . 

Maybe this is because I didn't remove build-py2-rootpy directory before re-building? Removing and testing.

**Comment by smuzaffar** [comment]
no do not delete directories. 
Do you get failures in root build or py2-rootpy? If it is in py2-rootpy then please look in py2-rootpy log file and see what is ROOTSYS set to.

**Comment by yamaguchi1024** [comment]
Ah root build (and it's hsimple) failing because I changed **not** to overwrite ROOTSYS when starting up ROOT which is set up to some temporary place..

I will try to fix this.

**Comment by smuzaffar** [comment]
ok we get the same error now in PR tests.
This is coming from root itself. My guess is that while building root we have ROOTSYS set to the install directory but by the time we run rootcling the etc/cling/lib/clang/5.0.0 are not yet copied in to the install directory.

**Comment by yamaguchi1024** [comment]
But this `/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/tmp/BUILDROOT/9a03951c41b8e38e1d887f660c565254/opt/cmssw/slc7_amd64_gcc700/lcg/root/6.15.01-cms/etc/cling/lib/clang/5.0.0` is not even an install directory, right? Looks very random path

**Comment by smuzaffar** [comment]
this is install directory durring build process. So
- /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD is directory where we checkout sources and run cmake
- /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/tmp/BUILDROOT is the directory where cmake is going to install root and cmsBuild package this directory in to RPM
- /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700 is the directory where RPM installs the package.

**Comment by yamaguchi1024** [comment]
Ah, I see. Is it possible to run rootcling after coping is completed? (Is it just because coping is slow?

**Comment by smuzaffar** [comment]
It is not in our control. It is root cmake which runs. 
May be we do not want to set ROOTSYS while build root itself?

**Comment by smuzaffar** [comment]
or set ROOTSYS to the /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/tmp/BUILDROOT/... directory during the build process?

**Comment by smuzaffar** [comment]
I think this was the reason root did not want to rely on ROOTSYS as at build time it might not work.

**Comment by yamaguchi1024** [comment]
Yeah.. I'm feeling like desending from pyroot is the most pragmatic plan.

**Comment by smuzaffar** [comment]
@yamaguchi1024 , may be for now you can change this https://github.com/yamaguchi1024/root/blob/3b8ad1c6e60b5c5b6cfac60623c7bd9a02269387/core/unix/src/TUnixSystem.cxx#L476 to do something like this
`if ROOTSYS and directory(ROOTSYS) then return` (convert it in to C++ :-) )

**Comment by yamaguchi1024** [comment]
Ah to check if the ROOTSYS directory exist! That's smart

**Comment by smuzaffar** [comment]
please test

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
```
wrapt (1.10.11)
+ pip2 install --disable-pip-version-check --user -v --no-deps rootpy-1.0.1.tar.gz
The directory '/afs/cern.ch/user/y/yuka/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/afs/cern.ch/user/y/yuka/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing ./rootpy-1.0.1.tar.gz
  Running setup.py (path:/build/yuka/build-py2-rootpy/tmp/pip-uIpptI-build/setup.py) egg_info for package from file:///build/yuka/build-py2-rootpy/BUILD/slc7_amd64_gcc700/external/py2-rootpy/1.0.1-cms/rootpy-1.0.1.tar.gz
    Running command python setup.py egg_info
    python: /build/yuka/build-py2-rootpy/BUILD/slc7_amd64_gcc700/lcg/root/6.15.01-cms/root-6.15.01/interpreter/llvm/src/tools/clang/include/clang/AST/Redeclarable.h:258: clang::Redeclarable<decl_type>::redecl_iterator& clang::Redeclarable<decl_type>::redecl_iterator::operator++() [with decl_type = clang::FunctionDecl]: Assertion `0 && "Passed first decl twice, invalid redecl chain!"' failed.
Cleaning up...
Command "python setup.py egg_info" failed with error code -6 in /build/yuka/build-py2-rootpy/tmp/pip-uIpptI-build/
Exception information:
Traceback (most recent call last):
  File "/build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/build/yuka/build-py2-rootpy/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code -6 in /build/yuka/build-py2-rootpy/tmp/pip-uIpptI-build/
error: Bad exit status from /build/yuka/build-py2-rootpy/tmp/rpm-tmp.uoYPlh (%build)


RPM build errors:
    Bad exit status from /build/yuka/build-py2-rootpy/tmp/rpm-tmp.uoYPlh (%build)
```
At least error changed :)

**Comment by yamaguchi1024** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by yamaguchi1024** [comment]
py2-rootpy now builts with cmsdev15 node!! Let's see how it goes here

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
Which package is this? (I still don't have an access to the log..)

**Comment by yamaguchi1024** [comment]
Ah ok it's written, the package is py2-pip
Does it mean at least py2-rootpy is succeeded? :D

**Comment by davidlange6** [comment]
the logs suggest its rootpy

* The action "build-external+py2-rootpy+1.0.1-cms" was not completed successfully because Failed to build py2-rootpy. Log file in /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/external/py2-rootpy/1.0.1-cms/log. Final lines of the log file:
File "/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
requirement_set.prepare_files(finder)
File "/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
abstract_dist.prep_for_dist()
File "/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
self.req_to_install.run_egg_info()
File "/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
command_desc='python setup.py egg_info')
File "/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc7_amd64_gcc700/external/py2-pip/9.0.3-gnimlf/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
% (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code -11 in /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/tmp/pip-CzKdVK-build/
error: Bad exit status from /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/tmp/rpm-tmp.ndXwYL (%build)

**Comment by smuzaffar** [comment]
and build log of rootpy is available https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4507/32152/external/py2-rootpy/1.0.1-cms/log

**Comment by yamaguchi1024** [comment]
```
Creating directory /build/yuka/build-py2-rootpy/BUILD/slc7_amd64_gcc700/external/py2-rootpy/1.0.1-cms2 if not existing.
Building py2-rootpy. Log can be found in /build/yuka/build-py2-rootpy/BUILD/slc7_amd64_gcc700/external/py2-rootpy/1.0.1-cms2/log.
rm -rf /build/yuka/build-py2-rootpy/BUILD/slc7_amd64_gcc700/external/py2-rootpy/1.0.1-cms2/pkgtools-pkg-src-move2git ; source /build/yuka/build-py2-rootpy/slc7_amd64_gcc700/rpm-env.sh ;  TMPDIR=/build/yuka/build-py2-rootpy/tmp  rpmbuild  --buildroot /build/yuka/build-py2-rootpy/tmp/BUILDROOT/22f7f6a2fd7c50716d0f19fc0448efc2 -ba --define '_topdir /build/yuka/build-py2-rootpy' --define "compiling_processes 12"  --define "cmscompilerv  700" --define "cmsos slc7_amd64" /build/yuka/build-py2-rootpy/SPECS/external/py2-rootpy/1.0.1-cms2/spec >/build/yuka/build-py2-rootpy/BUILD/slc7_amd64_gcc700/external/py2-rootpy/1.0.1-cms2/log 2>&1
Build successful.
(<function buildPackage at 0x7f4a1460f938>, <Package name=py2-rootpy>, <scheduler.Scheduler object at 0x7f4a14557a50>) done
Nothing else to be done, exiting.
Trying to install the rpm package external+py2-rootpy+1.0.1-cms2 just built.
Checking local path dependency for rpm package external+py2-rootpy+1.0.1-cms2 just build.
Done external+py2-rootpy+1.0.1-cms2
Requested to quit.
```

But it works in cmsdev15 :(

Maybe some compiler version changed? Is this command still valid and is consistent to this PR test?
./pkgtools/cmsBuild -a slc7_amd64_gcc700 --repo cms.week0 -c ./cmsdist -i build-py2-rootpy/ -j 12 --repository=cms.week0 build py2-rootpy

**Comment by yamaguchi1024** [comment]
Let's just run test again

**Comment by yamaguchi1024** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@yamaguchi1024 , should we close this now? There is already a more recent PR to test root master.

**Pull request closed without merging**
