### PR TITLE
drop high-level python2 tools

### PR DESCRIPTION
**Pull request by davidlange6**
try again for #6846 (but with more packages removed)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test with cms-sw/cmssw#33560

**Comment by davidlange6** [comment]
hi @smuzaffar - I think this should go into devel first until the migration is close to finished (which likely is limited by how quickly the unit tests are cleaned up) - what do you think?

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
I think all the failures except for Validation/geometry are fixed

**Comment by davidlange6** [comment]
please test with cms-sw/cmssw#33597

**Comment by davidlange6** [comment]
please test with cms-sw/cmssw#33597

**Comment by davidlange6** [comment]
hi @smuzaffar - are these errors somehow related to scram changes? (they should not be related to my changes)

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33597
yes @davidlange6 , I think these should be fixed for today's 11h00 IB. I am starting the tests again

**Comment by davidlange6** [comment]
Ok, thanks!
(We have these sorts of errors in the modules IB - thats interesting…)

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33597

**Comment by smuzaffar** [comment]
> Ok, thanks! (We have these sorts of errors in the modules IB - thats interesting…)

@davidlange6 , Modules IB issues are real one and I think they might be related to the https://github.com/cms-sw/cmssw/pull/33186 . 

I have built module IB using SCRAM V2 (perl base) and workflow 135.1 fails with the same error
```
2021-05-04 16:18:09.491313: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2394450000 Hz
04-May-2021 16:18:16 CEST  Closed file file:step1.root
----- Begin Fatal Exception 04-May-2021 16:18:16 CEST-----------------------
An exception of category 'DictionaryNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PATTriggerProducer label='patTrigger'
Exception Message:
No Dictionary for class: 'edm::AssociationMap<edm::OneToManyWithQualityGeneric<edm::View<reco::Track>,vector<TrackingParticle>,double,unsigned int,edm::RefToBaseProd<reco::Track>,edm::RefProd<vector<TrackingParticle> >,edm::RefToBase<reco::Track>,edm::Ref<vector<TrackingParticle>,TrackingParticle,edm::refhelper::FindUsingAdvance<vector<TrackingParticle>,TrackingParticle> > > >'
----- End Fatal Exception -------------------------------------------------

```

**Comment by davidlange6** [comment]
Yes, I need to look into this error.. Instead I mean some older ones affecting a few workflows (unit tests mostly)  that had the same sort of missing dictionary errors as in these tests (eg, the same missing dictionaries..)

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_PY3_X

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by davidlange6** [comment]
hi @smuzaffar - should we put this in DEVEL for 1100? 
(I don't see why any of these changes would give arch specific problems. Its removing things:) )

**Comment by smuzaffar** [comment]
> hi @smuzaffar - should we put this in DEVEL for 1100?
> (I don't see why any of these changes would give arch specific problems. Its removing things:) )

@davidlange6 , Just wanted to make sure to catch any `%ifarch aarch64|ppc64le` type statements in spec files.
Sure, we can put it in DEVEL IBs

**Comment by smuzaffar** [comment]
+externals
merging it for DVEL IBs.

**Comment by smuzaffar** [comment]
@davidlange6 , DEVEL IBs looks good. Lokk like it is safe to include it in master IBs

**Pull request merged**
