### PR TITLE
Update geant4 to release 10.5

### PR DESCRIPTION
**Pull request by mrodozov**
Try to get Geant4 to latest release
Resolves https://github.com/cms-externals/geant4/issues/36

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
