### PR TITLE
Update pacparser to 1.4.0

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar this is a known issue, let me prepare a patch real quick...

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , there is no need to create temp branch. You can just create a PR for https://github.com/cms-externals/frontier_client and test that pr along with this. e.g. you can run tests like `please test with cms-externals/frontier_client#XXXX` and bot should test both PRs together :-)

**Comment by iarspider** [comment]
Ah, didn't think of that solution. But I will need to change commit id anyway once frontier_client PR is merged.

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-externals/frontier_client/pull/3

**Pull request merged**
