### PR TITLE
WMAgent stable release 2.2.3.1

### PR DESCRIPTION
**Pull request by amaltaro**
WMAgent release to be deployed in production as part of a new upgrade campaign.

### CODE REVIEW

**Comment by arooshap** [comment]
-1 to fbc79e1bef0c053e731214c3201150ed9fb21e28 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8594/test_fbc79e1-20230714-224503.log" target="_blank">here</a>.

**Comment by arooshap** [comment]
+1 to df2650475af6b9b50cdd1337567dc1c2db725ebb on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8594/test_df26504-20230714-235812.log" target="_blank">here</a>.

**Comment by arooshap** [comment]
+1 to 09c4e06f475e00dbe27dddb5e6672351bf033a66 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8594/test_09c4e06-20230715-001503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
