### PR TITLE
[10_6_X] upgrade sherpa 2.2.10 to 2.2.11

### PR DESCRIPTION
**Pull request by SiewYan**
First attempt to upgrade sherpa to 2.2.11, expecting better prediction for v+jets samples compares to previous release. If this PR is successful, will followup with backports.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
allow @SiewYan test rights

**Comment by SiewYan** [comment]
Looks like the shared libraries could not link to the static libraries... there are changes on the MCFM linkage in the latest sherpa version [1]. 

[1] https://gitlab.com/sherpa-team/sherpa/-/merge_requests/389/diffs

**Comment by GurpreetSinghChahal** [comment]
@SiewYan Thank you! This issue has been discussed with Sherpa authors and the suggestion is compile/integrate this release without MCFM. There are a few issues under investigation for MCFM that could be solved in a few weeks time scale. We can use OpenLopps/blackhat for some processes instead of MCFM.

**Comment by SiewYan** [comment]
@GurpreetSinghChahal , i will disable mcfm for this sherpa version. Thanks for the clarification!

**Comment by SiewYan** [comment]
please test

**Comment by smuzaffar** [comment]
this should first go in IB/CMSSW_11_3_X/master branch, @SiewYan can you please open a PR for IB/CMSSW_11_3_X/master too

**Comment by SiewYan** [comment]
@smuzaffar  certainly! #6672

**Comment by smuzaffar** [comment]
+externals

**Comment by SiewYan** [comment]
assign generators

**Comment by SiewYan** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
