### PR TITLE
Add -fno-omit-frame-pointer as default flag for compilation

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung , any specific reason to add this? have you done any performance studies? If I understand correctly `-fno-omit-frame-pointer` is good for debugging applications

**Comment by fwyzard** [comment]
I agree that it may be a useful addition for debugging and profiling, but I would like to check the impact on the HLT performance before merging this.

**Comment by gartung** [comment]
This is meant to improve profiling.

**Comment by gartung** [comment]
I have not done any performance studies.

**Comment by gartung** [comment]
Can you suggest a workflow to test the HLT timing?

**Comment by fwyzard** [comment]
> Can you suggest a workflow to test the HLT timing?

Unfortunately no, nothing out of the box :-/

**Comment by gartung** [comment]
OK

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
please test with #9568

@gartung without #9568 test will fail again

**Comment by gartung** [comment]
Thanks

**Comment by gartung** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/9568

**Comment by gartung** [comment]
Closing for now as this did not improve the attribution of orphaned call stacks in gprofng or perf. Perf implements lbr stack stitching which still produces orphaned stacks. Vtune uses the vendor knowledge that TBB keeps track of the pointer to the spawned process that executes the code.

**Pull request closed without merging**
