### PR TITLE
Herwig 7.1.4 Fix for FxFx.so library

### PR DESCRIPTION
**Pull request by Andrej-CMS**
please see https://github.com/cms-sw/cmsdist/pull/4315

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by Andrej-CMS** [comment]
Dear @all,
the error seems not to be related to this PR or is it?

**Comment by smuzaffar** [comment]
@Andrej-CMS , I will submit some changes here to drop all this LD_LIBRARY_PATH settings. These are not needed any more. Plus need to fix the copying of FxFx.so in to lib/Herwig directory

**Comment by smuzaffar** [comment]
please test

**Comment by Andrej-CMS** [comment]
@smuzaffar 
thanks for the changes!

**Comment by smuzaffar** [comment]
@slava77 , @fabiocos any idea why we have these extra comparison failures?
I see that for workflow 150.0, 158.0, 250202.181, 25202.0, 11624.0 and 10224.0 there are comparison failures for L1TEMU sub-directory. Note that this PR also contains an update of GSL.

**Comment by fabiocos** [comment]
@smuzaffar I do no see recent additions that should directly affect the L1T emulator, the most recent one looks to me #24449 of a couple of days ago

**Comment by smuzaffar** [comment]
it might be due to gsl update, let me re-run without gsl update.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@Andrej-CMS , looks like updating GSL caused some failures in comparison. I am merging it without GSL update. If you need to update gsl then please make a separate PR.

**Pull request merged**
