### PR TITLE
[ROOT628] Updated root to tip of branch v6-28-00-patches

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
test parameters:
- full-cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar  I guess the unit test failure is fine - [previous update](https://github.com/cms-sw/cmsdist/pull/8759) was merged with the same failure

**Comment by smuzaffar** [comment]
+externals
yes this tests normally fails for full cmssw built.

**Pull request merged**
