### PR TITLE
Update tag for GeneratorInterface-EvtGenInterface to V02-00-11-01-00

### PR DESCRIPTION
**Pull request by mrodozov**
see https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/21

### CODE REVIEW

**Comment by mrodozov** [comment]
PR21 is adding new files (from PR20)

**Comment by mrodozov** [comment]
please test
lets check it

**Comment by mrodozov** [comment]
assign generators

**Comment by mrodozov** [comment]
please see
cms-data/GeneratorInterface-EvtGenInterface#20 for details

**Comment by agrohsje** [comment]
Hi @mrodozov you mean cms-data/GeneratorInterface-EvtGenInterface#21 and not cms-data/GeneratorInterface-EvtGenInterface#20 ? i.e. you start from the old tag, add marias files, but omit the other changes from alberto which are part of #20.

**Comment by mrodozov** [comment]
The details/comments about the change are in 20, 21 is the technical change itself.
I started from 02-00-11 , added only whats inside PR20 and omitted everything in between
you can see the description:
https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/21#issue-674453698

**Comment by agrohsje** [comment]
Let's wait for @mgratti to provide feedback on the question from @alberto-sanchez  about the BR normalization.

**Comment by mgratti** [comment]
@agrohsje, the question was answered, see https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/21#issuecomment-865860144

**Comment by agrohsje** [comment]
+generators
Sorry. Following exo meeting.

**Comment by mrodozov** [comment]
+generators

**Comment by mrodozov** [comment]
ping

**Comment by mrodozov** [comment]
+externals

**Comment by qliphy** [comment]
+1

**Comment by mgratti** [comment]
hi @silviodonato, @dpiparo, @qliphy, I would like to ask for the building of a release 102_X with the modifications of this PR included. Together with recent modifications in cmssw ([#33815](https://github.com/cms-sw/cmssw/pull/33815)), the release should allow to test and eventually inject the MC production of heavy long-lived neutrinos from a B semi-leptonic decays.
Please, let me know in case this type of request should be addressed in a different form. Thank you.

**Comment by qliphy** [comment]
@mgratti   https://github.com/cms-sw/cmssw/releases/CMSSW_10_2_27  is now available

**Comment by mgratti** [comment]
@qliphy , thanks a lot

**Comment by agrohsje** [comment]
And requested to be included in mc production. @mgratti

**Pull request merged**
