### PR TITLE
Upgrade jemalloc version to 5.2.0

### PR DESCRIPTION
**Pull request by amaltaro**
Besides the version update, don't run configure twice.

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 2819410b5112c9fe55f0117fae6fcca6a518a67e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4977/test_2819410-20190516-093507.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 50630196be8a2ef85c1e16d0835227908b23143c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4977/test_5063019-20190620-071005.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to d8665202fdd1cc999e93a76f6aa7b1cd057afd9b on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4977/test_d866520-20190620-123007.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
I have tests running (wmagent/reqmgr2/workqueue/wmstats) with this jemalloc update in and everything looks fine so far.

I wonder whether we could profit from this update still for the HG1907? @h4d4 @vkuznet @yuyiguo
Especially given the very large memory footprint seen in the DBS server in these last weeks.

IMO, it's safe enough (but still I'd like to double check my tests tomorrow morning)

**Comment by vkuznet** [comment]
I don't mind if we'll upgrade jemalloc, but I didn't test it, and since almost
all our service relies on it we need to ask for validation all service responsible.

**Pull request merged**
