### PR TITLE
Another set of python2 tools to be removed

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
test parameters:
  - full_cmssw = true

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , looks like this contains the changes of #6955 too ..right?
Can we drop `cryptography` too as no packages requires it any more (only pyOpenSSL was using it)

**Comment by davidlange6** [comment]
Yes, this contains #6955.  I don’t remember why we added cryptography - I’ll try to remind myself. Perhaps indeed its not needed.

**Comment by davidlange6** [comment]
I don't find anything that suggests that the cryptography package is important for some use case - I'll drop cryptography when I next update this (or in the next PR in case this one doesn't need updating)

**Pull request merged**
