### PR TITLE
Update ML related software

### PR DESCRIPTION
**Pull request by riga**
This PR updates software related to ML workflows. Details:

- Update ONNXRuntime from 1.3.0 to 1.6.0. The current fork is at [this branch](https://github.com/riga/onnxruntime/tree/cms/v1.6.0_testing) and could be included to cms_externals/onnxruntime. When 1.6.0 is working properly, the race conditions mentioned in https://github.com/cms-sw/cmssw/issues/32899 should be checked again.
- Add standalone XGBoost library to be used in C++. The Python3 bindings are linked to that version. The legacy Python2 bindings are pinned to an older XGBoost version and thus bring their own library as before.
- Add the [cmsml](https://cmsml.readthedocs.io/en/latest/) python package containing useful tools for working with ML in a cms-specific context. These tools are meant to work independently of cmssw, hence the externalization. **Note**: similar yet older versions of some of the tools are currently living in PhysicsTools/TensorFlow/python and should be removed (or properly deprecated) (https://github.com/cms-sw/cmssw/pull/32942).
- Add [`onnxmltools`](https://pypi.org/project/onnxmltools) which contains several converters to onnx model format. I only added the Python3 tools as they dropped Python2 quite a while ago, and we should have the latest version available to support more models.
- Minor version updates of other ml related software and add the luigi/law workflow tools (plus 2 dependencies) as they are used in some groups.

I tested with workflow 23424.0 (TTbar_13+2026D49PU): `runTheMatrix.py -w upgrade -l 23424.0`.

@mialiu149

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @riga for the updates. I have included your changes in cms-externals/onnxruntime repo now

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc10

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by riga** [comment]
Sorry for the late notice, but I would also like to include `onnxmltools` (within the next hour I hope) which contains a bunch of converters from {sklearn,tf,xgboost,...} to onnx format. This is python only, so I don't expect surprises when testing different architectures.

**Comment by mrodozov** [comment]
allow @riga test rights

**Comment by riga** [comment]
please test for slc7_amd64_gcc10

**Comment by riga** [comment]
please test for slc7_ppc64le_gcc9

**Comment by riga** [comment]
please test for slc7_aarch64_gcc9

**Comment by riga** [comment]
please test for slc7_amd64_gcc10

**Comment by riga** [comment]
please test for slc7_ppc64le_gcc9

**Comment by riga** [comment]
please test

**Comment by riga** [comment]
The error in [cms/6649/slc7_amd64_gcc10](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ae302a/12915/cmsswtoolconf.log) looks like an unresolved merge conflict but I can't see where it comes from.

The failed [cms/6649/slc7_ppc64le_gcc9/relvals](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ae302a/12914/runTheMatrix-results/11634.911_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/) test is due to a segfault in `OscarMTProducer:g4SimHits`, however, I can't see the connection to the changes in this PR yet.

**Comment by smuzaffar** [comment]
`11634.911` for `pcc64le` is already failing in power IBs

**Comment by smuzaffar** [comment]
please test for CMSSW_11_3_PY3_X
lets hope there are no merge conflicts

**Comment by mrodozov** [comment]
It comes from python_tools which seems to be unmergeble into gcc10 (gcc900 to gcc10), fails to merge it with a conflict and then the .spec file remains with the conflict lines -> malformed spec.
I think we can get the rest in and fix gcc10 python_tools by hand and test it.

**Comment by riga** [comment]
The failed unit test in `PhysicsTools/PythonAnalysis/test/testhep_ml.py` uses a wrong import in Python3 and is easy to fix. I will open a PR to CMSSW to change that. I can use the same PR to make the changes to the tools in PhysicsTools/TensorFlow/python/tools.py as mentioned above:

> Note: similar yet older versions of some of the tools are currently living in PhysicsTools/TensorFlow/python and should be removed (or properly deprecated).

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
Hum - there isn’t any history difference between these branches for python_tools.spec is there? Best we can keep it that way.

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc10
gcc10 branch was missing a new line in python_tools. It should be fine now

**Comment by smuzaffar** [comment]
+externals
looks good to go. PY3 unit tests needs cmssw PR

**Pull request merged**
