### PR TITLE
Get UTM 0.8.1 version

### PR DESCRIPTION
**Pull request by mrodozov**
please test
see https://github.com/cms-l1t-offline/cmssw/issues/856

### CODE REVIEW

**Comment by cavana** [comment]
I can confirm that UTM 0.8.1 compiles and executes just fine without any compilation errors or runtime exceptions in CMSSW_11_1_0.

For CMSSW_11_2_X_2020-10-26-2300, the UTM 0.8.1 code compiles just fine (no errors or warnings), but I do get a runtime exception that is unrelated to either the UTM or L1TGlobal packages:

----- Begin Fatal Exception 28-Oct-2020 10:01:49 CDT-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
Unable to find plugin 'PGeometricDetExtraRcd@NewProxy' in category 'CondProxyFactory'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------

That runtime exception is (to my knowledge) unrelated to any L1 Trigger packages, so I am unable to verify if UTM 0.8.1 actually executes successfully or not in CMSSW_11_2_X_2020-10-26-2300.   Could someone kindly point me to the configuration file (or provide the cmsDriver command) that was used to make the test in CMSSW_11_2_X_2020-10-26-2300? 

Best regards, Rick Cavanaugh

**Comment by mrodozov** [comment]
please test
lets just rerun this to see if it was the IB, but I doubt it
I checked already and it was also failing in 11_1 ... weird.

**Comment by mrodozov** [comment]
@cavana if it fails again with the latest available IB I'll write an instruction here how to setup it to make it fail

**Comment by makortel** [comment]
The `PGeometricDetExtraRcd` was recently removed (https://github.com/cms-sw/cmssw/pull/31729), and that required the GlobalTags to be updated as well (https://github.com/cms-sw/cmssw/pull/31780). The removal also caused similar problems elsewhere (https://github.com/cms-sw/cmssw/issues/31869).

I'd guess an update of the GlobaTag would fix your test.

**Comment by mrodozov** [comment]
@cavana I'm setuping 081 so I can share you a reproducible recipe, in the meanwhile I'll build 080 to check if it also fails to run relvals

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
to reproduce the failure:
```
#log on a dev machine
cmssw-cc7 
git clone https://github.com/cms-sw/cms-bot
./cms-bot/test-prs.sh -c IB/CMSSW_11_2_X/master -a slc7_amd64_gcc820 cms-sw/cmsdist#6338
cd $CMSSW_BASE/src
cmsenv ; scram b -j 16 ; 
voms-proxy-init # init your proxy 
# make sure the right utm is setup 
scram tool info utm # should be 0.8.1 installed in your local path
# must show version 081 taken from cmsdist PR 6338
runTheMatrix.py -l 136.793
# fails in step2 with std::bad_alloc
```
this is a runtime error which it doesn't seems to be related to the global tag update or if it does then I don't understand why it works with 0.7.5 but not with 0.8.1 . Fails both in from and outside singularity env, so it's not related to how it's run

**Comment by makortel** [comment]
> this is a runtime error which it doesn't seems to be related to the global tag update or if it does then I don't understand why it works with 0.7.5 but not with 0.8.1 .

I agree running out of memory is unlikely to be caused by GlobalTag (my comment on it was related to the `Unable to find plugin 'PGeometricDetExtraRcd@NewProxy'` error in https://github.com/cms-sw/cmsdist/pull/6338#issuecomment-718033234).

**Comment by mrodozov** [comment]
The reference was to @cavana how to setup it and get the runtime error (and that it's not only a unit test failure)
I'm opening an issue on the UTM repo. 
@rekovic

**Comment by cavana** [comment]
Thank you @mrodozov for the precise setup.   Using your recipe, I was able reproduce the runtime error that you see.  I have verified that the runtime error occurs for both utm_0.8.1 and utm_0.8.0 as well as in both CMSSW_11_2_x and CMSSW_11_1_x.  Those tests suggest that the source of the problem is not due to a difference between 11_2_x and 11_1_x.  Further, I have verified the runtime error does not occur for utm_0.7.5 in either CMSSW_11_1_x or CMSSW_11_2_x.   I am investigating, but I have no time frame for a resolution yet.

**Comment by rekovic** [comment]
please test with #32020

**Comment by rekovic** [comment]
@mrodozov 
The tests take a long time, isn't this unusual ?

**Comment by mrodozov** [comment]
unfortunately they are still pending on the queue. After root update and other externals all IBs built in full this usually takes more time than patch IBs. The job is not started until the console link is posted by the bot (I checked on jenkins, the job is on the queue)

**Comment by rekovic** [comment]
All tests are good.   We should merge this one for 11_2_X (it comes together with cms-sw/cmssw#32020)
Attn @silviodonato

**Comment by rekovic** [comment]
@mrodozov @silviodonato 
we'd like this for MWGR so would be good to merge in the master as soon as possible, so that we can subsequently merge the backport https://github.com/cms-sw/cmsdist/pull/6340 .

**Comment by smuzaffar** [comment]
@rekovic , as you have correctly mention, this PR should go in with cms-sw/cmssw#32020. So we have to wait for cms-sw/cmssw#32020 to be signed first

**Comment by silviodonato** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
