### PR TITLE
Move RecoMuon-MuonIdentification to tag V01-12-05

### PR DESCRIPTION
**Pull request by mrodozov**
Description in https://github.com/cms-data/RecoMuon-MuonIdentification/pull/6

### CODE REVIEW

**Comment by slava77** [comment]
based on the latest tests with cms-sw/cmssw#26460, I think that this is ready to go and can be merged.

**Comment by smuzaffar** [comment]
@slava77 , is it safe to merge it without cms-sw/cmssw#26460 ? Note that one data file was renamed.

**Comment by slava77** [comment]
it should be safe.
The renamed file was added in 
https://github.com/cms-data/RecoMuon-MuonIdentification/pull/5
which was needed for an earlier version of  cms-sw/cmssw#26460

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
