### PR TITLE
upgrade DBS to 3.2.11a

### PR DESCRIPTION
**Pull request by yuyiguo**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 3e48ac0de41ad9336a23749eabcdeaebaefb82ad on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
Hi @yuyiguo ,
We noticed that dbs3.spec is still using version 3.2.11, not 3.2.11a as we'd have expected from your last commit. Wasn't it a mistake? 

We've nevertheless deployed cmsweb-dev with the PR as you provided and DBS3 fails run, bugging with this error on startup:

```
Traceback (most recent call last):
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/WMCore/WebTools/Root.py", line 456, in <module>
    root.start()
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/WMCore/WebTools/Root.py", line 380, in start
    self._loadPages()
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/WMCore/WebTools/Root.py", line 263, in _loadPages
    self._mountPage(view, globalconf, factory, instance)
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/WMCore/WebTools/Root.py", line 332, in _mountPage
    obj = factory.loadObject(view_config.object, view_config, getFromCache = False)
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/WMCore/WMFactory.py", line 82, in loadObject
    classinstance = obj(args)
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/WMCore/WebTools/RESTApi.py", line 41, in __init__
    self._set_model(config)
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/WMCore/WebTools/RESTApi.py", line 58, in _set_model
    self.model = factory.loadObject(config.model.object, config)
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/WMCore/WMFactory.py", line 68, in loadObject
    module = __import__(module, globals(), locals(), [classname])
  File "/data/srv/HG1506a-comp3/sw.pre.coimbra/slc6_amd64_gcc481/cms/dbs3/3.2.11/lib/python2.6/site-packages/dbs/web/DBSReaderModel.py", line 1179
    if not isinstance(data['run_num'], list) and (data['run_num']=1 or data['run_num']="1"):
```

So if you intentionally left dbs3 package in version 3.2.11 (not 11a), would you please tell what is wrong with it?

Cheers,
Diego / @BrunoCoimbra.

**Comment by geneguvo** [comment]
We're guessing the correct is 3.2.11a as it run without any problems on cmsweb-dev and testbed. If that was not your intention, please speak up.

**Comment by yuyiguo** [comment]
It was my mistake. It should be 3.2.11a.
Thanks for fixing it.
Yuyi

**Pull request closed without merging**
