### PR TITLE
Rivet 2.7.0

### PR DESCRIPTION
**Pull request by mseidel42**
New Rivet 2.7.0 was released one week after #4427 was merged.

### CODE REVIEW

**Comment by mseidel42** [comment]
Added patches for CMS analyses as proposed to main rivet here: https://bitbucket.org/heprivet/rivet/pull-requests/4/cms-remove-eigensystem-dependence-fix-1/diff

(fixed one info file and removed GSL dependence)

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
Sorry, introduced mistake in hasty patching. It is fixed now and verified to build successfully.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
FYI @fabiocos

**Comment by fabiocos** [comment]
@intrepid42 @qliphy @efeyazgan @alberto-sanchez which real GEN tests were performed on this new version? Was the impact of this update on nanoAOD verified? According to the PR test there is no change, but I am not sure about the DQM coverage of nanoaods...

@peruzzim @fgolf FYI

**Comment by mseidel42** [comment]
Hi Fabio, the Rivet objects are included in https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py which is picked up by nanoDQM_cff.py->DQMOfflineMC_cff.py/DQMOffline_cff.py

Do you know where to find those plots?

**Comment by peruzzim** [comment]
Could you please clarify whether this is supposed to be a transparent change or not?
You can check PhysicsTools/NanoAOD/python/particlelevel_cff.py to see how potentially affected EDProducers are called.
Thanks!

**Comment by mseidel42** [comment]
There are no changes expected on the physics output. Otherwise, it would invalidate a huge amount of analyses integrated in the Rivet framework. Of course, it would be great if we can verify that ourselves using the nanoAod MC DQM.

`GeneratorInterface/RivetInterface` compiles without warnings, and `test/particleLevel_cfg.py` runs as expected.

(The update to Rivet 2.6.1 (#4427) required a small change in the DressedLeptons constructor but that is merged already.)

**Comment by mseidel42** [comment]
So, does anybody know if the nanoAod DQM plots are done?

**Comment by fabiocos** [comment]
@intrepid42 we have NanoAOD specific workflows with a dedicated DQM, in the short matrix 1325.7 whose results may be found for this test in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4730/33326/runTheMatrix-results/1325.7_TTbar_13_94Xv2NanoAODINPUT+TTbar_13_94Xv2NanoAODINPUT+NANOEDMMC2017_94XMiniAODv2+HARVESTNANOAODMC2017_94XMiniAODv2/ and that do not show any difference in the comparison with the original according to the report. Further similar workflows are:
1325.6, 1325.8, 1329.1 . I let @peruzzim better comment about the coverage expected by these tests.

**Comment by fabiocos** [comment]
Unless @peruzzim @fgolf have further suggestions about possible specific checks besides the basic PR test, I would move forward for integration in next IB. If this enters in 10_6_0_pre1 it will provide a basis for wider possible checks.

**Comment by peruzzim** [comment]
The DQM test covers the modules defined here: https://github.com/cms-nanoAOD/cmssw/blob/master-102X/PhysicsTools/NanoAOD/python/particlelevel_cff.py
i.e. dressed leptons, MET, and HTXS (this is not really tested though, as the sample does not contain the Higgs).
There should be no other content left uncovered by the DQM tests.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
