### PR TITLE
updates xrootd to 4.4.1

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by smuzaffar** [comment]
@iahmad-khan , please update the xrootd-toolfile also. Jenkins tests failed as scram was not able to find external/xrootd/4.4.1-cms/lib  (for xrootd 4.4.x, it is lib64).

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@davidlange6 , feel free to merge it (CMSSW_7_6_X).
@iahmad-khan , can you please make Pr for those release cycles where xrootd version if 4.0.4?

**Pull request merged**
