### PR TITLE
testing geant4 updates , dummy PR

### PR DESCRIPTION
**Pull request by iahmad-khan**
testing https://github.com/cms-externals/geant4/pull/13

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
please test

**Comment by smuzaffar** [comment]
@iahmad-khan , there is something wrong. It is still picking up both clhep verisosn

``````
2ae91c5ca000-2ae91c5cf000 rw-p 00000000 00:00 0 
2ae91c5cf000-2ae91c71d000 r-xp 00000000 00:20 504884                     /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc493/external/clhep/2.2.0.4-giojec/lib/libCLHEP-2.2.0.4.so
2ae91c71d000-2ae91c726000 rw-p 0014e000 00:20 504884                     /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc493/external/clhep/2.2.0.4-giojec/lib/libCLHEP-2.2.0.4.so
2ae91c726000-2ae91c728000 rw-p 00000000 00:00 0 
2ae91c728000-2ae91c8bb000 r-xp 00000000 fc:20 22681021                   /build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc493/external/clhep/2.3.1.1/lib/libCLHEP-2.3.1.1.so
2ae91c8bb000-2ae91c8c4000 rw-p 00193000 fc:20 22681021                   /build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc493/external/clhep/2.3.1.1/lib/libCLHEP-2.3.1.1.so
2ae91c8c4000-2ae91c8c6000 rw-p 00000000 00:00 0 ```

did you run any local tests?
``````

**Comment by smuzaffar** [comment]
@iahmad-khan , are you using correct branch of cmsdist? 
@civanch , https://github.com/cms-externals/geant4/pull/13 needs to be tested in DEVEL IBs ....right? If yes then Ijaz you need to use gcc530next branch (not stable)

**Comment by civanch** [comment]
@smuzaffar , yes, you are right - gcc530next branch should be used.

**Pull request closed without merging**
