### PR TITLE
update EgammaAnalysis-ElectronTools to V00-03-00

### PR DESCRIPTION
**Pull request by slava77**
backport of #6341

needed for cms-sw/cmssw#31995

### CODE REVIEW

**Comment by smuzaffar** [comment]
@slava77 , are these reco differences in comparison job expected?

**Comment by slava77** [comment]
> @slava77 , are these reco differences in comparison job expected?

yes, they are consistent with updates made in the master.
This cmsdist PR can be merged without the cms-sw/cmssw PR because the tag update in the data package corresponds to addition of a new file.

**Comment by mrodozov** [comment]
+externals

**Comment by qliphy** [comment]
+1

**Pull request merged**
