### PR TITLE
Update: HTCondor

### PR DESCRIPTION
**Pull request by khurtado**
Update:
HTcondor to 8.9.6
Boost to 1.69 (needed by HTCondor 8.9.x) 
Add dependencies needed by boost:
  OpenMPI
  Zstd

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to a7d2e81711fec85f815944950c2eaf06b2bcdd2c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5760/test_a7d2e81-20200418-170503.log" target="_blank">here</a>.

**Comment by khurtado** [comment]
Test this please

**Comment by muhammadimranfarooqi** [comment]
+1 to 72b41d7c0baaf1e641ed919859300c66af8ed1c7 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5760/test_72b41d7-20200419-224004.log" target="_blank">here</a>.

**Comment by khurtado** [comment]
Closing, superseded by #5967

**Pull request closed without merging**
