### PR TITLE
updates geant4 spec file to use latest commit from geant4-external

### PR DESCRIPTION
**Pull request by iahmad-khan**
Fixes https://github.com/cms-sw/cmsdist/issues/2378

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
the errors are not related to PR

**Comment by iahmad-khan** [comment]
@davidlt the errors are not related to PR , should we merge it

**Comment by davidlt** [comment]
@iahmad-khan I know errors are not related. Yes, add this to DEVEL. After all, DEVEL is for testing things.

**Pull request merged**
