### PR TITLE
Backport #4554 to 10_2 gcc7

### PR DESCRIPTION
**Pull request by mrodozov**
Backport requested: https://github.com/cms-sw/cmsdist/pull/4554#issuecomment-446569543

### CODE REVIEW

**Comment by mrodozov** [comment]
@fabiocos you start it from the corresponding cmssw PR because I don't know which one it is

**Comment by fabiocos** [comment]
@mrodozov in 10_4_X we have cms-sw/cmssw#25016 using cms-sw/cmsdist#4554 . Now in order to let in 10_2_X cms-sw/cmssw#25386 working properly we need the backport of that data file for 10_2_X. The release tests should not crash as this code is not used in regular workflows, but still this is needed for use in analysis

**Comment by fabiocos** [comment]
@mbluj FYI

**Comment by mbluj** [comment]
Hello,
I do not see this in 10_2_9 which was released earlier today (14/12/2018): https://github.com/cms-sw/cmssw/releases/CMSSW_10_2_9. Is it expected?

**Comment by fabiocos** [comment]
@mbluj release-notes show #4579 in the external updates list, do you see missing files?

**Comment by mbluj** [comment]
Correct, I've overlooked it in release notes. But, I have tried to run DNN-tau-Ids with 10_2_9 at lxplus, but cmsRun failed due to missing files. And, indeed there is not RecoTauTag/TrainingFiles/data/ in /cvmfs/cms.cern.ch/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_2_9/external/slc6_amd64_gcc700/data.

**Comment by fabiocos** [comment]
type bug-fix

**Comment by fabiocos** [comment]
sorry, not intended for this PR. Anyway it looks like there is something to be understood here, @mrodozov could you please cross check?

**Comment by mbluj** [comment]
I have also checked that the files are not present also neither in 10_4_0_pre4 nor in the most recent 10_2_X and 10_4_X IBs (dated 2018-12-14-1100).

**Comment by fabiocos** [comment]
I cross checked and noticed the same thing...

**Comment by smuzaffar** [comment]
@fabiocos , of course it will not be part of release as RecoTauTag-TrainingFiles dependency was not added in cmsswdata.

**Comment by smuzaffar** [comment]
@fabiocos , @mbluj sorry about this. Our fault, we missed the dependency in cmsswdata.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/4590 should fix it.

**Comment by fabiocos** [comment]
@smuzaffar thanks, as this code is not running in official workflows (@mbluj may confirm) this should not be a big problem in the short term, but of course we need to fix it

**Comment by mbluj** [comment]
> 
> 
> @smuzaffar thanks, as this code is not running in official workflows (@mbluj may confirm) this should not be a big problem in the short term, but of course we need to fix it

Yes, I confirm that the code is not run in official workflows and it is why the issue was not detected. But, obviously users will be unhappy that the files are missed in current releases.

**Pull request merged**
