### PR TITLE
Rollback DBS3 to 3.7.8

### PR DESCRIPTION
**Pull request by amaltaro**
Given that the current DBS3 version in production (3.8.1) has issues; Yuyi decided to revert it to the previous production version (3.7.8).

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 77c1b7fbcdd4ac06309df68142d0cdb7cf3025ee on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4958/test_77c1b7f-20190511-092004.log" target="_blank">here</a>.

**Comment by yuyiguo** [comment]
@amaltaro 
Alan,
we need to change

`%define wmcver 1.1.16.dbs3`
`Source0: git://github.com/dmwm/WMCore.git?obj=1.1.16_dbs/%{wmcver}&export=WMCore&output=/WMCore4%{n}.tar.gz`

to 
`%define wmcver 1.1.16`
`Source0: git://github.com/dmwm/WMCore.git?obj=master/%{wmcver}&export=WMCore&output=/WMCore4%{n}.tar.gz`

For all the dbs3 spec files calling wmcore. The reason was commented in [DBS Issue 603](https://github.com/dmwm/DBS/issues/603).

**Comment by amaltaro** [comment]
Good catch, Yuyi! I updated the two specs requiring WMCore code, can you please have another look?
BTW, is that `output=/WMCore4` (number 4) a typo? @yuyiguo

**Comment by yuyiguo** [comment]
@amaltaro 
Alan, 
I did not get you. which file's line 4?

**Comment by h4d4** [comment]
+1 to 8ae86a5d03b39bb8f3077271cbe7b4bb0d0b81b0 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4958/test_8ae86a5-20190511-174504.log" target="_blank">here</a>.

**Comment by yuyiguo** [comment]
@amaltaro 
Alan, output=/WMCore4 (number 4)  is not a typo. just checked.

**Comment by yuyiguo** [comment]
@amaltaro @h4d4 
Lina, Alan,
The patch looked good to me. Let me know if deployed on cmsweb-testbed. I will test.

**Comment by h4d4** [comment]
@yuyiguo Yuyi,

I've included the PR in tag [HG1905i](https://github.com/cms-sw/cmsdist/commits/HG1905i).
And I've deployed it on testbed. Please test and let me know.

Best Regards, Lina.

**Comment by yuyiguo** [comment]
OK, testing …

**Pull request merged**
