### PR TITLE
update CRAB TW and REST to 3.3.1805.rc1 and update WMCore to 1.1.2.crab7

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
@h4d4 Lina please merge this so we have updated spec files for CRAB services aligned to what runs currently in preprod.

**Comment by h4d4** [comment]
+1 to f0e549f09a8b53780264325fe9b3f8d810d94d4f on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3959/test_f0e549f-20180426-151506.log" target="_blank">here</a>.

**Comment by todor-ivanov** [comment]
merge

**Comment by h4d4** [comment]
@belforte @todor-ivanov  Stefano, I see that Todor merget it, so thanks to him for do it.

Additionally, I've have one question, as Todor merged the PR #3942 
this mind that actually the last release deployed on CMSWeb preprod, it's HG1805e[1]
has crabserver 3.3.1804.rc2 version. And if there is no show-stoppers HG1805e will be deployed to production. Therefore, my question is, which crabserver version should be on production:
3.3.1805.rc1 or 3.3.1804.rc2 ?

Best Regards, Lina.

[1] https://github.com/cms-sw/cmsdist/commits/HG1805e/crabserver.spec

**Comment by belforte** [comment]
We will want 3.3.1805.rc1. Or better yet create new 3.3.1805 tag with same content and install a sanely named version at last! sent from Stefano's mobileOn Apr 26, 2018 4:13 PM, Lina Jiménez  <notifications@github.com> wrote:@belforte @todor-ivanov  Stefano, I see that Todor merget it, so thanks to him for do it.
Additionally, I've have one question, as Todor merged the PR #3942
this mind that actually the last release deployed on CMSWeb preprod, it's HG1805e[1]
has crabserver 3.3.1804.rc2 version. And if there is no show-stoppers HG1805e will be deployed to production. Therefore, my question is, which crabserver version should be on production:
3.3.1805.rc1 or 3.3.1804.rc2 ?
Best Regards, Lina.
[1] https://github.com/cms-sw/cmsdist/commits/HG1805e/crabserver.spec

**Comment by h4d4** [comment]
@belforte @todor-ivanov Stefano, thanks for the feedback.
Sure, let me do it. I'll keep you posted.

Best Regards, Lina.

**Comment by h4d4** [comment]
@belforte @todor-ivanov Stefano, Todor,
I've deployed HG1805g, this tag brings crabserver 3.3.1805.rc1 version  on CMSWeb preproduction. 
Please remind to fill this ticket[1] letting me know if this version is ready to go to production.

Best Regards, Lina.
[1]https://gitlab.cern.ch/cms-http-group/doc/issues/102

**Comment by belforte** [comment]
Thanks Lina !
Done.
Stefano

**Pull request merged**
