### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
test parameters:
- pull_requests = cms-sw/cmssw#44328
- release = CMSSW_14_1_ROOT6_X

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by guitargeek** [comment]
Finally! What are the reco and DQM differences like, are they bad? Or just some numeric differences?

Given that RooFit now uses this new backend with autovectorization, I would be interested to know (according to my validations), there should be only differences at the floating-precision level.

Sorry I don't have access to take a look myself.

**Comment by smuzaffar** [comment]
@guitargeek , Reco and DQM comparisons are expected as we compare ROOT 6.30 (default in cmssw) with ROOT master.  
Even without latest root master changes we do see these differences e.g https://github.com/cms-sw/cmsdist/pull/8999#issuecomment-1942190331 for a month old root master vs root 6.30

**Comment by guitargeek** [comment]
Fantastic, thanks!

**Comment by antoniovilela** [comment]
@smuzaffar 
Hi Shahzad, is this good to go with [cms-sw/cmssw/44328 ](https://github.com/cms-sw/cmssw/pull/44328)?
Thanks.

**Comment by smuzaffar** [comment]
yes @antoniovilela

**Comment by smuzaffar** [comment]
+externals

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
