### PR TITLE
New version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to af5c522bd7886761aa1a87037ade9e2db36193b9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6221/test_af5c522-20200908-195503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Its failed.

**Comment by vkuznet** [comment]
ahh, I forgot to include go rotatelogs dependency (it is added in docker though). Please trigger a new build, I hope it will be fine now.

**Comment by muhammadimranfarooqi** [comment]
+1 to b553eba3e57e05276e9ba2369c83a9456b415a0a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6221/test_b553eba-20200908-201503.log" target="_blank">here</a>.

**Pull request merged**
