### PR TITLE
Build ROOT and DD4Hep in debug mode

### PR DESCRIPTION
**Pull request by mrodozov**
see https://github.com/cms-sw/cmssw/issues/32141#issuecomment-838869547
CLHEP is already is in RelWithDebugSymbols mode

### CODE REVIEW

**Comment by davidlange6** [comment]
We don't have a ppc branch?

On May 11, 2021 7:44 PM, Mircho Rodozov ***@***.***> wrote:

see cms-sw/cmssw#32141 (comment)<https://github.com/cms-sw/cmssw/issues/32141#issuecomment-838869547>
CLHEP is already is in RelWithDebugSymbols mode

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/cms-sw/cmsdist/pull/6893

Commit Summary

  *   Build ROOT and DD4Hep in debug mode

File Changes

  *   M dd4hep.spec<https://github.com/cms-sw/cmsdist/pull/6893/files#diff-71d575042aa0c5063c7a3b3456d09216a283b3805936d7ee23702fac27a752e9> (2)
  *   M root.spec<https://github.com/cms-sw/cmsdist/pull/6893/files#diff-f7675e8ed13f5b85d8cc2cfa4022ca6ab330c2f057a3c97654a365dbfa721ca5> (2)

Patch Links:

  *   https://github.com/cms-sw/cmsdist/pull/6893.patch
  *   https://github.com/cms-sw/cmsdist/pull/6893.diff

**Comment by davidlange6** [comment]
If not, then maybe using the DEVEL branch is less disruptive (means changing the ppc build to use a different cmsdist branch)

**Comment by mrodozov** [comment]
hmm I'm thinking to merge this in master build the ppc IB and then move it again to 
=Release

**Comment by davidlange6** [comment]
also good! go for it

**Pull request merged**
