### PR TITLE
New DAS version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by h4d4** [comment]
to 449c1214f1f06c1dd610c02a9e9f1ff9662330b8 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3527/test_449c121-20171025-005504.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@h4d4 Lina where is the log of the build, the provided link leads to 404 page.

**Comment by h4d4** [comment]
+1 to 449c1214f1f06c1dd610c02a9e9f1ff9662330b8 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3527/test_449c121-20171025-160504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to cb83faa94a3287d1c80ad12b32d3ff2342840b14 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3527/test_cb83faa-20171025-230505.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to b274482591a2b2aed86d6cfe399be7dcf05b7271 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3527/test_b274482-20171026-005504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 3307c7ddc2c39753d405efe66cbfeac037a580be on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3527/test_3307c7d-20171026-014504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 75ab4a1c8e45350e3e5d4bd971a618f0b93cd8ea on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3527/test_75ab4a1-20171026-125506.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 17ad9afe49a52e94da1685d78cfa570fc0f343be on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3527/test_17ad9af-20171026-132505.log" target="_blank">here</a>.

**Pull request merged**
