### PR TITLE
Added patch for decay of K0 and antiK0

### PR DESCRIPTION
**Pull request by civanch**
This is a clone of #3505 and #3510

### CODE REVIEW

**Comment by mrodozov** [comment]
are you sure about the compiler ? we cannot test this as we don't have an IB for it, we could've if it was for IB/CMSSW_9_3_X/gcc630

**Comment by civanch** [comment]
@mrodozov , I am not sure if this PR should be tested more than for 1 compiler but for me seems to be correct if PRs are merged for all branches - 9_3X/gcc530, 9_3_0/gcc630 and 9_3_0/gcc700 - probably only 1 test for the production release is enough.

**Comment by davidlange6** [comment]
prs are merged for all branches via an automatic process.

**Comment by civanch** [comment]
What I have observed , at least, in 9_3_X - geant4.spec file is not identical in different gcc branches. Was this needed for purpose or is a result of historical process - do not know.

**Pull request closed without merging**
