### PR TITLE
Fix tkonlinesw headers for clang error  ISO C++1z does not allow dynamic exception specifications [-Wdynamic-exception-spec]

### PR DESCRIPTION
**Pull request by gartung**
This changes the tkonlinesw headers after install to change throw(*) to noexcept(false) as suggested by clang error : ISO C++1z does not allow dynamic exception specifications [-Wdynamic-exception-spec]

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
@smuzaffar Chris suggested I add v4.1.0 to cms-exeternal/tkonlinesw, make the change, and commit the changes for testing.

**Comment by smuzaffar** [comment]
@gartung, I have sent you the invitation to join  cms-externals Developers team. This should allow you to push chnages to cms-externals/tkonlinesw repository. Please first push v4.1.0  to new branch cms/v4.1.0 and then add your changes

**Comment by davidlt** [comment]
This is probably similar or identical to what's in GCC 7.1.1 branch: https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_9_3_X/gcc700/trackerDAQ-4.1-cleanup-gcc7.patch (1+M patch, not small).

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
