### PR TITLE
Remove the CUDA API wrappers external

### PR DESCRIPTION
**Pull request by fwyzard**
As all Patatrack developments have migrated away from using the CUDA API wrappers, we can remove them from CMSSW.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#29109, cms-sw/cmssw#29110

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
This is expected to fail until cms-sw/cmssw#29110 is merged, because there were some leftover `<use name="cuda-api-wrappers"/>` in a BuildFile, event though it was not actually used.

**Comment by silviodonato** [comment]
please test
I solved a (trivial) conflict in cmssw-tool-conf.spec

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test with cms-sw/cmssw#29110

**Comment by fwyzard** [comment]
>  I solved a (trivial) conflict in cmssw-tool-conf.spec

Thanks.

**Comment by silviodonato** [comment]
cms-sw/cmssw#29110 has been merged

**Comment by fwyzard** [comment]
please merge ?

**Pull request merged**
