### PR TITLE
3.3.5 release of the client

### PR DESCRIPTION
**Pull request by mmascher**
Hi Diego, can you build RPM for this. It's an urgent fix for the crabclient.

Thanks,

### CODE REVIEW

**Comment by amaltaro** [comment]
@mmascher do you need it in the official comp repository or in the comp.pre is good enough for the moment?

**Comment by mmascher** [comment]
Hi @amaltaro , comp.pre is good enough for the moment.
Thanks

**Comment by amaltaro** [comment]
@geneguvo , perhaps you forgot to disable the test instance of the agent build? I successfully built it privately.

**Comment by geneguvo** [comment]
I'm doing tests with the build-agent. Sorry for the messages...

**Comment by geneguvo** [comment]
+1 to ca086f34047bb7a86a78df4878bf933ccf7abc2b on slc5_amd64_gcc461.

**Comment by amaltaro** [comment]
Since it's already in, I'm closing this PR. Thanks

**Pull request closed without merging**
