### PR TITLE
Bump xrootd to 4.8.4

### PR DESCRIPTION
**Pull request by mrodozov**
Update xrootd to new version as requested here: https://github.com/cms-sw/cmsdist/issues/4214

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
landed on the same machine twice, lets see if it's the machine that is slow

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
