### PR TITLE
HG1511 WMCore 1.0.11.pre8

### PR DESCRIPTION
**Pull request by ticoann**
Fixes critical bug on WQ and ReqMgr2

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 351540fd93d8adcceffb7e2d10881b65f7be3bf2 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1934/test_351540f-20151102-061506.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Sorry guys, I had a working patch and then I made a small change to fix a unittest, unfortunately it now creates a set instead of a list and cjson fails to encode it. Please don't merge this one yet, I'm testing again a fix for it. My bad!!!

**Comment by amaltaro** [comment]
You are the man Seangchan! Bruno, please go ahead with this request.

**Comment by ticoann** [comment]
Sorry Bruno for the hassle. And thank you very much Alan for finding the bug and fixing it. It was my mistake that I should have spot it earlier.

**Comment by BrunoCoimbra** [comment]
The PR has been merged! I'm working on deployment and we should have a new testbed release in the next hour.

**Comment by geneguvo** [comment]
+1 to 3835ace2c403a4fbdf8de56f3b8b9d43b67d3d50 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1934/test_3835ace-20151102-161503.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
Thank you very much Bruno!

**Pull request closed without merging**
