### PR TITLE
Upgrade Herwig to v7.2.1, and add patch to fix crash when reading lhe…

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
… files with comments

Backport of #6462 for use in 2018 production

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
looks like EOS issue, CRAB people are reporting xrootd missing files, too

**Comment by Dominic-Stafford** [comment]
From looking quickly at the results of these tests, they don't seem to be problems related to Herwig, so would it be possible to just rerun these test once the eos issues are resolved, please?

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
