### PR TITLE
WMAgent production release candidate 1.4.5; update rucio-clients to 1.24.2.post

### PR DESCRIPTION
**Pull request by amaltaro**
Changes in this PR are:
* bump rucio-clients (both python versions) to `1.24.2.post1`
* bump WMAgent to version `1.4.5`

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 32b247315cfd6df105fa7f1ac4cd3de3901ae0e5 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6615/test_32b2473-20210203-074502.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 75dc7072c57a275e30ced229d174e73b0ffff8f0 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6615/test_75dc707-20210203-092003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@belforte Stefano, I see crabtaskworker depends on `py2-rucio-clients`. Is it okay if I update it to the latest version (I haven't yet tested it).

**Comment by belforte** [comment]
should be OK. I do not think they changed anything that affects us. And I user pretty much same functionalities that you do.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
