### PR TITLE
fix for timestamp handling in coral frontier and sqlite plugins

### PR DESCRIPTION
**Pull request by ggovi**
This PR contains:
- a fix for the timestamp format in insert/update with SQLite coral plugin
- a fix for the timestamp format in selecting with Frontier coral plugin

### CODE REVIEW

**Comment by apfeiffer1** [comment]
please test

**Comment by nclopezo** [comment]
+1
tested building cmssw-tool-conf

**Comment by ggovi** [comment]
Hi, 
I'm not sure how, but this patch has broken the IB.
Some previously added frontier fixes have been reverted...

Currently investigating.

**Comment by davidlt** [comment]
Already solved for 1100 IB. `patchsrc9` was used twice, thus removing one of the patches. We will put CORAL source code into git as the next step, because we used all `patchsrc*` commands.

**Pull request merged**
