### PR TITLE
Update of cxxmodules branch (rebased on ROOT master)

### PR DESCRIPTION
**Pull request by oshadura**
Rebase of cxxmodules branch of Yuka on ROOT master

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @oshadura . I have created a new branch here https://github.com/cms-sw/root/commits/cmscxx/master/9da5b1c based on your changes plus cms patches. Now out automatic tools can keep it up to date with latest root changes unless there are merge conflicts.

**Comment by smuzaffar** [comment]
please test

**Comment by oshadura** [comment]
@smuzaffar thank you so much! I made a mistake and took wrong branch of Yuka (there are too many branches with almost the same name). Can I ask you please to create one more time a new branch + cms patches? Sorry for wasting your time before!

**Comment by smuzaffar** [comment]
sure , no problem @oshadura

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@oshadura , we are getting build time errors. In order to tests the fix quickly you can make a PR against cmscxx/master/9da5b1c branch of https://github.com/cms-sw/root repo.
```
/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/lcg/root/6.17.01-cms/root-6.17.01/core/metacling/src/TCling.cxx: In function 'bool LoadModule(const string&, cling::Interpreter&, bool)':
/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/lcg/root/6.17.01-cms/root-6.17.01/core/metacling/src/TCling.cxx:1110:18: error: redeclaration of 'clang::Preprocessor& PP'
    Preprocessor &PP = interp.getCI()->getPreprocessor();
                  ^~
/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc7_amd64_gcc700/lcg/root/6.17.01-cms/root-6.17.01/core/metacling/src/TCling.cxx:1081:25: note: 'clang::Preprocessor& PP' previously declared here
    clang::Preprocessor &PP = CI.getPreprocessor();
```

full root build log is available https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4802/33751/lcg/root/6.17.01-cms/log

**Comment by oshadura** [comment]
@smuzaffar thank you! I opened PR https://github.com/cms-sw/root/pull/124

**Comment by smuzaffar** [comment]
lets get this in today;s 23h IB

**Pull request merged**
