### PR TITLE
build openloops with mcmodel=medium flag

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmsdist/pull/5215

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc700

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc700

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc700

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc700

**Comment by fabiocos** [comment]
please test workflow 534.0,536.0 for slc7_aarch64_gcc700

**Comment by smuzaffar** [comment]
this does not work for aarch64

**Pull request closed without merging**
