### PR TITLE
May production CRABClient patch

### PR DESCRIPTION
**Pull request by emaszs**

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 549f1a3f05c813bf2117ed68426e04f7c575b515 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3043/test_549f1a3-20170515-175658.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
Hello Emilis
I've started to build the tag to you testbed with the last PR that you did:
https://github.com/cms-sw/cmsdist/pull/3042
So, my question is: I should include this new PR[1] too:
By the testbed deployment.
[1] https://github.com/cms-sw/cmsdist/pull/3043
Thanks.

**Comment by emaszs** [comment]
Ah, I don't think you should care about this PR, CRABClient is deployed on cvmfs automatically once I request a merge.

**Comment by emaszs** [comment]
merge

**Pull request merged**
