### PR TITLE
cuda toolfile: suppress volatile destination type warning

### PR DESCRIPTION
**Pull request by smuzaffar**
See https://github.com/cms-sw/cmssw/issues/45072 for more discussion.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = CUDADataFormats/TrackingRecHit,HeterogeneousCore/CUDAUtilities,RecoLocalTracker/SiPixelRecHits

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by fwyzard** [comment]
@smuzaffar could you move the extra flag into `cuda-flags.file` ?

**Comment by smuzaffar** [comment]
> @smuzaffar could you move the extra flag into `cuda-flags.file` ?

done via https://github.com/cms-sw/cmsdist/pull/9252

**Comment by smuzaffar** [comment]
closing it in favor of https://github.com/cms-sw/cmsdist/pull/9252

**Comment by fwyzard** [comment]
> done via #9252

thanks

**Pull request closed without merging**
