### PR TITLE
Update Intel oneAPI compiler to version 2023.2.0 [13.2.x]

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport #8618

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@perrotta @rappoccio , feel free to merge it for 13.2.X ( it is backport of https://github.com/cms-sw/cmsdist/pull/8618 )

**Comment by smuzaffar** [comment]
@perrotta @rappoccio should we merge this for 13.2.X ? This is not used in production so should not break any thing. It just updated the symlink to newer version of oneapi on protected cvmfs area

**Comment by perrotta** [comment]
+1

**Pull request merged**
