### PR TITLE
Update tensorflow to 2.11

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41873

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , I think you also need to drop the unit tests from cmssw which are using these dropped externals

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41950

**Pull request closed without merging**
