### PR TITLE
CRAB3 October RPMs

### PR DESCRIPTION
**Pull request by mmascher**
The main change is a new improved algorithm to calculate the hash of input sandboxes in the crabcache. It allows to recycle them if the content is the same. I'll post tomorrow more detailed comments tomorrow though.

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 1b9392102f1fe9a00c1117967f4413c5ad9602bd on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1818/test_1b93921-20150922-113536.log" target="_blank">here</a>.

**Comment by mmascher** [comment]
@BrunoCoimbra just pinged me, I missed the -1. It was because I forgot a `git add`

**Comment by geneguvo** [comment]
+1 to c5958f19f92391b903a67c1700db17f53c8e9387 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1818/test_c5958f1-20150922-121527.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to aa4c5ff6818af17e37ab4a9eb870fff78ee2b870 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1818/test_aa4c5ff-20150922-172707.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to d4c812b6aae598667961ecca2c3a1bb6d4137705 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1818/test_d4c812b-20150923-111504.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
Hi Marco,

It is still broken, but now it fails elsewhere:

```
[cmsweb@vocms0127 crabcache]$ tail -n1000 crabcache-20150923.log 
[23/Sep/2015:14:39:34]  WATCHDOG: starting server daemon (pid 3933)
[23/Sep/2015:14:39:34]  INFO: loading data into /crabcache
[23/Sep/2015:14:39:39]  ERROR: terminating due to error, error trace follows
[23/Sep/2015:14:39:39]  ERROR:   Traceback (most recent call last):
[23/Sep/2015:14:39:39]  ERROR:     File "/data/srv/HG1510a-comp/sw.pre.diego/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc6/lib/python2.6/site-packages/WMCore/REST/Main.py", line 387, in start_daemon
[23/Sep/2015:14:39:39]  ERROR:       self.run()
[23/Sep/2015:14:39:39]  ERROR:     File "/data/srv/HG1510a-comp/sw.pre.diego/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc6/lib/python2.6/site-packages/WMCore/REST/Main.py", line 440, in run
[23/Sep/2015:14:39:39]  ERROR:       self.install_application()
[23/Sep/2015:14:39:39]  ERROR:     File "/data/srv/HG1510a-comp/sw.pre.diego/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc6/lib/python2.6/site-packages/WMCore/REST/Main.py", line 240, in install_application
[23/Sep/2015:14:39:39]  ERROR:       module = __import__(module_name, globals(), locals(), [class_name])
[23/Sep/2015:14:39:39]  ERROR:     File "/data/srv/HG1510a-comp/sw.pre.diego/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc6/lib/python2.6/site-packages/UserFileCache/RESTBaseAPI.py", line 6, in <module>
[23/Sep/2015:14:39:39]  ERROR:       from UserFileCache.RESTFile import RESTFile, RESTLogFile, RESTInfo
[23/Sep/2015:14:39:39]  ERROR:     File "/data/srv/HG1510a-comp/sw.pre.diego/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc6/lib/python2.6/site-packages/UserFileCache/RESTFile.py", line 9, in <module>
[23/Sep/2015:14:39:39]  ERROR:       from UserFileCache.RESTExtensions import ChecksumFailed, validate_file, validate_tarfile, authz_login_valid, authz_operator,\
[23/Sep/2015:14:39:39]  ERROR:     File "/data/srv/HG1510a-comp/sw.pre.diego/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc6/lib/python2.6/site-packages/UserFileCache/RESTExtensions.py", line 12, in <module>
[23/Sep/2015:14:39:39]  ERROR:       from WMCore.Services.UserFileCache.UserFileCache import calculateChecksum
[23/Sep/2015:14:39:39]  ERROR:   ImportError: No module named Services.UserFileCache.UserFileCache
[23/Sep/2015:14:39:39]  WATCHDOG: server exited with exit code 1
```

Could you please build/upload/deploy/test it properly?

For now, we're leaving this PR out from the release.

**Comment by mmascher** [comment]
Hi Diego, the last commit should be the right one. 

FWIW yesterday I did the tests and thought it worked, but checking the server logs I can see the exact error you are posting. I have no idea what happened, I remember I did a `crab submit` and I thought it worked, but checking the also the client logs I can see the error in the submission... Bah, I was probably trying to finish it too quickly and my brain misread the output. Again, sorry about that.

**Comment by geneguvo** [comment]
+1 to 391b0f9e51dc3994b16ced7cf4efa5116fdd52f0 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1818/test_391b0f9-20150924-163507.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
Ok. We'll pick it for HG1510b.

**Pull request closed without merging**
