### PR TITLE
Upgrade lhapdf to 6.3.0, sets to 6.3.0f

### LINKED ISSUE #7097: Update LHAPDF 6.3.0
It seems that `lhapdf 6.2.3` python interface does not build with `python 3.9`. There is a newer version `lhapdf 6.3.0` ( https://lhapdf.hepforge.org/install.html ) available. Any objections on updating lhapdf to `6.3.0` ? 

We also have https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/lhapdf_makeLinks.file which creates symlinks for LHAPDF data sets from /cvmfs/cms.cern.ch/lhapdf/pdfsets in to lhapdf package. Currently it is doing it for version `/cvmfs/cms.cern.ch/lhapdf/pdfsets/6.2.3c` ? Instead of creating symlinks for individual pdfsets, can we just create symlink to the top level directory e.g. `lhapdf/share/LHAPDF -> /cvmfs/cms.cern.ch/lhapdf/pdfsets/%{setsversion}` ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/lhapdf.spec#L2 ) ?

### PR DESCRIPTION
**Pull request by mkirsano**
Fixes #7097

### CODE REVIEW

**Comment by mkirsano** [comment]
Explicit dowloading of pdf sets reduced to one set MSTW2008nlo68cl

**Comment by mkirsano** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by agrohsje** [comment]
please test
trying to understand the differences observed in 12_0_0_pre4 and pre6

**Comment by smuzaffar** [comment]
@agrohsje , this PR has been merged. What do you want to achieve by running tests again?

**Comment by agrohsje** [comment]
There was a gen validation report on Thursday and there is an issue with TTbar in 12_0_0_pre4 vs 12_0_0_pre6. Other processes don't show it. At some point we fixed PDF in gridpacks. I wanted to see which tests show differences here. Tests are already gone.

**Comment by agrohsje** [comment]
Problem seems related to a weight update in Pythia 8.3.

**Pull request merged**
