### PR TITLE
Update setuptools to 58.2.0; drop nose, hyperas, hyperopt

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
Not sure why it fails in cmsdist, but works in spack. Here is what Spack does:
```bash
python3 '-s' 'setup.py' '--no-user-cfg' 'build'
python3 '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=%{i}' '--single-version-externally-managed' '--root=%{i}' '--install-purelib=lib/python3.9/site-packages' '--install-platlib=lib/python3.9/site-packages' '--install-scripts=bin' '--install-data=' '--install-headers=include/python3.9'
```
(here the full installation path was replaced with `%{i}` for clarity)

And here is what cmsdist does:
```bash
python3 setup.py build
python3 setup.py install --single-version-externally-managed --record=/dev/null --skip-build --prefix=%{i}
```

**Comment by iarspider** [comment]
Spack log fragment:
```
byte-compiling %{i}/lib/python3.9/site-packages/_distutils_hack/override.py to override.cpython-39.pyc
byte-compiling %{i}/lib/python3.9/site-packages/_distutils_hack/__init__.py to __init__.cpython-39.pyc
running install_egg_info
running egg_info
writing setuptools.egg-info/PKG-INFO
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
writing requirements to setuptools.egg-info/requires.txt
writing top-level names to setuptools.egg-info/top_level.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.py' under directory 'tests'
warning: no files found matching '*.txt' under directory 'docs'
warning: no files found matching '*.conf' under directory 'docs'
warning: no files found matching '*.css' under directory 'docs'
warning: no files found matching '*.css_t' under directory 'docs'
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching 'indexsidebar.html' under directory 'docs'
adding license file 'LICENSE'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
Copying setuptools.egg-info to %{i}/lib/python3.9/site-packages/setuptools-58.2.0-py3.9.egg-info
running install_scripts
creating %{i}/lib/python3.9/site-packages/distutils-precedence.pth
```

cmsdist log:
```
byte-compiling %{i}/lib/python3.9/site-packages/_distutils_hack/__init__.py to __init__.cpython-39.pyc
byte-compiling %{i}/lib/python3.9/site-packages/_distutils_hack/override.py to override.cpython-39.pyc
running install_egg_info
Writing %{i}/lib/python3.9/site-packages/setuptools-58.2.0-py3.9.egg-info
running install_scripts
running build_scripts
error: cannot copy tree 'build/scripts-3.9': not a directory
```

**Comment by iarspider** [comment]
If I run `python3 setup.py egg_info` (as suggested in one of the issues on setuptools github) before `python3 setup.py install`, the build goes through, but `bin` directory is not created (it is also not created with Spack build), so the patching part of the spec breaks. The file  is now in `site-packages/command` dir:
```
$ find ${i} -name 'easy*'
.../lib/python3.9/site-packages/setuptools/command/__pycache__/easy_install.cpython-39.pyc
.../lib/python3.9/site-packages/setuptools/command/easy_install.py
```

But `easy_install` is a deprecated tool (replaced with `pip`), I guess I can just patch the files at their new location, and not create `%{i}/bin/easy_install`, right?

**Comment by iarspider** [comment]
```patch
diff --git a/py3-setuptools.spec b/py3-setuptools.spec
index 016a8a2..2fad229 100644
--- a/py3-setuptools.spec
+++ b/py3-setuptools.spec
@@ -11,12 +11,12 @@ Requires: python3
 %build
 python3 bootstrap.py
 python3 setup.py build
+python3 setup.py egg_info

 %install
 python3 setup.py install --single-version-externally-managed --record=/dev/null --skip-build --prefix=%{i}
 sed -i 's|#!.*python.*|#!/usr/bin/env python3|' \
- %{i}/bin/* \
  %{i}/${PYTHON3_LIB_SITE_PACKAGES}/setuptools/command/easy_install.py \
  %{i}/${PYTHON3_LIB_SITE_PACKAGES}/pkg_resources/_vendor/appdirs.py
-mv %{i}/bin/easy_install %{i}/bin/easy_install3

+mv %{i}/${PYTHON3_LIB_SITE_PACKAGES}/setuptools/command/easy_install.py %{i}/${PYTHON3_LIB_SITE_PACKAGES}/setuptools/command/easy_install3.py
```

**Comment by smuzaffar** [comment]
go ahead and apply the change and restart the tests

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
can you please try building it locally first?

**Comment by iarspider** [comment]
After updating beautifulsoup4 the local build of cmssw-tool-conf went through.

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
the error looks strange. Looks like it somehow download wrong nose sources. 
```
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc900/external/py3-nose/1.3.7-6beff7b8a1760021bdde26867c3bae38/lib/python3.9/site-packages/nose/core.py", line 153
    print "%s version %s" % (os.path.basename(sys.argv[0]), __version__)
```

**Comment by smuzaffar** [comment]
something is broken with new setup tools. The source file we use for py3-nose is http://cmsrep.cern.ch/cgi-bin/cmspkg/SOURCES/cms.week1/8bc4e66e35e9c14157cb4bea08d7236c/source.tar.gz (which is of course py2 based) but with old setuptools I see that pip runs
```
  /build/muz/x/x/w/slc7_amd64_gcc900/external/py3-setuptools/51.3.3-llifpc/lib/python3.9/site-packages/setuptools/lib2to3_ex.py:36: SetuptoolsDeprecationWarning: 2to3 support is deprecated. If the project still requires Python 2 support, please migrate to a single-codebase solution or employ an independent conversion process.
    warnings.warn(
  Fixing build/lib/nose/exc.py build/lib/nose/loader.py build/lib/nose/case.py build/lib/nose/core.py build/lib/nose/selector.py build/lib/nose/proxy.py build/lib/nose/commands.py build/lib/nose/failure.py build/lib/nose/__main__.py build/lib/nose/__init__.py build/lib/nose/result.py build/lib/nose/pyversion.py build/lib/nose/importer.py build/lib/nose/config.py build/lib/nose/inspector.py build/lib/nose/suite.py build/
lib/nose/util.py build/lib/nose/twistedtools.py build/lib/nose/plugins/capture.py build/lib/nose/plugins/multiprocess.py build/lib/nose/plugins/logcapture.py build/lib/nose/plugins/testid.py build/lib/nose/plugins/cover.py build/lib/nose/plugins/failuredetail.py build/lib/nose/plugins/doctests.py build/lib/nose/plugins/manager.py build/lib/nose/plugins/skip.py build/lib/nose/plugins/isolate.py build/lib/nose/plugins/__i
nit__.py build/lib/nose/plugins/allmodules.py build/lib/nose/plugins/xunit.py build/lib/nose/plugins/errorclass.py build/lib/nose/plugins/plugintest.py build/lib/nose/plugins/collect.py build/lib/nose/plugins/builtin.py build/lib/nose/plugins/prof.py build/lib/nose/plugins/attrib.py build/lib/nose/plugins/base.py build/lib/nose/plugins/deprecated.py build/lib/nose/plugins/debug.py build/lib/nose/sphinx/pluginopts.py bui
ld/lib/nose/sphinx/__init__.py build/lib/nose/ext/__init__.py build/lib/nose/ext/dtcompat.py build/lib/nose/tools/nontrivial.py build/lib/nose/tools/__init__.py build/lib/nose/tools/trivial.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  Fixing build/lib/nose/exc.py build/lib/nose/loader.py build/lib/nose/case.py build/lib/nose/core.py build/lib/nose/selector.py build/lib/nose/proxy.py build/lib/nose/commands.py build/lib/nose/failure.py build/lib/nose/__main__.py build/lib/nose/__init__.py build/lib/nose/result.py build/lib/nose/pyversion.py build/lib/nose/importer.py build/lib/nose/config.py build/lib/nose/inspector.py build/lib/nose/suite.py build/
lib/nose/util.py build/lib/nose/twistedtools.py build/lib/nose/plugins/capture.py build/lib/nose/plugins/multiprocess.py build/lib/nose/plugins/logcapture.py build/lib/nose/plugins/testid.py build/lib/nose/plugins/cover.py build/lib/nose/plugins/failuredetail.py build/lib/nose/plugins/doctests.py build/lib/nose/plugins/manager.py build/lib/nose/plugins/skip.py build/lib/nose/plugins/isolate.py build/lib/nose/plugins/__i
nit__.py build/lib/nose/plugins/allmodules.py build/lib/nose/plugins/xunit.py build/lib/nose/plugins/errorclass.py build/lib/nose/plugins/plugintest.py build/lib/nose/plugins/collect.py build/lib/nose/plugins/builtin.py build/lib/nose/plugins/prof.py build/lib/nose/plugins/attrib.py build/lib/nose/plugins/base.py build/lib/nose/plugins/deprecated.py build/lib/nose/plugins/debug.py build/lib/nose/sphinx/pluginopts.py bui
ld/lib/nose/sphinx/__init__.py build/lib/nose/ext/__init__.py build/lib/nose/ext/dtcompat.py build/lib/nose/tools/nontrivial.py build/lib/nose/tools/__init__.py build/lib/nose/tools/trivial.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
```

but this is not true for new setup tools https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-90434f/19772/external/py3-nose/1.3.7-6beff7b8a1760021bdde26867c3bae38/log and it does complain about 
```
Installing collected packages: nose
  *** Error compiling '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/tmp/BUILDROOT/6beff7b8a1760021bdde26867c3bae38/opt/cmssw/slc7_amd64_gcc900/external/py3-nose/1.3.7-6beff7b8a1760021bdde26867c3bae38/lib/python3.9/site-packages/nose/config.py'...
    File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/tmp/BUILDROOT/6beff7b8a1760021bdde26867c3bae38/opt/cmssw/slc7_amd64_gcc900/external/py3-nose/1.3.7-6beff7b8a1760021bdde26867c3bae38/lib/python3.9/site-packages/nose/config.py", line 68
      except ConfigParser.Error, exc:
                               ^
  SyntaxError: invalid syntax
  
  *** Error compiling '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/tmp/BUILDROOT/6beff7b8a1760021bdde26867c3bae38/opt/cmssw/slc7_amd64_gcc900/external/py3-nose/1.3.7-6beff7b8a1760021bdde26867c3bae38/lib/python3.9/site-packages/nose/core.py'...
    File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/tmp/BUILDROOT/6beff7b8a1760021bdde26867c3bae38/opt/cmssw/slc7_amd64_gcc900/external/py3-nose/1.3.7-6beff7b8a1760021bdde26867c3bae38/lib/python3.9/site-packages/nose/core.py", line 153
      print "%s version %s" % (os.path.basename(sys.argv[0]), __version__)
```

**Comment by iarspider** [comment]
Yup, setuptools >= 58 no longer support running 2to3 during builds: https://setuptools.pypa.io/en/latest/history.html#v58-0-0

**Comment by iarspider** [comment]
Since nose (nose1) is not developed anymore, maybe we can create a copy of the code after running 2to3 under cms-externals?

**Comment by smuzaffar** [comment]
sounds good to me, no idea how many other packages are doing it? Can you please do the following
- locally get existing cmsdist ( i.e. with old setup tools)
- edit setuptool spec and add a comment ( i.e force it to rebuild)
- build cmssw-tol-conf local and then search for `lib2to3_ex.py` in the build logs?

**Comment by iarspider** [comment]
Only two packages in IB/CMSSW_12_1_X/master branch of cmsdist rely on 2to3: py3-nose and py3-beautifulsoup4. The latter does not rely on 2to3 in version 4.10.0 .

**Comment by smuzaffar** [comment]
so update beautifulsoup4 to 4.10.0 and patch nose

**Comment by iarspider** [comment]
yes

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by davidlange6** [comment]
(maybe too late...) instead of doing work to support nose, it looks like we could drop it if we drop rep, hyperopt and hyperas. None of these are particularly actively developed now.

**Comment by smuzaffar** [comment]
> (maybe too late...) instead of doing work to support nose, it looks like we could drop it if we drop rep, hyperopt and hyperas. None of these are particularly actively developed now.

I am all in favor of dropping these, do we have any use of these in cmssw?

**Comment by smuzaffar** [comment]
we only have two unit tests for these https://github.com/cms-sw/cmssw/blob/efd752350175907928442f8c3e28f9dc6b733196/PhysicsTools/PythonAnalysis/test/BuildFile.xml#L68-L69 otherwise I do not see any usaged of these packages.

**Comment by smuzaffar** [comment]
@iarspider , dropping these packages from requirements.txt is not enough. You need to cleanup their deps e.g.
https://github.com/cms-sw/cmsdist/search?q=py3-hyperas
https://github.com/cms-sw/cmsdist/search?q=py3-hyperopt
https://github.com/cms-sw/cmsdist/search?q=py3-nose
https://github.com/cms-sw/cmsdist/search?q=py3-rep

please check if pkgconfig really needs `nose` ?

**Comment by smuzaffar** [comment]
looks like `py3-nose` is needed by https://github.com/cms-sw/cmsdist/blob/9da9c39fd5deeab5d9bb1d177f0efa5a0de82464/pip/pkgconfig.file too. so may be cleaning this up is not that trivil

**Comment by iarspider** [comment]
Yes, working on it. The dependency of pkgconfig on nose is weird...

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#35878

**Comment by iarspider** [comment]
@smuzaffar this RelVal fails in other PRs, so I think it's safe to merge this one.

**Comment by iarspider** [comment]
merge

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
closing as it has been integrated via https://github.com/cms-sw/cmsdist/pull/7696

**Pull request closed without merging**
