### PR TITLE
Update the rest of the ROOT deps

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
lets try again before checking the bot

**Comment by gudrutis** [comment]
Please test

**Comment by gudrutis** [comment]
@mrodozov, I introduced a bug which I fixed.

**Comment by mrodozov** [comment]
wait for the local build to finish to be certain it builds.

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
last commit fixes 2 of 3 unit test failures. For the third is not clear

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
