### PR TITLE
Update cms-tfaot and test models.

### PR DESCRIPTION
**Pull request by riga**
This PR updates the [cms-tfaot](https://github.com/cms-externals/cms-tfaot) python tools, which slightly update the AOT compilation workflow.

- Remove redundant wrapper header.
- Fix typo in dev workflow instructions.
- Header parsing contains input / output types.

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/44586

**Comment by smuzaffar** [comment]
please test

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
