### PR TITLE
updates geant4 data files  G4EMLOW6.54 and G4PhotonEvaporation5.0

### PR DESCRIPTION
**Pull request by iahmad-khan**
https://github.com/cms-externals/geant4/issues/19

### CODE REVIEW

**Comment by civanch** [comment]
@iahmad-khan , @smuzaffar , this PR may be tested successfully together with Geant4 10.4b01 - both code and data files. I have tested compilation - it is OK, no change in CMSSW is needed. If will start test run of new data with old G4 or new G4 with old data there will be problems.

**Comment by iahmad-khan** [comment]
please test

**Comment by civanch** [comment]
@iahmad-khan , test problem connected with the fact that we do not update two other datafiles: G4ENSDFSTATE and RadioactiveDecay. Both where already integrated into externals, when we add previous Geant4 version into DEVEL branch. It is G4ENSDFSTATE2.1 and G4RadioactiveDecay5.1.1

**Comment by iahmad-khan** [comment]
please test

**Comment by civanch** [comment]
@iahmad-khan , for me you updates are OK but it seems that for some reason old G4ENSDFSTATE is used.

**Comment by davidlange6** [comment]
@iahmad-khan @civanch - it doesn't look like the updates were correct... 

*** G4Exception : PART70002
      issued by : G4NuclideTable
5.609049e+17 is not valid indicator of G4Ions::G4FloatLevelBase. You may use a wrong version of ENSDFSTATE data. Please use G4ENSDFSTATE2.0 or later.
*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------

%MSG
%MSG-w G4cerr:  (NoModuleName) 10-Jul-2017 12:18:27 CEST pre-events

%MSG
%MSG-w G4cerr:  (NoModuleName) 10-Jul-2017 12:18:27 CEST pre-events
*** G4Exception: Aborting execution ***
%MSG

**Comment by smuzaffar** [comment]
looks like a bug in our cmsdist testing script. I am looking in to it.

**Comment by smuzaffar** [comment]
please test
test will fail anyway as root6 IBs (based on root master) are broken anyway.

**Comment by civanch** [comment]
When I try to find G4EMLOW6.54 inside /cvmfs/cms-ib.cern.ch/.... I fail, there are only 6.48 and 6.50, is it OK?

**Comment by smuzaffar** [comment]
yes this is correct. New G4 data packages are part of this PR and will only be available when we merge this PR.

**Comment by civanch** [comment]
All crashes happens at step3 in similar place:

In file included from DPGAnalysisSiStripTools_xr dictionary payload:52:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02480/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_3_ROOT6_X_2017-07-09-2300/src/DPGAnalysis/SiStripTools/interface/Multiplicities.h:21:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02480/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_3_ROOT6_X_2017-07-09-2300/src/FWCore/ParameterSet/interface/ParameterSet.h:15:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02480/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_3_ROOT6_X_2017-07-09-2300/src/FWCore/ParameterSet/interface/Entry.h:23:
/cvmfs/cms-ib.cern.ch/nweek-02480/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_3_ROOT6_X_2017-07-09-2300/src/DataFormats/Provenance/interface/LuminosityBlockID.h:84:17: error: no matching member function for call to 'doOp'
         return doOp<std::less>(iRHS);

**Comment by smuzaffar** [comment]
yes these are failure due to root6 and root team is looking in to these.

**Pull request merged**
