### PR TITLE
[10.3.X] update sherpa to 2.2.5

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
FYI @alberto-sanchez, @GurpreetSinghChahal, @qliphy, @efeyazgan

**Comment by alberto-sanchez** [comment]
Thanks a lot! 
Eventually we need this in MC production branches: 10_2 and 9_3

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
please test workflow 534.0

**Comment by fabiocos** [comment]
@alberto-sanchez which kind of validation of this new external version has been done so far?

**Comment by alberto-sanchez** [comment]
@fabiocos , we are working on that.

**Comment by alberto-sanchez** [comment]
test running so far shown not statistically discrepancies.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
