### PR TITLE
Update geant4 to version 11.2.ref08, update datasets

### PR DESCRIPTION
**Pull request by iarspider**
As requested in https://github.com/cms-externals/geant4/issues/85

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_2_GEANT4_X

**Comment by smuzaffar** [comment]
please test with #9453 for CMSSW_14_2_GEANT4_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_GEANT4_X

**Comment by smuzaffar** [comment]
please test with #9455 for CMSSW_14_2_GEANT4_X

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/9455 for CMSSW_14_2_GEANT4_X

**Comment by smuzaffar** [comment]
+externals

looks good to go in for G4 IBs

**Comment by smuzaffar** [comment]
cleaned up flags not used by cmake
```
  Manually-specified variables were not used by the project:

    CMAKE_STATIC_LIBRARY_CXX_FLAGS
    CMAKE_STATIC_LIBRARY_C_FLAGS
    DD4HEP_USE_PYROOT
    EXPAT_ROOT_DIR
```

**Pull request merged**
