### PR TITLE
Updated root to tip of branch v6-26-00-patches

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
test parameters:

* full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
test-edmpickevents and test-das-selected-lumis failed due to proxy parsing error. TestIOPoolInputNoParentDictionary failed with
```
no StreamerInfo found in <...>/DataFormatsTestObjects_xr_rdict.pcm therefore preventing schema evolution when reading this file. The file was produced with version 6.26/07 of ROOT.
```

@smuzaffar

**Comment by iarspider** [comment]
@aandvalenzuela commented on previous PR to update root-patches:
> TestIOPoolInputNoParentDictionary is expected due to version update.

**Comment by smuzaffar** [comment]
looks good but we will hold on to updating it for now ( waiting for root6.26 validation)

**Pull request closed without merging**
