### PR TITLE
Add skipped lumis and NanoAOD support to t0wmadatasvc

### PR DESCRIPTION
**Pull request by germanfgv**

### CODE REVIEW

**Comment by arooshap** [comment]
+1 to d7604794610a63335645afe0f31d5ebe4d780365 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8593/test_d760479-20230714-151002.log" target="_blank">here</a>.

**Comment by arooshap** [comment]
-1 to db574efcd9fc8134331d295cfc71a1f6c4a7a481 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8593/test_db574ef-20230714-165002.log" target="_blank">here</a>.

**Comment by germanfgv** [comment]
merge

**Comment by amaltaro** [comment]
@germanfgv German, you merged this while it was failing to build the package. Now I can't get to build a WMAgent release because it fails fetching the t0wmadatasvc:
https://github.com/cms-sw/cmsdist/pull/8594

Sorry, but I will have to revert this PR. Please create a new one and only merge once the build is successful please.

**Comment by germanfgv** [comment]
Hi @amaltaro.  I apologize, I got confused by the first successful test. We will move directly to a newer version of the service.

**Pull request merged**
