### PR TITLE
initial patch for mock

### PR DESCRIPTION
**Pull request by ticoann**
replacing #1901

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 907b3a5ec93fb17f595709e2cadc7cb7a5f2c552 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1929/test_907b3a5-20151028-005504.log" target="_blank">here</a>.

**Comment by ericvaandering** [comment]
I want to follow this

**Comment by ticoann** [comment]
Ah, yes, I miss that. Thanks Alan and don't be sorry. I make a lot more mistakes. :smile:

**Comment by geneguvo** [comment]
-1 to fe684995888e9ba7f2b5a26c5f4b0fdc92e7fb02 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1929/test_fe68499-20151028-180503.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
-1 to 42c1ea64a9f95bb46931eb4df269f2e3daf589b6 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1929/test_42c1ea6-20151028-181504.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
-1 to ce7320e7c0cb5a1d4513291d45d472cf6bd630c5 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1929/test_ce7320e-20151028-210503.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 0074a4c2e6f8086f18b9e8d1b49be97a5db6d640 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1929/test_0074a4c-20151028-222504.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
@geneguvo, Hi Diego, it seems all the dependencies for the mock is sorted now. Thank you for your help. Please review.

**Comment by geneguvo** [comment]
It worked on a test I did on the build machine. Soon I'll try it on a devvm.

One thing I noticed is that py2-six updated to 1.10.0. This package is also used by py2-jsonpath-rw, which in turn is used by DAS. I don't think that would cause any problem, but better @vkuznet be aware of that.

**Comment by vkuznet** [comment]
Diego,
it seems that py2-jsonpath-rw is used by DAS keyword search server written by
Vidmandas, so I'll need to validate the change once we'll switch to new
version.
Valentin.

**Comment by geneguvo** [comment]
Valentin, so would you be ok if I push this now? if we'd do another testbed, you can validate das there.

Btw. I've tested mock in my devvm and it worked.

**Comment by vkuznet** [comment]
Yes, I'm ok, as I said this part is used in keyword search which is a
supplement to DAS functionality and if it will become broken it
will have limited impact. Once it would be on testbed I can easily test this
part.
V.

**Comment by geneguvo** [comment]
Done. Pushed.

**Pull request closed without merging**
