### PR TITLE
Update cmssw-wm-tools.spec

### PR DESCRIPTION
**Pull request by davidlange6**
pick up the right python version based on what the cmssw fwk is using.

@smuzaffar - can you have a look at the changes and push to cvmfs if they look ok to you. 
https://github.com/cms-sw/cmssw-wm-tools/commit/dd8396181a6d483e53ce7a23235575c8a72ef463

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , this looks good to me. Any objection on merging it and deploying it or you would like to wait for @amaltaro feedback?

**Comment by davidlange6** [comment]
I think we can go ahead and merge it - that will make their tests easier (or we can wait until later, as you prefer)

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
