### PR TITLE
Update lwtnn to 2.13

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
Versions newer than 2.10 does not work with Eigen 3.4+ (the version in cmsdist is 3.4.90)

**Comment by iarspider** [comment]
Reopening: https://github.com/lwtnn/lwtnn/issues/161#issuecomment-1101471887

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc11

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc10

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc10

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
