### PR TITLE
Adding crab3 to cms-common

### PR DESCRIPTION
**Pull request by juztas**
@mmascher @davidlt @ktf 
For testing purpose I used my private git repository. Whenever it will be merged to crabclient repo, I will use tag name and not master for source ... Let me know if I am missing something.

Signed-off-by: Justas Balcas juztas@gmail.com

### CODE REVIEW

**Comment by davidlt** [comment]
I would suggest testing this on AFS first before pushing to CVMFS. `cms-common` is built and installed separately from `cmssw`.

**Comment by ktf** [comment]
This still sources crab provided dependencies, which IMHO is a bad idea. IMHO you should not source anything if $CMSSW_BASE is set, so that you can get consistent dependencies.

**Comment by davidlt** [comment]
There is useful bash snippet 

```
[ -z "$CLEANED" ] && exec /usr/bin/env -i CLEANED=1 /bin/sh "$0" "$@"
```

Which would re-execute the wrapper in "a clean" environment (no more CMSSW changes).

**Comment by smuzaffar** [comment]
why crab-client and crab2to3-client has hard coded path to /cvmfs/cms.cern.ch ? May be we should generate these scripts from cms-common itself. Also these scripts source /cvmfs/cms.cern.ch/crab3/crab_$os.sh file which sources init.sh for various binary packages (gcc, zlib, etc.). I would suggest that add a guard in /crab3/crab.sh  and source /cvmfs/cms.cern.ch/crab3/slc5_amd64_gcc461/cms/crabclient/3.3.8/etc/profile.d/dependencies-setup.sh only is scram env (SCRAMRT_SET env variable) is not set

**Comment by davidlt** [comment]
@smuzaffar CRAB3 is only installed on CVMFS, that's the only place where you can find it AFAIK.

**Comment by ktf** [comment]
what's the status of this? can we close it?

**Comment by juztas** [comment]
Closing. @mmascher is working on another solution.

**Pull request closed without merging**
