### PR TITLE
Update PycURL to 7.43.0.3 and build with pip

### PR DESCRIPTION
**Pull request by amaltaro**
@todor-ivanov here is the change that works out of the box for me (well, I can build and upload RPMs).
Note that I haven't made any changes to the curl.spec file. I tried to update curl to the same version used in the CMSSW branch, but I get failures building webdoc and/or dqmgui (no clue what the problem is).

Could you please test this PR - install WMAgent for instance, load the libraries and run your snippet to test DNS queries - and follow up any further changes that become necessary?

You can use my private repo: http://cmsrep.cern.ch/cgi-bin/repos/comp.amaltaro/slc7_amd64_gcc630?C=M;O=D

which has packages built with the new pycurl version. If you want to install WMAgent, you need to provide version `1.2.8-comp8`.
Thanks

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 1b34c6cef6ef59697d71239f25442b2e811db17d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5420/test_1b34c6c-20191212-104004.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
It does not work. Don't merge.

**Comment by todor-ivanov** [comment]
@amaltaro as we discussed and you tested earlier today it does not work. I am doing some more tests now. I will either update this PR or make a new one.

**Comment by smuzaffar** [comment]
@amaltaro , please look in to https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_1_X/master/pip/pycurl.file 
e.g. please set the following in your py*-pycurl.spec . this allows curl to use openssl backend

```
%define PipBuildOptions --global-option="--with-openssl" --global-option="--openssl-dir=${OPENSSL_ROOT}" 
%define PipPreBuild export PYCURL_SSL_LIBRARY=openssl
```

**Comment by amaltaro** [comment]
Thanks, Shahzad. With your suggestion I was able to properly build curl/pycurl and also import pycurl with no issues:
```
>>> import pycurl
>>> pycurl.version
'PycURL/7.43.0.3 libcurl/7.35.0 OpenSSL/1.0.1r zlib/1.2.8'
```

@todor-ivanov can you either:
* log in to vocms0262 and give that pycurl version (in WMAgent environment) another try to see if dns queries are okay now?
* or, use my private repo that was built with changes in the 2nd commit in this PR and play as you like.

My private repo is:
http://cmsrep.cern.ch/cgi-bin/repos/comp.amaltaro/slc7_amd64_gcc630?C=M;O=D

and here is the agent RPM to be used:
cms+wmagent+1.2.8-comp7-1-1.slc7_amd64_gcc630.rpm

**Comment by muhammadimranfarooqi** [comment]
+1 to b38442e52ea5c993a297cdf3da98d8a50301c071 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5420/test_b38442e-20191218-065505.log" target="_blank">here</a>.

**Comment by todor-ivanov** [comment]
@amaltaro 
I can confirm it works with the libcurl version from you repository. Here is the dump of the system trace:
```
========================================================================                                                                             
pycurl version: PycURL/7.43.0.3 libcurl/7.35.0 OpenSSL/1.0.1r zlib/1.2.8   
========================================================================
...
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3                                                                                                                                                                                                                    
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = 0                                                                                                                                                                                                         
sendto(3, "\2\0\0\0\16\0\0\0\27\0\0\0cmsweb-testbed.cern."..., 35, MSG_NOSIGNAL, NULL, 0) = 35                                                                                                                                                                                     
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])                                                                                                                                                                                      
read(3, "\2\0\0\0\1\0\0\0\2\0\0\0\10\0\0\0\27\0\0\0\0\0\0\0", 24) = 24                                                                                                                                                                                                            
read(3, "\274\270B\372\274\270@\232\2\2cmsweb-testbed.cern.ch"..., 33) = 33                                                                                                                                                                                                       
close(3)                                = 0                                                           
...
```

**Comment by muhammadimranfarooqi** [comment]
+1 to 8b4c9b4263489a6a51a332beae103aa4ef45f01a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5420/test_8b4c9b4-20191218-164506.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@amaltaro @todor-ivanov 

Should I merge and include this PR in the coming CMSWEB release?

Best
Imran

**Comment by todor-ivanov** [comment]
Hi @muhammadimranfarooqi ,
It should be either this one or  [1]. They will create conflict if merged together I beleive.

https://github.com/cms-sw/cmsdist/pull/5438

**Comment by amaltaro** [comment]
Superseeded by https://github.com/cms-sw/cmsdist/pull/5438
Closing this one!

**Pull request closed without merging**
