### PR TITLE
Update cmsmon-tools.spec

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar I'm not sure I wrote the `%setup` commands correctly - but at least it works. Also, should I uncomment and change `REVISION` https://github.com/cms-sw/cmsdist/blob/4cce242d626017c58b9a81b001bfd6914d148a8e/cmsmon-tools.spec#L100 ?

**Comment by smuzaffar** [comment]
@iarspider , `#CMSDIST_FILE_REVISION=1` should only be updated if the script's contents itself are updated and it should remain commented as [common_revision_script](https://github.com/cms-sw/cmsdist/blob/e0ddfdbc53c5daab74a70407a9d444a67b451bfd/rpm-preamble.file#L267-L271 )  search for this comment. So no need to uncomment/update CMSDIST_FILE_REVISION

**Comment by iarspider** [comment]
@smuzaffar thanks!

**Comment by smuzaffar** [comment]
+externals

**Review by smuzaffar — APPROVED** [review]

**Pull request merged**
