### PR TITLE
xerces 3.1 for cmssw 8 1 x/gcc530

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by smuzaffar** [comment]
cmsbuild, please test

**Comment by davidlt** [comment]
Note, that this needs changes on CMSSW side (the last time I checked). Thus I would advice adding it to DEVEL IBs first to prepare patch for CMSSW.

**Comment by smuzaffar** [comment]
@davidlt, yes I know. Just wanted to make sure that all external builds.
Agree that this should first go in DEVEL IB.

**Comment by smuzaffar** [comment]
@iahmad-khan , please make same PR for gcc530next branch so that we can test it in DEVEL IBs along with cms-sw/cmssw#14585

**Pull request closed without merging**
