### PR TITLE
[10.4.X] Added PhysicsTools-PatUtils data tool

### PR DESCRIPTION
**Pull request by smuzaffar**
New PhysicsTools-PatUtils data package introduced. This includes all the data files of cmssw/PhysicsTools/PatUtils/data. 

This can be merge with or before https://github.com/cms-sw/cmssw/pull/25380

### CODE REVIEW

**Comment by perrotta** [comment]
@smuzaffar @fabiocos : could this be merged since now? It only adds new files to the externals, and until #25380 is merged it does nothing (i.e. it can't harm). Thank you

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
@smuzaffar : backports to 10_2_X and 9_4_X are also needed.
Could you please take care of them? Thank you

**Pull request merged**
