### PR TITLE
Revert "Revert "Triton v2.3""

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmsdist#6296
This is same as https://github.com/cms-sw/cmsdist/pull/6293 which was wrongly merged without the requires  cms-sw/cmssw#31715
This should be merged with cms-sw/cmssw#31715 
FYI @qliphy , @silviodonato , @kpedro88

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- pull_request=cms-sw/cmssw#31715

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@smuzaffar what's the problem here?

**Comment by kpedro88** [comment]
please test

**Comment by smuzaffar** [comment]
issue might be with https://github.com/cms-sw/cmsdist/pull/6294 which I have reverted now.

**Comment by smuzaffar** [comment]
I have restarted the test, should be good now

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov please sign

**Comment by silviodonato** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
