### PR TITLE
Change root to Release (needed for perf measurements)

### PR DESCRIPTION
**Pull request by oshadura**
CC: @davidlange6 @vgvassilev

### CODE REVIEW

**Comment by oshadura** [comment]
@mrodozov can you help to trigger tests please? We needed this for next IB (running tonight or tomorrow fine as well). Thank you so much!

**Comment by mrodozov** [comment]
allow @oshadura test rights

**Comment by mrodozov** [comment]
please test

**Comment by davidlange6** [comment]
lets just merge this before the 2300 build.. I can do it if no one else does

**Comment by mrodozov** [comment]
+externals
merge it and I can stop the tests, it will break anyway so no point to keep the test running

**Comment by silviodonato** [comment]
+1

**Comment by mrodozov** [comment]
Thats definitely breaking because of the tensorflow changes, I just still rationalize how. But the change can go as it is

**Comment by silviodonato** [comment]
merge

**Comment by davidlange6** [comment]
Yea, likely not related…  there is a class of problems that seem to come out in the PR tests (especially in modules builds perhaps..)

On Feb 26, 2020, at 11:27 AM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:


Thats definitely breaking because of the tensorflow changes, I just still rationalize how. But the change can go as it is

**Pull request merged**
