### PR TITLE
[11.1.X] Retrained particle ID model and energy regression for HLT TDR

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #6562

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@slava77 , I assume that comparison diff here are same as we have seen for https://github.com/cms-data/RecoHGCal-TICL/pull/2 ? If you are OK with these then we can merge it for 11.1.X too.

**Comment by silviodonato** [comment]
urgent
(for HLT TDR)

**Comment by slava77** [comment]
> @slava77 , I assume that comparison diff here are same as we have seen for [cms-data/RecoHGCal-TICL#2](https://github.com/cms-data/RecoHGCal-TICL/pull/2) ? If you are OK with these then we can merge it for 11.1.X too.

yes, they look quite similar; it should be OK to go ahead wrt reco.

**Comment by smuzaffar** [comment]
+externals
thanks @slava77  for the confirmation

**Pull request merged**
