### PR TITLE
Enable LTO for IBs using master branch

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
And here the new branch for non-LTO IBs: https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_13_1_X/nonlto

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- skip_tests = static,header

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#40857

**Comment by smuzaffar** [comment]
+externals
@perrotta @rappoccio this change will enable LTO for 13.1.X IBs. We will also disable special LTO IBs but build a NONLTO_X IBs (just in case)

**Pull request merged**
