### PR TITLE
Update tensorflow 1.12.0

### PR DESCRIPTION
**Pull request by mrodozov**
Updates #4560 
Uses eigen, libjpeg-turbo and protobuf from cmsdist.

### CODE REVIEW

**Comment by gartung** [comment]
@mrodozov There is a new build target //tensorflow:install_headers see
https://github.com/cmsexternals/tensorflow/commit/39e324505c380c9d449dc31d34629a9d470c765f
I added this line to the spec

bazel $BAZEL_OPTS $BAZEL_EXTRA_OPTS //tensorflow:install_headers

I am not sure where the headers are put, but you may not need the whole copy headers section.

**Comment by mrodozov** [comment]
please test

**Comment by gartung** [comment]
@mrodozov @smuzaffar @Dr15Jones

The error is in the lite kernel. The version of eigen3 is too new.  This tflite kernel was moved recently on tensorflow master, which uses a newer version of eigen3.


  /home/gartung/cms-build/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/home/gartung/cms-build/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/_objs/eigen_support/eigen_support.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/_objs/eigen_support/eigen_support.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -iquote . -iquote bazel-out/k8-opt/genfiles -iquote bazel-out/k8-opt/bin -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote bazel-out/k8-opt/bin/external/bazel_tools -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/gemmlowp -iquote bazel-out/k8-opt/genfiles/external/gemmlowp -iquote bazel-out/k8-opt/bin/external/gemmlowp -iquote external/arm_neon_2_x86_sse -iquote bazel-out/k8-opt/genfiles/external/arm_neon_2_x86_sse -iquote bazel-out/k8-opt/bin/external/arm_neon_2_x86_sse -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive '-std=c++11' -DFARMHASH_NO_CXX_STRING -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK '-Wno-error=reorder' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/contrib/lite/kernels/eigen_support.cc -o bazel-out/k8-opt/bin/tensorflow/contrib/lite/kernels/_objs/eigen_support/eigen_support.pic.o)
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_oss.h:97:0,
                 from ./tensorflow/contrib/lite/kernels/internal/optimized/eigen_spatial_convolutions.h:37,
                 from tensorflow/contrib/lite/kernels/eigen_support.cc:20:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file" [-Wcpp]
 #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorDeviceGpu.h file"
  ^~~~~~~
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_oss.h:112:0,
                 from ./tensorflow/contrib/lite/kernels/internal/optimized/eigen_spatial_convolutions.h:37,
                 from tensorflow/contrib/lite/kernels/eigen_support.cc:20:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReductionCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorReductionGpu.h file" [-Wcpp]
 #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorReductionGpu.h file"
  ^~~~~~~
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_oss.h:131:0,
                 from ./tensorflow/contrib/lite/kernels/internal/optimized/eigen_spatial_convolutions.h:37,
                 from tensorflow/contrib/lite/kernels/eigen_support.cc:20:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorContractionCuda.h:3:2: warning: #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorContractionGpu.h file" [-Wcpp]
 #warning "Deprecated header file, please either include the main Eigen/CXX11/Tensor header or the respective TensorContractionGpu.h file"
  ^~~~~~~
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_oss.h:109:0,
                 from ./tensorflow/contrib/lite/kernels/internal/optimized/eigen_spatial_convolutions.h:37,
                 from tensorflow/contrib/lite/kernels/eigen_support.cc:20:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:52:30: error: 'TensorBlock' in namespace 'EigenForTFLite::internal' does not name a template type
   typedef typename internal::TensorBlock<
                              ^~~~~~~~~~~
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:52:41: error: expected unqualified-id before '<' token
   typedef typename internal::TensorBlock<
                                         ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:55:30: error: 'TensorBlockReader' in namespace 'EigenForTFLite::internal' does not name a template type
   typedef typename internal::TensorBlockReader<
                              ^~~~~~~~~~~~~~~~~
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:55:47: error: expected unqualified-id before '<' token
   typedef typename internal::TensorBlockReader<
                                               ^

**Comment by gartung** [comment]
This may require changing the Eigen namespace name in the copy of Eigen that tensorflow is using.

**Comment by fwyzard** [comment]
The idea was to have a *single* version of Eigen for Tensorflow and the rest of CMSSW.

**Comment by gartung** [comment]
We can try the  head of tensorflow master, but even that may use a version of Eigen that is not compatible with your changes. Tensorflow uses a commit off of the Eigen3 default branch. It looks like we are using a commit off of the Eigen3 3.3 branch.

**Comment by fwyzard** [comment]
No, we have been using the default (master) branch of Eigen for quite some time now.

**Comment by gartung** [comment]
Yes, but Tensorflow 1.12 is using a commit from Eigen3 master from July 2018.  We need to move to tensorflow master to get a compatible version of Eigen3.

**Comment by fwyzard** [comment]
OK, to clarify:

tensorflow 1.12.0 uses

    git commit:  f21be5f8d1591d2e2f774af30cb265b5781c4ce9
    changeset:   10938:fd6845384b86
    parent:      10937:c97c855bcc44
    parent:      10935:e5e305a158a0
    user:        Rasmus Munk Larsen <rmlarsen@google.com>
    date:        Fri Jun 22 15:09:44 2018 -0700
    summary:     merge


CMSSW uses

    git commit:  01ae86b9aad30b1e65cf1b749fd6cd9a645ac00d
    changeset:   11416:66ba78bf7efa
    parent:      11415:da648b5b9177
    user:        Christoph Hertzberg <chtz@informatik.uni-bremen.de>
    date:        Tue Sep 25 20:26:16 2018 +0200
    summary:     Don't deactivate BVH test for clang (probably, this was failing for very old versions of clang)

Both are from the Eigen3 master branch, not from the 3.3 branch.
I haven't looked at what changes affect Tensorflow, yet.

**Comment by mrodozov** [comment]
> We need to move to tensorflow master to get a compatible version of Eigen3.

I'm doing exactly that but as far as I can tell tf/master is still using the Eigen source used in tf/1.12 
https://github.com/tensorflow/tensorflow/compare/master...cms-externals:cms/v1.12.0

(where cms/v1.12.0 is tag 1.12.0 with our patches on top)

Would you pls show me what do you refer to

**Comment by gartung** [comment]
You are correct. I did not check that they updated the eigen source on tensorflow master.

**Comment by fwyzard** [comment]
@mrodozov , you can find the mercurial changeset used by Tensorflow in `tensorflow/workspace.bzl`.
v1.12.0 has
```
    tf_http_archive(
        name = "eigen_archive",
        build_file = clean_dep("//third_party:eigen.BUILD"),
        sha256 = "d956415d784fa4e42b6a2a45c32556d6aec9d0a3d8ef48baee2522ab762556a9",
        strip_prefix = "eigen-eigen-fd6845384b86",
        urls = [
            "https://mirror.bazel.build/bitbucket.org/eigen/eigen/get/fd6845384b86.tar.gz",
            "https://bitbucket.org/eigen/eigen/get/fd6845384b86.tar.gz",
        ],
    )
```
while the master has
```
    tf_http_archive(
        name = "eigen_archive",
        build_file = clean_dep("//third_party:eigen.BUILD"),
        sha256 = "df54d805573871d03aaef6d27d45439c18ff6e8db215a3b922b2daefd6914147",
        strip_prefix = "eigen-eigen-ad3bcd81cc49",
        urls = [
            "https://mirror.bazel.build/bitbucket.org/eigen/eigen/get/ad3bcd81cc49.tar.gz",
            "https://bitbucket.org/eigen/eigen/get/ad3bcd81cc49.tar.gz",
        ],
    )
``` 

So the former refers to `fd6845384b86` (git commit `f21be5f8d1591d2e2f774af30cb265b5781c4ce9`), while the latter refers to `ad3bcd81cc49` (git commit `c9f748adbc827fbcbd71b19e52ab7134c587396e` from last week).

**Comment by mrodozov** [comment]
@fwyzard now I see it yes but not when I compare branches it shows the old url. Anyway, I'll try the master now

**Comment by gartung** [comment]
I updated the master branch for cms-externals/eigen-git-mirror and cms-externals/tensorflow.

**Comment by fwyzard** [comment]
@mrodozov I have pushed to cms-externals the same commit that the head of tensorflow is using, to the branch `cms/c9f748adb` .

`c9f748adbc827fbcbd71b19e52ab7134c587396e` is the original commit from the Eigen mirror.
`47947007716cc1f02e496c4b148dc315a30fa7b4` contains my changes on top.

I have tested that the Patatrack changes build fine with the latter (I did not test the whole of CMSSW, though).

**Comment by fwyzard** [comment]
see #4643

**Comment by mrodozov** [comment]
Update: 
we have working build using the eigen from cmsdist based on this commit: https://github.com/mrodozov/tensorflow/commit/8eb3cbcb423c4d840e88a910c5db47404207b8a4
and the commits on top are adjusting comp flags and URLs to match cmsdist tools URLs. 
It builds with this changes: https://github.com/mrodozov/cmsdist/commits/build_tf_master_170119
which includes gcc update to 7.4 because: https://github.com/tensorflow/tensorflow/issues/25323 
Moving to 1.13.0-rc0 leads to this: https://github.com/grpc/grpc/issues/17506
After building the targets, the recipe fails with : 
cd tensorflow/contrib/makefile/downloads: No such file or directory
so @gartung we have to find another way of building this wheel.

**Comment by gartung** [comment]
@mrodozov remove everything from https://github.com/cms-sw/cmsdist/blob/3583c82dbf49470eaefec1faf56e2087fa437f81/tensorflow-sources.spec#L98 to
https://github.com/cms-sw/cmsdist/blob/3583c82dbf49470eaefec1faf56e2087fa437f81/tensorflow-sources.spec#L158

There is a new install target for headers that I don't recall at the moment. Once that is installed you can copy all of the headers out of bazel-bin with
cp -v $PWD/bazel-bin/tensorflow/include

**Comment by gartung** [comment]
@mrodozov add this line
$BAZEL_OPTS $BAZEL_EXTRA_OPTS //tensorflow:install_headers
at https://github.com/cms-sw/cmsdist/blob/3583c82dbf49470eaefec1faf56e2087fa437f81/tensorflow-sources.spec#L65

**Comment by mrodozov** [comment]
I have that target last 
https://github.com/mrodozov/cmsdist/blob/build_tf_master_170119/tensorflow-sources.spec#L73
It puts the headers in bazel-out/k8-opt/genfiles/tensorflow/include as described in:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L562
What would do from there when asked to build the wheel - I'm about to see (the structure of includes is now different)

**Pull request closed without merging**
