### PR TITLE
Update to Rivet 3.1.2 and Yoda 1.8.3

### PR DESCRIPTION
**Pull request by mseidel42**
Contains a couple of new features and analyses.

Hopefully no interface changes needed. Otherwise, unit tests should fail.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
the patch needs adjustment :/

**Comment by mseidel42** [comment]
Done!

(It worked locally with fuzz=1, and then I recreated the patch to work with fuzz=0)

**Comment by mrodozov** [comment]
please test

**Comment by mseidel42** [comment]
Hi all, it turns out that this needs an update of fastjet-contrib to include the LundPlane plugin:
```
pluginATLAS/ATLAS_2020_I1790256.cc:9:10: fatal error: fastjet/contrib/LundGenerator.hh: No such file or directory
 #include "fastjet/contrib/LundGenerator.hh"
```

@smuzaffar @fabiocos I see you were the last ones to update fast-jet contrib. Would it be possible to go to the latest 1.044 there?

**Comment by mrodozov** [comment]
I'll do it

**Comment by mseidel42** [comment]
Thanks a lot! It seems there are some CMS-specific patches to 1.033 which makes the update a bit more cumbersome.

Maybe it would be necessary / an opportunity to update fastjet to 3.3.4 as well?

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
well the externals built this time, it's something :)

**Comment by mseidel42** [comment]
Ok, the new problem should be fixed by https://github.com/cms-sw/cmssw/pull/30590

**Comment by silviodonato** [comment]
@smuzaffar, @mrodozov, @tulamor https://github.com/cms-sw/cmssw/pull/30590 is ready. Can we merge this PR?

**Comment by mrodozov** [comment]
yes, please :)

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Comment by makortel** [comment]
Could this Rivet update be causing many failures in the NANO step along
```
Rivet.Analysis.HiggsTemplateCrossSections: WARN  Unkown Higgs production mechanism. Cannot classify event. Classification for all events will most likely fail.
Rivet.AnalysisHandler: INFO  Using named weights
Error in RivetAnalysis::init method: No projections registered for parent 0x2b0f50c7a600
----- Begin Fatal Exception 20-Jul-2020 05:16:37 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Rethrowing an exception that happened on a different thread.
   [1] Reading branch edmTriggerResults_TriggerResults__HLT.
   Additional Info:
      [a] Fatal Root Error: @SUB=TStorageFactoryFile::ReadBufferAsync
Cannot read from a file that is not open

----- End Fatal Exception -------------------------------------------------
```
? (followed up in https://github.com/cms-sw/cmssw/issues/30836)

**Pull request merged**
