### PR TITLE
[Gcc12]Update cuda version 12.2.1

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by fwyzard** [comment]
nice 👍🏻

**Comment by smuzaffar** [comment]
Enable gpu

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
@fwyzard , although cuda 12.2.1 looks good but all GPU tests were skipped due with message [a] any idea?

[a]
```
Failed to initialise the CUDA runtime, the test will be skipped.
```

**Comment by smuzaffar** [comment]
gpu tests were run on htcondor gpu batch node which had the following gpu. Note that same type of gpu nodes are used by GPU IBs to run unit tests and except one all tests run
```
+ nvidia-smi
Tue Aug  8 13:22:02 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-PCIE-40GB           Off| 00000000:00:06.0 Off |                    0 |
| N/A   41C    P0               41W / 250W|    146MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     13141      G   /usr/bin/X                                   33MiB |
|    0   N/A  N/A     13215      G   /usr/bin/gnome-shell                         19MiB |
+---------------------------------------------------------------------------------------+
````

**Comment by fwyzard** [comment]
can you run `cudaComputeCapabilities` in a CMSSW environment on one of the node where the tests are skipped ?

**Comment by smuzaffar** [comment]
@fwyzard , on lxplus-gpu (which has [a] gpu) where unit tests are also skipped, I get this
```
lxplus> cmssw-el8 --nv
Singularity> cd /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/8643/34151/CMSSW_13_3_X_2023-08-07-1100/
Singularity> cmsenv
Singularity> echo $LD_LIBRARY_PATH | tr : 'n'Singularity> echo $LD_LIBRARY_PATH | tr : '\n'
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/8643/34151/CMSSW_13_3_X_2023-08-07-1100/biglib/el8_amd64_gcc12
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/8643/34151/CMSSW_13_3_X_2023-08-07-1100/lib/el8_amd64_gcc12
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/8643/34151/CMSSW_13_3_X_2023-08-07-1100/external/el8_amd64_gcc12/lib
/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-07-1100/biglib/el8_amd64_gcc12
/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-08-07-1100/lib/el8_amd64_gcc12
/cvmfs/cms-ci.cern.ch/week1/PR_3f407229/el8_amd64_gcc12/external/llvm/16.0.3-6ebd5c85e6445ff7c541390dd84225aa/lib64
/cvmfs/cms-ci.cern.ch/week1/PR_3f407229/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib64
/cvmfs/cms-ci.cern.ch/week1/PR_3f407229/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib
/cvmfs/cms-ci.cern.ch/week1/PR_3f407229/el8_amd64_gcc12/external/cuda/12.2.1-bdf3fff69eaec65abe18a7569592cab6/lib64/stubs
/.singularity.d/libs
Singularity> cudaComputeCapabilities                       
cudaComputeCapabilities: CUDA driver is a stub library
Singularity> $CMSSW_BASE/test/el8_amd64_gcc12/test_calo_rechit 
Failed to initialise the CUDA runtime, the test will be skipped.
```

[a]
```
Singularity> nvidia-smi
Wed Aug  9 09:56:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:07:00.0 Off |                    0 |
| N/A   50C    P0    28W /  70W |      2MiB / 15360MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by fwyzard** [comment]
Looks like the NVIDIA drivers and CUDA version on the machine are not compatible with CUDA 12.2.

If I try running the binary (without `cmsenv`), I get
```
Singularity> ./cudaComputeCapabilities
./cudaComputeCapabilities: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory
``` 

If I add the CUDA libraries to the path, I get
```
Singularity> LD_LIBRARY_PATH=/cvmfs/cms-ci.cern.ch/week1/PR_3f407229/el8_amd64_gcc12/external/cuda/12.2.1-bdf3fff69eaec65abe18a7569592cab6/lib64:$LD_LIBRARY_PATH ./cudaComputeCapabilities
cudaComputeCapabilities: CUDA driver version is insufficient for CUDA runtime version
```

If I try adding also the compatibility drivers, I get
```
Singularity> LD_LIBRARY_PATH=/cvmfs/cms-ci.cern.ch/week1/PR_3f407229/el8_amd64_gcc12/external/cuda/12.2.1-bdf3fff69eaec65abe18a7569592cab6/drivers:/cvmfs/cms-ci.cern.ch/week1/PR_3f407229/el8_amd64_gcc12/external/cuda/12.2.1-bdf3fff69eaec65abe18a7569592cab6/lib64:$LD_LIBRARY_PATH ./cudaComputeCapabilities
cudaComputeCapabilities: system has unsupported display driver / cuda driver combination
```

**Comment by fwyzard** [comment]
Indeed, according to https://docs.nvidia.com/deploy/cuda-compatibility/ this combination is not 
supported.

The machine has the driver version 520.61.05 .

To use the updated CUDA runtime directly, we need at least 525.60.13 :
image

To use the forward compatibility drivers, we need either an older driver (up to 470.57.02+ from CUDA 11.4) or a newer one (525.60.04+ from CUDA 12.0):
image

**Comment by smuzaffar** [comment]
As gcc12 branch is already using cuda 12.0.1, so I would suggest to merge this for gcc12. Any objections @fwyzard  ?

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by fwyzard** [comment]
> As gcc12 branch is already using cuda 12.0.1, so I would suggest to merge this for gcc12. Any objections @fwyzard ?

👍🏻

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Pull request merged**
