### PR TITLE
Fix ROCM_FLAGS [12.5.x]

### PR DESCRIPTION
**Pull request by fwyzard**
Delay the expansion of the COMPILER environment variables.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #8046

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@cms-sw/orp-l2 , this is just a technical bug fix for `rocm` toolfile. Feel free to include it for 12.5.X

**Comment by smuzaffar** [comment]
@perrotta @rappoccio this is bug fix and safe to merge it for 12.5.X

**Comment by perrotta** [comment]
+1

**Pull request merged**
