### PR TITLE
backporting sherpa2.2.6 and openloops2.0.0 to 71X

### PR DESCRIPTION
**Pull request by SiewYan**
backporting sherpa2.2.6 and openloops2.0.0

### CODE REVIEW

**Comment by SiewYan** [comment]
Hi, please apply the mentioned patches in [1] and [2] ,mentioned here [3]

[1] cms-externals/openloops@5141c0e
[2] https://gitlab.com/openloops/OpenLoops/commit/8ff8f52fe6e0f9f4f3f666b0d89279da64554fc3
[3] https://github.com/cms-sw/cmsdist/pull/4796

**Comment by SiewYan** [comment]
@mrodozov , could you please check the gitlab tag is correct and trigger the test?
Thanks.

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
thanks @mrodozov , can you please locally build it and compare the openloop install are to see if all the extra downloaded files are available  there? Compare it with the slc7_amd64_gcc700 installation of openloops 2.0.0 on CVMFS to make sure this this workaround actually copied all the files.

**Comment by qliphy** [comment]
@smuzaffar   #4823 is now merged.  Would you please trigger test this PR and move forward?  Thanks!

**Comment by mrodozov** [comment]
The installation on cvmfs has three folders, etc lib and proclib , all the files present in the 481 installation are also present in /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/external/openloops/2.0.0
the 481 installation is on cmsdev22 
/build/mrodozov/build_sherpa_gcc4/build_openloops_localrepo/slc6_amd64_gcc481/external/openloops/2.0.0

**Comment by smuzaffar** [comment]
+externals
thanks @mrodozov . @fabiocos  this is ready to go in 71X now.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
