### PR TITLE
Fix for EvtGen with Pythia8 >= 304

### PR DESCRIPTION
**Pull request by iarspider**
Reported to developers, will be included in the next release. See https://phab.hepforge.org/T144

### CODE REVIEW

**Comment by iarspider** [comment]
Please test

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
Please test

**Comment by iarspider** [comment]
+1

**Comment by smuzaffar** [comment]
assign generators

**Comment by agrohsje** [comment]
let me sign to indicate that GEN checked and is ok.

**Comment by agrohsje** [comment]
+generators

**Pull request merged**
