### PR TITLE
Backport of xz, root and rootfit from 72X

### PR DESCRIPTION
**Pull request by nclopezo**

### CODE REVIEW

**Comment by ktf** [comment]
@nclopezo please do not use cms-sw/cmsdist for topic branches, use your own repository.

**Comment by nclopezo** [comment]
ok, sorry, I hadn't noticed that I pushed it to the wrong repository.

**Comment by ktf** [comment]
No problem. Keep it in mind for next time.

**Comment by nclopezo** [comment]
the correct one is this one:
https://github.com/cms-sw/cmsdist/pull/812

**Pull request closed without merging**
