### PR TITLE
Update OpenCV to 4.7.0

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Updating the latest version to support gcc12

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/pkgtools/pull/197

**Comment by aandvalenzuela** [comment]
please test for el8_ppc64le_gcc11 with https://github.com/cms-sw/pkgtools/pull/197

**Comment by aandvalenzuela** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
