### PR TITLE
Rivet 4.0.1 and YODA 2.0.1

### PR DESCRIPTION
**Pull request by mseidel42**
- Updated Rivet and YODA, should fix some broken analyses, see https://gitlab.cern.ch/cms-gen/Rivet/-/issues/73
- Removed `Source1` patch as it is included in Rivet 4.0.1
- Change YODA plotting `script_generator.py` to `python3`, see https://gitlab.com/hepcedar/rivet/-/issues/494

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
something wrong here, unit test is using rivet from `rivet_x86-64-v3` where as it should have used the default `rivet` . I am looking in to it

**Comment by mseidel42** [comment]
Hi Shahzad, I pulled the user test area, is it possible to force it to use the rivet python libs in `/cvmfs/cms-ci.cern.ch/week0/PR_3c4b40b5/el8_amd64_gcc12/external/rivet/4.0.1-1343225d472136cb6244a534b76b8611/lib/python3.9/site-packages/rivet/`?

**Comment by smuzaffar** [comment]
looks like PYTHONPATH includes both `rivet_x86-64-v3` and `rivet` directories. I am checking how to avoid this

**Comment by smuzaffar** [comment]
this shows that both river python path are add. We should only add the default one
```
> grep /rivet /cvmfs/cms-ci.cern.ch/week0/PR_3c4b40b5/el8_amd64_gcc12/cms/cmssw-tools/2.0-ba0a9ecf230d66ffc990a5b56a99f0f7/lib/python3.9/site-packages/tool-deps.pth 
/cvmfs/cms-ci.cern.ch/week0/PR_3c4b40b5/el8_amd64_gcc12/external/rivet_x86-64-v3/4.0.1-cb14ff9bdb77ccb065b195eb7f90e278/lib/python3.9/site-packages
/cvmfs/cms-ci.cern.ch/week0/PR_3c4b40b5/el8_amd64_gcc12/external/rivet/4.0.1-1343225d472136cb6244a534b76b8611/lib/python3.9/site-packages
```

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_DEVEL_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_DEVEL_X

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_DEVEL_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- enable = threading
- workflow_threading = 534.0,536.0
- workflow = 534.0,536.0

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_MULTIARCHS_X

**Comment by smuzaffar** [comment]
+externals

looks good

**Comment by makortel** [comment]
> ---> test test-rivet-list had ERRORS

This failure is visible in IBs. Maybe it's random?
```
===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00001498aa95ee0b in waitpid () from /lib64/libc.so.6
#1  0x00001498aa8b2747 in do_system () from /lib64/libc.so.6
#2  0x0000149898b75f3d in TUnixSystem::StackTrace() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_MULTIARCHS_X_2024-10-30-2300/external/el8_amd64_gcc12/lib/libCore.so
#3  0x0000149898b73a14 in TUnixSystem::DispatchSignals(ESignals) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_MULTIARCHS_X_2024-10-30-2300/external/el8_amd64_gcc12/lib/libCore.so
#4  <signal handler called>
#5  0x00001498aa907231 in __memmove_avx_unaligned_erms_rtm () from /lib64/libc.so.6
#6  0x00001498aa38b8f9 in std::char_traits<char>::copy(char*, char const*, unsigned long) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/rivet_x86-64-v3/4.0.1-3594f6c327b0a107cb5d13327304e265/lib/python3.9/site-packages/rivet/core.so
#7  0x00001498aa39e456 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/rivet_x86-64-v3/4.0.1-3594f6c327b0a107cb5d13327304e265/lib/python3.9/site-packages/rivet/core.so
#8  0x00001498aa3a545c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars(char*, char*, char*) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/rivet_x86-64-v3/4.0.1-3594f6c327b0a107cb5d13327304e265/lib/python3.9/site-packages/rivet/core.so
#9  0x00001498aa39e0c9 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/rivet_x86-64-v3/4.0.1-3594f6c327b0a107cb5d13327304e265/lib/python3.9/site-packages/rivet/core.so
#10 0x00001498aa396dd9 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/rivet_x86-64-v3/4.0.1-3594f6c327b0a107cb5d13327304e265/lib/python3.9/site-packages/rivet/core.so
#11 0x000014989d747a40 in Rivet::split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_MULTIARCHS_X_2024-10-30-2300/external/el8_amd64_gcc12/lib/scram_x86-64-v3/libRivet.so
#12 0x000014989d751ee3 in Rivet::AnalysisInfo::buildOptionMap() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_MULTIARCHS_X_2024-10-30-2300/external/el8_amd64_gcc12/lib/scram_x86-64-v3/libRivet.so
#13 0x000014989d74dec1 in Rivet::AnalysisInfo::parseInfoFile() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_MULTIARCHS_X_2024-10-30-2300/external/el8_amd64_gcc12/lib/scram_x86-64-v3/libRivet.so
#14 0x000014989d747ba8 in Rivet::Analysis::loadInfo() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_MULTIARCHS_X_2024-10-30-2300/external/el8_amd64_gcc12/lib/scram_x86-64-v3/libRivet.so
#15 0x000014989d73103c in Rivet::AnalysisLoader::getAnalysis(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_MULTIARCHS_X_2024-10-30-2300/external/el8_amd64_gcc12/lib/scram_x86-64-v3/libRivet.so
#16 0x00001498aa35ea51 in __pyx_pf_5rivet_4core_14AnalysisLoader_8getAnalysis(_object*) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/rivet_x86-64-v3/4.0.1-3594f6c327b0a107cb5d13327304e265/lib/python3.9/site-packages/rivet/core.so
#17 0x00001498aa35e8bc in __pyx_pw_5rivet_4core_14AnalysisLoader_9getAnalysis(_object*, _object*, _object*) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/rivet_x86-64-v3/4.0.1-3594f6c327b0a107cb5d13327304e265/lib/python3.9/site-packages/rivet/core.so
#18 0x00001498ab8fb2f3 in cfunction_call (func=0x1498aa678220, args=<optimized out>, kwargs=<optimized out>) at Objects/methodobject.c:543
#19 0x00001498ab8b786e in _PyObject_MakeTpCall (tstate=0x14e43f0, callable=callable
entry=0x1498aa678220, args=args
entry=0x15a0ea0, nargs=1, keywords=keywords
entry=0x0) at Objects/call.c:191
#20 0x00001498ab86e50a in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775809, args=0x15a0ea0, callable=0x1498aa678220, tstate=<optimized out>) at ./Include/cpython/abstract.h:116
#21 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775809, args=0x15a0ea0, callable=0x1498aa678220, tstate=<optimized out>) at ./Include/cpython/abstract.h:103
#22 PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=<optimized out>, callable=0x1498aa678220) at ./Include/cpython/abstract.h:127
#23 call_function (kwnames=0x0, oparg=1, pp_stack=<synthetic pointer>, tstate=0x14e43f0) at Python/ceval.c:5077
#24 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3489
#25 0x00001498ab99ea91 in _PyEval_EvalFrame (throwflag=0, f=0x15a0d20, tstate=0x14e43f0) at ./Include/internal/pycore_ceval.h:40
#26 _PyEval_EvalCode (tstate=0x14e43f0, _co=_co
entry=0x1498abcc4c90, globals=globals
entry=0x1498abd2ea80, locals=locals
entry=0x1498abd2ea80, args=args
entry=0x0, argcount=argcount
entry=0, kwnames=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4329
#27 0x00001498ab99ee32 in _PyEval_EvalCodeWithName (_co=_co
entry=0x1498abcc4c90, globals=globals
entry=0x1498abd2ea80, locals=locals
entry=0x1498abd2ea80, args=args
entry=0x0, argcount=argcount
entry=0, kwnames=kwnames
entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4361
#28 0x00001498ab99ee7b in PyEval_EvalCodeEx (_co=_co
entry=0x1498abcc4c90, globals=globals
entry=0x1498abd2ea80, locals=locals
entry=0x1498abd2ea80, args=args
entry=0x0, argcount=argcount
entry=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4377
#29 0x00001498ab99eeab in PyEval_EvalCode (co=co
entry=0x1498abcc4c90, globals=globals
entry=0x1498abd2ea80, locals=locals
entry=0x1498abd2ea80) at Python/ceval.c:828
#30 0x00001498ab9de3a9 in run_eval_code_obj (locals=0x1498abd2ea80, globals=0x1498abd2ea80, co=0x1498abcc4c90, tstate=0x14e43f0) at Python/pythonrun.c:1221
#31 run_mod (mod=<optimized out>, filename=filename
entry=0x1498abc9a030, globals=globals
entry=0x1498abd2ea80, locals=locals
entry=0x1498abd2ea80, flags=flags
entry=0x7ffe54008348, arena=arena
entry=0x1498aa6e9fd0) at Python/pythonrun.c:1242
#32 0x00001498ab9dfdf2 in pyrun_file (flags=0x7ffe54008348, closeit=1, locals=0x1498abd2ea80, globals=0x1498abd2ea80, start=257, filename=0x1498abc9a030, fp=0x15764e0) at Python/pythonrun.c:1140
#33 pyrun_simple_file (flags=0x7ffe54008348, closeit=1, filename=0x1498abc9a030, fp=0x15764e0) at Python/pythonrun.c:450
#34 PyRun_SimpleFileExFlags (fp=fp
entry=0x15764e0, filename=<optimized out>, closeit=closeit
entry=1, flags=flags
entry=0x7ffe54008348) at Python/pythonrun.c:483
#35 0x00001498ab9e0453 in PyRun_AnyFileExFlags (fp=fp
entry=0x15764e0, filename=<optimized out>, closeit=closeit
entry=1, flags=flags
entry=0x7ffe54008348) at Python/pythonrun.c:92
#36 0x00001498ab9fdea8 in pymain_run_file (cf=0x7ffe54008348, config=0x14e0e20) at Modules/main.c:373
#37 pymain_run_python (exitcode=0x7ffe54008340) at Modules/main.c:598
#38 Py_RunMain () at Modules/main.c:677
#39 0x00001498ab9fe3c7 in pymain_main (args=0x7ffe54008430) at Modules/main.c:707
#40 Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:731
#41 0x00001498aa8917e5 in __libc_start_main () from /lib64/libc.so.6
#42 0x000000000040107e in _start ()
===========================================================
```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f23985/42520/unitTests/src/GeneratorInterface/RivetInterface/test/test-rivet-list/testing.log

**Comment by smuzaffar** [comment]
@makortel , yes this look like random. It is failing randomly for different IBs. I am looking in to it

**Comment by smuzaffar** [comment]
@mseidel42 , looks like issue is with `share/Rivet/MC_TAUPOL.info` file which has some options without `=` [a] and I think this is causing https://gitlab.com/hepcedar/rivet/-/blob/rivet-4.0.1/src/Core/AnalysisInfo.cc#L190-198 to fail when it tries to split `optv[1]`.  `MC_TAUPOL.info` was add in 4.0.1 via https://gitlab.com/hepcedar/rivet/-/commit/bbfe35abbec66b636b55f01acca9c11227e1cba7 . We either need to fix `MC_TAUPOL.info` to provide values for ` LOMASS, HIMASS` or fix the `Rivet::AnalysisInfo::buildOptionMap` to not assume that all options willhave values.

[a]
```
Options:
 - MODE=DITAU,SINGLE
 - LOMASS
 - HIMASS

```

**Comment by smuzaffar** [comment]
looks like https://gitlab.com/hepcedar/rivet/-/commit/8869db87de9d6c8cfe57e16b2c1469c3cf3b38bd has added the protection for invalid reads

**Comment by smuzaffar** [comment]
hopefully https://github.com/cms-sw/cmsdist/pull/9495 should fix this failure

**Pull request merged**
