### PR TITLE
New exporters version

### PR DESCRIPTION
**Pull request by vkuznet**
It includes CLOSE_WAIT and TIME_WAIT connection metrics

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to dc48eb462f95b0f2cfa5cb8c050f5c1f664aa62f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4966/test_dc48eb4-20190513-210506.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to feecbb7187a6fe9f670d94917f191e42a446fb2e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4966/test_feecbb7-20190515-004005.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 4f36061dc127f19c27fe602fcee457eecb70aa64 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4966/test_4f36061-20190515-151007.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@h4d4 , LIna, the last build was -1 and provided link leads to Not found page. Could you please restart the build and give me link to the build log

**Comment by h4d4** [comment]
to 787b617a4bf6c9a3ec02d5bfbf154eb1af9da94c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4966/test_787b617-20190515-230507.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
@vkuznet Valentin,

please check log pointed out in above test https://github.com/cms-sw/cmsdist/pull/4966#issuecomment-492441436

Best Regards, Lina.

**Comment by h4d4** [comment]
to 787b617a4bf6c9a3ec02d5bfbf154eb1af9da94c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4966/test_787b617-20190516-160508.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 787b617a4bf6c9a3ec02d5bfbf154eb1af9da94c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4966/test_787b617-20190516-182013.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
Lina, build come back ok now, we good to go.

**Pull request merged**
