### PR TITLE
ROOT: Use rootcling instead of genreflex for root dict generation

### LINKED ISSUE #8983: Use rootcling instead of genreflex
@vgvassilev , following https://github.com/root-project/root/issues/9448#issuecomment-1925418448 , I am updating cmssw build rules to make use of `rootcling` instead of `genreflex` but I get built errors e.g. for the old working `genreflex` command [a] the equivalent `rootcling` command [b] failed when we try to compile the generated `DataFormatsProvenance_xr.cc` file [d]. Note that [a] with `--debug` showed that it was running `rootcling` with args [c]. Both [b] and [c] looks similar except that I do not see `genreflex` command in [a] passing `-isystem<path>` to `rootcling`. 

Any idea whats wrong with new `rootcling` ?

[a]
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/bin/genreflex
src/DataFormats/Provenance/src/classes.h
-s
src/DataFormats/Provenance/src/classes_def.xml
-o
tmp/el8_amd64_gcc12/src/DataFormats/Provenance/src/DataFormatsProvenance/a/DataFormatsProvenance_xr.cc
--debug
--fail_on_warnings
--rootmap=tmp/el8_amd64_gcc12/src/DataFormats/Provenance/src/DataFormatsProvenance/a/DataFormatsProvenance_xr.rootmap
--rootmap-lib=libDataFormatsProvenance.so
-DCMS_DICT_IMPL
-D_REENTRANT
-DGNUSOURCE
-D__STRICT_ANSI__
-DGNU_GCC
-D_GNU_SOURCE
-DTBB_USE_GLIBCXX_VERSION=120301
-DTBB_SUPPRESS_DEPRECATED_MESSAGES
-DTBB_PREVIEW_RESUMABLE_TASKS=1
-DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1
-DBOOST_SPIRIT_THREADSAFE
-DPHOENIX_THREADSAFE
-DBOOST_MATH_DISABLE_STD_FPCLASSIFY
-DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX
-DCMSSW_GIT_HASH="CMSSW_14_0_X_2024-02-04-0000"
-DPROJECT_NAME="CMSSW"
-DPROJECT_VERSION="CMSSW_14_0_X_2024-02-04-0000"
-I/build/muz/rootcling/old/CMSSW_14_0_X_2024-02-04-0000/src
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_X_2024-02-04-0000/src
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/pcre/8.43-37eb2e8b73bab83d6645ecfd5d73dcaa/include
-isystem/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/boost/1.80.0-9d4e0dc8cf1f8fc8a67cf53ae917955e/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/bz2lib/1.0.6-d065ccd79984efc6d4660f410e4c81de/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/libuuid/2.34-27ce4c3579b5b1de2808ea9c4cd8ed29/include
-isystem/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/include
-isystem/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/tbb/v2021.9.0-5109e373398eaf79a8268d6a86a2f6e2/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/xz/5.2.5-6f3f49b07db84e10c9be594a1176c114/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/zlib/1.2.11-51072030b7f93c3ac6c4235f21e413cb/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/fmt/8.0.1-54e94b39f5cf29341bb9c4765764e1ca/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/md5/1.0.0-5b594b264e04ae51e893b1d69a797ec6/include
-DCMSSW_REFLEX_DICT
```
[b]
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/bin/rootcling
-f
tmp/el8_amd64_gcc12/src/DataFormats/Provenance/src/DataFormatsProvenance/a/DataFormatsProvenance_xr.cc
-inlineInputHeader
-failOnWarnings
-rmf
tmp/el8_amd64_gcc12/src/DataFormats/Provenance/src/DataFormatsProvenance/a/DataFormatsProvenance_xr.rootmap
-rml
libDataFormatsProvenance.so
-DCMS_DICT_IMPL
-D_REENTRANT
-DGNUSOURCE
-D__STRICT_ANSI__
-DGNU_GCC
-D_GNU_SOURCE
-DTBB_USE_GLIBCXX_VERSION=120301
-DTBB_SUPPRESS_DEPRECATED_MESSAGES
-DTBB_PREVIEW_RESUMABLE_TASKS=1
-DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1
-DBOOST_SPIRIT_THREADSAFE
-DPHOENIX_THREADSAFE
-DBOOST_MATH_DISABLE_STD_FPCLASSIFY
-DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX
-DCMSSW_GIT_HASH="CMSSW_14_0_X_2024-02-04-0000"
-DPROJECT_NAME="CMSSW"
-DPROJECT_VERSION="CMSSW_14_0_X_2024-02-04-0000"
-I/build/muz/rootcling/CMSSW_14_0_X_2024-02-04-0000/src
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_X_2024-02-04-0000/src
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/pcre/8.43-37eb2e8b73bab83d6645ecfd5d73dcaa/include
-isystem/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/boost/1.80.0-9d4e0dc8cf1f8fc8a67cf53ae917955e/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/bz2lib/1.0.6-d065ccd79984efc6d4660f410e4c81de/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/libuuid/2.34-27ce4c3579b5b1de2808ea9c4cd8ed29/include
-isystem/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/include
-isystem/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/tbb/v2021.9.0-5109e373398eaf79a8268d6a86a2f6e2/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/xz/5.2.5-6f3f49b07db84e10c9be594a1176c114/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/zlib/1.2.11-51072030b7f93c3ac6c4235f21e413cb/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/fmt/8.0.1-54e94b39f5cf29341bb9c4765764e1ca/include
-I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/md5/1.0.0-5b594b264e04ae51e893b1d69a797ec6/include
-DCMSSW_REFLEX_DICT
src/DataFormats/Provenance/src/classes.h
src/DataFormats/Provenance/src/classes_def.xml
```

[c]
```
Rootcling commandline:
0) rootcling
1) -v4
2) -f
3) tmp/el8_amd64_gcc12/src/DataFormats/Provenance/src/DataFormatsProvenance/a/DataFormatsProvenance_xr.cc
4) -rmf
5) tmp/el8_amd64_gcc12/src/DataFormats/Provenance/src/DataFormatsProvenance/a/DataFormatsProvenance_xr.rootmap
6) -rml
7) libDataFormatsProvenance.so
8) -inlineInputHeader
9) -failOnWarnings
10) -I/build/muz/rootcling/old/CMSSW_14_0_X_2024-02-04-0000/src
11) -I/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_X_2024-02-04-0000/src
12) -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/pcre/8.43-37eb2e8b73bab83d6645ecfd5d73dcaa/include
13) -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/bz2lib/1.0.6-d065ccd79984efc6d4660f410e4c81de/include
14) -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/libuuid/2.34-27ce4c3579b5b1de2808ea9c4cd8ed29/include
15) -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/xz/5.2.5-6f3f49b07db84e10c9be594a1176c114/include
16) -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/zlib/1.2.11-51072030b7f93c3ac6c4235f21e413cb/include
17) -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/fmt/8.0.1-54e94b39f5cf29341bb9c4765764e1ca/include
18) -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/md5/1.0.0-5b594b264e04ae51e893b1d69a797ec6/include
19) -DCMS_DICT_IMPL
20) -D_REENTRANT
21) -DGNUSOURCE
22) -D__STRICT_ANSI__
23) -DGNU_GCC
24) -D_GNU_SOURCE
25) -DTBB_USE_GLIBCXX_VERSION=120301
26) -DTBB_SUPPRESS_DEPRECATED_MESSAGES
27) -DTBB_PREVIEW_RESUMABLE_TASKS=1
28) -DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1
29) -DBOOST_SPIRIT_THREADSAFE
30) -DPHOENIX_THREADSAFE
31) -DBOOST_MATH_DISABLE_STD_FPCLASSIFY
32) -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX
33) -DCMSSW_GIT_HASH="CMSSW_14_0_X_2024-02-04-0000"
34) -DPROJECT_NAME="CMSSW"
35) -DPROJECT_VERSION="CMSSW_14_0_X_2024-02-04-0000"
36) -DCMSSW_REFLEX_DICT
37) src/DataFormats/Provenance/src/classes.h
38) src/DataFormats/Provenance/src/classes_def.xml
```

[d]
```
In file included from DataFormatsProvenance/a/DataFormatsProvenance_xr.cc:32:
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/include/TCollectionProxyInfo.h: In instantiation of 'static void* ROOT::Detail::TCollectionProxyInfo::Type<T>::construct(void*, std::size_t) [with T = std::vector<edm::IndexIntoFile::RunOrLumiIndexes>; std::size_t = long unsigned int]':
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/include/TCollectionProxyInfo.h:577:17:   required from 'static ROOT::Detail::TCollectionProxyInfo* ROOT::Detail::TCollectionProxyInfo::Generate(const T&) [with T = Pushback<std::vector<edm::IndexIntoFile::RunOrLumiIndexes> >]'
DataFormatsProvenance/a/DataFormatsProvenance_xr.cc:5825:71:   required from here
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/include/TCollectionProxyInfo.h:343:13: error: no matching function for call to 'edm::IndexIntoFile::RunOrLumiIndexes::RunOrLumiIndexes()'
  343 |             ::new(m) Value_t();
      |             ^~~~~~~~~~~~~~~~~~
In file included from /build/muz/rootcling/CMSSW_14_0_X_2024-02-04-0000/src/DataFormats/Provenance/src/classes.h:12,
                 from DataFormatsProvenance/a/DataFormatsProvenance_xr.cc:44:
/build/muz/rootcling/CMSSW_14_0_X_2024-02-04-0000/src/DataFormats/Provenance/interface/IndexIntoFile.h:484:7: note: candidate: 'edm::IndexIntoFile::RunOrLumiIndexes::RunOrLumiIndexes(int, edm::RunNumber_t, edm::LuminosityBlockNumber_t, int)'
  484 |       RunOrLumiIndexes(int processHistoryIDIndex, RunNumber_t run, LuminosityBlockNumber_t lumi, int indexToGetEntry);
      |       ^~~~~~~~~~~~~~~~
/build/muz/rootcling/CMSSW_14_0_X_2024-02-04-0000/src/DataFormats/Provenance/interface/IndexIntoFile.h:484:7: note:   candidate expects 4 arguments, 0 provided
/build/muz/rootcling/CMSSW_14_0_X_2024-02-04-0000/src/DataFormats/Provenance/interface/IndexIntoFile.h:482:11: note: candidate: 'constexpr edm::IndexIntoFile::RunOrLumiIndexes::RunOrLumiIndexes(const edm::IndexIntoFile::RunOrLumiIndexes&)'
  482 |     class RunOrLumiIndexes {
      |           ^~~~~~~~~~~~~~~~
/build/muz/rootcling/CMSSW_14_0_X_2024-02-04-0000/src/DataFormats/Provenance/interface/IndexIntoFile.h:482:11: note:   candidate expects 1 argument, 0 provided
/build/muz/rootcling/CMSSW_14_0_X_2024-02-04-0000/src/DataFormats/Provenance/interface/IndexIntoFile.h:482:11: note: candidate: 'constexpr edm::IndexIntoFile::RunOrLumiIndexes::RunOrLumiIndexes(edm::IndexIntoFile::RunOrLumiIndexes&&)'
/build/muz/rootcling/CMSSW_14_0_X_2024-02-04-0000/src/DataFormats/Provenance/interface/IndexIntoFile.h:482:11: note:   candidate expects 1 argument, 0 provided
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/include/TCollectionProxyInfo.h: In instantiation of 'static void* ROOT::Detail::TCollectionProxyInfo::Type<T>::construct(void*, std::size_t) [with T = std::map<edm::IndexIntoFile::IndexRunLumiKey, long long int>; std::size_t = long unsigned int]':
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/lcg/root/6.30.03-723f04ba093d0553281d42c7b0f6eee1/include/TCollectionProxyInfo.h:577:17:   required from 'static ROOT::Detail::TCollectionProxyInfo* ROOT::Detail::TCollectionProxyInfo::Generate(const T&) [with T = MapInsert<std::map<edm::IndexIntoFile::IndexRunLumiKey, long long int> >]'
DataFormatsProvenance/a/DataFormatsProvenance_xr.cc:6865:71:   required from here

```

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes https://github.com/cms-sw/cmsdist/issues/8983

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

looks good but we will integrate it for 14.1.X

**Comment by smuzaffar** [comment]
+externals

@makortel , any objection on this change?

**Comment by makortel** [comment]
No objections

**Comment by smuzaffar** [comment]
lets get this in for next IB

**Pull request merged**
