### PR TITLE
Update Eigen to commit c7dc0a897676 (> 3.3.4)

### PR DESCRIPTION
**Pull request by smuzaffar**
same as https://github.com/cms-sw/cmsdist/pull/3587 but for 10.0.X DEVEL IBs.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlt** [comment]
Based on by comment from 2 weeks ago (https://github.com/cms-sw/cmssw/issues/21174#issuecomment-342157015) I would suggest adding `-DBUILD_TESTING=OFF` otherwise it starts depending on Boost and potentially more IIRC.

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
