### PR TITLE
[cxxmodule] Fix genreflex errors

### PR DESCRIPTION
**Pull request by yamaguchi1024**
This PR should be tested with
https://github.com/cms-sw/cmssw/pull/25670. This enables pcm to be fully
generated (Not yet fully loaded, though).

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by yamaguchi1024** [comment]
```
-- ROOT default compression algorithm: zlib
CMake Error at cmake/modules/RootBuildOptions.cmake:321 (message):
>>> Option 'table' has been removed in ROOT v6.16.
Call Stack (most recent call first):
CMakeLists.txt:107 (include)
```

This is the error, I will just remove the option -Dtable=On

**Comment by yamaguchi1024** [comment]
please test :smiley_cat:

**Comment by davidlange6** [comment]
please test

**Comment by yamaguchi1024** [comment]
I don't understand what's happening to this error, compiling PhysicsTools/PythonAnalysis on cmsdev15 worked..

**Comment by yamaguchi1024** [comment]
```
/build/yuka/genreflex/build-cmssw-tool-confv2/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lL1TriggerDTTrackFinder
/build/yuka/genreflex/build-cmssw-tool-confv2/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lCondFormatsL1TObjects
collect2: error: ld returned 1 exit status
```
FYI, I get this error when compiling DataFormats/L1TMuon on cmsdev15

**Comment by slava77** [comment]
On 1/19/19 7:13 AM, Yuka Takahashi wrote:
> |/build/yuka/genreflex/build-cmssw-tool-confv2/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld:
> cannot find -lL1TriggerDTTrackFinder
> /build/yuka/genreflex/build-cmssw-tool-confv2/slc7_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld:
> cannot find -lCondFormatsL1TObjects collect2: error: ld returned 1 exit
> status |
> 
> FYI, I get this error when compiling DataFormats/L1TMuon on cmsdev15
> 
> 

the package appears in violation of the CMSSW package dependency rules
for the DataFormats
Dependence on either L1Trigger/ or CondFormats/ are not allowed.
(rootrflx should not be necessary either).
Perhaps it's a starting point.

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts#Restrictions_on_the_package_defi

**Comment by smuzaffar** [comment]
allow @yamaguchi1024 test rights

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
This is good!

**Comment by yamaguchi1024** [comment]
The problem seems that CondFormats/L1TObjects is using L1GtObject enum without including DataFormats/L1GlobalTrigger/interface/L1GtObject.h, so ROOT is injecting a forward declaration when loading CondFormatsL1TObjects_xr, which collide with the actual definition of L1TObjects in pcm.

**Comment by yamaguchi1024** [comment]
So I think we need to explicitly include `#include "DataFormats/L1GlobalTrigger/interface/L1GtObject.h"` at for example `CondFormats/L1TObjects/interface/L1GtBoard.h` and then explicitly add a dependency of DataFormats to CondFormats.

**Comment by smuzaffar** [comment]
@yamaguchi1024 , can you please make a PR

**Comment by yamaguchi1024** [comment]
CondFormats's dictionary is not being generated with `--cxxmodule` for some reason, while other libraries (DataFormats and FWCore) are generated with a proper flag. Is there any special treatment/flag for CondFormats?

**Comment by yamaguchi1024** [comment]
`CondFormats/Alignment/BuildFile.xml-<flags   GENREFLEX_ARGS="--"/>`
Looks like this is squashing all genreflex args to "--"..

**Comment by yamaguchi1024** [comment]
```
CondFormats/Alignment/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/BTauObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/BeamSpotObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/CSCObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/Calibration/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/CastorObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/Common/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/DQMObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/DTObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/EcalCorrections/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/GEMObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/GeometryObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/HIObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/HLTObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/HcalObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/L1TObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/Luminosity/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/MFObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/OptAlignObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/PCLConfig/BuildFile.xml:<flags GENREFLEX_ARGS="--"/>
CondFormats/RPCObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/RecoMuonObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/RunInfo/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
CondFormats/SiPixelObjects/BuildFile.xml:<flags   GENREFLEX_ARGS="--"/>
```
Let me know if you know why genreflex flag for CondFormats is being squashed..

**Comment by yamaguchi1024** [comment]
ping bot

**Comment by yamaguchi1024** [comment]
please test with https://github.com/cms-sw/cmssw/pull/25735

**Comment by smuzaffar** [comment]
correct GENREFLEX_ARGS="--"  was use to drop the --fail_on_warning flag but it is now also dropping the --modules flags. Let me see if we can separate these flags.

**Comment by yamaguchi1024** [comment]
@smuzaffar 
Thanks! That will be super helpful. Please feel free to fix or close https://github.com/cms-sw/cmssw/pull/25735 if you find a better way.

**Comment by yamaguchi1024** [comment]
This is not tested with cms-sw/cmssw/pull/25735.. no?

**Comment by yamaguchi1024** [comment]
ping bot

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
At least it compiles :)

@smuzaffar , do you know if these graphs (https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-dqm-tests/CMSSW_10_5_CXXMODULE_X_2019-01-22-2300/slc7_amd64_gcc700/150/memory_25202.0/mbGraph.html#?profile=performance.json&pid=95070) can be generated with given unittest failures? If that's the case, can we merge this to tonight's IB and see its performance tomorrow?

Btw, is the latest scram config change already being applied?

**Comment by yamaguchi1024** [comment]
@smuzaffar @mrodozov @davidlange6 Could you merge this for tonight's IB?

**Pull request merged**
