### PR TITLE
bump protobuf version

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
I would think we'll have the same testing errors here as in the mainstream - but lets find out..

**Comment by smuzaffar** [comment]
@davidlange6 , https://github.com/cms-sw/cmssw/pull/17798 should fix it.

**Comment by rovere** [comment]
These files have to be re-generated every-time you change protoc.
A possibility is to include their "compilation" out of the proto-message in the buildfile itself.

**Comment by davidlange6** [comment]
thanks! I'll add a note in the protobuf.spec file so we remember. since update rarely I don't think more work is needed to automate this

**Comment by davidlt** [comment]
Looks like at the end you had to bump protobuf version ;)

**Pull request merged**
