### PR TITLE
Update gperftools/tcmalloc to 2.11

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = Alignment/OfflineValidation, CondCore/CondDB
- enable = profiling

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test

re-run tests for production arch to get clean dqm comparisons

**Comment by iarspider** [comment]
ROOT6 failure is investigated here: https://github.com/cms-sw/cmssw/issues/40347

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ROOT6_X

**Comment by iarspider** [comment]
I can try to get more details for this failure, if needed.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , please check if we can make use of https://github.com/ObiWahn/tcmalloc-cmake (https://github.com/google/tcmalloc/issues/4) to build google/tcmalloc with cmake

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc11

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc11

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc11

**Comment by smuzaffar** [comment]
this looks good but this will go in after 13.3.0.pre2

**Pull request merged**
