### PR TITLE
Update DD4Hep 12_1 to specific commit

### LINKED ISSUE #7311: Switch DD4hep for 12_0 and 12_1 to latest commit
There is an important DD4hep fix in this commit:
https://github.com/AIDASoft/DD4hep/pull/871

Could our DD4hep please be switched to use this new version for both 12_0 and 12_1?

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #7311

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by smuzaffar** [comment]
please test
lets rerun

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
> Reco comparison results: 9 differences found in the comparisons

these look more typical for the architecture difference AVX vs AVX2 (+FMA?) between the baseline and this PR.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_12_1_X_2021-09-15-2300/slc7_amd64_gcc900/-GenuineIntel/matrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2.log
```
2021-09-16 06:37:17.271612: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:
  SSE4.1 SSE4.2 AVX AVX2 FMA
```

this PR https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8aadf5/18655/runTheMatrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2.log
```
2021-09-16 14:41:11.711304: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:
  SSE4.1 SSE4.2 AVX
```

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
