### PR TITLE
bump py2 and py3 versions to latest in pypi 

### PR DESCRIPTION
**Pull request by davidlange6**
It seems many packages are now requiring py2-wheel as a build time dependency. We want want to add that to build-with-pip at some point?

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
