### PR TITLE
Move the RecoEgamma-PhotonIdentification tag from 04 to 05

### PR DESCRIPTION
**Pull request by mrodozov**
Backport of https://github.com/cms-sw/cmsdist/pull/3668

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by slava77** [comment]
can this be merged?
tests that were started in https://github.com/cms-sw/cmssw/pull/22302#issuecomment-368050633 have completed OK

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
