### PR TITLE
Set Tensorflow logging level to 3

### LINKED ISSUE #1031: Set TF_CPP_MIN_LOG_LEVEL environment variable in tensorflow toolfile

### PR DESCRIPTION
**Pull request by makortel**
To accompany https://github.com/cms-sw/cmssw/pull/46065, as proposed in https://github.com/cms-sw/cmssw/issues/46002#issuecomment-2361846551.

Resolves https://github.com/cms-sw/framework-team/issues/1031

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
Thanks!

**Comment by smuzaffar** [comment]
+externals

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
