### PR TITLE
Update llvm to 6.0.0 RC1

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by davidlt** [comment]
Is this RC1 or something beyond that?

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
well i'm not sure because they don't have tags on their git mirror and their official repo doesn't work however they said rc1 after Jan17 and rc2 after Feb17 so it's rc1 probably.

**Comment by mrodozov** [comment]
please test

**Comment by davidlt** [comment]
Ignore these errors, those are easy to fix one we have new LLVM/Clang stack in the IBs. It's just the namespace issue.

**Pull request merged**
