### PR TITLE
Adjust root.spec according changes in ROOT

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test for CMSSW_11_0_CXXMODULE_X with https://github.com/cms-sw/root/pull/129

**Comment by mrodozov** [comment]
ping bot

**Comment by mrodozov** [comment]
please test for CMSSW_11_0_CXXMODULE_X with cms-sw/root#129

**Comment by mrodozov** [comment]
have to see why the bot is not doing anything

**Comment by mrodozov** [comment]
it configures. the PR does its job so lets see when to merge it (maybe the evening)
Unfortunately if I run tests only they'll link against the latest IB which is rekt so no point of doing that.

**Comment by oshadura** [comment]
No worries and thank you for the help!

**Pull request merged**
