### PR TITLE
upgrade lhapdf sets to 6.2.1d

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
The test errors are not caused by this PR. The code was not changed.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@mkirsano @efeyazgan @qliphy @alberto-sanchez do we have the blessing of the GEN group for this update? Was this version tested so as that we may merge it in for the latest validation and put it in production?

**Comment by smuzaffar** [comment]
assign generators

**Comment by efeyazgan** [comment]
yes, @mkirsano made some tests before making the PR. @mkirsano it would be good to briefly explain your test here for future reference.

**Comment by mkirsano** [comment]
I ran pythia8 with a few sets from the new location, in particular all the new sets that were requested. I think some standard tests also use lhapdf. As usual, most of sets are not changed.

**Comment by fabiocos** [comment]
if GEN is ok with this update, please sign it so as we may move forward asap with the integration

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
