### PR TITLE
Update data-L1Trigger-L1TMuon.spec

### PR DESCRIPTION
**Pull request by mrodozov**
Description: https://github.com/cms-data/L1Trigger-L1TMuon/pull/15

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
the PR itself is fine when tested with the 10_3  cms-sw/cmssw#24242, restarting it on it's own to get the test-approved label

**Comment by fabiocos** [comment]
@mrodozov @rekovic as far as I can see, this update just adds two new files and does not overwirte anything, so it should be safe for integration at any moment

**Comment by mrodozov** [comment]
@fabiocos agreed. as existing files have not been modified, seems so

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
