### PR TITLE
[10_6_X] Enabling Sherpa2ShortHepMC in sherpa

### PR DESCRIPTION
**Pull request by SiewYan**
Enable Sherpa2ShortHepMC function (MISSING) during Sherpa::FillHepMCEvent. 

Integrates fix (Sherpa 2.2.8) from Emilien Chapon, Junquan Tao and Rajdeep. Fix was modified for sherpa 2.2.10 to include HepMC3 version of  Sherpa2ShortHepMC:

HepMC2_Interface::Sherpa2ShortHepMC
HepMC3_Interface::Sherpa2ShortHepMC

NOTE, During FillHepMCEvent, different arguments are provided for Sherpa2ShortHepMC between class HepMC2_Interface and HepMC3_Interface:

p_hepmc2->Sherpa2ShortHepMC(blobs, event, blobs->Weight());
p_hepmc3->Sherpa2ShortHepMC(blobs, event);

-----

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by smuzaffar** [comment]
@SiewYan , please close this PR and open one for IB/CMSSW_10_6_X/gcc700 branch . Please always use the production branch for creating PRs. You can find production branch for each release cycles from https://raw.githubusercontent.com/cms-sw/cms-bot/master/config.map where each line represent one IB and production branch contains PROD_ARCH=1 e.g. for 10.6.X one should looks for 
```
SCRAM_ARCH=slc7_amd64_gcc700;PKGTOOLS_TAG=V00-32-XX;CMSDIST_TAG=IB/CMSSW_10_6_X/gcc700;RELEASE_BRANCH=CMSSW_10_6_X;RELEASE_QUEUE=CMSSW_10_6_X;BUILD_PATCH_RELEASE=1;ADDITIONAL_TESTS=HLT,baseline,static-checks,fwlite,valgrind,igprof-mp,igprof-pp,iwyu,lizard,flawfinder,cfipython,gpu,python3;PR_TESTS=1;PROD_ARCH=1;ENABLE_DEBUG=1;PRS_TEST_CLANG=1;DOCKER_IMG=cmssw/cc7:amd64;
```

**Comment by smuzaffar** [comment]
-externals

**Comment by SiewYan** [comment]
@smuzaffar thankyou so much for the information! I will keep it in mind for next time. Sorry about that! i will close it and make a new PR on prod branch.

**Comment by SiewYan** [comment]
Closing, superseded by https://github.com/cms-sw/cmsdist/pull/6196

**Pull request closed without merging**
