### PR TITLE
Fix YODA recipe

### PR DESCRIPTION
**Pull request by iarspider**
"master" branch was renamed to "main"

### CODE REVIEW

**Comment by iarspider** [comment]
testing locally for now, will run Jenkins test later

**Comment by iarspider** [comment]
please test

**Review by smuzaffar — COMMENTED** [review]
@iarspider , may be we take this opportunity and also move to new version 1.9.6?

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
+1

**Pull request merged**
