### PR TITLE
[Backport 12_4_X] Update to HEAD of libunwind master. Patch is no longer needed

### PR DESCRIPTION
**Pull request by aandvalenzuela**
There are some igprof failures due to `Segmentation fault` in `CMSSW_12_4_X` [(Sample log)](https://cmssdt.cern.ch/jenkins/job/ib-run-igprof/32934/console).

I think we need to backport changes made in `CMSSW_12_5_X` by [#7910](https://github.com/cms-sw/cmsdist/pull/7910) to `CMSSW_12_4_X` regarding libunwind (`igprof.spec` are already the same).

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@perrotta @qliphy this is backport to fix igprof for el8 in 12.4.X IBs. Feel free to merge it.

**Comment by perrotta** [comment]
+1
- Good to have in the next 12_4_1

**Pull request merged**
