### PR TITLE
New DCAFPilot version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to b664ac2952acd6042aaa8ff5b8ff54938534847d on slc6_amd64_gcc481.

**Comment by vkuznet** [comment]
Any news on including this PR, originally I got +1 from Diego but labels shows tests-pending. Who decide when to include it into main tree?

**Comment by geneguvo** [comment]
+1 to 37f5dd8e65d0eacb840a022e08bb2a73b774a606 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
"tests-pending" is coming from our offline colleague tools, which does not filter out branches used by COMP when doing any tests.

The "+1" comes from our build-agent as I have said many times. It does not mean that myself had reviewed it, but only tells it passed the build test.

We did not come into the reviewing/commissioning of DCAFPilot yet since we only finished HG1506 last Tuesday, and there is another service to commission which not only came before DCAFPilot request but is also more urgent.

Anyhow, if all you want is this RPM change to be pushed and it is not going to break anything without the corresponding  https://github.com/dmwm/deployment/pull/189, we're fine to push it at any time.

**Comment by vkuznet** [comment]
Diego,
thanks for clarification. I can wait on review/commissioning of DCAFPilot
package, but I prefer RPMs to be pushed into repository. We'll have summer
students who will work on this project and I need them to setup code plus
dependencies w/o holding my personal RPM repo in certain statue. Since
DCAFPilot is independent project I think it is safe to push RPMs only.
If you'll do it in whatever next cycle I'll appreciate it.
Thanks,
Valentin.

**Comment by geneguvo** [comment]
Sure. No problem. I've now pushed it. The RPMs on comp.pre shall be automatically released on the next run of the build-agent.

**Pull request closed without merging**
