### PR TITLE
Rivet 2.5.2 and Yoda 1.6.5

### PR DESCRIPTION
**Pull request by xjanssen**

### CODE REVIEW

**Comment by xjanssen** [comment]
Hi, What is the status of this PR now ? We need to have it integrated at some point to test new rivet plugins ...

**Comment by perrozzi** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
The added root dependency for such a trivial need (tiny c++ functions inside an interface to pyroot) in yoda (a package designed as an alternative to root) is pretty unfortunate..

**Pull request merged**
