### PR TITLE
update htcondor to 8.5.4

### PR DESCRIPTION
**Pull request by hufnagel**
Lots of changes. Had to rework the patch file (some removals, some changes, some additions) and had to remove everything related to the perl related workarounds as it didn't look applicable anymore.

Biggest problem was that the new included Globus 6.0 requires OpenSSL pkginfo file and we didn't ship that with our openssl rpm. So I am creating one from scratch inside the spec file.

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 602b39a3a3593d6a0bcef40c270b9190b3be2613 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2497/test_602b39a-20160906-141506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
Hi all, should we include this PR on HG1610?

**Comment by hufnagel** [comment]
In principle yes, the only holdup was CRAB3 testing.

**Comment by BrunoCoimbra** [comment]
I'll keep this PR open until Marco confirms Crab is good to go.

**Comment by BrunoCoimbra** [comment]
Got Marco's approval.

**Pull request closed without merging**
