### PR TITLE
Update cmssw-wm-tools.spec

### PR DESCRIPTION
**Pull request by davidlange6**
Adding the ability to make PSets if they do not already exist

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , please update the version date

**Comment by smuzaffar** [comment]
please test
ok I updated the version

**Comment by smuzaffar** [comment]
we are in process of building 12.1.0.pre2, once that is uploaded then I will merge and deploy it on cvmfs

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
