### PR TITLE
3 new packages

### PR DESCRIPTION
**Pull request by alja**
I have added 3 new packages.

CondFormats/Serialization and Geometry/CommonDetUnit were needed to compile exiting fwlite_build_set list.

I've got request from visualization HN that DataFormats/MuonSeed is included in FWLite. This is the reason why it is added here.

### CODE REVIEW

**Comment by alja** [comment]
+1
@osschar please watch this as well

**Comment by ktf** [comment]
@davidlange6

**Comment by smuzaffar** [comment]
Looks like current fwlite application set needs 154 more packages to compile (all due to source dependencies) https://cmssdt.cern.ch/SDT/html//rc//slc6_amd64_gcc481/www/sun/7.3-sun-02/CMSSW_7_3_X_2015-03-01-0200//BuildSet/fwlite/index.html . Currently fwlite release contains only 117 package. So I am not sure if we want to 154 packages more there which might bring in more externals.

One simple thing we can do is to make only <package>/interface directory of few packages part of fwlite build set e.g. only following 6 are needed to get the fwlite compiled
CondFormats/Serialization/interface
DataFormats/TrackerCommon/interface
FWCore/Framework/interface
Geometry/CommonDetUnit/interface
Geometry/TrackerGeometryBuilder/interface
RecoLocalCalo/HcalRecAlgos/interface
SimDataFormats/JetMatching/interface

**Comment by davidlange6** [comment]
not good.

what is bringing in RecoLocalCalo/HcalRecAlgos?

**Comment by slava77** [comment]
https://github.com/cms-sw/cmssw/pull/5389
DataFormats/METReco/interface/HcalNoiseHPD.h:#include
"RecoLocalCalo/HcalRecAlgos/interface/HcalCaloFlagLabels.h"
It was there since September.

Visual compliance checks don't always work.
Can we get a build test for this?

On 3/6/15 3:27 AM, David Lange wrote:

> not good.
> 
> what is bringing in RecoLocalCalo/HcalRecAlgos?
> 
> > On Mar 6, 2015, at 10:24 AM, Malik Shahzad Muzaffar notifications@github.com wrote:
> > 
> > Looks like current fwlite application set needs 154 more packages to compile (all due to source dependencies) https://cmssdt.cern.ch/SDT/html//rc//slc6_amd64_gcc481/www/sun/7.3-sun-02/CMSSW_7_3_X_2015-03-01-0200//BuildSet/fwlite/index.html . Currently fwlite release contains only 117 package. So I am not sure if we want to 154 packages more there which might bring in more externals.
> > 
> > One simple thing we can do is to make only /interface directory of few packages part of fwlite build set e.g. only following 6 are needed to get the fwlite compiled
> > CondFormats/Serialization/interface
> > DataFormats/TrackerCommon/interface
> > FWCore/Framework/interface
> > Geometry/CommonDetUnit/interface
> > Geometry/TrackerGeometryBuilder/interface
> > RecoLocalCalo/HcalRecAlgos/interface
> > SimDataFormats/JetMatching/interface
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-sw/cmsdist/pull/1427#issuecomment-77530090.

## 

---

 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

---

**Comment by smuzaffar** [comment]
@slava77, what kind of test?

**Comment by slava77** [comment]
Similar to the duplicateReflexLibrarySearch.py functionality
where it reports DFs defined in wrong places,
there can be a test for includes in DF to be only from allowed packages.

I'm fixing the RecoLocalCalo thing now

On 3/6/15 4:00 AM, Malik Shahzad Muzaffar wrote:

> @slava77 https://github.com/slava77, what kind of test?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-sw/cmsdist/pull/1427#issuecomment-77534318.

## 

---

 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

---

**Comment by smuzaffar** [comment]
We have a script which checks for dependency rules  https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Utilities/ReleaseScripts/scripts/CMSSWReleaseDependency.rules 
which basically we are using to control oracle, geant4 qt dependencies. I think we can have FWLiteDependency.rules to check its dependencies. I will work on it and will try to run it for each PR

**Comment by slava77** [comment]
After changes in #8113 I made git greps for Reco in DataFormats includes and didn't find anything else on top of this RecoLocalCalo/HcalRecAlgos/interface/HcalCaloFlagLabels.h.

**Comment by ghost** [comment]
I'm closing this PR complain if not happy.

**Pull request closed without merging**
