### PR TITLE
Updated dd4hep to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**
Following https://github.com/AIDASoft/DD4hep/pull/545

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@ianna looks like we need to update DD4Hep unit tests to go with this update. If neded @mrodozov can provide you a local build of this on cmsdev so that you can fix these unit tests.

**Comment by mrodozov** [comment]
on cmsdev20
```
scram p CMSSW_11_0_X_2019-08-08-1100
cp /build/mrodozov/build_dd4hep/slc7_amd64_gcc700/external/dd4hep-toolfile/1.0-cms/etc/scram.d/dd4hep* CMSSW_11_0_X_2019-08-08-1100/config/toolbox/slc7_amd64_gcc700/tools/selected/
cd CMSSW_11_0_X_2019-08-08-1100 ; cmsenv ; scram setup ;
git-cms-addpkg DetectorDescription/DDCMS
scram b -j 16 
scram b runtests_testDD4hepCompactView
```
just tried it, should work

**Comment by ianna** [comment]
Please take
https://github.com/cms-sw/cmssw/pull/27728

On 8 Aug 2019, at 14:38, Mircho Rodozov <notifications@github.com> wrote:


on cmsdev20

scram p CMSSW_11_0_X_2019-08-08-1100
cp /build/mrodozov/build_dd4hep/slc7_amd64_gcc700/external/dd4hep-toolfile/1.0-cms/etc/scram.d/dd4hep* CMSSW_11_0_X_2019-08-08-1100/config/toolbox/slc7_amd64_gcc700/tools/selected/
cd CMSSW_11_0_X_2019-08-08-1100 ; cmsenv ; scram setup ;
git-cms-addpkg DetectorDescription/DDCMS
scram b -j 16
scram b runtests_testDD4hepCompactView


just tried it, should work

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#27728

**Comment by smuzaffar** [comment]
thanks @ianna , tests are running now

**Comment by smuzaffar** [comment]
+externals
@fabiocos , this along with cms-sw/cmssw#27728 are ready to go in.

**Comment by fabiocos** [comment]
@smuzaffar @ianna I'll merge this and the parallel CMSSW update into the next IB

**Comment by fabiocos** [comment]
+1

**Pull request merged**
