### PR TITLE
Update to CUDA 12.4.1

### PR DESCRIPTION
**Pull request by fwyzard**
Update to CUDA 12.4.1:
  * CUDA runtime version 12.4.127
  * NVIDIA drivers version 550.54.15

See https://docs.nvidia.com/cuda/archive/12.4.1/cuda-toolkit-release-notes/index.html for the full CUDA 12.4.1 release notes and change log.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by iarspider** [comment]
@cmsbuild ignore tests-rejected with ib-failure

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
