### PR TITLE
[dependabot] Update grpcio and grpcio-tools to 1.60.1

### PR DESCRIPTION
**Pull request by iarspider**
https://github.com/cms-sw/cmsdist/security/dependabot/301

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@iarspider , looks like this update did not go well for ppc64le ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/build-any-ib/CMSSW_14_1_X_2024-02-12-2300/el8_ppc64le_gcc12/172292/external/py3-grpcio/1.60.1-59bbf78864765405ce8817233514a0fb/log ) can yo uplease check and provide a fix

**Comment by iarspider** [comment]
The core reason is that pygrpcio uses BoringSSL, which explicitly refuses to support anything but AMD64/AARCH64 architectures.

**Pull request merged**
