### PR TITLE
[9.3.X] [Geant4]: Fixed muon stopping

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #4143
This include updates propose here: https://github.com/cms-externals/geant4/pull/34

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@civanch I understand that this backport was suggested as a fix for rare crashes in production, so it makes sense to have it as we need to build a new 93X

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
+externals

**Comment by fabiocos** [comment]
merge

**Comment by civanch** [comment]
@fabiocos , yes you are right.

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
