### PR TITLE
ROOT master - remove a commit to fix failure

### PR DESCRIPTION
**Pull request by mrodozov**
removing https://github.com/root-project/root/commit/875e8fb91418f9e520e5d9b22fb1d32f4a42faf0

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test with CMSSW_12_0_ROOT6_X_2021-04-27-2300
I'd rather check this against the last stable ROOT IB

**Comment by mrodozov** [comment]
please test for CMSSW_12_0_ROOT6_X_2021-04-27-2300

**Comment by mrodozov** [comment]
please test with CMSSW_12_0_ROOT6_X_2021-04-27-2300

**Comment by mrodozov** [comment]
test parameters:
- release = CMSSW_12_0_ROOT6_X_2021-04-27-2300

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort
the comparison failed

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@slava77 this differences are present now also in the 6-24 test
are they reasonable/explicable/expected ? it's always this workflow

**Comment by smuzaffar** [comment]
@mrodozov the differences are due to different input used for workflow 140.53. I would suggest to re run the tests

**Comment by mrodozov** [comment]
please test
ok lets

**Comment by slava77** [comment]
> @slava77 this differences are present now also in the 6-24 test
> are they reasonable/explicable/expected ? it's always this workflow

ignoring  140.53, there are some unexpected points:
-  a failure in a comparison job for wf 140.56 https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_ROOT6_X_2021-05-02-0000+471dce/42578/validateJR/all_OldVSNew_RunHI2018wf140p56/all_OldVSNew_RunHI2018wf140p56.log
- differences in recoForwardProtons_ctppsProtons_multiRP_reRECO_obj_xiError (which is related to access to a data member of type `ROOT::Math::SMatrix<float, 5, 5, MatRepSym<float, 5>>`)

**Comment by slava77** [comment]
> there are some unexpected points:

and they were repeated in the latest test results



> * Reco comparison results: 14 differences found in the comparisons
> 
> * Reco comparison had  1 failed jobs

It seems like the two ROOT versions are not quote compatible.

**Pull request merged**
