### PR TITLE
[ROOT 6-20] Updated root to tip of branch v6-20-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test
I updated dd4hep

**Comment by mrodozov** [comment]
test parameters:
- pull_request=https://github.com/cms-sw/cmssw/pull/28965

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
Oh well :/ This is related to issue https://github.com/AIDASoft/DD4hep/issues/617
We have to test it either 
root master
root 6-20 but without the dd4hep changes

**Comment by mrodozov** [comment]
please test
this should work

**Comment by mrodozov** [comment]
abort
have to remove the default cmssw PR

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
updated in the consequent #5595

**Pull request closed without merging**
