### PR TITLE
Full migration to lhapdf6

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
Will we need any changes to pythia8 or herwig++ configuration fragments?

**Comment by mkirsano** [comment]
For pythia8 "LHAPDF5" should be substituted by "LHAPDF6" in the PDF command (pythia parameters)
herwig++ should be OK. The extension (like .LHpdf) is irrelevant, to be removed, but should work. The same for sherpa.

**Comment by bendavid** [comment]
Ok thanks.  We can wait for this to be merged and then add the needed config changes to cmssw afterwards.  (LHAPDF is not used for most standard pythia8 workflows in any case.)

**Comment by ghost** [comment]
@bendavid @mkirsano testing this locally.

**Comment by ghost** [comment]
+1
Tested full compilation up to cmssw-tool-conf.
Tested the packages:
GeneratorInterface/Pythia8Interface
GeneratorInterface/TauolaInterface
GeneratorInterface/ThePEGInterface
against this PR, no issues found during compilation.

**Pull request merged**
