### PR TITLE
Add patch for pythia8 and c++20; update alpaka to pick up fix for c++20

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_13_2_CPP20_X

**Comment by smuzaffar** [comment]
please test for CMSSW_13_2_CPP20_X

**Comment by iarspider** [comment]
please test for CMSSW_13_2_CPP20_X

**Comment by iarspider** [comment]
The failure doesn't seem to be related to changes in this PR.

**Comment by smuzaffar** [comment]
mergeing it now,
@iarspider , I think alpaka change can go in master IBs too

**Pull request merged**
