### PR TITLE
[G4][geant4_vecgeom] Update geant4 to 10.7.2

### PR DESCRIPTION
**Pull request by mrodozov**
This branch is identical to master for geant4 and vecgeom.
We can start building that IB again for G4 people to do their tests/validation
Currently there is no fresh IB for this branch

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@civanch we can get this in for the geant4_vecgeom since it's a devel IB anyway

**Comment by mrodozov** [comment]
+externals

**Comment by civanch** [comment]
This PR may be merged to this branch. For the master we will need extra validations.

**Pull request merged**
