### PR TITLE
Up dqmgui package to 9.7.8

### PR DESCRIPTION
**Pull request by pmandrik**
Update cmsgui to https://github.com/cms-DQM/dqmgui_prod/releases/tag/9.7.8
See changes here https://github.com/cms-DQM/dqmgui_prod/pull/12

### CODE REVIEW

**Comment by arooshap** [comment]
+1 to c32e9327bff382e69d1886753eac6b6d37686286 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8115/test_c32e932-20221003-104502.log" target="_blank">here</a>.

**Comment by arooshap** [comment]
Hi @pmandrik, your request has been merged in the `HG2210c` release in the testbed. You may consult it [here](https://github.com/cms-sw/cmsdist/pull/8115).


You may get started with the validation. :)


Thanks,
Aroosha

**Comment by muhammadimranfarooqi** [comment]
Hi @pmandrik 

Is this PR ready for production deployment? Kindly update. Thanks

**Comment by pmandrik** [comment]
Hi, @arooshap & @muhammadimranfarooqi . Thank you for the reminder. Do I understand correctly that https://cmsweb-testbed.cern.ch/dqm/offline/ is updated with new code? If yes, than in the JS code of the page I do not see the expected changes, while they are for sure available in https://github.com/cms-DQM/dqmgui_prod/releases/tag/9.7.8 zip file.
E.g. please check screenshots of testbed offline JS and online that was updated directly to new version.
Screenshot from 2022-10-06 15-58-04
Screenshot from 2022-10-06 15-58-00

**Comment by muhammadimranfarooqi** [comment]
Hi @pmandrik 

No, offline gui is production VM. The changes have not been deployed there. The PR is only deployed in dev gui i.e. `vocms0731`. If these changes will only appear in offline gui then we can proceed with production deployment

**Comment by pmandrik** [comment]
Hi, I see the required changes and everything works fine. The PR is ready for production deployment.

**Pull request merged**
