### PR TITLE
Update tag for RecoEgamma-ElectronIdentification to V01-01-04-01-00

### PR DESCRIPTION
**Pull request by mrodozov**
Move RecoEgamma-ElectronIdentification data to new tag, see
cms-data/RecoEgamma-ElectronIdentification#20

### CODE REVIEW

**Comment by mrodozov** [comment]
+externals
needs cms-sw/cmssw#33620

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#33620

**Comment by qliphy** [comment]
+1

**Pull request merged**
