### PR TITLE
Update root spec on CMS master branch - v6-10 patches to latest commit

### PR DESCRIPTION
**Pull request by mrodozov**
Update IB/CMSSW_10_1_X/gcc630 root.spec to tip of root v6-10 patches

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@fabiocos , @slava77 can you please check this comparison ?

**Comment by slava77** [comment]
@smuzaffar 
there are no changes in reco monitoring (validateJR plots confirm that).

The DQM shows changes in L1 Tau plots, which I think I've seen to change randomly in the past for PRs with significant recompilations.
e.g.
wf136 788_tauphi
wf136 788_tauphi_2nd

@rekovic @apana @thomreis @nsmith-

**Comment by thomreis** [comment]
What is the difference in the setup between the red and black histograms?

**Comment by slava77** [comment]
black is the baseline IB.
Red is baseline+PR.
If you are more familiar with the relmon plots, please compare the same to e.g.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-19-2300+3752/25168/136.788_RunSinglePh2017B+RunSinglePh2017B+HLTDR2_2017+RECODR2_2017reHLT_skimSinglePh_Prompt+HARVEST2017/HLT_TAU_Inclusive_L1.html

or more diffs in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-19-2300+3752/25168/136.788_RunSinglePh2017B+RunSinglePh2017B+HLTDR2_2017+RECODR2_2017reHLT_skimSinglePh_Prompt+HARVEST2017/L1T_L1TStage2CaloLayer2_Isolated-Tau.html

**Pull request merged**
