### PR TITLE
[14.0.X] Update tag for RecoBTag-Combined to V01-21-00

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmsdist/pull/9082
Needed by https://github.com/cms-sw/cmssw/pull/44756

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
+externals

it is backport and only new data file added. So can be merged safely

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
