### PR TITLE
[CXXMODULE] Update to latest root master changes

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
test parameters:
- full_cmssw = true

**Comment by aandvalenzuela** [comment]
please test

**Comment by davidlange6** [comment]
Again, why bother? If the master branch PR is ok, please just merge

**Comment by smuzaffar** [comment]
lets get this in CXXMODULE IB

**Pull request merged**
