### PR TITLE
Update PhysicsTools-NanoAOD to tag V01-00-02

### PR DESCRIPTION
**Pull request by mrodozov**
Description: cms-data/PhysicsTools-NanoAOD#3

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
@smuzaffar @mrodozov it is ok to integrate this package, but this should now go to IB/CMSSW_10_2_X/gcc630

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
abort

**Comment by fabiocos** [comment]
+1

**Pull request merged**
