### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

- User test area not present in `/cvmfs`.

**Comment by smuzaffar** [comment]
@aandvalenzuela , when external packages failed to build then there is no user area available on cvmfs. looks likedd4hep failed to build with root master. I would suggest to check with dd4hep maintainers , they might already have a fix for this.

**Comment by aandvalenzuela** [comment]
Fixed by https://github.com/AIDASoft/DD4hep/pull/987. Taking latest changes in a new PR + dd4hep version update.

**Pull request closed without merging**
