### PR TITLE
Update ROCm to 6.2.4 and GPU targets

### PR DESCRIPTION
**Pull request by fwyzard**
Update ROCm to version 6.2.4:
  - add `amd-smi` and ROCProfiler binaries and libraries
  - for the changes since ROCm 5.6.1, see the release notes for [ROCm 5.7.1](https://rocm.docs.amd.com/en/docs-5.7.1/release.html), [ROCm 6.0](https://rocm.docs.amd.com/en/docs-6.0.0/about/release-notes.html), [ROCm 6.1.2](https://rocm.docs.amd.com/en/docs-6.1.2/about/release-notes.html) and [ROCm 6.2.4](https://rocm.docs.amd.com/en/docs-6.2.4/about/release-notes.html).

Update the AMD GPU targets to those officially supported by ROCm 6.2.4, available to the public, and not deprecated:
  - Radeon Pro W6800, W7600†, W7800/W7900
  - Instinct MI100, MI210/MI250, MI300A/MI300X

See [this list](https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.2.4/reference/system-requirements.html) for more details.

---
† not officially supported but actively tested.

### CODE REVIEW

**Comment by fwyzard** [comment]
This _may_ fail with something similar to https://github.com/cms-sw/cmssw/issues/44821 , but we need a build in order to test any potential fixes.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for CMSSW_14_2_NONLTO_X

**Comment by smuzaffar** [comment]
as expected, it failsed with the same errors we have in https://github.com/cms-sw/cmssw/issues/44821#issuecomment-2072897252 . 

```
===========================================================
#5  0x0000154414274aab in std::filesystem::__cxx11::path::~path() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_NONLTO_X_2024-11-17-0000/external/el8_amd64_gcc12/lib/librocprofiler-register.so.0
#6  0x0000154414274acc in std::filesystem::__cxx11::path::~path() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_NONLTO_X_2024-11-17-0000/external/el8_amd64_gcc12/lib/librocprofiler-register.so.0
#7  0x00001543d2048534 in DD4hep_Flavor::PluginService::v2::Details::Registry::initialize() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_NONLTO_X_2024-11-17-0000/external/el8_amd64_gcc12/lib/libDD4hepGaudiPluginMgr.so
#8  0x000015446f86de97 in __pthread_once_slow () from /lib64/libpthread.so.0
#9  0x00001543d2044bca in DD4hep_Flavor::PluginService::v2::Details::Registry::factories[abi:cxx11]() () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_NONLTO_X_2024-11-17-0000/external/el8_amd64_gcc12/lib/libDD4hepGaudiPluginMgr.so
#10 0x00001543d2045746 in DD4hep_Flavor::PluginService::v2::Details::Registry::add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DD4hep_Flavor::PluginService::v2::Details::Registry::FactoryInfo) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_NONLTO_X_2024-11-17-0000/external/el8_amd64_gcc12/lib/libDD4hepGaudiPluginMgr.so
#11 0x00001543d2050ba7 in dd4hep_pluginmgr_add_factory_V2 () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_2_NONLTO_X_2024-11-17-0000/external/el8_amd64_gcc12/lib/libDD4hepGaudiPluginMgr.so
#12 0x00001543d20752ab in _GLOBAL__sub_I_DDTestVectorAlgo.cc () from lib/el8_amd64_gcc12/pluginDetectorDescriptionTestPlugins.so
#13 0x0000154470e1511a in call_init (l=<optimized out>, argc=argc

```

**Comment by fwyzard** [comment]
re-targeted to the devel branch

**Comment by smuzaffar** [comment]
+externals

good to go in DEVEL IBs. ROCM IBs is setup to use devel brach. Currently lumi node is offline for [4-day maintenance break](https://lumi-supercomputer.eu/lumi-service-status/information-4-day-maintenance-break-starting-on-monday-18-november-return-to-normal-operation-after-the-power-supply-maintenance/) . Once it is available we will build ROCM_X IB

**Comment by smuzaffar** [comment]
@fwyzard , this has been in devel IBs for over a month now. Is this ready to go in main 15.0.X IBs?

**Comment by fwyzard** [comment]
Ah, I forgot about it... we still need to add the stub to prevent linking to the host libstdc++.

**Comment by fwyzard** [comment]
@smuzaffar I've opened #9630 to try again in the main branch.

**Pull request merged**
