### PR TITLE
Update various low-level packages e.g. pip, setuptools etc.

### PR DESCRIPTION
**Pull request by iarspider**
Amalgamation of #7689 #7662 #7400

### CODE REVIEW

**Comment by iarspider** [comment]
pleas test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
looks good

**Pull request merged**
