### PR TITLE
Update openloops-2.0.b to openloops-2.0.0

### PR DESCRIPTION
**Pull request by SiewYan**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@SiewYan , for OpenLoops 2.0.b we have some optimization done by @davidlange6 and Philipp Maierhoefer 

https://github.com/cms-externals/openloops/commit/5141c0eab4286a4a685f03c4731ff0358e635e54
https://github.com/cms-externals/openloops/commit/5141c0eab4286a4a685f03c4731ff0358e635e54

Looks like these are missing in 2.0.0. Do we not need them?

**Comment by SiewYan** [comment]
Hi @smuzaffar , yes, please include the optimization. Thanks.

**Comment by smuzaffar** [comment]
@mrodozov , can you please get Openloop 2.0.0 tar file and create cms/2.0.0 branch under cms-externals/openloops and include our patches on top of it?

**Comment by mrodozov** [comment]
@SiewYan , I've added the the tar as initial commit on this branch https://github.com/cms-externals/openloops/tree/cms/v2.0.0 and this commit https://github.com/cms-externals/openloops/commit/5141c0eab4286a4a685f03c4731ff0358e635e54 but couldn't add this one https://github.com/cms-externals/openloops/commit/a0fd88934c5c5b83f66fa4791c07f7872ec00a13
as the structure of the code changed.

**Comment by SiewYan** [comment]
Hi @mrodozov thanks for creating the commit. I am adding previous committer @davidlange6 , @davidlange6  could you comment on the patch cms-externals/openloops@a0fd889 is necessary for new openloop 2.0.0? cc @GurpreetSinghChahal

**Comment by davidlange6** [comment]
I think we need a conversation with open loops before committing to some long term maintenance of patches. At least mine came from the authors directly, so its presumably not forgotten, but its hard to tell that.. 

Its impossible to tell from the commit history what is there or not, as the gitlab is maintained just by dumping in snapshots

https://gitlab.com/openloops/OpenLoops/commits/master

since the code has diverged quite a bit (at least in the spot checks I did) some more systematic checks are needed. [well, if anything my checks suggest that the fixes are not in, or else were reimplemented]

**Comment by GurpreetSinghChahal** [comment]
Hi @davidlange6, all: thanks! 

Let me add @jonaslindert (OpenLoops author). Jonas, a few changes were included via [1] and [2] while integrating OpenLoops 2.0.b in CMS software last year. Please suggest us if we still need those updates in OpenLoops 2.0.

@davidlange6: Could you please remind me why these updates were suggested while integrating OpenLoops 2.0.b in CMS software whereas standalone OpenLoops 2.0.b was working without these updates (afaik). Thanks!

[1]: [optimize the factorial function](https://github.com/cms-externals/openloops/commit/5141c0eab4286a4a685f03c4731ff0358e635e54)
[2]: [Avoid Collier initialisation in EW renorm with every integral call
](https://github.com/cms-externals/openloops/commit/a0fd889#diff-97f84fbc3ef6430981aa9791f0930edb)

**Comment by jonaslindert** [comment]
Hi @GurpreetSinghChahal, @davidlange6,

right. There have been structural changes in the code so [2] can not directly be applied anymore.
I will provide a corresponding patch for OpenLoops 2.0.0 in due time and we will incorporate that patch into any future version of OpenLoops. [1] on the other hand can directly be applied. We are reluctant to apply [1] directly in OpenLoops as this concerns the third-party tool COLLIER. However, we notified the authors of COLLIER about this issue. 

cheers,
Jonas

**Comment by davidlange6** [comment]
> 
> @davidlange6: Could you please remind me why these updates were suggested while integrating OpenLoops 2.0.b in CMS software whereas standalone OpenLoops 2.0.b was working without these updates (afaik). Thanks!

Right "working" but with a massive startup time in at least some examples. There are no physics changed, but probably a 50% increase in event throughput in a relval workflow that started to fail because it couldn't run ten events in 2 hours.

> 
> [1]: optimize the factorial function
> [2]: Avoid Collier initialisation in EW renorm with every integral call
>

**Comment by alberto-sanchez** [comment]
process libraries seems missing. That should included in the cms version

**Comment by jonaslindert** [comment]
Hi,

here you find a patch equivalent to [2] linked above. Future versions of OpenLoops will always include this:
https://gitlab.com/openloops/OpenLoops/commit/8ff8f52fe6e0f9f4f3f666b0d89279da64554fc3

cheers,
Jonas

**Comment by SiewYan** [comment]
@jonaslindert  thanks for the patch. thanks @davidlange6 for the clarification. @mrodozov could you proceed with the patching:

https://gitlab.com/openloops/OpenLoops/commit/8ff8f52fe6e0f9f4f3f666b0d89279da64554fc3

Thanks.

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test
run tests based on newer IB (with new geant4)

**Comment by SiewYan** [comment]
Hi all,

Thanks @alberto-sanchez  for pointing out, I found that we are missing the process libraries for openloops, because the Hepforce source is not able to generate process libraries.

The right source to grab is from gitlab [2], in anticipation of changing the source, i have updated Pull request #4796.

@mrodozov , I am not familiar changing the syntex of the Source from github [1], it is possible you could change openloops source pointing to gitlab with tag OpenLoops-2.0.0 [2]?

Thanks very much!
Cheers,

Siewyan

[1] https://github.com/SiewYan/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/openloops.spec#L5
[2] https://gitlab.com/openloops/OpenLoops/tree/OpenLoops-2.0.0

**Comment by mrodozov** [comment]
I took that tag from gitlab.com applied the patches and pushed it on our repo, so if we need to apply patches to be able to and also to skip the gimmick of getting the repo from one place and applying patches from another - within the .spec file. Hope this is fine

**Comment by mrodozov** [comment]
please test

**Comment by SiewYan** [comment]
Thanks @mrodozov for updating the source, its look like the new openloop does not generate process libraries during installation, still, though it is taken from gitlab. The error shows that proclib is missing from the installation , which is present in the previous openloops. 

However, with this command [1], all process libraries will be generated for openloop consumption. Thus with process libraries in place, the necessary *.so will be copied to proclib. Can you please trigger the test again? 

Many Thanks!

@GurpreetSinghChahal , do you think it is wise to include ALL libraries process? The build with all process libraries take extensive among of time.

[1] https://github.com/cms-sw/cmsdist/pull/4796/commits/dfda6e7748b4085bd8d7c7f3e421ef13dd11c186#diff-b687e31aa445c207a10a32a83628ff6dR26

**Comment by mrodozov** [comment]
please test

**Comment by qliphy** [comment]
@fabiocos @mrodozov   Can we merge this now?  This is needed for the next version of Sherpa, i.e. 226

**Comment by fabiocos** [comment]
please test workflow 534.0,536.0

**Comment by fabiocos** [comment]
+1

the needed patches have been applied

**Comment by fabiocos** [comment]
merge

**Pull request merged**
