### PR TITLE
LLVM to 9.0.1

### PR DESCRIPTION
**Pull request by smuzaffar**
@gartung , I included your changes for llvm here https://github.com/cms-externals/llvm-project/commit/379a43bc841451feccf78db64f2ed5c9e62c7de8 . Can you please check if every thing needed is included?

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by smuzaffar** [comment]
please test with cms-sw/pkgtools#153 for CMSSW_11_1_CLANG_X

**Comment by gartung** [comment]
@smuzaffar Yes, all of my changes are in your commit.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung , can you please check why codechecker failed to build with llvm 9?

**Comment by smuzaffar** [comment]
@mrodozov , can you please check if https://github.com/AliceO2Group/O2CodeChecker/pull/30/files is what we need in order to fix codechecker?

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by smuzaffar** [comment]
ping

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by smuzaffar** [comment]
@gartung , looks like we need to update Utilities/StaticAnalyzers for LLVM 9. Can you please look in to it.

**Comment by gartung** [comment]
Is there an RPM for the LLVM build?

**Comment by smuzaffar** [comment]
You can try building it locally using `cms-bot/test-prs.sh cms-sw/cmsdist#5456` command. It should build all externals locally and create cmssw area and checkout packages which needs rebuild.

**Comment by gartung** [comment]
Hmm...that failed unsafe. There must be some missing variable in my environment because the script was trying to rsync / to config/toolbox/slc7_amd64_gcc820/tools/selected
```
tmux,19714
  └─zsh,19715
      └─test-prs.sh,24897 -e cms-bot/test-prs.sh cms-sw/cmsdist#5456
          └─rsync,6133 -a / config/toolbox/slc7_amd64_gcc820/tools/selected/
              └─rsync,6134 -a / config/toolbox/slc7_amd64_gcc820/tools/selected/
                  └─rsync,6135 -a / config/toolbox/slc7_amd64_gcc820/tools/selected/
```

**Comment by gartung** [comment]
@smuzaffar see https://github.com/cms-sw/cmssw/pull/28744

**Comment by gartung** [comment]
test with https://github.com/cms-sw/cmssw/pull/28744

**Comment by smuzaffar** [comment]
thanks @gartung .
Do you have the logs file for test-prs.sh? Looks to me the WORKSPACE is empty in your case but it should not be as it is set here https://github.com/cms-sw/cms-bot/blob/master/test-prs.sh#L2

**Comment by gartung** [comment]
Setting **RELEASE_FORMAT = CMSSW_11_1_CLANG_X** seemed to help.

**Comment by gartung** [comment]
I was running in a tmux session so I did not think to capture the output to log. I only noticed because I got access denied error messages when copying files from /afs!

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by smuzaffar** [comment]
test parameters
  - release = CMSSW_11_1_CLANG_X
  - full_cmssw = true
 - pull_reuqtes = cms-sw/cmssw#28795

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
closing in favor of https://github.com/cms-sw/cmsdist/pull/5505

**Pull request closed without merging**
