### PR TITLE
backport highfive to 10_6_X

### PR DESCRIPTION
**Pull request by SiewYan**
Backporting HighFive #5996 to 10_6_X. In reference to https://github.com/cms-sw/cmssw/pull/30312 @smrenna

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@SiewYan I'm assuming you want this backport for the "default" compiler for 10_6 branch which is gcc700
->  the differences in comparison

**Comment by SiewYan** [comment]
@mrodozov , looks like the test on gcc700 is ok. And yes

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Pull request merged**
