### PR TITLE
Import ROOT 6.12 from CMSSW

### PR DESCRIPTION
**Pull request by schneiml**
This update is needed for the online DQMGUI, since the `ClassDef` version of `TF1` changed between 6.10 and 6.12.

@h4d4 please test and integrate this into CMSWEB asap.

### CODE REVIEW

**Comment by schneiml** [comment]
We should also bump the DQMGUI verison number. Let me see if I can get that into this PR...

**Comment by h4d4** [comment]
-1 to 1387da11f7a81ea5f4a24f83554d63549c4f1312 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4270/test_1387da1-20180816-114504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
to 4ccfc60508682e9f990769488df0ae7fe5081459 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4270/test_4ccfc60-20180816-130504.log" target="_blank">here</a>.

**Comment by rovere** [comment]
@h4d4 could you please re-trigger the build?

Thanks.

**Comment by h4d4** [comment]
@schneiml @rovere Hello Marcel and Marco,
I've just re-triggered this PR.

**Comment by rovere** [comment]
@h4d4 I see no trace of the build on the build machine....

**Comment by h4d4** [comment]
@rovere @schneiml 
boot takes time building root, it's testing, please  see [1] and [2]:

I'm going to send you yesterday's failed test. I've see below message on those logs:
fatal: ambiguous argument '9.3.3': unknown revision or path not in the working tree.

Best aregards, Lina
**[1]**
[lijimene@vocms055 ~]$ tail -f /build/dmwmbld/srv/logs/dmwmbld/dmwmbld-20180817
#4239,
#4066,
Latest status is failure

Testing (#4270), Import ROOT 6.12 from CMSSW...
Cloning into 'cmsdist'...
HEAD is now at e348205 Bump HG1808i.
Applying diff from URL: https://github.com/cms-sw/cmsdist/pull/4270.diff

Building RPMs...

**[2]** 
[dmwmbld@vocms055 4270]$ tail -f test_4ccfc60-20180817-143504.log
Checking if davix is cached.
davix is available from remote repository "comp". Not building. Downloading and installing...
Package external+davix+0.6.7 found in repository
Starting to process package external+cmake+3.7.0
Checking if cmake is cached.
cmake is available from remote repository "comp". Not building. Downloading and installing...
Package external+cmake+3.7.0 found in repository
Creating directory /build/dmwmbld/srv/state/dmwmbld/builds/4270/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07 if not existing.
Building root. Log can be found in /build/dmwmbld/srv/state/dmwmbld/builds/4270/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07/log.
source /build/dmwmbld/srv/state/dmwmbld/builds/4270/w/slc7_amd64_gcc630/rpm-env.sh ; TMPDIR=/build/dmwmbld/srv/state/dmwmbld/builds/4270/w/tmp  rpmbuild  --buildroot /build/dmwmbld/srv/state/dmwmbld/builds/4270/w/tmp/BUILDROOT/00d24a03748323beef489e4c79e7afe9 -ba --define '_topdir /build/dmwmbld/srv/state/dmwmbld/builds/4270/w' --define "compiling_processes 4"  --define "cmscompilerv  630" --define "cmsos slc7_amd64" /build/dmwmbld/srv/state/dmwmbld/builds/4270/w/SPECS/lcg/root/6.12.07/spec >/build/dmwmbld/srv/state/dmwmbld/builds/4270/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07/log 2>&1

**Comment by h4d4** [comment]
@rovere @schneiml
Actually the logs are pointed out above, for example:
https://cms-dmwm-builds.web.cern.ch/cms-dmwm-builds/4270/test_4ccfc60-20180816-130504.log

**Comment by h4d4** [comment]
-1 to 4ccfc60508682e9f990769488df0ae7fe5081459 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4270/test_4ccfc60-20180817-143504.log" target="_blank">here</a>.

**Comment by rovere** [comment]
Clash in namespace, fixing it.

**Comment by h4d4** [comment]
@rovere @schneiml  

I just wondering if this PR will include in next CMSWeb release[1]
I'm asking due to the first comment on this thread, and as you know,
the tag will take 2 weeks to be ready to go to production.

Best Regards, Lina.
[1] https://gitlab.cern.ch/cms-http-group/doc/issues/114

**Comment by rovere** [comment]
@schneiml 
please update this PR with 9.3.4 for DQMGUI that will solve the compilation issue.
I let @schneiml to comment on the inclusion of this release in CMSWeb release, since, honestly, I'm a little lost with the ongoing ROOT versioning situation....

**Comment by schneiml** [comment]
Updated the DQMGUI version.

Regarding the CMSWEB release: While we don't urgently need this for offline/CMSWEB, it would make things easier and more consistent if we can include it.

Ideally, can we have this in a CMSWEB development/test release tag as soon as possible, so we can try that release in online? that would save us the work of manual modifications there. If it then goes into production, we have the same, updated ROOT version on all GUIs and we are on the safe side regrading ROOT changes (for CMSSW 10_2, at least).

**Comment by h4d4** [comment]
+1 to 9290c7ca37ed41b2eb1b7ce0bdf8305561b6c79d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4270/test_9290c7c-20180817-172506.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
@schneiml Marcel,

in this case, I'm going to build a tag into HG1809 release, but just including this PR.
It' should be ready in a couple of hours.
I'll keep you posted.

Best Regards, Lina.

**Comment by threus** [comment]
@h4d4 Hi Lina, cloud you please keep me in cc about HG1809? Thanks!

**Comment by h4d4** [comment]
@schneiml @threus Marcel, Tomas,

I've built and deployed on CMSWeb testbed, the tag HG1809a [1],
it includes dqmgui 9.3.4 and root 6.12.07 as the PR specifies.
root package is now on cmsrep repository[2]

Below the output of one of the testbed nodes, with the HG1809a  installed:
```
[cmsweb@vocms0731 ~]$ ls -lash /data/srv/beHG1809a/sw/slc7_amd64_gcc630/lcg/root/
total 12K
4.0K drwxrwxr-x. 19 _sw _sw 4.0K Aug 20 11:56 6.12.07
```

Best Regards, Lina.
[1] https://github.com/cms-sw/cmsdist/releases/tag/HG1809a
[2]http://cmsrep.cern.ch/cgi-bin/repos/comp/slc7_amd64_gcc630?C=M;O=D

**Pull request merged**
