### PR TITLE
Add HFShowerLibrary_oldpmt_noatt_eta4_16en_v3 to SimG4CMS/Calo data.

### PR DESCRIPTION
**Pull request by ghost**
Remove unused SL file.
Update method of retriving data from afs.

### CODE REVIEW

**Comment by ghost** [comment]
+1
Tested compilation of cmssw package SimG4CMS against this.

**Comment by civanch** [comment]
I have checked privately that this file is working fine in 5_3_X

**Comment by davidlange6** [comment]
@civanch , all

Contrary to my previous understanding, the default workflows are affected by this PR. It seems that we are somehow using the HF shower library by default in full sim?

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc472/CMSSW_5_3_X_2015-03-18-0200/pyRelValMatrixLogs/run/1.0_ProdMinBias+ProdMinBias+DIGIPROD1+RECOPROD1/step1_ProdMinBias+ProdMinBias+DIGIPROD1+RECOPROD1.log

**Comment by civanch** [comment]
@davidlange6 , existence of the file is checked by python even if the file will not be opened. If old file was removed we have to fix g4SimHits. Because old SL was not used by default, this seems to be safe.

**Comment by davidlange6** [comment]
ah right… could you make a PR with the fix?

**Pull request merged**
