### PR TITLE
update some pip packages to most recent release available

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by mrodozov** [comment]
jenkins is returning proxy error , the server is running, I'm trying to understand what's wrong

**Comment by davidlange6** [comment]
hi @mrodozov - I think this is ready to be integrated? (I have more python changes waiting..)

**Pull request merged**
