### PR TITLE
HG1710 testbed WMCore 1.1.7.pre2

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by h4d4** [comment]
to 5c60eecc2817ed4db9b192eab96ff4a5576cd6a2 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3459/test_5c60eec-20170928-044505.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
ping

**Comment by h4d4** [comment]
to 5c60eecc2817ed4db9b192eab96ff4a5576cd6a2 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3459/test_5c60eec-20170928-122506.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
to 5c60eecc2817ed4db9b192eab96ff4a5576cd6a2 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3459/test_5c60eec-20170928-133217.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 5c60eecc2817ed4db9b192eab96ff4a5576cd6a2 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3459/test_5c60eec-20170928-153514.log" target="_blank">here</a>.

**Pull request closed without merging**
