### PR TITLE
DD4Hep - Get latest commits

### PR DESCRIPTION
**Pull request by mrodozov**
please test
DD4hep fails to build in rootmaster, needs latest changes

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Comment by smuzaffar** [comment]
@mrodozov , @ianna looks like this broke 6 unit tests in IBs. 
Can you please chck if it is issue with DD4Hep or cmssw part. I have no idea why tests tests worked for PR testing and failed for IB. Was there any thing DD4Hep related merged in last night IB?

**Comment by ianna** [comment]
@smuzaffar - it looks like the tests have nothing to do with DD4hep

**Comment by ianna** [comment]
```
TESTING all-in-one tool ...
Requesting file information for '/MinimumBias/Run2017A-TkAlMinBias-PromptReco-v1/ALCARECO' from DAS... Done.
Requesting file information for '/Cosmics/Run2017A-TkAlCosmics0T-PromptReco-v1/ALCARECO' from DAS... Done.
Requesting run information for '/HLTPhysics/Run2017A-TkAlMinBias-PromptReco-v1/ALCARECO' from DAS... Done.
Requesting file information for '/HLTPhysics/Run2017A-TkAlMinBias-PromptReco-v1/ALCARECO' from DAS... Done.
Requesting run information for '/JetHT/Run2017B-TkAlMinBias-09Aug2019_UL2017-v1/ALCARECO' from DAS... Done.
Requesting file information for '/JetHT/Run2017B-TkAlMinBias-09Aug2019_UL2017-v1/ALCARECO' from DAS... Done.
Requesting run information for '/DoubleMuon/Run2017A-TkAlZMuMu-PromptReco-v3/ALCARECO' from DAS... Done.
Requesting file information for '/DoubleMuon/Run2017A-TkAlZMuMu-PromptReco-v3/ALCARECO' from DAS... 
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3010] Unable to give access - user access restricted - unauthorized identity used ; Permission denied

cat: emptyModuleList.txt: No such file or directory
Done.

All-In-One Tool: /store/caf/user/cschomak/emptyModuleList.txt does not exist!
Failure running all-in-one test: status 1
status = 256

---> test testAlignmentOfflineValidation had ERRORS
 
```

**Comment by ianna** [comment]
```
----- Begin Fatal Exception 16-Jun-2020 19:00:59 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/relval/CMSSW_9_2_2/RelValProdTTbar_13/AODSIM/91X_mcRun2_asymptotic_v3-v1/10000/EEB99F74-DA4D-E711-A41C-0025905A48F2.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_2_2/RelValProdTTbar_13/AODSIM/91X_mcRun2_asymptotic_v3-v1/10000/EEB99F74-DA4D-E711-A41C-0025905A48F2.root
      [b] Input file root://cms-xrd-global.cern.ch//store/relval/CMSSW_9_2_2/RelValProdTTbar_13/AODSIM/91X_mcRun2_asymptotic_v3-v1/10000/EEB99F74-DA4D-E711-A41C-0025905A48F2.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/relval/CMSSW_9_2_2/RelValProdTTbar_13/AODSIM/91X_mcRun2_asymptotic_v3-v1/10000/EEB99F74-DA4D-E711-A41C-0025905A48F2.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_9_2_2/RelValProdTTbar_13/AODSIM/91X_mcRun2_asymptotic_v3-v1/10000/EEB99F74-DA4D-E711-A41C-0025905A48F2.root?tried=
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
Failure using patTuple_standard_cfg.py: status 84
status = 21504

---> test runtestPhysicsToolsPatAlgos had ERRORS
 
```

**Comment by ianna** [comment]
```
===== Test "checkMultiRunHarvestingOutput" ====
Error in <TFile::TFile>: file DQM_V0001_R000999999__Express__PCLTest__ALCAPROMPT.root does not exist
checkMultiRunHarvesting: ERROR. Could not find the file: DQM_V0001_R000999999__Express__PCLTest__ALCAPROMPT.root

---> test checkMultiRunHarvestingOutput had ERRORS
```

**Comment by ianna** [comment]
none of the above errors are DD4hep related

**Comment by smuzaffar** [comment]
How about https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-06-17-2300/unitTestLogs/DetectorDescription/DDCMS#/2-2 in last night IB

```
===== Test "testDD4hepExpandedView" ====
Running .Info in &lt;TGeoManager::TGeoManager&gt;: Geometry DUMMY, Detector Geometry created
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
CompactLoader    INFO  +++ Processing compact file: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_2_X_2020-06-17-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml with flag (null)
DD4CMS           INFO  +++ Processing the CMS detector description file:///data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_2_X_2020-06-17-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
Info in &lt;TGeoManager::SetTopVolume&gt;: Top volume is world_volume. Master volume is world_volume
Info in &lt;TGeoNavigator::BuildCache&gt;: --- Maximum geometry depth set to 100
Detector         INFO  *********** Created World volume with size: 10100 10100 45000
CTPPS_210_Right_Station:RP_210_Right_Sec_Rot_Angle*deg: Evaluator : unknown variable : CTPPS_210_Right_Station:RP_210_Right_Sec_Rot_Angle*deg
DD4CMS           ERROR Exception while processing xml source:file:///data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_2_X_2020-06-17-2300/src/Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Right_Station.xml
DD4CMS           ERROR ----&gt; dd4hep: Severe error during expression evaluation of CTPPS_210_Right_Station:RP_210_Right_Sec_Rot_Angle*deg
dd4hep: Error interpreting XML nodes of type &lt;Rotation/&gt;
dd4hep: Error interpreting XML nodes of type &lt;RotationSection/&gt;
E

##Failure Location unknown## : Error
Test name: testDDExpandedView::checkExpandedView
uncaught exception of type std::exception (or derived).
- dd4hep: Severe error during expression evaluation of CTPPS_210_Right_Station:
RP_210_Right_Sec_Rot_Angle*deg
dd4hep: Error interpreting XML nodes of type &lt;Rotation/&gt;
dd4hep: Error interpreting XML nodes of type &lt;RotationSection/&gt;
dd4hep: while parsing /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_2_X_202
0-06-17-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
dd4hep: with plugin:DD4hep_CompactLoader

Failures !!!
Run: 1   Failure total: 1   Failures: 0   Errors: 1

---&gt; test testDD4hepExpandedView had ERRORS
```

**Comment by ianna** [comment]
oh, yes. It's from the PPS PR https://github.com/cms-sw/cmssw/pull/30268 

@carl, @civanch, @smuzaffar  - We need to be able to run some integration tests from another subsystem:
If there are any changes in `Configuration/Geometry` we should at least run `DetectorDescription/DDCMS` unit tests. Also, the Geometry validation tests.

**Comment by ianna** [comment]
@mundim - could you, please, update the PPS XML files so that the `ConstantSections` had an `eval` attribute set to `true`?

**Comment by mundim** [comment]
Do you want this in a separate PR ?

**Comment by ianna** [comment]
> Do you want this in a separate PR ?

yes, please

**Comment by mundim** [comment]
Done. PR 30292

**Pull request merged**
