### PR TITLE
[ROOT630] Updated root to tip of branch v6-30-00-patches

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
test parameters:
- full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
test parameters:
- full-cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
test parameters:

- full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
