### PR TITLE
[Backport 12_4] Pythia Update to fix tau decays

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Backport of https://github.com/cms-sw/cmsdist/pull/8139.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test with https://github.com/cms-externals/pythia8/pull/29.

**Comment by aandvalenzuela** [comment]
please test with https://github.com/cms-externals/pythia8/pull/29

**Comment by aandvalenzuela** [comment]
Hi @agrohsje,
Should we also backport it to `12_5` for consistency, although used for heavy ion?
Thank you!

**Comment by perrotta** [comment]
> Hi @agrohsje, Should we also backport it to `12_5` for consistency, although used for heavy ion? Thank you!

@aandvalenzuela please prepare also the backport to 12_5 for whatever is backported to older cycles

**Comment by agrohsje** [comment]
Thanks @aandvalenzuela  and @perrotta! It should not impact HI but better/easier to have it for both.

**Comment by perrotta** [comment]
+1
- As decided during the [ORP meeting of Oct 25](https://indico.cern.ch/event/1208164/) 
- It does not affect minbias production for PU samples

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
