### PR TITLE
New version of WMArchive

### PR DESCRIPTION
**Pull request by vkuznet**
In this version we added:
- MonitManger class to manage docs to be send to monit
- add MonitManger to WMArchive

Switch WMArchive to python3 (experimental, needs to be tested) and new version of WMCore (1.2.7); added new py3-xxx package dependencies.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to 38430e216a3ba31e38c86ba2d7ded9c4a439b0bf on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5330/test_38430e2-20191105-011003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to 391c29075abf2e2af861d0fbada59818d0c6bb34 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5330/test_391c290-20191105-133004.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to c349e486e42eae01150cd1897dba772959574672 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5330/test_c349e48-20191105-161004.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
closing this in favor of #5332 and #5333

**Pull request closed without merging**
