### PR TITLE
[ROOT] root cxx modules

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@vgvassilev , @davidlange6 do we still need this patch https://github.com/cms-sw/cmsdist/blob/mrodozov-patch-3/root_boostmod2.patch?

**Comment by vgvassilev** [comment]
@smuzaffar I think this can go.

**Comment by mrodozov** [comment]
please test
its configuring without the patch now

**Comment by smuzaffar** [comment]
Please test

**Pull request merged**
