### PR TITLE
moving new, tested crab-dev to prod for SL6 compat

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by belforte** [comment]
@smuzaffar thanks for merging.  Will it be OK if I run https://cmssdt.cern.ch/jenkins/job/cms-build-package/ to build crab and deploy on CVMFS ?

**Comment by smuzaffar** [comment]
@belforte , go ahead and start the build job.

**Pull request merged**
