### PR TITLE
HG1804 testbed WCore 1.1.12.pre3

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by h4d4** [comment]
to 04bcf4c93e6d5701c783f577746b9a01326cd343 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3861/test_04bcf4c-20180322-043504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@h4d4 Lina, WMCore didn't have this tag. Can you run the build bot test again?

**Comment by amaltaro** [comment]
please test

**Comment by h4d4** [comment]
@amaltaro  Hi Alan, I've just edited the testing result to re-triggered this PR.
Let's wait for the boot.
Best Regards.

**Comment by h4d4** [comment]
+1 to 04bcf4c93e6d5701c783f577746b9a01326cd343 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3861/test_04bcf4c-20180322-091504.log" target="_blank">here</a>.

**Pull request merged**
