### PR TITLE
Upgrade Herwig 7.1.4 to Herwig 7.2.0

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
Backport of #5765 to upgrade Herwig7 from 7.1.4 to Herwig 7.2.0.
To be tested with: cms-sw/cmssw#29538

Kind regards,
Dominic

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#29538

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test workflow 511.0, 535.0 with cms-sw/cmssw#29538

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
+1
see https://github.com/cms-sw/cmssw/issues/29365 about the DQMHistoTests failures

**Pull request merged**
