### PR TITLE
Updated root to tip of branch v6-12-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
@smuzaffar @mrodozov this is just an update for the new version but does not affect the production one, right?

**Comment by smuzaffar** [comment]
@fabiocos , that is correct. It is just an update to pick up new changes in root 6.12 branch. I did not merge it yet as I am waiting to move to Root 6.12 in production (this PR contains updates on top of what we have in CMSSW_10_2_0_pre1_ROOT612 release).

**Comment by fabiocos** [comment]
@smuzaffar let's see whether there is any news from the validation

**Pull request closed without merging**
