### PR TITLE
Photosppandevtgen 7 1 x

### PR DESCRIPTION
**Pull request by inugent**
Backport: Adding EvtGen and Photos++ to cmsdist in 7_1_X already tested in 7_2X. Note version of Photos++ is being upgraded from 3.55 to 3.56 (includes patch for changes in pythia8 output).

### CODE REVIEW

**Comment by ghost** [comment]
+1
Tested compilation to full cmssw-tool-conf and against GeneratorInteface/EvtGenInterface and GeneratorInterface/PhotosInterface, no issues found.

Please bring this up at next ORP meeting (12/08/2014)

**Comment by bendavid** [comment]
@inugent, even if this is already tested in 72x privately, I think the pull request https://github.com/cms-sw/cmsdist/pull/918 has to be merged into 72x and make it into the IB's first.

**Comment by bendavid** [comment]
Still on hold.  (Not urgent and would like to sort out the Tauola issues first)

**Comment by ghost** [comment]
@inugent @bendavid I just figured out that this PR is missing the relevant parts in cmssw-tool-conf.
I prepared an identical PR to fix this in #1019. 
I am closing this one.

**Pull request closed without merging**
