### PR TITLE
Upgrade pythia8 to 226

### PR DESCRIPTION
**Pull request by smuzaffar**
Use cms-externals/pythia8 repo for sources: this replaces https://github.com/cms-sw/cmsdist/pull/3004
It should go with cms-sw/cmssw#18567

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by perrozzi** [comment]
can this be merged?

**Comment by smuzaffar** [comment]
+externals
@davidlange6 any objections on getting it merged for 71X IBs?

**Comment by davidlange6** [comment]
was brought up on the orp last week (and is on the orp agenda) - wanted validation report in 92x

**Comment by perrozzi** [comment]
cfr https://github.com/cms-sw/cmssw/pull/18567#issuecomment-306907935

**Comment by alberto-sanchez** [comment]
@davidlange6 Any comment on the posted plots (validation) in cmssw #18567 : https://github.com/cms-sw/cmssw/files/1059167/pythia8-226-validation.pdf

**Comment by davidlange6** [comment]
+1

**Pull request merged**
