### PR TITLE
WMCore pre-release candidate 1.4.7.pre2 for HG2104

### PR DESCRIPTION
**Pull request by amaltaro**
Tons of python3 code modernization in.
It also contains ReqMgr2 couchapp changes, so deployment on the VMs will be required **before** the k8s one.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to c409cccb250a3d3d20c487c5b9048728182ad03f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6702/test_c409ccc-20210305-140503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi can you please merge it? I'd suggest to leave the testbed deployment for Monday.

**Comment by amaltaro** [comment]
FYI @todor-ivanov

**Comment by muhammadimranfarooqi** [comment]
@amaltaro ok.

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 
Do you want me to deploy this on testbed today?

**Comment by amaltaro** [comment]
There is no need yet, @muhammadimranfarooqi . There is also a MSTransferor bug that we need to fix.
I should have a pre3 in a couple of days to be pushed to testbed, if that's okay with you.

**Comment by muhammadimranfarooqi** [comment]
ok thanks

**Pull request merged**
