### PR TITLE
[DD4Hep] Update to latest dd4hep dev, Try to fix reflections for volumes and assemblies

### LINKED ISSUE #6390: DD4hep update to master
Please update to DD4hep to master branch:
https://github.com/AIDASoft/DD4hep/pull/736

* This includes a new development in a G4 converter to handle reflected volumes CMS way (adding a prefix `_refl`)
* Fixes Assembly conversion to G4
* Removes duplicate volumes message

@dpiparo and @civanch - FYI

### PR DESCRIPTION
**Pull request by smuzaffar**
resolves https://github.com/cms-sw/cmsdist/issues/6390

### CODE REVIEW

**Comment by mrodozov** [comment]
😅😅😅

**Comment by ianna** [comment]
@smuzaffar - yes, the unit test needs an update to ROOT :-)

**Comment by smuzaffar** [comment]
@ianna , you mean there are still more things in root to be fixed? Note that for this PR test,  we have used root and dd4hep updates, are you expacting more fixes in root?

**Comment by smuzaffar** [comment]
+externals
merging this for IBs

**Comment by ianna** [comment]
> @ianna , you mean there are still more things in root to be fixed? Note that for this PR test, we have used root and dd4hep updates, are you expacting more fixes in root?

hmm... it looks like the two fixes in ROOT still did not fix the issue with a reflected solid title not being copied to a new shape...
Fortunately, when DD4hep provides us with a final version for reflected solids, we'll be able to drop the TGeo reflection factory that causes the title issue.

**Pull request merged**
