### PR TITLE
build CRAB services with py2-future

### PR DESCRIPTION
**Pull request by ddaina**

### CODE REVIEW

**Comment by ddaina** [comment]
@muhammadimranfarooqi ,
please take this PR that builds CRAB services with py2-future. 
*I could not find gitlab issue to make request, so asking here.
Thanks.

**Comment by muhammadimranfarooqi** [comment]
+1 to b4f5136bb144a210c53b1c4ae24b151ce425259a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6621/test_b4f5136-20210205-124502.log" target="_blank">here</a>.

**Comment by ddaina** [comment]
@muhammadimranfarooqi please wait a bit before merging, we are still discussing one thing. thanks.

**Comment by ddaina** [comment]
this is ready to be merged now. 

Imran, there is no need for you to deploy crabserver to testebed, we will do ourselves. Thanks

**Comment by muhammadimranfarooqi** [comment]
+1 to 6102825a2167c51716edfef31ba4b1837c1daaee on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6621/test_6102825-20210205-140503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to a4e975eb141dbf2d46ea403ece555cb529c2c05e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6621/test_a4e975e-20210205-143003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@ddaina 

Is it ready to merge?

**Comment by ddaina** [comment]
yes, now it is ready. :)  Sorry for a mess..

**Pull request merged**
