### PR TITLE
adding new pdl for bc in 7_1_x

### PR DESCRIPTION
**Pull request by alberto-sanchez**

### CODE REVIEW

**Comment by smuzaffar** [comment]
backport of https://github.com/cms-sw/cmsdist/pull/4069

**Comment by smuzaffar** [comment]
please test

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
Does this has to do with the depreciation of https connection to github?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
system curl does not work with cms bootstrap env for older releases. I force data packages to use wget instead

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by alberto-sanchez** [comment]
@fabiocos the MC request which uses this table has been requested. Could you please consider to merge this PR and make a new release?

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
The failing AddOn test has nothing to do with Generators:

----- Begin Fatal Exception 22-Jun-2018 14:41:46 CEST-----------------------
An exception of category 'DDException' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'p'
   [2] Calling event method for module PATElectronSelector/'selectedPatElectrons'
   [3] Calling produce method for unscheduled module PATElectronProducer/'patElectrons'
   [4] Using EventSetup component CaloTopologyBuilder/'' to make data CaloTopology/'' in record CaloTopologyRecord
   [5] Using EventSetup component CaloGeometryBuilder/'' to make data CaloGeometry/'' in record CaloGeometryRecord
   [6] Using EventSetup component EcalBarrelGeometryEP/'' to make data CaloSubdetectorGeometry/'EcalBarrel' in record EcalBarrelGeometryRecord
   [7] Using EventSetup component XMLIdealGeometryESSource/'' to make data DDCompactView/'' in record IdealGeometryRecord
Exception Message:

	DDLParser, algo requested is not defined.  Either AlgoInit() or check algo spelling.
 
		algo=global:angular
		parent=hcalalgo:HRCF
		self=hcalalgo:HEC1
 Element AlgoPosPart
----- End Fatal Exception -------------------------------------------------

It looks funny that this failure did not appear in the recent IB

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar I keep getting this AddOn test failure that is not observed in the base 7_1_X test, even running it in a standalone way. It anyway looks unrelated to the tested external change, as it has nothing to do with EvtGen. Any idea? Otherwise I would just merge it and see what happens in the IB.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
+externals

**Comment by fabiocos** [comment]
@smuzaffar can we merge this for the next IB?

**Comment by fabiocos** [comment]
merge

**Pull request merged**
