### PR TITLE
upgrade lhapdf sets to 6.1.5f

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by ghost** [comment]
please test

**Comment by covarell** [comment]
See:
https://github.com/cms-sw/cmsdist/pull/2037#issuecomment-164173203

**Comment by ghost** [comment]
Although I cannot see how this addon test failure is related to this external, the test run fine in the same IB. The actual log is: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2043/53/addOnTests/pat1/cmsRun__afs_cern.ch_cms_sw_ReleaseCandidates_vol1_slc6_amd64_gcc481_cms_cmssw_CMSSW_7_1_X_2015-12-13-1100_src_PhysicsTools_PatAlgos_test_IntegrationTe.log. 
Does anyone see if the error might be related?

**Comment by ghost** [comment]
@mkirsano What's the status of this PR?

**Comment by mkirsano** [comment]
The tests fail above is not related to this PR - the problem in explained in https://github.com/cms-sw/cmsdist/pull/2037#issuecomment-164173203

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
please test

**Comment by covarell** [comment]
@degano, what to do here? Of course this error cannot be related to PDF changes...

**Comment by ghost** [comment]
+1
I've double checked locally and the error is indeed unrelated. All other tests are fine.
@davidlange6 or Orp should still green light this.

**Comment by ghost** [comment]
please test

**Comment by covarell** [comment]
Can we merge anyway? I think it was discussed several times that the error cannot be related to this PR

**Comment by ghost** [comment]
@covarell I'm re-running the tests only to check the testing script.
The reason this is not merged yet is instead because first needs to be approved by ORP.

**Pull request merged**
