### PR TITLE
 Move back to ROOT 6.18 (11_2)

### PR DESCRIPTION
**Pull request by silviodonato**
Revert of cms-sw/cmsdist#5956 and cms-sw/cmsdist#5997.
Request from PPD to move back to ROOT 6.18 for the 11_1_0 reReco production in order to fix a PSS memory jump in DQM merge (@srimanob)

See: https://sft.its.cern.ch/jira/browse/ROOT-10927

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by srimanob** [comment]
Issue at https://github.com/cms-sw/cmssw/issues/30664

**Comment by mrodozov** [comment]
@silviodonato can we close this one now ?

**Comment by smuzaffar** [comment]
closing this now (already have merge conflicts). Please open a new one if needed

**Pull request closed without merging**
