### PR TITLE
Update RecoBTag-Combined=V01-01-01

### PR DESCRIPTION
**Pull request by mrodozov**
Reopen https://github.com/cms-sw/cmsdist/pull/4540 with changes to avoid conflict (faster than rebase)

### CODE REVIEW

**Comment by slava77** [comment]
tests with cms-sw/cmssw#25376 completed OK and comparisons show differences in expected places/variables.
Let's go ahead with merging.

IMHO, merged single file to contain the external specs will make things more complicated for reviews.

**Comment by smuzaffar** [comment]
@slava77 , data packages are growing this single file will allow us to reduce the number of files in cmsdist. 
For data packages it is more important to review the cms-data PR as compare to cmsdist PR :-)

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@slava77 , I merged it but now I realized that cms-sw/cmssw#25376 is not yet merged. Is it going to break tests if cmssw PR does not go in for 23h IB?

**Comment by slava77** [comment]
On 12/4/18 10:07 AM, Malik Shahzad Muzaffar wrote:
> @slava77
> , I merged it but now I realized that cms-sw/cmssw#25376
> is not yet merged. Is it going to break tests if cmssw PR does not go in
> for 23h IB?
> 

it should be OK in this case.

**Comment by slava77** [comment]
On 12/4/18 10:02 AM, Malik Shahzad Muzaffar wrote:
> @slava77
> , data packages are growing this single file will allow us to reduce the
> number of files in cmsdist.
> For data packages it is more important to review the cms-data PR as
> compare to cmsdist PR :-)
> 

I see.
But I can't run tests of cms-data without a cmsdist PR.
or did this change already?

**Comment by fabiocos** [comment]
+1

for reference

**Pull request merged**
