### PR TITLE
[DD4Hep] update on devel

### PR DESCRIPTION
**Pull request by mrodozov**
Get changes from a pull request (get from master lateer when merged)

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@ianna I think this needs CMSSW adjustments now . External seems to build as it failed later when building CMSSW 
/build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/DetectorDescription/DDCMS/interface/DDFilteredView.h:126:22: error: 'instanceOf' is not a member of 'dd4hep' 
in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f9521c/3043/build.log

**Comment by ianna** [comment]
> @ianna I think this needs CMSSW adjustments now . External seems to build as it failed later when building CMSSW
> /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/DetectorDescription/DDCMS/interface/DDFilteredView.h:126:22: error: 'instanceOf' is not a member of 'dd4hep'
> in
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f9521c/3043/build.log

Thanks, @mrodozov. How can I test the changes locally?

**Comment by mrodozov** [comment]
on cmsdev20
```
cd ${CMSSW_BASE}
cp /build/mrodozov/build_dd4/slc7_amd64_gcc820/external/dd4hep-toolfile/1.0-cms/etc/scram.d/* ${CMSSW_BASE}/config/toolbox/slc7_amd64_gcc820/tools/selected/ 
scram setup
scram b -j 16
```

**Comment by ianna** [comment]
@mrodozov - please, take the following PR https://github.com/cms-sw/cmssw/pull/28224

**Pull request closed without merging**
