### PR TITLE
configure pythia8 to use hepmc3 and hepmc2

### PR DESCRIPTION
**Pull request by mkirsano**
Configure pythia8 to be able to use both conversions: to HepMC2 and HepMC3

### CODE REVIEW

**Comment by mkirsano** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
assign generators
any objections on this change?

**Comment by Saptaparna** [comment]
looks fine, +1 from me.

**Comment by smuzaffar** [comment]
@mkirsano , I would suggest to lets include it in DEVEL IBs to get full tests and if every thing goes fine in DEVEL IBs then I will back port it for master, any objections?

**Comment by mkirsano** [comment]
If this is a normal (and hopefully quick) procedure developed for such cases, no objections

**Comment by smuzaffar** [comment]
as this is bit tricky ( mean pythia8 build with two different versions of hepmc) so I would like to test all relvals and unit tests before including it for next pre-release. I am merging it now and hopefully tomorrow we will have the results of the IB

**Pull request merged**
