### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
testDataFormatsScoutingRun{2,3} - also failing in IBs, https://github.com/cms-sw/cmssw/issues/41222
PrimaryVertex - fails in IBs as well: https://github.com/cms-sw/cmssw/issues/41270
testPVPlotting - I think it's caused by PrimaryVertex failure (corrupt ROOT file?)
HcalPFCuts_unittest - timeout

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
looks good

**Pull request merged**
