### PR TITLE
upgrade to herwigpp 2.7.1 and thepeg 1.9.2

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
This has to go in 72x first as usual

**Comment by bendavid** [comment]
(And also needs to be kept in sync between 71x and 53x at least)

**Comment by mkirsano** [comment]
Requires the modification of CMSSW : PR #4736

**Comment by smuzaffar** [comment]
@davidlange6, should we include this and cms-sw/cmssw#4736 in 53X?

**Comment by bendavid** [comment]
Can we move forward on this one (as also requested on the virtual ORP thread last week?)

**Comment by davidlange6** [comment]
I think I answered in the ORP - but if we are waiting on me… then yes - sounds good to me

**Comment by smuzaffar** [comment]
ok this looks good, I have created an identical request for slc6. I am now merging this for next IB along with cms-sw/cmssw#4736

**Pull request merged**
