### PR TITLE
Python3 specs

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by BrunoCoimbra** [comment]
+1 to 10f71a90442da77f5c253a65b4a98ef2b77d73ef on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2784/test_10f71a9-20170121-153506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to f90b258516d7ee64a57ef70ee9b228596c7ddf80 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2784/test_f90b258-20170302-180510.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
@BrunoCoimbra, @amaltaro , @h4d4, @ticoann
we are testing new jenkins server, so in order to test that we github webhooks work, can any of you please issue ping command?

**Comment by amaltaro** [comment]
ping

**Comment by smuzaffar** [comment]
thanks @amaltaro

**Comment by amaltaro** [comment]
You're very welcome, Shahzad!

**Pull request merged**
