### PR TITLE
Update fastjet to 3.4.0 beta

### LINKED ISSUE #6716: Test the latest fastjet release w/ thread-safety
The latest fastjet release 3.4.0-beta.1 (http://fastjet.fr/all-releases.html) incorporates thread safety improvements. For past fastjet releases, we had to maintain CMS-specific patches for thread safety.

Based on discussion with @rappoccio, CMS should only need the `--enable-limited-thread-safety` mode, so we can avoid the speed penalty from the full `--enable-thread-safety` mode.

It would be good to test this beta release to make sure it is fully compatible with CMSSW.

attn: @laurenhay

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #6716 
fastjet is building, lets see how it goes with cmssw.
we might move it on devel if needed

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
enable threading

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
lets wait for the next IB to include
https://github.com/cms-sw/cmssw/pull/33125
and check if it fixes the first failing relval

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
@kpedro88 could you suggest fastjet relvals for additional testing, or something else you might have in mind ?
It's integrating, from our side it's ok to go in

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by kpedro88** [comment]
@rappoccio @laurenhay should comment

**Comment by rappoccio** [comment]
Apologies, we missed this and were working on this in parallel to this PR. 

We have already requested that the fastjet team could disable all `std::cout` output via preprocessor directives, we are in discussion with them. 

In the meantime: fastjet is used by all reconstruction workflows. @kpedro88 was that what you were referring to?

**Comment by mrodozov** [comment]
@rappoccio note that this is not including your fixes for thread safety from here:
https://github.com/cms-externals/fastjet/tree/cms/v3.3.4
and it's used 'as it is' with additional flag enabled (see the commit diffs)
https://github.com/cms-externals/fastjet/tree/cms/v3.4.0-beta
and if you can suggest a test for the thread safety

**Comment by rappoccio** [comment]
@mrodozov Yes, understood, it should *not* include our patches. Any reconstruction workflow would utilize fastjet (example: matrix test 250202.181). The multithreaded performance should approximately match what is there in previous releases.

**Comment by mrodozov** [comment]
+externals
well then, since the tests are passing and 250202.181 is part of the relvals

**Comment by qliphy** [comment]
+1

**Pull request merged**
