### PR TITLE
Hg1602 dmwmmon datasvc

### PR DESCRIPTION
**Pull request by nataliaratnikova**
Hi ,
please take new DMWMMON-datasvc.spec  
commit https://github.com/cms-sw/cmsdist/commit/5110858be876b75e9c1754dd0f7ecbc80ed8f207

DMWMMON Data Service version 1.1.0 intended for CMSWEB HG1602 release. …

Changelog:
- storageusage  - implemented new algorithm that fixes serious bugs
- getlastrecord - improved documentation
- dumppacequery - new API useful for debugging

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 5110858be876b75e9c1754dd0f7ecbc80ed8f207 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2096/test_5110858-20160127-002505.log" target="_blank">here</a>.

**Comment by nataliaratnikova** [comment]
Hi Diego, 

do you know what is wrong with this pool request? 

I can't find the build log on the link in your comment... it does not seem to exist, please see [*] below. 
( tried on lxplus to bypass the firewalls). 

My own rpm build test on cmsbuild022 was successful. I include tail of the build output in  [**]. 

Any suggestions? 

Thanks, 
 Natalia. 

[*]
-sh-4.1$ wget https://cern.ch/cms-dmwm-builds/2096/test_5110858-20160127-002505.log
--2016-01-27 00:35:33--  https://cern.ch/cms-dmwm-builds/2096/test_5110858-20160127-002505.log
Resolving cern.ch... 188.184.9.234, 2001:1458:201:70::100:26
Connecting to cern.ch|188.184.9.234|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cms-dmwm-builds.web.cern.ch/cms-dmwm-builds/2096/test_5110858-20160127-002505.log [following]
--2016-01-27 00:35:33--  https://cms-dmwm-builds.web.cern.ch/cms-dmwm-builds/2096/test_5110858-20160127-002505.log
Resolving cms-dmwm-builds.web.cern.ch... 188.184.64.13
Connecting to cms-dmwm-builds.web.cern.ch|188.184.64.13|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-27 00:35:33 ERROR 404: Not Found.

[**]

Creating directory /build/ratnik/spacemon/w/BUILD/slc6_amd64_gcc481/cms/DMWMMON-datasvc/1.1.0 if not existing.
Building DMWMMON-datasvc. Log can be found in /build/ratnik/spacemon/w/BUILD/slc6_amd64_gcc481/cms/DMWMMON-datasvc/1.1.0/log.
TMPDIR=/build/ratnik/spacemon/w/tmp  rpmbuild  --buildroot /build/ratnik/spacemon/w/tmp/BUILDROOT/a232eefbe0b54e27042d0894d9609c7b -ba --define '_topdir /build/ratnik/spacemon/w'   --define "cmscompilerv  481" --define "cmsos slc6_amd64" /build/ratnik/spacemon/w/SPECS/cms/DMWMMON-datasvc/1.1.0/spec >/build/ratnik/spacemon/w/BUILD/slc6_amd64_gcc481/cms/DMWMMON-datasvc/1.1.0/log 2>&1
Build successful.
(<function buildPackage at 0x16d87d0>, <Package name=DMWMMON-datasvc>, <scheduler.Scheduler object at 0x1778b10>) done
Nothing else to be done, exiting.
Trying to install the rpm package just built.
Done
Requested to quit.
-sh-4.1$

**Comment by nikmagini** [comment]
Hi Natalia,

I see that one of the github messages is "This branch has conflicts that must be resolved" - it means that you pull request can't be merged for conflicts with the base cms-sw:comp_gcc481 branch, I suppose this is the reason for the build failure (dmwmbld can't even generate the new spec file, so it can't build...)

Anyway, please note that for HG1602 you're supposed to send a pull request to the cms-sw:comp_gcc493 branch instead of cms-sw:comp_gcc481.

So I don't think it's worth solving the conflicts in this pull request...

Please don't send the same pull request to cms-sw:comp_gcc493, instead start fresh, create a new branch in your private repo checking out cms-sw:comp_gcc493, update the spec files in your new private branch, and send a pull request from your new private branch to cms-sw:comp_gcc493.

**Comment by nataliaratnikova** [comment]
Hi Nicolo, Bruno, 

I have just created a new pool request: https://github.com/cms-sw/cmsdist/pull/2098
forked from  the cms-sw:comp_gcc493 branch. 
I see that neither  cms-sw:comp_gcc493, nor cms-sw:comp_gcc481 branch contain the previous version of DMWMMON-datasvc 1.0.5 included in CMSWEB November release.

Also, the PR again contained a warning that it's not able to automatically merge in my file. 
Please let me know if there is something else I need to do. 

Thanks, 
   Natalia.

**Comment by nataliaratnikova** [comment]
The same thing happens for the new PR: no build log found, and build fails...

**Pull request closed without merging**
