### PR TITLE
[106X] Update tag for Configuration-Generator to V01-04-00

### PR DESCRIPTION
**Pull request by tvami**
Backport of https://github.com/cms-sw/cmsdist/pull/8438
and
backport of https://github.com/cms-sw/cmsdist/pull/8440

Connected to https://github.com/cms-data/Configuration-Generator/pull/10 and https://github.com/cms-data/Configuration-Generator/pull/11

### CODE REVIEW

**Comment by perrotta** [comment]
The current Configuration-Generator tag for 10_6_X is V01-00-03, while the tag submitted here is V01-03-00

Is it correct to jump directly from V01-00-03 to the new V01-03-00 in 10_6_X? Were all intermediate tags only including additional files (in which case there are no issues in adding them) or where there some more convoluted changes instead?
It is true that we can always test that new tag in 10_6 and see what happens, but it would be great if @Saptaparna or someone else from generators could confirm.

**Comment by perrotta** [comment]
please test
(just to see what happens. However, I don't think this can be merged as such, unless some list with the content of the intermediate tags is provided)

**Comment by perrotta** [comment]
Tag V01-00-03 corresponds to https://github.com/cms-data/Configuration-Generator/pull/6 (see the message announcing the cmsdist tag at the end of the github thread)

The following ones are:
- https://github.com/cms-data/Configuration-Generator/pull/7 -> it includes fixes for long lived charginos, to be evaluated by generators
- https://github.com/cms-data/Configuration-Generator/pull/8 -> It only adds new files, probably fine
- https://github.com/cms-data/Configuration-Generator/pull/9 -> It only adds new files, probably fine
- https://github.com/cms-data/Configuration-Generator/pull/10 -> what you want in

**Comment by tvami** [comment]
> it includes fixes for long lived charginos, to be evaluated by generators

IIUC @qliphy was GEN L2 back then, maybe he remembers what happened. To me, it just seems like the analysis didnt use UL yet and then it was forgotten to be added later on.

Let me also tag @Saptaparna in this thread, since it seems to be a better place to discuss this than https://github.com/cms-data/Configuration-Generator/pull/10

**Comment by tvami** [comment]
OK the unit test failure is not connected

**Comment by smuzaffar** [comment]
@perrotta @tvami , normally it is fine to backport new data files in old release cycles. New data files do not break any thing and as data packages are only installed once on cvmfs so it is not an overhead for shared distribution. But I see https://github.com/cms-data/Configuration-Generator/pull/7 where data files with respect to V01-00-03 are changed (e.g 465 files were updated to have an extra line with `Block` keyword). I do not know if this change will break any thing in `10.6.X` or not. 

If we want to be really safe then I can create CMSSW_10_6_X branch based on `V01-00-03` tag  and then can merge https://github.com/cms-data/Configuration-Generator/pull/10 on top of it.

**Comment by perrotta** [comment]
Thank you @smuzaffar 

My impression, as well as the one of @tvami , is that the fixes in 7 were never backported to 10_6 simply because that analysis did not move yet on UL. And that without those fixes the generation of long lived charginos cannot even start in 10_6. We have asked confirmation to @cms-sw/generators-l2 for it.

If so, I would rather backport all those fixes at once and have them already available in case of needs, without attempting any gymnastic to backport only the newest ones.

Rather, I am noticing that for 10_6 there are two cmsdist queues:
- CMSSW_10_6_X/gcc700 (this one)
- CMSSW_10_6_X/gcc820

Are we supposed to backport to both them?

**Comment by smuzaffar** [comment]
Only `CMSSW_10_6_X/gcc700` is active branch and in use for 10.6.X ( https://github.com/cms-sw/cms-bot/blob/master/config.map#L59 ). `CMSSW_10_6_X/gcc820` was test branch for testing gcc8 , so no need to open any PR for this. We do not have 10.6.X Ibs for gcc8

**Comment by tvami** [comment]
hold 
 * I need to update the tag with the content of https://github.com/cms-data/Configuration-Generator/pull/11

**Comment by tvami** [comment]
unhold
 * updated to the latest tag

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmsdist/pull/8440

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
ciao @perrotta is the answer in https://github.com/cms-data/Configuration-Generator/pull/7#issuecomment-1510972300 satisfying and we can merge this or you really need an explicit approval from gen?

**Comment by Saptaparna** [comment]
Based on @smuzaffar's response, this is fine and won't affect anything else with regard to UL requests?
I am a bit unclear on the consequences of changing the tag.

**Comment by tvami** [comment]
hi @Saptaparna the change (that is besides my changes) includes fixes for long lived charginos. Based on what Mario said they never requested samples in UL, so in that sense there is no affect on existing UL requests. Mario also said 

>  propagation would indeed be welcome for the future.

(in https://github.com/cms-data/Configuration-Generator/pull/7#issuecomment-1510972300)

**Comment by Saptaparna** [comment]
Spoke to Tamas. 

+1

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/41359 
 * since we are waiting, let me actually clean the tests up

**Comment by smuzaffar** [comment]
+externals

looks good

**Pull request merged**
