### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**
Get latest commits from ROOT

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#26936
the PR is merged but the test picked CMSSW_11_0_ROOT6_X_2019-05-26-2300 and the IB don't have the change

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
See JIRA ticket: https://sft.its.cern.ch/jira/browse/ROOT-10154
during PR tests are we have root in LD_LIBRARY_PATH (one from release and one from local build). I have restarted the tests in full cmssw build mode, this should avoid these unit tests errors

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
