### PR TITLE
HDF5 toolfile cleanup and added openmpi deps

### PR DESCRIPTION
**Pull request by smuzaffar**
@mrodozov , lets try with minimum changes

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
😃 😃  well, if all python packages are building . I'm checking the cmssw pr

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#30312

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
