### PR TITLE
[12.4.X] backport multi-vec build rules and SCRAM

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@perrotta @rappoccio this should fix the SKYLAKE IB failures for 12.4.X IBs. These changes are already in 12.6.X IBs. It would be nice to get these in next 12.4.X full release.

**Comment by perrotta** [comment]
> +externals
> 
> @perrotta @rappoccio this should fix the SKYLAKE IB failures for 12.4.X IBs. These changes are already in 12.6.X IBs. It would be nice to get these in next 12.4.X full release.

Thank you @smuzaffar
Before signing, and not to forget: what about 12_5_X?

**Comment by smuzaffar** [comment]
@perrotta , https://github.com/cms-sw/cmsdist/pull/8082 is for 12.5.X but tests are still running.

**Comment by perrotta** [comment]
+1

**Pull request merged**
