### PR TITLE
Build Py3 dbs3-client from PyPi

### PR DESCRIPTION
**Pull request by amaltaro**
[description updated]
Build python3 dbs3-client and dbs3-pycurl client from PyPi (which uses the freshly created new repositories as well).

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to 5e0928231c5acf88a2a43abe7270d8961486cf67 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7360/test_5e09282-20211005-124503.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
@amaltaro , the actual error is
```
    creating /tmp/muzaffar/pip-req-build-q04u70y_/pip-egg-info/dbs_client.egg-info
    writing /tmp/muzaffar/pip-req-build-q04u70y_/pip-egg-info/dbs_client.egg-info/PKG-INFO
    writing dependency_links to /tmp/muzaffar/pip-req-build-q04u70y_/pip-egg-info/dbs_client.egg-info/dependency_links.txt
    writing requirements to /tmp/muzaffar/pip-req-build-q04u70y_/pip-egg-info/dbs_client.egg-info/requires.txt
    writing top-level names to /tmp/muzaffar/pip-req-build-q04u70y_/pip-egg-info/dbs_client.egg-info/top_level.txt
    writing manifest file '/tmp/muzaffar/pip-req-build-q04u70y_/pip-egg-info/dbs_client.egg-info/SOURCES.txt'
    error: package directory 'src/python/dbs' does not exist
```
looks like new dbs3 client now has `src/python/dbsClient` instead of `src/python/dbs`

**Comment by smuzaffar** [comment]
if intension is to rename the client then replace `dbs` with `dbsClient` here https://github.com/dmwm/DBS/blob/master/Client/setup.py#L34-L36  . If pypi package name is `dbs3-client` then I would suggest to rename the directory to `dbs3-client` instead of `dbsClient`

**Comment by amaltaro** [comment]
Good catch, Shahzad! Thanks

**Comment by amaltaro** [comment]
Oh, actually DBSClient uses a different setup.py script, this one:
https://github.com/dmwm/DBSClient/blob/main/setupPypi.py

@smuzaffar do you know if there is anything I can do to instruct the build script to run this:
```
Running command python setupPypi.py egg_info
```
instead of the default:
```
Running command python setup.py egg_info
```
?

I could try something like `mv setupPypi.py setup.py` as well, but I do not know at which stage of the pip parsing I would have to do that.

**Comment by muhammadimranfarooqi** [comment]
-1 to 74467a1040a6d90ee7de5831e30ee20772384bf4 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7360/test_74467a1-20211007-072010.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
And `patchsrc` is the answer to my question above.
So, I managed to patch the setup.py script, but the build (actually installation) still fails when checking the dependencies, error is:
```
++ pip3 show dbs3-client --disable-pip-version-check
++ grep '^Name:'
++ sed 's|^Name: *||;s| ||g'
+ PKG_NAME=dbs3-client
++ pip3 check --disable-pip-version-check
++ grep '^dbs3-client  *3.17.3  *requires '
++ sed 's|,.*||;s|.* |py3-|'
++ tr '\n' ' '
+ DEPS='py3-dbs3-pycurl '
+ '[' 'py3-dbs3-pycurl ' '!=' '' ']'
+ echo 'ERROR: Missing dependencies for py3-dbs3-client (python3) found: py3-dbs3-pycurl '
ERROR: Missing dependencies for py3-dbs3-client (python3) found: py3-dbs3-pycurl 
+ exit 1
```

which does not make sense to me, since `py3-dbs3-pycurl ` is properly defined in the `Requires` list of py3-dbs3-client spec.
I'm adding a hack line in the spec to actually remove that dependency from the requirements.txt source file.

**Comment by smuzaffar** [comment]
@amaltaro , issue is with `py3-dbs3-pycurl` package. Looks like it installed `dbs-3.4.4` instead of `dbs3-pycurl` e.g. look under  `slc7_amd64_gcc630/cms/py3-dbs3-pycurl/3.17.3/lib/python3.8/site-packages`

**Comment by muhammadimranfarooqi** [comment]
+1 to c9b8e05767702ceab6e0c6eeef4e3164f4b66758 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7360/test_c9b8e05-20211007-080504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to c9b8e05767702ceab6e0c6eeef4e3164f4b66758 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7360/test_c9b8e05-20211007-152503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to c9b8e05767702ceab6e0c6eeef4e3164f4b66758 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7360/test_c9b8e05-20211007-163503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 9aed5bdf8a0b2502aec8287be6ef60849ac51647 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7360/test_9aed5bd-20211012-062510.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 2e781dec987160e0ffdc779c0aefb180ed2acbc7 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7360/test_2e781de-20211012-092004.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 589503e7205403a0ec6515c47546981f77ac6fe0 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7360/test_589503e-20211019-075005.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Basic tests went fine. I'm going to use it with WMCore testbed services and run some further tests tomorrow.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
