### PR TITLE
Pbr fixes

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to fc5d9d6a0d1851a3925a815ed2380e603e521483 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2518/test_fc5d9d6-20160916-164506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
Hi @vkuznet, when should I merge this PR?

**Comment by vkuznet** [comment]
Bruno,
it is ready and can be done at your convenience, i.e. any time.
Thanks,
Valentin.

**Comment by BrunoCoimbra** [comment]
Perfect, so I'll include it in the next tag.
What about https://github.com/dmwm/deployment/pull/381 and https://github.com/dmwm/deployment/pull/382 ?

**Comment by vkuznet** [comment]
Bruno,
please include them too. They are ready.
Thanks,
Valentin.

**Pull request merged**
