### PR TITLE
upgrade lhapdf pdf sets to 6.2.1b

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
checking why it's taking so long to start ...

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
umm there is no IB/CMSSW_10_3_X/gcc630 branch, let me move it on 700

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Comment by efeyazgan** [comment]
Hi, sorry to come back to this late but why this was requested for 10_3 but not 10_2? thanks.

**Comment by mkirsano** [comment]
It was requested for 9_3 and/or 9_4. Before this I usually make the upgrade in master

**Pull request merged**
