### PR TITLE
 Update CUDA to version 9.1.85 

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@smuzaffar , how do I check what broke ?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3629/25069/summary.html does not seem to exist.

**Comment by fwyzard** [comment]
also, why does the error mentions CMSSW_7_2_DEVEL_X_2014-07-08-0900 ?
I thought I made the PR for the 10.0.x queue ?

**Comment by mrodozov** [comment]
@fwyzard let me check it and I'll come back to you. https://cmssdt.cern.ch/jenkins/job/ib-any-integration/25069/console gives a hint it might be cms git tools but I'm not sure yet

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
thanks for fixing the tests

**Pull request merged**
