### PR TITLE
Update LLVM to 12.0

### PR DESCRIPTION
**Pull request by mrodozov**
This is building, but:
uses the existing IWYU branch clang_11 (no clang_12 yet)
existing numba
llvmlite are behind even with the latest tag 0.36

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@smuzaffar no tests failed in cmssw, maybe we can try this in devel now ?

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_CLANG_X

**Comment by smuzaffar** [comment]
please test with #6969

**Comment by smuzaffar** [comment]
please test with #6969

**Comment by smuzaffar** [comment]
+externals
this looks good to go. Thje CLANG IBs will add 8 new compilation warnings [a] but those we can fix later

[a]
- https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4c1a0e/15552/build-logs/L1Trigger/VertexFinder/log.html
- https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4c1a0e/15552/build-logs/OnlineDB/SiStripO2O/log.html

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
looks good, lets get this in. We can fix the new 8 clang warnings once they appear in the clang IBs

**Pull request merged**
