### PR TITLE
Upgrade pythia8 to 305

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
To be tested together with cmssw PR #33898

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#33898

**Comment by iarspider** [comment]
I have a patch for EvtGen, let me figure out how to apply it...

**Comment by iarspider** [comment]
Please test with #6949

**Comment by mrodozov** [comment]
please test with #6949, cms-sw/cmssw#33898

**Comment by iarspider** [comment]
please test with #6949, cms-sw/cmssw#33898, cms-sw/cmssw#33902

**Comment by mrodozov** [comment]
`47440 differences found in the comparisons`
@mkirsano

**Comment by mkirsano** [comment]
After looking attentively at the logs I found a potential problem. Report sent to the authors, thay admitted that it is a problem. Waiting for solution.

**Comment by mkirsano** [comment]
This is to be substituted by the upgrade to 307 in about one week

**Comment by smuzaffar** [comment]
closing this, please open a new PR with updated version (when available).

**Pull request closed without merging**
