### PR TITLE
updating herwig to version 7.1.4 and ThePeG to 2.1.4

### PR DESCRIPTION
**Pull request by alberto-sanchez**

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test workflow 535.0, 511.0

**Comment by mrodozov** [comment]
please test workflow 535.0, 511.0

**Comment by alberto-sanchez** [comment]
error seems unrelated.

**Comment by mrodozov** [comment]
please test
they are not, we had some unavailable eos dataset.

**Comment by mrodozov** [comment]
well we still have the same issue

**Comment by davidlange6** [comment]
hum

[dlange@lxplus100 dlange]$ dasgoclient -query="site file=/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root"
T0_CH_CERN_Export
T0_CH_CERN_MSS
T1_IT_CNAF_Buffer
T1_IT_CNAF_MSS


so its nowhere on disk - but can you confirm if it is or is not on the IB eos space?

david

**Comment by mrodozov** [comment]
There is a file here:
 /store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/
and this works:
runTheMatrix.py -l 4.22 -i all --ibeos

**Comment by davidlange6** [comment]
so aside from eos problems, everything is set up as expected. lets try again

**Comment by davidlange6** [comment]
please test

**Comment by mrodozov** [comment]
This wont work as this file is not found anywhere
```
23-Aug-2018 11:35:43 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root
%MSG-w XrdAdaptorInternal:  file_open 23-Aug-2018 11:35:44 CEST pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 23-Aug-2018 11:35:44 CEST pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root?tried=.
%MSG
23-Aug-2018 11:35:44 CEST  Fallback request to file root://xrootd-cms.infn.it//store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root
%MSG-w XrdAdaptorInternal:  file_open 23-Aug-2018 11:36:51 CEST pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root?tried=+1213xrootd-cms-redir-01.cr.cnaf.infn.it.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 23-Aug-2018 11:36:51 CEST pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root?tried=+1213xrootd-cms-redir-01.cr.cnaf.infn.it,.
```
We can however get the file from 
/store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/
and put it in 
/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/
so that it would be available on eoscms. But I don't have permissions to do that. 
Another way is to pass the --ibeos to the runTheMatrix command.

**Comment by davidlange6** [comment]
> 
> We can however get the file from
> /store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/
> and put it in
> /store/data/Run2011A/Cosmics/RAW/v1/000/160/960/
> so that it would be available on eoscms. But I don't have permissions to do that.
> Another way is to pass the --ibeos to the runTheMatrix command.

the pr tests should already run with --ibeos, no?

**Comment by mrodozov** [comment]
No, but there is a section 'extra matrix args' 
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/29999/parameters/
I restarted the PR with --ibeos argument, if this works I'll configure the job to have it by default.

**Comment by davidlange6** [comment]
hum, i'm surprised. but lets see how things work or not..

**Comment by slava77** [comment]
On 8/23/18 3:03 AM, David Lange wrote:
> hum, i'm surprised. but lets see how things work or not..
> 
>> On Aug 23, 2018, at 11:56 AM, Mircho Rodozov
> <notifications@github.com> wrote:
>>
>> No, but there is a section 'extra matrix args'
>> https://cmssdt.cern.ch/jenkins/job/ib-any-integration/29999/parameters/
>> I restarted the PR with --ibeos argument, if this works I'll configure
> the job to have it by default.
>>

I seem to recall that for jenkins the magic was not the --ibeos but
CMS_PATH=/cvmfs/cms-ib.cern.ch/week0 or similar which eventually makes
the local site catalog point to /store/user/cmsbuild for LFN -> PFN

**Comment by slava77** [comment]
You can even see the evidence of using the cmsbuild in the jenkins log:
```23-Aug-2018 01:10:54 CEST  Initiating request to open file 
root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root
```

the last failures were initially connected to then actually reading that file from EOS:
``` Failed to open file at URL root://p06636710k01172.cern.ch:1095//eos/cms/store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root?cap.msg ... ```

**Comment by mrodozov** [comment]
This option is doing just that:
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L264
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L282
and also now the test passed through step2. I'd still prefer to get the dataset available since PRs are not the only trouble.

**Comment by davidlange6** [comment]
@alberto-sanchez - please fix the title of this PR to reflect what is being updated

**Comment by mrodozov** [comment]
@slava77 I see now, I got confused as the file was there I assumed the default for the job is searching  on its default location. While the problem was that it couldn't open it even it was there.
```
23-Aug-2018 01:10:54 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root
%MSG-w XrdAdaptorInternal:  file_open 23-Aug-2018 01:13:46 CEST pre-events
Failed to open file at URL root://p06636710k01172.cern.ch:1095//eos/cms/store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root?
```
and earlier today:
```
23-Aug-2018 12:46:23 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root
23-Aug-2018 12:46:26 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root
```
& sry for the spam.

**Comment by davidlange6** [comment]
QA differences from premix sample only - certainly not related to these changes

**Comment by davidlange6** [comment]
merge

**Pull request merged**
