### PR TITLE
p5-time-hires is required for crabserver

### PR DESCRIPTION
**Pull request by juztas**
During validation of SLC6 crabserver required p5-time-hires.

Pushing only to SLC6 branch.

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to e14d2ab499614eb2601815f3ba770c749d5efb19 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
Isn't crabserver entirely on python? why do we need a perl library for it?

**Comment by juztas** [comment]
no, it is not entirely on python. it requires to have external condor. I have not tested putting it on condor spec file, but looks like it should go to condor spec file. Rebase pull request ?

```
Executing RPM (/data/srv/HG1408a/sw.pre/slc6_amd64_gcc481/external/apt/0.5.16-comp/bin/rpm-wrapper -Uvh -r /data/srv/HG1408a/sw.pre --force --prefix /data/srv/HG1408a/sw.pre --ignoreos --ignorearch --force --prefix /data/srv/HG1408a/sw.pre --ignoreos --ignorearch --oldpackage)...
error: Failed dependencies:
        perl(Time::HiRes) is needed by external+condor+8.1.6-1-1.x86_64
E: Sub-process /data/srv/HG1408a/sw.pre/slc6_amd64_gcc481/external/apt/0.5.16-comp/bin/rpm-wrapper returned an error code (23)
```

**Comment by geneguvo** [comment]
Yes. I had noticed that before and had it on my stack of patches. Yesterday I've finally pushed it upstream. See:
https://github.com/cms-sw/cmsdist/commit/2adcb60314d2ab3c795150e4a09670fb55d1bc3d

I'm therefore close this PR without picking it.
Cheers,
Diego.

**Comment by juztas** [comment]
Thanks Diego. Closing

**Pull request closed without merging**
