### PR TITLE
Add NVML python bindings [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
Backport of #9134

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #9134

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fwyzard** [comment]
@cms-sw/orp-l2 could you merge this for the next 14.0.x release ?

We need the NVML python bindings to determine the correct CPU-GPU affinity in the new HLT nodes.

**Comment by fwyzard** [comment]
urgent

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
