### PR TITLE
Update pyopenssl to 18.0.0; created spec for all its dependencies

### PR DESCRIPTION
**Pull request by amaltaro**
Main goal was to update the pyopenssl version in order to get two security vulnerabilities fixed, as reported in the WMCore repo:
https://github.com/dmwm/WMCore/network/alert/requirements.txt/pyopenssl/closed

However, several other changes were needed and in short they are:
* updated several other specs, reusing those from the CMSSW 10_4_X branch
* updated build-with-pip to be in sync with the CMSSW branch (rules for py2-* packages installed via pip)
* openssl spec had to be updated to include those 3 cryptograpic algorithms
* python library versions updated as much as possible (including numpy and scipy). Still a bunch to be updated though.

@h4d4 please review and merge when convenient

### CODE REVIEW

**Comment by h4d4** [comment]
-1 to 3471566a68771f53518f2c6d0e107744ce9900de on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_3471566-20181105-141505.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
cffi package is failing to be built because it requires C libraries that are not available.
I'll wait for Shahzad @smuzaffar because he's working on the same thing, then I'll update this patch ;)

**Comment by h4d4** [comment]
-1 to 5a82c5e7615537f7988eff682ddd07bb277210f9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_5a82c5e-20181109-091506.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to a27860641ecd9977439bc99b7258230dd96c2260 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_a278606-20181109-092505.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
@amaltaro and @h4d4 , are you using pkgtools V00-32-XX now?

**Comment by h4d4** [comment]
-1 to 6d045fd6e10d60f80bb09bef8361d4722305495c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_6d045fd-20181109-093506.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
I'm using it in my local tests @smuzaffar , but the bot builder is still on V00-30 I think.
I sent an email to the HN asking @h4d4 to update that (and cc'ed you), please let us know if there is any important information in the new branch which I did not mention in my email. Thanks!

**Comment by h4d4** [comment]
to b8a6295c40763258cf91e65ce8371084fa8f7ee2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_b8a6295-20181109-153508.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
@amaltaro I've edited the latest test output in order to retrigger the PR waiting for results
/build/dmwmbld/srv/current/apps/pkgtools is pointing to V00-32-XX

**Comment by h4d4** [comment]
-1 to b8a6295c40763258cf91e65ce8371084fa8f7ee2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_b8a6295-20181109-182009.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
@amaltaro Alan, 

recalling this[1] I've ensured[2] that /build/dmwmbld/srv/current/apps/pkgtools HEAD points to 
V00-32-XX, but tets are still failing below boot logs(are the same that appear when the PR was tested with V00-30-XX):

Testing (#4479), Update pyopenssl to 18.0.0; created spec for all its dependencies...
Cloning into 'cmsdist'...
HEAD is now at 2b2d0bb Merge pull request #4486 from ticoann/wmagent_1.1.18.patch1
Applying diff from URL: https://github.com/cms-sw/cmsdist/pull/4479.diff
<stdin>:17: trailing whitespace.
## INITENV +PATH PYTHONPATH %i/${PYTHON_LIB_SITE_PACKAGES} 
<stdin>:142: trailing whitespace.
 
<stdin>:158: trailing whitespace.
 
<stdin>:169: trailing whitespace.
 
<stdin>:249: new blank line at EOF.
+
warning: squelched 3 whitespace errors
warning: 8 lines add whitespace errors.

Building RPMs...
Latest status is failure

Best Regards, Lina.
[1] https://github.com/cms-sw/cmsdist/pull/3789#issuecomment-371082106
[2] 
[dmwmbld@vocms055 pkgtools]$ pwd
/build/dmwmbld/srv/current/apps/pkgtools
[dmwmbld@vocms055 pkgtools]$ git log -20 --pretty=oneline --decorate
fad44d44e6bf31ae45828b2f9ddc84bd10f8010f (HEAD, V00-32-XX) Update ChangeLog.md

**Comment by amaltaro** [comment]
No worries Lina, openssl is still broken. I haven't decided how to handle that case yet, either trying to fix that spec or trying to get it upgraded to openssl 1.1.1, but that's much more work then what I was willing to do.

**Comment by h4d4** [comment]
+1 to 2fa1f788ddc1a5013640408108475eb243389d44 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_2fa1f78-20181114-103009.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@h4d4 it has lots of important changes, so let me run some tests in my VM before we consider merging it.

**Comment by smuzaffar** [comment]
@h4d4 and @amaltaro are you using pkgtools V00-32-XX now?

**Comment by amaltaro** [comment]
I used 00-32 in my tests, not sure what Lina has in the build bot though. @h4d4 ?

**Comment by h4d4** [comment]
@amaltaro @smuzaffar 

Yes, the boot is pointing to HEAD of branch  V00-32-XX  please see [1] and [2].

Best Regards, Lina.
[1]
`[dmwmbld@vocms055 pkgtools]$ pwd`
`/build/dmwmbld/srv/current/apps/pkgtools`
`[dmwmbld@vocms055 pkgtools]$ git branch`
 `V00-30-XX`
`* V00-32-XX`
`[dmwmbld@vocms055 pkgtools]$ git log -20 --pretty=oneline --decorate`
`fad44d44e6bf31ae45828b2f9ddc84bd10f8010f (HEAD, V00-32-XX) Update ChangeLog.md`
`35c2a7d07cdb64c5cc0aca6ad4c97db98cfc0bd1 Update ChangeLog.md`
`c09c2ed2b6d63cfc3b8710d3b44c110828aeaf25 Update ChangeLog.md`
`3614383d317d4c1a005aa3679a3bfcca29cd31a1 Create ChangeLog.md`
[2]
`[dmwmbld@vocms055 pkgtools]$ pwd`
`/build/dmwmbld/srv/current/apps/pkgtools`
`[dmwmbld@vocms055 pkgtools]$ git branch`
 ` V00-30-XX`
`* V00-32-XX`
`[dmwmbld@vocms055 pkgtools]$ git log -20 --pretty=oneline --decorate`
`fad44d44e6bf31ae45828b2f9ddc84bd10f8010f (HEAD, origin/V00-32-XX, V00-32-XX) Update ChangeLog.md`
`35c2a7d07cdb64c5cc0aca6ad4c97db98cfc0bd1 Update ChangeLog.md`
`c09c2ed2b6d63cfc3b8710d3b44c110828aeaf25 Update ChangeLog.md`

**Comment by h4d4** [comment]
+1 to c343f3704a65417b43d2bb9a2406d2c81e6e2f59 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_c343f37-20181115-155008.log" target="_blank">here</a>.

**Review by vkuznet — COMMENTED** [review]
Alan,
could you please clarify few things:
- why do you delete blocks which generate dependencies-setup.{sh,csh} for specific package
- how versioning is handling when you apply build-with-pip, as far as I know pip will download and install latest version while rpm spec explicitly defines the version of packages
- you also used pip2 install which implies that specific packages will need to be re-factored again when we'll switch to python3. Can we introduce a pip spec which will define "our" pip (which so far will be pip2 and later will be pip3) and then rely on it everywhere in other specs (via required) and use our pip to install packages.

**Comment by smuzaffar** [comment]
@vkuznet , I can answer these
- cmsBuild now auto generate these dependencies-setup.{sh,csh} files for all packages. It only does if they are not explicitly generated by a package.
- pip install is run with --no-deps , so it will not download and install the package dependencies. But to make sure that all dependencies of a package are available we use pip check after the build. See build-with-pip implementation for details.
- In comp you only have python2 so that is why Alan dropped the python3 sections otherwise build-with-pip (https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_4_X/gcc700/build-with-pip.file) should be able to install packages for both py2 and py3.

**Comment by amaltaro** [comment]
Thanks for answering those questions, @smuzaffar . One more thing though, when you say "cmsbuild now auto generate...", this is one of the features from the new pkgtools, isn't it? I had a look at your release notes but I couldn't find it.

**Comment by smuzaffar** [comment]
changelog for pkgtools V00-32-XX is available here https://github.com/cms-sw/pkgtools/blob/V00-32-XX/ChangeLog.md
I think the dependencies-setup.{sh,csh} feature was already in V00-30-XX but one need to have https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_4_X/gcc700/rpm-preamble.file#L240-L264 
if you do nto have these macros in your cmsdist/rpm-preamble.file then please add them there.

**Comment by amaltaro** [comment]
We have the `addDependency` macro in the comp version and apparently one has to explicitly call it in order to build the dependencies* files. 

I didn't get though why the new macro (that you pointed out) doesn't need to be explicitly called from every spec we want to build those files? Is there any other changes that enforce that macro `AutoSetupDependencies` to be called for every single spec?

**Comment by smuzaffar** [comment]
`addDependency` was added by @vkuznet when cmsBuild did not have the support for generating these files. For  `addDependency` one has to added it explicitly in every spec file and then in `%post` section you have to relocate these files. New macros `AutoSetupDependencies`  are automatically added in the spec by cmsBuild.

**Comment by amaltaro** [comment]
Ok. I see further changes in the PR that you made back in 2017. I think that change is decoupled from this one, so I'll create a new PR with what I understood so far and ask for your review. Thanks

**Comment by smuzaffar** [comment]
sure.
If I understand correctly `addDependency` is used only by py3 packages of @vkuznet. So you can keep the definiton of  `addDependency` and just add the extra macros in rpm-preamble.file Or better to cleanup all spec and let cmsBuild take care of the dependencies :-)

**Comment by smuzaffar** [comment]
@amaltaro , by the way you might want to see the latest changes we did for pip packages https://github.com/cms-sw/cmsdist/pull/4514. Now cmsBuild can auto generate py2-* spec . May be you want to take advantage of this and cleanup comp cmsdist :-)

Now pip packages are listed in pip/requirements.txt file (e.g. here https://github.com/cms-sw/cmsdist/pull/4514/files#diff-8d33d96e5ae1b0fd471d1a8fa5d1ff6b) and cmsBuild can generate spec files out of this list. This will be helpful in future when we want to generate py3-*.spec

**Comment by amaltaro** [comment]
Thanks, Shahzad. At this rate, I guess we'll never manage to converge (or get closer to) comp into cmssw branch :-)
I don't want to make too much changes for the moment and there are other things that I need to get in asap. Once we're in a better timing, I'll bug you again about this (or even better, someone from CMSWEB will).

**Comment by smuzaffar** [comment]
@amaltaro , good thing about new style of building pip packages is that you have to do less work :-) just copy blindly our new pip directory in to comp branch and drop all your py2-*.spec files (which use build-with-pip) and that is it :-) cmsBuild will take care of the rest.

**Comment by amaltaro** [comment]
I wish it was just **just**. Look at this PR, I was supposed to simply update pyopenssl version. It took me one month to get all bits in and now it's going to take one or two more months to get it merged... :)

**Comment by h4d4** [comment]
+1 to b16d85578790f58e6fcf54971992e1daaa3d0f25 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_b16d855-20190103-175008.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 2dfc364875ef5cab173aef7a03d906c994d3ad31 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_2dfc364-20190104-085009.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 2dfc364875ef5cab173aef7a03d906c994d3ad31 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_2dfc364-20190104-093510.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 2dfc364875ef5cab173aef7a03d906c994d3ad31 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_2dfc364-20190104-100508.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 2dfc364875ef5cab173aef7a03d906c994d3ad31 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_2dfc364-20190104-104009.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 2dfc364875ef5cab173aef7a03d906c994d3ad31 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_2dfc364-20190104-111512.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 2dfc364875ef5cab173aef7a03d906c994d3ad31 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_2dfc364-20190104-115009.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 1ad94fbe4572d18289380ee1679d6ee1be86082e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_1ad94fb-20190104-122509.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 1ad94fbe4572d18289380ee1679d6ee1be86082e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_1ad94fb-20190104-130509.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 1ad94fbe4572d18289380ee1679d6ee1be86082e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_1ad94fb-20190104-134009.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 1ad94fbe4572d18289380ee1679d6ee1be86082e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_1ad94fb-20190104-141509.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
closing it to avoid automated tests

**Comment by amaltaro** [comment]
Wondering why I can't reopen my own PR?
@smuzaffar @h4d4 can you please reopen it to see whether the build bot will behave? Thanks

**Comment by smuzaffar** [comment]
no idea, check with github support.
For now , can you try 'please open' comment?

**Comment by amaltaro** [comment]
please open

**Comment by h4d4** [comment]
+1 to 1ad94fbe4572d18289380ee1679d6ee1be86082e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_1ad94fb-20190107-093010.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 1ad94fbe4572d18289380ee1679d6ee1be86082e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_1ad94fb-20190107-101009.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
closing again to avoid issues with the bot

**Comment by amaltaro** [comment]
I just pushed in a new commit. Let's see how the bot build will behave this time. @h4d4 if the bot misbehave again, can you please look into it?

**Comment by h4d4** [comment]
-1 to f32d375b885aa4c8d44121b7ca8890d941593473 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_f32d375-20190114-142506.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 7fa6921b6f8ffe6d16aba6006dfb7173d97b6eb6 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_7fa6921-20190114-143508.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 7fa6921b6f8ffe6d16aba6006dfb7173d97b6eb6 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_7fa6921-20190114-151007.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
looks like it did not work.
Who maintain the comp bot code? Please fix this bug.

**Comment by h4d4** [comment]
-1 to 7fa6921b6f8ffe6d16aba6006dfb7173d97b6eb6 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_7fa6921-20190114-155013.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 7fa6921b6f8ffe6d16aba6006dfb7173d97b6eb6 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4479/test_7fa6921-20190114-162508.log" target="_blank">here</a>.

**Comment by smuzaffar** [comment]
I have closed this PR. please fix the bot.

**Pull request closed without merging**
