### PR TITLE
Update Eigen to commit c7dc0a897676 (> 3.3.4)

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by fwyzard** [comment]
Can I have some feedback about having this in 10.0.x and 9.4.x ?

**Comment by smuzaffar** [comment]
@fwyzard , we also need tensorflow updated (https://github.com/cms-externals/tensorflow/commit/6438b7f7459232044dbb4e042f2c42cbdf925fad ) to go with this. I have updated it for 10.0.X PR.

**Comment by fwyzard** [comment]
Merged in 10.0.x, closing for 9.4.x .

**Pull request closed without merging**
