### PR TITLE
Update pythia8.spec

### PR DESCRIPTION
**Pull request by mrodozov**
Testing changes: https://github.com/cms-externals/pythia8/commit/6e0f72a4478754a4fb13c91ccc92f21947f2788e

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@fabiocos , any objection on merging this ? This contains the fix from @kpedro88   https://github.com/cms-externals/pythia8/pull/12 (to Fix all uninitialized member variables

**Comment by kpedro88** [comment]
@alberto-sanchez does the pythia update need to be backported to any other branches?

**Comment by fabiocos** [comment]
@smuzaffar @kpedro88 from what I understand this fix has been already submitted to pythia8 authors and should be part of a next distribution. As it has been verified to solve the problems observed, I would say we integrate it to test within CMSSW_10_2_0_pre5

**Comment by alberto-sanchez** [comment]
@kpedro88, @fabiocos ,
    Yes, we can wait for the next pythia8 release and then backport to MC prod releases, if that does not take too long.

**Comment by kpedro88** [comment]
@alberto-sanchez I don't think the suggestion is to wait for the next official pythia release, but to test for a while in the development branch before backporting, since it is a large amount of code (though in principle no changes should occur).

**Comment by fabiocos** [comment]
@alberto-sanchez @kpedro88 exactly. Of course ideally all our fixes should enter into the main distribution, it is not good to maintain patches over patches

**Comment by alberto-sanchez** [comment]
absolute agree.

**Pull request merged**
