### PR TITLE
Update crab client

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by belforte** [comment]
@smuzaffar  I hope there is a better solution than detect the 27a60cc501cf00215a28461ccdc2a04b suffix by this error and update the spec with it !
Anyhow this is not urgent since Andrea Sciaba' just found a subtle bug in CRABClient (which only affects HammerCloud of course) and at this point I'd rather fix that as well.  Still, kindly let me know how to solve this version naming.

**Comment by smuzaffar** [comment]
@belforte , as `crab-build.file` file is updated so basically all `crab-*.spec` need to change the suffix. In this case suffix in `crab-dev.spec` also needs changes

**Comment by belforte** [comment]
got it, thanks. Will try again with a new crab-dev tag and the fix for HammerCloud

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
