### PR TITLE
Include CXX11 vers in template args for llvm

### PR DESCRIPTION
**Pull request by mrodozov**
As discussed here:
https://github.com/cms-externals/llvm-project/commit/a0f653798ce2e441cabef0311f11f8fd2ce8b1f0#commitcomment-34938607

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort
there is typo

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort
fails with another error

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test

**Pull request closed without merging**
