### PR TITLE
PPC - remove -mlong-double-64 flag and use the default

### PR DESCRIPTION
**Pull request by mrodozov**
Compiling externals with the -mlong-double-64 makes their long double types to have only 64 bits size when cmssw long double vars remain 128 using the defaults.
In this case cmssw 128 bits var were passed to clhep compiled with -mlong-double-64

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
test parameters:
- architecture = slc7_ppc64le_gcc9
- full_cmssw = true

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
test parameters:
- release/arch = CMSSW_12_0_X_2021-05-21-2300/slc7_ppc64le_gcc9
- full_cmssw = true

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/33892

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
test parameters:
- pull_requests = cms-sw/cmssw#33892
- architecture = slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
test parameters:
- pull_requests = cms-sw/cmssw#33892
- architecture = slc7_ppc64le_gcc9
- full_cmssw = true

**Comment by mrodozov** [comment]
full CMSSW to test other places it may fail

**Comment by smuzaffar** [comment]
@mrodozov , I have not followed the complete discussion about this flag but if this is not needed any more then please just remove it from https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/compilation_flags.file#L2 instead of updating all the specs where it is used.

**Comment by mrodozov** [comment]
yes that went trough few name modifications, I can just remove it and keep the original name.
the discussion is here:

https://github.com/cms-sw/cmssw/issues/33743
and also at the bottom of one of the PPC issues:
https://github.com/cms-sw/cmssw/issues/32141

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov , ah I did not realize that there are few specs where we are not using `%{ppc64le_build_flags}` . I would suggest to update the `fftjet, fmt and geant4` and use %{ppc64le_build_flags} flag e.g. 
```
%ifarch ppc64le
    -DCMAKE_CXX_FLAGS="-mlong-double-64"
%endif
```
should become
```
%ifarch ppc64le
    -DCMAKE_CXX_FLAGS="%{ppc64le_build_flags}"
%endif
```

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov , please add also 
```
## INCLUDE compilation_flags
```
for `fftjet, fmt and geant4` where we now use `%{ppc64le_build_flags}`. You can add this line just after the first line `### RPM ....`

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@smuzaffar cms-sw/cmssw#33892 is merged now we can get this one for the evening IB

**Comment by smuzaffar** [comment]
@mrodozov , I would like to test OpenBlas change separately to see if that works for SKYLAKEAVX512_X IBs. Can you please just make a PR with only OpenBLAS update?

**Comment by mrodozov** [comment]
I remove the openblas changes. get it as it is ?

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9
lets run tests again ( just to make sure there is no typo)

**Comment by smuzaffar** [comment]
+externals
looks good

**Pull request merged**
