### PR TITLE
build gmp standalone to get gmp.h needed for gcc plugin builds

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by davidlt** [comment]
There is `gmp-static` package, which should be at 6.1.0 version in gcc530 branch and 5.0.2 in stable branch.

**Comment by gartung** [comment]
The gmp version should match the one gcc was compiled against. The Atlas gcc plugin I am testing was written against gcc 4.9.3 which uses gmp 6.0a. The gcc internals have probably changed for gcc 5.3. This does not cause a rebuild of gcc since it depends on gcc.

**Comment by davidlt** [comment]
That's why there is `gmp-static` which does not provide shared library, otherwise shared library would end up in `LD_LIBRARY_PATH` thus potentially overriding what was used in GCC.

You don't need `gmp.spec`, because our GCC packages provides `gmp` and `gmpxx` libraries and headers.

Simply put use `${GCC_ROOT}/include` and `${GCC_ROOT}/lib` and you will get exact version used for our GCC.

**Comment by gartung** [comment]
OK. The Atlas gcc plugin was built again the LCG gcc distribution that does not include gmp.h. It required setting up a standalone gmp.

**Comment by davidlt** [comment]
Yeah, it's wrong that our package is called GCC. Basically it's a toolchain package (GCC, binutils, elfutils, etc) + all the prerequisites (MPFR, ISL, GMP, etc).

**Pull request closed without merging**
