### PR TITLE
Gcc491 build on osx fix for gmp

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by ktf** [comment]
@gartung is this ok also on linux?
@degano we should probably have a repository for gmp (and similars) in cms-externals.

**Comment by gartung** [comment]
@ktf I have not tested on linux.

**Comment by gartung** [comment]
@ktf @degano How about moving to gcc492. I know gcc492 builds on OSX. I build gcc first in order to build rpm480.

**Comment by gartung** [comment]
Will submit in combination with rpm patch.

**Pull request closed without merging**
