### PR TITLE
Backport #4554 to 9_4 gcc630

### PR DESCRIPTION
**Pull request by mrodozov**
Backport requested: https://github.com/cms-sw/cmsdist/pull/4554#issuecomment-446569543

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar when this is merged I will move forward with cms-sw/cmssw#25385

**Comment by fabiocos** [comment]
@smuzaffar any objection to merge? I will prepare a new cmssw PR with all the commits squashed

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
no objections, I have signed it and it should be merged now.

**Pull request merged**
