### PR TITLE
[11.1.X] update L1Trigger-L1THGCal V01-02-00

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #5982

### CODE REVIEW

**Comment by silviodonato** [comment]
@smuzaffar can we merge this with https://github.com/cms-sw/cmssw/pull/30355 ?

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
yes @silviodonato

**Comment by silviodonato** [comment]
+1

**Pull request merged**
