### PR TITLE
[11.2] Backport of 6998 i.e. PhysicsTools-PatUtils=V00-05-00

### PR DESCRIPTION
**Pull request by mrodozov**
see https://github.com/cms-data/PhysicsTools-PatUtils/pull/4#issuecomment-856542399

### CODE REVIEW

**Comment by smuzaffar** [comment]
Backport of #6998

**Comment by mrodozov** [comment]
@mariadalfonso do we still need this for 11_2 ?

**Comment by mariadalfonso** [comment]
@mrodozov 
indeed we need this properly distributed
(in 10_6 this is in now https://github.com/cms-sw/cmsdist/pull/7000)

**Comment by smuzaffar** [comment]
@mariadalfonso , is there cmssw PR to go with it e.g. backport of https://github.com/cms-sw/cmssw/pull/33758 for 11.2.X?

**Comment by mariadalfonso** [comment]
@smuzaffar 

uhm, we only plan to have master (12_X) and 10.6.X but we do not foresee any nano backport to the 11.2.
so I think we can close this for 11.2.

**Pull request closed without merging**
