### PR TITLE
WMCore 1.1.14.pre2 release candidate

### PR DESCRIPTION
**Pull request by amaltaro**
Also fixed how reqmgr2 and reqmgr2ms specs copy the binary files.
FYI @ticoann

### CODE REVIEW

**Comment by h4d4** [comment]
-1 to b49cc378d29a36f1236bdeef6d52bba72a3f060d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4021/test_b49cc37-20180522-131504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 640a230d2df7b040cfea54bda1f7a17fffba19a0 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4021/test_640a230-20180522-140504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Ok, after squashing a bunch of other commits together (which caused lots of trouble), I think I managed to fix this PR.

**Comment by h4d4** [comment]
+1 to 828fb8c452fea9d9365d8f031abb87a33a5e3f8c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4021/test_828fb8c-20180522-142504.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
Thanks Alan, I wonder why it didn't failed before.

**Pull request merged**
