### PR TITLE
Hg1807 das

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 88e446528760538b5e606ae74307754983200747 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4097/test_88e4465-20180606-212503.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to c8f99d70b2159588ac9f7e83227d1820a4dd2600 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4097/test_c8f99d7-20180611-201506.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 17e549129fa01e6093708feadbbe04cc4ef797cf on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4097/test_17e5491-20180611-203505.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 4b64ec39f17d95ae91ef83d82286b3e3eaee9fc6 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4097/test_4b64ec3-20180611-221504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to c775a2ca22f753bb06ed7421297d207fa72f141e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4097/test_c775a2c-20180611-223504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to de7ed048157f39f73ef7f83c963b923298c83a9b on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4097/test_de7ed04-20180612-135504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 4aeef639a6e0d9b4469a2ffbc98f9943842a0d8c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4097/test_4aeef63-20180612-163529.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@h4d4 , Lina, how I can see the log? Everything is build fine in my environment. But build here provides -1 and there no log. When I click on provided link [here](https://cms-dmwm-builds.web.cern.ch/cms-dmwm-builds/4097/test_4aeef63-20180612-163529.log) it points to 404 - not found page

**Comment by h4d4** [comment]
-1 to 53d264062c7b7e616c0aabfcb685e06f5c62e352 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4097/test_53d2640-20180612-173600.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
replaced with: https://github.com/cms-sw/cmsdist/pull/4110

**Pull request closed without merging**
