### PR TITLE
Update some python packages to align with Spack

### PR DESCRIPTION
**Pull request by iarspider**
* [x] Update py3-certifi to 2022.9.14
* [x] Update py3-fonttools to 4.37.3
* [x] Update py3-ipykernel to 6.16.0
* [x] py3-executing 1.1.0
* [x] py3-zmq 24.0.1
* [x] py3-poetry-plugin-export 1.0.7
* [x] py3-fastjsonschema 2.16.2

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please tesst

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
+externals

@smuzaffar ok to merge?

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
> +externals
> 
> @smuzaffar ok to merge?

not yet, lets wait for https://github.com/cms-sw/cmssw/issues/39697

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
