### PR TITLE
Update data-GeneratorInterface-EvtGenInterface

### PR DESCRIPTION
**Pull request by mrodozov**
BP of https://github.com/cms-sw/cmsdist/pull/4181 to 7_1_X

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
this is know issue with 71X and cmsdist data external PRs. cmsdist data external PRs picks up some `Geometry/*/data` files from data externals which are not in sync with the files in `cmssw/src/Geometry/*/data`.
We can update the `data-Geometry-*` data packages to have the same files as they are in cmssw or ignore this error and merge this PR (as we were doing in past)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
