### PR TITLE
Remove old dls-client and dbs-client specs

### PR DESCRIPTION
**Pull request by amaltaro**
Remove two very old specs that are no longer used:
* dbs-client
* dls-client

even though they were still "required" by:
* asyncstageout
* crabserver
* crabtaskworker

### CODE REVIEW

**Comment by amaltaro** [comment]
FYI @belforte

**Comment by belforte** [comment]
did you check already that crab stuff builds w/o those (just in case... ) ? otherwise I'll do

**Comment by belforte** [comment]
p.s. we are about to remove asyncstageout.spec as well :-)

**Comment by amaltaro** [comment]
I did some tests with the new openssl and tons of other things together, I failed to build crabtaskworker. Others built well.

> p.s. we are about to remove asyncstageout.spec as well :-)

Good to know. I might drop it from the list of required specs to be built in comp.spec, such that it doesn't get built with the new openssl :-D

**Comment by amaltaro** [comment]
Oh, and don't worry about building it manually. If there are problems, CMS Bot will answer with a "-1"

**Comment by belforte** [comment]
yes, drop asyncstageout from build list.

**Comment by muhammadimranfarooqi** [comment]
+1 to 77a4bb7ea5763b4cf66acb8d6f486ce9ea1227db on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6403/test_77a4bb7-20201111-145003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
From the logs:
```
...
Build successful asyncstageout.
Build successful crabserver.
Build successful crabtaskworker.
Build successful crab-devtools.
...
```

so, from my side everything looks great. 

@belforte if you are happy with this, can you please give @muhammadimranfarooqi Imran the green light to merge? Thanks

**Comment by belforte** [comment]
@muhammadimranfarooqi OK to merge from my side. Can you or Alan also look into not trying to build on SL6 anymore so we avoid that the above messsage about Some checks haven't completed yet always sticks around  forever ?

**Comment by belforte** [comment]
@ddaina FIY and take this chance to simplify accordingly the spec files you use

**Comment by ddaina** [comment]
thanks @belforte . Whenever we build RPMs in Jenkins, it always take most recent spec files version from `comp_gcc630` branch, so changes will be picked automatically.

**Pull request merged**
