### PR TITLE
[form] explicilty added zlib and gmake dependencies

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for cc8_aarch64_gcc8

**Comment by mrodozov** [comment]
also $PLATF_CONF_OPTS are not recognized on neither arch and can be removed

**Comment by smuzaffar** [comment]
@mrodozov , please check the configure script and use the correct options to build shared libs

**Comment by mrodozov** [comment]
Seems this external only builds executables. 
From the file history it seems this external config is just a copy-paste from another external
https://github.com/cms-sw/cmsdist/commit/aa4592f839a2286d156fc7a082db1511ab8d41fc#diff-55665aa46b2f10e735668849da33a259 
i.e. https://github.com/cms-sw/cmsdist/blob/aa4592f839a2286d156fc7a082db1511ab8d41fc/gosamcontrib.spec
from where the flags come from. From 
/cvmfs/cms.cern.ch/slc7_amd64_gcc820/external/form/4.1.033e-pafccj/
it's clear only executables were created, so no flags linking libs are required.

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test for cc8_aarch64_gcc8

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
comparison fails second time for this pr, maybe we can open it for prod arch and let it be ported to cc8  ?

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
