### PR TITLE
ROOT next [6.22] Update to latest on 6.22

### PR DESCRIPTION
**Pull request by mrodozov**
include latest DD4Hep updates

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@slava77 considering https://github.com/cms-sw/cmsdist/pull/6657 would you please have a look also this one
usually when I see non-master branch differences I attribute it to the differences in externals/OS, but this is very close to what we have in cmsdist/master (excluding dd4hep changes)
I think we have to go back also here :/

**Comment by slava77** [comment]
> @slava77 considering #6657 would you please have a look also this one

Apart for 
> You potentially added 8146090 lines to the logs

the reco differences look OK
-  there are a bunch in 140.53 due to the DAS issue of getting an inconsistent input file compared to the baseline (transient?)
- - and a few logError/Warnings in workflows with mixing which can be ignored.

**Comment by mrodozov** [comment]
the #6657 also looks ok on it's own so it's probably what's in dd4hep

**Pull request merged**
