### PR TITLE
upgrade thepeg from 1.9.0a to 1.9.2 and herwigpp from 2.7.0a to 2.7.1

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by vciulli** [comment]
+1
This is needed for TOP studies.

**Comment by bendavid** [comment]
Does this need a corresponding CMSSW pull request as well?

**Comment by bendavid** [comment]
(Discussing with Mikhail the answer is that the required interface changes are already in 72x, so this is ready to go)

**Comment by ktf** [comment]
@degano I've created cms-externals/thepeg. Can you please adapt this pull request to use it and drop all the thepeg related patches from cmsdist?

**Comment by ghost** [comment]
I re-created the PR in #931 picking thepeg from cms-externals repository.
I am closing this one.

**Pull request closed without merging**
