### PR TITLE
CUDA 9.0.176 for 9.2.x

### PR DESCRIPTION
**Pull request by fwyzard**
Update CUDA to version 9.0.176.

Include `libcudart_static.a` in the external.

No longer include `libcuda.so.*` and `libnvidia-fatbinaryloader.so.*` in the external; instead, rely on the libraries installed on the system, since they would anyway need to match the version of the installed (kernel) driver.

To make them available at link time, we add `libcuda.so` to the libraries, and add `lib64/stubs` to the linker library path.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport #3460

**Comment by smuzaffar** [comment]
+externals

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
Moved to 9.4.x and later.

**Pull request closed without merging**
