### PR TITLE
CRAB server 3.3.9.rc2

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 807f3a3ecaaebc7ce84ac8f9351897cfbe6130b0 on slc5_amd64_gcc461.

**Comment by geneguvo** [comment]
We just built it ourselves and it succeeded. Don't know why it failed in the bld agent.

**Comment by mmascher** [comment]
There is a patch file in the commit. Maybe something similar to the "trailing whitespaces removed" we experienced some time ago?

**Comment by geneguvo** [comment]
Could be... although I pushed a fix for that a while ago already. Anyway, the build logs should tell what went wrong.

**Pull request closed without merging**
