### PR TITLE
[cxxmodule] Optimize runtime with no preloading

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
ping bot

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
@smuzaffar @mrodozov Can you trigger a test for this?

**Comment by mrodozov** [comment]
allow @yamaguchi1024 test rights

**Comment by yamaguchi1024** [comment]
please test

**Comment by yamaguchi1024** [comment]
please test

**Pull request closed without merging**
