### PR TITLE
Update crab-dev to v3.230130

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by belforte** [comment]
I had made a mistake when creating the release and the tag was not what indicated here. I have fixed that.

**Comment by belforte** [comment]
please test

**Comment by belforte** [comment]
@smuzaffar looks like I can't send commands to the bot. Please make it try again.

**Comment by iarspider** [comment]
@cmsbuild please ping

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
+externals

crab build and test passed

**Pull request merged**
