### PR TITLE
backporting sherpa2.2.6 and openloops2.0.0 to 93X

### PR DESCRIPTION
**Pull request by SiewYan**
Hi, please apply the mentioned patches in [1] and [2]

[1] cms-externals/openloops@5141c0e
[2] https://gitlab.com/openloops/OpenLoops/commit/8ff8f52fe6e0f9f4f3f666b0d89279da64554fc3

### CODE REVIEW

**Comment by SiewYan** [comment]
@mrodozov , could you please check the gitlab tag is correct and trigger the test?
Thanks.

**Comment by mrodozov** [comment]
please test

**Comment by qliphy** [comment]
@smuzaffar   #4823 is now merged.  Would you please trigger test this PR and move forward?  Thanks!

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
