### PR TITLE
[MXNet] use modern thread local

### PR DESCRIPTION
**Pull request by smuzaffar**
This shoudl fix the issue with threading for centos8, ppc64le, aarch64 IBs ( https://github.com/cms-sw/cmssw/issues/30432 )

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters
- pull_requests = cms-externals/incubator-mxnet#1

**Comment by smuzaffar** [comment]
please test workflow 2.0,4.17,108.0,134.702 for cc8_amd64_gcc8

Although pr tests are not going to run in threaded mode.

**Comment by makortel** [comment]
(from 23234.0)
```
dropped waiting message count 0
free(): invalid pointer
```
So the attempted fix does not seem to work always(?).

**Comment by smuzaffar** [comment]
please test workflow 140.5611,20434.1,20434.103 for slc7_ppc64le_gcc820

**Comment by smuzaffar** [comment]
In this case it is failing here
```
#6  0x00007ffff556adb0 in _int_free () from /lib64/libc.so.6
#7  0x00007fffdaa28465 in HcalFrontEndMap::~HcalFrontEndMap() ()
   from /cvmfs/cms-ib.cern.ch/nweek-02636/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-07-05-0000/lib/cc8_amd64_gcc8/libCondFormatsHcalObjects.so
#8  0x00007fffd8e019a2 in edm::eventsetup::CallbackProxy<edm::eventsetup::Callback<HcalHardcodeCalibrations, std::unique_ptr<HcalFrontEndMap, std::default_delete<HcalFrontEndMap> >, HcalFrontEndMapRcd, edm::eventsetup::CallbackSimpleDecorator<HcalFrontEndMapRcd> >, HcalFrontEndMapRcd, std::unique_ptr<HcalFrontEndMap, std::default_delete<HcalFrontEndMap> > >::invalidateCache() ()
   from /cvmfs/cms-ib.cern.ch/nweek-02636/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-07-05-0000/lib/cc8_amd64_gcc8/pluginCalibCalorimetryHcalPlugins.so
#9  0x00007ffff7c343a1 in edm::eventsetup::EventSetupRecordImpl::invalidateProxies() ()
   from /cvmfs/cms-ib.cern.ch/nweek-02636/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-07-05-0000/lib/cc8_amd64_gcc8/libFWCoreFramework.so
#10 0x00007ffff7c32870 in edm::FunctorWaitingTask<edm::eventsetup::EventSetupRecordIOVQueue::startNewIOVAsync(edm::WaitingTaskHolder const&, edm::WaitingTaskList&)::{lambda(edm::LimitedTaskQueue::Resumer)#1}::operator()(edm::LimitedTaskQueue::Resumer)::{lambda(std::__exception_ptr::exception_ptr const*)#1}>::execute() ()
   from /cvmfs/cms-ib.cern.ch/nweek-02636/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-07-05-0000/lib/cc8_amd64_gcc8/libFWCoreFramework.so
#11 0x00007ffff66b7bed in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::process_bypass_loop (this=this@entry=0x7ffff4597200, context_guard=..., t=t@entry=0x7ffff4409b40,
    isolation=isolation@entry=0) at ../../src/tbb/custom_scheduler.h:393
#12 0x00007ffff66b7ee5 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7ffff4597200, parent=..., child=<optimized out>)
    at ../../include/tbb/task.h:1003
#13 0x00007ffff7c3331d in edm::eventsetup::EventSetupRecordIOVQueue::~EventSetupRecordIOVQueue() ()
   from /cvmfs/cms-ib.cern.ch/nweek-02636/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-07-05-0000/lib/cc8_amd64_gcc8/libFWCoreFramework.so
#14 0x00007ffff7bf5691 in edm::EventProcessor::~EventProcessor() ()
   from /cvmfs/cms-ib.cern.ch/nweek-02636/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-07-05-0000/lib/cc8_amd64_gcc8/libFWCoreFramework.so
#15 0x0000000000411733 in (anonymous namespace)::EventProcessorWithSentry::~EventProcessorWithSentry() ()
#16 0x000000000041136f in main ()
```

**Comment by smuzaffar** [comment]
For workflow 23234.1001, the error occurs here [a]. 

[a]

```
dropped waiting message count 0

Thread 1 "cmsRun" hit Breakpoint 1, L1FPGATrackProducer::~L1FPGATrackProducer() () at /build/muz/x/CMSSW_11_2_X_2020-07-05-2300/src/L1Trigger/TrackFindingTracklet/plugins/L1FPGATrackProducer.cc:287
287     L1FPGATrackProducer::~L1FPGATrackProducer() {
(gdb) n

Thread 1 "cmsRun" hit Breakpoint 1, L1FPGATrackProducer::~L1FPGATrackProducer() () at /build/muz/x/CMSSW_11_2_X_2020-07-05-2300/src/L1Trigger/TrackFindingTracklet/plugins/L1FPGATrackProducer.cc:287
287     L1FPGATrackProducer::~L1FPGATrackProducer() {
(gdb) n
288       if (asciiEventOut_.is_open()) {
(gdb) n
287     L1FPGATrackProducer::~L1FPGATrackProducer() {
(gdb) n
86            ~new_allocator() _GLIBCXX_USE_NOEXCEPT { }
(gdb) n
double free or corruption (!prev)

Thread 1 "cmsRun" received signal SIGABRT, Aborted.
0x00007ffff551f70f in raise () from /lib64/libc.so.6

```

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test workflow 2.0,4.17,108.0,134.702 for cc8_amd64_gcc8

**Comment by makortel** [comment]
The latest round shows the following for 23234.1001
```
malloc(): invalid size (unsorted)
```
jemalloc is extremely picky about memory being released correctly, any incorrect free leads to a disaster (e.g. `delete` instead of `delete[]`). It could be that the stack traces are symptoms of such disasters, while the actual cause occurs elsewhere (silently).

 I find it more believable that the "modern thread local" does not work in practice than it would lead to problems in many other places.

**Comment by smuzaffar** [comment]
I think these errors are already there in IB and have nothing to do with multi threading of mxnet change,
For now I have again disabled the multi threading for cc8, aarch64, ppc64le IBs to see what else is broken. I am afraid this might have something to do with L1 changes we have recently integrated.

**Pull request closed without merging**
