### PR TITLE
Revert "boost,boost-toolfile: update to 1.57.0"

### PR DESCRIPTION
**Pull request by davidlange6**
AlCa needs the new version of boost in 74x reverted… I'm creating a PR by reverting David's original one - but could someone test and see how a CMSSW build goes - I don't see that we had fallout issues from this change, but maybe I've missed something.

Reverts cms-sw/cmsdist#1184

### CODE REVIEW

**Comment by ktf** [comment]
Ciao,

why not simply reverting boost serialisation to the one version?

## 

Ciao,
Giulio

**Comment by davidlange6** [comment]
if that is "easy", that would be fine.

**Comment by davidlt** [comment]
You mention 74X, but this is being done for 73X. Older versions of Boost will break condDBv2 conditions XML output.

What is exact reasoning for reverting Boost?

**Comment by apfeiffer1** [comment]
Hi David,

You mention 74X, but this is being done for 73X. Older versions of Boost

> will break condDBv2 conditions XML output.
> 
> What is exact reasoning for reverting Boost?

the reason is that releases with boost 1.51 (like 7.2 and 7.3) can not read
the objects written by 74x with boost 1.57, which is critical.

Thanks,
       cheers, andreas

**Comment by davidlt** [comment]
How do plan to solve this in a long term? I hope you don't expect CMSSW to use already old Boost for N years further.

Have you tried debugging the issue?

This might be another good example of downfall of using ROOT+data, Boost+data. Data must be in a different realm and not connected to the code.

**Comment by apfeiffer1** [comment]
Hi David,

How do plan to solve this in a long term? I hope you don't expect CMSSW to

> use already old Boost for N years further.
> 
> Have you tried debugging the issue?
> 
> This might be another good example of downfall of using ROOT+data,
> Boost+data. Data must be in a different realm and not connected to the code.
> 
> this was discussed at the AlCaDB meeting yesterday. We will be looking into
> this for 75x and try to find a solution for the future which takes the
> evolution into account.

Thanks,
       cheers, andreas

**Comment by davidlange6** [comment]
Hi Andreas,

@fwyzard, fyi
From the 74x devel IB, it seems that CMSSW has grown some boost 1.57 dependencies

#include <boost/core/demangle.hpp>

from

https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/HLTrigger/HLTcore/interface/defaultModuleLabel.h

Could you suggest a workaround?

thx-
David

**Comment by fwyzard** [comment]
I guess we can check the boost version, and make

```
 std::string name = boost::core::demangle(typeid(T).name());
```

fall back to

```
 std::string name = boost::units::detail::demangle(typeid(T).name());
```

for older versions of boost.

**Comment by davidlange6** [comment]
i'm ok with that (as hopefully a short term solution)

**Comment by ghost** [comment]
@davidlange6 is this still wanted? Or can we close it?

**Comment by davidlange6** [comment]
this PR is superseded

**Pull request closed without merging**
