### PR TITLE
[13_0_X] Update Generator tag to V01-07-00

### PR DESCRIPTION
**Pull request by tvami**
Backport of https://github.com/cms-sw/cmsdist/pull/8699

Needed in [13_0_X] because the 2023 MC is done in that release cycle

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@smuzaffar can you please merge this?

**Comment by smuzaffar** [comment]
+externals

@cms-sw/orp-l2 , please feel free to include it for next 13.0.X Ib/release

**Comment by rappoccio** [comment]
+1

**Pull request merged**
