### PR TITLE
[10.6.X][ROOT] Update to latest 6.12 patches branch

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar the unit test failure above is unrelated to ROOT, see cms-sw/cmssw#26236 temporarily fixed by cms-sw/cmssw#26245 . The material budget unit test is now fixed. Unless there are surprises in the RelVal tests, I would be in favour to integrate this PR for next IB

**Comment by smuzaffar** [comment]
agree @fabiocos . I will wait for comparison results before merging it

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
