### PR TITLE
Update dd4hep to match ROOT TGeoMatrix interface

### PR DESCRIPTION
**Pull request by mrodozov**
Need for update described here:
https://github.com/AIDASoft/DD4hep/issues/426
Until dd4hep is updated accordingly

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@fabiocos step1 das queries logs are just lists of root files 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4241/29660/runTheMatrix-results/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/step1_dasquery.log
 and they may vary if they have different order in the baseline log files.
We need this changes on dd4hep to get latest commits from ROOT

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
@mrodozov thank you for preparing it. @ianna I see just a small bunch of DDCMS unit tests activated. Do we have a way to check consistency of geometries so far?

**Comment by fabiocos** [comment]
+1

**Comment by ianna** [comment]
@fabiocos - yes, the check is done by hand via visualization. There are no differences so far. Eventually, we'll have it automated.

**Pull request merged**
