### PR TITLE
[ROOT] Updated root modules branch

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@vgvassilev @oshadura 
is this because of the missing 
CLING_PREBUILT_MODULE_PATH variable (so that I just add it and rebuild without shovelling around why it's not building)
?

**Comment by vgvassilev** [comment]
Looks like it...

**Comment by mrodozov** [comment]
please test

**Comment by oshadura** [comment]
@mrodozov is it possible to see a full log for the ROOT build?

**Comment by mrodozov** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a1e390/3054/lcg/root/6.17.01-a1e390/log

**Comment by oshadura** [comment]
@mrodozov which last commit you picked up for ROOT?

**Comment by mrodozov** [comment]
If you see:
https://github.com/cms-sw/root/commits/cmscxx/master/a3b11a4 
the last commit from root master is 
https://github.com/cms-sw/root/commit/a3b11a499f2de8aa2c740b05f136308f3328c6cd
the rest is what we put on top

**Comment by oshadura** [comment]
We think problem is connected with wrong rebasing or with not-needed patch.. 
Can we remove these two patches: https://github.com/cms-sw/root/commit/d56fa42fbd144b42993136366f9dcc20a17ee7e9 and
https://github.com/cms-sw/root/commit/4e6f3e6c219c02e09f8cf5d8934f2b4a060ae172

**Comment by mrodozov** [comment]
alright. now if I remove this two this one 
https://github.com/cms-sw/root/commit/7bfd248d06c72fb1dacf7ee12282ac7fba9320ab
doesn't fit along with the rest of the custom patches.
Could you get all it needs on top of master using https://github.com/cms-sw/root/commits/cmscxx/master/a3b11a4 patches and point me to the branch I'll put it on cms-sw/root.

**Comment by vgvassilev** [comment]
That cannot be. The patch you mentioned does not have common code with the other two patches.

**Comment by mrodozov** [comment]
weird. maybe I was doing something wrong. would you check this one if it's fine ? 
https://github.com/cms-sw/root/commits/cmscxx/master/4b5cddf

**Comment by oshadura** [comment]
> weird. maybe I was doing something wrong. would you check this one if it's fine ?
> https://github.com/cms-sw/root/commits/cmscxx/master/4b5cddf

Looks good!

**Comment by mrodozov** [comment]
please test

**Comment by davidlange6** [comment]
@smuzaffar @mrodozov - it seems from the console log that this test failed. Is that incorrect?

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
since the error was as in the other PR

**Comment by oshadura** [comment]
@smuzaffar @mrodozov I am bit a confused if I should look here? Or here https://github.com/cms-sw/cmsdist/pull/5287 ?

**Comment by mrodozov** [comment]
@oshadura the PR that you opened #5284 looks ok. Not sure why since the only difference is that there are more commits in this one from root master

**Comment by davidlange6** [comment]
lets get #5284 merged and come back to this one? (and hopefully my cmssw pr thats related also goes in to make life easier)

**Comment by oshadura** [comment]
Now checking output of #5284 it doesn't look "healthy" as well: 
`Module DataFormatsHcalDetId not found.
Error in <TCling::LoadPCM>: ROOT PCM /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_CXXMODULE_X_2019-10-22-2300/lib/slc7_amd64_gcc820/libDataFormatsHcalDetId_rdict.pcm file does not exist` 
Lets wait to @davidlange6 cmssw PRs to land?

**Comment by smuzaffar** [comment]
@davidlange6 , looks like there are still dependency issues that is why  #5284 failed

**Comment by smuzaffar** [comment]
@oshadura , is there any cmssw PR which should fix the dependency issues? we can test that with #5284

**Comment by smuzaffar** [comment]
I see https://github.com/cms-sw/cmssw/pull/28222 which is fully signed so hopefully it will land soon in cmssw. I would suggest that we merge #5284. Although it will break cxxmodule IBs but at last this will show the missing dependencies issue and then it might be easier to fix those in dev area

**Comment by mrodozov** [comment]
close in favor of https://github.com/cms-sw/cmsdist/pull/5298

**Pull request closed without merging**
