### PR TITLE
Update CUDA to support Pascal, Volta, Turing, Ampere and Lovelace GPUs

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard , this did not help. GPU relval still failed with the same error as in IB
- PR: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e1f586/35252/runTheMatrixGPU-results/12434.587_TTbar_14TeV+2023_Patatrack_AllTripletsGPU_Validation/step2_TTbar_14TeV+2023_Patatrack_AllTripletsGPU_Validation.log
IB: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_3_GPU_X_2023-10-17-2300/pyRelValMatrixLogs/run/12434.587_TTbar_14TeV+2023_Patatrack_AllTripletsGPU_Validation/step2_TTbar_14TeV+2023_Patatrack_AllTripletsGPU_Validation.log#/

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- workflows_gpu = 160.03502,12434.504,12434.503

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
@fwyzard , gpu tests for x86_64 worked this time. Unit tests failure are
- testEigenGPUNoFit_t was already there due to eigen update. 
- testTFVisibleDevicesCUDA:  Tensorflow /cuda part was disabled for gcc12 that is why this test is failing. 

are you happy with current list of cuda archs? once aarch64/ppc64le tests are done then I can merge this

**Comment by fwyzard** [comment]
@smuzaffar 

> are you happy with current list of cuda archs? once aarch64/ppc64le tests are done then I can merge this

the current list should cover all GPUs we currently have access to.
To be more complete, we could add the architectures for the A40/A10 (`sm_87`) and H100 (`sm_90`) GPUs:
```diff
-%define cuda_arch 60 70 75 80 89
+%define cuda_arch 60 70 75 80 87 89 90
```

Do you have some idea of how much that would increase the build time and binary size?

**Comment by fwyzard** [comment]
@smuzaffar let's merge this, we can add more architectures later.

**Comment by smuzaffar** [comment]
> @smuzaffar let's merge this, we can add more architectures later.

sure, once 13.3.0.pre4 is uploaded then I will merge this.

> Do you have some idea of how much that would increase the build time and binary size?

`CMSSW/lib` binary size increased by ~3% (39MB: from 1189MB to 1228MB). I do not have access to individual build time for each package but overall full cmssw build time is nearly same between 150-155mins

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
