### PR TITLE
New dasgoclient version

### PR DESCRIPTION
**Pull request by vkuznet**
This PR fixes dasgoclient error with specific data-service queries.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@vkuznet was I too early to start the test?

**Comment by smuzaffar** [comment]
@vkuznet , did you upload https://cern.ch/valya/dasgoclient/cms+dasgoclient-binary+v01.00.07-1-1.slc6_amd64_gcc530.rpm?

**Comment by vkuznet** [comment]
I made a mistake in dasgoclient spec file, since I switch to gcc630 architecture while spec was pointed to gcc530 one. I made appropriate change in #3390 which is replacement of this PR. I'm closing it now.

**Pull request closed without merging**
