### PR TITLE
ROOT 6.22 - test TBB 2021.1.1

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/root/pull/149, https://github.com/cms-sw/cmsdist/pull/6544, cms-externals/heppdt#1

**Comment by smuzaffar** [comment]
will dd4hep work without toolfile change?

**Comment by smuzaffar** [comment]
cms-externals/heppdt#1 has been merged and is part of IBs, so no need to include it in tests

**Comment by mrodozov** [comment]
yes, because we don't add the flag `-DDD4HEP_USE_GEANT4_UNITS=ON`  to the dd4 cmake here, but only in the dd4hep update. I'm avoiding it on purpose because we are not merging this PR and we'll get the dd4 update before that (I guess). In the next PR I expect we'll already have the dd4 changes.

>  cms-externals/heppdt#1 has been merged and is part of IBs, so no need to include it in tests

I missed it was also added to cmsdist.

**Comment by xvallspl** [comment]
I've seen the mistake, tricky backports :)

**Comment by xvallspl** [comment]
A mistake slipped through, can I request for the build to start again with the updated changes in my branch? I'll hold on merging the patches

**Comment by smuzaffar** [comment]
please test with cms-sw/root#149, #6544

**Comment by smuzaffar** [comment]
@xvallspl , I have re-started the tests

**Comment by xvallspl** [comment]
Thanks, Shahzad!

**Comment by smuzaffar** [comment]
please test with cms-sw/root#149, #6544
strange error, lets retry

**Comment by mrodozov** [comment]
please test with #6544

**Comment by mrodozov** [comment]
please test with #6544

**Comment by mrodozov** [comment]
please test
check integration with tbb 2020

**Comment by mrodozov** [comment]
luckily  root is building, but it's again this "mysterious" issue with rivet.

**Comment by makortel** [comment]
Would it be possible to see the full build log of rivet? The last lines
```
* The action "build-external+rivet+3.1.3-6324f4091fbcd41b20a9b546001cffb1" was not completed successfully because Failed to build rivet. Log file in /build/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/external/rivet/3.1.3-6324f4091fbcd41b20a9b546001cffb1/log. Final lines of the log file:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02665/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/memory:80,
from ../include/Rivet/Tools/RivetSTL.hh:10,
from ../include/Rivet/Config/RivetCommon.hh:6,
from ../include/Rivet/Analysis.hh:5,
from pluginATLAS/ATLAS_2014_I1307756.cc:2:
/cvmfs/cms-ib.cern.ch/nweek-02665/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/unique_ptr.h:53:28: note: declared here
53 |   template<typename> class auto_ptr;
|                            ^~~~~~~~
```
looks interesting but is not enough to understand the cause.

**Comment by smuzaffar** [comment]
rivet build log is accessible via the summary page . here  it is it's direct link https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b3b50f/12550/external/rivet/3.1.3-6324f4091fbcd41b20a9b546001cffb1/log

**Comment by smuzaffar** [comment]
the actual error is [a], I do not know where is Q12 on line number 112 in this code

[a]
```
/cvmfs/cms-ib.cern.ch/nweek-02665/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/unique_ptr.h:53:28: note: declared here
   53 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
pluginCESR/CLEOII_1997_I446031.cc: In member function 'virtual void Rivet::CLEOII_1997_I446031::analyze(const Rivet::Event&)':
pluginCESR/CLEOII_1997_I446031.cc:112:25: error: 'Q12' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  112 |        _h_etap[ix]->fill(scale);
      |        ~~~~~~~~~~~~~~~~~^~~~~~~
In file included from /build/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc900/external/fastjet/3.3.4-ghbfee/include/fastjet/JetDefinition.hh:657,
                 from ../include/Rivet/Tools/RivetFastJet.hh:6,
                 from ../include/Rivet/Jet.fhh:6,
                 from ../include/Rivet/ParticleBase.hh:5,
                 from ../include/Rivet/Particle.hh:6,
                 from ../include/Rivet/Event.hh:6,
                 from ../include/Rivet/Analysis.hh:7,
                 from pluginBELLE/BELLE_2020_I1777678.cc:2
```

**Comment by smuzaffar** [comment]
looks like issue is here https://gitlab.com/hepcedar/rivet/-/blob/rivet-3.1.3/analyses/pluginCESR/CLEOII_1997_I446031.cc#L69 which has been fixed upstream https://gitlab.com/hepcedar/rivet/-/commit/902956783b111bdaa88ef9f029e5ce705bd48e01#44473ed08eb877c1422ccecc9178053e3ac4a76f  . I do not understand why we only randomly gets this error. 

@mrodozov , I would suggest to apply the patch to initialize Q12, Q22

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov , I would suggest to just patch for the un-initialized variabled. The rest we do not need unless generator team ask for that

**Comment by mrodozov** [comment]
abort
right, some of this is actually alice patches

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov , please open a separate PR for rivet changes

**Comment by mrodozov** [comment]
sure, but also this failure I think it's this:
https://github.com/root-project/root/blob/289c1d701d8d36cecd8376f03ffc9651644dd315/core/imt/src/RTaskArena.cxx#L82
and I don't see why a warning would fail

**Comment by makortel** [comment]
> and I don't see why a warning would fail

We convert many ROOT messages to exceptions. The default behavior for an "unknown" message is to throw an exception, and some "known" messages are converted to MessageLogger messages with various severity levels. The logic is here
https://github.com/cms-sw/cmssw/blob/master/FWCore/Services/plugins/InitRootHandlers.cc#L178

For these particular messages from RTaskArena
https://github.com/root-project/root/blob/98ff53015fbf7927c0942d331877022c1e5664c8/core/imt/src/RTaskArena.cxx#L77-L84
I'd be tempted to translate them to INFO level in CMSSW (we deliberately want this behavior to occur, and the warning could just confuse users). @Dr15Jones, what do you think?

**Comment by Dr15Jones** [comment]
Let’s first ask the ROOT team exactly why they put that message out. If it is just INFO, we should just do the suggested conversion to a MessageLogger messages.

**Comment by Dr15Jones** [comment]
So I took a look at the code where the message originates
https://github.com/root-project/root/blob/289c1d701d8d36cecd8376f03ffc9651644dd315/core/imt/src/RTaskArena.cxx#L81-L84

and I'm now of the opinion that we should make all messages from "RTaskArenaWrapper" to be MessageLogger INFO messages.

**Comment by smuzaffar** [comment]
do we already have a cmssw PR to convert `RTaskArenaWrapper` warnings to `MessageLogger` INFO message?

**Comment by mrodozov** [comment]
not yet, I'm banging head with the data tag job :/

**Comment by Dr15Jones** [comment]
> do we already have a cmssw PR to convert RTaskArenaWrapper warnings to MessageLogger INFO message?

If it would help, I can make one.

**Comment by smuzaffar** [comment]
yes please Dr15Jones 

> If it would help, I can make one.

**Comment by Dr15Jones** [comment]
See https://github.com/cms-sw/cmssw/pull/32782

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#32782

**Comment by mrodozov** [comment]
CERN network is having trouble -> requests to github are failing with timeouts, see:
https://cern.service-now.com/service-portal/?id=outage&n=OTG0061899

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#32782

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#32782

**Comment by mrodozov** [comment]
rivet patch is merged, we have a PR for the latest DD4Hep and another one for TBB. closing this.
The PR is failing because of the missing DD4Hep module files (might be due to the IB not including the fix, we'll see)

**Pull request closed without merging**
