### PR TITLE
fix directory structure of lhapdf6 and keep archive library

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
+1
This is needed to use lhapdf6 with madgraph_aMC@NLO

Would prefer not to wait for the ORP if possible.

**Comment by bendavid** [comment]
(no CMSSW interface changes required)

**Comment by ktf** [comment]
@degano, can you check this out, please?

**Comment by mkirsano** [comment]
As lhapdf6 tool is kept inactive, this should have no effect on CMSSW

**Comment by ghost** [comment]
+1
Tested compilation till cmssw-tool-conf.

**Pull request merged**
