### PR TITLE
Try the version of eigen used in tensorflow 1.3

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@davidlange6

**Comment by gartung** [comment]
@dr15jones please test

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by davidlange6** [comment]
hi @smuzaffar - this changes results so we need to look at it more carefully - lets save this change for 94x.

**Comment by davidlange6** [comment]
ah - its for devel - never mind, all is fine (but unfortunately the comparisons are not available...)

**Comment by gartung** [comment]
@davidlange6 @smuzaffar This needs to go into 94x/630 before tensorflow_cc can be merged.

**Pull request merged**
