### PR TITLE
Update ASO spec file.

### PR DESCRIPTION
**Pull request by HassenRiahi**

### CODE REVIEW

**Comment by amaltaro** [comment]
I guess you are providing bug fixes for the current testbed release (HG1407), is that correct? Such comments in the subject or description are always welcomed... Thanks

**Comment by HassenRiahi** [comment]
Yes, I commented here https://svnweb.cern.ch/trac/CMSDMWM/ticket/4293#comment:9. This PR includes a view asked by the transfer team.

**Comment by HassenRiahi** [comment]
https://github.com/dmwm/AsyncStageout/commit/7caa25dcd71404bbea7e38f265f8da460b6fca6f

**Comment by geneguvo** [comment]
+1 to 4711b62915674f221f7e5435b0739c0afc76ea93 on slc5_amd64_gcc461.

**Pull request closed without merging**
