### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6783

**Comment by mrodozov** [comment]
please test
for having also the root master build

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@smuzaffar as discussed yesterday if there are few unit tests / relvals failing to merge it and have an IB

**Pull request merged**
