### PR TITLE
[14_0_X] Update L1Trigger-L1TMuon tag

### PR DESCRIPTION
**Pull request by aloeliger**
Updates muon tag as done in https://github.com/cms-sw/cmsdist/pull/9226/files [as requested](https://github.com/cms-sw/cmssw/pull/45107#issuecomment-2159480470). This should update the L1Muon data repository for L1Muon backport PR https://github.com/cms-sw/cmssw/pull/45107

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

only adds new data files ( https://github.com/cms-data/L1Trigger-L1TMuon/pull/28/files ). This should go with https://github.com/cms-sw/cmssw/pull/45107

**Comment by missirol** [comment]
I'm confused. https://github.com/cms-sw/cmssw/pull/45107 was said to depend on this PR, but the former was merged 3 weeks ago, while the latter (this one) is still not merged.

Should this be included in the next 14_0_X release ?

**Comment by aloeliger** [comment]
@missirol My understanding is yes.

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , I am merging this for 14.0.X as this was needed by https://github.com/cms-sw/cmssw/pull/45107 which was merged 3 weeks ago

**Pull request merged**
