### PR TITLE
Addhepmc3

### PR DESCRIPTION
**Pull request by mkirsano**
Add tool hepmc3 for future migration HepMC2 -> HepMC3. It is not used yet. To facilitate further development.

### CODE REVIEW

**Comment by mkirsano** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

looks good, lets tests for other archs

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc11

**Comment by mkirsano** [comment]
Errors cannot be related. Only compilation errors can be.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
