### PR TITLE
Update OpenMPI, UCX and related libraries

### PR DESCRIPTION
**Pull request by fwyzard**
Update:
  - OpenMPI to v4.1.6
  - UCX to v1.15.0
  - RDMA Core to v50.0
  - NVIDIA gdrcopy to v2.4.1

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
please test with #9046, #9050

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc12

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
