### PR TITLE
[ROOT6] Root update master 20221122

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
https://github.com/cms-sw/cms-bot/pull/1888 to forward root master gcc11 merges to root module gcc11

**Comment by aandvalenzuela** [comment]
@smuzaffar, comparison was aborted when submitting the results (rsync) due to time out. Shall we test it again?
I think it is anyway taking too much time:
```
16:25:06 [140]-  Running                 ( ${CMS_BOT_DIR}/compareTriggerResults -r ${WORKSPACE}/data/${COMPARISON_RELEASE} -t ${WORKSPACE}/data/PR-${PR_NUM} -f "*/${WF_DIR}/step*.root" -o ${WORKSPACE}/upload/triggerResults > ${WORKSPACE}/upload/triggerResults/${WF_DIR}.log 2>&1 ) || true &
16:25:06 [141]+  Running                 ( ${CMS_BOT_DIR}/compareTriggerResults -r ${WORKSPACE}/data/${COMPARISON_RELEASE} -t ${WORKSPACE}/data/PR-${PR_NUM} -f "*/${WF_DIR}/step*.root" -o ${WORKSPACE}/upload/triggerResults > ${WORKSPACE}/upload/triggerResults/${WF_DIR}.log 2>&1 ) || true &
16:25:06 + wait
01:45:26 + '[' Xtrue = Xtrue ']'
01:45:26 ++ date
01:45:26 + echo '[Thu Nov 24 01:45:26 CET 2022] Finished comparisons of edm::TriggerResults'
01:45:26 [Thu Nov 24 01:45:26 CET 2022] Finished comparisons of edm::TriggerResults
```

I have retried the comparison job in the meantime.

**Comment by smuzaffar** [comment]
please test
lets rerun using new gcc11 based root6 IBs

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
