### PR TITLE
Update tag for PhysicsTools-PatUtils to V00-03-00

### PR DESCRIPTION
**Pull request by mrodozov**
backport of https://github.com/cms-sw/cmsdist/pull/6938 on 10_6

### CODE REVIEW

**Comment by mrodozov** [comment]
+externals 
tested in 33759

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#33759

**Comment by mariadalfonso** [comment]
test pass, we can merge this in 10_6 to facilitate the various tests

**Comment by qliphy** [comment]
+1

**Comment by mrodozov** [comment]
not before you've merged the cmssw PR unless this cms-data tag was only new files

**Comment by mrodozov** [comment]
I see cms-sw/cmssw#33758 is also not merged . should be fine

**Pull request merged**
