### PR TITLE
[ROOT6] Update ROOT tip of branch master

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
test parameters:

- full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar the error is in cmssw code or in root code? Also, there is cling assertion failure logged:
```
>> Checking EDM Class Version for src/DataFormats/EcalRawData/src/classes_def.xml in libDataFormatsEcalRawData.so
>> Checking EDM Class Version for src/DataFormats/EcalRecHit/src/classes_def.xml in libDataFormatsEcalRecHit.so
@@@@ ----> OK  EDM Class Transients 
python3: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc11/lcg/root/6.29.01-8b1fb99c2f98c5fc80c3d3abd70c9452/root-6.29.01/interpreter/llvm/src/tools/clang/lib/AST/DeclCXX.cpp:1499: clang::NamedDecl* getLambdaCallOperatorHelper(const clang::CXXRecordDecl&): Assertion `!Calls.empty() && "Missing lambda call operator!"' failed.
 *** Break *** abort
```

**Comment by smuzaffar** [comment]
@iarspider , please open a root-project/root issue. Looks like something changes in root whch broke this. I think it might be due to the error mentioned above
```
>> Checking EDM Class Transients in libDataFormatsCTPPSReco.so
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/lcg/root/6.29.01-8b1fb99c2f98c5fc80c3d3abd70c9452/etc/cling/std.modulemap:497:10: error: module 'std.bits/uses_allocator_args.h' requires feature 'cplusplus20'
  module "bits/uses_allocator_args.h" {
         ^
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/external/gcc/11.2.1-f9b9dfdd886f71cd63f5538223d8f161/include/c++/11.2.1/memory_resource:42:10: note: submodule of top-level module 'std' implicitly imported here
#include    // uninitialized_construct_using_alloc
         ^
```

open a root issue and ping @vgvassilev to look in to it

**Comment by iarspider** [comment]
> @iarspider , please open a root-project/root issue. Looks like something changes in root whch broke this. I think it might be due to the error mentioned above

https://github.com/root-project/root/issues/12240

**Comment by iarspider** [comment]
Closing in favor of #8312

**Pull request closed without merging**
