### PR TITLE
Updated dd4hep to tip of branch master

### PR DESCRIPTION
**Pull request by gudrutis**

### CODE REVIEW

**Comment by ianna** [comment]
@gudrutis - Thanks!

**Comment by gudrutis** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by ianna** [comment]
@smuzaffar - is the following warning/error due to the update?
```
Warning in <TStreamerInfo::BuildCheck>: 
   The StreamerInfo of class TGeoVolume read from file /build/yana/DD4HEP/CMSSW_10_4_X_2018-11-11-2300/src/./cmsDD4HepGeom.root
   has the same version (=6) as the active class but a different checksum.
   You should update the version to ClassDef(TGeoVolume,7).
   Do not try to write objects with the current class definition,
   the files will not be readable.

Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 6 of class 'TGeoVolume' is missing from 
the on-file layout version 6:
   TGeoExtension* fUserExtension; //
Warning in <TStreamerInfo::BuildCheck>: 
   The StreamerInfo of class TGeoNode read from file /build/yana/DD4HEP/CMSSW_10_4_X_2018-11-11-2300/src/./cmsDD4HepGeom.root
   has the same version (=2) as the active class but a different checksum.
   You should update the version to ClassDef(TGeoNode,3).
   Do not try to write objects with the current class definition,
   the files will not be readable.

Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 2 of class 'TGeoNode' is missing from 
the on-file layout version 2:
   TGeoExtension* fUserExtension; //
Warning in <TClass::Init>: no dictionary for class dd4hep::VolumeExtension is available
Warning in <TClass::Init>: no dictionary for class dd4hep::Region is available
Warning in <TClass::Init>: no dictionary for class dd4hep::Handle<dd4hep::RegionObject> is available
Warning in <TClass::Init>: no dictionary for class dd4hep::RegionObject is available
Warning in <TClass::Init>: no dictionary for class dd4hep::NamedObject is available
Warning in <TClass::Init>: no dictionary for class dd4hep::LimitSet is available
Warning in <TClass::Init>: no dictionary for class dd4hep::Handle<dd4hep::LimitSetObject> is available
Warning in <TClass::Init>: no dictionary for class dd4hep::LimitSetObject is available
Warning in <TClass::Init>: no dictionary for class dd4hep::VisAttr is available
Warning in <TClass::Init>: no dictionary for class dd4hep::Handle<dd4hep::VisAttrObject> is available
Warning in <TClass::Init>: no dictionary for class dd4hep::VisAttrObject is available
Warning in <TClass::Init>: no dictionary for class dd4hep::Handle<dd4hep::NamedObject> is available
Warning in <TClass::Init>: no dictionary for class dd4hep::PlacedVolumeExtension is available
TFile**		/build/yana/DD4HEP/CMSSW_10_4_X_2018-11-11-2300/src/./cmsDD4HepGeom.root	
 TFile*		/build/yana/DD4HEP/CMSSW_10_4_X_2018-11-11-2300/src/./cmsDD4HepGeom.root	
  KEY: TGeoManager	default;1	Detector Geometry
  KEY: TNamed	CMSSW_VERSION;1	CMSSW_10_4_X_2018-11-11-2300
  KEY: TNamed	tag;1	unknown
Warning in <TClass::Init>: no dictionary for class dd4hep::PlacedVolumeExtension::VolIDs is available
Info: Geometry table file: cmsDD4HepGeom.root
Error: Failed to find simulation geomtery file. Please set the file path with --sim-geom-file option.
```

**Comment by smuzaffar** [comment]
@ianna , yes it could be. Do you get this warning if you use CMSSW_10_4_X_2018-11-09-1100 IB (where we have previous version of dd4hep)?

**Comment by ianna** [comment]
@smuzaffar - only if I try to read a root file produced with CMSSW_10_4_X_2018-11-11-2300

**Comment by smuzaffar** [comment]
Looks like new dictionaries are added in new dd4hep which are saved in the root file that is why when reading it with an older version of dd4hep we get this warning. I guess you will not get the warning if you read it back in the same release .... right?

**Comment by ianna** [comment]
nope, the warnings are present in the CMSSW_10_4_X_2018-11-11-2300 as well.

**Comment by smuzaffar** [comment]
@ Dr15Jones any idea what could be wrong here?
@ianna , would you suggest to revert dd4hep change before we understand the issue. We are building 10.4.0.pre2 today. If this dd4hep update is breaking things then we should revert it.

**Comment by davidlange6** [comment]
this would be a "normal" behavior right? the old dd4hep build would not be expected to know about the newer dd4hep changes or be able to deal properly with them.

**Comment by smuzaffar** [comment]
yes but if I understand correctly @ianna is getting warnings with newer dd4ep too.

**Comment by fabiocos** [comment]
@ianna @smuzaffar could you please clarify whether the problem is on the new files as well? I have started to build the externals for CMSSW_10_4_0_pre2, in case I should stop, revert the dd4hep and restart...

**Comment by smuzaffar** [comment]
@fabiocos , do not stop the external builds for pre2. Even in case we have to revert dd4hep then it is just one external which only cmssw uses.

**Comment by fabiocos** [comment]
ok, after everything is built we may restart the build rebuilding just that, right?
It is not directly affecting production, it si mostly for @ianna 's work, but still it is not nice to have it broken a priori

**Pull request merged**
