### PR TITLE
[Configuration-Generator] Fix auxiliary decay files for long lived chargino

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by scodella** [comment]
Can you please back port it also to 71X? We need to use those files in RunIISummer15GS. Thanks

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/4964 is for 71X

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
