### PR TITLE
meschach: fix for parallel build

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar can you move the changes for parallel build into a separate patch?

**Comment by smuzaffar** [comment]
> @smuzaffar can you move the changes for parallel build into a separate patch?

done

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
