### PR TITLE
WMAgent stable release 2.1.6.2

### PR DESCRIPTION
**Pull request by amaltaro**
This patch release has a fix for GQ -> LQ data acquisition.

### CODE REVIEW

**Comment by arooshap** [comment]
+1 to 30d960de58922382c8686cf93a8165e9498c72d8 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8278/test_30d960d-20230131-093002.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Comment by arooshap** [comment]
Hi @amaltaro,

I have created a new tag `HG2302c` that incorporates this PR.

Thanks!

**Comment by amaltaro** [comment]
Thank you Aroosha. In future events, please don't invest time creating the cmsdist HG tag. It's not needed for WMAgent (and will likely not be needed for WMCore central services as well).

**Pull request merged**
