### PR TITLE
Replace old HF shower data in SimG4CMS/Calo.

### PR DESCRIPTION
**Pull request by ghost**
As requested in #795.

### CODE REVIEW

**Comment by davidlange6** [comment]
@degano - we still need this file:

SimG4CMS/Calo/data/HFShowerLibrary_npmt_eta4_16en.root

in addition to the new one

**Comment by ghost** [comment]
Yes, I fixed both PRs, sorry for that.

**Comment by civanch** [comment]
@degano, sorry after today discussion with HCAL experts its turn out that not the best file was taken for 2015 production.

The correct one is located in /afs/cern.ch/user/a/abdullin/public/HF_NewShowerLibrary_NewPMTs/HFShowerLibrary_npmt_noatt_eta4_16en.root - it is also required change file name inside data-SimG4CMS-Calo.spec file from 

HFShowerLibrary_npmt_eta4_16en.root
to
 HFShowerLibrary_npmt_noatt_eta4_16en.root

**Comment by civanch** [comment]
At the last SIM meeting (September,5) it was confirmed that we need to have two HF SLs:
HFShowerLibrary_npmt_noatt_eta4_16en.root
HFShowerLibrary_oldpmt_noatt_eta4_16en.root
@degano, please, proceed with this PR

**Comment by davidlange6** [comment]
Hi all

Not yet for 71x. Let's get it to work in 72 first.

On Sep 5, 2014, at 5:28 PM, "Vladimir Ivantchenko" <notifications@github.com<mailto:notifications@github.com>> wrote:

At the last SIM meeting (September,5) it was confirmed that we need to have two HF SLs:
HFShowerLibrary_npmt_noatt_eta4_16en.root
HFShowerLibrary_oldpmt_noatt_eta4_16en.root
@deganohttps://github.com/degano, please, proceed with this PR

**Comment by civanch** [comment]
@degano, if this PR is closed does it means that new HF SL both for 2012 and for 2015 are in the recent IB? In that case I can make corresponding PR for python configuration?

**Comment by ghost** [comment]
@civanch sorry, that was a mistake.
The corresponding PR for 72X, however, should be already in, I am waiting for ORP green light to put this one in as well.

**Comment by civanch** [comment]
PR 5466 for cmssw is pending which is required updated SL files.
Files to be included:

SimG4CMS/Calo/data/HFShowerLibrary_npmt__noatt_eta4_16en.root
SimG4CMS/Calo/data/HFShowerLibrary_oldpmt_noatt_eta4_16en.root

@davidlange6, can we now push these PRs?

**Pull request closed without merging**
