### PR TITLE
Update RecoMuon-TrackerSeedGenerator to V00-05-00

### PR DESCRIPTION
**Pull request by perrotta**
It replaces https://github.com/cms-sw/cmsdist/pull/8458/files which has conflicts

Move RecoMuon-TrackerSeedGenerator data to new tag, see
https://github.com/cms-data/RecoMuon-TrackerSeedGenerator/pull/5

### CODE REVIEW

**Comment by perrotta** [comment]
please test
(just to be sure...)

**Comment by missirol** [comment]
@cms-sw/externals-l2 , we would need a backport of this PR to `13_0_X`. Is that something you could take care of ? (is it okay to ask here, or is there a procedure to follow ?)

**Comment by aandvalenzuela** [comment]
Hello @missirol,

Find backport at https://github.com/cms-sw/cmsdist/pull/8461.
Thanks!

**Comment by perrotta** [comment]
merge

**Pull request merged**
