### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
ROOT changed Minuit logging here in master:
root-project/root#6705
and it's only in master, which means either we ask them to put it in 6-22 and fix it once or device something else.
To use the new logging nearly but not exactly straightforward so authors of
RecoLocalCalo/HcalRecAlgos should have to setup the MnPrint:: SetLevel -> Verbose and some other printing

**Comment by davidlange6** [comment]
I realize that we have copied and modified some root code here.. The trouble with that being that now we should in theory re-copy and re-modify it.. 

Practically some easy alternatives are
a) use the cms message logger for printouts (advantage - will behave like other cms code)
b) add the ifdefs for these - eg, from here:
https://github.com/root-project/root/pull/6705/files#diff-0dee475476c5a425f99aedd676a201955d915d7622abcfe256a2d1fcccc36872L105

**Comment by mrodozov** [comment]
I substituted all calls with LogInfo since they were just printouts anyway 
https://github.com/cms-sw/cmssw/pull/32440

**Comment by mrodozov** [comment]
please test

**Pull request merged**
