### PR TITLE
Update xrootd to 4.0.4  (backport 7_1_X)

### PR DESCRIPTION
**Pull request by silviodonato**
Update of xrootd to 4.0.4 in CMSSW_7_1_X in order to solve the issue with `cmsLHEtoEOSManager` ( https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/7320/1.html ).
The problem was fixed by https://github.com/cms-sw/cmssw/pull/31553 and https://github.com/cms-sw/cmssw/pull/31922 .
However the fix did not work in `CMSSW_7_1_X` (specifically `CMSSW_7_1_32`, used in https://cms-pdmv.cern.ch/mcm/campaigns?prepid=RunIIWinter15pLHE) because of the old version `xrootd`.

This PR updates `xrootd` to 4.0.4 by backporting the relevant commits from `CMSSW_7_5_8_patch7` (corresponding to https://cms-pdmv.cern.ch/mcm/campaigns?prepid=HINPbPbWinter16pLHE)

### CODE REVIEW

**Comment by silviodonato** [comment]
test parameters:
- workflows = 1370.0,1370.17,1370.18,25215.0,25215.17,25215.18

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
assign pdmv

**Comment by silviodonato** [comment]
@smuzaffar do you think the PR is ok?

**Comment by jordan-martins** [comment]
+1

**Comment by smuzaffar** [comment]
@silviodonato , yes this looks good.

**Comment by silviodonato** [comment]
please test

**Comment by smuzaffar** [comment]
abort
@silviodonato ,for some strange reason this build hangs while loading UtilitiesXrdAdaptorPlugin plugin. This plugin uses xrootd. 
I have aborted the job and will try to build locally to see what is wrong.

**Comment by smuzaffar** [comment]
@silviodonato , it is not this simple. We need cmssw changes to go with newer version of xrootd. For example I see https://github.com/cms-sw/cmssw/pull/6592 was for porting cmssw to xrootd 4.x

There are a lot of other cmssw changes which might be needed. So it is not trivial to backpot xoortd to 71X. One thing which we can do is to use system xrootd for the cmsLHEManager script e.g. script can unset cmssw env and use xrootd from system.

**Comment by silviodonato** [comment]
Thanks @smuzaffar , I realized that the problem is the absence of `xrdfs` in `singularity`. We don't get any error running `BPH-RunIIWinter15pLHE-00009` on `lxplus6`. I moved the discussion on https://github.com/cms-sw/cmssw/issues/32035

**Pull request closed without merging**
