### PR TITLE
upgrade to lhapdf6 sets version 6.1.5a

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
+1

**Comment by bendavid** [comment]
Actually @mkirsano, doesn't this have to go in the other branch instead?
https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_5_3_X/slc6_amd64_gcc472

(and in that branch I had already done the update to 6.1.5 at least)

**Comment by mkirsano** [comment]
We always used */stable branch. I can add to this branch as well.

**Comment by bendavid** [comment]
Yes, maybe @ktf, @degano et al can tell us which we should be using for 53x from now on.  (Clearly from a generator/production standpoint we have no need for further slc5 releases)

**Comment by bendavid** [comment]
(but since I did the last update in https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_5_3_X/slc6_amd64_gcc472 I guess it has to go there)

**Comment by nclopezo** [comment]
Hi All, 
Yes, I can confirm that the branch that is used for the 5_3_X-slc6_amd64_gcc472 is IB/CMSSW_5_3_X/slc6_amd64_gcc472. https://github.com/cms-sw/cms-bot/blob/master/config.map#L40

**Comment by smuzaffar** [comment]
closing this PR, identical request has been integrated in the correct branch

**Pull request closed without merging**
