### PR TITLE
Drop TopRex

### PR DESCRIPTION
**Pull request by iarspider**
Notice: doesn't seem to be used in CMSSW. The only non-text references I could find are these: [1](https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Pythia6Interface/src/Pythia6Service.cc#L167), [2](GeneratorInterface/Pythia6Interface/src/txgive.F). Not sure how to handle these.

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , do we need a cmssw pr to go with this change?

**Comment by iarspider** [comment]
@smuzaffar PhotosInterface was dropped in https://github.com/cms-sw/cmssw/pull/37616, which was merged 18 hrs ago, could this PR be picking up old cmssw version?

EDIT: I could've missed some reference, let me double-check

EDIT2: 
```
$ git clone https://github.com/cms-sw/cmssw.git -b CMSSW_12_4_DEVEL_X
$ find cmssw -name PhotosInterface.cc
# Nothing found
```

**Comment by smuzaffar** [comment]
@iarspider tests are run against `CMSSW_12_4_DEVEL_X_2022-04-24-2300` which includes https://github.com/cms-sw/cmssw/pull/37616

**Comment by smuzaffar** [comment]
test with out full_cmssw

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
> @smuzaffar PhotosInterface was dropped in [cms-sw/cmssw#37616](https://github.com/cms-sw/cmssw/pull/37616), which was merged 18 hrs ago, could this PR be picking up old cmssw version?
> 
> EDIT: I could've missed some reference, let me double-check
> 
> EDIT2:
> 
> ```
> $ git clone https://github.com/cms-sw/cmssw.git -b CMSSW_12_4_DEVEL_X
> $ find cmssw -name PhotosInterface.cc
> # Nothing found
> ```

ok issue understaood now. When PR tests are run for `full_cmssw=true` then bot was checking out `CMSSW_12_4_X` branch [a] instead of dedicated devel branch. https://github.com/cms-sw/cms-bot/commit/b2d75955d3e7bfc2a4d9b2a0d771b1caa698832b should fix this issue. Anyway, I have restarted the tests without `full_cmssw` 

[a]
```
11:15:13 ++ git branch
11:15:13 ++ grep '^  *CMSSW_'
11:15:13 + git checkout CMSSW_12_4_X
11:15:13 Switched to branch 'CMSSW_12_4_X'
11:15:13 Your branch is up to date with 'official-cmssw/CMSSW_12_4_X'.
11:15:13 + echo '/*/'
11:15:13 + git read-tree -mu HEAD
```

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

No idea why we have too many comparison failures

**Comment by smuzaffar** [comment]
tests passed , lets get this in DEVEL IBs

**Pull request merged**
