### PR TITLE
Improve protobuf text_format output

### PR DESCRIPTION
**Pull request by kpedro88**
This PR applies a small patch to protobuf so that text output from the `text_format` Python API avoids repetition for both primitive types and message types. This is used to get more concise printouts from the `cmsTritonConfigTool` (see https://github.com/cms-sw/cmssw/issues/43695 and https://github.com/cms-sw/cmssw/pull/43696).

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#43696

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/43696

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
