### PR TITLE
Update Geant4 to 10.6.10

### PR DESCRIPTION
**Pull request by mrodozov**
@civanch would you check the config please ?

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by civanch** [comment]
@mrodozov , #32009 should fix compilation problem.

**Comment by mrodozov** [comment]
please test
I see it's merged now

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/32009

**Comment by smuzaffar** [comment]
Tests are still running but lets get this merged for GEANT4 IB.

**Pull request merged**
