### PR TITLE
Updated root to tip of branch v6-12-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
This PR introduced a crash in runtestPhysicsToolsPatAlgos.

It would be nice to not ignore somewhat clear problems in ROOT I/O.

The symptoms also include a problem earlier seen in test builds and reported in https://github.com/cms-sw/cmssw/pull/22594#issuecomment-426146748
where a file 02FB8769-5433-E711-BBDE-0025905A6076.root from ```/JetHT/Run2016E-18Apr2017-v1/AOD``` shows a crash on exit from the root session when doing ```en->Scan("recoPFJets_ak4PFJets__RECO.obj.energy()");```

I propose to revert.

@fabiocos

**Comment by fabiocos** [comment]
@slava77 this was not ignored, I discussed it with Shahzad and Chris, and yesterday I think we agreed to wait for a few days a possible fix, or revert this PR before 10_4_0_pre1 is built

**Comment by slava77** [comment]
looking around a bit more, I see that  validateJR scripts running on miniAOD files are crashing
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_4_X_2018-10-15-2300+24432/28943/validateJR/all_mini_OldVSNew_TTbar13TeVPUppmx2018wf250202p181/all_mini_OldVSNew_TTbar13TeVPUppmx2018wf250202p181.log

I will not be able to sign any [new, non-trivial] reco PRs without the fix/revert.

**Comment by slava77** [comment]
> @slava77 this was not ignored

related to my comment
> It would be nice to not ignore somewhat clear problems in ROOT I/O.

I meant to not ignore the failures in tests before merging an external.

**Comment by fabiocos** [comment]
@DrJones15 @smuzaffar is there any news about a possible fix? Otherwise I would say let's just revert the patch

**Pull request merged**
