### PR TITLE
[Do not merge] Test cmssw build image

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
test parameters:
- full_cmssw = true
- container = cmssw/el8:x86_64-buildtime

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Updating image with the missing pkgs (`libaio` missing and probably the other `lib*` packages that we discussed on Friday @smuzaffar)

**Comment by smuzaffar** [comment]
wait @aandvalenzuela , let me check something

**Comment by aandvalenzuela** [comment]
Right, I am checking the bootstrap, because I did not find `libaio` in my case, but the package is there in the regular driver

**Comment by smuzaffar** [comment]
looks like `libaio` needs to go in to runtime image as it is needed at runtime ( by oracle libs)

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
My bad, I have only rebuilt runtime image

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Adding `textinfo` pkg. From `gcc` build log: `*** Makeinfo is missing. Info documentation will not be built`.

**Comment by smuzaffar** [comment]
is it `textinfo` of `texinfo` ?

**Comment by aandvalenzuela** [comment]
`texinfo`, sorry!

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
please test

use latest IB

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

- rebuilding gcc

**Comment by aandvalenzuela** [comment]
Failing tests are known issues. `gcc` rebuilds fine.

**Pull request closed without merging**
