### PR TITLE
scram-project-build: do not relocate ELF for tests

### PR DESCRIPTION
**Pull request by davidlt**
The tests are not shipped with CMSSW, no need for relocate them.
Solves globbing issues in find command.

Signed-off-by: David Abdurachmanov David.Abdurachmanov@cern.ch

### CODE REVIEW

**Comment by smuzaffar** [comment]
test are shipped with cmssw, why you think otherwise?
--shahzad

**Comment by davidlt** [comment]
Because the directory `./test/$SCRAM_ARCH` is empty?

**Comment by smuzaffar** [comment]
may be in a patch release (where there are no tests build) but for full 
release it should have all the tests.

**Comment by davidlt** [comment]
You are right.

**Comment by davidlt** [comment]
I will re-add test relocation after 1400 IB.

**Pull request merged**
