### PR TITLE
clean up of toolfiles that are now part of py2-pippkgs

### PR DESCRIPTION
**Pull request by davidlange6**
and migration cjson to pip

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , while you are on it, can you please fix
```
****WARNING: Invalid tool py2-pytz. Please fix py2-pandas file.
```
and may be py2-pandas.spec too.

**Comment by davidlange6** [comment]
will do
thanks for noticing that one

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Pull request merged**
