### PR TITLE
Update tag for DQM-Integration to V00-07-00

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmsdist/pull/9259

Move DQM-Integration data to new tag, see https://github.com/cms-data/DQM-Integration/pull/8. Needed by https://github.com/cms-sw/cmssw/pull/45289

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test with https://github.com/cms-sw/cmssw/pull/45289

**Comment by smuzaffar** [comment]
@mmusich , note that this change also includes the changes of https://github.com/cms-data/DQM-Integration/pull/7 ( i.e. DQM-Integration=V00-06-00 ), I hope this is ok to backport to 14.0.X ?

**Comment by mmusich** [comment]
> note that this change also includes the changes of https://github.com/cms-data/DQM-Integration/pull/7 ( i.e. DQM-Integration=V00-06-00 ), I hope this is ok to backport to 14.0.X ?

@smuzaffar, it is because `V00-07-00` completely superseded `V00-06-00` , so it's fine to jump over that version.

**Comment by smuzaffar** [comment]
+externals

need to go in with https://github.com/cms-sw/cmssw/pull/45289

**Comment by rappoccio** [comment]
+1

**Pull request merged**
