### PR TITLE
Set `ALPAKA_DEFAULT_HOST_MEMORY_ALIGNMENT=128` [12.5.x]

### PR DESCRIPTION
**Pull request by fwyzard**
Backport of #8107 to 12.5.x .

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #8107

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = HeterogeneousCore
- build_verbose = true

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+orp

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
