### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
The error seems related to a glitch of `eoscms.cern.ch`
```

dropped waiting message count 0
[2020-07-15 03:21:52.645764 +0200][Error  ][PostMaster        ] [p06253937k46044.cern.ch:1095 #0] Forcing error on disconnect: [ERROR] Operation interrupted.
[2020-07-15 03:36:31.415360 +0200][Error  ][PostMaster        ] [eoscms.cern.ch:1094 #0] Forcing error on disconnect: [ERROR] Operation interrupted.


Fatal system signal has occurred during exit

---> test runtestTqafExamples had ERRORS


```

**Comment by smuzaffar** [comment]
agree, unit test failure is unrelated here. We can restart the test here, it is for root master branch only

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
unit test failure are not related to this PR

**Pull request merged**
