### PR TITLE
[L1Trigger-L1THGCal] New motherboard mappings and add numbers of links

### PR DESCRIPTION
**Pull request by smuzaffar**
based on https://github.com/cms-data/L1Trigger-L1THGCal/pull/14

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals
based on tests run here https://github.com/cms-data/L1Trigger-L1THGCal/pull/14
This update only include new files so can be merged

**Comment by fabiocos** [comment]
@smuzaffar unfortunately I overlooked this is needed by #26820, and this is causing a failure in the last IB...

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
