### PR TITLE
Add `ROOT_INCLUDE_PATH` to `alpaka.xml`

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
For future reference, we saw messages like
```
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for alpaka/dev/DevCpu.hpp
   requested to autoload type alpaka::DevCpu
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for alpaka/queue/QueueGenericThreadsBlocking.hpp
   requested to autoload type alpaka::QueueGenericThreadsBlocking
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for alpaka/core/ApiCudaRt.hpp
   requested to autoload type alpaka::ApiCudaRt
```
when running a job producing a "portable product" in the Event on a developer area. Quick web search suggested to add the "offending" headers to `ROOT_INCLUDE_PATH`.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
