### PR TITLE
backport sherpa 2.2.8 to 71X

### PR DESCRIPTION
**Pull request by SiewYan**

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@SiewYan @qliphy I understand that you do not need a parallel update of openloops, please confirm

**Comment by SiewYan** [comment]
@fabiocos , thanks for the merge! The ultimate goal is to have latest openloops 2.1.0 alongside with sherpa 2.2.8.
 The delay of backport was caused by obsolete git version (1.8.3.1) in 71X, which unable openloops 2.1.0 to function properly.
Due to the urgency, we decided to stick with openloops 2.0.0 for the time being.

**Pull request merged**
