### PR TITLE
Move to root / roofit 5.34.17, including IO patches from Chris.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidlt** [comment]
Is this based on official ROOT 5.34.17? If TMVA weight files were not adjusted in standard IBs, this should break RelVals.

**Comment by ktf** [comment]
It is based on the official 5.34.17. Can you point me to the actual issue (or propose a fix)?

**Comment by davidlt** [comment]
Last 'ORP meeting before Christmas. Solved for ROOT6 IB.

The following lines must be removed in CMSSW and CMSDIST (externals):

## CMSSW

```
RecoEgamma/EgammaTools/data/TMVAnalysis_Likelihood.weights.txt:VerboseLevel: "Default" [Verbosity level]
```

## CMSDIST

```
RecoParticleFlow/PFProducer/data/MVAnalysis_BDT.weights_PfElectrons23Jan.txt:VerboseLevel: "Info" [Verbosity level]
RecoParticleFlow/PFProducer/data/MVAnalysis_BDT.weights_PfElectrons23Jan_IntToFloat.txt:VerboseLevel: "Info" [Verbosity level]
RecoParticleFlow/PFProducer/data/MVAnalysis_BDT.weights_finalID_hzz-pions.txt:VerboseLevel: "Info" [Verbosity level]
RecoParticleFlow/PFProducer/data/MVAnalysis_BDT.weights_pfConversionAug0411.txt:VerboseLevel: "Default" [Verbosity level]
RecoParticleFlow/PFTracking/data/BDT_weights_21.txt:VerboseLevel: "Info" [Verbosity level]
RecoParticleFlow/PFTracking/data/MVAnalysis_BDT.weights_convBremFinder_19Apr.txt:VerboseLevel: "Info" [Verbosity level]
RecoParticleFlow/PFTracking/data/MVAnalysis_BDT.weights_convBremFinder_19Apr_IntToFloat.txt:VerboseLevel: "Info" [Verbosity level]
```

Thus RecoEgamma/EgammaTools (CMSSW), data-RecoParticleFlow-PFProducer (CMSDIST), and data-RecoParticleFlow-PFTracking (CMSDIST).

**Comment by ktf** [comment]
You mean from the files themselves? If that is the case, for cmsdist, it 
should be enough we rebuild the data packages and the new files will be 
picked up, right?

**Comment by ktf** [comment]
Also, is there any reason for not doing this for 71X/stable?

**Comment by davidlt** [comment]
Yes, from the files themselves. `VerboseLevel:` option in TMVA is not supported anymore (ROOT5 and ROOT6). I did it for ROOT6 only, but for stable it should be done by reco guys. They know all the details. Also new ROOT version is needed for OSX 10.9, thus indirectly it also blocks 10.9.

**Comment by ktf** [comment]
@anton-a and @slava77 are you ok with having these changes in vanilla 71X?

**Comment by ktf** [comment]
ping?

**Pull request merged**
