### PR TITLE
CRAB 3.3.1912.patch1 with WMCore 1.2.9

### PR DESCRIPTION
**Pull request by belforte**
Please test this in preproduction

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 02fad1451b870b482e3d5f6d80bba6c14dbd81b2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5441/test_02fad14-20191218-230504.log" target="_blank">here</a>.

**Comment by belforte** [comment]
since build was OK, will it be uploaded to COMP repo ? I wanted to trigger a new container for this, but need the newe HG tag.

**Comment by belforte** [comment]
Hope we do not need "days" to push a change in pre-prod. By the way, why do we keep bulding for  slc6_amd64_gcc493  as well ? Is anything being deployed anywhere on that arch ?

**Comment by muhammadimranfarooqi** [comment]
> Hope we do not need "days" to push a change in pre-prod. By the way, why do we keep bulding for slc6_amd64_gcc493 as well ? Is anything being deployed anywhere on that arch ?

@belforte 
Is this related to CMSWEB? Should I merge this? I don't know about old architecture why its there. 

Best
Muhammad Imran

**Comment by belforte** [comment]
@muhammadimranfarooqi thanks for checking. Yes, this is about CMSWEB. But I made this PR w/o knowing the status of cmsweb preprod. Given the work that you have in progress there, it is better that you do not merge now but wait until the procedure for changes in the new cmsweb-k8s-testbed is established, at which point we should have standard answers for all questions.
I leave to Valentin to say if the bot should be changed to forget about old arch. 
I will be able to test things using the k8s test clusters in the meanwhile.
`

**Comment by amaltaro** [comment]
The old architecture check can be safely removed. `slc6_amd64_gcc493` is not used for at the very least, 2 years.

**Comment by muhammadimranfarooqi** [comment]
@belforte 

Should I merge and include this PR in the coming CMSWEB release. Please advise. 

Best
Imran

**Comment by muhammadimranfarooqi** [comment]
@belforte 
I just noticed, there is a conflict as well. Please have a look at this as well. 

Best
M Imran

**Comment by belforte** [comment]
thanks @muhammadimranfarooqi for checking. This should not be merged since we moved on with CRAB version and WMCore integration. I am closing it.
What I need to understand is what is now the best way to get a new CRAB REST version deployed in the k8s preprod cluster. I thought that one of the goals of k8s transition was to get out of the rigid monthly deployment cycle.

**Pull request closed without merging**
