### PR TITLE
Add C++ wrappers for the CUDA API

### PR DESCRIPTION
**Pull request by fwyzard**
Add C++ wrappers for the CUDA API from https://github.com/eyalroz/cuda-api-wrappers

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
backport #3691

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
@fwyzard , does it looks good/usable in 10.1.X?

**Comment by fwyzard** [comment]
Looks like it does work - I've been able to build all the examples.

**Comment by makortel** [comment]
I can also confirm that my prototype code (using cuda-api-wrappers in a very hacky way in 10_0_0) works fine (=compiles, runs) in a recent 10_1_X IB.

**Pull request merged**
