### PR TITLE
Update root on cmsdist master

### PR DESCRIPTION
**Pull request by mrodozov**
please test
new commits on root 6.14 to be picked

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals
@fabiocos , any objections updating root 6.14  for master IB. We want to back port it to 10.6.X ( https://github.com/cms-sw/cmsdist/issues/5313 )

**Comment by fabiocos** [comment]
@smuzaffar @slava77 as we want to move forward asap to 6.18, better to merge this now, so it can be checked in next pre-release before the switch

**Comment by fabiocos** [comment]
+1

**Comment by slava77** [comment]
I didn't realize we are still using 6.14 in the cmssw master.
Thanks for merging.
This means that I can also check the update in the 110X. This is probably a nicer way than jumping directly to 106X

**Comment by smuzaffar** [comment]
@slava77 , latest root 6.14 is now available in CMSSW_11_0_X_2019-10-31-2300 and above. Please  check if the pyroot enum issue is fixed.

**Comment by slava77** [comment]
I confirm that this now behaves as expected. More details follow, if needed.

using test.py
```python
import os, re, sys, time, ROOT, subprocess
from DataFormats.FWLite import Events, Handle

muonHandle, muonLabel = Handle("std::vector<pat::Muon>"),"slimmedMuons"

ROOT.gROOT.SetBatch(True)
events = Events("root://cms-xrd-global.cern.ch//store/group/phys_muon/dmytro/tmp/store+mc+RunIIAutumn18MiniAOD+DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8+MINIAODSIM+102X_upgrade2018_realistic_v15-v1+80000+695EE995-7CA9-5A46-81EF-C6777A74C791.root")
nevents = 0

print "ROOT.reco.MatchedMuonFromGaugeOrHiggsBoson  = ", ROOT.reco.MatchedMuonFromGaugeOrHiggsBoson
print "ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  = ", ROOT.reco.GhostMuonFromGaugeOrHiggsBoson
print "ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson  = ", ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson

for event in events:
    if nevents>=100: break
    nevents+=1
    event.getByLabel(muonLabel, muonHandle)
    muons = muonHandle.product()
    for muon in muons:
        if muon.simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson or muon.simExtType()>1e4 or muon.simExtType()<0:
            print "simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson or pos/neg: pt: %0.1f \tsimType: %d \textSimType: %d" % (muon.pt(),muon.simType(),muon.simExtType())
        if muon.simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson:
            print "simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson: pt: %0.1f \tsimType: %d \textSimType: %d" % (muon.pt(),muon.simType(),muon.simExtType())
        if muon.simExtType()==ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson:
            print "simExtType()==ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson: pt: %0.1f \tsimType: %d \textSimType: %d" % (muon.pt(),muon.simType(),muon.simExtType())
```

in CMSSW_11_0_X_2019-10-31-1100 there are several things wrong
```
ROOT.reco.MatchedMuonFromGaugeOrHiggsBoson  =  10
ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  =  -10
ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson  =
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    print "ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson  = ", ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson
AttributeError: type object 'int' has no attribute 'GhostMuonFromGaugeOrHiggsBoson'
#and, further ignoring the nested enum call:
simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson or pos/neg: pt: 1.1      simType: 4294967292     extSimType: 4294967286
simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson or pos/neg: pt: 1.0      simType: 4294967294     extSimType: 4294967292
```

in CMSSW_11_0_X_2019-10-31-2300 the behavior is as expected
```
ROOT.reco.MatchedMuonFromGaugeOrHiggsBoson  =  10
ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  =  -10
ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson  =  -10
simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson or pos/neg: pt: 1.1      simType: -4     extSimType: -10
simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson: pt: 1.1         simType: -4     extSimType: -10
simExtType()==ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson: pt: 1.1     simType: -4     extSimType: -10
simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson or pos/neg: pt: 1.0      simType: -2     extSimType: -4
```

**Pull request merged**
