### PR TITLE
Updated root to tip of branch v6-30-00-patches

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
root 6.30 changes are https://github.com/root-project/root/compare/dcf4d2a31a...8f594ff6aa 
@makortel @Dr15Jones, any objection on get these in 14.1.X default IBs (I see there are some thread safety related changes too) ?

**Comment by Dr15Jones** [comment]
@smuzaffar as long as our tests and RelVals pass, I don't have any objections.

**Comment by makortel** [comment]
> root 6.30 changes are [root-project/root@dcf4d2a...8f594ff](https://github.com/root-project/root/compare/dcf4d2a31a...8f594ff6aa)
> @makortel @Dr15Jones, any objection on get these in 14.1.X default IBs (I see there are some thread safety related changes too) ?

Let's get them in. I see commits from https://github.com/root-project/root/pull/15113, that are needed to address https://github.com/cms-sw/cmssw/issues/33084, and https://github.com/root-project/root/pull/15459, that was motivated by https://github.com/cms-sw/cmssw/issues/44670.

**Comment by smuzaffar** [comment]
test parameters:
- enable = threading

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
PR DQM/reco comparison show a lot of  differences

**Comment by Dr15Jones** [comment]
I believe differences when using threads is expected. Was the results of the non-thread case also problematic?

**Comment by smuzaffar** [comment]
DQM/reco comparison is only run for non-threaded runs.

**Comment by makortel** [comment]
Would it make sense to rerun the tests (without the threading, just to make sure)? The earlier tests did not show unexpected differences.

**Comment by smuzaffar** [comment]
sure I can re-run it once 11h00 IB is available. By the way https://github.com/cms-sw/cmsdist/pull/9189#issuecomment-2108062562 are without threading

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
> sure I can re-run it once 11h00 IB is available. By the way [#9189 (comment)](https://github.com/cms-sw/cmsdist/pull/9189#issuecomment-2108062562) are without threading

Right. There the comparison differences are in 12834.7 that are known to be spurious https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
Last round of tests looks clean

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
