### PR TITLE
Update to 3.3.2002.rc1

### PR DESCRIPTION
**Pull request by lecriste**
CRABServer 3.3.2002.rc1
WMCore 1.2.9

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 925a8cc93b3a693c166a9a55f8dda50b53d1936f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5485/test_925a8cc-20200122-145005.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@lecriste 

Should this be included in upcoming release?

**Comment by lecriste** [comment]
No. This is a CRAB client update, no link with CMSWEB.

**Comment by muhammadimranfarooqi** [comment]
Ok. Thanks for clarification.

**Comment by amaltaro** [comment]
Is this outdated and no longer needed?

**Pull request closed without merging**
