### PR TITLE
Drop the "cub" external library (11.1.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Starting with CUDA 11.0, cub is officially included in the CUDA toolkit.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #5943

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
+externals
this tool was not used by any thing in cmssw, so it is safe to remove it

**Comment by silviodonato** [comment]
+1

**Pull request merged**
