### PR TITLE
Update modules IB CLHEP

### PR DESCRIPTION
**Pull request by mrodozov**
synch with cmsdist/master

### CODE REVIEW

**Comment by mrodozov** [comment]
a sec to bring Vassil's commits on top of 2440 ...

**Comment by smuzaffar** [comment]
@davidlange6 , what about these changes of @vgvassilev  https://github.com/cms-externals/clhep/commit/33f7866e81e8eb1129b49cdb565ea6fddeb5f9f0 ? Do we need these for clhep 2.4.4.0?

**Comment by mrodozov** [comment]
I'm getting those on a cms/module/2440 branch
although they are mostly upstream already.

**Comment by davidlange6** [comment]
Hum, they aren’t already a part of 2.4.4.0? (:()

**Comment by mrodozov** [comment]
they are i edited my comment, I'm not sure if all are - lets assume they all are (and fix them if some are not)

**Pull request merged**
