### PR TITLE
New DAS release

### PR DESCRIPTION
**Pull request by vkuznet**
In this release, we switch to production rucio URLs

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 5d6d68576fb705ef300c23fc67dfda7f2456f0b8 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5730/test_5d6d685-20200409-161504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
to cf04a637f67ace90d6dff2d07e0a71976a9763e2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5730/test_cf04a63-20200409-163003.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
Muhammad, this is usual go permission issue, please change the permission in build area and trigger the build again (I commit one tag after another and first build was successful but locked permissions).

**Comment by muhammadimranfarooqi** [comment]
> Muhammad, this is usual go permission issue, please change the permission in build area and trigger the build again (I commit one tag after another and first build was successful but locked permissions).

Yes, I am running again.

**Comment by muhammadimranfarooqi** [comment]
+1 to cf04a637f67ace90d6dff2d07e0a71976a9763e2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5730/test_cf04a63-20200409-170504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Is it ready to go in now?

**Comment by vkuznet** [comment]
yes, it is ready to be merged. Thanks.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

By the way, this is the script that runs for this task. In the build case. If you can figureout the permission error here, it would be great. 
https://github.com/dmwm/deployment/blob/master/dmwmbld/dmwmbld_task

**Pull request merged**
