### PR TITLE
Update Alpaka to version 1.1.0 [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
Major changes include:
  - introduce SYCL/oneAPI support for CPUs and Intel GPUs
  - make alpaka platforms full objects, and rename from `Pltf` to `Platform`
  - make the vendor random number generators support optional
  - refactor `Vec` type, and add `.x()`, `.y()`, `.z()` accessors
  - enable support for asynchronous memory operations in ROCm 5.3 and later
  - change all CUDA warp operations to synchronise all threads
  - remove `ALPAKA_ASSERT_OFFLOAD`, introduce `ALPAKA_ASSERT_ACC`
  - implement `copysign()`, `fma()`, `log2()`, `log10()` math functions
  - simplify offset and pitch APIs
  - add support for CUDA 12.2, 12.3 and ROCm 5.6, 5.7, 6.0
  - improve error messages related to kernel launches
  - rework thread pool and callback threads
  - fix `alpaka::wait(device, event)` function for CUDA/HIP GPUs
  - implement `alpaka-ls`

Disable the vendor specific random number generators in Alpaka (NVIDIA cuRAND, AMD rocRAND, Intel DPL).

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #8957

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmssw#43943

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard , as [fwyzard:IB/CMSSW_14_0_X/master_alpaka_1.1.0](https://github.com/fwyzard/cmsdist/tree/IB/CMSSW_14_0_X/master_alpaka_1.1.0) branch was used for testing multiple arch and release cycles so we are now hitting the max statuses limit (1000 per commit). Can you please push a simple change to this branch e.g. adding a comment in the ChangeLog file? this will push push a new commit and will allow bot to set new status

[a]
```
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "Status", "code": "custom", "message": "This SHA and context has reached the maximum number of statuses."}], "documentation_url": ["https://docs.github.com/rest/commits/statuses#create-a-commit-status"](https://docs.github.com/rest/commits/statuses#create-a-commit-status)}
```

**Comment by fwyzard** [comment]
or... just merge it ?

I can push something only later today

**Comment by smuzaffar** [comment]
should this go with  cms-sw/cmssw#43943 ?

**Comment by fwyzard** [comment]
> should this go with [cms-sw/cmssw#43943](https://github.com/cms-sw/cmssw/pull/43943) ?

Yes.

**Comment by antoniovilela** [comment]
This was tested with cms-sw/cmssw#43943

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
