### PR TITLE
[Do not merge] Testing ROOT 6.16

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by yamaguchi1024** [comment]
Is this still testing?

**Comment by yamaguchi1024** [comment]
please test :smile_cat:

**Comment by davidlange6** [comment]
please test




On 18 Jan 2019, at 18:26, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


Pull request #4633<https://github.com/cms-sw/cmsdist/pull/4633> was updated.

**Comment by yamaguchi1024** [comment]
Looks good! Closing

**Pull request closed without merging**
