### PR TITLE
New version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 0e06b02626b5e82f10a1ff8e76f1fac2e481b2f9 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2684/test_0e06b02-20161128-153505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 79067969e5acbb81d9cfde64e7a18f567f9769f9 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2684/test_7906796-20161130-201509.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to f1c55f8070077cb3441b239773ca1d11242aab09 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2684/test_f1c55f8-20161130-212509.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to cc57775e4676390ee8468faa354058916742d199 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2684/test_cc57775-20161202-125507.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to bf5de1358a73203b169ad948808756a8ed73a463 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2684/test_bf5de13-20161206-211508.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
+1 to 6276ff1016906388c6a6427be6371c8d2215b44f on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2684/test_6276ff1-20161212-233508.log" target="_blank">here</a>.

**Pull request merged**
