### PR TITLE
[Pythia8][306] Pythia Update to fix tau decays

### PR DESCRIPTION
**Pull request by smuzaffar**
See https://github.com/cms-externals/pythia8/pull/29

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-externals/pythia8#29

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by aandvalenzuela** [comment]
From the discussion in Software Release meeting, this PR can be merged as soon as possible. The next step is to discuss with @cms-sw/generators-l2 and PPD if a backport to `12_4_X` is needed. Thanks!

**Comment by smuzaffar** [comment]
+externals

@cms-sw/generators-l2 , @perrotta @rappoccio this PR includes the pythia8 fix for tau decays ( https://github.com/cms-externals/pythia8/pull/29 ) . Feel free to include it for next 12.6.X IB/pre-release. Let us know if this should be backported to 12.4/12.5 release cycles

**Comment by agrohsje** [comment]
Indeed, a back-port to 12_4 is needed as this will be used in the Run3 MC campaign we are starting now. Thanks so much!

**Comment by perrotta** [comment]
+1

**Pull request merged**
