### PR TITLE
move to latest config tag V05-05-03

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by davidlt** [comment]
This include fixes for _rootcint_ dictionaries and compiler flags order?

**Comment by smuzaffar** [comment]
yes. It is already being used in devel/next branch.

**Comment by smuzaffar** [comment]
@davidlt, by the way this only contains one fix for rootcint i.e. it drops the starting src/ from the path of LinkDef file. The other fix for finding out the headers directly included by LinkDef file and passing those on command-line is not yet done.

**Comment by davidlt** [comment]
@smuzaffar we don't need the second part, because decision was made to move away from _rootcint_ dictionaries at the end. We just need to actually do it and not keep it dragging for a long time.

**Pull request merged**
