### PR TITLE
use std=c++17 for cuda

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = HeterogeneousCore,HeterogeneousTest,RecoLocalCalo/EcalRecProducers,DataFormats/HcalDigi

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
FYI @fwyzard , passing `c++20` for host compiler breaks nvcc [a]. I am testing `c++17`   to see if works

[a]
```
>> Compiling alpaka/cuda src/HeterogeneousCore/AlpakaInterface/test/alpaka/testKernel.dev.cc
.../gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/cpp_type_traits.h(176): error: identifier "char8_t" is undefined
      struct __is_integer<char8_t>
                          ^
.../gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/cpp_type_traits.h(418): error: identifier "char8_t" is undefined
      struct __is_byte<char8_t>
....
....
.../gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/concepts(57): error: identifier "concept" is undefined
        concept __same_as = std::is_same_v<_Tp, _Up>;
        ^
.../gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/concepts(62): error: identifier "concept" is undefined
      concept same_as
                       ^
```

**Comment by fwyzard** [comment]
I don't think it's a good idea to build some files with `c++17` and some files with `c++20`, especially within the same library or plugin 🤔

**Comment by fwyzard** [comment]
What is the compilation command that fails?

**Comment by smuzaffar** [comment]
this command failed
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02798/el8_amd64_gcc12/external/cuda/12.2.1-bdf3fff69eaec65abe18a7569592cab6/bin/nvcc -x cu -MMD -MF tmp/el8_amd64_gcc12/src/HeterogeneousCore/AlpakaInterface/test/alpakaTestKernelCudaAsync/alpaka/testKernel.dev.cc.d -dc -DGNU_GCC -D_GNU_SOURCE -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DCMSSW_GIT_HASH='CMSSW_13_3_CPP20_X_2023-08-14-1100' -DPROJECT_NAME='CMSSW' -DPROJECT_VERSION='CMSSW_13_3_CPP20_X_2023-08-14-1100' -I/build/muz/cpp/CMSSW_13_3_CPP20_X_2023-08-14-1100/src -I/cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_CPP20_X_2023-08-14-1100/src -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02798/el8_amd64_gcc12/external/alpaka/develop-20230621-9bddc1f4bec282c5df27cfb492a2be8b/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02798/el8_amd64_gcc12/external/boost/1.80.0-18ae330322096fcd3a2722b58b9abf74/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02798/el8_amd64_gcc12/external/cuda/12.2.1-bdf3fff69eaec65abe18a7569592cab6/include -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02798/el8_amd64_gcc12/external/catch2/2.13.6-17102db92de47c6a473c6e67627c548a/include -std=c++20 -O3 --generate-line-info --source-in-ptx --display-error-number --expt-relaxed-constexpr --extended-lambda -gencode arch=compute_60,code=[sm_60,compute_60] -gencode arch=compute_70,code=[sm_70,compute_70] -gencode arch=compute_75,code=[sm_75,compute_75] -Wno-deprecated-gpu-targets -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored --cudart shared -DALPAKA_DEFAULT_HOST_MEMORY_ALIGNMENT=128 -DALPAKA_ACC_GPU_CUDA_ENABLED -UALPAKA_HOST_ONLY --compiler-options '-O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -ftree-vectorize -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -Wno-error=array-bounds -Warray-bounds -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DALPAKA_DEFAULT_HOST_MEMORY_ALIGNMENT=128 -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_HOST_ONLY -DBOOST_DISABLE_ASSERTS  -std=c++20 -fPIC '  /build/muz/cpp/CMSSW_13_3_CPP20_X_2023-08-14-1100/src/HeterogeneousCore/AlpakaInterface/test/alpaka/testKernel.dev.cc -o tmp/el8_amd64_gcc12/src/HeterogeneousCore/AlpakaInterface/test/alpakaTestKernelCudaAsync/alpaka/testKernel.dev.cc.o
```

**Comment by smuzaffar** [comment]
actually, passing `c++20` to both `nvcc` and host compiler fails with error ( see [IBs logs](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_3_CPP20_X_2023-08-14-1100/HeterogeneousCore/AlpakaInterface))
```
nvcc error   : 'cudafe++' died due to signal 9 (Kill signal)
```
the build process consumes a lot of memory
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                  
 4067 muzaffar  20   0   30.9g  25.3g    148 R 100.0 88.4   7:13.33 cudafe++  
```
then I was trying to pass `c++17` to `nvcc` only but that fails as the host compiler was using `c++20`

**Comment by fwyzard** [comment]
This looks similar to [NVIDIA bug #4139863](https://github.com/fwyzard/nvidia_bug_4139863) (a memory exhaustion in `cudafe++` in c++20 mode).

Unfortunately I have not heard any news about it from NVIDIA :-/

**Comment by fwyzard** [comment]
In turn, NVIDIA suggested that is the same bug described at https://stackoverflow.com/questions/76047498/cuda-compiler-infinite-loop .

**Pull request closed without merging**
