### PR TITLE
update mkFit to V2.0.1-1+pr280 for AVX2 support

### PR DESCRIPTION
**Pull request by slava77**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 11634.7

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
is there a special target to test AVX2 build with the bot?

**Comment by smuzaffar** [comment]
@slava77 , No there no such target yet

**Comment by slava77** [comment]
the regular tests run OK.

it's worth to merge after the AVX2 setup is checked, since this is the primary reason for the update.

**Comment by smuzaffar** [comment]
hold
I will check the avx2 setup and will unhold/approve it

**Comment by smuzaffar** [comment]
unhold
build fine with avx2 flags

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
