### PR TITLE
update utm: fix distinct L1 conditions being hashed to the same string

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #4133

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
for this backport let's wait for the validation in master

**Comment by smuzaffar** [comment]
@rekovic, do we still need it for 10.1.X? If yes, @fabiocos , @kpedro88 can we merge it?

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
