### PR TITLE
Remove patch that does not work with head of Igprof/master

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
@smuzaffar this pr was just to test with https://github.com/cms-externals/igprof/pull/5

**Comment by gartung** [comment]
please test with https://github.com/cms-externals/igprof/pull/5

**Comment by smuzaffar** [comment]
@gartung , let me know when these PRs (this one and https://github.com/cms-externals/igprof/pull/5)  are ready to go in

**Comment by gartung** [comment]
@smuzaffar I merged the pull request for cms-externals/igprof and updated this pull request with the commit. It is ready for merging.

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
@smuzaffar can this be merged

**Comment by smuzaffar** [comment]
+externals
looks good to me

**Pull request merged**
