### PR TITLE
Add cpu_features library

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by aandvalenzuela** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
