### PR TITLE
New py3 files for WMArchive and others

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 5ca5c66b31657ee84048000012a82ef567aacd33 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5333/test_5ca5c66-20191105-170503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 5a69205d23cb5fb4268bab595975929064a38081 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5333/test_5a69205-20191106-144004.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , Muhammad, could you please merge this PR, it brings python3 spec dependencies files required to move forward with WMArchive build migration to python3.

**Comment by amaltaro** [comment]
@vkuznet Valentin, can you please clarify why you're no longer building with pip a few of the python3 specs?

**Comment by vkuznet** [comment]
I try to stick with existing py2 specs. Where pip migration happened I use pip install, where it is not happened I still want to replicate existing specs with python3. This way is easier to maintain both python specs sets.

**Comment by vkuznet** [comment]
If I miss something feel free to point to inconsistencies. But keep in mind that it is not one-to-one migration since py2 ports may contain backported codebase which is no longer required in py3 land

**Comment by muhammadimranfarooqi** [comment]
+1 to b1e1314106d20a1710b5f0d25d121dc37090f63b on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5333/test_b1e1314-20191106-162004.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
I think maintaining python specs built with pip are much simpler than building things by our own. Eventually we should migrate all python packages to build with pip, so you have the opportunity to, I'd definitely move those python3 specs to pip as well.

Another point, cmssw folks use a single `build-with-pip` file: https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/master/build-with-pip.file

but I acknowledge it might be too much work for this PR.

**Comment by vkuznet** [comment]
Alan,
if you paid closer attention this PR contains
build-with-pip3.file which is analog of build-with-pip.file
where I changed from pip to pip3. So I do use pip (but only pip3 version)
and I said I do use pip3 everywhere where it is possible.
But to make transition easier I need to maintain consistent builds
and I chose to stick with identical body of specs between py2 and py3 ports.

**Comment by amaltaro** [comment]
You misunderstood me!
What I meant is that we could build python packages with the same build-with-pip.file, no matter whether it's python2 or python3. That would, of course, require changes to build-with-pip.file, that's why I pointed you to the cmssw version...

**Comment by muhammadimranfarooqi** [comment]
+1 to 6e9e03e751ea46b533ab220ea0222ab626cae457 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5333/test_6e9e03e-20191106-164004.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
Ahh, I didn't know that cmssw merged both python under one build-with-pip.file, that's good and we can use it, but again we should start doing this in stages. If we'll update build-with-pip.file now
we'll need to build and validate all py2 specs with it, then we can move to py3.

I wonder how build will pick the python version in new build-with-pip.file? In there I see doPython2 and doPython3 but someone somewhere should set it up. So we need more info before moving to single file.

**Comment by muhammadimranfarooqi** [comment]
+1 to 686410bb6fa5e4dbf53b4b5d376ef95496d6c50f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5333/test_686410b-20191107-150505.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@h4d4 @muhammadimranfarooqi , could you please merge this PR. It contains oy3 specs. I'm not sure about slc6 gcc493 build since it is out of date.

**Pull request merged**
