### PR TITLE
upgrade lhapdf to 6.4.0, sets to 6.4.0b

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mkirsano   there are a lot of DQM comparison differences https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-10-05-1100+dbfa9e/45970/validateJR.html . Do you understand these? are they expacted?

**Comment by smuzaffar** [comment]
assign generators
@mkirsano @cms-sw/generators-l2 , are these DQM comparison changes expected with lhapdf update?

**Comment by mkirsano** [comment]
Differences are possible. My tests give reasonable results.

**Comment by smuzaffar** [comment]
+externals
@cms-sw/generators-l2 is it needed for 12.1.0 release?

**Comment by agrohsje** [comment]
hi @smuzaffar, @mkirsano, for run 3 we still have 12_0: 
 https://cms-pdmv.cern.ch/mcm/campaigns?cmssw_release=CMSSW_12_0_*&page=0&shown=63

**Comment by mkirsano** [comment]
+1

**Comment by smuzaffar** [comment]
@qliphy , @perrotta please check if this should go in 12.2.X or not?

**Comment by qliphy** [comment]
please test
the last test was done weeks ago and the log is lost.  To check whether the differences really matters.

**Comment by agrohsje** [comment]
+generators
re-sign; Mikhail above: Differences are possible. My tests give reasonable results.

**Comment by smuzaffar** [comment]
@qliphy , @perrotta this is ready to go in 12.2.X

**Comment by qliphy** [comment]
+1

**Pull request merged**
