### PR TITLE
Pyquen reintegration as external

### PR DESCRIPTION
**Pull request by wouf**

### CODE REVIEW

**Comment by smuzaffar** [comment]
assign generators

**Comment by wouf** [comment]
Could You please to freeze this PR until I will find the reason of vertex warning.

**Comment by smuzaffar** [comment]
hold
on requests of @wouf https://github.com/cms-sw/cmsdist/pull/4790#issuecomment-475887738

**Comment by wouf** [comment]
Thanks, we can continue.

**Comment by smuzaffar** [comment]
unhold

**Comment by fabiocos** [comment]
@alberto-sanchez this needs GEN signature as well, as it goes together with cms-sw/cmssw#26226

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
+externals
just to keep the signatures clean

**Pull request merged**
