### PR TITLE
Yoda 1.6.7 and Rivet 2.5.4

### PR DESCRIPTION
**Pull request by xjanssen**
Update of external packages Rivet and Yoda. Might need to be also propagated to lower CMSSW versions.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by xjanssen** [comment]
Thanks, we will need this to be back-ported to 94X as well. Do I need to do a separate PR ?

**Comment by smuzaffar** [comment]
yes, please create new PR for 94X.

**Pull request merged**
