### PR TITLE
upgrade to evtgen 1.4.0p1

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by davidlt** [comment]
This was not tested with CMSSW and IBs are broken (not compiling).

```
CMSSW_7_6_X_2015-08-26-2300/src/GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels/EvtLb2plnuLCSRFF.cpp:87:10: error: 'ERROR' was not declared in this scope
    report(ERROR,"EvtGen") << "Only Lb -> p transitions allowed in EvtLb2plnuLCSRFF.\n";  
```

@davidlange6 @smuzaffar

**Comment by ghost** [comment]
@davidlt Okay, for the time being I reverted it here: #1776

**Comment by smuzaffar** [comment]
@mkirsano , looks like you need to use EvtGenReport(EVTGEN_ERROR,"EvtGen") instead of report(ERROR,"EvtGen")

Can you please provide a fix as soon as possible.

For now I have marked CMSSW_7_6_X_2015-08-26-2300 IB as bad one so ib-integration tests should not use it

**Comment by ghost** [comment]
@smuzaffar I'm working on the fix myself, should be ready soon.

**Pull request merged**
