### PR TITLE
Update to CUDA 11.2

### PR DESCRIPTION
**Pull request by fwyzard**
Update to CUDA 11.2 (11.2.0):
  * CUDA runtime version 11.2.72
  * NVIDIA drivers version 460.27.04

Various new fetures and bug fixes.

See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html .

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for cc8_amd64_gcc9

**Comment by fwyzard** [comment]
please test for slc7_aarch64_gcc9

**Comment by fwyzard** [comment]
please test for cc8_ppc64le_gcc9

**Comment by fwyzard** [comment]
please test for slc7_aarch64_gcc9

**Comment by fwyzard** [comment]
please abort

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for cc8_amd64_gcc9

**Comment by fwyzard** [comment]
please test for cc8_ppc64le_gcc9

**Comment by fwyzard** [comment]
please test for slc7_aarch64_gcc9

**Comment by fwyzard** [comment]
I assume the 11624.911 step1 DD4HEP failure is unrelated ?

**Comment by fwyzard** [comment]
Looking at the message, the PyMVA error seems unrelated, too.

**Comment by mrodozov** [comment]
11624.911 is failing in the ppc IB , but not in the x86. Also not failing in the next IB
The PyMVA is failing in the ppc IB

**Comment by fwyzard** [comment]
:+1:

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for slc7_ppc64le_gcc9

**Comment by fwyzard** [comment]
please test for slc7_aarch64_gcc9

**Comment by fwyzard** [comment]
please test for slc7_ppc64le_gcc9

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
The `slc7_ppc64le_gcc9` failures seem unrelated to CUDA.

**Comment by fwyzard** [comment]
@smuzaffar can we merge this before https://github.com/cms-sw/cmsdist/pull/6523 ?

**Comment by smuzaffar** [comment]
+externals
looks good to go

**Pull request merged**
