### PR TITLE
Rivet 2.6.1 + Yoda 1.7.4

### PR DESCRIPTION
**Pull request by mseidel42**
Open issue with loading library, see https://github.com/cms-sw/cmsdist/issues/3679
* RivetAnalyzer does not work on slc6, works only on slc7
* ParticleLevelProducer works on ~~slc6~~+slc7

--> acceptable as slc6 will be phased out?

Other fixes:
* made rivet available in python so that rivet scripts work again (this should be fixed in previous releases also)
* asciidoc fails to compile documentation within CMSSW environment --> deactivated in configure script

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
Hi, I see that the test fails on compilation warnings. Will fix that in a CMSSW pull request.

**Comment by smuzaffar** [comment]
workflow 1325.7 also fails due to 'static TLS' issue.

**Comment by mseidel42** [comment]
Ah, I see. We run the Rivet-based ParticleLevelProducer for NanoAod there... So no reliable behavior on slc6 :(

**Comment by xjanssen** [comment]
What's missing for this PR ?

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
@smuzaffar Do you understand why it runs in 10_5 now? Is it using slc7 as default, or did something else change?

**Comment by smuzaffar** [comment]
yes, production arch is slc7 now but we still have slc6 for 10.5.X. Once this tests is done then I will trigger it for slc6 too.

**Comment by smuzaffar** [comment]
by the way, there is Rivet 2.6.2 and Yoda 1.7.4 available. Should we try to bump the versions here?

**Comment by xjanssen** [comment]
ok, good because if the test succeed we could try to jump directly to the latest release of Rivet (2.6.2) and also Yoda 1.7.4 that are available

**Comment by xjanssen** [comment]
oops crossing, the answer is yes

**Comment by mseidel42** [comment]
Ok, I updated both. It probably does not improve anything wrt the slc6 problem

**Comment by smuzaffar** [comment]
please test
rivet 2.6.1 + yoda 1.7.1 looks good for slc7 and as expected it fails for slc6

**Comment by mseidel42** [comment]
Strange, works for me?!

```
mseidel@lxplus030 ..idel/CMSSW_dev/Rivet/CMSSW_10_5_0_pre1 % rivet --version
rivet v2.6.2
```

**Comment by smuzaffar** [comment]
The error we are getting is [a]. Looks like Rivet is do not recognize `--with-gsl` option [b]

[a]
```
In file included from pluginCMS/CMS_2018_I1690148.cc:12:0:
../include/Rivet/Math/MatrixDiag.hh:7:10: fatal error: gsl/gsl_vector.h: No such file or directory
 #include "gsl/gsl_vector.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

[b]
```
+ ./configure --disable-silent-rules --prefix=/build/muz/rivet/cc6/tmp/BUILDROOT/fab1d9ecc88f4241ac05c826ebab845b/opt/cmssw/slc6_amd64_gcc700/external/rivet/2.6.2 --with-hepmc=/build/muz/rivet/cc6/slc6_amd64_gcc700/external/hepmc/2.06.07-omkpbe2 --with-fastjet=/build/muz/rivet/cc6/slc6_amd64_gcc700/external/fastjet/3.3.0-omkpbe --with-gsl=/build/muz/rivet/cc6/slc6_amd64_gcc700/external/gsl/2.2.1-omkpbe2 --with-yoda=/build/muz/rivet/cc6/slc6_amd64_gcc700/external/yoda/1.7.4 --disable-doxygen --disable-pdfmanual --with-pic CXX=/build/muz/rivet/cc6/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/g++ CPPFLAGS=-I/include
configure: WARNING: unrecognized options: --with-gsl
```

**Comment by mseidel42** [comment]
Ups, it seems they removed the GSL dependence in 2.6.x while we (in fact: it was me) wrote an analysis that needs the GSL `Eigensystem`, developed in 2.5.4 and included then in 2.6.2...

Maybe they have GSL installed system-wide on their test machine so that it passed their validation. I will try to fix the problem and make a pull request to Rivet.

In the meanwhile, should we move back to Rivet 2.6.1 here?

**Comment by smuzaffar** [comment]
@intrepid42  , In order to get this merged we need to make sure that this works on slc6 too. It is OpenMP which is causing the Static TLS problem. I tested by disabling OpenMP on slc6 and failing workflow worked. Should we conditionally disable openmp for slc6 and continue with integration?

```
case %{cmsplatf} in
  slc6*) sed -i -e 's#^ *OPENMP_CXXFLAGS=.*#OPENMP_CXXFLAGS=#' configure ;;
easc
```

**Comment by mseidel42** [comment]
Thanks a lot for figuring that out!

**Comment by xjanssen** [comment]
see my comment, Yoda 1.7.1 maybe to be used with Rivet 2.6.1, no ?

**Comment by mseidel42** [comment]
I will do a test run to see if it's backward-compatible

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
I think it works with Yoda 1.7.4. The RivetInterface runs a plugin and I get reasonable yoda and dat files.

There just seems to be some latex problem with slc7, so I cannot generate the final plots.

**Comment by mseidel42** [comment]
Update: the plotting problem seems to be caused by this:
```! LaTeX Error: File `SIunits.sty' not found.```

Whom do we need to contact for that?

**Comment by smuzaffar** [comment]
@intrepid42 , tests passed for both slc6 and slc7. Can you please a cmssw PR to fix these warnings 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4427/32898/build-logs/GeneratorInterface/RivetInterface/log.html

**Comment by mseidel42** [comment]
@smuzaffar Yes, please see https://github.com/cms-sw/cmssw/pull/25817

**Comment by smuzaffar** [comment]
+externals
FYI @fabiocos

**Comment by fabiocos** [comment]
+1

@smuzaffar I understand that this version now passes also the test on slc6 (contrary to what initially stated in the explanation of this PR). There is already a fix at CMSSW level for the compilation warning, so let's test this in the IB.

@intrepid42 we have a limited test in generatorInterface/RivetInterface, in case it could be expanded with more analyses testing more features, do you see this as interesting?

**Pull request merged**
