### PR TITLE
Added RecoTauTag-TrainingFiles V00-01-00

### PR DESCRIPTION
**Pull request by smuzaffar**
resolve https://github.com/cms-sw/cmsdist/issues/4455

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar thanks, launching the final cross check in cmssw, then we may merge both this and cms-sw/cmssw#25016

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@smuzaffar thanks, the test in cmssw is successfully, I move forward with the integration

**Comment by fabiocos** [comment]
@smuzaffar we need a backport of this in 10_2_X (for cms-sw/cmssw#25386) and 9_4_X

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care of it

**Pull request merged**
