### PR TITLE
[AARCH64][GCC10] Build with -march=armv8-a

### PR DESCRIPTION
**Pull request by smuzaffar**
Thsi change should only effect aarch64 builds

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc10

**Comment by Dr15Jones** [comment]
The actual problem is 
```
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-02-2300/src/TrackingTools/AnalyticalJacobians/src/AnalyticalCurvilinearJacobian.cc:49:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-02-2300/src/TrackingTools/AnalyticalJacobians/src/AnalyticalCurvilinearJacobianSSE.icc: In member function 'void AnalyticalCurvilinearJacobian::computeFullJacobian(const GlobalTrajectoryParameters&, const GlobalPoint&, const GlobalVector&, const GlobalVector&, const double&)':
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-02-2300/src/TrackingTools/AnalyticalJacobians/src/AnalyticalCurvilinearJacobianSSE.icc:51:22: error: 'hadd' was not declared in this scope; did you mean 'fadd'?
   51 |   tt = mathSSE::sqrt(hadd(tt, tt));
      |                      ^~~~
      |                      fadd
```

**Comment by Dr15Jones** [comment]
Looks like `hadd` is conditionally declared here

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DataFormats/Math/interface/SSEVec.h#L512-L514

**Comment by smuzaffar** [comment]
@Dr15Jones  I do not understand why this failed here. The changes here should only effect aarch64 builds. So cs8_amd64 should not fail ( at least cs8_amd64 IBs are not failing)

**Comment by Dr15Jones** [comment]
@smuzaffar it looks like something is preventing the declaration of `__SSE3__`

**Comment by smuzaffar** [comment]
ah right, the https://github.com/cms-sw/cmsdist/pull/7592/files#diff-9ae93e4d39c78dbb82f952da0248bf67d11ce362f51e329364779da933923564R13 is overriding COMPILER_CXXFLAGS . good catch I will fix this

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for alma8_amd64_gcc10

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
