### PR TITLE
Update pip to 10.0.1

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
This brings in new `flit` dependency and problem is that `flit` is not available for python2

**Comment by smuzaffar** [comment]
hold

**Pull request closed without merging**
