### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by davidlange6** [comment]
@vgvassilev - this seems related to your changes in root? [this is a non-modules build]

BeamHaloProducer: starting event generation ... 
terminate called after throwing an instance of 'edm::Exception'
  what():  An exception of category 'FatalRootError' occurred.
   Additional Info:
      [a] Fatal Root Error: @SUB=TCling::LoadPCM
ROOT PCM ../../lib/slc7_amd64_gcc700/SimDataFormatsValidationFormats_xr_rdict.pcm file does not exist

**Comment by vgvassilev** [comment]
Likely, I will have to debug it.

**Comment by mrodozov** [comment]
please test
not sure if the fix is in the new commits but lets get them anyway

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by davidlange6** [comment]
hi @mrodozov - @vgvassilev and I were working on this - his PR to the root repo looks like it fixes this issue. Its merged in the root master now. Could you update to the more recent master and try again

(https://github.com/root-project/root/pull/4277)

**Comment by smuzaffar** [comment]
closing in favor of #5170

**Pull request closed without merging**
