### PR TITLE
fix EvtGen data path

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
please test

**Comment by smuzaffar** [comment]
CMSSW 11.3 and 12.0 are using evtgen 2.0 , so I guess this fix should be backported to those release cycles too .... right @mkirsano

**Comment by mkirsano** [comment]
In principle yes, but this is not very critical as in many cases the CMS specific data files are used

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
