### PR TITLE
update python packages and xtensor

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
unit test fixed by cms-sw/cmssw#26475
I'd suggest we merge both after the trivial tests pass on both @fabiocos

**Comment by davidlange6** [comment]
(correction, I don't mean to suggest rerunning tests on the cmsdist PR - that takes all night for just checking unit test)

**Comment by fabiocos** [comment]
@davidlange6 what about https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/pip/py2-deepdish.file ? At this point I would say it is not needed either, am I correct? Probably it does not harm as it is used if the entry is present in the requirements file

https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/pip/cmsdist_packages.py#L4

and you have removed it...

**Comment by fabiocos** [comment]
@mrodozov FYI I would like merge this for next IB (with cms-sw/cmssw#26475)

**Comment by mrodozov** [comment]
@fabiocos go ahead

**Comment by mrodozov** [comment]
IBs are building

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by mrodozov** [comment]
I'm going to put condition for numpy as the 1.16.2 doesn't build on arm
 
```
00:21:04 numpy/core/src/npymath/npy_math_internal.h.src: In function 'npy_cacoshf':
00:21:04 numpy/core/src/npymath/npy_math_internal.h.src:482:12: internal compiler error: Segmentation fault
00:21:04 return @kind@@c@(x, y);
```

**Comment by davidlange6** [comment]
interesting -  (actually the numpy release notes talk about improved support for arm)

**Pull request merged**
