### PR TITLE
[ROOT6] Update ROOT to tip of master branch

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
I am looking into the failures

**Comment by aandvalenzuela** [comment]
Just as an update on this topic, I think the failures in testing could be related to the recent changes in ROOT `graf2d/gpad/src/TCanvas.cxx` (commits [d3a5e48e9e85aa08b92770ed05fb4f3a704cde80](https://github.com/root-project/root/commit/d3a5e48e9e85aa08b92770ed05fb4f3a704cde80) and [771c44692bcbcb8f31799d044d50c3675e785de0](https://github.com/root-project/root/commit/771c44692bcbcb8f31799d044d50c3675e785de0)). I am testing those changes separately.

FYI, @linev (just in case you have any thoughts on that)

**Comment by linev** [comment]
@aandvalenzuela 

Can you identify which commit make a problem?
And can you test changes before I commit them to ROOT master?

**Comment by linev** [comment]
@aandvalenzuela 
One more question - are all tests running in batch mode? 
With '-b' flag?

**Comment by smuzaffar** [comment]
please test

lets re-run the tests (just to make sure the failure is consistent )

**Comment by smuzaffar** [comment]
> @aandvalenzuela One more question - are all tests running in batch mode? With '-b' flag?

@linev , I think these tests run in batch mode. Note that these tests are not running `root` executable directly but root libs are loaded via `cmsRun` application. Tests fail in https://github.com/cms-sw/cmssw/blob/master/CommonTools/TrackerMap/src/TrackerMap.cc#L1834-L2123 where we create a  TCanvas object https://github.com/cms-sw/cmssw/blob/master/CommonTools/TrackerMap/src/TrackerMap.cc#L2017

I am trying to build cmssw part in debug mode to see where exactly the crash happens

**Comment by aandvalenzuela** [comment]
Hi! I am reverting the commits that modify the canvas at https://github.com/cms-sw/cmsdist/pull/8597 to identify which one caused the issue

**Comment by smuzaffar** [comment]
@linev , so the failure occurs at https://github.com/cms-sw/cmssw/blob/master/CommonTools/TrackerMap/src/TrackerMap.cc#L1181 as 
```
TPaletteAxis *realPalette = (TPaletteAxis *)StripMap->GetListOfFunctions()->FindObject("palette");
```
could not find the `palette` function object and returned `0`. Any idea if there was any change in TH2Poly/TH2 class which could have caused this

**Comment by linev** [comment]
Now I see a reason. Problem appears by this commit from Olivier @couet:

https://github.com/root-project/root/commit/43b0d6ed5f8c9035d580170462a4437ed5326afc

We decide to use "col" draw option as default for `TH2` and `TH3`.
And there is logical failure when handling TH2Poly draw options here:

https://github.com/root-project/root/blob/master/hist/histpainter/src/THistPainter.cxx#L4367

I will provide fix soon.

**Comment by linev** [comment]
Hi @aandvalenzuela 

I prepare PR for handling draw options for `TH2Poly` class.

https://github.com/root-project/root/pull/13267

Does it solves all your problems? Or there other crashes - not connected with `TH2Poly` class?

Your PR #8597 will not solve the problem.

**Comment by aandvalenzuela** [comment]
Hi @linev,
PR https://github.com/cms-sw/cmsdist/pull/8597 was only for reverting individual commits and run the tests.
All the tests were failing at the same point, so I will open a separate PR once https://github.com/root-project/root/pull/13267 is merged. Thanks for the fix!

**Comment by linev** [comment]
But does my fix helps for all cases? I cannot check it myself.

And when do you want to have this fix? Olivier @couet is now in vacations - he will be back next week.

**Comment by aandvalenzuela** [comment]
I am opening a PR to test https://github.com/root-project/root/pull/13267 and check if it fixes all the cases

**Comment by iarspider** [comment]
please close

superseeded by #8609

**Pull request closed without merging**
