### PR TITLE
comp.pre slc5_amd64_gcc461 reqmgr

### PR DESCRIPTION
**Pull request by zdenekmaxa**
ReqMgr update to pull WMCore 0.9.64 tag

### CODE REVIEW

**Comment by dballesteros7** [comment]
@zdenekmaxa The current spec file for reqmgr is using a specific branch of WMCore, this needs to be changed in this pull request to point back to master plus the update in the version.

**Comment by zdenekmaxa** [comment]
@dballesteros7, this pull request is supposed to fetch 0.9.64, which, AFAIK, is not a branch anymore.

**Comment by dballesteros7** [comment]
Yes, but look at:

https://github.com/zdenekmaxa/cmsdist/blob/d02d2a3eb473e9f6e2d8549c89b85d0c3eedbfb9/reqmgr.spec#L6

It is using the size-per-evt-fix branch + 0.9.64 tag which doesn,t exist, it needs to be:

Source: git://github.com/dmwm/WMCore.git?obj=master/%{realversion}&export=%n&output=/%n.tar.gz

**Comment by geneguvo** [comment]
Hey guys,
I'm going to take both reqmgr.spec and reqmgr2.spec from what was it CVS HEAD, then will update their versions to 0.9.64. Would it be ok? or should I use 0.9.65? please let me know ASAP.

**Comment by dballesteros7** [comment]
There is no difference for the ReqMgr between 0.9.64 and 0.9.65 so the former is ok.

**Comment by zdenekmaxa** [comment]
> It is using the size-per-evt-fix branch + 0.9.64 tag which doesn,t exist, it needs to be:
> Source: git://github.com/dmwm/WMCore.git?obj=master/%{realversion}&export=%n&output=/%n.tar.gz

oh yes, I missed that, thanks.

**Comment by zdenekmaxa** [comment]
closing, superseded by #16

**Pull request closed without merging**
