### PR TITLE
TBB - add cmake config in the install for DD4Hep

### PR DESCRIPTION
**Pull request by mrodozov**
please test
see this: https://github.com/AIDASoft/DD4hep/pull/675
this is the shortest way to add the config for DD4Hep

### CODE REVIEW

**Comment by smuzaffar** [comment]
@makortel , @Dr15Jones  there is newer version of TTB 2020_U2 . Any objection on including that in to cmssw 11.2.X?

**Comment by smuzaffar** [comment]
@mrodozov , I would suggest to use cmake to build TBB too

**Comment by Dr15Jones** [comment]
@smuzaffar there had been discussion in the TBB GitHub page about weaknesses in the cmake handling in tbb.

**Comment by Dr15Jones** [comment]
@smuzaffar I'm all for using a newer version as long as our code compiles with it :). [They are planning on removing interfaces in the future which we are making use of right now]

**Comment by smuzaffar** [comment]
Thanks @Dr15Jones , @mrodozov pls update tbb in separate pr and keep on using the make instwad of cmake

**Comment by mrodozov** [comment]
closing this, see 
https://github.com/cms-sw/cmsdist/pull/5961

**Pull request closed without merging**
