### PR TITLE
Update Geant4 to 11.0.9 (g4vecgeom IB)

### PR DESCRIPTION
**Pull request by iarspider**
Resolves cms-externals/geant4#64

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar merge conflict?

**Comment by smuzaffar** [comment]
> @smuzaffar merge conflict?

no, there was a [typo](https://github.com/cms-sw/cmsdist/commit/439a830c3b286e20fd7ed2043c5f5f99113c5f3b) which should be fixed now

**Comment by smuzaffar** [comment]
looks good

**Pull request merged**
