### PR TITLE
updates xrootd to 4.4.1

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
please test

**Comment by smuzaffar** [comment]
@iahmad-khan , this does not look right .... https://github.com/cms-externals/xrootd/commits/cms/v4.4.0 has commits from July while your update https://github.com/cms-externals/xrootd/commits/cms/v4.4.1 has commits from April.

**Comment by smuzaffar** [comment]
correct PR is https://github.com/cms-sw/cmsdist/pull/2555

**Comment by smuzaffar** [comment]
-externals

**Pull request closed without merging**
