### PR TITLE
Update Yoda and Rivet vesions and source location

### LINKED ISSUE #5587: Update YODA and Rivet
assign generators
we are updating yoda and rivet recipes (see https://github.com/cms-sw/cmsdist/pull/5586)
as we had to patch yoda (see https://github.com/cms-sw/cmsdist/pull/5531/files , yoda file)
and we thought let's ask if we should update to newer rivet and yoda versions

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #5587 
change the sources to gitlab.com
reason - to have forks on cms-externals if we need patches (we will need for ROOT6 IBs) and
suggest contributions
also versions update

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@slava77 @intrepid42 there are differences in comparison , please advise

**Comment by mrodozov** [comment]
Resolves: #5587

**Comment by mseidel42** [comment]
Hi Mircho, the differences don't seem to be related to Rivet.

Unit tests are fine and apparently no differences in NanoAod?

**Comment by mrodozov** [comment]
looks like it, yes. would you say it's safe to get them in this case ?

**Comment by mseidel42** [comment]
Hi, I had another look at the [nanoAod DQM plots](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-02-21-1100+681573/35186/files/1325.7_TTbar_13_94Xv2NanoAODINPUT+TTbar_13_94Xv2NanoAODINPUT+NANOEDMMC2017_94XMiniAODv2+HARVESTNANOAODMC2017_94XMiniAODv2/), and everything looks fine to me.

So yes, please go ahead with the update :)

**Comment by mrodozov** [comment]
+externals
it's up to the release manager now

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc820
lets run final tests for non-x86 archs

**Comment by smuzaffar** [comment]
looks good

**Pull request merged**
