### PR TITLE
Updated rootnext to tip of branch v6-14-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
Test if latest commits (3 more since the last test) on 6-14 are fixing existing issues

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by yamaguchi1024** [comment]
Let's try
```
-DLLVM_BUILD_TYPE=Release \
```

**Comment by smuzaffar** [comment]
please test

**Pull request closed without merging**
