### PR TITLE
[ROOT618] Update root to 6.18.04 for 11.0.X

### PR DESCRIPTION
**Pull request by smuzaffar**
FYI @fabiocos , this should bring ROOT 6.18.04 in to 11.0.X master

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar thank you, this is the moment to move forward, if everything looks ok I would go for the integration in tonight's IB

**Comment by fabiocos** [comment]
@smuzaffar I would say that the failures are unrelated to this PR, a timeout due to the long list of jobs to be run? No problem is seen neither in ROOT618 IBs nor in standalone tests...

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@smuzaffar @Dr15Jones I will devote tonight's IB to the update of ROOT, and integrate the other pending PRs in my to-do list into the next one tomorrow, so as we may have a clean reference depending only on ROOT change

**Comment by smuzaffar** [comment]
@fabiocos , lets merge it now so that I can fix any forward porting issues before the IB starts

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
