### PR TITLE
[14.0.X] Using consistent Eigen alignment settings

### PR DESCRIPTION
**Pull request by smuzaffar**
Backport of #9060 
It also contains changes from #9061 (which actually enable the vectorization package built of `lwtnn, opencv and pytorch`

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals 

@rappoccio, @antoniovilela  feel free to merge it for 14.0.X. This is needed to fix https://github.com/cms-sw/cmssw/issues/44188 issue

**Comment by smuzaffar** [comment]
type urgent

**Comment by perrotta** [comment]
urgent

**Comment by antoniovilela** [comment]
> +externals
> 
> @rappoccio, @antoniovilela feel free to merge it for 14.0.X. This is needed to fix [cms-sw/cmssw#44188](https://github.com/cms-sw/cmssw/issues/44188) issue

We need https://github.com/cms-sw/cmsdist/pull/9061 to go in first, correct?

**Comment by smuzaffar** [comment]
yes @antoniovilela . https://github.com/cms-sw/cmsdist/pull/9061 is ready to go in ( I am just waiting for the comparison results for the multi-arch IB)

**Comment by antoniovilela** [comment]
> yes @antoniovilela . #9061 is ready to go in ( I am just waiting for the comparison results for the multi-arch IB)

Thanks. Can the backport wait for the IB tests and be merged tomorrow? We will collect a few more PRs for the next 14_0 release (14_0_2).
@cms-sw/alca-l2

**Comment by smuzaffar** [comment]
@antoniovilela , https://github.com/cms-sw/cmsdist/pull/9061 is merged now and will be part of tonight's 23h00 IBs. Feel free to merge this for 14.0.X tomorrow morning before 11h00 IB

**Comment by antoniovilela** [comment]
> @antoniovilela , https://github.com/cms-sw/cmsdist/pull/9061 is merged now and will be part of tonight's 23h00 IBs. Feel free to merge this for 14.0.X tomorrow morning before 11h00 IB

Hi Shahzad, I might not make it before 11h (I am 4h behind). If I do not merge it tonight, feel free to merge it tomorrow morning.
Thanks.

**Comment by smuzaffar** [comment]
@antoniovilela , 14.1.X IBs look good. So I am merging it now for 14.0.X

**Comment by antoniovilela** [comment]
> @antoniovilela , 14.1.X IBs look good. So I am merging it now for 14.0.X

Thanks.

**Pull request merged**
