### PR TITLE
Advance to latest release of RecoBTag/CTagging data.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-data/RecoBTag-CTagging/commit/7a5db4187a1a8192e3b669b3de074553884a4a86

### CODE REVIEW

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

@degano 
comparisons never completed.
I'm not sure if it is a feature of the cmsdist jenkins tests or there was a glitch in the comparison step.

**Comment by slava77** [comment]
@cmsbuild please test
sigh, the last attempt faced massive github downtime

**Comment by ghost** [comment]
@slava77 I have accidentally merged this PR before the tests where actually completed. I reverted it and I've opened a new one here: #2106.
PS All the above tests failed due to a bug in the testing script, fixed now.

**Pull request merged**
