### PR TITLE
Add gcc toolfile with location of gcc plugin headers and library

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones @smuzaffar

**Comment by smuzaffar** [comment]
@gartung , does this only work for gcc7 and above? If yes then we should update the cmssw PR to only build it for gcc7 archs

**Comment by gartung** [comment]
It should work with any gcc. I just happened to make the change on the gcc7 branch.

**Comment by gartung** [comment]
I will add the gcc-plugin in its own spec so I do not need this toolfile.

**Pull request closed without merging**
