### PR TITLE
Vecgeom patch for 00.05.00

### PR DESCRIPTION
**Pull request by mrodozov**
Resolve: https://github.com/cms-sw/cmsdist/issues/4626

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
> Reco comparison results: 8 differences found in the comparisons

there is apparently nothing relevant related to the update.
Our MC tests with jenkins are only on about 20 sim events.
It looks like the fix for the uninit variable has fairly small impact (at least not affecting every event).

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
