### PR TITLE
revert rivet on gcc820

### PR DESCRIPTION
**Pull request by mrodozov**
Rivet update is breaking 820 and 900 IBs, reverting after this PR is finished

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
@mrodozov this will break CMSSW, as it is seen, unless also cms-sw/cmssw#27610 is reverted. Which is the rivet build problem on gcc820? Unless it cannot be fixed quickly I prefer to roll back everything and integrate it again when the issue is understood and fixed (@intrepid42 FYI)

**Comment by mseidel42** [comment]
Hi, do you have the failed build logs for me? Unfortunately, it is now impossible to tell me **yesterday**, so please give me at least a morning to look at it, to avoid back-and forth in cmssw (https://github.com/cms-sw/cmssw/pull/27787) and gcc700 (https://github.com/cms-sw/cmsdist/pull/5159)

**Comment by fabiocos** [comment]
@intrepid42 I do not want to put pressure on you, but I doubt this development is desperately urgent. There are other unrelated reasons for which we might need to have in a short time a pre6 version, so I need to have a clean IB.

**Comment by fabiocos** [comment]
So unless the fix is trivial and can be done before the week-end I prefer to reset the situation, and let you prepare a new version with calm.

**Comment by mseidel42** [comment]
I found the build log [here](https://cmssdt.cern.ch/jenkins/job/build-any-ib/79713/console), and it looks like the fastjet-contrib dropped out of the requirements. It was there in https://github.com/cms-sw/cmsdist/pull/5107... Fix is here: https://github.com/cms-sw/cmsdist/pull/5160

```
00:31:38 * The action "build-external+rivet+3.0.1" was not completed successfully because Failed to build rivet. Log file in /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/external/rivet/3.0.1/log. Final lines of the log file:
00:31:38 configure: Found fastjet header directory at /build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/fastjet/3.3.0-pafccj/include
00:31:38 checking for fastjet-config... /build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/fastjet/3.3.0-pafccj/bin/fastjet-config
00:31:38 checking FastJet version using fastjet-config... 3.3.0
00:31:38 configure: FastJet lib flags: -Wl,-rpath,/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/fastjet/3.3.0-pafccj/lib -lm -L/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/fastjet/3.3.0-pafccj/lib -lfastjettools -lfastjet -lfastjetplugins -lsiscone_spherical -lsiscone -lfastjetcontribfragile -lfastjettools
00:31:38 configure: FastJet ld flags: -L/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/fastjet/3.3.0-pafccj/lib
00:31:38 checking fastjet/D0RunIIConePlugin.hh usability... yes
00:31:38 checking fastjet/D0RunIIConePlugin.hh presence... yes
00:31:38 checking for fastjet/D0RunIIConePlugin.hh... yes
00:31:38 checking fastjet/TrackJetPlugin.hh usability... yes
00:31:38 checking fastjet/TrackJetPlugin.hh presence... yes
00:31:38 checking for fastjet/TrackJetPlugin.hh... yes
00:31:38 checking fastjet/contrib/SoftDrop.hh usability... no
00:31:38 checking fastjet/contrib/SoftDrop.hh presence... no
00:31:38 checking for fastjet/contrib/SoftDrop.hh... no
00:31:38 configure: error: Required FastJet Contrib headers were not found: did you install FastJet Contrib?
```

**Pull request merged**
