### PR TITLE
Add OpenMP support for ROCm

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
Could you add something about the motivation for adding OpenMP support?

**Comment by fwyzard** [comment]
> Could you add something about the motivation for adding OpenMP support?

@VinInn is using it for local tests, I though we could add it in CMSSW.

**Comment by makortel** [comment]
So what does it do exactly? Add an ability to use OpenMP offloading to AMD GPUs? Or use OpenMP as "HIP backend"? Or something else?

**Comment by fwyzard** [comment]
> So what does it do exactly? Add an ability to use OpenMP offloading to AMD GPUs? Or use OpenMP as "HIP backend"? Or something else?

According to https://rocm.docs.amd.com/en/latest/about/compatibility/openmp.html , it should support OpenMP offloading to AMD GPUs.

**Comment by fwyzard** [comment]
Update from @VinInn: the OpenMP packages are required to compile any source that uses `#pragma omp ...` with `hipcc`.

**Comment by fwyzard** [comment]
Superseded by #9050 .

**Pull request closed without merging**
