### PR TITLE
[geant4_vecgeom] Update Geant4 to 11.0, G4EMLOW to 8.0, G4PARTICLEXS to 4.0

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_12_3_G4VECGEOM_X

**Comment by iarspider** [comment]
please test for CMSSW_12_3_G4VECGEOM_X

**Comment by iarspider** [comment]
please test for CMSSW_12_3_G4VECGEOM_X

**Comment by smuzaffar** [comment]
+externals
For special geant4 vecgeom ib

**Pull request merged**
