### PR TITLE
[rust] Delete .git files which are breaking slc7 builds

### PR DESCRIPTION
**Pull request by smuzaffar**
This should fix slc7 builds

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc11

**Comment by fwyzard** [comment]
Why do we even have Rust in cmsdist ?

**Comment by smuzaffar** [comment]
`rust` is needed by `py3-cryptography` which is needed by `py3-poetry` ( a python packaging and deps managment tool required by many python packages) :-(

**Comment by smuzaffar** [comment]
+externals

rust builds for both el8 and slc7 now

**Pull request merged**
