### PR TITLE
Include Boost.MPI

### PR DESCRIPTION
**Pull request by fwyzard**
Include Boost.MPI:
  - add a dependency on OpenMPI
  - build boost with MPI support
  - add a new boost_mpi tool

Update OpenMPI to version 2.1.4.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
The build failed with

* The action "fetch-external+openmpi+2.1.4" was not completed successfully because Unable to download http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.4.tar.gz

however the link works fine for me ?

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
On a second look, there is this in the log:

> Error while downloading http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.4.tar.gz: <urlopen error [Errno 1] _ssl.c:492: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

but I don't get any such problem locally, nor on lxplus.
It also works with https, but maybe that can help on the build machine ?

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
I have updated the source URL to follow the redirect, let's see if that helps...

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
The download failed again with
```
Error while downloading https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.4.tar.gz: <urlopen error [Errno 1] _ssl.c:492: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
```

However I can download it without problems on a random lxpus6 or lxplus7 machine:
```
$ curl https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.4.tar.gz -o openmpi-2.1.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.9M  100 13.9M    0     0  5368k      0  0:00:02  0:00:02 --:--:-- 5959k
$ md5sum openmpi-2.1.4.tar.gz 
b109e64641041c97ed6909325b65ec0c  openmpi-2.1.4.tar.gz
```

@smuzaffar, @gudrutis, @mrodozov, can you look into why the download fails on the build machine ?

**Comment by mrodozov** [comment]
I'll look into it

**Comment by fwyzard** [comment]
@mrodozov did you find any problems with the build ?

**Comment by mrodozov** [comment]
I'm trying to circumvent it. I think it's a urllib2 related issue which cmsBuild uses and there are two ways - I get the tar, put it somewhere where we can get it from (say cms-externals repo) or try to substitute urllib2 calls with urllib3 + requests which I can't say how long it would take. I'm thinking trying the fist option first

**Comment by fwyzard** [comment]
Do you have any idea why the build instructions I am using [1] work fine on lxplus7 ?

[1]
```bash
git clone -b V00-32-XX git@github.com:cms-sw/pkgtools.git PKGTOOLS
git clone -b IB/CMSSW_10_3_X/gcc700_openmpi git@github.com:fwyzard/cmsdist.git CMSDIST
PKGTOOLS/cmsBuild -a slc7_amd64_gcc700 --repository=cms.week1 -c CMSDIST -i BUILD --builders 4 -j 32 build openmpi
```
I get
```
Bootstrapping cmsBuild area.
Done. Setup log can be found in /tmp/fwyzard/BUILD/tmpX/bootstrap.log.
Generated cache: external+gcc+7.0.0-omkpbe2
Generated cache: external+autotools+1.3-omkpbe2
Generated cache: external+openmpi+2.1.4
Package external+openmpi+2.1.4 requested.
This will bring in also the following packages: 
external+autotools+1.3-omkpbe2 (4974eadf9aa1ccd67045a895ccb42ac3)
external+gcc+7.0.0-omkpbe2 (8ed230187c2a06a277ca03ddf192b0cd)
Starting to process package external+openmpi+2.1.4
Checking if openmpi is cached.
Package external+openmpi+2.1.4 not found in repository. Queuing for build.
Dependencies for external+openmpi+2.1.4: ['install-external+gcc+7.0.0-omkpbe2', 'install-external+autotools+1.3-omkpbe2', 'fetch-external+openmpi+2.1.4']
Fetching sources for openmpi
Starting to process package external+gcc+7.0.0-omkpbe2
Checking if gcc is cached.
gcc is available from remote repository "cms.week1". Not building. Downloading and installing...
Package external+gcc+7.0.0-omkpbe2 found in repository
Starting to process package external+autotools+1.3-omkpbe2
Checking if autotools is cached.
autotools is available from remote repository "cms.week1". Not building. Downloading and installing...
Package external+autotools+1.3-omkpbe2 found in repository
Done fetching https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.4.tar.gz
(<function fetchSources at 0x7f43efd16ed8>, <Package name=openmpi>, <scheduler.Scheduler object at 0x7f43efa35250>) done
Creating directory /tmp/fwyzard/BUILD/BUILD/slc7_amd64_gcc700/external/openmpi/2.1.4 if not existing.
Building openmpi. Log can be found in /tmp/fwyzard/BUILD/BUILD/slc7_amd64_gcc700/external/openmpi/2.1.4/log.
...
```

**Comment by fwyzard** [comment]
Ah, lxplus7 (CC7) have python 2.7, while lxplus6 (SLC6) have python 2.6 - and indeed with the latter I can reproduce the problem.

So it seems a solution could be to move the build host to CC7 (in fact, I didn't know we could build CC7 packages on SLC6).

Or at least, install and use python 2.7 for `cmsBuild`.

**Comment by fwyzard** [comment]
It seems that using the new source address *without* https does not incur in the urllib issue... let's try if it builds

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by mrodozov** [comment]
yes this works, although I tried with http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.4.tar.gz and it failed, yet it's http. There is a difference with the urllib2 on lxplus & on cmsbuild () machine somewhere, or with the openssl used.

**Comment by fwyzard** [comment]
http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.4.tar.gz has a redirect to https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.4.tar.gz, which in turns has a redirect to https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.4.tar.gz - so it picks up HTTPS along the way.

Instead, http://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.4.tar.gz stays HTTP, wihout any redirects.

And yes, on lxplus6 I do get the same error as the build machine.

**Comment by fabiocos** [comment]
@fwyzard @mrodozov @Dr15Jones this is not changing the boot version as far as I can see, just its interplay with OpenMPI , so we should not expect (besides the PR test) any effect on CMSSW. Was this tool tested somewhere else (devel IB for instance)?

**Comment by fwyzard** [comment]
We are using it in the Patatrack release, but there is very little validation there, apart from the pixel tracking workflows.

**Comment by fabiocos** [comment]
@fwyzard as at this point I want to build CMSSW_10_3_0_pre2 without further delays, I would prefer to merge it in the week-end, unless Mircho has further doubts or objections

**Comment by fwyzard** [comment]
@fabiocos sure, delaying this to pre3 is not a problem for us.

**Comment by mrodozov** [comment]
I have no objections about merging this.

**Comment by Dr15Jones** [comment]
I have no objection in merging it in pre3.

**Comment by fabiocos** [comment]
@ggovi FYI

**Comment by davidlange6** [comment]
merge




On 20 Aug 2018, at 08:54, Fabio Cossutti <notifications@github.com<mailto:notifications@github.com>> wrote:


@ggovi<https://github.com/ggovi> FYI

**Pull request merged**
