### PR TITLE
backported openmpi and share changes in to 93X

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #3405
- fix openmpi build: enable mpi-cxx
- updated sherpa to 2.2.4 and fixes for openmpi

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by davidlange6** [comment]
+1

**Pull request merged**
