### PR TITLE
XrootD - backport 531 from devel to master

### LINKED ISSUE #7179: Bump xrootd to 5.3.x
We are still using 4.12, it's high time to move on! :)

On a serious note, fwlite can not open CERN EOS files througg TFile::Open("root://eoscms.cern.ch/..." because of that. I assume cmsRun has the same problem.

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #7179 
this is a backport of https://github.com/cms-sw/cmsdist/pull/7180

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- pull_request = cms-sw/cmssw#34991, cms-sw/cmssw#35481
- enable_test = threading

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
enable threading

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
hold

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for cc8_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping

**Comment by smuzaffar** [comment]
please test cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for CMSSW_12_1_ROOT6_X

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc11

**Comment by smuzaffar** [comment]
please test for CMSSW_12_1_ROOT6_X

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc10

**Comment by smuzaffar** [comment]
+externals
looks good to go in

**Comment by smuzaffar** [comment]
this should be merged with https://github.com/cms-sw/cmssw/pull/34991 and https://github.com/cms-sw/cmssw/pull/35481
better to merge these just few minutes before the IB e.g. at 10h50 or 22h50

**Comment by smuzaffar** [comment]
hold
lets check with comp team if they have any concern over the xrootd 5.3 migration

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
unhold

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmssw#34991, cms-sw/cmssw#35481
- enable_test = threading

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
this should be merged along with cms-sw/cmssw#34991 cms-sw/cmssw#35481

**Comment by qliphy** [comment]
+1
thanks!

**Pull request merged**
