### PR TITLE
[ROOT628] Root update v6 28 00 patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
tests look good (2 unit tests are failing in IBs and other 2 are due to grid certificate issue on build node (not related to this PR))

**Comment by smuzaffar** [comment]
This is only for ROOT628 IBs

**Pull request merged**
