### PR TITLE
geant4 10.5 udpated for special GEANT4 branch

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@civanch , without vecgeom we get this type of error. I would suggest that we merge this in to GEANT4 IB and build and IB so that you can provide fixes for this via CMSSW_10_3_GEANT4_X branch.

**Comment by civanch** [comment]
@smuzaffar , thanks!

**Comment by smuzaffar** [comment]
@civanch , FTI, new geant4 version is now available in CMSSW_10_3_GEANT4_X_2018-09-28-1600 IB. We will build these IBs on demand (e.g. when there are fixes for geant4 or cmssw ).

**Comment by civanch** [comment]
@smuzaffar , unfortunately, I cannot do 'scram b' due to the same problem, so should provide a new version of Geant4 coherent with new version of VecGeom.

**Comment by civanch** [comment]
@smuzaffar , it turned out that G4 postpone git migration and promptly provide a new G4 version:

https://cernbox.cern.ch/index.php/s/6JhoLIeTQP7pilI 
the same tar at afs: ~vnivanch/public/geant4-10-04-ref-08/geant4-10-04-ref-08.tar.gz

VecGeom reference version coherent with this version of Geant4 is : 
https://gitlab.cern.ch/VecGeom/VecGeom/tree/v01.00.01

**Comment by civanch** [comment]
@smuzaffar , I tried out CMSSW_10_3_GEANT4_X_2018-10-02-1100 but fail to build because 

/cvmfs/cms-ib.cern.ch/nweek-02544/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lusolids

likely this means that vecgeom is not seen by linker.

**Comment by smuzaffar** [comment]
@civanch , can you please edit config/toolbox/slc6_amd64_gcc700/tools/selected/vecgeom.xml file and remove `<lib name="usolids"/>` and rebuild? 
Looks like new vecgeom do not build libusolids.a (may be they have merged libusolids and libvecgeom)

**Comment by civanch** [comment]
@smuzaffar , if I change vecgeom.xml as you propose and apply a minor fix #24805 everything is working fine. #24805 will be likely merged when CMSSW_10_4 will be available.

**Pull request merged**
