### PR TITLE
Updated root to tip of branch v6-30-00-patches

### PR DESCRIPTION
**Pull request by iarspider**
Changes: https://github.com/root-project/root/compare/bd1b2a6bc8..86805a0e3e

### CODE REVIEW

**Comment by iarspider** [comment]
Changes are mostly in jsroot

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@makortel , https://github.com/root-project/root/compare/bd1b2a6bc8..86805a0e3e are the root change on top of root 6.30 commit we are using.  I do not see any thing interesting for CMS in this diff (mostly GUI, root CI and JSROOT changes). Should we freeze root 6.30 in 14.1.X or keep it up with the latest root 6.30 changes?

**Comment by iarspider** [comment]
please test

**Comment by makortel** [comment]
@smuzaffar 

> https://github.com/root-project/root/compare/bd1b2a6bc8..86805a0e3e are the root change on top of root 6.30 commit we are using. I do not see any thing interesting for CMS in this diff (mostly GUI, root CI and JSROOT changes). 

I agree.

> Should we freeze root 6.30 in 14.1.X or keep it up with the latest root 6.30 changes?

Umm, haven't we usually continued updating root in the development release cycle? We can of course take a pause in the updates until something potentially interesting comes backported to 6.30.

**Comment by smuzaffar** [comment]
> Umm, haven't we usually continued updating root in the development release cycle?

we do but not very frequently

> We can of course take a pause in the updates until something potentially interesting comes backported to 6.30.

I would suggest to lets hold this update to let the other big changes (e.g cuda/eigen/tf xla) to sync in first. We can check root 6.30 update next week

**Comment by makortel** [comment]
Sounds good.

**Comment by smuzaffar** [comment]
closing it for now, will recheck next week if there are any root 6.30 updates available

**Comment by aandvalenzuela** [comment]
Hello @smuzaffar,

Comparison for this week is https://github.com/root-project/root/compare/bd1b2a6bc8..a3d817e5d8
Should we update?

Thanks,
Andrea

**Pull request closed without merging**
