### PR TITLE
Python package updates 

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , looks like now it is missing chardet
```
Traceback (most recent call last):
  File "/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/cms-bot/./report-pull-request-results", line 8, in <module>
    import requests
  File "/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc530/external/py2-pippkgs/5.0-cms/lib/python2.7/site-packages/requests/__init__.py", line 44, in <module>
    import chardet
ImportError: No module named chardet
```

**Comment by davidlange6** [comment]
hum, i thing this is requests no longer bundling stuff it depends on directly (good) - seems the list will be chardet, idna, certifi - too bad that I start to have unit tests that catch these things..

**Comment by davidlange6** [comment]
ok, I think I got all the packages that requests now depends on - but one more commit needed

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
