### PR TITLE
fastjet 3.4.1 and fastjet-contrib 1.051

### PR DESCRIPTION
**Pull request by smuzaffar**
Update [fastjet 3.4.1](https://fastjet.fr/all-releases.html) with bug fixes
```
- Resolved MAJOR BUG that arose with full thread-safety enabled (reported by Ludo Scyboz),
where PseudoJet::reset_momentum and PseudoJet::operator= failed to update internally cached
values of phi() and rap(). In some instances related issues could also lead to race conditions.
- eliminated NaN from square-root of negative mean areas in background estimation (now returns zero) 
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@perrotta @rappoccio is it too late to get this in for 13.1.X ? 
@makortel , this version of fastjet has a bug fix for thread safety but I am not sure if we are affected by this

**Comment by perrotta** [comment]
@smuzaffar I intended to build pre4 ~now
Since I did not start it yet, it is not (yet) too late
If the inclusion is safe, I think we can merge it and start building pre4 right after: just decide quickly, feel free to consider "+orp" here

**Comment by smuzaffar** [comment]
+externals
PR tests look good, DQM/Reco comparison show differences in MessageLogger, so let get this in then.

**Comment by smuzaffar** [comment]
Thanks @perrotta , I have merged it now. If it helps then I can start an IB too

**Comment by perrotta** [comment]
> If it helps then I can start an IB too

Do you think it is needed?
I would start the build o pre4 now anyhow, but we can still have a look at the results of the IB tests before the uploads

**Comment by smuzaffar** [comment]
11h00 IB does not contain this change, so you have to wait for 23h00 IB results. If this is fine then no need to build an extra IB

**Comment by makortel** [comment]
> this version of fastjet has a bug fix for thread safety but I am not sure if we are affected by this

Good question. I don't recall seeing fastjet-specific thread safety problems in a long time, but I don't expect our testing to be able catch all possible problems :) Since the comparisons were clean, I'd be tempted to backport these fixes to 13_0_X (but maybe after 13_1_0_pre4 has been validated?

**Pull request merged**
