### PR TITLE
update root to version 6.26.10+patches

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #8396

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

unit test failure is known issue with root updates and this unit tests. As this tests creates a dev area and then mixes libs from old root and new root.

@perrotta , @rappoccio , following the recommendation here https://github.com/cms-sw/cmssw/issues/41246#issuecomment-1494964874 , this backported the latest root 6.26 changes in to 13.0.X. This is ready to go in, feel free to merge it

**Comment by francescobrivio** [comment]
urgent 

 - needed for a 13_0_3 to be used online as soon as possible

**Comment by perrotta** [comment]
+1
- According to https://github.com/cms-sw/cmsdist/pull/8421#issuecomment-1495367094 "unit test failure is known issue with root updates and this unit tests"
- Let have this merged in 13_0_X, so that we can build a CMSSW_13_0_3 with it if it will be decided so during the joint operation meeting of today

**Comment by perrotta** [comment]
@smuzaffar thank you for merging 
I would have done so anyhow before 1100: I was just waiting a bit in case the tests that you launched last would have finished before that. However, I agree with you that we can look at the results of those tests even when this PR is merged.

**Pull request merged**
