### PR TITLE
update t0 spec to 2.0.8

### PR DESCRIPTION
**Pull request by hufnagel**
updating the t0 spec to version 2.0.8

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to e70bee817885a38ae98e4886c63a96271e8914d3 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3113/test_e70bee8-20170620-202506.log" target="_blank">here</a>.

**Comment by hufnagel** [comment]
merge

**Comment by amaltaro** [comment]
ping

**Comment by amaltaro** [comment]
merge

**Pull request merged**
