### PR TITLE
[Geant4] Update vecgeom to 1.1.6 on G4 branch

### PR DESCRIPTION
**Pull request by mrodozov**
please test
in response to https://github.com/cms-externals/geant4/issues/45

### CODE REVIEW

**Comment by mrodozov** [comment]
Seems the GEANT4 IB doesn't include latest cmssw DD4Hep changes

**Comment by mrodozov** [comment]
test parameters:
- pull_requests = https://github.com/cms-sw/cmssw/pull/29055

**Comment by mrodozov** [comment]
please test

**Comment by civanch** [comment]
yes we checked privately and had the same problem. It may be resolved if GEANT4 IB will be rebuilt using current master.

**Comment by silviodonato** [comment]
please test with https://github.com/cms-externals/geant4/issues/45, https://github.com/cms-sw/cmssw/pull/29108

**Comment by silviodonato** [comment]
> yes we checked privately and had the same problem. It may be resolved if GEANT4 IB will be rebuilt using current master.

Do you mean we will get these errors until this PR is merged?

**Comment by mrodozov** [comment]
abort
cms-externals/geant4#45 is an issue, and this PR is the result :) I think Vladimir was explaining that the last Geant4 IB doesn't have some changes that are in cmssw and if we rebuild the IB to pick the changes and retry this PR will work

**Comment by civanch** [comment]
Yes, the problem unrelated to this PR

**Comment by civanch** [comment]
@mrodozov  explanation is correct.

**Comment by mrodozov** [comment]
right. I'm scheduling the Geant4 IB then

**Comment by silviodonato** [comment]
@mrodozov I think the plan is then:
- make a new Geant4 IB (11am IB?)
- test this PR
- wait for the new IB and IB test (11pm IB?)
- make 11_1_0_pre4_GEANT4 if everything is ok (tomorrow?).

Do you agree?

**Comment by mrodozov** [comment]
please test
I agree. The IB is already on cvmfs so lets retry

**Comment by silviodonato** [comment]
> please test
> I agree. The IB is already on cvmfs so lets retry

Great! Thanks!

**Comment by mrodozov** [comment]
abort
the test picked a PR which is not necessary

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
do we need https://github.com/cms-sw/cmssw/pull/29108 ?

**Comment by silviodonato** [comment]
> do we need [cms-sw/cmssw#29108](https://github.com/cms-sw/cmssw/pull/29108) ?

It is not necessary, but it will be part of pre4_GEANT4.

**Comment by civanch** [comment]
I would afraid that if cms-sw/cmssw#29108 is merged here then later we may have problems, because it will stay on hold in master for non-negligble time.

**Comment by silviodonato** [comment]
> I would afraid that if [cms-sw/cmssw#29108](https://github.com/cms-sw/cmssw/pull/29108) is merged here then later we may have problems, because it will stay on hold in master for non-negligble time.

The idea was to use #29108 (a clone of #29077) only for the test.
We have already a commit in CMSSW (https://github.com/cms-sw/cmssw/tree/61e522225cab761ec911f816ab12d895e35474a6) that corresponds to CMSSW_11_1_0_pre4+#29077.
We can use that commit to make CMSSW_11_1_0_pre4_GEANT4.

**Comment by civanch** [comment]
Later, when CMSSW_11_1_0_pre4_GEANT4 will get green light, we should integrate in master #29108 (or any equivalent) together with new Geant4.

**Comment by silviodonato** [comment]
please test with cms-externals/geant4#45, cms-sw/cmssw#29108

**Comment by silviodonato** [comment]
please test

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#29108

**Comment by silviodonato** [comment]
@mrodozov @civanch I don't think https://github.com/cms-sw/cmssw/pull/29108 can solve the error

**Comment by mrodozov** [comment]
@silviodonato I'm digging into it and the file is there (in 1.1.6)
https://gitlab.cern.ch/VecGeom/VecGeom/blob/v1.1.6/VecGeom/base/Global.h
I'll have to setup manually both 1.1.5 and 1.1.6 and see what's wrong

**Comment by mrodozov** [comment]
@civanch @silviodonato
the VecGeom moved "some" (actually a lot of) headers into a new directory, called VecGeom.
https://gitlab.cern.ch/VecGeom/VecGeom/tree/v1.1.6/VecGeom
that was before just in
https://gitlab.cern.ch/VecGeom/VecGeom/tree/v1.1.6
for example see
https://gitlab.cern.ch/VecGeom/VecGeom/tree/v1.1.5
and then
https://gitlab.cern.ch/VecGeom/VecGeom/tree/v1.1.6 
and you'll notice the difference in folders.
I've added the missing change in the this particular place where it was failing in
TrackPropagation/Geant4e , adding the new prefix fixed that particular place but in general Geant4 now need to get this changes into Geant4 i.e. all VecGeom includes must adapt  
volumes/UnplacedBox.h -> VecGeom/volumes/UnplacedBox.h
volumes/UnplacedTube.h -> VecGeom/volumes/UnplacedTube.h
base/Global.h -> VecGeom/base/Global.h
This is beyond the scope of me fixing CMSSW and need to be fixed in Geant4

**Comment by civanch** [comment]
@mrodozov , I would propose to qualify this as failed attempt. Let us close this PR.
I will report problem to VecGeom. 

VecGeom.1.1.5 has no problem which stops us from validation of the new Geant4. Let us go forward with making Geant4 IB with VecGeom.1.1.5

**Comment by civanch** [comment]
@mrodozov , I just chat with Gabriele Cosmo, we looked into build instructions and suspect that the problem is in location of "include" directory (lines 41-42 of spec file). In VecGeom.1.1.5 it was "include" in VecGeom1.1.6 it is "include/VecGeom". Gabriele propose to add both to the path. If what he said is clear  you may try once more but I still propose to skip upgrade to VecGeom1.1.6 and continue with making Geant4 IB.

**Comment by mrodozov** [comment]
@civanch I started thinking of adding the additional include path in the toolfile, too.
The yesterday IB -> CMSSW_11_1_GEANT4_X_2020-03-05-1100 has this additional changes
https://github.com/cms-sw/cmsdist/pull/5622
https://github.com/cms-sw/cmsdist/pull/5623
https://github.com/cms-sw/cmssw/pull/29084
do you need another IB or you want to build a release ?

**Comment by civanch** [comment]
For me the release is the first thing. We need to be coherent with 11_1_0_pre4, VecGeom may be updated after.

**Comment by mrodozov** [comment]
Now it's clear because you were saying you need an IB :)

**Comment by silviodonato** [comment]
@mrodozov the GEANT4 release has to include https://github.com/cms-sw/cmssw/pull/29055.
If we keep VecGeom1.1.5, I think we can build the release with

"Build CMSSW_11_1_0_pre4_GEANT4"
ARCHITECTURE:slc7_amd64_gcc820
CMSSW_COMMIT:61e522225cab761ec911f816ab12d895e35474a6
CMSDIST_COMMIT:REL/CMSSW_11_1_0_pre4/slc7_amd64_gcc820

where 61e522225cab761ec911f816ab12d895e35474a6 is CMSSW_11_1_0_pre4 (b9d71f609fd8d9ab4101c6ad1319f224b5205e39) + https://github.com/cms-sw/cmssw/pull/29104 (a copy of https://github.com/cms-sw/cmssw/pull/29055)

**Comment by silviodonato** [comment]
https://github.com/cms-sw/cmssw/issues/29136

@civanch we are making CMSSW_11_1_0_pre4_GEANT4
that is a copy of CMSSW_11_1_0_pre4, including also cms-sw/cmssw#29104 (a copy of cms-sw/cmssw#29055).

**Comment by mrodozov** [comment]
please test

**Comment by silviodonato** [comment]
@civanch did you refer to this PR during the last ORP meeting? Did you ask for a new CMSSW_11_1_0_pre4_GEANT4 including this PR?

**Comment by civanch** [comment]
No, this is a useful update of VecGeom but authors change build rule, so it does not compile and we decided not including it into CMSSW_11_1_0_pre4_GEANT4  in order to save time. 

This RP is needed for regular GEANT4 branch. The recent modification fail testing now due to boost. I will try to have a look...

**Comment by smuzaffar** [comment]
@civanch , we need a newer GEANT4 IBs to start the tests. Old geant4 IB is using older version of boost. 
I am triggering a fresh full build of GEANT4 IB so that we can continue with tests.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar, Thanks!

**Pull request merged**
