### PR TITLE
Mark the `TriangularSolverMatrix` "kernel" functions as `EIGEN_DEVICE_FUNC`

### LINKED ISSUE #42460: [GPU] Unit test `testEigenGPUNoFit_t` failing when testing inverse 5x5
Hello,

Unit test `testEigenGPUNoFit_t` (module `RecoTracker/PixelTrackFitting`) is failing when running `TEST INVERSE 5x5` with:
```
===== Test "testEigenGPUNoFit_t" ====
TEST EIGENVALUES
TEST INVERSE 3x3
TEST INVERSE 4x4
TEST INVERSE 5x5
testEigenGPUNoFit_t: /tmp/avalenzu/CMSSW_13_3_GPU_X_2023-08-02-2300/src/RecoTracker/PixelTrackFitting/test/test_common.h:24: bool isEqualFuzzy(C1, C2, double) [with C1 = Eigen::Matrix<double, 5, 5>; C2 = Eigen::Matrix<double, 5, 5>]: Assertion `std::abs(a(i, j) - b(i, j)) < std::min(std::abs(a(i, j)), std::abs(b(i, j))) * epsilon' failed.
/bin/sh: line 1: 1044014 Aborted                 (core dumped) sh -c 'testEigenGPUNoFit_t '

---> test testEigenGPUNoFit_t had ERRORS
TestTime:4
^^^^ End Test testEigenGPUNoFit_t ^^^^                                         
```

We already had a similar issue when testing the 5x5 inverse in this unit test (See https://github.com/cms-sw/cmssw/issues/33797).

I can reproduce it in lxplus-gpu nodes.

### PR DESCRIPTION
**Pull request by fwyzard**
This should fix https://github.com/cms-sw/cmssw/issues/42460 .

For reference, the changes are https://github.com/cms-externals/eigen-git-mirror/commit/e021252e5767868dac39ab75a73616ec871460ec :
```diff
diff --git a/Eigen/src/Core/products/TriangularSolverMatrix.h b/Eigen/src/Core/products/TriangularSolverMatrix.h
index 9f5ead2d6..7354d8df2 100644
--- a/Eigen/src/Core/products/TriangularSolverMatrix.h
+++ b/Eigen/src/Core/products/TriangularSolverMatrix.h
@@ -21,6 +21,7 @@ template <typename Scalar, typename Index, int Mode, bool Conjugate, int TriStor
 struct trsmKernelL {
   // Generic Implementation of triangular solve for triangular matrix on left and multiple rhs.
   // Handles non-packed matrices.
+  EIGEN_DEVICE_FUNC
   static void kernel(
     Index size, Index otherSize,
     const Scalar* _tri, Index triStride,
@@ -31,6 +32,7 @@ template <typename Scalar, typename Index, int Mode, bool Conjugate, int TriStor
 struct trsmKernelR {
   // Generic Implementation of triangular solve for triangular matrix on right and multiple lhs.
   // Handles non-packed matrices.
+  EIGEN_DEVICE_FUNC
   static void kernel(
     Index size, Index otherSize,
     const Scalar* _tri, Index triStride,
@@ -38,6 +40,7 @@ struct trsmKernelR {
 };
 
 template <typename Scalar, typename Index, int Mode, bool Conjugate, int TriStorageOrder,int OtherInnerStride>
+EIGEN_DEVICE_FUNC
 EIGEN_STRONG_INLINE void trsmKernelL<Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride>::kernel(
     Index size, Index otherSize,
     const Scalar* _tri, Index triStride,
@@ -89,6 +92,7 @@ EIGEN_STRONG_INLINE void trsmKernelL<Scalar, Index, Mode, Conjugate, TriStorageO
 
 
 template <typename Scalar, typename Index, int Mode, bool Conjugate, int TriStorageOrder, int OtherInnerStride>
+EIGEN_DEVICE_FUNC
 EIGEN_STRONG_INLINE void trsmKernelR<Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride>::kernel(
     Index size, Index otherSize,
     const Scalar* _tri, Index triStride,
```

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Note that the compiler _would_ warn about the underlying error, but Eigen silences those warnings.
Maybe we should remove that silencing ?

The culprit seems to be https://github.com/cms-externals/eigen-git-mirror/blob/e021252e5767868dac39ab75a73616ec871460ec/Eigen/src/Core/util/DisableStupidWarnings.h#L117 :
```c++
  EIGEN_NV_DIAG_SUPPRESS(20011)
```

**Comment by fwyzard** [comment]
The failing tests are unrelated to these changes, while `testEigenGPUNoFit_t` now passes: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-895c67/35367/gpuUnitTests/src/RecoTracker/PixelTrackFitting/test/testEigenGPUNoFit_t/testing.log .

**Comment by fwyzard** [comment]
@smuzaffar can this be merged ?

**Comment by smuzaffar** [comment]
+externals

unit tests failures are not related to this PR

**Pull request merged**
