### PR TITLE
[DD4Hep] Updated to get conversion for Polyhedra and Polycone fix

### LINKED ISSUE #5341: DD4hep: update to master
Please, update the dd4hep external to its master branch. This fixes a bug in G4 converter for Polyhedra.

Thanks.

### PR DESCRIPTION
**Pull request by smuzaffar**
Resolves #5341
https://github.com/AIDASoft/DD4hep/issues/578

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar @kpedro88 @ianna the DQM differences looks unrelated to this PR, linked to #28367

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
