### PR TITLE
new scram version, config tag, html log zip instead of tar gz

### PR DESCRIPTION
**Pull request by smuzaffar**
see PR #295

### CODE REVIEW

**Comment by davidlt** [comment]
@smuzaffar have you tested it locally?

**Comment by smuzaffar** [comment]
I build cmssw.spec and every thing worked fine. I must admit I did not 
build cmssw-ib.spec (where I have changes for uzing zip instead of tar).

**Comment by davidlt** [comment]
Any particular reason for uzing zip instead of *nix friendly tarballs?

**Comment by smuzaffar** [comment]
Giulio had noticed that for few days IB web pages are very slow 
(specailly when are go to runTheMatrix logs). I noticed that extrating 
the files list from the tar file was very slow as compare to zip and 
also extraing single file out of tgz was more than 1000 time slower, so 
we diced to use zip.

**Comment by smuzaffar** [comment]
you can see the difference by going to

logs with zip:
http://cmssdt.cern.ch/SDT/cgi-bin//showMatrixTestLogs.py/slc5_amd64_gcc481/www/thu/7.0-thu-02/CMSSW_7_0_X_2013-12-12-0200/pyRelValMatrixLogs/run/

vs logs in tgz
https://cmssdt.cern.ch/SDT/cgi-bin//showMatrixTestLogs.py/slc6_amd64_gcc481/www/thu/7.0-thu-02/CMSSW_7_0_X_2013-12-12-0200/pyRelValMatrixLogs/run/

**Comment by ktf** [comment]
tarballs do not have an index, zip does.

**Comment by davidlt** [comment]
I did some digging. You are correct that standard tarball does not contain index, while zip contains index and compress each file individually.

**Comment by ktf** [comment]
I know I'm correct, as always...;)

**Pull request merged**
