### PR TITLE
Initial reference for RecoHGCal-TICL data repo

### PR DESCRIPTION
**Pull request by mrodozov**
to test with https://github.com/cms-sw/cmssw/pull/27634

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
+externals

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
