### PR TITLE
Update xrootd to 4.2.3.

### PR DESCRIPTION
**Pull request by ghost**
Ported from 8_0_X/next.

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by smuzaffar** [comment]
@degano , need to fix xrootd-toolfile too to have lib64 instead of lib.

```
Setting up all tools in current area
**** ERROR: No such file or directory: /build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc493/external/xrootd/4.2.3-cms/lib
     SCRAM does not allow prompting for user input anymore.
     Please fix the tool file for "xrootd" and provide a valid value for "LIBDIR".
```

**Comment by smuzaffar** [comment]
@degano  , are you looking in to this?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
please test

**Comment by davidlt** [comment]
What's the status of this?

**Comment by ghost** [comment]
The unit tests reported failed are the same failing in the IB.

**Comment by ghost** [comment]
please test

**Pull request merged**
