### PR TITLE
add BOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX to boost defs

### PR DESCRIPTION
**Pull request by slava77**
based on #5657

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test for slc7_ppc64le_gcc820

**Comment by slava77** [comment]
I'm curious if the build was just too long for the machine to handle or if there was a real problem

**Comment by smuzaffar** [comment]
So some unknow reason, boot-toolfile generation did not find the boost libs
```
++ getLibName thread
+++ find /build/cmsbld/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/slc7_ppc64le_gcc820/external/boost/1.72.0/lib -name libboost_thread.so -exec basename '{}' ';'
++ libname=
++ echo
++ sed -e 's|[.][^-]*$||;s|^lib||'
+ export BOOST_THREAD_LIB=
+ BOOST_THREAD_LIB=
```
that is why coral build failed 
```
>> Building shared library tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/liblcg_CoralKernel.so
/build/cmsbld/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/slc7_ppc64le_gcc820/external/gcc/8.3.0/bin/c++ -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++1z -ftree-vectorize -Wstrict-overflow -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -fsigned-char -fsigned-bitfields -mlong-double-64 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -shared -Wl,-E -Wl,-z,defs tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/Service.cpp.o tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/PluginManager.cpp.o tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/Property.cpp.o tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/Context.cpp.o tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/PropertyManager.cpp.o -o tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/liblcg_CoralKernel.so -Wl,-E -Wl,--hash-style=gnu -L/build/cmsbld/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/tmp/BUILDROOT/95cb1e512053070bd4b737919ece51ca/opt/cmssw/slc7_ppc64le_gcc820/cms/coral/CORAL_2_3_21-9440de/slc7_ppc64le_gcc820/lib -L/build/cmsbld/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/tmp/BUILDROOT/95cb1e512053070bd4b737919ece51ca/opt/cmssw/slc7_ppc64le_gcc820/cms/coral/CORAL_2_3_21-9440de/external/slc7_ppc64le_gcc820/lib -L/build/cmsbld/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/tmp/BUILDROOT/95cb1e512053070bd4b737919ece51ca/opt/cmssw/slc7_ppc64le_gcc820/cms/coral/CORAL_2_3_21-9440de/ -llcg_CoralBase -lnsl -lcrypt -ldl -lrt
/cvmfs/cms-ib.cern.ch/nweek-02620/slc7_ppc64le_gcc820/external/gcc/8.3.0/bin/../lib/gcc/powerpc64le-unknown-linux-gnu/8.3.1/../../../../powerpc64le-unknown-linux-gnu/bin/ld: tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/PluginManager.cpp.o: in function `coral::PluginManager::readPluginsFromDir(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
PluginManager.cpp:(.text+0x9a0): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/cvmfs/cms-ib.cern.ch/nweek-02620/slc7_ppc64le_gcc820/external/gcc/8.3.0/bin/../lib/gcc/powerpc64le-unknown-linux-gnu/8.3.1/../../../../powerpc64le-unknown-linux-gnu/bin/ld: PluginManager.cpp:(.text+0xafc): undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/cvmfs/cms-ib.cern.ch/nweek-02620/slc7_ppc64le_gcc820/external/gcc/8.3.0/bin/../lib/gcc/powerpc64le-unknown-linux-gnu/8.3.1/../../../../powerpc64le-unknown-linux-gnu/bin/ld: PluginManager.cpp:(.text+0xb2c): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/cvmfs/cms-ib.cern.ch/nweek-02620/slc7_ppc64le_gcc820/external/gcc/8.3.0/bin/../lib/gcc/powerpc64le-unknown-linux-gnu/8.3.1/../../../../powerpc64le-unknown-linux-gnu/bin/ld: PluginManager.cpp:(.text+0xb54): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
gmake: *** [tmp/slc7_ppc64le_gcc820/src/LCG/CoralKernel/src/lcg_CoralKernel/liblcg_CoralKernel.so] Error 1
```

**Comment by smuzaffar** [comment]
ah I know the reason of previous failure. During PR tests we do not download all package but create symlinks from cvmfs. In this case boost package (as it is not changed) was symlinked and that is why `find` command failed as it does not follow symlinks bydefault

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
@smuzaffar 
please also run a test on PPC

**Comment by smuzaffar** [comment]
@slava77 , I have tested it on PPC by hand ( https://github.com/cms-sw/cmsdist/issues/5657#issuecomment-600301396 ) and it works. Testing it here is not going to help as there are build errors on PPC (due to onnxruntime) so bot is not going to run runTheMatrix.

**Comment by slava77** [comment]
> @slava77 , I have tested it on PPC by hand ( [#5657 (comment)](https://github.com/cms-sw/cmsdist/issues/5657#issuecomment-600301396) ) and it works. Testing it here is not going to help is there are build errors on PPC (due to onnxruntime) so bot is not going to run runTheMatrix.

OK, fair enough

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
