### PR TITLE
Update Geant4 to 11.0.6 in geant4vecgeom IBs

### PR DESCRIPTION
**Pull request by iarspider**
Closes https://github.com/cms-externals/geant4/issues/60

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_12_5_G4VECGEOM_X

**Comment by iarspider** [comment]
please test for CMSSW_12_5_G4VECGEOM_X

**Comment by iarspider** [comment]
please test for CMSSW_12_5_G4VECGEOM_X/el8_amd64_gcc10

**Comment by iarspider** [comment]
please test for CMSSW_12_5_G4VECGEOM_X/el8_amd64_gcc10

**Comment by iarspider** [comment]
@civanch 
```
*** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002abc8da7d3eb in waitpid () from /lib64/libc.so.6
#1  0x00002abc8d9debaf in do_system () from /lib64/libc.so.6
#2  0x00002abc8b3d2cdb in TUnixSystem::StackTrace() () from /pool/condor/dir_26012/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_G4VECGEOM_X_2022-06-30-2300/external/el8_amd64_gcc10/lib/libCore.so
#3  0x00002abc8b3d0275 in TUnixSystem::DispatchSignals(ESignals) () from /pool/condor/dir_26012/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_G4VECGEOM_X_2022-06-30-2300/external/el8_amd64_gcc10/lib/libCore.so
#4  <signal handler called>
#5  0x00002abc880f66b8 in vecgeom::cxx::PolyconeStruct<double>::Init (this=0x7ffce9c57070, phiStart=0.78539816339744828, phiTotal=5.6723200689815707, numZPlanes=0, zPlane=0x1a0d260, rInner=0x1a0ad00, rOuter=0x1a0adc0) at /cvmfs/cms-ib.cern.ch/nweek-02739/el8_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/PolyconeStruct.h:163
#6  0x00002abc8819b1a5 in vecgeom::cxx::UnplacedPolycone::UnplacedPolycone (this=0x7ffce9c57030, phiStart=0.78539816339744828, phiTotal=5.6723200689815707, numRZ=9, r=0x1a0ade0, z=0x1a0b0f0) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/vecgeom-v1.2.0/source/UnplacedPolycone.cpp:237
#7  0x00002abc880ec141 in vecgeom::cxx::CommonUnplacedVolumeImplHelper<vecgeom::cxx::PolyconeImplementation<vecgeom::cxx::ConeTypes::UniversalCone>, vecgeom::cxx::UnplacedPolycone>::CommonUnplacedVolumeImplHelper (this=0x7ffce9c57030) at /cvmfs/cms-ib.cern.ch/nweek-02739/el8_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/UnplacedVolumeImplHelper.h:85
#8  vecgeom::cxx::LoopUnplacedVolumeImplHelper<vecgeom::cxx::PolyconeImplementation<vecgeom::cxx::ConeTypes::UniversalCone>, vecgeom::cxx::UnplacedPolycone>::LoopUnplacedVolumeImplHelper (this=0x7ffce9c57030) at /cvmfs/cms-ib.cern.ch/nweek-02739/el8_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/UnplacedVolumeImplHelper.h:276
#9  vecgeom::cxx::SUnplacedPolycone<vecgeom::cxx::ConeTypes::UniversalCone>::UnplacedPolycone (this=0x7ffce9c57030) at /cvmfs/cms-ib.cern.ch/nweek-02739/el8_amd64_gcc10/external/vecgeom/v1.2.0-274160740fee426d01da83d4c334c7a0/include/VecGeom/volumes/UnplacedPolycone.h:264
#10 G4UAdapter<vecgeom::cxx::SUnplacedPolycone<vecgeom::cxx::ConeTypes::UniversalCone> >::G4UAdapter<double, double, int, double const*, double const*> (name=..., this=0x7ffce9c57000) at /pool/condor/dir_26012/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc10/external/geant4/11.0.6-0ca95a95041ad5ea09d23a531146cab7/geant4.11.0.6/source/geometry/management/include/G4UAdapter.hh:83
#11 G4Polycone::G4Polycone (this=0x7ffce9c57000, name=..., phiStart=0.78539816339744828, phiTotal=5.6723200689815707, numRZ=9, r=0x1a0ade0, z=0x1a0b0f0) at /pool/condor/dir_26012/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc10/external/geant4/11.0.6-0ca95a95041ad5ea09d23a531146cab7/geant4.11.0.6/source/geometry/solids/specific/src/G4UPolycone.cc:97
#12 0x000000000040853b in doPolycone2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double, double, std::vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> > const&) ()
#13 0x0000000000405512 in main ()
===========================================================
```

**Comment by civanch** [comment]
@iarspider , similar problem was two months ago, when we tried to use new version of VecGeom and DD4Hep. With some efforts it was resolve. For that it was needed simultaneous recompilation of all these packages. The issue itself in the geometry classes was not understood.

**Comment by iarspider** [comment]
please test for CMSSW_12_5_G4VECGEOM_X/el8_amd64_gcc10

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
test parameters:
  - full_cmssw = true

**Comment by iarspider** [comment]
please test for CMSSW_12_5_G4VECGEOM_X/el8_amd64_gcc10

**Comment by smuzaffar** [comment]
lets get this in G4Gecgeom Ibs

**Pull request merged**
