### PR TITLE
[WIP] Remove py3-google-common package

### PR DESCRIPTION
**Pull request by iarspider**
google-common is no longer needed for Python >= 3.3: https://packaging.python.org/guides/packaging-namespace-packages/

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , please also drop https://github.com/cms-sw/cmsdist/blob/0cc1731f10cda8684848a0eba3657ac020d847f2/python_tools.spec#L16

**Comment by iarspider** [comment]
please abort

**Comment by smuzaffar** [comment]
also add `py3-protobuf` in to python tools

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
looks good
```
muzaffar@cmsdev20.cern.ch>python3
iPython 3.9.6 (default, Jul 28 2021, 18:12:51)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google import protobuf
>>> protobuf.__file__
'/cvmfs/cms-ci.cern.ch/week1/PR_6cbf53ed/slc7_amd64_gcc900/external/py3-protobuf/3.15.1-dhcijl/lib/python3.9/site-packages/google/protobuf/__init__.py'
>>> from google import auth
>>> auth.__file__
'/cvmfs/cms-ci.cern.ch/week1/PR_6cbf53ed/slc7_amd64_gcc900/external/py3-google-auth/1.27.0-llifpc2/lib/python3.9/site-packages/google/auth/__init__.py'
>>>
```

**Pull request merged**
