### PR TITLE
Update Keras to 2.4.3 to fix TF unit test

### PR DESCRIPTION
**Pull request by mrodozov**
this suggests the failure in the test is fixed updating keras:
https://github.com/tensorflow/tensorflow/issues/38589#issuecomment-719447077

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test
testing standalone to see if this can be merged before tf

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Pull request merged**
