### PR TITLE
upgrade pythia8 to 303

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
please test

**Comment by mkirsano** [comment]
please test with https://github.com/cms-sw/cmssw/pull/31705

**Comment by mkirsano** [comment]
please test

**Comment by mrodozov** [comment]
please test with https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/15

**Comment by alberto-sanchez** [comment]
Looks like the changes were not taken into account. Perhaps https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/data/cmsswdata.txt need to be update as well.

**Comment by mrodozov** [comment]
testing with a data pull request does take the changes from the data pr.
updating a record in cmsswdata to a new tag is just referring to a change that was merged. we made this exactly for testing a data pr before merging it. 

this is from the jenkins job: https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/9983/console

```
18:40:34 + git clone https://github.com/cms-data/GeneratorInterface-EvtGenInterface -b master
18:40:34 Cloning into 'GeneratorInterface-EvtGenInterface'...
18:40:36 + pushd GeneratorInterface-EvtGenInterface
18:40:36 + git pull git://github.com/alberto-sanchez/GeneratorInterface-EvtGenInterface.git master
18:40:37 From git://github.com/alberto-sanchez/GeneratorInterface-EvtGenInterface
18:40:37  * branch            master     -> FETCH_HEAD
18:40:37 Updating d64ecb5..b352975
18:40:37 Fast-forward
18:40:37  evt_2014.pdl | 36 ++++++++++++++++++------------------
18:40:37  1 file changed, 18 insertions(+), 18 deletions(-)
18:40:37 + popd
```
meaning the PR was applied

**Comment by alberto-sanchez** [comment]
You are right. I have identified some hard coded numbers inside the EvtGen Interface.
I will prepare a separate PR to fix that.

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/31816, cms-data/GeneratorInterface-EvtGenInterface#15

**Comment by alberto-sanchez** [comment]
Looks like the problem with Lambdas is gone, but still are issue with  a couple of kaons

**Comment by mkirsano** [comment]
please test with cms-sw/cmssw#31816, cms-data/GeneratorInterface-EvtGenInterface#15

**Comment by alberto-sanchez** [comment]
The issue with the Lambdas and Ks mismatch of the EvtGen interface and Pythia 8.3.03 is gone. 
The current problem is with a parameter, which is not accepted by pythia 
SLHA:keepSM = on
In the test cfg Py8_lambadb_evtgen1_Lb2plnuLCSR_cfg.py (I am adding a commit to fix this)

There is also another problem with 
TauAnalysis/MCEmbeddingTools
apparently in the SIM step. Perhaps a undecayed particle or something like that.

**Comment by mkirsano** [comment]
please test with cms-sw/cmssw#31816, cms-data/GeneratorInterface-EvtGenInterface#15

**Comment by mkirsano** [comment]
I would suggest to merge at this point, and then may be debug the remaining crash

**Comment by agrohsje** [comment]
assign generators

**Comment by qliphy** [comment]
please test with cms-sw/cmssw#31816, cms-data/GeneratorInterface-EvtGenInterface#15

**Comment by mkirsano** [comment]
The same single crash, no new errors

**Comment by qliphy** [comment]
Right, but from https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-bfcce0/10278/unitTests.log
it seems not a SIM issue, but due to that Pythia8HadronizerFilter:generator gets crashed.
Can you reproduce this error locally? and is it possible due to multi-thread mode? 


Begin processing the 1st record. Run 274199, Event 245779397, LumiSection 125 on stream 0 at 26-Oct-2020 05:40:05.064 CET

 --------  LHA event information and listing  ---------------------------------------------------------------------- 

    process =        0    weight =   1.0000e+00     scale =  -1.0000e+00 (GeV) 
                        alpha_em =  -1.0000e+00    alpha_strong =  -1.0000e+00

    Participating Particles 
    no        id stat     mothers     colours      p_x        p_y        p_z         e          m        tau    spin 
     1        23    2     0     0     0     0    -12.300     -7.799      4.711     88.216     86.878   0.000   9.000
     2       -15    1     1     1     0     0    -26.852    -19.663     37.636     50.273      1.777   0.000   1.000
     3        15    1     1     1     0     0     14.552     11.864    -32.925     37.944      1.777   0.044  -1.000

 --------  End LHA event information and listing  ------------------------------------------------------------------ 

 --------  PYTHIA Event Listing  (complete event)  ---------------------------------------------------------------------------------
 
    no         id  name            status     mothers   daughters     colours      p_x        p_y        p_z         e          m 
     0         90  (system)           -11     0     0     0     0     0     0    -12.300     -7.799      4.711     88.216     86.878
     1         23  (Z0)               -22     0     0     2     3     0     0    -12.300     -7.799      4.711     88.216     86.878
     2        -15  tau+                23     1     0     0     0     0     0    -26.852    -19.663     37.636     50.273      1.777
     3         15  tau-                23     1     0     0     0     0     0     14.552     11.864    -32.925     37.944      1.777
                                   Charge sum:  0.000           Momentum sum:    -12.300     -7.799      4.711     88.216     86.878

 --------  End PYTHIA Event Listing  -----------------------------------------------------------------------------------------------


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Mon Oct 26 05:40:07 CET 2020
Thread 3 (Thread 0x2b5cb1098700 (LWP 25876)):
#0  0x00002b5c50701a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
...
...
Current Modules:

**Module: Pythia8HadronizerFilter:generator (crashed)**

A fatal system signal has occurred: segmentation violation
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-25-2300/src/TauAnalysis/MCEmbeddingTools/test/runtests.sh: line 37: 25848 Segmentation fault      cmsDriver.py TauAnalysis/MCEmbeddingTools/python/EmbeddingPythia8Hadronizer_cfi.py --filein file:lhe_and_cleaned.root --fileout file:simulated_and_cleaned.root --conditions auto:run2_mc --era Run2_2016 --eventcontent RAWRECO --step GEN,SIM,DIGI,L1,DIGI2RAW,RAW2DIGI,RECO --datatier RAWRECO --customise TauAnalysis/MCEmbeddingTools/customisers.customiseGenerator --beamspot Realistic25ns13TeV2016Collision -n -1 --customise_commands "process.generator.nAttempts = cms.uint32(1000)\n" --python_filename simulation.py
+ die 'Failure during Simulation step' 139
+ echo Failure during Simulation step: status 139
Failure during Simulation step: status 139
+ exit 139
status = 35584

---> test testTauEmbeddingProducers had ERRORS

**Comment by mkirsano** [comment]
Yes, it could be a GEN step problem. The point is that I cannot 
reproduce at all pythia8 303 in CMSSW without merging or at least a 
special CMSSW release. There is some critical difference between pythia8 
302 and 303, the tool substitution dos not work.

**Comment by smuzaffar** [comment]
@mkirsano , we do now deploy the externals builds for a PR on cvmfs. You can do something like [a] to reproduce the error
[a]
```
#create project area
scram p CMSSW_11_2_X_2020-10-27-1100
cd CMSSW_11_2_X_2020-10-27-1100/
#setup new tools
mv config/toolbox/slc7_amd64_gcc820/tools/selected config/toolbox/slc7_amd64_gcc820/tools/selected.backup
cp -r /cvmfs/cms-ci.cern.ch/prs/cms.week0.PR_bfcce0_CMSSW_11_2_X_slc7_amd64_gcc820/slc7_amd64_gcc820/cms/cmssw-tool-conf/46.0-bfcce0/tools/selected config/toolbox/slc7_amd64_gcc820/tools/
scram setup
#make sure that we do not pick up any libraries from tools of cmssw release 
chmod +x config/SCRAM/hooks/runtime/50-remove-release-external-lib
#setup env
cmsenv
#checkout needed cmssw PR
git cms-merge-topic 31816
#checkout packages which needs rebuild due to pythia8 change
scram b echo_pythia8_USED_BY | grep 'pythia8_USED_BY' | tr ' ' '\n' | grep '^self/' | cut -d/ -f2,3 | sort | uniq | xargs git cms-addpkg
#build all the checked out packages
scram b -j 10
#run tests
cd src/TauAnalysis/MCEmbeddingTools
export CMS_PATH=/cvmfs/cms-ib.cern.ch
scram b runtests
```

**Comment by silviodonato** [comment]
@mkirsano did you manage to reproduce the error?

**Comment by mkirsano** [comment]
Yes

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#31816, cms-data/GeneratorInterface-EvtGenInterface#15
this should rebuilt the external and deply them to /cvmfs/cms-ci.cern.ch area for testing

**Comment by smuzaffar** [comment]
@mkirsano , new tools are now available under `
/cvmfs/cms-ci.cern.ch/prs/cms.week1.PR_cd6a578b/slc7_amd64_gcc820/cms/cmssw-tool-conf/46.0-1433518976b5895a6fdb344e4a52b4e7/tools/selected` . You can use the same instructions ( https://github.com/cms-sw/cmsdist/pull/6286#issuecomment-717425854 ) to re-produce the error.

**Comment by mkirsano** [comment]
please test with cms-sw/cmssw#31816, cms-sw/cmssw#32077, cms-data/GeneratorInterface-EvtGenInterface#15

**Comment by mkirsano** [comment]
+1

**Comment by mkirsano** [comment]
To be merged together with 3 other PR as in the latest test

**Comment by smuzaffar** [comment]
@mkirsano , are the comparison differences here expacted?

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/6411 should go in with this PR to get the needed data external changes.

**Comment by mkirsano** [comment]
I am not a specialist in comparison. Some differences between versions 
are expected.

**Comment by agrohsje** [comment]
+1

**Comment by mrodozov** [comment]
I'd say lets just wait for the new (old)ROOT version that is coming with today 1100 IB, test it against it and then check the comparison.

**Comment by silviodonato** [comment]
> I'd say lets just wait for the new (old)ROOT version that is coming with today 1100 IB, test it against it and then check the comparison.

@mrodozov shall we start the new tests?

**Comment by mrodozov** [comment]
please test with  cms-sw/cmssw#31816, #6411

**Comment by silviodonato** [comment]
@mrodozov @cms-sw/generators-l2  I think the changes are just statistic fluctuations due to the new generator. I don't know if you usually require a full validation from @cms-sw/pdmv-l2 for pythia updates.

**Comment by agrohsje** [comment]
Hi @silviodonato . Indeed, as you always expect changes by changing versions, it would be useful to run some dedicated comparison campaign, check the differences and make sure they map our expectations from the P8 logs. This would also help to spot unexpected behaviour.

**Comment by mrodozov** [comment]
+externals
the external is integrating, if you say the comparison is reasonable - we get it in

**Comment by chayanit** [comment]
@silviodonato , the validation on generators are done in every campaign separately by GEN-only workflows but thanks for pointing this out as we will also have to provide RECO-only workflows to RECO validators in order to disentangle the generator effects. Is this coming in the next pre release?

**Comment by silviodonato** [comment]
Thanks @chayanit . I think we can include this PR in the prerelease. @cms-sw/generators-l2 do you agree?

@cms-sw/generators-l2 I have a further question about the comparison (https://github.com/cms-sw/cmsdist/pull/6286#issuecomment-730809150): do you know why some plots have disappeared?
For instance: plot HLT/HLTEgammaValidation/EfficiencyByPath_Ele in wf 12434.0 (see https://tinyurl.com/yxd6d7c5 )

**Comment by agrohsje** [comment]
Hi @silviodonato . Looks good to me.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
