### PR TITLE
Updating MagneticField-Interpolation tag V01-00-01

### PR DESCRIPTION
**Pull request by mrodozov**
Description of PR on cmsdata is "Add tables for map version 160812 for 3 and 3.8 T". PR: https://github.com/cms-data/MagneticField-Interpolation/pull/1

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by davidlange6** [comment]
hold

**Comment by slava77** [comment]
@davidlange6 please clarify the reason for the hold.
Thank you.

**Comment by davidlange6** [comment]
Merge

**Comment by davidlange6** [comment]
merge

**Pull request merged**
