### PR TITLE
CRAB hc1811 release which was skipped

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by h4d4** [comment]
-1 to 24bf18339743d818b625e3b87c008246e8446939 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4509/test_24bf183-20181117-224004.log" target="_blank">here</a>.

**Comment by belforte** [comment]
test

**Comment by belforte** [comment]
test this

**Comment by h4d4** [comment]
+1 to 1b89107ef9834f590fcd17d4fbdb97a319531533 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4509/test_1b89107-20181119-172506.log" target="_blank">here</a>.

**Pull request merged**
