### PR TITLE
Update Geant4 to 10.7ref09

### PR DESCRIPTION
**Pull request by ddaina**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- pull_requests = cms-sw/cmssw#36737

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@civanch , looks like `geant4-parfullcms` does not work with new geant4 version. Any reason to keep building  `geant4-parfullcms` , can we drop it from cmssw distro? Note that `geant4-parfullcms` is not maintained any more , the source code of this are downloaded from http://davidlt.web.cern.ch/davidlt/vault/%{realname}.%{realversion}.tar.bz2 ( and the person `davidlt`  has left cms a long time ago)

**Comment by civanch** [comment]
@smuzaffar , there is no reason to build parfullsim - I am not sure it was ever used recent years.

**Comment by smuzaffar** [comment]
@ddaina , can you please update this PR and remove `geant4-parfullcms`

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@civanch , right so dd4hep failed to build with newer geant4 ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b6c16f/20363/external/dd4hep/v01-18x-b0ba8d9db156bba37a2d9b5cfd320054/log ) . should we open issue with dd4hep ( I am not sure if they have access to geant4 11 code to test)?

**Comment by civanch** [comment]
@smuzaffar , this place inside DD4hep for me is strange. I do not know why DD4hep work with primary particles. We need making a ticket for them.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , unfortunately, we come to the dead-line of the bug-fix for the new Geant4. So, at this point would be better if we will continue on top of the public release 11.0, which will be available in December. DD4hep should be also updated on top of the public release. I would propose to close this PR and corresponding issue.

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar ¨, as I see it is not a compilation problem but some inconsistency. From the log I do not understand the problem. By the way, cmake and list of directories in Geant4 were updated.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@civanch looks like dd4hep is now ready for geant4 version 11 but now we need cmssw changes for G4 11 (see build errors https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b6c16f/21580/build-logs/ )

**Comment by civanch** [comment]
@smuzaffar , thanks! will try to address this issue shortly.

**Comment by civanch** [comment]
@smuzaffar , #36659 should fix the problem.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_G4VECGEOM_X

**Comment by smuzaffar** [comment]
@civanch , there are still few more errors, can you please look in to these too https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b6c16f/21613/build-logs/ ?

**Comment by civanch** [comment]
I am working on it.

**Comment by civanch** [comment]
@smuzaffar , is it possible to start test with #36737 ?

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_G4VECGEOM_X

@civanch , I have updated the test parameters https://github.com/cms-sw/cmsdist/pull/7436#issuecomment-963887495 to use cms-sw/cmssw#36737 now

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , it seems that the test is OK.

**Comment by smuzaffar** [comment]
@civanch , yes tests result look good. I will merge this once  cms-sw/cmssw#36737  is merged.

**Pull request merged**
