### PR TITLE
Update xrootd to v4.2.3, no CMS custom patches.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by davidlt** [comment]
All our custom patches are integrated?

**Comment by ghost** [comment]
@davidlt No, the I've looked at the diff and it seemed to me that there was none needed. I may be wrong though.

**Comment by davidlt** [comment]
@degano there are needed patches, e.g. fixing xrootd version in headers. This breaks ROOT from building.

**Comment by davidlt** [comment]
https://github.com/cms-externals/xrootd/commit/ccdcf41e5a45281374360a6a1e0521e064024bc0

This file needs to be imported from xrootd release tarball, otherwise xrootd fails to populate some of it's headers. Then this breaks things like `FindXrootd.cmake`.

**Comment by ghost** [comment]
@davidlt 
Done here: https://github.com/cms-sw/cmsdist/pull/1851

**Pull request merged**
