### PR TITLE
[DD4hep] Fix CC8 IBs

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- release/arch = CMSSW_11_1_X_2020-02-27-2300/cc8_amd64_gcc8
- pull_requests = https://github.com/cms-sw/cmssw/pull/29055

**Comment by mrodozov** [comment]
please test
lets see if this will work. since last night IB is broken we need the previous one

**Comment by mrodozov** [comment]
abort
now this will have the external change but not the cmssw one , because its not in the IB (see above)

**Comment by mrodozov** [comment]
please test

**Comment by silviodonato** [comment]
It works. Thanks @mrodozov !

**Pull request merged**
