### PR TITLE
Updated root to tip of branch v6-12-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
weird, the log says:
```
14:33:44 Checking if rivet-toolfile is cached.
14:33:44 Package external+rivet-toolfile+1.0-cms3 not found in repository. Queuing for build.
```
while when I try building it by hand: 
`rivet-toolfile is available from remote repository "cms.week1". Not building. Downloading and installing...`
I'll retry

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
