### PR TITLE
[G4VECGEOM] Update geant4 to 11.0.7 and dd4hep to 01.22

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by iarspider** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by civanch** [comment]
@iarspider , https://github.com/cms-externals/geant4/pull/62 should resolve the problem.

**Comment by iarspider** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by civanch** [comment]
Problem report shows the problem we observed when use -O3 for VecGeom

**Comment by smuzaffar** [comment]
@civanch , but here vecgeom is built with -O2 ( https://github.com/cms-sw/cmsdist/blob/update-geant4-11.0.7-dd4hep-01-22-geant4_vecgeom/vecgeom.spec#L26 )

**Comment by smuzaffar** [comment]
` -O3 for VecGeom` is only enabled for gcc11 builds

**Comment by smuzaffar** [comment]
by the way, one of these failed workflow also fail for IBs

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Pull request merged**
