### PR TITLE
updated sherpa to v2.2.2

### PR DESCRIPTION
**Pull request by smuzaffar**
Requested https://github.com/cms-externals/sherpa/pull/9

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by pmillet** [comment]
I did a few tests with slc6_amd64_gcc620 / CMSSW_9_0_DEVEL_X_2017-02-23-2300.
While event generation seems to work fine, an issue occurs when trying to do the phase space calculation:
```
Sherpa: Matrix_Element_Handler::InitializeProcesses throws normal exit: 
   Source code created. Run './makelibs' to compile.
Exception_Handler::SignalHandler: Signal (11) caught. 
Exception_Handler::GenerateStackTrace(..): Generating stack trace 
{
  0x7fab02e605a4  in 'SHERPA::Event_Handler::MPISync()' (Event_Handler.C:430)
  0x7fab02e60f39  in 'SHERPA::Event_Handler::Finish()' (Event_Handler.C:393)
  0x7fab04005a8b  in 'SHERPA::Sherpa::SummarizeRun()' (Sherpa.C:328)
  0x7fab04005bf9  in 'SHERPA::Sherpa::PrepareTerminate()' (Sherpa.C:313)
  0x7fab02b5b470  in 'ATOOLS::Terminate()' (Exception_Handler.C:135)
  0x3bbd21ed1d    in '__libc_start_main' (??:?)
}   Cannot continue.
Sherpa: Matrix_Element_Handler::InitializeProcesses throws normal exit: 
   Source code created. Run './makelibs' to compile.
Segmentation fault
```
Running makelibs and producing events works fine afterwards. This issue does not occur in 71X with gcc481. I contacted the Sherpa authors about this. According to them, this happens when Sherpa is wrapping up and can safely be ignored for the moment. They are investigating to find the source and possible fixes of this bug.

**Comment by pmillet** [comment]
@govoni, @perrozzi
should we proceed with including this into 90X?
according to @smuzaffar this is needed before getting it into 71X (see https://github.com/cms-sw/cmsdist/pull/2856)

**Comment by perrozzi** [comment]
(the answer was yes :-) )

**Pull request merged**
