### PR TITLE
CRAB3 3.3.7.rc4/rc5 versions for HG1407

### PR DESCRIPTION
**Pull request by mmascher**
Includes the following fixes (just mentioning crabserver and ignoring crabclient and crabtaskworker):
- Fix the regexp for the publishname parameter.
- Fix getoutput and getlog which were always failing
- Raise a proper error when the task is not found in the database (status API)
- Fix dbs report for usage with multiple output datasets

And a new feature recently requested for CSA14:
- Add the possibility to blacklist site in case ignoreLocality is set

### CODE REVIEW

**Comment by bbockelm** [comment]
Hi Marco,

I saw a patch fly by from Burt Holzman fixing /store/temp/user stageout at FNAL in WMCore.

Does this include that patch for the task worker?

Brian

**Comment by geneguvo** [comment]
-1 to 34b104bf3563952b23c747715272c8af50f5b4f2 on slc5_amd64_gcc461.

**Comment by mmascher** [comment]
Hi Brian, it does not, we'll include it later if it does not need to be deployed on cmsweb.

**Comment by bbockelm** [comment]
Nope, doesn't need to go on cmsweb.  Was just curious.

**Comment by geneguvo** [comment]
Hi Marco,

This build is failing with:
 The action "build-cms+crabserver+3.3.7.rc5" was not completed successfully because Failed to build crabserver. Log file in /build/diego/comp/w/BUILD/slc5_amd64_gcc461/cms/crabserver/3.3.7.rc5/log. Final lines of the log file:
-rw-r--r-- amaltaro/zh    6457 2014-06-20 11:06:42 WMCore-0.9.95b/standards/.pylintrc
-rw-r--r-- amaltaro/zh    1579 2014-06-20 11:06:42 WMCore-0.9.95b/standards/checkOutputs.py
-rw-r--r-- amaltaro/zh   15553 2014-06-20 11:06:42 WMCore-0.9.95b/standards/README
-rw-r--r-- amaltaro/zh    2647 2014-06-20 11:06:42 WMCore-0.9.95b/standards/allowed_failing_tests.txt
-rw-r--r-- amaltaro/zh   27868 2014-06-20 11:06:41 WMCore-0.9.95b/setup_test.py
-rw-r--r-- amaltaro/zh    3851 2014-06-20 11:06:41 WMCore-0.9.95b/setup.py
- STATUS=0
- '[' 0 -ne 0 ']'
- cd WMCore-0.9.95b
- chmod -Rf a+rX,u+w,g-w,o-w .
- echo 'Patch #0 (crabserver3-setup):'
  Patch #0 (crabserver3-setup):
- cat /build/diego/comp/w/SOURCES/cms/crabserver/3.3.7.rc5/crabserver3-setup
- patch -s -p1 --fuzz=0
  1 out of 1 hunk FAILED -- saving rejects to file setup_dependencies.py.rej
  error: Bad exit status from /build/diego/comp/w/tmp/rpm-tmp.1D8oJR (%prep)

RPM build errors:
Bad exit status from /build/diego/comp/w/tmp/rpm-tmp.1D8oJR (%prep)

Can you confirm this patch really applies cleanly? When I tried building it myself, I got the same error. Perhaps you using the wrong wmcore tag?

**Comment by geneguvo** [comment]
Ok. I found the problem. There is a trailing whitespace in the line "'WMCore.JobSplitting', 'WMCore.Services.SiteDB+', 'WMCore.Services.DBS+', ". 

When we apply these PRs in our scripts we "fix" whitespace errors (cat PR.diff | git apply --whitespace=fix), but obviously we should not do that for .patch files like the crabserver3-setup.patch.

I'll fix that. Sorry.

**Pull request closed without merging**
