### PR TITLE
[10_2_X] Update data-RecoBTag-Combined.spec

### PR DESCRIPTION
**Pull request by mrodozov**
Backport of #4540

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 0 differences found in the comparisons

this confirms that this external can be merged by itself before the cms-sw/cmssw#25370 is merged.

**Comment by smuzaffar** [comment]
+externals

this resolves #4537

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@andrzejnovak @slava77 @perrotta this external update is needed by cms-sw/cmssw#25370 , that is not yet ready to be merged. As 10_2_9 should start today, is this integration causing issues if not matched to its CMSSW counterpart? I see in https://github.com/cms-data/RecoBTag-Combined/pull/19/files that some files are removed and a few slightly modified, but this might change the behaviour, am I correct?

**Comment by slava77** [comment]
@fabiocos 
tests completed in https://github.com/cms-sw/cmsdist/pull/4550#issuecomment-444179513
show that this external can be integrated by itself.

**Comment by fabiocos** [comment]
@slava77 sorry to be pedantic, is this test supposed to catch the changes induced by these data files? You answer would imply it is, they should appear in miniAOD output, am I correct? In such a case likely workflow 136.85 in the matrix should catch that? Where are these changes supposed to show an effect otherwise?

**Comment by fabiocos** [comment]
ok, you comment

"jenkins tests pass and comparisons with the baseline show changes only in slimmedJetsAK8 jet tags in an expected way: new tags are added and the existing ones are unchanged"...

**Comment by slava77** [comment]
> ok, you comment
> 
> "jenkins tests pass and comparisons with the baseline show changes only in slimmedJetsAK8 jet tags in an expected way: new tags are added and the existing ones are unchanged"...

Sorry, I'm lost.
I was responding to 
> @andrzejnovak @slava77 @perrotta this external update is needed by cms-sw/cmssw#25370 , that is not yet ready to be merged. As 10_2_9 should start today, is this integration causing issues if not matched to its CMSSW counterpart? 

which I read as "can we integrate this data PR without cms-sw/cmssw#25370?"
My response is that by itself this data PR can be integrated and will not introduce any differences.

**Pull request merged**
