### PR TITLE
Update tensorflow to 1.12.0

### PR DESCRIPTION
**Pull request by mrodozov**
Move tensorflow to 1.12.0 and adjust py2-tensorflow. libjpeg-turbo to be moved to variable later

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
comparing https://github.com/tensorflow/tensorflow/blob/v1.6.0/tensorflow/core/common_runtime/direct_session.cc to https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/core/common_runtime/direct_session.cc : 
it looks like we need quite a few updates in PhysicsTools/TensorFlow/src/NTSession.cc and the tbbsession.

**Comment by mrodozov** [comment]
@slava77 I wanted to see if tf builds fine (which surprisingly it does) and then we adjust cmssw interfaces

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
close in favor of #4639

**Pull request closed without merging**
