### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@slava77 , Can you please check the reco comparison changes here https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_ROOT6_X_2021-06-07-2300+28b4d8/43295/validateJR.html ?

@mrodozov , we need to understand the comparison diff before we integrate this.

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
we still have 7 reco comparison differences , we ned to understand why these are there.
@slava77 can you please give it a look

**Comment by slava77** [comment]
> we still have 7 reco comparison differences , we ned to understand why these are there.
> @slava77 can you please give it a look

the differences are all in ctppsProtons error/uncertainty plot, e.g. in 136.874
all_OldVSNew_RunEGamma2018Cwf136p874c_log10recoForwardProtons_ctppsProtons_multiRP_reRECO_obj_xiError

it could be an artifact of how these plots are made. The script loads the old file first; if the new file has a different format/streaming, the plots may look wrong. I can't recall if we have any other plots from `SMatrix` data members, perhaps absence of other differences indicates that this is specific to `SMatrix`. https://github.com/cms-sw/root/compare/817af6fa03d4f6cbd019968202b8e94871925aed...4ac5a62bcd789630618f7f720155a0a4749e333e is not particularly revealing.

@jan-kaspar @fabferro 
is this collection and variable monitored in DQM?
If monitored, the lack of differences in the DQM plots should validate this PR.

**Comment by smuzaffar** [comment]
@jan-kaspar @fabferro @cms-sw/dqm-l2 , can you please look in to DQM plots ( as suggested here https://github.com/cms-sw/cmsdist/pull/6997#issuecomment-860923299 )

**Comment by jfernan2** [comment]
@smuzaffar the DQM bin by bin tool does not see those changes on CTPPS for 136.874 or any other wf

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_ROOT6_X_2021-06-13-2300+28b4d8/43446/dqm-histo-comparison-summary.html

All changes seen are in */EventInfo/CMSSW_Version as expected

I let @jan-kaspar and @fabferro to comment on the CTPPS details

**Comment by smuzaffar** [comment]
as dqm bin by bin comparisonm are not seeing these diff. So lets merge this and go ahead with next root master update

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
