### PR TITLE
Drop graphviz

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , I think we can drop graphviz, it was used by doxygen but we have dropped that. So this can be remove too. Just move the spec in the archive dir

**Comment by iarspider** [comment]
Will do that, thanks!

**Comment by iarspider** [comment]
please test

**Review by smuzaffar — APPROVED** [review]

**Pull request merged**
