### PR TITLE
Added patch for decay of K0 and antiK0

### PR DESCRIPTION
**Pull request by civanch**
This is a patch for K0 and antiK0 decay cloned from #3505

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by mrodozov** [comment]
I think this one is the same https://github.com/cms-sw/cmsdist/pull/3504

**Comment by civanch** [comment]
Yes, I am trying propagate the same patch to Geant4 to 9_3_X and 9_4_X. The new commits (of the same geant4.spec) are needed because I see that geant4.spec are not identical in these branches.

**Comment by civanch** [comment]
@davidlange6 , @mrodozov , large number of failures is expected here, because the IB for comparisons includes #3501 which changes sim histories. Now the histories should be as before #3501.

**Comment by davidlange6** [comment]
right - thats why you were asked to do it for 93x...

**Comment by davidlange6** [comment]
merge

**Pull request merged**
