### PR TITLE
Build WMAgent with a python3 stack

### PR DESCRIPTION
**Pull request by amaltaro**
This is a work in progress PR.

It builds a new `wmagentpy3` spec file, based on the python3 stack library.

First commit builds wmagentpy3 with the first set of dependencies, such as (rucio-clients brings tons of dependencies though):
```
Requires: yui libuuid couchdb15 condor pystack jemalloc cmsmonitoring dbs3-client
Requires: python3 py3-sqlalchemy py3-httplib2 py3-pycurl py3-rucio-clients
```

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 6caa1ed1cb99d95c04ba6cdd29c06dbd67629809 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_6caa1ed-20210129-064002.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to 78201be0617162c61b0207cdf066d1964743fa3c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_78201be-20210129-071004.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to 10dbc2991e963c763b9cfefb10e5a540aa8e968a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_10dbc29-20210129-083003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to 0097b3bcc35e43870c421792e44ad9d282ea68d0 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_0097b3b-20210129-161503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@smuzaffar Shahzad, I'm afraid I need to ask for your advice on one issue here.

The last build, with logs available at:
https://cms-dmwm-builds.web.cern.ch/cms-dmwm-builds/6603/test_0097b3b-20210129-161503.log

reports the following error for py3-cryptography:
```
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```

while googling for it, I found many ways around this problem, like a) updating pip; b) updating setup-tools; c) providing the openssl development libraries.

Looking at the cmsdist IB_11_3_* branch:
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/master/pip/cryptography.file

I noticed you provide your home made build of openssl. Unless I missed something, wasn't it supposed to be using the system openssl, instead of the openssl spec built in cmsdist?

**Comment by amaltaro** [comment]
Trying to downgrade cryptography version from 3.3.1 to 3.2.1, which is the same one built for IB_11 branch. Let's see if it goes through now :)

**Comment by smuzaffar** [comment]
@amaltaro , we have dropped openssl for CentOS8 builds (IB/CMSSW_11_3_X/cc8 branch).
The problem here is that py3-cryptography is trying to build its dependencies locally and gcc failed to build part of ssl. I woud suggest to do the foolowing
- Add `--no-build-isolation --no-index` to `pip3 install ` command in your build-with-pip3.file. This will force pip3 to not build/install dependencies. See our https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/master/build-with-pip.file 
- After updaing the above you will noticed that py3-cryptography needs a newer version of setuptool 40.6.0 , so I would suggets to update setuptools too.
- Then you will need to add py3-wheel in your branch , as py3-cryptography also need wheel to build.

**Comment by muhammadimranfarooqi** [comment]
-1 to 59af9e4d942c5b7fa833d66422b68295602aa766 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_59af9e4-20210129-172004.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Haaa, it looks like I managed to build it with version 3.2.1:
```
Build successful py3-cryptography.
```

but I guess it's just a matter of time until I hit this problem and have the need to follow your suggestion, which will build every single python package in our repository :-(

Onto the next problem now...

**Comment by muhammadimranfarooqi** [comment]
-1 to 83eccdd313bd0419f77cbc9de67cc376cbf5edf2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_83eccdd-20210129-180504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to 8b894d40179431fc78587365f0796dbbb7d532db on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_8b894d4-20210129-185003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to 7693f4152dbd81f10666f4bc7298f430e2473353 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_7693f41-20210129-213004.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 07cc67984fe39fa047986078682d104914cc8ffe on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_07cc679-20210129-222003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 915ba2a437cdc5ab37b84b444d5145ee21929ead on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_915ba2a-20210201-122004.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
-1 to 8d54f6b311a25b25da43b46e49ea342ce19364ce on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_8d54f6b-20210201-155004.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi Imran, this build seems to be stuck or not getting triggered. Would you know why it does not run (or does not report back)?

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

It is still in process of building RPMs

**Comment by muhammadimranfarooqi** [comment]
+1 to 6829629bafcd9c6c9bfe54d2a7e7844aa16315f7 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6603/test_6829629-20210202-082503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Perfect!
@muhammadimranfarooqi Imran, given that this PR only affects the python3 specs (and a new wmagentpy3 spec), could you please merge it? Thanks

**Pull request merged**
