### PR TITLE
Upgrading some python packages

### PR DESCRIPTION
**Pull request by davidlange6**
my local tests are unhappy with some un-understandable errors with missing dependencies.. I want to see if the automatic tests have the same issue.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test


On 11 Mar 2020, at 21:37, cmsbuild <notifications@github.com> wrote:

﻿

A new Pull Request was created by @davidlange6<https://github.com/davidlange6> (David Lange) for branch IB/CMSSW_11_1_X/master.

@cmsbuild<https://github.com/cmsbuild>, @smuzaffar<https://github.com/smuzaffar>, @mrodozov<https://github.com/mrodozov>, @tulamor<https://github.com/tulamor> can you please review it and eventually sign? Thanks.
cms-bot commands are listed here<http://cms-sw.github.io/cms-bot-cmssw-cmds.html>

**Comment by davidlange6** [comment]
ok, good, the failures in my test area are not reproduced here... the failing unit test was due to a package version inconsistency - funny that pip didn't see that at build time.. I've fixed that

Requirement.parse('parso>=0.5.2'), {'jedi'}

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
