### PR TITLE
Java 1.7 for First prototype of circuit awarness integration in Phedex

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to a772dfef86706a4ad2ff79c4f58a8d582dcf0f15 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1837/test_a772dfe-20150924-131504.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
Any reason for calling the it "java-jdk1-7.spec" instead of using the older "java-jdk.spec"? IFAIK nothing is using this package in COMP for good. There's only some build time requirements which might not even be needed anymore.

I'll therefore apply these changes directly to java-jdk.spec. If you meant to call the package java-jdk1-7 for some other reason, we need to change the name of the package in the first like line of the spec to match it too. Let me know.

**Comment by juztas** [comment]
I named it like that, because found java-jdk.spec to be used. Will change it now

**Comment by geneguvo** [comment]
Thanks Justas for the prompt action! I'm building it now.

**Comment by geneguvo** [comment]
+1 to 8f75d73eebd3ccfdb00c41da43c3243cc2d5f5ba on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1837/test_8f75d73-20150925-150506.log" target="_blank">here</a>.

**Pull request closed without merging**
