### PR TITLE
backporting sherpa 2.2.8 and openloops 2.1.0 to 93X

### PR DESCRIPTION
**Pull request by SiewYan**
1.) Backport sherpa 2.2.8
2.) Backport openloops 2.1.0 [*]

[*] @smuzaffar , @mrodozov , I have defined processes libraries collection for openloops 2.1.0, can it be uploaded to the external git repo and feed into openloops https://github.com/cms-sw/cmsdist/blob/a813937406a3fb809a0419632e474d102047c293/openloops.spec#L26 ?

user.coll:
https://shoh.web.cern.ch/shoh/Topics/public/openloops/user.coll

### CODE REVIEW

**Comment by smuzaffar** [comment]
@SiewYan , yes you can 
- add a file e.g. `openloops-user.coll.file` in cmsdist 
- Add `Source1: openloops-user.coll` in opeloops.spec to  get acces to this file during build time
- During build phase you can access this file via `%{ _sourcedir}/openloops-user.coll`

**Comment by SiewYan** [comment]
@smuzaffar Thanks a tonnes! I will test it locally in cmsdist, if its build, i will update this PR.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@SiewYan I would prefer that we have this in place for master first

**Comment by SiewYan** [comment]
@fabiocos , in 110X?

**Comment by fabiocos** [comment]
@SiewYan yes (for the time being)

**Comment by SiewYan** [comment]
https://github.com/cms-sw/cmsdist/pull/5388

**Comment by fabiocos** [comment]
@SiewYan if the update of the version with the old limited list of processes is nevertheless useful, I suggest to update this PR accordingly so as we may merge it, waiting for a solution to the problem of the large process library

**Comment by SiewYan** [comment]
Thanks @fabiocos for followup, I am including cms sherpa expert @GurpreetSinghChahal and Openloop author @jonaslindert

**Comment by SiewYan** [comment]
@fabiocos , I have disabled the excessive process libraries, reverting to lhc.coll with some relevant lib process for Top physics. @smuzaffar , could you trigger the test? 
Thanks!

**Comment by fabiocos** [comment]
please test workflow 534.0

**Comment by fabiocos** [comment]
@SiewYan @smuzaffar as far as I can see this is the backport of the master setup, even though the process list is now specified into a separate file (but its content corresponds to the standard master configuration).

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals
correct, now openloops do not generate few big libs (total size is 11GB) and it does not fail for aarch64.

**Pull request merged**
