### PR TITLE
Enable the sherpa interface to MCFM (with inbuild mcfm version)

### PR DESCRIPTION
**Pull request by thuer**

### CODE REVIEW

**Comment by thuer** [comment]
It is not installing MCFM as a new external, it just builds a temporary MCFM version where the needed library is then incorporated in the libSherpaMCFM.so and from then on the MCFM installation is not needed anymore

**Comment by bendavid** [comment]
+1
Ok sounds good.

**Comment by vciulli** [comment]
It is needed for H+2 jets NLO 
Thx @thuer

**Comment by ghost** [comment]
+1
Tested compilation, tested compilation of GeneratorInterface/SherpaInterface against it.
Merging now.

**Pull request merged**
