### PR TITLE
Backport MXNet and DeepBoostedJet models.

### PR DESCRIPTION
**Pull request by hqucms**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
backport of #4207

**Comment by slava77** [comment]
@fabiocos 
I see that the 10_2_5 build has already started without this external(s).
Are there some concerns remaining related to this external(s)?
Please clarify.
Thank you.

**Comment by fabiocos** [comment]
@slava77 as this PR does not concern only mxnet but also RecoBTag combined I preferred to link it to the integration of the CMSSW code, which is not part of 10_2_5 (pending its validation in 10_3_X)

**Comment by slava77** [comment]
On 9/13/18 9:35 AM, Fabio Cossutti wrote:
> @slava77
> as this PR does not concern only mxnet but also RecoBTag combined I
> preferred to link it to the integration of the CMSSW code, which is not
> part of 10_2_5 (pending its validation in 10_3_X)
> 

Thank you for the clarification.
Please note that the change in RecoBTag combined is only in the deepAK8
files [1].
The modifications are to suppress a warning message in the files which
are already in 10_2_X.

https://github.com/cms-data/RecoBTag-Combined/compare/V01-00-13...V01-00-14

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
