### PR TITLE
Include Boost.MPI (10.2.x backport)

### PR DESCRIPTION
**Pull request by fwyzard**
Include Boost.MPI:
  - add a dependency on OpenMPI
  - build boost with MPI support
  - add a new boost_mpi tool

Update OpenMPI to version 2.1.4.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #4255

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by mrodozov** [comment]
there is no gcc630 branch anymore, the remaining for 10_2 is only gcc7 now.

**Pull request closed without merging**
