### PR TITLE
geant4 10.02.p02: Backport fix of G4CutTube from Geant4 development

### PR DESCRIPTION
**Pull request by smuzaffar**
requested by @civanch https://github.com/cms-externals/geant4/pull/17

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , sorry, an extra class is needed to be backported G4GeomTools
Should I add it to closed PR or where?

**Comment by smuzaffar** [comment]
@civanch , you need to make a new PR

**Comment by smuzaffar** [comment]
please test
this PR now also include changes requested here https://github.com/cms-sw/cmsdist/issues/3103

**Comment by smuzaffar** [comment]
@civanch, do we need this in 92X?

**Comment by civanch** [comment]
@smuzaffar , this should improve CPU performance a bit and reliability of tracking in the new pixel. Unfortunately, tracker validation show many differences due to simulation history change. This is normal but a discussion with @davidlange6 is needed.

**Comment by davidlange6** [comment]
hi @civanch - has someone done a physics validation already?

**Comment by civanch** [comment]
Statistically calorimeter results agree (were check using limited number of events).

**Comment by davidlange6** [comment]
hi @civanch - as we discussed, please make a 93x PR. Thanks

**Comment by civanch** [comment]
@smuzaffar , @davidlange6 , #3149 is done for 93x, this PR may be closed.

**Pull request closed without merging**
