### PR TITLE
necessary changes for Herwig714 in CMSSW

### PR DESCRIPTION
**Pull request by Andrej-CMS**
to be tested with https://github.com/cms-sw/cmssw/pull/28649

### CODE REVIEW

**Comment by Andrej-CMS** [comment]
should I do the same PR, but for GCC700?

**Comment by smuzaffar** [comment]
We do not have gcc7 for 94X. We do have SLC7/CC7 builds but they use the same cmsdist branch.

**Comment by Andrej-CMS** [comment]
@smuzaffar 
Thanks a lot for clarifying! I was confused by this branch https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_9_4_X/gcc700

**Comment by smuzaffar** [comment]
yes that was a development branch, we are not building IBs or releases from that branch

**Comment by smuzaffar** [comment]
cms-sw/cmssw#28649 is closed , should we close this PR too?

**Comment by smuzaffar** [comment]
closing it as the cmssw PR is also closed. Please open a new one if this is still needed in 94X

**Pull request closed without merging**
