### PR TITLE
BuildRules: Fix for class version checks

### PR DESCRIPTION
**Pull request by smuzaffar**
See https://github.com/cms-sw/cmssw/pull/46678#issuecomment-2514223602
`edmCheckClassVersion` was move from `FWCore/Utilities` to `FWCore/Reflection`

New build rules 
- uses the correct path for `edmCheckClassVersion`
- fails if `edmCheckClassVersion` or `edmCheckClassTransients` are not found

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

this should fail with error like
```
>> Checking EDM Class Version for src/SimDataFormats/CaloAnalysis/src/classes_def.xml in libSimDataFormatsCaloAnalysis.so
error: class 'CaloParticle' has a different checksum for ClassVersion 4. Increment ClassVersion to 5 and assign it to checksum 2074797506
Suggestion: You can run 'scram build updateclassversion' to generate src/SimDataFormats/CaloAnalysis/src/classes_def.xml.generated with updated ClassVersion
gmake: *** [config/SCRAM/GMake/Makefile.rules:1875: tmp/el8_amd64_gcc12/src/SimDataFormats/CaloAnalysis/src/SimDataFormatsCaloAnalysis/libSimDataFormatsCaloAnalysis.so] Error 1

```

**Comment by smuzaffar** [comment]
type bugfix

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#46851

**Comment by makortel** [comment]
Mmh, these errors look concerning. E.g. `CTPPSDetId` was last changed in 2022 (in https://github.com/cms-sw/cmssw/pull/38886, and not in a way that should require a checksum update). I want to investigate a bit if e.g. https://github.com/cms-sw/cmssw/pull/45423 introduced some bug. For the record below is the full list of checksum errors
```
error: class 'CTPPSDetId' has a different checksum for ClassVersion 3. Increment ClassVersion to 4 and assign it to checksum 1554945820
error: class 'TotemRPDetId' has a different checksum for ClassVersion 3. Increment ClassVersion to 4 and assign it to checksum 1915602617
error: class 'CTPPSDiamondDetId' has a different checksum for ClassVersion 3. Increment ClassVersion to 4 and assign it to checksum 3253161212
error: class 'CTPPSPixelDetId' has a different checksum for ClassVersion 3. Increment ClassVersion to 4 and assign it to checksum 1640295022
error: class 'TotemTimingDetId' has a different checksum for ClassVersion 3. Increment ClassVersion to 4 and assign it to checksum 3647294361
error: class 'CaloTowerDetId' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 3039490998
error: class 'EBDetId' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 55396465
error: class 'EEDetId' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 55927906
error: class 'ESDetId' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 58407964
error: class 'EcalTrigTowerDetId' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 1597424810
error: class 'EcalScDetId' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 800615613
error: class 'EcalPnDiodeDetId' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 1385551474
error: class 'reco::ElectronSeed' has a different checksum for ClassVersion 13. Increment ClassVersion to 14 and assign it to checksum 438154954
error: class 'L2MuonTrajectorySeed' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 4137731643
error: class 'L3MuonTrajectorySeed' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 934859799
error: class 'reco::ConvBremSeed' has a different checksum for ClassVersion 12. Increment ClassVersion to 13 and assign it to checksum 1070104702
```

**Comment by smuzaffar** [comment]
locally checking out all these packages and getting https://github.com/cms-sw/cmssw/pull/46851/files changes did not show any errors. as cms-sw/cmssw#46851 is merged now, so I will trigger an IB and then rerun the tests

**Comment by makortel** [comment]
Using the same IB as the tests (CMSSW_15_0_X_2024-12-03-1100), I checked `DataFormats/CTPPSDetId/src/classes_def.xml` (containing `CTPPSDetId`, `CTPPSDiamondDetId`, `CTPPSPixelDetId`, `TotemRPDetId`, `TotemTimingDetId`) and `DataFormats/MuonSeed/src/classes_def.xml` (containing `L2MuonTrajectorySeed`, `L3MuonTrajectorySeed`) with `edmDumpClassVersion` and `edmCheckClassVersion`, and both scripts report the same checksum as are written in the `classes_def.xml` files.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
lets get this in DEVEL IBs

**Pull request merged**
