### PR TITLE
Upgrade pycurl from pip (to version: 7.43.0.3)

### PR DESCRIPTION
**Pull request by todor-ivanov**
!!! DO NOT MERGE !!!
Work in progress!

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 8402ea6f7cbe85f89e00ea1572dd71962651a8a1 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5438/test_8402ea6-20191217-212504.log" target="_blank">here</a>.

**Comment by todor-ivanov** [comment]
@smuzaffar thanks for the hint here: [1]. It does fix the issue with pycurl while trying to fetch it with pip. What we have as a problem, though, is a little bit deeper. And I think we've came to the point when we should start asking the experts here. The real problem is that pycurl is linked with libcurl and in our branch the version of curl is quite old (7.35) and has the 'c-ares' flag enabled, which is our actual culprit. We are afraid to just remove that because someone must have enabled that flag for a reason. What we would like to do is to upgrade 'libcurl' to the latest version, strip out the flag, find all the dependencies (which seems to be a lot) and request all the packages that might be affected to be tested with the new version. I already tried to take 'curl.spec' from here [2], or even just remove the flag, but in both cases the our environment does not build and breaks in 'cms+dqmgui+9.3.9' [3] or even some other places I have not inspected yet.

Can you please help us in building the environment and the dependency tree - finding all the afected pakages and solving this. Thanks in advance.

[1]
https://github.com/cms-sw/cmsdist/pull/5420#issuecomment-566500098

[2]
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_1_X/master/curl.spec

[3]
```
./boost/gil/extension/numeric/algorithm.hpp:70:38: warning: unused parameter '__first1' [-Wunused-parameter]
     static _Tp apply(_InputIterator1 __first1, 
                                      ^~~~~~~~
./boost/gil/extension/numeric/algorithm.hpp:71:38: warning: unused parameter '__first2' [-Wunused-parameter]
                      _InputIterator2 __first2, _Tp __init, 
                                      ^~~~~~~~
./boost/gil/extension/numeric/algorithm.hpp:72:40: warning: unused parameter '__binary_op1' [-Wunused-parameter]
                      _BinaryOperation1 __binary_op1,
                                        ^~~~~~~~~~~~
./boost/gil/extension/numeric/algorithm.hpp:73:40: warning: unused parameter '__binary_op2' [-Wunused-parameter]
                      _BinaryOperation2 __binary_op2) {
                                        ^~~~~~~~~~~~
In file included from ./DQM/serverext.cc:18:0:
./DQM/VisDQMTools.h: At global scope:
./DQM/VisDQMTools.h:110:20: warning: 'std::__cxx11::string unhexlify(const string&)' defined but not used [-Wunused-function]
 static std::string unhexlify(const std::string& s)
                    ^~~~~~~~~
c++ -D_GNU_SOURCE -D_DARWIN_C_SOURCE -DWITHOUT_CMS_FRAMEWORK=1 -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -U__DEPRECATED -fPIC -g -O2 -W -Wall -Wno-long-long -pedantic -std=c++17 -Wno-unused-local-typedefs -I. -I. -I/build/tivanov/w/tmp/BUILDROOT/6c934d8825bf101073bab399c8b303b6/build/tivanov/w/slc7_amd64_gcc630/cms/dqmgui/9.3.9-comp2/128/xinclude -I/build/tivanov/w/tmp/BUILDROOT/6c934d8825bf101073bab399c8b303b6/build/tivanov/w/slc7_amd64_gcc630/cms/dqmgui/9.3.9-comp2/128/include -I/build/tivanov/w/slc7_amd64_gcc630/external/classlib/3.1.3-comp/include -I/build/tivanov/w/slc7_amd64_gcc630/external/boost/1.57.0-comp2/include -I/build/tivanov/w/slc7_amd64_gcc630/external/python/2.7.13-comp/include/python2.7 -I/build/tivanov/w/slc7_amd64_gcc630/lcg/root/6.14.09-comp2/include -I/build/tivanov/w/slc7_amd64_gcc630/external/zlib/1.2.8/include -I/build/tivanov/w/slc7_amd64_gcc630/external/pcre/8.37/include -I/build/tivanov/w/slc7_amd64_gcc630/external/libpng/1.2.47/include -I/build/tivanov/w/slc7_amd64_gcc630/external/libjpg/8b/include -I/build/tivanov/w/slc7_amd64_gcc630/external/protobuf/3.5.2/include -I/build/tivanov/w/slc7_amd64_gcc630/external/jemalloc/5.2.0/include -shared -o Accelerator.so serverext.o DQMNet.o DQMError.o -Wl,-z,defs -L. -L. -L/build/tivanov/w/tmp/BUILDROOT/6c934d8825bf101073bab399c8b303b6/build/tivanov/w/slc7_amd64_gcc630/cms/dqmgui/9.3.9-comp2/128/xlib -L/build/tivanov/w/tmp/BUILDROOT/6c934d8825bf101073bab399c8b303b6/build/tivanov/w/slc7_amd64_gcc630/cms/dqmgui/9.3.9-comp2/128/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/classlib/3.1.3-comp/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/boost/1.57.0-comp2/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/python/2.7.13-comp/lib -L/build/tivanov/w/slc7_amd64_gcc630/lcg/root/6.14.09-comp2/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/zlib/1.2.8/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/pcre/8.37/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/libpng/1.2.47/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/libjpg/8b/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/protobuf/3.5.2/lib -L/build/tivanov/w/slc7_amd64_gcc630/external/jemalloc/5.2.0/lib -lDQMGUI -lclasslib -lpcre -lz -lpthread -lprotobuf -ldl -lrt -lboost_python -lpython2.7 -lpng
make: Target `all' not remade because of errors.
error: command 'make' failed with exit status 2
error: Bad exit status from /build/tivanov/w/tmp/rpm-tmp.1Un5eB (%build)


RPM build errors:
    Bad exit status from /build/tivanov/w/tmp/rpm-tmp.1Un5eB (%build)
```

**Comment by amaltaro** [comment]
Shahzad @smuzaffar you might want to wait for Todor's feedback here:
https://github.com/cms-sw/cmsdist/pull/5420#issuecomment-566880252

**Comment by smuzaffar** [comment]
@todor-ivanov , did you try enabling c-ares in new curl? With change [a] I was able to build our curl with c-ares [b]. https://github.com/cms-sw/cmsdist/pull/382 tells why c-ares were added . 

[a]
```
diff --git a/curl.spec b/curl.spec
index 09a5aa6..9097ca7 100644
--- a/curl.spec
+++ b/curl.spec
@@ -2,6 +2,7 @@
 Source: http://curl.haxx.se/download/%{n}-%{realversion}.tar.gz
 Requires: openssl
 Requires: zlib
+Requires: c-ares
 
 %prep
 %setup -n %{n}-%{realversion}
@@ -22,7 +23,8 @@ esac
   --with-ssl=${OPENSSL_ROOT} \
   --without-nss \
   --without-libssh2 \
-  --with-gssapi=${KERBEROS_ROOT}
+  --with-gssapi=${KERBEROS_ROOT} \
+  --enable-ares=${C_ARES_ROOT}
 
 make %{makeprocesses}
 

```

[b]
```
[muzaffar@cmsdev31 cmsdist]$ source ../w/slc7_amd64_gcc630/external/py2-pycurl/7.43.0.3-comp/etc/profile.d/init.sh 
[muzaffar@cmsdev31 cmsdist]$ python
Python 2.7.13+ (default, Dec 18 2018, 10:09:09) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> pycurl.version
'PycURL/7.43.0.3 libcurl/7.59.0 OpenSSL/1.0.1r zlib/1.2.8 c-ares/1.10.0'
>>> 
```

**Comment by smuzaffar** [comment]
and I was able to build dqmgui too ... so what is the actual issue you see in your builds?

**Comment by amaltaro** [comment]
Shahzad, our goal is to actually get rid of c-ares because it bypasses the DNS caching, thus potentially overloading the DNS servers.

Thanks for the pointer by the way. Now we know which services deserve special attention when we roll pycurl/libcurl changes in (without c-ares).

**Comment by muhammadimranfarooqi** [comment]
+1 to 8663043fbaaa9eecd00fbff44b25bdbf0c7e5905 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5438/test_8663043-20191218-211003.log" target="_blank">here</a>.

**Comment by todor-ivanov** [comment]
Hi Shahzad @smuzaffar. Thanks again. I actually managed to build with 'curl 7.59.0' and uploaded 'comp' environment in my repository. I had to delete my whole build directory and start from scratch. Something was obviously wrong there. The new rpms can be fetched from here [1], in case somebody wants to test them before we decide if we should merge this PR or this one [2]. 
FYI @amaltaro

[1]
http://cmsrep.cern.ch/cgi-bin/repos/comp.tivanov/slc7_amd64_gcc630?C=M;O=D

http://cmsrep.cern.ch/cmssw/repos/comp.tivanov/slc7_amd64_gcc630/8bf9f441cc82cd9455721410ddf265b481fc8682c4d011768040290819ec42bb/RPMS/ff/ff6abcfa375cc9450303f0dceb7cd8b5/external+py2-pycurl+7.43.0.3-comp-1-1.slc7_amd64_gcc630.rpm

http://cmsrep.cern.ch/cmssw/repos/comp.tivanov/slc7_amd64_gcc630/8bf9f441cc82cd9455721410ddf265b481fc8682c4d011768040290819ec42bb/RPMS/e6/e64226ee16b3691fe7e99884ed5ecbf8/external+curl+7.59.0-1-1.slc7_amd64_gcc630.rpm


[2]
https://github.com/cms-sw/cmsdist/pull/5420

**Comment by muhammadimranfarooqi** [comment]
+1 to 6474a24e5c0ae1e5a0215487fcb876066a3a8e27 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5438/test_6474a24-20191218-232504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Tests with central WMCore services and WMAgent are looking good with these changes.
```
>>> import pycurl
>>> pycurl.version
'PycURL/7.43.0.3 libcurl/7.59.0 OpenSSL/1.0.1r zlib/1.2.8'
>>> 
```

I suggest we discuss it in today's WMCore meeting and then make a wider announcement via web-interfaces. This will need to be tested thoroughly, especially on DBS.

**Comment by muhammadimranfarooqi** [comment]
@amaltaro @todor-ivanov 

Should I merge and include this PR in the coming CMSWEB release as well?

 Best
Imran

**Comment by todor-ivanov** [comment]
Hi @muhammadimranfarooqi ,
It should be either this one or  [1]. They will create conflict if merged together I beleive.

[1] https://github.com/cms-sw/cmsdist/pull/5420

**Comment by todor-ivanov** [comment]
@muhammadimranfarooqi  Sorry, I should have been more specific. It should be this one to merge (as we discussed in DMWM meeting), because this one also upgrades libcurl.

**Pull request merged**
