### PR TITLE
wmagent 1.1.8.patch3

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by h4d4** [comment]
-1 to 05c1e425e0c56d675fdcd1ca73f5a3b3deb54933 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3643/test_05c1e42-20171220-015504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 656b0dc426ba92ae2b0926b782b4309fd86107f9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3643/test_656b0dc-20171220-025504.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
merge

**Comment by h4d4** [comment]
+1 to 0b4b275c234311ea5fef656d08bc34a3962fafef on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3643/test_0b4b275-20171220-031504.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
ping

**Comment by smuzaffar** [comment]
let me check @ticoann  why comp-bot is not reacting

**Comment by ticoann** [comment]
@smuzaffar, Thanks

**Pull request merged**
