### PR TITLE
Remove file, migration to ROOT6 was done.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@vgvassilev , looks like this file is still in use here
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/gcc700/mctester.spec#L5
if this is not needed then please cleanup mctester.spec too.

**Comment by vgvassilev** [comment]
I do not know if we need it in that case. What does this path exactly patch? Some external library?

**Comment by vgvassilev** [comment]
@smuzaffar, I've removed the use but let's see if it works...

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@vgvassilev , looks like patch is needed to build mctester.

**Comment by davidlange6** [comment]
hi @vgvassilev - i thought mctester-cling.patch is going in the needed direction? (eg, the patch we discussed last week was to do exactly rootcint -> rootling)

**Comment by vgvassilev** [comment]
Yes, I got it now. I misunderstood the initial idea. Closing this one.

**Pull request closed without merging**
