### PR TITLE
HG1707 testbed

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to dc7c7d2d48a5157e0fac08adcf5cdb5e1394b1c5 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3122/test_dc7c7d2-20170624-055941.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
@ticoann @amaltaro Ticoan, Alan. Just to be sure, I should include this PR on the testbed deployment for tomorrow June 26th?

**Comment by ticoann** [comment]
Hi Lina, I am still trying to add one more feature. I will make the official request to https://gitlab.cern.ch/cms-http-group/doc/issues/67/ later today. 
Thanks,
Seangchan

**Comment by h4d4** [comment]
+1 to 38f71237895185643b693f65c7a186b73e88fbd2 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3122/test_38f7123-20170627-063506.log" target="_blank">here</a>.

**Pull request merged**
