### PR TITLE
t0.spec file for T0 version 3.1.5

### PR DESCRIPTION
**Pull request by LinaresToine**
PR to create new T0 release with latest version of WMCore

### CODE REVIEW

**Comment by LinaresToine** [comment]
please test

**Comment by LinaresToine** [comment]
Hello @arooshap, I do not think the 'please test' command was acknowledged. Maybe I'm missing something? Thanks!

**Comment by arooshap** [comment]
please test

**Comment by arooshap** [comment]
+1 to 1f0c8c85e72a71182fb8491915aadfab2e4fc19e on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8978/test_1f0c8c8-20240131-144502.log" target="_blank">here</a>.

**Comment by arooshap** [comment]
Hi @LinaresToine, I tried again and it worked.

**Comment by LinaresToine** [comment]
Hello @arooshap .  I updated the t0.spec file with the new release tag. The previous one did not pass the test. This one did pass the test so it should be good to go. Thank you very much!!

**Comment by LinaresToine** [comment]
please test

**Comment by arooshap** [comment]
+1 to aee7fe13891c11cf34dfd0f0832f22269ca5e654 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8978/test_aee7fe1-20240222-012002.log" target="_blank">here</a>.

**Comment by LinaresToine** [comment]
merge

**Pull request merged**
