### PR TITLE
Updated root to tip of branch v6-22-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by smuzaffar** [comment]
@makortel , We are trying to update root here and noticed that there are many failures like [a]. Any idea what could cause such issue?

[a]
```
---- Begin Fatal Exception 14-Oct-2020 14:14:54 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] While initializing meta data for branch: SiPixelRecHitedmNewDetSetVector_siPixelRecHits__RECO.
   Additional Info:
      [a] Fatal Root Error: @SUB=TProtoClass::FindDataMember
data member with index 0 is not found in class boost::any

----- End Fatal Exception -------------------------------------------------

----- Begin Fatal Exception 14-Oct-2020 14:15:00 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   Additional Info:
      [a] Fatal Root Error: @SUB=TProtoClass::FindDataMember
data member with index 0 is not found in class edm::TypeWithDict

----- End Fatal Exception ------------------------------------------------- 
```

**Comment by makortel** [comment]
I have no idea. @Dr15Jones, @pcanal would you have any suggestions?

**Comment by Dr15Jones** [comment]
FYI @pcanal

**Comment by smuzaffar** [comment]
by the way, we have seen the same errors while testing root master branch.

**Comment by smuzaffar** [comment]
the changes we are testing are https://github.com/root-project/root/compare/d6156de...e4cd9d3

**Comment by Dr15Jones** [comment]
The code in question is a private base class which has all of its data members set as `transient` in the classes_def.xml file

https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/DetSetVectorNew.h#L89

https://github.com/cms-sw/cmssw/blob/c024f9fb5b4ddf6515ed4ae87914ca8d57d83b1d/DataFormats/Common/src/classes_def.xml#L97

**Comment by pcanal** [comment]
There was change in the way we iterate through the data members so it looks like we overlooked something.  @smuzaffar can you tell me how to reproduce this with a debug version of ROOT?  Thanks.

**Comment by Dr15Jones** [comment]
@pcanal I believe all ROOT specific builds are done with debug. Try CMSSW_11_2_ROOT6_X_2020-10-12-2300.

**Comment by smuzaffar** [comment]
@Dr15Jones , @pcanal these changes are not in IBs. One needs to built it locally. @mrodozov can you pelase build (on cmsdevXX) this PR + build root in debug mode and provide instructions to @pcanal so that he can test it.

**Comment by mrodozov** [comment]
yes of course.

**Comment by mrodozov** [comment]
@pcanal 
- log on cmsdev20

```
scram p CMSSW_11_2_ROOT622_X_2020-10-13-2300
cp /build/mrodozov/root622/build_rootmaster/slc7_amd64_gcc820/lcg/root-toolfile/2.1-cms/etc/scram.d/* CMSSW_11_2_ROOT622_X_2020-10-13-2300/config/toolbox/slc7_amd64_gcc820/tools/selected/
cd CMSSW_11_2_ROOT622_X_2020-10-13-2300 ; cmsenv ; scram setup ; scram b
```
The this CMSSW release is this way setup with the root 622 with -DCMAKE_BUILD_TYPE=Debug 
It's still building, maybe in 30 minutes

**Comment by pcanal** [comment]
I was able to log it and set up the build area.   Could you give an example of command line leading to the error message?  Thanks.

**Comment by makortel** [comment]
E.g. `runTheMatrix.py -l 11634.0`, although it gives a little bit different error (in step2)
```
----- Begin Fatal Exception 14-Oct-2020 14:58:04 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=L2MuonProducer label='hltL2Muons'
   Additional Info:
      [a] Fatal Root Error: @SUB=TProtoClass::FindDataMember
data member with index 0 is not found in class tbb::internal::atomic_impl<unsigned long>

----- End Fatal Exception -------------------------------------------------
```
but should not require grid certificate to run.

**Comment by pcanal** [comment]
I must have missed an important setup step:
```
[pcanal@cmsdev20 src]$ pwd
/build/pcanal/cms-6314/CMSSW_11_2_ROOT622_X_2020-10-13-2300/src
[pcanal@cmsdev20 src]$ less 11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/step1_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA.log
----- Begin Fatal Exception 15-Oct-2020 16:08:07 CEST-----------------------
An exception of category 'DictionaryNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Calling ProductRegistryHelper::addToRegistry, checking dictionaries for produced types
Exception Message:
No data dictionary found for the following classes:

  edm::Wrapper<edm::TriggerResults>

```
What should I do to fix that?

**Comment by Dr15Jones** [comment]
@pcanal what were the exact commands you used?

**Comment by smuzaffar** [comment]
@pcanal , I would suggest to run `cmsenv` after `scram build` to rest the env
Do not forget to run `scram build` which creates the symlinks for the new root.

**Comment by pcanal** [comment]
I did:
```
  529  . /cvmfs/cms.cern.ch/cmsset_default.sh
  530  scram p CMSSW_11_2_ROOT622_X_2020-10-13-2300
  531  cp /build/mrodozov/root622/build_rootmaster/slc7_amd64_gcc820/lcg/root-toolfile/2.1-cms/etc/scram.d/* CMSSW_11_2_ROOT622_X_2020-10-13-2300/config/toolbox/slc7_amd64_gcc820/tools/selected/
  532  cd CMSSW_11_2_ROOT622_X_2020-10-13-2300 ; cmsenv ; scram setup ; scram b
  533  scram b
  536  runTheMatrix.py -l 11634.0
  537  ls .log
  541  less ./11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/step1_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA.log
  542  cd src
  543  runTheMatrix.py -l 11634.0
  544  less 11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/ step1_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA.log
  545  less 11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/step1_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA.log
  546  scram b
  547  runTheMatrix.py -l 11634.0
 548  less 11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/step1_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA.log
```

**Comment by smuzaffar** [comment]
looks like we need to build cmssw packages which depend on root. I would suggest to integrate it for ROOT622 IBs (which are identical to CMSSW_11_2_X IBs as we already have moved to root 6.22 for master branch). This will allow us a clean up and an IB for @pcanal to test.
Any objections @makortel  , @silviodonato

**Comment by makortel** [comment]
No objections from me.

**Comment by smuzaffar** [comment]
OK I am merging it and starting an IB now. 
@pcanal , I will report back here once we have an IB for you to test.

**Comment by smuzaffar** [comment]
@pcanal , you should be able to use CMSSW_11_2_ROOT622_X_2020-10-15-1100 IB to run tests. 
```
scram p CMSSW_11_2_ROOT622_X_2020-10-15-1100
cd CMSSW_11_2_ROOT622_X_2020-10-15-1100/
cmsenv
runTheMatrix.py -l 11634.0
cd 11634.0_*
gdb --args cmsRun step2_DIGI_L1_DIGI2RAW_HLT.py
```

**Comment by pcanal** [comment]
@smuzaffar Thanks.  I can indeed reproduce the problem :)

**Comment by pcanal** [comment]
The problem causing the ROOT error messages mentioned earlier is fixed by https://github.com/root-project/root/pull/6668

**Comment by smuzaffar** [comment]
thanks @pcanal , I am testing it for CMSSW ROOT6 IBs now 
https://github.com/cms-sw/cmsdist/pull/6328
 cms-sw/root#142

**Comment by smuzaffar** [comment]
@pcanal ,  root-project/root#6668 has fixed the issue but now we see the next one. I have tested latest root master +  root-project/root#6668 and now we get error [a] in few unit tests and relvals . See the details here https://github.com/cms-sw/cmsdist/pull/6328#issuecomment-713535003


[a]
```
----- Begin Fatal Exception 21-Oct-2020 12:49:29 CEST-----------------------
An exception of category 'InvalidReference' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Calling method for module PoolOutputModule/'FEVTDEBUGHLToutput'
Exception Message:
Inconsistency RefCoreStreamer: transient Ref or Ptr cannot be made persistent.
----- End Fatal Exception -------------------------------------------------
```

**Comment by pcanal** [comment]
@smuzaffar I am having trouble locating a test (failure) I can both run (I have no certificate) and shows the errors.  Can you help me?

**Comment by Dr15Jones** [comment]
@pcanal try
```
runTheMatrix.py -l 8.1
```
The 3rd process run should fail.

**Comment by pcanal** [comment]
I am (again) doing something wrong.  I did:
```
. /cvmfs/cms.cern.ch/cmsset_default.sh
scram p CMSSW_11_2_ROOT6_X_2020-10-20-2300 # number taken from the linke https://github.com/cms-sw/cmsdist/pull/6328#issuecomment-713535003 provided by @smuzaffar 
cd CMSSW_11_2_ROOT6_X_2020-10-20-2300/
cmsenv
runTheMatrix.py -l 8.1
```
and got what seems to be success:
```
processing relval_standard
processing relval_highstats
processing relval_pileup
processing relval_generator
processing relval_extendedgen
processing relval_production
processing relval_ged
ignoring relval_upgrade from default matrix
processing relval_2017
processing relval_2026
ignoring relval_identity from default matrix
processing relval_machine
processing relval_premix
Running up to 4 concurrent jobs, each with 1 thread per process

Preparing to run 8.1 BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18

# in: /build/pcanal/cms-6314/CMSSW_11_2_ROOT6_X_2020-10-20-2300 going to execute cd 8.1_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18
 cmsDriver.py BeamHalo_13TeV_cfi.py  --conditions auto:phase1_2018_cosmics -s GEN,SIM -n 500 --era Run2_2018 --eventcontent RAWSIM --relval 666000,100000 --scenario cosmics --datatier GEN-SIM --beamspot Realistic25ns13TeVEarly2018Collision --fileout file:step1.root  > step1_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18.log  2>&1


# in: /build/pcanal/cms-6314/CMSSW_11_2_ROOT6_X_2020-10-20-2300 going to execute cd 8.1_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18
 cmsDriver.py step2  --conditions auto:phase1_2018_cosmics -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2018 --scenario cosmics --datatier GEN-SIM-DIGI-RAW -n 10 --era Run2_2018 --eventcontent FEVTDEBUG --filein  file:step1.root  --fileout file:step2.root  > step2_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18.log  2>&1


# in: /build/pcanal/cms-6314/CMSSW_11_2_ROOT6_X_2020-10-20-2300 going to execute cd 8.1_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18
 cmsDriver.py step3  --conditions auto:phase1_2018_cosmics -s RAW2DIGI,L1Reco,RECO,ALCA:MuAlGlobalCosmics,DQM --scenario cosmics --datatier GEN-SIM-RECO,DQMIO -n 10 --era Run2_2018 --eventcontent RECOSIM,DQM --filein  file:step2.root  --fileout file:step3.root  > step3_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18.log  2>&1


# in: /build/pcanal/cms-6314/CMSSW_11_2_ROOT6_X_2020-10-20-2300 going to execute cd 8.1_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18
 cmsDriver.py step4  --conditions auto:phase1_2018_cosmics -s ALCA:TkAlBeamHalo+MuAlBeamHaloOverlaps+MuAlBeamHalo --datatier ALCARECO -n 1000 --era Run2_2018 --eventcontent ALCARECO --filein  file:step3.root  --fileout file:step4.root  > step4_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18.log  2>&1


# in: /build/pcanal/cms-6314/CMSSW_11_2_ROOT6_X_2020-10-20-2300 going to execute cd 8.1_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18
 cmsDriver.py step5  --conditions auto:phase1_2018_cosmics --filein file:step3_inDQM.root -s HARVESTING:dqmHarvestingFakeHLT --filetype DQM --scenario cosmics --era Run2_2018 --mc  -n 100  --fileout file:step5.root  > step5_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18.log  2>&1

8.1_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Oct 22 15:56:34 2020-date Thu Oct 22 15:48:28 2020; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

What did I miss?

**Comment by Dr15Jones** [comment]
@pcanal, maybe it is a threading problem. The directive I gave you uses only 1 thread. 
In the step3_*.py file you will find in the 8.1_BeamHalo_UP18+BeamHalo_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCABH_UP18+HARVESTCOS_UP18 directory, go and change the value

```
process.options.numberOfThreads = 4
process.options.numberOfStreams = 4
```

then run cmsRun with the editted configuration. 

If, instead, you want to rerun all of the jobs with more threads, do `runTheMatrix.py -l 8.1 -t 4` which will run them all using 4 threads.

**Comment by smuzaffar** [comment]
@pcanal , we have not merged the latest root changes in CMSSW_11_2_ROOT6_X_2020-10-20-2300  so that is why it is working. Tests are failing during PR tests. 
I can merge the PRs for cmssw  and build and IB for you to test

**Comment by Dr15Jones** [comment]
Ah, also, the problem is in the ROOT 6.22 build. Try

```
scram project CMSSW_11_2_ROOT622_X_2020-10-21-2300
```

**Comment by smuzaffar** [comment]
@pcanal , I now have merged https://github.com/cms-sw/cmsdist/pull/6330 (which is based on latest root 6.22 changes + plus your fix). I have started an IB so that we can run the tests again

**Comment by pcanal** [comment]
@smuzaffar I can confused:

> @pcanal , we have not merged the latest root changes in CMSSW_11_2_ROOT6_X_2020-10-20-2300

so that would make sense that I don't see the problem but then you linked: "See the details here [#6328 (comment)](https://github.com/cms-sw/cmsdist/pull/6328#issuecomment-713535003)" which mentions that release.

**Comment by smuzaffar** [comment]
@pcanal , PR tests are runing against a existing release. CMSSW_11_2_ROOT6_X_2020-10-20-2300 is a release based on working version of root. and PR tests use this release as base and use new root to run pr tests.

**Comment by pcanal** [comment]
Fair enough :) ... Can you remind me the step I need to follow to be testing the PR then :)

**Comment by smuzaffar** [comment]
@pcanal , once `CMSSW_11_2_ROOT622_X_2020-10-22-1600` release is available (hopefully in 3 to 4 hours)then you can do something like
```
scram p CMSSW_11_2_ROOT622_X_2020-10-22-1600
cd CMSSW_11_2_ROOT622_X_2020-10-22-1600
cmsenv
runTheMatrix.py -l 5.1
cd  5.1_*
gdb --args cmsRun TTbar_8TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_DIGI2RAW_L1Reco_RECO_EI_VALIDATION_DQM.py 
```

**Comment by pcanal** [comment]
Got it.  Thanks.

**Comment by smuzaffar** [comment]
@pcanal , did you manage to reproduce the issue?

**Comment by pcanal** [comment]
Yes, I can reproduce the problem.  But so far it is a ... challenging one.  Running the example (to the point of failure) is slowish in the debugger and so far, I have made little progress in determine why/how/when the 'transient' flag is set incorrect in one of the RefCoreWithIndex object and/or why a transient RefCoreWithIndex is added to the branch ("recoMuons_muons__RECO.obj")

**Comment by pcanal** [comment]
I found and resolved the problem (mostly).  See https://github.com/root-project/root/pull/6728.  This patch is sufficient to solve the problem if all enums that are stored as the key of an associative container are using the default size.  If some are using the non-default size, we also need the (upcoming) fix for https://github.com/root-project/root/issues/6725.

**Comment by pcanal** [comment]
Related PR merged into main branch and v6.22 patch branch.

**Comment by smuzaffar** [comment]
thanks @pcanal , I am testing latest v6.22 here
CMSSW master: https://github.com/cms-sw/cmsdist/pull/6359
CMSSW ROOT622: https://github.com/cms-sw/cmsdist/pull/6358

**Comment by smuzaffar** [comment]
@pcanal , looks like latest ROOT 6.22 updates broke our tests again [a] (e.g see https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-eac189/10459/runTheMatrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step3_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log ). Things were in good shape with ROOT v622 commit https://github.com/root-project/root/commit/db0b0f7b96c08fb1b7cc0c1c11e65c08784327a0 + your change for non-zero size enum. But with latest root v6.22 ( https://github.com/root-project/root/commits/v6-22-00-patches ) we have few crashes.  I have integrated https://github.com/cms-sw/cmsdist/pull/6358 for our ROOT622 IBs and in few hours we will have full tests results. 

[a]
```
#3  0x00002af504960a59 in sig_dostack_then_abort () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_ROOT622_X_2020-11-02-2300/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002af4f3e84290 in TStreamerInfo::AddReadAction (this=0x2af506a31000, readSequence=0x2af536e87740, i=0, compinfo=0x2af59072d588) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-1718c3698c5b60720e5f35ab8ee4efc5/root-6.22.03/io/io/src/TStreamerInfoActions.cxx:3317
#6  0x00002af4f3e830c9 in TStreamerInfo::Compile (this=0x2af506a31000) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-1718c3698c5b60720e5f35ab8ee4efc5/root-6.22.03/io/io/src/TStreamerInfoActions.cxx:3191
#7  0x00002af4f3e6c1ae in TStreamerInfo::BuildOld (this=0x2af506a31000) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-1718c3698c5b60720e5f35ab8ee4efc5/root-6.22.03/io/io/src/TStreamerInfo.cxx:2547
#8  0x00002af4f45f22ad in TClass::GetStreamerInfo (this=0x2af536bcd800, version=6) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-1718c3698c5b60720e5f35ab8ee4efc5/root-6.22.03/core/meta/src/TClass.cxx:4619
#9  0x00002af4f3e6fd3e in TStreamerInfo::ForceWriteInfo (this=0x2af531d13300, file=0x2af4fb7ede00, force=false) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-1718c3698c5b60720e5f35ab8ee4efc5/root-6.22.03/io/io/src/TStreamerInfo.cxx:3156
#10 0x00002af4f35f6aa1 in TTreeCloner::CopyStreamerInfos (this=0x7ffc12abb970) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-1718c3698c5b60720e5f35ab8ee4efc5/root-6.22.03/tree/tree/src/TTreeCloner.cxx:465
#11 0x00002af4f35f5ad0 in TTreeCloner::Exec (this=0x7ffc12abb970) at /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-1718c3698c5b60720e5f35ab8ee4efc5/root-6.22.03/tree/tree/src/TTreeCloner.cxx:202
#12 0x00002af551da8999 in edm::RootOutputTree::fastCloneTTree(TTree*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_ROOT622_X_2020-11-02-2300/lib/slc7_amd64_gcc820/libIOPoolOutput.so
#13 0x00002af551da8fa4 in edm::RootOutputTree::maybeFastCloneTree(bool, bool, TTree*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_ROOT622_X_2020-11-02-2300/lib/slc7_amd64_gcc820/libIOPoolOutput.so
#14 0x00002af551da2ec9 in edm::RootOutputFile::beginInputFile(edm::FileBlock const&, int) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_ROOT622_X_2020-11-02-2300/lib/slc7_amd64_gcc820/libIOPoolOutput.so
#15 0x00002af4f30ce9d8 in edm::Schedule::openOutputFiles(edm::FileBlock&) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_ROOT622_X_2020-11-02-2300/lib/slc7_amd64_gcc820/libFWCoreFramework.so
```

**Comment by pcanal** [comment]
@smuzaffar let me know when the build is ready to debug. (and please remind me one of the non-certificate reproducer :) )

**Comment by makortel** [comment]
@pcanal For the workflow @smuzaffar pointer to, `runTheMatrix.py -l 23234.0` should be sufficient (to run the GEN-SIM locally and not use any non-local input files).

**Comment by smuzaffar** [comment]
@pcanal , new IB CMSSW_11_2_ROOT622_X_2020-11-03-1100 is available but  only one workflow `4.17` failed ( https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/slc7_amd64_gcc820/CMSSW_11_2_ROOT622_X_2020-11-03-1100/pyRelValMatrixLogs/run/4.17_RunMinBias2011A+RunMinBias2011A+HLTD+RECODR1reHLT+HARVESTDR1reHLT+SKIMDreHLT/step5_RunMinBias2011A+RunMinBias2011A+HLTD+RECODR1reHLT+HARVESTDR1reHLT+SKIMDreHLT.log ) . Strangely for next IB (CMSSW_11_2_ROOT622_X_2020-11-03-2300) this workflow `4.17` passed. May be it is some thread related issue. Tests for 23h00 IB are still running, I will update again once we have full results of 23h00 IB

**Comment by Dr15Jones** [comment]
> Strangely for next IB (CMSSW_11_2_ROOT622_X_2020-11-03-2300) this workflow 4.17 passed. May be it is some thread related issue. 

The issue looks like a memory overwrite sort of problem to me. Such problems can 'move' around when using multiple threads since the order of new/delete is not consistent process to process.

The problem seems to be a corrupted virtual table called when a data product read from file is being deleted.

**Comment by pcanal** [comment]
@smuzaffar https://github.com/root-project/root/pull/6768 solves the problems and has been merged into the master and v6.22 branches.

**Comment by smuzaffar** [comment]
thanks @pcanal , I already have tested and intergeted it for today's 11h00 ROOT622 IB.
I confirm that the errors I was getting during PR tests are fixed. The IB is now running the tests and I already see that one workflow fails [a]. I will report back is there is a simple way to reproduce this

[a] workflow 1002.0 step3
 https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_ROOT622_X_2020-11-09-1100/pyRelValMatrixLogs/run/1002.0_RRD+RunMinBias2011A+RECODR1+COPYPASTE/step3_RRD+RunMinBias2011A+RECODR1+COPYPASTE.log#/274-274

```
#3  0x00002b53f04a0a59 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_ROOT622_X_2020-11-09-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b53e7e48fb6 in std::type_info::name (this=0x384b180000000000) at /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/include/c++/8.4.0/typeinfo:100
#6  0x00002b53e8e1c377 in TClass::GetClass (typeinfo=..., load=true) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/core/meta/src/TClass.cxx:3185
#7  0x00002b53e8e45078 in TIsAProxy::operator() (this=0x2b540ba13680, obj=0x2b5425981240) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/core/meta/src/TIsAProxy.cxx:117
#8  0x00002b53e8e1a607 in TClass::GetActualClass (this=0x2b5414f1f400, object=0x2b5425981240) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/core/meta/src/TClass.cxx:2573
#9  0x00002b53e85cdd84 in TBufferIO::WriteObjectAny (this=0x2b542ef9bc60, obj=0x2b5425981240, ptrClass=0x2b5414f1f400, cacheReuse=true) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/io/io/src/TBufferIO.cxx:504
#10 0x00002b53e8662500 in TGenCollectionStreamer::WriteObjects (this=0x2b5426c40800, nElements=14, b=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/io/io/src/TGenCollectionStreamer.cxx:984
#11 0x00002b53e866382e in TGenCollectionStreamer::Streamer (this=0x2b5426c40800, b=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/io/io/src/TGenCollectionStreamer.cxx:1449
#12 0x00002b53e8627cc8 in TCollectionStreamer::Streamer (this=0x2b540ba4d448, buff=..., pObj=0x2b543fa90760, onFileClass=0x0) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/io/io/src/TCollectionProxyFactory.cxx:166
#13 0x00002b53e85b7079 in TCollectionClassStreamer::Stream (this=0x2b540ba4d410, b=..., obj=0x2b543fa90760, onfileClass=0x0) at include/TCollectionProxyFactory.h:183
#14 0x00002b53e8e2681c in TClass::StreamerExternal (pThis=0x2b543780d800, object=0x2b543fa90760, b=..., onfile_class=0x0) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/core/meta/src/TClass.cxx:6613
#15 0x00002b53e7dc6cf1 in TClass::Streamer (this=0x2b543780d800, obj=0x2b543fa90760, b=..., onfile_class=0x0) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.22.03-b5939d52a0322c380ff1dab7b0540fed/root-6.22.03/core/meta/inc/TClass.h:568
```

**Comment by pcanal** [comment]
@mrodozov which version did you import?  There was a fatal bug solved today (In the function TStreamerInfo::SetClass:
```

void TStreamerInfo::SetClass(TClass *newcl)
{
   if (newcl) {
      // This is mostly (but not only) for the artificial "This" streamerElement for an stl collection.
      Update(fClass, newcl);
   }
   fClass = newcl;
}
```
is the correct code.

**Comment by smuzaffar** [comment]
I took your PR https://github.com/cms-sw/root/pull/146/commits on top of root's v6.22 branch. Looks like your PR was update after I merge. 
Ok, let me rsync from root 6.22 branch then

**Comment by pcanal** [comment]
I can't verify 1002.0 due to a DAS error.  I would need the input file and step3 script on cmsdev20.

**Comment by smuzaffar** [comment]
@pcanal , let me re-build the IB using latest latest root v6.22 branch and then we will see how it goes.

**Comment by smuzaffar** [comment]
@pcanal , wf 1002.0 step2 input and  config files are available under /afs/cern.ch/user/m/muzaffar/public/root622/1002.0
`cmsRun step3_NONE.py`  randomly produce thsi crash. 

As I wrote, this IB includes https://github.com/cms-sw/root/pull/146/commits which might not have all of your changes, So feel free to test the above otherwise wait till tomorrow when we have new IB based on latest root v6.22

**Comment by pcanal** [comment]
For the record, it was reported elsewhere that this problems are solved but there are other issues.  (https://github.com/cms-sw/cmssw/issues/30359#issuecomment-725634540)

**Pull request merged**
