### PR TITLE
[DD4hep] Update to latest commit v01-15x

### PR DESCRIPTION
**Pull request by smuzaffar**
the dd4hep plugin generator is renamed to `listcomponents_dd4hep` now

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by cvuosalo** [comment]
#32809 should fix the failure of the 11624.911 workflow. I will submit a PR to remove the failing `GeometryDTGeometryBuilderTestDriver` test.

**Comment by cvuosalo** [comment]
#32823 is fixing more files that are impacted by the DD4hep change in this PR. Several more files will also need to be fixed.

**Comment by cvuosalo** [comment]
#32834 disables the failing `GeometryDTGeometryBuilderTestDriver` unit test.

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#32823, cms-sw/cmssw#32834

**Comment by smuzaffar** [comment]
please test

**Comment by cvuosalo** [comment]
Discussion is underway with DD4hep and ROOT developers. A fix in either DD4hep or ROOT is expected soon.

**Comment by mrodozov** [comment]
@cvuosalo would you share with us the JIRA ticket or the github issue number ?

**Comment by cvuosalo** [comment]
The fix to the units-setting issue is coming in DD4hep PR #783 and ROOT PR #7165.

**Comment by cvuosalo** [comment]
DD4hep PR #783 and ROOT PR #7165 are now both merged.

**Comment by mrodozov** [comment]
this will allegedly work with latest root 622 commits so lets try it

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6657

**Comment by mrodozov** [comment]
@cvuosalo this integrated with the latest changes from ROOT 6.22 but it has many comparison differences
@slava77 I'd like to ask if the diffs are explicable/reasonable

**Comment by slava77** [comment]
>  @slava77 I'd like to ask if the diffs are explicable/reasonable

Reco comparisons are apparently significantly different only in the DD4HEP workflow 11634.911. A few spot-checks suggest that this has a different random number sequence either in SIM or later in DIGI; so, many distributions are somewhat different.

Based on 
> You potentially added 8145430 lines to the logs

This looks pretty bad.

A few files that I checked have a lot of 
```
%MSG-e Root_Error:  AfterModBeginStream TThreadExecutor::ParallelFor()  17-Feb-2021 18:07:39 CET BeforeEvents
tbb::global_control is limiting the number of parallel workers. Proceeding with 1 threads this time
```
these are not present in the baseline.

**Comment by mrodozov** [comment]
@slava77 I'm very sorry I did a mistake. sorry for the noise this is not tested with the proper root

**Comment by mrodozov** [comment]
no no, it's fine actually. it's the proper ROOT.
but the ROOT update itself is showing only 12 diffs (see https://github.com/cms-sw/cmsdist/pull/6657)

**Comment by makortel** [comment]
> ```
> %MSG-e Root_Error:  AfterModBeginStream TThreadExecutor::ParallelFor()  17-Feb-2021 18:07:39 CET BeforeEvents
> tbb::global_control is limiting the number of parallel workers. Proceeding with 1 threads this time
> ```

@Dr15Jones Seems that https://github.com/cms-sw/cmssw/pull/32782 turned the `tbb::global_control` messages (from elsewhere than `RTaskArenaWrapper`) from exception to ERROR level messages instead of INFO that was the goal of that PR.

**Comment by slava77** [comment]
> no no, it's fine actually. it's the proper ROOT.
> but the ROOT update itself is showing only 12 diffs (see #6657)

As I tried to summarize in https://github.com/cms-sw/cmsdist/pull/6612#issuecomment-780851666
Relevant differences are only in the DD4HEP workflow 11634.911.

I don't see anything bad for reco, the differences in 11634.911 are apparently happening earlier, in the SIM or perhaps DIGI stage.
I'm leaving it to @cms-sw/geometry-l2 to sign-off/confirm if this update is expected to introduce some differences.

**Comment by Dr15Jones** [comment]
> Seems that cms-sw/cmssw#32782 turned the tbb::global_control messages (from elsewhere than RTaskArenaWrapper) from exception to ERROR level messages instead of INFO that was the goal of that PR.

See https://github.com/cms-sw/cmssw/pull/32947

**Comment by mrodozov** [comment]
please test with #6657, cms-sw/cmssw#32947

**Comment by cvuosalo** [comment]
Unit tests and DD4hep workflow results look good. I think this PR can be merged. I will test it some more in parallel.
+geometry

**Comment by mrodozov** [comment]
+externals
alright then :) we need #6657 , too

**Pull request merged**
