### PR TITLE
Revert "Update frontier client to 2.8.13 and pacparser to 1.3.5."

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmsdist#1882

### CODE REVIEW

**Comment by davidlt** [comment]
Please, include the reason why it's being reverted.

**Comment by smuzaffar** [comment]
tests are failing with crashes 
https://cmssdt.cern.ch/SDT/cgi-bin//showAddOnLogs.py/slc6_amd64_gcc493/www/mon/7.6-mon-23/CMSSW_7_6_X_2015-10-12-2300/addOnTests/

```
#5  0x00007fb32f3c3602 in je_extent_tree_ad_remove (rbtree=rbtree@entry=0x7fb32f3dc000 , node=node@entry=0x0) at src/extent.c:38
#6  0x00007fb32f3c4dcd in je_huge_dalloc (ptr=, unmap=) at src/huge.c:219
#7  0x00000030fa8cf670 in freeaddrinfo () from /lib64/libc.so.6
#8  0x00007fb318674713 in frontier_FreeAddrInfo () from /build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-10-12-2300/external/slc6_amd64_gcc493/lib/libfrontier_client.so.2
#9  0x00007fb318672717 in frontierHttpClnt_resetwhenold () from /build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-10-12-2300/external/slc6_amd64_gcc493/lib/libfrontier_client.so.2
#10 0x00007fb31867c855 in frontier_postRawData () from /build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-10-12-2300/external/slc6_amd64_gcc493/lib/libfrontier_client.so.2
#11 0x00007fb31867c61c in frontier_getRawData () from /build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-10-12-2300/external/slc6_amd64_gcc493/lib/libfrontier_client.so.2
#12 0x00007fb318678d09 in frontier::Session::getData(std::vector > const&) () from /build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-10-12-2300/external/slc6_amd64_gcc493/lib/libfrontier_client.so.2
```

@DrDaveD is looking in to it

**Comment by davidlt** [comment]
So, jemalloc segfaulted? There is a new version of jemalloc with a number of bug fixes.

**Comment by DrDaveD** [comment]
No, the problem was a case of frontier client re-using memory after it was freed.  I will have a new release shortly.

**Comment by DrDaveD** [comment]
Upgraded requested in #1898

**Pull request merged**
