### PR TITLE
change pythia8 version from 180 to 183

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
tested by internal tests of Pythia8Interface

**Comment by bendavid** [comment]
+1
(For what it's worth)

**Comment by ktf** [comment]
@degano can you do the usual checks before we merge this? Thanks.

**Comment by ghost** [comment]
+1 
@ktf Tested on CMSSW_7_1_X_2014-02-12-0200, everything seems fine.

**Pull request merged**
