### PR TITLE
Changes for new DCAFPilot

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 624a7b89199474ec5759a45cf21fab61116f1e02 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2384/test_624a7b8-20160711-190510.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
-1 to 0e5fb816fcf4b7b3173bf33a92993d41caee2af0 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2384/test_0e5fb81-20160711-192509.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
-1 to 6893a94a6968dedd67b23a6d5dae97cf6c81869f on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2384/test_6893a94-20160712-194515.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
-1 to 008cc7eebe55abcad735cba82aa58592d268dc5c on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2384/test_008cc7e-20160712-220516.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
-1 to a5c025424dfd4e492b7d68c9365019ec7354ca78 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2384/test_a5c0254-20160712-224513.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
-1 to a5c025424dfd4e492b7d68c9365019ec7354ca78 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2384/test_a5c0254-20160713-103536.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to fb8402760abdf9918938af53d12a6711fdc91fcd on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2384/test_fb84027-20160713-145510.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
Merged!

**Pull request closed without merging**
