### PR TITLE
Update RecoEgamma-PhotonIdentification to 01-00-06

### PR DESCRIPTION
**Pull request by mrodozov**
Description: https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/7

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
about " please test"

IIUC, these tests are expected to fail. we still need a PR in CMSSW to adjust to the file renamings

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
lets restart it when we have the cmssw pr then

**Comment by slava77** [comment]
@guitargeek please clarify on the status of the CMSSW PR.

**Comment by guitargeek** [comment]
It's ready, but Egamma is waiting for the one who trained the photon ID to validate the MVA output.

What I can do myself is to get rid of the new ID in the PR, and we do a PR for the new weight files structure plus some other improvements and bug fixes in PhotonIdentification. Later, when I fnally get the egamma green light, I could follow up with the ID config file and the inclusion in Mini/NanoAOD.

**Comment by slava77** [comment]
On 7/30/18 6:58 AM, Jonas Rembser wrote:
> It's ready, but Egamma is waiting for the one who trained the photon ID
> to validate the MVA output.
> 
> What I can do myself is to get rid of the new ID in the PR, and we do a
> PR for the new weight files structure plus some other improvements and
> bug fixes in PhotonIdentification. Later, when I fnally get the egamma
> green light, I could follow up with the ID config file and the inclusion
> in Mini/NanoAOD.
> 

this sounds like a good plan.
Let's go ahead with this.

**Comment by guitargeek** [comment]
Okay! I set up a PR which implements the plan here: https://github.com/cms-sw/cmssw/pull/24131

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
