### PR TITLE
make dxr depend on sqlite so maybe it will get rebuilt when sqlite is…

### PR DESCRIPTION
**Pull request by gartung**
… rebuilt

### CODE REVIEW

**Comment by davidlt** [comment]
Note, we still need to rewrite Makefile for it to look into our SQLite3 location.

**Comment by gartung** [comment]
The trilite.patch addresses this.
https://raw.githubusercontent.com/cms-sw/cmsdist/IB/CMSSW_7_6_X/stable/trilite.patch

**Comment by davidlt** [comment]
I completely forgot about it, I was looking at plain unpatched version last night.

**Comment by davidlt** [comment]
This definitely LGTM.

**Comment by gartung** [comment]
@degano Can this be tested?

**Comment by ghost** [comment]
@gartung Yes, I'm on it.

**Comment by ghost** [comment]
@gartung I've tested it and found no issue. However is it necessary for dxr to also depend on llvm?

**Comment by davidlt** [comment]
Yes, because it uses Clang.

**Comment by gartung** [comment]
Further testing showed that the statement must be enclosed in a conditional otherwise the trlilite library load segfaults.

**Comment by gartung** [comment]
@davidlt @degano 
How can I compile this against sqlite 3.7. When I compile against sqlite 3.7 then the library does not segfault.

**Comment by davidlt** [comment]
I thought you said it works fine after recompiling, isn't it? Is it the same segfault like before?

**Comment by gartung** [comment]
Yes. It turns out I was compiling again sqlite 3.7 on one machine. When I tried to reproduce it on a VM running on my Mac the segfault happened again. There is some change to the sqlite_extenstion_init between sqlite 3.7 and sqlite 3.8 that I am trying to figure out.

On Oct 7, 2015, at 4:01 PM, davidlt <notifications@github.com<mailto:notifications@github.com>> wrote:

I thought you said it works fine after recompiling, isn't it? Is it the same segfault like before?

**Comment by gartung** [comment]
I can't make DXR work with sqlite 3.8. DXR needs to be compiled and used with sqlite 3.7. I can do that by hand when I need to run DXR.

**Pull request closed without merging**
