### PR TITLE
Update dd4hep.spec

### PR DESCRIPTION
**Pull request by mrodozov**
Pick latest commits from DD4Hep

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
@ianna I assume this is ok for you

**Comment by ianna** [comment]
@fabiocos - yes, I've asked @mrodozov to update it. Thanks.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
