### PR TITLE
Python packages update

### PR DESCRIPTION
**Pull request by davidlange6**
other than version bumps:
1) yoda misses its python path starting from 10_2_X. This is fixed now (we'll back port this fix)
2) hdf5 misses some libraries in its tool file. Those are added

### CODE REVIEW

**Comment by davidlange6** [comment]
note that tensorflow (rebuilt due to numpy) is now filling my home directory with cache files... so I believe this is fully tested but cannot be sure.. I'll file an issue about tensorflow seperately.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

hum no idea

**Comment by smuzaffar** [comment]
@davidlange6 , looks like you need to update xtl.spec to version 0.4.16 (which is requirement of xtensor)
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4345/30482/external/xtensor/0.17.4/log

```
+ cmake -DCMAKE_INSTALL_PREFIX=/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/tmp/BUILDROOT/1ac3ea0a2b5d931c39caff06ecb43ebf/opt/cmssw/slc6_amd64_gcc700/external/xtensor/0.17.4 -Dxtl_DIR=/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc700/external/xtl/0.4.1-gnimlf/lib64/cmake/xtl/
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/cc
-- Check for working C compiler: /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/c++
-- Check for working CXX compiler: /build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc700/external/gcc/7.0.0-omkpbe2/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building xtensor v0.17.4
CMake Error at CMakeLists.txt:31 (find_package):
  Could not find a configuration file for package "xtl" that is compatible
  with requested version "0.4.16".
```

**Comment by davidlange6** [comment]
Thanks - I just did -

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
seems we still have non-reproducible L1 codes?

**Comment by smuzaffar** [comment]
+externals

**Comment by davidlange6** [comment]
merge

**Pull request merged**
