### PR TITLE
Specs/changes to support x509-scitokens-issuer in cmsweb frontend

### PR DESCRIPTION
**Pull request by vkuznet**
This PR contains changes to cmsweb frontend to enable x509-scitokens support. This PR partially overlaps with Alan's PR: https://github.com/cms-sw/cmsdist/pull/4479 where we added plenty of specs to build crytography libs. To do that openssl spec was required to be changed to support ec and other functionality.

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 465fa7d961ced302a717e36471a8d17fa77f2efb on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_465fa7d-20181213-145008.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to dcdfb33d89091ac0c8bf22807f1ecb0aa6bcf1ae on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_dcdfb33-20181213-173007.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to af78517faf876caf454f5b93a51d0e184fb667e9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_af78517-20181213-191004.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 89ddce767f79173ed004e2536dadf238b025d425 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_89ddce7-20181214-002504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to a59cc7abfbe993604fdb70e285281de674646e32 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_a59cc7a-20181214-020505.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 603f48d7304f2138c13ddc5507fa55b50a03096a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_603f48d-20181214-141505.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to bae547885523e1ceb0d968053e187ff2221b565a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_bae5478-20181214-160506.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 4bcaaa126e4aa5add9d8a8acadd90e548de99446 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_4bcaaa1-20181214-165004.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 82375e82b8a62f7e234e93bc186cd7adec866409 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_82375e8-20181214-210505.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 2892eb43f90985369caa0239832fb7dc21b86690 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_2892eb4-20181214-225005.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
-1 to 78ef1a6e72be61ffe3618bd650cd77b3f1049d74 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_78ef1a6-20181215-154505.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 2be16efd7a5cdd9c59ba9392ba134ae4564befa3 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_2be16ef-20181217-192504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 96151de08dcac10f22505062983a2002970f873a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4584/test_96151de-20181217-211504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
It's interesting to see that we decided to hold off with my PR: https://github.com/cms-sw/cmsdist/pull/4479 until January 2019 because it had _major_ changes to the specs (openssl.spec) but merged this one with part of those changes...

**Comment by vkuznet** [comment]
Alan, it is special request by Brian to include x509 scitoken issuer
support into cmseeb that it can be tested with xrootd. By accident it
requires change to opens too to support crypto libraries. I reused you PR
for some parts. But we didn't change pyooenssl. So all questions to Brian.

**Comment by amaltaro** [comment]
@vkuznet Valentin, I've been working on building COMP packages with system openssl, and this PR provides `mod_gridsite24.spec` spec, which is the only spec I still didn't manage to build.

Before I spend more time trying to get that spec fixed/built, can I ask you how relevant are these changes regarding the current effort to migrate CMS services to sci-tokens? Are you still depending on these - especially mod_gridsite24.spec - or are you working on a different approach now?

**Comment by vkuznet** [comment]
This module is still required for apache based FEs which add support for scitokens. Therefore for cmsweb it is required. But it is also tight to our migration of token based authentication and GO based implementation of FEs. The later really depends on teams to verify cmsweb-auth.cern.ch (including DMWM/WMCore team). The sooner you'll do your job the sooner we can drop Apache and in fact this module.

**Pull request merged**
