### PR TITLE
Update ROCm to version 5.6.1

### PR DESCRIPTION
**Pull request by fwyzard**
Update ROCm to version 5.6.1:
  - see https://rocm.docs.amd.com/en/docs-5.6.1/release.html for the list of changes and fixes.

Add the ROCm packages to support OpenMP and Thrust:
  -  the OpenMP packages are required to compile any source that uses `#pragma omp ...` with `hipcc`;
  - the Thrust packages are needed for compatibility with CUDA, and are used by the HIP backend of PyTorch.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
> **Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c3f070/37928/summary.html **COMMIT**: [64510f3](https://github.com/cms-sw/cmsdist/commit/64510f32ccbf0758a2cffed0e6d78f109725b53c) **CMSSW**: CMSSW_14_1_X_2024-03-05-2300/el8_amd64_gcc12 **User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/9050/37928/install.sh` to create a dev area with all the needed externals and cmssw changes.
> ## External Build
> 
> I found compilation error when building:
> 
> Build successful rocm.
> (, , ) done
> Trying to install the rpm package external+rocm+5.6.1-6320ba1f36f64f70428881e859817e3e just built.
> Checking local path dependency for rpm package external+rocm+5.6.1-6320ba1f36f64f70428881e859817e3e just build.
> RPM installation stderr rocm:
> error: Failed dependencies:
> 	libffi.so.6()(64bit) is needed by external+rocm+5.6.1-6320ba1f36f64f70428881e859817e3e-1-1.x86_64
> 	libpython3.6m.so.1.0()(64bit) is needed by external+rocm+5.6.1-6320ba1f36f64f70428881e859817e3e-1-1.x86_64
> 
> Failed to install RPM for rocm
> Requested to quit.

@iarspider @aandvalenzuela do you have any idea why we see these errors ?

ROCm 5.6.1 should not be significantly different from ROCm 5.6.0, and that one used to build correctly.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for slc7_amd64_gcc12

**Comment by fwyzard** [comment]
please test for el9_amd64_gcc12

**Comment by fwyzard** [comment]
please test for el8_aarch64_gcc12

**Comment by fwyzard** [comment]
please test for el8_ppc64le_gcc12

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
@iarspider @aandvalenzuela @smuzaffar can any of you approve this for 14.1.x ?

**Comment by iarspider** [comment]
+externals

**Comment by smuzaffar** [comment]
>> libffi.so.6()(64bit) is needed by external+rocm+5.6.1-6320ba1f36f64f70428881e859817e3e-1-1.x86_64
>> libpython3.6m.so.1.0()(64bit) is needed by external+rocm+5.6.1-6320ba1f36f64f70428881e859817e3e-1-1.x86_64

> ROCm 5.6.1 should not be significantly different from ROCm 5.6.0, and that one used to build correctly.

@fwyzard , this is because the newly added `openmp-extras-devel-16.56.0.50601-93.el%{rhel}.%{_arch}.rpm ` is build against system python 3.6. Following are the two libs which are linked against python 3.6
```
llvm/lib-debug/ompd/ompdModule.so
llvm/lib-debug/ompd/ompdModule.cpython-36m-x86_64-linux-gnu.so
```

**Comment by fwyzard** [comment]
I see... I guess we should drop those specific files ?
The only alternative is that we start building ROCm from sources, so we can link our version of python.

**Pull request merged**
