### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Could this be cause by the removal of `RooCatType` at https://github.com/root-project/root/pull/12800?

**Comment by iarspider** [comment]
yes

**Comment by aandvalenzuela** [comment]
Thanks! I am working on a fix for this

**Comment by aandvalenzuela** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41737

**Comment by aandvalenzuela** [comment]
Tests `testDataFormatsScoutingRunX` are failing in IBs

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
