### PR TITLE
Remove Photos 215.5, Tauola 27.121.5

### PR DESCRIPTION
**Pull request by iarspider**
Split from https://github.com/cms-sw/cmsdist/pull/7763

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1
- This should have been tested with #37616
- The cumulative test succeeds in https://github.com/cms-sw/cmssw/pull/37616#issuecomment-1107885498

**Comment by perrotta** [comment]
merge

**Pull request merged**
