### PR TITLE
[14.2.X]Update tag for Geometry-TestReference to V00-16-00

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #9538

Needed for https://github.com/cms-sw/cmssw/pull/46792 ( which is already merged)

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = Geometry/MTDGeometryBuilder

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

update data file is only used by unit test (which now passed). Merge  it for 11h00 IB

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
