### PR TITLE
Add py3-pyjwt to dmwm specs

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
to 7f6186dca7945978f53148b2de3a46b1a582471f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7647/test_7f6186d-20220224-201003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
No dependencies beyond the standard library, that is great!

**Comment by amaltaro** [comment]
@muhammadimranfarooqi could you please trigger another test of this PR? Thanks

**Comment by muhammadimranfarooqi** [comment]
+1 to 7f6186dca7945978f53148b2de3a46b1a582471f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7647/test_7f6186d-20220414-192003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi Imran, do we need to trigger another test before it gets merged?

**Comment by amaltaro** [comment]
merge

**Pull request merged**
