### PR TITLE
Bump rucio-clients to version 1.23.6

### PR DESCRIPTION
**Pull request by amaltaro**
Besides the WMCor eco-system, it has an impact on the CRAB TaskWorker too. FYI @belforte 
Release notes: https://github.com/rucio/rucio/releases

### CODE REVIEW

**Comment by amaltaro** [comment]
@muhammadimranfarooqi could you please check whether cms-bot is running?

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

yes, currently building RPMs from logs.
```
Testing (#6241), WMAgent release candidate 1.4.0...
/build/dmwmbld/srv/state/dmwmbld/builds/6241
Cloning into 'cmsdist'...
HEAD is now at 9eb8f37 Move to HTCondor 8.9.7 (#5967)
Applying diff from URL: https://github.com/cms-sw/cmsdist/pull/6241.diff

Building RPMs...
```

**Comment by muhammadimranfarooqi** [comment]
+1 to 5e11ff0bb05d4ab7f336bb32ae260dd1bfb5a731 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6240/test_5e11ff0-20200915-160230.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi could you please merge this PR?

**Comment by amaltaro** [comment]
@muhammadimranfarooqi I still don't see the RPM in cmsrep. Is it possible that the change of node (for cmsrep) from yesterday is missing a final setup to let this node/user upload RPMs?

**Pull request merged**
