### PR TITLE
add workaround for some myproxy delegation problem

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by smuzaffar** [comment]
Please test

**Comment by smuzaffar** [comment]
please test

**Comment by belforte** [comment]
@smuzaffar I did not see you issuing the `+ externals` comment to dmwmbot this time. Are things OK never the less ?

**Comment by smuzaffar** [comment]
+externals
yes I am OK with the change, the runtime errors are due to another external.

**Pull request merged**
