### PR TITLE
[G4][geant4_only] Update geant4 to 10.7.2

### PR DESCRIPTION
**Pull request by mrodozov**
Get the latest G4 tag in the G4 IB

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by civanch** [comment]
@mrodozov , it is not clear why there is build error in RECO sub-library while only Geant4 version is changed.

**Comment by mrodozov** [comment]
@civanch we don't have a fresh IB that includes this change in mkFit . This evening we'll have it and restart the test
the IB used here is CMSSW_12_0_GEANT4_X_2021-06-15-2300 which doesn't include the change needed.
We don't build that IB everyday as we do for other releases

**Comment by mrodozov** [comment]
please test
now we have geant4 IB (since this evening)

**Comment by civanch** [comment]
@mrodozov , I think the test is now positive, the fact that simulations histories are different and we have no regression means, that we have to do private validation and PPD validation campaign. This PR may be merged to special branches GEANT4 and G4VECGEOM.

**Pull request merged**
