### PR TITLE
Herwig7: Finally arriving in CMSSW

### PR DESCRIPTION
**Pull request by mharrend**
Was originally PR #2457 , but original PR was closed and new PR was started as asked by @smuzaffar

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mharrend , looks like you have to re-base or cherry pick the commits in gcc530. Current changes have conflicts with gcc530 branch

**Comment by mharrend** [comment]
@smuzaffar Could you please help me with the re-base / cherry pick?
I have tried to do it by myself creating the mharrend:cms-sw-IB/CMSSW_8_1_X/gcc530 branch but I still get a merge error.
The branch mharrend:cms-sw-IB/CMSSW_8_1_X/gcc530 is directly derived from the cmssw branch and I only copied the 10 files which need to be changed to it. Honestly, I do not understand why still a merge error occurs since I have created a new commit.
Any help will be appreciated.

**Comment by mharrend** [comment]
@smuzaffar  I do not mind if you create a branch yourself and just copy my 10 files from the mharrend:cms-sw-IB/CMSSW_8_1_X/gcc530:
-  new file:   herwigpp-missingBoostMTLib.patch
-  new file:   madgraph5amcatnlo-compile.patch
-  new file:   madgraph5amcatnlo-config.patch
-  new file:   madgraph5amcatnlo-toolfile.spec
-  new file:   madgraph5amcatnlo.spec
-   modified:   herwigpp-toolfile.spec
-   modified:   herwigpp.spec
-   modified:   lhapdf.spec
-   modified:   thepeg-toolfile.spec
-   modified:   thepeg.spec

I would be just glad if we could finally implement Herwig7 as soon as possible.

**Pull request closed without merging**
