### PR TITLE
[10.6.X] Update MXNet to 1.5.0

### PR DESCRIPTION
**Pull request by hqucms**
Backport of https://github.com/cms-sw/cmsdist/pull/5148 to 10_6_X. 

This will be needed for the backport of https://github.com/cms-sw/cmssw/pull/28902.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
Backport of #5148

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
