### PR TITLE
[14_0_X] Update tag for RecoBTag-Combined to V01-22-00

### PR DESCRIPTION
**Pull request by hqucms**
Backport of https://github.com/cms-sw/cmsdist/pull/9139.
Needed by https://github.com/cms-sw/cmssw/pull/44660.

### CODE REVIEW

**Comment by hqucms** [comment]
backport of https://github.com/cms-sw/cmsdist/pull/9139

**Comment by hqucms** [comment]
please test

**Comment by rappoccio** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
