### PR TITLE
Update LLVM to version 10.0.0 (plus bugfixes)

### PR DESCRIPTION
**Pull request by fwyzard**
Update LLVM to version 10.0.0, plus
  - [ELF] Fix a null pointer dereference when --emit-relocs and --strip-debug are used together
  - [llvm-objcopy] Improve tool selection logic to recognize llvm-strip-$major as strip
  - Bump version to 10.0.1
  - Add yaml defintions for CI tests with GitHub Actions
  - Use FinishThunk to finish musttail thunks
  - [CodeGen] Fix sinking local values in lpads with phis
  - [COFF] Don't treat DWARF sections as GC roots
  - [DAGCombine] Fix splitting indexed loads in ForwardStoreValueToDirectLoad()
  - Teach TreeTransform to substitute into resolved TemplateArguments.
  - [ELF][test] Rename SHF_LINK_ORDER related "metadata" to "linkorder"
  - [ELF][test] Improve linkerscript/linkorder.s
  - [ELF] Allow SHF_LINK_ORDER and non-SHF_LINK_ORDER to be mixed
  - [SimplifyCFG]  Skip merging return blocks if it would break a CallBr.
  - [X86][SSE] combineX86ShufflesConstants - early out for zeroable vectors (PR45443)
  - add release notes for ffp-model and ffp-exception-behavior
  - [CodeView] Align type records on 4-bytes when emitting PDBs
  - [PowerPC] Update alignment for ReuseLoadInfo in LowerFP_TO_INTForReuse

Cherry-pick CMS specific changes:
  - Skip calling the gcc compiler.
  - Update scan-build to always remove working dir from path
  - Add CMS custom c++11 attributes

Update IWYU accordingly.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
Let's see if this works ...

**Comment by fwyzard** [comment]
Note that I did not update the CMSCodeChecker .

**Comment by smuzaffar** [comment]
@fwyzard , we already have a PR open for with https://github.com/cms-sw/cmsdist/pull/5708

**Comment by fwyzard** [comment]
Ah, sorry - I didn't see any llvm 10 banch in th cms-external repository, but nod I do.

Actually, cms/release/10.x/7899a11 seems based on the clang master rather than the 10.0.x branch ?

**Comment by smuzaffar** [comment]
No idea why @mrodozov created the branch based on llvm master. We can move to cms/release/10.x/92d5c1b . Can you please fix include "Adjust CMS additions to new constructors and methods" fix too ( https://github.com/cms-externals/llvm-project/commit/b7fd81c2a6bd6ef0b9bc0742667ec21649b6b159 ) ?

**Comment by fwyzard** [comment]
Done.

I've actually squashed the second commit to make it easier to cherry-pick the changes in the next updates.

**Comment by smuzaffar** [comment]
thanks @fwyzard , I have updated https://github.com/cms-sw/cmsdist/pull/5708 to use the correct branch and commits. I am closing this PR as https://github.com/cms-sw/cmsdist/pull/5708 contains fixes for other tools too.

**Comment by fwyzard** [comment]
Sure, no problem.

**Comment by mrodozov** [comment]
`No idea why @mrodozov created the branch based on llvm master.`
I took clang_10 first but then the build failed, and when I was searching how to fix it I found this 
https://github.com/include-what-you-use/include-what-you-use/commit/53487d209729d5781007dc0fd6076dc585cb3727
which as you can see is only available in master

**Comment by smuzaffar** [comment]
you can take include-what-you-use from master but keep llvm from clang_10

**Comment by fwyzard** [comment]
let me know if that doesn't work, I guess I can make a separate PR for IWYU to backport the fix to the clang 10.0 branch

**Pull request closed without merging**
