### PR TITLE
Replace MADGRAPH5AMCATNLO_ROOT

### PR DESCRIPTION
**Pull request by smuzaffar**
sync changes from IB/CMSSW_11_2_X/cc8 branch

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test
FYI @mrodozov , this shoudl resolve the merge conflicits too

**Comment by mrodozov** [comment]
One patch was removed for cc8
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/cc8/madgraph5amcatnlo.spec#L9
patches are 2 here:
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/madgraph5amcatnlo.spec

**Comment by smuzaffar** [comment]
cc8 uses version 2.6.7 so yes patch might have removed there

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
