### PR TITLE
added rust 1.57.0

### PR DESCRIPTION
**Pull request by smuzaffar**
This is needed to build cryptography python package from sources

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
Just curious, what requires rust?

**Comment by smuzaffar** [comment]
python package `cryptography` requires it when build from sources ( see https://github.com/cms-sw/cmsdist/pull/7537 ) . Although `cryptography` prebuild wheels are available but they are for newer version of OpenSSL and also there is no wheel for powerPC. So we have to build it from sources and this requires rust.

**Pull request merged**
