### PR TITLE
Add libunwind dependency on zlib.

### PR DESCRIPTION
**Pull request by gartung**
Changes between libunwind v1.4 and v1.5 
https://github.com/libunwind/libunwind/compare/v1.4.0...v1.5
may include a dependency on libz.so. 
Since we use our own libz.so libunwind.so should be linked against it.

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
please test

**Comment by mrodozov** [comment]
please test
the last IB will have https://github.com/cms-sw/cmssw/pull/33474

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
