### PR TITLE
sqlAlchemy updated version to 0.9.6

### PR DESCRIPTION
**Pull request by jmonkevicius**
Updated sqlalchemy from 0.5.2 to 0.9.6 version.

Before using this change, the patch to WMCore must be installed: https://github.com/dmwm/WMCore/pull/5286

It was tested only in SLC6 and pushed to comp_gcc481 branch.

@amaltaro @juztas @hufnagel

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 8e29ed3b182f89d2cf2dbfeb91be115ba2fb548a on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
Thanks Jonas.

Provided the wmcore fixes that are needed together to work with this new sqlalchemy don't break anything on the SLC5 land, I'd say we need to include it on our SLC6 branch asap in order to have our services validated yet in time for the HG1410 deployment cycle.

**Comment by hufnagel** [comment]
Check with @amaltaro on that, he validated the wmcore fixes with SLC5 and @ticoann has already merged them. Once the SLC6 wmagent spec is updated to point at the new tag containing the wmcore fixes, the new sqlalchemy can go into the SLC6 branch I would say.

**Comment by geneguvo** [comment]
Ok. Great!

**Comment by amaltaro** [comment]
SLC5 with the current sqlAlchemy (0.5.2) + the wmcore patch looks fine from my tests. Since this change is only for gcc481, there is no need to test the new sqlAlchemy for SLC5.

**Comment by jmonkevicius** [comment]
Wrong pull request

**Pull request closed without merging**
