### PR TITLE
Drop legacy MC generators

### PR DESCRIPTION
**Pull request by iarspider**
@cms-sw/generators-l2 We would like to drop the following MC generators:

* cascade
* charybdis
* herwig 6.520
* jimmy
* photos 215.5
* ~~pythia6~~
* ~~hydjet 1.9.1~~
* tauola 27.121.5
* toprex

These are ancient and not developed anymore

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
(hydjet++ still requires pythia6 and pyquen)

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
assign generators

@iarspider , [build logs](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7f7900/23787/build-logs/) shows that many of these are still in use. 

@cms-sw/generators-l2 , can you please confirm that these generators are still needed in cmssw?

**Comment by Saptaparna** [comment]
@mkirsano and @SiewYan 

It should be ok to remove these generators:

- cascade
- charybdis
- herwig 6.520
- jimmy
- photos 215.5
- hydjet 1.9.1
- tauola 27.121.5
- toprex

Please let me know if you foresee issues, otherwise, I'm happy to sign it.

**Comment by SiewYan** [comment]
@Saptaparna I do not have an opinion on those legacy generators, maybe @mkirsano can comment.

**Comment by smuzaffar** [comment]
@mkirsano any objections?

**Comment by mkirsano** [comment]
I had only doubts about cascade, so I asked the responsible person. It is OK to remove it.

**Comment by iarspider** [comment]
@Saptaparna @mkirsano @SiewYan thanks. Is hydjet++ used, or can it also be dropped? It will allow dropping pythia6 and pyquen.

**Comment by agrohsje** [comment]
We shouldn't remove hydjet++ (and so P6). This is e.g. needed by HIN group.

**Comment by iarspider** [comment]
@agrohsje noted.

**Comment by iarspider** [comment]
The following PRs for main cmssw repository remove usage of legacy generators:

* cascade: https://github.com/cms-sw/cmssw/pull/37611
* charybdis: could not find any references to it in cmssw
* herwig 6.520, jimmy: https://github.com/cms-sw/cmssw/pull/37612
* photos 215.5, tauola 27.121.5: https://github.com/cms-sw/cmssw/pull/37616
* hydjet 1.9.1: https://github.com/cms-sw/cmssw/pull/37620
* toprex: the only non-text references I could find are these: [1](https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Pythia6Interface/src/Pythia6Service.cc#L167), [2](GeneratorInterface/Pythia6Interface/src/txgive.F). Not sure how to handle these.

**Comment by stahlleiton** [comment]
Hi @iarspider ,

Was the removal of Hydjet 1.9 discussed in a meeting?
We still heavily use this generator in the HIN PAG (see the minimum bias request for 2018 PbPb in https://cms-pdmv.cern.ch/mcm/requests?prepid=HIN-HINPbPbAutumn18GS-00033&page=0&shown=127) and plan to make the transition to Hydjet++ soon, but we still need the old generator to prepare samples for the Run 3 PbPb data taking.

**Comment by iarspider** [comment]
Hi @stahlleiton,

no, it was not discussed. Sure, we can keep hydjet 1.9.

**Comment by iarspider** [comment]
Splitting into separate PRs as suggested by Shahzad.

**Comment by agrohsje** [comment]
dear @stahlleiton. can you comment on  what is missing to have hydjet++   for run 3? not pushing to remove 1.9, i am just trying to understand where we are. i assumed that this is ready as priority was very high (and we are discussing already since a bit).

**Comment by stahlleiton** [comment]
We are currently producing samples with Hydjet++ and will start a full study comparing Hydjet vs Hydjet++ within the HIN group.

**Comment by agrohsje** [comment]
Thanks. Maybe nice to summarize at some point in a GEN meeting? I know it is very special but could still be interesting to see. @cms-sw/generators-l2, what do you think?

**Comment by stahlleiton** [comment]
Sure, we can present the results in a GEN meeting once the study is done.

**Pull request closed without merging**
