### PR TITLE
WMCore patch release 2.0.0.cmsweb1 and WMAgent 1.5.7.patch2; Bump dbs3-client to 4.0.6

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes https://github.com/dmwm/WMCore/issues/10983

Summary of changes is the following:
* bump py3-dbs3-client version to `4.0.6`
* make new patch release for WMAgent: `1.5.7.patch2`
* make new patch release for WMCore central services: `2.0.0.cmsweb1`

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to d0f0fea00ab10481714020f247a523500bf1d5a9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7614/test_d0f0fea-20220209-202003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

It failed

**Comment by amaltaro** [comment]
I am waiting for the logs to become fully available to see what went wrong. I just double-checked all tags mentioned here and they have been properly created in the repository, so I am unsure why it failed.

**Comment by amaltaro** [comment]
Okay, error was in the py3-dbs3-client spec, which no longer has multiple setup.py scripts:
```
+ mv setupPypi.py setup.py
mv: cannot stat 'setupPypi.py': No such file or directory
```

I updated this PR and it should trigger the build bot once again.

**Comment by muhammadimranfarooqi** [comment]
+1 to a59d7ab164629e2f1ddab0a141920466ff4e2e88 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7614/test_a59d7ab-20220209-204502.log" target="_blank">here</a>.

**Pull request merged**
