### PR TITLE
[10.6] Backport onnxrt 1.3.0 to 10_6

### PR DESCRIPTION
**Pull request by mrodozov**
please test
I kept eigen in the toolfile but removed protobuf. 
I don't see the direct requirement for eigen as there was none, maybe in cmssw ? 
anyway, onnxrt is building with it's own protobuf (3.11.3)

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov , please check if the onnx toolfile is correct, I see there are build error
[a]
```
16:45:21 + scram setup /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2020-06-04-1100/config/toolbox/slc7_amd64_gcc700/tools/selected/onnxruntime.xml
16:45:21 
16:45:21 Finding a value for ONNXRUNTIME_BASE:
16:45:21 
16:45:21 	Checks [OK] for /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc700/external/onnxruntime/1.3.0-a4c94c
16:45:21 
16:45:21 Finding a value for INCLUDE:
16:45:21 
16:45:21 	Checks [OK] for /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc700/external/onnxruntime/1.3.0-a4c94c/include
16:45:21 
16:45:21 Finding a value for LIBDIR:
16:45:21 
16:45:21 	Checks [FAIL] for /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc700/external/onnxruntime/1.3.0-a4c94c/lib64
16:45:21 **** ERROR: No such file or directory: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc700/external/onnxruntime/1.3.0-a4c94c/lib64
16:45:21      SCRAM does not allow prompting for user input anymore.
16:45:21      Please fix the tool file for "onnxruntime" and provide a valid value for "LIBDIR".
```

**Comment by mrodozov** [comment]
please test
I'm removing eigen from the toolfile. 1.3 is not using it

**Comment by mrodozov** [comment]
@hqucms we'll need the cmssw part to test with this

**Comment by hqucms** [comment]
@mrodozov Thank you very much!

I created https://github.com/cms-sw/cmssw/pull/30123 to add the CMSSW part.

**Comment by hqucms** [comment]
@mrodozov @smuzaffar 
I think this version of ONNXRuntime should be good to integrate -- everything runs fine w/ https://github.com/cms-sw/cmssw/pull/30123 and there do not seem to be any conflict between onnxrt's internal protobuf and the CMSSW one. The few small differences are only at numerical precision level due to switch from TF/MXNet to onnxrt.

**Comment by mrodozov** [comment]
+externals 
merging this before cms-sw/cmssw#30123 won't break anything

**Comment by slava77** [comment]
@cmsbuild please test

just to check how this runs by itself

**Comment by silviodonato** [comment]
+1

**Comment by mrodozov** [comment]
abort

**Pull request merged**
