### PR TITLE
add professor2

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by iahmad-khan** [comment]
@mkirsano did you successfuly build these specs locally?

**Comment by mkirsano** [comment]
I did not manage to test locally because it starts to recompile many packages and fails somewhere. So I just took the PR from 81X. Is it possible to use some other branch so that it does not recompile unchanged packages?

**Comment by mkirsano** [comment]
eigen was upgraded to 3.3.0 as compared to 81X, it has additional level in includes so that users don't have tedious time. The new commit should fix the problem, though I still cannot build locally, I have errors like
* The action "fetch-external+py2-pyparsing+2.1.10" was not completed successfully because Traceback
result = item[0](*item[1:])
File "PKGTOOLS/cmsBuild", line 2624, in fetchSourcesNew
File "PKGTOOLS/cmsBuild", line 469, in download
KeyError: 'pip'

**Comment by smuzaffar** [comment]
@mkirsano , looks like you are using an old pkgtools. Please update it to head of V00-30-XX branch

**Comment by mkirsano** [comment]
Thanks, local build is OK now.

**Comment by iahmad-khan** [comment]
please test

**Comment by davidlange6** [comment]
Hi @mkirsano - I presume we can take v1.0 of sympy from https://pypi.python.org/pypi/sympy/1.0? We have pip support in CMSSW now.

**Comment by mkirsano** [comment]
Hello, David, it seems that it requires additional dependency: mpmath package with a version >= 0.19.
Can we simply request the addition of py2-sympy to CMSSW so that it is done professionally? After that we add professor2

**Comment by davidlange6** [comment]
I think so - I'll work on adding sympy today.

**Comment by davidlange6** [comment]
Hi @mkirsano could you rebase this pr (also for 91x instead of 90x). Thanks

**Pull request closed without merging**
