### PR TITLE
zlib: experimental changes (SSE4.2, PCLMUL, AVX2)

### PR DESCRIPTION
**Pull request by iahmad-khan**
The following is a mix of Cloudfare + Brian + orignal zlib. Some
internal functions are implemented with SSE4.2, PCLMUL and AVX2.
Thos are picked at load time. This still builds on "generic" machine.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by davidlange6** [comment]
seems this one is ready to merge?

**Comment by davidlt** [comment]
No, this should be built only for x86_64, for aarch64 / ppc64le we should grab later 1.2.11 original version. We have discussed it, but don't have the changes prepared.

**Comment by davidlange6** [comment]
ok, that was not obvious from the thread

**Comment by smuzaffar** [comment]
closing in favor of #2806

**Pull request closed without merging**
