### PR TITLE
draft hepmc with cmake; cleanup old patches

### PR DESCRIPTION
**Pull request by davidlange6**
Needs to be updated with the correct repository when cms-externals/hepmc#2 is merged.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
you can use cms-externals/hepmc#2 as additional PR here and keep the default source
`please test with cms-externals/hepmc#2` should work

**Comment by davidlange6** [comment]
Hum, good to know - but how does this predict the commit hash?

**Comment by davidlange6** [comment]
looks like rivet was missing a build requires dependency on auto tools

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
@civanch @smuzaffar - I don't fully understand the reason behind this error message. hepevt_ is not defined in either the .a or .so in the existing or new hepmc. libHepMCfio* has undefined hepmc_ symbols (as expected). Do you have ideas as to the cause? A missing dependency in cmssw? 

As the existing hepmc has no .so I will delete them as a possible workaround..

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , yes look like `hepmc_` is not defined for even existing hepmc build but as we only have static libs so when we link hepmc in to cmssw then we only link the functions we use in cmssw. That is why we do not see these errors in our existing build. 

linking against shared libs is different story, one need to have all function defined (even if you never call them).

**Comment by davidlange6** [comment]
Ok, so my “fix” will work… it would be nice to eventually keep the so libs too..

**Comment by mrodozov** [comment]
> Hum, good to know - but how does this predict the commit hash?

I don't think it's predicting what it does is to get the PR branch head, and in this case the commit will be the PR head.

```
19:27:10 + pushd llvm-project
19:27:10 + git pull git://github.com/cms-externals/llvm-project.git gartung-esrgetcheck
19:27:11 From git://github.com/cms-externals/llvm-project
19:27:11  * branch            gartung-esrgetcheck -> FETCH_HEAD
19:27:13 Checking out files:  40% (2/5)   
Checking out files:  60% (3/5)   
Checking out files:  80% (4/5)   
Checking out files: 100% (5/5)   
Checking out files: 100% (5/5), done.
19:27:14 Updating 9ac43ce..18f656c
19:27:14 Fast-forward
19:27:14  clang-tools-extra/clang-tidy/cms/CMSTidyModule.cpp |  3 +
19:27:14  clang-tools-extra/clang-tidy/cms/CMakeLists.txt    |  3 +-
19:27:14  .../clang-tidy/cms/ESRecordGetCheck.cpp            | 91 ++++++++++++++++++++
19:27:14  .../clang-tidy/cms/ESRecordGetCheck.h              | 40 +++++++++
19:27:14  .../checkers/cms-eventsetuprecord-get.cpp          | 99 ++++++++++++++++++++++
19:27:14  5 files changed, 235 insertions(+), 1 deletion(-)
19:27:14  create mode 100644 clang-tools-extra/clang-tidy/cms/ESRecordGetCheck.cpp
19:27:14  create mode 100644 clang-tools-extra/clang-tidy/cms/ESRecordGetCheck.h
19:27:14  create mode 100644 clang-tools-extra/test/clang-tidy/checkers/cms-eventsetuprecord-get.cpp
```

you can see this PR that's still open:
https://github.com/cms-externals/llvm-project/pull/10
I never had to read it (how it works) which means it works pretty well :D

**Comment by smuzaffar** [comment]
cmsBuild instead of downloading the sources using the url in spec, it just clone the external repo , go to the PR base branch and merge the PR changes and then use that cloned directory as downloaded sources. So yes, for externals coming from our github external repo, one can just open a PR for external and directly run tests without cmsdist PR.

**Comment by davidlange6** [comment]
so I propose we merge https://github.com/cms-externals/hepmc/pull/2

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
cool - thanks @smuzaffar

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@davidlange6 , I guess now we need https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/rootmodule/clhep-toolfile.spec#L29 and https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/rootmodule/clhep-toolfile.spec#L33 like changes for hepmc-toolfile for rootmodule branch ... right?

**Comment by davidlange6** [comment]
Yes. I’ll take care of that ~tomorrow after seeing that these changes are ok

**Pull request merged**
