### PR TITLE
Update Geant4 to version 11.2.1

### LINKED ISSUE #9085: Migrate master from Geant4 11.1.2 to 11.2.1
The new Geant4 11.2.1 is validated by SIM group (https://indico.cern.ch/event/1394263/ ). It is shown that there are no technical problems and no difference in physics results. CPU/memory analysis shows minor advantage (CPU - 0-3% depending on WF, less memory - see https://nhoerman.web.cern.ch/nhoerman/cms_simulation/olsky-05/Summary_MinBias_TTbar_SMS-T1tttt_ZEE_SIM_CMSSW_14_1_G4VECGEOM_8_thread_run-3_FullSim.html ).

We propose switch Geant4 master to variant tested in G4VECGEOM branch, which includes Geant4 itself and datasets  G4EMLOW-8.5, G4ABLA-3.3, G4INCL-1.2.

We expect regular validation within 14_1_0_pre2 without creation of a parallel IB and without extra validation campaign.

### PR DESCRIPTION
**Pull request by iarspider**
Closes https://github.com/cms-sw/cmsdist/issues/9085

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Review by smuzaffar — APPROVED** [review]

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@cms-sw/orp-l2 , please note that this PR updates the Geant4 version to `11.2.1` for 14.1.X master IBs and once merged then it will be part of 14.1.0.pre2 release. See the @civanch requests at https://github.com/cms-sw/cmsdist/issues/9085 . Please sign it to get it in to next 14.1.X IB

**Comment by antoniovilela** [comment]
+1

**Comment by civanch** [comment]
@smuzaffar , Thanks!

**Pull request merged**
