### PR TITLE
Update L1Trigger-L1THGCal to tag 05 (93X)

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #3785

### CODE REVIEW

**Comment by smuzaffar** [comment]
@kpedro88 , is this really for 93X?

**Comment by kpedro88** [comment]
Yes, it is needed for L1T backports.

**Comment by smuzaffar** [comment]
please test

**Comment by kpedro88** [comment]
@smuzaffar can you merge this one?

**Comment by smuzaffar** [comment]
@kpedro88 , done

**Pull request merged**
