### PR TITLE
Switch to Geant4 10.3ref08

### PR DESCRIPTION
**Pull request by civanch**
Switch for new G4 reference tag

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , unfortunately, I cannot access summary.html, so not clear what is wrong. Have you an idea?

**Comment by smuzaffar** [comment]
@civanch , above link is fixed now. cmsBuild failed to build Geant4 with error message
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3375/22652/external/geant4/10.04.b01-cms/log
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc630/external/gcc/6.3.0/bin/cc
-- Check for working C compiler: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc630/external/gcc/6.3.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc630/external/gcc/6.3.0/bin/g++
-- Check for working CXX compiler: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc630/external/gcc/6.3.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_TLS
-- Performing Test HAVE_TLS - Success
-- Found EXPAT: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc630/external/expat/2.1.0/lib/libexpat.so (found version "2.1.0") 
-- Found XercesC: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/slc6_amd64_gcc630/external/xerces-c/3.1.3/lib/libxerces-c.so  
CMake Error at source/cmake/Modules/G4CMakeMain.cmake:39 (message):
  G4CMakeMain can only be included once
Call Stack (most recent call first):
  source/CMakeLists.txt:56 (include)


-- Configuring incomplete, errors occurred!
See also "/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/BUILD/slc6_amd64_gcc630/external/geant4/10.04.b01-cms/build/CMakeFiles/CMakeOutput.log".
error: Bad exit status from /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/testBuildDir/tmp/rpm-tmp.P7WMH1 (%build)

```

**Comment by civanch** [comment]
please test
not clear what is the reason of the bug - let us try test again

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
tests in jenkins look good. merging it and restarting a new IB

**Pull request merged**
