### PR TITLE
Move llvm to 8.0.1 as llvm-lite was updated to 0.29

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by davidlange6** [comment]
hum, should we revert llvm-lite while this is on-going? I'm not sure why its incompatibility wasn't noticed during my python tool pull request? I should check if we left unit tests disabled...

**Comment by smuzaffar** [comment]
@davidlange6 , this is because llvmlite was explicitly using a fixed source
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/gcc700/pip/py2-llvmlite.file#L2

**Comment by davidlange6** [comment]
Ha.. yes, that was a bad thing to do.. thanks for the fix!

**Comment by smuzaffar** [comment]
please test for CMSSW_11_0_CLANG_X

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#27663 for CMSSW_11_0_CLANG_X

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#27663 for CMSSW_11_0_CLANG_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#27663

**Comment by smuzaffar** [comment]
@fabiocos , we would like to merge this PR and cms-sw/cmssw#27663 for DEVEL IBs so see any side effects of llvm.

**Comment by fabiocos** [comment]
@smuzaffar right, what do we expect for clan-tidy? I see several updates there

**Comment by fabiocos** [comment]
in any case this is for the gcc700next so ok for me

**Comment by smuzaffar** [comment]
@fabiocos , once it is in DEVEL IBs then we can run clang-tidy and clang-format to see if it fixes some issues or if tells us to re-format every thing

**Comment by fabiocos** [comment]
*or if tells us to re-format every thing* exactly my concern :-)

**Pull request merged**
