### PR TITLE
update to the latest T0 version

### PR DESCRIPTION
**Pull request by hufnagel**
Waiting on #3481 before I merge this since I want to use 1.1.6.patch5.

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 8dee95f87b3bc7870d8193f824e6e4f16364ed32 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3482/test_8dee95f-20171004-044506.log" target="_blank">here</a>.

**Comment by hufnagel** [comment]
merge

**Comment by hufnagel** [comment]
Are my permissions still screwed up ?

**Comment by ticoann** [comment]
merge

**Pull request merged**
