### PR TITLE
[Tensorflow] Update to version 2.6.0

### PR DESCRIPTION
**Pull request by smuzaffar**
- Update TF to 2.6.0
- Update Eigen to latest commit https://gitlab.com/libeigen/eigen/-/commit/82dd3710dac619448f50331c1d6a35da673f764a (version 3.4.90)
  -  I added the cms changes ( https://github.com/cms-externals/eigen-git-mirror/commit/5c78a3657102009ea20604808bf4d5a30df6ec7a ) needed for powerpc and cuda/GPU. Few of our changes were rejected. Rejected changes are available here https://muzaffar.web.cern.ch/muzaffar/eigen-82dd3710dac619448f50331c1d6a35da673f764a.rej , @fwyzard @ericcano can you please check if these are needed and open a PR for cms-externals/eigen-git-mirror branch  cms/master/82dd3710dac619448f50331c1d6a35da673f764a ?

### CODE REVIEW

**Comment by fwyzard** [comment]
Shazad, for the GPU part, can you see if the branch at
https://gitlab.com/fwyzard/eigen/-/tree/extend_CUDA_support merges cleanly ?

I rebased on top of Eigen master a couple of days ago.

.A

**Comment by smuzaffar** [comment]
Thanks @fwyzard , your branch is already using  the latest eigen commit. So I only need to add 
- https://github.com/cms-externals/eigen-git-mirror/commit/4ad2a6cf17758d5a249fa78829810233222c8294
- https://github.com/cms-externals/eigen-git-mirror/commit/29be49c7adb747dac91f2c94b0ec76a0f0bfc8dc ( which is already included in upstream).

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
Please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
FYI @riga
I see the following warnings while running `cmsml`
```
Running .2021-08-23 15:20:29.705176: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From py3-cmsml/0.1.1-llifpc2/lib/python3.9/site-packages/cmsml/tensorflow/tools.py:99: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From py3-tensorflow/2.6.0-3523f1ae2b020b77593e6809dd6db596/lib/python3.9/site-packages/tensorflow/python/framework/convert_to_constants.py:927: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
```
these warning are also there for TF 2.5 ( https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-08-22-2300/unitTestLogs/PhysicsTools/TensorFlow#/ )
I see that you are maintainer of https://pypi.org/project/cmsml/ , so may be you can update provide a new version of `cmsml` to avoid this warning?

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
