### PR TITLE
python2.7.6 for comp_gcc481

### PR DESCRIPTION
**Pull request by juztas**
Tested with crabserver,crabtaskworker, crabclient (:+1)
Will require tests of all other service maintainers.
We can`t prevent users mixing env and it is time to move on to newer python
Tested also building full comp (:+1) and it is uploaded here: http://cmsrep.cern.ch/cmssw/comp.pre.jbalcas.jbalcas/RPMS/slc6_amd64_gcc481/

Signed-off-by: Justas Balcas justas.balcas@cern.ch

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 410dc571c34c9b7172ceb77b415947ce70b85112 on slc6_amd64_gcc481.

**Comment by juztas** [comment]
Seems to be a BOT problem

```
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -L/build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/expat/2.0.1/lib -L/build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/bz2lib/1.0.6/lib -L/build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/ncurses/5.9/lib -L/build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/db4/4.8.30/lib -L/build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/gdbm/1.8.3/lib -L/build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/zlib/1.2.8/lib -L/build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/openssl/1.0.1m-comp/lib -L/build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/sqlite/3.8.1/lib /build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/ncurses/5.9/lib/libncurses.a /build/dmwmbld/srv/state/dmwmbld/builds/1492/w/slc6_amd64_gcc481/external/readline/6.2/lib/libreadline.a Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/parsetok.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Objects/obmalloc.o Python/mysnprintf.o Python/pyctype.o Parser/tokenizer_pgen.o Parser/printgrammar.o Parser/pgenmain.o -lpthread -ldl  -lutil -o Parser/pgen
Parser/firstsets.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[1]: *** [Parser/pgen] Error 1
```

```
[jbalcas@vocms22 srv]$ ls -l state/dmwmbld/builds/1492/w/BUILD/slc6_amd64_gcc481/external/python/2.7.6/python-2.7.6/Parser/firstsets.o
-rw-r--r--. 1 dmwmbld zh 16104 Apr 14 17:38 state/dmwmbld/builds/1492/w/BUILD/slc6_amd64_gcc481/external/python/2.7.6/python-2.7.6/Parser/firstsets.o
[jbalcas@vocms22 srv]$ file state/dmwmbld/builds/1492/w/BUILD/slc6_amd64_gcc481/external/python/2.7.6/python-2.7.6/Parser/firstsets.o
state/dmwmbld/builds/1492/w/BUILD/slc6_amd64_gcc481/external/python/2.7.6/python-2.7.6/Parser/firstsets.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

**Comment by geneguvo** [comment]
Hi Justas,
Moving the python version is a delicate subject and we should not discuss it in a pull request. Best thing is to raise this on next release planning meeting IMHO. It needs careful review and there are various implications to the services.

This is normally the kind of thing we change when we move to new architectures, and IIUC @ericvaandering/@nikmagini mentioned in the last release planning meeting we'd target the new arch/new python somewhere for the end of the year.

Cheers,
Diego.

**Comment by juztas** [comment]
Hi @geneguvo 
I have already mentioned to you and @mmascher that I was playing with python2.7 and crabclient and we had some discussions with hard coded paths and problems in mixing env. I started this pull request before all discussions started. (I think @ericvaandering first mentioned this in O&C week).
Now I was able to deploy taskworker, crabserver, crabclient and seems to be OK. (Of course it requires more validation then only one simple workflow)

I agree that it needs careful review and I am not saying that it should go now or tomorrow to production. Please merge/review/reject it at your convenience.

Cheers,
Justas

**Comment by juztas** [comment]
Closed. Created new pull request to new branch after yesterdays meeting. https://github.com/cms-sw/cmsdist/pull/1532

**Pull request closed without merging**
