### PR TITLE
Updated root to tip of branch v6-14-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
Get latest commits (recent PR root-project/root#2488 now merged)

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
test on it's own to see if it would break as master (still one unit test and addon test failing)

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
@mrodozov 
are the tests here now good enough to be merged?
I'm asking in relation to https://github.com/cms-sw/cmssw/pull/22594#issuecomment-415853631

**Comment by mrodozov** [comment]
Compared with what we merged on root master branch is acceptable. So I'll merge it

**Comment by mrodozov** [comment]
+externals

**Comment by slava77** [comment]
IIUC, this PR is now included in CMSSW_10_3_ROOT614_X_2018-08-28-2300, including the fix from root-project/root#2488

I still have a similar problem to the one that was present in earlier tests in July in https://github.com/cms-sw/cmssw/pull/22594#issuecomment-403376254

To reproduce
- setup the release
- in root -l -b do the following:

```
FWLiteEnabler::enable();
en = new TChain("Events");
en->Add("root://cms-xrd-global.cern.ch//store/relval/CMSSW_9_4_5_cand1/RelValTTbar_13/MINIAODSIM/94X_mc2017_realistic_v14_PU_RelVal_rmaod-v1/10000/84A84D5B-9E2E-E811-B103-0CC47A7C35F4.root");
#a local copy is available on cmsdev14:/build/slava77/RawReference/RelValTTbar_13/CMSSW_9_4_5_cand1-94X_mc2017_realistic_v14_PU_RelVal_rmaod-v1/MINIAODSIM/84A84D5B-9E2E-E811-B103-0CC47A7C35F4.root
en->Scan("patJets_slimmedJets__PAT.obj.pt()");
```

The above ends with ``` *** Break *** segmentation violation```
with stack trace:
```
#11 0x00007f6d941ed147 in void std::_Destroy_aux<false>::__destroy<edm::PtrVector<reco::Candidate>*>(edm::PtrVector<reco::Candidate>*, edm::PtrVector<reco::Candidate>*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_3_ROOT614_X_2018-08-28-2300/lib/slc6_amd64_gcc700/libDataFormatsCandidate.so
#12 0x00007f6d941efe8d in ROOT::Detail::TCollectionProxyInfo::Pushback<std::vector<edm::PtrVector<reco::Candidate>, std::allocator<edm::PtrVector<reco::Candidate> > > >::resize(void*, unsigned long) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_3_ROOT614_X_2018-08-28-2300/lib/slc6_amd64_gcc700/libDataFormatsCandidate.so
#13 0x00007f6daa0a2c7c in TGenCollectionProxy::Allocate (this=0x2f6faf0, n=0) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc700/lcg/root/6.14.01-ebmjdi/root-6.14.01/io/io/src/TGenCollectionProxy.cxx:1179
#14 0x00007f6daa263312 in TStreamerInfo::ReadBuffer<char**> (this=0x2f9f780, b=..., arr=
```

in CMSSW_10_3_0_pre2 the same leads to some meaningful printouts
```
***********************************
*    Row   * Instance * patJets_s *
***********************************
*        0 *        0 * 136.24371 *
*        0 *        1 * 118.62297 *
*        0 *        2 * 74.196975 *
*        0 *        3 * 48.971794 *
```

@smuzaffar, @mrodozov please check/confirm that CMSSW_10_3_ROOT614_X_2018-08-28-2300, includes new root build with the fix from root-project/root#2488

**Comment by slava77** [comment]
it looks like the new root build is not included:
- ```which root``` points to ```/cvmfs/cms.cern.ch/slc6_amd64_gcc700/lcg/root/6.12.07-ogkkac2```
- ls -lh there points to Aug 17 build time, while root-project/root#2488 was merged on Aug 21.

**Comment by slava77** [comment]
oops, sorry for the noise in the last message, I was in a wrong window. The CMSSW_10_3_ROOT614_X_2018-08-28-2300 has root from ```/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc700/lcg/root/6.14.01-ebmjdi``` and the build date there is Aug 29 from the file time stamps

**Comment by slava77** [comment]
the stack trace is different from what I've see in July
Back then it was  
```
#6   in TClass::GetRealData(char const*) const () from lib/libCore.so
#7   in TClass::GetDataMemberOffset(char const*) const () from lib/libCore.so
#8   in ROOT::read_patcLcLCandKinResolution_0(char*, TVirtualObject*) () from lib/slc6_amd64_gcc630/libDataFormatsPatCandidates.so
#9   in int TStreamerInfo::ReadBufferArtificial<char**>(TBuffer&, char** const&, TStreamerElement*, int, int) () from lib/libRIO.so
```

@pcanal please check if you can reproduce the problem I mentioned above https://github.com/cms-sw/cmsdist/pull/4277#issuecomment-417115455

**Pull request merged**
