### PR TITLE
Update geant4 in master to 11.2.2

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
Do we need any geant4 data updates to go with this ?

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
Please test

**Comment by civanch** [comment]
@smuzaffar , regression is not expected but statistically results well in agreement with the baseline. Our validation results are at https://indico.cern.ch/event/1438083/contributions/6051394/attachments/2895892/5077406/Sim-Talk194.pdf 

Updated datafiles are not needed for this patch release.

**Comment by smuzaffar** [comment]
assign simulation

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@civanch , any objection on including this ? if not can you please sign it?

**Comment by civanch** [comment]
+1

**Pull request merged**
