### PR TITLE
Update pythia8 with latest commit.

### LINKED ISSUE #5225: Update pythia8 to fix re-initialization
The latest fix to pythia8 provided by @smrenna cms-externals/pythia8#14 should be integrated to build CMSSW_11_0_0_pre8

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #5225 
integrates PR https://github.com/cms-externals/pythia8/pull/14 into the existing branch

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by fabiocos** [comment]
@mrodozov sorry, I did not notice you had already done it...

**Comment by mrodozov** [comment]
It's fine. It's better to keep yours because of the special workflow to be tested.

**Pull request closed without merging**
