### PR TITLE
Move to ROOT pre-6.06 (almost final)

### PR DESCRIPTION
**Pull request by davidlt**
This is a move to ROOT pre-6.06 (almost final, ROOT commit: 1f31574810df80153353b50167ceb868b520edc5).

Tested on slc6_amd64_gcc493 up to `root-toolfile`.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@davidlt , @holzman , I guess we are missing  https://github.com/cms-sw/root/pull/108 for root 6.06 ...right?

**Comment by davidlt** [comment]
Yes, I guess, this applies fine. I can add this on top.

**Comment by davidlt** [comment]
Updated. One commit is already upstreamed, the only missing part in 6.06 seems to be 'TS3WebFile - add support for session keys'. That's the only one I cherry picked.

**Comment by smuzaffar** [comment]
local tests done by @davidlt looks good.

**Pull request merged**
