### PR TITLE
Update root6 to v6-02-03.

### LINKED ISSUE #1288: Move to root 6.2.03
We were discussing about moving the ROOT6 IB to use the last (released) version of root, however @wmtan was suggesting there might be issues. Do we want to go on with this?

@davidlange6

### PR DESCRIPTION
**Pull request by ghost**
Fix #1288.

### CODE REVIEW

**Comment by ktf** [comment]
Move to use root-mirror/root@2e7ec527c98e5edfe38d1a86d302b061a59c065f

**Comment by wmtan** [comment]
We still do not have an IB using tag v6.02.03.   This is a blocker for any further progress on ROOT6.
Please advise.

**Comment by ktf** [comment]
How do you mean? `CMSSW_7_4_ROOT6_X_2015-01-21-0200` contains this fix.

**Comment by ktf** [comment]
(and it's available, at least at CERN)

**Comment by wmtan** [comment]
Sorry.  I made a mistake. It is available.  Mea Culpa.

**Pull request merged**
