### PR TITLE
Update to Herwig7

### PR DESCRIPTION
**Pull request by mharrend**
Dear all, 

this PR should finally work and allow to update Herwig++ to Herwig7.

I used the information from @mkirsano to update the closed #2100  PR.

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
@mharrend Do you know what might have gone wrong? Did you test this PR locally before submitting?

**Comment by mharrend** [comment]
Hello Alessandro,

yes, I checked it locally first and the error with the MG5aMC part was
quite unexpected since this package compiled always so far.
I will check it more thoroughly on Monday and will update the PR then.

Best regards,

## Marco

Marco A. Harrendorf marco.harrendorf@cern.ch
KIT - IEKP 

Am Montag, den 11.04.2016, 01:11 -0700 schrieb Alessandro Degano:

**Comment by ghost** [comment]
@mharrend Thanks for the updates, however your branch wouldn't merge in the cms-sw one as there are conflicts. Could you please rebase locally your branch on the cmssw official one and then commit again?

**Comment by ghost** [comment]
@mharrend Your PR is still not mergeable, please solve the conflicts locally and push again to your branch.

**Comment by mharrend** [comment]
Hello Alessandro, dear all,

I am still stucked with the error of Herwig7 not finding the LHAPDF
PDFsets.

I have done some debug and the weird thing is that the proper LHAPDF
binary is found during the make step of Herwig7 and that the LHAPDF
binary itself finds the proper PDFsets.

So I have contacted the Herwig7 authors, hoping to get some help with
this strange issue.

I will coming back to this thread as soon as I have found a solution.

Best regards,

## Marco

Marco A. Harrendorf marco.harrendorf@cern.ch
KIT - IEKP 

Am Montag, den 25.04.2016, 00:36 -0700 schrieb Alessandro Degano:

**Comment by ghost** [comment]
Hello Marco,
Thanks for the updates.
Cheers,
Alessandro

**Comment by ghost** [comment]
Since this PR would need rebasing anyway, I'll close it for now. You can open a new one once you have the answer from Herwig team.

**Pull request closed without merging**
