### PR TITLE
[12.4.X] Add collier toolfile

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
Backport of https://github.com/cms-sw/cmsdist/pull/9206 to provide collier path for run 3 madgraph gridpack generation

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@cms-sw/orp-l2, please feel free to merge it for next 12.4.X IB/release

**Comment by rappoccio** [comment]
+1

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , I will not backport this PR to CMSSW_13_0_X as it also requires https://github.com/cms-sw/cmsdist/pull/8930 which was not to 13.0.X. So please go ahead with CMSSW_13_0_X release without backport of collier toolfile PR

**Comment by antoniovilela** [comment]
> @cms-sw/orp-l2 , I will not backport this PR to CMSSW_13_0_X as it also requires #8930 which was not to 13.0.X. So please go ahead with CMSSW_13_0_X release without backport of collier toolfile PR

I had missed this, apologies. I will build 13_0_19 & 13_0_19_HLT (and also 13_0_19_HeavyIon).

**Pull request merged**
