### PR TITLE
Upgrade sherpa to 2.2.6

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 534.0,536.0

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
@mkirsano @qliphy @efeyazgan @alberto-sanchez the minimal technical check seems ok. Was any deeper test performed? Do you want to proceed with the integration of this new version of Sherpa?

**Comment by qliphy** [comment]
adding @GurpreetSinghChahal @SiewYan  

@fabiocos   Yes, I think Sherpa group will proceed more physics validation with this new version of Sherpa.

This is targeting [the Sherpa working meeting](https://indico.cern.ch/event/783787/) on Mar 19th

**Comment by fabiocos** [comment]
+1

**Comment by SiewYan** [comment]
Thanks @qliphy  for adding me. Thanks for orp-approved.

**Pull request merged**
