### PR TITLE
updated sqlalchemy to version 1.3.4

### PR DESCRIPTION
**Pull request by gudrutis**
This PR's also how SQLAlchemy is built.

### CODE REVIEW

**Comment by gudrutis** [comment]
please test

**Comment by smuzaffar** [comment]
@ggovi , there are two security vulnerabilities in the SQLAlchemy version we are using and suggestion from github was to move to 1.3.3 or above. This PR includes SQLAlchemy 1.3.4 + our patches. Are there are tests in cmssw which use SQLAlchemy to make sure it works as expected?

**Comment by ggovi** [comment]
@smuzaffar 
we don't have (yet) specific unit tests. But there are tests exercising enough, like 
https://github.com/cmssw/cmssw/blob/master/CondTools/RunInfo/test/RunInfoStart_O2O_test.sh
and 
https://github.com/cms-sw/cmssw/blob/master/CondTools/Ecal/test/EcalDAQ_O2O_test.sh
and similars...

**Comment by smuzaffar** [comment]
thanks @ggovi . I created https://github.com/cms-sw/cmssw/pull/27142 to make sure that cmssw unit tests are run when  SQLAlchemy is updated.

**Comment by smuzaffar** [comment]
ping bot

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
