### PR TITLE
[Python] Added hepdata lib python package

### LINKED ISSUE #4954: Include hepdata_lib python package
[hepdata_lib](https://pypi.org/project/hepdata-lib/) is a tool for users to convert their ROOT files into the standard HepData format for analysis archival and distribution. It would be useful to distribute this to users in CMSSW.

### PR DESCRIPTION
**Pull request by smuzaffar**
This resolves https://github.com/cms-sw/cmsdist/issues/4954
New python package hepdata-lib added. Note that it is only added for Python2 as it depends on root and we only have root build with python2.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc700

**Comment by fabiocos** [comment]
@smuzaffar @kpedro88 I see on the package page a dependency on ImageMagick that anyway is not reported in this update. Is that not really needed, and the ROOT interface is enough?

**Comment by smuzaffar** [comment]
@fabiocos , ImageMagick (convert command) is needed at runtime. We can built and distribute it but as it is available for most distributions we can just use it from system (just like many other commands we use from system).

**Comment by fabiocos** [comment]
@smuzaffar sure, I was just concerned about adding another dependency...

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
