### PR TITLE
Update dd4hep to tag 01-08

### PR DESCRIPTION
**Pull request by mrodozov**
Get the latest commits and new tag 01-08 from https://github.com/AIDASoft/DD4hep

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , @ianna  requested this. Any objection on merging it?

**Comment by fabiocos** [comment]
+1

@ianna @smuzaffar this is not supposed to impact 2018 production workflows

**Pull request merged**
