### PR TITLE
[ROOT626] Root update v6 26 00 patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

need to build full cmssw as root version changed

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
looks good but we will update root 6.26 after 13.0.0.pre3

**Pull request closed without merging**
