### PR TITLE
[BuildRules] First implementation of RocM build rules

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#40619

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/40619

**Comment by fwyzard** [comment]
👍🏻 

the ROCm tests compiled and ran, as much as they can without a GPU:
```
===== Test "testHipCheck" ====
===============================================================================
All tests passed (2 assertions in 1 test case)

---> test testHipCheck succeeded
TestTime:4
^^^^ End Test testHipCheck ^^^^
```
and
```
===== Test "testRequireROCmDevices" ====
Failed to initialise the ROCm runtime, the test will be skipped.

---> test testRequireROCmDevices succeeded
TestTime:4
^^^^ End Test testRequireROCmDevices ^^^^
```

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/40619

**Comment by smuzaffar** [comment]
+externals
build rules looks good

**Comment by fwyzard** [comment]
@smuzaffar I'm trying to build some simple HIP/ROCm device code, and I noticed that when `hipcc` compiled the `*.hip.cc` files, the `ROCM_FLAGS` are missing:
```
$ scram tool info rocm | grep ROCM_FLAGS
ROCM_FLAGS+=-fgpu-rdc --offload-arch=gfx900 --target=x86_64-redhat-linux-gnu --gcc-toolchain=$(COMPILER_PATH)
```

Do we need to add `ROCM_FLAGS` (and maybe `ROCM_LDFLAGS`) to `.SCRAM/el8_amd64_gcc11/MakeData/Tools/self.mk` and `.SCRAM/el8_amd64_gcc11/MakeData/variables.mk` ?

**Comment by smuzaffar** [comment]
@fwyzard , https://github.com/cms-sw/cmsdist/pull/8271 should fix this issue. We just need to tell scram to treat these ROCM flags as valid compiler flags

**Pull request merged**
