### PR TITLE
[ROOT] Update root 6.14

### PR DESCRIPTION
**Pull request by smuzaffar**
back-port root changes from Ib/CMSSW_10_6_X/rootnext branch.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@fabiocos , all looks good for root 6.14. When ever you have green light from validation then please merge it.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar let's leave next IB just for this, we have used it for months so it is mostly to have a clean reference than because we expect surprises

**Pull request merged**
