### PR TITLE
DAS + MongoDB32

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 9f53afaf3de7ad7cb209ef923b32d5f0de8d8db9 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2446/test_9f53afa-20160812-172918.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
-1 to 9f53afaf3de7ad7cb209ef923b32d5f0de8d8db9 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2446/test_9f53afa-20160816-135509.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
I updated WMArchive in separate PR: https://github.com/cms-sw/cmsdist/pull/2453 Now it relies on mongo32

**Comment by geneguvo** [comment]
-1 to 9f53afaf3de7ad7cb209ef923b32d5f0de8d8db9 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2446/test_9f53afa-20160818-150509.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
+1 to 78df37b58dc01b6bac8f9edcf7e8b15faa090aad on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2446/test_78df37b-20160818-170511.log" target="_blank">here</a>.

**Pull request closed without merging**
