### PR TITLE
Update pip to 903

### PR DESCRIPTION
**Pull request by mrodozov**
Bump pip to 9.0.3

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by davidlange6** [comment]
ha - great - was on my todo list - but there is a 903 that we might as well go to - or did you find a problem with that?

**Comment by mrodozov** [comment]
not at all it's just when I prepared that pr there was no 93

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
I tried building vincia locally it went fine so let's retry

**Pull request merged**
