### PR TITLE
Oracle: update instantclient 19.11

### LINKED ISSUE #5950: Oracle instant client - new version available
After the core software meeting we were going trough Oracle website
to search if there is a Arm release now available, although there isn't the client 
version moved to version 19 wrt the 12 we are using. 
The question is can we get the latest client considering compatibility issues and if you know any obstacles not letting us use it

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes #5950

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
assign db

**Comment by smuzaffar** [comment]
@ggovi , this Pull request adds new Oracle instant client 19.11 with libocci build using GCC 5.3 ( i.e new c++ ABI). PR tests looks good. Whould you like to test it first before we merge it e.g. we can merge it in DEVEL IBs to give you a chance to check it?

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/cc8_amd64_gcc9

**Comment by mrodozov** [comment]
Oracle publishing Arm executable. it's like ... magic 😅
Also we might need to remove oracle-fake for non x86 in here:
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/cmssw-tool-conf.spec#L190

**Comment by ggovi** [comment]
Ok, good i'll make some test with the DEV build. Do I need to sign this before?

**Comment by smuzaffar** [comment]
> Oracle publishing Arm executable. it's like ... magic 
> Also we might need to remove oracle-fake for non x86 in here:
> https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/cmssw-tool-conf.spec#L190

@mrodozov , oracle not yet ready for non-x86-64 archs. We are still missing the occi libs for non-x86-64, so we have to keep the oracle-fake

**Comment by smuzaffar** [comment]
@ggovi , Oracle client 19.11 should be available in today's 23h00 DEVEL IB. Tomorrow morning your can test it in CMSSW_12_0_DEVEL_X IB.

**Comment by ggovi** [comment]
@smuzaffar 
I've executed a few chained tests, nothing abnormal to notify...

**Comment by smuzaffar** [comment]
tthanks @ggovi , this is good news.

**Pull request merged**
