### PR TITLE
Update t0.spec T0 Version 3.0.8

### PR DESCRIPTION
**Pull request by germanfgv**

### CODE REVIEW

**Comment by arooshap** [comment]
-1 to d640a2d0c8f9dba7d49f4541409d6ea12783b5bd on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8306/test_d640a2d-20230210-000502.log" target="_blank">here</a>.

**Comment by germanfgv** [comment]
please test

**Comment by arooshap** [comment]
+1 to a2a32cd9622f759d97b2c454a8e6770f3db6d4cf on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8306/test_a2a32cd-20230210-140503.log" target="_blank">here</a>.

**Comment by germanfgv** [comment]
merge

**Pull request merged**
