### PR TITLE
[XRootd] Update to version 5.1.1

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test
checking something

**Comment by mrodozov** [comment]
this is weird I ran it locally with -t and all - it works  (all this failing wf's) with the new xrootd, with a cmake_build_type=Debug 
I don't think it's because of the debug build. I also checked the local files they are there

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
lets check this update on devel, I suspect the problem is not with xrootd itself

**Pull request merged**
