### PR TITLE
RecoMuon-MuonIdentification: ttH MVA training for Run2017 data/MC

### PR DESCRIPTION
**Pull request by smuzaffar**
https://github.com/cms-data/RecoMuon-MuonIdentification/pull/3

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by drkovalskyi** [comment]
when can I expect it to become available in nightlies? I don't see the file in CMSSW_10_2_X_2018-06-20-2300 and without it I cannot commit changes that are needed for CMSSW_10_2_X release.

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
as it just adds a new file, so I am merging it now. It should be available in today's 11h00 IB.

**Pull request merged**
