### PR TITLE
t0wmadatasvc.spec file for new release

### PR DESCRIPTION
**Pull request by LinaresToine**
This PR is for the new t0wmadatasvc release, which includes addition of new T0 API entry point requested in this jira ticket: https://its.cern.ch/jira/projects/CMSTZ/issues/CMSTZ-1051?filter=allissues

### CODE REVIEW

**Comment by germanfgv** [comment]
@LinaresToine lets use this PR to fix the mess I created before. Please, before creating an oficial release do the following:

1. Merge your changes into the main dmwm:t0wmadatasvc repository
2. Draft a new release in said repository with the desired version number
3. Change the `Source1` variable to use the main repository, instead of using your personal fork.

**Comment by LinaresToine** [comment]
@germanfgv Done

**Comment by LinaresToine** [comment]
please test

**Comment by germanfgv** [comment]
@arooshap could you generate and upload the RPM for this service as it is done, for example, with t0.spec? We are currently still installing from RPM and the new version does not seem to be available in the comp repo

**Pull request merged**
