### PR TITLE
[ROOT6] Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by aandvalenzuela**
No news on https://github.com/cms-sw/cmsdist/pull/8289.
But let's run the tests just in case it is fixed.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by iarspider** [comment]
test parameters:

- full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
Waiting for ROOT fix: https://github.com/root-project/root/issues/12240

**Comment by iarspider** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Same error. Waiting for https://github.com/root-project/root/issues/12240

**Comment by smuzaffar** [comment]
@aandvalenzuela , looks like the patch here is not complete, can you please update it https://patch-diff.githubusercontent.com/raw/root-project/root/pull/12276.patch and restart the tests?

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Now it built!
FYI, @smuzaffar, @iarspider

**Comment by davidlange6** [comment]
The new part of the patch is directly related to the errors.... Makes sense that this fixes things.

**Comment by smuzaffar** [comment]
lets wait for https://github.com/root-project/root/pull/12276 to go in and then update root master to use the latest commit.

By the way, in future if you have to test a root PR then instead of including `patch` just use root's user branch e.g. in this case https://github.com/vgvassilev/root/tree/cxxmodules-gcc11 adn open cms-sw/root PR ( usign the root commit branch) and then test it directly from cms-sw/root repo :-)

**Comment by aandvalenzuela** [comment]
Update of root master with the tested patch at https://github.com/cms-sw/cmsdist/pull/8320

**Pull request closed without merging**
