### PR TITLE
[10.6.X] Backport of cms-data/RecoJets-JetProducers#10 on 10_6

### PR DESCRIPTION
**Pull request by mrodozov**
please test
needed for https://github.com/cms-sw/cmssw/pull/29045

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by mrodozov** [comment]
@silviodonato this are just updating tag version for 10_2 and 10_6 and can go in (both of them)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
