### PR TITLE
Rename herwigpp to herwig7, and upgrade to Herwig 7.2.2

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
Backports  #6499  (Rename herwigpp tool to herwig7 so that it can be found by scram tool info and gen checking script) and #6708 (Upgrade Herwig to version 7.2.2, and include patch for madgraph lhe files without merging).

Tested with workflow 535 and matchbox test command command from Herwig twiki, and with two madgraph + Herwig examples: one with merging, one without.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
this reminds me you need something like this for 10_6 then 
https://github.com/cms-sw/cmssw/pull/32468

**Comment by Dominic-Stafford** [comment]
Sorry, I've just made that, it's here: cms-sw/cmssw#33111

**Comment by mrodozov** [comment]
and it also reminds me we are having trouble with one relval because madgraph and herwig needs to be python3 compatible

**Comment by Dominic-Stafford** [comment]
Herwig 7.2.2 should be python3 compatible, though I haven't checked this yet

**Comment by mrodozov** [comment]
+externals
look ok to me

**Comment by qliphy** [comment]
+1

**Pull request merged**
