### PR TITLE
comp.pre slc5_amd64_gcc461 dbs3 dbs3-client dbs3-migration dbs3-pycurl-client 

### PR DESCRIPTION
**Pull request by giffels**
Hi Alan, Diego,

Stefano and Federica found today two problems with the current DBS 3 service. One is in the Lexicon.py for the input validation and one in the migration service. Both are triggered only by certain dataset/block pattern. Both can cause failures when CRAB 2 is publishing into DBS 3.

Could you deploy the DBS hot fix version 3.2.1a, which contain only those two changes, please?

Sorry for the inconvenience.

Thanks,
Yuyi & Manuel

### CODE REVIEW

**Comment by yuyiguo** [comment]
@amaltaro 
@geneguvo 
@giffels 
Hi, Alan, Degio:

I just found another small, but important change needed in DBS3 server code. Manuel will build a new rpm tomorrow morning and test. Please hold on this one.

**Comment by amaltaro** [comment]
Hi Yuyi, Manuel, do you consider it's very important (and safe) to go to production on a Friday?
Just wondering whether it would be a showstopper for CRAB in case we push it to production on Monday only.. Thanks

**Comment by giffels** [comment]
Hi (adding @belforte),

I have tested the new version and it works like expected. I feel confident, that it will be safe to put it into production. However, I am leaving CERN after lunch and will have only sporadic access to mails until probably Monday and no access to the code. So it might be better to do the upgrade when Yuyi is available and can react in case of problems.

@belforte: Do you think CRAB can wait until Monday to get it into production? I can understand Alan, putting things in production on Fridays is a bad habit. 

Cheers,
Manuel

**Comment by belforte** [comment]
@giffels I would wait monday to do the change. Can we let users attempt publish (and migration) anyhow or better keep new crab2 in the drawer and put phys03 R/O until then ?
I am not sure if there's any bad effect from people doing things like I was doing yesterday.,
If it is only some fraction of them possibly having problems that will be solved later, but majority OK, I will let them go today.

**Comment by amaltaro** [comment]
Thanks Manuel! While we decide the last bits on how to proceed, I'll get this 3.2.1b version and start building RPMs. So in principle we only push it to production on Monday.

**Comment by giffels** [comment]
Okay, then I would say @amaltaro can redeploy testbed today and production on Monday, so we have the weekend to spot eventual problems. Does that sound reasonable?

@belforte: Yuyi discovered yesterday another bug, causing wrong processing_versions in the migrated dataset/block, when the processing_version is 0. So, I would suggest to release the new CRAB version on Monday together with the upgrade. We can easily put phys01, phys02 and phys03 in R/O mode, if that is desired, too?
Meanwhile you can do your tests with cmsweb-testbed.cern.ch, once it has been re-deployed. BTW.: It is possible to migrate data from prod/global to any other dbs server, also dbs3-dev01.cern.ch, in case you need to urgently test things before the re-deployment of cmsweb-testbed.cern.ch.

Cheers,
Manuel

**Comment by belforte** [comment]
@giffels Let's put phys0x in R/O until monday. We want 01/02 to stay R/O anyhow (somehow there must have been a miscommunication from Eric on that).

**Comment by giffels** [comment]
@belforte: Okay, I will put them into read-only mode.

**Comment by belforte** [comment]
@amaltaro confirming from my side what manuel wrote: deploy testbed tonight if possible, but production only on monday

**Comment by ericvaandering** [comment]
Yes, as sent in an e-mail, only phys03 should be writable when we come back from this migration.

**Comment by amaltaro** [comment]
This DBS3 version is in testbed now. Stefano, Manuel, Yuyi, please proceed with the validation and let me know whether it's ok or not to push it to production on Monday. I appreciate if you can provide results by Sunday morning :)

**Comment by yuyiguo** [comment]
@giffels 
@belforte 
Hi, Alan:
I tested the server on two DBS VM instance that has exactly same code as cmsweb-testbed. I did not test on cmsweb-testbed because Stefano was testing on it and my test was heavy. 
I did two run rounds of tests. Both tests showed that is it safe to deploy to production.
Thanks,
Yuyi

**Comment by amaltaro** [comment]
Thanks Yuyi.
@belforte, if I don't hear anything back from you till 6 pm today, I'll announce the production cmsweb intervention for tomorrow morning. Thanks

**Comment by belforte** [comment]
@amaltaro  my tests on cmsweb-testbed were all OK. Ssorry I had communicated this to Yuyi/Manuel but not to you. Please go ahead. Thanks

**Comment by yuyiguo** [comment]
@giffels 
@amaltaro 
@belforte 
Hi, Alan:

Stefano did more testing and found the same problem that we were trying to fix last Friday. I ran debugged on our VM and confirmed the problem. Still not sure why the patch did not work on all the datasets. Please do not deploy cmsweb on Monday. 
Sorry, 
Yuyi

**Comment by amaltaro** [comment]
Ok, I've just cancelled today's production upgrade. Thanks for the warning!
Alan.

**Comment by belforte** [comment]
thanks Alan, also  for being always there outside normal hours !
Stefano

On 02/17/2014 07:32 AM, Alan Malta Rodrigues wrote:

> Ok, I've just cancelled today's production upgrade. Thanks for the warning!
> Alan.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-sw/cmsdist/pull/410#issuecomment-35231836.

## 

Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Pull request closed without merging**
