### PR TITLE
Updated root to tip of branch v6-30-00-patches

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for el8_amd64_gcc12

**Comment by iarspider** [comment]
please test for CMSSW_14_0_ROOT630_X/el8_amd64_gcc12

**Comment by smuzaffar** [comment]
please test

hopefully https://github.com/cms-sw/cms-bot/commit/9d8c62ae489b4cec0beb46509dfdd5adc8869deb change should fix the default release for testing

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
