### PR TITLE
Initialization fixes on top of pythia8 240 (from fixes on top of 230 not yet integrated)

### PR DESCRIPTION
**Pull request by fabiocos**
Update pythia8 with K. Pedro's patch to preserve fixes of initializations not yet imported in the official package.

### CODE REVIEW

**Comment by fabiocos** [comment]
@kpedro88 @efeyazgan @qliphy @alberto-sanchez FYI

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar thanks, I copy-and-pasted from a previous version but missed this.,..

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
