### PR TITLE
[master] Drop legacy MC generators

### PR DESCRIPTION
**Pull request by iarspider**
Forward-port of #7803, #7805, #7806, #7807, #7808 to master branch. A prerequisite for https://github.com/cms-sw/cmssw/pull/37813 .

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- pull_request =  cms-sw/cmssw#37813

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1
- Tested with https://github.com/cms-sw/cmssw/pull/37813

**Comment by iarspider** [comment]
+1

**Pull request merged**
