### PR TITLE
Update root 6-12

### PR DESCRIPTION
**Pull request by mrodozov**
Get one commit on top of 6-12

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@fabiocos , @slava77 , @ Dr15Jones, this PR adds on commit [a]. This was merged in root 6.14 and above a long time ago and now we have requested to include in 6.12 too. This is needed to move forward with GCC 7.4 and GCC 8.3. PR tests looks good. We have one unit test failing which is already failing in IBs. Comparison also looks good.

Any objections on integrating it in 10.6.X?

[a] https://github.com/root-project/root/pull/3518
[IO] Do not loop over base classes of pair since it is an stl template 
https://github.com/cms-sw/root/commit/32b81d13cf2bae1fb9f41a9a5ce46cb28657d55f

**Comment by fabiocos** [comment]
+1

this does not look to solve the existing issue, but the tests do not show evidence for new problems as well

**Pull request merged**
