### PR TITLE
13 tev update data fast simulation pile up producer for 62x

### PR DESCRIPTION
**Pull request by giamman**
Same as https://github.com/cms-sw/cmsdist/pull/219

### CODE REVIEW

**Comment by davidlt** [comment]
Rebase your changes on to of `CMSSW_6_2_X`. You can always check a diff before making a pull request.

**Comment by davidlt** [comment]
@giamman actually it's a wrong branch. You made it for `cms-sw:IB/CMSSW_7_0_X/stable` and not `CMSSW_6_2_X`

**Comment by giamman** [comment]
Ops, I am sorry, I don't know how this could happen. What's the quickest/cleanest way of fixing this kind of mistakes? Or should I restart from scratch and make a new pull request?

**Comment by davidlt** [comment]
@giamman a new pull request is needed. Closing this one.

**Comment by giamman** [comment]
Uhm, I am trying again to follow your instructions, but I still get into the 7_0_X branch:

<pre>
[lxplus433] /afs/cern.ch/work/g/giamman/fastsim/pu $ cmsrel CMSSW_6_2_X_2013-10-15-1400
WARNING: Release CMSSW_6_2_X_2013-10-15-1400 is not available for architecture slc5_amd64_gcc481.
         Developer's area is created for available architecture slc5_amd64_gcc472.
[lxplus433] /afs/cern.ch/work/g/giamman/fastsim/pu $ setenv SCRAM_ARCH slc5_amd64_gcc472
[lxplus433] /afs/cern.ch/work/g/giamman/fastsim/pu $ cd CMSSW_6_2_X_2013-10-15-1400/src
[lxplus433] /afs/cern.ch/work/g/giamman/fastsim/pu/CMSSW_6_2_X_2013-10-15-1400/src $ cmsenv
[lxplus433] /afs/cern.ch/work/g/giamman/fastsim/pu/CMSSW_6_2_X_2013-10-15-1400/src $ git clone git@github.com:giamman/cmsdist.git cmsdist-giamman
Cloning into 'cmsdist-giamman'...
Enter passphrase for key '/afs/cern.ch/user/g/giamman/.ssh/id_rsa':
remote: Counting objects: 55345, done.
remote: Compressing objects: 100% (34171/34171), done.
remote: Total 55345 (delta 36978), reused 37516 (delta 21033)
Receiving objects: 100% (55345/55345), 23.10 MiB | 8.61 MiB/s, done.
Resolving deltas: 100% (36978/36978), done.
Checking out files: 100% (724/724), done.
[lxplus433] /afs/cern.ch/work/g/giamman/fastsim/pu/CMSSW_6_2_X_2013-10-15-1400/src $ git branch
fatal: Not a git repository (or any parent up to mount point /afs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[lxplus433] /afs/cern.ch/work/g/giamman/fastsim/pu/CMSSW_6_2_X_2013-10-15-1400/src $ cd cmsdist-giamman
[lxplus433] /afs/cern.ch/work/g/giamman/fastsim/pu/CMSSW_6_2_X_2013-10-15-1400/src/cmsdist-giamman $ git branch
* IB/CMSSW_7_0_X/stable
</pre>

Did I do something wrong?

**Comment by davidlt** [comment]
You don't need CMSSW environment. Select a proper branch, via `git checkout IB/CMSSW_6_2_X/stable`.

Once you are making a pull request, make sure `IB/CMSSW_6_2_X/stable` is selected as a target branch to merge in.

**Comment by giamman** [comment]
Thanks, it works. I was also confused by the fact that one has to manually select the right branch at the moment of doing the pull request (I think that it is automatically selected in case of pull requests to CMSSW, right?)

**Comment by davidlt** [comment]
@giamman If the branch name is the same on your fork, GitHub by default will pick it, because the names matches. If the names does not match, I think it goes for the default branch, which is always set to the current development.

**Comment by ktf** [comment]
>   Thanks, it works. I was also confused by the fact that one has to manually
>   select the right branch at the moment of doing the pull request (I think
>   that it is automatically selected in case of pull requests to CMSSW,
>   right?)

IIRC it should actually work also in cmsdist, if you start from 
IB/CMSSW_X_Y_Z/stable. Was that the case?

Ciao,

## Giulio

Office: 6-2-25 CERN
Tel: +41227671799
GitHub: http://github.com/ktf/

**Comment by giamman** [comment]
I started from IB/CMSSW_6_2_X/stable but then, on github, by default it was proposing the comparison (and pull request) against 7_0_X, and I had to manually change it to 6_2_X.

Cheers,
Andrea

---

Andrea Giammanco
Phone (CERN):    +41 22 76 71567
Mobiles: +41 76 2323672 (CH), +32 497 135121 (BE), +39 349 5552471 (IT)

**Pull request closed without merging**
