### PR TITLE
[DD4Hep] Try latest version v01-16-01 which is needed by root 6.24 and root master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
FYI @cms-sw/geometry-l2 @cms-sw/simulation-l2

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by cvuosalo** [comment]
@cmsbuild please test workflow 11634.911, 11650.911

**Comment by cvuosalo** [comment]
Looks good.
+geometry

**Comment by smuzaffar** [comment]
please test for CMSSW_11_3_ROOT6_X

**Comment by smuzaffar** [comment]
please test for CMSSW_11_3_ROOT624_X

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
