### PR TITLE
Patch rivet, yoda, thepeg, fastjet and tkonlinesw to avoid deprecated warnings

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_14_0_DEVEL_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
