### PR TITLE
Use build-with-pip

### PR DESCRIPTION
**Pull request by ticoann**
replace #4363

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to b978fb322f615b5436a60ec9c81f392b7a13311a on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4398/test_b978fb3-20181001-180504.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
@h4d4, @smuzaffar, @amaltaro, @bbockelm, This is weird, I used the exactly the same patch but it doesn't trigger build repeatedly anymore.  Anyway, I will run some test with agent, reqmgr, etc wheter this upgrade break anything. Thank you for all your help.

**Comment by amaltaro** [comment]
@ticoann I'm going to build 1.1.18.pre1 on my private repo, so I can add these changes too.

**Comment by amaltaro** [comment]
@ticoann @h4d4 I ran a bunch of WMCore services with these changes in and I didn't see any issues.
I'm not sure whether we should announce these changes to everyone in the webtools egroup or not, since it touches some base specs used by the other services. It might be useful to just let people know, in case they see anything strange with their service in testbed in the next week.

**Comment by h4d4** [comment]
@ticoann @amaltaro Hello Alan, Seangchan

maybe you know what is wrong with below:
to build rucio I'm testing with 1 or 2, including those in comp.spec:
1- rucio-client
2- rucio-clients 

But with 1- I'm getting:
FATAL: Package name 'rucio-client' and spec name 'rucio-clients' does not match

And with 2- :
FATAL: Package name 'rucio-client' and spec name 'rucio-clients' does not match

Thanks!

**Comment by ticoann** [comment]
Sorry LIna, It was my mistake. I wonder why it didn't give me the error on my test.
Anyway, I create the new patch.

https://github.com/cms-sw/cmsdist/pull/4445

Sorry for the all the problem.  Thanks,

**Comment by h4d4** [comment]
@ticoann Thanks for the prompt reply!
Let me try with this new patch.

**Comment by h4d4** [comment]
@ticoann @amaltaro Alan, Seangchan

I'm still getting errors building this package
I'm first testing the build of all this in my local repo with:
[1] pkgtools/cmsBuild -c cmsdist --repository comp -a slc7_amd64_gcc630 --builders 8 -j 4 --work-dir w build comp | tee logBuild

I've added rucio-client into comp.spec:
[lijimene@vocms055 cmsdist]$ grep -rn 'rucio' comp.spec 
11:Requires: popdbweb victorweb confdb tfaas rucio-client

But executing [1] I'm getting this error[2]
The error persists after update pip [3]
[lijimene@vocms055 lijimene]$ pip install --upgrade pip
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages (18.1)

Still checking this.

Best Regards, Lina.
[2]
Package external+py2-pip+9.0.3 found in repository
Fetching sources for rucio-client
Error while downloading sources from pip://rucio-client/1.18.0?pip_options=--no-deps%20--no-binary%3D:all:&output=/source.tar.gz using pip.

. /build/lijimene/w/slc7_amd64_gcc630/external/py2-pip/9.0.3/etc/profile.d/init.sh;  which pip; pip download  --no-deps --no-binary=:all: -d /build/lijimene/w/tmp/tmpxKD7OK rucio-client==1.18.0; /bin/ls /build/lijimene/w/tmp/tmpxKD7OK| grep -v files.list > /build/lijimene/w/tmp/tmpxKD7OK/files.list 
256 
/build/lijimene/w/slc7_amd64_gcc630/external/py2-pip/9.0.3/bin/pip
Collecting rucio-client==1.18.0
Could not find a version that satisfies the requirement rucio-client==1.18.0 (from versions: )
No matching distribution found for rucio-client==1.18.0
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command. 

(<function fetchSources at 0x7f813d49c938>, <Package name=rucio-client>, <scheduler.Scheduler object at 0x7f813871ef90>) done
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
* The action "build-external+rucio-client+1.18.0" was not completed successfully because The following dependencies could not complete:
fetch-external+rucio-client+1.18.0
* The action "final-job" was not completed successfully because The following dependencies could not complete:
fetch-external+rucio-client+1.18.0
build-external+rucio-client+1.18.0
* The action "install-external+rucio-client+1.18.0" was not completed successfully because The following dependencies could not complete:
build-external+rucio-client+1.18.0
* The action "build-cms+comp+HG1811a" was not completed successfully because The following dependencies could not complete:
install-external+rucio-client+1.18.0
* The action "install-cms+comp+HG1811a" was not completed successfully because The following dependencies could not complete:
build-cms+comp+HG1811a
* The action "fetch-external+rucio-client+1.18.0" was not completed successfully because Unable to download pip://rucio-client/1.18.0?pip_options=--no-deps%20--no-binary%3D:all:&output=/source.tar.gz

**Comment by ticoann** [comment]
Lina, I am so sorry for the all the trouble.
I will investigate the problem.
Meanwhile you can remove the rucio-client.spec with this patch.

https://github.com/cms-sw/cmsdist/pull/4446

So you can proceed with testbed. Sorry again for all the trouble.
Seangchan

**Comment by h4d4** [comment]
@ticoann @amaltaro 

Seangchan, in case, that this info could be useful,
while I was investigating if maybe it was a problem with the vm where I build the tags,
 I've made this test:

building the packages but with below change:
py2-pip.spec  to18.1 instead of  9.0.3
but again at the end, the building failed with[1]

Thanks for #4446 I'm going to procedure with testbed.

Best Regards, Lina.
[1] Checking local path dependency for rpm package cms+dqmgui+9.3.4-comp3 just build.
Done
Trying to install the rpm package cms+dqmgui-webdoc+9.3.4-comp3 just built.
Checking local path dependency for rpm package cms+dqmgui-webdoc+9.3.4-comp3 just build.
Done
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
* The action "build-external+rucio-client+1.18.0" was not completed successfully because The following dependencies could not complete:
fetch-external+rucio-client+1.18.0
* The action "final-job" was not completed successfully because The following dependencies could not complete:
fetch-external+rucio-client+1.18.0
build-external+rucio-client+1.18.0
install-external+rucio-client+1.18.0
* The action "install-external+rucio-client+1.18.0" was not completed successfully because The following dependencies could not complete:
build-external+rucio-client+1.18.0
* The action "build-cms+comp+HG1811a" was not completed successfully because The following dependencies could not complete:
install-external+rucio-client+1.18.0
* The action "install-cms+comp+HG1811a" was not completed successfully because The following dependencies could not complete:
build-cms+comp+HG1811a
* The action "fetch-external+rucio-client+1.18.0" was not completed successfully because Unable to download pip://rucio-client/1.18.0?pip_options=--no-deps%20--no-binary%3D:all:&output=/source.tar.gz

**Comment by ticoann** [comment]
Thank you for the information Lina, I remember this patch was giving several problem but in the end all sorted out. I added rucio client after that. I didn't see any errors initially but I must made a mistake. Anyway, thanks for the investigation I will update the pip and check the source path.

**Pull request merged**
