### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**
get latest from master

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test with #7120

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with #7120

**Comment by smuzaffar** [comment]
@mrodozov , why testing it with SCRAM V2 of 11.3.X release cycle?

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
I thought it's a fix for 12_0 (didn't check the branch) because it's failing the J job while building cmssw 
but it didn't say why, I saw a scram bug fix PR - I though oh well maybe thats it an it's still not in the ROOTX IB :) 
I don't see anything failing in the prev CMSSW build attempts logs, the scram command finished judging by the logs
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2a6883

**Comment by smuzaffar** [comment]
please test with cms-sw/cms-bot#1586

**Comment by smuzaffar** [comment]
please test with cms-sw/cms-bot#1586

**Comment by mrodozov** [comment]
I'll change the PR number because the 
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/7102/16741/install.sh
doesn't appear on cvmfs

**Pull request closed without merging**
