### PR TITLE
Dire 2.002 (10_1_X)

### PR DESCRIPTION
**Pull request by mseidel42**
10_1_X backport of #4090

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
backport of https://github.com/cms-sw/cmsdist/pull/4090

**Comment by fabiocos** [comment]
as discussed at the ORP on June 12, it does not look needed for the time being

**Comment by smuzaffar** [comment]
closing it for now. If needed please re-open or make a new PR for 10.1.X

**Pull request closed without merging**
