### PR TITLE
Back port from pull request #2052 for 75X

### PR DESCRIPTION
**Pull request by skeshri**
Pede Revision 148: /tags/V04-03-03 "with Function not decreasing Fix"
cherry picked from commit 08d7a2e920e7c543eb59984221736e3c43098aaa

### CODE REVIEW

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by skeshri** [comment]
Hi @degano  ! Could you please merge this pull request, if all tests are successfully done? 

Thanks!

**Comment by ghost** [comment]
@davidlange6 Here as well, is this okay for 75X?

**Comment by skeshri** [comment]
Hi @degano and @davidlange6 !

what is the status for this pull request? Is this pull request fine and passed all the test? If it is then please merge it!

Thanks!

**Pull request merged**
