### PR TITLE
1.0.5 version of wmagent

### PR DESCRIPTION
**Pull request by ticoann**
Please create the new rpm for wmagent.

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 05d0d41d801fd9a35aa12117a16c746e4d8e5b47 on slc6_amd64_gcc481.

**Comment by amaltaro** [comment]
Don't we need to change the dependency to couch1.6 now @ticoann ?

**Comment by ticoann** [comment]
Yes, we do. But not sure how. I need Diego's advice. Alan, we need 1.0.5 rpm more urgently, right? I will change the  pull request for 1.0.5.
Not sure why build fails, It was built fine in my vm.

**Comment by amaltaro** [comment]
That's right Seangchan! 1.0.5 version is the RPM we need for tomorrow or so. Also update the dependency to couchdb15 please. Tomorrow I'll sort out the deployment tweaks with Diego.

**Comment by ticoann** [comment]
Thanks, Alan. I update the pull request with 1.0.5 version

**Comment by amaltaro** [comment]
You forgot to update "Requires: couchdb" to "Requires: couchdb15" :-)

**Comment by geneguvo** [comment]
-1 to 23d2e5312f80b8a6962162907a4294ce93956f52 on slc6_amd64_gcc481.

**Comment by ticoann** [comment]
> You forgot to update "Requires: couchdb" to "Requires: couchdb15" :-)

That is the part I don't quite understand I think I had to create couchdb15 deployment script make that work. (I am not sure how that works without deployment script). 

Looking at the workqueue.spec it still has Required: couchdb but it uses couch1.6.
https://github.com/cms-sw/cmsdist/blob/comp_gcc481/workqueue.spec#L7

I want to get Diego's advice how to do that before make any changes.

**Comment by ticoann** [comment]
Changed the Requires couchdb to couchdb15. I though we need couchdb15 deployment script but Alan said and tested everything works this way. Thanks, Alan.

**Comment by geneguvo** [comment]
-1 to 5fee5ab11df55db91527287f906696ce81a854e3 on slc6_amd64_gcc481.

**Comment by geneguvo** [comment]
+1 to 5fee5ab11df55db91527287f906696ce81a854e3 on slc6_amd64_gcc481.

**Pull request closed without merging**
