### PR TITLE
Back port from pull request #2052 for 76X

### PR DESCRIPTION
**Pull request by skeshri**
Pede Revision 148: /tags/V04-03-03 "with Function not decreasing Fix"
cherry picked from commit 08d7a2e920e7c543eb59984221736e3c43098aaa

### CODE REVIEW

**Comment by ghost** [comment]
@cmsbuild please test

**Comment by skeshri** [comment]
Hi @degano ! Could you please merge this pull request, if all tests are successfully done?

Thanks!

**Comment by ghost** [comment]
Hi, @skeshri actually since this is not a development release we should have the Orp sign.
@davidlange6 are you good with this? Does it need further discussion?

**Comment by davidlange6** [comment]
yes, its ok for 76x. Thanks for inquiring.

**Comment by skeshri** [comment]
Thanks @degano @davidlange6 !

**Pull request merged**
