### PR TITLE
 Update DD4Hep 12_0 to specific commit

### PR DESCRIPTION
**Pull request by mrodozov**
see #7311

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@qliphy , @perrotta feel free to integrate this for 12.0.X

**Comment by perrotta** [comment]
+1
- Update DD4Hep for 12_0, where it is not used in productions

**Pull request merged**
