### PR TITLE
[5.3.X] backport cms-git-tools changes

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar there is apparently a problem with the test. I think that in this case it would be better to integrate it (after test) and explicitly make a new build

**Comment by smuzaffar** [comment]
please test
lets re-run it once again

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
