### PR TITLE
Update llvm.spec with latest commit hash

### PR DESCRIPTION
**Pull request by gartung**
Update to clang static analyzer core to use scoped named for variable when calculating issue hash

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung , this looks good, do you want to run any local tests against `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8537/32966/install.sh` to see if your changes actually work?

**Comment by gartung** [comment]
I did already before I merged the branch.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
