### PR TITLE
patching CLEO model for production studies

### PR DESCRIPTION
**Pull request by alberto-sanchez**
This simple patch in required in order to use this model in MC production.

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test workflow 541.0, 545.0

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
Dear @qliphy, @silviodonato,  we are interested in having this patch in production asap. We will need to generate some MC samples using this decay model.

This is the distribution before the patch

BuggedInvarianteMass

and, this is the distribution after the patch

CorrectedInvMass

**Comment by qliphy** [comment]
> Dear @qliphy, @silviodonato, we are interested in having this patch in production asap. We will need to generate some MC samples using this decay model.

@alberto-sanchez 
Thanks!  It looks good to me.  Adding @smuzaffar @mrodozov @cms-sw/generators-l2 
What is the time scale for the MC production?

**Comment by smuzaffar** [comment]
looks good to me. @alberto-sanchez do we need a similar patch for evtgen 2.0.0 https://github.com/cms-externals/evtgen/blob/cms/2.0.0/src/EvtGenModels/EvtYmSToYnSpipiCLEO.cpp#L145 ?

**Comment by alberto-sanchez** [comment]
> @alberto-sanchez
> What is the time scale for the MC production?

As soon as is available

**Comment by alberto-sanchez** [comment]
> looks good to me. @alberto-sanchez do we need a similar patch for evtgen 2.0.0 https://github.com/cms-externals/evtgen/blob/cms/2.0.0/src/EvtGenModels/EvtYmSToYnSpipiCLEO.cpp#L145 ?

Yes, we will need something similar in evtgen 2.0
I wonder how is the best way to go for it. In principle the compilation of 2.0 is different than in 1.6, and we already have a 
repo for that in cms-external, probaly we could create a new branch (say cms/2.0.1) and make the change in that branch,
waht do you think?

**Comment by smuzaffar** [comment]
@alberto-sanchez , the usual procedure for such fixes is that 
- fork the cms-external repo e.g in this case https://github.com/cms-externals/evtgen
- Add changes in your fork on top of the branch e.g. in this case add your changes for cms/2.0.0 branch
- Open a PR using your feature/bugfix branch to the https://github.com/cms-externals/evtgen

Once we have PR for https://github.com/cms-externals/evtgen then we can already start testing it

**Comment by smuzaffar** [comment]
by the way, you can do the same for cms/1.6.0 branch (i.e instead of adding patch in to cmsdist, it is better to patch it directly in the cms-externals/evtgen repo cms/1.6.0 branch)

**Comment by alberto-sanchez** [comment]
I have create the Pull request for 2.0, in 1.6 the way the source is downloaded is different, we actually are not using the cms repo, but the tarball distributed at that time.

**Comment by smuzaffar** [comment]
+externals
>I have create the Pull request for 2.0, in 1.6 the way the source is downloaded is different, we actually are not using the cms repo, but the tarball distributed at that time. 

ah you are right @alberto-sanchez. This PR is good for 10.6.X then.

**Comment by qliphy** [comment]
+1

**Pull request merged**
