### PR TITLE
WMAgent release candidate: 1.4.7.patch2

### PR DESCRIPTION
**Pull request by amaltaro**
It also includes wmagentpy3 update.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 08bdbcf8d20e2f35a1875b3db2417ae952396170 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6819/test_08bdbcf-20210419-104932.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Comment by amaltaro** [comment]
FYI @todor-ivanov

**Comment by todor-ivanov** [comment]
Thanks @amaltaro

**Pull request merged**
