### PR TITLE
New dasgoclient version

### PR DESCRIPTION
**Pull request by vkuznet**
Adjust Rucio call `/replica/list` to use the following JSON:
```
{"dids":[{"name":"dataset-name","scope":"cms"}],"domain":null,"all_states":false,
 "resolve_archive":false,"resolve_parents":false,"rse_expression":"site-name"}
```

For details, see discussion in https://github.com/cms-sw/cmsdist/pull/6602

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by vkuznet** [comment]
@smuzaffar , is there anything pending in this PR? Can we move forward with it?

**Comment by smuzaffar** [comment]
@vkuznet , CMSSW IBs have few broken tests. I would like to see green IBs before merging this ( as this might break the 3 tests rucio is not returning any files)

**Pull request merged**
