### PR TITLE
Rivet 2.7.2 and YODA 1.75

### PR DESCRIPTION
**Pull request by mseidel42**
Rivet and YODA minor revision updates

### CODE REVIEW

**Comment by mrodozov** [comment]
allow @intrepid42  test rights

**Comment by mrodozov** [comment]
now you can test the PR and retry it if it needs retriggering

**Comment by mseidel42** [comment]
please test

**Comment by mseidel42** [comment]
Need to update RivetInterface for https://bitbucket.org/heprivet/rivet/commits/6ae4b32acee01c19b4fc064fa168e1083a61621c

**Comment by mseidel42** [comment]
please test with https://github.com/cms-sw/cmssw/pull/26936

**Comment by fabiocos** [comment]
@smuzaffar ok for me to move forward at next IB

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
