### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by arooshap** [comment]
@smuzaffar is this PR ready to be incorporated? The DQM team just informed me about it.

**Comment by smuzaffar** [comment]
@arooshap , https://github.com/cms-sw/cmsdist/pull/8893 is the PR which DQM team needs for online DQM gui

**Comment by smuzaffar** [comment]
+externals

tests passed

**Pull request merged**
