### PR TITLE
Backport of DNS resolution patch for Xrootd client.

### PR DESCRIPTION
**Pull request by ghost**
@bbockelm:

"Previously, we tried to update to 3.3.3, then to 4.0.3, then hit
a ROOT issue.  Meanwhile, Ops didn't get the fix they were waiting
for.  So, while we wait on ROOT, here's the originally-requested
backport.

Original patch here:
https://github.com/xrootd/xrootd/commit/6184cd0f24145ebae66bc782d929444d19700fdc"

Close #1003.

### CODE REVIEW

**Comment by bbockelm** [comment]
Hi @degano -

Can you give me a ping when there's a build available?  I have the appropriate setup locally for testing the failover which wouldn't be covered by the IB tests.

Brian

**Comment by ghost** [comment]
+1
Tested compilation up to cmssw-tool-conf.

**Comment by ghost** [comment]
Hi @bbockelm,
I just merged this and should be available from tonight IB (0200) I will confirm that tomorrow.

**Comment by ghost** [comment]
@bbockelm I confirm that this is available.

**Pull request merged**
