### PR TITLE
New spec for cmsexitcodes service

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to e52532cd5a0dcffcbcf031c15f8be321285d94be on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5355/test_e52532c-20191114-224003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 72a3f04d387da493471cad267fa55399ae77141d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5355/test_72a3f04-20191114-230504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 5216e0f5338f1cb23f68a65e4f0e2f9593094c6c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5355/test_5216e0f-20191115-153505.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@h4d4 , @muhammadimranfarooqi  please merge this PR. It is ready now to be deployed to cmsweb.

**Pull request merged**
