### PR TITLE
[10.6.X] Update MXNet to 1.5.0

### PR DESCRIPTION
**Pull request by mrodozov**
please test
redo of #5535

### CODE REVIEW

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
@hqucms @mrodozov  can we merge this or we need the future backport of https://github.com/cms-sw/cmssw/pull/28902
(same comment for https://github.com/cms-sw/cmsdist/pull/5591)

**Comment by mrodozov** [comment]
we have this comment https://github.com/cms-sw/cmsdist/pull/5534#issuecomment-590101024 but I'd rather ask @hqucms again 
if we merge the new version behaviour doesn't change, so we can do it, correct ?

**Comment by hqucms** [comment]
> we have this comment [#5534 (comment)](https://github.com/cms-sw/cmsdist/pull/5534#issuecomment-590101024) but I'd rather ask @hqucms again
> if we merge the new version behaviour doesn't change, so we can do it, correct ?

@mrodozov @silviodonato Yes we can merge this.

**Comment by silviodonato** [comment]
please test

**Comment by mrodozov** [comment]
please test
comparison job failed because of github 500 exception, lets retry

**Comment by silviodonato** [comment]
this will be needed for the backport of https://github.com/cms-sw/cmssw/pull/28902

**Comment by silviodonato** [comment]
+1

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
apparently this made it only to IB/CMSSW_10_6_X/gcc820,
while the production arch for 106X is still slc7_amd64_gcc700. 
So, only gcc820 IBs in 106X have MXNet at 1.5.0, while the default (gcc700) is still  using 1.2.1.

Please propagate to all of 10_6_X.
Thank you.

**Pull request merged**
