### PR TITLE
Test onnxruntime 1.7.2 integration

### PR DESCRIPTION
**Pull request by mrodozov**
@hqucms any objection to move to 1.7.2 if it integrates,
we can update it to the last tag before trying to fix/report the Arm runtime errors

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by hqucms** [comment]
> @hqucms any objection to move to 1.7.2 if it integrates,

No:) Thank you @mrodozov !

**Comment by mrodozov** [comment]
abort
the jenkins job has stuck

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
