### PR TITLE
Update tag for DQM-EcalMonitorClient to V00-03-00  [13_0_X]

### PR DESCRIPTION
**Pull request by perrotta**
Move DQM-EcalMonitorClient data to new tag, see
https://github.com/cms-data/DQM-EcalMonitorClient/pull/3

Backport https://github.com/cms-sw/cmsdist/pull/8476 to 13_0_X

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@abhih1 this was forgotten when https://github.com/cms-sw/cmssw/pull/41195 was merged.
Now I wonder: why there are no crashes in the IB after the merge of https://github.com/cms-sw/cmssw/pull/41195 , e.g. CMSSW_13_0_X_2023-04-27-2300 and CMSSW_13_0_X_2023-04-28-1100?

**Comment by abhih1** [comment]
> @abhih1 this was forgotten when [cms-sw/cmssw#41195](https://github.com/cms-sw/cmssw/pull/41195) was merged. Now I wonder: why there are no crashes in the IB after the merge of [cms-sw/cmssw#41195](https://github.com/cms-sw/cmssw/pull/41195) , e.g. CMSSW_13_0_X_2023-04-27-2300 and CMSSW_13_0_X_2023-04-28-1100?

@perrotta I'm not sure. I dont know exactly how the IB testing works, but the lines in MLClient.cc which uses those data files are only run if a Pileup [condition](https://github.com/cms-sw/cmssw/blob/CMSSW_13_0_X/DQM/EcalMonitorClient/src/MLClient.cc#L60-L63) is satisfied. So if a non-collision run was used in testing it wont be affected.

**Comment by perrotta** [comment]
+1
- Needed by https://github.com/cms-sw/cmssw/pull/41195 when run online

**Comment by perrotta** [comment]
merge

**Pull request merged**
