### PR TITLE
Remove mkFit as an external

### PR DESCRIPTION
**Pull request by fwyzard**
Please re-submit it as a part of CMSSW, following the usual (lengthy and through) integration procedure.

### CODE REVIEW

**Comment by mrodozov** [comment]
> Please re-submit it as a part of CMSSW

You are suggesting we make mkFit part of cmssw instead of being external because ... ?

**Comment by fwyzard** [comment]
... because it implements a part of the physics reconstruction software for CMS (track reconstruction), written by members of CMS.

**Comment by smuzaffar** [comment]
@makortel , what do you think? I guess we need a cmssw PR to go with it .... right?

**Comment by makortel** [comment]
Right, a CMSSW PR would be needed.

**Comment by smuzaffar** [comment]
closing it, reopen for latest release cycle along with CMSSW PR

**Pull request closed without merging**
