### PR TITLE
Update root.spec to last commit in modules branch

### PR DESCRIPTION
**Pull request by davidlange6**
I left off one commit by mistake in the PR merged last night. This fixes that issue (the commit was already in the appropriate branch in the cms fork of root.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@vgvassilev @davidlange6 root itself is building I'm merging this to have a new IB with it

**Comment by vgvassilev** [comment]
This would probably regress the CXXMODULE build of CMSSW as it is now failing at the testing phase. With this merged it will fail at compilation again...

**Comment by mrodozov** [comment]
hm right, I wasn't following the state of the IB and assuming it was failing anyway. I see it is building now indeed (the last IB). Is it coming from ROOT changes then ?

**Comment by vgvassilev** [comment]
We will have to investigate. Our CHEP paper (you guys included) depends on the measurements we can get now from CMSSW. We can merge this PR and break the system (if we want to investigate on the live IB) only after the paper deadline which is in 2 weeks :)

**Pull request closed without merging**
