### PR TITLE
First build from GIT...

### PR DESCRIPTION
**Pull request by TonyWildish**
...DMWMMON itself has only minor changes, such as being less strict on allowing characters in directory names.

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 3051e10e22341cf3e3e278a1e356ac38c97e9ce0 on slc5_amd64_gcc461.

**Comment by TonyWildish** [comment]
can you be more specific about the error please? It builds fine for me...

**Comment by amaltaro** [comment]
I did not see anything in the logs, but it seems you forgot to either a) create the correct tag DMWMMON-DATASVC_1_0_1 or b) you set the incorrect version in the spec file (1.0.1 instead of 1.0.1pre1). BTW, you can see logs under /build/dmwmbld/srv/state/dmwmbld/builds/<PR>

**Comment by TonyWildish** [comment]
oops, my apologies, I did screw up the tagging. The correct tag is now in place, and a clean build does work for me.

**Pull request closed without merging**
