### PR TITLE
[13_2_X] Update tag for RecoBTag-Combined to V01-25-00

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of https://github.com/cms-sw/cmsdist/pull/9504

@mandrenguyen

### CODE REVIEW

**Comment by smuzaffar** [comment]
@stahlleiton , we are updating tag from V01-22-00 to V01-25-00. I think we also need cmssw changes to go with this update .... right ?

**Comment by stahlleiton** [comment]
> @stahlleiton , we are updating tag from V01-22-00 to V01-25-00. I think we also need cmssw changes to go with this update .... right ?

In principle no changes in CMSSW would be needed in this case.

**Comment by smuzaffar** [comment]
please test

**Comment by stahlleiton** [comment]
I will investigate the issue and fix it with a PR

**Comment by stahlleiton** [comment]
The following PR https://github.com/cms-sw/cmssw/pull/46673 should fix the issue seen in the tests

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#46673

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge

**Pull request merged**
