### PR TITLE
Update git to 2.38.1

### PR DESCRIPTION
**Pull request by iarspider**
@smuzaffar Latest version is 2.38.1 - should we go for it?

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , I think there is no urgent need to update unless there are issues. As this might rebuilt few externals, so we can wait for any big change (update of gcc or python) and directly go to latest git version

**Comment by iarspider** [comment]
hold

let's wait for big update then

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
unhold
this can go in with #8231 which is already rebuilding packages rebuild by this change.

**Comment by smuzaffar** [comment]
+externals
this can go in once 13.0.0.pre2.LTO is built

**Pull request merged**
