### PR TITLE
upgrade lhapdf sets to 6.1.6a

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@davidlange6 any objection getting this in 91x?

**Comment by davidlange6** [comment]
@mkirsano - the PR is finalized now?

**Comment by mkirsano** [comment]
Yes, it is finalized

**Comment by davidlange6** [comment]
please test

**Pull request merged**
