### PR TITLE
Move back to ROOT 6.18 (11_1)

### PR DESCRIPTION
**Pull request by silviodonato**
Revert of #5942 and #5951.
Request from PPD to move back to ROOT 6.18 for the 11_1_0 reReco production in order to fix a PSS memory jump in DQM merge (@srimanob)

See: https://sft.its.cern.ch/jira/browse/ROOT-10927

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by srimanob** [comment]
Issue at https://github.com/cms-sw/cmssw/issues/30664

**Comment by mrodozov** [comment]
use this commit https://github.com/cms-sw/cmsdist/commit/8f2bae381218c0eae469fd40444ffb43be837152
and also what is the plan for this to build the release and turn it back to 6-20 ?

**Comment by srimanob** [comment]
@mrodozov 
I think we should stay with 6.18 for 11_1 as it becomes production release now, and its lifetime is not that long. For 6.20, we is still on with with 11_2, but we definitely need fix from ROOT. The behaviour is on last 6.22 also.

**Comment by silviodonato** [comment]
@mrodozov 
- I moved the root tag to `2b91a0f8b8a094137a90fed9b340d99a3108c2d4` (taken from commit https://github.com/cms-sw/cmsdist/commit/8f2bae381218c0eae469fd40444ffb43be837152)
- The plan is to build a release as soon as possible because the memory issue is preventing us from running RelVals. I hoped to build of the release this night together with the night IB, but I want to see at least the result of the PR test before merging it. Likely I will start the build of `11_1_1` tomorrow morning after having merged this PR.
- As @srimanob said, I think we can keep 6.18 in 11_1. About 11_2, we can keep ROOT 6.22 (ie. close https://github.com/cms-sw/cmsdist/pull/6069) or move back to 11_1 waiting for a bug-fix of ROOT (see https://sft.its.cern.ch/jira/browse/ROOT-10927). @srimanob do you need ROOT 6.18 to run RelVals in 11_2_0_pre2?

**Comment by silviodonato** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@silviodonato , this PR is not based on IB/CMSSW_11_1_X/root618 branch. I am merging this and starting a 11.1.ROOT618_X IB.

**Pull request merged**
