### PR TITLE
WMAgent 1.1.0.patch1

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, Alan please review.

### CODE REVIEW

**Comment by BrunoCoimbra** [comment]
+1 to 15d05e7e67d88ea0570e84cb479e0048df27ff5f on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2816/test_15d05e7-20170209-063506.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge please

**Comment by amaltaro** [comment]
ping

**Comment by amaltaro** [comment]
merge

**Comment by amaltaro** [comment]
@smuzaffar it works ;)

**Pull request merged**
