### PR TITLE
Remove Rivet AnalysisHandler patch

### PR DESCRIPTION
**Pull request by mseidel42**
AnalysisHandler patch not needed anymore with https://github.com/cms-sw/cmssw/pull/32950

### CODE REVIEW

**Comment by mrodozov** [comment]
allow @ intrepid42 test rights

**Comment by mseidel42** [comment]
Please test with https://github.com/cms-sw/cmssw/pull/32950

**Comment by mseidel42** [comment]
please test with cms-sw/cmssw#32950

**Comment by mseidel42** [comment]
> allow @ intrepid42 test rights

Oops, I think there is a superfluous space between @ and my user name

**Comment by mrodozov** [comment]
allow @intrepid42 test rights

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mseidel42** [comment]
please abort

**Comment by mseidel42** [comment]
please test with cms-sw/cmssw#32950

**Comment by mrodozov** [comment]
+externals
0 diffs. it's a removal of a patch.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
