### PR TITLE
[10.3.X] OpenLoops: NLO QCD+EWK predictions updated in Openloops

### PR DESCRIPTION
**Pull request by smuzaffar**
as requested here cms-externals/openloops#10

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , please merge it at your convince. 
This is also requested for 10.2 and 9.3

**Comment by fabiocos** [comment]
+1

**Pull request merged**
