### PR TITLE
wmagent 1.1.10.patch4 gcc493

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by amaltaro** [comment]
@hufnagel Dirk, are you planning to deploy T0 in CC7 any time soon? You're going into a dangerous land remaining at slc6

**Comment by hufnagel** [comment]
We already switched a couple of the replay VM to CC7. I just don't want to force Tier0Ops to switch all of the other VM immediately with 2.1.1 (but this will be the last release I am going to build on both archs).

**Comment by h4d4** [comment]
+1 to 3070caaca09a2db6f65c01eee59a8ddfba94fce3 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/3757/test_3070caa-20180220-220506.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
merge

**Pull request merged**
