### PR TITLE
Drop cgal

### PR DESCRIPTION
**Pull request by iarspider**
Notice: CGAL is now (>= 5.0) a header-only library.

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , looks like this external is also not needed any more. It was only used ion one cmssw package but has been dropped ( https://github.com/cms-sw/cmssw/pull/18684#issuecomment-302248100 ) few years ago. I would suggest to remove this external too.

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
