### PR TITLE
 [ROOT-618] Update DD4Hep with latest commits from master and PR from ROOT

### PR DESCRIPTION
**Pull request by mrodozov**
@ianna its building (I built it) lets see if it runs

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/root/pull/128

**Comment by smuzaffar** [comment]
@mrodozov and @ianna we should wait for root to merge it first either in their master branch of v6.18 branch.

**Comment by smuzaffar** [comment]
hold
wait for  https://github.com/root-project/root/pull/4006 to be merged in root first

**Comment by mrodozov** [comment]
dd4 is updated in newer pr, closing this

**Pull request closed without merging**
