### PR TITLE
Python 2.7.11

### PR DESCRIPTION
**Pull request by davidlt**
Moving CMSSW to the latest and greatest version of Python 2.7.11. Note, that starting 2.7.9 version SSL host verification is enabled by default thus machines must have CERN CA bundles installed (i.e. CERN-CA-certs).

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by davidlt** [comment]
So, what do we do with this PR?

**Comment by ghost** [comment]
Probably we don't want it to be on 8_0_X, we might put it in the DEVEL branch for the next release.

**Comment by davidlt** [comment]
It's in a DEVEL branch for quite some time already. We can discuss it's fate at Core Software meeting.

**Comment by smuzaffar** [comment]
My worry is that once we have it in release then we have to deal with messages like my script XYZ does not work after setting  cmssw env ....

**Comment by ghost** [comment]
This has been merged in 81X.

**Pull request closed without merging**
