### PR TITLE
fix couchbug for redirecting log

### PR DESCRIPTION
**Pull request by ticoann**
https://build.opensuse.org/package/view_file/server:database/couchdb/couchdb-1.6.1-fix-restart.patch?rev=bd081d78379f6ef4ccf2ce96b0bf5aee

### CODE REVIEW

**Comment by BrunoCoimbra** [comment]
-1 to 5059f67667b4c66f0aa511c149d93452b314721f on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_5059f67-20170123-220506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to b1e14c2a2de7afdc69b6a6c4deeab4b99bf27022 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_b1e14c2-20170123-221506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to 99dab9779dff1f6b711d6f139db173879349786d on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_99dab97-20170125-214506.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
ping

**Comment by BrunoCoimbra** [comment]
-1 to 4fb5f6150879067f629154d296895f6e6e9cb6a3 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_4fb5f61-20170125-215506.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
ping

**Comment by BrunoCoimbra** [comment]
-1 to 7528ac2b0582a063071672cd20a2460cdd4208c5 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_7528ac2-20170126-040505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to 0b3c66bead5ea42f90295e7489119533a9ce6f45 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_0b3c66b-20170126-050505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to 52e5bdfc334e19df2bfc62a1dd36f32e9fc2fe5d on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_52e5bdf-20170126-061506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to 65f562f6d92068e15d15f8847be0afbb080cc345 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_65f562f-20170126-064505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to 1488321801e36ba8dbb97dbcd16aff947fded326 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_1488321-20170126-071506.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
@BrunoCoimbra, Hi Bruno, I am getting following error.

prefix=/build/dmwmbld/srv/state/dmwmbld/builds/2786/w/tmp/BUILDROOT/46c6317a6fda78376239740bee7ea09d/build/dmwmbld/srv/state/dmwmbld/builds/2786/w/slc6_amd64_gcc493/external/couchdb15/1.6.1-comp5 --with-js-lib=/build/dmwmbld/srv/state/dmwmbld/builds/2786/w/slc6_amd64_gcc493/external/spidermonkey/1.8.5-comp3/lib --with-js-include=/build/dmwmbld/srv/state/dmwmbld/builds/2786/w/slc6_amd64_gcc493/external/spidermonkey/1.8.5-comp3/include/js --with-erlang=/build/dmwmbld/srv/state/dmwmbld/builds/2786/w/slc6_amd64_gcc493/external/erlang/R14B04-comp/lib/erlang/usr/include --with-win32-icu-binaries=/build/dmwmbld/srv/state/dmwmbld/builds/2786/w/slc6_amd64_gcc493/external/icu4c/4_0_1
/build/dmwmbld/srv/state/dmwmbld/builds/2786/w/tmp/rpm-tmp.eys72s: line 31: ./configure: No such file or directory
error: Bad exit status from /build/dmwmbld/srv/state/dmwmbld/builds/2786/w/tmp/rpm-tmp.eys72s (%build)

The original src file location is no longer exist, so I change the src file location. But it seems there are a little difference on the file. There is no Makefile.in and configure file. (There is configure.ac)
I am not sure where to fix it. Could you give me some pointer?

**Comment by davidlt** [comment]
Looks like you have switched from release tarballs to code repository, which might not be the same things, .e.g, once you are preparing a release tarball you are generating specific files. In your case you don't have `./configure` it's not generate and `configure.ac` is actually a source code used to generate actual script (same applies for `Makefile.am` and other files). If you use directly code from GitHub you need to do release cooking steps to prep content for consumption. For this particular issue either there is a bash script that contains the right command to kick off `configure/Makefile.in/etc` generation or you need to write yourself.

**Comment by davidlt** [comment]
Here: https://github.com/apache/couchdb/blob/1.6.x/bootstrap

**Comment by BrunoCoimbra** [comment]
Hi @ticoann, @davidlt,

We just got to the same conclusion here. The problem is that our build machine doesn't have the required packages for running bootstrap. I'm now seeing what can be done from CMSWEB side. Maybe generating our own tarball somewhere else?

**Comment by BrunoCoimbra** [comment]
Hey @ticoann, could you try using the following source link:
https://www.apache.org/dyn/closer.lua?path=/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz

It brings a tarball which includes configure and Makefile.in.

**Comment by BrunoCoimbra** [comment]
Actually I've just did it myself so we can save some time! :)

**Comment by BrunoCoimbra** [comment]
-1 to 191a7e2012e538315f9cafb8b4d99dc7f98c848f on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_191a7e2-20170126-133505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to 191a7e2012e538315f9cafb8b4d99dc7f98c848f on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_191a7e2-20170126-135505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
Sorry @ticoann I got the wrong link somehow, here is the right one!
http://www.pirbot.com/mirrors/apache/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz

**Comment by BrunoCoimbra** [comment]
-1 to cc857aebe6b48e321a8ef8314c427471177dcd07 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_cc857ae-20170126-140505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to acf1a96e2968e4fe28ea62a063fa2bed06561821 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_acf1a96-20170126-141505.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
-1 to 9e4df22c474e9e70aeb6ed36acfa11b31866c463 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_9e4df22-20170126-150506.log" target="_blank">here</a>.

**Comment by BrunoCoimbra** [comment]
Hey @ticoann, in the end the only change that I've made was changing the source link. It seems to have helped a bit but it's still not building. I tried a minor change (already reverted) that didn't help much. I'll not touch the code further to avoid affecting your work, but can count on me if you need help with this.

**Comment by BrunoCoimbra** [comment]
+1 to 1b44d7c9692de6d33e4e955289d8eab6aa0b775d on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_1b44d7c-20170126-222507.log" target="_blank">here</a>.

**Comment by ticoann** [comment]
Thank you very much Bruno, David. It seems it is working fine now. I will deploy and test

**Comment by ticoann** [comment]
I tested in vm, this seems to working fine.

**Comment by h4d4** [comment]
Hey @ticoann should we merge it now?

**Comment by ticoann** [comment]
Hi Lisa I just talk to Alan, and I think the better fix is 
changing couch deployment script. 


https://github.com/dmwm/deployment/blob/master/couchdb/deploy

But the src url still need to be changed. So I will update the patch and request the merge again.
Thanks

@amaltaro, Alan, I can't find the fix on imagent anymore in the pull request.

**Comment by BrunoCoimbra** [comment]
+1 to 75b0704d4b0d0c9fdb483ccc7707f15e99580052 on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2786/test_75b0704-20170203-075508.log" target="_blank">here</a>.

**Pull request merged**
