### PR TITLE
Update DBSClient to latest tag 4.0.9

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 16060246d1c35b38a69c1c60d8b6722126044b8f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/8040/test_1606024-20220825-154002.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@belforte do you want me to merge it?

**Comment by belforte** [comment]
yes, please

**Comment by amaltaro** [comment]
merge

**Pull request merged**
