### PR TITLE
New version of Go compiler

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , Muhammad, if build is ok please merge it. This is new compiler version of Go language which we use in other tools like DAS. Therefore the build will probably trigger DAS rebuild.

**Comment by muhammadimranfarooqi** [comment]
-1 to 7ba9648e8ba108f5f131c5a41255928499d35174 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5640/test_7ba9648-20200313-140504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
to 9c8583f68eca716be459db53ae9d895a91929046 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5640/test_9c8583f-20200313-165003.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , I cannot see the log anymore as a link leads to 404 Not Found page. Could you please trigger new fresh build.

Regarding tfaas removal, since this package is not related to production, and it has very complex build structure, I decided to delete it for time being to move forward with new Go compiler. Once we'll switch I'll work separately on adjusting tfaas spec to new compiler (I need time to figure out how to build Go TF, protobuf, etc, libraries which are required).

**Comment by muhammadimranfarooqi** [comment]
to 9c8583f68eca716be459db53ae9d895a91929046 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5640/test_9c8583f-20200313-173004.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
to 9c8583f68eca716be459db53ae9d895a91929046 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5640/test_9c8583f-20200313-175504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Valentin, after cleanup of das area it is still failing. I don't know where these logs are located.

**Comment by vkuznet** [comment]
Why did you close it? The last build link provided the log and I looked up what was wrong. Please re-open the issue, I can't do it here.

**Comment by smuzaffar** [comment]
it is failing because something depends on tfaas but this PR suggests to delete that spec file.
[a]
build/dmwmbld/srv/state/dmwmbld/builds/5640/cmsdist/tfaas.spec
ERROR! File not found: /build/dmwmbld/srv/state/dmwmbld/builds/5640/cmsdist/tfaas.spec

**Comment by vkuznet** [comment]
I figured it out with latest log and removed tfaas dependency, but I need to reopen the issue to test forward the new compiler.

Can you re-open the PR or should I create another one?

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Sorry, it was closed by mistake. I am opening this agian

**Comment by vkuznet** [comment]
please trigger new build since I removed tfaas dependency from comp.spec

**Comment by muhammadimranfarooqi** [comment]
-1 to ffe1ab4a2fd05d97b5ccc964ed50eaf5e83372e9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5640/test_ffe1ab4-20200313-182503.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
I'd suggest to remove tfass in a different PR. It has nothing to do with a go update.

**Comment by vkuznet** [comment]
Alan, unfortunately it does, the Go compiler is lower level and therefore if I change it the upper packages should be build as well. So far (due to complex tfaas build procedure) it fails and I can't get clean build. Once I'll know what fails and what not I'll separate PR into smaller chunks (if necessary). I'm still in a middle of the build and various upstream dependent packages.

**Comment by amaltaro** [comment]
So, my suggestion is to actually break it in 2 PRs.:
1. remove tfass from the stack software (and get it merged)
2. then update the go spec file in a separate PR

**Comment by vkuznet** [comment]
Alan, please do not provide suggestion on partial view. The changes requires not only to tfaas but to broader set of packages. In particular, I need DAS, all monitoring exporters to be compiled with new compiler. As I said I will align PR properly once I get all pieces.

**Comment by vkuznet** [comment]
TO move forward, I created separate PR for removing tfaas package, please see https://github.com/cms-sw/cmsdist/pull/5642/
I need this PR to be merged first to proceed with upgrade of Go compiler. Therefore I'm closing this PR and will await that @muhammadimranfarooqi  will merge #5642

**Comment by vkuznet** [comment]
For the record, I was only able to align our exporters with Go version 1.13.8, but couchdb exporter fails still with 1.14, therefore we'll upgrade to Go compiler 1.13.8, see https://github.com/cms-sw/cmsdist/pull/5643

**Pull request closed without merging**
