### PR TITLE
[G4VECGEOM] Update clhep to 2.4.6.0, vecgeom to 1.2.1

### LINKED ISSUE #8209: Migration to CLHEP 2.4.6.0
For the new version of Geant4 it is recommended to update CLHEP library to 2.4.6.0. It is expected that this update may be done for all IBs of CMSSW including master. Regression is expected.

### LINKED ISSUE #8210: Migration of G4VECGEOM branch to VecGeom 1.2.1
A new reference version of the VecGeom package 1.2.1 is available. It is recommended for the new Geant4 11.1. It would be good to test this version in advance using G4VECGEOM branch.

### PR DESCRIPTION
**Pull request by iarspider**
Closes #8209, #8210.

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , base branch for this PR is not correct

**Comment by iarspider** [comment]
please test

**Comment by civanch** [comment]
Is base IB OK?

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
G4 Vengeom IB is bit old , let me re-build a new one which we can use for testing

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
Please test

**Comment by smuzaffar** [comment]
@civanch , looks like tests are failing due to vecgeom update here
```
#5  0x00002adf1c01e5a5 in vecgeom::cxx::CommonUnplacedVolumeImplHelper<vecgeom::cxx::PolyhedronImplementation<(EInnerRadii)0, (EPhiCutout)0>, vecgeom::cxx::VUnplacedVolume>::SafetyToIn(vecgeom::cxx::Vector3D<double> const&) const () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#6  0x00002adf1c021dc7 in G4UAdapter<vecgeom::cxx::UnplacedPolyhedron>::DistanceToIn(CLHEP::Hep3Vector const&) const () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#7  0x00002adf1c0e6274 in G4VoxelNavigation::ComputeStep(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, double, double&, G4NavigationHistory&, bool&, CLHEP::Hep3Vector&, bool&, bool&, G4VPhysicalVolume**, int&) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#8  0x00002adf1bd00001 in G4Navigator::ComputeStep(CLHEP::Hep3Vector const&, CLHEP::Hep3Vector const&, double, double&) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#9  0x00002adf1bf1733a in G4Transportation::AlongStepGetPhysicalInteractionLength(G4Track const&, double, double, double&, G4GPILSelection*) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#10 0x00002adf1c554bf2 in G4SteppingManager::DefinePhysicalStepLength() () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#11 0x00002adf1c555d00 in G4SteppingManager::Stepping() () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#12 0x00002adf1bf0f27b in G4TrackingManager::ProcessOneTrack(G4Track*) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#13 0x00002adf1bba0f79 in G4EventManager::DoProcessing(G4Event*) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so
#14 0x00002adf1b80ae60 in RunManagerMTWorker::produce(edm::Event const&, edm::EventSetup const&, RunManagerMT&) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8211/29458/CMSSW_13_0_G4VECGEOM_X_2022-12-04-2300/biglib/el8_amd64_gcc11/pluginSimulation.so

```

**Comment by civanch** [comment]
@smuzaffar , I make a ticket to VecGeom and Jonas just report that -O2 with gcc11 resolve the issue. So, it is a very specific VecGeom problem (code seems to be correct but during optimisation non-initialized vector is crashing). Until it s understood -O2 should be used for VecGeom.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , we discuss with Gabriele. He said two things: 1) Geant4 tests for any platform only using -O2 for all components including Geant4 itself. He claim that -O3 does not bring speed-up in Geant4 benchmarks. 2) VecGeom 1.2.1 includes fixes proposed by ATLAS, they should not affect CMS in a significant way from his point of view.

So, there are two possibilities: propagate -O2 to VecGeom, Geant4, and dd4hep or stay with VecGeom 1.2.0. In the last case we only update clhep.

**Comment by smuzaffar** [comment]
@civanch , I am fine with both options. Do you have any preference?

**Comment by civanch** [comment]
Of course, if we manage to use 1.2.1 it seems to be better. Gabriele claims that -O2 is as performant as -O3.

**Comment by hahnjo** [comment]
I think you should prefer `-O2`. The fact that `gcc11` equally miscompiles VecGeom means that whatever we thought the problem is was not fixed with `gcc11`. By extension, it means that it can get other parts of VecGeom wrong that we just haven't found yet...

**Comment by smuzaffar** [comment]
please test
ok, I have updated dd4hep, vecgeom and geant4 to use `-O2 -DNDEBUG`

**Comment by smuzaffar** [comment]
please test

**Comment by aandvalenzuela** [comment]
It seems comparison is not going to report the results back since it is failing at:
```
09:08:17 + mv /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-eac510/1000.0_RunMinBias2011A /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-eac510/1000.0_RunMinBias2011A
09:08:17 mv: cannot move '/data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-eac510/1000.0_RunMinBias2011A' to a subdirectory of itself, '/data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-eac510/1000.0_RunMinBias2011A/1000.0_RunMinBias2011A'
```
I am writing a small fix for this

**Comment by smuzaffar** [comment]
thanks @aandvalenzuela for checking this. https://github.com/cms-sw/cms-bot/commit/25334a80677fb9dee7c5758c9043ca90f5efc701 change should fix the issue. I have restarted the comparison job now

**Comment by aandvalenzuela** [comment]
I first added this extra check https://github.com/cms-sw/cms-bot/blob/master/pr_testing/run-pr-comparisons#L126, should I keep it @smuzaffar?

**Comment by smuzaffar** [comment]
thanks for typo fix at https://github.com/cms-sw/cms-bot/commit/06cf85056df37c45a71770a6c0736ad998c2d06d :-)
No need to have https://github.com/cms-sw/cms-bot/blob/master/pr_testing/run-pr-comparisons#L126 but it is harmless, so no need to remove it

**Comment by hahnjo** [comment]
FWIW I opened https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108008, let's see what the GCC people think

**Comment by smuzaffar** [comment]
@civanch , this looks good now. I am merging it for next G4 Vecgeom IB

**Comment by civanch** [comment]
@smuzaffar , thanks, it is confirmed by gcc that there is problem in -O3. When new IB will be available will try to check CPU.

**Comment by smuzaffar** [comment]
@civanch , CMSSW_13_0_G4VECGEOM_X_2022-12-07-2300 and CMSSW_13_0_GEANT4_X_2022-12-07-2300 IBs are available

**Comment by civanch** [comment]
I have check CPU. It turned out that this switch from -O3 to -O2 provide CPU penalty 2.2% for MinBias and 4.9% for ttbar. So, we need -O3 indeed. The solution may be work around for problematic class of VecGeom

**Comment by hahnjo** [comment]
Yes, I can also measure the performance penalty. We *may* try working around the problem (I can prepare a patch), *or* we can try compiling Geant4 with `-O3` and only VecGeom with `-O2` (as we did in the past).

**Comment by hahnjo** [comment]
FWIW the bug in GCC should be fixed, cf. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107323 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108008. Once there is an updated compiler with the fixes, we can consider going back to `-O3` also for VecGeom.

**Pull request merged**
