### PR TITLE
Add new dataset for Geant4 10.02: G4ENSDFSTATE.

### LINKED ISSUE #2191: Update list of Geant4 data for Geant4 10.2
Geant4 10.2 requires a new dataset G4ENSDFSTATEDATA1.2.1 (1.6Mb), tar file is available at url: http://geant4.web.cern.ch/geant4/support/download.shtml

This file may be added both to the main and DEVEL branches.

There are updated data files for 10.2 in the same page:
  G4EMLOW6.48 (24.2Mb)
  G4PhotonEvaporation3.2 (8.9 Mb)
  G4RadioactiveDecay4.3.1 (7.6 Mb)
These files are not backward compatible, so should be used only in the DEVEL branch until Geant4 10.2 will be moved to the main branch.

### PR DESCRIPTION
**Pull request by ghost**
Fix #2191.

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
@civanch Looks like the matrix errors are genuine, see for instance [135.4](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2192/131/runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log):

```
-------- EEEE ------- G4Exception-START -------- EEEE -------

*** ExceptionHandler is not defined ***
*** G4Exception : PART70000
      issued by : G4NuclideTable
G4ENSDFSTATEDATA environment variable must be set
*** Fatal Exception ***
-------- EEEE -------- G4Exception-END --------- EEEE -------
```

Looks like we need to modify something in Pythia.

**Comment by civanch** [comment]
@degano , I suspect that in  geant4-G4ENSDFSTATE.spec in line#2 we need
%define G4RunTime G4ENSDFSTATEDATA

**Comment by ghost** [comment]
@civanch Okay, I'll try that now.

**Comment by ghost** [comment]
please test

**Pull request merged**
