### PR TITLE
update pythia8 to version 235

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
please test

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mkirsano , I guess the two updates (for memory leaks) we had on top of 230 
https://github.com/cms-externals/pythia8/commit/883c288615359bb7cef2f716e3f1ba4cc794bbd8
https://github.com/cms-externals/pythia8/commit/c8c4231b482948d62271ff88b286432445365b78
are not needed any more with this version of pythia8?

**Comment by mkirsano** [comment]
@smuzaffar hopefully the memory leak is fixed by the authors. I am going to check it immediately after merge.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by perrozzi** [comment]
just for me to understand: is that a compilation problem? if so, does it seem to depend on the gcc version?

**Comment by mkirsano** [comment]
I see that in Matrix Tests Outputs there are two tests with identical generator part: 5.1_TTbar+TTbarFS+HARVESTFS/
25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT/
The first one passes with 10 events, the second crashes in the first pythia event. Does it mean that the crash has nothing to do with pythia?

**Comment by smuzaffar** [comment]
these error looks reproducible and looks like they are coming from pythia
```
Thread 1 (Thread 0x7fb1e1adfc20 (LWP 13453)):
#0  0x0000003553edf383 in poll () from /lib64/libc.so.6
#1  0x00007fb1df3bb774 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02519/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-04-08-0000/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007fb1df3bc06a in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02519/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-04-08-0000/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007fb1df3bd166 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02519/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-04-08-0000/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007fb1c8b1955d in Pythia8::ProcessLevel::nextOne(Pythia8::Event&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-04-10-1100/external/slc6_amd64_gcc630/lib/libpythia8.so
#6  0x00007fb1c8b1a49d in Pythia8::ProcessLevel::next(Pythia8::Event&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-04-10-1100/external/slc6_amd64_gcc630/lib/libpythia8.so
#7  0x00007fb1c8b2cee9 in Pythia8::Pythia::next() () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-04-10-1100/external/slc6_amd64_gcc630/lib/libpythia8.so
#8  0x00007fb1cb68b3ff in Pythia8Hadronizer::generatePartonsAndHadronize() () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-04-10-1100/lib/slc6_amd64_gcc630/pluginGeneratorInterfacePythia8Filters.so
#9  0x00007fb1cb6bdd19 in edm::GeneratorFilter<Pythia8Hadronizer, gen::ExternalDecayDriver>::filter(edm::Event&, edm::EventSetup const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-04-10-1100/lib/slc6_amd64_gcc630/pluginGeneratorInterfacePythia8Filters.so
```

**Comment by mkirsano** [comment]
Yes, but there is another test where the same code works in the same way (at least it should) and does not crash. Anyway, is there any idea how this can be debugged? The whole CMSSW should be built for this, I have never tried it.

**Comment by smuzaffar** [comment]
it could be that there might be missing dependency and we might not be building something during PR tests which should have been built. 
I would suggest to put it in DEVEL IBs first.

**Comment by smuzaffar** [comment]
@mkirsano , CMSSW_10_2_DEVEL_X_2018-04-12-1100 contains new version of pythia8 but I see there are tests crashing in the IB too 

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_2_DEVEL_X_2018-04-12-1100/unitTestLogs/RecoMET/METProducers

**Comment by mkirsano** [comment]
@smuzaffar thanks, I ran Pythia8Interface internal tests, all passed. Also, I checked that the memory leak in lhapdf interface is fixed.

**Comment by smuzaffar** [comment]
@mkirsano , do you understand the reason behind the failing tests in devel IB. They look related to pythia8 update.

**Comment by mkirsano** [comment]
OK, I am trying to look. I reproduced it. The minimal config causing crash is in attachment. The crash disappears if I remove the simulation step

[fail.txt](https://github.com/cms-sw/cmsdist/files/1907062/fail.txt)

**Comment by mkirsano** [comment]
The reason of the crash is some memory corruption. In the method ProcessLevel::nextOne, after the event generation,  infoPtr->isVMDstateA() = 48. This should never happen in pp collisions. Also, this is a bool variable. infoPtr->idVMDA(), infoPtr->mVMDA() etc are crazy numbers.
I remind that this happens only in presence of the simulation step.

**Comment by mkirsano** [comment]
@Dr15Jones @fabiocos , can somebody help with debugging this? The problem seems to be related to pythia8 235, but pythia8 without simulation step works fine, so it can be a manifestation of a bug in CMSSW. I have no experience with debugging the memory corruption. We are going to put a request at the meting next week, but I don't know if the development release will live until then.

**Comment by Dr15Jones** [comment]
I would suggest running this program under valgrind
```
valgrind cmsRun config.py
```

Be warned, this will be about 60x slower. valgrind is very good at finding memory problems.

**Comment by mkirsano** [comment]
@Dr15Jones with valgrind it did not crash

**Pull request merged**
