### PR TITLE
Update libffi to 3.4.2

### PR DESCRIPTION
**Pull request by mrodozov**
the 3.2.1 version is 7 years old
https://github.com/libffi/libffi/releases/tag/v3.2.1

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
@mrodozov , it is not `libtiff` ... right? please update the PR title and commit message

**Comment by mrodozov** [comment]
> @mrodozov , it is not `libtiff` ... right? please update the PR title and commit message

yes, sorry about that it's strange I named the branch properly and malapropped the commit message

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = Alignment,CondCore

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
hold
this does not fix the ppc64le unit test failure issue. As this rebuild nearly all the externals so lets hold on to this update and we can include it either in newer archs e.g. gcc11 or we can merge it once we have to change any other base level package.

**Pull request merged**
