### PR TITLE
[LWTNN] update to version 2.10

### PR DESCRIPTION
**Pull request by smuzaffar**
new version should fix the issue reported here https://github.com/cms-sw/cmsdist/issues/5122#issuecomment-520465810

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , this is ready to go in. Feel free to merge it before 11.0.pre7. It is suppose to fix ths issue mentioned https://github.com/cms-sw/cmsdist/issues/5122#issuecomment-520465810

**Comment by fabiocos** [comment]
@smuzaffar thank you, I will integrate it for next IB

**Comment by fabiocos** [comment]
+1

**Pull request merged**
