### PR TITLE
add pandas

### PR DESCRIPTION
**Pull request by TaiSakuma**
This PR adds [_pandas_](http://pandas.pydata.org/).

Following [the presentation](https://indico.cern.ch/event/384920/session/4/contribution/3) at [the RECO/AT meeting](https://indico.cern.ch/event/384920/) on Thursday, 30 April 2015, I tried writing _spec files_ for _pandas_ and its requirements.

This is my first PR to this repo. I am not familiar with the development of this repo. I might not be doing right.

First, this PR is made to the branch [IB/CMSSW_7_5_X/stable](https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_7_5_X/stable). I am not sure if this is the right branch. Please let me know if this PR should be made to another branch.

_pandas_ depends on three other packages. It also has recommended and optional dependencies. These are listed at:
- http://pandas.pydata.org/pandas-docs/stable/install.html#dependencies

This PR upgrades NumPy and python-dateutil to meet the requirement.

The website above states that recommended dependencies provide large speedups for large data sets, which might be very useful. But this PR doesn't install those recommended dependencies. I could try to add them as a separate PR.

~~This PR adds ATLAS as NumPy uses it. The compilation of ATLAS is probably the most complicated part of this PR.~~
#### Comments of packages

I will add comments below for several packages.
##### ATLAS

(_This PR no longer adds ATLAS_)

This PR adds [ATLAS](http://math-atlas.sourceforge.net/), which NumPy uses for fast calculation of linear algebra. ATLAS is in the branch [IB/CMSSW_4_4_X/stable](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_4_4_X/stable/atlas.spec). I copied the spec file from the branch and updated to use [the most recent verion](http://sourceforge.net/projects/math-atlas/files/Stable/) of ATLAS.
###### Tuning

The performance of ATLAS depends on [how it is tuned](http://math-atlas.sourceforge.net/atlas_install/node6.html) at the compile time. This PR uses only `-b 64` for the tuning. This might not be the best option. Or this might not work on OSX.
###### Netlib LAPACK

This PR uses [the "--with-netlib-lapack-tarfile" option](http://math-atlas.sourceforge.net/atlas_install/node8.html), which will compile [netlib's LAPACK](http://www.netlib.org/lapack/) and install it. 

However, the _cmsdist_ also has _lapack.spec_. So there will be two instances of Netlib's LAPACK.
###### Shared objects

I modified Makefile such that shared objects are built in the way in which NumPy and other packages appear to expect.

The configuration option [--shared](http://math-atlas.sourceforge.net/atlas_install/node22.html) creates two share objects: _libsatlas.so_ and _libtatlas.so_, which include all symbols for serial and parallel API's respectively, which are not other packages that use ATLAS expect and find by default. For example, see [a stackoverflow post](http://stackoverflow.com/questions/13439296/build-shared-libraries-in-atlas).

This PR builds those two shared objects but doesn't install them.

Instead, this PR builds seven share objects, each for one archive file and install them. Those share objects are _libatlas.so_, _libf77blas.so_, _libcblas.so_, _liblapack.so_, _libptf77blas.so_, _libptcblas.so_, and _libptlapack.so_.
##### NumPy

[This website](http://www.scipy.org/scipylib/building/linux.html) says that shared objects for BLAS, LAPACK, and ATLAS can be specified by environmental variables. However, this wasn't the case when I tried. So instead, this PR uses _site.cfg_ to specify those.
##### _pandas_

I modified _setup.py_ so that _setuptools_ won't compile NumPy again. I think setuptools are supposed to check if requires are installed and if not then install them. However, it would always try to install NumPy even when NumPy is installed. I couldn't figure out why. So I just removed several lines in _setup.py_ that indicate the requirement of NumPy.

I removed the NumPy requirement from both `setup_requires` and `install_requires`. If it is in `setup_requires`, the setuptools would compile NumPy before compiling pandas. If it is not in `setup_requires` but in `install_requires`, the setuptools would compile NumPy after compiling _pandas_.
#### Test the branch

I tested my branch with the following commands on ~~lxplus~~ _cmsdev_.

``` bash
CMSSW_X_Y_Z=CMSSW_7_5_0_pre3
ARCH=slc6_amd64_gcc491
QUEUE=`echo $CMSSW_X_Y_Z | sed -e 's/\(CMSSW_[0-9][0-9]*_[0-9][0-9]*\).*/\1_X/'`
eval $(curl -f -L https://raw.githubusercontent.com/cms-sw/cms-bot/master/config.map | grep "SCRAM_ARCH=$ARCH;" | grep "RELEASE_QUEUE=$QUEUE;")
git clone -b $CMSDIST_TAG git@github.com:cms-sw/cmsdist.git CMSDIST
git clone -b $PKGTOOLS_TAG git@github.com:cms-sw/pkgtools.git PKGTOOLS
sh -e PKGTOOLS/scripts/prepare-cmsdist $CMSSW_X_Y_Z $ARCH
cd CMSDIST
git remote add mine git@github.com:TaiSakuma/cmsdist.git
git fetch mine
git merge mine/dev-20150430-01-CMSSW_7_5_X-pandas
cd ..
screen -e^vv -L time PKGTOOLS/cmsBuild --architecture=$ARCH --builders 4 -j 16 build cms-git-tools
screen -e^vv -L time PKGTOOLS/cmsBuild --architecture=$ARCH --builders 4 -j 16 build py2-pandas-toolfile
```

_pandas_ is compiled.

I don't know how to enter the environment that was built. So I didn't try to import _pandas_ to a Python script.

Any comments or suggestions are welcome.

### CODE REVIEW

**Comment by ktf** [comment]
I'm only concerned about the ATLAS usage, which is a painful beast to 
support, given it autotunes. Can't you use the standard version of 
LAPACK / BLAS?

## 

Ciao,
Giulio

**Comment by TaiSakuma** [comment]
@ktf, Ok. I will try without ATLAS.

**Comment by TaiSakuma** [comment]
@ktf, I updated the PR. It won't add ATLAS any more.

**Comment by ktf** [comment]
Thanks. @degano can you try this out? I would say let's get this PR in and then let's have a `cms-externals` repo for all the modified externals.

**Comment by ghost** [comment]
@ktf @TaiSakuma I'm testing it right now.

**Comment by ghost** [comment]
@ktf @TaiSakuma I found out an issue while building the packages that depends on the ones modified with this PR: py2-pyfits was not completing correctly.
I fixed the error on top of @TaiSakuma branch and created a PR to his repository here: https://github.com/TaiSakuma/cmsdist/pull/1.
The error is probably unrelated to this PR but would fail the whole compilation nevertheless.

**Comment by TaiSakuma** [comment]
@degano, thank you for the test and fix. I merged your PR.

**Comment by ghost** [comment]
+1
Tested compilation of all the externals involved and their dependencies.

**Pull request merged**
