### PR TITLE
[Do not merge] Test ROOT fix for TH2Poly class (ROOT PR #13267)

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Testing if ROOT fix provided at https://github.com/root-project/root/pull/13267 solves https://github.com/cms-sw/cmsdist/pull/8590.
Patch applied on top of the ROOT update (https://github.com/cms-sw/root/commits/cms/master/d2ac936296).

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
@aandvalenzuela , you need to update the tag in root.spec to be `9a34719fb2420d056e6eaf66b6e5e9817fcc830a` otherwise pr tests are only going to test the previous commit

**Comment by smuzaffar** [comment]
For root PRs testing, I would suggest to open a cms-sw/root PR using the root developers branch and directly run tests from cms-sw/root PR

**Comment by smuzaffar** [comment]
abort
bot is testing it against not ROOT6 IB as currently there is no 13.3.ROOT6.X IB

**Comment by aandvalenzuela** [comment]
Closing in favor of https://github.com/cms-sw/root/pull/180

**Pull request closed without merging**
