### PR TITLE
Updated root to tip of branch v6-22-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
get latest from 6-22 . 
wait for this night 6.22 IB to include https://github.com/cms-sw/cmssw/pull/32842 
(merged ~9 this morning and still not in the 6.22 IB)

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#32782

**Comment by mrodozov** [comment]
+externals
cms-sw/cmssw#32782 was merged and this can go in.

**Comment by makortel** [comment]
> [cms-sw/cmssw#32782](https://github.com/cms-sw/cmssw/pull/32782) was merged

No it isn't?

**Comment by mrodozov** [comment]
no it isn't. I was looking into cms-sw/cmssw#32842 :/

**Comment by silviodonato** [comment]
+1

**Pull request merged**
