### PR TITLE
Update data-L1Trigger-L1TCalorimeter.spec

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by ghost** [comment]
https://github.com/cms-data/L1Trigger-L1TCalorimeter/pull/11/commits/b6122c8bed771bb10c9551f078f463a26d18389d

**Comment by davidlange6** [comment]
hum - seems I forgot to merge this?

**Comment by davidlange6** [comment]
please test

**Comment by ghost** [comment]
@davidlange6 I think the tests won't help much since it's only files addition. If we'r good we can just merge this.

**Comment by davidlange6** [comment]
good point
will merge it

**Pull request merged**
