### PR TITLE
Update geant4 to 11.0.7 and dd4hep to 01.22

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test for CMSSW_12_6_GEANT4_X/el8_amd64_gcc10

**Comment by iarspider** [comment]
please test for CMSSW_12_6_GEANT4_X/el8_amd64_gcc11

**Comment by iarspider** [comment]
@civanch can you fix this error:
```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc10/external/geant4/11.0.7-4393c138cfd77b7e58b4a74cd61f7a23/include/Geant4/G4FTFTunings.hh:158:5: error: missing braces around initializer for 'std::__array_traits::_Type' {aka 'G4String [10]'} [-Werror=missing-braces]
  158 |     };
      |     ^
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc10/external/geant4/11.0.7-4393c138cfd77b7e58b4a74cd61f7a23/include/Geant4/G4FTFTunings.hh:161:96: error: missing braces around initializer for 'std::__array_traits::_Type' {aka 'int [10]'} [-Werror=missing-braces]
  161 |     std::array< G4int, sNumberOfTunes > fApplicabilityOfTunes = { 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
      |                                                                                                ^
```

**Comment by iarspider** [comment]
please test for CMSSW_12_6_GEANT4_X/el8_amd64_gcc10

**Comment by smuzaffar** [comment]
looks good to go in special geant4 ibs

**Comment by smuzaffar** [comment]
@iarspider , as this is merged now, can you open a PR for geant4 gcc11 too?

**Pull request merged**
