### PR TITLE
[G4]Update to version 11.3.cand00 along with G4 dataset

### PR DESCRIPTION
**Pull request by smuzaffar**
FYI @civanch

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_GEANT4_X

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmssw#46675
- release = CMSSW_14_2_GEANT4_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_GEANT4_X

**Comment by civanch** [comment]
@smuzaffar , There is the fix I in CMSSW  https://github.com/cms-sw/cmssw/pull/46675

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_GEANT4_X

**Comment by civanch** [comment]
@smuzaffar , sorry I miss your PR and make https://github.com/cms-sw/cmssw/pull/46675 which is doing the same thing. Let us continue testing with your PR.

**Comment by smuzaffar** [comment]
No worries @civanch , https://github.com/cms-sw/cmssw/pull/46675  has a better implementation so I have close mine

**Comment by civanch** [comment]
Let us first finish testing.

**Comment by iarspider** [comment]
@cmsbuild ignore tests-rejected with ib-failure
See https://github.com/cms-sw/cmssw/issues/46682

**Comment by iarspider** [comment]
@smuzaffar I think this is good to go into G4/G4VecGeom IBs.

**Comment by smuzaffar** [comment]
No @iarspider , it needs https://github.com/cms-sw/cmssw/pull/46675 PR to merge first

**Comment by smuzaffar** [comment]
+externals

good to go in Geant4 IB. I will start a special build of G4 at 13h00

**Pull request merged**
