### PR TITLE
WMAgent release candidate 1.4.7.patch1

### PR DESCRIPTION
**Pull request by amaltaro**
First WMAgent release candidate for the 1.4.7 series.

I'm taking advantage and also bumping our python3-based WMAgent spec.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 4ef7d797dd3d66130891f4ea842eabb11a8f7583 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6811/test_4ef7d79-20210414-202003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Comment by amaltaro** [comment]
FYI @todor-ivanov

**Comment by todor-ivanov** [comment]
Thanks @amaltaro !

**Pull request merged**
