### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**
refresh the install.sh script with new PR number

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with cms-sw/cms-bot#1586

**Comment by smuzaffar** [comment]
1. cms-bot PR has been merged, so no need to test with it
2. the error reported here https://github.com/cms-sw/cmsdist/pull/7102#issuecomment-879028190 looks real. I think root might have (re)moved the `RooMinuit.h` here. We might need to check and fix cmssw code

**Comment by mrodozov** [comment]
sure the error is real, I've built ROOT already to fix the cmssw part, the only thing we'll need the install.sh scirpt is to checkout all cmssw deps to fix all "surprises" that may pop up

**Comment by smuzaffar** [comment]
No idea what do you mean by " install.sh scirpt is to checkout all cmssw", according to previous test the only error is in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2a6883/16741/build-logs/ ( PhysicsTools/TagAndProbe )

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/34461

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#34461 for CMSSW_12_0_ROOT6_X

**Comment by mrodozov** [comment]
in any case we can't have the root master change in cmssw master, unless RooMinimizer is able to substitute RooMinuit in 6.22, which means backporting this rootmaster change to 6.22

**Pull request merged**
