### PR TITLE
Create spec for rucio-client python library

### PR DESCRIPTION
**Pull request by amaltaro**
Superseeds #4389

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to db66c2c98464c760ba73590b92e0eb4836a365b2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4647/test_db66c2c-20190117-152504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@h4d4 can you please clarify which pkgtools branch and commit is the bot builder using?
I just tried building this RPM and it failed with missing dependencies.

**Comment by h4d4** [comment]
+1 to 47e0551ccbed361f28880c7f0133414f88a3103d on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4647/test_47e0551-20190117-170505.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@h4d4 I ran some basic tests and I'm now able to use the rucio-clients library. This is ready to be merged as well.

**Pull request merged**
