### PR TITLE
igprof: changes for running on AL9 host

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
@gartung

**Comment by gartung** [comment]
@smuzaffar new commit 0488ecf96b6c834bff422ce1d14bf76c57cbd14e

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
One more change. commit 16da627e12a806cd8ab072e7288223c91086ea25

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
@smuzaffar new commit 0488ecf96b6c834bff422ce1d14bf76c57cbd14e

**Comment by gartung** [comment]
@smuzaffar One more change.  commit 16da627e12a806cd8ab072e7288223c91086ea25

**Comment by gartung** [comment]
@smuzaffar  see https://github.com/cms-sw/cmsdist/pull/9229
All tests pass.

**Comment by smuzaffar** [comment]
closing in favor of https://github.com/cms-sw/cmsdist/pull/9229

**Pull request closed without merging**
