### PR TITLE
Update ROOT 6.26 in CMSSW master

### PR DESCRIPTION
**Pull request by iarspider**
Align with rootnext branch

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
its is a version update, so better to run the tests with `full_cmssw`

**Comment by iarspider** [comment]
test parameters:
- full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

looks good to go in 13.1.X

**Comment by smuzaffar** [comment]
@iarspider , can you please disable ROOT626 IBs now

**Pull request merged**
