### PR TITLE
updating sherpa 2.2.6 to bugfix release sherpa 2.2.7

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test workflow 534.0,536.0

**Comment by smuzaffar** [comment]
+externals
@fabiocos , this is ready to go in master

**Comment by fabiocos** [comment]
@SiewYan @qliphy @agrohsje which kind of physics validation was done of this package? Or are you planning to do it on the 11_0_X development branch?

**Comment by SiewYan** [comment]
@fabiocos , We are planning to do it on 11_0_X development branch.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
