### PR TITLE
dasgoclient: Updated to version v02.05.52

### PR DESCRIPTION
**Pull request by smuzaffar**
New dasgoclient is also build for riscv64

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
This version needs Cython 3.x, but we can't update Cython - this will break numpy, and we can't update numpy because it will break Tensorflow.

**Comment by iarspider** [comment]
https://github.com/scikit-learn/scikit-learn/blob/1.5.0/pyproject.toml#L97

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
