### PR TITLE
Update ROOT to use tagged version 6.30.04+cms patch in master IBs

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
test parameters:

- full_cmssw = true

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

looks good but let include it in 14.1.X

**Comment by smuzaffar** [comment]
@makortel @Dr15Jones  , this update root to `6.30.04` . the ROOT changes w.r.t to we have in 14.0.X are https://github.com/root-project/root/compare/be7addb844...b9577a0bdf . Any objections on move to ROOT 6.30.04 for 14.1.X . We can also backport it to 14.0.X if needed

**Comment by Dr15Jones** [comment]
I don't have any issues on my side

**Comment by makortel** [comment]
No objections from me either. The commit list showed some fixes that could be nice to have in 14_0_X too.

**Comment by smuzaffar** [comment]
merging it for 14.1.X

**Pull request merged**
