### PR TITLE
Revert "adding VBFNLO and Hjets++ to the externals linked to Herwig7"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmsdist#4753

Pending the fix preventing to build with gcc9

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @alberto-sanchez @Andrej-CMS how much urgent and critical is this addition? At present this is a show-stopper to move forward with gcc9. Do you have a reactive contact person among the authors to discuss with?

**Comment by Andrej-CMS** [comment]
Dear @fabiocos ,
I think, you can revert this change, if it doesn't compile in GCC9. I will forward the information to the authors

**Comment by Andrej-CMS** [comment]
@fabiocos 
could you maybe point me to the error that happens when you compile it with GCC9? This will certainly help the authors

**Comment by fabiocos** [comment]
@Andrej-CMS please see the comment of @smuzaffar https://github.com/cms-sw/cmsdist/pull/4753#issuecomment-499497841

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar if we want to try a gcc9 build corresponding to 11_0_0_pre2 better to merge this into next IB

**Comment by smuzaffar** [comment]
+externals
agree @fabiocos

**Comment by smuzaffar** [comment]
I have restarted 23h IB for GCC9 now

**Comment by fabiocos** [comment]
@smuzaffar good, let's see how it goes...

**Comment by Andrej-CMS** [comment]
> @efeyazgan @qliphy @alberto-sanchez @Andrej-CMS how much urgent and critical is this addition? At present this is a show-stopper to move forward with gcc9. Do you have a reactive contact person among the authors to discuss with?

@fabiocos I have contacted the authors and will make a new PR, when they provide a new version that compiles in GCC9

**Comment by fabiocos** [comment]
@Andrej-CMS excellent, thank you for following this issue

**Pull request merged**
