### PR TITLE
Added pyGithub, the python library to acces github

### PR DESCRIPTION
**Pull request by nclopezo**
It is used by the report-pull-request-results script. I just noticed that I had accidentally pushed to the cms-sw repository for the pull request #332

### CODE REVIEW

**Comment by ktf** [comment]
Can you do it for 71X? Thanks.

**Comment by nclopezo** [comment]
Can I reopen this for 7_0_X and also add it for 6_2_X, In the tests for these releases, the tests still need to copy the library.

**Comment by ktf** [comment]
This is working in 71X, right? Yes, please back port to 70X, 62X and 53X.

@davidlange6

**Comment by nclopezo** [comment]
Yes, this is working in 7_1_X

**Pull request merged**
