### PR TITLE
Updated root to tip of branch v6-14-00-patches

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@fabiocos , this just include a small update ( https://github.com/root-project/root/commit/84a781add3e02f17cea71665b76b87c8b5dd3a8d ) on top what we already have in CMSSW_11_0_X. This was requested by @ianna . I would suggest to include it for tonight's IB.

**Comment by fabiocos** [comment]
@smuzaffar @ianna I will integrate it tonight

**Comment by fabiocos** [comment]
+1

**Pull request merged**
