### PR TITLE
[Tensorflow] Update to version 2.5.0

### PR DESCRIPTION
**Pull request by smuzaffar**
- Tensorflow 2.5.0
- Bazel 3.7.2
- Eigen commit https://gitlab.com/libeigen/eigen/-/commit/f612df273689a19d25b45ca4f8269463207c4fee as requited by TF
- tensorboard 2.5.0
- tensorboard-data-server 0.6.1
- tensorflow-estimator 2.5.0

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

FYI @riga

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
enable profiling

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
assign reconstruction
@cms-sw/reconstruction-l2  tensorflow 2.5.0 update looks good, can you please check the profiling results and sign this PR if all look good?

**Comment by smuzaffar** [comment]
@slava77,@perrotta,@jpata any objection on going forward with TF 2.5.0 integration?

**Comment by slava77** [comment]
> @slava77,@perrotta,@jpata any objection on going forward with TF 2.5.0 integration?

https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_12_0_X_2021-07-15-2300%2Fslc7_amd64_gcc900%2F11834.21%2FPR-39f2e8%2F16905%2Fstep4_PAT_PU.resources&resource=time_thread&colours=default&groups=packages&threshold=0
vs
baseline
https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_12_0_X_2021-07-15-2300%2Fslc7_amd64_gcc900%2F11834.21%2Fstep4_PAT_PU.resources&resource=time_thread&colours=default&groups=packages&threshold=0

timing of deepTau and deepMet modules looks consistent (both are a few % slower with this PR tests, but some other times are up as well, which is most likely the measurement stability). Also, there are no differences.

So, it should be fine to merge for reco needs.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
