### PR TITLE
Use a private pythia8 200pre1 tarball in cmsdist 73x with some other changes in the pythia8 spec files

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
To be synchronized with CMSSW_7_3_X GeneratorInterface changes, PR CMSSW #5422

**Comment by bendavid** [comment]
Just for book-keeping sake can you rename this pull request to something more descriptive?

**Comment by bendavid** [comment]
+1

**Comment by mkirsano** [comment]
Josh, do you mean that the branch name should be longer?
I have never renamed a branch that is already pushed, can try now.

**Comment by bendavid** [comment]
No no I just meant the name of the pull request in the web interface.

**Comment by bendavid** [comment]
The "my log message of changes" that appears at the top of the page.  I think you should have an edit button to change it right from the web interface.

**Comment by bendavid** [comment]
perfect, thanks

**Comment by bendavid** [comment]
@degano, this is going to need another iteration.  Shouldn't break anything as is, but the new jet matching code is not quite usable.  Might be useful to anyways include this and see if we break existing tests in the 73x IB.
(The forthcoming fix concerns namespace/inlining issues in headers which are curently not used in CMSSW)

**Pull request merged**
