### PR TITLE
Update RecoEgamma-ElectronIdentification to new tag

### PR DESCRIPTION
**Pull request by mrodozov**
https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/8

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
@mrodozov @smuzaffar
please make the same change for 94_MAOD_X as well

Thank you.

This is needed for integration of https://github.com/cms-sw/cmssw/pull/22303

**Comment by smuzaffar** [comment]
@slava77 , as cms-data/RecoEgamma-ElectronIdentification#8 just adds new files, so I think it should be safe to add this in 94X instead of creating a new external branch for 94MAOD.

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
is there an external PR for the 94X MAOD now?

**Comment by smuzaffar** [comment]
@slava77 , https://github.com/cms-sw/cmsdist/pull/3774 is for 94X (94MAOD)

**Pull request merged**
