### PR TITLE
Update cuda to 10.1.168 for x86_64

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
looks good to merge.  merging it for tonight's IB.
FYI @fwyzard

**Comment by fwyzard** [comment]
Thanks !

In the meantime CUDA 10.1 update 2 was released, and I may have an update
for ARM as well.

.A

**Comment by smuzaffar** [comment]
@fwyzard , looks like they have changed the structure of cuda-toolkit (specially for NsightCompute-*) and now it contains
```
ls cuda-toolkit
bin  doc  EULA.txt  extras  include  lib64  libnsight  libnvvp  nsight-compute-2019.4.0  nsightee_plugins  nsight-systems-2019.3.7.5  nvml  nvvm  share  src  targets  tools  version.txt
```
can you please look in to it and make update cuda.spec?

**Comment by fwyzard** [comment]
Sure, will do.

**Comment by fwyzard** [comment]
See #5191 .

**Pull request merged**
