### PR TITLE
Update Photos++ to 3.61 and EvtGen to 1.6.0 (7_1_X)

### PR DESCRIPTION
**Pull request by mseidel42**
Adds pair emission, needed for backport of https://github.com/cms-sw/cmssw/pull/26853

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mseidel42** [comment]
Hm, looks like we would need to update EvtGen (and Tauola++) as well :(

@mkirsano Do you think that could work easily, or do we need to change the CMSSW interfaces as well then?

**Comment by mkirsano** [comment]
I don't remember that this needed interface change, but I could forget. We have already photos++ 3.61 in master and higher releases, can look there and compare. In principle, Junquan Tao is a responsible for photos++ integration, you can try to ask him to perform this upgrade. If he is not available please let me know.

**Comment by alberto-sanchez** [comment]
Sorry, I did not realise of this discussion when I launched the test of  cms-sw/cmssw#26886

**Comment by mseidel42** [comment]
Externals and CMSSW interfaces (see https://github.com/cms-sw/cmssw/pull/26886) compile fine after updating EvtGen to 1.6.0.

However, I still get this at runtime and cannot figure out where the 3.56 remant is hiding. I hope it does not occur in a clean test build:
```
                            =========================
                              PHOTOS, Version:  3.56
                              Released at:  3/5/14
                            =========================
```

**Comment by mseidel42** [comment]
Sorry, one patch was missing

**Comment by mseidel42** [comment]
I emailed BPH conveners to ask if the EvtGen upgrade is ok for them.

Apart from that, it would be great to have an IB as soon as possible, so that I can test the whole production chain.

**Comment by mseidel42** [comment]
BPH would be happy about an upgrade (EvtGen 1.7.0 if possible) but I get crashes like this:

```
Begin processing the 394th record. Run 1, Event 394, LumiSection 1 at 31-May-2019 18:15:44.882 CEST
********************************************************************************
*
* WT_INT: Combined Weight is exceeding 1., Weight =        1.022487
* Fatal Error Message, I stop this Run !
*
********************************************************************************
```

Checking with Photos authors but it might also be due to the problem that I have Photos 3.56 remnant somewhere in my test setup :(

`scram tool info` looks ok though, and compilation of the updated interface would fail with the old version 3.56:
```
% scram tool info photospp
Tool info as configured in location /afs/cern.ch/work/m/mseidel/CMSSW_dev/Photos/CMSSW_7_1_41
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Name : photospp
Version : 3.61
++++++++++++++++++++
SCRAM_PROJECT=no
PHOTOSPP_BASE=/afs/cern.ch/work/m/mseidel/CMSSW_dev/Photos/a/slc6_amd64_gcc481/external/photospp/3.61
LIB=Photospp PhotosppHepMC PhotosppHEPEVT
LIBDIR=/afs/cern.ch/work/m/mseidel/CMSSW_dev/Photos/a/slc6_amd64_gcc481/external/photospp/3.61/lib
INCLUDE=/afs/cern.ch/work/m/mseidel/CMSSW_dev/Photos/a/slc6_amd64_gcc481/external/photospp/3.61/include
USE=hepmc

```

**Comment by mseidel42** [comment]
Updating DECAY.DEC and evt.pdl files (don't know if these have been specifically adapted for CMS?) solves the WT_INT error but the EvtGen run just hangs after some hundred events.

@mrodozov Are there instructions to build a clean CMSSW release from scratch? Or can I access the JIRA builts somehow?

**Comment by mseidel42** [comment]
Let me add that same test config with Photos++ 3.61 and EvtGen 1.6.0 runs without problems in 10_6_0. So I am 90% confident that the problem is caused by some Photos 3.56 zombie lib in my setup, and a clean build should work fine.

**Comment by mrodozov** [comment]
There are instructions here:
https://twiki.cern.ch/twiki/bin/view/CMS/SDTHowToBuildCMSSWRelease
and here:
http://cms-sw.github.io/build-release.html but only release managers can request (approve) a release.
I'd suggest to build the cmssw-tool-conf external with this PR changes inside the cmsdist folder (it would rebuild only the changes) and then have cmssw setup linked against the locally built externals to make sure cmssw doesn't have anything remaining from the old setup (not that it has as far as I can see now)
Let me know if you have done that already.

**Comment by mseidel42** [comment]
Thanks for the suggestion! I asked to build only photos-toolfile and evtgen-toolfile before.

However, now it fails when installing the RPMs:
```
File "/eos/home-m/mseidel/CMSSW_dev/PhotosUpdate/a/share/cms/cmspkg/V00-00-30/cmspkg.py", line 501, in update_rpm_cache
n, rv = r.split(" ")
ValueError: too many values to unpack
```

**Comment by mrodozov** [comment]
Can you send the full log or describe how to reproduce this (the commands you are running)

**Comment by mseidel42** [comment]
It seems to be an eos problem, it works now when I compile `cmssw-tool-conf ` in a /tmp directory. Do you know if there are still any lxbuild instances to do these things?

> and then have cmssw setup linked against the locally built externals to make sure cmssw doesn't have anything remaining from the old setup

I was not sure how to do this, so I am trying to compile `cmssw` now so that I can change my `$CMS_PATH` and fetch it completely from there.

**Comment by mseidel42** [comment]
Compiling `cmssw` fails with:
```
>> Compiling  /tmp/mseidel/a/tmpX/BUILDROOT/95332dcd43211c3dae07e060cc2eb3af/opt/cmssw/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_41-cms/src/CommonTools/Utils/src/returnType.cc 
/tmp/mseidel/a/slc6_amd64_gcc481/external/gcc/4.8.1/bin/c++ -c -DGNU_GCC -D_GNU_SOURCE -DCMSSW_GIT_HASH="CMSSW_7_1_41" -DPROJECT_NAME="CMSSW" -DPROJECT_VERSION="CMSSW_7_1_41-cms" -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -I/tmp/mseidel/a/tmpX/BUILDROOT/95332dcd43211c3dae07e060cc2eb3af/opt/cmssw/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_41-cms/src -I/tmp/mseidel/a/slc6_amd64_gcc481/lcg/root/5.34.18-ddibom/cint -I/tmp/mseidel/a/slc6_amd64_gcc481/external/boost/1.51.0-cms2/include -I/tmp/mseidel/a/slc6_amd64_gcc481/external/libuuid/2.22.2/include -I/tmp/mseidel/a/slc6_amd64_gcc481/external/pcre/7.9__8.33/include -I/tmp/mseidel/a/slc6_amd64_gcc481/external/bz2lib/1.0.5/include -I/tmp/mseidel/a/slc6_amd64_gcc481/external/tbb/42_20131118oss/include -I/tmp/mseidel/a/slc6_amd64_gcc481/external/zlib/1.2.8/include -I/tmp/mseidel/a/slc6_amd64_gcc481/lcg/root/5.34.18-ddibom/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -Wstrict-overflow -std=c++11 -msse3 -ftree-vectorize -Wno-strict-overflow -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -fipa-pta -felide-constructors -fmessage-length=0 -ftemplate-depth-300 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=maybe-uninitialized -Werror=strict-aliasing -Werror=narrowing -Werror=uninitialized -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -DBOOST_DISABLE_ASSERTS -fPIC -MMD -MF tmp/slc6_amd64_gcc481/src/CommonTools/Utils/src/CommonToolsUtils/returnType.d /tmp/mseidel/a/tmpX/BUILDROOT/95332dcd43211c3dae07e060cc2eb3af/opt/cmssw/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_41-cms/src/CommonTools/Utils/src/returnType.cc -o tmp/slc6_amd64_gcc481/src/CommonTools/Utils/src/CommonToolsUtils/returnType.o
+ '[' '' == set ']'
error: Bad exit status from /tmp/mseidel/a/tmpX/rpm-tmp.13FW5W (%build)


RPM build errors:
    Bad exit status from /tmp/mseidel/a/tmpX/rpm-tmp.13FW5W (%build)
```

The command I am using is `time pkgtools/cmsBuild --new-scheduler -i a -a slc6_amd64_gcc481 --builders 4 -j $(($(getconf _NPROCESSORS_ONLN) * 2)) build cmssw` with CMSSW version set to 7_1_41 in cmssw.spec.

**Comment by fabiocos** [comment]
@intrepid42 @efeyazgan @qliphy as discussed at the last ORP meeting, this PR both updates PHOTOS, which might be ok, and evtgen. Which is the physics backward compatibility of both of them? The corresponding CMSSSW PHOTOS update has been already backported to 9_3_X, but that was not changing the underlying external version.

**Comment by mseidel42** [comment]
While the email discussion is ongoing, let me put the change logs here for reference:

**Photos 3.56->3.61**

```
Sept 29 2015
- Change to enable use of Photos in case when there are no incoming (beam
  or grandmother(s) ) for the decaying particle. Relevant part of the code, 
  requiring the adaptation, became active since introduction of pair 
  emission in  Photos v. 3.56. Such non-standard contents of event records
  result in some cases of downgraded precision. In particular, matrix elements 
  in case of Z/gamma*/W  (in future also narrow vector states) decays, 
  can not be then calculated. Thanks to John Back and Michal Kreps 
  for the input. 
Apr 26 2015
- cleaning of code, examples reference files completed. 
  Version no 3.60 introduced, code prepared for submission to CPC 
Mar 24 2015
- examples updated to pythia v8.2
- LCG scripts updated to the new directory structure and pythia v8.2
- examples/README-PYTHIA-VERSIONS added explaining how to use examples with
  older pythia versions
Mar 2 2015
- version 3.58 introduced
- directory structure reorganized to get rid of misleading FORTRAN keyword and obsolete
  photosFortranInterfaces directory.
- libraries content and name changed. Now HEPEVT and HepMC interface can be
  linked separately
- The new libraries are linked as: -lPhotospp -lPhotosppHEPEVT -lPhotosppHepMC
Feb 26 2015
- tests and rounding error fix for simultaneous pairs and photons generation in long runs
Feb 3 2015
- Emission of extra lepton  pairs introduced. 
- Tests of phase space (presamples on/off): comparison with flat space
  completed  
- Soft matrix element installed and normalization of numerical results
  checked (as function of maximum energy of pairs and lepton mass) 
  at 2 % precision level
- distributions checked to look resonable, but no comparison with 
  semi-analytical results.
- documentation and test need to be completed.
- Version 3.57 introduced
```

**EvtGen 1.3.0->1.6.0**
```
R01-06-00-------------------------------------------------------------------
1st June 2016 John Back
    New tag incorporating all changes below. Recommended external packages
    are HepMC 2.06.09, pythia 8.186, Photos++ 3.61 and Tauola++ 1.1.5.

28th April 2016 Michal Kreps
    For Ds+ --> 2pi+ pi- there was double counting of branching fraction
    resulting in total branching fraction being 1.5 times larger than measured
    one. Fix by revisiting submodes, which now fill total Ds --> 3pi.

25th April 2016 Michal Kreps
    Added DECAY.DEC/XML, which contain updated semileptonic charm and beauty 
    branching fractions using the 2014 PDG, tuned to minimize disagreements 
    between measurements and EvtGen for both inclusive and exclusive decays. 
    Updated the evt.pdl particle properties file to the PDG 2014 edition.

    Implemented new LQCD form factors for Lb --> L mu mu from arXiv paper 
    1602.01399 (EvtRareLbToLllFFlQCD); old LQCD form factors are removed.

18th March 2016 John Back
    Fixed incorrect spinor algebra used in S1 -> 1/2 S2, 1/2 -> S3 S4 decays
    in EvtDiracParticle::rotateToHelicityBasis() functions, courtesy of
    Luis Miguel Garcia Martin and the IFIC Valencia LHCb group.

19th Feburary 2016 John Back
    Fixed bug in the definition of the initial spinor term Sinit in 
    EvtRareLbToLll::HadronicAmpRS(), from Tom Blake (LHCb).

12th February 2016 John Back
    From LHCb, added extensions to the EvtHQET2(FF) model for semitauonic
    decays from Brian Hamilton, which needs a patch to EvtSemiLeptonicAmp 
    from Jack Wimberley to ensure that the q^2 range is physical when 
    finding the maximum amplitude probability.

2nd December 2015 John Back
    From LHCb, added EvtKStopizmumu model for KS -> pi0 mu mu decays based on
    JHEP08(1998)004, courtesy of Veronika Chobanova, Diego Martinez Santos
    and Jeremy Dalseno. Added EvtConst::Fermi for Fermi coupling constant.

R01-05-00-------------------------------------------------------------------
21st October 2015 John Back
    New tag incorporating all changes below. Recommended external packages
    are HepMC 2.06.09, pythia 8.186, Photos++ 3.61 and Tauola++ 1.1.5.

    Added the EvtB2MuMuMuNu model for simulating the very rare four-leptonic 
    decays B- -> mu+ mu- anti-nu_mu mu-, courtesy Nikolai Nikitin.

16th October 2015 John Back
    Updated the configure script to automatically select the library names
    for PHOTOS++; version 3.56 and below uses Fortran, version 3.61 and above
    uses C++ only (default). Avoid using v3.60, since it does not work.
    This needs the PHOTOS libraries built before EvtGen is configured.
    Modified setupEvtGen.sh to use Photos++ v3.61.

7th October 2015 John Back
    Updated EvtGenExternal/EvtPhotosEngine to check that additional particles
    from the outgoing vertex are indeed (FSR) photons, since later versions of 
    PHOTOS introduce pair emission, where particles may not always be photons.

    Added the genRootDecayChain.cc validation program to create ROOT files 
    containing information about the complete decay tree. Two example test
    decay files BKstarGamma.dec and BuDst0rhop.dec can be used with this; the
    first tests PHOTOS, the second looks at sequential decay chain storage.
    The plotBKstarGamma.C ROOT macro can be used for B -> K* gamma plots.

2nd October 2015 John Back    
    Modified EvtSVPHelAmp and added a new EvtSVPHelCPMix model, implementing 
    the complete mixing phenomenology of Bs to vector gamma decays, courtesy 
    of Clara Remon (LHCb).

    EvtD0mixDalitz code: cleanup, inverted q/p for decays of D0bar (simplifies
    user decay files) and fixed y parameter bug, courtesy of Jordi Tico (LHCb).

    Changed the initialisation order of the infrared cut-off in EvtPhotosEngine.
    This actually has no effect, since the exponentiation function sets it to the
    same 1e-7 value, but it's now in the correct order if we need to update it.

    Removed all remaining obsolete pragma (Win32) warnings from some classes.

23rd September 2015 Michal Kreps
    Reimplement the real Spence function in C++ and removed its fortran
    implementation.

15th September 2015 Michal Kreps
    Fixed accessed uninitialised memory in EvtPDL.cpp, line 213.
    Modified the configure and setupEvtGen.sh scripts to work on Mac; needed
    Mac compilation patch files added to the new "platform" subdirectory. 

10th September 2015 John Back
    Updated setupEvtGen.sh to use the recommended external packages:
    HepMC 2.06.09, pythia 8.186, Photos++ 3.56 and Tauola++ 1.1.5. 

    Fixed form-factor calculations for the BTOSLLBALL model 6 used to generate
    b -> sll decays, courtesy of Christoph Langenbruch and David Loh (LHCb). 
    Affects B->K*ll, B->rholl and B->omegall, particularly the electron modes.

    In the validation directory, added runPhotosTest.sh for testing FSR in
    Upsilon(4S) -> e+ e- decays, and changed the plot comparison scripts to
    use the 2nd directory "oldRootFiles" (which could be a soft-link) for 
    including ROOT histograms made from a previous version of EvtGen.    

27th August 2015 John Back
    Added Mersenne-Twister random number generator (RNG) EvtMTRandomEngine.
    It requires c++11 compiler features (>= gcc 4.7), which should 
    automatically be enabled by the configure script. Introduced the 
    preprocessor environment variable EVTGEN_CPP11 for c++11 features.
    EvtMTRandomEngine is the default RNG for the validation and test examples
    if c++11 features are enabled.

    Added a phase-space test validation/genPHSP.sh and PhaseSpacePlots.C to
    visually check the flatness of Dalitz plots in order to ensure that the
    RNG is not producing biased results that depend on particle ordering.

    Added the models EvtbsToLLLLAmp and EvtbsToLLLLHyperCP for 
    B0_q -> l+ l- l+ l- decays (SM and one supersymmetric scenario), 
    courtesy of Nikolai Nikitin and Konstantin Toms. Documentation provided
    in doc/evt_BQTOLLLL_model.pdf and doc/evt_BQTOLLLLHYPERCP_model.pdf.

    Changed the installation and set-up script name to be just setupEvtGen.sh;
    it uses the VERSION variable to specify the required tag. List of tags
    are available using either "svn ls -v http://svn.cern.ch/guest/evtgen/tags"
    or by going to http://svn.cern.ch/guest/evtgen/tags in a web browser.

12th June 2015 John Back
    Changed the width of chi_b1 in evt.pdl from 9.8928 GeV (!) to zero.

1st May 2015 John Back
    Added Bc -> scalar ell nu (EvtBcSMuNu) and Bc -> tensor ell nu 
    (EvtBcTMuNu) decays, courtesy of Jack Wimberley, LHCb. Also included the 
    chi_c1 mode for EvtBcVMuNu.   

R01-04-00-------------------------------------------------------------------
2nd April 2015 John Back
    Removed the EvtStdlibRandomEngine class since this can produce biases
    to kinematic distributions when one or more of the daughters is a 
    resonance, such as B0 -> K pi psi (thanks to Antonio Augusto Alves Jr 
    who discovered this issue). EvtSimpleRandomEngine is now the default 
    random number generator in the validation and test examples.

    Incorporated several additions and modifications from LHCb:
    a) From Michal Kreps, Tom Blake & Christoph Langenbruch,
       added rare Lb --> Lambda^(*) ell ell models described in
       arXiv:1108.6129, with various form factors from Gutsche et al. 
       (arXiv:1301.3737) and lattice QCD  (arXiv:1212.4827)
    b) From Andrew Crocombe, implemented Bs --> K* form factors 
       from Ball-Zwicky and z-parametrization form factors from 
       arXiv:1006.4945 for EvtbTosllBallFF
    c) Christoph Langenbruch fixed the Bs -> phi ll form factors in
       EvtbTosllBallFF; T3 showed a non-physical pole at very low 
       q2 which significantly affected the electron mode
    d) From Michal Kreps, removed semicolons from wrong places to
       clear warnings when compiled with the "-pedantic" option.

9th October 2014 John Back
    Change svnweb.cern.ch to svn.cern.ch in the setup script.

1st April 2014 John Back
     In EvtReport, modified the logging output severity status flags
     to have the "EVTGEN_" prefix, e.g. INFO becomes EVTGEN_INFO. 
     The global report() function has been renamed to EvtGenReport().

31st March 2014 John Back
     Added the ability to store named attributes for EvtParticles in the
     form of a map<string, int>. The setAttribute(name, value) stores the
     required value, while getAttribute(name) retrieves the integer value.
     This is used in EvtPhotosEngine to specify the final-state radiation
     "FSR" attribute to 1 for any additional photons (EvtPhotonParticles)
     created by Photos++. It also stores the "ISR" attribute, but this 
     is always set to zero, since only FSR photons are created.
     If the named attribute doesn't exist, then getAttribute() returns zero.

29th January 2014 Daniel Craik
     Removed mass assertion on GS shape in EvtDalitzReso to allow it to also 
     be used for charged rho resonances.

27th January 2014 John Back
     Minor corrections to Vub models to remove further gcc 4.8 warnings.
     Updated configure script to work for MacOS clang (from Genser team).
```

**Comment by mseidel42** [comment]
Finally, after rebuilding CMSSW completely from scratch:
```
********************************************************************************

                            =========================
                              PHOTOS, Version:  3.61
                              Released at:  29/9/15
                            =========================

                     Photos QED corrections in Particle Decays

           Monte Carlo Program - by E. Barberio, B. van Eijk and Z. Was
           From version 2.09   - by P. Golonka and Z. Was
           From version 3.00   - by N. Davidson, T. Przedzinski and Z. Was
********************************************************************************
```

Generated 10k events without any crash/error/hanging :-)

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
