### PR TITLE
[71X][Pythia8] Fix all uninitialized member variables

### PR DESCRIPTION
**Pull request by smuzaffar**
testing https://github.com/cms-externals/pythia8/pull/17

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@fabiocos  @kpedro88 , this is to integrate your changes https://github.com/cms-externals/pythia8/pull/17
If the results here looks good then I can merge https://github.com/cms-externals/pythia8/pull/18 and update this PR to use the correct cms/226 branch

**Comment by kpedro88** [comment]
@smuzaffar this looks good, please proceed

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
