### PR TITLE
New TFaaS version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to f81479d866fbfa2fc07381e50e1e390c3ab1e288 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4066/test_f81479d-20180531-223504.log" target="_blank">here</a>.

**Comment by h4d4** [comment]
+1 to 349c551cb792fdd4fcdb4118881639cdc2591ffc on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4066/test_349c551-20180606-150504.log" target="_blank">here</a>.

**Comment by davidlange6** [comment]
is this obsolete?

**Comment by vkuznet** [comment]
Yes, it is obsolete, closing the ticket.

**Pull request closed without merging**
