### PR TITLE
Update stomp python module to the latest stable version

### PR DESCRIPTION
**Pull request by amaltaro**
@dciangot Diego, ASO seems to be the only service using this module.
Could you please check whether this update will break the ASO code (very likely to happen)?

If it does, would you mind updating the ASO code to work with the new version? @stiegerb knows exactly what are the differences.
@vkuznet FYI

@BrunoCoimbra once we get the green light from Diego, can you please review and merge? I managed to build the RPM in my VM, though I didn't try to upload it.

### CODE REVIEW

**Comment by BrunoCoimbra** [comment]
+1 to 8dd09a3060e850da88b9b9a8b94f5c9c8217a0de on slc6_amd64_gcc493.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/2744/test_8dd09a3-20161215-182248.log" target="_blank">here</a>.

**Comment by dciangot** [comment]
ok, thank you for noticing. I'm going to check it and let you know.

**Comment by stiegerb** [comment]
If you need an indication of what changed in the interface, maybe this helps:
https://github.com/stiegerb/WMCore/commit/ed1a0f7853149063a3705a9f21e084c384f0e763

(Note that these are changes to go from v4 *back* to v3)

**Comment by amaltaro** [comment]
@dciangot if you need the ASO RPM with the new stomp version, please find it here:
http://cmsrep.cern.ch/cgi-bin/repos/comp.amaltaro/slc6_amd64_gcc493?C=M;O=D (tag HG1612h-comp3)

@stiegerb I'll try to deploy wmagent today and then I'll bug you via gtalk to try it out (just to see whether it works with this stomp)

**Comment by vkuznet** [comment]
@amaltaro , @stiegerb could you please clarify for me which version of stomp we should use (v3 and v4) and if so which version of StompAMQ to use. Benjamin just showed this change https://github.com/stiegerb/WMCore/commit/ed1a0f7853149063a3705a9f21e084c384f0e763 and I need to know if it is available in WMCore.

**Comment by stiegerb** [comment]
Hi Valentin,
You should use stomp.py v4 (latest is v4.1.15), which is compatible with the StompAMQ version here.
The change I showed makes StompAMQ compatible with stomp.py v3.1.7, but hopefully we won't need this.

**Comment by amaltaro** [comment]
ALL, Benjamin and I just tested the new stomp library version with WMCore code and it works fine.

**Comment by amaltaro** [comment]
@dciangot Hi Diego, did you manage to test it? Ideally we'd like to have it in for the next production cycle (Feb).

**Comment by dciangot** [comment]
Hi, just tested it and except for one line fix (aso side), everything looks good.

**Comment by amaltaro** [comment]
Thanks, Diego!
@BrunoCoimbra please review and merge

**Pull request merged**
