### PR TITLE
Update mkFit to V3.4.0-0

### PR DESCRIPTION
**Pull request by mmasciov**
Related CMSSW and cms-data PR are coming.

https://github.com/trackreco/mkFit/releases/tag/V3.4.0-0%2Bpr369

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test with cms-sw/cmssw#35652, cms-data/RecoTracker-MkFit#6

**Comment by makortel** [comment]
@cmsbuild, please test with cms-sw/cmssw#35652, cms-data/RecoTracker-MkFit#6

**Comment by smuzaffar** [comment]
@cmsbuild, please test with cms-sw/cmssw#35652, cms-data/RecoTracker-MkFit#6

**Comment by smuzaffar** [comment]
+externals
but it should be merged with cms-sw/cmssw#35652, cms-data/RecoTracker-MkFit#6

**Comment by perrotta** [comment]
+1
- To be merged together with #35652

**Pull request merged**
