### PR TITLE
Updated root to tip of branch v6-22-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
get update commits from 6.22

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
test parameter:
- addpkg = FWCore

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test

**Pull request closed without merging**
