### PR TITLE
[14.0.X] Update tag for RecoMuon-TrackerSeedGenerator to V00-07-00

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmsdist/pull/9210

Move RecoMuon-TrackerSeedGenerator data to new tag, see
https://github.com/cms-data/RecoMuon-TrackerSeedGenerator/pull/7

Cc: @wonpoint4

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/externals-l2 can you please merge this?

**Comment by mmusich** [comment]
type hlt-integration

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
only new data files  , so should be safe to include in 14.0.X

**Pull request merged**
