### PR TITLE
Update hdf5 to 1.10.6

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by Dr15Jones** [comment]
thanks!

**Comment by mrodozov** [comment]
oops

**Comment by Dr15Jones** [comment]
Any progress?

**Comment by mrodozov** [comment]
I'm building this on cmsdev24 to try fix the externals not building so, no, not much :/

**Comment by smuzaffar** [comment]
py2-h5py released version does not support hdf5 1.12.0 yet https://github.com/h5py/h5py/issues/1560. You need to get master branch of  https://github.com/h5py/h5py

**Comment by mrodozov** [comment]
update is I have built h5py for Python3, but from what I suspect from here:
https://github.com/h5py/h5py/issues/1505
h5py is only available for Python3 now (no surprise if so)
This means keras and keras applications might need only be available for py3 , and all that depends on them, too (meaning tensorflow). 
I'm building the entire cmsdist to check

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@Dr15Jones is 1.10.6 acceptable (Dec 2019) ? The other scenario might be ... clumsy . See the last commit comment

**Comment by mrodozov** [comment]
please test

**Comment by sabasehrish** [comment]
It  is okay to update to HDF5 1.10.6 for now.

**Comment by Dr15Jones** [comment]
@smuzaffar FYI I'm working with @sabasehrish who is the expert on hdf5

**Comment by mrodozov** [comment]
test parameters:
- release = CMSSW_11_2_X_2020-07-18-1100

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Pull request merged**
