### PR TITLE
[10_6_X] Add Niels Lohmann's JSON for Modern C++ header-only library

### PR DESCRIPTION
**Pull request by hqucms**
Backport of https://github.com/cms-sw/cmsdist/pull/5641 for 10_6_X.

> Add an external and a tool file for  Niels Lohmann's JSON for Modern C++
> header-only library, from https://github.com/nlohmann/json .
> 
> Can be used in CMSSW by adding to a BuildFile.xml:
>     <use name="json"/>
> 
> and to a source or header file:
>     #include <nlohmann/json.hpp>
>     using json = nlohmann::json;
> 
> or, to include only the forward-declation:
>     #include <nlohmann/json_fwd.hpp>
>     using json = nlohmann::json;
> 
> See https://github.com/nlohmann/json/blob/develop/README.md for some
> documentation.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
lets run a standalone test

**Comment by smuzaffar** [comment]
-externals
@hqucms please submit the PR for IB/CMSSW_10_6_X/gcc700 branch

**Comment by hqucms** [comment]
@smuzaffar Sorry about the trouble. I created another one to the gcc700 branch: https://github.com/cms-sw/cmsdist/pull/6145.

**Pull request closed without merging**
