### PR TITLE
[TBB] Try latest fixes on ppc

### PR DESCRIPTION
**Pull request by mrodozov**
See https://github.com/cms-sw/cmssw/issues/33636#issuecomment-863205907
we don't have tbb external and we don't need it for this temp test on PPC
I used my fork

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
please test for CMSSW_12_0_X_2021-06-16-2300/cc8_ppc64le_gcc9

**Comment by mrodozov** [comment]
CMSSW_12_0_X_2021-06-16-2300/slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
test parameters:
- release/arch=CMSSW_12_0_X_2021-06-16-2300/slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- enable_test = threading
- workflow_threading = 4000.0,23434.99,34634.0,34834.999,35034.0,36234.0,36634.0,37434.0

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
@smuzaffar the relvals finished without errors (surprisingly fortunate) should we merge this , build ppc IB and revert it to have a ppc IB with it ?

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_X/slc7_ppc64le_gcc9
looks like the last tests did not run the extra threading workflows

**Comment by mrodozov** [comment]
the threading relvals finished:
```

19:45:12 37434.0_TTbar_14TeV+2026D83+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Jun 18 18:20:51 2021-date Fri Jun 18 17:53:55 2021; exit: 0 0 0 0
19:45:12 250202.181_TTbar_13UP18+TTbar_13UP18INPUT+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jun 18 18:45:12 2021-date Fri Jun 18 18:04:22 2021; exit: 0 0 0 0 0
19:45:12 44 43 42 32 18 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed
```

and it was started with 4 threads:

```
19:16:09 # in: /scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-relvals/runTheMatrixTHREADING-results going to execute cd 37434.0_TTbar_14TeV+2026D83+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal
19:16:09  cmsDriver.py step3  --conditions auto:phase2_realistic_T21 -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,VALIDATION:@phase2Validation+@miniAODValidation,DQM:@phase2+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO -n 10 --geometry Extended2026D83 --era Phase2C11I13M9 --eventcontent FEVTDEBUGHLT,MINIAODSIM,DQM --filein  file:step2.root  --fileout file:step3.root  --suffix "-j JobReport3.xml "  --nThreads 4 > step3_TTbar_14TeV+2026D83+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log  2>&1
```
but it wasn't reported
in short this test is finished but I have to check why it isn't reporting when it's done

**Comment by smuzaffar** [comment]
@mrodozov , there is no need to merge , build IB and revert. I have started an IB build job to use your branch `mrodozov-patch-1` . let see if that is enough to test TBB for power

[a] https://cmssdt.cern.ch/jenkins/job/build-any-ib/111708/console
```
14:11:47 + P=CMSDIST
14:11:47 + '[' '!' -d CMSDIST ']'
14:11:47 + git clone -b mrodozov-patch-1 git://github.com/cms-sw/cmsdist.git CMSDIST
14:11:49 Cloning into 'CMSDIST'...
14:12:00 + pushd CMSDIST
14:12:00 /scratch/cmsbuild/jenkins_a/workspace/build-any-ib/CMSDIST /scratch/cmsbuild/jenkins_a/workspace/build-any-ib
14:12:00 + git remote add originrw git@github.com:cms-sw/cmsdist.git
14:12:00 + popd
```

**Comment by mrodozov** [comment]
I was thinking we can make a patch with the changes and use for PPC only if we need it further than one IB

**Comment by mrodozov** [comment]
the IB is built closing this

**Pull request closed without merging**
