### PR TITLE
Upgrade MariaDB spec from 10.1.21 to 10.6.5

### PR DESCRIPTION
**Pull request by amaltaro**
This PR provides a major upgrade for MariaDB, from 10.1.21 all the way to 10.6.5.

Erik ran extensive tests, including jenkins unit tests and there was only 1 new test failing.
In terms of configuration, our current configuration is very similar to the default values provided in 10.6.5. Further tweak and exploration might be needed, in a future phase though.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to 38b9375a7c25b3e68601712024769d842a1efed1 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7205/test_38b9375-20210806-094003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 09847d4b77ea1406fc044d57515a075a7536e0a3 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7205/test_09847d4-20210806-132002.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 4c05fda6b9e06d93ab176945f54e6ca1734fabac on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7205/test_4c05fda-20211108-200504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
