### PR TITLE
Bugfix/add nss deps

### PR DESCRIPTION
**Pull request by PerilousApricot**
Nss was sucking in zlib and sqlite dependencies from the system instead of from ourself

### CODE REVIEW

**Comment by davidlt** [comment]
You can always drop `NSS_USE_SYSTEM_SQLITE` and `USE_SYSTEM_ZLIB`. In that case embedded zlib and sqlite3 is used.

**Comment by PerilousApricot** [comment]
Ah, I didn't realize that. Let me finish pushing all my local changes
upstream then try building the other way to make sure it clicks.

-Melo

**Comment by davidlt** [comment]
It will click correctly, but the question would be: is using embedded zlib and sqlite3 for nss trigger any compatibility issues, or not? I am moving towards directly that it doesn't. You might also want to enable

```
export BUILD_OPT=1
export NSS_NO_PKCS11_BYPASS=1
```

And we should try to build with `NSS_BUILD_WITHOUT_SOFTOKEN`. We shouldn't ship _softoken_ or _freebl_ libraries. _glibc_ depends on _freebl_.

I did some experimentation and went back into thinking mode: https://github.com/davidlt/cmsdist/commit/2ec18b73dc3bb195f4ff2fc6cb763a0e87f62406

**Comment by PerilousApricot** [comment]
Interesting. Let me try and build with all those options in a bit and deploy a server with it. Can you think of a good test that would hit a potential compatibility snag?

**Comment by davidlt** [comment]
Well:

libnss-sqlite is a Name Service Switch (NSS) library which allows you to use a SQLite database as backend for UNIX authentication. This way, you can store users and groups in a database rather than in files.

This sounds that might not be needed, and if I recall correctly it's only used by _softoken_.

**Pull request closed without merging**
