### PR TITLE
cmssw-osenv: Mount cvmfs projects.cern.ch for cern.ch/cms domains only

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
Can you add the `.cms` domain ?

**Comment by smuzaffar** [comment]
> Can you add the .cms domain ?

@fwyzard , so `hostname -d` returns "cms" for this network?

**Comment by fwyzard** [comment]
Yes.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
