### PR TITLE
New dasgoclient version

### PR DESCRIPTION
**Pull request by vkuznet**
This is new dasgo client version based on up-coming das2go server which is scheduled to be in production on cmsweb in early June. It fixed several user-based queries and align with new das2go version.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by vkuznet** [comment]
please hold on this PR, I discovered a bug in run query which I need to fix.

**Comment by vkuznet** [comment]
-1, please hold on this PR since I discovered one bug in run queries which I need to fix.

**Comment by vkuznet** [comment]
I'm closing this PR due to found bug and will post another one with new version.

**Comment by vkuznet** [comment]
replaced with #4024

**Pull request closed without merging**
