### PR TITLE
add lzma and xz dependencies as their python interface is now in python3 itself

### PR DESCRIPTION
**Pull request by davidlange6**
should fix unit tests failure in PhysicsTools/PythonAnalysis (but I didn't check it)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by mrodozov** [comment]
xz provides lzma lib 
```
[mrodozov@cmspc001 millepede]$ ls /cvmfs/cms.cern.ch/slc7_amd64_gcc820/external/xz/5.2.4/lib/
liblzma.so  liblzma.so.5  liblzma.so.5.2.4
```
I think only xz will do

**Comment by davidlange6** [comment]
whoops - yes

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
