### PR TITLE
Dire 2.001

### PR DESCRIPTION
**Pull request by mseidel42**
Integrating Dire for Pythia

### CODE REVIEW

**Comment by smuzaffar** [comment]
@intrepid42 , as this is new tool, please add its dependency in cmssw-tool-conf.spec ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_1_X/gcc630/cmssw-tool-conf.spec ) too

**Comment by mseidel42** [comment]
Ok, done!

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
