### PR TITLE
bump py2/py3 versions of tools with updates in pypi

### PR DESCRIPTION
**Pull request by davidlange6**
Hopefully I got the various .file additions correct. 

Otherwise, onnxruntime has dropped slc6 support in versions newer than 1.3.0. Either our spec files or our pip do not deal nicely with manylinux2014 wheels. [it seems our pip needs to be 19.3, so likely "just" pip that needs to be updated]
@smuzaffar

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , we should remove the onnxruntime from the pip/requirement.txt file. We build python onxxruntime module via the onnxruntime.spec .

**Comment by davidlange6** [comment]
ah - right, I think I rediscover that the tensor flow we have is not ready for the newest numpy.

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
does this unit test have something to do with python tools? I would assume not.

>> Entering Package FWCore/MessageService
Package FWCore/MessageService: Running test fmt_test.cppunit
 
===== Test "fmt_test.cppunit" ====
Running .42 fooE

##Failure Location unknown## : Error
Test name: test_fmt_external::test_fmt
uncaught exception of type std::exception (or derived).
- invalid format string

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test
as we have updated TF 2.1.2 recently so lets get fresh results

**Comment by mrodozov** [comment]
please test
lets recheck with the unit test not failing

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
