### PR TITLE
Updating GeneratorInterface-EvtGenInterface to to new tag V02-00-09

### PR DESCRIPTION
**Pull request by mrodozov**
https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/11

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by oozcelik** [comment]
The PR is mainly needed for 93X

**Comment by mrodozov** [comment]
+externals

**Comment by alberto-sanchez** [comment]
@mrodozov , can this PR be made for 93x as well?. Thanks!

**Comment by davidlange6** [comment]
hi @mrodozov @alberto-sanchez - what is the master PR number?

**Comment by alberto-sanchez** [comment]
@davidlange6 I did think this was master in this case.

**Comment by davidlange6** [comment]
ah - whoops - i was confused by a link I followed for a 93x request (but now I see that the backport was just made)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
