### PR TITLE
Updated root to tip of branch v6-22-00-patches

### PR DESCRIPTION
**Pull request by mrodozov**
get two new commits from 6-22

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@slava77 there are some reco comparison diffs, may I ask to check them ?

**Comment by mrodozov** [comment]
+externals
except the reco diffs

**Comment by makortel** [comment]
The reco differences are in MessageLogger (`logErrorHarvester`), so likely can be ignored.

**Pull request merged**
