### PR TITLE
New DAS version

### PR DESCRIPTION
**Pull request by vkuznet**
- fixes various bugs with nil pointers (happen due to network failures in DAS requests)
- re-design loading template files as well as TLS certs, now they are cached

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to ac2291c489de6983e9f18b12c00afd53cc53231b on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5650/test_ac2291c-20200316-195003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
to d709bd919d1c28ace2b349910f530d23d2d37552 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5650/test_d709bd9-20200317-151005.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , Muhammad it seems to me it is still go read-only issue with our build. My first tag was successful, while when I updated it seems to me that build had read-only go related areas which requires manual intervention. Could you please clean-up this build (change the permission chmod -R u+w /<build-path>) and re-trigger the build again.

**Comment by muhammadimranfarooqi** [comment]
I have cleanup. Should be ok this time

**Comment by muhammadimranfarooqi** [comment]
+1 to d709bd919d1c28ace2b349910f530d23d2d37552 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5650/test_d709bd9-20200317-173005.log" target="_blank">here</a>.

**Pull request merged**
