### PR TITLE
Roll back to CUDA 12.1.1 [gcc 12]

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmsdist#8515

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- enable = gpu

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
Do we gain anything from CUDA 12.1 over 12.0 ?
If not, I would prefer to stay with 12.0 and keep the `--src-in-ptx` option.

**Comment by smuzaffar** [comment]
@fwyzard , I am just testing that if cuda `12.1.1` and no `--src-in-ptx` flag allow us to move forward with gcc12/cuda12. Note that cuda `12.0.1` with gcc12  has build errors 

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_2_X_2023-05-29-1100/RecoLocalTracker/SiStripClusterizer
```
gcc/x86_64-redhat-linux-gnu/12.2.1/include/avx512fp16intrin.h(38): error: vector_size attribute requires an arithmetic or enum type
```

**Comment by smuzaffar** [comment]
even removing `--source-in-ptx` does not  work for cuda12/gcc12 due to error [a] (which is there for both cuda 12.0.1 and 12.1.1)


[a]
```
>> Compiling  RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu
gcc/12.2.1/lib/gcc/x86_64-redhat-linux-gnu/12.2.1/include/avx512fp16intrin.h(38): error: vector_size attribute requires an arithmetic or enum type
                  __v8hf __attribute__ ((__vector_size__ (16)));
```

**Comment by fwyzard** [comment]
hi @smuzaffar , as a workaround you can add
```c++
#undef _Float16
```
right after
```
#include <cub/cub.cuh>
```
in [`RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu`](https://github.com/cms-sw/cmssw/blob/master/RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu).

While this _should_ be safe for us (we don't use _Float16 in `SiStripRawToClusterGPUKernel.cu`) I do not know if this can have any consequences in general.

I'll open a bug report with NVIDIA.

**Comment by fwyzard** [comment]
See
  - https://forums.developer.nvidia.com/t/including-cub-header-breakes-compilation-with-gcc-12-and-sse2-or-better/255018
  - https://developer.nvidia.com/nvidia_bug/4139266 (protected)
  - https://github.com/fwyzard/nvidia_bug_4139266

**Comment by fwyzard** [comment]
After feedback from NVIDIA, the workaround should be safe, see https://github.com/cms-sw/cmssw/pull/41819 .

In the meantime, a fix is being prepared upstream, see https://github.com/NVIDIA/libcudacxx/pull/476 .

**Comment by smuzaffar** [comment]
thanks a lot @fwyzard for following this up.  As you like to stay with cuda 12.0.1 with `--source-in-ptx`  so I am closing this PR

**Comment by jrhemstad** [comment]
@fwyzard I wanted to go out of my way to thank you for providing such an excellent bug triage and reproducer in https://github.com/fwyzard/nvidia_bug_4139266. 

We had been trying to track this down from other bug reports and it would have taken me forever to figure out the `_Float16` macro conflict. 

If only every bug report and reproducer was this good :wink:.

**Pull request closed without merging**
