### PR TITLE
Update the tag

### PR DESCRIPTION
**Pull request by mrodozov**
Testing the changes added here: https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/6 , new xml files

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
new files were added, which are not used in the code yet.
So, the integration should be straightforward at this point: I propose to merge this.

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
please make the same change for 94_MAOD_X as well

Thank you.

This is needed for integration of https://github.com/cms-sw/cmssw/pull/22302

**Comment by smuzaffar** [comment]
@slava77 , for now both 9.4.X and 9.4.MAOD.X share the same externals. Is it safe to put this in 9.4.X  (maod will also pick it up) otherwise we have to add separate branch for maod.

**Comment by smuzaffar** [comment]
@slava77 , looks like this PR just add few new files, so I think this is same to put in 94X.

**Pull request merged**
