### PR TITLE
Bump up openloops to 2.1.0 on 11_0_X

### PR DESCRIPTION
**Pull request by SiewYan**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@SiewYan  can you please check if these two patches https://github.com/cms-externals/openloops/commits/cms/v2.0.0 on top of openloops 2.0.0 are part of new version? If not then we have to patch v2.1.0 sources too.

**Comment by SiewYan** [comment]
@smuzaffar , https://github.com/cms-externals/openloops/commit/df5dc23c322dd460c4f8f3cdfa331bb190c647f6 is included in 2.1.0 but not this https://github.com/cms-externals/openloops/commit/64e5488359106d511ec13b7b382dd46fef1907bb
Please include the latter. Thanks!

**Comment by smuzaffar** [comment]
@mrodozov , can you please update cms-externals/openloops for v2.1.0 and include the missing patch

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
@SiewYan sorry, but this and the backport in #5187 do not seem consistent, why?

**Comment by SiewYan** [comment]
@fabiocos , PR https://github.com/cms-sw/cmsdist/pull/5187 meant only for Sherpa 2.2.7. I made a mistake by testing openloop build on the same branch (sherpa integrated branch)... Could you reject backport PR https://github.com/cms-sw/cmsdist/pull/5187 ? I will resubmit a clean sherpa backport PR later. Sorry for the inconvenience..

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
please test workflow 534.0,536.0

**Comment by fabiocos** [comment]
+1

sherpa workflows using openloops run

**Pull request merged**
