### PR TITLE
config.map: move _THREADED_X to SLC6 and IB/CMSSW_7_1_X/jemalloc341

### PR DESCRIPTION
**Pull request by davidlt**
Signed-off-by: David Abdurachmanov davidlt@cern.ch

### CODE REVIEW

**Comment by ktf** [comment]
mmm… I'm not sure that will work. did you setup the branch in jenkins to build THREADED on slc6? @nclopezo can you please set it up?

**Comment by davidlt** [comment]
All done (incl. Jenkins jobs).

**Comment by ktf** [comment]
Let's rock.

**Comment by nclopezo** [comment]
Ok. I was checking on jenkins, and then I saw the messages.

**Pull request merged**
