### PR TITLE
Fix boost herwigpp 71 x

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ktf** [comment]
@degano This broke ThePegInterface. How was this tested? @mkirsano can you look into it? Thanks.

**Comment by mkirsano** [comment]
I did not understand - what is broken? The internal test of 
ThePEGInterface works, I checked.

**Comment by mkirsano** [comment]
It is possible that when I tested it configured without Boost the 
system Boost of my computer was used. Anyway, now it works for me, and 
like this it is closer to the GENSER configuration. In GENSER it is also 
configured with fastjet.

**Comment by ghost** [comment]
@mkirsano Don't worry, the problem was due to the timing of the IB.
It's all working now.
This PR in particular was needed to use cmsdist BOOST, but it's unrelated to ThePegInterface.

**Pull request merged**
