### PR TITLE
New DAS version

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to 785030a15e01475ed1a560509f4bbd6fc0d0be4b on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5386/test_785030a-20191127-184503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
dce2cc24f2a8cb02404c67fc8c0b59517ea716c9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5386/test_dce2cc2-20191127-202503.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , Muhammad, I can't see the log it leads to 404 page. Could you please clean-up das2go build area and trigger new fresh build again.

**Comment by vkuznet** [comment]
I built successfully new das in my local build on vocms055, and I bet that issue here is orphan build files. I had this issue before with Lina and this happens because go compiler left files in read-only mode. To fix it Lina made chmod -R u+r /<build-path>/das2go; rm -rf /<build-path>/das2go and then started new build

**Comment by muhammadimranfarooqi** [comment]
+1 to dce2cc24f2a8cb02404c67fc8c0b59517ea716c9 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5386/test_dce2cc2-20191128-114503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet ,

I did this chmod -R u+r //das2go; rm -rf //das2go and then started new build and it worked.

**Pull request merged**
