### PR TITLE
 Update llvm/clang to version 7.0.0 (release) 

### PR DESCRIPTION
**Pull request by fwyzard**
Also
  -  enable support for compiling CUDA code to NVPTX on amd64;
  -  disable automatic package dependencies.

For the moment, skip building dxr, numba and llvmlite, until they support LLVM 7.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
numba / llvmlite for clang 7 is tracked here: https://github.com/numba/llvmlite/issues/396

**Comment by fwyzard** [comment]
As for DXR, we are using a revision that is 4 years old; the current version of DXR does not use trilite and sqlite,  and instead relies on elasticsearch etc.

Would it make sense to try and update to the current version, rather than patching up the old one we use ?

**Comment by smuzaffar** [comment]
@fwyzard , for now, we can merge this for DEVEL IB to get it fully tested.
About DXR, problem is the DXR server side setup. Newer DXR requires Elesticsearch. It was not a trivial update when last time we checked also was requiring too many resources (3GB/release in ES).

Anyway, I have made a PR ( https://github.com/fwyzard/cmsdist/pull/1)  to fix the dxr compilation with new llvm.

**Comment by fwyzard** [comment]
Thanks, I will merge it and re-submit the tests.

About ElasticSearch, could we make use of the centralised CERN instance ?

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
+externals
merging it for DEVEL IBs.

**Pull request merged**
