### PR TITLE
bump pybind11 to 2.6.0

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
for some reason this is failing with 
`/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/python/2.7.15-bcolbf2/bin/python2 is needed by external+py2-pybind11+2.6.0-2a3870c96873cf9f7c8e62977f2cf50f-1-1.x86_64`
twice
which of course is very weird 😅
I'm building it to figure it out

**Comment by mrodozov** [comment]
oh well it says 
/bin/python2 
now thats new

**Comment by smuzaffar** [comment]
@davidlange6 , it is failing due to local path dependencies
```
10:21:30 Error: Local path dependency found for external+py2-pybind11+2.6.0-2a3870c96873cf9f7c8e62977f2cf50f.
10:21:30 --> /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/python/2.7.15-bcolbf2/bin/python2
10:21:30 ./opt/cmssw/slc7_amd64_gcc820/external/py2-pybind11/2.6.0-2a3870c96873cf9f7c8e62977f2cf50f/bin/pybind11-config
```

**Comment by davidlange6** [comment]
Ok, that should be easy to fix. I’ll have a look.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
these tests failed with
```
17:23:58 **** ERROR: No such file or directory: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/py2-pybind11/2.6.0-928da45838fd499ec9807f7ac5ccd17a/include/python2.7
17:23:58      SCRAM does not allow prompting for user input anymore.
17:23:58      Please fix the tool file for "py2-pybind11" and provide a valid value for "INCLUDE".
```

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
