### PR TITLE
Move to boost 1.57.00

### PR DESCRIPTION
**Pull request by ktf**
cms-externals/boost@040a06a

### CODE REVIEW

**Comment by ktf** [comment]
As decided in the ORP, we will move CMSSW_7_3_X and CMSSW_7_2_X (in a separate PR) to boost 1.57.00 to mitigate forward port issues of boost_serialization. In the process we move boost to use our own cms-externals/boost mirror, in order to make selective updates of boost easier in the future.

@davidlange6 @andreasp

**Comment by ktf** [comment]
@degano can you please build up to cmssw-tool-conf this one?

**Comment by davidlt** [comment]
Changes in CMSSW must go in before this. They are compatible between different boost versions.

Tracking ticket was: https://github.com/cms-sw/cmsdist/issues/1167

You need at least:
https://github.com/cms-sw/cmssw/pull/6278
https://github.com/cms-sw/cmssw/pull/6289
https://github.com/cms-sw/cmssw/pull/6353
https://github.com/cms-sw/cmssw/pull/6399
https://github.com/cms-sw/cmssw/pull/6369

Might be more, would need to look into my PRs history.

**Comment by ktf** [comment]
@davidlt Can you prepare a PR which fixes all the issues in both CMSSW_7_3_X and CMSSW_7_2_X? Thanks.

**Comment by davidlt** [comment]
Actually those are already in CMSSW_7_3_X, but older releases probably don't have this cleanup.

**Comment by davidlt** [comment]
Will make a PR for CMSSW_7_2_X with cleanups.

**Comment by ktf** [comment]
@davidlange6 We do not need this for  CMSSW_7_1_X, right?

**Comment by ktf** [comment]
@apfeiffer1

**Comment by ktf** [comment]
Are we happy with 72X? Shall I go ahead and do the same with CMSSW_7_3_X? @davidlange6 @apfeiffer1

**Comment by apfeiffer1** [comment]
> Are we happy with 72X? Shall I go ahead and do the same with CMSSW_7_3_X?
> @davidlange6 https://github.com/davidlange6 @apfeiffer1
> https://github.com/apfeiffer1
> 
> sorry, with the dropbox issues around, I did not yet have time to look at
> this in any detail. :(

Also, if you agree, I would like to backport the XML code for the
conditions at the same time, so we don't need to do this later when we need
it. We could also do this separately in a week or two, of course. Let me
know.

Thanks,
       cheers, andreas

**Comment by ktf** [comment]
No objections on my side. Please let me know when we want to switch 73X back to boost 1.57.00.

**Comment by davidlange6** [comment]
My memory was that this step was not needed. 72x and 73x both have a pretty short lifetime unless the LHC schedule changes by a lot. Remind me of why its needed?

**Comment by apfeiffer1** [comment]
> My memory was that this step was not needed. 72x and 73x both have a
> pretty short lifetime unless the LHC schedule changes by a lot. Remind me
> of why its needed?

as I said, it's not needed, more a "good to be prepared" thing - if you
think that 73X will die out in online soon, fine to skip this with me on
both cycles. In any case I don't think it's really needed for 72x, agreed.

Thanks,
       cheers, andreas

**Comment by ktf** [comment]
The original plan as I understood it was:
- switch 72X (done)
- check
- switch 73X
- wait for 74X to be ready for the switch
- switch 74X

did I misunderstand? My understanding was that we wanted to have 7XY (X > 2) using 1.57 for consistency.

**Comment by davidlange6** [comment]
Hi Giulio

Switch _boost_, yes.

**Comment by ghost** [comment]
I prepared another PR: #1396 based on this one, including https://github.com/ktf/cmsdist/commit/184d3e560416a5b0a3493d360db4b22ee7763d06 and a small fix to the setup of boost.spec.
I am closing this one.

**Comment by apfeiffer1** [comment]
> The original plan as I understood it was:
> - switch 72X (done)
> - check
> - switch 73X
> - wait for 74X to be ready for the switch
> - switch 74X
> 
> did I misunderstand? My understanding was that we wanted to have 7XY (X >
> 2) using 1.57 for consistency.
> 
> I thought we said that we still keep 750pre1 with boost 1.51, and only then
> move the 74x to boost 1.57, but yes, other than that, I agree.

Thanks,
       cheers, andreas

**Comment by ktf** [comment]
Yes, sorry, my confusion (including the fact I did not notice 
@davidlange6 question was about XML).

So we go ahead with 73X and boost 1.57 today?

**Comment by apfeiffer1** [comment]
> Yes, sorry, my confusion (including the fact I did not notice
> @davidlange6 question was about XML).
> 
> So we go ahead with 73X and boost 1.57 today?

yes, that sounds OK to me ...

Thanks,
       cheers, andreas

**Comment by davidlange6** [comment]
Sounds good - we likely will need the ability to build releases as patches of 732 for CRUZET - but I assume that is not a big problem to support?

**Comment by ktf** [comment]
If we do not need to change the externals that's hopefully business as 
usual.

**Comment by apfeiffer1** [comment]
On Tue, Feb 17, 2015 at 10:47 AM, Giulio Eulisse notifications@github.com
wrote:

>  If we do not need to change the externals that's hopefully business as
> usual.
> 
> On 17 Feb 2015, at 10:45, David Lange wrote:
> 
> > Sounds good - we likely will need the ability to build releases as
> > patches of 732 for CRUZET - but I assume that is not a big problem to
> > support?

at some point we have to make sure that whatever the HLT/online is using is
based on a release of boost 1.57 - and we have to do this _before_ we move
the 75x series to 1.57 (or rather the dropbox). so that all "reader"
releases can handle the (new) data.

Thanks,
       cheers, andreas

**Comment by davidlange6** [comment]
Hi Andreas

Right - but we also need to support small bug fixes on current operations. We'll meanwhile need to find a good time for a bigger update online.

**Comment by apfeiffer1** [comment]
> Right - but we also need to support small bug fixes on current operations.
> We'll meanwhile need to find a good time for a bigger update online.

sure, I understand this. I just wanted to add a reminder (also to myself)
that we can not switch the dropbox-release (75x, the "writing" release) to
boost 1.57 until _all_ readers in actual use (esp. in HLT) have been moved
to a release with 1.57.

Thanks,
       cheers, andreas

**Pull request closed without merging**
