### PR TITLE
Update Intel oneAPI compiler to version 2024.0

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@smuzaffar do we have anything in CMSDIST or CMSSW that actually tests the Intel compiler ?

**Comment by smuzaffar** [comment]
> @smuzaffar do we have anything in CMSDIST or CMSSW that actually tests the Intel compiler ?

No, I don't think any thing in cmssw depend on it

**Comment by fwyzard** [comment]
OK, so the update cannot break anything... on the other hand, we won't know if it works until we try to use it.
Maybe next year we can try to add some tests.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
