### PR TITLE
Update geant4 to version 10.01.p02.

### PR DESCRIPTION
**Pull request by ghost**
Update geant4 data files accordingly.
https://github.com/cms-externals/geant4/commit/ba06375bc3f709e90555746c17f2daae663e2924

### CODE REVIEW

**Comment by ghost** [comment]
+1
Tested compilation.
Tested build of SimG4Core and SimG4CMS against it.

**Comment by davidlange6** [comment]
@degano, @smuzaffar

could you revert this PR in all 76x releases

**Comment by davidlt** [comment]
@davidlange6 what is wrong with newer version? Could we make that "reason" ends up in git message?

**Comment by davidlange6** [comment]
apparent physics bugs under discussion in the sim meeting

**Comment by smuzaffar** [comment]
@degano

**Pull request merged**
