### PR TITLE
[12.5.X] backport multi-vec build rules and SCRAM

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

@perrotta , @rappoccio this backports the SCRAM and build rules changes needed for multi-vec IBs ( same as #8083 ).

**Comment by perrotta** [comment]
+1

**Pull request merged**
