### PR TITLE
python tool updates

### PR DESCRIPTION
**Pull request by davidlange6**
Additional python package updates - nearly caught up with what is in pypi now.

Not really for this PR - it seems we need to revisit what ends up in python_tools.spec. It doesn't seem we are maintaining the py3-*specs there.  Perhaps this file can be automatically derived from requirements.txt plus the list of exceptions?

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
