### PR TITLE
Add Alignment* modules

### PR DESCRIPTION
**Pull request by oshadura**
cc @davidlange6 @vgvassilev

### CODE REVIEW

**Comment by mrodozov** [comment]
I see the IB has failed to build exactly that parts, should we merge this and restart ?

**Comment by davidlange6** [comment]
I”ll take care of it. Indeed we have a problem that local tests do not behave as the full builds do.

On Jun 23, 2020, at 2:37 PM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:



I see the IB has failed to build exactly that parts, should we merge this and restart ?

**Comment by smuzaffar** [comment]
test parameters
 - full_cmssw = true
 - pull_requests = cms-sw/cmsdist#5984

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
My belief is that we don’t have the needed dependency prs merged for this to work. But let’s see;)


On 28 Jun 2020, at 14:07, Malik Shahzad Muzaffar <notifications@github.com> wrote:

﻿

test parameters

  *   full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
yea, indeed, this broke the IB in the same way that it did last week...

**Comment by smuzaffar** [comment]
humm, PR tests with full cmssw build compiled successfully .... which is what IB build should do

**Comment by davidlange6** [comment]
but the "good" news is that the bot PR tests have the same defect as my local full builds - they compile just fine with these modules..

**Comment by davidlange6** [comment]
yes - crossing messages... its a difficulty for us

**Comment by davidlange6** [comment]
anyway, if the bot resources are not too full, a new IB would be useful (as I think we'd have results in time to take actions before the next one)

**Comment by smuzaffar** [comment]
so looks like missing dependency in CondFormats/Alignment .... 
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/a24b23f728e711a7f728102f9a1e0ae5/opt/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_CXXMODULE_X_2020-06-29-2300/src/CondFormats/Alignment/interface/Definitions.h:14:10: remark: building module 'DataFormatsGeometrySurface' as '/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/a24b23f728e711a7f728102f9a1e0ae5/opt/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_CXXMODULE_X_2020-06-29-2300/tmp/slc7_amd64_gcc820/src/CondFormats/Alignment/src/CondFormatsAlignment/a/DataFormatsGeometrySurface.pcm' [-Rmodule-build]
#include "DataFormats/GeometrySurface/interface/TkRotation.h"
```

**Comment by davidlange6** [comment]
yes, thats right. Now I should figure out where that PR is.. (as I don’t find it)

On Jun 30, 2020, at 7:47 AM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



so looks like missing dependency in CondFormats/Alignment ....

/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/a24b23f728e711a7f728102f9a1e0ae5/opt/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_CXXMODULE_X_2020-06-29-2300/src/CondFormats/Alignment/interface/Definitions.h:14:10: remark: building module 'DataFormatsGeometrySurface' as '/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/a24b23f728e711a7f728102f9a1e0ae5/opt/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_CXXMODULE_X_2020-06-29-2300/tmp/slc7_amd64_gcc820/src/CondFormats/Alignment/src/CondFormatsAlignment/a/DataFormatsGeometrySurface.pcm' [-Rmodule-build]
#include "DataFormats/GeometrySurface/interface/TkRotation.h"

**Pull request merged**
