### PR TITLE
for 5tev pp run is needed

### PR DESCRIPTION
**Pull request by alberto-sanchez**
Properties for Bc needed for pp 5 Tev run. As request I am adding them.
see: https://twiki.cern.ch/twiki/bin/view/CMS/PP5TeV2017OfficialMC

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
@smuzaffar , @fabiocos , apparently this patch is need for official MC production. Wonder if you can approve it at your early convenience. Thanks!

**Comment by smuzaffar** [comment]
backport of https://github.com/cms-sw/cmsdist/pull/4181

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
+1

only an addition to the existing data tables for evtgen

**Pull request merged**
