### PR TITLE
Updated root module to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
ROOT changed Minuit logging here in master:
https://github.com/root-project/root/pull/6705
and it's only in master, which means even we ask them to put it in 6-22 and fix it once or device something else.
To use the new logging nearly but not exactly straightforward so authors of 
RecoLocalCalo/HcalRecAlgos should have to setup the MnPrint:: SetLevel -> Verbose and some other printing

**Comment by davidlange6** [comment]
hi @mrodozov - I will merge this as its the way forward to add a needed llvm patch (llvm inside of root) for gcc9

**Comment by mrodozov** [comment]
its fine its just now it will also needs the cmssw change for minuit

**Comment by davidlange6** [comment]
Yes, If the error in RecoLocalCalo becomes the worst problem in the modules ib, I’ll be happy!

**Pull request merged**
