### PR TITLE
[HDF5] disable cxx and enable threadsafe

### LINKED ISSUE #8569: Thread-safe HDF5 compiler option
It looks like a special compiler option is needed to allow HDF5 to be run in a multi-threaded program. See

https://support.hdfgroup.org/HDF5/faq/threadsafe.html

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes #8569

- Remove unused `--disable-static-enable-shared` flag
- enable threadsafe which requires
  - disabling CXX interface
  - enable unsupported to make sure that we build high level libs which are required by h5py python module
- Remove hdf5-cpp toolfile

FYI @Dr15Jones

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
thanks

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc11

**Pull request merged**
