### PR TITLE
[INT-CHECK] Root6 patch for S3 key auth.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/holzman/root/commit/5ccdddc11a38ab5b3647f8f737f2d5115b956d21

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by ghost** [comment]
@holzman The above error appeared when trying to compile your root branch in our environment. Does it looks like a plausible error? Or is it totally unreleated?

**Comment by davidlange6** [comment]
it naively looks completely unrelated

**Comment by holzman** [comment]
This looks totally unrelated to me too. The patch doesn't touch boost.

**Comment by ghost** [comment]
Right, those are issues also present in the IB used for the test. I'm retriggering with a more recent and sane IB.

**Comment by smuzaffar** [comment]
this looks good, jenkins tests infrastruture for testiong externals still need some improvements.

**Comment by smuzaffar** [comment]
this is now included in #2017

**Pull request closed without merging**
