### PR TITLE
[DD4hep] Update to v01-19

### LINKED ISSUE #7513: Update DD4hep to latest v01-19 for 12_3
To keep up with the latest DD4hep release, please update DD4hep to v01-19 for 12_3.

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes https://github.com/cms-sw/cmsdist/issues/7513

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
hold
(Till when we'll build CMSSW_12_3_0_pre2 based on CMSSW_12_3_X_2021-12-16-1100)

**Comment by civanch** [comment]
Because we see regression, this update is safe and after CMSSW_12_3_0_pre2 can be merged.

**Comment by perrotta** [comment]
unhold

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
