### PR TITLE
continue with removing python2 versions

### PR DESCRIPTION
**Pull request by smuzaffar**
backported from DEVEL IBs

### CODE REVIEW

**Comment by smuzaffar** [comment]
@davidlange6 , can you please fix pip/requirement.txt file. last night I updated pillow and that is now creating conflicts with this PR. just update
```
pillow==8.2.0 ; python_version>'3.0'
```
in your branch

**Comment by davidlange6** [comment]
hum, I think I got it..

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- pull_request = cms-sw/cmssw#33991

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , in your next round, please 
- drop `py2-Pygments` , it was only used by DXR but DXR is now pyY3 only. 
- drop py2-pillow, it is only required by `bokeh` which we only build for py3

This should fix the 2 security issue https://github.com/cms-sw/cmsdist/security/dependabot

**Comment by davidlange6** [comment]
> On Jun 10, 2021, at 8:43 AM, Malik Shahzad Muzaffar ***@***.***> wrote:
> 
> 
> @davidlange6 , in your next round, please
> 
> 	• drop py2-Pygments , it was onlyused by DXR but DXR is now pyY3 only.

Its already gone..
https://github.com/cms-sw/cmsdist/pull/7008/commits/fab1a81a0c7bd0674c040a9d6d716277b29bf891

> 	• drop py2-pillow, it is only required by bokeh which we only builf for py3

Thats in my next round already

**Comment by smuzaffar** [comment]
please test
restart the tests with cms-sw/cms-bot#1562 which should allow to run clang, static analysis , py3, code rules on cmssw PRs only instead of full cmssw. Hopefully this save some PR test time

**Comment by smuzaffar** [comment]
please test
restarted after fixing the test parameters

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
