### PR TITLE
Update glimpse to 4.18.7-6; fix source URL (the old one is dead)

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , looks like some of these patches were already merged https://github.com/az143/glimpse/commit/23edbf54d45cefb1a5537598efe88d2b68470afb . So can we cleanup our patches. I would also sugest to fork the `az143/glimpse` repo under `cms-externals/glimpse` and apply any cms specific patches there and remove those from cmsdist.

**Comment by iarspider** [comment]
@smuzaffar yes, the patches are included, but not applied (or, to be exact, they are applied when building .deb file). There are no CMS-specific patches for glimpse - I guess you meant "fork glimpse and apply all these patches, instead of putting them in cmsdist", right?

**Comment by smuzaffar** [comment]
yes , fork it and apply these patches in github (instead of keeping them in cmsdist). I think the last commit here https://github.com/az143/glimpse/commits/master contains some the patches we are applying e.g.

- https://github.com/az143/glimpse/commit/23edbf54d45cefb1a5537598efe88d2b68470afb#diff-4b070e0327dad0c262609258066ffe4ea6938187e776068c9946c1111a86754f
- https://github.com/az143/glimpse/commit/23edbf54d45cefb1a5537598efe88d2b68470afb#diff-0a022496b0126785b8e2d4277bb300be8930c106586b59453fb848956d4dc53d
- https://github.com/az143/glimpse/commit/23edbf54d45cefb1a5537598efe88d2b68470afb#diff-e8d32a3a1ad6ab3b7a4426c0e88fda071b1a376976daa377f6e96adc290f4710

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
> @smuzaffar yes, the patches are included, but not applied (or, to be exact, they are applied when building .deb file).

ah right, yes they have added the debian patches but did not apply, sorry for the noise :-)

**Comment by iarspider** [comment]
No problem.

**Comment by smuzaffar** [comment]
looks good, lets get this isn DEVEL IBs first ( just to test the glimps itself as it is only used at the time of cmssw build)

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
