### PR TITLE
New version of dasgoclient

### PR DESCRIPTION
**Pull request by vkuznet**
Put back build_all

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
and there is one thing I don't quite understand - how does the dasgoclient-binary.rpm ends up in https://cern.ch/valya/dasgoclient/
the dasgoclient-binary.spec creates the rpm and dasgoclient.spec uses it but there is nothing that uploads it in between.
I uncommented the build_all and the spec built the rpm, but then I had to upload it manually so that dasgoclient.spec to get it from
https://github.com/mrodozov/dasgoclient_rpms

**Comment by vkuznet** [comment]
Mircho, I follow procedure established together with Shahzad some time ago. When I build an RPM for dasgoclient-binary I manually copy it to /eos/user/v/valya/www/dasgoclient/ area. Then we build dasgoclient which picks it up from there. I'm all in favor of more clear build instructions but that what was setup originally and we follow this path.

**Comment by mrodozov** [comment]
ok now I know :) thanks. I was thinking maybe I'm missing something.

**Comment by vkuznet** [comment]
Is there any way to look at unit test log outside of browser, it seems to me it is so huge that I can't even load it in a browser. I also have doubt that Magnetic Field unit test has anything to do with dasgoclient.

**Comment by mrodozov** [comment]
it doesn't . it fails in IBs. If the relvals are fine we'll get it in today before 2300 (to fix the IBs)

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@mrodozov , can you please start eithe rarm or ppc64 IB now

**Comment by smuzaffar** [comment]
just call it 11h00 IB

**Pull request merged**
