### PR TITLE
update root.spec to use latest 6-02 branch

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by davidlt** [comment]
Looks good. Just one question is https://github.com/cms-sw/root/commit/e7161fc2b05f9ffcbdf63f6973f9037b29716f36 available in 6.04 and master branches on official root repos?

**Comment by smuzaffar** [comment]
it is in master 7f655aa but not in 6.04 patches

**Comment by davidlt** [comment]
Thanks, I guess I need to pick it up into 6.04 later on. We should ask for this to be back ported.

**Comment by davidlt** [comment]
I just sent a request for a back port.

**Comment by davidlt** [comment]
Done. The commit is back ported to 6.02 and 6.04 branches.

**Pull request merged**
