### PR TITLE
Update Configuration-Generator tag - 7_1

### PR DESCRIPTION
**Pull request by mrodozov**
Regarding this request https://github.com/cms-sw/cmsdist/pull/4761#issuecomment-470555704

### CODE REVIEW

**Comment by scodella** [comment]
Is any test required for this request?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@mrodozov I would like to integrate the master version and this backport, as they are just addition of data files

**Comment by scodella** [comment]
does the compilation error message give any hint to you? Is there any action should I take?

**Comment by scodella** [comment]
sorry to bother you again on this, but do you think this error can be fixed? Please let me know if I should take any action.

**Comment by fabiocos** [comment]
please test

to verify whether it was just a temporary issue in the build procedure

**Comment by smuzaffar** [comment]
I am looking in to it.

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
