### PR TITLE
[ROOT 6.22] update to tip of v6-22-00-patches branch

### PR DESCRIPTION
**Pull request by smuzaffar**
This should be tested when 11.3.ROOT622.X IB is available

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true
- pull_requests = #6612

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true
- pull_requests = #6612, cms-sw/cmssw#32782

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true
- pull_requests = #6612, https://github.com/cms-sw/cmssw/pull/32842

**Comment by mrodozov** [comment]
please test
I want to see if 32842 is fixing the 11624.911 relval

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
we updated 6-22 since this PR so we can close this

**Pull request closed without merging**
