### PR TITLE
tool file

### PR DESCRIPTION
**Pull request by KiSooLee**
tool file is made and applied.
How can I test spec file at offline?

### CODE REVIEW

**Comment by KiSooLee** [comment]
+1

**Comment by davidlt** [comment]
This needs rebasing as it carries unrelated commits.

**Comment by KiSooLee** [comment]
I have tried git clone in CMSSW_8_0_0_pre4.
But it brings 7_0_X branch.
Could you please let me know available CMSSW version to get 8_0_X branch?

**Comment by davidlt** [comment]
`git checkout IB/CMSSW_8_0_X/stable` if you already have a local close of cmsdist. For rebasing, `git rebase -i IB/CMSSW_8_0_X/stable` if `IB/CMSSW_8_0_X/stable` is locally available.

**Pull request closed without merging**
