### PR TITLE
adding ppjjjj library [10_6_X backport]

### PR DESCRIPTION
**Pull request by SiewYan**
Adding missing library, needed for SMP's four-jet production study.

backport from
https://github.com/cms-sw/cmsdist/pull/6956

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
assign generators

**Comment by SiewYan** [comment]
please test

**Comment by mrodozov** [comment]
@SiewYan if you remember we had to remove files some time ago from 12_0 because they were not there anymore
I guess openloops for 10_6 didn't had to rebuild and thats why never failed

**Comment by SiewYan** [comment]
@mrodozov yeah! some of those libs are no longer available. Should I synchronize this list with 12_0_X's?

**Comment by mrodozov** [comment]
@SiewYan best do that, yes :)

**Comment by SiewYan** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
