### PR TITLE
[DD4Hep] Update to latest changes from master branch

### PR DESCRIPTION
**Pull request by smuzaffar**
Update DD4Hep to latest commit ae82afcac3986b62049c87fe3e96e2af790f75f8
- fix patch for building static library
- No need to have cms-external/dd4hep as no patch is needed for now for GDML

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@ianna , can you please look at this unit test GeometryDTGeometryBuilderTestDriver? Log shows [a]. @fabiocos if no objections then we can merge it in to DEVEL IBs so that Ianna can test it?

```
> Layer  Wh:2 St:3 Se:12 Sl:2 La:2  SL  Wh:2 St:3 Se:12 Sl:2  chamber  Wh:2 St:3 Se:12  Topology W/H/L: 4.2/1.3/299 first/last/# wire 1/58/58 Position  (552.824,-293.331,533.35)  normVect  (-0.866025,0.5,4.03516e-16)  bounds W/H/L: 243.73/1.15/304
> Layer  Wh:2 St:3 Se:12 Sl:2 La:3  SL  Wh:2 St:3 Se:12 Sl:2  chamber  Wh:2 St:3 Se:12  Topology W/H/L: 4.2/1.3/299 first/last/# wire 1/57/57 Position  (553.95,-293.981,533.35)  normVect  (-0.866025,0.5,4.03516e-16)  bounds W/H/L: 239.53/1.15/304
> Layer  Wh:2 St:3 Se:12 Sl:2 La:4  SL  Wh:2 St:3 Se:12 Sl:2  chamber  Wh:2 St:3 Se:12  Topology W/H/L: 4.2/1.3/299 first/last/# wire 2/57/56 Position  (555.076,-294.631,533.35)  normVect  (-0.866025,0.5,4.03516e-16)  bounds W/H/L: 235.33/1.15/304
Failure using cmsRun /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-10-16-1200/src/Geometry/DTGeometryBuilder/test/python/testDTGeometry.py: status 255
status = 65280

---> test GeometryDTGeometryBuilderTestDriver had ERRORS
 
^^^^ End Test GeometryDTGeometryBuilderTestDriver ^^^^
```

**Comment by ianna** [comment]
@smuzaffar and @fabiocos - it looks like the difference reported is unrelated to DD4hep version. ```normVector``` is ours and we do not have a unit test for it:
```
< Chamber  Wh:-2 St:1 Se:1  Position  (431.175,39.12,-533.35)  normVect  (-1,4.32978e-17,4.32978e-17)  bounds W/H/L: 218/36.2/251.1

> Chamber  Wh:-2 St:1 Se:1  Position  (431.175,39.12,-533.35)  normVect  (-1,1.80411e-16,-6.21021e-20)  bounds W/H/L: 218/36.2/251.1
```
I'd say we merge the new version and I'll update the reference for the test.

**Comment by fabiocos** [comment]
@ianna the difference is at the level of numerical rounding I would say, i.e. how well we approximate 0. Anyway why do you say that it is unrelated to DD4hep version? It changes when changing the external library, probably a tiny numerical effect, but that we do not observe otherwise, no?

Fine for me to merge it in the DEVEL IB, but it would be good to have the unit test fixed in parallel before integrating in the master branch, it is not good to have too many failures around (and we have already several of them for other reasons).

It would be good anyway to understand the cause of this difference, or understand how to get it under control.

**Comment by smuzaffar** [comment]
lets get this merged for DEVEL IBs so that @ianna can test and provide a fix for master

**Pull request merged**
