### PR TITLE
Update cmake to 3.14.5

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
hi @smuzaffar - this looks ready to go in?

**Comment by mrodozov** [comment]
@fabiocos any concern about merging this and the two root updates this evening ?
I'd suggest the evening builds as it will rebuild lots of pkgs on all slc7*gcc7-8-9 branches

**Comment by fabiocos** [comment]
+1

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
