### PR TITLE
Update Geant4 to 10.1.p02 and ParFullCMS

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-externals/geant4/commit/ba06375bc3f709e90555746c17f2daae663e2924
https://github.com/cms-externals/parfullcms/commit/15512c809659aafd4e52b6e31acf1cc8737cfe1d

### CODE REVIEW

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
@civanch Everything looks fine. Should we merge it?

**Comment by ghost** [comment]
please test

**Comment by civanch** [comment]
@degano , yes, let us merge to the DEVEL. We did not intend to merge  this to 8_0_X but work in the DEVEL for some time.

**Comment by ghost** [comment]
please test

**Comment by ghost** [comment]
@civanch I'm sorry but due to a bug in the testing script the previous test (from 4 days ago) was invalid (since it only tested part of the PR). The test running now should provide the correct result.

**Comment by ghost** [comment]
please test
(while the result above is correct there is an issue with the log files in the web page)

**Comment by civanch** [comment]
@degano , what I see it is necessary to change is in the file CMakeList.txt in line 56:
 README -> README.md
it is necessary but may be not enough. What I do not understand if the line 5 in the updated spec file is correct:

 Source: https://github.com/%{github_user}/%{realname}/archive/%{realversion}.tar.gz

Is it really tared and gzipped now?

**Comment by ghost** [comment]
@civanch I've fixed that error some time ago and the latest log shows another compilation error.
Yes now it is tarred and gzipped, as it is taken from github.

**Comment by ghost** [comment]
@civanch I'm reopening this PR here: #2021.

**Pull request closed without merging**
