### PR TITLE
Update geant4 to p03.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-externals/geant4/commit/86c476e297a2f1e3461929714240b0c6709012e3.

Fix https://github.com/cms-sw/cmsdist/issues/1359.

### CODE REVIEW

**Comment by ghost** [comment]
+1
Tested compilation up to cmssw-tool-conf.

**Comment by civanch** [comment]
@degano, I am trying to test CMSSW_7_4_THREADED_X_2015-02-18-1400 and it is failing to me. What I see is geant4 10.1p03 built in MT mode but I do not see  10.1p03-mpjdmj patch on top. The build is failing due TLS problem, this is another problem.

**Comment by civanch** [comment]
@degano , sorry for not identifying the problem in time: I was not able to find out a correct cmdist branch with Geant4e patch on top of Geant4 10.0p03. This patch is strongly needed in order to have Geant4e backward propagator in RECO working. It was validated using THREADED branch. I have rechecked, that in CMSSW_7_4_THREADED_X_2015-02-19-1400 IB both biglib and Geant4 10.0p03+mpjdmj are working fine.
So, we need reopen this PR or create a new one to apply Geant4 patch for 7_5_X . The patch itself  is at the url:
http://vnivanch.web.cern.ch/vnivanch/verification/verification/data/geant4-10.0p03-cms.patch

**Comment by ghost** [comment]
@civanch @ktf Giulio has reverted Geant4 to p02 on 7_5_X the 19th of February. I'm not aware of the issue behind the decision. Before that the Geant4 version used in 7_4_X_THREADED and 7_5_X where the same by definition because they where taken from the same repository, tag:
https://github.com/cms-externals/geant4/commit/86c476e297a2f1e3461929714240b0c6709012e3

**Comment by civanch** [comment]
@degano , IB of February,18 was broken for some reason - biglib does not work property, so Giulio restored previous Geant4. I visually compared spec files (THREADED/7_5_X) and did not figure out why this happens, for me they are the same. Probably, we need to make a second attempt taking  10.0p03 + patch mentioned above. It should work because THREADED is synchronized with 7_4_X , 7_5_X is similar too.

**Comment by ghost** [comment]
@civanch we found out the issue. The toolfile was missing the Geant4 MT flag.
I prepared a PR here: https://github.com/cms-sw/cmsdist/pull/1419 and everything looks to work fine.

**Pull request merged**
