### PR TITLE
Updated root to tip of branch v6-16-00-patches

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
@fabiocos , @slava77 can you please confirm is the comparison looks good here?

**Comment by slava77** [comment]
> +externals
> @fabiocos , @slava77 can you please confirm is the comparison looks good here?

It's worth to check the logwarnings in 158.0, where differences are reported.
What is the right link to the directory with the baseline matrix outputs?

**Comment by smuzaffar** [comment]
@slava77 , baseline IB relval results are available https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_0_X_2019-05-27-2300/ 
We will fix the link to point to correct baseline in the summary page.

**Comment by slava77** [comment]
The extra warning in the step3 of 158.0 is

```
%MSG-e ExcessiveTime:  PhotonValidator:pfPhotonValidation  29-May-2019 06:27:21 CEST Run: 1 Event: 1
ExcessiveTime: Module used 708.572 seconds of time which exceeds the error threshold configured in the Timing Service of 600 seconds.
```

this looks mildly suspicious

**Comment by fabiocos** [comment]
@slava77 @smuzaffar in the PR test the TimingService is active, please check in the JobReport.xml for its output. But I see this is not true in the baseline...

**Comment by slava77** [comment]
In the baseline the 1st event processing starts at 00:25:35 and the file is closed at 00:26:57.
So, the time spent in pfPhotonValidation in the baseline is certainly less than in this PR.

**Comment by fabiocos** [comment]
please test

@slava77 in a standalone test with the TimeReport per module I could not see anything strange...

**Comment by fabiocos** [comment]
@smuzaffar @slava77 in the new test it does not seem to me there were odd timing issues

**Pull request merged**
