### PR TITLE
Update root to version 6.02.10 with CMS patches on top of it.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/cms-sw/root/commit/84e6d82d392f79a6f1de53a51397db5b74e44f6c

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by smuzaffar** [comment]
@davidlange6, this should also go in 74X/root6 ....right?

**Comment by davidlange6** [comment]
Hi Shahzad

lets check it on 750pre6 and then consider the change for 74x/root6 (so in a week)

**Comment by smuzaffar** [comment]
ok thanks

**Pull request merged**
