### PR TITLE
Move to root 6.24

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR should update root 6.24 for default IBs

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- enable_test = threading

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc11

**Comment by smuzaffar** [comment]
please test for cc8_amd64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
Just to check if I understood correctly, did this update of 6.24 now build properly on ppc64le?

**Pull request merged**
