### PR TITLE
[Vincia] remove VinciaMG4 and VinciaMG5 libs

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar this requires cms-sw/cmssw#28301

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#28301

**Comment by smuzaffar** [comment]
tests ( https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/3636/console ) is already running with cms-sw/cmssw#28301

**Comment by fabiocos** [comment]
@smuzaffar ok good, should I just abort this one?

**Comment by smuzaffar** [comment]
No

**Comment by smuzaffar** [comment]
+externals
@fabiocos , the comparison results will not be ready by 11h. We can either delay the 11h IB by an hour or would you like to merge this PR before 11h?

**Comment by fabiocos** [comment]
@smuzaffar please delay the IB, I do not expect surprises but...

**Comment by fabiocos** [comment]
+1 

To avoid delaying too much next build

**Pull request merged**
