### PR TITLE
[BuildRule] alpaka backend inverted logic support added

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = FWCore,DataFormats, Heterogeneous, CUDA
- enable = gpu

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fwyzard** [comment]
@smuzaffar, what does this PR do ?

**Comment by smuzaffar** [comment]
@fwyzard , it implements feature requested in https://github.com/cms-sw/cmssw-config/issues/93 i.e allowing 
```
<flags ALPAKA_BACKENDS="!serial"/>
```
to build all backend except `serial` backend.

**Comment by fwyzard** [comment]
Thanks !

**Pull request merged**
