### PR TITLE
Upgrade pythia8 to 306

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
assign generators

@cms-sw/generators-l2 there are a lot of comparison differences with `pythia8 306` version. Are this expected with this update?

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
I think it is normal to have many small differences for a new pythia8 
version

  In my tests, I don't see big differences this time.

14/07/21 01:55, cmsbuild пишет:

**Comment by smuzaffar** [comment]
if this is ok then @cms-sw/generators-l2  can you please sign this ?

**Comment by mkirsano** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@qliphy , @silviodonato @perrotta any objection on mergign pythia8 version 306 for 12.0.X ?

**Comment by qliphy** [comment]
@smuzaffar  I am fine to merge this.  
 @silviodonato @perrotta  Please go ahead if you have no objections.

**Comment by smuzaffar** [comment]
lets merge it then.

**Comment by mtosi** [comment]
@cmsbuild, please test
(the results of previous checks are no longer available, and we would need to see if the TP distributions is the same)
because in the comparison of TTbar events they drastically differ
image

**Comment by agrohsje** [comment]
Hi @mtosi. Tests look good. Do you have any news on the tracking particle eta in ttbar?

**Pull request merged**
