### PR TITLE
New DAS version to fix issue with Rucio server

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
to ca05693c05869def5053c3eaecae15ab7b3e9726 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5515/test_ca05693-20200202-162503.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
Muhammad, the new DAS version address issues with Rucio server and therefore you can merge it safely. We don't need this version in new upgrade release (Feb), therefore you should merge when you'll finish the upgrade.

**Comment by muhammadimranfarooqi** [comment]
to 7a02705b90566a00b9a7e13c250c7ab40c2032aa on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5515/test_7a02705-20200202-205003.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
Muhammad, could you please clean-up build area (change build permission for go code) and re-trigger the build again. In my area code compiled correctly. I can't see the log posted from `-1` exit code, but I would assume that build needs a clean-up its build area.

**Comment by muhammadimranfarooqi** [comment]
+1 to 7a02705b90566a00b9a7e13c250c7ab40c2032aa on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5515/test_7a02705-20200203-103004.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Tests passed after clean-up. 

Cheers

**Pull request merged**
