### PR TITLE
Update devel to python3.9.5

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
seems that we need to move to tensor flow 2.5 before going to python3.9..

**Comment by smuzaffar** [comment]
Could it be that pip  rejects the wheel if it does not match the python version ( e.g in this case cp38 should be cp39) https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/pip/py3-tensorflow.file#L3 

Note that tensorflow it self has built fine with python 3.9

**Comment by smuzaffar** [comment]
strange, I do not see tensorflow-sources built . I thought it should have built due to  python3.spec update

**Comment by smuzaffar** [comment]
jenkins lohgs shows that tensorflow-sources was built successfully
```
17:30:10 Trying to install the rpm package external+tensorflow-sources+2.4.1-177bfcc756ecc6c53972e13a118c184c just built.
17:30:10 Checking local path dependency for rpm package external+tensorflow-sources+2.4.1-177bfcc756ecc6c53972e13a118c184c just build.
17:30:10 Done external+tensorflow-sources+2.4.1-177bfcc756ecc6c53972e13a118c184c
```
but I do not see the buildlog of it under https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-198110/16273/external/

**Comment by davidlange6** [comment]
It can be - I didn’t investigate - however, I see from the tensorflow release notes that it does not support python3.9 until 2.5

**Comment by smuzaffar** [comment]
try using `cp39` https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/pip/py3-tensorflow.file#L3 here and see where it fails

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
the error does not look related. will try again

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , i thint the error is related to PR. numba version 0.52.0 does not support python3.9. I think you need to use version 0.53

**Comment by davidlange6** [comment]
Yes - I missed that - I was confused by the messages about triton-server in the log..

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
looks like opencv needs python
```
opencv-4.5.1/modules/python/src2/cv2.cpp:17:10: fatal error: Python.h: No such file or directory
   17 | #include <Python.h>
      |          ^~~~~~~~~~
```

**Comment by smuzaffar** [comment]
issue is hard coded python 3.8 paths
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/devel/opencv.spec#L31-L32

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
there is one interesting unit test failure that I will look at, though it looks like tests went well enough to consider for DEVEL

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-198110/16312/unitTests/src/FWCore/PythonFramework/test/TestFWCorePythonFrameworkDriver/testing.log

**Comment by davidlange6** [comment]
hi @smuzaffar - I don't understand this unit test failure... if other things go ok, I'd be in favor of adding this to DEVEL to make it easy to debug. (it looks like other things are going ok, but lets see how the tests all finish)

**Comment by smuzaffar** [comment]
yes the failed unit test looks weird, I agree to merge it for DEVEL and then debug. I am merging it now

**Comment by davidlange6** [comment]
This error reproduced in the IB.  I'll look later today.

**Pull request merged**
