### PR TITLE
update Intel tools for CMSSW 10.0.x

### PR DESCRIPTION
**Pull request by fwyzard**
Update the Intel Compiler to version 2018.0.128
Update Intel VTune to version 2018.0.2.525261
Update Intel TBB to 2018 Update 1

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
@fwyzard , looks like c++17  change (for gcc630) did not go well with boost serialization 
https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc630/www/wed/10.0-wed-23/CMSSW_10_0_X_2017-11-29-2300
```
/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/4d50a45c6a4a8cce5ffcb3898507a4b8/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2017-11-29-2300/src/CondFormats/Serialization/python/condformats_serialization_generate.py --output /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/4d50a45c6a4a8cce5ffcb3898507a4b8/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2017-11-29-2300/tmp/slc6_amd64_gcc630/src/CondFormats/ESObjects/src/CondFormatsESObjects/a/Serialization.cc --package src/CondFormats/ESObjects/ -- -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/4d50a45c6a4a8cce5ffcb3898507a4b8/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2017-11-29-2300/src/CondFormats/ESObjects/src -DGNU_GCC -D_GNU_SOURCE -DCMSSW_GIT_HASH="CMSSW_10_0_X_2017-11-29-2300" -DPROJECT_NAME="CMSSW" -DPROJECT_VERSION="CMSSW_10_0_X_2017-11-29-2300" -DTBB_USE_GLIBCXX_VERSION=60300 -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/4d50a45c6a4a8cce5ffcb3898507a4b8/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2017-11-29-2300/src -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/lcg/root/6.10.08-mmelna2/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/pcre/8.37-oenich/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/boost/1.63.0-fmblme/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/bz2lib/1.0.6/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/gsl/2.2.1/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/libuuid/2.22.2/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/tbb/2018_U1/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/xz/5.2.2-oenich/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/zlib-x86_64/1.2.11/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/md5/1.0.0/include -I/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc630/external/tinyxml/2.5.3-fmblme/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++17 -ftree-vectorize -Wstrict-overflow -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -fno-crossjumping -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=maybe-uninitialized -Werror=strict-aliasing -Werror=narrowing -Werror=uninitialized -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -DBOOST_DISABLE_ASSERTS -Wno-error=unused-variable -fdebug-prefix-map=/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w=/opt/cmssw -fdebug-prefix-map=/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/4d50a45c6a4a8cce5ffcb3898507a4b8/opt/cmssw=/opt/cmssw -g
[2017-11-30 00:36:59,576] ERROR: Diagnostic: [Error] invalid value 'c++17' in '-std=c++17'
[2017-11-30 00:36:59,576] ERROR:    at line 0 in None
```

I would sugegst to revert it to c++1z for gcc630

**Comment by davidlt** [comment]
Yup, we need to keep `c++1z` because Clang version in GCC 6.3.0 does not accept `c++17`. IIRC, this is not the case in GCC 7 branch.

**Comment by fwyzard** [comment]
Does the serialisation code take the flags from the llvm-cxxcompiler tool ?
If so we can add
```xml
    <flags REM_CXXFLAGS="-std=c++17"/>
    <flags CXXFLAGS="-std=c++1z"/>
```
to llvm-cxxcompiler ?

**Comment by davidlt** [comment]
It does a messy thing. It reads original GCC flags and then modifies them enough to make Clang happy (I was against that). Do you (or some tool) explicitly need `-std=c++17`? If so, we can modify boost serialization to transform `-std=c++17` to `-std=c++1z` internally if Clang versions is bellow 5.0.0 (or something along these lines).

**Comment by fwyzard** [comment]
ICC/ICPC (Intel compiler) understands `-std=c++17` but not `-std=c++1z`.
So the alternative would be to revert GCC to `-std=c++1z` and add to the ICC tool file something along the lines of
```xml
    <flags REM_CXXFLAGS="-std=c++1z"/>
    <flags CXXFLAGS="-std=c++17"/>
```

**Comment by smuzaffar** [comment]
condformats_serialization_generate.py script calls `scram b echo_CondFormatsPACKAGE_CXXFLAGS` to get the flags. So adding it to llvm will not help.

**Comment by smuzaffar** [comment]
@fwyzard, yes we can add it in icc toolfiles. By the way, will .cc files compiled with c++1z and .cu with c++17 work together? Can you test this and add PR?

**Comment by fwyzard** [comment]
> condformats_serialization_generate.py script calls scram b echo_CondFormatsPACKAGE_CXXFLAGS to get the flags. So adding it to llvm will not help.

Is there no way to get the LLVM flags for a package, even if the compiler is GCC ?
Something like 
```
scram b echo_CondFormatsPACKAGE_CXXFLAGS COMPILER='llvm compile'
```
?

**Comment by smuzaffar** [comment]
`scram b echo_CondFormatsPACKAGE_CXXFLAGS COMPILER='llvm'` should be enough but we need to check with the author of condformats_serialization_generate.py

**Comment by davidlt** [comment]
They didn't want to that originally and was already suggested to them (years ago).

**Comment by fwyzard** [comment]
@davidlt, who were the original author ? do you remember what was the objection ?

**Comment by fwyzard** [comment]
@smuzaffar actually it looks like scram explicitly passes the flags to the tool:
```make
# CondFormat Serialization generation
define generate_CondSerialization
  @$(startlog_$(2))[ -d $(@D) ] ||  $(CMD_mkdir) -p $(@D) &&\
  $(CMD_echo) ">> Generating CondFormat Serialization code from header file $< " &&\
  $(VERB_ECHO) $(COND_SERIALIZATION_SCRIPT) --output $(LOCALTOP)/$@ --package $(dir $3) -- $(call AdjustFlags,$1,,CPPFLAGS CXXFLAGS) &&\
  (            $(COND_SERIALIZATION_SCRIPT) --output $(LOCALTOP)/$@ --package $(dir $3) -- $(call AdjustFlags,$1,,CPPFLAGS CXXFLAGS) || ($(CMD_rm) -f $@ && exit 1)) $(endlog_$(2))
endef
```

How would one tell scram to use the llvm flags instead ?

**Comment by smuzaffar** [comment]
@fwyzard, ah right ..... if scram flags are not passed then script runs `scram build echo_....`.
While building, scram has set gcc as compiler so it is not easy to change the compiler and get flags. We either need to define a flag to add/drop flags for boost serialization or we go with your trick and remove/add flag for icc toolfile.

**Comment by fwyzard** [comment]
Can SCRAM itself call

scram b echo_CondFormatsPACKAGE_CXXFLAGS COMPILER='llvm'

to get b the right flags ?

**Comment by smuzaffar** [comment]
one can (never tested , might not work due to some internal cached flags) but it would be very expensive call.

**Comment by davidlt** [comment]
@fwyzard see https://github.com/cms-sw/cmssw/blob/master/CondFormats/Serialization/python/condformats_serialization_generate.py#L18

**Comment by smuzaffar** [comment]
FYI, @fwyzard , new build rules now allow to pass llvm-cxxcompiler flags ( https://github.com/cms-sw/cmssw-config/commit/3417ef69233ae6aec25736dbb7367f7b8aedf2d9#diff-0a86a53bf24863421e1a627d229895e1R675)  to condformats_serialization_generate.py

**Comment by fwyzard** [comment]
@smuzaffar nice.
Does it mean from now on we don't need to customise the flags in condformats_serialization_generate.py , and we can just rely on the LLVM flags ?

**Comment by smuzaffar** [comment]
@fwyzard , yes that is correct. Now condformats_serialization_generate.py should receive only LLVM flags.

**Pull request merged**
