### PR TITLE
XRootD: Update to version 5.4.0 and build with scitokens-cpp

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test for alc7_amd64_gcc11

**Comment by iarspider** [comment]
please test for slc7_amd64_gcc11

**Comment by iarspider** [comment]
please test for slc7_aarch64_gcc11

**Comment by iarspider** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
thanks @iarspider . Have you checked if `scitokens-cpp` generates any shared library? If yes then we need a scram tool file for it too and update xroot toolfile to have dependency on that.

**Comment by davidlange6** [comment]
hi - has there been any discussion of what (if any) new requirements having client-side tokens libraries will have on the need to update old release cycles in the future? Eg, will old external stacks become more problematic with this evolution?

**Comment by smuzaffar** [comment]
No  @davidlange6 I do not know any such discussion. @bockjoo do you know ? Note that currently xrootd 5.3 is only available in CMSSW 12.3.X, and there was no request to back port it to old release cycles.

**Comment by davidlange6** [comment]
Indeed, I was more worried of forward constraints - but maybe we will eventually have an impact on the older UL releases.

**Comment by bockjoo** [comment]
@smuzaffar I don't know any such discussion.
By the way, just heads-up:
Although succeeding, xrdcp in CMSSW_12_3_0_pre4 behaves differently from the one in XRootD 5.4 with the token issued by https://cms-auth.web.cern.ch/
and I can open an AAA file with CMSSW_12_3_0_pre4 but failed to read the file with error '[ERROR] Socket timeout' (errno=0, code=103).

**Comment by iarspider** [comment]
@smuzaffar should I wait until tests are done and then push the toolfile? I don't want to abort the builds

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for slc7_aarch64_gcc11

**Comment by iarspider** [comment]
please test for slc7_ppc64le_gcc11

**Comment by iarspider** [comment]
@smuzaffar I think it's ready to be merged.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
lets get the latest IB

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc11

**Comment by smuzaffar** [comment]
lets merge this for DEVEL IBs for full tests

**Review by smuzaffar — APPROVED** [review]

**Pull request merged**
