### PR TITLE
Updated root to tip of branch v6-14-00-patches (cmsdist master)

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
the failing unit tests mostly hangs during PR testing but it works in IBs.

**Comment by smuzaffar** [comment]
@fabiocos @Dr15Jones, this udpates root 6.14 for normal IBs. This brings in following changes

https://github.com/root-project/root/compare/84a781a...5e217f2

Feel free to merge it

**Comment by Dr15Jones** [comment]
I don't believe any production jobs make use of TTreeFormula so it seems unlikely to break any production.

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar within CMSSW this is just used in macros of  HLTriggerOffline/Egamma, and within Fireworks https://cmssdt.cern.ch/lxr/source/Fireworks/Core/src/FWTSelectorToEventList.cc#0006 (not clear to me where this is really used).

Is the unit test failure reproducible?

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
@fabiocos  , we can include this too for next IB

**Comment by fabiocos** [comment]
+1

**Pull request merged**
