### PR TITLE
Backport HLS to 10_6_X

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: https://github.com/cms-sw/cmsdist/issues/5178

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
there's nothing failing in the 10_6 IB and also this is adding new stuff, can't be because of the PR itself :/ 
Error says: 
`
XrdCl::File::Open(name='root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/0E2CC5D5-9D87-7348-9219-B00CD718C847.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3014] Unable to open file  /eos/cms/store/user/cmsbuild/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/0E2CC5D5-9D87-7348-9219-B00CD718C847.root; Network is unreachable`
Lets just retry

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
FYI @fabiocos , this is new hls tool for 10.6.X . Nothing uses it yet but developers asked to back-port it. Feel free to merge it

**Comment by fabiocos** [comment]
+1

**Pull request merged**
