### PR TITLE
add memory_profiler

### PR DESCRIPTION
**Pull request by ticoann**

### CODE REVIEW

**Comment by h4d4** [comment]
+1 to 0b4cf4735468be80bb7219123340afc09997b4ca on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/4031/test_0b4cf47-20180524-213504.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
Haaa, fine work Seangchan!

**Comment by ticoann** [comment]
It still didn't solve the problem. :-(

**Comment by amaltaro** [comment]
Lina, can you please review and merge this PR? Thanks

**Comment by amaltaro** [comment]
ping

**Pull request merged**
