### PR TITLE
Update CUDA to version 10.0.130

### PR DESCRIPTION
**Pull request by fwyzard**
See https://docs.nvidia.com/cuda/pdf/CUDA_Toolkit_Release_Notes.pdf .

Update the SCRAM tool files for CUDA 10:
  - drop the device-side cublas libraries;
  - add a tool for the new nvjpeg library.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
merging for DEVEL IBs.

**Comment by fwyzard** [comment]
@smuzaffar thanks.
By the way, do we actually build IBs from the gcc700next branch ?

**Comment by smuzaffar** [comment]
@fwyzard yes. CMSSW_10_3_DEVEL_X IBs are based on gcc700next branch.

**Comment by smuzaffar** [comment]
we only build those for 23h00 though.

**Comment by fwyzard** [comment]
ah, I see, we build them only for SLC6 .

**Comment by smuzaffar** [comment]
Yes only for slc6. If needed we can build for slc7 too but may be not every night.

**Comment by davidlange6** [comment]
+1 for dropping slc6 in favor of cc7... (didn't we agree to do that already some time ago?)

**Comment by smuzaffar** [comment]
generators workflows (500's) are still not ready for slc7

**Comment by davidlange6** [comment]
whats the eta for that? (maybe it shouldn't hope up the cmssw development branch, as after all the generators developers don't really care about it)

**Comment by smuzaffar** [comment]
generators do not care for devel branch but mostly we use it to test new externals which we want to move back to production branch. So I would like to run these for same arch/compiler. Of course we can add CC7 IBs for DEVEL too.

**Comment by davidlange6** [comment]
> On Sep 27, 2018, at 2:46 PM, Malik Shahzad Muzaffar <notifications@github.com> wrote:
> 
> generators do not care for devel branch but mostly we use it to test new externals which we want to move back to production branch. So I would like to run these for same arch/compiler. Of course we can add CC7 IBs for DEVEL too.

Thats reasonable indeed - but no ETA for gen supporting cc7? Seems we need to again discuss how to move forward (1.5 years after agreeing we could in 6 months)

**Pull request merged**
