### PR TITLE
Add dependencies for jupiter

### PR DESCRIPTION
**Pull request by mrodozov**
Add new external to fix jupyter crash

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
thanks @mrodozov . @fabiocos we should get this in for 10.2.0 to fix the jupyter issue reported here https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2583.html

**Comment by fabiocos** [comment]
@smuzaffar ok, I am not sure that tests are really testing much here

**Comment by smuzaffar** [comment]
@fabiocos , we tested locally and after adding the tool we were able to run `jupyter notebook --no-browser --port=8891`

of course we should add more tests in cmssw to make sure that jupyter installation work

**Comment by fabiocos** [comment]
@smuzaffar fine for me to merge it so

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
