### PR TITLE
Update cmsweb exporters

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , I provided update for cmsweb exporters since we're using them in VM based cluster. We'll need new build of RPMs to include this version and to be deployed to testbed/production VM clusters. Please schedule it in next cmsweb upgrade.

**Comment by muhammadimranfarooqi** [comment]
-1 to 66b53de399b9e22aa28b35483cca1246953d2526 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6501/test_66b53de-20201211-192503.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
I'm looking into the error, it seems to me we'll need a new GoLang version since prometheus code breaks backward compatibility. I"ll investigate and will update the ticket.

**Comment by muhammadimranfarooqi** [comment]
+1 to 8ece0bef39a0b5283de866b30e4849a55b7991b7 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6501/test_8ece0be-20201211-211504.log" target="_blank">here</a>.

**Pull request merged**
