### PR TITLE
Update OpenMPI and other network components

### PR DESCRIPTION
**Pull request by fwyzard**
#### Update OpenMPI to version 4.1.2
This is a bugfix release, see https://www.mail-archive.com/announce@lists.open-mpi.org/msg00145.html for the details.

#### Update UCX to version 1.12.0

This is a feature release, for a list of all changes, updates and bug fixes since 1.10.1 see:
  - https://github.com/openucx/ucx/releases/tag/v1.11.0
  - https://github.com/openucx/ucx/releases/tag/v1.12.0

#### Update RDMA Core to version 36.3

This is a bugfix release, for the changes since version 36.0 see:
  - https://github.com/linux-rdma/rdma-core/releases/tag/v36.1
  - https://github.com/linux-rdma/rdma-core/releases/tag/v36.3

#### Update GDRCopy to version 2.3

This is a bugfix release, for the changes since version 2.2 see https://github.com/NVIDIA/gdrcopy/releases/tag/v2.3 .

#### Update Hardware Locality library to version 2.7.0

This is a major release, see https://raw.githubusercontent.com/open-mpi/hwloc/v2.7/NEWS for all the changes.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
I plan to submit various updates that eventually should be integrated together, but I would prefer to test them adding only one or two at a time.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
unhold

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by fwyzard** [comment]
> **Failed Tests**: UnitTests RelVals
> **Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21949/summary.html
> **COMMIT**: [4c15d9b](https://github.com/cms-sw/cmsdist/commit/4c15d9b8fb4418775e8acc353e7134b7e023f945)
> **CMSSW**: CMSSW_12_3_X_2022-01-23-0000/slc7_aarch64_gcc11
> **User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/7544/21949/install.sh` to create a dev area with all the needed externals and cmssw changes.

The MPI unit tests did pass:
  - [HeterogeneousCore/MPICore/test/testMPI](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21949/unitTests/src/HeterogeneousCore/MPICore/test/testMPI/testing.log)
  - [HeterogeneousCore/MPIServices/test/TestHeterogeneousCoreMPIServices](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21949/unitTests/src/HeterogeneousCore/MPIServices/test/TestHeterogeneousCoreMPIServices/testing.log)

**Comment by fwyzard** [comment]
> **Failed Tests**: UnitTests
> **Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21947/summary.html
> **COMMIT**: [4c15d9b](https://github.com/cms-sw/cmsdist/commit/4c15d9b8fb4418775e8acc353e7134b7e023f945)
> **CMSSW**: CMSSW_12_3_X_2022-01-23-0000/slc7_amd64_gcc10
> **User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/7544/21947/install.sh` to create a dev area with all the needed externals and cmssw changes.

The MPI unit tests did pass:
  - [HeterogeneousCore/MPICore/test/testMPI](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21947/unitTests/src/HeterogeneousCore/MPICore/test/testMPI/testing.log)
  - [HeterogeneousCore/MPIServices/test/TestHeterogeneousCoreMPIServices](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21947/unitTests/src/HeterogeneousCore/MPIServices/test/TestHeterogeneousCoreMPIServices/testing.log)

**Comment by fwyzard** [comment]
> **Failed Tests**: UnitTests
> **Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21948/summary.html
> **COMMIT**: [4c15d9b](https://github.com/cms-sw/cmsdist/commit/4c15d9b8fb4418775e8acc353e7134b7e023f945)
> **CMSSW**: CMSSW_12_3_X_2022-01-23-0000/slc7_ppc64le_gcc11
> **User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/7544/21948/install.sh` to create a dev area with all the needed externals and cmssw changes.

The MPI unit tests did pass:
  - [HeterogeneousCore/MPICore/test/testMPI](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21948/unitTests/src/HeterogeneousCore/MPICore/test/testMPI/testing.log)
  - [HeterogeneousCore/MPIServices/test/TestHeterogeneousCoreMPIServices](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1eca18/21948/unitTests/src/HeterogeneousCore/MPIServices/test/TestHeterogeneousCoreMPIServices/testing.log)

**Comment by smuzaffar** [comment]
+externals
@fwyzard , this looks good to go in, are you done with updates?

**Comment by fwyzard** [comment]
@smuzaffar yes, thanks, I unheld the PR when it was ready from my side.

**Comment by smuzaffar** [comment]
this looks good to go in, unit test failure for `materialBudgetTrackerPlots` is not related to changes here

**Pull request merged**
