### PR TITLE
[14_1_X] Update tag for RecoBTag-Combined to V01-25-00

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of https://github.com/cms-sw/cmsdist/pull/9504

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

@stahlleiton , I guess there is no cmssw PR to go with this in 14.1.X?

**Comment by stahlleiton** [comment]
> please test
> 
> @stahlleiton , I guess there is no cmssw PR to go with this in 14.1.X?

No, there is no PR associated to this

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , feel free to sign/merge  it for 14.1.X

**Comment by stahlleiton** [comment]
@mandrenguyen , maybe we could also add this to the upcoming CMSSW_14_1_X release

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
