### PR TITLE
[ROOT6] Root update master

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Hi @smuzaffar, do we need to update the IB/CMSSW_12_4_X/rootmodule branch this time?

**Comment by smuzaffar** [comment]
> Hi @smuzaffar, do we need to update the IB/CMSSW_12_4_X/rootmodule branch this time?

yes @aandvalenzuela , every time we update `rootmaster` branch we should also update`rootmodule` branch too

**Comment by davidlange6** [comment]
Please - it can always stay in sync with the root master branch.

**Comment by smuzaffar** [comment]
@davidlange6 , we already have auto forwarding setup for this ( https://github.com/cms-sw/cms-bot/blob/master/forward_ports_map.py#L98 ) e.g. see https://github.com/cms-sw/cmsdist/commits/IB/CMSSW_12_6_X/rootmodule/root.spec history

**Pull request merged**
