### PR TITLE
comp.pre slc5_amd64_gcc461 dbs3 dbs3-client dbs3-migration dbs3-pycurl-client

### PR DESCRIPTION
**Pull request by giffels**
Hi @amaltaro , @geneguvo,

the new hot fix version DBS 3.2.1c fixes the show stopper of todays production upgrade. 

Could you deploy it to testbed and once it has been validated to production, please?

Thank you very much,
Yuyi & Manuel

CC: to @belforte

### CODE REVIEW

**Comment by amaltaro** [comment]
Thanks Manuel, we intend to push it to testbed tomorrow morning, we just need to solve the
space issue in cmsrep before that. 
@belforte , please prepare your battery of tests for tomorrow.

**Comment by amaltaro** [comment]
It's in testbed now. @yuyiguo and @belforte , please validate it.
Thanks

**Comment by yuyiguo** [comment]
Thanks Alan.
I will next test it and let you know.
Yuyi

**Comment by amaltaro** [comment]
Hi Yuyi, Stefano finished CRAB tests and everything is OK in testbed. Did you manage to run your battery of tests? Thanks

**Comment by yuyiguo** [comment]
Hi, Alan:

I am in the middle of test. Still need a few hours to finish the test. Everything looks good to me. I do not expect any problems, but like to finish the tests. If you like to prepare for the production deployment tomorrow, I think you can start now. I will let you know my final test result as soon as I am done.

Manuel will be on the road tomorrow. We need to put prod/phys03 back for writing . Could you update dbs view tomorrow after the deployment? If you cannot for any reason, I will update it late tonight so Stefano can write to prod/phys03 tomorrow as soon as the deployment finished. 

Thanks a lot,
Yuyi

**Comment by amaltaro** [comment]
Hi Yuyi,
my only preparation for today is the official announcement. So I prefer waiting for your final results before announcing the tomorrow's upgrade.
About 'prod/phys03', I'm afraid I have no push/commit privileges to dmwm/DBS, so it would be better if you enable it before the end of your day. (?)
In case it helps you, I intend to proceed with the deployment at 1 pm CERN time. Considered all today's tests are ok. Thanks

**Comment by ericvaandering** [comment]
Thanks for the pointer, Alan. Yuyi, if there are any problems, please let me know. My inclination is to push ahead even if small problems are found as long as the impact is not severe. Of course, no problems as expected is even better!

**Comment by belforte** [comment]
we share this inclination all along. My reading is that at certain time
it looked like a large fraction of user publication attempt could end up
with failure and DB needing fixing by hand for each failed migration attempt,
which would have been too much.
Stefano

On 02/18/2014 09:38 PM, Eric Vaandering wrote:

> Thanks for the pointer, Alan. Yuyi, if there are any problems, please let me know. My inclination is
> to push ahead even if small problems are found as long as the impact is not severe. Of course, no
> problems as expected is even better!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-sw/cmsdist/pull/413#issuecomment-35430708.

## 

Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by ericvaandering** [comment]
Right, I agree. So it seems like we are in a different place now and we are all on the same page.

**Comment by yuyiguo** [comment]
I sumbited 599 datasets for migration. So far I got two third done. 
I will change DBS view tonight to make prod/phys03 writable.
Yuyi

**Comment by amaltaro** [comment]
And the upgrade announcement was made.
However I'll still for these final results by tomorrow morning.
Yuyi, make sure that all the backends properly enable 'phys03', just to avoid typos in the file, etc
Thanks

**Comment by amaltaro** [comment]
"still wait", it seems it's time to go to bed :)

**Comment by belforte** [comment]
thanks Alan !

On 02/18/2014 11:10 PM, Alan Malta Rodrigues wrote:

> "still wait", it seems it's time to go to bed :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-sw/cmsdist/pull/413#issuecomment-35441219.

## 

Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by ericvaandering** [comment]
Yes, thanks. Beer is on me at the next O&C week.

Eric

**Comment by yuyiguo** [comment]
Just a short update; I  have 135 datasets to migrate. So far no show-stoppers.
will check back tonight after my kids' piano lessons.

**Comment by yuyiguo** [comment]
Hi, Everyone:
My test is done. I give green light for deploying DBS3 to cmsweb.
I enabled prod/phys03 for writing and tested that I could access it.
Cheers,
Yuyi

**Comment by amaltaro** [comment]
Perfect! Thanks Yuyi.

**Comment by belforte** [comment]
very good. I just tried to publish in Prod and it worked.
Now we need new server ASAP before users notice and
trigger some buggy migrations.
Stefano

On 02/19/2014 03:12 AM, Yuyi Guo wrote:

> Hi, Everyone:
> My test is done. I give green light for deploying DBS3 to cmsweb.
> I enabled prod/phys03 for writing and tested that I could access it.
> Cheers,
> Yuyi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-sw/cmsdist/pull/413#issuecomment-35458975.

## 

Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Pull request closed without merging**
