### PR TITLE
Bump PhEDEx to version 4.1.4

### PR DESCRIPTION
**Pull request by TonyWildish**
trivial fixes also in DMWMMON and PHEDEX-datasvc

### CODE REVIEW

**Comment by geneguvo** [comment]
-1 to 5f41d82968751eeffe100fcc2019864a7a4b6287 on slc5_amd64_gcc461.

**Comment by TonyWildish** [comment]
Hi Diego,

sorry about the hassle. Can you give me a hint why it doesn't build please? It works fine for me, what have I missed?

**Comment by geneguvo** [comment]
Hi,
I think that's because you selected the SLC5 branch "comp", instead of the SLC6 one "comp_gcc481"? Your patch does not apply to the SLC5 specs:

```
Pull Requests to test:
#1228, Bump PhEDEx to version 4.1.4
#1111, Spec/patches to build apache 2.4 and mod_perl for it
Latest status is pending

Testing (#1228), Bump PhEDEx to version 4.1.4...
Cloning into 'cmsdist'...
HEAD is now at d9853d9 Update crab client to 3.3.10. Close #1101.
Applying diff from URL: https://github.com/cms-sw/cmsdist/pull/1228.diff
error: patch failed: DMWMMON-datasvc.spec:1
error: DMWMMON-datasvc.spec: patch does not apply
error: patch failed: PHEDEX-datasvc.spec:1
error: PHEDEX-datasvc.spec: patch does not apply
Updating status to failure: build test failed at least on slc5_amd64_gcc461
```

**Comment by TonyWildish** [comment]
Ah, it's the datasvc and DMWMMON. I don't really know how those got in there :-(

I'll fix it, thanks.

**Pull request closed without merging**
