### PR TITLE
add mock in wmagent-dev (Do not merge)

### PR DESCRIPTION
**Pull request by ticoann**
@geneguvo, @ericvaandering, Hi Eric, Diego I tried to add mock package for wmagent-dev rpm. (I had to add pdr since mock has dependency on that.) However when I try to import mock after deploying rpm, I get following error.

```
>>> import mock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/local/data1/sryu/unittestdeploy/wmagent/1.0.10.pre6-comp3/sw.pre.sryu/slc6_amd64_gcc481/external/py2-mock/1.3.0/lib/python2.6/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/storage/local/data1/sryu/unittestdeploy/wmagent/1.0.10.pre6-comp3/sw.pre.sryu/slc6_amd64_gcc481/external/py2-mock/1.3.0/lib/python2.6/site-packages/mock/mock.py", line 71, in <module>
    _v = VersionInfo('mock').semantic_version()
  File "/storage/local/data1/sryu/unittestdeploy/wmagent/1.0.10.pre6-comp3/sw.pre.sryu/slc6_amd64_gcc481/external/py2-pbr/1.8.1/lib/python2.6/site-packages/pbr/version.py", line 452, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "/storage/local/data1/sryu/unittestdeploy/wmagent/1.0.10.pre6-comp3/sw.pre.sryu/slc6_amd64_gcc481/external/py2-pbr/1.8.1/lib/python2.6/site-packages/pbr/version.py", line 439, in _get_version_from_pkg_resources
    result_string = packaging.get_version(self.package)
  File "/storage/local/data1/sryu/unittestdeploy/wmagent/1.0.10.pre6-comp3/sw.pre.sryu/slc6_amd64_gcc481/external/py2-pbr/1.8.1/lib/python2.6/site-packages/pbr/packaging.py", line 668, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
```

Could you advice how to fix this?

### CODE REVIEW

**Comment by geneguvo** [comment]
+1 to 578930610a1ba0dcbb74d7762769b4c92f9d62b8 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1901/test_5789306-20151014-210503.log" target="_blank">here</a>.

**Comment by geneguvo** [comment]
About the reported issue itself. I gave it a try and it appears to be the setuptools+egginfo business bugging around. As with the futurize script, we cannot remove these .egg-info files.

When I removed the egg-info cleaning from the spec files, I was able to go a bit further, but now it complains about "ImportError: No module named funcsigs". So you have to add  that (and maybe other) dependencies too.

**Comment by ticoann** [comment]
Thank you very much Diego, I will add the dependencies and run the test.

**Comment by geneguvo** [comment]
-1 to c73292c6648acb23120c2483ccecfd265db66986 on slc6_amd64_gcc481.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/1901/test_c73292c-20151028-003505.log" target="_blank">here</a>.

**Pull request closed without merging**
