### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by davidlange6** [comment]
Threading issues?

An exception of category 'FatalRootError' occurred while
   [0] Calling EventProcessor::runToCompletion (which does almost everything after beginJob and before endJob)
   Additional Info:
      [a] Fatal Root Error: @SUB=TReentrantRWLock::Rewind
Lock rewinded from a thread that does not own the Write lock

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
I think their latest commit fixes this (hopefully)

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
