### PR TITLE
Test if patch for libunwind is still needed

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test

**Review by smuzaffar — COMMENTED** [review]
@iarspider , you also need to remove https://github.com/cms-sw/cmsdist/pull/7328/files#diff-dd06fbda92fac3097870ba04a4d65176d03e59b59e4432d9fae165d9f38e12cbR12 . I would suggest to remove the lines instead of commenting out

**Comment by iarspider** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
@iarspider , so igprof failed to build due to the comma issue 
```
/home/cmsbuild/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/slc7_aarch64_gcc9/external/libunwind/1.5-fdd3db4a8c586939d8a46938c317cb36/include/libunwind-aarch64.h:161:33: error: comma at end of enumerator list [-Werror=pedantic]
  161 |     UNW_TDEP_EH = UNW_AARCH64_X0,
      |                                 ^
```

**Comment by iarspider** [comment]
Do you know where the `-Werror=pedantic` comes from? It doesn't seem to come from libunwind itself

**Comment by smuzaffar** [comment]
this must be in igprof spec/makefile

**Comment by smuzaffar** [comment]
may be you can update https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_1_X/master/igprof-gcc8.patch and add `-Wno-error=pedantic` ?

**Comment by iarspider** [comment]
> 
> 
> may be you can update https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_1_X/master/igprof-gcc8.patch and add `-Wno-error=pedantic` ?

Was just going to suggest that!

**Comment by iarspider** [comment]
@smuzaffar I propose to drop `-Werror` entirely (this is what was ultimately done in Spack after a long discussion).

**Comment by iarspider** [comment]
please test for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
@iarspider , ah that will hide all the warnings and code can crash at runtime due to these ignored warning (specially for new archs/compilers).
I would suggest to close this PR, we should keep our libunwind patch.

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test for slc7_aarch64_gcc9

**Comment by iarspider** [comment]
please test for slc7_ppc64le_gcc9

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar setting `-Wno-error=pedantic` works. If the tests for PowerPC and amd64 go through, can this be merged?

**Comment by iarspider** [comment]
please test for slc7_ppc64le_gcc9

**Review by smuzaffar — COMMENTED** [review]
looks ok but problem is in libunwind itself. any package using libunwind will fail if it uses `-pedantic ` flag

**Comment by smuzaffar** [comment]
+externals

**Comment by iarspider** [comment]
> 
> 
> looks ok but problem is in libunwind itself. any package using libunwind will fail if it uses `-pedantic ` flag

Let's see if [this PR](https://github.com/libunwind/libunwind/pull/303) will go through

**Pull request merged**
