### PR TITLE
Update Pythia8 to 8.307

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@smuzaffar @mkirsano  I can try adding HepMC3 flag, similar to #7677

**Comment by smuzaffar** [comment]
hold
I think @cms-sw/generators-l2  should decide when to move to new version of pythia8

**Review by smuzaffar — DISMISSED** [review]

**Comment by smuzaffar** [comment]
closing it, we can reopen once @cms-sw/generators-l2 need to update pythoa8 to version 8.307

**Comment by Saptaparna** [comment]
Indeed, we will need this version but probably we can also move directly to 8.308 sometime next year for the Run 3 samples.

**Pull request closed without merging**
