### PR TITLE
Hg1403 das

### PR DESCRIPTION
**Pull request by vkuznet**
Please take changes for DAS HG1403 release

### CODE REVIEW

**Comment by vidma** [comment]
Das 2.5.2 include the new metadata with field list updated for dbs2->dbs3

**Comment by amaltaro** [comment]
@vidma , @vkuznet are we going to use DAS 2.5.1 or 2.5.2? This PR is referring to 2.5.1. Please answer and/or update this PR ASAP, otherwise it'll delay testbed deployment

**Comment by amaltaro** [comment]
@vidma , please make a new PR in case you need a new DAS tag. I've just built HG1403a with DAS 2.5.1. Thanks

**Comment by vidma** [comment]
Hi, 
2.5.2 would have been better, but my response somehow didn't get sent...
this is not a big deal, we could perform this update at some point later...

**Pull request closed without merging**
