### PR TITLE
Backporting sherpa2.2.6 and openloops2.0.0 to 102X

### PR DESCRIPTION
**Pull request by SiewYan**
Hi, please apply the mentioned patches in [1] and [2]

[1] cms-externals/openloops@5141c0e
[2] https://gitlab.com/openloops/OpenLoops/commit/8ff8f52fe6e0f9f4f3f666b0d89279da64554fc3

### CODE REVIEW

**Comment by mrodozov** [comment]
please test
lets try this

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by SiewYan** [comment]
Hi @mkirsano 

i am backporting sherpa 2.2.6 to 102X and it is unsuccessful, I have tested it locally and i found the error stem from configure stage, its terminated at:

....
checking dependency style of mpicc... ./configure: line 4734: 18813 Segmentation fault      mkdir sub
./configure: line 4666: sub/conftest.c: No such file or directory
.....

Do you have any idea what might caused this? is mpicc not included in 102X?

@GurpreetSinghChahal, @alberto-sanchez, @qliphy, @efeyazgan

**Comment by mrodozov** [comment]
@SiewYan @mkirsano any suggestion how to "skip" this makeinfo test with say - patch over the makefiles or any other trick ? It's strange that when I test by hand in production env my little hack works but not when I test with the bot . More on how to hack around the makeinfo requirement here https://sourceware.org/bugzilla/show_bug.cgi?id=18113 and we already have similar patch https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/gdb-disable-makeinfo.patch that I couldn't retrofit

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by qliphy** [comment]
Adding @davidlange6 @fabiocos @kpedro88

There is an issue with this PR on "makeinfo".   Please find below a summary from Siew Yan:

1.) Update/Upgrade sherpa and open loop:
a.) Upgrade sherpa to 2.2.6 in 106X [1] (COMPLETE)
b.) Update open loops-2.0.b to openloops-2.0.0 [2] (COMPLETE)

2.) Backporting:
a.) Backporting sherpa 2.2.6 and openloops2.0.0 to 71X [3] (PENDING)
b.) Backporting sherpa 2.2.6 and openloops2.0.0 to 93X [4] (PENDING)
c.) Backporting sherpa 2.2.6 and openloops2.0.0 to 102X [5] (FAIL)

Pertaining to the nature of the issue on backporting sherpa and openloop in 102X [5], the bot failed at creating a makefile prior to sherpa building, specifically [6] :

The action "build-external+sherpa+2.2.6" was not completed successfully because Failed to build sherpa. …

/build/cmsbld/jenkins/workspace/ib-any-integration/testBuildDir/BUILD/slc6_amd64_gcc700/external/sherpa/2.2.6/sherpa-2.2.6/missing: line 81: makeinfo: command not found

WARNING: 'makeinfo' is missing on your system.
You should only need it if you modified a '.texi' file, or
any other file indirectly affecting the aspect of the manual.
You might want to install the Texinfo package:
<http://www.gnu.org/software/texinfo/>
The spurious makeinfo call might also be the consequence of
using a buggy 'make' (AIX, DU, IRIX), in which case you might

In response to this, Mircho Rodozov came out with a patch to circumvent makeinfo check (locally), however the hack does not work in bot testing[7]. The issue occur strangely to me as sherpa built successfully in 106X unless the issue came from the cmssw release side. 

[1] https://github.com/cms-sw/cmsdist/pull/4726
[2] https://github.com/cms-sw/cmsdist/pull/4796
[3] https://github.com/cms-sw/cmsdist/pull/4821
[4] https://github.com/cms-sw/cmsdist/pull/4822
[5] https://github.com/cms-sw/cmsdist/pull/4823
[6] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4823/34340/cmsswtoolconf.log
[7] https://github.com/cms-sw/cmsdist/pull/4823#issuecomment-483995421

**Comment by smuzaffar** [comment]
please test
For now we have disabled building Manual

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@efeyazgan @qliphy from the discussion at the ORP meeting I understand that this update is not going to break physics compatibility with the current production version

@smuzaffar we may move forward with the integration, I doubt the makeinfo is relevant for our CMSSW purposes

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
