### PR TITLE
Fix undefined spec variable for CUDA on ARM

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test for slc7_aarch64_gcc820

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc820

**Comment by mrodozov** [comment]
comparison job failed again

**Comment by silviodonato** [comment]
@mrodozov Andrea ran "please test for slc7_aarch64_gcc820" last night, and the test was ok. I would merge this PR in the next IB. Do you have some special reason for running again the tests?

**Comment by mrodozov** [comment]
I was going to ask you to get this in the IB, yes, the test will keep running regardless. Yes, the reason was to see if the comparison jon will fail again as we have trouble with the comparison jobs for ROOT6 IBs and now also for this ...

**Comment by mrodozov** [comment]
+externals

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
