### PR TITLE
Upgrade python cms monitoring

### PR DESCRIPTION
**Pull request by vkuznet**
This PR contains changes to update python cms-monitoring library to newer version.

### CODE REVIEW

**Comment by amaltaro** [comment]
Looks good to me, thanks Valentin.

**Comment by muhammadimranfarooqi** [comment]
+1 to 11c36f9571aa89a5bc1f98780b938f3ba588dadc on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6726/test_11c36f9-20210312-151003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi I let @vkuznet confirm, but this is no longer relevant. CMSMonitoring is already set to a newer version than the one provided in this PR.

**Comment by vkuznet** [comment]
yes, CMSMonitoring has newer version and this PR is obsolete.

**Pull request closed without merging**
