### PR TITLE
[14_0_X] Update AXOL1TL to v4.0.0

### PR DESCRIPTION
**Pull request by thesps**
Backport of #9271

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by aloeliger** [comment]
@cms-sw/externals-l2 Just a heads up, this is potentially desired by Wednesday to make HLT deadlines. Would there be any objection to signing it?

**Comment by mmusich** [comment]
urgent

**Comment by mmusich** [comment]
@smuzaffar please sign, this is in the way of the next trigger train, see https://github.com/cms-sw/cmssw/pull/45356#issue-2384530571 thank you.

**Comment by smuzaffar** [comment]
+externals

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
