### PR TITLE
Test latest CRAB Client tag

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@slava77 I don't understand how crab update can lead to differences in the comparison but still , 25 is somehow enough to ask to have a look :/

**Comment by belforte** [comment]
I guess that the build picked up other changes as well. This (that test of PR for CRAB spec files result with changes/errors in reco, dqm or other cmssw validation checks) happens all of the times.

**Comment by mrodozov** [comment]
it shouldn't. thats why I'm asking what's wrong if anything, I have to know. If nothings wrong I'm merging it before 2300

**Comment by belforte** [comment]
I am not pressing you @mrodozov , No problem, you can merge at any time. Simply I have seen tests failing on non-CRAB-related things several other times. I agree that it would be nicer if they didn't. But w/o knowing what exactly is compared with what I can't comment further.

**Pull request merged**
