### PR TITLE
Using consistent Eigen alignment settings

### PR DESCRIPTION
**Pull request by smuzaffar**
This is follow up on https://github.com/cms-sw/cmsdist/pull/9043. This change allows
- to use consistent build flags for project depending on eigen
- enable vectorization build for `lwtnn, opencv and pytorch` packages

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_MULTIARCHS_X/el8_amd64_gcc12

**Comment by makortel** [comment]
Thanks @smuzaffar. I have two questions
* In https://github.com/cms-sw/cmsdist/pull/9043#discussion_r1515795232 you discovered that `lwtnn` 2.13 overrides the `CMAKE_CXX_FLAGS`. Should this PR update `lwtnn` 2.14.1?
* Do we care about `professor2`? It depends on `eigen`, but as far as I can tell nothing in CMSSW depends on it. (I'm also fine if we deal with it later, given the [urgency](https://github.com/cms-sw/cmsdist/pull/9043#issuecomment-1988299088))

**Comment by smuzaffar** [comment]
ah my bad @makortel , yes `lwtnn` should be updated ( I already have updated the PR).
For `professor2`, I am still running some local tests. As it is not directly used in cmssw so I will update it in a separate PR

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_MULTIARCHS_X/el8_amd64_gcc12

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
lets get this in for next 14.1.X IB.

**Comment by fwyzard** [comment]
> enable vectorization build for `lwtnn, opencv and pytorch` packages

@smuzaffar it looks like those packages are still using only `-msse3` ?

**Comment by smuzaffar** [comment]
Yes @fwyzard , for default (non multiarch build) IBs these packages will still use `-msse3`.  This PR only adds these packages in to list of packages which can be build for multi-archs. https://github.com/cms-sw/cmsdist/pull/9061 PR actually build these packages for multi-archs (see logs https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b88baa/38046/externals/ ) 
```
[29/38] : && /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/g++ \
-fPIC -DEIGEN_DONT_PARALLELIZE -DEIGEN_MAX_ALIGN_BYTES=64 -march=x86-64-v3 \
-Wall -pedantic -Wextra -Wcomment -Wunused-value -O3 -DNDEBUG  \
CMakeFiles/lwtnn-dump-config.dir/src/lwtnn-dump-config.cxx.o -o bin/lwtnn-dump-config  lib/liblwtnn-stat.a && :
```

**Comment by fwyzard** [comment]
OK, thanks.

I see that the default build has
```
cmake ../lwtnn-2.14.1 -G Ninja -DCMAKE_CXX_COMPILER=g++ '-DCMAKE_CXX_FLAGS=-fPIC -DEIGEN_DONT_PARALLELIZE -DEIGEN_MAX_ALIGN_BYTES=64 -msse3' ...
```
while the v3 build has
```
cmake ../lwtnn-2.14.1 -G Ninja -DCMAKE_CXX_COMPILER=g++ '-DCMAKE_CXX_FLAGS=-fPIC -DEIGEN_DONT_PARALLELIZE -DEIGEN_MAX_ALIGN_BYTES=64 -march=x86-64-v3' ...
```
but, looking at the spec files, I don't see what makes the change between the two !

**Comment by smuzaffar** [comment]
@fwyzard , to avoid maintaining two spec files (e.g. lwtnn.spec and lwtnn_x86-64-v3.spec) `cmsBuild` has a way of auto generating `<package>_<micro-arch>.spec`  from `<package>.spec`. For multi-arch packages, it uses https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_1_X/master/vectorization/cmsdist_packages.py to auto generate `<package>_x86-64-v3.spec` by replacing the default micro-arch flag (`-msse3`) with the selected micro-arch flag (`-march=x86-64-v3`)

**Comment by fwyzard** [comment]
Ah... I see, thanks.

**Pull request merged**
