### PR TITLE
More python packages update for nose2 dependency

### PR DESCRIPTION
**Pull request by amaltaro**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to d6a02d3a7a2467acdefad901092b967fe62d15b3 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6043/test_d6a02d3-20200707-153503.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to 4845d005e50fbcdd5cba28867eb1a9008dffd9fa on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6043/test_4845d00-20200708-001003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi this is only used by CRAB and WMCore dev tools. I'll go ahead and merge it soon to create a new WMAgent release.

**Comment by muhammadimranfarooqi** [comment]
+1 to ed8ce42a2ffdf36325c27231b848a71940eeba02 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6043/test_ed8ce42-20200709-074003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
