### PR TITLE
Update llvm/clang to 7.0.0-svn342187 (release) (10.3.x backport)

### PR DESCRIPTION
**Pull request by fwyzard**
Update IWYU to the current master.

Disable automatic package dependencies: llvm 7 includes a new tool, llvm-exegesis, that depepnds on libpfm.so. Rather than including this library in the CMSSW stack, we assume that it will be available form the host system; as it's not something strictly necessary to have, we avoid a hard dependency on it in the RPM package.

Enable support for compiling CUDA code on amd64.

Backport basic support for compiling with CUDA 10.0 from the llvm 8 master branch.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #4353 and #4367 from 10.3.x devel IBs

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
OK, so it's not a transient error... do we know where it comes from ?
Probably I will be able to look into it only after next week.

**Comment by smuzaffar** [comment]
closing due to integration of https://github.com/cms-sw/cmsdist/pull/4359

**Pull request closed without merging**
