### PR TITLE
[ROOT] get latest commits from master

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by smuzaffar** [comment]
this is the error while loading disc
```
>> Checking EDM Class Transients in libDataFormatsHGCalReco.so
While building module 'boost_functional' imported from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_ROOT6_X_2020-06-01-2300/src/DataFormats/Common/interface/Ref.h:115:
While building module 'boost_utils' imported from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/boost/1.72.0-nlgpag/include/boost/container_hash/extensions.hpp:22:
In file included from <module-includes>:34:
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/boost/1.72.0-nlgpag/include/boost/make_shared.hpp:14:
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/boost/1.72.0-nlgpag/include/boost/smart_ptr/make_shared.hpp:14:
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/boost/1.72.0-nlgpag/include/boost/smart_ptr/make_shared_object.hpp:17:
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/boost/1.72.0-nlgpag/include/boost/smart_ptr/shared_ptr.hpp:28:
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/boost/1.72.0-nlgpag/include/boost/smart_ptr/detail/shared_count.hpp:30:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc820/external/boost/1.72.0-nlgpag/include/boost/smart_ptr/detail/sp_counted_impl.hpp:254:31: error: declaration of 'allocator_trait
s' must be imported from one of the following modules before it is required:
        std.algorithm
        std.string
        std.deque
        std.forward_list
        [...]
        typedef typename std::allocator_traits<A>::template rebind_alloc< this_type > A2;
                              ^
/cvmfs/cms-ib.cern.ch/nweek-02631/slc7_amd64_gcc820/external/gcc/8.2.0-bcolbf/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.4.0/../../../../include/c++/8.4.0/bits/alloc_traits.h:83:12: note: previous declaration is here
    struct allocator_traits : __allocator_traits_base
           ^

```

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
adds this https://github.com/root-project/root/pull/5793 on top
lets test it

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
