### PR TITLE
Enable -std=c++20 for CMSSW build

### PR DESCRIPTION
**Pull request by smuzaffar**
FYI @makortel

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
@smuzaffar, CUDA 12.0 was released last week, with support for GCC 12 and c++20.
I'm taking the opportunity to redesign the CUDA spec files, I will make a PR for it in the coming days.

**Comment by makortel** [comment]
I also just came across with https://github.com/root-project/root/pull/11311#issuecomment-1252819197 so I'm less optimistic now that "partially switching" to C++20 would work...

**Comment by fwyzard** [comment]
Can we build ROOT in c++20 mode ?

**Comment by smuzaffar** [comment]
we can try

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
> Can we build ROOT in c++20 mode ?

As far as I can tell, no. The LLVM 13 was integrated in ROOT master ~last week (earlier use LLVM 9), and here is their open PR to support for building with C++20 https://github.com/root-project/root/pull/11874 .

**Comment by smuzaffar** [comment]
please test for CMSSW_13_2_ROOT628_X

**Comment by fwyzard** [comment]
@smuzaffar are we already using CUDA 12 for this ?

I just reproduced and submitted another bug report...
  - https://forums.developer.nvidia.com/t/compiling-a-catch2-application-with-nvcc-std-c-20-leads-a-crash-in-cudafe/255088
  - https://developer.nvidia.com/nvidia_bug/4139863 (protected)
  - https://github.com/fwyzard/nvidia_bug_4139863

**Comment by smuzaffar** [comment]
no @fwyzard , this is still based on cuda 11.5

**Comment by fwyzard** [comment]
ah... so we would use c++20 with gcc and g++17 with nvcc ?

**Comment by smuzaffar** [comment]
> ah... so we would use c++20 with gcc and g++17 with nvcc ?

ah right, we also have https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_2_X/master/cuda-flags.file#L19 
```
%define nvcc_stdcxx -std=c++17
```

I thought we were getting it form gcc xml. let me try to move the c++std flag to its own dedicated flag file.

**Comment by fwyzard** [comment]
Mhm, OK, but keep in mind that CUDA 11.5 (up to CUDA 11,8, included) do not support C++20.
The support was added only with CUDA 12.

**Comment by smuzaffar** [comment]
ok, so may be I need to setup a new IB for testing c++20 with
- gcc 12 or gcc 11
- cuda 12
- root 6.28

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
> ok, so may be I need to setup a new IB for testing c++20 with
> 
> * gcc 12 or gcc 11
> * cuda 12
> * root 6.28

Yeah, given the complexity a new IB sounds like a good choice (sorry).

**Comment by makortel** [comment]
```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_13_2_X_2023-05-31-2300/src/FWCore/MessageLogger/interface/ErrorObj.icc:61:27: error: 'fmt' is not a constant expression
   61 |     auto str = fmt::format(fmt, args...);
      |                ~~~~~~~~~~~^~~~~~~~~~~~~~
```
cppreference has for [`std::format()`](https://en.cppreference.com/w/cpp/utility/format/format)
> As of [P2216R3](https://wg21.link/P2216R3), it is an error if the format string is not a constant expression. [std::vformat](https://en.cppreference.com/w/cpp/utility/format/vformat) can be used in this case.

So the `ErrorObj::format()` etc need to be fixed (possibly adding `ErrorObj::vformat()` for the case of runtime-known formatting strings)

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/41888 makes an attempt to fix the MessageLogger's interface. At least the MessageService unit tests compile in the C++20-enabled build of https://github.com/cms-sw/cmsdist/pull/8233#issuecomment-1572210519

**Comment by smuzaffar** [comment]
We now have 13.2.CPP20 IBs setup which use
- GCC 12
- ROOT 6.28 (built with c+=20)
- CUDA 12
- TF with disabled GPU

closing this PR now

**Pull request closed without merging**
