### PR TITLE
Update Sherpa 2.2.8

### PR DESCRIPTION
**Pull request by SiewYan**
1.) Bump up Sherpa to 2.2.8
2.) Interface with Rivet3
3.) Install lhc processes only for openloops

### CODE REVIEW

**Comment by fabiocos** [comment]
@SiewYan we have just recently updated sherpa to 2.2.7 , and the validation of this version for backport is not even finalized to my knowledge. Is this further update meant to supersede the previous one, even for 10_6_X?

**Comment by fabiocos** [comment]
please test workflow 534.0,536.0

**Comment by SiewYan** [comment]
@fabiocos , yes, the update on sherpa 2.2.8 meant to supersede 2.2.7 for 10_6_X. Update on sherpa 2.2.7 on 11_0_X was dropped though..

@smuzaffar , any news from the openloop related issue? thanks.

**Comment by smuzaffar** [comment]
@SiewYan, please re-do this Pr for IB/CMSSW_11_0_X/master branch

**Comment by smuzaffar** [comment]
@fabiocos , no openloop issue is not resolved. We can not build it for AARCH64 using gcc 8. We have disabled for non x86_64 archs https://github.com/cms-sw/cmsdist/pull/5221 . Openloops developer suggested that they have avoid the issue by using `-mcmodel=medium` flog for x86_64 ( https://github.com/cms-sw/cmsdist/pull/5222 ) but this trick does not work for non x86_64. So for now openloops is disabled for non x86_64.

**Comment by SiewYan** [comment]
@smuzaffar , sorry, should i abort this PR and push the changes on IB/CMSSW_11_0_X/master branch?

**Comment by smuzaffar** [comment]
yes please

**Comment by SiewYan** [comment]
re-PR: https://github.com/cms-sw/cmsdist/pull/5231

**Pull request closed without merging**
