### PR TITLE
Improve Eigen compatibility with CUDA (10.4.x devel)

### PR DESCRIPTION
**Pull request by fwyzard**
Update Eigen to the master branch as of Tue Sep 25 20:26:16 2018 +0200
  - hg hash  66ba78bf7efa93f69a075830a87a010ed1b1fe30
  - git hash 01ae86b9aad30b1e65cf1b749fd6cd9a645ac00d

Patch Tensorflow to follow Eigen internal changes
  - cherry-pick changes from upstream repository
  - add local changes for the latest updates

Improve Eigen compatibility with CUDA
  - add support for cache-size queries on CUDA devices.
  - extend support for matrix inversion on CUDA devices above 4x4 matrices;
the size of the matrices that can be inverted is limited at runtime by the per-thread stack size.
  - extend support for diagonal matrices on CUDA devices.
  - fix deprecation warning in CUDA 10.0.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
rebased on IB/CMSSW_10_4_X/gcc700 as of 10.4.0-pre1, and remove one Tensorflow backport

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
Do you have any idea why this fails, while the same changes (#4474) work on the standard IB ?

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
the error doesn't look related to eigen. lets try again

**Comment by smuzaffar** [comment]
lets get this in devel IBs and after 10.4.0.pre2 we can merged include it in normal IBs.

**Comment by fwyzard** [comment]
Thanks.

I'd rather have it in pre2 than after, but I can bring it up at the next ORP (unless pre2 srrives before that).

**Comment by smuzaffar** [comment]
@fabiocos wants to build pre2 over the weekend.

**Comment by fwyzard** [comment]
I see... I'd still be happy to have this in (it saves me from building the externals myself for Patatrack) but I won't complain if it enters after pre2...

**Pull request merged**
