### PR TITLE
[94X] backport cms-git-tools changes

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_9_4_X

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
94X patch IBs are failing due to cms-git-tools issue. I am merging it to get 94X in working state

**Comment by fabiocos** [comment]
@smuzaffar I'll pick it in next build to be done asap

**Pull request merged**
