### PR TITLE
Upgrade Herwig to v7.2.1, and add patch to fix crash when reading lhe…

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
Backport of https://github.com/cms-sw/cmsdist/pull/6462 for use in UL production

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@Dominic-Stafford  , should this go in CMSSW_11_2_X too? If yes then can you please open a PR for IB/CMSSW_11_2_X/master

**Comment by Dominic-Stafford** [comment]
Hi, I wasn't planning on doing this for 11_2 as I don't believe it's used in any MC production campaigns, but I can easily do this if you feel it would be useful?

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
test parameters:
- workflows=511.0

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
