### PR TITLE
[ROOT626] Root update v6 26 00 patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
@aandvalenzuela , this error is due to update to root version (https://github.com/root-project/root/blob/v6-26-00-patches/build/version_number :  6.26/07 ). please update root version to 6.26.07 in root.spec file and request a full cmssw PR test

**Comment by iarspider** [comment]
test parameters:
- full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
> @aandvalenzuela , this error is due to update to root version (https://github.com/root-project/root/blob/v6-26-00-patches/build/version_number : 6.26/07 ). please update root version to 6.26.07 in root.spec file and request a full cmssw PR test

Thanks, Shahzad!

**Comment by aandvalenzuela** [comment]
Wow, that was a fast reaction! Thank you team :)

**Pull request merged**
