### PR TITLE
Use same soruces for jemalloc and jemalloc-debug

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by fwyzard** [comment]
Few years ago the `jemalloc-debug` package was explicitly not upgraded to jemalloc 5.0 because of it being extremely slow: https://github.com/cms-sw/cmsdist/pull/3329 .

Was it ever investigated, before switching ?

**Comment by smuzaffar** [comment]
@fwyzard , it think issue there was the use of `jemalloc-debug` libs in production which were overriding the `jemalloc` libs. This happed as the `jemalloc-debug` toolfiles were not skipped/dropped 9 https://github.com/cms-sw/cmsdist/pull/3329/files#diff-e2f892bf13eeb6853c89ce59c658bb3b860981ce12ad8e32cc2063e79a5c08afR192 )

**Comment by fwyzard** [comment]
Ah, I see, so the issue was `jemalloc-debug` vs `jemalloc`, not `jemalloc-debug` 5.0 vs 4.5. Thanks for clarifying !

**Pull request merged**
