### PR TITLE
GCC 11.4; CUDA 11.8; cleanup for cmsplatf/cmsos use

### LINKED ISSUE #7571: cmsdist  changes needed to avoid use of cmsplatf
We need to cleanup cmsdist to avoid use of cmsplatf usage. This is not urgent but for any major rebuild of externals (e.g. python/gcc version change, new arch etc. ) we should cleanup these specs.

- Use `%ifos darwin` to run darwin/osx specific build commands for following
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/boost.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/charybdis.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/hector.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/pythia6.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/cmake.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/evtgen.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/xerces-c.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/curl.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/valgrind.spec
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/tkonlinesw.spec

- Remove unused https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/bz2lib.spec#L3 
- Check if gcc version check here https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/starlight.spec#L24-L26 can be improved

### PR DESCRIPTION
**Pull request by smuzaffar**
- Update GCC version to 11.4.1 and its prerequisites and build with zstd support ( changes backported from gcc 12 branch)
- CUDA 11.8 which has GCC 11.4 support
- Fixes to resolve https://github.com/cms-sw/cmsdist/issues/7571 i.e. clean up for the usage of `cmsplatf` and `cmsos`
- Added missing dependencies for sqlite, swig, py3-pillow, gnuplot

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- enable = gpu

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
Please test

**Comment by smuzaffar** [comment]
@makortel  @fwyzard , this PR updates CUDA 11.8  and GCC 11.4 (along with some cleanup). Tests look good, do you want to run any local tests before we integrate it for 13.2.X (after 13.2.0.pre2 build)

**Comment by fwyzard** [comment]
I'm OK with the changes.

I had already tested CUDA 11.8.0 standalone, and the performance was the same as 12.0 and 12.1: they have a slightly worse performance than 11.5 in the standalone test, but the CMSSW measurement with 12.x did not show any impact, so it shouldn't be a problem and from that point of view we can go ahead.

Since the main update in 11.8.0 is the support for the latest GPU generations, I think we should update the `cuda-flags.file` accordingly:

https://github.com/cms-sw/cmsdist/blob/97b10490505b46d36f6ecf48fdc44b17e9aa19e5/cuda-flags.file#L4-L12

I would simplify it to
```spec
# build support for Pascal, Volta, Turing, Ampere, Lovelace and Hopper
%define cuda_arch 60 70 75 80 86 89 90
```

This list targets `80` for the A100 and A30, `86` for the A40, A10 and the RTX 3000 series, and `89` for the L4, L40, and RTX 4000 series.

The main drawback of building for more architectures is that it will take longer and produce slightly larger libraries.

If that's a problem, a more minimal list could be:
```spec
# build support for Pascal, Volta, Turing, Ampere, and Hopper
%define cuda_arch 60 70 75 80 90
```

**Comment by makortel** [comment]
Just to be explicit, I'm ok with the changes as well.

**Comment by smuzaffar** [comment]
ok I have added `%define cuda_arch 60 70 75 80 86 89 90` flags. lets see how the build goes and what are the sizes of different externals

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard , looks like `cuda_arch 60 70 75 80 86 89 90` is not working , see the error above

**Comment by fwyzard** [comment]
I can have a look next week... it's strange that it fails for sm 60, since
that was already enabled.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard ,  how about we test the new cuda_arch once gcc11.4 changes are merged?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
Please test

**Comment by smuzaffar** [comment]
> DQMHistoTests: Total failures: 11

mostly in message logger but there are couple of errors for HLT https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-19-2300+81a383/57586/12434.0_TTbar_14TeV+2023/

> Reco comparison results: 45 differences found in the comparisons

mostly due to message logger but there are few in wfs 4.53 and 9.0 which are non-message logger failure.

**Comment by smuzaffar** [comment]
+externals

**Comment by makortel** [comment]
> > DQMHistoTests: Total failures: 11
> 
> mostly in message logger but there are couple of errors for HLT https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-19-2300+81a383/57586/12434.0_TTbar_14TeV+2023/

Those differences look compatible with random differences reported in https://github.com/cms-sw/cmssw/issues/41200

**Comment by smuzaffar** [comment]
@perrotta @rappoccio this is good to go in. It includes GCC minor version update and cuda 11.8 . Note that due to GCC changes it rebuilts all the externals. I would like to get this in 13.2.X IBs now so that we have couple of weeks of IBs before we cut last open pre-release

**Comment by perrotta** [comment]
+1

**Pull request merged**
