### PR TITLE
Re-add patches to propagate lhe numbering through herwig

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
Re-adds the necessary Herwig patches to read numbers from an LHE file, which were initially added in #8349, then reverted in #8417 due to an issue with multithreading.

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/42673
- relvals_threading = 512.0
- enable = threading

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

this should only be merged with https://github.com/cms-sw/cmssw/pull/42673

**Comment by iarspider** [comment]
please test workflow 535.0,537.0,538.0

**Comment by smuzaffar** [comment]
ah   has been merged with this PR. let force merge this too

**Pull request merged**
