### PR TITLE
[BuildRules] Enable Alpaka/Rocm backend

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = HeterogeneousCore, DataFormats/Portable, HeterogeneousTest, DataFormats/PortableTestObjects
- pull_request = cms-sw/cmssw#40725, cms-sw/cmssw#40736
- skip_test = static
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
Now I am confused :-(

The same workflows work for me using a release area created with `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/8301/30533/install.sh`, both on a machine with GPUs and on a machine without any GPUs.

**Comment by makortel** [comment]
I can reproduce the error if I artificially set `ProcessAcceleratorCUDA._available = False` in https://github.com/cms-sw/cmssw/pull/40725. It seems strange that `del` or `delattr()` raise an error when the `CUDAService` is clearly there. I'll take a deeper look.

**Comment by makortel** [comment]
Ah, it's because the `Process` is wrapped as `ProcessForProcessAccelerator` when passed to `ProcessAccelerator.apply()`, and that doesn't implement `__delattr__()`. I'll add it.

**Comment by fwyzard** [comment]
Ah, thanks for the fix.

> I can reproduce the error if I artificially set `ProcessAcceleratorCUDA._available = False` in [cms-sw/cmssw#40725](https://github.com/cms-sw/cmssw/pull/40725).

Any idea why it worked for me on a machine without any GPUs, and on a machine where I set explicitly `CUDA_VISIBLE_DEVICES=` ?

**Comment by makortel** [comment]
The fix is in https://github.com/cms-sw/cmssw/pull/40736

> > I can reproduce the error if I artificially set `ProcessAcceleratorCUDA._available = False` in [cms-sw/cmssw#40725](https://github.com/cms-sw/cmssw/pull/40725).
> 
> Any idea why it worked for me on a machine without any GPUs, and on a machine where I set explicitly `CUDA_VISIBLE_DEVICES=` ?

I have no idea.

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
@smuzaffar this is also being tested as part of https://github.com/cms-sw/cmssw/pull/40725

**Comment by fwyzard** [comment]
test parameters:
  - skip_test = static

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#40725

**Comment by smuzaffar** [comment]
@fwyzard , https://github.com/cms-sw/cmsdist/pull/8301#issuecomment-1423192226 already skips the static checks :-) so I deleted your comment which was also overriding the parameters provided by https://github.com/cms-sw/cmsdist/pull/8301#issuecomment-1423192226

**Comment by fwyzard** [comment]
The changes introduced by this PR, namely
```diff
 %if "%{?configtag:set}" != "set"
-%define configtag       V07-05-11
+%define configtag       V07-05-12
 %endif
```
correspond to https://github.com/cms-sw/cmssw-config/compare/V07-05-11..V07-05-12:
```diff
   <flags CHECK_PRIVATE_HEADERS="1"/>
   <flags SCRAM_TARGETS="haswell sandybridge nehalem"/>
   <flags OVERRIDABLE_FLAGS="CPPDEFINES CXXFLAGS FFLAGS CFLAGS CPPFLAGS LDFLAGS CUDA_FLAGS CUDA_LDFLAGS LTO_FLAGS ROCM_FLAGS ROCM_LDFLAGS"/>
-  <flags ALPAKA_BACKENDS="cuda serial"/>
+  <flags ALPAKA_BACKENDS="cuda rocm serial"/>
   <flags CODE_CHECK_ALPAKA_BACKEND="serial"/>
   <flags ENABLE_LTO="@ENABLE_LTO@"/>
  </client>
```

and do not seem to have anything to do with the availability of the `CUDAService`.

@smuzaffar @iarspider could you look into what is actually causing the tests to fail ?

**Comment by smuzaffar** [comment]
though the change in cmssw-config look simple but that enables `alpaka/rocm` backend which means all the packages with alpaka code should now be generated an extra `ROCmAsync` product. Also I think the DataFormat packages also need classes files for rocm. May be we need a full cmssw build to get such change in?

**Comment by fwyzard** [comment]
Yes, those changes should come through https://github.com/cms-sw/cmssw/pull/40725 .

**Comment by smuzaffar** [comment]
please test

let me run the tests with full cmssw build

**Comment by smuzaffar** [comment]
@fwyzard , could there be a typo ? I see message
```
Service Request unable to find requested service with compiler type name ' CUDAService'
```
i.e. a space before the `CUDAService`

**Comment by fwyzard** [comment]
I did see that, but I couldn't find anything related in either of the PRs
:-/

**Comment by smuzaffar** [comment]
ok I found the issue, see https://github.com/cms-sw/cmssw/pull/40725#issuecomment-1425800987 for details

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#40832

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#40832 for el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@smuzaffar @perrotta @rappoccio, now that 13.1.0-pre1 is out, can we merge this in 13.1.x, and backport it to 13.0.0 ?

**Comment by fwyzard** [comment]
(all test failures were unrelated to this PR, let's see if they go away re-running on a more recent IB)

**Comment by fwyzard** [comment]
please test for el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
ehm, what ?

**Comment by fwyzard** [comment]
I presume this
```
error: line 417: Unknown tag: <<<<<<< HEAD
```
means there is a conflict somewhere... I've opened https://github.com/cms-sw/cmsdist/pull/8346 with the same diff but a clean commit history.

**Comment by smuzaffar** [comment]
problem here is that it is also using a cmssw PR for 13.0.X ( https://github.com/cms-sw/cmsdist/pull/8301#issuecomment-1423192226 ) due to which bot tried to use 13.0.X cmsdist branch ( CMSSW_13_0_X_2023-02-28-1500/el8_ppc64le_gcc11 )

**Pull request closed without merging**
