### PR TITLE
Updated root to tip of branch v6-28-00-patches

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
looks like issue with latest root changes. I have opened https://github.com/root-project/root/issues/12771

**Pull request closed without merging**
