### PR TITLE
[ROOT628] Update ROOT to tip of branch v6-28-00-patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

good to go in root628. The unit test normally failed during PR tests with full cmssw re-build and root version update

**Pull request merged**
