### PR TITLE
Update crabserver and crabcache to depend on WMCore 1.3.6.crab1 tag

### PR DESCRIPTION
**Pull request by ddaina**
Update WMCore tag to 1.3.6.crab1 and CRAB tag to v3.200816

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 9bbfcff651e770c206f09d1848bc11b9c292fd5f on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6178/test_9bbfcff-20200818-155003.log" target="_blank">here</a>.

**Comment by ddaina** [comment]
merge

**Comment by ddaina** [comment]
merge

**Comment by amaltaro** [comment]
@ddaina @muhammadimranfarooqi I think the subject of this PR (and commit message) might be misleading. Something like "Update CrabServer and CrabCache to depend on WMCore 1.3.6.crab1" would be more meaningful IMO. If you agree, I'd suggest to update this PR title and also the CMSWEB release notes.

I also noticed that Daina merged this PR herself, and AFAIK things that go into CMSWEB still have to go through the CMSWEB (aka. they are supposed to merge PRs). Just my 2cents ;)

**Comment by ddaina** [comment]
@amaltaro agree on commit message comment, it is indeed misleading, I have updated PR title. Thanks! @muhammadimranfarooqi could you please do the same for the CMSWEB release notes?

regarding merging the PR, @belforte please correct me if I am wrong, but we merge ourselves, don't we (this is at least what I see in the PR history)? Or is it applicable to your PR and mine should be merged by you or CMSWEB operator?

**Comment by amaltaro** [comment]
Services that don't get deployed in CMSWEB, we can merge ourselves (like CrabClient, WMAgent, TaskWorker). CRABServer goes to CMSWEB, so it should go through the CMSWEB team.

**Comment by muhammadimranfarooqi** [comment]
@ddaina @amaltaro 

I have updated release notes. I agree with Alan for not merging PRs for CMSWEB services.

**Comment by ddaina** [comment]
OK, thanks, I'll do accordingly then next time :)

**Pull request merged**
