### PR TITLE
[10_6_X + gcc700] Bump of cepgen version to 1.2.5

### PR DESCRIPTION
**Pull request by forthommel**
This PR bumps the CepGen version to the gcc7x upstream version 1.2.5.
This latter drops the support to various add-ons, and in particular ROOT interface (which allows to drop the CMake patch introduced earlier to cleans it up from the CepGenAddOns CMake directive).

FYI: @bbilin

### CODE REVIEW

**Comment by bbilin** [comment]
@cmsbuild please test

**Comment by bbilin** [comment]
Also this involves a bugfix regarding missing status of particles in HepMC format.

**Comment by forthommel** [comment]
My bad! I forgot a leftover `%patch` instruction in the spec-file!

**Comment by bbilin** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
+externals

@cms-sw/orp-l2 , feel free to include it for 10.6.X IBs

**Comment by rappoccio** [comment]
+1

**Comment by forthommel** [comment]
Thanks a lot, @bbilin, @smuzaffar, @rappoccio !

**Pull request merged**
