### PR TITLE
Update root spec on CMS rootgcc6 branch to latest master commits

### PR DESCRIPTION
**Pull request by mrodozov**
Update IB/CMSSW_10_0_X/rootgcc6 root.spec to tip of root master

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
github went down, the test failed while trying to communicate with it.

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Pull request merged**
