### PR TITLE
Fix py2 dxr linux 76x next

### PR DESCRIPTION
**Pull request by gartung**
Merge conflict in Requires lines. Please take mine

### CODE REVIEW

**Comment by davidlt** [comment]
LGTM regarding the _next_ branch, but GitHub says that this has a conflict.

**Comment by gartung** [comment]
Conflict is addition of string at end of Requires line.

**Comment by ghost** [comment]
@gartung you should rebase on top of what I just merged

**Comment by gartung** [comment]
The remaining difference is that I remade the trilite patch with git. The patch command has to change to accomodate that.

**Pull request merged**
