### PR TITLE
Update rucio-clients from 1.23.6 to 1.23.11

### PR DESCRIPTION
**Pull request by amaltaro**
I haven't tried to build it locally, let's see how bot builds goes with it.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
+1 to 1c21fe1d30219aa3f1283cfd0ebfa5da14b37969 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6447/test_1c21fe1-20201124-231003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@belforte Stefano, this can affect the next crabtaskworker that you build from COMP. Honestly, I haven't tested this version yet, but it should be safe enough.

**Comment by belforte** [comment]
yeah.. let's assume it works and if does not we'll scream. We always test new builds before deploying in production

**Comment by amaltaro** [comment]
Thanks Stefano! We can have the first tests today in testbed and in my private VM. Still further tests will be needed from a newer WMAgent version as well, since those use different functionalities/APIs from the client. We keep in touch ;)

**Comment by amaltaro** [comment]
@muhammadimranfarooqi you might want to merge this one before I make the WMCore PR

**Comment by amaltaro** [comment]
@belforte the client now checks for the certificates permissions, which broke a couple of services CMSWEB testbed nodes.
E.g.:
```
Details: X.509 authentication selected, but private key (BLAH-key.pem) permissions are liberal (required: 400, found: 440)
```

I'm still discussing with Imran whether we risk trying to fix it in the deployment of workqueue/reqmgr2ms, or whether we rollback the version and tackle it in the next month... Will let you know today/tomorrow.

**Comment by muhammadimranfarooqi** [comment]
I have fixed the permission issue in the K8s using `run.sh`  script for `workqueue` and deployed again.

```
[root@workqueue-5b546679b7-wlcfj data]# ls -l /data/srv/current/auth/workqueue/
total 20
-r--------. 1 _workqueue _workqueue 3399 Nov 25 13:19 dmwm-service-cert.pem
-r--------. 1 _workqueue _workqueue 1828 Nov 25 13:19 dmwm-service-key.pem
-r--r-----. 1 _workqueue _workqueue   20 Nov 25 13:19 header-auth-key
-r--r-----. 1 _workqueue _workqueue   93 Nov 25 13:19 WorkQueueSecrets.py
-r--r-----. 1 _workqueue _workqueue  266 Nov 25 13:19 WorkQueueSecrets.pyc
```

**Comment by belforte** [comment]
well done @muhammadimranfarooqi . On the good side CRAB applications on CMSWEB do not talk to Rucio, so we will not be affected. I looked at TaskWorker and we have correct mode 400 already for the *key.pem. FWIW notice that *cert.pem is the public key and does not need to be protected.

**Comment by muhammadimranfarooqi** [comment]
Thanks Stefano, I am updating *cert.pem permission to 440.

**Pull request merged**
