### PR TITLE
bump sherpa up to 2.2.10 for Ultra-Legacy

### PR DESCRIPTION
**Pull request by SiewYan**
bump sherpa up to 2.2.10 for Ultra-Legacy

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
This PR is to make use of the included feature to recover Spin correlation for tau in the top decay. https://gitlab.com/sherpa-team/sherpa/-/merge_requests/296

**Comment by SiewYan** [comment]
assign generator

**Comment by SiewYan** [comment]
@GurpreetSinghChahal

**Comment by mrodozov** [comment]
Can I ask if you plan to get sherpa 2.2.10 in 11_2 first, and if yes can we do it  first there and then backport it maybe ?

**Comment by SiewYan** [comment]
@mrodozov , thanks for the suggestion and yes, we are fine with that.

**Comment by SiewYan** [comment]
#6115

**Comment by SiewYan** [comment]
please test for CMSSW_10_6_X/slc7_amd64_gcc700

**Comment by mrodozov** [comment]
please test for CMSSW_10_6_X/slc7_amd64_gcc700

**Comment by SiewYan** [comment]
Closing in favor of #6116

**Pull request closed without merging**
