### PR TITLE
bump python tool versions to recent versions on pypi

### PR DESCRIPTION
**Pull request by davidlange6**
(looks like a lot of packages dropped python2 support recently - I didn't go through to split python2 and python3 version of any of these, so the python3 versions are falling behind in some cases)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_11_3_PY3_X

**Comment by smuzaffar** [comment]
@davidlange6 , as this is going to build nearly all the pythoon packages, I would suggest to do the same for pip (for python3) i.e. a separate py3-pip package

**Comment by smuzaffar** [comment]
closing in favor of https://github.com/cms-sw/cmsdist/pull/6557

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
looks like message logger differences for comparsion

**Pull request merged**
