### PR TITLE
Revert "Update root to include fix for TH1::clone leak."

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmsdist#1852

### CODE REVIEW

**Comment by davidlt** [comment]
Why revert? If I recall, this is a critical and required memory leak fix.

**Comment by smuzaffar** [comment]
74X IBs and 7.4.14 release failed 
https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc491/www/wed/7.4-wed-11/CMSSW_7_4_X_2015-09-30-1100

```
Traceback (most recent call last):
  File "/build/cmsbuild/jenkins-workarea/workspace/build-cache/cms.week0/w/tmp/BUILDROOT/83961e39f93f631edfab59d8d104c1a4/opt/cmssw/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-09-30-1100/src/FWCore/Utilities/scripts/edmCheckClassVersion", line 186, in <module>
    errorCode,rootClassVersion,classChecksum = checkClass(name,info[XmlParser.classVersionIndex],info[XmlParser.versionsToChecksumIndex])
  File "/build/cmsbuild/jenkins-workarea/workspace/build-cache/cms.week0/w/tmp/BUILDROOT/83961e39f93f631edfab59d8d104c1a4/opt/cmssw/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-09-30-1100/src/FWCore/Utilities/scripts/edmCheckClassVersion", line 129, in checkClass
    raise RuntimeError("TClass::GetCheckSum: Failed to load dictionary for base class. See previous Error message")
RuntimeError: TClass::GetCheckSum: Failed to load dictionary for base class. See previous Error message
```

my guess is that it is due to this root update.

**Comment by davidlt** [comment]
But the same ROOT is in CMSSW_7_6_X and it works fine. Also does this rever bubbles up to CMSSW_7_6_X via auto-crap-forward?

**Comment by smuzaffar** [comment]
76X is using the tip of 6-02-00-branches while 74X is way behind that one. 
Ah I see that beside the cms-sw/root#101 (memory leak fix) there is also cms-sw/root#95 from @Dr15Jones  for thread efficiency changes got in to 74X. @davidlange6 , I guess we do not want cms-sw/root#95 to be part of 74X yet .....right?

**Comment by davidlange6** [comment]
Its not a big problem if the thread efficiency changes were included - but if these are the two changes to root that went in, I’m sure its #95 that causes the checksum issues (and thus is a sign that we would need a different implementation to be compatible with the 74x root)

So, lets indeed go back to just the 74x root + cms-sw/root#95

**Pull request merged**
