### PR TITLE
[pythia6]Move pythia6_pdfdummy in to separate tool

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

This will fail where pythia6_pdfdummy is explicitly needed

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

This will fail where pythia6_pdfdummy is explicitly needed

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46684

**Comment by smuzaffar** [comment]
+externals

This should go in along with https://github.com/cms-sw/cmssw/pull/46684

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
