### PR TITLE
WMAgent production release candidate: 1.3.6.patch3; with new rucio-client 1.23.0

### PR DESCRIPTION
**Pull request by amaltaro**
Update the rucio-clients version from 1.22.2 to 1.23.0;
then also update WMAgent spec to 1.3.6.patch3

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
-1 to 00759ba9697018602c9ac18203dc6973fbe8906c on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6075/test_00759ba-20200715-004003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
rucio-clients 1.23.0 brings a new whole load of dependencies. So I'm trying to build this agent with 1.22.8 instead.

**Comment by muhammadimranfarooqi** [comment]
-1 to c213dfa24cafebc731cadc024ec6bb25f6978142 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6075/test_c213dfa-20200715-092504.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to e2d7ef24e6ab149d6eea44c6d66c17cb94e53957 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6075/test_e2d7ef2-20200715-134916.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
merge

**Pull request merged**
