### PR TITLE
Update root 6-14 with commits from master

### LINKED ISSUE #5127: pyROOT enum fixes: update rootmaster to pickup merge of root-project/root#4121 ... and root-project/root#4202
Please update to the recent rootmaster  to check that the feature/fix needed in the context of cms-sw/cmssw#26446  actually works OK for us.

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: https://github.com/cms-sw/cmsdist/issues/5127
(hopefully)

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@slava77 after looking into 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c2c11c/1796/lcg/root/6.14.09-cms/log
and checking how many changes went for pyROOT looking here:
https://github.com/root-project/root/commits?author=etejedor
I'm not sure it can be straightforward. I'll try to stitch it because it fails before the end but In case it takes too long I'll ask ROOT officially for backport (which I can't say how long it takes)

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
I noted our goal in https://sft.its.cern.ch/jira/browse/ROOT-8935
For now I just wanted to have a CMSSW IB with the existing fix in rootmaster to confirm that everything is working at least there out of the box.

**Comment by mrodozov** [comment]
that would be https://github.com/cms-sw/cmsdist/pull/5129 
there was no other way to test it straightforward with
https://github.com/cms-sw/cmssw/pull/26446
Anyway, this one builds, so if it goes fine one you can use it to test with the cmssw pr OR wait the other one to go in the ROOT master IB, and test with it. 
To test with this one would be sooner (at least can serve this purpose :/ )

**Comment by slava77** [comment]
> there was no other way to test it straightforward with cms-sw/cmssw#26446

I'm actually somewhat inappropriately using cms-sw/cmssw#26446 as an issue tracker. If the root solution is in place, then the cms-sw/cmssw#26446 PR is not needed.

**Comment by mrodozov** [comment]
@slava77 closing this, the results are available on the cmssw pr

**Pull request closed without merging**
