### PR TITLE
[AArch64] build cmssw aarch64 with -mno-outline-atomics file

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/36788

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true
- enable_test = threading
- workflow_threading = 4.44,13.0,11634.24,140.56

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by fwyzard** [comment]
Building with `-mno-outline-atomics` will require hardware support for the LSE instructions from the ARMv8.1 ISA.
If our build machines support only the ARMv8.0 ISA, the build is expected to fail at run time :-/

**Comment by dan131riley** [comment]
> Building with `-mno-outline-atomics` will require hardware support for the LSE instructions from the ARMv8.1 ISA.

I thought the point of the outline atomics was to enable use of LSE at runtime, so I expected `-mno-outline-atomics` to revert to the pre-10.1 behavior that didn't use LSE instructions.

> If our build machines support only the ARMv8.0 ISA, the build is expected to fail at run time :-/

Our build machines (at least the ones I'm aware of) have been upgraded to ThunderX2 that support the ARMv8.1 ISA, and since gcc 10.1 have been using the LSE instruction set at runtime.  I was wondering if the use of LSE was causing the mysterious failures we've been seeing, so I was hoping that flag would disable LSE.

**Comment by dan131riley** [comment]
> /bin/sh: line 1: 2956474 Illegal instruction     (core dumped) /usr/bin/touch /data/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-01-23-2300/tmp/slc7_aarch64_gcc11/cache/edm_edmPluginRefresh

This is really weird--/usr/bin/touch crashed?  I have no idea how adding that flag could cause that to crash.

**Comment by fwyzard** [comment]
> Our build machines (at least the ones I'm aware of) have been upgraded to ThunderX2 that support the ARMv8.1 ISA

Ah, OK.
Do we have interactive access to any of those nodes ?

**Comment by smuzaffar** [comment]
@fwyzard , you can login to those node. I am going to send you the instructions via email

**Comment by fwyzard** [comment]
> > Building with `-mno-outline-atomics` will require hardware support for the LSE instructions from the ARMv8.1 ISA.
> 
> I thought the point of the outline atomics was to enable use of LSE at runtime, so I expected `-mno-outline-atomics` to revert to the pre-10.1 behavior that didn't use LSE instructions.

OK, I guess I misread the GCC's documentation:

> `-moutline-atomics`
> `-mno-outline-atomics`
>
>    Enable or disable calls to out-of-line helpers to implement atomic operations. These helpers will, at runtime, determine if the LSE instructions from ARMv8.1-A can be used; if not, they will use the load/store-exclusive instructions that are present in the base ARMv8.0 ISA.
>
>    This option is only applicable when compiling for the base ARMv8.0 instruction set. If using a later revision, e.g. `-march=armv8.1-a` or `-march=armv8-a+lse`, the ARMv8.1-Atomics instructions will be used directly. The same applies when using `-mcpu=` when the selected cpu supports the `lse` feature. This option is on by default.

So
  - with `-march=armv8.1-a` or later, `-moutline-atomics`/`-mno-outline-atomics` has no effect, and LSE are always used
  - with `-march=armv8-a`, `-moutline-atomics` uses helpers to check if LSE are available and use them, or fall back to the old instructions otherwise
  - with `-march=armv8-a`, `-mno-outline-atomics` always uses the  old instructions
  
?

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

lets re-run the tests

**Comment by dan131riley** [comment]
> * with `-march=armv8.1-a` or later, `-moutline-atomics`/`-mno-outline-atomics` has no effect, and LSE are always used
> * with `-march=armv8-a`, `-moutline-atomics` uses helpers to check if LSE are available and use them, or fall back to the old instructions otherwise
> * with `-march=armv8-a`, `-mno-outline-atomics` always uses the  old instructions

I think that's correct.  We aren't specifying `-march` or `-mcpu` so I'd expect it to use the base ARMv8 instructions with `-mno-outline-atomics` (in fact, I got started on this line of investigation due to a handful crashes in the outline LSE routines).

**Comment by smuzaffar** [comment]
correct, we are not setting `-mcpu/arch` for aarch64. We have two arm64 nodes 
- thunderx2: olarm-202
- thunderx: olarm-102

but we are currently using olarm-202 only. Let me build all externals and cmssw with `-mcpu=armv8-a` on  olarm-202 and see if that helps.

**Comment by dan131riley** [comment]
> Refitted track not found in list
> ----- End Fatal Exception -------------------------------------------------

Well, that kills that theory.  Not only does the error reproduce with LSE disabled, but it also shows that the error reproduces in a single-threaded test (which I had not noticed before), which rules out synchronization primitives.

**Comment by smuzaffar** [comment]
@dan131riley , yes looks like outline-atomics is not the issue. I have built gcc with outline atomics disabled ( https://github.com/cms-sw/cmsdist/pull/7593 ) and still the same error ( https://github.com/cms-sw/cmsdist/pull/7593#issuecomment-1025225126 )

**Pull request closed without merging**
