### PR TITLE
[11.2 ROOT master] Get latest commits 

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
root changed something dd4hep is failing :/

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test
somethings went wrong I guess

**Comment by mrodozov** [comment]
Is this boost or should I try fix it ?

**Comment by smuzaffar** [comment]
looks like we might be missing some header file. please check cmssw code and see if we are missing any boost header in our code

**Comment by smuzaffar** [comment]
@mrodozov , hopefully https://github.com/cms-sw/cmssw/pull/30293 shoudl fix the issue. I think error is due to missing `vector` include

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
