### PR TITLE
[ROOT626] Updated root to tip of branch v6-26-00-patches

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
test parameters:

- full_cmssw = true

**Comment by aandvalenzuela** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by aandvalenzuela** [comment]
- `TestIOPoolInputNoParentDictionary` is expected due to version update.
- `DMRall` is also failing in IBs but for `ROOT6`, I am looking into it.
- `TestGeneratorInterfaceEvtGenInterface_external_bplus` timed out.
- `testSSTGainPCL_fromCalibTree` failing because of `Cannot find tree with name gainCalibrationTreeStdBunch/tree in file root://cms-xrd-global.cern.ch//store/group/dpg_tracker_strip/comm_tracker/Strip/Calibration/calibrationtree/GR18/calibTree_325310.root`. Looking into it also, in the mean I will retry the tests for this one since it was not failing in the previous iteration.

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
Test `testSSTGainPCL_fromCalibTree` is not explicitly failing in IBs, but the root file required for the test is also not reachable. See https://github.com/cms-sw/cmssw/issues/40097.

**Pull request closed without merging**
