### PR TITLE
Update ROCm targets

### PR DESCRIPTION
**Pull request by fwyzard**
Build HIP/ROCm code in CMSSW for:
  - Radeon Pro WX 8200/9100 (gfx900)
  - Radeon Pro W7800/W7900 (gfx1100)
  - Radeon Pro W7600 (gfx1102)
  - Instinct MI210/MI250 (gfx90a)

### CODE REVIEW

**Comment by fwyzard** [comment]
test parameters:
  - full_cmssw = true
  - enable_test = gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Looks good to me.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
