### PR TITLE
[10_6_X] Update tag for Configuration-Generator to V01-10-00

### PR DESCRIPTION
**Pull request by tvami**
Backport of https://github.com/cms-sw/cmsdist/pull/9528

### CODE REVIEW

**Comment by tvami** [comment]
Backport of https://github.com/cms-sw/cmsdist/pull/9528

**Comment by tvami** [comment]
@smuzaffar please approve this, it's just the label change backport

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
+externals

this only container new data files  (https://github.com/cms-data/Configuration-Generator/pull/17/files)

**Comment by smuzaffar** [comment]
merging it for 10.6.X

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
