### PR TITLE
WMAgent release candidate 1.4.0

### PR DESCRIPTION
**Pull request by amaltaro**
This is meant to be merged only once rucio-clients has been updated to `1.23.6`, see:
https://github.com/cms-sw/cmsdist/pull/6240

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
to c11314e98b3a3660378c95f84d8d26a8255b84b2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6241/test_c11314e-20200915-151003.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi can you trigger these tests again please?

**Comment by muhammadimranfarooqi** [comment]
+1 to c11314e98b3a3660378c95f84d8d26a8255b84b2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/6241/test_c11314e-20200916-085502.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
please merge

**Pull request merged**
