### PR TITLE
drop data-* and py2-* files and auto generate them

### PR DESCRIPTION
**Pull request by smuzaffar**
- Drop all py2-* packages and auto generate them when needed
  - new py2 packages should be added in cmsdist/pip/requirements.txt file
- Drop all cmssw data-* packages and auto generate them when needed
  - new data packages should be added in cmsdist/data/data-build-github-new.txt
  - Any updade to data packages should be done via data/data-build-github-new.txt along with any cleanup
- This needs pkgtools V00-32-XX ( https://github.com/cms-sw/pkgtools/commit/ea055de0aab670de91a6dad5c1eb6ca4b2542882 )

This PR should not re-build any package as generated specs should have the same contents as the existing .spec files.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
PR tests confirms that this does not re-build any package
```
12:01:49 Checking if cms-git-tools is cached.
12:01:49 cms-git-tools is available from remote repository "cms.week1". Not building. Downloading and installing...

12:01:52 Package cms+cms-git-tools+181115.0 found in repository
12:01:52 Starting to process package cms+cmssw-tool-conf+45.0-ikaegh4
12:01:52 Checking if cmssw-tool-conf is cached.
12:01:52 cmssw-tool-conf is available from remote repository "cms.week1". Not building. Downloading and installing...
```

**Comment by davidlange6** [comment]
Cool!



On 20 Nov 2018, at 12:04, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


PR tests confirms that this does not re-build any package

12:01:49 Checking if cms-git-tools is cached.
12:01:49 cms-git-tools is available from remote repository "cms.week1". Not building. Downloading and installing...

12:01:52 Package cms+cms-git-tools+181115.0 found in repository
12:01:52 Starting to process package cms+cmssw-tool-conf+45.0-ikaegh4
12:01:52 Checking if cmssw-tool-conf is cached.
12:01:52 cmssw-tool-conf is available from remote repository "cms.week1". Not building. Downloading and installing...

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
