### PR TITLE
Update OpenMPI to version 2.1.5 (critical bugfix release)

### PR DESCRIPTION
**Pull request by fwyzard**
Open MPI v2.1.5 is a critical bug fix release, and is likely the last release in the v2.1.x series.
Open MPI v2.1.5 is only recommended for those who are still running Open MPI v2.0.x or v2.1.x.

In addition, enable support for multithreading in OpenMPI.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
I guess something went awry with the tests ?

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
Note that the tests for the 10.2.x backport (https://github.com/cms-sw/cmsdist/pull/4261) did succeed.

**Comment by kpedro88** [comment]
@smuzaffar, @gudrutis, @mrodozov is this okay to be merged? The backport is requested for the next 10_2_X release

**Comment by smuzaffar** [comment]
+externals

**Comment by kpedro88** [comment]
+1

**Pull request merged**
