### PR TITLE
Bump rucio-clients to 1.22.2; update production urls

### PR DESCRIPTION
**Pull request by amaltaro**
Bump rucio client to the latest version: 1.22.2
and update the host_url and auth_url to the upcoming production instances, as a reference to: https://github.com/cms-sw/cmsdist/issues/5752

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
to cc173e3171b8286e6cea26d1cfdb9bee4c12f901 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5753/test_cc173e3-20200417-072004.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi I cannot find any failure in the log (or the log is incomplete).
Can you please check and/or retrigger the bot build? Thanks

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

There are errors of some dependencies. I can see the errors. I am triggering again.

**Comment by muhammadimranfarooqi** [comment]
+1 to cc173e3171b8286e6cea26d1cfdb9bee4c12f901 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5753/test_cc173e3-20200417-105004.log" target="_blank">here</a>.

**Comment by amaltaro** [comment]
@muhammadimranfarooqi I guess it was a transient failure. Can you please merge this PR? I'll then use it in the upcoming WMAgent release.

**Pull request merged**
