### PR TITLE
[G4] Update geant4 to 11.1.ref09

### PR DESCRIPTION
**Pull request by iarspider**
Closes https://github.com/cms-externals/geant4/issues/75

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_13_3_GEANT4_X/el8_amd64_gcc11

gcc version was moved to 12, but no IBs for that gcc version are available yet

**Comment by smuzaffar** [comment]
lets wait for gcc12 geant4 IBs

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/43004

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/43004

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#43004 for CMSSW_13_3_GEANT4_X

**Comment by smuzaffar** [comment]
@civanch , we are kind of stuck with this G4 update. There is a build error [a] which if we fix for G4 11.1.ref09 then it will break production IBs. Only way forward is to create a dedicated g4 branch of cmssw and update `SimG4Core/Application/src/ExceptionHandler.cc` in that branch

[a]
```
  SimG4Core/Application/src/ExceptionHandler.cc:72:10: error: enumeration value 'IgnoreTheIssue' not handled in switch [-Werror=switch]
    72 |   switch (localSeverity) {
```

**Comment by iarspider** [comment]
@smuzaffar we can put the extra `case` inside `#if - #endif` block - I think there should be some macro containing G4 version. I am looking into it.

**Comment by smuzaffar** [comment]
there is G4 version macro but it is set to 1112 for both geant4 versions

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#43048 for CMSSW_13_3_GEANT4_X

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/43048 helped, once it is merged then we can update geant4 11.1 ref09 for geant4 IBs

**Comment by smuzaffar** [comment]
+externals

https://github.com/cms-sw/cmssw/pull/43048  is merge so this can go in for GEANT4 too

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

looks good to go in GEANT4 IBs ( all tests passed)

**Comment by iarspider** [comment]
@smuzaffar thanks!

**Pull request merged**
