### PR TITLE
Revert "Revert "Update to Rivet 3.1.2 and Yoda 1.8.3""

### PR DESCRIPTION
**Pull request by mseidel42**
Reverts #6103

Multi-stream problems fixed in https://github.com/cms-sw/cmssw/pull/30888

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mseidel42** [comment]
Ah, we need to revert this one again: https://github.com/cms-sw/cmssw/pull/30838

**Comment by mseidel42** [comment]
Needs https://github.com/cms-sw/cmssw/pull/31355

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#31355
right ?

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#31355
to get the new build rules

**Comment by qliphy** [comment]
+operations

**Comment by qliphy** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
