### PR TITLE
[ROOT] Update root master

### PR DESCRIPTION
**Pull request by mrodozov**
please test

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
well something is wrong with ROOT I have to see what :/

**Comment by smuzaffar** [comment]
see this https://sft.its.cern.ch/jira/browse/ROOT-10758 .
pyRoot fails to load some shared libraries.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
