### PR TITLE
Updated boost to 1.78

### PR DESCRIPTION
**Pull request by davidlange6**
(at least to see what unit tests fail)

### CODE REVIEW

**Comment by davidlange6** [comment]
test parameters:
 - full_cmssw = true
 - pull_requests = cms-sw/cmssw#36701

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for cs8_amd64_gcc10

**Comment by smuzaffar** [comment]
@ggovi @davidlange6 , boost 1.78 looks good to go in, any objections on including it in 12.3.X?

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc11

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc11

**Comment by smuzaffar** [comment]
@ggovi @davidlange6 , any objections on integrating boost 1.78 in 12.3.X release cycle?

**Comment by smuzaffar** [comment]
please test
lets refresh the tests

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by francescobrivio** [comment]
Hi @davidlange6 and @smuzaffar!
Just out of curiosity (and to better organize things in AlCa), is there already a timeline / planned release to make this updated boost version the default in CMSSW?

**Comment by smuzaffar** [comment]
@davidlange6 , was there any thing in boost 1.78 which you think is needed for cxxmodules IBs?
@francescobrivio , no there is no timeline or planned release for this to go in. Basic PR tests are passed. If you need an env to test it then we can include this in DEVEL IBs to have full scale Ib tests.

**Comment by davidlange6** [comment]
Not needed no, useful, yes -  I'd rather not wait another year to update boost. Being not yet in data taking, it seemed the right time.

**Comment by smuzaffar** [comment]
OK, lets get this it DEVEL IB so that db/alca can run tests if needed

**Comment by smuzaffar** [comment]
+externals
unit tests failure is due to data package update which was not included in this test
merging this for 12.3.DEVEL.X IBs to run full scale tests

**Comment by francescobrivio** [comment]
@smuzaffar we don't have specific tests, just a couple of scripts (outside CMSSW, such as the condition uploader) that just need to be made aware of this change.

**Comment by smuzaffar** [comment]
@cms-sw/alca-l2  @cms-sw/db-l2  this has been integrated in DEVEL IBs now. All tests look good. The serialization part of boost contains only build system releated changed e.g. https://github.com/boostorg/serialization/compare/boost-1.75.0...boost-1.78.0 .

**Comment by tvami** [comment]
We finished with our tests, AlCaDB is OK with integrating this in the main CMSSW release too, @cms-sw/orp-l2 @smuzaffar

**Pull request merged**
