### PR TITLE
Update mkfit to V3.2.0-0

### PR DESCRIPTION
**Pull request by mmasciov**
Related CMSSW and cms-data PR are coming.

https://github.com/trackreco/mkFit/releases/tag/V3.2.0-0%2Bpr354

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test with https://github.com/cms-sw/cmssw/pull/35199, https://github.com/cms-data/RecoTracker-MkFit/pull/4

**Comment by smuzaffar** [comment]
@cmsbuild, please test with cms-sw/cmssw#35199, cms-data/RecoTracker-MkFit#4

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
