### PR TITLE
[ONNX runtime] Update for powerpc

### PR DESCRIPTION
**Pull request by mrodozov**
please test
patch is taken from here https://github.com/onnx/onnx/pull/2482

### CODE REVIEW

**Comment by smuzaffar** [comment]
@mrodozov , I think we need cmssw PR too to go with protobuf.

**Comment by mrodozov** [comment]
please test
I'll fix the cmssw part, but lets see the external built
protobuf builds with cmake now. the installation is the same except it has a cmake config in /lib

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
test parameters:
- full_cmssw = true
- pull_requests = https://github.com/cms-sw/cmssw/pull/29486, https://github.com/cms-sw/cmssw/pull/29510

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov what about the other changes by @hqucms [a] ? Why have you dropped those? @hqucms can you please confirm if these [a] are still valid for v1.2.0?

[a]
https://github.com/cms-externals/onnxruntime/commit/12f9ce57d0b9cb82611284a435020de9b39e1107
https://github.com/cms-externals/onnxruntime/commit/3dbce7cb7ee10301f55b8a1ba2e414c6cb5ee1eb

**Comment by mrodozov** [comment]
https://github.com/cms-externals/onnxruntime/commit/12f9ce57d0b9cb82611284a435020de9b39e1107
are not needed anymore, they are in the code. 
I'm adding 
https://github.com/cms-externals/onnxruntime/commit/3dbce7cb7ee10301f55b8a1ba2e414c6cb5ee1eb
which I missed

**Comment by hqucms** [comment]
I think we want to add `MLAS_DYNAMIC_CPU_ARCH` like in https://github.com/cms-externals/onnxruntime/commit/3dbce7cb7ee10301f55b8a1ba2e414c6cb5ee1eb. This will allow us to control whether to use AVX or more advanced instructions. Without it we may get non-reproducibility at PR validation time.

The changes on LSTM thread pool (https://github.com/cms-externals/onnxruntime/commit/3dbce7cb7ee10301f55b8a1ba2e414c6cb5ee1eb) is no longer needed as the thread pool usage is already fixed upstream in ONNXRuntime.

**Comment by mrodozov** [comment]
@hqucms what about this https://github.com/cms-externals/onnxruntime/commit/12f9ce57d0b9cb82611284a435020de9b39e1107#diff-c4fcbbc1a16e3957fa378471afc8d2c2R1122
do we still need one thread only (while I'm on it)
ok I see your comment there ill get the orig piece

**Comment by hqucms** [comment]
> @hqucms what about this [cms-externals/onnxruntime@12f9ce5#diff-c4fcbbc1a16e3957fa378471afc8d2c2R1122](https://github.com/cms-externals/onnxruntime/commit/12f9ce57d0b9cb82611284a435020de9b39e1107#diff-c4fcbbc1a16e3957fa378471afc8d2c2R1122)
> do we still need one thread only (while I'm on it)

@mrodozov I think we don't need it.

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test for slc7_ppc64le_gcc820
lets test it for PowerPC

**Comment by mrodozov** [comment]
it needs also a cmssw PR for the new file

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc820

**Comment by mrodozov** [comment]
```
/scratch/cmsbuild/jenkins_a/workspace/ib-run-pr-tests/CMSSW_11_1_X_2020-04-17-2300/src/PhysicsTools/ONNXRuntime/interface/ONNXRuntime.h:19:10: fatal error: 'onnxruntime/core/session/onnxruntime_cxx_api.h' file not found
15:08:27 #include "onnxruntime/core/session/onnxruntime_cxx_api.h"
```
I think we have to enable the onnxruntime toolfile for ppc first

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc820

**Comment by slava77** [comment]
it looks like this part of the log leads to the rest
```
unable to load lib/slc7_aarch64_gcc820/pluginGeneratorInterfaceRivetInterface_plugins.so because /home/cmsbld/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/slc7_aarch64_gcc820/external/gcc/8.3.0/lib64/libgomp.so.1: cannot allocate memory in static TLS block
 will ignore pluginGeneratorInterfaceRivetInterface_plugins.so and continue.

```

why did it not make this a failed build though?

**Comment by mrodozov** [comment]
I think we found a way on arm to trick it let me see

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc820

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
this stuck on building tensorflow since yesterday. onnxruntime however, built :) lets retry

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc820

**Comment by mrodozov** [comment]
Latest commit fixes this:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_ppc64le_gcc820/CMSSW_11_1_X_2020-04-21-2300/DataFormats/HGCalReco
the test would've failed, better fix it before that. 
I built the DataFormats/HGCalReco before pushing it. It builds
the other compile errors are onnxruntime related

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc820

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc820

**Comment by smuzaffar** [comment]
test parameters:
 - full_cmssw = true
 - pull_requests = cms-sw/cmssw#29486

**Comment by smuzaffar** [comment]
please test
lets test it for amd64 (produciton arch) . Results of aarch64 and ppc64le looks reasonable and the unit test failures are not due to onnxruntime update

**Comment by smuzaffar** [comment]
+externals
@silviodonato , this is ready to go in. onnxruntime now builds for ppc64le too and tests results looks promissing.

**Comment by smuzaffar** [comment]
hold
we need to fix compilation warnings in cmssw due to new protobuf ( https://github.com/cms-sw/cmssw/pull/29486#issuecomment-618873757 )

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
unhold

**Comment by silviodonato** [comment]
+1

**Pull request merged**
