### PR TITLE
[BuildRules] Enable alpaka ROCm backend

### PR DESCRIPTION
**Pull request by fwyzard**
Same as #8301 with a clean commit history.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
urgent

backport needed for 13.0.0

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = FWCore,HeterogeneousCore, DataFormats/Portable, HeterogeneousTest, DataFormats/PortableTestObjects

**Comment by smuzaffar** [comment]
please test

lets make sure that we rebuild packages with rocm dict

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
Thanks, I _really_ needed this to break the IBs even more.

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
please test
(Now it should work...)

**Comment by fwyzard** [comment]
well, now it's broken in its own rights :-)

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
@smuzaffar thanks for the update, `V07-07-03` worked locally for me

**Comment by fwyzard** [comment]
`---> test testFWCoreUtilities had ERRORS` (for `el8_ppc64le_gcc11`) should be unrelated to these changes.
In fact, it's already present in [the latest IB](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_1_X_2023-03-01-2300/unitTestLogs/FWCore/Utilities#/62-74).

**Comment by smuzaffar** [comment]
+externals

**Comment by fwyzard** [comment]
> `---> test testFWCoreUtilities had ERRORS` (for `el8_ppc64le_gcc11`) should be unrelated to these changes. In fact, it's already present in [the latest IB](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_1_X_2023-03-01-2300/unitTestLogs/FWCore/Utilities#/62-74).

Traced to a bug in TBB, see https://github.com/cms-sw/cmssw/issues/34647#issuecomment-1453137952 .

**Pull request merged**
