### PR TITLE
enable python extension for fastjet

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov , can you please check how to enable python interface or fastjet?

**Comment by mrodozov** [comment]
@rappoccio , we were trying to enable python support for fastjet when the following broke the build:
```
make[2]: Entering directory `/build/mrodozov/build_fastjet/BUILD/slc6_amd64_gcc630/external/fastjet/3.3.0-cms/fastjet-3.3.0/pyinterface'
/bin/sh ../libtool  --tag=CXX --silent  --mode=compile g++ -DHAVE_CONFIG_H -I. -I../include/fastjet  -I/build/mrodozov/build_fastjet/slc6_amd64_gcc630/external/python/2.7.11-fjcbno/include/python2.7 -I/build/mrodozov/build_fastjet/slc6_amd64_gcc630/external/python/2.7.11-fjcbno/include/python2.7 -g  -Woverloaded-virtual  -DDROP_CGAL   -I../include -I../include -I../tools -DSWIG  -g  -Woverloaded-virtual  -DDROP_CGAL  -O3 -Wall -ffast-math -ftree-vectorize -msse3 -MT _fastjet_la-swig_wrap.lo -MD -MP -MF .deps/_fastjet_la-swig_wrap.Tpo -c -o _fastjet_la-swig_wrap.lo `test -f 'swig_wrap.cpp' || echo './'`swig_wrap.cpp
swig_wrap.cpp: In function 'std::__cxx11::string fastjet_Error___str__(const fastjet::Error*)':
swig_wrap.cpp:5244:87: error: 'const class fastjet::Error' has no member named 'description'
SWIGINTERN std::string fastjet_Error___str__(fastjet::Error const *self){return self->description();}
^~~~~~~~~~~
swig_wrap.cpp: In function 'PyObject* _wrap_Error_description(PyObject*, PyObject*)':
swig_wrap.cpp:9470:48: error: 'const class fastjet::Error' has no member named 'description'
result = ((fastjet::Error const *)arg1)->description();
```
where the file fastjet/3.3.0-cms/fastjet-3.3.0/pyinterface/swig_wrap.cpp complained that there is no method description in the fastjet::Error class. So I went to check the class definition and I noticed that 
https://github.com/cms-externals/fastjet/commit/156108f360da28d06005671f845a38117908fe8c#diff-a15fd2fb4d8b1a8d12b7666facb52109L66
the method has been removed. I noticed you've removed entirely the declaration of the description method - have you done that by accident (so we could bring the declaration back) or the method is removed on purpose ?
Thanks & cheers,
M.

**Comment by rappoccio** [comment]
I think this must have been removed by a previous patch (I apply all of them) for thread safety. If this is safe from a thread standpoint (I think it looks to be so to me) then we can safely bring it back in.

**Comment by rappoccio** [comment]
Is this somehow looking for python 2.6 instead of 2.7?

**Comment by davidlange6** [comment]
it found the system python not our python - it looks like a dependency on python is missing from fastjet.spec

**Comment by mrodozov** [comment]
Yes the dep was missing I've added it in #3867 as I can't put commits on top of this PR. I'm closing this one

**Pull request closed without merging**
