### PR TITLE
Update Pythia8 to 230 in CMSSW_7_1_X

### PR DESCRIPTION
**Pull request by silviodonato**
This should be the minimal change to update Pythia8 to 230 in CMSSW_7_1_X

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by qliphy** [comment]
assign @cms-sw/generators-l2   @cms-sw/pdmv-l2

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@mkirsano @cms-sw/generators-l2  We are building a special 7_1_X release with Pythia8.230, under the requirement from pdmv.  
Would you please have a look at the above compilation error message?  Thanks.

**Comment by mkirsano** [comment]
What I see for the moment is that the author's version compiles, the one from cms git - not.

**Comment by SiewYan** [comment]
Hi, I did some digging as well, it looks like the defined type shared_ptr is not defined in cmsexternal's version of pythia8.

`include/Pythia8Plugins/LHAPDF6.h:26:5: error: 'shared_ptr' in namespace 'std' does not name a type
`
The author version defines shared_ptr in SharedPointers.h [1]


[1] http://home.thep.lu.se/~torbjorn/doxygen83/SharedPointers_8h_source.html

**Comment by mkirsano** [comment]
I remember now that story. The compiler in 7_1_X is too old (gcc 4.8). For this reason the upgrade to pythia8 230, patched against memory leak in lhapdf interface, was not backported to 7_1_X. The patch did not compile by 4.8.

**Comment by mkirsano** [comment]
Upgrade to a higher version of pythia8 could be a simplest solution.

**Comment by qliphy** [comment]
Thanks @mkirsano @SiewYan ,  so we can go for pythia8.303 directly , right?

**Comment by mkirsano** [comment]
If higher version is OK, I would suggest 240. pythia8 303 means many changes in the interface and many differences in physics

**Comment by agrohsje** [comment]
Thanks for the investigations. I will ping Alp to see if they are ok with 240.

**Comment by alpakpinar** [comment]
Hi @agrohsje , all, thanks a lot for the work. I think we should be okay with Pythia 8 240, I'll quickly check with the analysis team and I'll let you know soon.

Thanks,
Alp

**Comment by alpakpinar** [comment]
Hi @agrohsje , all, Pythia 8 240 would also work for us, thank you!

**Comment by smuzaffar** [comment]
closing, this is not needed any more.

**Pull request closed without merging**
