### PR TITLE
Get llvmlite from github and enable llvmlite,numba for gcc7

### PR DESCRIPTION
**Pull request by mrodozov**
Get llvmlite from source to enable llvmlite and numba for gcc7 IBs

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test
not sure if this is consistent, so let's just check it

**Comment by smuzaffar** [comment]
normal unit test failing due to numba and llvm5 conbination

**Pull request merged**
