### PR TITLE
Update GeneratorInterface-EvtGenInterface to V02-03-00

### PR DESCRIPTION
**Pull request by kfjack**
Update the tag for GeneratorInterface-EvtGenInterface to V02-03-00, in order to use the newly added decay and pdl files in the EvtGen generation.

This is a back port of PR #6807.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by kfjack** [comment]
Hi all please let me know if I should move the line "GeneratorInterface-EvtGenInterface=V02-03-00" from [data-build-github] to the [default] section according to the descriptions. Many thanks.

**Comment by qliphy** [comment]
> Hi all please let me know if I should move the line "GeneratorInterface-EvtGenInterface=V02-03-00" from [data-build-github] to the [default] section according to the descriptions. Many thanks.

It seems so to me.  You may also refer to https://github.com/cms-sw/cmsdist/pull/6654

**Comment by kfjack** [comment]
Many thanks @qliphy! Moved accordingly.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
