### PR TITLE
Update UTM to 0.7.5

### LINKED ISSUE #5555: pr 111X (110X) , UTM 0.7.5 in cms-externals
Dear @smuzaffar, 
(attn @boudoul)

New UTM for 11_1_X, and backport to 11_0_X
========================
This is a request to add a new version of the UTM library, tag utm_0.7.5, [1] needed for L1T to be included in CMSSW_11_1_X, and backport to 11_0_X.  This UTM library is intended to be used for MWGR#1.

Description:
=========
The patch fixes the bunch crossing offset issue concerning external signals and centrality signals (+/- offset was ignored). This bug was introduced in version 0.7.0.  The patch also contains fix of offending syntax. 

Run Coordination/Operations note:
==========================
This UTM library is intended to be used for tests in MWGR#1 if can make it in time. The UTM library is used for O2O (p5), and GlobalTrigger emulation, performed in HLT, OnlineDQM, OfflineDQM.  So deploying the new CMSSW with the updated UTM library requires operations coordination.

[1]
https://gitlab.cern.ch/cms-l1t-utm/utm/tree/utm_0.7.5

### PR DESCRIPTION
**Pull request by mrodozov**
please test
Resolves: https://github.com/cms-sw/cmsdist/issues/5555
hopefully builds out of the box
@rekovic

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals
@silviodonato feel free to merge it

**Comment by smuzaffar** [comment]
@silviodonato , this is needed by MWGR ( https://github.com/cms-sw/cmsdist/issues/5555 ) . It looks good. Can we get this in for next IB? so that we can backport it to 11.0.X

**Comment by silviodonato** [comment]
+1

**Comment by boudoul** [comment]
Dear @silviodonato and @smuzaffar , let's not rush on this for this MWGR (which is starting soon very soon) and discuss at the ORP , assuming @rekovic can make the presentation in the run meeting as I requested in the discussion here https://github.com/cms-sw/cmsdist/issues/5555

**Comment by rekovic** [comment]
Thanks for merging it.

Yes, as agreed in the meeting of @boudoul, we will not use it for MWGR#1.  It is not critical.  MWGR is used only as a full-system-in-operations test.
 
So, I would still like to backport it to whatever release we are going to use for the next MWGR#2, for which there should be plenty of time to prepare. i.e. switch CMSSW in operations (O2O, HLT, OnlineDQM, OfflineDQM).

**Comment by boudoul** [comment]
Dear @rekovic , @smuzaffar , could you please remind me the status of the backport ? Next MWGR is in ~3 weeks, and it would be good to have it for this MWGR . Thank you.

**Comment by smuzaffar** [comment]
@boudoul , this has been back ported and integrated in 11.0.x via #5557

**Comment by boudoul** [comment]
ah excellent, thanks @smuzaffar , I missed it .

**Pull request merged**
