### PR TITLE
Initial commit for the HLS headers

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
please test for slc7_aarch64_gcc700

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@mrodozov , please backport it for 10.6.X (as requested https://github.com/cms-sw/cmsdist/issues/5178 )

**Pull request merged**
