### PR TITLE
New das version: replace logrus with log and fix DBS instance issue on testbed

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
to 83c0230d9d2af91ba600f24107ae20715f7aa6a2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5971/test_83c0230-20200619-204503.log" target="_blank">here</a>.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , could you please clean-up das build area and restart the build. The error from log seems to come from multiple builds rather from the new version itself.

**Comment by vkuznet** [comment]
Here is a message:
```
start DASTools build: /build/dmwmbld/srv/state/dmwmbld/builds/5971/w/BUILD/slc7_amd64_gcc630/cms/das/04.06.17
+ git clone https://github.com/dmwm/DASTools.git
fatal: destination path 'DASTools' already exists and is not an empty directory.
```
So, I would suggest to remove the build area:
```
rm -r f /build/dmwmbld/srv/state/dmwmbld/builds/5971
```
and then restart the build.

**Comment by muhammadimranfarooqi** [comment]
to 83c0230d9d2af91ba600f24107ae20715f7aa6a2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5971/test_83c0230-20200619-231003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

After deleting area `rm -rf /build/dmwmbld/srv/state/dmwmbld/builds/5971` and triggering again got the same error again

**Comment by muhammadimranfarooqi** [comment]
-1 to 83c0230d9d2af91ba600f24107ae20715f7aa6a2 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5971/test_83c0230-20200619-234502.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
+1 to b43f1c4385c3af46172662754a1f7b2f3610f393 on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/5971/test_b43f1c4-20200620-003503.log" target="_blank">here</a>.

**Comment by yuyiguo** [comment]
@vkuznet 
What DBS instance issue did this PR fix?

**Comment by vkuznet** [comment]
Yuyi, it is internal to DAS maps which has prod/global instance while in testbed we need to have int/global. I fixed that DAS should read default from the supplied maps.

**Pull request merged**
