### PR TITLE
enable cxxmodules fwcore packages

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters
  - full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , @vgvassilev  this shoudl allow to build CXXMOdules for `FWCore/Reflection FWCore/Utilities`. I did not add `FWCore/Framework FWCore/ParameterSet` for now as there are build errors for those

**Comment by vgvassilev** [comment]
@smuzaffar, sounds good!

**Comment by davidlange6** [comment]
hi @smuzaffar - is there an easy way to reproduce the issues you saw with the other FWCore packages?

**Comment by smuzaffar** [comment]
Try creating dev area and 
- checkout the FW packages
- touch  FW/Package/src/classes.h and FW/Package/src/classes_def.xml
- enable CXXMODULES for these FW packages in config/SCRAM/GMAKE/CXXModules.mk file
- scram build

**Comment by davidlange6** [comment]
Easy! - thanks - @vv is having a look
(Of course we know we have local vs full build differences…)

On Jun 24, 2020, at 8:57 AM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



Try creating dev area and

  *   checkout the FW packages
  *   touch FW/Package/src/classes.h and FW/Package/src/classes_def.xml
  *   enable CXXMODULES for these FW packages in config/SCRAM/GMAKE/CXXModules.mk file
  *   scram build

**Comment by vgvassilev** [comment]
They work for me:
ls lib/slc7_amd64_gcc820/*pcm
lib/slc7_amd64_gcc820/FWCoreFramework.pcm     lib/slc7_amd64_gcc820/FWCoreReflection.pcm
lib/slc7_amd64_gcc820/FWCoreParameterSet.pcm  lib/slc7_amd64_gcc820/FWCoreUtilities.pcm

**Comment by smuzaffar** [comment]
looks good @vgvassilev . For me the full build failed due due to errors in FWCoreFramework and FWCoreParameterSet.
I will open a PR to enable these and run a full build test

**Pull request merged**
