### PR TITLE
Update libjpeg-turbo to 2.0.1

### PR DESCRIPTION
**Pull request by mrodozov**
Update to 2.0.1 as tf 1.12 now works with 2.0.x

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
