### PR TITLE
Update Sherpa 2.2.8 [11_0_X_master]

### PR DESCRIPTION
**Pull request by SiewYan**
1.) Bump up Sherpa to 2.2.8
2.) Interface with Rivet3
3.) Install lhc processes only for openloops

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test workflow 534.0,536.0

**Comment by smuzaffar** [comment]
@SiewYan thanks for the update, looks like this also fixed the issue of openloops for aarch64.
@fabiocos , once this is merged then #5232 should enable openloops agains for aarch64

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
