### PR TITLE
Update DD4Hep to latest on master

### PR DESCRIPTION
**Pull request by mrodozov**
Previous pr was merged to make an IB for debugging a unit test
Deps on tbb removed (not used)

### CODE REVIEW

**Comment by mrodozov** [comment]
@cvuosalo I started an IB CMSSW_11_3_X_2021-01-26-0100 that includes the changes from this PR 
once it's ready you'll need to get it with scram 
`scram p CMSSW_11_3_X_2021-01-26-0100`
and run the unit test and the relval failing

**Comment by mrodozov** [comment]
@cvuosalo @ianna 
using the CMSSW_11_3_X_2021-01-26-0100 IB will get the conditions in which the
`GeometryDTGeometryBuilderTestDriver` 
test is failing - it fails the same way as in the PR, and it includes the dd4hep from this PR

If you want to build the external and have it locally installed, so you can also patch it you can do:
```
git clone https://github.com/cms-sw/cms-bot
./cms-bot/test-prs.sh -a slc7_amd64_gcc900 cms-sw/cmsdist#6594 -r CMSSW_11_3_X_2021-01-26-1100
```
This takes few hours to build the external and all related to it changes in CMSSW

**Comment by cvuosalo** [comment]
@mrodozov @ianna With the special IB, I ran DD4hep tests. Once again, the `DDDefintion` error is appearing. I thought it had been fixed. Any ideas about it?
```
DD4hep           WARN  ++ Using globally Geant4 unit system (mm,ns,MeV)
PluginService    ERROR Factory requested: DDDefinition_XML_reader (N10__cxxabiv120__function_type_infoE) :bad any_cast
PluginService    ERROR Stub is invalid!
dd4hep: Failed to locate plugin to interprete files of type "DDDefinition" - no factory:DDDefinition_XML_reader. 		No factory with name Create(DDDefinition_XML_reader) for type DDDefinition_XML_reader found.
		Please check library load path and/or plugin factory name.
dd4hep: while parsing /cvmfs/cms-ib.cern.ch/nweek-02665/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-26-0100/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
dd4hep: with plugin:DD4hep_CompactLoader
```

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@cvuosalo I'm runing the tests to have the logs and search for the missing symbols mentioned yesterday.

**Comment by mrodozov** [comment]
@cvuosalo there is something mentioned here:
https://github.com/cms-sw/cmssw/issues/32181#issuecomment-763117890

**Comment by cvuosalo** [comment]
@mrodozov  Markus Frank suggests that the problem with `DDDefinition` may be caused by:
1. ROOT map file not being properly generated.
2. Load-library path is wrong.

Are either of these possible?

**Comment by cvuosalo** [comment]
The `DDDefinition` error can be reproduced by running "cmsRun Geometry/EcalCommonData/test/python/dumpECDD4Hep_cfg.py" in the special IB.

**Comment by mrodozov** [comment]
I'll see it later when I'm finished with other things to be done would you elaborate which Library-path (to cmssw generated lib, dd4hep lib path etc) and which ROOT map.
You can also type
env
to see all the environment vars which are holding the library paths

**Comment by cvuosalo** [comment]
@mrodozov I was just repeating suggestons from Markus. I don't have more to add about them.
I have noticed the `DDDefinition` error is also appearing in `CMSSW_11_3_ASAN_X_2021-01-27-2300`. I'm not sure what that tells us.

**Comment by smuzaffar** [comment]
closing in favor of #6612 6612

**Pull request closed without merging**
