### PR TITLE
Updated root to tip of branch master

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters
 - full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@vgvassilev , @davidlange6 , comparison jobs now crash and hang [a]. We start noticing this behaviour when we tried to update https://github.com/root-project/root/compare/0a6e147...dee0df8 

Any idea what could have caused this?

[a]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_ROOT6_X_2020-01-29-2300+d4fa1a/34895/alternative-comparisons/runDQMComp-4.22.log

**Comment by smuzaffar** [comment]
@vgvassilev , @davidlange6 did you manage to look in to this?

**Comment by vgvassilev** [comment]
@smuzaffar nothing seems suspicious to me.

Lets ping @linev and @bellenot who might have a clue.

**Comment by linev** [comment]
Sorry, I cannot access log file. 
Most my changes about batch-mode RCanvas - they are not used in cmssw.
Two other commits about memory leaks in TPad::Print(). 
If you see crashes during saving of TCanvas images - I want to get full debug output

**Comment by smuzaffar** [comment]
here is last part of log file
```
Save : /DQMData/Run 160960/DQM/Run summary/TimerService/source time_real_byls
Info in <TCanvas::Print>: Current canvas added to ps file diff.ps
Info in <TCanvas::Print>: Current canvas added to pdf file diff.pdf
Save : /DQMData/Run 160960/DQM/Run summary/TimerService/source time_thread_byls
Info in <TCanvas::Print>: Current canvas added to ps file diff.ps
Info in <TCanvas::Print>: Current canvas added to pdf file diff.pdf
Info in <TCanvas::Print>: ps file diff.ps has been closed
Info in <TCanvas::Print>: pdf file diff.pdf has been closed

 *** Break *** abort



===========================================================
There was a crash (kSigAbort).
This is the entire stack trace of all threads:
===========================================================
#0  0x00002aac51e6241c in waitpid () from /lib64/libc.so.6
#1  0x00002aac51ddff12 in do_system () from /lib64/libc.so.6
#2  0x00002aac51688832 in TUnixSystem::Exec (this=0x1d85570, shellcmd=0x5ca1050 "/cvmfs/cms-ib.cern.ch/nweek-02613/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/etc/gdb-backtrace.sh 14154 1>&2") at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:2108
#3  0x00002aac5168906a in TUnixSystem::StackTrace (this=0x1d85570) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:2398
#4  0x00002aac5168c95c in TUnixSystem::DispatchSignals (this=0x1d85570, sig=kSigAbort) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:3634
#5  0x00002aac51684ae6 in SigHandler (sig=kSigAbort) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:403
#6  0x00002aac5168c874 in sighandler (sig=6) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:3607
#7  0x00002aac5167de72 in textinput::TerminalConfigUnix::HandleSignal (this=0x2aac51861420 <textinput::TerminalConfigUnix::Get()::s>, signum=6) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/textinput/src/textinput/TerminalConfigUnix.cpp:100
#8  0x00002aac5167db8a in (anonymous namespace)::TerminalConfigUnix__handleSignal (signum=6) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/textinput/src/textinput/TerminalConfigUnix.cpp:36
#9  <signal handler called>
#10 0x00002aac51dd3337 in raise () from /lib64/libc.so.6
#11 0x00002aac51dd4a28 in abort () from /lib64/libc.so.6
#12 0x00002aac516888d8 in TUnixSystem::Abort (this=0x1d85570) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:2155
#13 0x00002aac51509258 in TApplication::ProcessLine (this=0x1ddbe90, line=0x7ffd5659e0d9 ".qqqqqq", sync=false, err=0x7ffd5659e06c) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/base/src/TApplication.cxx:1348
#14 0x00002aac51075df5 in TRint::ProcessLineNr (this=0x1ddbe90, filestem=0x2aac510858e7 "ROOT_prompt_", line=0x7ffd5659e0d9 ".qqqqqq", error=0x7ffd5659e06c) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/rint/src/TRint.cxx:763
#15 0x00002aac51075574 in TRint::HandleTermInput (this=0x1ddbe90) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/rint/src/TRint.cxx:609
#16 0x00002aac51073105 in TTermInputHandler::Notify (this=0x3c7d990) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/rint/src/TRint.cxx:131
#17 0x00002aac51077417 in TTermInputHandler::ReadNotify (this=0x3c7d990) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/rint/src/TRint.cxx:123
#18 0x00002aac51686d2a in TUnixSystem::CheckDescriptors (this=0x1d85570) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:1311
#19 0x00002aac51686155 in TUnixSystem::DispatchOneEvent (this=0x1d85570, pendingOnly=false) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:1066
#20 0x00002aac5157b9cd in TSystem::InnerLoop (this=0x1d85570) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/base/src/TSystem.cxx:413
#21 0x00002aac5157b77b in TSystem::Run (this=0x1d85570) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/base/src/TSystem.cxx:363
#22 0x00002aac5150a884 in TApplication::Run (this=0x1ddbe90, retrn=false) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/base/src/TApplication.cxx:1623
#23 0x00002aac5107492a in TRint::Run (this=0x1ddbe90, retrn=false) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/rint/src/TRint.cxx:462
#24 0x00000000004011f4 in main (argc=1, argv=0x7ffd565a0568) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/main/src/rmain.cxx:30
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#10 0x00002aac51dd3337 in raise () from /lib64/libc.so.6
#11 0x00002aac51dd4a28 in abort () from /lib64/libc.so.6
#12 0x00002aac516888d8 in TUnixSystem::Abort (this=0x1d85570) at /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc820/lcg/root/6.19.01-himbmo/root-6.19.01/core/unix/src/TUnixSystem.cxx:2155
===========================================================

```

**Comment by linev** [comment]
Seems to be, problem is handling of ".qqqqqq" at the exit of the ROOT.
It has nothing to do with changes in TPad::Print() - just try command `root -l -e '.qqqqqq'`
By the way - why '.qqqqqq' used to exit from the macro?

**Comment by vgvassilev** [comment]
The `.qqqqqq` sends different signal iirc. I do not understand why we get this test failure. Shahzad, could we narrow the commits?

**Comment by linev** [comment]
Long time ago `.qqqqqq` was cardinal way to abort ROOT application without doing any cleanup at the end. It was working that way until ROOT 6.18. Seems to be, changed in current master

**Comment by smuzaffar** [comment]
@mrodozov , can you please try building root master locally and run `root -l -e '.qqqqqq'` to see if you can re-produce this error? If you can then please try to narrow down the root commits and find out which one is causing this error.

**Comment by linev** [comment]
I found commit from Enric causing problem with .qqqqqq
https://github.com/root-project/root/commit/361a4600f8655854ce9f17a268909ac5fd75ef7d
Commit add `kSigAbort` handler and blocks `.qqqqqq`.
ROOT issue is created: https://sft.its.cern.ch/jira/browse/ROOT-10545

**Comment by smuzaffar** [comment]
thanks @linev

**Comment by vgvassilev** [comment]
Nice catch Sergey!!

**Comment by mrodozov** [comment]
`git branch --contains 361a4600`
shows that only master contains it, I tried removing only it's part so we can "trim it out" until its fixed but there are futher commits added on top of what https://github.com/root-project/root/commit/361a4600f8655854ce9f17a268909ac5fd75ef7d is touching, so it becomes ... tricky.

**Pull request closed without merging**
