### PR TITLE
Py3 Changes for frontier py client and py2-sqlalchemy

### PR DESCRIPTION
**Pull request by mrodozov**
Changes for frontier client and sqlalchemy frontier connector

### CODE REVIEW

**Comment by davidlange6** [comment]
@mrodozov - I don't believe the sqalc patch will work on python2 - you need to check the python version..

**Comment by davidlange6** [comment]
ah - but that patch explains my current error...

**Comment by mrodozov** [comment]
I'm fixing the version check part and then it will work

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
