### PR TITLE
bump crab client version in  crab-dev

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@belforte , https://github.com/dmwm/CRABClient/commit/033e254cc84bc610a0e1913f9bd4e30b272224f0 change required a corresponding change in `crab-build.file`. I have pushed the needed changes here.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by belforte** [comment]
> @belforte , https://github.com/dmwm/CRABClient/commit/033e254cc84bc610a0e1913f9bd4e30b272224f0 change required a corresponding change in crab-build.file. I have pushed the needed changes here.

Thanks @smuzaffar and sorry for having given you extra work. Should we do or have done something on our side to prevent this problem ? Adding @mapellidario who authored the change in `crab-bash-completion.sh`. Maybe there's at least some cautionary comment that we can add for whoever will change that file again in the future.

**Comment by smuzaffar** [comment]
@belforte , yes I think having a comment like [a] just before the `complete -F` command in `crab-bash-completion.sh` will help for future updates

[a]
```
######################################################
# Please make sure that 'complete` command below meet following rules
# - Starts with: complete\s+-F\s+<crab-function-name>\s+
# - Ends with: \s+crab
#  Otherwise suggest changes in crab-build.file in cms-sw/cmsdist repository
#####################################################
```

**Pull request merged**
