### PR TITLE
Update dqmgui.spec to dqmgui 9.7.4 release

### PR DESCRIPTION
**Pull request by pmandrik**
Remove checking of code from cmssw in old dqmgui package following discussion:
https://github.com/cms-DQM/dqmgui_prod/pull/3

Compiled successfully locally.

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@pmandrik 

This PR was not testbed by bot and I did not see anything in the bot logs for this PR. Can you commit any comment on this PR please. Actually you were not in authorized list of users. I have added you in the list now

**Comment by smuzaffar** [comment]
@muhammadimranfarooqi , so do you have to add every user who opens a PR in the authorized list?

**Comment by muhammadimranfarooqi** [comment]
+1 to f9d9f927cc79cc62ea083e4fccb44cd861352ffa on slc7_amd64_gcc630.<br>Build log can be found <a href="https://cern.ch/cms-dmwm-builds/7882/test_f9d9f92-20220523-103003.log" target="_blank">here</a>.

**Comment by muhammadimranfarooqi** [comment]
> @muhammadimranfarooqi , so do you have to add every user who opens a PR in the authorized list?

Yes, only authorized users'PR can be tested.

**Comment by smuzaffar** [comment]
that I know, but my question is that do you have to add every user who opens a PR in authorized list? If yes then what is the point of authorized list ? For users who are not in authorized list, one of the comp admins should sign the PR so that bot can start the tests

**Pull request merged**
