### PR TITLE
[10.6][OpenLoops] Update to version 2.1.2

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #7066 
FYI @SiewYan , this should be the correct backport. It allows us to cache the openloops process sources. Also the cmsdist production branch for `10.6.X` is `IB/CMSSW_10_6_X/gcc700`

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by SiewYan** [comment]
Thanks! @smuzaffar

**Comment by SiewYan** [comment]
assign generators

**Comment by GurpreetSinghChahal** [comment]
Thanks @smuzaffar and @SiewYan! 
@qliphy @perrotta if all tests are fine then we're happy to sign it asap. Would it be possible for you to wait for a couple of hours only so this PR could jump on the upcoming 10.6.x that you're building today? If we see any potential error today then you can ignore my suggestion and build 10.6.x without it.

**Comment by perrotta** [comment]
> Thanks @smuzaffar and @SiewYan!
> @qliphy @perrotta if all tests are fine then we're happy to sign it asap. Would it be possible for you to wait for a couple of hours only so this PR could jump on the upcoming 10.6.x that you're building today? If we see any potential error today then you can ignore my suggestion and build 10.6.x without it.

@GurpreetSinghChahal I also had to relaunch the tests for #34527, because I realized that the last ones were ran three weeks ago. Please proceed with the evaluation of the results of this one as soon as the results will get available, and sign it if you are happy with it. As such, this will also get included in the going to be built 10_6_release

@smuzaffar : would we merge this PR in 10_6, should we then make a full 10_6 release, instead of a pach one?

**Comment by smuzaffar** [comment]
@perrotta , patch releases by definition can not include any external changes, so you need to build a full release in order to include the external updates.

**Comment by smuzaffar** [comment]
+externals
I think test failure are due to power cut issues

**Comment by smuzaffar** [comment]
@qliphy , @perrotta , once @cms-sw/generators-l2 signs it then feel free to merge it

**Comment by GurpreetSinghChahal** [comment]
+generators

**Comment by perrotta** [comment]
merge

**Pull request merged**
