### PR TITLE
Update Configuration-Generator tag to 01-00-03 on 7_1

### PR DESCRIPTION
**Pull request by mrodozov**
Description is here: cms-data/Configuration-Generator#6
Backport of #4850

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by scodella** [comment]
Hi, is everything fine with the check?

**Comment by smuzaffar** [comment]
+externals
@scodella , every thing looks good. This tests only checked if we can build the externals. Is there any cmssw PR to tests these new data files ? Otherwise @fabiocos its good to go in.

**Comment by fabiocos** [comment]
@kpedro88 I think you should get it for next build you are planning

**Comment by kpedro88** [comment]
@fabiocos I already launched a patch build. I can abort it and launch a full build if this is ready to go.

**Comment by fabiocos** [comment]
@kpedro88 at this point it is worthwhile to have a full build including this backport I would say

**Comment by kpedro88** [comment]
The patch is already finished, I'll just do a full build tomorrow

**Comment by kpedro88** [comment]
backport of #4850

**Comment by kpedro88** [comment]
+1

**Comment by scodella** [comment]
May I ask what is the next step to have it in a production release to be used in McM requests? Will it be done automatically or do I need to take any action? Thanks.

**Comment by kpedro88** [comment]
@scodella I built CMSSW_7_1_39 over the weekend. It is available now. See: https://hypernews.cern.ch/HyperNews/CMS/get/relAnnounce/2029.html

**Pull request merged**
