### PR TITLE
Update CUDA to version 10.1.105, on x86_64

### PR DESCRIPTION
**Pull request by fwyzard**
Update CUDA to version 10.1.105, on x86_64
  * CUDA version 10.1.105
    Support for gcc 8 and clang 7.
    Include new Matrix Multiply library cublasLt.
    Various fxes to CUDA libraries and NVCC compiler.

  * NVIDIA drivers version 418.39

See https://docs.nvidia.com/cuda/archive/10.1/cuda-toolkit-release-notes/index.html .

### CODE REVIEW

**Comment by fwyzard** [comment]
This re-introduces CUDA 10.1 for the GCC 8 builds; this was in already, but was reverted together with the GCC 7 build.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
Sorry, for the typo, it now seems to be working fine locally.

**Comment by fwyzard** [comment]
The failure in `1325.7 step2` is hopefully completely unrelated to CUDA.
Is it a known issue ?  Or possibly a temporary failure ?

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@fwyzard , any reason to not get this in production releases (gcc 7) ?

**Comment by fwyzard** [comment]
Yes, see #4815

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
