### PR TITLE
[ROOT632] Updated root to tip of branch v6-32-00-patches

### PR DESCRIPTION
**Pull request by iarspider**
Changes: https://github.com/cms-sw/root/compare/648a3d81d4...5f257f1a1a
Version changed to 6.32.04

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
test parameters:
- full_cmssw = true

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
> Version changed to 6.32.04

@iarspider , please update the version in root.spec

**Comment by smuzaffar** [comment]
@iarspider , there are some recent change in root 6.32 patches branch, as you have to update the version string, please also get the latest root 6.32 changes

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
> @iarspider , there are some recent change in root 6.32 patches branch, as you have to update the version string, please also get the latest root 6.32 changes

my bad, forget this, I do not know which branch of root I was looking at

**Comment by iarspider** [comment]
> TestIOPoolInputNoParentDictionary 

Always fails when ROOT updates

> TestFWCoreReflectionClassVersionUpdate 

I guess this is expected?

**Comment by smuzaffar** [comment]
+externals

yes these failures are expected

**Pull request merged**
