### PR TITLE
[10.6] Include latest changes from 240 branch

### PR DESCRIPTION
**Pull request by mrodozov**
please test
the change was proposed and discussed here https://github.com/cms-externals/pythia8/pull/22

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@silviodonato , please feel free to merge it. This is follow up of https://github.com/cms-externals/pythia8/pull/22

**Comment by silviodonato** [comment]
bug-fix
(see https://github.com/cms-externals/pythia8/pull/22)

**Comment by silviodonato** [comment]
+1

**Comment by qliphy** [comment]
@silviodonato @smuzaffar @mrodozov   Thanks！ Can you make a new 10_6_X release to include this?

**Comment by smuzaffar** [comment]
@qliphy , there is a new request to patch pythia8 ( https://github.com/cms-externals/pythia8/pull/23 ) . Shouldn't we wait for that to be included before building the 10.6 release?

**Comment by qliphy** [comment]
@smuzaffar  Ok, let's wait for that.  Thanks.

**Pull request merged**
