### PR TITLE
removal of additional python2 tools

### PR DESCRIPTION
**Pull request by davidlange6**
daily dose of potential python2 removals

### CODE REVIEW

**Comment by davidlange6** [comment]
test parameters:
  - full_cmssw = true

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
whoops I didn't drop crypography yet - I will do it the next update..

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
